### PR TITLE
[4.0] Fixed lost request parameters on save

### PR DESCRIPTION
**Pull request by HRIT-Florian**
Pull Request for Issue #26657.

### Summary of Changes
On menu save, reloading form request values missing on error.
Screenshot, see issue #26657

### Testing Instructions
See issue #26657

### Expected result
See issue #26657

### Actual result
See issue #26657

### Documentation Changes Required
Nope

### CODE REVIEW

**Comment by Fallatas** [comment]
I have tested this item :white_check_mark: successfully on 08f65796a53322b140310744bb563a2e2a775cd3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26675">issues.joomla.org/tracker/joomla-cms/26675</a>.</sub>

**Comment by joomlamarco** [comment]
I have tested this item :white_check_mark: successfully on 08f65796a53322b140310744bb563a2e2a775cd3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26675">issues.joomla.org/tracker/joomla-cms/26675</a>.</sub>

**Comment by SharkyKZ** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26675">issues.joomla.org/tracker/joomla-cms/26675</a>.</sub>

**Comment by HLeithner** [comment]
If I checked the history correctly this code exists since 10+ years. Why does it fail now and does it impact any other component?

**Comment by SharkyKZ** [comment]
It fails in 3.x too. My guess the idea here is not to send `request` to the model because `request` doesn't exist in the table and is not stored by the model.

If you want, this can be refactored so `request` is still stored to user state but not sent to the model.

**Comment by HRIT-Florian** [comment]
@HLeithner it shouldn't effect, it's an old bug and these PR is also required for the already merged Save2Menu Feature #26681 ! If it couldn't be merged, we could also not go with the merged PR #26681

**Comment by HLeithner** [comment]
The shouldn't be any problem that this parameter get's to the model, JTable wouldn't save it if the field doesn't exists.

The only question is, are there any site effects for any component if this exists now? I don't think so but maybe I'm missing something.

**Comment by HRIT-Florian** [comment]
Yes, but we did fixed that, because it is definetly required for #26681 to pass the data from the article. Without that PR, #26681 will definetly not run. At the PBF we had tested it also with other components. Unfortunately I cannot answer myself whether it has an effect on any other components. But it couldn't be a huge problem.

**Comment by HLeithner** [comment]
Thanks.

**Comment by HRIT-Florian** [comment]
Thanks.

**Pull request merged**
