### PR TITLE
[4.0][com_tag] - class not found

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue 
`Class 'Joomla\Component\Tags\Site\Model\TagsHelperRoute' not found `

### Summary of Changes
added missed class 

### Testing Instructions
tag an article, view  on frontend the article and click on the tag

### Expected result
no error

### Actual result

Class 'Joomla\Component\Tags\Site\Model\TagsHelperRoute' not found

### CODE REVIEW

**Comment by adj9** [comment]
I have tested this item :white_check_mark: successfully on 92eaad02650b911030fabd31b9d096a776161af6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23990">issues.joomla.org/tracker/joomla-cms/23990</a>.</sub>

**Comment by faustonenci** [comment]
I have tested this item :white_check_mark: successfully on 92eaad02650b911030fabd31b9d096a776161af6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23990">issues.joomla.org/tracker/joomla-cms/23990</a>.</sub>

**Comment by robertolongo** [comment]
I have tested this item :white_check_mark: successfully on 92eaad02650b911030fabd31b9d096a776161af6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23990">issues.joomla.org/tracker/joomla-cms/23990</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23990">issues.joomla.org/tracker/joomla-cms/23990</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
