### PR TITLE
[4.1] Fix pagination in Task Scheduler

### PR DESCRIPTION
**Pull request by ditsuke**
Pull Request for Issue #36437.

### Summary of Changes

Pagination in the task manager was broken because we were filtering out orphaned tasks from an already paginated list. To solve this, we could either filter out orphans from a fully loaded task list or do the filtering within the query by passing all active routines queries through task plugins. I chose the latter approach, which should fix this issue.

### Testing Instructions
- Create > 5 tasks.
- Orphan some of the tasks so that non-orphaned tasks = 5.
- Set Task Manager pagination size to 5.
- Exclude orphaned tasks in the task manager (the default is not really applied)

### Actual result BEFORE applying this Pull Request

 We see < 5 tasks in the task manager.

### Expected result AFTER applying this Pull Request
We see 5 tasks in the task manager.

### Documentation Changes Required
\-

### CODE REVIEW

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 4fa2ace14387d688bf88cc08e0224db17a6d46a3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36438">issues.joomla.org/tracker/joomla-cms/36438</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 4fa2ace14387d688bf88cc08e0224db17a6d46a3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36438">issues.joomla.org/tracker/joomla-cms/36438</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36438">issues.joomla.org/tracker/joomla-cms/36438</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
