### PR TITLE
[3+] php8 deprecation str_replace Passing null to param

### PR DESCRIPTION
**Pull request by PhilETaylor**
Ensure that if there is no browserVersion then we do not run null through str_replace

Code review

Screenshot 2021-12-24 at 18 55 26

### CODE REVIEW

**Comment by wilsonge** [comment]
Is this a 'real world' problem? Or something limited to PHPUnit runs - where we should just mock things better. Asking because if there's no version presumably there's no user agent either and we're just md5'ing the base url of the site here and not getting a unique hash ever (unsure what the implications are of that without starting to deep dive)

I mean I'm sure this solves the immediate problem - just wondering if this has unmasked a rabbit hole

**Comment by PhilETaylor** [comment]
you should never be trying to push NULL through str_replace regardless of where its run :)

**Comment by PhilETaylor** [comment]
> just wondering if this has unmasked a rabbit hole

Welcome to the PHP 8.1+ party :)

**Comment by alikon** [comment]
got this deprecation notice as well on  J.4 too

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 728e5e07958957a162f5dfa3802c811b0a5a679c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36400">issues.joomla.org/tracker/joomla-cms/36400</a>.</sub>

**Comment by wilsonge** [comment]
> got this deprecation notice as well on J.4 too

Where? This is the string used for the name of all the cookies. If it's not unique it starts to get concerning.

**Comment by PhilETaylor** [comment]
I only noticed it on phpunit runs.

**Comment by PhilETaylor** [comment]
build now passing.

**Comment by Fedik** [comment]
I think the fix is valid, the issue may happen when `WebClient::detectBrowser` fail to detect the browser and so version.
Can happen due many reasons, as UserAgent string is not strict and can be anything.

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on 7a9a8701ca2485b07bcb5fec8fd81fcf6567322e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36400">issues.joomla.org/tracker/joomla-cms/36400</a>.</sub>

**Comment by zero-24** [comment]
Will merge this for now but I would say that complete method does not make sense to me but looks like I'm the only one here :)

**Pull request merged**
