### PR TITLE
[#34035] Errors uninstalling partially a package & reinstalling it

### PR DESCRIPTION
**Pull request by b92**
Copy description from http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=34035&start=0
### Issue

Errors uninstalling partially a package & reinstallint it (see how to reproduce) :
Into the Backend you will have the Warning messages :

**Warning**

JFolder: :files: Path is not a folder. Path: /administrator/components/com_mycomponent
JFolder: :files: Path is not a folder. Path: /administrator/components/com_ mycomponent
JInstaller: :Install: Cannot find XML setup file
JFolder: :files: Path is not a folder. Path: /components/com_ mycomponent
JFolder: :files: Path is not a folder. Path: /components/com_ mycomponent
JInstaller: :Install: Cannot find XML setup file

And into the apache error log :

Warning:  array_unique() expects parameter 1 to be array, null given in \site-joomla33\libraries\cms\installer\installer.php on line 1873, referer: http://localhost/site-joomla33/administrator/index.php?option=com_installer
### Testing

Have a Joomla package with a component and plugin

Uninstall the component ‘only’ (not the package) using Extensions/Manager (you will keep the package and plugin)

Reinstall the whole package (which include the extension: component & plugin)

You will have the error (displayed & error log)

### CODE REVIEW

**Comment by CedricTakongmo** [comment]
Hi guy,
I could not test this issue. I tried the testing instructions with the packages K2_v2.6.9, virtuemart.3.0.9 and jce_252 on joomla 3.4.4 dev, but I did not have any error. May be you can tell us with which package you tested it. It could be that this issue have been already treated on the core.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4057">issues.joomla.org/joomla-cms/4057</a>.</sub>

**Comment by b92** [comment]
For the test, you need to use a Joomla package witch use the Joomla mechanism for the package to install the component, plugin, component... referenced into the xml file (for the package), not installing a first component, which install itself the plugin like K2.

Take a look at: Zoo, BS MyJspace for example.

**Comment by Margreet137** [comment]
Hello
We have tested installing and uninstalling both packages the Zoo and the BS MySpace package. In both cases the installation and uninstall goes allright. We couldn't encounter the errors related to JFolder and Jinstaller. Looking at the history of this issue I see it started in aug 2014.
The Joomla version is 3.5.0 beta. Probably this error is fixed in meantime
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/4057">issues.joomla.org/joomla-cms/4057</a>.</sub>

**Comment by bxtrdturbo** [comment]
Hello
We have tested installing and uninstalling both packages the Zoo and the BS MySpace package. In both cases the installation and uninstall goes allright. We couldn't encounter the errors related to JFolder and Jinstaller. Looking at the history of this issue I see it started in aug 2014.
The Joomla version tested on  is 3.5.0 beta. Probably this error is fixed in meantime<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/4057">issues.joomla.org/joomla-cms/4057</a>.</sub>

**Comment by roland-d** [comment]
@b92 Thank you for your contribution. As there have been multiple tests that can no longer confirm the issue and it is an older PR, I am going to close this PR. If you feel the issue still exists, feel free to open this PR with updated information.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/4057">issues.joomla.org/joomla-cms/4057</a>.</sub>

**Pull request closed without merging**
