### PR TITLE
Single contact view. Support for number of articles to display (articles_display_num) #6474

### PR DESCRIPTION
**Pull request by ghost**
Issue https://github.com/joomla/joomla-cms/issues/6474
"Count of articles can't be configured at com_contacts contact form"

This PR adds a setting named  "articles_display_num" to several contact menu items  of com_contact and to single contact settings/display options..

If a contact is asigned/linked to a user and field "Show User Articles" is set to SHOW, you can now select an option in field "# Articles to List" that controls the number of articles of the user/contact that shall be displayed in frontend in single contact view.

I also added an OPTION "Use Contact Settings" for menu items.

You can set "# Articles to List" in
- Contacts Manager > Global Options > Tab Contact
- Menu type Contacts » Featured Contacts > Tab Form
- Menu type Contacts » categories > Tab Contact Display Options
- Menu type Contacts » List Contacts in a Category > Tab Contact Display Options 
- Menu type Contacts » Single Contact > Tab Contact Display Options

Please test them all and be aware that overriding rules should be the same like in com_content views.
Menu settings override global settings and so on.

Backwards compatibilty: PR should fall back to 10 articles when settings "# Articles to List" are untouched after applying patch.

Test :
- Create a new contact
- assign it to a user (e.g. site admin)
- create more than 10 items with the site admin (or the user you choose) e.g. 12
- enable the "Show Articles" option for the contact
- see the contact at the frontend
- you see only 10 items not all and can't configure this value
- Apply patch.
- Test settings "# Articles to List" in menu items, global settings, contact settings like described above. 
- See image below if you have several menu items where settings could have conflicts.

Addition concerning tests:
- If you use a Joomla with testing sample data:
- \- Link contact titled "Contact Name Here" with user "Super User" (is owner of lots of articles).
- \- Go to menu "All frontend views". Search for "contact". You may get listed all possible contact views.
- \- !!!Be aware that you have to deactivate other menu items for testing one. See image where I tested menu item "Featured"!!!

contact-menus

QUESTION: Should there be a condition that checks if SHOW_ARTICLES is set to SHOW before the model loads all the articles? 10 articles were loaded always, also before PR.

### CODE REVIEW

**Comment by brianteeman** [comment]
Language strings should be sorted alphabetically

**Comment by zero-24** [comment]
@bertmert @test works as expected. Thanks! One more tester here.

**Comment by infograf768** [comment]
>QUESTION: Should there be a condition that checks if SHOW_ARTICLES is set to SHOW before the model loads all the articles? 10 articles were loaded always, also before PR. 

This looks like a good idea.

**Comment by bertmert** [comment]
I've added now a condition for loading articles only when SHOW_ARTICLES is set to SHOW.

By the way:
Can somebody explain why we have this condition in model?
```
// If we are showing a contact list, then the contact parameters take priority
// So merge the contact parameters with the merged parameters
if ($this->getState('params')->get('show_contact_list'))
{
 $this->getState('params')->merge($contactParams);
}
```
I understand what it does but don't understand the logic behind it. Why do we override global/menu settings if contact selection is displayed

contact1

but not if not displayed and we call the contact via catgory view?

contact2

**Comment by larapetersen** [comment]
@test Could recreate issue. Works as described before & after the patch. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6485">issues.joomla.org/joomla-cms/6485</a>.</sub>

**Comment by zero-24** [comment]
Thanks for testing :+1: moving to RTC now!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6485">issues.joomla.org/joomla-cms/6485</a>.</sub>

**Comment by davdebcom** [comment]
@test
Seems to be working
Was already testing when second successful test was submitted :-)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6485">issues.joomla.org/joomla-cms/6485</a>.</sub>

**Comment by zero-24** [comment]
>Was already testing when second successful test was submitted :-)
No problem @davdebcom all tests are good tests!

**Comment by sovainfo** [comment]
Request to be labelled as "New Feature".

**Comment by brianteeman** [comment]
No

**Pull request closed without merging**
