### PR TITLE
[4.4] Fix Banners application crashes

### PR DESCRIPTION
**Pull request by joomdonation**
Pull Request for Issue #42841.

### Summary of Changes
The current code in `BannerHelper` classs bind a `Joomla\CMS\Date\Date` object to `:date` parameter and could cause application crashes in some environments as reported in the issue. This PR changes code so that the parameter is bound by a  string in Datetime format instead (same with the code in other places in Joomla). I also rename the variable to `$nowDate` to imply that this is current date time (also, same with similar codes use in other places in Joomla)

### Testing Instructions

- Use Joomla 4.4
- Apply patch
- Access to Banners Management screen from administrator area of your site

### Actual result BEFORE applying this Pull Request
Sometime application crashes

### Expected result AFTER applying this Pull Request

Always works, no crashes anymore.

### Link to documentations
Please select:
- [x] No documentation changes for docs.joomla.org needed
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 183b5621e7ade4f0e926580eedd0ea848edea98e<br /><br />code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42869">issues.joomla.org/tracker/joomla-cms/42869</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 183b5621e7ade4f0e926580eedd0ea848edea98e<br /><br />code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42869">issues.joomla.org/tracker/joomla-cms/42869</a>.</sub>

**Comment by chmst** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42869">issues.joomla.org/tracker/joomla-cms/42869</a>.</sub>

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
