### PR TITLE
[4.0] Installation: Adding a hint on top of Password field

### PR DESCRIPTION
**Pull request by infograf768**
### Summary of Changes
As installation password must now be at least 12 characters, this adds a hint on top of the field.

### Testing Instructions
Patch and install a clean Jooomla

### Actual result BEFORE applying this Pull Request
No way to know one needs 12 characters minimum to install joomla

### Expected result AFTER applying this Pull Request
Screen Shot 2020-08-18 at 12 45 44

### CODE REVIEW

**Comment by brianteeman** [comment]
Fine by me but it needs to be checked for accessibility by the accessibility team

**Comment by brianteeman** [comment]
Hints are generally considered to be bad for accessibility even though they wont fail automated tests see https://www.smashingmagazine.com/2018/06/placeholder-attribute/

Placing the text between the label and the input and associating it with the input using `aria-described by ` on the input  seems to be the recommendation.

But please check with the accessibility team

**Comment by infograf768** [comment]
We have many occurences of hint in core. Should it not be solved at that level?

**Comment by brianteeman** [comment]
Please ask the accessibility team

**Comment by infograf768** [comment]
@zwiastunsw 
Anything you can do?

**Comment by chmst** [comment]
Why not expand the label?

**Comment by infograf768** [comment]
The code for `hint` in the password field (`/layouts/joomla/form/field/password.php`) is:
`strlen($hint) ? 'placeholder="' . htmlspecialchars($hint, ENT_COMPAT, 'UTF-8') . '"' : '',

In core this is what we have for the Search field
```
<input type="text" name="filter[search]" id="filter_search" value="" class="form-control" aria-describedby="filter[search]-desc" placeholder="Search" inputmode="search">
```

It is a text field layout where we have among attributes
`!empty($description) ? 'aria-describedby="' . $name . '-desc"' : '',`

If I add the same attribute in the password field layout + a description in the xml, i.e.
```
		<field
			name="admin_password"
			type="password"
			label="INSTL_ADMIN_PASSWORD_DESC"
			description="INSTL_ADMIN_PASSWORD_LENGTH"
			hint="INSTL_ADMIN_PASSWORD_LENGTH"
			id="admin_password"
			class="form-control" // to take off
			required="true"
			autocomplete="new-password"
			validate="password"
		/>
```
I will get
```
<input type="password" name="jform[admin_password]" id="jform_admin_password" value="" autocomplete="new-password" class="form-control form-control required" aria-describedby="jform[admin_password]-desc" maxlength="99" required="" data-min-length="4" placeholder="Enter at least 12 characters.">
```

Is it what you want for accessibility?

Note:
We also have to correct the double `form-control` class as it is already defined in the layout and is unecessary in the xml
`!empty($class) ? 'class="form-control ' . $class . '"' : 'class="form-control"',`

**Comment by brianteeman** [comment]
you should remove the placeholder=
and add a div with an id of jform[admin_password]-desc that contains the text

**Comment by infograf768** [comment]
So, what you mean is that the Search field is wrong?
There is a div for it indeed but as a tooltip role... It keeps the placeholder.

Screen Shot 2020-08-18 at 09 19 26

I think this is correct.

I can obtain a similar result for installation password with the change above and
```
<div class="password-group">
	<div class="input-group">
		<input
			type="password"
			name="<?php echo $name; ?>"
			id="<?php echo $id; ?>"
			value="<?php echo htmlspecialchars($value, ENT_COMPAT, 'UTF-8'); ?>"
			<?php echo implode(' ', $attributes); ?>>
		<?php if (!empty($description)) : ?>
			<div role="tooltip" id="<?php echo $name . '-desc'; ?>">
				<?php echo htmlspecialchars(Text::_($description), ENT_COMPAT, 'UTF-8'); ?>
			</div>
		<?php endif; ?>
		<span class="input-group-append">
			<button type="button" class="btn btn-secondary input-password-toggle">
				<span class="fas fa-eye fa-fw" aria-hidden="true"></span>
				<span class="sr-only"><?php echo Text::_('JSHOWPASSWORD'); ?></span>
			</button>
		</span>
	</div>
</div>
```
to get
Screen Shot 2020-08-18 at 10 01 35

Remains to add the css which is absent from installation
```
// set up hidden tooltip
[role="tooltip"]:not(.show) {
  z-index: $zindex-tooltip;
  display: none;
  max-width: 100%;
  padding: .5em;
  margin: .25em;
  color: $white;
  text-align: start;
  background: $black;
  border-radius: .2rem;
}

// reveal associated tooltip on focus
:focus + [role="tooltip"],
:hover + [role="tooltip"] {
  position: absolute;
  display: block;
}
```
Agree?

**Comment by brianteeman** [comment]
reading on my phone but that would be correct if you wanted it as a "tooltip" style

**Comment by infograf768** [comment]
hmm not a good solution. The tip is displayed IN the field...

**Comment by infograf768** [comment]
I can get, after I take off the hint

Screen Shot 2020-08-18 at 10 58 58

and code is

Screen Shot 2020-08-18 at 11 00 00

Don't know any way to display a `<div>` in the field itself to replace the hint.

**Comment by brianteeman** [comment]
> Don't know any way to display a <div> in the field itself to replace the hint.

You definitely do not want to do that. That is what the article was explaining makes the hint not accessible.
You can either do it as you have done as a "tooltip" or as below which is what I thought you would be doing

image

**Comment by brianteeman** [comment]
Or do as @chmst suggested
image

**Comment by infograf768** [comment]
> as below which is what I thought you would be doing

Easy enough. I prefer 

Screen Shot 2020-08-18 at 12 40 40

or, with text-muted

Screen Shot 2020-08-18 at 12 45 44

**Comment by infograf768** [comment]
It can now be tested. Accessibility should be OK.
Screen Shot 2020-08-18 at 17 16 47

**Comment by Quy** [comment]
Please consider doing it this way:



Add the following after line 114 and delete lines 95-99.

```
	<?php if (!empty($description)) : ?>
		<small id="<?php echo $name . '-desc'; ?>" class="form-text text-muted">
			<?php echo htmlspecialchars(Text::_($description), ENT_COMPAT, 'UTF-8'); ?>
		</small>
	<?php endif; ?>
```

**Comment by brianteeman** [comment]
@quy please read the article I linked to which explains why this is a bad idea. Telling me **after** the input what I should have put in the input is not correct

**Comment by Quy** [comment]
OK. Keep it as it but change the markup slightly.

30402before

**Comment by infograf768** [comment]
@Quy will do

**Comment by infograf768** [comment]
@Quy
`<small>` (which means `font-size: .8rem;`) would not work on Macintosh if not inside a `<div>`. The hint is displayed to the right of the field.

I just added the `small` class to get the result proposed. I.e.
```
<?php if (!empty($description)) : ?>
	<div id="<?php echo $name . '-desc'; ?>" class="text-muted small">
		<?php echo htmlspecialchars(Text::_($description), ENT_COMPAT, 'UTF-8'); ?>
	</div>
<?php endif; ?>
```

Screen Shot 2020-08-19 at 08 45 41


Folks, please test.

**Comment by Magnytu2** [comment]
I have tested this item :white_check_mark: successfully on bebeccb40d995312b23d9b2782a0587568d09b90<br /><br />Works fine for me.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30402">issues.joomla.org/tracker/joomla-cms/30402</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on bebeccb40d995312b23d9b2782a0587568d09b90<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30402">issues.joomla.org/tracker/joomla-cms/30402</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30402">issues.joomla.org/tracker/joomla-cms/30402</a>.</sub>

**Pull request merged**
