### PR TITLE
IE 8 Fix Global Configuration form submit

### PR DESCRIPTION
**Pull request by Fedik**
Here is :bug: fix for IE8, that cause "Save" button do not work in Global configuration.

**Test**
Open Global configuration in IE8 and try save.
**Actual result:** nothing happens
**Expected:** form saved

### CODE REVIEW

**Comment by RickR2H** [comment]
Fix worked in IE8 Emulation mode!
for the next tester not knowing how to emulate IE8, here is the documentation https://msdn.microsoft.com/en-us/library/dn255001(v=vs.85).aspx
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7468">issues.joomla.org/joomla-cms/7468</a>.</sub>

**Comment by waader** [comment]
I am unable to replicate the problem under win xp with ie 8.0. When I change for example the "site name" it is saved with or without the patch.

**Comment by Fedik** [comment]
@waader hm, strange, I found this bug on Win 8 in IE8 Emulation mode

**Comment by RickR2H** [comment]
I tested it on Windows 7 and IE8 emulation and can confirm the bug.

**Comment by Fedik** [comment]
Any way, use `setAttribute()` more safe than direct assignment, in this case.
Even jQuery warn about such problem http://api.jquery.com/prop/ : 
>Attempting to change the type property (or attribute) of an input element created via HTML or already in an HTML document will result in an error being thrown by Internet Explorer 6, 7, or 8.

So if for @waader this patch still work then I would count it as success test :wink:

**Comment by AnneKlapwijk** [comment]
I have tested this item :white_check_mark: successfully on 7d81098e00567fa722a872fb7e9c6c34f3b69772<br /><br />Successfully reproduced the issue in IE8.
After applying the patch, the 'Save' button worked and the form was saved.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7468">issues.joomla.org/joomla-cms/7468</a>.</sub>

**Comment by Iclamer** [comment]
I have tested this item :white_check_mark: successfully on 7d81098e00567fa722a872fb7e9c6c34f3b69772<br /><br />Successfully reproduced the issue in IE8.
After applying the patch, the 'Save' button worked and the form was saved.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7468">issues.joomla.org/joomla-cms/7468</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7468">issues.joomla.org/joomla-cms/7468</a>.</sub>

**Comment by rdeutz** [comment]
@Fedik could you have a look at the merge conflicts, thanks.

**Comment by Fedik** [comment]
good old problem with merging the minified script version :smile:

**Pull request merged**
