### PR TITLE
Global Config SEO showon options

### PR DESCRIPTION
**Pull request by brianteeman**
#### Summary of Changes

Cosmetic UI change to show/hide options based on selection
#### SEO No

ezfb 1
#### SEO Yes

vxyx

### CODE REVIEW

**Comment by hans2103** [comment]
I have tested this item :white_check_mark: successfully on da5d48bc46c8e689379753a5fb8e67af5720f986<br /><br />I like this showOn toggle!
Thank you for this PR. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10225">issues.joomla.org/joomla-cms/10225</a>.</sub>

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on da5d48bc46c8e689379753a5fb8e67af5720f986<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10225">issues.joomla.org/joomla-cms/10225</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10225">issues.joomla.org/joomla-cms/10225</a>.</sub>

**Comment by BurtNL** [comment]
I have tested this item :white_check_mark: successfully on da5d48bc46c8e689379753a5fb8e67af5720f986<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10225">issues.joomla.org/joomla-cms/10225</a>.</sub>

**Pull request merged**
