### PR TITLE
[4.0] Add legend and fix display

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
Add legend and fix display.

### Testing Instructions
Install sample demo
Go to Menus > Manage 
Edit a menu
Go to Permissions tab

### Expected result
legend-after

### Actual result
legend-before

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 435a9e39637d1413ecc1946d90594d6ed4023152<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26403">issues.joomla.org/tracker/joomla-cms/26403</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 435a9e39637d1413ecc1946d90594d6ed4023152<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26403">issues.joomla.org/tracker/joomla-cms/26403</a>.</sub>

**Comment by infograf768** [comment]
rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26403">issues.joomla.org/tracker/joomla-cms/26403</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
