### PR TITLE
[4.0] Use Framework's Image package

### PR DESCRIPTION
**Pull request by mbabker**
### Summary of Changes

Have the `JImage` class chain extend the Framework's Image package.  For the most part this basically proxies everything in `JImage` over and has `JImageFilter` extend the Framework's counterpart class.  The two base classes in the CMS chain will also auto-inject a logger into the instance.  Deprecate most existing classes for removal at 5.0, there isn't a good way to proxy these without breaking class inheritance or if someone has custom filter objects causing them to need to rename classes.
### Testing Instructions

Using the `JImage` API is still possible without error.
### Documentation Changes Required

Classes documented as deprecated in 4.x and removed at 5.0.

### CODE REVIEW

**Comment by zero-24** [comment]
@mbabker any reason to not deprecate the J* Calsses for 4.0 and remove it with 4.0?

**Comment by mbabker** [comment]
Unless we're pulling in the package on the 3.x branch it'd be more disruptive to require anyone using the API to use version conditionals for 3.x and 4.x use than to do it this way.

**Comment by zero-24** [comment]
ok sounds fair :smile:

**Comment by wilsonge** [comment]
Is it deliberate that JImage itself isn't also deprecated for 5.0?

**Comment by wilsonge** [comment]
https://docs.joomla.org/Potential_backward_compatibility_issues_in_Joomla_4#Image This has been documented as is. I think it's probably a bug that JImage isn't also deprecated in which case we need another PR and documentation update for that

**Comment by mbabker** [comment]
The JImage constructor is automatically injecting the JLog PSR-3 bridge in for logging.  Other than that, it's basically checking functionality between the CMS and Framework and ensuring they're the same.

**Pull request merged**
