### PR TITLE
[4.0] Alt Text

### PR DESCRIPTION
**Pull request by brianteeman**
This simple PR updates the text used for the ALT label to be consistent with elsewhere in Joomla.

This PR changes the text used when adding an image with drag and drop and with the image xtd-editor plugin

image

image

cc @carcam

### CODE REVIEW

**Comment by dgrammatiko** [comment]
@brianteeman just brought the checkbox for the empty alt tag to drag and drop here: https://github.com/joomla/joomla-cms/pull/31578
It's missing the translation string (in the .ini file) and a line after https://github.com/joomla/joomla-cms/blob/eb9095e10b74f21d1852204de142dc4d049dc9a5/plugins/editors/tinymce/tinymce.php#L528 to pass it to the js

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on f4c3a81ee4c96075308f6dd2c4ae21e2c64db2f5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31577">issues.joomla.org/tracker/joomla-cms/31577</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on f4c3a81ee4c96075308f6dd2c4ae21e2c64db2f5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31577">issues.joomla.org/tracker/joomla-cms/31577</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31577">issues.joomla.org/tracker/joomla-cms/31577</a>.</sub>

**Comment by chmst** [comment]
Thanks!

**Comment by brianteeman** [comment]
thx

**Pull request merged**
