### PR TITLE
Update News Feed ID in Single News Feed menu item - MySQL

### PR DESCRIPTION
**Pull request by imanickam**
Pull Request for Issue # .
No Issue Registered

### Summary of Changes
At present the News Feed ID mentioned/chosen in the SQL of the menu item with title Single News Feed is 4.  Whereas there are only three News Feed Items defined in the Sample Data Learn and their IDs are 1, 2, and 3.  So, there is no News Feed item with ID 4.  This results in error when the menu item Single News Feed is chosen in the front end when the Sample Data Learn is installed.

### Testing Instructions

(a) Install Joomla! with Sample Data LEARN.  Choose this option while installing Joomla!

(b) View the site

(c) On the site, in the menu "About Joomla!", click on the menu item "Single News Feed"
1_Single_News_Feed_Menu_Item

### Expected result

5_Result_of_Single_News_Feed_Menu_Item_After_Correction

### Actual result

2_Error_Feed_Not_Found

### Documentation Changes Required
There are only three News Feed Items Defined in the Sample Data (Learn) and their IDs are 1, 2, and 3.  See the following image.
4_News_Feeds_Available_in_Sample_Learn

Where as in the insert statement of SQL for the menu item "Single News Feed", the ID is mentioned as 4.  This results in the error.  See the image below:
3_Menu_Item_Single_News_Feed

If the ID is changed to an ID of a News Feed item that is present (example: 2), the error will not show and the correct news feed would be shown.
6_Menu_Item_Single_News_Feed_After_Correction
 
Note:
The testing cannot be done with Patch Tester.  First testing must be done just by installing Joomla!  The second test also must done as a fresh install.  However, after unzipping the files, the modified file/files has/have to be copied from Github.  This action will overwrite the appropriate sample data files.  After that, the installation dialog has to be invoked.

### CODE REVIEW

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on 8e6406a69a5669709fdf1890be199208485baaa6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27100">issues.joomla.org/tracker/joomla-cms/27100</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 8e6406a69a5669709fdf1890be199208485baaa6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27100">issues.joomla.org/tracker/joomla-cms/27100</a>.</sub>

**Comment by infograf768** [comment]
rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27100">issues.joomla.org/tracker/joomla-cms/27100</a>.</sub>

**Comment by infograf768** [comment]
tks

**Pull request merged**
