### PR TITLE
3370_show_title_article_problem

### PR DESCRIPTION
**Pull request by Kixo**
**The problem**
No matter what I set the properties in the backend, the boolean value for "show_title" is always TRUE.
At first I edited "components\com_content\views\article\tmpl\default.php" Line 43:
-- get('show_title') || $params->get('show_author')) : ?>
++ get('show_title')&&$params->get('show_page_heading')) || $params->get('show_author')) : ?>
I know it is not a permanent solution, because that condition would be tied to two variables.
**The solution**
It will not break existing use case scenario but now user have the option to inherit Article options instead of Global options in that article.

I have made it possible for any option to be used in this way if it will be needed. It can be enabled by adding option COM_CONTENT_FIELD_VALUE_USE_ARTICLE_SETTINGS

_Description pasted from original issue by Brian Teeman_

### CODE REVIEW

**Comment by davdebcom** [comment]
@Kixo Sent you a pull request to add use Joomla\Registry\Registry; to the top of view.html.php

@ Other testers: if you get the error, add "use Joomla\Registry\Registry;" to the top of view.html.php.

@Test
Works. Adds an option "Use Article Settings" to menu item edit view for articles to use the "Show title" setting as defined in the article itself (not com_content options). 

@HermanPeeren and I discussed it. We might want to discuss if this is the best solution UX wise. We should either add "Use Article Settings" for all options (not just title) or adjust "Use Global" name to "Use Article Settings" and adjust the function to always take the setting from the article, which could be "Use Global". The term "Use Global" might be better as "Use Global Article Settings".

**Comment by roland-d** [comment]
@Kixo Can you look at the PR sent to you by @davdebcom so we can test this issue further?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/3700">issues.joomla.org/joomla-cms/3700</a>.</sub>

**Comment by roland-d** [comment]
Hello @Kixo 

Thank you for your contribution.

The last comment here was on 21st August. Can you please update the pull request?

If no reply is received within 4 weeks we will close this issue.

Thanks for understanding! <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/3700">issues.joomla.org/joomla-cms/3700</a>.</sub>

**Comment by brianteeman** [comment]
Closed due to inactivity stated above.
It can always be reopened if needed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/3700">issues.joomla.org/joomla-cms/3700</a>.</sub>

**Pull request closed without merging**
