### PR TITLE
s/postion/position

### PR DESCRIPTION
**Pull request by PhilETaylor**
s/postion/position

### CODE REVIEW

**Comment by Twincarb** [comment]
I have tested this item :white_check_mark: successfully on ae2d3aed293627eee302821d93897cf5add6f699<br /><br />Code Review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23009">issues.joomla.org/tracker/joomla-cms/23009</a>.</sub>

**Comment by richard67** [comment]
@PhilETaylor The "Postions" also occurs [in file "plugins\content\pagenavigation\pagenavigation.php" at the end of line 184](https://github.com/joomla/joomla-cms/blob/d67e585595d41b3705aa0673fd4d3afdaa68d7b5/plugins/content/pagenavigation/pagenavigation.php#L184).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23009">issues.joomla.org/tracker/joomla-cms/23009</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on ae2d3aed293627eee302821d93897cf5add6f699<br /><br />Code review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23009">issues.joomla.org/tracker/joomla-cms/23009</a>.</sub>

**Comment by PhilETaylor** [comment]
> @PhilETaylor The "Postions" also occurs in file "plugins\content\pagenavigation\pagenavigation.php" at the end of line 184.

Thus proving the fact that I was not using a blind search and replace :)

**Comment by richard67** [comment]
@PhilETaylor I've never said that 👅

**Comment by PhilETaylor** [comment]
Others have. 👅

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23009">issues.joomla.org/tracker/joomla-cms/23009</a>.</sub>

**Comment by PhilETaylor** [comment]
As this one is RTC already I've added the missing s/postions/positions to https://github.com/joomla/joomla-cms/pull/23030/files

**Pull request merged**
