### PR TITLE
[5][com_installer] add toolbar button 1 click

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #42980 .

### Summary of Changes
+ toolbar button from Extensions : Manage to Extensions : Update
+ toolbar button from Extensions : Update to Extensions : Manage

### Testing Instructions
from Extensions : Manage to Extensions : Update and viceversa 1 click only

### Actual result BEFORE applying this Pull Request
multiple click

### Expected result AFTER applying this Pull Request
1 click

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on f25a7e1bb57e2e66939a2db72a51e4b217de5204<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42985">issues.joomla.org/tracker/joomla-cms/42985</a>.</sub>

**Comment by brianteeman** [comment]
personaly I would not accept this PR. It works but isnt it changing the UI/UX from its original intent?

**Comment by chmst** [comment]
Personally I always thought that the original had a UX problem here and this was missing. I don't remeber why ther was a origianl intention at all ofr a discussion.

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on f25a7e1bb57e2e66939a2db72a51e4b217de5204<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42985">issues.joomla.org/tracker/joomla-cms/42985</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42985">issues.joomla.org/tracker/joomla-cms/42985</a>.</sub>

**Comment by LadySolveig** [comment]
Thank you @alikon and also for testing @ChristineWk @ceford

**Pull request merged**
