### PR TITLE
Cypress test for featured com_contact.

### PR DESCRIPTION
**Pull request by rajputanuj31**
Add com_contact cypress test.

### CODE REVIEW

**Comment by laoneo** [comment]
Thank you for the pull request. There are some code style issues https://ci.joomla.org/joomla/joomla-cms/63375/1/29. Can you fix them?

**Comment by rajputanuj31** [comment]
> Thank you for the pull request. There are some code style issues https://ci.joomla.org/joomla/joomla-cms/63375/1/29. Can you fix them?

Fixed.

**Comment by laoneo** [comment]
Thank you very much for your first pr!

**Comment by rajputanuj31** [comment]
Thanks a lot for merging it.

**Pull request merged**
