### PR TITLE
[4.0] reverse category order

### PR DESCRIPTION
**Pull request by brianteeman**
Use the correct class to ensure the display of the field is full width

### Before
image

### After
image

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 9329f32fc2fb6a453e4a49eb70a6e5dc19ce2ea3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34932">issues.joomla.org/tracker/joomla-cms/34932</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 9329f32fc2fb6a453e4a49eb70a6e5dc19ce2ea3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34932">issues.joomla.org/tracker/joomla-cms/34932</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34932">issues.joomla.org/tracker/joomla-cms/34932</a>.</sub>

**Comment by Quy** [comment]
Thanks!

**Comment by brianteeman** [comment]
thx

**Pull request merged**
