### PR TITLE
[4.2 RC1] Feed display module not working

### LINKED ISSUE #38310: [4.2 RC1] Feed display module not working
### Steps to reproduce the issue
Create a Feed display module.
Enter https://www.joomla.org/announcements.feed?type=rss in Feed URL parameter
Enter Sidebar-right as position (using cassiopeia template)

### Expected result
Display Feed infos.

### Actual result
Feed display module shows "Feed not found" error in all cases.

### System information (as much as possible)
Joomla 4.2 RC1
PHP 8.1

### Additional comments
Seems to be related to fix #38095 
Librairies/src/Feed/Parser/RssParser.php : line 355 makes RSS reader point to far in RSS file.

### PR DESCRIPTION
**Pull request by conseilgouz**
Pull Request for Issue #38310 .

### Testing Instructions
Create a Feed display module.
Enter https://www.joomla.org/announcements.feed?type=rss in Feed URL parameter
Enter Sidebar-right as position (using cassiopeia template)

### Actual result BEFORE applying this Pull Request

Feed display module shows "Feed not found" error in all cases.

### Expected result AFTER applying this Pull Request

Display Feed infos.

### CODE REVIEW

**Comment by conseilgouz** [comment]
AppVeyor failed because $this->version has correct values for Atom and RSS files.

tests\Unit\Libraries\Cms\Feed\Parser\AtomParserTest.php file and tests\Unit\Libraries\Cms\Feed\Parser\RssParserTest.php seem to be wrong.

**Comment by richard67** [comment]
> AppVeyor failed because $this->version has correct values for Atom and RSS files.
> 
> tests\Unit\Libraries\Cms\Feed\Parser\AtomParserTest.php file and tests\Unit\Libraries\Cms\Feed\Parser\RssParserTest.php seem to be wrong.

@conseilgouz Then you should fix the tests, too. Let us know if you need some help or advise for that.

**Comment by richard67** [comment]
P.S.: You can run the unit test locally on a git clone by running `composer install` (if not done yet) and then `./libraries/vendor/bin/phpunit --testsuite Unit` from the Joomla folder.

**Comment by richard67** [comment]
@conseilgouz The failing tests can be found here https://github.com/joomla/joomla-cms/blob/4.2-dev/tests/Unit/Libraries/Cms/Feed/Parser/AtomParserTest.php#L374-L387 and here https://github.com/joomla/joomla-cms/blob/4.2-dev/tests/Unit/Libraries/Cms/Feed/Parser/RssParserTest.php#L583-L601 .

But from reading the code, the tests seem to be correct regarding the checked versions.

Here the output from the test run in Appveyor:

```
There were 2 failures:
1) Joomla\Tests\Unit\Libraries\Cms\Feed\Parser\AtomParserTest::testInitialiseSetsOldVersion
Failed asserting that two strings are equal.
--- Expected
+++ Actual
@@ @@
-'0.3'
+'1.0'
C:\projects\joomla-cms\tests\Unit\Libraries\Cms\Feed\Parser\AtomParserTest.php:386
2) Joomla\Tests\Unit\Libraries\Cms\Feed\Parser\RssParserTest::testParseSetsVersion
Failed asserting that null matches expected '2.0'.
C:\projects\joomla-cms\tests\Unit\Libraries\Cms\Feed\Parser\RssParserTest.php:600
FAILURES!
Tests: 757, Assertions: 1190, Failures: 2, Skipped: 1.
Command exited with code 1
```

So it seems your PR is not right or changes something at the wrong place.

**Comment by conseilgouz** [comment]
@richard67 : unit test files (RSS & ATOM) have been updated, so they match FeedFactory behaviour : go to root node and read it.

**Comment by conseilgouz** [comment]
@richard67 : integration/drone/pr has a phpmin-system-postgress error : I'm afraid I don't have enough knowledge to fix this one....

**Comment by conseilgouz** [comment]
After merging branch, postgress error disappeared...

**Comment by richard67** [comment]
@conseilgouz Sometimes we have unrelated errors in system tests e.g. due to timeouts.

But besides this I am not convinced of your changes in the tests. The tests looked right to me before. I don’t have the time now for testing it myself, but if nobody else can reproduce the issue I have doubts on this PR.

**Comment by conseilgouz** [comment]
@richard67 : about the changes, when initialise function is called in RssParser.php and AtomParser, stream (xmlreader) has read the root node : it's done in FeedFactory.php, function getFeed(), lines 68 and above.
In the unit test files, I just reproduced this behaviour.
Before my changes, initialise (in AtomParser.php and RssParser.php) was performing a moveToNextElement when reader was already on the feed or rss record (which should contain version info) : that was introduced by PR #38095

**Comment by conseilgouz** [comment]
> but if nobody else can reproduce the issue I have doubts on this PR.

That's a 4.2 RC1 issue. Let's hope somebody else will see this issue.

**Comment by conseilgouz** [comment]
2 ways to fix #38310 
1.  update FeedFactory.php, so it does not read xml file before calling initialise function
or 
2. update RssParser & AtomParser so they assume actual xlm record is the root node

Current PR is following fix 2 idea.

**Comment by alikon** [comment]
i can replicate the issue like  has been described

**Comment by conseilgouz** [comment]
> i can replicate the issue like has been described

It seems that just the two of us are interested in this issue.

**Comment by fontanil** [comment]
I have tested this item :white_check_mark: successfully on 6157800586d2285afc1bcc903775fd267c489dc4<br /><br />Tested with success (4.2.0 rc2 dev)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38312">issues.joomla.org/tracker/joomla-cms/38312</a>.</sub>

**Comment by conseilgouz** [comment]
@alikon : one more human test to go.....

**Comment by YGomiero** [comment]
I have tested this item ✅ successfully 

Tested with success (4.2.0 rc2 dev)

**Comment by richard67** [comment]
> I have tested this item ✅ successfully
> 
> Tested with success (4.2.0 rc2 dev)

@YGomiero A comment with a green check mark is not sufficient for the test to count. You have to mark your test result in the issue tracker here https://issues.joomla.org/tracker/joomla-cms/38312 , use the blue "Test this" button at the top left corner, select the test result and finally submit. Could you do so? Thanks in advance.

**Comment by YGomiero** [comment]
I have tested this item :white_check_mark: successfully on 6157800586d2285afc1bcc903775fd267c489dc4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38312">issues.joomla.org/tracker/joomla-cms/38312</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38312">issues.joomla.org/tracker/joomla-cms/38312</a>.</sub>

**Pull request merged**
