### PR TITLE
[4.0] Store module namespace on installation

### PR DESCRIPTION
**Pull request by joomdonation**
Pull Request for Issue # .

### Summary of Changes
This PR did two things:

1. Store namespace for module when modules are installed/updated

2. Update xml files to have correct namespace tag for namespaced modules

This PR is created so that @wilsonge can finish his PR https://github.com/joomla/joomla-cms/pull/18703/

### Testing Instructions
Can be merged by code review

### CODE REVIEW

**Comment by brianteeman** [comment]
i am a bit confused as the changes in the adapter are only for installed modules and none of these modules are installed that way

**Comment by joomdonation** [comment]
As I mentioned, this PR was created so that @wilsonge can finish his PR  #18703. That PR creates namespace maps for modules and components but our current code doesn't store namespace of modules during install it (we store it for components already).  Hope it answers your question

**Comment by brianteeman** [comment]
> our current code doesn't store namespace of modules during install 

The modules you have updated are not "intalled" by the installer so i dont see how updating the xml of these modules will have any effect

**Comment by joomdonation** [comment]
When someone wants to develop a new module which supports namespace, he can looks at the XML file of one of core modules to know how to set namespace for the module (so that the module classes will be uploadable). We do that for our core components, too

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 606a6f321c25e0ab77e898287190cb34c34a51b7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19325">issues.joomla.org/tracker/joomla-cms/19325</a>.</sub>

**Pull request merged**
