### PR TITLE
Allow to use filter.state for delete button in ListView

### PR DESCRIPTION
**Pull request by HLeithner**
Since Joomla! 4 we have a useful addToolBar function in ListView which generates the toolbar pretty well. But it's missing to accept the `filter.state` instead of the legacy `filter.published` used in some components. Since Joomla ist self also uses `filter.state` it should support it here too.

### Summary of Changes
Check current value of the state `filter.state` and `filter.published`.
I would not expect any b/c issues because both values are used for the same usecase and at the moment you have to override `addToolbar` anyway to use the `filter.state`.

### Testing Instructions
Test core joomla extensions if filtering for the status "Trashed" still work.
Bonus create an extension which users `filter.state` as column field. (of course I tested it and it's working)

### Actual result BEFORE applying this Pull Request
* Trash button still Trash button

### Expected result AFTER applying this Pull Request
* Trash button is now a Delete button

### Documentation Changes Required

Not really because base documentation is missing.

### CODE REVIEW

**Comment by richard67** [comment]
Unit tests are consistently failing here, but I think it’s not related to this PR. The LDAP authentication tests are failing. Could be a problem on the 4.3-dev branch in general.

**Comment by richard67** [comment]
P.S.: The LDAP tests have been added to 4.3-dev with PR #38593 . They one worked but now fail.

**Comment by HLeithner** [comment]
@richard67 pr was not uptodate with 4.3-dev branch and the openldap service was missing.

**Comment by HLeithner** [comment]
This pull request has been automatically rebased to 4.4-dev.

**Review by wilsonge — APPROVED** [review]

**Comment by tomsrocket** [comment]
I spent some time trying to test this, but I could not confirm this works. 
I am not sure I correctly understand how to test this. 
Can you please add more detailed instructions how to test this?

**Comment by joomdonation** [comment]
@tomsrocket This class is actually not used in Joomla core, so it would be for someone with code review skill. So unless you have developer experience, please ignore this PR.

**Comment by joomdonation** [comment]
I have tested this item :white_check_mark: successfully on 628d53a0063fb23161baf0fc286d128ef255103c<br /><br />Code review !<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38797">issues.joomla.org/tracker/joomla-cms/38797</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 628d53a0063fb23161baf0fc286d128ef255103c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38797">issues.joomla.org/tracker/joomla-cms/38797</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38797">issues.joomla.org/tracker/joomla-cms/38797</a>.</sub>

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
