### PR TITLE
Fix tinymce when sorting happen

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue #24343 .

### Summary of Changes

The patch re-init an editor when the iframe moved around DOM.

### Testing Instructions
Apply patch, run `npm install`
Please follow #24343

Or create subform with editor (example in Custom HTML):
```xml
<field type="subform" name="subform" multiple="true" label="subform">
  <form>
    <field type="editor" name="text" label="editor" buttons="false"  default="I am a text!"/>
  </form>
</field>
```

Add couple rows in subform and try sort them. Then watch editor content.

### Actual result BEFORE applying this Pull Request
Content are gone.

### Expected result AFTER applying this Pull Request
Content still there (can be with little delay)

### Documentation Changes Required
None

### CODE REVIEW

**Comment by HLeithner** [comment]
This pull request has automatically rebased to 4.2-dev.

**Comment by JonasAtZwetschke** [comment]
I have tested this item :white_check_mark: successfully on 1007fe6b9da12201ea789627221f5248c3b3a578<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36345">issues.joomla.org/tracker/joomla-cms/36345</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36345">issues.joomla.org/tracker/joomla-cms/36345</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 1007fe6b9da12201ea789627221f5248c3b3a578<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36345">issues.joomla.org/tracker/joomla-cms/36345</a>.</sub>

**Comment by roland-d** [comment]
Thank you

**Comment by Quy** [comment]
@Fedik Please check why the editor loses focus when editing an article.

**Comment by Fedik** [comment]
@Quy what wrong with focus? works fine for me

**Comment by Fedik** [comment]
I see, Firefox and Chrome handle iframe events diferently. I will check.

**Pull request merged**
