### PR TITLE
Added a plugin event to change the SQL query of the data list in the "ListModel" class

### PR DESCRIPTION
**Pull request by motokraft**
Pull Request for Issue #36978.

### Summary of Changes
Add a plugin event to the **ListModel::getItems** function before executing the SQL query

### Testing Instructions
None

### Actual result BEFORE applying this Pull Request
It is not possible to change the SQL query before execution

### Expected result AFTER applying this Pull Request
Add plugin event to change SQL query before execution

### Documentation Changes Required
None

### CODE REVIEW

**Comment by Hackwar** [comment]
This would qualify as a new feature and there will be no new features in the 3.x branch. Besides that, we had this feature request several times before and they were always denied. Your best bet is to override the model in a plugin and make your changes directly.

**Comment by motokraft** [comment]
> This would qualify as a new feature and there will be no new features in the 3.x branch. Besides that, we had this feature request several times before and they were always denied. Your best bet is to override the model in a plugin and make your changes directly.

Yes, what are you talking about! I did a merge for the first time... Using your version, what kind of shitty code will turn out then! I want it to be simple for the user and fast for the server, and you suggest writing shitty code ....

**Comment by motokraft** [comment]
> Your best bet is to override the model in a plugin and make your changes directly.

I want to do the best so as not to fence any garbage

**Comment by Hackwar** [comment]
You wont get very far if you insult people. I was trying to propose to you something that you can do right now to get what you want, but regardless of that, my first comment still stands:

Joomla 3.x is EOL and only receives bugfixes and security fixes. This here is neither and instead is a new feature. It can NOT be accepted for 3.10. If you really think that this should be implemented, then you would have to do this PR for Joomla 4, specifically for at least Joomla 4.2.

But as I also wrote, this has been proposed several times before and was always rejected.

**Comment by motokraft** [comment]
> ou wont get very far if you insult people.

I didn't mean to offend you in any way, it's just how Google translate goes

**Pull request closed without merging**
