### PR TITLE
Update compile-to-es2017.es6.js

### PR DESCRIPTION
**Pull request by brianteeman**
Fixes typo

s/tranpiling/transpiling

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 1c8506a53e4a109a2fe444ec8a2d4c5c54bb7897<br /><br />Code review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36153">issues.joomla.org/tracker/joomla-cms/36153</a>.</sub>

**Comment by khu5h1** [comment]
I have tested this item :white_check_mark: successfully on 1c8506a53e4a109a2fe444ec8a2d4c5c54bb7897<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36153">issues.joomla.org/tracker/joomla-cms/36153</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36153">issues.joomla.org/tracker/joomla-cms/36153</a>.</sub>

**Comment by pritam825** [comment]
I have tested this item :white_check_mark: successfully on 1c8506a53e4a109a2fe444ec8a2d4c5c54bb7897<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36153">issues.joomla.org/tracker/joomla-cms/36153</a>.</sub>

**Comment by Quy** [comment]
Thanks

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
