### PR TITLE
[4.3] spelling atributes/attributes

### PR DESCRIPTION
**Pull request by brianteeman**
Simple speling mistake created by me

code review

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 7829413b608473f26e7c2f6a1d4888bc0a3ab89a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41076">issues.joomla.org/tracker/joomla-cms/41076</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 7829413b608473f26e7c2f6a1d4888bc0a3ab89a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41076">issues.joomla.org/tracker/joomla-cms/41076</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41076">issues.joomla.org/tracker/joomla-cms/41076</a>.</sub>

**Comment by obuisard** [comment]
Thank you Brian @brianteeman.

**Pull request merged**
