### PR TITLE
Show the position where the error happens in the trace

### PR DESCRIPTION
**Pull request by laoneo**
### Summary of Changes
When debug mode is activated and an exception is thrown, then the stack trace is shown. This trace includes the call stack except the information where the actual error happened. This PR includes that information

### Testing Instructions
- Set debugging to yes in the global configuration 
image
- In the file /administrator/components/com_content/content.php after line 8 add the code `throw new Exception();`
- In the back end open Content -> Articles

### Expected result
A stack trace is shown where the last line is
> /administrator/components/com_content/content.php:9

### Actual result
A stack trace is shown where the last line is
> /libraries/cms/component/helper.php:399

### CODE REVIEW

**Comment by mbabker** [comment]
This PR is doing nothing but adding a commented line of code?

**Comment by laoneo** [comment]
Fixed.

**Review by yvesh — APPROVED** [review]

**Comment by N6REJ** [comment]
test passed... 
image

**Comment by laoneo** [comment]
@N6REJ can you please mark it as success in the issue tracker. Thanks.

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on cf00f07dfb847543103a8a68b23e4beaee0536b0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14169">issues.joomla.org/tracker/joomla-cms/14169</a>.</sub>

**Comment by yvesh** [comment]
I have tested this item :white_check_mark: successfully on cf00f07dfb847543103a8a68b23e4beaee0536b0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14169">issues.joomla.org/tracker/joomla-cms/14169</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC as there are 2 successfully Tests?

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14169">issues.joomla.org/tracker/joomla-cms/14169</a>.</sub>

**Pull request merged**
