### PR TITLE
[Optimize] Add config for admin choose way for generate image of thumbnail for JImage class

### PR DESCRIPTION
**Pull request by ThongTran-Dev**
Allow admin can choose which way they want when generate thumbnail image of `JImage` class.
- Best quality but more speed.
- Fastest speed but not good quality (pixelated bug).

### CODE REVIEW

**Comment by Bakual** [comment]
Imho, that should be an extension specific setting and not a global one.

**Comment by infograf768** [comment]
If considered, please alpha order new string
` +COM_CONFIG_THUMBNAIL_SETTINGS="Image Thumbnail Settings" `

**Comment by wilsonge** [comment]
I agree with @Bakual at best this should be a constructor parameter (add a `$options` array which makes this easier). Then it's down to the extension to initialise as appropriate. It's definitely NOT something to be set in the application

To be honest I'm not even sure if it should be a function specific parameter (you might want to resize an image in good quality at large resolutions and low quality at smaller, for example)

**Comment by Bakual** [comment]
Closing this PR as it will not be merged in this form.
Feel free to propose something in the class itself which can be used by the extensions.

**Comment by javigomez** [comment]
I'm not sure witch is the right solution but I have tested this and there is an error in the way JImage generates png thumbnails, ending in pixelated results. And with Thong's way the thumb looks good.

Linking here Roberto's comment https://github.com/redCOMPONENT-COM/redCORE/pull/548#issuecomment-139472890

**Comment by wilsonge** [comment]
I agree that this needs fixing. But setting it at the `JFactory` level is 100% wrong. As I said I *think* it should be at the function level - but if people want it at the class level like i said I could understand it.

**Pull request closed without merging**
