### PR TITLE
[4.0] TinyMCE: Fix full screen design editor view in articles

### PR DESCRIPTION
**Pull request by Arpit-24**
Pull Request for Issue #24237  .

### Summary of Changes

Hides the header and options panel in full screen mode triggered by using view > fullscreen

### Testing Instructions

1) Open an article for editing from the administrator panel.
2) In the editor use view > fullscreen

### Expected result

Full screen editor with no overlap between elements in all screen resolutions

### Actual result

Overlapping options panel with the editor element.

### Documentation Changes Required

None

### CODE REVIEW

**Comment by Arpit-24** [comment]
Screenshot (1228)

Current result after change.

**Comment by brianteeman** [comment]
Please update the title of this PR and your others to ensure they are meaningful

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on c64bf2d81e6d17bc0a3aabf84a07efaeee3e99d7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24334">issues.joomla.org/tracker/joomla-cms/24334</a>.</sub>

**Comment by bembelimen** [comment]
Please see https://github.com/joomla/joomla-cms/pull/24110 when updating any TinyMce stuff, they will probably become invalid in a few days...

**Comment by sanderpotjer** [comment]
I have tested this item :red_circle: unsuccessfully on c64bf2d81e6d17bc0a3aabf84a07efaeee3e99d7<br /><br />With the latest 4.0-dev branch including the TinyMCE 5 this no longer seems to be an issue. Before applying this patch the screen already looks good without the toolbar being visible. 

Screenshot 2019-05-05 at 10 20 20

My suggestion is to close this PR.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24334">issues.joomla.org/tracker/joomla-cms/24334</a>.</sub>

**Comment by ghost** [comment]
Closed as suggested above.

**Pull request closed without merging**
