### PR TITLE
Removed Complete & from open site and open admin button

### PR DESCRIPTION
**Pull request by khu5h1**
Pull Request for Issue #18833 (part).

### Summary of Changes

Removed `Complete &` from the `open site` and `open admin` buttons in all languages.

### Testing Instructions
Install Joomla and after its successful installation, the Congratulations page will have `Open site` and `Open admin` buttons.

### Actual result BEFORE applying this Pull Request

`Complete &` appeared on the installation completion page.

### Expected result AFTER applying this Pull Request

`Complete &` is removed from the installation completion page.

### Documentation Changes Required
No

### CODE REVIEW

**Comment by richard67** [comment]
It needs to adapt system tests to the changed button texts, see the log here: https://ci.joomla.org/joomla/joomla-cms/48299/1/22

**Comment by richard67** [comment]
Question: Do you really speak all these languages for which you have changed the text? Or have you just removed the first 2 words everywhere without understanding what they mean?

I would expect that this PR changes only the English (GB) texts and leaves the translations to the translation teams.

**Comment by khu5h1** [comment]
Hey @richard67, Thank you for your feedback. I am trying to figure out a way to solve the failing test. Apart from this, I have used Google Translator and have translated all the languages. Then, accordingly, I have committed the changes.

**Comment by khu5h1** [comment]
By the way, May you please help me with some code pointers/references to solve the failing tests.

**Comment by richard67** [comment]
@khu5h1 Am not familiar with these tests either but will try to find someone who is.

**Comment by khu5h1** [comment]
Sure @richard67 , I will try to figure out the solution to the failing tests.

**Comment by Kubik-Rubik** [comment]
@khu5h1 Thanks for the PR! Please do not modify language files of languages you are not speaking fluently (best practice: only update the main language file **en-GB**). We have dedicated translation teams with native speakers who will take care of it!

Your change will let this test to fail:

grafik

You need to update this test as well to pass the check.

**Comment by dgrammatiko** [comment]
The changes should be reflected here: https://github.com/joomla-projects/joomla-browser/blob/95e099d99044ba9915d0d99b31028b723e2fc7e4/src/JoomlaBrowser.php#L306

**Comment by wojsmol** [comment]
@khu5h1 As a member of Polish translation team I support many request above to revert changes to languages other then en-GB.

**Comment by wojsmol** [comment]
@khu5h1 If you revert changes to languages other then English then I will make PR to fix tests.

**Comment by wojsmol** [comment]
Related PR created https://github.com/joomla-projects/joomla-browser/pull/223

**Comment by wojsmol** [comment]
I have tested this item :white_check_mark: successfully on 213ac48099544a230cd021b48553d03b958518cf<br /><br />on code review <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35988">issues.joomla.org/tracker/joomla-cms/35988</a>.</sub>

**Comment by manav014** [comment]
I have tested this item :white_check_mark: successfully on 213ac48099544a230cd021b48553d03b958518cf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35988">issues.joomla.org/tracker/joomla-cms/35988</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35988">issues.joomla.org/tracker/joomla-cms/35988</a>.</sub>

**Comment by richard67** [comment]
Unfortunately this PR solves the mentioned issue only partly. It removes the "Complete &" but still leaves 2 buttons. So it seems we have to leave that issue open.

**Comment by khu5h1** [comment]
Yeah, we shall keep that issue open and I will create a separate PR for the remaining changes.

**Comment by richard67** [comment]
@khu5h1 Then it would be good if you could change the text at the top of your PR's description to show that it solves the issue only party, e.g. by changing from "Pull Request for Issue #18833 ." to "Pull Request for Issue #18833 (part).". Thanks in advance.

**Comment by brianteeman** [comment]
https://github.com/joomla/joomla-cms/issues/18833#issuecomment-346697153

**Comment by richard67** [comment]
> [#18833 (comment)](https://github.com/joomla/joomla-cms/issues/18833#issuecomment-346697153)

@khu5h1 Could you check this comment in the issue? I think it is right, the naming we use is "Administrator" and not "Admin".

@wojsmol If that has been done, could you adjust your PR for the tests?

Thanks in advance both.

I know, it was wrong all the time before, but it would make sense to fix it here and not need another PR for that which again will have to change the tests in the other repository, too.

**Comment by richard67** [comment]
Back to pending due to requested changes.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35988">issues.joomla.org/tracker/joomla-cms/35988</a>.</sub>

**Comment by khu5h1** [comment]
I also think that it is good to change `admin` to `Administrator`. I have committed the requested changes.:)

**Comment by wojsmol** [comment]
I have tested this item :white_check_mark: successfully on d0a87b3d09fab62e915b128a482e58bc4fa99ec6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35988">issues.joomla.org/tracker/joomla-cms/35988</a>.</sub>

**Comment by wojsmol** [comment]
@richard67 PR in the other repo updated as requested.

**Comment by richard67** [comment]
@wojsmol Thanks.

**Comment by manav014** [comment]
I have tested this item :white_check_mark: successfully on d0a87b3d09fab62e915b128a482e58bc4fa99ec6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35988">issues.joomla.org/tracker/joomla-cms/35988</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35988">issues.joomla.org/tracker/joomla-cms/35988</a>.</sub>

**Comment by khu5h1** [comment]
Thank you Everyone for your comments and feedback. :)

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
