### PR TITLE
Mod languages performance improvements

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Description

Mod_languages (the module with the language flags), is one of the modules that can be in all pages that has slower performances (if 3 or more languages > 10ms).

So, this PR makes some code changes to get some small performance improvements.

No behaviour is changed.
##### Performance Tests

| Published Languages | Before PR | After PR |
| :-- | :-: | :-: |
| 1 | ~5.5 ms | ~3.7 ms |
| 2 | ~7.5 ms | ~4.0 ms |
| 3 | ~10 ms | ~4.2 ms |
| 4 | ~12 ms | ~4.4 ms |
| 5 | ~15 ms | ~5.3 ms |

Note: Tests were made with Joomla Debug Console in PHP 5.6 - no caching
#### How to test
1. Fresh Joomla install with multilanguage (install 5 or more languages)
2. Apply this patch.
3. Verify all the flags in mod_languages are working fine

To check the performance improvements, turn on Joomla debugging and check the `Application: afterRenderModule mod_languages (xxxxxx)` execution time, before and after the PR
#### Observations

Suggestions, code reviews and improvements are welcome.

### CODE REVIEW

**Comment by wojsmol** [comment]
@andrepereiradasilva  see https://github.com/andrepereiradasilva/joomla-cms/pull/1

**Comment by andrepereiradasilva** [comment]
thanks @wojsmol

**Comment by wojsmol** [comment]
@andrepereiradasilva see https://github.com/andrepereiradasilva/joomla-cms/pull/2

**Comment by andrepereiradasilva** [comment]
thanks again

**Comment by infograf768** [comment]
This works fine.
Could you also correct the remainings pre-existing CS?
`;?>` to `; ?>`

**Comment by andrepereiradasilva** [comment]
Done.

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 2b4938e29cd115bfdb299074527b1ca91098f26d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8869">issues.joomla.org/joomla-cms/8869</a>.</sub>

**Comment by dgt41** [comment]
I have tested this item :white_check_mark: successfully on 2b4938e29cd115bfdb299074527b1ca91098f26d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8869">issues.joomla.org/joomla-cms/8869</a>.</sub>

**Comment by dgt41** [comment]
@joomla-bot 💤

**Comment by wilsonge** [comment]
Merged with https://github.com/joomla/joomla-cms/commit/1bf94b9f0d2af6727a08be5ec7a42d26d4f97837

**Pull request closed without merging**
