### PR TITLE
[3.9]Update privacyconsent.php to properly 'namespace' the consents state

### PR DESCRIPTION
**Pull request by joeforjoomla**
Pull Request for Issue https://github.com/joomla-projects/privacy-framework/issues/242.

### Summary of Changes
Change the 'where' clause to properly apply remind, expiration and user consented status by namespacing consents based on the 'subject' field.

Refer to issue https://github.com/joomla-projects/privacy-framework/issues/242

### Testing Instructions
Test that the privacyconsent plugin only manages the state of consents of the core PLG_SYSTEM_PRIVACYCONSENT_SUBJECT

### Expected result
Consents stored in the #__privacy_consents table by third-party extensions must not be affected nor affect the working mode of the privacyconsent plugin.

### CODE REVIEW

**Comment by sanderpotjer** [comment]
I have tested this item :white_check_mark: successfully on c4603717e2af9377acc9386b4d87990b9358b7cc<br /><br />I could argue that the subject should also be taken into account for the onUserAfterDelete function if you really want "Consents stored in the #__privacy_consents table by third-party extensions must not be affected nor affect the working mode of the privacyconsent plugin."

But at the other hand it is the only way to make sure that all user related consents are deleted upon deleting a user, also if 3rd party extensions "Forget" to implement the onUserAfterDelete.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22047">issues.joomla.org/tracker/joomla-cms/22047</a>.</sub>

**Comment by sanderpotjer** [comment]
Another thing to consider for this PR: in this way we force any other 3rd party implementation to add their own remindExpiringConsents function. It will require some work, but it might be nice to make that more optional. So adding consents without the requirement to have all functions in your own plugin.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22047">issues.joomla.org/tracker/joomla-cms/22047</a>.</sub>

**Comment by joeforjoomla** [comment]
I agree @sanderpotjer but i think it's better leave it as now for the onUserAfterDelete  function, it's perfectly acceptable to delete even third-party consents upon a user deletion.

For the other thing, it's up to third-party extensions to choose if the consents must have an expiration time or not. Not in all cases this is required and could be done even in a manual way.

**Comment by mbabker** [comment]
> Another thing to consider for this PR: in this way we force any other 3rd party implementation to add their own remindExpiringConsents function. It will require some work, but it might be nice to make that more optional.

The code in the core plugins is really geared toward the core features/workflow, some of it may work for third party but not always.

With that said, some work started on a core job/cron type system since we've been adding a lot of plugins lately that have a cron-like schedule (either hardcoded or configurable).  I'd say that with that job system in place, a lot of the logic for the remind/invalidate stuff could move into a component helper class with parameters for key values that could more easily be re-used.  Until we get there though, since plugins aren't really part of the API, we're fine with this as is.

**Comment by alikon** [comment]
if  someone is interested in `core job/cron type system`
https://github.com/joomla-projects/privacy-framework/pull/133
https://github.com/joomla-projects/privacy-framework/pull/217

**Comment by joeforjoomla** [comment]
Thanks guys,

**Pull request merged**
