### PR TITLE
[4.0] Remove some eslint comments

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # .

### Summary of Changes

- Removes `// eslint-disable-next-line max-len` comments 

### Testing Instructions

Just review

### CODE REVIEW

**Comment by brianteeman** [comment]
If drone is successful then it can be safely merged

**Comment by richard67** [comment]
> If drone is successful then it can be safely merged

Due to the code freeze I'd prefer to leave that to @wilsonge

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on a0992c8a07bdfcf7f38c2ce394f39000aa4c8a3a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34983">issues.joomla.org/tracker/joomla-cms/34983</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on a0992c8a07bdfcf7f38c2ce394f39000aa4c8a3a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34983">issues.joomla.org/tracker/joomla-cms/34983</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34983">issues.joomla.org/tracker/joomla-cms/34983</a>.</sub>

**Comment by richard67** [comment]
Thanks!

**Pull request merged**
