### PR TITLE
Use the curl default option for get/post/put

### PR DESCRIPTION
**Pull request by bembelimen**
If you use post/put method curl/PHP offers own options. Some REST-APIs require e.g. CURLOPT_POST instead of CURLOPT_CUSTOMREQUEST = 'POST'. So let's stick to the docs.

see: [http://php.net/manual/en/function.curl-setopt.php]

### CODE REVIEW

**Comment by chmst** [comment]
@test - good find, bembelimen!

**Comment by jacxx** [comment]
I have tested it and it is good, thanks bembelimen

Jacxx

**Comment by zero-24** [comment]
Based on testing by @jacxx and @chmst i move this here to RTC. Thanks @bembelimen <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6312">issues.joomla.org/joomla-cms/6312</a>.</sub>

**Comment by phproberto** [comment]
Merged. Thanks!

**Comment by PhilETaylor** [comment]
Can you provide information on which ```Some REST-APIs require``` this to be the way it has been proposed?

**Comment by bembelimen** [comment]
Hello,

I had problems with this api: https://cloudconvert.com/apiconsole

**Pull request closed without merging**
