### PR TITLE
[4.0] Correct small typo

### PR DESCRIPTION
**Pull request by astridx**
### Summary of Changes
Correct small typo

### Testing Instructions
Code review

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 48b6bf8479f923d5a32b0022c3581cb8d7a253cf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27642">issues.joomla.org/tracker/joomla-cms/27642</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 48b6bf8479f923d5a32b0022c3581cb8d7a253cf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27642">issues.joomla.org/tracker/joomla-cms/27642</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27642">issues.joomla.org/tracker/joomla-cms/27642</a>.</sub>

**Comment by Quy** [comment]
Thanks!

**Pull request merged**
