### PR TITLE
revert #30778 part2

### PR DESCRIPTION
**Pull request by N6REJ**
Pull Request for Issue # .

### Summary of Changes

added the ignored/changed files by #30778 

### Testing Instructions

code review

### CODE REVIEW

**Comment by brianteeman** [comment]
There are no changes here

**Comment by N6REJ** [comment]
*bear is soooo confused now*

**Comment by brianteeman** [comment]
Your local branches are messed up

**Comment by N6REJ** [comment]
> Your local branches are messed up

talking to @SharkyKZ about it in bug squad because It doesn't seem so from what "I'M" seeing.  I'm not touching anything else until I'm advised what to do.
After doing a wipe and fresh "git reset --hard it does infact show those files missing/added to staging which afaik means it's not MY install thats nerfed.
please check staging yourself for
before ( current staging )
image
my replacing
image

**Comment by brianteeman** [comment]
You can see that staging does not contain the image file you reference
https://github.com/joomla/joomla-cms/tree/staging/images

**Comment by N6REJ** [comment]
> You can see that staging does not contain the image file you reference
> https://github.com/joomla/joomla-cms/tree/staging/images

UGH!.. I just did a full wipe and reclone

**Pull request closed without merging**
