### PR TITLE
Fix incorrect calendar paths

### PR DESCRIPTION
**Pull request by saharin88**
Pull Request for Issue https://github.com/joomla/joomla-cms/pull/15441#issuecomment-297091667.

### Summary of Changes
Fixes incorrect paths for resources

### CODE REVIEW

**Comment by wilsonge** [comment]
I've fixed the CSS path here and added the link to the correct issue :)

**Comment by dgt41** [comment]
I have tested this item :white_check_mark: successfully on 318cec9650ec5fb974f188c0e3cc5bd7525078a2<br /><br />To test replace in isis/index.php
```php
defined('_JEXEC') or die;
```
with

```php
defined('_JEXEC') or die;
JHtml::_('behavior.calendar');
```

and check the page source for the css and the scripts files
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15546">issues.joomla.org/tracker/joomla-cms/15546</a>.</sub>

**Comment by wilsonge** [comment]
@brianteeman are you able to test this please?

**Comment by brianteeman** [comment]
**And this is why merging a pr without any tests was a bad idea!!!!**

Using the test instructions from @dgt41 this PR works as intended

**Comment by gwsdesk** [comment]
I confirm this as well. This was also posted to me by @Markus Bopp of Crosstec just a few ago.This works with the method as described by  @dgt41

**Pull request merged**
