### PR TITLE
[4.0] Align icon and text in search button

### PR DESCRIPTION
**Pull request by drmenzelit**
Pull Request for Issue # .

### Summary of Changes
Added display: flex for icon and text inside search button, see comment 
https://github.com/joomla/joomla-cms/pull/31827#issuecomment-753423889

### Testing Instructions
Create a smart search module on the sidebar. 
Run npm

### Actual result BEFORE applying this Pull Request
The search button is too big

image

### Expected result AFTER applying this Pull Request

image

### CODE REVIEW

**Comment by adj9** [comment]
I have not tested this item.<br /><br />I tried installing PR to see the effect. The first installation I got error 500 when accessing /administator.
In the second installation logging into the backend I cannot log in. The _users table in the db is empty.

Only I have these problems with the test of Joomla! with the Patch?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31839">issues.joomla.org/tracker/joomla-cms/31839</a>.</sub>

**Comment by drmenzelit** [comment]
@adj9 how are you installing the patch? Do you have problems with other PRs? This PR changes only a scss file...

**Comment by adj9** [comment]
I did an installation of Joomla! for npm on a website (not local). Checking the db I have the empty users table. 

It seems strange to me too, the db has nothing to do with the patch!

Before installing the package I emptied the db.

**Comment by drmenzelit** [comment]
You only need to apply the PR and run npm run build:css to process the changes done in the scss file of the Cassiopeia template.

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on 968f2ca1f2adf2936d334725e478b31ea9fe61f1<br /><br />Works as described.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31839">issues.joomla.org/tracker/joomla-cms/31839</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 968f2ca1f2adf2936d334725e478b31ea9fe61f1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31839">issues.joomla.org/tracker/joomla-cms/31839</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31839">issues.joomla.org/tracker/joomla-cms/31839</a>.</sub>

**Comment by infograf768** [comment]
Thanks!

**Pull request merged**
