### PR TITLE
[4.1] Apply badge markup

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
Add badge markup to be consistent with plugins/modules.

### Testing Instructions
Go to System > Mail Templates
Edit a template.
See badge.
Edit a module.
See badge.
Edit a plugin.
See badge.

### Actual result BEFORE applying this Pull Request
mail-template

### Expected result AFTER applying this Pull Request
mail-template-badge

### CODE REVIEW

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on 601cdcd74c4be6d2dd78b5164e12d8e71307a7dc<br /><br />Tested successfully in 4.1.1-dev of 10 March using Wampserver 3.2.7 and PHP 8.0.15<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37237">issues.joomla.org/tracker/joomla-cms/37237</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 601cdcd74c4be6d2dd78b5164e12d8e71307a7dc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37237">issues.joomla.org/tracker/joomla-cms/37237</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37237">issues.joomla.org/tracker/joomla-cms/37237</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
