### PR TITLE
UX Isis: Improve sidebar and style fixes

### PR DESCRIPTION
**Pull request by 810**
- Added height to 100% (sidebar)
- Adding background to sidebar
- Fixed logo spacing
- Form style fixed
#### Sidebar

sidebarheight
#### Components Options

sidebar
#### Global Settings

global
#### How to test

Apply patch. 
- See that the logo on the right is correct height.
- See that yes/no options are the same width as dropdowns on the config, also check other items on settings.
- See the improvements on Global and Options.

### CODE REVIEW

**Comment by bertmert** [comment]
I see some problems. See images before/after, 1024px width. (I know that there are problems before patch, too. Between 869 and 1024px. But now there are more somehow). 
1024px-old

AFTER:
1024px-new

**Comment by designbengel** [comment]
Hello!
The Sidebar is sticking to the left side in safari browser. screen shot 2015-03-16 at 05 57 48
On iPhone 6 View it doesn´t take the whole width
screen shot 2015-03-16 at 06 00 01<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6446">issues.joomla.org/joomla-cms/6446</a>.</sub>

**Comment by 810** [comment]
Ok i updated the code, at least the fix is working for big widths <1400. For smaller there are to many issues with it, so i will leave it as it is.

**Comment by dam-man** [comment]
screen shot 2015-04-10 at 08 49 31
There is still a little piece not OK. See my attachment. This is on smaller screen only. When using it on  a normal resolution it is OK.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6446">issues.joomla.org/joomla-cms/6446</a>.</sub>

**Comment by designbengel** [comment]
@810 @zero-24 any new fixes for this? <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6446">issues.joomla.org/joomla-cms/6446</a>.</sub>

**Comment by 810** [comment]
@roland-d I have updated the code, you can check if you still got merge issues.

@test
This is only for >1300px screens. For other sizes, the easiest way is start new admin template, there are to many issue's

**Comment by designbengel** [comment]
i don´t agree with that, because one template should be able to serve most screensizes - that´s why it´s based on bootstrap, isn´t it? <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6446">issues.joomla.org/joomla-cms/6446</a>.</sub>

**Comment by 810** [comment]
The issue are the language strings. All kind of stings are not equal sizes, so it doesn't fit for all languages.

**Comment by designbengel** [comment]
i checked your patch on Mac Os X (Safari, Chrome) and iPhone6 right now successful - the issue @dam-man posted is just in emulator view in chrome on my side. 


<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6446">issues.joomla.org/joomla-cms/6446</a>.</sub>

**Comment by zero-24** [comment]
RTC based on the lastet tests<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6446">issues.joomla.org/joomla-cms/6446</a>.</sub>

**Comment by roland-d** [comment]
I am removing the RTC label for now because the sidebar is not full length on the Articles/Categories/Plugins list. Yes, it shows till the bottom of the screen until I scroll down, then the bar stops. This is not the case on the menu list or contacts for example. After these views I stoppeed looking where else it might be different.

Can you check?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6446">issues.joomla.org/joomla-cms/6446</a>.</sub>

**Comment by brianteeman** [comment]
It has been 5 months since @rolandd commented above. I am setting this to be Information required and it will be closed within 4 weeks if not updated<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6446">issues.joomla.org/joomla-cms/6446</a>.</sub>

**Comment by brianteeman** [comment]
Closed as stated above<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6446">issues.joomla.org/joomla-cms/6446</a>.</sub>

**Pull request closed without merging**
