### PR TITLE
[4.1] Fix RTL installation

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/37285 .

### Summary of Changes
- Use the right path for the css

### Documentation Changes Required

No, this is a bug

### CODE REVIEW

**Comment by richard67** [comment]
By review I'd say this PR is correct because a few lines below, in line 23, we already use the right path for the JS file.

**Comment by brianteeman** [comment]
> By review I'd say this PR is correct because a few lines below, in line 23, we already use the right path for the JS file.

thats why I suggested it ;)

**Comment by richard67** [comment]
What I still don't understand is why I could not reproduce the issue here. But I have tested that with this PR the installation form still looks ok here with LTR and RTL.

**Comment by dgrammatiko** [comment]
@richard67 @brianteeman on my local server with either paths (just `template.css` or `[installation/template/css/template.css` I get the correct result but lets use the stricter one (the line is missing the options array for `'relative' => true` and I'm guessing the logic is a bit flaky on windows[?])
Unless if adding `->registerAndUseStyle('template.installation', 'template' . ($this->direction === 'rtl' ? '-rtl' : '') . '.css', ['version' => 'auto', 'relative' => true],[])` is working, then this is a better solution

Screenshot 2022-03-16 at 13 41 08

**Comment by dgrammatiko** [comment]
@brianteeman can you please confirm that the latest commit works as expected on your env?

**Comment by brianteeman** [comment]
give me 5

**Comment by dgrammatiko** [comment]
BTW there's a PHP notice in the last page
Screenshot 2022-03-16 at 14 04 44


The solution is adding 
```
						<?php if (empty($element)) : ?>
							<?php continue; ?>
						<?php endif; ?>
```

after https://github.com/joomla/joomla-cms/blob/8f862d6ee33b00df6781bb9442366599bb428c3a/installation/tmpl/remove/default.php#L247

**Comment by brianteeman** [comment]
I have tested this item :red_circle: unsuccessfully on 1e6b461b0c909724b0c207638f497c0e39ba6979<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37292">issues.joomla.org/tracker/joomla-cms/37292</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 1e6b461b0c909724b0c207638f497c0e39ba6979<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37292">issues.joomla.org/tracker/joomla-cms/37292</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 245c81f5b224d5eeb7e81919afc5c8ed72faf000<br /><br />Issue can be reproduced by creating a file "template.css" in the Joomla root. This can be an empty file.

Without the PR, installation form is not styled.

With the PR it is.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37292">issues.joomla.org/tracker/joomla-cms/37292</a>.</sub>

**Comment by richard67** [comment]
@brianteeman For some reason your test result had an old commit reference. Not your fault, I think, but maybe a caching issue of the tracker. I've restored your test result in the tracker so it is properly counted.

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37292">issues.joomla.org/tracker/joomla-cms/37292</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37292">issues.joomla.org/tracker/joomla-cms/37292</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
