### PR TITLE
Code Style Fix for administrator/components/com_admin

### PR DESCRIPTION
**Pull request by photodude**
Pull Request for Code Style issue. No blank line found after control structure / Please consider an empty line before the return statement;
#### Summary of Changes

[Automatically Fixed with the PHPCS 2 fixers](https://github.com/joomla/coding-standards/pull/109)
#### Testing Instructions

Merge by code review

### CODE REVIEW

**Comment by wojsmol** [comment]
I have tested this item :white_check_mark: successfully on 686de8dcbb70da37a0b2eafaa1f239bd2fe9b204<br /><br />code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11011">issues.joomla.org/joomla-cms/11011</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 686de8dcbb70da37a0b2eafaa1f239bd2fe9b204<br /><br />on code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11011">issues.joomla.org/joomla-cms/11011</a>.</sub>

**Comment by zero-24** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11011">issues.joomla.org/joomla-cms/11011</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by photodude** [comment]
Thanks everyone!

**Pull request merged**
