### PR TITLE
[4.0] Composer packages update

### PR DESCRIPTION
**Pull request by brianteeman**
Package operations: 0 installs, 48 updates, 0 removals
  - Updating symfony/polyfill-php80 (v1.18.1 => v1.20.0) 
  - Updating symfony/polyfill-mbstring (v1.18.1 => v1.20.0) 
  - Updating symfony/polyfill-intl-normalizer (v1.18.1 => v1.20.0) 
  - Updating symfony/polyfill-intl-grapheme (v1.18.1 => v1.20.0) 
  - Updating symfony/polyfill-ctype (v1.18.1 => v1.20.0) 
  - Updating symfony/string (v5.1.5 => v5.1.8) 
  - Updating symfony/polyfill-php73 (v1.18.1 => v1.20.0) 
  - Updating symfony/console (v5.1.5 => v5.1.8) 
  - Updating joomla/console (2.0.0-beta => 2.0.0-beta2) 
  - Updating phpmailer/phpmailer (v6.1.7 => v6.1.8) 
  - Updating symfony/var-dumper (v5.1.5 => v5.1.8) 
  - Updating symfony/polyfill-php72 (v1.18.1 => v1.20.0) 
  - Updating symfony/error-handler (v5.1.5 => v5.1.8) 
  - Updating symfony/options-resolver (v5.1.5 => v5.1.8) 
  - Updating symfony/ldap (v5.1.5 => v5.1.8) 
  - Updating symfony/web-link (v5.1.5 => v5.1.8) 
  - Updating symfony/yaml (v5.1.5 => v5.1.8) 
  - Updating symfony/stopwatch (v5.1.5 => v5.1.8) 
  - Updating symfony/process (v5.1.5 => v5.1.8) 
  - Removing symfony/polyfill-php70 (v1.18.1)
  - Installing symfony/polyfill-php70 (v1.20.0)
  - Updating symfony/finder (v5.1.5 => v5.1.8) 
  - Updating symfony/filesystem (v5.1.5 => v5.1.8) 
  - Updating symfony/event-dispatcher (v5.1.5 => v5.1.8) 
  - Updating php-cs-fixer/diff (v1.3.0 => v1.3.1) 
  - Updating doctrine/annotations (1.10.4 => 1.11.1) 
  - Updating composer/xdebug-handler (1.4.3 => 1.4.4) 
  - Updating composer/semver (1.7.0 => 3.2.2) 
  - Updating friendsofphp/php-cs-fixer (v2.16.4 => v2.16.7) 
  - Updating squizlabs/php_codesniffer (3.5.6 => 3.5.8) 
  - Updating symfony/css-selector (v5.1.5 => v5.1.8) 
  - Updating guzzlehttp/psr7 (1.6.1 => 1.7.0) 
  - Updating phpspec/prophecy (1.11.1 => 1.12.1) 
  - Updating codeception/phpunit-wrapper (8.1.2 => 8.1.3) 
  - Updating codeception/lib-asserts (1.13.1 => 1.13.2) 
  - Updating codeception/codeception (4.1.7 => 4.1.9) 
  - Updating codeception/module-asserts (1.3.0 => 1.3.1) 
  - Updating codeception/module-db (1.0.1 => 1.0.2) 
  - Updating codeception/module-rest (1.2.3 => 1.2.5) 
  - Updating php-webdriver/webdriver (1.8.2 => 1.8.3) 
  - Updating codeception/module-webdriver (1.1.1 => 1.1.3) 
  - Updating symfony/dom-crawler (v5.1.5 => v5.1.8) 
  - Updating symfony/browser-kit (v5.1.5 => v5.1.8) 
  - Updating codeception/lib-innerbrowser (1.3.2 => 1.3.4) 
  - Updating guzzlehttp/promises (v1.3.1 => 1.4.0) 
  - Updating guzzlehttp/guzzle (7.0.1 => 7.2.0) 
  - Updating codeception/module-phpbrowser (1.0.1 => 1.0.2) 
  - Updating symfony/polyfill-iconv (v1.18.1 => v1.20.0) 
  - Updating fgrosse/phpasn1 (v2.1.1 => v2.2.0)

### CODE REVIEW

**Comment by richard67** [comment]
Composer failing here in Drone due to unrelated reason caused by the testing environment problem, see issue #31281 .

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 2eb78477d628925e95e78f1197a7b2620d8cb70c<br /><br />Applied the patch on a clean 4.0dev branch and run composer install. Result:
- The packages to be updated were updated, others loaded from cache.
- No new warnings or error messages.
- After npm ci and new installation: The CMS works as well as before.

Code-review: The lock file contains no unresolved dependencies.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31279">issues.joomla.org/tracker/joomla-cms/31279</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 2eb78477d628925e95e78f1197a7b2620d8cb70c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31279">issues.joomla.org/tracker/joomla-cms/31279</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31279">issues.joomla.org/tracker/joomla-cms/31279</a>.</sub>

**Comment by richard67** [comment]
I've restored previous test results because only change after tests was a clean branch update.

**Comment by HLeithner** [comment]
new phpcs detects new error not sure if it's an error in phpcs or in our code base or in our configuration...

**Comment by wilsonge** [comment]
@brianteeman can you fix the PHPCS issues reported please - I understand this PR doesn't directly cause them - but clearly somehow they're coming in from the composer update and I need to be sure that the codeception updates run through cleanly further on in the drone pipeline

**Comment by brianteeman** [comment]
ok will do that for you now as you asked nicely :)

**Comment by brianteeman** [comment]
@wilsonge all done - they were all valid code style issues. Mainly from one PR

**Comment by Quy** [comment]
One more fix please. https://ci.joomla.org/joomla/joomla-cms/37300/1/6

**Comment by brianteeman** [comment]
done

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 1a60feb222c6084a7432c67fb17211517aac86e9<br /><br />Tested again.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31279">issues.joomla.org/tracker/joomla-cms/31279</a>.</sub>

**Comment by wilsonge** [comment]
Thankyou!

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
