### PR TITLE
[4.0] Enabling SCSS linting

### PR DESCRIPTION
**Pull request by Hackwar**
For some reason, Hound doesn't lint our SCSS. This is an attempt to enable that. Lets see if this blows up spectacularly now. 😄

### CODE REVIEW

**Comment by C-Lodder** [comment]
Don't forget to add the exclusions

**Comment by Hackwar** [comment]
I actually don't want any exclusions. Why should we exclude anything? In any case, we currently don't seem to have any linting at all...

**Comment by C-Lodder** [comment]
You should not be linting anything in the `node_modules` directory. So this needs to be excluded.

**Comment by Hackwar** [comment]
As the node_modules folder is not part of our repo and the config explicitly states scss files, we should be fine.

**Comment by C-Lodder** [comment]
@Hackwar Not everything is done on Github. There are people who do their linting prior to submitting a PR

**Comment by gylaz** [comment]
Keep in mind that Hound will only review/monitor the changes in the pull request.

**Comment by C-Lodder** [comment]
@gylaz True. I'm thinking of those who do local linting :)

**Comment by Hackwar** [comment]
Closing this one, since my assumption seems to have been wrong. Hound does indeed only lint those files which were changed and since we didn't change all files lately, that would explain that... Anyway, changing this here would be an unnecessary change, thus closing.

**Comment by ciar4n** [comment]
> Hound does indeed only lint those files which were changed and since we didn't change all files lately, that would explain that.

All template scss changed between https://github.com/joomla/joomla-cms/pull/26793 and https://github.com/joomla/joomla-cms/pull/26794

**Pull request closed without merging**
