### PR TITLE
Removed redundant 'flash uploader' CSS

### PR DESCRIPTION
**Pull request by ciar4n**
Pull Request for Issue #22430 .

### Summary of Changes
The 'Flash-based file uploader' was removed in 3.1 due to an XSS vulnerability. This PR removes the related CSS which appears to have been missed.

### Testing Instructions
Apply PR and ensure media field modal is displayed correctly

### CODE REVIEW

**Comment by Quy** [comment]
Delete here and search for `.upload-queue` to see related files to update.

https://github.com/joomla/joomla-cms/blob/49183dfb5e84f3451a73d0be95defc3201d95c32/administrator/templates/isis/less/blocks/_custom.less#L103-L111

**Comment by ciar4n** [comment]
Thank you @Quy. Removed.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 30a4202b9cdbbb4a3a36eea132a11d5ab49d0fb9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22453">issues.joomla.org/tracker/joomla-cms/22453</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 30a4202b9cdbbb4a3a36eea132a11d5ab49d0fb9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22453">issues.joomla.org/tracker/joomla-cms/22453</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22453">issues.joomla.org/tracker/joomla-cms/22453</a>.</sub>

**Pull request merged**
