### PR TITLE
[4.0] oops png

### PR DESCRIPTION
**Pull request by brianteeman**
png was accidentally placed in the doc and the image filetypes. this pr corrects that.

to test you will need to apply the pr
go to the media manager options
delete the content of the Legal Document Extensions (File Types)
save
(this will put the correct defaults back)
go to articles and add a png as an intro image

Pull Request for Issue #34740

### CODE REVIEW

**Comment by richard67** [comment]
@brianteeman I've found one more place here: https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_media/src/Model/ApiModel.php#L603

**Review by richard67 — APPROVED** [review]

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 45a3e4db43afa4cc5e3b54802b30f8191d6e5520<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34753">issues.joomla.org/tracker/joomla-cms/34753</a>.</sub>

**Comment by dgrammatiko** [comment]
I have tested this item :white_check_mark: successfully on 45a3e4db43afa4cc5e3b54802b30f8191d6e5520<br /><br />Sorry, this was a stupid bug<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34753">issues.joomla.org/tracker/joomla-cms/34753</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34753">issues.joomla.org/tracker/joomla-cms/34753</a>.</sub>

**Comment by Quy** [comment]
Thanks!

**Comment by brianteeman** [comment]
s**t happens

**Pull request merged**
