### PR TITLE
[4.0] let's quote a varchar

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #25748

### Summary of Changes
quote a varchar please - standard SQL

### Testing Instructions
see issue #25748 

### Expected result
no error

### Actual result
generic error

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on aeaaf3366f443fa42f60f1dba0278a60d1bffff7<br /><br />Solves both errors mentioned in issue #25748 .<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25752">issues.joomla.org/tracker/joomla-cms/25752</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on aeaaf3366f443fa42f60f1dba0278a60d1bffff7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25752">issues.joomla.org/tracker/joomla-cms/25752</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25752">issues.joomla.org/tracker/joomla-cms/25752</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
