### PR TITLE
workflow standard sql

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #42031 .

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by richard67** [comment]
The issue has been reported for 4.3.4, so a fix should be done for the 4.4-dev branch and then be merged up to 5.0-dev.

**Comment by kochinc** [comment]
There was a mistake in the join() call. Please see the revised commit at #42031.

**Comment by richard67** [comment]
> There was a mistake in the join() call. Please see the revised commit at #42031.

@kochinc Could you make a pull request from that commit? Just referring to it in an issue doesn’t make it usable yet.

**Comment by kochinc** [comment]
> > There was a mistake in the join() call. Please see the revised commit at #42031.
> 
> @kochinc Could you make a pull request from that commit? Just referring to it in an issue doesn’t make it usable yet.

Done. See PR #42036.

**Comment by richard67** [comment]
@alikon I think @kochinc 's PR #42036 is better because it removes the condition also from the where clause (besides adding it to the join like both PRs do. In addition his PR is already for 4.4-dev. I suggest to close this one here in favour of  PR #42036 .

**Pull request closed without merging**
