### PR TITLE
Fix for [5.2] admin template broken #43932

### LINKED ISSUE #43932: [5.2] admin template broken
### Steps to reproduce the issue
checkout 5.2 and npm i

the fieldsets are being rendered without the required class of "options-form"

### Expected result
image

### Actual result

image

### PR DESCRIPTION
**Pull request by pe7er**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/43932

### Summary of Changes

This PR fixes the layout in the Global Configuration in the administrator back-end

### Testing Instructions

Go to /administrator/index.php?option=com_config and see the misalligned "Site" and missing border

### Actual result BEFORE applying this Pull Request

before

### Expected result AFTER applying this Pull Request

after

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Fedik** [comment]
Please, also do the same for `$description`

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 8ca67a8b98da32aae340c82164cd36e755cc7890<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43935">issues.joomla.org/tracker/joomla-cms/43935</a>.</sub>

**Comment by fgsw** [comment]
I have tested this item :white_check_mark: successfully on 8ca67a8b98da32aae340c82164cd36e755cc7890<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43935">issues.joomla.org/tracker/joomla-cms/43935</a>.</sub>

**Comment by Hackwar** [comment]
Thank you!

**Pull request merged**
