### PR TITLE
[Regression] Keep B/C in the redirect plugin

### PR DESCRIPTION
**Pull request by zero-24**
### Summary of Changes

If you have set up some urls with mixed upper and lower case in the redirect component before this patch they did not got redirected anymore.
 
### Testing Instructions

- Set up a redirect with a uppercase char in the URL.
- call the exact URL with the uppercase
- no redirect
- apply this patch
- it is working again

### Expected result

Old redirects still work

### Actual result

Old redirects with uppercase chars are broken

### Documentation Changes Required

None

### CODE REVIEW

**Comment by wilsonge** [comment]
> that patch

Which patch xD

**Comment by zero-24** [comment]
> Which patch xD

that => this

So without this patch here they did not got redirected anymore. I'm going to fix that ;)

**Comment by zero-24** [comment]
This patch here: https://github.com/joomla/joomla-cms/pull/13853 introduced the issue by forcing it to be lowercase but not respecting the mixed ones in the database. ;)

**Comment by ghost** [comment]
@zero-24 i setup following redirect which works without PR so i guess i didn't get Issue:
bildschirmfoto 2017-07-14 um 07 10 48

**Comment by infograf768** [comment]
hmm, This here works without patch:

screen shot 2017-07-14 at 09 07 38

**Comment by zero-24** [comment]
The problem is that they does not find the old URL. 

Please set the old URL withe upper cases and a different URL with lower cases. Please also make sure that the plugin is enabled.

**Comment by infograf768** [comment]
When the Expired URL contains a some Upper case, indeed this patch corrects the issue.
screen shot 2017-07-14 at 09 36 44


<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17124">issues.joomla.org/tracker/joomla-cms/17124</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 6edabc850681828ce90a145f2a8014d687337e48<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17124">issues.joomla.org/tracker/joomla-cms/17124</a>.</sub>

**Comment by zero-24** [comment]
> When the Expired URL contains a some Upper case, indeed this patch corrects the issue.

Is'n this than a succesful test?

**Comment by zero-24** [comment]
Ah our messages crossed ;)

**Comment by matrikular** [comment]
I have tested this item :white_check_mark: successfully on 031a3d89b37d18ac54d3ed1faa882a0bbb04aac1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17124">issues.joomla.org/tracker/joomla-cms/17124</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 031a3d89b37d18ac54d3ed1faa882a0bbb04aac1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17124">issues.joomla.org/tracker/joomla-cms/17124</a>.</sub>

**Comment by infograf768** [comment]
RTC, good for 3.7.4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17124">issues.joomla.org/tracker/joomla-cms/17124</a>.</sub>

**Pull request merged**
