### PR TITLE
[5.1] Convert mod_toolbar to service provider

### PR DESCRIPTION
**Pull request by joomlaweby**
### Summary of Changes

Converts the toolbar administrator module to service provider.

### Testing Instructions

1. Make sure you have administrator module mod_toolbar published
2. You should see module output

mod_toolbar

### Actual result BEFORE applying this Pull Request

Module works as expected

### Expected result AFTER applying this Pull Request

Module works same way as before applying pull request

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on d3bca7b38e59e6f4031679a23d8dd106f990b9d5<br /><br />Applied patch and looked at several admin pages - all toolbars worked normally (included logout/login).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42838">issues.joomla.org/tracker/joomla-cms/42838</a>.</sub>

**Comment by fgsw** [comment]
I have tested this item :white_check_mark: successfully on d3bca7b38e59e6f4031679a23d8dd106f990b9d5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42838">issues.joomla.org/tracker/joomla-cms/42838</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42838">issues.joomla.org/tracker/joomla-cms/42838</a>.</sub>

**Comment by LadySolveig** [comment]
Thank you @joomlaweby and also testing @ceford @fgsw

**Pull request merged**
