### PR TITLE
Added method getGroupTitle

### PR DESCRIPTION
**Pull request by HelgeSverre**
Added a helper method for getting the title of a group by its id.

I've not found any method to do this in the Joomla documentation so i put it it.

This example will echo out the title of every group that a user is in:
### Example

``` php
// Get the JUser object of the current user
$user   = JFactory::getUser();

// Get an array of the group id's that the current user is in.
$groups = JAccess::getGroupsByUser($user->id);

// Loop through each group id
foreach ($groups as $groupId) {
    // Print out the title of that group
    echo JAccess::getGroupTitle($groupId);
}

```

### CODE REVIEW

**Comment by zero-24** [comment]
@HelgeSverre I have just send you a quick CS PR.

Can you add some example code for the testers?

**Comment by HelgeSverre** [comment]
@zero-24 Sure


This example will echo out the title of every group that a user is in:

### Example
```php
// Get the JUser object of the current user
$user 	= JFactory::getUser();

// Get an array of the group id's that the current user is in.
$groups = JAccess::getGroupsByUser($user->id);

// Loop through each group id
foreach ($groups as $groupId) {
    // Print out the title of that group
    echo JAccess::getGroupTitle($groupId);
}

```

**Comment by zero-24** [comment]
Thanks @test successful :+1: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6994">issues.joomla.org/joomla-cms/6994</a>.</sub>

**Comment by jwaisner** [comment]
@test 

Patch works as intended.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6994">issues.joomla.org/joomla-cms/6994</a>.</sub>

**Comment by zero-24** [comment]
RTC Thanks :smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6994">issues.joomla.org/joomla-cms/6994</a>.</sub>

**Comment by HelgeSverre** [comment]
What does RTC stand for?

**Comment by zero-24** [comment]
>What does RTC stand for?

Ready to commit. So the changes works as expected and a maintainer need to take a decision to include or not :smile: Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6994">issues.joomla.org/joomla-cms/6994</a>.</sub>

**Comment by mbabker** [comment]
Added a unit test for the method and merged to `3.5-dev` via 7620400

**Pull request closed without merging**
