### PR TITLE
[4.0] Update some Form-related typehints

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue # .

### Summary of Changes

Use namespaced class.
Add typehints to plugin.

### Testing Instructions

Code review.

### Documentation Changes Required

IDK.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on c89e6939f3809871bc5d0ed1d3ad061c6de095ba<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25427">issues.joomla.org/tracker/joomla-cms/25427</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on c89e6939f3809871bc5d0ed1d3ad061c6de095ba<br /><br />code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25427">issues.joomla.org/tracker/joomla-cms/25427</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25427">issues.joomla.org/tracker/joomla-cms/25427</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
