### PR TITLE
LICENSE.txt

### PR DESCRIPTION
**Pull request by brianteeman**
The licence file we include is named LICENSE.txt but 748 files referred to just LICENSE

NB I excluded vendor supplied files obviously AND fof and libraries/joomla
as my understanding that any changes for these should be made upstream. If that is wrong I can always update this PR

### CODE REVIEW

**Comment by zero-24** [comment]
> The licence file we include is named LICENSE.txt but 748 files referred to just LICENSE

https://github.com/joomla/joomla-cms/blob/staging/installation/LICENSES ?

Isn't it the other way?

**Comment by brianteeman** [comment]
@zero-24 installation is a different issue see #14296

The license file referred to is https://github.com/joomla/joomla-cms/blob/staging/LICENSE.txt

**Comment by zero-24** [comment]
Ah. Sorry looks like i overlooked this file.

**Review by zero-24 — APPROVED** [review]

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 33c0cf94d4394407983b5094b10f4ff7bc3e5918<br /><br />Code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16317">issues.joomla.org/tracker/joomla-cms/16317</a>.</sub>

**Comment by tonypartridge** [comment]
I have tested this item :white_check_mark: successfully on 33c0cf94d4394407983b5094b10f4ff7bc3e5918<br /><br />On Code review. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16317">issues.joomla.org/tracker/joomla-cms/16317</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Comment by wilsonge** [comment]
Thanks Brian!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
