### PR TITLE
[#32036] Removing MooTools dependencies form administrator/templates folder

### PR DESCRIPTION
**Pull request by AshanFernando**
Under GSoC MooTools to jQuery project, this PR removes the MooTools dependencies in administrator/templates folder.

Feature Tracker Item:
http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=32036&start=575

### CODE REVIEW

**Comment by dgt41** [comment]
@AshanFernando Can you update this PR?
Also can you: 
rename `JHtml('behavior.formvalidation');` to `JHtml('behavior.formvalidator');` 
replace the inline scripts with `JFactory::getDocument()->addScriptDeclaration("code");

It would be easier if you break it to smaller parts, e.g. per component: com_content, com_admin etc

**Comment by zero-24** [comment]
Hi @AshanFernando 

as is this issue still valid. but pull requests to the master branch of this repo are not longer accepted. Can you close this pull request and submit a new one against the staging branch with the fixes that @dgt41 noted?
If there is no response in a month we will close the PR here.

Thanks for understanding!

**Comment by dgt41** [comment]
@zero-24 as there was no response I went ahead and changed #5245 to incorporate the changes proposed here, and the one I propose in the comment above. I hope @AshanFernando is ok with this

**Comment by AshanFernando** [comment]
Hi,

Just saw the messages. how can I help?

**Comment by dgt41** [comment]
@AshanFernando All kudos to you!!! You’ve done an exceptional job here.

**Comment by zero-24** [comment]
So we can close here @AshanFernando @dgt41 ?

**Comment by dgt41** [comment]
@zero-24 fine with me

**Comment by brianteeman** [comment]
Based on @AshanFernando and @dgt41 comments I am closing this See #5245

**Pull request closed without merging**
