### PR TITLE
Pass required parameter to canEditState.

### PR DESCRIPTION
**Pull request by Harmageddon**
Original report by user ernebenan on joomla-bugs.de: http://www.joomla-bugs.de/forum/index.php/topic,734.0.html

### Summary of Changes
The `JModelAdmin::canEditState` method requires one non-optional argument `$record`. As the parent method does not use the argument, it could be omitted, but PHP (at least starting from 7.0) throws a warning:

> Warning:  Missing argument 1 for JModelAdmin::canEditState(), called in /administrator/components/com_content/models/article.php on line 211 and defined in/libraries/legacy/model/admin.php on line 680

(PHP 7.0)

respectively an exception

> Too few arguments to function JModelAdmin::canEditState(), 0 passed in /administrator/components/com_content/models/article.php on line 211 and exactly 1 expected

(PHP 7.1)

### Testing Instructions
* Requirements: 
  * PHP 7.1 (to get the exception)
  * Backend template: Hathor (because Isis processes the ordering request via AJAX, so you won't see the error)
* Navigate to "Content - Featured Articles".
* Order by "Ordering".
* Try to change the ordering of the articles, e.g. moving one up or down.

### Expected result
* Re-ordering should work without any errors.

### Actual result
* On PHP 7.1, the action fails with the previously mentioned exception.

### Solution
* Apply this patch and test again.

### CODE REVIEW

**Comment by Quy** [comment]
Duplicate #13500

**Comment by franz-wohlkoenig** [comment]
closed as Duplicate Report #13500<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16146">issues.joomla.org/tracker/joomla-cms/16146</a>.</sub>

**Comment by Harmageddon** [comment]
If #13500 is merged before this one here, I'd agree to close this one. However, as #13500 is a bit more complex and thus might break something else, I'd like to re-open this PR here, because it fixes a bug existing in 3.7.1 and current staging. 
Users with PHP 7.1 and Joomla! 3.7.0/1/upcoming 2 can't manually change the order of articles anymore. #13500 might require some more testing and in the case, that will hopefully not be happening, that it breaks something and needs to be reverted, the bug mentioned here would be re-introduced. I'd prefer to keep PRs fixing bugs separate from those improving code with no intended effect.

**Comment by rdeutz** [comment]
reopened on request of @Harmageddon

**Comment by gwsdesk** [comment]
Please see this post on the Joomla 3.7.0 FAQ related to the Hathor template https://docs.joomla.org/J3.x:Hathor_admin_template_has_not_been_updated_to_work_with_the_new_features

**Comment by brianteeman** [comment]
@gwsdesk using hathor in this case is just as a quick demo of the problem

**Comment by gwsdesk** [comment]
@brianteeman understood but in 3.7.2 we have no more Hathor to select from ;-)

**Comment by brianteeman** [comment]
@gwsdesk i guess you are using a different version of joomla to me than - hathor has not been removed

**Comment by gwsdesk** [comment]
@brianteeman I was looking at the wrong open tab sorry for that. I can test this and post back

**Comment by sandstorm871** [comment]
I have tested this item :white_check_mark: successfully on 5365b3b0bc637aaf123e1eda8d7edd40b9f30bb4<br /><br />Not sure who uses Hathor, but I tested this successfully ;)

Without applied patch, I see an "0 - An Error Has Occured"
After Patch, ordering works as expected

@pete-rossetti - Wanna do the 2nd test<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16146">issues.joomla.org/tracker/joomla-cms/16146</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 5365b3b0bc637aaf123e1eda8d7edd40b9f30bb4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16146">issues.joomla.org/tracker/joomla-cms/16146</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Pull request merged**
