### PR TITLE
[4.0] Remove un-used line of code

### PR DESCRIPTION
**Pull request by joomdonation**
Pull Request for Issue # .

### Summary of Changes
Just a tiny PR to remove un-used line of code in renderComponent method in ComponentHelper class.

### Testing Instructions
Code review

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 1680ba6bb42753caaf25136f0d83f6029a16da34<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23394">issues.joomla.org/tracker/joomla-cms/23394</a>.</sub>

**Comment by bonzani** [comment]
I have tested this item :white_check_mark: successfully on d8de7925272a56d7e7ede72fc730971d512261ff<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23394">issues.joomla.org/tracker/joomla-cms/23394</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23394">issues.joomla.org/tracker/joomla-cms/23394</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
