### PR TITLE
[5][webservices]  add filter by search

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #42503 .

### Summary of Changes
added filter bt search

### Testing Instructions

{{base_path}}/api/index.php/v1/tags?filter[search]=text
{{base_path}}/api/index.php/v1/content/categories?filter[search]=text

### Actual result BEFORE applying this Pull Request
N/A

### Expected result AFTER applying this Pull Request

response take care of serch filter

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by aberenguer78** [comment]
Sorry I'm new adding feature requests. You mentioned me to test I don't know how to test. There's a new Joomla 4 version??
We need this feature in joomla 4 because we don't have our systems yet prepaired to migrate to joomla 5,
thanks in advance

**Comment by alikon** [comment]
iirc new feature cannot go in 4.x series, if the release lead consider this a bug fix i will  do it in the 4.x branch
for test you can copy the changed lines in a j4 site

**Comment by aberenguer78** [comment]
I have downloaded CategoriesController and TagsController and tested locally and it works fine.
I have tried to add another filter in the controllers displaylist:
if (\array_key_exists('alias', $apiFilterInfo)) {
            $this->modelState->set('filter.alias', $filter->clean($apiFilterInfo['alias'], 'STRING'));
        }
But this code doesen't work and I don't know why. The idea is to filter only by the alias field, is possible??
Sample query:
{{base_url}}/{{base_path}}/tags?filter[alias]=provatag2

Please, we need this filter search for the 4.x branch in a new version, thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42519">issues.joomla.org/tracker/joomla-cms/42519</a>.</sub>

**Comment by walturbo** [comment]
I have tested this item :white_check_mark: successfully on c8da43838e696adaf43bf28d641767e4d1aa6931<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42519">issues.joomla.org/tracker/joomla-cms/42519</a>.</sub>

**Comment by Hackwar** [comment]
@aberenguer78 could you mark the PR as tested by you in the issue tracker? If you do, then we can mark this as ready to commit and this PR could already be in Joomla 5.1.

**Comment by aberenguer78** [comment]
#42503 It's closed. I tested locally on 15th of December locally and it works fine. You, have my comments here :
https://github.com/joomla/joomla-cms/pull/42519#issuecomment-1857501479 
 Walturbo tested it too and it's ok.
I don't know how to mark the issue as tested

**Comment by aberenguer78** [comment]
I have tested this item :white_check_mark: successfully on c8da43838e696adaf43bf28d641767e4d1aa6931<br /><br />It was tested successfully on 15/12/2023<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42519">issues.joomla.org/tracker/joomla-cms/42519</a>.</sub>

**Comment by Hackwar** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42519">issues.joomla.org/tracker/joomla-cms/42519</a>.</sub>

**Comment by LadySolveig** [comment]
Thank you @alikon and also for testing and support @aberenguer78 @walturbo @Hackwar

**Pull request merged**
