### PR TITLE
[4.0] Remove multiple lines / padding between fieldsets

### PR DESCRIPTION
**Pull request by ciar4n**
Pull Request for Issue # .

### Summary of Changes

- Remove multiple lines between fieldsets
- Remove excess padding around fieldsets

### Before
image

### After
image

### CODE REVIEW

**Comment by brianteeman** [comment]
Personally I find it clearer before this PR to see which fields are in a group - especially on single column pages such as article options.

image

image

**Comment by richard67** [comment]
Does this PR solve issue #33548 , or is that something else?

**Comment by ciar4n** [comment]
@richard67 That issues appears to be just for the frontend where this is for the backend.

@brianteeman I dont think wrapping everything in boxes is the answer if you want more distinction between fieldsets.

**Comment by brianteeman** [comment]
I'm open to any suggestion

**Comment by ceford** [comment]
I prefer the status quo - the legend in a complete outline of the items it encloses. Can we vote this pr down?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33873">issues.joomla.org/tracker/joomla-cms/33873</a>.</sub>

**Comment by ciar4n** [comment]
> I'm open to any suggestion

Considering this PR is one, how many do you want?

**Comment by ciar4n** [comment]
Closing considering lack of interest.

**Pull request closed without merging**
