### PR TITLE
css issue

### PR DESCRIPTION
**Pull request by CEWebDesign**
correct code

### CODE REVIEW

**Comment by Bakual** [comment]
Is there a way to test this change?

**Comment by brianteeman** [comment]
Yes. Run it through a CSS validator. 
The original code is invalid and doesn't do anything.

**Comment by joo7** [comment]
is it possible in github to see who wrote the code in the first place and for what reason?

**Comment by sovainfo** [comment]
@joo7  When viewing the file on github you can use blame and history to find out who wrote the code.
Normally that leads to a commit or PR that sorts of describes the reason.

**Comment by Bakual** [comment]
> Yes. Run it through a CSS validator. 
The original code is invalid and doesn't do anything.

@brianteeman I'm aware of that. But since it is currently invalid it could be removed without changing anything.
However this PR changes behavior and thus I asked for test instructions. `overflow: hidden` may or may not be the desired behavior after all.

**Comment by Bakual** [comment]
@joo7 It was introduced with https://github.com/joomla/joomla-cms/pull/3169

**Comment by joo7** [comment]
close in favor of #8595

**Comment by JoomliC** [comment]
@Bakual Yes, it was mine error ;-)
This could be removed with no issue.

**Pull request closed without merging**
