### PR TITLE
[com_installer] Translate the extension name if possible

### PR DESCRIPTION
**Pull request by zero-24**
Pull Request for Issue #11567 
#### Summary of Changes

Allow all kind of extensions to have translatable names
#### Testing Instructions
- go to com_installer -> manage -> manage
- select the type `Library`
- see all items are translated (no language string)
- go to the database and edit the entry for the Joomla Lib
- set the name (collum params) to `LIB_JOOMLA_XML_DESCRIPTION`

`{"name":"LIB_JOOMLA_XML_DESCRIPTION","type":"library","creationDate":"2008","author":"Joomla! Project","copyright":"Copyright (C) 2005 - 2016 Open Source Matters. All rights reserved.","authorEmail":"admin@joomla.org","authorUrl":"https:\/\/www.joomla.org","version":"13.1","description":"LIB_JOOMLA_XML_DESCRIPTION","group":"","filename":"joomla"}`
- go to  com_installer -> manage -> manage again
- see it is not translated
- apply this PR
- see it is translated.
#### Documentation Changes Required

Nothing as this is the same as all other extensions.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 44f1ae222fc465b200ec0cfc51674e2c7f74f6a8<br /><br />Followed test instructions - all good<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11595">issues.joomla.org/joomla-cms/11595</a>.</sub>

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on 44f1ae222fc465b200ec0cfc51674e2c7f74f6a8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11595">issues.joomla.org/joomla-cms/11595</a>.</sub>

**Comment by zero-24** [comment]
@mbabker do you remember a reason for this `conditional` in the first place?

**Comment by mbabker** [comment]
https://github.com/joomla/joomla-cms/commit/879de61f0680cb934de409f44cb4f162d532eadd

**Comment by zero-24** [comment]
Thanks. If that gots accepted i can move the names to the language files.

**Comment by brianteeman** [comment]
Setting RTC as we have two good tests. The count was just reset by the merge update<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11595">issues.joomla.org/joomla-cms/11595</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11595">issues.joomla.org/joomla-cms/11595</a>.</sub>

**Comment by truptikagathara** [comment]
I have tested this item :white_check_mark: successfully on 19e8832297ef5e946c32eee7369248ea34b7a5d6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11595">issues.joomla.org/joomla-cms/11595</a>.</sub>

**Comment by zero-24** [comment]
>Thanks. If that gots accepted i can move the names to the language files.

Done https://github.com/joomla/joomla-cms/pull/11626

**Pull request merged**
