### PR TITLE
Better Component Config layout

### PR DESCRIPTION
**Pull request by bygiro**
Better layout when no Label, like for "permissions" fieldset

### CODE REVIEW

**Comment by zero-24** [comment]
Hi @bygiro I'm not sure what you try to fix? Can you add a bit more description to your issue? Expecial a way to test this PR?

**Comment by bygiro** [comment]
if there is no label in the xml field, the "control-group" input is still rendered with an empty div with class "control-label" and a div with class "controls" (container of the input). the visual layout will be ugly, because the div with class "controls" has "margin-left: 180px;".
in the "permissions" tab, this does not happens, because the label is not completely rendered and the input container doesn't have any "controls" class.
I added an option to do not render the label and to remove the "controls" class if there is no label attribute in the xml field of the form.
I hope I've been a bit more clear. I thought it was clear from the code.

**Comment by brianteeman** [comment]
From the limited description of what this does I have not been able to test that it does what you say. I also do not understand in what situation you will not have a label.

I am setting this to information required. Please update this with full testing instructions and an explanation of the use case. This will be closed within 4 weeks if not updated.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8232">issues.joomla.org/joomla-cms/8232</a>.</sub>

**Comment by infograf768** [comment]
If a field has no label, the name of the field is used.

**Comment by brianteeman** [comment]
Closed as stated above<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8232">issues.joomla.org/joomla-cms/8232</a>.</sub>

**Pull request closed without merging**
