### PR TITLE
Change array to short syntax in LevelModel

### PR DESCRIPTION
**Pull request by laoneo**
Followup of #39297 to change array to short syntax.

Can be merged on review.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by ReLater** [comment]
I have tested this item :white_check_mark: successfully on 74a6391ed40892c74a9c63a253bc9dcbf0f147b3<br /><br />Code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39581">issues.joomla.org/tracker/joomla-cms/39581</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 74a6391ed40892c74a9c63a253bc9dcbf0f147b3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39581">issues.joomla.org/tracker/joomla-cms/39581</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39581">issues.joomla.org/tracker/joomla-cms/39581</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
