### PR TITLE
[4.0] Download Key manager SQL errors

### PR DESCRIPTION
**Pull request by brianteeman**
PR for #26164

Fix the mysql installation table

### CODE REVIEW

**Comment by roland-d** [comment]
I have tested this item :white_check_mark: successfully on 98137a19bcddc2eae355a7f0ba62b2c1890aee45<br /><br />After installation of Joomla the fields are in the correct table and being used.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26165">issues.joomla.org/tracker/joomla-cms/26165</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by wilsonge** [comment]
@brianteeman @roland-d can you check if this needs doing on postgresql too please

**Comment by brianteeman** [comment]
@wilsonge I did already or I would have submitted a patch ;)

**Comment by wilsonge** [comment]
cool thanks!

**Pull request merged**
