### PR TITLE
[4.0] Fix tooltip cutoff

### PR DESCRIPTION
**Pull request by Quy**
Continuation fix of #26673

### Summary of Changes
Fix tooltip cutoff.

### Testing Instructions
Go to Content > Workflows.
Under `Stages` column, click the number.
Hover over the `Publish` icon.
Click `Back` button.
Under `Transitions` column, click the number.
Hover the `Publish` icon.

### CODE REVIEW

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on 7cc8e12345fa33736127ab0f02b7b43e00eb757a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26877">issues.joomla.org/tracker/joomla-cms/26877</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 7cc8e12345fa33736127ab0f02b7b43e00eb757a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26877">issues.joomla.org/tracker/joomla-cms/26877</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26877">issues.joomla.org/tracker/joomla-cms/26877</a>.</sub>

**Comment by vijaykhollam** [comment]
I have tested this item :white_check_mark: successfully on 3c7c1ea5c1e8db9454d11e3a5a09944cfb335877<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26877">issues.joomla.org/tracker/joomla-cms/26877</a>.</sub>

**Comment by deepa-g** [comment]
I have tested this item successfully

**Comment by deepa-g** [comment]
I have tested this item :white_check_mark: successfully on 3c7c1ea5c1e8db9454d11e3a5a09944cfb335877<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26877">issues.joomla.org/tracker/joomla-cms/26877</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
