### PR TITLE
[5.3] Email cloak comments

### PR DESCRIPTION
**Pull request by brianteeman**
Corrects the comment so that it makes sense

code review

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 28d2cec9da05827e7eb77e22020c1e0426d6589d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44102">issues.joomla.org/tracker/joomla-cms/44102</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 28d2cec9da05827e7eb77e22020c1e0426d6589d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44102">issues.joomla.org/tracker/joomla-cms/44102</a>.</sub>

**Comment by richard67** [comment]
RTC ... though I don't understand why this PR is for 5.3-dev and not for 5.2-dev.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44102">issues.joomla.org/tracker/joomla-cms/44102</a>.</sub>

**Comment by laoneo** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
