### PR TITLE
[com_users] notes view: Add max level filter

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
Pull Request for Improvement.
#### Summary of Changes

All backend views that are or are associated with tree like structures (e.g. menus, categories) should have a max level filter.

This is valid currently for:
- com_menus items view
- com_content articles view
- com_content featured view
- com_tags tags view

So, this PR is a part of series of PR to add that filter in the views that use categories:
- com_contacts contacts view (RTC https://github.com/joomla/joomla-cms/pull/9975)
- com_banners banners view (RTC https://github.com/joomla/joomla-cms/pull/9977)
- com_newsfeeds newsfeeds view (RTC https://github.com/joomla/joomla-cms/pull/9978)
- com_notes notes view (**this PR**)
- com_banners tracks view (https://github.com/joomla/joomla-cms/pull/10009)

image
#### Testing Instructions
1. Use latest staging and apply this patch
2. Create some user notes categories with at least two levels
3. Create some user notes and associate them to the categories created in 2..
4. Test the new max levels filter.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 86c5fc5029fee20add0929823e0d686f95132419<br /><br />Not sure it is really needed but it is consistent<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9984">issues.joomla.org/joomla-cms/9984</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 86c5fc5029fee20add0929823e0d686f95132419<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9984">issues.joomla.org/joomla-cms/9984</a>.</sub>

**Comment by andrepereiradasilva** [comment]
and thanks again for testing!

**Comment by richard67** [comment]
@andrepereiradasilva I know you have no non-utf8mb4 database available to help me with testing my PR 9847 (not wanna link it hete because not related to this here), but maybe you could set up such?

If your PHP versions and MySQL versions are coupled somehow (e.g. because using a common package like XAMPP for that), and you use some kind of virtual machiens (VMware or so), you could set up a VM with old stuff for the database server and with new stuff (for fulfilling 3.5.x requirements) for the Joomla! installation, which looks at the old db server.

The test itself then would not need much time, and you could keep the VM with the old db server for later use (when I make my next big PR for handling utf8mb4 conversion for extensions). You know, there is a lack of good experienced testers having such old mysql versions.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9984">issues.joomla.org/joomla-cms/9984</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9984">issues.joomla.org/joomla-cms/9984</a>.</sub>

**Comment by rdeutz** [comment]
technically this is a new feature and it doesn't fix a bug so it has to go into 3.6.0

**Comment by MDXBilal12** [comment]
I have tested this item :white_check_mark: successfully on 86c5fc5029fee20add0929823e0d686f95132419<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9984">issues.joomla.org/joomla-cms/9984</a>.</sub>

**Comment by rdeutz** [comment]
@aaleksanyants cloud you please check the merge conflicts, thanks

**Comment by rdeutz** [comment]
Ups wrong name @andrepereiradasilva cloud you please check the merge conflicts, thanks

**Comment by andrepereiradasilva** [comment]
finally ... conflicts fixed

**Pull request merged**
