### PR TITLE
[4.0] Password toggler markup and styling

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/24312.

### Summary of Changes

Corrects password toggler markup and styling to have a visible focus outline.
Converts to FA icons, adds `fa-fw` class to keep same width when toggling.

### Testing Instructions

Run `node build.js --compile-js`.
Go to a form with password field.
Inspect styling.
Click on toggle button a few times.
Check that the icon and the screenreader text changes correctly.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by brianteeman** [comment]
it was pointed out to me before that the code should not be dependant on using fontawesome especially for the frontend

**Comment by Quy** [comment]
See #22680

**Comment by brianteeman** [comment]
The width issue is resolved by this

BUT (sorry there is always a but)

The hover/active (?) colour is now different - almost black

### before
before

### after
after

**Comment by SharkyKZ** [comment]
That's just how `btn-secondary` is styled in Atum. There's still the width issue, icon is clearly off-center.

**Comment by brianteeman** [comment]
So why did you change it to that button. It's not consistent with similar functions

**Comment by SharkyKZ** [comment]
To use them same class everywhere.

**Comment by brianteeman** [comment]
My apologies - we are actually using a mix already :(

image

The first is btn-primary and the second btn-secondary

**Comment by brianteeman** [comment]
Was it intentional to change the styling on the front end login module?

### Before
image

### After
image

**Comment by SharkyKZ** [comment]
Yes, the button is now styled like a button.

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 2e10620c84ac58045be3bce34debafddc8bfbabc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27733">issues.joomla.org/tracker/joomla-cms/27733</a>.</sub>

**Comment by Quy** [comment]
Eye is not centered so there is a slight shift when toggling between icons.

eye


password

**Comment by SharkyKZ** [comment]
@Quy similar issue before patch, except whole button changes width. Related issue https://github.com/joomla/joomla-cms/issues/24853.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on cb0ee08cca6915a6d91768a0a56fe907e5c8e029<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27733">issues.joomla.org/tracker/joomla-cms/27733</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27733">issues.joomla.org/tracker/joomla-cms/27733</a>.</sub>

**Pull request merged**
