### PR TITLE
Standardize method for getting database object in models

### PR DESCRIPTION
**Pull request by wilsonge**
We have a `getDbo()` method in JModelLegacy (https://github.com/joomla/joomla-cms/blob/staging/libraries/legacy/model/legacy.php#L373) . This effectively is still a proxy to `JFactory::getDatabase()` - however it can be injected into the class and I see us standardising on using this method as us really promoting the use of injection into MVC classes instead of using these static JFactory methods.
## Testing

To test navigate around the backend and check all the views work affected parts are:
- Saving a category
- Saving a banner
- Displaying the system information
- Saving a contact
- Saving an article
- Viewing the list of installed extensions in Extension Manager
- Checking for existing extensions when using Discover in Extension Manager
- Checking the database is upto date in Extension Manager
- Using the purge cache button in the Joomla Update Component
- Saving a menu item
- Getting the list of available menu types when creating a menu item
- Saving a newsfeed
- Loading module lang files
- Saving a template
- Getting the user groups for a user in User Manager

As this is about getting the database object it should be REALLY obvious if something is broken (like the page completely dies).

On top of that check using the vote plugin in the frontend of Joomla in an article and registration view in the frontend

### CODE REVIEW

**Comment by zero-24** [comment]
@wilsonge can you again merge staging into this PR to fix the merge conflicts? Thanks!

**Comment by smohila** [comment]
Seems to work.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4992">issues.joomla.org/joomla-cms/4992</a>.</sub>

**Comment by wilsonge** [comment]
Merged in staging @zero-24

**Comment by garstud** [comment]
@test with success, i succeed to :
- view an article in frontend
- make a frontend registration, login and log out in frontend
- display a contact detail in frontend
- edit and save an article in frontend
- edit and save an article in backend

Perhaps, it may needs more tests intructions on other joomla functions !?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4992">issues.joomla.org/joomla-cms/4992</a>.</sub>

**Comment by wilsonge** [comment]
I've tried to write the complete list of things affected. Thanks so much for testing!

**Comment by Kubik-Rubik** [comment]
@wilsonge Couldn't rebase against staging. Could you please update this PR?

**Comment by wilsonge** [comment]
There's a green merge button. GitHub seems to think everything is up to date?

**Comment by wilsonge** [comment]
I just merged in staging and there weren't any conflicts - maybe try applying the diff from https://github.com/joomla/joomla-cms/pull/4992.diff ?

**Comment by Kubik-Rubik** [comment]
Still had 4 conflicts.... but could solve them! :-)

Thank you @wilsonge! Merged.

**Pull request closed without merging**
