### PR TITLE
Remove colon from tooltip

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue 11382
#### Summary of Changes

We were using the same string for both the tooltip where it would just say Article Count
and for the more visible string where it would say Article Count: 99

To fix this I created a new string to be used for the tooltip without the colon

### CODE REVIEW

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on bac8547d57752511e9a92e6d6c6e1fb3d697ad74<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11385">issues.joomla.org/joomla-cms/11385</a>.</sub>

**Comment by Lavsteph** [comment]
I have tested this item :white_check_mark: successfully on bac8547d57752511e9a92e6d6c6e1fb3d697ad74<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11385">issues.joomla.org/joomla-cms/11385</a>.</sub>

**Comment by brianteeman** [comment]
Rtc thanks for testing<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11385">issues.joomla.org/joomla-cms/11385</a>.</sub>

**Comment by infograf768** [comment]
I am not sure using "COM_CONTENT_NUM_ITEMS_DESC" makes sense here as we usually keep this for forms.
Why not use what it is for:
"COM_CONTENT_NUM_ITEMS_TIP"

**Comment by brianteeman** [comment]
didnt spot we had a _TIP

I will make that change - thanks

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 6eb48df3a80c206992c93bb3d1298602a998c4ea<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11385">issues.joomla.org/joomla-cms/11385</a>.</sub>

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on 6eb48df3a80c206992c93bb3d1298602a998c4ea<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11385">issues.joomla.org/joomla-cms/11385</a>.</sub>

**Pull request merged**
