### PR TITLE
[4.0][a11y]Replace link by button in com_contact

### PR DESCRIPTION
**Pull request by hardik-codes**
This PR replaces link by a button for the dismiss button in com_contact
### Summary of Changes
Replaced ```< a``` Tag by the correct ```< button``` Tag

### Testing Instructions
Code inspection

### CODE REVIEW

**Comment by brianteeman** [comment]
this and most other cases like this have already been fixed in joomla 3 and are just waiting for @wilsonge to merge them upstream into j4

there are plenty of things to do without re-doing code that is already solved.

**Comment by hardik-codes** [comment]
> this and most other cases like this have already been fixed in joomla 3 and are just waiting for @wilsonge to merge them upstream into j4

Ok, I didn't know about that.

**Comment by hardik-codes** [comment]
> there are plenty of things to do without re-doing code that is already solved

Could you please let me know some of them so that I can start working on them.

**Comment by Quy** [comment]
Closing as stated per brianteeman.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24186">issues.joomla.org/tracker/joomla-cms/24186</a>.</sub>

**Pull request closed without merging**
