### PR TITLE
[4.0] Added the module ID to the forms HTML id so that it is unqiue and you…

### PR DESCRIPTION
**Pull request by uglyeoin**
… can have multiple login forms.

Pull Request for Issue # .

### Summary of Changes
Added the module ID to the HTML ID making it unique and allowing for multiple login forms.  

### Testing Instructions
Add a login module to the front end
Inspect the source code and see that the login module has an id of id="login-form"
Install the patch
Inspect the login form and see that the module now has an ID with a module number added to the end of it. e.g. id="login-form-16"

### Expected result
ID's should always be unique

### Actual result
ID is static but module can be replicated.
You see the correct module ID attached to the ID making it unique

### Documentation Changes Required
n/a

### CODE REVIEW

**Comment by sanderpotjer** [comment]
I have tested this item :white_check_mark: successfully on 6a0a65f1b912be2be75daf13b7f312e7bd991394<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24757">issues.joomla.org/tracker/joomla-cms/24757</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 6a0a65f1b912be2be75daf13b7f312e7bd991394<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24757">issues.joomla.org/tracker/joomla-cms/24757</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24757">issues.joomla.org/tracker/joomla-cms/24757</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
