### PR TITLE
s/curent/current

### PR DESCRIPTION
**Pull request by PhilETaylor**
s/curent/current

### CODE REVIEW

**Comment by Razzo1987** [comment]
Also in libraries/vendor/joomla/string/src/phputf8/utils/position.php line 120

**Comment by PhilETaylor** [comment]
Thanks @Razzo1987 - I tend not to modify files that Joomla inherited and are not created by Joomla. Certain people get upset at making typo changes in copyrighted code.

**Comment by Razzo1987** [comment]
I have tested this item :white_check_mark: successfully on 3c15bd7770c34679781865d176cc8ec045fdedef<br /><br />OK<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31947">issues.joomla.org/tracker/joomla-cms/31947</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 3c15bd7770c34679781865d176cc8ec045fdedef<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31947">issues.joomla.org/tracker/joomla-cms/31947</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31947">issues.joomla.org/tracker/joomla-cms/31947</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
