### PR TITLE
[4.0] Template preview link

### PR DESCRIPTION
**Pull request by brianteeman**
pr for #29432 Double icon

As suggested by @infograf768 https://github.com/joomla/joomla-cms/issues/29432#issuecomment-639393473 this removes the open eye icon when preview is enabled

### after
image

### CODE REVIEW

**Comment by Quy** [comment]
Add title to `Open in new window`?

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on 2cf2c13905d039d34baa7eff8ae4f00af5ae917e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29717">issues.joomla.org/tracker/joomla-cms/29717</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 2cf2c13905d039d34baa7eff8ae4f00af5ae917e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29717">issues.joomla.org/tracker/joomla-cms/29717</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29717">issues.joomla.org/tracker/joomla-cms/29717</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
