### PR TITLE
[4.0] Mod status titles

### PR DESCRIPTION
**Pull request by brianteeman**
3 of the 4 icons have a title tag - for consistency this pr makes sure all 4 have a title
screenshotr14-23-00

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 51746eac813f1e57870182494329fd6a4310e193<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17360">issues.joomla.org/tracker/joomla-cms/17360</a>.</sub>

**Review by C-Lodder — APPROVED** [review]

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 51746eac813f1e57870182494329fd6a4310e193<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17360">issues.joomla.org/tracker/joomla-cms/17360</a>.</sub>

**Comment by ghost** [comment]
RTC after two successful tests.

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
