### PR TITLE
Add version and IE conditional statements to JHtml::stylesheet/JDocument::addStyleSheet methods and deprecate JDocument::addSyleSheetVersion()

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
Pull Request for Improvement.
### Summary of Changes

This PR does for stylesheets what was done for script in https://github.com/joomla/joomla-cms/pull/11289

Ie, adds the ability to add add media version and IE conditional statements to the stylesheets link tag using `JDocument::addStyleSheet()` and `JHtml::stylesheet()` methods.  

Also deprecates `JDocument::addSyleSheetVersion()` method.
### Testing Instructions

Please test this in all possible scenarios.
Any problem will get stylesheets not loading.
- Do a code review.
- Use 3.7.x branch and apply patch
- Check backend and frontend styles are working fine
- Add external css stylesheets like to isis/protostar index.php, some examples:

``` php
// JDocument B/C tests
/* addStyleSheet($url, $type = 'text/css', $media = null, $attribs = array()) */
$this->addStyleSheet('/path/to/external/bcaddStyleSheet1.css');
$this->addStyleSheet('/path/to/external/bcaddStyleSheet2.css', '', null, array());
$this->addStyleSheet('/path/to/external/bcaddStyleSheet3.css', 'text/css', 'all', array('scriptid' => 1));
/* addStyleSheetVersion($url, $version = null, $type = 'text/css', $media = null, $attribs = array()) */
$this->addStyleSheetVersion('/path/to/external/bcaddStyleSheetVersion1.css');
$this->addStyleSheetVersion('/path/to/external/bcaddStyleSheetVersion2.css', null, '', null, array());
$this->addStyleSheetVersion('/path/to/external/bcaddStyleSheetVersion3.css', 'version-string', 'text/css', 'all', array('scriptid' => 1));

// JDocument new method signature tests
/* addStyleSheet($url, $options = array(), $attribs = array()) */
$this->addStyleSheet('/path/to/external/addStyleSheet0.css');
$this->addStyleSheet('/path/to/external/addStyleSheet1.css', array(), array('id' => 'stylesheetid'));
$this->addStyleSheet('/path/to/external/addStyleSheet2.css', array(), array('id' => 'stylesheetid', 'data-test' => 1));
$this->addStyleSheet('/path/to/external/addStyleSheet3.css', array(), array('data-attrib' => 'original-value'));
$this->addStyleSheet('/path/to/external/addStyleSheet4.css', array(), array('data-attrib' => 'final-value'));
$this->addStyleSheet('/path/to/external/addStyleSheet5.css', array(), array('data-attrib' => array('item1' => 'value1', 'item2' => 'value2')));
$this->addStyleSheet('/path/to/external/addStyleSheet6.css', array('version' => 'auto'), array('data-attrib' => array('item1' => 'value1', 'item2' => 'value2')));
$this->addStyleSheet('/path/to/external/addStyleSheet7.css', array('version' => 'version-string'), array('media' => 'all', 'data-attrib' => array('item1' => 'value1', 'item2' => 'value2')));
$this->addStyleSheet('/path/to/external/addStyleSheet8.css', array('version' => 'auto', 'conditional' => 'lf IE 9'), array('data-attrib' => array('item1' => 'value1', 'item2' => 'value2')));

// JHTML B/C Tests
/* stylesheet($file, $attribs = array(), $relative = false, $path_only = false, $detect_browser = true, $detect_debug = true) */
JHtml::_('stylesheet', 'media/system/css/jquery.Jcrop.min.css');
JHtml::_('stylesheet', 'system/frontediting.css', array('id' => 'stylesheetid'), true, false, false, false);

// JHtml new method signature tests
/* stylesheet($file, $options = array(), $attribs = array()) */
JHtml::_('stylesheet', 'media/com_finder/css/indexer.css', array(), array('data-attrib' => array('item1' => 3, 'item2' => 'value2')));
JHtml::_('stylesheet', 'system/adminlist.css', array('relative' => true), array('data-attrib' => array('item1' => 3, 'item2' => 'value2')));
JHtml::_('stylesheet', 'system/calendar-jos.css', array('relative' => true, 'version' => 'auto'), array('data-attrib' => array('item1' => 3, 'item2' => 'value2')));
JHtml::_('stylesheet', 'system/mootree.css', array('relative' => true, 'version' => 'version-string'), array('media' => 'all', 'data-attrib' => array('item1' => 3, 'item2' => 'value2')));
JHtml::_('stylesheet', 'system/mootree_rtl.css', array('relative' => true, 'version' => 'version-string', 'conditional' => 'lf IE 9'), array('media' => 'all', 'data-attrib' => array('item1' => 3, 'item2' => 'value2')));
```
- Check the HTML output and confirm all is fine
- Do the same tests for anything else you can remember
### Observations

From a B/C perspective i think there are no issues, but mantainers please check.

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
can anyone review test this so we can have similiar API for script (js) and style (css).
don't want this kind of changes to be a late merge than can cause problems after.

Also after this is tested/merged it will allow to add version to css files so they are not cached uin browser after joomla updates, which with all isis template changes in 3.7.0 would be advised.

@dgt41 @C-Lodder @Fedik @brianteeman @zero-24 @infograf768 need testers here please

**Comment by brianteeman** [comment]
Sorry - never saw this. Will add it to my todo

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on 73fc98a717cb21f8879d80090054d3754a8ea901<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12375">issues.joomla.org/tracker/joomla-cms/12375</a>.</sub>

**Comment by Fedik** [comment]
only thing I have noticed, that some IDE interpret `addStyleSheet` and `addScript` as deprecated, that really can confuse people 😉 

screen 2016-10-31 19 19 55 265x203

**Comment by andrepereiradasilva** [comment]
> only thing I have noticed, that some IDE interpret addStyleSheet and addScript as deprecated, that really can confuse people 😉

i can change it to note on both after this is merged

**Comment by dgt41** [comment]
@andrepereiradasilva @Fedik actually this is good, devs should use ONLY JHtml

**Comment by Fedik** [comment]
well, it seems correct way 
http://softwareengineering.stackexchange.com/questions/229644/how-to-annotate-method-signature-changes

**Comment by andrepereiradasilva** [comment]
ok following https://github.com/joomla/joomla-cms/pull/11289 and https://github.com/joomla/joomla-cms/pull/12373 all js files are now referenced with media version in the core.

We need to do this in css files also! (particuly with 3.7.0o isis redesign)

One more test here please so this can be merged and after make a PR to add media version to all css files in the core.

**Comment by brianteeman** [comment]
Tested successfully 

no sha again @mbabker<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12375">issues.joomla.org/tracker/joomla-cms/12375</a>.</sub>

**Comment by mbabker** [comment]
Whomever keeps breaking my app, please stop.

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 73fc98a717cb21f8879d80090054d3754a8ea901<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12375">issues.joomla.org/tracker/joomla-cms/12375</a>.</sub>

**Comment by andrepereiradasilva** [comment]
thanks @brianteeman !

**Comment by andrepereiradasilva** [comment]
RTC ?

**Comment by andrepereiradasilva** [comment]
@jeckodevelopment RTC this one too?

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12375">issues.joomla.org/tracker/joomla-cms/12375</a>.</sub>

**Comment by andrepereiradasilva** [comment]
thanks!

**Comment by andrepereiradasilva** [comment]
oh no! this one is crazy too now!

**Comment by jeckodevelopment** [comment]
can't understand why the bot is playing with the Unit/system test label.

**Comment by andrepereiradasilva** [comment]
in this one is playing with the language label https://github.com/joomla/joomla-cms/pull/12739

**Comment by jeckodevelopment** [comment]
@mbabker please help!
The bot is going crazy!!!!!

**Comment by alikon** [comment]
loop

**Comment by jeckodevelopment** [comment]
The only thing i see is the name of the PR too long :D

**Comment by andrepereiradasilva** [comment]
bot's code ...
```
while (1)
{
add label;
remove label;
}
```

**Comment by jeckodevelopment** [comment]
Opened an issue https://github.com/joomla/jissues/issues/906

**Comment by mbabker** [comment]
If all of you would stop breaking my bots I would greatly appreciate it.

**Comment by jeckodevelopment** [comment]
Tell us how we can avoid breaking it :)

**Comment by mbabker** [comment]
> Tell us how we can avoid breaking it :)

Well if I knew that there wouldn't be 50 label events on this here item.  Either way the pull request listener won't act on labeled events anymore.  Guess I'm gonna have to move up my weekend rewriting that entire subsystem.

**Pull request merged**
