### PR TITLE
Issue with content languages access in 3.4.0 (replaces #6172)

### PR DESCRIPTION
**Pull request by infograf768**
To test, create a basic multilanguage site with 3.4.0. Easiest is to use the functionnality when installing Joomla.
Then edit  with phpmyadmin the _languages table in the database and set the `access` column values to 0.

Display frontend is broken.
Patch and test again.

### CODE REVIEW

**Comment by Bakual** [comment]
Thanks. Looks fine to me.

**Comment by mahagr** [comment]
I would also add sticky notification to admin to allow/force users to fix the database integrity issue so we can restore the new code later.

I don't think that isset() is needed as the variable should be always present..?

**Comment by Hackwar** [comment]
as @mahagr says, the isset() is unnecessary.

**Comment by infograf768** [comment]
in the module we just indeed use if($language->access etc. the isset was not in the original PR implementing the access.
Now looking when it was added.

**Comment by infograf768** [comment]
took off the isset.

**Comment by infograf768** [comment]
I suggest to commit this for 3.4.1 and add, when ready, a postinstall message

RTC

**Comment by zero-24** [comment]
@infograf768 postinstall can be found here: https://github.com/joomla/joomla-cms/pull/6195

**Comment by zero-24** [comment]
moving RTC to match the RTC label on github<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6194">issues.joomla.org/joomla-cms/6194</a>.</sub>

**Comment by wilsonge** [comment]
JM can you just add a code comment above this line just adding

```
// @todo: In Joomla 2.5.4 and earlier access wasn't set properly and gives a value of 0
```

or something similar so in the future we can come back to it and try and apply a longer term fix?

**Comment by infograf768** [comment]
done

**Comment by Bakual** [comment]
> in the future we can come back to it and try and apply a longer term fix?

I'd say we can remove it for 4.0. Because then we can assume everyone has saved the value (especially given we have the postinstall message). Also it allows to make backward incompatible changes.

**Comment by mbabker** [comment]
You can't even assume it then, today we're making a fix for a change that was applied in 2.5.4, a release almost 3 years ago and on a previous major release branch.  The only 'safe' assumption is that people will find ways to break things :smiley:

**Comment by Bakual** [comment]
Sure enough, but at least we are allowed to break it :)

**Comment by infograf768** [comment]
Imho it does not cost much to leave the check (which btw also exists in the switcher module).

**Pull request merged**
