### PR TITLE
[5.2] Update PHPUnit to 10

### PR DESCRIPTION
**Pull request by rdeutz**
Pull Request for Issue #42528 .

### Summary of Changes
Update PHPUnit to the next major version because the current one we are using is outdated

### Testing Instructions

**Test/Merge after #43381**

Unit test should work as before.

### CODE REVIEW

**Comment by richard67** [comment]
@rdeutz It seems you are updating a lot of composer dependencies, see the lock file. Can it be that you have just run a `composer update` instead of a `composer update phpunit/phpunit`?

**Comment by brianteeman** [comment]
@richard67 try that and you will see why

**Comment by richard67** [comment]
> I have tested this item ✅ successfully on [4f5f61c](https://github.com/joomla/joomla-cms/commit/4f5f61c7d7d6ac71b7ccb34b9ffa77c522b46629)

@brianteeman You have noticed that both appveyor and drone are failing due to failing unit tests?

@rdeutz If that is expected because it needs the other PR, then your testing instructions should make that more clear.

**Comment by brianteeman** [comment]
The composer lock updates are correct and if you try to do a composer update phpunit (as I said) then you will see why

Tests failing does not necessarily mean that the PR is wrong. It can also mean that the tests are wrong. We know that there are multiple tests that are either wrong or flakey.

**Comment by brianteeman** [comment]
@richard67 not sure what happened but when you replied to my comment you actually edited it. So it looks like I have said what you said. I have deleted it. and paste below 

The composer lock updates are correct and if you try to do a composer update phpunit (as I said) then you will see why

Tests failing does not necessarily mean that the PR is wrong. It can also mean that the tests are wrong. We know that there are multiple tests that are either wrong or flakey.

I am well aware that these are failing unit tests which are failing. Thats what I was referring to.

-----

As you can see now from Roberts ammended update the original update was correct. You just need to try it for yourself and you will see that you cannot just update phpunit without also updating a large batch of dependencies.

**Comment by richard67** [comment]
> not sure what happened but when you replied to my comment you actually edited it.

@brianteeman No idea what happened either, but it was not by purpose.

> As you can see now from Roberts ammended update the original update was correct.

I know it needs to update a bunch of them, but in the first attempt there were definitely some included which are no dependencies of PHP unit. Now after the recent 2 commits it seems to be right.

**Comment by rdeutz** [comment]
> @rdeutz If that is expected because it needs the other PR, then your testing instructions should make that more clear.

updated

one fail is expected when #43381 is not merged the other ones not

re-did the composer update

**Comment by rdeutz** [comment]
closed in favor of #43865

**Comment by richard67** [comment]
> closed in favor of #43865

@rdeutz Forgotten to close?

**Comment by rdeutz** [comment]
yes

**Pull request closed without merging**
