### PR TITLE
fix hr system-readmore not working with additional parameter

### PR DESCRIPTION
**Pull request by Tomas42**
Pull Request for Issue #12194   .
### Summary of Changes

changed regex pattern to ignore additional parameters in hr system-readmore (additional parameters will be removed).

### Testing Instructions
Works only when saving an article.

### Documentation Changes Required

ignore additional parameters in the hr-system-readmore

### CODE REVIEW

**Comment by zero-24** [comment]
I have tested this item :red_circle: unsuccessfully on <br /><br />hmm it do not work here on my end.

I have sample data installed and that added to the "First blog post" your extended read more `<hr id="system-readmore" style="width: 1013.75px; word-spacing: 0px;">` after that I can confirm it is broken but the same thing happen with that patch applyed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12199">issues.joomla.org/joomla-cms/12199</a>.</sub>

**Comment by Tomas42** [comment]
@zero-24: Just to make sure: after installing the patch you opened the article again and saved it? because the splitting into intro/fulltext only works on saving the text.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12199">issues.joomla.org/joomla-cms/12199</a>.</sub>

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on 2ae3898a0bbfa0385a179b847665b4a4b210a5bd<br /><br />Ah ok thanks for the tip works now. Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12199">issues.joomla.org/tracker/joomla-cms/12199</a>.</sub>

**Comment by hans2103** [comment]
I have tested this item :red_circle: unsuccessfully on 2ae3898a0bbfa0385a179b847665b4a4b210a5bd<br /><br />changed regex doesn't **ignore** the additional parameters, it **removes** them. 

After save ```<hr id="system-readmore" style="width: 1013.75px; word-spacing: 0px;">``` will be changed into ```<hr id="system-readmore" />```

When you write ignore, I was expecting that it doesn't matter what kind of additional parameter you add. 
When you write delete then this test is successful. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12199">issues.joomla.org/tracker/joomla-cms/12199</a>.</sub>

**Comment by Tomas42** [comment]
@hans2103: i added your hint to the description.
FYI: Joomla stores intro and full text in separate fields. The system-readmore-tag is created when editing an article to separate the fields again when the article is stored. The tag is never stored or used outside the editor. So any other parameters to this tag should be meaningless.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12199">issues.joomla.org/tracker/joomla-cms/12199</a>.</sub>

**Comment by coolcat-creations** [comment]
i have no clue, it works as good before the patch like after. It removes the additional attributes, but isn´t that a wanted function?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12199">issues.joomla.org/tracker/joomla-cms/12199</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
I have tested this item :red_circle: unsuccessfully on 2ae3898a0bbfa0385a179b847665b4a4b210a5bd<br /><br />with and without PR a `<hr id="system-readmore" style="width: 1013.75px; word-spacing: 0px;">` changes to `<hr id="system-readmore" />`<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12199">issues.joomla.org/tracker/joomla-cms/12199</a>.</sub>

**Comment by mbabker** [comment]
I don't see the issue with that. `<hr id="system-readmore" />` doesn't actually get output on a page, it's used internally as a marker to split the introtext and fulltext values.  IMO we shouldn't encourage using that specific `<hr>` as a styling element since the only place you ever see it is the backend editor.

**Comment by Sieger66** [comment]
Additional step to see the issue #12194 :

Chance the editor to "Editor-None" and  save a article with :
<hr id="system-readmore" style="width: 1013.75px; word-spacing: 0px;">

**Comment by Sieger66** [comment]
I have tested this item :white_check_mark: successfully on 2ae3898a0bbfa0385a179b847665b4a4b210a5bd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12199">issues.joomla.org/tracker/joomla-cms/12199</a>.</sub>

**Comment by roland-d** [comment]
@mbabker said that this isn't shown on the page, so what is the use of allowing additional attributes to the readmore tag?

**Comment by brianteeman** [comment]
This change really makes no sense at all - why would someone go to the trouble of adding styling to something that is never displayed.

**Comment by Tomas42** [comment]
@brianteeman  I can not explain how she added the style. It was most likely unintentional, may be with some copy and paste or something like that.
As these styles are not useful and the current behavior (ignoring such a styled hr when splitting the article) is most likely unexpected I suggested this fix to ignore the additional stuff and split the article on the hr. 
So the actual question is: 
If a user added some style to the hr-tag, for whatever reason, why should joomla not use the styled hr-tag to split the editor content into intro and full text?
If someone know a reason please post here, otherwise it should be save to use the fix.

**Comment by franz-wohlkoenig** [comment]
set Status on "Needs Review".<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12199">issues.joomla.org/tracker/joomla-cms/12199</a>.</sub>

**Comment by Quy** [comment]
I don't see a use case/purpose to adding style to the readmore marker. If you have to, then add `system-readmore` css to `custom.css` file.

**Comment by Quy** [comment]
Closing for reasons stated above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12199">issues.joomla.org/tracker/joomla-cms/12199</a>.</sub>

**Pull request closed without merging**
