### PR TITLE
fixed protected function calls in repeatable field

### PR DESCRIPTION
**Pull request by julienV**
Pull Request for Issue # .

### Summary of Changes
Replaced deprecated function calls in repeatable fields. It's deprecated, but can still be used by 3rd party.

### Testing Instructions
display a form with a repeatable field

### Expected result
it should work without throwing a fatal error...

### CODE REVIEW

**Comment by Robbie8** [comment]
The Joomla support issue https://forum.joomla.org/viewtopic.php?f=706&t=955602&p=3498001#p3498001 gives more information on how the problem was identified

**Comment by Quy** [comment]
@Robbie8 Please mark your test result here: https://issues.joomla.org/tracker/joomla-cms/18325

**Comment by Robbie8** [comment]
I have tested this item :white_check_mark: successfully on 01c3a2f15a27006653e6a4129e9c90b49ddb4e8d<br /><br />I tested this by accessing the Article Manager - to add a new article and edit an existing one. 
Both tests completed as required<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18325">issues.joomla.org/tracker/joomla-cms/18325</a>.</sub>

**Comment by ghost** [comment]
@Robbie8 can you please describe how you test so we get the needed second Test?

**Comment by ghost** [comment]
Reminder for @Robbie8 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18325">issues.joomla.org/tracker/joomla-cms/18325</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 01c3a2f15a27006653e6a4129e9c90b49ddb4e8d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18325">issues.joomla.org/tracker/joomla-cms/18325</a>.</sub>

**Comment by laoneo** [comment]
The functions "getLabel" and "getInput" are not deprecated. And can you post a link to the code where a fatal error is thrown? I can't think of a place where a deprecated message throws a fatal error.

**Comment by laoneo** [comment]
I had a second look and indeed, these functions are protected. So we have to change to the properties or better to use the functions from the form instance.

**Comment by laoneo** [comment]
@julienV can you update the description with proper test instructions?

**Comment by julienV** [comment]
Hi, sorry guys, but this is 5 (!!) years old, i have moved on, and i really don't have the time to setup everything for this...

**Comment by laoneo** [comment]
@julienV thanks for clarification. I'm closing it then and when somebody else wants to take over, feel free to open a new pr on the most recent 4 branch.

**Pull request closed without merging**
