### PR TITLE
[4.0] Fix workflow state submenu

### PR DESCRIPTION
**Pull request by bembelimen**
Pull Request for Issue #21491 .

### Summary of Changes
Fix disappearing of left column

### Testing Instructions
See: #21491

### Expected result
Menu column is still visible

### Actual result
Menu column disappear.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 9aca034b73a1859715a868f76eda06ad31a7023b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21508">issues.joomla.org/tracker/joomla-cms/21508</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 9aca034b73a1859715a868f76eda06ad31a7023b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21508">issues.joomla.org/tracker/joomla-cms/21508</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21508">issues.joomla.org/tracker/joomla-cms/21508</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
