### PR TITLE
Common class for list type modules

### PR DESCRIPTION
**Pull request by ciar4n**
Pull Request for Issue # .

### Summary of Changes
The following list modules often get the same CSS applied to them however there is no common HTML class to target them. This PR adds a common class to each (`mod-list`).

mod_articles_archive
mod_articles_categories
mod_articles_category
mod_articles_latest
mod_articles_news
mod_articles_popular
mod_menu
mod_related_items
mod_users_latest

### Testing Instructions
Code review

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 8c1ea6c9d82fa45563a778587dc1f3d3a211e4c1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22688">issues.joomla.org/tracker/joomla-cms/22688</a>.</sub>

**Comment by infograf768** [comment]
I have not tested this item.<br /><br />On review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22688">issues.joomla.org/tracker/joomla-cms/22688</a>.</sub>

**Comment by infograf768** [comment]
RTC. No brainer.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22688">issues.joomla.org/tracker/joomla-cms/22688</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 8c1ea6c9d82fa45563a778587dc1f3d3a211e4c1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22688">issues.joomla.org/tracker/joomla-cms/22688</a>.</sub>

**Pull request merged**
