### PR TITLE
Adds keyup trigger on showon elements

### PR DESCRIPTION
**Pull request by regularlabs**
### Summary of Changes
This PR will make elements show/hide when typing in a text field.

Currently, the showon elements are only updated when the value of a field changes (onChange).
However, when typing in a text field, the change event is only triggered when the focus is moved to another element.

So the PR changes that behaviour to also update the showon fields when the keyup event is triggered.

### Testing Instructions
Add this code to a form xml file (inside a fieldset).
We'll use the banners config file for this example:
`administrator/components/com_banners/config.xml`
```
<field name="my_text_field" type="text" label="My Text Field" />
<field name="my_note" type="note" class="alert alert-success"
	   description="Shows when the text field is not empty"
	   showon="my_text_field!:"
/>
```

### Before PR
Start typing in the text field. Nothing happens.
But when clicking outside the textfield, or hitting tab, the note shows.
before

### After PR
Start typing in the empty text field. 
The note shows as soon as it is not empty.
The note also hides again as soon as you delete the characters in the text field.
after

### CODE REVIEW

**Comment by brianteeman** [comment]
I stand by my previous comments in #22890

**Comment by regularlabs** [comment]
Noted.

**Comment by ciar4n** [comment]
I have tested this item :white_check_mark: successfully on 924633146148eaf0fac70599d11ad8650653b1a1<br /><br />Just to mention.. currently, if a user fills a field that triggers the display of another and goes on to click an action that closes (eg Save and Close), that field may never be seen. This PR fixes that.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22912">issues.joomla.org/tracker/joomla-cms/22912</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 924633146148eaf0fac70599d11ad8650653b1a1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22912">issues.joomla.org/tracker/joomla-cms/22912</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22912">issues.joomla.org/tracker/joomla-cms/22912</a>.</sub>

**Comment by tonypartridge** [comment]
I can see this causing havoc on bigger forms with the whole page jumping around when typing. 

Can we adjust this so it’s an exact match value? So if value = Goodbar only match on Goodbar.

Or at the very least make it a field value option to toggle on/off?

**Comment by regularlabs** [comment]
The fields will only show if it matches whatever you put into the check. The same way it works for any other field.
Why would it be jumping? It doesn't close and open fields after every keypress. As you can see in the example given.
Also it is up to the developer on how to use this (using showon on text fields). So how could this cause havoc?

**Comment by tonypartridge** [comment]
Ahh sorry I’ve just checked the code as was on my mobile last night, I assumed looking at the video you were showing on value = foobar .  And it was revealing on f etc.

**Comment by regularlabs** [comment]
Any reason why this isn't merged yet?

**Comment by mbabker** [comment]
I've purposefully held off on anything that looked feature-esque just to be safe in case something came up warranting 3.9.1 be released sooner than expected.  I'll merge your PRs over the weekend assuming nothing comes up before then.

**Comment by regularlabs** [comment]
Ok, thanks :)

**Pull request merged**
