### PR TITLE
[4.0] Workflow help button

### PR DESCRIPTION
**Pull request by brianteeman**
PR for #29754

Thanks @ceford

Apply the pr and make sure that the help buttons in com_workflow all work

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on cdceaa4aaddef90d46fa1753300056d7fdd64a05<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29757">issues.joomla.org/tracker/joomla-cms/29757</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on cdceaa4aaddef90d46fa1753300056d7fdd64a05<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29757">issues.joomla.org/tracker/joomla-cms/29757</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29757">issues.joomla.org/tracker/joomla-cms/29757</a>.</sub>

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on cdceaa4aaddef90d46fa1753300056d7fdd64a05<br /><br />All good!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29757">issues.joomla.org/tracker/joomla-cms/29757</a>.</sub>

**Comment by brianteeman** [comment]
Thanks all

**Pull request merged**
