### PR TITLE
Improving the consistency of the HTML models 

### PR DESCRIPTION
**Pull request by charvimehradu**
Pull Request for Issue #38539 .

### Summary of Changes
Improving the consistency of the HTML models as instructed by labeling the input tag first, as is done in the components login form.
Additionally, you can review this PR in relation to PR#39669
### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
I have the same questions that I had on your other pull request

**Comment by charvimehradu** [comment]
@brianteeman 
I've responded to the questions you raised in the previous issue. I apologize for the delay; to be completely honest, I was not aware of the submit option and believed it was still awaiting your evaluation.

**Comment by brianteeman** [comment]
@charvimehradu every pull request should be on a clean branch so that it only includes the changes for this issue and not all the code from your previous pull request. As you can see there are 6 files changed here but I suspect that you only meant to change one of them.

**Comment by charvimehradu** [comment]
okay noted

**Pull request closed without merging**
