### PR TITLE
Render only the input when no fieldsets are specified in subform layouts

### PR DESCRIPTION
**Pull request by laoneo**
Pull Request for PR #13069.

### Summary of Changes
The label of the field is show in the table layout of the subform field as column header and then inline before the input field
This PR shows the label beside the input field only when the fields itself should be grouped by its groups.

### Testing Instructions
Put the following XML code into the file administrator/components/com_content/models/forms/article.xml after line 162 (inside the basic fieldset in the attribs tag).

```
<field name="demo" type="subform" label="Subform" multiple="true" layout="joomla.form.field.subform.repeatable-table">
	<form>
		<field name="name"
			label="Name"
			size="30" type="text" />

		<field name="value"
			label="Value"
			size="30" type="text" />
	</form>
</field>
```
### Expected result
The labels should not be shown in the cell, like
image

## Actual result
The labels are shown.
image

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on eac64ae37db6a60856081810d48e7832cac2518b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13093">issues.joomla.org/tracker/joomla-cms/13093</a>.</sub>

**Comment by Fedik** [comment]
now I remember why was need `$field->renderField()`, it need for `showon` feature,

maybe we can do something like `$field->renderField(array('label' => false))`, 
but cannot check currently

**Comment by ralain** [comment]
I have tested this item :white_check_mark: successfully on eac64ae37db6a60856081810d48e7832cac2518b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13093">issues.joomla.org/tracker/joomla-cms/13093</a>.</sub>

**Comment by jeckodevelopment** [comment]
Rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13093">issues.joomla.org/tracker/joomla-cms/13093</a>.</sub>

**Comment by Fedik** [comment]
please hold on, 
need to test `showon` feature, 
for it can use xml from #12511 with `layout="joomla.form.field.subform.repeatable-table"` or:

```xml
<field name="items" type="subform"  multiple="true"  label="Subform Field" 
layout="joomla.form.field.subform.repeatable-table" >
  <form>
    <field name="type" type="list" default="0" label="Type" >
        <option value="0">Small</option>
        <option value="1">Medium</option>
        <option value="2">Large</option>
       </field>

        <field name="something"  type="text"
            label="Show when Type=Large" showon="type:2" />
   </form>
</field>
```


I cannot currently, maybe this evening or tomorrow

**Comment by laoneo** [comment]
Just tested it and showon is not working. Thanks for having a look @Fedik !!

**Comment by Fedik** [comment]
hm, `$field->renderField(array('hiddenLabel' => true));` partially do the thing, 
but default Joomla! styling add `.form-horizontal .controls {margin-left: 180px;}` 
No idea what the best solution here

**Comment by laoneo** [comment]
Can this being tested again, I'v updated the description with the new test instructions, thanks!!

**Comment by ralain** [comment]
@laoneo Left margin reset isn't working right now because the data-group attribute is being modified when we insert rows. Perhaps target data-base-name, instead? That should be the same for each row.

**Comment by Fedik** [comment]
I have tested and it not realy work, @ralain are right, 
but there one more thing, this code add CSS multiple times. 
So maybe better place:
```php
JFactory::getDocument()->addStyleDeclaration(
  '.subform-repeatable-group[data-base-name="' . $fieldname . '"] .controls { margin-left: 0px }'
);
```

in the repeatable-table.php somewhere after this line [repeatable-table.php#L62](https://github.com/Digital-Peak/joomla-cms/blob/a2a8c49d76eeea05c94f68b8a30bede8389255e8/layouts/joomla/form/field/subform/repeatable-table.php#L62) 

Other possible solution is to add specific class to `<div class="subform-repeatable-wrapper subform-table-layout">` and use CSS file to stylig.

```html
<div class="subform-repeatable-wrapper subform-table-layout subform-table-layout-<?php echo $sublayout; ?>">
```

and in css:
```css
.subform-table-layout-section .controls { margin-left: 0px }
```

**Comment by ralain** [comment]
> Other possible solution is to add specific class to `<div class="subform-repeatable-wrapper subform-table-layout">` and use CSS file to stylig.

Indeed, I would personally prefer a single global css rule over the embedded styles, if possible.

**Comment by laoneo** [comment]
Changed to your suggestion, thanks for your help, much appreciated.

**Comment by Fedik** [comment]
only, please move `addStyleDeclaration()` in to the `repeatable-table.php` somewhere after this line [repeatable-table.php#L62](https://github.com/Digital-Peak/joomla-cms/blob/a2a8c49d76eeea05c94f68b8a30bede8389255e8/layouts/joomla/form/field/subform/repeatable-table.php#L62) , because in current place it will be added multiple times

**Comment by laoneo** [comment]
Done, should work now

**Comment by laoneo** [comment]
Can we have another round of testing please. Thanks.

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on a2722437bb7d0c8af37b78ee75d165a263e1c807<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13093">issues.joomla.org/tracker/joomla-cms/13093</a>.</sub>

**Comment by ralain** [comment]
I have tested this item :white_check_mark: successfully on a2722437bb7d0c8af37b78ee75d165a263e1c807<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13093">issues.joomla.org/tracker/joomla-cms/13093</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13093">issues.joomla.org/tracker/joomla-cms/13093</a>.</sub>

**Comment by zero-24** [comment]
Merged thanks

**Pull request merged**
