### PR TITLE
[4.0] Notice when searching Contacts by ID

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue # .

### Summary of Changes

Fixes notice when searching contacts by ID.

### Testing Instructions

Search for contact by ID, e.g. enter `id:1` to search field.

### Expected result

No notices.

### Actual result

>Notice: Only variables should be passed by reference in administrator\components\com_contact\Model\ContactsModel.php on line 304

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 6a7216d32a9dd11ab8e96edd662d2e4fe5350c91<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25640">issues.joomla.org/tracker/joomla-cms/25640</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 6a7216d32a9dd11ab8e96edd662d2e4fe5350c91<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25640">issues.joomla.org/tracker/joomla-cms/25640</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25640">issues.joomla.org/tracker/joomla-cms/25640</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
