### PR TITLE
[4.0] Update Sites title

### PR DESCRIPTION
**Pull request by brianteeman**
As shown in the screenshot this is not just for extensions

image

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on d6ec250bd75cc88f3004940aa0de7a144b547f96<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36471">issues.joomla.org/tracker/joomla-cms/36471</a>.</sub>

**Comment by Shubhamverma2796** [comment]
I have tested this item :white_check_mark: successfully on d6ec250bd75cc88f3004940aa0de7a144b547f96<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36471">issues.joomla.org/tracker/joomla-cms/36471</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36471">issues.joomla.org/tracker/joomla-cms/36471</a>.</sub>

**Comment by Quy** [comment]
Thanks

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
