### PR TITLE
Remove $false = false

### PR DESCRIPTION
**Pull request by chmst**
Pull Request for Issue # .

### Summary of Changes
as title says.

### Testing Instructions
Code review should be enough.

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on c571d8dcdb9a22f7c3cd6c84613889535906c3d1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38069">issues.joomla.org/tracker/joomla-cms/38069</a>.</sub>

**Comment by sandewt** [comment]
I have tested this item :white_check_mark: successfully on c571d8dcdb9a22f7c3cd6c84613889535906c3d1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38069">issues.joomla.org/tracker/joomla-cms/38069</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38069">issues.joomla.org/tracker/joomla-cms/38069</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
