### PR TITLE
[4.0] Load webcomponents with asset manager

### PR DESCRIPTION
**Pull request by Fedik**
### Summary of Changes
This will load webcomponents with asset manager.

### Testing Instructions
Apply patch run `npm install`
Click around, try create/edit content, all should work as before.

### Expected result
Everything works

### Actual result
Everything works

### Documentation Changes Required
Need to update Asset documentation to describe how to add webcomponent to it.

ping @wilsonge

### CODE REVIEW

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 0afe53a3bbb2dd5a153605d9609500579f5383ac<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27418">issues.joomla.org/tracker/joomla-cms/27418</a>.</sub>

**Comment by dgrammatiko** [comment]
@Fedik are you also covering this hidden functionality: https://github.com/joomla/joomla-cms/blob/543246ade38fa9ed3bb933e63375b70f8ec9b972/libraries/src/HTML/HTMLHelper.php#L765

**Comment by Fedik** [comment]
nope, it not hidden now
it need to explicitly call to the style if webcomponent have a style, eg:
https://github.com/joomla/joomla-cms/blob/0afe53a3bbb2dd5a153605d9609500579f5383ac/layouts/joomla/form/field/color/simple.php#L55-L59

**Comment by dgrammatiko** [comment]
much better 👍

**Comment by wilsonge** [comment]
Thanks!

**Comment by wilsonge** [comment]
Thanks!

**Comment by Fedik** [comment]
the doc for this part https://docs.joomla.org/J4.x:Web_Assets#Working_with_a_web_component

**Pull request merged**
