### PR TITLE
Add emoji font-family

### PR DESCRIPTION
**Pull request by 810**
Now you can see colored icons instead of a black icon

#### Test instructions:
You need utf8mb4 collation

1) go to http://getemoji.com/ copy some emoji's 
2) create new/edit article, paste the emoji's 

3) 
before patch:
emo1

after: 
emo2

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
how to test?

**Comment by 810** [comment]
@andrepereiradasilva instructions added

**Comment by andrepereiradasilva** [comment]
Using windows 10.

In firefox, ie 11 and edge i see coloful emojis after patch.
In chrome doesn't work.

Also shouldn't this be added to beez3 too?

**Comment by 810** [comment]
chrome is using the blink engine, so it doesn't work 

I can add it later to beez3

**Comment by andrepereiradasilva** [comment]
ok i see, chrome as not added support for those fonts.

**Comment by richard67** [comment]
@810 "I can add it later to beez3": Means we shall wait with testing until you added it to this PR here? Or means you will make another PR for that so we already shall test this one?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9956">issues.joomla.org/joomla-cms/9956</a>.</sub>

**Comment by 810** [comment]
@richard67 updated the beez3 css

**Comment by richard67** [comment]
@810 For me there is no difference between before and after patch regarding colours of emojis. Some have colours, some have not.

Only when I remove the fonts "Helvetica Neue", Helvetica, Arial, sans-serif, "Apple Color Emoji" from the body tag's properties e.g. in Firebug, then I see a change for the emojis listed in the last section "Emojis that work in your Twitter Name, Twitter Bio, and Ask.fm questions" at [http://getemoji.com/](http://getemoji.com/ "http://getemoji.com/").

I tested on Windows 10 with latest versions of Firefox and Google Chrome.

Just clearing broswer cache does not help.

Am I missing something, e.g. related to cached fonts?

@andrepereiradasilva When you tested, did you verify with pre-patched, and was there a change? And which emojis did you use?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9956">issues.joomla.org/joomla-cms/9956</a>.</sub>

**Comment by Fedik** [comment]
test result a lot depend from OS

**Comment by 810** [comment]
not all emoji's are standard implanted on all browsers. I added the same font-family as GitHub/facebook/ect

**Comment by richard67** [comment]
Well then I better not test because I cannot replicate the issue and any change from this PR.

**Comment by 810** [comment]
emo3

There is indeed not all icons are translated

**Comment by andrepereiradasilva** [comment]
actually after resting what @richard67 said it's true. with or without the PR the emojis stays the same in firefox on windows.

**Comment by richard67** [comment]
A snakeoil PR? (joke)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9956">issues.joomla.org/joomla-cms/9956</a>.</sub>

**Comment by andrepereiradasilva** [comment]
i think the emoji rendering or not are OS/browser related. and @810 it trying to make a fallback in OS/browsers combinations that don't render them, right?

@810 what is your browser/OS combination?

**Comment by 810** [comment]
Win10 - insiders build
edge/ie11/ff/chrome (not working)

**Comment by richard67** [comment]
I just tested again with Firefor and now also with Microsoft's **Edge** on same OS (Win 10), with the emojis I mentioned before, the last section "Emojis that work in your Twitter Name, Twitter Bio, and Ask.fm questions" at [http://getemoji.com/](http://getemoji.com/ "http://getemoji.com/").

And now I could see a slight difference:

MS Edge before patch:
screen shot 2016-04-17 at 15 43 50

MS Edge after patch:
screen shot 2016-04-17 at 15 43 58

Firefox before patch:
screen shot 2016-04-17 at 15 44 03

Firefox after patch:
screen shot 2016-04-17 at 15 44 10

So this PR at least seems to make things a bit better in certain cases without doing harm in other cases.

And with the Firefox test I either was blind when testing 1st time, or there was stuff cached so it looked the same, don't know now what went wrong.

@810 Would you consider this being a good test?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9956">issues.joomla.org/joomla-cms/9956</a>.</sub>

**Comment by 810** [comment]
you can test it here also on the comment: just paste the emoji ;)

**Comment by richard67** [comment]
@810 

> you can test it here also on the comment: just paste the emoji ;)

How you mean that?

And is my test sufficient and good now, or not? You did not answer that.

**Comment by 810** [comment]
I thought there will be more icons that have colors, Also I see other issue I will update the pr

**Comment by mikeveeckmans** [comment]
I have tested this item :white_check_mark: successfully on e5e8efea310696ea29729ce780733f725f22d5e2<br /><br />Test OK

Mac OSX (10.11.4) , tested on firefox and chrome.

Emoji shown in article title, article content and H2, H3
Tested on Protostar, Beez3 & 3rdparty template<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9956">issues.joomla.org/joomla-cms/9956</a>.</sub>

**Comment by richard67** [comment]
@810 In Protostar the font-families you have added are applied. But in Beez3 not. The reason is following code in "templates/beez3/css/layout.css" beginning at line 13:

> body#shadow {
    font-family: arial,sans-serif;
}

This made me check in which other css we have font-families set.

They are a lot.

Limiting my search to the templates folder (for frontend templates) I still get a lot:

> beez3\css\layout.css:   font-family: arial,sans-serif
beez3\css\layout.css:   font-family: inherit;
beez3\css\nature.css:   font-family: arial, helvetica, sans-serif;
beez3\css\print.css:  font-family:Arial, Verdana, Helvetica, sans-serif;
beez3\css\template_rtl.css:     font-family: 'Titillium Maps',  Arial;
protostar\css\template.css:     font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
protostar\css\template.css:     font-family: inherit;
protostar\css\template.css:     font-family: Monaco, Menlo, Consolas, "Courier New", monospace;
protostar\css\template.css:     font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
protostar\css\template.css:     font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
protostar\css\template.css:     font-family: 'IcoMoon';
protostar\css\template.css:     font-family: 'IcoMoon';
protostar\css\template.css:     font-family: 'IcoMoon';
system\css\editor.css:  font-family: Tahoma,Helvetica,Arial,sans-serif;
system\css\editor.css:  font-family:Helvetica ,Arial,sans-serif;
system\css\editor.css:  font-family: Arial, Helvetica,sans-serif;
system\css\editor.css:  font-family: Helvetica,Arial,sans-serif;
system\css\editor.css:  font-family: Arial, Helvetica, sans-serif;
system\css\error.css:   font-family: helvetica, arial, sans-serif;
system\css\error.css:   font-family: helvetica, arial, sans-serif;
system\css\error.css:   font-family: helvetica, arial, sans-serif;
system\css\offline.css: font-family: Arial, Helvetica, Sans Serif; font-size: 14px;
system\css\offline.css: font-family: inherit;

Not to mention all those in administrator/templates and in the media folder (and subfolders).

Of course not all of these need to be updated by your change, but I think at least things like "body#shadow" or other "body#...", like the one I mentioned at the top.

Am not sure if @mikeveeckmans tested the fonts used, or if he just checked if the emojis show up (like his test result reads), which would be not a valid test in my opinion then because objective of this PR is another than showing emojis which do not show up before.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9956">issues.joomla.org/joomla-cms/9956</a>.</sub>

**Comment by 810** [comment]
@richard67 On css files you need just 1 time to load the new font. Then its included on every page.

That's why I just added It once.

**Comment by MDXBilal12** [comment]
I have tested this item :white_check_mark: successfully on e5e8efea310696ea29729ce780733f725f22d5e2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9956">issues.joomla.org/joomla-cms/9956</a>.</sub>

**Comment by brianteeman** [comment]
I'm confused - is this good to merge or not?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9956">issues.joomla.org/joomla-cms/9956</a>.</sub>

**Comment by Fedik** [comment]
The Patch is good only for OS X users, and maybe some Win10 users

**Comment by sanek4life** [comment]
recently find this official website with all Emoji symbols- http://www.unicode.org/emoji/charts/full-emoji-list.html

**Comment by gunjanpatel** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9956">issues.joomla.org/joomla-cms/9956</a>.</sub>

**Comment by brianteeman** [comment]
Based on the comment from @fedik above I am removing the RTC status<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9956">issues.joomla.org/joomla-cms/9956</a>.</sub>

**Comment by zero-24** [comment]
@joomla-cms-bot please do the job that @brianteeman prepared for you :smile:

**Comment by brianteeman** [comment]
It also has merge conflicts that need to be resolved

**Comment by gunjanpatel** [comment]
It needs to be in **Need Review** status then? not for resolving conflicts but based on previous comments. :smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9956">issues.joomla.org/joomla-cms/9956</a>.</sub>

**Comment by brianteeman** [comment]
> The Patch is good only for OS X users, and maybe some Win10 users

I am closing this PR. We would need to ensure it worked on all supported platforms and browsers before it could be accepted.

Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9956">issues.joomla.org/joomla-cms/9956</a>.</sub>

**Comment by 810** [comment]
All browser are ok for me now, with the latest builds
Edge, IE11, chrome,ff

**Comment by brianteeman** [comment]
IE 8 & 9 ?

**Comment by 810** [comment]
http://caniemoji.com/microsoft-windows/

**Comment by brianteeman** [comment]
So it's still a problem for chrome?

**Comment by 810** [comment]
now its fixed:

wdw

**Comment by brianteeman** [comment]
Reop

**Comment by brianteeman** [comment]
Reopened for further testing

**Comment by 810** [comment]
any update please

**Comment by franz-wohlkoenig** [comment]
should this PR be tested?

**Comment by 810** [comment]
yes please,

but we are waiting for approval of this pr

**Comment by franz-wohlkoenig** [comment]
I have tested this item :red_circle: unsuccessfully on 1a4146ba4a1642b951c0c55303c5844621e309e9<br /><br />Switch from utf8_general to utf8mb4-general, copied "Pale Emojis" from http://getemoji.com/ in Article:

- In masOS Sierra colored emoji's are shown in Firefox 50, Safari 10, Chrome 55.
- In Windows Server 2008 black colored emoji's are shown in Firefox 45.0.1, IE11<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9956">issues.joomla.org/tracker/joomla-cms/9956</a>.</sub>

**Comment by johnnydement** [comment]
I would suggest to go with emojione.com integration, there're free, CC, Open source standard and continuosly in development, they have several ways to integrate, would be great to have a homogeneous set, ascii ones don't always look too good... nor have skin tones (last time I checked them)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9956">issues.joomla.org/tracker/joomla-cms/9956</a>.</sub>

**Comment by brianteeman** [comment]
It has been a long time since this was proposed. It's not really going anywhere fast due to browser support issues and it's hardly a required feature.

**Pull request closed without merging**
