### PR TITLE
Remove the never working limitstart call

### PR DESCRIPTION
**Pull request by zero-24**
### Summary of Changes

Remove the never working limitstart call. I did go back in the history and that not working call is included since the intial commit to GitHub:
https://github.com/joomla/joomla-cms/blame/56fbf2c55293b3188c7d85163dfcf91eac01741c/components/com_content/helpers/icon.php#L106-L110

Intial report by @moira-lachesis

### Testing Instructions

Confirm that the print button in the frontend still works.

### Expected result

The print button in the frontend still works.

### Actual result

The print button in the frontend works but append a empty an unused `&page=`.

### Documentation Changes Required

None.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on d39631bbb1c931efd07f93f73c631b9c8b5b3d95<br /><br />tested on a single and a multipage article and apart from the page= now being removed it all works the same<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17184">issues.joomla.org/tracker/joomla-cms/17184</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on d39631bbb1c931efd07f93f73c631b9c8b5b3d95<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17184">issues.joomla.org/tracker/joomla-cms/17184</a>.</sub>

**Comment by ghost** [comment]
RTC after two successful tests.

**Comment by zero-24** [comment]
@mbabker I'm not sure what happend here if you have a few minutes please check this.

**Comment by mbabker** [comment]
You started the PR based on staging then changed the branch to 3.8.  But your staging branch is a few commits ahead of the 3.8 branch (expected, the commits in this PR aren't merged to 3.8 yet).  So it's fine for now, I just have to remember to merge staging to 3.8 before merging this PR.

**Comment by zero-24** [comment]
Thans for checking!

**Comment by mbabker** [comment]
Manually applied https://github.com/joomla/joomla-cms/pull/17184/commits/d39631bbb1c931efd07f93f73c631b9c8b5b3d95 to staging at https://github.com/joomla/joomla-cms/commit/129748118638c80b6d07e8d51114eb3fe1816694 since things were still out of whack after dealing with the branch stuff.

**Pull request closed without merging**
