### PR TITLE
[4.0][On Hold] Replace chosen with choices js

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # .

### Summary of Changes
- Introduce Choices.js: https://github.com/jshjohnson/Choices
- Replace chosen in the the category on the fly field
- Chosen will still be shipped (aim is that core will not use it in J4)
- Needs styling to match the templates

### Testing Instructions
Edit an article and try to insert a category on the fly:
screen shot 2017-05-09 at 18 24 31

ATM there is a PHP error for `Table Category not supported. File not found.` So @laoneo and @joomdonation I think is related to namespacing...

### Documentation Changes Required

UPD. This is on hold till we send a PR upstream for: https://github.com/jshjohnson/Choices/issues/163

### CODE REVIEW

**Comment by Bakual** [comment]
> Chosen will still be shipped (aim is that core will not use it in J4)

What about deprecate in J3.8 and remove chosen with J4 but add choices into J3.8 (or 3.9) so extensions could already use it? Imho there isn't much point dragging chosen along the whole J4.
Or is there a reason you want to keep it?

**Comment by dgt41** [comment]
@Bakual choices are not IE8 compatible...

**Comment by joomdonation** [comment]
@dgt41 That's a problem with the choice of creating model object directly from the class. I made a temp fix https://github.com/dgt41/joomla-cms/pull/53 for now. The backend team needs to find a proper solution for it later

**Comment by dgt41** [comment]
@joomdonation it works nicely now, thanks!

**Comment by Bakual** [comment]
> choices are not IE8 compatible...

@dgt41 So what? As long as core doesn't use it, it's no problem to include it in J3.8/9. We're not breaking B/C here. As for 3rd party extensions using it, it's up to them if they want to support IE8 or not. They don't have to support the same browsers as core does.

**Comment by C-Lodder** [comment]
@dgt41 - Oh forgot to say, have you deprecated chosen in 3.x?

**Comment by dgt41** [comment]
@C-Lodder nope: https://github.com/joomla/joomla-cms/blob/staging/libraries/cms/html/formbehavior.php#L40

**Comment by ciar4n** [comment]
I have tested this item :white_check_mark: successfully on bd6779ff852b6d229a2672216095d25957bf6d34<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15916">issues.joomla.org/tracker/joomla-cms/15916</a>.</sub>

**Comment by dgrammatiko** [comment]
Closing here, we  will try to create a custom element tag that will satisfy all our needs (accessibility, drag and drop, etc)

**Pull request closed without merging**
