### PR TITLE
[fields] content plugin description

### PR DESCRIPTION
**Pull request by brianteeman**
Improve the english of the plugin description

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 366ae849eee393ec72b75087222e68196b6ffac4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14547">issues.joomla.org/tracker/joomla-cms/14547</a>.</sub>

**Comment by Twincarb** [comment]
I have tested this item :white_check_mark: successfully on 366ae849eee393ec72b75087222e68196b6ffac4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14547">issues.joomla.org/tracker/joomla-cms/14547</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC as there are 2 successfully Tests?

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14547">issues.joomla.org/tracker/joomla-cms/14547</a>.</sub>

**Pull request merged**
