### PR TITLE
[4] Remove unused file

### PR DESCRIPTION
**Pull request by PhilETaylor**
### Summary of Changes

Deleted the file as per the instructions contained in the file:

```
// @TODO Remove when webcomponents get merged into the core
```

### Testing Instructions

Im guessing.. paging @dgrammatiko our resident Webcomponents expert... 

Install Joomla. Create some validation errors on installing Joomla on purpose.

### CODE REVIEW

**Comment by brianteeman** [comment]
it is referencing a layout that doesnt exist 
`
		return LayoutHelper::render('installation.template.html.system.message', $displayData);`

**Comment by PhilETaylor** [comment]
@brianteeman Further reason to delete this file then right?

**Comment by dgrammatiko** [comment]
Probably the todo is wrong but this PR is looking fine

**Comment by richard67** [comment]
It would have to be added to the list of files to be deleted in script.php .. but maybe it's better if we do that later with the tool which is in development before @wilsonge builds the RC.

**Comment by PhilETaylor** [comment]
Did you miss the fact this is in the installation folder? Does that make a difference?

**Comment by wilsonge** [comment]
Merging on review. Indeed as installation nothing will go into script.php :)

**Comment by richard67** [comment]
Ahh good .. installation :-) sometimes we are lucky

**Pull request merged**
