### PR TITLE
[#33765] Add fast check for image orientation

### PR DESCRIPTION
**Pull request by itbra**
Detecting an image's orientation (landscape, portrait, etc) may become a repetitive task when is comes to decide which values to set for width and height to the resize() method. I found my self in need to know if the images i process are in landscape or portrait or (rather rarly) in square format. As a first step i coded this check whereever i needed it which i found pretty unhandy. Querying this information from the JImage class statically like is possible with the getImageFileProperties() method was a very helpful faster solution.

At another stage (when preparing my view) i found myself again require to know an image's orientation to apply a CSS class. As can be seen the need for this information is there which is why i add this pull request including the 3 new methods: isCubic(), isLandscape(), isPortrait().

**Test Instructions** (mabe somebody experienced is willing to adopt it into the image test class?

```
1. Create the helper class file from this PR under JPATH_LIBRARIES . '/joomla/image/helper.php'

2. In JPATH_LIBRARIES . '/joomla/image/image.php' method `getImageFileProperties()` replace

// Build the response object.
$properties = (object) array(
    'width' => $info[0],
    'height' => $info[1],
    'type' => $info[2],
    'attributes' => $info[3],
    'bits' => isset($info['bits']) ? $info['bits'] : null,
    'channels' => isset($info['channels']) ? $info['channels'] : null,
    'mime' => $info['mime']
);

return $properties;

with

return JImageHelper::getImageFileProperties($path);

as wished by @dongilbert.

3. Take any file e.g. the currently active template's index.php and at the very top 
right below `defined('_JEXEC') or die;` paste this code:

// Define the file to use. 
// NOTE:   Make sure this file exists or use another path to an existing image file!
$file = JPATH_BASE . '/images/powered_by.png';

echo '<pre>file: ' . print_r($file, true) . '</pre>';
echo '<pre>' . print_r(str_repeat('_', 51), true) . '</pre>';

// Get instance of JImage.
$image = new JImage($file); // $image must be instance of JImage

// Get image properties calling static method from JImageHelper.
$props = JImageHelper::getImageFileProperties($file);   // $props must be an object

echo '<pre>props: ' . print_r($props, true) . '</pre>';
echo '<pre>' . print_r(str_repeat('_', 51), true) . '</pre>';

echo '<pre>' . print_r('Check for every property separately:', true) . '</pre>';
echo '<pre>' . print_r(str_repeat('_', 51), true) . '</pre>';

// Check the returned data contains all of these properties.
foreach (array(
   'width',
   'height',
   'type',
   'attributes',
   'bits',
   'channels',
   'mime',
   'filesize',
   'orientation') as $p
)
{
    if (array_key_exists($p, $props))
    {
        echo "<pre>{$p} is: " . print_r($props->$p, true) . '</pre>';
    }
    else
    {
        echo '<pre>' . print_r("\$props does not contain {$p}-data", true) . '</pre>';
    }
}

echo '<pre>' . print_r(str_repeat('_', 51), true) . '</pre>';
jexit('Done');

The expected output should be:

file: /path/to/joomla/images/powered_by.png
___________________________________________________
props: stdClass Object
(
    [width] => 150
    [height] => 35
    [type] => 3
    [attributes] => width="150" height="35"
    [bits] => 8
    [channels] => 
    [mime] => image/png
    [filesize] => 2301
    [orientation] => landscape
)
___________________________________________________
Check for every property separately:
___________________________________________________
width is: 150
height is: 35
type is: 3
attributes is: width="150" height="35"
bits is: 8
channels is: 
mime is: image/png
filesize is: 2301
orientation is: landscape
___________________________________________________
Done
```

Any feedback is welcome.

### CODE REVIEW

**Comment by itbra** [comment]
Anyone to take some minutes to test this feature? The testing procedure is well documented at the associated [github item](https://github.com/joomla/joomla-cms/commit/2f7d3148acf722d1794bfbeef4a2ebeed9efb258 "Read test instructions") and really takes very less time.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/3568">issues.joomla.org/joomla-cms/3568</a>.</sub>

**Comment by itbra** [comment]
Sorry for the wrong link. [Here is the correct one](https://github.com/joomla/joomla-cms/pull/3568 "Read test instructions").<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/3568">issues.joomla.org/joomla-cms/3568</a>.</sub>

**Comment by zero-24** [comment]
@itbra sorry for the delay.

I have just tested it but i'm not exactly sure if it is a successful test?

I have add your code form here: https://github.com/joomla/joomla-cms/pull/3568#issue-32916258

The result is:
```file: [Joomla Root]/images/powered_by.png orientation from JImage: landscape fileProperties contains width: 1 fileProperties contains height: 1 fileProperties contains type: 1 fileProperties contains attributes: 1 fileProperties contains bits: 1 fileProperties contains channels: 1 fileProperties contains mime: 1 fileProperties contains filesize: 1 fileProperties contains orientation: 1 orientation from JImageHelper: landscape`
```

Is this the correct one?

**Comment by roland-d** [comment]
@test The orientation is returned as expected but I also wonder like @zero-24 if the rest of the info is correct, it looks wrong to me.

On another note, I don't understand why the code is in a helper file and not just in JImage? Is it just because so you can't get the static value of the orientation? To me, it would be nicer to just have one class handling the image information.

**Comment by itbra** [comment]
*@zero-24* and *@roland-d* which Joomla! version did you test against? I remember that everything worked fine and the results were as expected when i implemented my code. I guess that otherwise there would've been more complaints since then.

*@roland-d* If you read the whole discussion you'll notice that i initially added my solution to class `JImage`. The original author *@dongilbert* asked me on **on 7 May 2014** to move it over to `JImageHelper`.

**Comment by zero-24** [comment]
@test successful with the last stat of the test instructions. Thanks @itbra

**Comment by roland-d** [comment]
@itbra Thanks for the explanation, I saw that @dongilbert asked you to move it to a helper class. I was just asking what the reason behind it is. I don't see the advantage of it.

**Comment by itbra** [comment]
Neither do I. But since I just wanted to see this feature getting merged soon I just did what I was asked for. Unfortunately it isn't yet merged.

**Comment by roland-d** [comment]
@itbra It wasn't merged because there were no tests, now there are 2 tests by myself and @zero-24 so that is OK. However I do question the usage of the helper file. Either we make it 1 file and merge it like that, otherwise I will consult with the PLT to see if it needs to be a single file or needs a helper file.

**Comment by itbra** [comment]
Whatever fits and suits the merge requirements.

**Comment by roland-d** [comment]
@wilsonge @Bakual Can you guys please answer if the change should be in a helper file or the main JImage file? My preference goes to the main JImage file.

**Comment by Kubik-Rubik** [comment]
I would be fine with the helper class. +1

> As a rule of thumb, helpers should contain functionality that is common but has no special designation under the overall architecture of the application.
>
> - Suffix the classname with Helper
> - Use static methods whenever possible

*http://stackoverflow.com/questions/7064867/helper-class-in-php*

Developers could easily use the helper classes in their own extensions without having to instantiate a JImage object.

**Comment by Bakual** [comment]
I don't care either way.
JImage is more used to actually change the image in some way. While this proposed code only reads information from the image.

**Comment by roland-d** [comment]
Thanks guys, merged in c41fcf0

**Comment by smz** [comment]
well... I don't know and it is now surely too late, but my 2 cents are that a new helper class for 2 methods that could had fit in JImage without breaking anything is... over-engineering

**Comment by smz** [comment]
... and I think all those  `@since       __DEPLOY_VERSION__` are wrong...

**Comment by Bakual** [comment]
@smz Can you do a PR please? It's never to late to change something as long as it isn't released yet.
The `__DEPLAY_VERSION__` stuff sure is wrong.

**Comment by smz** [comment]
@Bakual Of course! Will do ASAP (later today...)

**Comment by smz** [comment]
New PR fixing some issues in this: #7060

**Pull request closed without merging**
