### PR TITLE
[4] revert #33145

### PR DESCRIPTION
**Pull request by PhilETaylor**
revert #33145

as per https://github.com/joomla/joomla-cms/pull/33145#issuecomment-844510261

### CODE REVIEW

**Comment by wilsonge** [comment]
Marking as RB because I don't want to ship the RC next Tuesday without this. But I'm holding from just merging on review until I test what was up with the original issue - and trying to find out why this workaround fixed it.

**Comment by PhilETaylor** [comment]
Sorry.

**Comment by wilsonge** [comment]
Don't worry! You did what you thought was right! And you're doing more than enough in so many other areas of the code base that I'd never have gotten around to!!

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 190424974e38ec51fdc1df80fb7d3a57016a508f<br /><br />Marking as successful based on it doing what it says<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33993">issues.joomla.org/tracker/joomla-cms/33993</a>.</sub>

**Comment by richard67** [comment]
@wilsonge Please check if you prefer this one here pr the other PR #34043 .

**Comment by PhilETaylor** [comment]
Closed in favour of https://github.com/joomla/joomla-cms/pull/34043

**Pull request closed without merging**
