### PR TITLE
Directly set $feed_email in configuration.php created during installation

### PR DESCRIPTION
**Pull request by wojsmol**
Hello
IMHO configuration.php created during the installation should not differ as to set the value of this created after saving the global settings without making any changes immediately after installation. This PR sets a the default setting that display RSS email address = author. If PR #7411 by @pe7er to be approved before my then this PR will need to be adjusted.

### CODE REVIEW

**Comment by zero-24** [comment]
@wojsmol here is just a CS fix that removes the whitespace: https://github.com/wojsmol/joomla-cms/pull/1

**Comment by wojsmol** [comment]
@zero-24 CS PR marget

**Comment by farrelljsec** [comment]
I have tested this item :white_check_mark: successfully on b71eeb24792231d67677232d5879956504b99a21<br /><br />It works, but not good to show the author email address.
Better would be: public $ feed_email = 'none';<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7911">issues.joomla.org/joomla-cms/7911</a>.</sub>

**Comment by zero-24** [comment]
@wojsmol can you implement the suggestion by @farrelljsec ? If that is done please ping me so i can do the seccond test :smile: Thanks.

**Comment by wojsmol** [comment]
@zero-24 change made, @farrelljsec thanks for testing :smile:

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on fd462bc67e7caf5dfbef0f8e8745d0d4dde02e7f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7911">issues.joomla.org/joomla-cms/7911</a>.</sub>

**Comment by zero-24** [comment]
Just alterd @farrelljsec test as we just implement the suggestion and add my test. So we are complete to RTC. Thanks :smiley: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7911">issues.joomla.org/joomla-cms/7911</a>.</sub>

**Pull request merged**
