### PR TITLE
[4.0] [plg_system_stats] Move fields to subdirectory

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Moves fields of `plg_system_stats` to `src` subdirectory to avoid case sensitivity issues when upgrading from J3.

### Testing Instructions

Apply patch. Delete `libraries/autoload_psr4.php` file.
Edit System - Joomla! Statistics plugin. Check that `Select here to see the information that will be sent.` text and `Reset Unique ID` button still appear.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 16b67ca930cb645f60a3f7ba861502773a3de157<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27630">issues.joomla.org/tracker/joomla-cms/27630</a>.</sub>

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on 16b67ca930cb645f60a3f7ba861502773a3de157<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27630">issues.joomla.org/tracker/joomla-cms/27630</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27630">issues.joomla.org/tracker/joomla-cms/27630</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
