### PR TITLE
com_installer discover view: searchtools ordering and some improvements

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Description

This PR adds, for consistency, as it exists in so many other views in the backoffice, the order select box of the search tools to com_installer discover view.

Also:
- now discovers the extensions by default onload (if not discovered before).
- the columns were reordered to match the "Manage" view.
- corrects bug where the folder filter has not selecting the search button, and other small graphical issues.
###### Before PR

image
###### After PR

image
#### How to test
1. Install latest staging and apply this patch
2. Go to the database "prefix_extensions" table and delete the "beez3" and "hathor" rows (or other if you want).
3. Go to Extensions -> Manage -> Discover (you will see hathor and beez3 there)
4. Check the search, ordering select box and the filter are working fine.
5. Test desktop, tablet and mobile view (ex: reduce browser width).
6. Install hathor and beez here and check if ok.

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on c42375c4f9043ac32c5827462f750260df9a926e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9114">issues.joomla.org/joomla-cms/9114</a>.</sub>

**Comment by grhcj** [comment]
I have tested this item :white_check_mark: successfully on c42375c4f9043ac32c5827462f750260df9a926e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9114">issues.joomla.org/joomla-cms/9114</a>.</sub>

**Comment by brianteeman** [comment]
RTC - thanks for testing<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9114">issues.joomla.org/joomla-cms/9114</a>.</sub>

**Comment by andrepereiradasilva** [comment]
This one needs similiar changes like the ones made yesterday in https://github.com/joomla/joomla-cms/pull/9118.

This changes can solve the problem with translatable columns results (Location, Type and Folder). They are incorrected sorted in some languages (depending on the translation), also, location is always incorrected sorted because as it is now is sorting by client id, not the client translate text.

This problem existed before this PR, but i think i can solve this in this PR too if you guys are willing to test again after the changes.

**Comment by richard67** [comment]
@andrepereiradasilva If I have time I am willing to test again, sure. But this PR is already RTC, so it might get merged before you can provide the changes. In this case, if you make a new PR then, let me know here so I find it and can help with testing.

**Comment by grhcj** [comment]
@andrepereiradasilva Please let me know me when you changed this behaviour.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9114">issues.joomla.org/joomla-cms/9114</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@richard67 @grhcj ok, should be good now, please retest.

A change like this is also needed in com_installer manage and updatesites view, but that's a new PR.

**Comment by andrepereiradasilva** [comment]
@richard67 @grhcj ok, should be good now, please retest.

A change like this is also needed in com_installer manage and updatesites view, but that's a new PR.

**Comment by richard67** [comment]
I go sleep now, I'll test tomorrow if still necessary then. Good night.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on d14ddda718c6108ebbe377c32110c60404346fdc<br /><br />Works still as desired plus sorting by Location is alphabetic now, tested English, German (which is same as English at this point and so not a good example for this test) and Russian (for which I could look up the alphabet at Wikipedia, I do not understand Russian).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9114">issues.joomla.org/joomla-cms/9114</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@richard67 when i say German is because the "Type" column. Although it seems is correctly ordered before this last change, it isn't.

It's true that in com_installer discover view is not easy to check (you would have to have a lot of discovered extensions of several types).

But you can see what i mean by going to manage (or update sites) view. In the "Type" column "Library" in english is "Bibliothek" in german so should be ordered in a different way.

Either way thanks for the test.

**Comment by richard67** [comment]
@andrepereiradasilva Ok, thanks for the clarification. I have repeated my test with extensions of diverse type and can confirm that the Type column is now sorted alphabetically while before it was not, so my successful test result is still valid.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9114">issues.joomla.org/joomla-cms/9114</a>.</sub>

**Comment by grhcj** [comment]
I have tested this item :white_check_mark: successfully on d14ddda718c6108ebbe377c32110c60404346fdc<br /><br />Still works as expected (in desktopk, tablet and mobile view).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9114">issues.joomla.org/joomla-cms/9114</a>.</sub>

**Comment by wilsonge** [comment]
Merged - thanks!

**Pull request closed without merging**
