### PR TITLE
[4.3] Revert 38576

### PR DESCRIPTION
**Pull request by joomdonation**
Pull Request for Issue # .

### Summary of Changes
This PR reverts https://github.com/joomla/joomla-cms/pull/38576 , solves the release blocker https://github.com/joomla/joomla-cms/issues/40052. The original change to the file administrator/components/com_tags/src/Table/TagTable.php is valid, only change to the file libraries/src/Table/ContentType.php is wrong . However, due to the limitation of the current tag routing, we require each tag to have unique alias, so I revert the the whole PR.

### Testing Instructions
1. Use Joomla 4.3-dev 
2. Try to install Hikashop extension which can be downloaded below
[com_hikashop_starter_v4.7.1_2023-03-09_15-53-14.zip](https://github.com/joomla/joomla-cms/files/10932896/com_hikashop_starter_v4.7.1_2023-03-09_15-53-14.zip)

### Actual result BEFORE applying this Pull Request
You got error: Missing field in database: Joomla\CMS\Table\ContentType &#160; alias.

### Expected result AFTER applying this Pull Request
No error, the extension was installed properly.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 2ca9256a4acbb930e2611233fd69f6d495b56509<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40060">issues.joomla.org/tracker/joomla-cms/40060</a>.</sub>

**Comment by obuisard** [comment]
I have tested this item :white_check_mark: successfully on 2ca9256a4acbb930e2611233fd69f6d495b56509<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40060">issues.joomla.org/tracker/joomla-cms/40060</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40060">issues.joomla.org/tracker/joomla-cms/40060</a>.</sub>

**Comment by obuisard** [comment]
Thank you Tuan @joomdonation for the PR!

**Pull request merged**
