### PR TITLE
Inject the database into the installer script when possible

### PR DESCRIPTION
**Pull request by laoneo**
### Summary of Changes
Injects the database into the installer script when possible. Like that installer scripts can access the database without loading it through the factory class.

### Testing Instructions
Install any extension.

### Actual result BEFORE applying this Pull Request
All works.

### Expected result AFTER applying this Pull Request
All works.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
surely this is a new feature so must be for J5 and require documentation

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on 6ae40efab95602bd46e4ce0a4f34b0f52aa8ff37<br /><br />Tested successfully in Joomla 4.4.0-dev of 5 May using Wampserver 3.3.1 and PHP 8.2.6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40724">issues.joomla.org/tracker/joomla-cms/40724</a>.</sub>

**Comment by sandewt** [comment]
> Install any extension.

I installed an extension and it works. The extension is installed.

Can I do an extra check, for example if $this->getDabase() can actually be loaded? Or is not that necessary?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40724">issues.joomla.org/tracker/joomla-cms/40724</a>.</sub>

**Comment by laoneo** [comment]
Your installer script needs to use the db aware interface. Then $this->getDatabase() should be filled. If you can test this, that would be perfect.

**Comment by laoneo** [comment]
Good catch, had to proxy the legacy installer class as well. Can you try again?

**Comment by sandewt** [comment]
I have tested this item :white_check_mark: successfully on d58bbc842ec1732c08b041611fd5d94cd9a26901<br /><br />> I have tried something like this in the installer script.php file of mod_readingbar (= test module)

script.php works now<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40724">issues.joomla.org/tracker/joomla-cms/40724</a>.</sub>

**Comment by laoneo** [comment]
@toivo can you test this again with your extension? Thanks

**Pull request merged**
