### PR TITLE
[com_fields] Set the catid value on the category when showing the fields

### PR DESCRIPTION
**Pull request by laoneo**
Pull Request for Issue #14375.

### Summary of Changes
For categories only the fields are considered, which belong to this category when editing a category or showing a category.

### Testing Instructions
- Create an article category with the name Test
- Create a field "Demo1" with the **Category** context for "All" categories
image
- Create a second field  "Demo2" with the **Category** context and assign it to the "Test" category
- Create a third field  "Demo3" with the **Category** context and assign it to the category "Uncategorized"
- Edit the category Test

### Expected result
Only the fields "Demo1" and "Demo2" should be shown in the Fields tab.

### Actual result
The fields "Demo1" and "Demo3" are shown.

Additionally in the Articles List menu item, the correct fields are displayed.

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on f7b0c3d739a633d5a27642495adfb619ba157db9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14399">issues.joomla.org/tracker/joomla-cms/14399</a>.</sub>

**Comment by AlexRed** [comment]
I have tested this item :white_check_mark: successfully on bd93dccf3cc4341aaa64d1dde536c8919e9a5301<br /><br />Patch ok for me<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14399">issues.joomla.org/tracker/joomla-cms/14399</a>.</sub>

**Comment by laoneo** [comment]
@franz-wohlkoenig can you please test it again.

@AlexRed thanks!

**Comment by franz-wohlkoenig** [comment]
I have tested this item :red_circle: unsuccessfully on bd93dccf3cc4341aaa64d1dde536c8919e9a5301<br /><br />Categorie-Fields "Demo1", "Demo2" are shown, but Value of Fields isn't saved.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14399">issues.joomla.org/tracker/joomla-cms/14399</a>.</sub>

**Comment by laoneo** [comment]
Did you use the latest staging? There was a bug which is fixed with https://github.com/joomla/joomla-cms/commit/9e4b281f5707cd20f8d3653ae81cd33c11edef26. Make sure you have that one.

**Comment by franz-wohlkoenig** [comment]
latest nightlybuild is installed.

**Comment by laoneo** [comment]
Fix was merged today, it will be part in the next nightly.

**Comment by laoneo** [comment]
@franz-wohlkoenig can you test it again please, it should work now? Thanks.

**Comment by franz-wohlkoenig** [comment]
Same: Categorie-Fields "Demo1", "Demo2" are shown, but Value of Fields isn't saved; latest nightlybuild is installed; all Fields and Category are new created.

**Comment by laoneo** [comment]
I'v just tested it and it worked with the latest staging.

**Comment by laoneo** [comment]
Can you make a screencast, about how it works on your end? There is no reason why it shouldn't.

**Comment by franz-wohlkoenig** [comment]
i will reinstall first, that helped some time ago.

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 7d0f4740bf0b613cbd585ed0192160b4029ee538<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14399">issues.joomla.org/tracker/joomla-cms/14399</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
@AlexRed can you please retest?

**Comment by AlexRed** [comment]
I have tested this item :white_check_mark: successfully on 7d0f4740bf0b613cbd585ed0192160b4029ee538<br /><br />Patch ok for me<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14399">issues.joomla.org/tracker/joomla-cms/14399</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14399">issues.joomla.org/tracker/joomla-cms/14399</a>.</sub>

**Pull request merged**
