### PR TITLE
[5.1] Fix error in media field, add missing dependency in media-select field

### PR DESCRIPTION
**Pull request by Fedik**
### Summary of Changes
Fix for https://github.com/joomla/joomla-cms/issues/43022

Add missing dependency in media-select field

### Testing Instructions
Run `npm install`.

Edit template settings on frontend, try select a logo.

### Actual result BEFORE applying this Pull Request
nothing works

### Expected result AFTER applying this Pull Request
works

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed
- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Kostelano** [comment]
I have tested this item :white_check_mark: successfully on 8f06074e4677fd036cafe2fa1bb412e09a434e9f<br /><br />Works!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43080">issues.joomla.org/tracker/joomla-cms/43080</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 8f06074e4677fd036cafe2fa1bb412e09a434e9f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43080">issues.joomla.org/tracker/joomla-cms/43080</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43080">issues.joomla.org/tracker/joomla-cms/43080</a>.</sub>

**Comment by LadySolveig** [comment]
Thank you @Fedik and also for testing @Kostelano @viocassel

**Pull request merged**
