### PR TITLE
Correcting Beez3 search and smartsearch display

### PR DESCRIPTION
**Pull request by infograf768**
See https://github.com/joomla/joomla-cms/issues/8425

As Beez is not fully boostrap compatible, we have to use for Search the word itself.
Calendar has its proper replacement icon in Beez.

I also corrected the wrong display of the Check boxes

I used 2 different test sites, one with the patch and one without. This explains some module positions differences in the screenshots below.

<b>Before Patch for com_search</b>

com_search_before2

<b>After patch for com_search</b>

com_search_after2

<b>Before Patch for smartsearch</b>
(Do not forget to enable Date filtering in SmartSearch Component Parameters to show the calendar field)

screen shot 2015-11-18 at 17 39 22

<b>After patch for smartsearch</b>

smart_search_after

### CODE REVIEW

**Comment by fontanil** [comment]
I have tested this item :white_check_mark: successfully on 9eb5d9b3ce615f3d277c925de319d6d662e10675<br /><br />Tested successfully on 3.5.0 beta1
Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8480">issues.joomla.org/joomla-cms/8480</a>.</sub>

**Comment by waader** [comment]
I have tested this item :white_check_mark: successfully on 9eb5d9b3ce615f3d277c925de319d6d662e10675<br /><br />Much better now. Thanks infograf768!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8480">issues.joomla.org/joomla-cms/8480</a>.</sub>

**Comment by zero-24** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8480">issues.joomla.org/joomla-cms/8480</a>.</sub>

**Comment by infograf768** [comment]
@waader @fontanil 
This also solved the scroll bar issue (forgot to tell :smile: ) See https://github.com/joomla/joomla-cms/pull/8487 where I solve this for Protostar

**Pull request merged**
