### PR TITLE
Elude Warning

### PR DESCRIPTION
**Pull request by vzenix**
Warning: Invalid argument supplied for foreach() in C:\inetpub\wwwroot\Abogados\trunk\libraries\joomla\database\driver.php on line 1492

### CODE REVIEW

**Comment by brianteeman** [comment]
Please provide details how someone can replicate this bug so that they can
check the fix.

Also what database engine are you using?

**Comment by vzenix** [comment]
Server SQL: SQL Server 2008 R2
Web Serer: IIS 7
Joomla Versión: 3.3.6

This is  for prevent bad use of this function in third party components or bugs of external components.

**Comment by zero-24** [comment]
@vzenix Travis fails on this PR

```php

There was 1 failure:
1) JDatabaseDriverTest::testQuoteName
Tests the left-right quotes on an object.
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
-    0 => '[a]'
-    1 => '[test]'
 )
/home/travis/build/joomla/joomla-cms/tests/unit/suites/libraries/joomla/database/JDatabaseDriverTest.php:479

```

Can you have a look into it?

**Comment by vzenix** [comment]
Where i can find this test class for debug the code?

I search in all source file but can't find this?.

**Comment by rdeutz** [comment]
you need to check out the repository and then it is in "tests/unit/suites/libraries/joomla/database/JDatabaseDriverTest.php" or look here https://github.com/joomla/joomla-cms/blob/staging/tests/unit/suites/libraries/joomla/database/JDatabaseDriverTest.php

**Comment by Hackwar** [comment]
In any case, this means that it is a break in backwards compatibility.

**Comment by brianteeman** [comment]
Thank you for your contribution but it has been decided that this is not something that will be included in the core of Joomla.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5946">issues.joomla.org/joomla-cms/5946</a>.</sub>

**Pull request closed without merging**
