### PR TITLE
Update en-GB.com_contact.ini

### PR DESCRIPTION
**Pull request by MartijnMaandag**
Makes the text the same as in articles (better for helpscreen documentation).

Pull Request for Issue # .

### CODE REVIEW

**Comment by brianteeman** [comment]
Personally I would do it the other way

**Comment by MartijnMaandag** [comment]
I don't (What to do with "Show Category", Show Contact List" and "Show User Articles" in Contacts and what to do with "Show Intro Text", "Show Category", "Show Parent", "Show Associations", "Show Author", "Show Title" ......... in Articles?)

**Comment by brianteeman** [comment]
https://github.com/joomla/joomla-cms/issues/17178

**Comment by brianteeman** [comment]
Personally the strings should be without show if the options are show/hide and with if the options are yes/no
eg
Show Info yes/no
Info Show/hide

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 93c4275e4e6a79b3676875352836966606c0d65a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18405">issues.joomla.org/tracker/joomla-cms/18405</a>.</sub>

**Comment by ghost** [comment]
set this Pull Request as "Easy Test".<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18405">issues.joomla.org/tracker/joomla-cms/18405</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 93c4275e4e6a79b3676875352836966606c0d65a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18405">issues.joomla.org/tracker/joomla-cms/18405</a>.</sub>

**Comment by ghost** [comment]
RTC after two successful tests.

**Comment by brianteeman** [comment]
For reference all the Show ABC strings have been changed in J4 to remove the word show in favour of using show/hide for the value instead of yes/no

**Comment by mbabker** [comment]
Looking at it in context, I think for 3.x for consistency we might be better off merging this, but to be honest I don't have a strong opinion either way (either keeping as is or merging).

Ping @joomla/cms-maintainers if someone's got an opinion either way make a call.

screen shot 2018-01-15 at 9 12 21 am

**Comment by brianteeman** [comment]
As they have all been changed to not use the word show in j4 it seems silly to change it here the otherway. but no strong feeling either

**Comment by MartijnMaandag** [comment]
If it will change in J4 don't spent time in this.

**Comment by brianteeman** [comment]
ok - closing it then

**Pull request closed without merging**
