### PR TITLE
[4.0] Installer cleanup

### PR DESCRIPTION
**Pull request by brianteeman**
the ability to set the site_metadesc and the site_offline are not present in this installer

The language files hd also been removed but they were still referenced in the setup.xml

@dgrammatiko @wilsonge 
Don't forget that ftp is still marked todo
and
I wanted to try and check the pre-install screen strings but i couldnt trigger it for testing - any tips

### CODE REVIEW

**Comment by wilsonge** [comment]
For the PHP Version incompatible screen bump the PHP Version here to something stupid like PHP 8.0 https://github.com/joomla/joomla-cms/blob/4.0-dev/installation/index.php#L16

For the pre-install screen if I remember rightly you need to set one of the states https://github.com/joomla/joomla-cms/blob/4.0-dev/installation/src/Model/ChecksModel.php#L77 here to be false instead of determining a value

**Comment by brianteeman** [comment]
php version I had done. I was trying that for the pre-install screen but maybe I did something wrong - will try again in the morning - thanks

**Comment by wilsonge** [comment]
Amended link above to point to the 4.0 branch instead of staging branch! Just tested now and changing that line to be false definitely triggers the screen for me

**Comment by brianteeman** [comment]
ok - thanks

**Comment by wilsonge** [comment]
Merging this one in the mean time! Thanks!

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
