### PR TITLE
Fix table breakpoint in Maintenance: Database view

### PR DESCRIPTION
**Pull request by RickR2H**
### Summary of Changes
The table with the database info in the Maintenance: Database view is to wide on some breakpoints.

### Testing Instructions
Go to System -> Maintenance - Database
Set screen size to 800px
Refresh the page an see ie table fits

### Actual result BEFORE applying this Pull Request
Image 2

### Expected result AFTER applying this Pull Request
Image 4

### Documentation Changes Required
No

### CODE REVIEW

**Comment by ceford** [comment]
Almost all of the tables in Joomla are too wide for one or more screen sizes. What happens when you rotate your device to portrait mode? Do we need to lose more columns? <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35862">issues.joomla.org/tracker/joomla-cms/35862</a>.</sub>

**Comment by RickR2H** [comment]
@ceford IMHO I think on a phone you should see only relevant information and hide all the clutter as we are on a small screen. I don't think people will maintain there sites mainly on there phone, In this case all the info to maintain and fix the database are there.

**Comment by ricardo1709** [comment]
I have tested this item :white_check_mark: successfully on 406d28f17dc27c9b74687793f541db5a4c9b8c90<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35862">issues.joomla.org/tracker/joomla-cms/35862</a>.</sub>

**Comment by rjharishabh** [comment]
I have tested this item :white_check_mark: successfully on 406d28f17dc27c9b74687793f541db5a4c9b8c90<br /><br />Marking successful test as this PR works as intended<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35862">issues.joomla.org/tracker/joomla-cms/35862</a>.</sub>

**Comment by rjharishabh** [comment]
RTC after two successful tests<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35862">issues.joomla.org/tracker/joomla-cms/35862</a>.</sub>

**Comment by bembelimen** [comment]
I really hate, that we hide data instead of having a proper responsive solution, but till this happen, we have to go this way...

**Comment by bembelimen** [comment]
Thx

**Comment by simbus82** [comment]
> I really hate, that we hide data instead of having a proper responsive solution, but till this happen, we have to go this way...

You are right, but for now is a good solution. Maybe in future on mobile we can put a "more info" button and show all "row missing data" in a modal popup..

**Pull request merged**
