### PR TITLE
[4.0] Full Image class hint

### PR DESCRIPTION
**Pull request by brianteeman**
Based on feedback and user requests this simple pr adds a hint for the type of class you can add in the image class for the full article image

cc @softforge

image

### CODE REVIEW

**Comment by softforge** [comment]
Even those that know how to use classes can have a senior moment so such class hints are really helpful. Its a half way hose to the hard coded way we had in J3 that had left and right switch and the universal way to allow any styling to be added

**Comment by brianteeman** [comment]
please test and report results

**Comment by dgrammatiko** [comment]
@brianteeman could you add is also here https://github.com/joomla/joomla-cms/blob/7978f281c49276756cd6fe6faa61a8c30ec77a53/build/media_source/system/js/fields/joomla-media-select.w-c.es6.js#L408-L411

Something like 
```html
    <div class="input-group">
      <label class="input-group-text" for="${this.parentId}-classes">${this.classestext}</label>
      <input class="form-control" type="text" id="${this.parentId}-classes" data-is="img-classes"/>
      <small for="${this.parentId}-classes">${Joomla.Text._('JLIB_FORM_MEDIA_IMAGE_CLASS_DESC')}</small>
    </div>
```
and adding the text here https://github.com/joomla/joomla-cms/blob/7978f281c49276756cd6fe6faa61a8c30ec77a53/layouts/joomla/form/field/media.php#L143 like

```php
Text::script('JLIB_FORM_MEDIA_IMAGE_CLASS_DESC', true);

```

BTW the text needs to be in the joomla.ini

**Comment by brianteeman** [comment]
@dgrammatiko I will do that in a separate pr

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 1b57e8b9195fbfb091db1e6911564c546b0fe14b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36267">issues.joomla.org/tracker/joomla-cms/36267</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 1b57e8b9195fbfb091db1e6911564c546b0fe14b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36267">issues.joomla.org/tracker/joomla-cms/36267</a>.</sub>

**Comment by chmst** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36267">issues.joomla.org/tracker/joomla-cms/36267</a>.</sub>

**Comment by khu5h1** [comment]
I have tested this item :white_check_mark: successfully on 1b57e8b9195fbfb091db1e6911564c546b0fe14b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36267">issues.joomla.org/tracker/joomla-cms/36267</a>.</sub>

**Comment by Quy** [comment]
Thanks

**Pull request merged**
