### PR TITLE
[4.0] Grammar in lang string

### PR DESCRIPTION
**Pull request by brianteeman**
Fixes an error in a language string merged in #20192

(Please make sure that codeowners have reviewed and approved PR before merging)

### CODE REVIEW

**Comment by carlitorweb** [comment]
I have tested this item :white_check_mark: successfully on 0a7f3efac4b05b0abfe159e6f0532160b8a38cbc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20694">issues.joomla.org/tracker/joomla-cms/20694</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 0a7f3efac4b05b0abfe159e6f0532160b8a38cbc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20694">issues.joomla.org/tracker/joomla-cms/20694</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20694">issues.joomla.org/tracker/joomla-cms/20694</a>.</sub>

**Comment by zero-24** [comment]
Merged thanks!

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
