### PR TITLE
[4.0] Move form text below field

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
For consistency, move form text below field and use `form-text` class.

### Testing Instructions
Go to System > Site Templates
Click `Cassiopeia Details and Files`.
Click `Copy Template` button.

### Actual result BEFORE applying this Pull Request
copy-template-before

### Expected result AFTER applying this Pull Request
copy-template-after

### CODE REVIEW

**Comment by brianteeman** [comment]
For consistency please put the text-muted class back

**Comment by Quy** [comment]
`form-text` sets `color` and `font-size` so no need to use `text-muted`.

**Comment by Quy** [comment]
I will be doing a separate PR to remove `text-muted` from `form-text` that has this class.

**Comment by brianteeman** [comment]
image

**Comment by Quy** [comment]
I understand but why add another class to override the color. Might as well override `.form-text`.

**Comment by Quy** [comment]
Plus you can barely tell the difference without `text-muted`.

**Comment by Quy** [comment]
From [Bootstrap 5 Migration](https://getbootstrap.com/docs/5.0/migration/) page.
```
.form-text no longer sets display, but does set color and font-size. So instead of <small class="form-text text-muted"> you should now use <div class="form-text">.
```

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on e506f27d0f366c14c3b66142b1920238570dc3b0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33436">issues.joomla.org/tracker/joomla-cms/33436</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on e506f27d0f366c14c3b66142b1920238570dc3b0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33436">issues.joomla.org/tracker/joomla-cms/33436</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33436">issues.joomla.org/tracker/joomla-cms/33436</a>.</sub>

**Comment by richard67** [comment]
> I will be doing a separate PR to remove `text-muted` from `form-text` that has this class.

@Quy Trusting this, the PR is ok for me. But for consistency that really should not be forgotten.

**Pull request merged**
