### PR TITLE
[5.0] translation description text error pages

### PR DESCRIPTION
**Pull request by heelc29**
### Summary of Changes

update innerHTML of #descText1 element (translation)

### Testing Instructions

produce an error page are open any error html page directly
eg. `domain.tl/includes/incompatible.html`
switch language

### Actual result BEFORE applying this Pull Request

description text is always englisch
image

### Expected result AFTER applying this Pull Request

description is translated
image

### Link to documentations
Please select:
- [x] No documentation changes for docs.joomla.org needed
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by richard67** [comment]
@heelc29 Do we have this issue also in 4.4-dev, or only in 5.0-dev?

**Comment by heelc29** [comment]
Yes, but I decided to do it for J5 to avoid conflict with https://github.com/joomla/joomla-cms/pull/41935

**Comment by HLeithner** [comment]
Issues which appear in 4.4 have to be fixed in 4.4 (till the release of 5.2) and will be upmerged by the maintainers to 5.x.

Could you please rebase your PR for 4.4, thanks

**Comment by richard67** [comment]
@HLeithner This here is the PR, not the issue, so it should not be closed, it just needs to be rebased.

**Comment by HLeithner** [comment]
it's not possible (afaik) to rebase a joomla 5.0-dev pr to 4.4-dev branch

**Comment by richard67** [comment]
> it's not possible (afaik) to rebase a joomla 5.0-dev pr to 4.4-dev branch

@HLeithner Why should that not be possible?

**Comment by HLeithner** [comment]
because all commits from 5.0-dev which are not in 4.4-dev will be in this commit and you would update 4.4-dev branch to joomla 5.0. I switched this pr to 4.4 branch for demonstration.

**Comment by richard67** [comment]
> because all commits from 5.0-dev which are not in 4.4-dev will be in this commit and you would update 4.4-dev branch to joomla 5.0. I switched this pr to 4.4 branch for demonstration.

@HLeithner I see.

**Comment by HLeithner** [comment]
@heelc29 can you recreate the PR for 4.4 please?

**Comment by heelc29** [comment]
@HLeithner here we go #42030

**Pull request closed without merging**
