### PR TITLE
Remove explicit transparency upon PNG loading

### PR DESCRIPTION
**Pull request by n3t**
This code is IMO unnecessary, as it is called again in resize method. More over it is strange to modify image upon loading it. Issue raised here https://github.com/joomla/joomla-cms/issues/7655

---

Joomla 3.x introduced some changes to JImage class which influence quality of resized PNGs with transparency. To demonstrate it see this images:

Original
test

Resized in Joomla 2.5
j25

Resized in Joomla 3
j30

Test code to resize is

``` php
      $original = new JImage($src);
      $original->resize(140,140,false, JImage::SCALE_INSIDE);
      $original->toFile($dest,IMAGETYPE_PNG);
```

Tested on PHP 5.3.29 with GD 2.1.0 compatible, libPNG 1.6.12 
and on PHP 5.5.27 with GD 2.1.0 compatible, libPNG 1.2.49

this behavior is caused by setting explicitly transparent color in loadFile method. For some reason isTransparent() returns false in this case, so transparent color is set explicitly causing the image look like that. 

I am not sure why this code is at this place (loading image), as it seems to solve black background issue, when SCALE_FIT is used on resizing. However in resize method it is introduced again.

### CODE REVIEW

**Comment by n3t** [comment]
Any chance to get this commited? Current results of resizing transparent images are terrible looking.

**Comment by andrepereiradasilva** [comment]
@n3t this will be committed when:
- if has two successful tests.
- after the two successful tests will be labeled as RTC and the maintains decide in which version it should be merged (in the current case 3.5.x or 3.6).

So my advice is make very clear test instructions so testers can follow then to test without spending much time trying to understand what's the implications.
example: https://github.com/joomla/joomla-cms/pull/9690

Remember: there are almost 400 open PR an few volunteers are willing to do tests.

**Comment by brianteeman** [comment]
@n3t I would test this if I knew how to <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7658">issues.joomla.org/joomla-cms/7658</a>.</sub>

**Comment by n3t** [comment]
@andrepereiradasilva @brianteeman Sorry for late reply, I was quite busy.

Test instructions:

1/ Install attached package: [issue7658.zip](https://github.com/joomla/joomla-cms/files/217924/issue7658.zip)
2/ Make sure your tmp folder is writable
3/ execute CLI script test_issue_7658.php
4/ See your tmp folder for results (issue7658.trans.png, issue7658.nontrans.png and issue7658.jpg)
5/ Apply this patch and execute the CLi again
6/ See the results again and comapre mainly transparent PNG (issue7658.trans.png)
7/ Uninstall issue7658 package and purge your tmp folder

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on ee18e8ba681b8b564d49c4622ffe6e1b4c19057c<br /><br />Thanks for the detailed test instructions - made it really easy to confirm the issue and your fix<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7658">issues.joomla.org/joomla-cms/7658</a>.</sub>

**Comment by andrepereiradasilva** [comment]
Followed test instructions and the difference in issue7658.nontrans.png is clear:

Before:
issue7658 nontrans

After:
issue7658 nontrans

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on ee18e8ba681b8b564d49c4622ffe6e1b4c19057c<br /><br />As test in last comment<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7658">issues.joomla.org/joomla-cms/7658</a>.</sub>

**Comment by brianteeman** [comment]
RTC 

See what happens when you have good testing information :)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7658">issues.joomla.org/joomla-cms/7658</a>.</sub>

**Comment by n3t** [comment]
Thank you guys, next time I will get better with testing instructions from the beginning :-)

**Pull request merged**
