### PR TITLE
[4.0] Select options font-size

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #26918  

### Summary of Changes
reduce the font size used in the regular select so that it is the same (smaller) size as the one from choices.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 91bba95d4ad0dda6e02bae00403e494c1bc312a3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26983">issues.joomla.org/tracker/joomla-cms/26983</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 91bba95d4ad0dda6e02bae00403e494c1bc312a3<br /><br />Woks as described.

But to be honest, I would have preferred the bigger fonts which are shown on the unexpanded list.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26983">issues.joomla.org/tracker/joomla-cms/26983</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26983">issues.joomla.org/tracker/joomla-cms/26983</a>.</sub>

**Comment by wilsonge** [comment]
Thanks! Wondering if it would be good to explicitly set both font sizes from an SCSS variable just so it's clear to people

**Comment by brianteeman** [comment]
@wilsonge what do I know if something is a good idea or not. I only understand enough to make things work.

**Pull request merged**
