### PR TITLE
Missing verb and adjective

### PR DESCRIPTION
**Pull request by brianteeman**
The string should be

COM_CONFIG_FIELD_DATABASE_TYPE_DESC="The type of database in use, selected during the installation process. Do not edit this field unless you are migrating to a different type of database, perhaps due to changing your hosting provider."

Note that the verb "are" is missing before this PR

Also
COM_CONFIG_FIELD_DATABASE_PREFIX_DESC="The prefix used for your database tables, created during the installation process. Do not edit this field unless absolutely necessary (eg the transfer of the database to a new hosting provider)."

Note that the adjective "this" is missing before this PR

### CODE REVIEW

**Comment by brianteeman** [comment]
updated description and title

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on 8fcec807ea1d4e7558438920ddfe14cf4fb8dc8e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14651">issues.joomla.org/tracker/joomla-cms/14651</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 8fcec807ea1d4e7558438920ddfe14cf4fb8dc8e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14651">issues.joomla.org/tracker/joomla-cms/14651</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14651">issues.joomla.org/tracker/joomla-cms/14651</a>.</sub>

**Pull request merged**
