### PR TITLE
Bugfix for #6782

### PR DESCRIPTION
**Pull request by ghost**
Unfortunately, there was a little bug within #6782. See the original PR for more details. This PR should fix it.

### CODE REVIEW

**Comment by zero-24** [comment]
@nueckman this https://github.com/nueckman/joomla-cms/pull/2 should make travis a happy guy :smile:

**Comment by wilsonge** [comment]
@nueckman Can you PR this to staging as the other PR was sent to (and merged into) staging!

**Comment by wilsonge** [comment]
If you get an email from my previous message ignore it :P I made stupid comments :)

**Comment by nueckman** [comment]
Thanks @zero-24.

@wilsonge Don't worry. Life is a stupid thing ;)

**Comment by zero-24** [comment]
### How to test

- install the 3.5-dev branche: http://developer.joomla.org/cms-packages/Joomla_3.5.0-dev-Development-Full_Package.zip
- and apply this patch
- look out for a MenuItem-Field (e.g. creating a menu item with the type "alias")
- Nested items should now be prefixed with the level indicator
- make sure it still looks like this with the patch applyed:
pr-6782-screen1

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on 453f1aaab1aace48076a91919cab43b343dc5c75<br /><br />Still works as expeced. Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7148">issues.joomla.org/joomla-cms/7148</a>.</sub>

**Comment by dgt41** [comment]
I have tested this item :white_check_mark: successfully on 453f1aaab1aace48076a91919cab43b343dc5c75<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7148">issues.joomla.org/joomla-cms/7148</a>.</sub>

**Comment by zero-24** [comment]
RTC. Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7148">issues.joomla.org/joomla-cms/7148</a>.</sub>

**Pull request merged**
