### PR TITLE
Handle accepted encoding in curl correct

### PR DESCRIPTION
**Pull request by laoneo**
Curl needs the accepted encoding header set as curl option and not only as header.
## Test instructions

Add the following code to the file administrator/components/com_content/content.php after line 17

``` php
$options = new JRegistry();
$http = new JHttp($options, new JHttpTransportCurl($options));
$content = $http->get(
        'https://p20-calendars.icloud.com/published/2/L-7oRelmRSvcRxR8H-6Ni8btBd-dfx0NEh2GgZVeW1PZC1w1qHaA6-IKpUwsQ85mERNvoVjhUIgdyNwSvLelkS9DCTLKr_nLY0ZrMRD3mt4', array('Accept-Encoding'=>'deflate'))->body;
echo $content;die;
```

When you have applied the patch then you will see some ics content. If not then you will see some gzip compressed headers.

### CODE REVIEW

**Comment by Hackwar** [comment]
Please fix the codestyle issue that Travis is complaining about.

**Comment by laoneo** [comment]
Where can I find out what for a code style is wrong?

**Comment by Hackwar** [comment]
click on the details link and select one of the testruns and then scroll to the bottom.

**Comment by laoneo** [comment]
Done....

**Comment by roland-d** [comment]
@laoneo I have tested this with the code
```php
$options = new JRegistry();
$http = new JHttp($options, new JHttpTransportCurl($options));
$content = $http->get(
	'https://www.google.com/calendar/ical/en.dutch%23holiday%40group.v.calendar.google.com/public/basic.ics', array('Accept-Encoding'=>'deflate'))->body;
echo $content;die;

Without the patch I see the calendar content and with the patch I see the calendar content. So it seems the patch is not needed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5210">issues.joomla.org/joomla-cms/5210</a>.</sub>

**Comment by laoneo** [comment]
Google doesn't deliver gzip compressed content. But I created a test calendar on my private iCloud account which I published. I've updated the test instructions, you can ad the code now as it is without searching for an iCloud url. Thanks for your help.

**Comment by roland-d** [comment]
@laoneo I have taken the updated code (fixed the url as it started with ihttps ;) ) and added it to the content.php file. Without or with the patch, I always see the calendar data. So I can't reproduce the issue.

**Comment by laoneo** [comment]
@roland-d strange, perhaps some different server settings. Hopefully some others will be able to reproduce the issue. Thanks for your help so far.

**Comment by roland-d** [comment]
I have tested this again on a Mac and now I am able to reproduce the issue. Gzipped data is shown before the patch and regular calendar data after applying the patch. Test is succesfull.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5210">issues.joomla.org/joomla-cms/5210</a>.</sub>

**Comment by brianteeman** [comment]
@laoneo Unfortunately this cant be tested anymore because you have deleted your branch. Please resolve this or this will have to be closed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5210">issues.joomla.org/joomla-cms/5210</a>.</sub>

**Comment by roland-d** [comment]
@brianteeman It can be tested but it's a bit more cumbersome, you would have to change the file manually with the same changes as shown on the "Files changed" tab.

We can still merge it even though the branch is gone.

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 5584223956d6a88d086a08069bf8f69ea047e298<br /><br />I dont understand this or why we need it but I can confirm it does what it says as stated by @roland-d <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5210">issues.joomla.org/joomla-cms/5210</a>.</sub>

**Comment by brianteeman** [comment]
With my test and Rolands I am setting this RTC and someone else can decide if this is needed or not<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5210">issues.joomla.org/joomla-cms/5210</a>.</sub>

**Comment by roland-d** [comment]
As for me I don't see an issue having this option. It enables another cURL option to be configured when sending a request.

From the PHP manual:
> CURLOPT_ENCODING 	The contents of the "Accept-Encoding: " header. This enables decoding of the response. Supported encodings are "identity", "deflate", and "gzip". If an empty string, "", is set, a header containing all supported encoding types is sent.

**Comment by laoneo** [comment]
I can recreate the branch with the patch if needed.

**Comment by brianteeman** [comment]
I "think" that will make it easier to be merged - not sure - but no harm

On 13 April 2016 at 11:29, Allon Moritz <notifications@github.com> wrote:

> I can recreate the branch with the patch if needed.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/5210#issuecomment-209359137>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Pull request merged**
