### PR TITLE
Replace curly braces for PHP 7.4 compatibility

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Replaces curly brackets used for array and string access with square brackets to solve deprecation warnings in PHP 7.4:

>Array and string offset access syntax with curly braces is deprecated

### Testing Instructions

Code review?

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by wilsonge** [comment]
Given this as a PR to @nikosdion https://github.com/akeeba/angie/pull/76 so we can try and get an official version of the restore.php code with this in. Rather than starting to monkey patch this ourselves. If we do need to patch this way we'll need to modify the copyright at the top of restore.php similar to how we did in fof with https://github.com/joomla/joomla-cms/commit/4889f00d3770048371c83a02d8ff81ae5c85a61e

**Comment by SharkyKZ** [comment]
Should we make changes to FoF too? And what about other libraries like idna_convert and lessphp?

**Comment by brianteeman** [comment]
> Should we make changes to FoF too? And what about other libraries like idna_convert and lessphp?

Never change an upstream library. If needed submit a pull request to that libraries vendor

**Comment by SharkyKZ** [comment]
Those libraries aren't maintained. We did make changes to FoF in the past https://github.com/joomla/joomla-cms/commits/staging/libraries/fof.

**Comment by wilsonge** [comment]
FOF is fine to change. idna convert is also fine as it's something internal to string and doesn't exist on packagist. i already did that one in the framework https://github.com/joomla-framework/string/commit/33944ac13e4148b286bc07bb47fa39609a3279a1 

Let's try submitting lessphp back to them - https://github.com/leafo/lessphp/compare/v0.5.0...master but there hasn't been a release in nearly 5 years - so unsure whether they'll actually accept it or not.

**Comment by SharkyKZ** [comment]
Submitted https://github.com/leafo/lessphp/pull/647.

**Comment by nikosdion** [comment]
Hey, guys. Thank you for the PR! George made it to the wrong repo but don't worry, I know where else to apply it :)

@wilsonge Do you want me to make a PR with the new version of `restore.php`? If so, only J3 or both J3 and J4?

**Comment by wilsonge** [comment]
Thankyou very much! Sorry for the wrong repo thing. Just to j3 please and it will get merged upto j4

**Comment by wilsonge** [comment]
@SharkyKZ can you remove the restore.php changes from this PR please and they'll be covered in @nikosdion 's separate PR

**Comment by SharkyKZ** [comment]
Done.

**Comment by nikosdion** [comment]
I PR'ed the new restore.php, see https://github.com/joomla/joomla-cms/pull/25793

BTW, has anyone managed to *reliably* run PHP 7.4 betas on either macOS or Ubuntu 19.04? I don't want to have to pull in half of the known universe to compile it myself on Ubuntu, I really don't have the time anymore :/

**Comment by wilsonge** [comment]
I haven't yet - but we're doing it in drone with the php 7.4 nightly docker container - so i think that's where i'm going to start at https://github.com/joomla/joomla-cms/blob/4.0-dev/.drone.yml#L73

**Comment by nikosdion** [comment]
@wilsonge OK, that's pretty much what I thought I would have to do. I am not a huge fan of dockerizing everything because of various issues I've had with XDebug, hostnames, testing CLI applications and ownership / permissions of files in mounted volumes but I digress. I am now using https://github.com/devilbox/docker-php-fpm-7.4 because it solves the ownership / permissions issue and creates a tidy PHP-FPM server I can use with my localhost setup, e.g.:
```bash
docker run \
	--rm -d --name devilbox-php74 \
	-e NEW_UID=$(id -u) \
	-e NEW_GID=$(id -g) \
	-e TIMEZONE="Europe/Athens" \
	-e DOCKER_LOGS=0 \
	-e FORWARD_PORTS_TO_LOCALHOST="3306:host.docker.internal:3306, 1025:host.docker.internal:1025, 6379:host.docker.internal:6379" \
	-p 127.0.0.1:9074:9000 \
	-v $(pwd)/logs:/var/log/php \
	-v $(pwd)/php_config:/etc/php-custom.d \
	-v /path/to/my/sites:/path/to/my/sites \
	-v /path/to/my/git/repos:/path/to/my/git/repos \
	-t devilbox/php-fpm:7.4-work
```
to start the PHP-FPM server and then a couple of lines in my .htaccess to use it:
```apache
<FilesMatch "\.php$">
SetHandler "proxy:fcgi://127.0.0.1:9074/"
</FilesMatch>
```

**Comment by C-Lodder** [comment]
R.E the `lessphp` library, it looks like one of the forks has a lot of PR ported from the original repo and has more interaction: https://github.com/MarcusSchwarz/lesserphp

May be an idea to submit your PR there

**Comment by SharkyKZ** [comment]
@C-Lodder I don't think that library is compatible with ours. Plus, they only have tests for PHP 5.6+.

**Comment by SharkyKZ** [comment]
@C-Lodder I don't think that library is compatible with ours.

**Review by rdeutz — APPROVED** [review]

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 2861347c2922594404d93b95fc2400e19f117949<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25782">issues.joomla.org/tracker/joomla-cms/25782</a>.</sub>

**Comment by mbabker** [comment]
Files in `libraries/idna_convert` need a notification they have been altered.

**Comment by SharkyKZ** [comment]
@mbabker Added note. Thanks.

**Review by wilsonge — APPROVED** [review]

**Comment by HLeithner** [comment]
Thanks for fixing deprecated the syntax.

**Pull request merged**
