### PR TITLE
Improved PHPDoc for JDatabaseDriver::updateObject

### PR DESCRIPTION
**Pull request by f-liva**
The $key parameter can be either an array or a string but from PHPDoc it was only an array

Pull Request for Issue # .

### CODE REVIEW

**Review by wilsonge — APPROVED** [review]

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on af00cdd8ceec5493683133502fd62ba7212d62de<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25134">issues.joomla.org/tracker/joomla-cms/25134</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on af00cdd8ceec5493683133502fd62ba7212d62de<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25134">issues.joomla.org/tracker/joomla-cms/25134</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25134">issues.joomla.org/tracker/joomla-cms/25134</a>.</sub>

**Comment by Quy** [comment]
@HLeithner  Please merge.

**Comment by HLeithner** [comment]
Shouldn't the & be removed?

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
