### PR TITLE
[3.9] Mark PLG_FIELDS_SQL_RULES_ADAPTED deprecated

### PR DESCRIPTION
**Pull request by ReLater**
See https://github.com/joomla/joomla-cms/pull/28760

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 3a2864bcf2ac404912cc38fbc359c7978d68399a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28761">issues.joomla.org/tracker/joomla-cms/28761</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 3a2864bcf2ac404912cc38fbc359c7978d68399a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28761">issues.joomla.org/tracker/joomla-cms/28761</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28761">issues.joomla.org/tracker/joomla-cms/28761</a>.</sub>

**Comment by zero-24** [comment]
merging thnaks 👍

**Comment by infograf768** [comment]
I would not have merged this (File will be marked as modified on crowdin and other systems). Useless work for TTs at this stage as we already have a PR taking off that string in 4.0 which has already been merged.
The reason behind a deprecation is to ease the work when switching to j4. Obviously not necessary now.

@zero-24 Please revert

**Comment by Bakual** [comment]
> File will be marked as modified on crowdin and other systems)

Just a comment on this for the future: Crowdin will **not** mark this string as modified, other systems (like com_localise) might. Crowdin looks at each individual string, not at the whole file.

**Comment by infograf768** [comment]
thanks for info

**Comment by ReLater** [comment]
> The reason behind a deprecation is to ease the work when switching to j4. 

It's also an information for developers. Not only for translators.

**Pull request merged**
