### PR TITLE
[com_tags] tags menu items parameters review

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
### Summary of Changes

While making the PR to check the global default options i noticed some issues with the menu items.

So this PR does for the 3 com_tags menu items a review:
1. XML Code Style
2. Remove all default values of parameters that use useglobal (otherwise this would override the useglobal)
3. Remove all filter="integer" values of parameters that use useglobal (otherwise this would tur the empty value to 0 when saving and thus messing the useglobal logic)
4. Added some deprecated and todo paramaters to the parameter that does not use useglobal

### Testing Instructions

0. XML code review (use https://github.com/joomla/joomla-cms/pull/12981/files?w=1 for ignoring the whitespace changes - faster)
1. Apply patch and https://github.com/joomla/joomla-cms/pull/12979 patch (if not merged)
2. Go to com_tags options and save the options
3. Create the 3 tag menu items type and global values are there

### Documentation Changes Required

None.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :red_circle: unsuccessfully on a1981e10690158d18c05210852f1dd7c06e33160<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12981">issues.joomla.org/tracker/joomla-cms/12981</a>.</sub>

**Comment by brianteeman** [comment]
Still got some show global without the values

screen shot 2016-12-05 at 06 46 29<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12981">issues.joomla.org/tracker/joomla-cms/12981</a>.</sub>

**Comment by brianteeman** [comment]
Ooops posted on the wrong item - i havent tested this one yet<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12981">issues.joomla.org/tracker/joomla-cms/12981</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
I have tested this item :red_circle: unsuccessfully on 270fb2f89b102857b0ab6b6a1e2b88334a2094e4<br /><br />Missing Information about "Global Setting" in `Compact list of tagged items`on Tab `List Layouts` the `# Items to List`. Other 2 menu item types shows Value of Global Setting.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12981">issues.joomla.org/tracker/joomla-cms/12981</a>.</sub>

**Comment by ghost** [comment]
If this Issue get no Response, it will be closed at 22th September 2018.

**Comment by ghost** [comment]
This has been closed due to lack of response to the requests above – it can always be reopened.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12981">issues.joomla.org/tracker/joomla-cms/12981</a>.</sub>

**Pull request closed without merging**
