### PR TITLE
[4.0] tab to space

### PR DESCRIPTION
**Pull request by brianteeman**
Replaces a tab with a space.

Code review

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 7696462e4e09b1e9e581f54c450148a658e4af06<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34028">issues.joomla.org/tracker/joomla-cms/34028</a>.</sub>

**Comment by YatharthVyas** [comment]
I have tested this item :white_check_mark: successfully on 7696462e4e09b1e9e581f54c450148a658e4af06<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34028">issues.joomla.org/tracker/joomla-cms/34028</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34028">issues.joomla.org/tracker/joomla-cms/34028</a>.</sub>

**Comment by richard67** [comment]
Thanks! Could have been even merged by review.

**Comment by brianteeman** [comment]
indeed.

**Pull request merged**
