### PR TITLE
[5.1] Cypress typos/grammar

### PR DESCRIPTION
**Pull request by brianteeman**
Minor grammar issues

### Testing Instructions

Code review

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 18fa73e2bb80d12f9d40ac0e318202783114f1d3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43833">issues.joomla.org/tracker/joomla-cms/43833</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 18fa73e2bb80d12f9d40ac0e318202783114f1d3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43833">issues.joomla.org/tracker/joomla-cms/43833</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43833">issues.joomla.org/tracker/joomla-cms/43833</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on d7ea76c9b4332c7268ab8b61f0c26eabbf535bc7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43833">issues.joomla.org/tracker/joomla-cms/43833</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on d7ea76c9b4332c7268ab8b61f0c26eabbf535bc7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43833">issues.joomla.org/tracker/joomla-cms/43833</a>.</sub>

**Comment by LadySolveig** [comment]
@muhme @laoneo could you have a quick look here? Does it make sense to have this change already in the 4.4 branch.

**Comment by muhme** [comment]
> @muhme @laoneo could you have a quick look here? Does it make sense to have this change already in the 4.4 branch.

Yes, from my point of view. We do commits on the actual standard branch 4.4-dev (if the tests are independent of release), so that the tests can be up-merged. I have it on my todo list to down-merge/recreate this PR. But perhaps, there is a more smarter approach?

**Comment by brianteeman** [comment]
see #43853

**Comment by LadySolveig** [comment]
Thank You @brianteeman and @muhme

**Comment by muhme** [comment]
Thank You @brianteeman 👍

**Pull request closed without merging**
