### PR TITLE
[4.3] Phan: Optimizing import statements

### PR DESCRIPTION
**Pull request by Hackwar**
### Summary of Changes
I ran the "optimize imports" action from PHPStorm on our codebase and this is what was the result. (Minus some unnecessary optimizations, like removing spaces in JS or ordering lowercase imports before uppercase ones.)

### Testing Instructions
Codereview

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
I ran a similar check yesterday in vs-code with similar results. The difference was that I just assumed in my ignorance that as there were so many that they must have been false positives.

**Comment by Hackwar** [comment]
Looks like a lot of those things are from earlier refactoring, where for example all Factory::getDbo() were moved to a $this->getDatabase() instead of something like that.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 44f3b8b9781826578691e3bd9476298fbc433dd4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39984">issues.joomla.org/tracker/joomla-cms/39984</a>.</sub>

**Comment by joomdonation** [comment]
I have tested this item :white_check_mark: successfully on 44f3b8b9781826578691e3bd9476298fbc433dd4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39984">issues.joomla.org/tracker/joomla-cms/39984</a>.</sub>

**Comment by joomdonation** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39984">issues.joomla.org/tracker/joomla-cms/39984</a>.</sub>

**Comment by obuisard** [comment]
Thank you Hannes @Hackwar, this was tedious...

**Pull request merged**
