### PR TITLE
[4.0] fix a todo, drop the slider button

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # .

### Summary of Changes
- This button is not used anywhere in the core
- This button was based on mootools and mootools are not here anymore
- This PR **drops** that button!!! 
- Javascript code was wrongly appended in shown.js
- That code is now deleted 
- Classmap updated

### Testing Instructions
Slider was not used anywhere in the core anyways so code review is what is needed here

### Documentation Changes Required

This **is a B/C break** and needs to be documented and also communicated!!!!

### CODE REVIEW

**Comment by Quy** [comment]
Add deleted files to the list in `administrator/components/com_admin/script.php`?

**Comment by Hackwar** [comment]
May I ask what this button did? Would we need something like this again? Somehow I had an input element of type "range" in my mind when reading this, but as a button? Anyway, good that you are removing this stuff. :wink: I don't think that you have to add any files to the deleted files list, since that most likely has to happen by script shortly before we go to RC.

**Comment by Hackwar** [comment]
I have tested this item :white_check_mark: successfully on cc38f141c3d9d6f9a392a7cf95e58cf773ab5617<br /><br />Tested by codereview<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23388">issues.joomla.org/tracker/joomla-cms/23388</a>.</sub>

**Comment by dgrammatiko** [comment]
@Hackwar by translating the js part `<div class="collapse fade" id="collapse-${name}"><iframe class="iframe" src="${url}" height="${height}" width="100%"></iframe></div>` I think this was acting like an accordion kinda thingy. So when someone was clicking on that button then the container would expand and the iframe would be rendered inside.

**Comment by Quy** [comment]
It is my understanding that the list is for when upgrading to handle deleted files.

**Comment by mbabker** [comment]
Someone can run https://github.com/joomla/joomla-cms/blob/4.0-dev/build/deleted_file_check.php and build a full list of files at an appropriate time.  Since the entire upgrade process is messed up right now, no point in randomly adding files to that list in random PRs; enforce it after everything is caught up.

**Comment by bonzani** [comment]
I have tested this item :white_check_mark: successfully on cc38f141c3d9d6f9a392a7cf95e58cf773ab5617<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23388">issues.joomla.org/tracker/joomla-cms/23388</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23388">issues.joomla.org/tracker/joomla-cms/23388</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
