### PR TITLE
fix get list position error

### PR DESCRIPTION
**Pull request by trananhmanh89**
Pull Request for Issue # .

### Summary of Changes
fix typo

### Testing Instructions
Just create new instance of PositionsModel then use getList function.

### CODE REVIEW

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on 3016c55ca704f40418c8ef4e946eef9f4b0d29d3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30672">issues.joomla.org/tracker/joomla-cms/30672</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 3016c55ca704f40418c8ef4e946eef9f4b0d29d3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30672">issues.joomla.org/tracker/joomla-cms/30672</a>.</sub>

**Comment by infograf768** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30672">issues.joomla.org/tracker/joomla-cms/30672</a>.</sub>

**Comment by infograf768** [comment]
tks

**Pull request merged**
