### PR TITLE
Some ideas on an Isis flatter repaint

### PR DESCRIPTION
**Pull request by ciar4n**
flat1

Just another take on #11789 
### Summary of Changes

Changes only to UI elements. Removal of background gradients. More uniform styling between template.css and chosen.css
### Testing Instructions

Apply the patch and browse administration.
### Documentation Changes Required

None

### CODE REVIEW

**Comment by dgt41** [comment]
@ciar4n I like it!
But the usage of custom.css is wrong. Custom.css is supposed to be used from users to further customise the template. With the current approach you are eliminating that option.
Either make a PR with the changes to https://github.com/joomla/joomla-cms/pull/11789 or create a new PR based on https://github.com/joomla/joomla-cms/pull/11789 with your changes and let's close https://github.com/joomla/joomla-cms/pull/11789.

**Comment by ciar4n** [comment]
Thank you @dgt41 

Admittedly I meant this as strictly a demo and hadn't considered it for anything else. I will do as you suggest. Sorry about that. I am not much practiced at both Github and the Joomla developement community.. learning slowly! :)

**Comment by PhilETaylor** [comment]
The grey buttons looks disabled to me. I dont like it. However I doubt design can be done by collaborative opinions though.

**Comment by ciar4n** [comment]
@dgt41 I have applied the changes here but would it be better to close this PR and create a new one? I'm guessing this is something to do with the branch conflict?

@PhilETaylor Fair point on the buttons looking disabled. I bumped up the contrast on the button borders making them hopefully stand out a little more (header screenshot updated).

**Comment by C-Lodder** [comment]
Hmm, I like this too. 

@ciar4n - If it's easier for you to create a new PR, go for it. I'd suggest creating a new branch when from "staging" on your fork before making then changes though. Will make your life much easier if you want to submit another PR before this is merged ;)

**Comment by BhaveshTailored** [comment]
I have tested this item :white_check_mark: successfully on 4c453bf8b8d9469bdbf51651c41d3886b4eeadac<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11813">issues.joomla.org/joomla-cms/11813</a>.</sub>

**Comment by bhavikTailored** [comment]
- I have tested successfully and attached screen shot.
- screen shot 2016-08-29 at 00 09 31<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11813">issues.joomla.org/joomla-cms/11813</a>.</sub>

**Comment by bhavikTailored** [comment]
I have tested this item :white_check_mark: successfully on 4c453bf8b8d9469bdbf51651c41d3886b4eeadac<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11813">issues.joomla.org/joomla-cms/11813</a>.</sub>

**Comment by ciar4n** [comment]
Thank you @C-Lodder 

I'll do as you suggest. Start from scratch and apply the changes to a new branch. Best start as I mean to go on :)

I'll close this PR and and create a new one once complete.

**Pull request closed without merging**
