### PR TITLE
[4.0] Fix exporting banner tracks

### PR DESCRIPTION
**Pull request by Quy**
Pull Request for Issue #26818.
Alternate fix to #26848.

### Summary of Changes
Use toolbar class instead of layout to display the export modal.

### Testing Instructions
Go to Components -> Banners -> Tracks
Click on Export

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on d1fc6721a921066c031f07862d501a53d29e5ea7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27091">issues.joomla.org/tracker/joomla-cms/27091</a>.</sub>

**Comment by vijaykhollam** [comment]
I have tested this item :white_check_mark: successfully on d1fc6721a921066c031f07862d501a53d29e5ea7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27091">issues.joomla.org/tracker/joomla-cms/27091</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27091">issues.joomla.org/tracker/joomla-cms/27091</a>.</sub>

**Comment by wilsonge** [comment]
I think a variation of the fix in the original PR #26848 is actually correct (we'd need to change the jQuery dependency to use native JS which should be easy enough).

Reason being is whilst this works (it's effectively reversing https://github.com/joomla/joomla-cms/pull/10934 ) - effectively all this does is mask we've had a b/c break in the layout - the layout when used by other extensions is still going to have exactly the same issues as originally.

If we do go down this route we basically have to remove the toolbar modal layout - as it's going to be useless

**Pull request closed without merging**
