### PR TITLE
fixes #4127 #6693

### PR DESCRIPTION
**Pull request by eshiol**
fixes JDatabaseQuery __toString
UNION ALL
UNION + ORDER BY

### CODE REVIEW

**Comment by eshiol** [comment]
If you use union and order, you will always get the error: "Incorrect usage of UNION and ORDER BY"
$query1 = JFactory::getDbo()->getQuery(true);
$query1->select(array('id', 'title'))->from('#__content')->where('title LIKE ' . $query1->q($query1->e('A', true) . '%', false));
$query2 = JFactory::getDbo()->getQuery(true);
$query2->select(array('id', 'title'))->from('#__content')->where('title LIKE ' . $query1->q($query1->e('B', true) . '%', false));
$query1->union($query2)->order('id DESC');
JFactory::getDbo()->setQuery($query1)->execute();

unionAll doesn't work properly. The string you entered into the unionAll method was never appended to the SQL query
$query1 = JFactory::getDbo()->getQuery(true);
$query1->select(array('id', 'title'))->from('#__content')->where('title LIKE ' . $query1->q($query1->e('A', true) . '%', false));
$query2 = JFactory::getDbo()->getQuery(true);
$query2->select(array('id', 'title'))->from('#__content')->where('title LIKE ' . $query1->q($query1->e('B', true) . '%', false));
echo $query1->unionAll($query2);

Expected result
The code above should output "SELECT id, title FROM #__content WHERE title LIKE 'A%' UNION ALL (SELECT id, title FROM #__content WHERE title LIKE 'B%')".

Actual result
At the moment the output is "SELECT id, title FROM #__content WHERE title LIKE 'A%'".

**Comment by infograf768** [comment]
looks lik this pr is messed up.

**Comment by alikon** [comment]
yes files changed have nothing in common with the pr description

**Comment by eshiol** [comment]
I've merged two pull requests, but I don't know why. The file to pull is the first one with the id: [22a262d](https://github.com/joomla/joomla-cms/pull/12536/commits/22a262d55ccb1294676cacdc0db29b53f9a6e35c)
Do you think I have to close this pull request and open a new one?

**Comment by alikon** [comment]
yes should be the better move

**Comment by eshiol** [comment]
the bug is solved  #10817

**Pull request closed without merging**
