### PR TITLE
[4.0] type_added

### PR DESCRIPTION
**Pull request by puneeth-chanda**
Pull Request for Issue #23948

### Summary of Changes
Button tags added

### CODE REVIEW

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on b1297a9e7ea956483cb426a90f03106a368b4bcc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23997">issues.joomla.org/tracker/joomla-cms/23997</a>.</sub>

**Comment by bembelimen** [comment]
I have tested this item :white_check_mark: successfully on b1297a9e7ea956483cb426a90f03106a368b4bcc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23997">issues.joomla.org/tracker/joomla-cms/23997</a>.</sub>

**Comment by Quy** [comment]
Should package-lock.json be included?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23997">issues.joomla.org/tracker/joomla-cms/23997</a>.</sub>

**Comment by rdeutz** [comment]
> Should package-lock.json be included?

only when package.json is changed

@puneet0191 can you have a look, please?

**Comment by wilsonge** [comment]
It shouldn't be changed - seems to be related to https://github.com/npm/npm/issues/20934

Basically @puneeth2001 can you revert the changes in the package-lock please

**Comment by puneeth-chanda** [comment]
ok I'll do it

**Comment by Quy** [comment]
RT<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23997">issues.joomla.org/tracker/joomla-cms/23997</a>.</sub>

**Comment by puneeth-chanda** [comment]
Closing this since there is a problem with branch.
 #24033 new PR

**Pull request closed without merging**
