### PR TITLE
Beez: Remove useless JS-Code related to btn-group

### PR DESCRIPTION
**Pull request by Minei3oat**
Pull Request for Issue # .

### Summary of Changes
In the template.js of Beez the JS-Code for boostraps `btn-group` is implementeted but without the missing CSS-Code it is useless. This PR removes the useless code.
If the `btn-group` should be added later, the code can be copied from Protostar.

### Testing Instructions
Beez should work as before.

### Documentation Changes Required
none

### CODE REVIEW

**Comment by dgt41** [comment]
@Minei3oat I think it would be better if you add the missing css instead of removing the script

**Comment by Minei3oat** [comment]
Now the missing css is added.

**Comment by Minei3oat** [comment]
The Bootstrap code is in conflict with Beez3 (Look at the buttons when editing an article or module: https://github.com/joomla/joomla-cms/blob/staging/templates/beez3/css/personal.css#L145-L186).

Since Beez3 sometimes didn't uses chosen and uses a very simple style, I'm thinking about removing `btn-group` entirely like I've done first. Its not really needed.

**Comment by brianteeman** [comment]
@minei3oat what is the status of this. If I read your last comment correctly there is more work to be done before it is ready for testing?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12029">issues.joomla.org/tracker/joomla-cms/12029</a>.</sub>

**Comment by Minei3oat** [comment]
Yes, that's right, there are is the problem with the buttons when editing an article.

**Comment by anjahage** [comment]
@Minei3oat Is this issue still relevant?

Otherwise @nibra will look at it<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12029">issues.joomla.org/tracker/joomla-cms/12029</a>.</sub>

**Comment by Minei3oat** [comment]
This issue was never relevant.
The buttons work without the design as good as with the colored design. Because of this, I first wanted to remove the useless JavaScript-code but as you can see there was the wish of adding the missing css instead of removing the js. But as this issue is not so relevant and my time limited I don't invested much and so it got stuck with the conflicts.

**Comment by franz-wohlkoenig** [comment]
@Minei3oat so should this PR be closed?

**Comment by Minei3oat** [comment]
As there is still useless code, I propose to go back to the original intention of this PR and delete this code.
If someone want's to add the colored buttons later, the code can be copied from Protostar.

**Comment by franz-wohlkoenig** [comment]
@Minei3oat is this PR ready for Test?

**Comment by Minei3oat** [comment]
Now it should be ready for testing.

**Comment by franz-wohlkoenig** [comment]
thanks @Minei3oat

**Comment by franz-wohlkoenig** [comment]
@Minei3oat i have tested a little but have less Experience in Beez so it would help if you can instruct which Sample Sites to look easy for testing.

**Comment by Minei3oat** [comment]
As I explained above, the removed code was useless because the CSS-Classes are missing. I discovered this by viewing a form with `btn-group`.

If code-review counts as test, the best test would be to search the CSS-Classes added by the removed JS and see that they not exists.

**Comment by franz-wohlkoenig** [comment]
can you give me an Example of Form with `btn-group` so i can test if 

> Beez should work as before.

**Comment by Minei3oat** [comment]
If you edit a module their is the possibility to change the status of the module (Published/Unpublished/Trashed). This is a `btn-group`, as you can see in Protostar.

**Comment by franz-wohlkoenig** [comment]
Tested on an Article (Publish / Unpublish / ...) cause using Beez Icon on Module for "Edit" isn't shown. All works as without Patch but Source-Code looks same with- and without PR.

**Comment by Minei3oat** [comment]
The Article-View doesn't uses `btn-group`.
With adding `&template=beez3` to the URL you can change the template to Beez for the request.

**Comment by franz-wohlkoenig** [comment]
http://localhost:8888/3/index.php/en/park-blog/18-second-blog-post&template=beez3 doesn't change Template.

**Comment by Minei3oat** [comment]
Because there is no other parameter in the URL it must be a `?` instead of a `&`.

**Comment by franz-wohlkoenig** [comment]
that works. But there is also no Icon on Module.

**Comment by Minei3oat** [comment]
1. Load the page with the module you want to edit with an other template
2. Click the edit icon
3. add the parameter to the URL

This will result in the edit page of the module displayed with Beez as template.

**Comment by franz-wohlkoenig** [comment]
#### Source-Code without PR:
without
#### Source-Code with PR:
with

**Comment by Minei3oat** [comment]
Due to unknown reasons Beez uses the class `btn-group` for this buttons (sometimes all in one `div`, sometimes all in separat `div`s) without using them in CSS. But this code is hardcoded in PHP-Files in /html/... and not influenced by this PR.

**Comment by franz-wohlkoenig** [comment]
so how to Test this PR?

**Comment by Minei3oat** [comment]
As I stated above the code was useless. So I don't know how to test this PR. Imho there is the option to compare the functionality of some pages/`btn-group`s before and after the PR and find no difference or to look at the CSS of Beez and see that the JS-Code was useless. (Beez doesn't have CSS-Rules for `active` in this context, `btn-primary`, `btn-succes`, `btn-danger`, `disabled`)

**Comment by franz-wohlkoenig** [comment]
Hopefully there are 2 other Tester with more Skills.

**Comment by ghost** [comment]
If this PR get no Response, it will be closed at 17th September 2017.

**Comment by ghost** [comment]
This has been closed due to lack of response to the requests above – it can always be reopened.

**Pull request closed without merging**
