### PR TITLE
[com_joomlaupdate] review config global default options

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
### Summary of Changes

This PR intends to normalize onfig global default options in com_joomlaupdate.

The method used was:
1. Review cs of the config.xml file - also add missing default values
2. Check the current params in installation joomla.sql mysql
3. Add missing defaults to install sql

### Testing Instructions

0. Code review

### Documentation Changes Required

None.

### Added/Changed defaults in the xml

none. just added the sql part

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on f25b192b9edf2134a94ca1c7d05a9feb859bf840<br /><br />on code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12965">issues.joomla.org/tracker/joomla-cms/12965</a>.</sub>

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on f25b192b9edf2134a94ca1c7d05a9feb859bf840<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12965">issues.joomla.org/tracker/joomla-cms/12965</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12965">issues.joomla.org/tracker/joomla-cms/12965</a>.</sub>

**Comment by andrepereiradasilva** [comment]
just fixed conflicts no need to retest

**Comment by wilsonge** [comment]
Sorry merging Brian's PR earlier has caused more conflicts :(

**Comment by zero-24** [comment]
Please fix the conflicts. I'm removing RTC until that :smile:

**Comment by andrepereiradasilva** [comment]
@zero-24 fixed conflicts

**Comment by zero-24** [comment]
Thanks :+1:

**Pull request merged**
