### PR TITLE
Save an active tab state inside nested tab sets

### PR DESCRIPTION
**Pull request by shanginn**
Pull Request for Issue # .
#### Summary of Changes

I have modified this code to keep tracks of all active tabs, when there is nested tabs present.
For example, if you making changes in some category and you navigate to the Rules tab there will be another tab set inside with Groups. With previous code only last clicked tab is saved to local storage.
So if you clicked Rules tab in the local storage will be "#rules", but when you click some Group this "#rules" will be overtighten by, for example, "#permission-1" and next time you reload the page your Rules tab will not be active.
With this code all active tabs will be tracked and saved to local storage.
#### Testing Instructions

Create a category in Articles manager, click Rules, click Public. Reload the page and there you have it: Rules and Public both open.

### CODE REVIEW

**Comment by killoltailored** [comment]
Please provide more information regarding where can find "RULES" option in Article Manager<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10026">issues.joomla.org/joomla-cms/10026</a>.</sub>

**Comment by brianteeman** [comment]
I think he means permissions <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10026">issues.joomla.org/joomla-cms/10026</a>.</sub>

**Comment by AnishaTailored** [comment]
I have tested this item :white_check_mark: successfully on 5a58379a67c1f38b24771ea465fc7dfbe1036f1e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10026">issues.joomla.org/joomla-cms/10026</a>.</sub>

**Comment by rahultomar** [comment]
I have tested this item :white_check_mark: successfully on 5a58379a67c1f38b24771ea465fc7dfbe1036f1e<br /><br />Just followed the steps given and it tested successfully <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10026">issues.joomla.org/joomla-cms/10026</a>.</sub>

**Comment by killoltailored** [comment]
I have tested this item :white_check_mark: successfully on 5a58379a67c1f38b24771ea465fc7dfbe1036f1e<br /><br />Tested successfully with Joomla Version: Joomla! 3.6.0-rc Release Candidate [ Noether ] 28-June-2016 20:34 GMT <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10026">issues.joomla.org/joomla-cms/10026</a>.</sub>

**Comment by roland-d** [comment]
@shanginn Can you please fix the conflicts? Thank you.

**Comment by shanginn** [comment]
@killoltailored, yeah, I meant permissions.
@roland-d, I'm sorry, but I don't know where I can find conflicts. It's my first pull-request experience.
It says

```
This branch has conflicts that must be resolved
Only those with write access to this repository can merge pull requests.
```

If you could, provide some more information please, it'll be my pleasure to contribute.

**Comment by roland-d** [comment]
@shanginn 
> I'm sorry, but I don't know where I can find conflicts.

No problem, let me try to help you. If you are familiar with GIT, the easiest way to find out the conflicts is to merge the staging branch into your patch-1 branch.

If you are not familiar with GIT, the easiest is to make a new pull request and reference this one.

Let me know if you need any further help.

**Comment by shanginn** [comment]
Thank you for the reply. But I don't really know, if I did it right. please, correct me, if there is something wrong.

**Comment by roland-d** [comment]
@shanginn The pull request is all good now. The conflicts are resolved. We just need to get the people to test again.

**Comment by Devportobello** [comment]
About third party, any code using ```localStorage.getItem('tab-href')``` is now broken !
More over, now if i need to know the active tab, i need first to ```JSON.parse``` then take the last value ```.pop()```
```active-tabs``` hold the history of clicked tabs, so if we take for example the content components, if you click 20 times tabs then reload, script will show/hide step by step tabs... what about performance ?

**Comment by zero-24** [comment]
Please open a new bug report with all needed information. Commenting on a closed / merged PR get missed fast. Thanks

**Pull request merged**
