### PR TITLE
[4.0] Make dropdown full width

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
Change class to make the dropdown full width. This is the same markup as in the other modals.

### Testing Instructions
Go to Content > Fields
Create a new field.
In list view, click checkbox.
Under `Actions` dropdown, select Batch.
See `To Move or Copy your selection please select a group.`

### Actual result BEFORE applying this Pull Request
field-batch-before

### Expected result AFTER applying this Pull Request
field-batch-after

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 74ff36335bf0a97c3fd8efec80b5357160ba3c84<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34916">issues.joomla.org/tracker/joomla-cms/34916</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 74ff36335bf0a97c3fd8efec80b5357160ba3c84<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34916">issues.joomla.org/tracker/joomla-cms/34916</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34916">issues.joomla.org/tracker/joomla-cms/34916</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
