### PR TITLE
[4.0] Fix #21357 when multilanguage is implemented

### PR DESCRIPTION
**Pull request by infograf768**
Code error in #21357

### Summary of Changes
Making sure we are in multilang before using forcedLanguage.
Changing the code to get the article language as `$this->element['language']` is wrong in this case.

### Testing Instructions
Create a multingual site with articles set to some languages and other set to All languages.
When using the new "New Menu Item" button, the modal presented should take into account the language of the article for the Menu item created.
For an article tagged to ALL languages the language for the menu item can be anything (no forcedLanguage).
But for an article tagged to a specific language, the menu item should also be tagged to the same language.
This is unrelated to the Menu, which can be set to ALL or any language.

### Before patch
We can choose in the modal any language for the menu item.

### After patch
When the article is not tagged to ALL, the new menu item is already tagged to the same language as the article and it can't be changed.
screen shot 2018-08-03 at 17 15 42

### Documentation Changes Required

yes when doc is made for #21357

@bene-we

### CODE REVIEW

**Comment by infograf768** [comment]
Note: I also think the language load can be simplified
from
```
$language = Factory::getLanguage();
				$language->load('com_menus', JPATH_ADMINISTRATOR, 'en-GB');
				$language->load('com_menus', JPATH_ADMINISTRATOR, $language->getDefault());
				$language->load('com_menus', JPATH_ADMINISTRATOR);
```
to simply
```
				// Load the language files
				$language = Factory::getLanguage();
				$language->load('com_menus', JPATH_ADMINISTRATOR, null, false, true);

**Comment by ghost** [comment]
test this ~~Weekend~~ now.

**Comment by ghost** [comment]
After save new Article no Button "New Menu Item" is shown.
### System information
- Nightly Build 4.0.0-alpha5-dev
- Multilingual Sample Data (French, German DE, Persian)
- Template: Cassiopeia
- macOS Sierra, 10.13.6
- Firefox 61 (64-bit)
#### CloudAccess.net
- PHP 7.1.15
- MySQLi 5.7.18-cll-lve

**Comment by infograf768** [comment]
hmm. The new button stuff was created in https://github.com/joomla/joomla-cms/pull/21357 2 days ago.

**Comment by ghost** [comment]
#21357 is merged so the Button should show. Installed Nightly 2 Times, get as always the "AJAX-Error" at end of Update but not the Button.

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 9d562e55f9848996482925bd962926e319f9c47b<br /><br />Works as expected after new Installation of Nightly (not Update as before).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21391">issues.joomla.org/tracker/joomla-cms/21391</a>.</sub>

**Comment by bene-we** [comment]
@infograf768 did not thougt about this, thank you
@franz-wohlkoenig many thanks for testing again

**Comment by ghost** [comment]
@bene-we thanks for your Work.

**Comment by infograf768** [comment]
@bene-we 
Please set your test OK in https://issues.joomla.org/tracker/joomla-cms/21391 by using the blue button "Test this"

**Comment by infograf768** [comment]
Note: will create the new PR for lang load separately.

**Comment by bene-we** [comment]
I have tested this item :white_check_mark: successfully on 9d562e55f9848996482925bd962926e319f9c47b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21391">issues.joomla.org/tracker/joomla-cms/21391</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Comment by wilsonge** [comment]
Thanks JM!

**Pull request merged**
