### PR TITLE
[4.0] Menus Manager: Fix system links menu items Status icon and add back tip

### PR DESCRIPTION
**Pull request by infograf768**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/24721

### Summary of Changes
Using the override `administrator/components/com_menus/Service/HTML/Menus.php` for `jgrid.published` in the Menu items Manager.
In 3.x this is done by `/administrator/components/com_menus/helpers/html/menus.php`

This will display again the correct Status icon for System Links menu items as well as using the specific tip for each menu item icon.

**NOTE: This will not modify the display of the tooltip as this requires a specific PR for `jgrid`.**

### Testing Instructions
Make sure you have created a System Links menu item (URL, Heading, Separator, Alias).

Display the Menu Items Manager and try to modify the status of these menu items
Although they may be Published, the icon the grey cross
If one uses the toolbar to Unpublish the item, the icon displays a black folder instead of the grey cross

The tip is the default tip used by `jgrid` and NOT the specific menu items tip.

Patch and test again.

### Before patch
For a URL menu item
Screen Shot 2019-06-12 at 11 47 36

For a non system links menu item
Screen Shot 2019-06-12 at 11 47 52

### After patch
For a URL menu item:
The icon reflect the Published status and the specific tip
Screen Shot 2019-06-12 at 11 43 17

and for a non system links menu item, the specific tip
Screen Shot 2019-06-12 at 11 43 05

### Note2
I have not modified the existing language strings for the tips. They represent an action and not the existing status. This can be discussed elsewhere.

### CODE REVIEW

**Comment by infograf768** [comment]
Note :
Another solution is to totally give up the specific strings and use a `PublishedButton` which would deal with publish_down and publish_up while displaying the tip fine as done for articles.
We may lose the `Component enabled` part of the tip and need to customise the button to accept dealing with the System Links.

**Comment by infograf768** [comment]
The other solution is to change the Model and give up the overrides. Would still need some changes in Jgrid to display the tip ok

**Comment by 810** [comment]
I have tested this item :white_check_mark: successfully on 4bec54995ebdcf6250af69e577a5becccc305a77<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25185">issues.joomla.org/tracker/joomla-cms/25185</a>.</sub>

**Comment by SharkyKZ** [comment]
This breaks display for expired items.

**Comment by infograf768** [comment]
@SharkyKZ 
yes I know. I am able to solve the issue only if we forget about component enabled or not.
In that case we will get 
Screen Shot 2019-06-12 at 16 50 49

Where Newsfeeds component is disabled-> shows Unpublished icon and no useful tip.
Screen Shot 2019-06-12 at 16 55 00


Except if someone finds a trick, we have to choose between both ways.

**Comment by brianteeman** [comment]
The "tooltips" have always been a confusing mess of action and status https://github.com/joomla/joomla-cms/issues/9359

**Comment by infograf768** [comment]
Found a way to display a badge when component is disabled while keeping expired icon.
Closing this PR as I will propose a new solution.

**Comment by infograf768** [comment]
Please test this new one
https://github.com/joomla/joomla-cms/pull/25197

**Pull request closed without merging**
