### PR TITLE
[4.0] Fix Upgrade with postgresql- From Joomla v3.9.x to v4.0

### PR DESCRIPTION
**Pull request by twister65**
Pull Request for Issue #25467.

### Summary of Changes
Use right data type of template styles home column in db.
Synchronize PR #25477 with PR #25484.

### Testing Instructions
Install a copy of Joomla 3.9.10 on postgres.
Apply this PR to your joomla source directory.
Build an update package to your joomla-4.0-dev source directory:
git tag 4.0.0-alpha11-dev
php build/build.php
Update Joomla 3.9.10 with the new update package.
Check if Joomla upgrades successfully

### CODE REVIEW

**Comment by twister65** [comment]
@richard67 and @alikon , please test.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on a37567f411b90b84f49a673f55f57afb8eb8b827<br /><br />Code review. Is obvious.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25507">issues.joomla.org/tracker/joomla-cms/25507</a>.</sub>

**Comment by richard67** [comment]
@twister65 Maybe these sql statements should be extended in both mysql and postgresql to handle also template styles where the value for column `home` is not '0' or '1' but a language code, e.g. 'de-DE', 'en-GB', ...
I think that could be subject of another, future PR, so I gave this one here a good test.
But if you wanna do it in this one I can text again tomorrow evening.

**Comment by richard67** [comment]
Hmm, I just see that could become too complicated maybe.

**Comment by richard67** [comment]
@twister65 Maybe you should change title and description of this PR, because you don't change data type of a database column, you only use right data type in the schema update for inserting the data into that table. Other stuff (data type) is still correct in 4.0-dev because mistake from staging was not merged to 40.0-dev yet.

**Comment by twister65** [comment]
Sorry for the mistake, I did not anticipate your PR @richard67 .

**Comment by twister65** [comment]
There is also another issue. When you select PostgreSQL (native) in Joomla 3.9.x and upgrade to Joomla 4.x, the database type is not recognized because Joomla 4.x only supports PostgreSQL (PDO).
In Global Configuration -> Server -> Database Type, MySQL (PDO) is displayed instead of PostgreSQL (PDO). And in the configuration file, $dbtype is 'postgresql', instead of 'pgsql'.
We must force the database type to PGSQL during the upgrade.

**Comment by richard67** [comment]
> We must force the database type to PGSQL during the upgrade.

Ping @wilsonge

**Comment by richard67** [comment]
@wilsonge Any idea how we will handle switching from native PostgreSQL driver in 3.9.x or 3.10.x to the PostgreSQL PDO driver when updating to 4.0.x?

**Comment by wilsonge** [comment]
Sorry I thought I'd already merged this!

I can't really remember now but i think the intention is to make people do this in Joomla 3.x (obviously we have the upgraded Joomla Upgrade Component in the 3.10 branch). Because obviously we have the same issue for the people currently on the mysql driver. That's the reason we backported the postgresql pdo driver into 3.x

**Comment by wilsonge** [comment]
Thanks for testing guys and for the PR!

**Comment by twister65** [comment]
Perhaps, we can add a test here:
https://github.com/joomla/joomla-cms/blob/153feb3db0af22b3eedb07b5a96b01e39c1a0c6b/administrator/components/com_admin/script.php#L77

**Comment by twister65** [comment]
This is done here:
https://github.com/joomla/joomla-cms/blob/ba2c285592be0440fbb77bd77defa228274ca9e5/libraries/src/Service/Provider/Database.php#L74-L82

**Comment by richard67** [comment]
Now as you posted, I remember having seen that, too, recently. But why has that not worked when you tested? Or has it worked, and I missunderstood your comment above?

**Comment by twister65** [comment]
But I don't think it is called during the upgrade.
@wilsonge can enlighten us.

**Comment by richard67** [comment]
Maybe the same thing should be added to the postflight method of administrator/components/com_admin/script.php?

**Comment by richard67** [comment]
Or is postflight too late?

**Comment by wilsonge** [comment]
What do you mean by during the upgrade :)

**Comment by twister65** [comment]
Upgrade: from Joomla v3.9.x to v4.x.

**Comment by richard67** [comment]
And during? ;-)

**Comment by wilsonge** [comment]
I mean when we download the previous patch then we're still on the old db driver. As soon as you've unzipped the files and done the file cleanup (all part of the 0-100 status bar) and the page reloads then you should be using that database.php file from the DIC. As JFactory will have been overwritten with the new file and we'll be using the Joomla Framework DB Driver v2

**Comment by twister65** [comment]
> As JFactory will have been overwritten with the new file and we'll be using the Joomla Framework DB Driver v2

Yes, otherwise the upgrade would have failed.
But `$dbtype` is not correct in the configuration file. I think we need to solve this problem.

**Comment by richard67** [comment]
Agree.

**Comment by twister65** [comment]
Please, review / test this PR #25729 .

**Pull request merged**
