### PR TITLE
[4.0] Fix RTL Cassiopea menu item alignment

### PR DESCRIPTION
**Pull request by infograf768**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/21747

### Summary of Changes
Corrected nav padding

### Testing Instructions
Multilingual site or site language set to Persian.
Display home page with specific Perisan Mainmenu

Can be tested with Patchtester

### Before patch
See https://github.com/joomla/joomla-cms/issues/21747

### After patch
screen shot 2018-08-20 at 09 28 17

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 0a851cea19e99e1815bf1cd761a042788ea75287<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21749">issues.joomla.org/tracker/joomla-cms/21749</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 0a851cea19e99e1815bf1cd761a042788ea75287<br /><br />Great stuff


Is it worth checking the template for all ***-left 

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21749">issues.joomla.org/tracker/joomla-cms/21749</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Comment by ghost** [comment]
> Is it worth checking the template for all ***-left

@brianteeman if i understand correct: no > #21750

**Pull request merged**
