### PR TITLE
Add a value to language forum string

### PR DESCRIPTION
**Pull request by Bakual**
See https://github.com/joomla/joomla-cms/pull/8171 for the initial discussion.

The issue we have is that in Crowdin (and probably other translation tools) we can't translate strings where there is nothing to translate. So empty strings can't be translated.

This particular string here goes beyond translating as it also decides if a menuitem in the help menu is shown or not. However I don't see a reason why we can't always show the link to the language forums.
#### Testing

After applying this PR, you now see a new menuitem in the help menu pointing to the language forums.

### CODE REVIEW

**Comment by brianteeman** [comment]
As the other values in the menu are in capital case then for consistency this should be as well

> MOD_MENU_HELP_SUPPORT_OFFICIAL_FORUM="Official Support Forum"
 MOD_MENU_HELP_SUPPORT_CUSTOM_FORUM="Custom Support Forum"
MOD_MENU_HELP_SUPPORT_OFFICIAL_LANGUAGE_FORUM="Official language forums"
 
==>
MOD_MENU_HELP_SUPPORT_OFFICIAL_LANGUAGE_FORUM="Official Language Forums"

**Comment by Bakual** [comment]
Done. Good point.

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 82e71c0773bee5ac140bdac384d91747c578122d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8547">issues.joomla.org/joomla-cms/8547</a>.</sub>

**Comment by wojsmol** [comment]
I have tested this item :white_check_mark: successfully on 82e71c0773bee5ac140bdac384d91747c578122d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8547">issues.joomla.org/joomla-cms/8547</a>.</sub>

**Comment by brianteeman** [comment]
Setting RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8547">issues.joomla.org/joomla-cms/8547</a>.</sub>

**Pull request merged**
