### PR TITLE
[4.0] fix unpublish submenu module

### PR DESCRIPTION
**Pull request by chmst**
Pull Request for Issue #25993

**Summary of Changes**
Add class module-wrapper to the card

**Testing Instructions**
Try to remove a submenu module from a dashboard.

**Expected result**
The modules disappears from the dashboard

**Actual result**
The module is not removed due to a js error

### CODE REVIEW

**Comment by alikon** [comment]
maybe it's me that don't understand how this is supposed to work,btw....
even with this pr when i click on unpubilsh (now it is)  unpublished, but after a refresh/reload all the submenus are unpublished ...  which is not what i expect 

ezgif-4-4bb9a5d2a458

**Comment by infograf768** [comment]
My guess there is a confusion (what is not confusing in this dashboard stuff?...) between the modules displayed in the `cpanel-help` (or `cpanel-system` etc.) position vs those displaying a quickicon group in `cpanel`. 

In the issue above, when you unpublish one module in the cpanel-help, it in fact unpublishes the whole `Help Submenu` module containing the `Preset - Help Dashboard`

Therefore let's say you have added another admin module in that `cpanel-help` position, you will never know what happens when you unpublish one among what looks like different modules but are not.

The only solution to this would be to group each REAL module under the same Global Title with the edit/unpublish icon and take OFF the icon from the parts of this global module.

Whoever implemented that did not think further than the end of the nose...

**Comment by infograf768** [comment]
In any case will create an issue for that.

@chmst
> Testing Instructions
Try to remove a submenu module from a dashboard.

Do you mean using `Unpublish` from the cog? Whatever the dashboard?
If yes, it works here without this patch.

**Comment by chmst** [comment]
@infograf: There are two kinds of Modules: Normal backend Modules and submenu modules. 
Backend Modules i.e. latest articles, worked always,

Submenu modules could be unpublished via the cog, but were not removed from the screen without refresh. 
This was fixed by this PR.

**Comment by brianteeman** [comment]
> Whoever implemented that did not think further than the end of the nose...

Please comment on the code without making comments about people

**Comment by richard67** [comment]
@chmst I've just tested with success that the js error disappears. But the behavior is a bit weird, so I'd like to ask you if that is expected behavior or not with this PR applied.

First I unpublish the user fields on the users dashboard with the cog menu item marked with a red frame in following screenshot:

snap-1

After that, the users dashboard shows still the other submenu items:

snap-2

When I reload the page, the users dashboard shows only the "normal" backend module:

snap-3

The admin menu manage view shows the users submenu unpublished:

snap-4

When I publish it again, the users dashboard looks like at the beginning.

So it seems we can unpublish only the complete admin submenu module, ok. that might be expected behavior.

But that in the middle we still see the other items which disappear after page reload, that's a bit strange.

Anyway, if you say that's intended behavior or not subject of this PR, I will give it a good test.

**Comment by chmst** [comment]
@richard67 thank you for testing and making this clear.

I found the js problem by chance while trying to build an own dashboard. It is confusing, also for me and needs some thinking about menu presets. The presets and their usage are not new in joomla but first I must find out how this works.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on d5827bdeb3d923c3b1b056c8a5d1baa752acc86f<br /><br />Fixes js error as described.

Other oddities regarding modules of type "admin submenu" with or without presets are not subject of this PR.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26009">issues.joomla.org/tracker/joomla-cms/26009</a>.</sub>

**Comment by infograf768** [comment]
> Other oddities regarding modules of type "admin submenu" with or without presets are not subject of this PR.

Agree. I just pointed to them to explain @alikon issue in https://github.com/joomla/joomla-cms/pull/26009#issuecomment-524605478

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 549357855edb150e1afdc719519d14ef5ed17846<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26009">issues.joomla.org/tracker/joomla-cms/26009</a>.</sub>

**Comment by infograf768** [comment]
RTC.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26009">issues.joomla.org/tracker/joomla-cms/26009</a>.</sub>

**Comment by infograf768** [comment]
tks

**Pull request merged**
