### PR TITLE
[4.2] Fix deprecated warnings for HTMLHelper Calendar

### PR DESCRIPTION
**Pull request by joomdonation**
Pull Request for Issue # .

### Summary of Changes
On PHP 8.1+, we will see deprecated warning like below when you use HTMLHelper calendar method

`Deprecated
: Function strftime() is deprecated in [ROOT]\libraries\src\HTML\HTMLHelper.php on line XXXX`

This PR attempts to solve it by converting some of the most widely used format parameters uses by `strftime() ` function to the DateTime format use by `DateTime` class. Then use `DateTimeImmutable` class to format the input value instead of using `strftime()` function.

The supported formats which will be converted automatically are: **%Y**, **%m**, **%d**, **%H**, **%M**, **%S**. 

It does not solve the issue for every cases, but hopefully, most of developers just use these supported formats and won't have to update their code to address this deprecated warning.

### Testing Instructions
1. Use Joomla 4 on PHP 8.1 or PHP 8.2
2. Open the file , paste the following lines of code somewhere administrator/templates/atum/index.php (I attempt to test the function with different combination of the supported formats)

```php
$data = [
  '%Y-%m-%d' => '2023-12-20',
  '%d-%m-%Y' => '2023-12-20',
  '%m-%d-%Y' => '2023-12-20',
  '%Y-%m-%d %H:%M:%S' => '2023-12-20 13:20:00',
  '%d-%m-%Y %H:%M:%S' => '2023-12-20 13:20:00',
  '%m-%d-%Y %H:%M:%S' => '2023-12-20 13:20:00',
  '%Y-%m-%d %H:%M' => '2023-12-20 13:20',
  '%d-%m-%Y %H:%M' => '2023-12-20 13:20',
  '%m-%d-%Y %H:%M' => '2023-12-20 13:20',
];

$name = 'test_calendar';
$count = 0;

foreach ($data as $format => $value) {
    echo HTMLHelper::_('calendar', $value, $name . '_' . $count, $name . '_' . $count, $format) . '<br />';
    $count++;
}
```

### Actual result BEFORE applying this Pull Request
You will see ton of deprecated warnings

### Expected result AFTER applying this Pull Request
No warnings anymore, the calendar inputs are displayed with the right date.

### Link to documentations
Please select:
- [x] No documentation changes for docs.joomla.org needed
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 342cf1f03c43a988f70eddb4df048693ca800b7b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39869">issues.joomla.org/tracker/joomla-cms/39869</a>.</sub>

**Comment by alikon** [comment]
after pr
image

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 342cf1f03c43a988f70eddb4df048693ca800b7b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39869">issues.joomla.org/tracker/joomla-cms/39869</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39869">issues.joomla.org/tracker/joomla-cms/39869</a>.</sub>

**Comment by fancyFranci** [comment]
Nice! Thank you!

**Pull request merged**
