### PR TITLE
Language install core loader - Show Joomla Spinner on language install

### PR DESCRIPTION
**Pull request by MacJoom**
Pull Request for Issue #.

### Summary of Changes

Show Joomla Logo while installing additional language

### Testing Instructions

Install additional language (System Dashboard)

### Actual result BEFORE applying this Pull Request

No Spinner is shown

### Expected result AFTER applying this Pull Request

Joomla Logo Spinner is shown

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by fgsw** [comment]
I have tested this item :white_check_mark: successfully on 989f88ee2e4316f7fc10290223fda11d3a45a4cd<br /><br />Thanks @MacJoom<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42602">issues.joomla.org/tracker/joomla-cms/42602</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 989f88ee2e4316f7fc10290223fda11d3a45a4cd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42602">issues.joomla.org/tracker/joomla-cms/42602</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42602">issues.joomla.org/tracker/joomla-cms/42602</a>.</sub>

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
