### PR TITLE
[5.1] Alpha sorting strings in plg_system_jooa11y.ini

### PR DESCRIPTION
**Pull request by tecpromotion**
### Summary of Changes

alpha sorting

### Testing Instructions

.

### Actual result BEFORE applying this Pull Request

not sorted alphabetically

### Expected result AFTER applying this Pull Request

sorted alphabetically

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 5c323ef4407793cf36638778c988b4134bf331a4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43122">issues.joomla.org/tracker/joomla-cms/43122</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 5c323ef4407793cf36638778c988b4134bf331a4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43122">issues.joomla.org/tracker/joomla-cms/43122</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43122">issues.joomla.org/tracker/joomla-cms/43122</a>.</sub>

**Comment by LadySolveig** [comment]
Thank you @tecpromotion  and also for review and testing @Quy @viocassel

**Pull request merged**
