### PR TITLE
[4.0] Use scalar typehints and return types for new APIs and final classes in libraries

### PR DESCRIPTION
**Pull request by mbabker**
### Summary of Changes

Makes use of PHP 7 typing features in classes/methods new to the 4.0 or classes/methods which are declared final and therefore B/C breaks are acceptable for these changes since final classes/methods cannot be extended.

### Testing Instructions

Code review

### CODE REVIEW

**Comment by wilsonge** [comment]
Unsure about the MVCFactory changes. Currently these are going into the 3.9 branch https://github.com/joomla/joomla-cms/blob/3.9-dev/libraries/src/MVC/Factory/MVCFactoryInterface.php - the 3.9 interface and 4.x interface should be compatible so if we do this we should backport the typehints into 3.9 and document a PHP 7 minimum there i guess as a 4.x compatibility feature

**Comment by mbabker** [comment]
Well, I'm just going by `@since` tags right now.  Since they have 4.0 versions, I can only assume that's the first version they're in place unless they're corrected.

**Comment by wilsonge** [comment]
Yeah that's my fault. We haven't tagged any alpha's in 3.9 yet so it still has an `__DEPLOY_VERSION__` version. When I tagged the 4.0 alpha it got replaced. That's just my bad :/

**Comment by mbabker** [comment]
Undid changes to MVC factory stuff.

**Pull request merged**
