### PR TITLE
Warn users that is not possible to use Shared session with Force HTTPS = Administrator Only

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/16485.

### Summary of Changes

Adds a warning message when the used set the config to use "Shared Session" with "Force HTTPS" to "Administrator Only".

### Testing Instructions

1. Apply patch
2. Set config "Shared Session" to "Yes" and "Force HTTPS" to "Administrator Only".
4. Config saved but you get a warning telling that shared session will not work.

### Expected result

Warn the user that shared sessions will nto work with current configuration.

### Actual result

None.

### Documentation Changes Required

None.

### CODE REVIEW

**Comment by richard67** [comment]
@andrepereiradasilva For me this PR does not work because when changing the "Shared Session" value and saving the config, I get logged out and so never will see any warning message. The tooltip of the "Shared Session" toggle clearly tells that, too. So maybe it would be sufficient just to change that tool tip text so it contains your warning in general? I tested on a 3.7.2, not on latest staging.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16509">issues.joomla.org/tracker/joomla-cms/16509</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@richard67 yes you're right will close this and just make a PR to add info to the shared session tooltip

**Comment by andrepereiradasilva** [comment]
@richard67 check https://github.com/joomla/joomla-cms/pull/16514

**Comment by richard67** [comment]
@andrepereiradasilva Maybe you should also add some information to the COM_CONFIG_FIELD_FORCE_SSL_DESC text that when choosing "Administrator only", the "Shared Session" option will not work anymore ;-) But this would cause a merge conflict with the other PR you have open for the secure cookie info :-P

**Pull request closed without merging**
