### PR TITLE
Newsfeeds - move Filters from left to [Search Tools]

### PR DESCRIPTION
**Pull request by pe7er**
This PR moves the Filter options of the Newsfeeds to the [Search Tools] button.
**Note**: The ordering dropdown in [Search Tools] **needs to be fixed** before merging.
(See Issue #6941 regarding the inconsistency with Filter options).
## Test instructions

In back-end > Components > Newsfeeds
See the filters on the left

screen shot 2015-05-15 at 08 07 33

Compare with the filters in **Category Manager for Newsfeeds**: 
In back-end > Components > Newsfeeds > Categories

screen shot 2015-05-15 at 08 07 33
### This PR changes moves the Filters

from the left to the middle column and will be visible when you click on the [Search Tools] button.

screen shot 2015-05-15 at 08 07 33
### **Notes:**

I can use some help & suggestions regarding the following issues:
- The ordering dropdown in [Search Tools] is currently not working
- The /administrator/components/com_newsfeeds/views/newsfeeds/tmpl/default.php might have old obsolete code in it
- The /administrator/components/com_newsfeeds/views/newsfeeds/view.html.php still has **protected function getSortFields()** which might be obsolete because the order options are now specified in /administrator/components/com_newsfeeds/models/forms/filter_newsfeeds.xml

### CODE REVIEW

**Comment by brianteeman** [comment]
After applying the patch the filters do move - great
BUT
After applying a filter they are hidden again - if you look at article manager they are still open<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6952">issues.joomla.org/joomla-cms/6952</a>.</sub>

**Comment by brianteeman** [comment]
Also as Tag information  is NOT visible in the list view it seems strange to me for their to be a filter<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6952">issues.joomla.org/joomla-cms/6952</a>.</sub>

**Comment by pe7er** [comment]
Thanks for testing! I've to check the issue with the [Search Tools] closing after filtering.

I agree with removing the "Tag" filter as it's not displayed in any of the columns.

**Comment by m-b-o** [comment]
Works fine
BUT
the filters are hidden after applying<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6952">issues.joomla.org/joomla-cms/6952</a>.</sub>

**Comment by pe7er** [comment]
Thanks for testing. I corrected the problem with the closing Search Tools for Category + Tags filter.
Now the [Search Tools] should remain opened when any of the filters has been selected.

**Comment by brianteeman** [comment]
Retested and all good now<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6952">issues.joomla.org/joomla-cms/6952</a>.</sub>

**Comment by brianteeman** [comment]
Setting RTC now - thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6952">issues.joomla.org/joomla-cms/6952</a>.</sub>

**Comment by mbabker** [comment]
Merged to `3.5-dev` via c8b9875

**Pull request closed without merging**
