### PR TITLE
[4.0] DRY for warning pages

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # .

### Summary of Changes
Code refactoring for the two warning pages (unsupported PHP version, incomplete Env)
- one command for both `node build.js --build-check`
- settings stored in the setitngs.json
- one, html/css/js file
- 
### Testing Instructions
Check the generated files in the system template, appart from various CS they are exactly the same! WIN

### CODE REVIEW

**Comment by wilsonge** [comment]
You need @rdeutz to fix drone if we do this (i can't see this step in the drone yml file)

**Comment by rdeutz** [comment]
it is in the prepare step npm install does the trick via the postinstall script

**Comment by dgrammatiko** [comment]
@rdeutz do I have to patch something here?

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
