### PR TITLE
[4.3] Discover Select columns

### PR DESCRIPTION
**Pull request by brianteeman**
Adds the column select script to the discover extensions view

To test make sure you have some extensions in a discover state

image

### CODE REVIEW

**Review by wilsonge — APPROVED** [review]

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 2fd6f969b5d3fa8176fda0f4b6fe6f9a32766a07<br /><br />Works and does not hurt, but seems rather useless in this table.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39284">issues.joomla.org/tracker/joomla-cms/39284</a>.</sub>

**Comment by brianteeman** [comment]
> Works and does not hurt, but seems rather useless in this table.
> 
>

Depends on the screen size and some extensions really abuse what they can put in these fields making it necessary at all screen sizes

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 2fd6f969b5d3fa8176fda0f4b6fe6f9a32766a07<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39284">issues.joomla.org/tracker/joomla-cms/39284</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39284">issues.joomla.org/tracker/joomla-cms/39284</a>.</sub>

**Comment by laoneo** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
