### PR TITLE
[#31495] Fixing Smartsearch to allow for searching for date ranges

### PR DESCRIPTION
**Pull request by Hackwar**
This creates a PR from this JC item: http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=31495&start=25
Simply doing this so that the JC item can be closed and we have this in JIssues instead.

### CODE REVIEW

**Comment by nueckman** [comment]
Need rework<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4175">issues.joomla.org/joomla-cms/4175</a>.</sub>

**Comment by roland-d** [comment]
Hello @Hackwar 

Can you please follow up on the unsuccessful tests. Thank you.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4175">issues.joomla.org/joomla-cms/4175</a>.</sub>

**Comment by roland-d** [comment]
Hello @Hackwar

Thank you for your contribution.

The last comment here was on 21st August. So the question is, Is this issue/pull request still valid?
If no reply is received within 4 weeks we will close this issue.

Thanks for understanding! <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/4175">issues.joomla.org/joomla-cms/4175</a>.</sub>

**Comment by Hackwar** [comment]
Hello @roland-d I did not create this change myself, but simply pulled in the patch from joomlacode before it got lost. The main change, the date comparison in the last changed lines in this PR are already added, so I guess this can be dropped. I'll close it. :smiley:

**Pull request closed without merging**
