### PR TITLE
Fix folder browsing and file upload that broke in 3.8.8 due to escaping

### PR DESCRIPTION
**Pull request by PhilETaylor**
Pull Request for Issue #20585 .

### Summary of Changes

replace encoded slashes with hard slashes only when needed
(Conservative approach, instead of decoding the whole string, just in case the encoding was done for 'security' reasons (hint: it was))

### Testing Instructions

replicate #20585 - apply PR - should be fixed.

### CODE REVIEW

**Comment by PhilETaylor** [comment]
@mbabker  @joomla/security

**Comment by ViscountVic** [comment]
I have tested this item :white_check_mark: successfully on 579a6ed11897ee96833e547442192f23f7bd784f<br /><br />Changes working right. Thank you very much.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20586">issues.joomla.org/tracker/joomla-cms/20586</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 579a6ed11897ee96833e547442192f23f7bd784f<br /><br />Looks OK here<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20586">issues.joomla.org/tracker/joomla-cms/20586</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Comment by madesign** [comment]
Still happen to me. Will it be fixed with the next update?

**Comment by Quy** [comment]
Yes in the next release v3.8.9.

**Comment by MattMcManis** [comment]
@Quy @franz-wohlkoenig 

How can I patch it myself in 3.8.8 instead of waiting for 3.8.9? It has broken the functionality of a site I'm working on.

**Comment by Leen29** [comment]
Hello all,
on one of my test site I have this problem also have it already updated to joomla 3.8.9 dev but it remains strange. I can just put the image in a subfolder.
but I make a new article on the administrator side and I want to go there
uploading a photo and putting it in a special folder does not work.
But I can edit an article via the frontside there I can upload an image in a sub folder.
ps
sorry for mv english 't s from google.translate

**Comment by ghost** [comment]
@Leen29 can you please open a new Issue as this one is merged?

**Pull request merged**
