### PR TITLE
[4.0] RTL: correcting Joomla Installation display

### PR DESCRIPTION
**Pull request by infograf768**
### Summary of Changes 
Correcting Select language height by taking off `custom-select-sm` (this also for LTR) and using the correct `select-bg-rtl.svg` for RTL by adding the file.
Correcting placement of top icon
Correcting Install Languages caption text alignement

Deleted unused `select-bg-active.svg`

### Testing Instructions
Patch. Run npm.
Edit en-GB langmetadata.xml to set RTL to 1

### Before patch
LTR

selectlanguage-nosm

RTL
Screen Shot 2020-01-31 at 08 03 04

### After patch

RTL Top icon correct placement
Select language OK (height also OK for LTR )

firstpage-rtl

RTL Caption (text-align was set to left)

caption-rtl

### CODE REVIEW

**Comment by Quy** [comment]
This is also an issue in LTR except there is a space between label and switcher.

**Comment by chmst** [comment]
Not sure about that. After patch has still a language which per se is ltr, also users which a rtl language will see and read it ltr. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27732">issues.joomla.org/tracker/joomla-cms/27732</a>.</sub>

**Comment by infograf768** [comment]
>  After patch has still a language which per se is ltr, also users which a rtl language will see and read it ltr

This has been corrected by @wilsonge recently. It now behaves correctly as in J3.
The language selected in the first page, ltr or rtl will remain effective until quitting installation and therefore the direction is too. It is defined by the rtl metadata.
Evidently, as we have no Rtl installation lang yet, the strings are taken from en-GB, but it is easy in this case to see that evrything is fine. Look for example at the periods which are placed at the left. Alignment is also the important part.
Concerning the issue remarked by @Quy I will look what I can do tomorrow.

**Comment by infograf768** [comment]
@Quy 
Switcher label now corrected.

RTL
Screen Shot 2020-02-01 at 08 57 25

LTR
Screen Shot 2020-02-01 at 08 54 30

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 47cf8b243c3d7b025ddd7c740e00dab31f2659bd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27732">issues.joomla.org/tracker/joomla-cms/27732</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 47cf8b243c3d7b025ddd7c740e00dab31f2659bd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27732">issues.joomla.org/tracker/joomla-cms/27732</a>.</sub>

**Comment by richard67** [comment]
@infograf768 PR does what it claims to do, so I give it a good test.

But I saw that when editing the database prefix field and the browser offers a previously used value, the offered value is left aligned:
test-pr-27732_2

With other text fields this is not the case:
test-pr-27732_1

Do you think you can fix that, too?

**Comment by infograf768** [comment]
> and the browser offers a previously used value, the offered value is left aligned

How did you get that?

**Comment by infograf768** [comment]
That value is set to be LTR and align right when using an RTL language, in order to get the underscore correctly.

```
#jform_db_prefix {
    direction: ltr;
    text-align: right;
}
```
I remarked that the field "remembers" former prefixes used. I.e. when we click in the field when it is empty, you can choose one of the prefixes in the list.

Screen Shot 2020-02-02 at 08 32 18

The fact that this specific field is set as LTR forces the dropdown to display it as LTR. The text-align is not considered by the browser.

Therefore I guess nothing we can do about that and if you chose one of the existing values it will display correctly in the field and saved correctly.

**Comment by infograf768** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27732">issues.joomla.org/tracker/joomla-cms/27732</a>.</sub>

**Comment by wilsonge** [comment]
Getting this in so we largely have a working RTL installer. If anyone has ideas on specifics for that dropdown willing to consider any further PRs obviously

**Comment by brianteeman** [comment]
It is always going to be "strange" when you use an ltr text in a RTL site.

**Comment by richard67** [comment]
@infograf768 Sorry for late answer, but I needed my beauty sleep ;-) I thought that drow down is a standard Firefox thing, am using the latest version. But meanwhile I'm not so sure, maybe it is also coming from my F-Secure addon. It shows that drop down as soon as you type something in that field which fits to what was remembered for that field from previous usage. E.g. if for username field was "richard" in past, it shows the dropdown when you are starting to type "rich". For me this is not really an issue.

**Comment by richard67** [comment]
@infograf768 P.S.: [Your explanation above](https://github.com/joomla/joomla-cms/pull/27732#issuecomment-581107814) explains it well and is absolue ok for me.

**Comment by infograf768** [comment]
@richard67 
I have also looked at unicode-bidi and bidi-direction.
It looks like Firefox is storing remembered fields (in `formhistory.sqlite`) as stated in these advanced parameters and only taking care of the direction, not text-align. A pure RTL direction will store it as align right.

**Pull request merged**
