### PR TITLE
[com_contact] add searchtools to modal layout and solves bugs

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Description

This PR adds searchtools to com_contact modal layout contacts view.

Also, in normal layout:
- correct bug: by default the filter was open with no filters selected.
- correct bug: when selecting the category filter or the tag filter the searchtools hides.
- improves responsive visual (mobile/tablet/desktop)
- solves other minor graphical issues.
- minor code style improvements
###### Before PR

image
###### After PR

image
###### Before PR (modal)

image
###### After PR  (modal)

image
#### How to test

Normal view:
1. Install latest staging and apply this patch
2. Go to Components -> Contacts
3. Check if search, filters, ordering and pagination are working properly
4. Test on mobile and tablet (ex: reduce browser width)

Modal view:
1. Enable language associations.
2. Create some contacts in several languages.
3. Edit one of those contacts and go to "Associations" tab and click on "Select" on any language.
4. Check if search, filters, ordering and pagination are working properly in modal.
5. Test on mobile and tablet (ex: reduce browser width)

### CODE REVIEW

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 6297df570ef6916dcac620aee4b55d776800b25b<br /><br />Works fine.



To testers, this PR includes the same changes to the field type "Category" as https://github.com/joomla/joomla-cms/pull/9195.

Therefore they have to be tested separately after reverting one of them.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9198">issues.joomla.org/joomla-cms/9198</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 6297df570ef6916dcac620aee4b55d776800b25b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9198">issues.joomla.org/joomla-cms/9198</a>.</sub>

**Comment by brianteeman** [comment]
RTC - thanks again<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9198">issues.joomla.org/joomla-cms/9198</a>.</sub>

**Comment by rdeutz** [comment]
@andrepereiradasilva could you have a look at the merge conflicts, thanks.

**Comment by andrepereiradasilva** [comment]
conflicts fixed

**Pull request merged**
