### PR TITLE
[4.0] com_contacts fields

### PR DESCRIPTION
**Pull request by brianteeman**
Contacts has an option to show custom user fields. I thought it wasn't working as the list didnt show any of my fields. On closer inspection the problem was that it is supposed to be "field groups" not "fields".

This PR changes the field label from "User Custom Fields" to "User Custom Field Groups"

image

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 9e8abd1ed39b2d72eca394a05d2ae99f31e830b4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28275">issues.joomla.org/tracker/joomla-cms/28275</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 9e8abd1ed39b2d72eca394a05d2ae99f31e830b4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28275">issues.joomla.org/tracker/joomla-cms/28275</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28275">issues.joomla.org/tracker/joomla-cms/28275</a>.</sub>

**Comment by richard67** [comment]
Thanks.

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
