### PR TITLE
[4.1] spelling trough/through

### PR DESCRIPTION
**Pull request by brianteeman**
code review only

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 857592a08d9d8474a96fea822f5832aac87c77de<br /><br />review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38054">issues.joomla.org/tracker/joomla-cms/38054</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 857592a08d9d8474a96fea822f5832aac87c77de<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38054">issues.joomla.org/tracker/joomla-cms/38054</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38054">issues.joomla.org/tracker/joomla-cms/38054</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
