### PR TITLE
Reference issue #17065 - REGRESSION[4.0]: Database driver limit/offset not working anymore for SQL strings

### PR DESCRIPTION
**Pull request by joeforjoomla**
Pull Request for Issue #17065 .

### Summary of Changes
Allow to set a LIMIT clause for direct queries.

### CODE REVIEW

**Comment by mbabker** [comment]
1) The change needs to be applied on the Framework repository instead of direct editing the file here in the CMS repo
2) Look at my last comment in the issue, that should fix the logic for all drivers and not apply a partial fix for one specific code path

**Comment by joeforjoomla** [comment]
Just wanted to point you out an idea about the issue and how to fix it. I've not so much knowledge of the Framework repository that you are merging into J4

**Comment by joeforjoomla** [comment]
I confirm you that changing the code as you suggested and adding one more processLimit call works: 

`		if ($this->sql)
		{
			return $this->sql;
		}`

to 

`		if ($this->sql)
		{
			$this->sql = $this->processLimit($this->sql, $this->limit, $this->offset);
			return $this->sql;
		}`

**Comment by mbabker** [comment]
https://github.com/joomla-framework/database/commit/a21ee689f82992e0e7b94bb5f7cbd549f9a00c1c fixes it in the Framework repo.  We just need to merge the change up to the 2.0 branch then run a `composer update` here to pull in the change.

This PR can be closed out and we can close the issue once the merge has been finished.

**Comment by joeforjoomla** [comment]
Thanks Michael, sounds great.
I'll close the issue as well when the merge has been completed.

**Pull request closed without merging**
