### PR TITLE
[4.0] Pull left permission field for com_config

### PR DESCRIPTION
**Pull request by chmst**
Pull left the Permissions Field of com_config.

### Testing Instructions
Have a look on Global Configuration, Tab permission. Before and after applying the patch.
The field has some space at the left. 
In all other components there is no space.

### Expected result
All Permission tabs look equal

### Actual result

com_config_permissions

### CODE REVIEW

**Comment by Quy** [comment]
This is not reproducible on the dev branch.

**Comment by chmst** [comment]
Strange. I have the effect on firefox but not on edge or chrome.

**Comment by Quy** [comment]
It is fine for me in Firefox. Try clearing the browser's cache.

**Comment by chmst** [comment]
you are right - the cache.

**Pull request closed without merging**
