### PR TITLE
[4.3] warning.css code style

### PR DESCRIPTION
**Pull request by brianteeman**
The code style is to always have a trailing semicolon

code review

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 2a320b14d5dacbfa20187592594fbbecbe021c32<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39797">issues.joomla.org/tracker/joomla-cms/39797</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 2a320b14d5dacbfa20187592594fbbecbe021c32<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39797">issues.joomla.org/tracker/joomla-cms/39797</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39797">issues.joomla.org/tracker/joomla-cms/39797</a>.</sub>

**Comment by obuisard** [comment]
Thank you Brian @brianteeman !

**Comment by brianteeman** [comment]
Thx

**Pull request merged**
