### PR TITLE
[4.x] Name attribute in xml - code style

### PR DESCRIPTION
**Pull request by brianteeman**
All the `<name>` elements in the xml files use lowercase except for these two.

Doesn't break anything having these in a different case but it does look odd when you look at the #__extensions table

Code review should be enough

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 9ff9d265a7dc6172451cae872967a71e7a1cd3ef<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37387">issues.joomla.org/tracker/joomla-cms/37387</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 9ff9d265a7dc6172451cae872967a71e7a1cd3ef<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37387">issues.joomla.org/tracker/joomla-cms/37387</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37387">issues.joomla.org/tracker/joomla-cms/37387</a>.</sub>

**Comment by Quy** [comment]
Thanks

**Pull request merged**
