### PR TITLE
[4.0][SQL] - wrong inner join

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #21889  .

### Summary of Changes
fixed wrong written INNER JOIN

### Testing Instructions
see #21889 and use PDO

### Expected result

query are written in SQL standard

### Actual result
 query are written in mysql dialect

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 4d0da93caf837dbfb452cfb31b2d1fbcd302207e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21893">issues.joomla.org/tracker/joomla-cms/21893</a>.</sub>

**Comment by richard67** [comment]
There are code style errors though:

FILE: ...joomla-cms/administrator/components/com_content/Model/ArticlesModel.php

FOUND 2 ERROR(S) AFFECTING 2 LINE(S)

 229 | ERROR | Opening parenthesis of a multi-line function call must be the last content on the line
 248 | ERROR | Opening parenthesis of a multi-line function call must be the last content on the line
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21893">issues.joomla.org/tracker/joomla-cms/21893</a>.</sub>

**Comment by alikon** [comment]
grrr

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 07dbc7ef4b47cef303de5bafb04a6cc89dcd9484<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21893">issues.joomla.org/tracker/joomla-cms/21893</a>.</sub>

**Comment by alikon** [comment]
well now drone failure is not up to this pr :sweat_smile:

**Comment by richard67** [comment]
Yes, I saw. Some timeout on user creation.

**Pull request merged**
