### PR TITLE
[4.0] Fix New backend template - change tab issue

### PR DESCRIPTION
**Pull request by anuragteapot**
Pull Request for Issue #21142

### Summary of Changes
Change coding style.

### Testing Instructions
Steps to reproduce the issue

I created the test with new `uitab` function. 
So, if you test this on other place, this will not work.  Because, we have work to convert  `bootstrap.startTabSet` to `uitab.startTabSet`.

So, use 
1.  `article`  visit  `administrator/index.php?option=com_content&view=article&layout=edit` 
and 

2. `template`  visit  `administrator/index.phpoption=com_templates&view=template&id=510&file=aG9tZQ==`

And change tab and refresh page.

### Expected result
 You still on same tab. 

### Actual result
Tab changed.

### Documentation Changes Required
No

@dgrammatiko @laoneo @astridx

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :red_circle: unsuccessfully on 089aec4c8945f0308abc4cab88f6bb768869b5dd<br /><br />Same Behaviour using PR as described in #21142, test on Template > Styles.
### System information
- Nightly Build 4.0.0-alpha4-dev
- Multilingual Sample Data
- Template: Cassiopeia
- macOS Sierra, 10.13.6
- Firefox 61 (64-bit)
#### CloudAccess.net
- PHP 7.1.15
- MySQLi 5.7.18-cll-lve<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21183">issues.joomla.org/tracker/joomla-cms/21183</a>.</sub>

**Comment by dgrammatiko** [comment]
Please undo the changes in the js

**Comment by anuragteapot** [comment]
> I have tested this item red_circle unsuccessfully on 089aec4
> 
> Same Behaviour using PR as described in #21142, test on Template > Styles.
> 
> System information
> Nightly Build 4.0.0-alpha4-dev
> Multilingual Sample Data
> Template: Cassiopeia
> macOS Sierra, 10.13.6
> Firefox 61 (64-bit)
> CloudAccess.net
> PHP 7.1.15
> MySQLi 5.7.18-cll-lve

@franz-wohlkoenig 
Yes, this is an expected behaviour because code is not using new tab function.

**Comment by anuragteapot** [comment]
> Please undo the changes in the js

@dgrammatiko I reverted the changes in js 
After this,  I am getting the same issue.
screenshot from 2018-07-19 18-57-28

**Comment by anuragteapot** [comment]
@dgrammatiko I changes the code here. https://github.com/joomla/joomla-cms/blob/0a976c3811da3f9ddfab358ba6fbcfacdb05f759/build/webcomponents/js/tab/tab.js#L111

To like this 
screenshot from 2018-07-19 19-03-49

**Comment by anuragteapot** [comment]
Then it works fine for me.
Because, `tab.hash` is undefined. We want id of tab right ?

**Comment by anuragteapot** [comment]
@franz-wohlkoenig You can follow this.
1. Open the `System Menü` and click on `Site Templates`
2. Click on 
selection_012

3. Change tab to `Created Overrides` and reload page.

**Comment by dgrammatiko** [comment]
@Anu1601CS the code is not in this repo, it is in https://github.com/joomla-projects/custom-elements

We just copy this to the main repo because it was easier when we were working with the backend template.
Essentially if you change something here will be lost when we switch to the normal, custom elements repo.

**Comment by anuragteapot** [comment]
@dgrammatiko Ok, should i close this ?
And, make a PR in  
https://github.com/joomla-projects/custom-elements

**Comment by Quy** [comment]
@Anu1601CS Yes, that is how I interpreted his comment.

**Comment by dgrammatiko** [comment]
No this pr right now is fine

**Review by dgrammatiko — APPROVED** [review]

**Comment by ghost** [comment]
@Anu1601CS i was following Description in #21142 as the Test Instructions wasn't clear for me.

Will try again.

**Comment by ghost** [comment]
Following Instructions on https://github.com/joomla/joomla-cms/pull/21183#issuecomment-406283502 got:
screen shot 2018-07-19 at 16 56 27

**Comment by anuragteapot** [comment]
@franz-wohlkoenig No, right now this change is fine as @dgrammatiko commented.
Because we have work to change `bootstrap.startTabSet` to `uitab.startTabSet` as per our new code.

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on f71268c53f931de0cabcb5befad507226e40f7a7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21183">issues.joomla.org/tracker/joomla-cms/21183</a>.</sub>

**Comment by anuragteapot** [comment]
https://github.com/joomla/joomla-cms/pull/21183#issuecomment-406283502
@franz-wohlkoenig Yes, this is an issue right now. So, we have to fix in main custom elements repo here https://github.com/joomla-projects/custom-elements 

Then, this issue going to fix.
I would suggest you to reopen this issue. #21142

**Comment by ghost** [comment]
#21142 reopened as stated above.

**Comment by astridx** [comment]
I have tested this item :white_check_mark: successfully on dae854fc717215dc0c809e0e3f4b534e8fab760e<br /><br />I checked out this branch and I could see the new uitab. As only the file administrator/components/com_templates/tmpl/template/default.php is changed that's what I expected.

After refreshing I saw the content of all tabs on the page (among themselves). That should be changed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21183">issues.joomla.org/tracker/joomla-cms/21183</a>.</sub>

templates customise cassiopeia test administration 28

**Comment by dgrammatiko** [comment]
> After refreshing I saw the content of all tabs on the page (among themselves). That should be changed.

what do you mean? The content is available before the js has been executed, this is normal. Hiding it is a huge problem for SEO!

**Comment by astridx** [comment]
@dgrammatiko 

> what do you mean? The content is available before the js has been executed, this is normal. Hiding it is a huge problem for SEO!

I mean that I see all content like you see in the attached picture. I only expect to see the content of the current tab. But I think we have to handle this via javascript int the the file `/media/system/webcomponents/js/joomla-tab.js` , right?

**Comment by dgrammatiko** [comment]
@astridx all the tabs are active as far as i can see, that's why you see all the tabs

**Comment by dgrammatiko** [comment]
This tabs bug will be fixed shortly

**Comment by astridx** [comment]
> This tabs bug will be fixed shortly

@dgrammatiko Thank you for confirming. I marked the test as successful because I assumed that this is just about switching to the new ui tabs. I just wanted to say that the view is not quite correct yet.

**Comment by dgrammatiko** [comment]
please test https://github.com/joomla/joomla-cms/pull/21204

**Comment by laoneo** [comment]
What's the status here?

**Comment by anuragteapot** [comment]
@laoneo We will wait until #21204 get merge to the core.

**Comment by astridx** [comment]
#21204 is merged now.

**Comment by anuragteapot** [comment]
@dgrammatiko Is tab issue fixed?

**Comment by dgrammatiko** [comment]
@Anu1601CS I have no clue, I added the part for the id, is there something else broken?

**Comment by anuragteapot** [comment]
@dgrammatiko Yes, I think here https://github.com/joomla-projects/custom-elements/blob/563e8c4e36038bcd3723720f6903adb9b34110ac/src/js/tab/tab.js#L104

It always gives `-1` . So, if we set `if (tabLinkHash.indexOf(theId) === -1)`  Then, it works fine.

**Comment by brianteeman** [comment]
Closed - nothing left to do here and I created a pr for the js https://github.com/joomla-projects/custom-elements/pull/106

**Pull request closed without merging**
