### PR TITLE
[4.0] Strip zero padding from openssl_decrypt response

### PR DESCRIPTION
**Pull request by cheesegrits**
Pull Request for Issue # .

### Summary of Changes

Strip zero padding from plaintext response in OpenSSL decrypt, otherwise encrypting / decrypting is not symmetrical, unless the plain text was exactly the same as the OpenSSL block length.  So encoding a plain text string, then decoding it, the decoded result will (most likely) not be "==" or "===" the plain text.

NOTE - the rtrim() is exactly what the com_users UserModel does when fetching the OTP ...

https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_users/Model/UserModel.php#L1061

... which I wish I'd known before spending an hour or so banging my head on this one.  And seems to me like the rtrim() should just go in decrypt, and not be something that has to be applied to the returned value.

### Testing Instructions

Insert this code at the bottom of ./index.php

```
$key = \JFactory::getConfig()->get('secret');
$aes = new Joomla\CMS\Encrypt\Aes($key, 256);
$plaintext = "this is a test, this is only a test, do not adjust your set";
$encrypted = $aes->encryptString($plaintext);
$decrypted = $aes->decryptString($encrypted);
if ($plaintext === $decrypted) {
	echo "YAY!";
}
else
{
	echo "WTAF?!?";
	var_dump($plaintext, $decrypted);
}
```
... then load the page.

### Expected result

Expect result is "YAY!", my decrypted result === my plain text.

### Actual result

Actual result is "WTAF?!?".  My decrypted result was not === my plain text, because it got zero padded.

Apply the PR, and YAY!

### Documentation Changes Required

None?

### CODE REVIEW

**Comment by ghost** [comment]
Changed Title to "[4.0] ".<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19182">issues.joomla.org/tracker/joomla-cms/19182</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 215c37085d38c771a2c3ae7b6fe2f97d2e227980<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19182">issues.joomla.org/tracker/joomla-cms/19182</a>.</sub>

**Comment by laoneo** [comment]
Now the rtrim in the UserModel is not needed anymore, can you remove that then please. Thanks.

@mbabker are you ok with the change?

**Review by mbabker — APPROVED** [review]

**Comment by laoneo** [comment]
Thanks.

**Pull request merged**
