### PR TITLE
[4.0] correct date for .sql update file

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #28387 .

### Summary of Changes
rename update sql files from 4.0.0-2020-09-03.sql to 4.0.0-2020-03-10.sql

### Testing Instructions
review

### CODE REVIEW

**Comment by ReLater** [comment]
But there exists already another and different file "4.0.0-2020-03-09.sql".
https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_admin/sql/updates/mysql/4.0.0-2019-03-09.sql

Combine them?

**Comment by richard67** [comment]
@ReLater The one you've linked above is same day and month but for 2019, here  we deal with 2020 ;-)

**Comment by richard67** [comment]
@alikon Last change was not really necessary because @ReLater mixed up 2019 and 2020. But it also doesn't do any harm so you can leave it as it is now.

Update: But if you leave it as it is now, you have to change the file name in your PR description.

**Comment by alikon** [comment]
grr , 
Screenshot from 2020-03-18 13-54-28
cannot find that on local repo anyway  changed

**Comment by richard67** [comment]
@alikon If you leave it as it is now, you have to change the file name in your PR description.

**Comment by ReLater** [comment]
Oh, sorry, sorry for confusion!!
There is a conflicting file 4.0.0-2020-03-09.sql in my installation.
It comes from pr for plg_system_donttranslate that I applied wit Joomla Patch Tester. https://github.com/joomla/joomla-cms/pull/28261

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 21136185bf834eb507c01abd2ef94deb1bf2ada9<br /><br />Tested by review. I've changed the new file name in the description so it matches the last changes.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28388">issues.joomla.org/tracker/joomla-cms/28388</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
