### PR TITLE
Introduce Free2Wait monetization of open-source development

### PR DESCRIPTION
**Pull request by PatchRanger**
### Summary of Changes
Please refer to https://github.com/Free2Wait/composer-free2wait .
In short: this PR proposes a way to monetize open-source development of your project.
The idea is similar to how free-to-play works in gamedev industry: "You are free to wait for the package download - but in case if time is money for you, please consider buying non-waiting access to the package - every cent goes to the package developer to incentive the open-source development."

Please give me your feedback about the idea: what do you think? Does it comply & correspond to open-source development spirit? What benefits do you see? And what drawbacks?

### CODE REVIEW

**Comment by alikon** [comment]
> what do you think? 

it's a joke ?

> Does it comply & correspond to open-source development spirit?

NO

**Comment by PatchRanger** [comment]
> it's a joke ?

@alikon No, it isn't. I've made a prototype of working service - and am really interested whether it corresponds to your needs.

> NO

Could you please clarify a bit: why do you think it is not affordable way of monetizing open-source development?

**Comment by alikon** [comment]
to be crystal clear, i speak only for myself
`monetizing  open-source development`  is a contraddiction in terms

**Comment by Bakual** [comment]
Certainly nothing for a CMS where security releases have to be applied as fast as possible.
In fact this also contradicts the very nature of OpenSource as access to the software shall not be restricted. Otherwise it becomes ClosedSource 👎

**Comment by PatchRanger** [comment]
Happy New 2018 Year!

> monetizing open-source development is a contraddiction in terms

@alikon Actually it isn't, it's a common misconception.
As Richard Stallman stated:

> Free software is a matter of liberty, not price. To understand the concept, you should think of free as in free speech, not as in free beer.

See also for reference:
- https://en.wikipedia.org/wiki/Free_software
- https://ell.stackexchange.com/a/25k19
- https://www.gnu.org/philosophy/selling.html

> Certainly nothing for a CMS where security releases have to be applied as fast as possible.

@Bakual We could exclude security releases (by tag) from monetization. 

> access to the software shall not be restricted

Do you consider 10-seconds-delay before download as a restriction? To clarify the concept I propose: all sources remain open, everybody can download from or browse at Github at any moment - the only thing I suggest to change is the way it is distributed via package manager ('composer'): defer every package install/update for as little as 10 seconds - or make users to pay micropayment in favor of package developers.

**Comment by brianteeman** [comment]
Composer is not an option for joomla so irrespective of any other issues with your idea it is a no go for us

**Comment by mbabker** [comment]
The Joomla project is not joining in on this endeavor, be it for its non-Composer distributed CMS package or any Composer distributed package.  End of discussion.

**Pull request closed without merging**
