### PR TITLE
Update jQuery Autocomplete to 1.2.22

### PR DESCRIPTION
**Pull request by viocassel**
This PR updates the library jQuery Autocomplete to version 1.2.22.

### CODE REVIEW

**Comment by dam-man** [comment]
@viocassel is this one of the test example we can use for you updated AutoComplete script?

- Navigate to Articles
- Click New 
- Choose Category
- See attachmentscreen shot 2015-10-10 at 05 39 36

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7800">issues.joomla.org/joomla-cms/7800</a>.</sub>

**Comment by waader** [comment]
I have tested this item :white_check_mark: successfully on 0c158315c3ddfe81faf8f366949cc3a3a905a8d3<br /><br />Tested the module and component of com_finder in frontend.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7800">issues.joomla.org/joomla-cms/7800</a>.</sub>

**Comment by pos-it** [comment]
I have tested this item :white_check_mark: successfully on 0c158315c3ddfe81faf8f366949cc3a3a905a8d3<br /><br />Tested with *com_finder* and *com_finder*.
Both do the autocomplete with the jQuery Autocomplete 1.2.22 in the same way as in 1.2.18
Did not find any other Joomla! Component/Module/Plugin that uses the this JS<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7800">issues.joomla.org/joomla-cms/7800</a>.</sub>

**Comment by zero-24** [comment]
RTC. Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7800">issues.joomla.org/joomla-cms/7800</a>.</sub>

**Comment by viocassel** [comment]
Update jQuery Autocomplete to 1.2.24

**Comment by rdeutz** [comment]
could we have one more test on 1.2.24 before merging, please

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on 2a88f1eae90130435e40e11092535ee7d8813228<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7800">issues.joomla.org/joomla-cms/7800</a>.</sub>

**Comment by zero-24** [comment]
Just tested the lastes version with com_finder and it works. Good to merge @rdeutz <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7800">issues.joomla.org/joomla-cms/7800</a>.</sub>

**Pull request merged**
