### PR TITLE
[4.0] Remove tag_desc

### PR DESCRIPTION
**Pull request by brianteeman**
The helptext displayed for the tags field in the article-newsflash module is not needed AND it is not a correct explanation.

As we dont need it and it is the last use of the string then the string is removed as well

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on bfece1ca0cf4a84e5dd0d9e06ab1a7fb44ee9d25<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24321">issues.joomla.org/tracker/joomla-cms/24321</a>.</sub>

**Comment by Hackwar** [comment]
I have tested this item :white_check_mark: successfully on bfece1ca0cf4a84e5dd0d9e06ab1a7fb44ee9d25<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24321">issues.joomla.org/tracker/joomla-cms/24321</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24321">issues.joomla.org/tracker/joomla-cms/24321</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
