### PR TITLE
[4.0] statistcis help

### PR DESCRIPTION
**Pull request by brianteeman**
Add missing string

Thanks to @ceford

PR for #29736

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on ab5ac961d4e5f31b761d57e18d27f7226a1f0c85<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29737">issues.joomla.org/tracker/joomla-cms/29737</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on ab5ac961d4e5f31b761d57e18d27f7226a1f0c85<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29737">issues.joomla.org/tracker/joomla-cms/29737</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29737">issues.joomla.org/tracker/joomla-cms/29737</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thx

**Pull request merged**
