### PR TITLE
[5.1] Minor cleanup for modules JS

### PR DESCRIPTION
**Pull request by C-Lodder**
### Summary of Changes

As Joomla no longer supports IE11, this PR mainly removes the need for converting a NodeList to an Array, as evergreen browser's implementation of `forEach` can iterater over a NodeList.

Also includes some other minor tweaks.

image

### Testing Instructions

Code review @dgrammatiko @Fedik

### CODE REVIEW

**Comment by Fedik** [comment]
Looks good from review, 
However it would be good to see at least one human test to confirm that the Admin menu still works.

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on e971d1ee23a701affb345ea56500dfb298ed4e2e<br /><br />Okay, menu seems still working :) <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42784">issues.joomla.org/tracker/joomla-cms/42784</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on e971d1ee23a701affb345ea56500dfb298ed4e2e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42784">issues.joomla.org/tracker/joomla-cms/42784</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42784">issues.joomla.org/tracker/joomla-cms/42784</a>.</sub>

**Comment by LadySolveig** [comment]
Thank you @C-Lodder and for testing @Fedik @viocassel

**Pull request merged**
