### PR TITLE
Fixing the testing sample data for newsfeeds

### PR DESCRIPTION
**Pull request by zero-24**
Pull Request for Issue #13979 .

### Summary of Changes

The testing sample data points to a non existing neewsfeed id `4` this is changed to id `1`
The testing sample data has an invalid RSS feed for the module this have been moved to `http://feeds.joomla.org/JoomlaMagazine`

Thanks @infograf768  for the analyse and @franz-wohlkoenig for finding the issues.

### Testing Instructions

Install: https://github.com/zero-24/joomla-cms/archive/installation_fixes.zip
Confirm the `Single News Feed` menu entry works now
Confirm the  `Feed Display` works now too

### Expected result

The `Single News Feed` menu entry work
The  `Feed Display` works

### Actual result

The `Single News Feed` menu entry does not work
The  `Feed Display` does not work

### Documentation Changes Required

None.

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 11121fd69ebb2d8de4d8b04be196842767ed24ee<br /><br />URL "Joomla.org" should open in new Tab.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14032">issues.joomla.org/tracker/joomla-cms/14032</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 11121fd69ebb2d8de4d8b04be196842767ed24ee<br /><br />OK for me in sql<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14032">issues.joomla.org/tracker/joomla-cms/14032</a>.</sub>

**Comment by zero-24** [comment]
> URL "Joomla.org" in Menu "Top" should open in new Tab.

Is this a regression or a suggestion? @franz-wohlkoenig

**Comment by franz-wohlkoenig** [comment]
suggestion @zero-24

**Comment by zero-24** [comment]
Ok can you open a new issue for that? I hope i can send a patch for that soon but with the issue it does not get lost ;)
Based on your tests i'm setting this to RTC now :) Thanks!

**Comment by wilsonge** [comment]
Good work :)

**Pull request merged**
