### PR TITLE
[3.x] Deprecate fof for Joomla 4.0

### PR DESCRIPTION
**Pull request by zero-24**
Pull Request for 3.6.3
### Summary of Changes

Deprecate FOF for Joomla 4.0
### Testing Instructions

Code review
### Documentation Changes Required

None here.

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 4c0da178dcde554ceeb14478431010e9427f9d01<br /><br />code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12130">issues.joomla.org/joomla-cms/12130</a>.</sub>

**Comment by mbabker** [comment]
I'd change the message to "include FOF if required" or something similar to
the social package notices personally (FOF3 can be installed via Composer).

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 3e564b1f191009526800f421dce06cb973ce7c39<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12130">issues.joomla.org/joomla-cms/12130</a>.</sub>

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on 3e564b1f191009526800f421dce06cb973ce7c39<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12130">issues.joomla.org/joomla-cms/12130</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12130">issues.joomla.org/joomla-cms/12130</a>.</sub>

**Pull request merged**
