### PR TITLE
Use the new wrapper classes in the filesystem package

### PR DESCRIPTION
**Pull request by mbabker**
Redo of #4827

From our testing sprint in October, we've taken some initial steps to modernize some of our architecture and focus on replacing static methods as able.  To do so without backward compatibility breaks, we've introduced several wrapper classes which are object based and enable developers to utilize these to work with what will be the object based API in a later major release.

This PR demonstrates how the wrappers can be used internally by using the newly created wrappers for the Filesystem package within its classes.  In conjunction with https://github.com/joomla/joomla-cms/pull/4717 this demonstrates how we can begin modernizing the code in phased steps without introducing larger B/C breaks between major releases by providing a compatibility layer in our current releases.
### Testing Instructions
- Apply the patch
- Perform actions in the user interface that interact with the filesystem (the media manager and extension manager are great places to test from)
- Ensure filesystem management still works

### CODE REVIEW

**Comment by Kubik-Rubik** [comment]
Thank you for the new PR, I will look into it in more detail soon!

**Comment by Fedik** [comment]
**test**
works good here
tried upload/create/delete in media manager, and install/uninstall extensions

**Comment by gunjanpatel** [comment]
Working fine in media manager. Tried to Add, remove file and create folder. Tried to install and upgrade component. All working fine for me. 

Testing Environment:

PHP Built On	Linux gunjan 3.13.0-43-generic #72-Ubuntu SMP Mon Dec 8 19:35:06 UTC 2014 x86_64
Database Version	5.5.40-0ubuntu0.14.04.1
Database Collation	utf8_general_ci
PHP Version	5.5.9-1ubuntu4.5
Web Server	Apache/2.4.7 (Ubuntu)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5849">issues.joomla.org/joomla-cms/5849</a>.</sub>

**Comment by brianteeman** [comment]
Has two tests - setting RTC - thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5849">issues.joomla.org/joomla-cms/5849</a>.</sub>

**Pull request merged**
