### PR TITLE
Fix: Empty Sessions / Logged-in in other accounts Ref #5214

### PR DESCRIPTION
**Pull request by enes-oerdek**
See: http://issues.joomla.org/tracker/joomla-cms/5214
#### Original report

My community has over 300.000 registered Members and est. 200.000 users daily. When entering joomla, a lot of users get empty sessions. That means, the Session-ID is just "".
If one of these users log in with the empty session, some of the others are also logged in with the same account. They can edit the profile, read/write personal messages etc. That's a huge problem, because no one wants others to enter the profile.
#### Steps to reproduce the issue

Delete all the cookies, and enter Joomla website.
#### Expected result

User gets an unique Session-ID.
#### Actual result

You are logged in as another user and/or share the empty Session-ID with other people. This happens with low likelihood. But if you have lots of users, it happens a lot.
#### System information (as much as possible)

Joomla:  Joomla! 2.5.27 Stable [ Ember ] 30-September-2014 14:00 GMT 
Webserver:  nginx/1.2.1 
Database-version:  5.5.40-0+wheezy1-log 
PHP:  fpm-fcgi 
#### Additional comments

You can also reproduce this issue, if you change your session-id cookie within browser developer tools.

### CODE REVIEW

**Comment by zero-24** [comment]
Thanks @enesbil i have just send a PR to fix CS issues to make travis happy with us :smile: https://github.com/enesbil/joomla-cms/pull/1/files<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6430">issues.joomla.org/joomla-cms/6430</a>.</sub>

**Comment by creativeprogramming** [comment]
thanks @enesbil hope this will get merged

**Comment by zero-24** [comment]
@creativeprogramming are you able to test it? As you report the same issue. Thanks

**Comment by creativeprogramming** [comment]
I started the test for this patch today (sorry for delay but it's a production environment)

I'll let you know if problem disappears with this patch

**Comment by brianteeman** [comment]
@creativeprogramming were you able to test this?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6430">issues.joomla.org/joomla-cms/6430</a>.</sub>

**Comment by brianteeman** [comment]
Thanks to @euismod2336 for pointing out that this is for Joomla 2.5 which is now end of life and unsupported so I am closing this.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6430">issues.joomla.org/joomla-cms/6430</a>.</sub>

**Pull request closed without merging**
