### PR TITLE
Categories correct ordering with pagination

### PR DESCRIPTION
**Pull request by t-arapi**
Pull Request for Issue # .

### CODE REVIEW

**Comment by brianteeman** [comment]
Please describe the problem this pr fixes. How to replicate the bug and how to test the fix

**Comment by t-arapi** [comment]
When you order all the items, there's no problem, but when i try to put a different pagination order (like for example when i try o put another order, 5 or 10 for pagination, the 1st page is correct, but the other ones are not accurate, as they change the order without me knowing, like they go randomly)
This is a file that shows what I mean: 
aaaa

**Comment by brianteeman** [comment]
Sorry that shows nothing

**Comment by t-arapi** [comment]
###  Category list:
total
### First page 5 items:
p1
### Second page:
p2

**Comment by brianteeman** [comment]
Sorry but I still cannot see what is wrong<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11906">issues.joomla.org/joomla-cms/11906</a>.</sub>

**Comment by jeckodevelopment** [comment]
@t-arapi can you please create an animation that shows the issue? because screenshots are not so clear

**Comment by t-arapi** [comment]
1. Create 7 categories
2. Show content categories diplay all
3. Reorder al cats (remember the order)
4. Show content categories limit 5 (pagination has 2 pages)
5. Go to page 2 and order up the last item
6. Show content categories diplay all
7. Check up the order that you have now and if it is the same as the previous one

Does this help somehow?

**Comment by brianteeman** [comment]
I think I have replicated it - is this what you meant

cats

**Comment by t-arapi** [comment]
Yes, more or less, although the category number 9 should be the sixth in the final order and not  the fisrt.

**Comment by brianteeman** [comment]
Yes that's the bug?

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 508b3f4eb9d6b86463ae3d8d40d3d7fd1343b336<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11906">issues.joomla.org/joomla-cms/11906</a>.</sub>

**Comment by AnishaTailored** [comment]
I have tested this item :white_check_mark: successfully on d6b66a56efaae4ac6644741a95273e2ffc603730<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11906">issues.joomla.org/joomla-cms/11906</a>.</sub>

**Comment by truptikagathara** [comment]
I have tested this item :white_check_mark: successfully on d6b66a56efaae4ac6644741a95273e2ffc603730<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11906">issues.joomla.org/joomla-cms/11906</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11906">issues.joomla.org/joomla-cms/11906</a>.</sub>

**Comment by rdeutz** [comment]
This needs more testing, I am not 100% sure that the fix is ok and doesn't have side effects.

**Comment by rdeutz** [comment]
set to needs review since we have tested this <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11906">issues.joomla.org/joomla-cms/11906</a>.</sub>

**Comment by tomartailored** [comment]
I have tested this item :white_check_mark: successfully on d6b66a56efaae4ac6644741a95273e2ffc603730<br /><br />yes , i have tested this successfully<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11906">issues.joomla.org/joomla-cms/11906</a>.</sub>

**Comment by brianteeman** [comment]
Removed the milestone for now

**Comment by brianteeman** [comment]
@rdeutz have you done a review?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11906">issues.joomla.org/tracker/joomla-cms/11906</a>.</sub>

**Comment by roland-d** [comment]
nudging @rdeutz

**Comment by franz-wohlkoenig** [comment]
maybe @rdeutz is enough.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11906">issues.joomla.org/tracker/joomla-cms/11906</a>.</sub>

**Comment by ghost** [comment]
If this PR get no Response, it will be closed at 17th September 2017.

**Comment by brianteeman** [comment]
@franz-wohlkoenig this PR is waiting a review from a maintainer. It has been tested by several people as good but @rdeutz wanted to hold back on merging it so he could do further tests. It shouldnt be closed just because a maintainer hasnt approved/merged it

**Comment by ghost** [comment]
thanks for Info @brianteeman and thanks for approve @rdeutz

**Comment by rdeutz** [comment]
just go ahead with this, @mbabker can make the decision<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11906">issues.joomla.org/tracker/joomla-cms/11906</a>.</sub>

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
