### PR TITLE
Alpha order com_content (frontend)

### PR DESCRIPTION
**Pull request by zero-24**
### Summary of Changes

alpha order com_content (frontend)

### Testing Instructions

None / Review

### Documentation Changes Required

None

### CODE REVIEW

**Comment by infograf768** [comment]
This is not alpha ordered.
Example:
```ini
+COM_CONTENT_CATEGORY_LIST_TABLE_CAPTION="List of articles in category %s"
 COM_CONTENT_CATEGORY="Category: %s"
```
should be:
```
 COM_CONTENT_CATEGORY="Category: %s"
+COM_CONTENT_CATEGORY_LIST_TABLE_CAPTION="List of articles in category %s"
```
same for
```
 COM_CONTENT_PUBLISHED_DATE_ON="Published: %s"
+COM_CONTENT_PUBLISHED_DATE="Published Date"
```
etc.

**Comment by infograf768** [comment]
I made a PR towards your branch:
https://github.com/zero-24/joomla-cms/pull/24

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on ce09af8eaf237895618658d1c9b2798cbff7abea<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14224">issues.joomla.org/tracker/joomla-cms/14224</a>.</sub>

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on ce09af8eaf237895618658d1c9b2798cbff7abea<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14224">issues.joomla.org/tracker/joomla-cms/14224</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14224">issues.joomla.org/tracker/joomla-cms/14224</a>.</sub>

**Pull request merged**
