### PR TITLE
[4.0] Update TinyMCE and Codemirror

### PR DESCRIPTION
**Pull request by C-Lodder**
### Summary of Changes

Update Tinymce to v4.7.6 and Codemirror to 5.34.0

### CODE REVIEW

**Comment by dgrammatiko** [comment]
You need to run 2 more commands:
`node build --compilecss`
and
`node build --compilejs`

Right now you just removed all the minified css and js from codemirror

**Comment by C-Lodder** [comment]
Just goes to show how long I've been out the game

**Comment by wilsonge** [comment]
This is conflicting with something. Can you please fix :)

**Comment by C-Lodder** [comment]
@wilsonge done

**Comment by mokhin-denis** [comment]
I have tested this item :red_circle: unsuccessfully on 8a032858fc19e6dfd63d568224b1e5c34efe745d<br /><br />TinyMCE works, 
TinyMCE
but I cant see Codemirror.
Codemirror
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19483">issues.joomla.org/tracker/joomla-cms/19483</a>.</sub>

**Comment by C-Lodder** [comment]
@mokhin-denis was the Codemirror issue there before the update?

**Comment by mokhin-denis** [comment]
@C-Lodder I used [Testing Joomla! patches](https://docs.joomla.org/Testing_Joomla!_patches), applied this patch and get that results

**Comment by C-Lodder** [comment]
@mokhin-denis Yes, but was it an issue **before** the patch?

**Comment by mokhin-denis** [comment]
@C-Lodder Should I add an Issue before checking the patch or what? I do not understand

**Comment by C-Lodder** [comment]
Nevermind, I'll take a look later

**Pull request closed without merging**
