### PR TITLE
Correct and clarify tooltip in tag options

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #8916 .
#### Summary of Changes

The options in tags for Display headings and display date were not clear that this only referred to the compact list of tags.

### CODE REVIEW

**Comment by 1apweb** [comment]
I have tested this item :white_check_mark: successfully on 8d3ad8c8be8d756b2631cbbda5c2cd7190a0eb86<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11415">issues.joomla.org/joomla-cms/11415</a>.</sub>

**Comment by Giuse69** [comment]
Hi, I understand that dates and headers are setting for just the compact view and not also for tagged items list (as now in the tooltip), but about number of items, this is not shown even in the compact view. Is this correct?

**Comment by brianteeman** [comment]
It wouldnt show in the compact list as that is a list of the articles that have been tagged not a list of the tags

**Comment by Giuse69** [comment]
Ok, so in which view/menù the number of items is shown?

**Comment by brianteeman** [comment]
Not sure as I am not at my computer and I've only ever used the module but I would assume the one that displays the actual tags and not the list of tagged items.

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on 8d3ad8c8be8d756b2631cbbda5c2cd7190a0eb86<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11415">issues.joomla.org/joomla-cms/11415</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11415">issues.joomla.org/joomla-cms/11415</a>.</sub>

**Pull request merged**
