### PR TITLE
[4.0] Featured Articles View - Add id to Status and Featured

### PR DESCRIPTION
**Pull request by YatharthVyas**
Pull Request for Issue #33725

### Summary of Changes
Added id similar to articles view

### Testing Instructions
1. Apply Patch
2. Visit Backend
3. Featured Articles View

Ensure that the errors are gone and everything works

### Actual result BEFORE applying this Pull Request
image

### Expected result AFTER applying this Pull Request
featured

### Documentation Changes Required
None

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 0cc65d5506d11d64a632528c0c95d8b89b519053<br /><br />Thanks @YatharthVyas <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33738">issues.joomla.org/tracker/joomla-cms/33738</a>.</sub>

**Comment by drmenzelit** [comment]
I have tested this item :white_check_mark: successfully on 0cc65d5506d11d64a632528c0c95d8b89b519053<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33738">issues.joomla.org/tracker/joomla-cms/33738</a>.</sub>

**Comment by drmenzelit** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33738">issues.joomla.org/tracker/joomla-cms/33738</a>.</sub>

**Comment by Quy** [comment]
Thank you!

**Comment by YatharthVyas** [comment]
Thanks everyone

**Pull request merged**
