### PR TITLE
Allow Joomla to be extended with JDEBUG defined by developers

### PR DESCRIPTION
**Pull request by PhilETaylor**
Pull Request for Issue #15827 .

### Summary of Changes

Allow Joomla to be extended with JDEBUG defined by developers when in a sub folder without FOF moaning and fatal erroring. 

### Testing Instructions

Apply PR and check Joomla operates as normal.

Create api.php in Joomla tmp folder with content 

```php
<?php
define('_JEXEC', 1);
define('JPATH_BASE', realpath('../'));
ini_set('display_errors', '1');
error_reporting(E_ALL);
define('JDEBUG', 1);
include_once JPATH_BASE . '/includes/defines.php';
include_once JPATH_BASE . '/includes/framework.php';
include_once JPATH_BASE . '/libraries/joomla/factory.php';
```

### Expected result

No errors on running 

### Actual result

```
PHP Fatal error:  Uncaught Error: Call to a member function logAddLogger() on null in /Users/phil/Sites/joomla-cms/libraries/fof/include.php:26
Stack trace:
#0 /Users/phil/Sites/joomla-cms/libraries/cms.php(45): include_once()
#1 /Users/phil/Sites/joomla-cms/includes/framework.php(23): require_once('/Users/phil/Sit...')
#2 /Users/phil/Sites/joomla-cms/tmp/api.php(8): include_once('/Users/phil/Sit...')
#3 {main}
  thrown in /Users/phil/Sites/joomla-cms/libraries/fof/include.php on line 26
```

### Documentation Changes Required

None

### CODE REVIEW

**Review by mbabker — APPROVED** [review]

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on ec7f86a131b0b86f68f85b32463ac6db1a5392aa<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15843">issues.joomla.org/tracker/joomla-cms/15843</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
@PhilETaylor i have Debug enabled + api.php in tmp-Folder but didn't get `PHP Fatal error:`.

**Comment by PhilETaylor** [comment]
Is your `error_reporting` in PHP disabled or set to `E_ALL` ?  is `display_errors=on` in your `php.ini`?

even with the latest staging I still get this when running the example code: 

```
Fatal error: Uncaught Error: Call to a member function logAddLogger() on null in /Users/phil/Sites/joomla-cms/libraries/fof/include.php:26 Stack trace: #0 /Users/phil/Sites/joomla-cms/libraries/cms.php(45): include_once() #1 /Users/phil/Sites/joomla-cms/includes/framework.php(23): require_once('/Users/phil/Sit...') #2 /Users/phil/Sites/joomla-cms/tmp/api.php(8): include_once('/Users/phil/Sit...') #3 {main} thrown in /Users/phil/Sites/joomla-cms/libraries/fof/include.php on line 26
```

**Comment by franz-wohlkoenig** [comment]
@PhilETaylor thanks for Answer. As i don't know how to set this Values this Issue is about my Knowledge.

**Comment by ghost** [comment]
@PhilETaylor 

> As i don't know how to set this Values this Issue is about my Knowledge.

**Comment by PhilETaylor** [comment]
The testing instructions are in the PR text, under "testing instructions"....

**Comment by ghost** [comment]
i meant comments starting https://github.com/joomla/joomla-cms/pull/15843#issuecomment-303449828

**Comment by ghost** [comment]
Actually i'm testing not as the "how to set this Values this Issue is about my Knowledge".

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on ef3e2f32b1f3db769ae06b721efbcd75053db0fe<br /><br />Changes applied manually.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15843">issues.joomla.org/tracker/joomla-cms/15843</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15843">issues.joomla.org/tracker/joomla-cms/15843</a>.</sub>

**Pull request merged**
