### PR TITLE
[4.0] Remove file from template url

### PR DESCRIPTION
**Pull request by Bakual**
Currently in the template file manager, the URL argument `file` is always present, even when no file is actually edited. This isn't necessary and is a bit confusing in the code.

### Summary of Changes
This PR removes all instances where the argument isn't necessary and adjusts the checks.

There will be a small difference in behavior: Currently you can execute non-edit-related actions (eg create override or delete a folder) and after the redirect the previously opened file will still be open. After this patch it will be closed.
Keep in mind that even currently, all changes made in that file since the last save would be lost if you run such an action. So it gives a wrong impression to always reopen it.
Imho, the edit mode should disable all other tabs and non-edit buttons. To prevent the data loss. But that would be a task for another PR.

I also removed the hidden `compressed_formats` parameter and related checks. Since it was a hidden parameter with only `zip` as value, it basically was a hardcoded to 'zip'. I instead just really hardcoded it into the code.

### Testing Instructions
Play around with the template file manager and see if something is broken.
Especially also try the various file manipulations (edit, create, delete, copy, resize, crop, ...)

### Expected result
Works as before

### Actual result
No difference

### Documentation Changes Required
None

### CODE REVIEW

**Comment by brianteeman** [comment]
Can you look at resolving the conflicts so that this can be tested please.

**Comment by Bakual** [comment]
Conflicts solved

**Comment by uthorat** [comment]
I have tested this item :white_check_mark: successfully on 93fd2a15289d757e770eac186ac04d38919309c8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23655">issues.joomla.org/tracker/joomla-cms/23655</a>.</sub>

**Comment by anibalsanchez** [comment]
I have tested this item :white_check_mark: successfully on 93fd2a15289d757e770eac186ac04d38919309c8<br /><br />From #JMAD19 PBF, Test OK<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23655">issues.joomla.org/tracker/joomla-cms/23655</a>.</sub>

**Comment by alikon** [comment]
@Bakual conflict once again, please

**Comment by roland-d** [comment]
@Bakual Any interest in picking this up and fixing the conflicts?

**Comment by Bakual** [comment]
Nah, I'm closing this as I would have to do it fresh again. It's not that important :)

**Pull request closed without merging**
