### PR TITLE
Php7 tests

### PR DESCRIPTION
**Pull request by nibra**
The test suite is currently failing on PHP7. This PR fixes the issues reported by Travis.

### CODE REVIEW

**Comment by mbabker** [comment]
We have PHP 7 compat issues dealt with in the `3.5-dev` branch (where things are passing with flying colors).

**Comment by nibra** [comment]
Ok! Is theproblem with the framework's String class solved, too? That name is not allowed in PHP7. I propose to rename it to `Utf8String`.

**Comment by mbabker** [comment]
We renamed it to `StringHelper` in the Framework (see https://github.com/joomla-framework/string/commit/a1f95062659826b1ff37f4bb1c239852de505bc9) and changed the legacy `JString` to directly extend from that versus the now disallowed named class.

**Comment by nibra** [comment]
Very good. Then this PR is of no use; I'm closing it.

**Pull request closed without merging**
