### PR TITLE
[4.0] com_privacy capabilities

### PR DESCRIPTION
**Pull request by brianteeman**
This PR changes the heading from h4 to h2 as there should be no "gaps" in the headings

This PR also changes the bootstrap accordion to the browser native Details/Summary element as used elsewhere.

Styling of this is beyond the scope of this PR
Other parts of com_privacy are beyond the scope of this PR

### CODE REVIEW

**Comment by Quy** [comment]
Remove `use Joomla\CMS\HTML\HTMLHelper;`.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on eb86171ec8215d98f74e6924f687b6185a49ca76<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25740">issues.joomla.org/tracker/joomla-cms/25740</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on c06313b312ac2a8b238ecba6c8743b92819e5df8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25740">issues.joomla.org/tracker/joomla-cms/25740</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25740">issues.joomla.org/tracker/joomla-cms/25740</a>.</sub>

**Comment by C-Lodder** [comment]
Note that MS Edge does not support the Details/Summary elements (with the accordion effect). The content will always be visible.
Edge Chromium should be released in late 2019 (which will support it). Just something to think about.

**Comment by brianteeman** [comment]
polyfills are available for broken browsers https://github.com/javan/details-element-polyfill

**Comment by wilsonge** [comment]
Thanks! Created an issue for the details/summary thing so it doesn't get forgotten https://github.com/joomla/joomla-cms/issues/25749

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
