### PR TITLE
[4.3] validate="CssIdentifier"

### PR DESCRIPTION
**Pull request by brianteeman**
The majority of fields that accept a css class also have a validation rule to make sure its valid css

Some fields were missed. This PR resolves that.

To Test
Code review that the fields changed are indeed fields that should only accept css

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on f18b5f27a5cd53bb0d90951e937098bf3c3e5e0c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41349">issues.joomla.org/tracker/joomla-cms/41349</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on f18b5f27a5cd53bb0d90951e937098bf3c3e5e0c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41349">issues.joomla.org/tracker/joomla-cms/41349</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41349">issues.joomla.org/tracker/joomla-cms/41349</a>.</sub>

**Comment by Fedik** [comment]
The pr is correct, however this can break an existing user values.
Example people can use the icon field for random stuff in the layout override.
I would not do it in patch release. It is for 4.4 or 5.0

**Comment by brianteeman** [comment]
> Example people can use the icon field for random stuff in the layout override.

do we really have to care about people doing stupid things?

Anyway its upto the maintainers where it is merged

**Comment by obuisard** [comment]
Thank you Brian @brianteeman for the PR!

**Pull request merged**
