### PR TITLE
[4.4] Incorrect message for user fields

### PR DESCRIPTION
**Pull request by brianteeman**
Alternative for #41435 

### Summary of Changes
The user profile displays various fields. Some of them have a value, some of them have no value and some of them have no value but that means they use the site default value.

Originally the text was "No information entered" but this wasn't correct for the fields using a default value so I changed the text to "website default" in https://github.com/joomla/joomla-cms/pull/25699

That was **wrong** as I only considered the basic params in a user profile and not any additional fields such as from the user profile plugin or a custom field.

This created a scenario where a users name and address in their profile would be displatyed as "website default" when it should have been blank.

This PR keeps the behaviour on the basic params to display "website default" but removes any default text being used for the other fields as its not appropriate.

### Testing Instructions
1. Create a user custom field
2. Publish the user profile plugin
3. Create a menu item to display a user profile
4. Log in to the front end and go to the profile page
5. Edit the profile by setting some but not all fields

### Actual result BEFORE applying this Pull Request
image

### Expected result AFTER applying this Pull Request
image

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
rebased to 4.4

**Comment by joomleb** [comment]
@brianteeman 
I updated the [Test site](https://github.com/joomla/joomla-cms/pull/41435#issuecomment-1696016994) 
For me it is NOT running as expected.

**Frontend**

> For all fields that can be left empty = just to don't show nothing, any value, left it empty.

Are you sure the rule is applying by default also on the Users Joomla Custom Fields ? 
I created a Calendar (Birthday) Joomla Custom Field and "Website Default"is still shown.

> For all the fields that when not yet setted they redirect to a "site default value" like the "Basic Settings" fields (Time Zone, Frontend Language,...)  = just to show the default value and not the written "site default".

Right now also here it is showing nothing as above, instead to show the default value.

So, for example, from:
- Time Zone: Website default
- Frontend Language: Website default

They should be shown directly as:
- Time Zone: UTC-5
- Frontend Language: Spanish

Where "UTC-5" and "Spanish" are the default values.

Do you want Super Admin credentials of the test site ? (Where I can send it to you ?

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on 3db8c0b28eac325af8577c006fd1f6ae6cf98f59<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41513">issues.joomla.org/tracker/joomla-cms/41513</a>.</sub>

**Comment by joomleb** [comment]
Hi @ceford 
on Frontend:

**A** - Are you sure the rule to write nothing is applying by default also on the Users Joomla Custom Fields ?
I tested creating some custom fields and I always have back "Website Default" as value.

**B** - For all the fields that, when not yet setted, they redirect to a "site default value" like the "**Basic Settings**" fields (Time Zone, Frontend Language,...), they should just to show the default _value_ and not the written "site default" (or nothing)

Please, Can you reproduce them ?

**Comment by ceford** [comment]
On A: I added a Textarea field and confirm that if I do not enter any data it appears in the front end without any data. That confirms the Test Pass result.

On B: My test results show what the pull request required. If you think the Time Zone should show the actual time zone rather than Website default perhaps that is a separate issue.

**Comment by MacJoom** [comment]
Hi @joomleb - what is the status here - does this PR solve your issue? Can you give successful test? And would you close your PR #41435 in favour of this PR? Thank you

**Comment by joomleb** [comment]
Hi @MacJoom 
Okay, I'm going to close the #41435 
I'm still "stopped" to this point https://github.com/joomla/joomla-cms/pull/41435#issuecomment-1697502018 (backend/frontend).
For me, Joomla 4.4 frontend, is not running as expected:

**A** - Are you sure the rule to write nothing is applying by default also on the **Users Joomla Custom Fields** ?
I tested creating some custom fields and I always have back "Website Default" as value.

**B** - For all the fields that, when not yet setted, they redirect to a "site default value" like the "**Basic Settings**" fields (Time Zone, Frontend Language,...), they should just to show the default value and not the written "site default" (or nothing)

Please, Can you reproduce them ?

**Comment by MacJoom** [comment]
@brianteeman - can you comment on joomlebs issues? Thank you.

**Comment by Quy** [comment]
Before PR:
41513-before

After PR:
41513-after

@MacJoom Regarding joomlebs: Issue A is solved with this PR. Issue B is a separate issue.

**Comment by joomleb** [comment]
Hi @Quy 

**A** -  As far as I understand, what is shown in your image is your image is the (old) **User Profile Joomla plugin**.
What I asked is: Are you sure that the rule "to write nothing" is applying by default also on the **Users Joomla Custom Fields** ?
I tested creating some new custom fields and I always have back "Website Default" as value...
Please, Have you tested it by creating a new _Custom Field_ ?

**B** - @MacJoom - Please, Are you going to split it?  Or, What should I do ?

**Comment by Quy** [comment]
No issues with custom fields. I did a calendar field as you mentioned in your previous comment.

41513-custom-fields

**Comment by joomleb** [comment]
@Quy 

A - I re-tested it right now with success, thank you

B - I remain available...

**Review by joomleb — APPROVED** [review]
Point A tested with success

**Comment by brianteeman** [comment]
@quy what are the updates that are requested

**Comment by Quy** [comment]
https://github.com/joomla/joomla-cms/pull/41513#issuecomment-1816968839

Before PR, the `About Me` value is escaped.

**Comment by joomleb** [comment]
@Quy 
Thank you 
Done #42377

**Comment by brianteeman** [comment]
@quy sorry I didnt see anything in the comment you linked to that said the change was wrong. I have now reverted that line

**Comment by Quy** [comment]
Now no values are displayed except Website field.

41513-no-values

**Comment by brianteeman** [comment]
isnt that the entire point?

**Comment by joomleb** [comment]
Hi guys,
@brianteeman What do you mean with "closing this for now" ?
I'm asking to know what to do with its alter ego ticket #42377 I opened in November...

**Pull request closed without merging**
