### PR TITLE
Adds \ to all defines

### PR DESCRIPTION
**Pull request by N6REJ**
Pull Request for Issue # .

### Summary of Changes

using \define speeds things up.
several places were missing the \ This corrects that.

### Testing Instructions
make sure J! still runs.
code review?

### CODE REVIEW

**Comment by brianteeman** [comment]
a PR that touches over 2700 files is impossible to test

**Comment by brianteeman** [comment]
Why are you deleting `.github/SECURITY.md`

**Comment by N6REJ** [comment]
> Why are you deleting `.github/SECURITY.md`

I'm not... it was deleted in #30778 
image

**Comment by brianteeman** [comment]
No it wasn't and yes you are. 

image

image

**Comment by brianteeman** [comment]
You are also deleting 

image

**Comment by brianteeman** [comment]
And adding an unrelated svg

image

**Comment by brianteeman** [comment]
Every file in the fof folder that you have changed need to have their copyright updated if it does not already do so

` * @note        This file has been modified by the Joomla! Project and no longer reflects the original work of its author.`

**Comment by N6REJ** [comment]
@brianteeman might wanna check staging before you blame me for everything.. I didn't add anything

**Comment by N6REJ** [comment]
after reviewing several files I"m closing this as it's changing things that I didn't change.

**Comment by brianteeman** [comment]
git doesnt lie

**Comment by N6REJ** [comment]
your full of crap @brianteeman #30778 is the cause of all that.. check the damn logs!!
image

**Comment by N6REJ** [comment]
you owe me an apology 
image

**Pull request closed without merging**
