### PR TITLE
Update mod_breadcrumbs

### PR DESCRIPTION
**Pull request by cr2a-graphique**
Add default symbol to breadcrumb separator

### CODE REVIEW

**Comment by brianteeman** [comment]
Is this really needed? We already have the following code https://github.com/joomla/joomla-cms/blob/staging/modules/mod_breadcrumbs/helper.php#L80

In addition by changing the default value we are potentially breaking the styling of every template out there which is assuming the default behaviour as stated in the code above.

What is the reasoning for this change<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9066">issues.joomla.org/joomla-cms/9066</a>.</sub>

**Comment by cr2a-graphique** [comment]
improve the display by default.
Links are very close if no separation symbol set

**Comment by brianteeman** [comment]
Surely thats a css issue in whichever template is being used

On 4 February 2016 at 11:06, mikaelR <notifications@github.com> wrote:

> improve the display by default.
> Links are very close if no separation symbol set
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/9066#issuecomment-179773229>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
Closed as stated above<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9066">issues.joomla.org/joomla-cms/9066</a>.</sub>

**Pull request closed without merging**
