### PR TITLE
[com_contact] Improve search tooltip

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Summary of Changes

Simple PR to improve the search tooltip and element label (accessibility) in com_contact.
#### Testing Instructions

Code review, or:
1. Apply patch
2. Go to Components -> Contacts -> Contacts , check the tooltip in the search field.

### CODE REVIEW

**Comment by RonakParmar** [comment]
I have tested this item :white_check_mark: successfully on 12ae12aedec37234fd6b8ab8d6ddaad17e4dd8d3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10176">issues.joomla.org/joomla-cms/10176</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 12ae12aedec37234fd6b8ab8d6ddaad17e4dd8d3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10176">issues.joomla.org/joomla-cms/10176</a>.</sub>

**Comment by andrepereiradasilva** [comment]
RTC?

**Comment by brianteeman** [comment]
It is now ;)

**Pull request merged**
