### PR TITLE
Composer update joomla/utilities

### PR DESCRIPTION
**Pull request by richard67**
Pull Request for Issue #34365 and https://github.com/joomla/joomla-cms/pull/34380#issuecomment-855236815.

### Summary of Changes

Update composer dependency "joomla/utilities" to version "1.6.2" which contains the fix for issue 34365 .

### Testing Instructions

Code review and check that composer works in Appveyor and Drone.

Or if you can reproduce issue #34365 , verify that this PR fixes it according to the description there.

### Actual result BEFORE applying this Pull Request

Version "1.6.1" of the composer dependency "joomla/utilities" is used.

### Expected result AFTER applying this Pull Request

Version "1.6.2" of the composer dependency "joomla/utilities" is used.

### Documentation Changes Required

None.

### CODE REVIEW

**Review by wilsonge — APPROVED** [review]

**Comment by nikosdion** [comment]
Thank you! 🙏🏽

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 00aa5934e6e4a37cda3ee9c09d745072aa81e4ce<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34421">issues.joomla.org/tracker/joomla-cms/34421</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 00aa5934e6e4a37cda3ee9c09d745072aa81e4ce<br /><br />Everything works as expected after this PR and resolves #34365 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34421">issues.joomla.org/tracker/joomla-cms/34421</a>.</sub>

**Comment by jwaisner** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34421">issues.joomla.org/tracker/joomla-cms/34421</a>.</sub>

**Pull request merged**
