### PR TITLE
Fixing contact fields

### PR DESCRIPTION
**Pull request by Bakual**
Pull Request for Issue #14004 .

### Summary of Changes
This PR adds the object to the FieldsHelper::extract method as an optional argument. This way extensions can determine in their helper if the context is the proper one for the current object.
It adds a check to the com_contact helper so it can give the correct context (mail or contact) back based on the passed object (item or form).

### Testing Instructions
* Assign some custom fields to a contact as well as its mail form and add some values.
* Check the contact in frontend, the fields should show up as expected and form needs to additional fields.

### Expected result
Fields show up as expected both in contact and form.

### Actual result
Only the added fields for the contact form show up.

### Documentation Changes Required
None

### Comment
We need this because in com_contact (and maybe 3rd party extensions) the context doesn't differentiate between the contact itself and the contact form. It's always "com_contact.contact". So we need a way to differentiate that, which we can do by looking at the object.
With 4.0, we can change the context for the contact form to "com_contact.mail". The question is if we then should remove the optional argument again (and deprecate it right away now) or if we want to leave it for 4.x. Imho, it wouldn't really hurt to pass it and it *may* be helpful for 3rd parties.

### CODE REVIEW

**Comment by AlexRed** [comment]
I have tested this item :white_check_mark: successfully on c024c88e3bdaa61a71d3b495114a0ffe68081190<br /><br />Patch ok for me<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14015">issues.joomla.org/tracker/joomla-cms/14015</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on c024c88e3bdaa61a71d3b495114a0ffe68081190<br /><br />Form-Fields not shown in Backend.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14015">issues.joomla.org/tracker/joomla-cms/14015</a>.</sub>

**Comment by laoneo** [comment]
I would mark it as deprecated. For me it is cleaner as it is actually. But due the contextes are right now we need this one in the three series.

**Comment by laoneo** [comment]
I have tested this item :white_check_mark: successfully on c024c88e3bdaa61a71d3b495114a0ffe68081190<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14015">issues.joomla.org/tracker/joomla-cms/14015</a>.</sub>

**Comment by Bakual** [comment]
> I would mark it as deprecated. For me it is cleaner as it is actually. But due the contextes are right now we need this one in the three series.

The thing here is the same as with other stuff for 4.0. I don't feel very comfortable introducing something just to deprecate it right away.
I agree it is cleaner, but imho there is no drawback in passing the object as well and it could be a huge help for some 3rd parties.

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14015">issues.joomla.org/tracker/joomla-cms/14015</a>.</sub>

**Pull request merged**
