### PR TITLE
Comment typos

### PR DESCRIPTION
**Pull request by brianteeman**
Assorted comment typos - can be merged on review

### CODE REVIEW

**Comment by cokencorn** [comment]
I have tested this item :white_check_mark: successfully on 612551d1d88e4b5ec1c7c4d0cb477f8692adede4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14968">issues.joomla.org/tracker/joomla-cms/14968</a>.</sub>

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on 612551d1d88e4b5ec1c7c4d0cb477f8692adede4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14968">issues.joomla.org/tracker/joomla-cms/14968</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14968">issues.joomla.org/tracker/joomla-cms/14968</a>.</sub>

**Comment by zero-24** [comment]
Thanks @brianteeman !

**Pull request merged**
