### PR TITLE
Solution for tagging in different languages

### PR DESCRIPTION
**Pull request by A-Kasaaian**
Pull Request for Issue # .
### Summary of Changes

A solution for: https://github.com/joomla/joomla-cms/issues/10761
The issue was created by "event.which === 188"  which means ',' on keyup event but I changed it to 2 different events. Keyup to check if enter is pressed and keypress to check if ',' is pressed while typing in English. An event listener is changed to two event listener and a function.
### Testing Instructions

I tested code with multiple languages such as Hebrew, Persian, Arabic and ... to see if there is a key charCode equal to 44 among their numbers and alphabet which would cause issues and other key code tests and typing test in Joomla tag field to make sure there is no conflict. I found out that 44 is probably an unique charCode. The code passed all tests successfully
### Documentation Changes Required

There is an issue in typing tags in different languages. Pressing ',' in tags means you are done and it will be saved, but it's only for English not other languages such as Arabic, Persian, Hebrew and ... which was bothering me and many other Joomla users. So that I made changes to solve this problem. Now, you can press ',' but it submits tag just if you are typing in English language and if you are typing in other languages continue as long as you want and press enter at the end. Tested in many languages and everything works fine.

### CODE REVIEW

**Comment by csthomas** [comment]
Hi, IMO comma should not be added to tag when there is only a few letters (less that 3).

Can you test and add this changes:

```diff
diff --git a/layouts/joomla/html/tag.php b/layouts/joomla/html/tag.php
index abc6a6fdcd..2e8e055b40 100644
--- a/layouts/joomla/html/tag.php
+++ b/layouts/joomla/html/tag.php
@@ -43,9 +43,9 @@ if ($allowCustom)
        JFactory::getDocument()->addScriptDeclaration(
                "
                jQuery(document).ready(function ($) {
-      var customTagPrefix = '#new#';
+                       var customTagPrefix = '#new#';
 
-                       function tagHandler(event,element){
+                       function tagHandler(event,element) {
                                        // Search an highlighted result
 
                                        var highlighted = $('" . $selector . "_chzn').find('li.active-result.highlighted').first();
@@ -85,23 +85,27 @@ if ($allowCustom)
 
                                        element.value = '';
                                        $('" . $selector . "').trigger('liszt:updated');
-                                       event.preventDefault();
-
                        }
 
                        // Method to add tags pressing enter
                        $('" . $selector . "_chzn input').keypress(function(event) {
-                               // Tag is greater than the minimum required chars and enter pressed
-                               if (this.value && this.value.length >= " . $minTermLength . " && (event.which === 13 || event.charCode === 44)) {
+                               // Comma pressed
+                               if (event.charCode === 44) {
+                                       // Tag is greater than the minimum required chars
+                                       if (this.value && this.value.length >= " . $minTermLength . ") {
+                                               tagHandler(event,this);
+                                       }
 
-                                       tagHandler(event,this);
+                                       // Do not add comma to tag
+                                       event.preventDefault();
                                }
                        });
+
                        $('" . $selector . "_chzn input').keyup(function(event) {
                                // Tag is greater than the minimum required chars and enter pressed
-                               if (this.value && this.value.length >= " . $minTermLength . " && (event.which === 13)) {
-
+                               if (event.which === 13 && this.value && this.value.length >= " . $minTermLength . ") {
                                        tagHandler(event,this);
+                                       event.preventDefault();
                                }
                        });
                });
```

**Comment by A-Kasaaian** [comment]
@csthomas everything must be OK by now

**Comment by csthomas** [comment]
From code review: I suggest to not deleting blank lines in more cases, before comments and after closing parentheses such as `}` or `);`.

**Comment by A-Kasaaian** [comment]
I didn't. It had been done previously. This time I just copied[ this version](https://github.com/joomla/joomla-cms/blob/staging/layouts/joomla/html/tag.php) and changed two parts, which is described in the last commit [here](https://github.com/joomla/joomla-cms/issues/10761).

**Comment by csthomas** [comment]
Take a look at the red lines at https://github.com/joomla/joomla-cms/pull/12366/files

**Comment by A-Kasaaian** [comment]
OK that was a mistake because I didn't copy and past properly. It's resolved now,

**Comment by csthomas** [comment]
I tested you PR unsuccessful because the enter button has stopped working.

 I have created different PR #18768 that should solve your problem.

**Comment by ghost** [comment]
closed in Favor of #18768.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12366">issues.joomla.org/tracker/joomla-cms/12366</a>.</sub>

**Pull request closed without merging**
