### PR TITLE
fix Filter per language missing brackets

### PR DESCRIPTION
**Pull request by nielsnuebel**
the where clause must be in brackets, because without brackets the query returns articles that match with language = \* without checking the created_by = user_id

### CODE REVIEW

**Comment by Bakual** [comment]
Agreed with the fix, but there is a codestyle issue. You need to add a space before the closing bracket:
Change `$db->quote('*') .')'` to `$db->quote('*') . ')'`

**Comment by phproberto** [comment]
Also please add the information to reproduce the issue and test the patch.

**Comment by joomdonation** [comment]
Seems there are still something wrong with the PR (based on code review):

1. I think we don't need to have $query->where('a.created_by = ' . (int) $result->user_id) because It is added before already https://github.com/joomla/joomla-cms/blob/staging/components/com_contact/models/contact.php#L381 and I don't see any reasons that only be added if the site is multilingual.

2. Seems we are using IN clause for language query in other places in core, not using OR. A quick google search also show that IN has better performance in OR. So maybe we should change OR to IN

So the code in the PR could be changed to:

````php
if (JLanguageMultilang::isEnabled())
{
	$query->->where('a.language IN (' . $db->quote(JFactory::getLanguage()->getTag()) . ',' . $db->quote('*') . ')');
}
````

**Comment by joomdonation** [comment]
Made a PR at https://github.com/nn-medienagentur/joomla-cms/pull/1 . In case we agree with this change @nn-medienagentur can merge the PR to save time.

**Comment by zero-24** [comment]
Moving to `Information required` until @nn-medienagentur have a look into here. Thanks :smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6784">issues.joomla.org/joomla-cms/6784</a>.</sub>

**Comment by nn-medienagentur** [comment]
@joomdonation you're right.

**Comment by brianteeman** [comment]
Removed Information Required tag<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6784">issues.joomla.org/joomla-cms/6784</a>.</sub>

**Comment by designbengel** [comment]
So.... How to test it :-)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6784">issues.joomla.org/joomla-cms/6784</a>.</sub>

**Comment by infograf768** [comment]
@test
This works fine here.

To test:
Display a contact for USER1 in frontend. "Show User Articles" should be set to "Show" in the menu item. (Don't forget that, in  multilanguage, a user/author should have only one contact to which is assigned language 'All' OR one contact for each published Content Language.)
Create an article set to All Languages and assign it to another user (USER2) than the one displayed by the menu item.

That article will be displayed by the menu item in the list of Articles for USER1.
Patch and test again: it will not any more as it does not belong to that user.

**Comment by designbengel** [comment]
@infograf768 i tested like you described the issue but can´t reproduce it.
Steps:
- Created two Users (User 1, User 2) Both have language set to "All"
- Created an Article with Language Set to "all" for User 2
- Created two Articles for User 1 (en-GB, de-DE)
- Created a Menüitem for Displaying Contact for User 1 (Show Articles is marked)
-> The Show Articles Slide only shows the articles of user 1
After deleting the two Articles from User 1 the slide is not visible anymore.

~ Any other instructions, did i miss something ?
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6784">issues.joomla.org/joomla-cms/6784</a>.</sub>

**Comment by mikeveeckmans** [comment]
Cannot reproduce this error.
Not a multilingual site, nor on a single language site.

used version J!3.5.1 
followed the test instructions from @infograf768 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6784">issues.joomla.org/joomla-cms/6784</a>.</sub>

**Comment by brianteeman** [comment]
Several people have stated that they cannot reproduce the issue. This could be because it no longer exists and has been solved elsewhere or it is down to the test intructions not being detailed enough.

Please can you check if this is still an issue and update with detailed test instructions or this will be closed in a few weeks.

Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6784">issues.joomla.org/joomla-cms/6784</a>.</sub>

**Comment by nn-medienagentur** [comment]
Here is the description to reproduce the issue.


1. create a User1 
2. create a User2
3. create a article like "User1 Language ALL" and select created_by the User1 Language ALL
4. create a article like "User2 Language UK" and select created_by the User2 Language en-GB
5. create a Contact "User2" and liked the Contact with User2 Language ALL
6. Add a new MenuItem from type Contacts - > Single contact add select the User2 and change in "Contact Display Options" -> Show User Article to "show" language for the Menu can be ALL
7.  IMPORTANT now you have do enable the Plugin "System - Language Filter"

Now you see on the Frontend in the Single Contact View the Article from User 1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6784">issues.joomla.org/joomla-cms/6784</a>.</sub>

**Comment by mikeveeckmans** [comment]
I have tested this item :white_check_mark: successfully on 47cc3011f38a98615b5ad71b56cfee43827a5dca<br /><br />Tested again with new instructions.
Now i could reproduce the error and test patch.
TEST OK<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6784">issues.joomla.org/joomla-cms/6784</a>.</sub>

**Comment by brianteeman** [comment]
Rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6784">issues.joomla.org/joomla-cms/6784</a>.</sub>

**Comment by mikeveeckmans** [comment]
@nn-medienagentur what are the changes? <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6784">issues.joomla.org/joomla-cms/6784</a>.</sub>

**Comment by nn-medienagentur** [comment]
@mikeveeckmans  nothing, why are you asking?

**Comment by rdeutz** [comment]
Just one comment before I merge this, I check what is faster "or" vs. "in" and it seems that "in" is faster.

**Pull request merged**
