### PR TITLE
[4.2] select category string

### PR DESCRIPTION
**Pull request by brianteeman**
corrects the capitalisation

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on f54576aa771a229b6002123cf1d54a4d4c3bda4f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39930">issues.joomla.org/tracker/joomla-cms/39930</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on f54576aa771a229b6002123cf1d54a4d4c3bda4f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39930">issues.joomla.org/tracker/joomla-cms/39930</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39930">issues.joomla.org/tracker/joomla-cms/39930</a>.</sub>

**Comment by roland-d** [comment]
Thank you

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
