### PR TITLE
Fix pagination in user components and com_users (with enabled filters)

### PR DESCRIPTION
**Pull request by Disaron**
Sometimes pagination in JModelList don`t work. Usually it happens when you are on first page and has no active filters (if it present) in frontend. Reason that list.start state is cleared in populateState method.

Second commit fix pagination in users list com_users when you activate some filters.

### CODE REVIEW

**Comment by infograf768** [comment]
Please first test https://github.com/joomla/joomla-cms/pull/8467

**Comment by Disaron** [comment]
infograf768, tested. No this is not helps in frontend (solved by [3aee886](https://github.com/Disaron/joomla-cms/commit/3aee886ac45570f3dc6589f2020b7dcee0b27357)).

**Comment by Bakual** [comment]
Can you provide exact steps to reproduce the issue you see?

The first commit almost certainly is wrong. The value for `start` should be cleaned for sure, removing that is no option as it would be a security issue allowing uncleaned input into the states.

The second commit looks wrong as well. The PR #8467 should indeed have fixed that.

**Comment by Disaron** [comment]
First commit break my mind at two weeks after migration to 3.4.5.
Create custom model list with filtering in frontend, fill some items to see pagination.
Select 1st page.
Drop session (logout on anything else, I have SSO).
Try to go to 2nd page.
1st page still selected.

Well I see another solution (no time to create pull request now):
```
case 'start':
    $value = $inputFilter->clean($value, 'int');
    break;
```
For second commit I think that [this](https://github.com/Bakual/joomla-cms/commit/c44e0f55f6060749cac80e21c2482fe246fcd1a9) commit says you why it possible ;)

**Comment by mbabker** [comment]
com_content had overridden the parent populateState method long before 3.4.5's release, the two topics are unrelated.

The line you've removed in JModelList actually is 100% irrelevant to processing.  Even if you inject a value for the list.start model state via the request, it is overwritten by the limitstart query variable and its default value if it isn't sent.  Even so, if it were the actual value used then list.start must be an integer given its use cases and that is exactly what is happening there.

**Comment by Disaron** [comment]
Sorry but happening what?
Current code in staging:
````
case 'limit':
case 'start':
 	$limit = $inputFilter->clean($value, 'int');
 	break;
````

`$limit =` - seriously? Maybe must be `$value =` ;)

**Comment by Disaron** [comment]
`com_content had overridden the parent populateState method long before 3.4.5's release, the two topics are unrelated.`
Then you must know, that in current release pagination in com_content goes to first page when you reopen list? Because list.start not save in states (maybe it`s feature, I don`t know...)

**Comment by Bakual** [comment]
True, that part with the start and limit indeed looks wrong. Can you do a PR to fix that alone, without anything else and without removing filtering for the start.

**Comment by Bakual** [comment]
> Then you must know, that in current release pagination in com_content goes to first page when you reopen list? Because list.start not save in states (maybe it's feature, I don't know...)

That is indeed by design. The pagination isn't saved in the userstates in frontend views.

**Comment by Disaron** [comment]
Done: [#8481](https://github.com/joomla/joomla-cms/pull/8481)

**Comment by Bakual** [comment]
Closing this one as we have a PR that deals only with the issue at hand

**Pull request closed without merging**
