### PR TITLE
[a11y] dropdown

### PR DESCRIPTION
**Pull request by brianteeman**
Continuing the work to prevent assistive technology reading out the value of an icon. This PR addresses the icons in com_contact, com_messages, com_contact an com_redirect as show in the screenshots below.

screenshotr19-51-04
screenshotr20-01-38
screenshotr20-06-56
screenshotr20-16-42

### CODE REVIEW

**Comment by brianteeman** [comment]
If anyone is able to help updating the unit tests I would appreciate it @yvesh @zero-24

**Comment by zero-24** [comment]
I have just send you a PR for the drone error. The phpunit thing looks strange to me on a first quick look. I need to check that with @yvesh

**Comment by zero-24** [comment]
Travis is green now too. Thanks @yvesh and @brianteeman

**Comment by brianteeman** [comment]
Thanks for the help there @zero-24 @yvesh

**Comment by brianteeman** [comment]
any testers?

**Comment by franz-wohlkoenig** [comment]
@brianteeman is this code review or how to test?

**Comment by tonypartridge** [comment]
I have tested this item :white_check_mark: successfully on 58ee5005033f7f6c547014f307fca0740c5296de<br /><br />Code Review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15046">issues.joomla.org/tracker/joomla-cms/15046</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 58ee5005033f7f6c547014f307fca0740c5296de<br /><br />Code review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15046">issues.joomla.org/tracker/joomla-cms/15046</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
