### PR TITLE
[4.0] Logo alignment [a11y]

### PR DESCRIPTION
**Pull request by brianteeman**
Pull request for #27858 

This is not perfect as it still changes size slightly but its better than before where it moved from right to left. The change was to add `preserveAspectRatio="xMinYMin meet"` into the svg see http://tutorials.jenkov.com/svg/svg-viewport-view-box.html

### before
logo

### after
after

### CODE REVIEW

**Comment by C-Lodder** [comment]
SVG should be minified. You can use this: https://jakearchibald.github.io/svgomg/

**Comment by brianteeman** [comment]
Happy for someone else to do that. It was the minification that broke the svg in the first place

**Comment by C-Lodder** [comment]
Does adding `preserveAspectRatio="xMinYMin meet"` to the original minified file work?

**Comment by brianteeman** [comment]
Good idea @C-Lodder done that

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on a2c562e8de8fdcf5cf75d2abc5c0ff12da335d5f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27880">issues.joomla.org/tracker/joomla-cms/27880</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on a2c562e8de8fdcf5cf75d2abc5c0ff12da335d5f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27880">issues.joomla.org/tracker/joomla-cms/27880</a>.</sub>

**Comment by jwaisner** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27880">issues.joomla.org/tracker/joomla-cms/27880</a>.</sub>

**Comment by brianteeman** [comment]
thank you - not perfect but better than it was

**Pull request merged**
