### PR TITLE
[4.0] Site/Admin select in searchtools

### PR DESCRIPTION
**Pull request by brianteeman**
see screenshots for changes

If we wait for an expert to fix it then it will never happen

On pages where we still have an admin/site select such as `/administrator/index.php?option=com_languages&view=installed&client=1` there is an error in the RTL css that forces it to be full width

### Before
image

### After
image

### CODE REVIEW

**Comment by infograf768** [comment]
That is not enough.
As I said in the other pr for searchtools, we have an issue when reducing the window as we should get float none but the template rtl css does not load after the system css in that case.

**Comment by brianteeman** [comment]
The order that the css is loaded is a different issue. 
float: none is completely wrong for a desktop site and that is what this fixes.

(we really should not have a template-rtl.css)

**Comment by infograf768** [comment]
It HAS to switch to none when the window is reduced. This pr alone breaks the whole display on mobile. One can’t solve an issue while creating another.
Both situations have to be solved together...

**Comment by brianteeman** [comment]
well before this PR the desktop was broken. I will work on fixing the mobile now

**Comment by brianteeman** [comment]
until someone works out the css ordering this PR now works correctly on mobile as well

**Comment by infograf768** [comment]
See discussion in https://github.com/joomla/joomla-cms/pull/27384
After this is solved, we may have to totally refactor the css for searchtools.
I also informed maintainers about the issue.

Note: yes, the change to mobile with `!important` works in a similar way as ltr now.

**Comment by infograf768** [comment]
Closing as the changes here are included in https://github.com/joomla/joomla-cms/pull/27416

**Pull request closed without merging**
