### PR TITLE
[4.0][api][com:users] add more fields to the users entrypoint

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #30220 .

### Summary of Changes
added more fields to the users enrtypoint

### Testing Instructions
single user
{{base_path}}/api/index.php/v1/users/{userid}
list of users
{{base_path}}/api/index.php/v1/users/

### Actual result BEFORE applying this Pull Request
more fields not rendered

### Expected result AFTER applying this Pull Request
more fields rendered
Screenshot from 2020-07-30 21-05-38

### Documentation Changes Required

probably

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on fe96b673a4d2058b5d37f3e8cfa32b058ccd5aa7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30239">issues.joomla.org/tracker/joomla-cms/30239</a>.</sub>

**Comment by bonzani** [comment]
I have tested this item :white_check_mark: successfully on fe96b673a4d2058b5d37f3e8cfa32b058ccd5aa7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30239">issues.joomla.org/tracker/joomla-cms/30239</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30239">issues.joomla.org/tracker/joomla-cms/30239</a>.</sub>

**Comment by chetanmadaan** [comment]
I have tested this item :white_check_mark: successfully on fe96b673a4d2058b5d37f3e8cfa32b058ccd5aa7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30239">issues.joomla.org/tracker/joomla-cms/30239</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
