### PR TITLE
[4.0] Remove icon/class in modal footer

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
This PR removes icon/class in modal footer to be consistent with other modals.

This PR does not fix the hover color/order in #29560.

### Testing Instructions
Go to Home Dashboard.
Scroll to the bottom.
Click `Add module to the dashboard`.

### Actual result BEFORE applying this Pull Request
Icon in button.

### Expected result AFTER applying this Pull Request
No icon in button.

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 9bc2609b6cc2ff6a6bb848626a460e922d83210d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32293">issues.joomla.org/tracker/joomla-cms/32293</a>.</sub>

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on 9bc2609b6cc2ff6a6bb848626a460e922d83210d<br /><br />Tested successfully in Beta8-dev of 4 February using PHP 8.0.1.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32293">issues.joomla.org/tracker/joomla-cms/32293</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32293">issues.joomla.org/tracker/joomla-cms/32293</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
