### PR TITLE
Cypress test to display tags in frontsite

### PR DESCRIPTION
**Pull request by rajputanuj31**
add a test to display tags in com_tag.

### CODE REVIEW

**Comment by laoneo** [comment]
Can you fix the code style error?

**Comment by rajputanuj31** [comment]
> Can you fix the code style error?

fixed.

**Comment by laoneo** [comment]
Thanks. Looks like we have now the default value issues for tags as the tests are failing.

**Comment by laoneo** [comment]
Thanks!

**Comment by rajputanuj31** [comment]
Thanks for merging it.

**Pull request merged**
