### PR TITLE
[4.0] Dropped btn-xs in atum

### PR DESCRIPTION
**Pull request by Harshil99**
Pull Request for Issue #21244.

### Testing Instructions
Compile by npm ci.

### Expected result
xs buttons not working as removed in Bootstrap 4.

### Actual result
xs buttons are displayed

### Documentation Changes Required
None.

### CODE REVIEW

**Comment by brianteeman** [comment]
Much better to stop using the classes in the markup than to add them

**Comment by Harshil99** [comment]
@brianteeman Is it already stopped using or needed to change these classes ? I will try doing that.

**Comment by brianteeman** [comment]
Sorry I know you are trying to help but it doesnt take a second to do a search

**Comment by C-Lodder** [comment]
Please add to the correct scss file. The one you've used is for imports

**Comment by Harshil99** [comment]
@C-Lodder I think of including these changes in _buttons.scss but it reflects in template.css but here changes are needed in bootstrap.css. If there is other way or so then please let me know, I will change it asap.

**Comment by C-Lodder** [comment]
https://github.com/joomla/joomla-cms/blob/127fc00fb835b1160c25a35e12448e372209315b/administrator/templates/atum/scss/vendor/bootstrap/_buttons.scss

**Comment by infograf768** [comment]
Would'nt it be OK in
`/administrator/templates/atum/scss/vendor/bootstrap/_buttons.scss` ?

**Comment by infograf768** [comment]
lol

**Comment by Harshil99** [comment]
@infograf768 Moved changes to _buttons.scss.

**Comment by infograf768** [comment]
Please look at
https://github.com/joomla/joomla-cms/issues/21244

A decision should be taken.

**Comment by wilsonge** [comment]
Remove the class usage

**Comment by Quy** [comment]
Closing for now until a fix as suggested per wilsonge<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24457">issues.joomla.org/tracker/joomla-cms/24457</a>.</sub>

**Pull request closed without merging**
