### PR TITLE
[4.0] Update editor versions in manifest files

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

This was missed in https://github.com/joomla/joomla-cms/pull/30334.

### Testing Instructions

Code review.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 9abaf78aa8dccb756e62f91dbaca22581ffdd7c9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30340">issues.joomla.org/tracker/joomla-cms/30340</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 9abaf78aa8dccb756e62f91dbaca22581ffdd7c9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30340">issues.joomla.org/tracker/joomla-cms/30340</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30340">issues.joomla.org/tracker/joomla-cms/30340</a>.</sub>

**Comment by dgrammatiko** [comment]
FWIW the build tools should do this automatically, eg someone has to do the changes in the package.json (eg `npm audit --fix`) and then run `npm install` again. The whole idea was that the 3rd party dependencies should be a fairly easy maintenance task

**Comment by wilsonge** [comment]
Yeah dunno whether the files weren't added or something else. the build tools do still work doing that though

**Pull request merged**
