### PR TITLE
[4.0] behaviour plugin

### PR DESCRIPTION
**Pull request by brianteeman**
change the description of the behaviour plugins to remove the word "content" to avoid confusion with the word "articles"

Partial Pull Request for Issue #33418

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on f58921c9eec8bfbf809d2795bba2542ed4d968c7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33420">issues.joomla.org/tracker/joomla-cms/33420</a>.</sub>

**Comment by himanshu007-creator** [comment]
I have tested this item :white_check_mark: successfully on f58921c9eec8bfbf809d2795bba2542ed4d968c7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33420">issues.joomla.org/tracker/joomla-cms/33420</a>.</sub>

**Comment by saumyasarkar11** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33420">issues.joomla.org/tracker/joomla-cms/33420</a>.</sub>

**Comment by brianteeman** [comment]
@saumyasarkar11 thanks but you dont have the access rights to set something as ready to commit

**Comment by richard67** [comment]
Yes, and we who have the rights don't need someone to tell us what to do.

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33420">issues.joomla.org/tracker/joomla-cms/33420</a>.</sub>

**Comment by drmenzelit** [comment]
Thanks

**Comment by saumyasarkar11** [comment]
> @saumyasarkar11 thanks but you dont have the access rights to set something as ready to commit

Very sorry, my bad. I didn't know about this

**Comment by saumyasarkar11** [comment]
> Yes, and we who have the rights don't need someone to tell us what to do.

Sorry again, I didn't intend to do that

**Comment by richard67** [comment]
@saumyasarkar11 No problem. I remember when I started here on GitHub for the project, I tried the same, to see if it works 😉

**Comment by brianteeman** [comment]
Thanks everyone

**Pull request merged**
