### PR TITLE
Add bootstrap tooltip extended: 4 extra positions and RTL support

### PR DESCRIPTION
**Pull request by cyrez**
This PR introduces bootstrap-tooltip-extended.js to add 4 positions and RTL support for BS tooltips.

It follows discussion about tooltip placement issue when inside modals: https://github.com/joomla/joomla-cms/pull/10100#issuecomment-215035558
#### Summary of Changes
- New <code>JHtml::_('bootstrap.tooltipExtended');</code> method  to load bootstrap-tooltip-extended.js to get 4 extra positions : <code>top-left</code>, <code>top-right</code>, <code>bottom-left</code> and <code>bottom-right</code> (https://github.com/cyrilreze/bootstrap-tooltip-extended)
- ~~Add tooltip-extended arrow css styles in <code>bootstrap-extended.less</code>~~
- Define a default <code>data-placement="auto-dir top-left"</code> (if data-placement is undefined) for class <code>.modalTooltip</code> (handler class for BS tooltip when inside a modal-body).
- In the same time, remove previously changes for Batch modals, when adding tooltip container in PR #9944 and #9379 (this is not needed anymore since the container is now set directly in modal layout main, PR #10100)
#### Testing Instructions
- Apply Patch and empty cache
- Open any modals not using iframe: Batch, Copy Template...
- Check if tooltip placement is top-left (as shown in screenshot below)
- Change language to a RTL language (eg. Arabic)
- Then open again the same modals as in LTR language : the position of tooltip is reversed (top-left becomes top-right)
#### Screenshots

(eg. batch modules)

BEFORE PATCH
capture d ecran 2016-05-05 a 15 50 02

AFTER PATCH
**Left-to-right (LTR) language direction :** 
capture d ecran 2016-05-04 a 17 01 16

**Right-to-left (RTL) language direction :** 
capture d ecran 2016-05-04 a 17 26 29

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
Did you change bootstrap js and bootstrap extended css? 
Are they not vendor libraries that should not be changed?

I think you should had as new files.

**Comment by mbabker** [comment]
bootstrap-extended IIRC is a Joomla thing, not native Bootstrap.

And the bootstrap.js is already core hacked to bits to deal with event names, MooTools incompatibilities, and "auto-hover" on the dropdown menus (compare joomla.org and api.joomla.org mega menus and how you have to click to move between them; the former is using Joomla Bootstrap and the later the native Bootstrap).  So, we're already long past pure vendor files (at least here).

**Comment by andrepereiradasilva** [comment]
ok, didn't know the history. 
I tought any vendor code should not be hacked.

**Comment by mbabker** [comment]
The keyword there is "should" 😉 

It really should be "must", but considering Joomla has a history of hacking third party code, good luck changing that.

**Comment by brianteeman** [comment]
When bs abandoned v2 and we were stuck with it we had no option<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10237">issues.joomla.org/joomla-cms/10237</a>.</sub>

**Comment by andrepereiradasilva** [comment]
i see, vendor code MUST not ever be changed ... for 4.0 then

**Comment by mbabker** [comment]
Most of those hacks came when we first implemented Bootstrap 2.1 because they weren't going to make changes to deal with the MooTools conflicts and someone decided they wanted fluid dropdowns on the top nav bar in Isis (which I agree is a nice little UX thing but it came at the expense of hacking Bootstrap).

**Comment by andrepereiradasilva** [comment]
ok, so, for what is to this PR, this change in vendor lib is ok, because the vendor lib is already changed.
fine, to me.

**Comment by JoomliC** [comment]
Note: i can add this as a separated plugin too. ;-)

The first reason is to have a better placement of the tooltip when inside a modal. BS 3 has an auto placement based on an additional viewport option.
This extension plugin here works both on version 2 and 3 of Bootstrap.

We can too implement tooltip from BS3 (backward compatible) and then just set the viewport when tooltip inside a modal, to the modal ID ;-)

**Comment by JoomliC** [comment]
> Did you change bootstrap js and bootstrap extended css?
Are they not vendor libraries that should not be changed?

@andrepereiradasilva note about bootstrap, i have hacked nor change nothing in Bootstrap, just added a plugin in bootstrap.js, which extends tooltip plugin.
bootstrap.js is a one readable compiled file of all bootstrap plugins as you can customize it yourself on getbootstrap: http://getbootstrap.com/customize/#plugins
bootstrap-tooltip-extended.js is just one plugin, and nothing change in library bootstrap-tooltip.js
So here, no hacking of bootstrap, only extending. ;-)

> I think you should had as new files.

Maybe an idea...! As this way, we can call it only when needed, and this way, could be used by site template using bootstrap 3.

With something like : 
<code>JHtml::_('bootstrap.tooltipExtended', $selector, $params = array());</code>
OR to extend tooltip class like this :
<code>JHtml::_('bootstrap.tooltip', $selector, $params = array(), $extended = false);</code> and then loading separated js and css for tooltip extended ?

@andrepereiradasilva, @mbabker, @brianteeman ...
What's your opinion about this other possibility ?

**Comment by andrepereiradasilva** [comment]
> @andrepereiradasilva note about bootstrap, i don't have hacked nor changed nothing in Bootstrap, just added a plugin in bootstrap.js, which extends tooltip plugin.
> bootstrap.js is a one readable compiled file of all bootstrap plugins as you can customize it yourself on getbootstrap: http://getbootstrap.com/customize/#plugins
> bootstrap-tooltip-extended.js is just one plugin, and nothing change in library bootstrap-tooltip.js
So here, no hacking of bootstrap, only extending. ;-)

I know. I mean changing the bootstrap(.min).js file. :smile: 

> What's your opinion about this other possibility ?

IMHO it would be better.

**Comment by JoomliC** [comment]
So, what about this : 
```
	public static function tooltipExtended($extended = true)
	{
		if ($extended)
		{
			JHtml::_('script', 'jui/bootstrap-tooltip-extended.min.js', false, true);
			JHtml::_('stylesheet', 'jui/bootstrap-tooltip-extended.css', false, true);
		}
	}
```

We call files with <code>JHtml::_('bootstrap.tooltipExtended');</code> (this will be useful in modals)

This way, no change in bootstrap.js, and no change in core less/css files.

Maybe should i go this way ?

**Comment by andrepereiradasilva** [comment]
i agree

**Comment by JoomliC** [comment]
@andrepereiradasilva Done! ;-)

Testing Instructions not changed: in all modals (Batch, copy Template...)

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on c76be51c4a4ee8c1ff1f0d3b3dd790dfed187672<br /><br />Nice work!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10237">issues.joomla.org/joomla-cms/10237</a>.</sub>

**Comment by infograf768** [comment]
will test tomorrow. :smiley:

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on c76be51c4a4ee8c1ff1f0d3b3dd790dfed187672<br /><br />It works here. Thanks. Lets give @infograf768 a chance to test too.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10237">issues.joomla.org/joomla-cms/10237</a>.</sub>

**Comment by brianteeman** [comment]
rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10237">issues.joomla.org/joomla-cms/10237</a>.</sub>

**Comment by Kubik-Rubik** [comment]
Thank you @JoomliC and testers!

**Pull request merged**
