### PR TITLE
remove joomlaconnect newsfeed

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #11344 .
#### Summary of Changes

In the sample data is a News Feed called Joomla Connect, the problem is that http://feeds.joomla.org/JoomlaConnect is no longer an rss feed
So we either have to remove the feed from the sample data or get it fixed on the web site (https://github.com/joomla/joomla-websites/issues/426)

This PR removes it from the sample data

### CODE REVIEW

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on 27fbee9

**Comment by hardiktailored** [comment]
I have tested this item :white_check_mark: successfully on 27fbee988425f04991dc4eb81d399410cd62983c<br /><br />Code reviewed. Looks fine.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11368">issues.joomla.org/joomla-cms/11368</a>.</sub>

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on 27fbee988425f04991dc4eb81d399410cd62983c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11368">issues.joomla.org/joomla-cms/11368</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC please<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11368">issues.joomla.org/joomla-cms/11368</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11368">issues.joomla.org/joomla-cms/11368</a>.</sub>

**Comment by jeckodevelopment** [comment]
@brianteeman I need to understand how to call the bot :P

**Comment by brianteeman** [comment]
@jeckodevelopment I will contact you on glip later today

**Comment by jeckodevelopment** [comment]
@brianteeman thank you!

**Pull request merged**
