### PR TITLE
[5.2] Guided Tours: How to Create Categories Updated Language

### PR DESCRIPTION
**Pull request by sdwjoomla**
Updated the step descriptions for How to Create Articles to provide more information for new users.

Pull Request for Issue # .

### Summary of Changes
- Updated How to Create Categories steps in the com_guidedtours.sys.ini file
- Added SQL files to change the position of the parent category step with language string title COM_GUIDEDTOURS_TOUR_CATEGORIES_STEP_PARENT_TITLE
- Updated installation/extensions.sql file

### Testing Instructions
Using a Joomla 5.0 instance, click Take a Tour > How to Create Categories?

### Actual result BEFORE applying this Pull Request
**Step 1: How to create categories**

**Step 2: Select the 'New' button**

**Step 3: Add a title for the category**

**Step 4: Enter an alias**

**Step 5: Add content**

**Step 6: Select parent category**

**Step 7: Select the status**

**Step 8: Set the access

 level**

**Step 9: Add tags**

**Step 10: Add a note**

**Step 11: Add a version note**

**Step 12: Select 'Save and Close'**

**Step 13: Congratulations!**

### Expected result AFTER applying this Pull Request
**Step 1: How to create categories**

**Step 2: Create a New Category**

**Step 3: Add a Title for the Category**

**Step 4: Generate or Add the Category Alias**

**Step 5: Add a Category Description**

**Step 6: Select a Parent Category**

**Step 7: Select the Category Status**

**Step 8: Set the Category Access Level**

**Step 9: Add One or More Tags**

**Step 10: Add a Note**

**Step 11: Add a Version Note**

**Step 12: Save and Close**

**Step 13: Congratulations!**

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
I am not in favour of this change. It breaks multiple guidelines for the UI. Specifically https://manual.joomla.org/docs/user-interface-text/#notes

**Comment by sdwjoomla** [comment]
Thank you @brianteeman  for taking a look at the PR. The link provided speaks to "Avoid Over Communications" which does not apply in this case as it falls more within the documentation area. The intended audience would need the extra information that the updated language provides.

**Review by obuisard — APPROVED** [review]

**Comment by brianteeman** [comment]
same comments and observations as I wrote on the other pr

**Review by HLeithner — CHANGES_REQUESTED** [review]
Can't merged this till the translations has been moved out of the sys.ini file as mentioned here https://github.com/joomla/joomla-cms/pull/40606#issuecomment-1596273139

**Comment by sdwjoomla** [comment]
@brianteeman was done on a laptop. The SQL changes are changes in position to address overlay issues.
Resetting the PR to draft until the language change issues noted by @HLeithner are resolved.

**Comment by HLeithner** [comment]
This pull request has been automatically rebased to 5.1-dev.

**Comment by web54** [comment]
checked in 5.1.0-beta1-dev and failed (no change)

**Comment by HLeithner** [comment]
This pull request has been automatically rebased to 5.2-dev.

**Comment by coolcat-creations** [comment]
I have tested this item :red_circle: unsuccessfully on d6ee90055ae9c88494fdc37a28b69de3f33624fd<br /><br />checked in 5.2.0-beta2 and failed (no change)
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41047">issues.joomla.org/tracker/joomla-cms/41047</a>.</sub>

**Comment by sdwjoomla** [comment]
> I have tested this item 🔴 unsuccessfully on [d6ee900](https://github.com/joomla/joomla-cms/commit/d6ee90055ae9c88494fdc37a28b69de3f33624fd)checked in 5.2.0-beta2 and failed (no change)
> 
> This comment was created with the [J!Tracker Application](https://github.com/joomla/jissues) at [issues.joomla.org/tracker/joomla-cms/41047](https://issues.joomla.org/tracker/joomla-cms/41047).

Thanks @coolcat-creations for your interest in this PR.  It is currently still  a DRAFT and not yet ready for testing.

**Comment by sdwjoomla** [comment]
Closing PR - will work with the GT team to implement in the future.

**Pull request closed without merging**
