### PR TITLE
[4.0] Namespace Content - Confirm Consent plugin

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Namespaces Content - Confirm Consent plugin.

### Testing Instructions

Apply patch. Delete `libraries/autoload_psr4.php` file.
Enable Content - Confirm Consent plugin.
Create a contact with email.
View the contact form in frontend.
Check that consent checkbox appears in the form.

### Documentation Changes Required

IDK.

### CODE REVIEW

**Comment by jwaisner** [comment]
After applying patch the consent checkbox and link are broken.

AFTER


BEFORE

**Comment by jwaisner** [comment]
I have tested this item :red_circle: unsuccessfully on b7a5c00f2667e63244b48a6f2674ca41524f1399<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27641">issues.joomla.org/tracker/joomla-cms/27641</a>.</sub>

**Comment by jwaisner** [comment]
Also looks like Composer had to be reran after applying the patch which was not included in the instructions, but even after running that (using Git and Patchtester) I still have the same issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27641">issues.joomla.org/tracker/joomla-cms/27641</a>.</sub>

**Comment by SharkyKZ** [comment]
@jwaisner did you delete `libraries/autoload_psr4.php` file after applying patch? Running Composer is not required.

**Comment by jwaisner** [comment]
yes, that file was deleted after I applied the patch.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27641">issues.joomla.org/tracker/joomla-cms/27641</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on f54d303b6f21bc7b17d4905b334c13c55a625edc<br /><br />After latest commit the patch applies correctly. All looks good.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27641">issues.joomla.org/tracker/joomla-cms/27641</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :red_circle: unsuccessfully on f54d303b6f21bc7b17d4905b334c13c55a625edc<br /><br />The field is required, but if it is noch checked, it has not the aria-invalid="false" and is not marked by a red border.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27641">issues.joomla.org/tracker/joomla-cms/27641</a>.</sub>

**Comment by SharkyKZ** [comment]
@chmst Not related to this PR.

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on f54d303b6f21bc7b17d4905b334c13c55a625edc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27641">issues.joomla.org/tracker/joomla-cms/27641</a>.</sub>

**Comment by chmst** [comment]
Sorry. The checkbox itself is all right<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27641">issues.joomla.org/tracker/joomla-cms/27641</a>.</sub>

**Comment by SharkyKZ** [comment]
RTC.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27641">issues.joomla.org/tracker/joomla-cms/27641</a>.</sub>

**Pull request merged**
