### PR TITLE
[4.4] Correct file size validation for Media component

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/43387 .
Alternative to https://github.com/joomla/joomla-cms/pull/43904

### Summary of Changes

Fix media manager ApiController to check actual file size, instead of POST size.

### Testing Instructions
Please follow #43387

### Actual result BEFORE applying this Pull Request
False error

### Expected result AFTER applying this Pull Request
No false error

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed
- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 883539f045f1fb1d44277021a231ef86a0692759<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43906">issues.joomla.org/tracker/joomla-cms/43906</a>.</sub>

**Comment by ChristineWk** [comment]
Followed the instructions - and got the expected error message.

After applying the Patch, I got: 
```The patch could not be applied because it conflicts with a previously applied patch: administrator/components/com_media/src/Controller/ApiController.php```
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43906">issues.joomla.org/tracker/joomla-cms/43906</a>.</sub>

**Comment by Quy** [comment]
> Followed the instructions - and got the expected error message.
> 
> After applying the Patch, I got: `The patch could not be applied because it conflicts with a previously applied patch: administrator/components/com_media/src/Controller/ApiController.php`
> This comment was created with the [J!Tracker Application](https://github.com/joomla/jissues) at [issues.joomla.org/tracker/joomla-cms/43906](https://issues.joomla.org/tracker/joomla-cms/43906).

Please make sure you don't have other patches applied.

**Comment by ChristineWk** [comment]
tks @Quy. If I had applied other patches, I wouldn't have been able to "fetch". Because then a different message would appear after fetch data. I'll check again. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43906">issues.joomla.org/tracker/joomla-cms/43906</a>.</sub>

**Comment by ChristineWk** [comment]
As a test I also tried a different pr (patch). This one was displayed. I tried again, unfortunately I now have error 500 (backend) Frontend OK. So I have to pass now .....<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43906">issues.joomla.org/tracker/joomla-cms/43906</a>.</sub>

**Comment by ChristineWk** [comment]
So, I was able to clear the 500 error. It was a MySQL issue.
After "fetch data" I got the above message again. 
So I clicked "Reset" and everything was fine again.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43906">issues.joomla.org/tracker/joomla-cms/43906</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 883539f045f1fb1d44277021a231ef86a0692759<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43906">issues.joomla.org/tracker/joomla-cms/43906</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43906">issues.joomla.org/tracker/joomla-cms/43906</a>.</sub>

**Comment by MacJoom** [comment]
Thank you!

**Pull request merged**
