### PR TITLE
Missing dollar for variable in en-GB.lib_joomla.ini

### PR DESCRIPTION
**Pull request by sisko1990**
Variable typo in ini string

### CODE REVIEW

**Comment by roland-d** [comment]
Hello,

Thank you for your submission. Please provide test instructions so people know what to test.

**Comment by sisko1990** [comment]
I don't know under which circumstances these messages are triggered, but I see that the variable differs from all other variables in the language files.
And the PHP manual say I'am right: http://de2.php.net/manual/en/function.sprintf.php#example-5433

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 3ea2899b961c42c5aabd09bd2ad26df4538d0ec5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10658">issues.joomla.org/joomla-cms/10658</a>.</sub>

**Comment by infograf768** [comment]
Obvious typo. Can be merged on review. RTC.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10658">issues.joomla.org/joomla-cms/10658</a>.</sub>

**Comment by roland-d** [comment]
Thanks everybody

**Comment by sovainfo** [comment]
Introduced by me in https://github.com/joomla/joomla-cms/pull/6644/files. Must have overlooked the correct syntax. Thanks for fixing.

**Pull request merged**
