### PR TITLE
[4.0] Workflows strings

### PR DESCRIPTION
**Pull request by brianteeman**
Just as we dont use "manager" in the title any more as it is redundant there is no need to use "List" either. Workflows was the only place that used this term.

Code review should be fine

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 05a07a8ca9b24aa8418e18cb1da2992227c51b51<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33938">issues.joomla.org/tracker/joomla-cms/33938</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 05a07a8ca9b24aa8418e18cb1da2992227c51b51<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33938">issues.joomla.org/tracker/joomla-cms/33938</a>.</sub>

**Comment by Quy** [comment]
Thank you

**Comment by brianteeman** [comment]
thank you

**Pull request merged**
