### PR TITLE
Typos

### PR DESCRIPTION
**Pull request by demis-palma**
To be merged on review

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 0434cfdd0ea3d73d2552a68314be5a0aa12378e1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14966">issues.joomla.org/tracker/joomla-cms/14966</a>.</sub>

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on 0434cfdd0ea3d73d2552a68314be5a0aa12378e1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14966">issues.joomla.org/tracker/joomla-cms/14966</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14966">issues.joomla.org/tracker/joomla-cms/14966</a>.</sub>

**Review by brianteeman — APPROVED** [review]

**Comment by zero-24** [comment]
Thanks @demis-palma :+1:

**Pull request merged**
