### PR TITLE
[5.2] Update PackageAdapter.php

### PR DESCRIPTION
**Pull request by BrainforgeUK**
Remove whitespace around extension folder names.

Pull Request for Issue # .

### Summary of Changes

Apply trim() function to filename.

An alternative solution would be to remove the whitespace in the manifest.
But why? It is valid XML and the installation failure can catch extension developers by surprise.

### Testing Instructions

Install attached test package.
[test1.zip](https://github.com/joomla/joomla-cms/files/11800469/test1.zip)

### Actual result BEFORE applying this Pull Request

Package installation fails.

### Expected result AFTER applying this Pull Request

Package installation succeeds

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on 13632866f6d3b5c7827d83bbb2ce279696bcf2c4<br /><br />After install: uninstall com_test1, plg_quickicon_test1, plg_user_test1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40989">issues.joomla.org/tracker/joomla-cms/40989</a>.</sub>

**Comment by ceford** [comment]
Oops - should have uninstalled Package Test1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40989">issues.joomla.org/tracker/joomla-cms/40989</a>.</sub>

**Comment by HLeithner** [comment]
This pull request has been automatically rebased to 4.4-dev.

**Comment by exlemor** [comment]
I have tested this item :white_check_mark: successfully on 13632866f6d3b5c7827d83bbb2ce279696bcf2c4<br /><br />Hi @brainforgeUK, I have tested successfully but

1. is this really necessary? ( I ask because would an extension developer not build his/her extension package correctly based on established process/documentation ).

I am definitely no expert, it just feels like we are trying to fix something that shouldn't exist in the real world and/or quite rare if the extension is built correctly. Mind you, I may completely wrong.


2. When I tried uninstalling your Package test1.zip, I received these error messages, FYI:

Warning
Package Uninstall: Missing manifest file.

info
Error uninstalling package.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40989">issues.joomla.org/tracker/joomla-cms/40989</a>.</sub>

**Comment by Hackwar** [comment]
Hello @BrainforgeUK, something went wrong when switching the branches and you have now unrelated changes in your PR. Could you rebase the PR and fix those issues?

**Comment by Hackwar** [comment]
Since you recreated the PR, I'm closing this one.

**Pull request closed without merging**
