### PR TITLE
[4.0] Fix markup

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
Add space before attribute.

### Testing Instructions
Edit a menu item.
View page source.

Code review.

### Actual result
markup

### CODE REVIEW

**Comment by ReLater** [comment]
I have tested this item :white_check_mark: successfully on 522389ddc32b340d3c5006674b5627144cdd89a5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24807">issues.joomla.org/tracker/joomla-cms/24807</a>.</sub>

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on 522389ddc32b340d3c5006674b5627144cdd89a5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24807">issues.joomla.org/tracker/joomla-cms/24807</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24807">issues.joomla.org/tracker/joomla-cms/24807</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
