### PR TITLE
Variable names - naming conventions - testing the waters

### PR DESCRIPTION
**Pull request by frankmayer**
I was thinking of doing some work on updating variable names according to naming conventions.
Since these are all in function scope, no issues are expected.

Here is a small commit to test the waters with the team. If the things changed in this one commit are ok with you guys, I'll happily attach some more to this PR.

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on ed949da9d1c9f3be9c1ebf643c8df5c0c946edfe<br /><br />Not that i have any say in this, but for me is ok! Code review.
Still, if this accepted, i would advice to make multiple small PR.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13170">issues.joomla.org/tracker/joomla-cms/13170</a>.</sub>

**Comment by frankmayer** [comment]
@andrepereiradasilva I was thinking, in order to not have hundreds of separate PRs (local branches, etc), to separate in the style of /administrator, then /components then /modules, etc...

**Review by manojLondhe — COMMENTED** [review]
Changes look good! :+1:

**Comment by Bakual** [comment]
Looks good to me as well.
General rule of thumb: smaller PRs are easier to review and test and get merged faster. That is especially important when you touch a lot of files/lines as it reduces the chance for accumulating merge conflicts.

**Comment by frankmayer** [comment]
@bakual yes, that's clear now ;) ... 
I have not found the golden rule, yet, for such mass changes. I think I'll compartmentalize even further though, as /administrator and /libraries/cms might have a lot of changes...

So let's call the changes in this PR final and get it ready to be merged. :smile:

**Review by andrepereiradasilva — APPROVED** [review]

**Comment by anibalsanchez** [comment]
I have tested this item :white_check_mark: successfully on ed949da9d1c9f3be9c1ebf643c8df5c0c946edfe<br /><br />Test OK<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13170">issues.joomla.org/tracker/joomla-cms/13170</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13170">issues.joomla.org/tracker/joomla-cms/13170</a>.</sub>

**Pull request merged**
