### PR TITLE
[4.0] regenerate helptoc

### PR DESCRIPTION
**Pull request by brianteeman**
Not sure how you can test this as its the results of an automated script (buildTOC.php)

All I can think of is to see that there is a new "Action Logs" entry in the help toc and that links work

image

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on a64c15ff8bcf7efcc0f97c2ab380f6b6544659fb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33415">issues.joomla.org/tracker/joomla-cms/33415</a>.</sub>

**Comment by alikon** [comment]
> Not sure how you can test this as its the results of an automated script 

just apply the pr or manually change that file

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on a64c15ff8bcf7efcc0f97c2ab380f6b6544659fb

I applied the pull request and saw the new "Action Logs" entry.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33415">issues.joomla.org/tracker/joomla-cms/33415</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33415">issues.joomla.org/tracker/joomla-cms/33415</a>.</sub>

**Comment by richard67** [comment]
@brianteeman I've just compared the old and the new json and found that this PR not only adds the one for action logs but also removes the `"EXTENSIONS_MODULE_MANAGER_EDIT":"EXTENSIONS_MODULE_MANAGER_EDIT"`. Is that by purpose?

**Comment by brianteeman** [comment]
It's an autogenerated script so would need to follow the conditions in the script to find out

**Comment by brianteeman** [comment]
its removed because there is no help page for it

**Comment by richard67** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
