### PR TITLE
Update htaccess.txt

### PR DESCRIPTION
**Pull request by brianteeman**
Updated the comments in the htaccess file to make it clearer that the modules referred to are Apache modules and not Joomla modules

(I just had someone asking why joomla didnt ship with mod_rewrite installed like all the other modules)

This is done as a separate PR to the J4 PR as the files are quite different

### CODE REVIEW

**Review by wilsonge — APPROVED** [review]

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 3dcb6a8dd2bd66d34d5326f41c27306f96615fbc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25738">issues.joomla.org/tracker/joomla-cms/25738</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 3dcb6a8dd2bd66d34d5326f41c27306f96615fbc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25738">issues.joomla.org/tracker/joomla-cms/25738</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25738">issues.joomla.org/tracker/joomla-cms/25738</a>.</sub>

**Comment by richard67** [comment]
I hope these users will not ask now why there is a US army helicopter mentioned in the text ;-)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25738">issues.joomla.org/tracker/joomla-cms/25738</a>.</sub>

**Comment by HLeithner** [comment]
Thank you for you ongoing effort making comments better in Joomla!

**Comment by brianteeman** [comment]
thnks

**Pull request merged**
