### PR TITLE
Remove tags related code from com_banners

### PR DESCRIPTION
**Pull request by joomdonation**
Pull Request for Issue # .

### Summary of Changes
This simple PR just removed tags related code from com_banner as tag is not used inside this component at all

### Testing Instructions
Code review only

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on f8fb832f7c383db7232015276e87134b1bea4459<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19245">issues.joomla.org/tracker/joomla-cms/19245</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on f8fb832f7c383db7232015276e87134b1bea4459<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19245">issues.joomla.org/tracker/joomla-cms/19245</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
Ready to Commit after two successful tests.

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Pull request merged**
