### PR TITLE
Fixing preview in Templates > Templates

### PR DESCRIPTION
**Pull request by jeckodevelopment**
Pull Request for Issue #11356 .
#### Summary of Changes

Changed the URL for the preview -> `template` instead of `templateStyle`
#### Testing Instructions

Fixing #11356

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11357">issues.joomla.org/joomla-cms/11357</a>.</sub>

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11357">issues.joomla.org/joomla-cms/11357</a>.</sub>

**Comment by Lavsteph** [comment]
I have tested this item :white_check_mark: successfully on <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11357">issues.joomla.org/joomla-cms/11357</a>.</sub>

**Comment by dgt41** [comment]
I have tested this item :white_check_mark: successfully on <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11357">issues.joomla.org/joomla-cms/11357</a>.</sub>

**Comment by zero-24** [comment]
Hi, bot i know it is late (at least here) but the label is stil needed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11357">issues.joomla.org/joomla-cms/11357</a>.</sub>

**Pull request merged**
