### PR TITLE
[4.2] hotkeys

### PR DESCRIPTION
**Pull request by brianteeman**
In the past there were some issues with folders with a . in them. I forget what the issue was. As a result choices.js was stored in choicesjs to avoid this.

This pr does the same for hotkeys.js

@fancyFranci

### CODE REVIEW

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on 5eea7efee3b5536cdaa6245107aebc29c5a30f98<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38334">issues.joomla.org/tracker/joomla-cms/38334</a>.</sub>

**Comment by Kostelano** [comment]
I have tested this item :white_check_mark: successfully on 63987b351dc5913a206f3c6101e798fce0a70fab<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38334">issues.joomla.org/tracker/joomla-cms/38334</a>.</sub>

**Comment by brianteeman** [comment]
This PR will be closed in 24 hours. There is no point in it existing once 4.2 is released. Just dont say no one knew the folder name was a problem and you have to write a complex pr to fix the mess

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38334">issues.joomla.org/tracker/joomla-cms/38334</a>.</sub>

**Comment by roland-d** [comment]
Thank you. The issue with a dot is described here: https://github.com/joomla/joomla-cms/pull/22263#discussion_r219211595

**Comment by brianteeman** [comment]
well at least it got merged in the end

**Pull request merged**
