### PR TITLE
[5.1] Fix TinyMCE media button, insert link bug

### LINKED ISSUE #43365: [5.1] TinyMCE: can't insert media in article
### Steps to reproduce the issue
In an article try to insert a PDF file (CMS Content -> Media)

### Expected result
You can insert a link to or you get an iframe with the PDF

### Actual result
Javascript error, insert button doesn't work for download PDF. Iframe seems to be inserted, after saving the article, the iframe dissapears

grafik

### System information (as much as possible)
Joomla 5.1
PHP 8.1.28 / 8.2.18
MySQL 8.0.35  / MariaDB 10.6.15

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/43365

### Summary of Changes

Fix inserting PDF in to TinyMCE as a link

### Testing Instructions
Run `npm install`
In TinyMCE editor try to insert a PDF file, using Media button

### Actual result BEFORE applying this Pull Request
Nothing hapen.
Browser console shows an error

### Expected result AFTER applying this Pull Request
Link inserted

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed
- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 6339fe1313b4453df5a4d95b0e05b548c8486098<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43374">issues.joomla.org/tracker/joomla-cms/43374</a>.</sub>

**Comment by carlitorweb** [comment]
I have tested this item :white_check_mark: successfully on 6339fe1313b4453df5a4d95b0e05b548c8486098<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43374">issues.joomla.org/tracker/joomla-cms/43374</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43374">issues.joomla.org/tracker/joomla-cms/43374</a>.</sub>

**Comment by LadySolveig** [comment]
Thank you @Fedik and for testing @Quy @carlitorweb

**Pull request merged**
