### PR TITLE
[4.1] Fix Task Scheduling Behavior with WebCron (...)

### PR DESCRIPTION
**Pull request by ditsuke**
Pull Request for Issue #36460.

### Summary of Changes
Fixes scheduling bypass with no ID passed to WebCron etc.

### Testing Instructions
- Create a Scheduled task "WebCronTest" to Sleep for 5 seconds with:
 - Execution Rule = Interval, Minutes
 - Interval in Minutes = 60
- In the component options for Scheduler:
 - Enable Web Cron
 - Copy your secret URL. It should look like: `http://example.com/index.php/component/ajax/?plugin=RunSchedulerWebcron&group=system&format=json&hash=xxx`
- Visit URL. Takes 5 second => "WebCronTest" executed.
- Visit URL again/reload.

### Actual result BEFORE applying this Pull Request
URL takes 5 seconds to load again => "WebCronTest" executed again even when it's not due.

### Expected result AFTER applying this Pull Request
URL does not take 5 seconds. "WebCronTest" is not executed since it should not be due again before 60 minutes.

### Documentation Changes Required
\-

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 82662d27e8457f4a434d4dfdc1468b253f454800<br /><br />I've tested also with 10 minutes instead of 60 if the task is started again when this time has expired (I did not have the time to wait for an hour). This works, too.

I.e. without the PR: Task is triggered with every page load. With PR: Task is not triggered with every page load but is triggered when the last execution is 10 minutes or longer in past, as it should be.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36461">issues.joomla.org/tracker/joomla-cms/36461</a>.</sub>

**Comment by richard67** [comment]
@PhilETaylor Could you give it a quick test, too? For me it worked fine. Thanks in advance.

**Comment by dgrammatiko** [comment]
I have tested this item :white_check_mark: successfully on 82662d27e8457f4a434d4dfdc1468b253f454800<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36461">issues.joomla.org/tracker/joomla-cms/36461</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36461">issues.joomla.org/tracker/joomla-cms/36461</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
