### PR TITLE
[4.0] com_contact blank state

### PR DESCRIPTION
**Pull request by brianteeman**
See #33264 for instructions but this time for contacts and not content

This PR requires the code from #33264 to be merged first - specifically the change in `libraries/src/MVC/Model/ListModel.php`

added a docs links

### CODE REVIEW

**Comment by PhilETaylor** [comment]
could always use the link to the help proxy? https://help.joomla.org/proxy?keyref=Help40:Contacts&lang=en#Description I guess... ?

**Comment by ceford** [comment]
Why do we need a **Learn More** button? Surely this is just a rabbit hole likely to lead the new user astray. A click on the **Add your first article** button should be a good enough place to start. There is the **Help** button at the top right.

**Comment by PhilETaylor** [comment]
Because the WHOLE POINT is Empty State Design. 

https://www.toptal.com/designers/ux/empty-state-ux-design

Does it need a Learn More button - maybe not on all pages. 

Does it need MORE explanation on some page HELL YES! It needs to be proportional to the page though. Thats the point.

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on ee7b670084f8eebcf5e997428693efb57720d0d5<br /><br />Applied patch #33264 first. With that patch activated I then applied this patch. Works great!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33265">issues.joomla.org/tracker/joomla-cms/33265</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on ee7b670084f8eebcf5e997428693efb57720d0d5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33265">issues.joomla.org/tracker/joomla-cms/33265</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33265">issues.joomla.org/tracker/joomla-cms/33265</a>.</sub>

**Comment by brianteeman** [comment]
Thank you

**Pull request merged**
