### PR TITLE
[4.0] [plg_sampledata_multilang] Add missing checks

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue # .

### Summary of Changes

Adds context check in last step. Fixes weird alert when installing Testing Sample Data.

### Testing Instructions

1. On monolingual site install Testing Sample Data. Inspect progress messages.
2. On multilingual site install Multilingual Sample Data. Inspect progress messages.

### Expected result

1. Messages appear normally.
2. Works like before.

### Actual result

1. Empty space appears between step 7 and step 8 messages.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on e3ebc695c819b24be66dfa1dd70371f17f683003<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27183">issues.joomla.org/tracker/joomla-cms/27183</a>.</sub>

**Comment by infograf768** [comment]
@SharkyKZ 
If checking session is necessary for this plugin concerning the last Step, then it is also necessary for blog sample data as we only have there

```
	public function onAjaxSampledataApplyStep4()
	{
		if ($this->app->input->get('type') != $this->_name)
		{
			return;
		}
```
I suggest to also correct that one in this PR.

**Comment by SharkyKZ** [comment]
Not really necessary in the last step.

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on a03ac6e05aeac5489076c697f7facc1b037ada73<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27183">issues.joomla.org/tracker/joomla-cms/27183</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27183">issues.joomla.org/tracker/joomla-cms/27183</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
