### PR TITLE
[5.0beta1] Unique identifier

### PR DESCRIPTION
**Pull request by brianteeman**
Tweak the language strings

### Actual result BEFORE applying this Pull Request

image

### Expected result AFTER applying this Pull Request
image

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on fc970c7d7e9cada95b45925a36603139044bfcd0<br /><br />Review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41604">issues.joomla.org/tracker/joomla-cms/41604</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on fc970c7d7e9cada95b45925a36603139044bfcd0<br /><br />cr<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41604">issues.joomla.org/tracker/joomla-cms/41604</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on fc970c7d7e9cada95b45925a36603139044bfcd0<br /><br />cr<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41604">issues.joomla.org/tracker/joomla-cms/41604</a>.</sub>

**Comment by alikon** [comment]
rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41604">issues.joomla.org/tracker/joomla-cms/41604</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41604">issues.joomla.org/tracker/joomla-cms/41604</a>.</sub>

**Pull request merged**
