### PR TITLE
Ensure we still have valid users to batch reset password

### PR DESCRIPTION
**Pull request by wilsonge**
To test:
Select the user you are currently logged in with only and batch reset their password (with a value of yes or no).

Before the patch you'll get a mysql warning. After the patch you'll get a notice that no users have been selected.

This is because you cannot reset the password of the currently logged in user so suddenly you are trying to batch reset no users.

### CODE REVIEW

**Comment by infograf768** [comment]
This does not work here.
If I choose another user than the one logged in and set Batch Require Password Reset to "No" or "Yes", I get the same message. 

>Batch process failed with following error: No Users selected.

**Comment by infograf768** [comment]
It works though if you change to
```
if (empty($user_ids))
		{
			$this->setError(JText::_('COM_USERS_USERS_NO_ITEM_SELECTED'));

			return false;
		}
```
No more mysql error, even when selecting multiple users including yourself. In that last case the "Require Password Reset" param is applied to the other users only.

Maybe we would need a new string btw;
Something like:
`COM_USERS_USERS_ERROR_CANNOT_REQUIRERESET_SELF="You can't require a Password reset for yourself."`

**Comment by wilsonge** [comment]
This is what comes of copy/pasting the wrong snippet of code from my local server. Thanks JM! Fixed now!

**Comment by infograf768** [comment]
What about the new language string? It does not make much sense in this context as a user has been selected.

**Comment by brianteeman** [comment]
Agree with @infograf768 this needs a different language string
@wilsonge can you do that please<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8804">issues.joomla.org/joomla-cms/8804</a>.</sub>

**Comment by wilsonge** [comment]
Done and rebased onto staging at the same time

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 3ca055a3d3a749a93b2cada0959a8e4d50400605<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8804">issues.joomla.org/joomla-cms/8804</a>.</sub>

**Comment by bertmert** [comment]
I have tested this item :white_check_mark: successfully on 3ca055a3d3a749a93b2cada0959a8e4d50400605<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8804">issues.joomla.org/joomla-cms/8804</a>.</sub>

**Comment by brianteeman** [comment]
RTC - thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8804">issues.joomla.org/joomla-cms/8804</a>.</sub>

**Pull request merged**
