### PR TITLE
Improve checks for important menu items in custom admin menu

### PR DESCRIPTION
**Pull request by izharaazmi**
Improve checks for presence of important menu items in custom admin menu.

### Summary of Changes
* Improve recovery link to bring user back to same page when switching recovery mode on/off, currently it takes the user to admin home page.
* One liner message for all the 3 important menu item for simplicity.
* Stop annoying info alert on every page when user is in menu recovery mode and show “exit recovery” as a menu item inside recovery menu parent itself.

### Testing Instructions
* Create a custom admin menu and set it as your active menu in menu module settings.
* A message stating that the important menu items Module Manager, Menu Manger and Component Container are missing should be shown including a link to enable the recovery mode.
* Creating any of these items in the custom admin menu should remove that item from the list of missing items in the warning.
* Exit recovery mode should be shown in the recovery menu when you turn on recovery mode.

### Documentation Changes Required
None

### CODE REVIEW

**Comment by infograf768** [comment]
I suggest to change the message, using ordered variables and including the menu type:
from

`+MOD_MENU_IMPORTANT_ITEMS_INACCESSIBLE_LIST_WARNING="The active administrator menu does not contain - <strong>%s</strong>. Click to <strong><a href='%s'>turn on the menu recovery mode</a></strong>."`

to

`+MOD_MENU_IMPORTANT_ITEMS_INACCESSIBLE_LIST_WARNING="The <strong>%1$s</strong> active administrator menu does not contain - <strong>%2$s'</strong>. Click to <strong><a href='%3$s'>turn on the menu recovery mode</a></strong>."`

and modify $msg in menu.php to:

`$msg = JText::sprintf('MOD_MENU_IMPORTANT_ITEMS_INACCESSIBLE_LIST_WARNING', $menutype, implode(', ', $missing), $uri->toString());`

in order to get a better information when multiple custom admin menus:

screen shot 2017-02-25 at 10 36 14

Otherwise, everything looks fine here.
👍

**Comment by izharaazmi** [comment]
Doing it.

Btw, how did you manage to product messages for two menutypes at the same
time? IMO, only one can be active at a time. Did you create two modules?

**Comment by izharaazmi** [comment]
Done!

**Comment by infograf768** [comment]
> IMO, only one can be active at a time. Did you create two modules?

Yep. This the nice feature about it. One may create multiple custom admin languages (needs multiple admin menutypes and their modules). Then it is "just" a matter of creating the correct access levels. 
That last part can be tricky as core defines "Special" as common access level for quite a few user groups. Tricky but not impossible.

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on adb62913ef885c403036e0e0f3a7ad36e1e50263<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14235">issues.joomla.org/tracker/joomla-cms/14235</a>.</sub>

**Comment by infograf768** [comment]
One aspect to look at, maybe.
when we have 2 menutypes the recovery link is the same for both and it picks the first one created.

`/administrator/index.php?option=com_menus&view=items&menutype=myadminmenu&recover_menu=1`

**Comment by izharaazmi** [comment]
Everything in the recovery link except `&recover_menu=1` part is the current page url. That does not depend on the active menu type or the menu type that rendered the message.

This is to land the user back to same page when switching recovery mode.

**Comment by AlexRed** [comment]
I have tested this item :white_check_mark: successfully on adb62913ef885c403036e0e0f3a7ad36e1e50263<br /><br />Patch ok for me<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14235">issues.joomla.org/tracker/joomla-cms/14235</a>.</sub>

**Comment by infograf768** [comment]
rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14235">issues.joomla.org/tracker/joomla-cms/14235</a>.</sub>

**Pull request merged**
