### PR TITLE
Modal com_newsfeeds: improve Select & Edit Newsfeed

### PR DESCRIPTION
**Pull request by cyrez**
Improve modals to select and to edit a news feed.
**Note: to be testing on staging.**
#### Summary of Changes
- When Bootstrap modal loads an iframe, BS tooltips with placement top are truncated at the top border of the iframe. (no auto placement in BS2). This PR sets the tooltip placement to bottom to fix this issue.
- Remove inline CSS
- Content is embedded in a container div (using already existing container-popup class for modal.php)
- Add empty lines to improve the readability
- Add viewport dimensions (new <code>3.6.0-dev</code>)
- News feed edit modal is simplified (load edit layout, so no dupplicated code)
- Fix Edit button when current associated news feed in data is not the selected news feed
- Control if modal, in edit layout
- Add <code>Save</code> (keep modal open), <code>Save & Close</code> and <code>Close</code> button to the footer of the modal
- Fix Edit modal not opening as a modal (missing bootstrap.renderModal for Edit modal)
- Fix consistency of fieldsets <code>$this->ignore_fieldsets</code>, and add missing tabs, and remove dupplicated fieldset metadata (as using now correct edit view inside the modal)
#### Testing Instructions (Staging + Multilanguages enabled!)
- Go to Components > News Feeds > open a news feed, and go to <code>Associations</code> tab to select associated news feed to open the modal.
- Verify tooltip placement is bottom, and not truncated
- Verify the modal size now is proportionnal to viewport (modal is 80/100th viewport width, and modal-body is 70/100th viewport height)
- Select an associated news feed and save the news feed to show edit button
- Open Edit modal and play with it ;-)
- Do the same in a menu item type "Single news feed", for Select and Edit news feed.

Same rendering as for Categories in PR #10441 (screenshots)

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 2e2f7e1245746a0b4a20d840336fc2ed0137a6ef<br /><br />All worked fine.
Great work again!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10516">issues.joomla.org/joomla-cms/10516</a>.</sub>

**Comment by BurtNL** [comment]
I have tested this item :white_check_mark: successfully on 2e2f7e1245746a0b4a20d840336fc2ed0137a6ef<br /><br />Tested successfully, works as described.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10516">issues.joomla.org/joomla-cms/10516</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10516">issues.joomla.org/joomla-cms/10516</a>.</sub>

**Comment by roland-d** [comment]
Thanks everybody

**Pull request merged**
