### PR TITLE
[4.0] Quickicons wrap-able text

### PR DESCRIPTION
**Pull request by ciar4n**
Pull Request for Issue #14476 and #14478 .

### Summary of Changes
Allows quickicons text to wrap correctly.

### Testing Instructions
Apply patch and resize browser window, observing quickicons.

### Before Patch
See #14476 and #14478

### After Patch
4-quickicons2

### Documentation Changes Required
None

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 8331685808ab192d1eb0eb8c5f66f2b9c152f0a6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14507">issues.joomla.org/tracker/joomla-cms/14507</a>.</sub>

**Comment by C-Lodder** [comment]
@ciar4n - did you also text the mobile quick icons? They have a different design so just wanna make sure this doesn't break them

**Comment by ciar4n** [comment]
@C-Lodder Checked and still working fine..

4-quickicons3

**Review by C-Lodder — APPROVED** [review]

**Comment by wilsonge** [comment]
Can you fix conflicts please (should just need a rerun of the compiler)

**Comment by ciar4n** [comment]
@wilsonge Done!

**Pull request merged**
