### PR TITLE
[4.0] WCAG 1.4.3: Elements must have sufficient color contrast (#disk-1)

### PR DESCRIPTION
**Pull request by brianteeman**
The color used for the title of the tree eg LOCAL fails the accessibility contrast checks. This PR resolves that.
Element path: #disk-1

Snippet: ```<h2 id="disk-1" class="media-disk-name" tabindex="-1">Local</h2>```

  Element has insufficient color contrast of 2.32 (foreground color: #aaaaaa, background color: #ffffff, font size: 8.4pt (11.2px), font weight: bold). Expected contrast ratio of 4.5:1

### CODE REVIEW

**Comment by brianteeman** [comment]
updated branch to retrigger appveypr

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on bf2e1815cd8b5ac36b48e2775426ac45023e65b0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26824">issues.joomla.org/tracker/joomla-cms/26824</a>.</sub>

**Comment by brianteeman** [comment]
re-trigger drone

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 37b92d7b03ac1e0f4b2da48ce643cafb880d93da<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26824">issues.joomla.org/tracker/joomla-cms/26824</a>.</sub>

**Comment by infograf768** [comment]
rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26824">issues.joomla.org/tracker/joomla-cms/26824</a>.</sub>

**Comment by zero-24** [comment]
Merged thanks :+1:

**Comment by brianteeman** [comment]
thank you

**Pull request merged**
