### PR TITLE
[5.2] Clarify Cache Plugin

### PR DESCRIPTION
**Pull request by brianteeman**
Adds the highlighted text to the description of the page cache plugin in a perhaps feeble attempt to better explain why it probably is not what the user wants to enable.

image

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on c248a6336915269e3c23e7ef6a9dc4a7fed61405<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43378">issues.joomla.org/tracker/joomla-cms/43378</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on c248a6336915269e3c23e7ef6a9dc4a7fed61405<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43378">issues.joomla.org/tracker/joomla-cms/43378</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43378">issues.joomla.org/tracker/joomla-cms/43378</a>.</sub>

**Comment by pe7er** [comment]
Thanks @brianteeman !

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
