### PR TITLE
[4.0] Backend. Tabs empty in com_config if module User Status deactivated.

### PR DESCRIPTION
**Pull request by ReLater**
### Testing Instructions
- Go to "Administrator Modules" and deactivate all modules of type "User Status".
- Go to "Global Configuration".
- Click a component in left navigation, e.g. "Articles"
- Click on blue tabs above. 

### Expected result
- Tabulator content displayed.

### Actual result
- All tabulators are empty

### CODE REVIEW

**Comment by Quy** [comment]
Can you move line 16 above the `use` statements? Thanks.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on c61c0a2907c82503d339804832a2d50c9765a735<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24928">issues.joomla.org/tracker/joomla-cms/24928</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on c61c0a2907c82503d339804832a2d50c9765a735<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24928">issues.joomla.org/tracker/joomla-cms/24928</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24928">issues.joomla.org/tracker/joomla-cms/24928</a>.</sub>

**Pull request merged**
