### PR TITLE
Update log messages

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #14557 .

### CODE REVIEW

**Comment by zero-24** [comment]
> Successfully authenticated to complete the Joomla update.

hmm. If you find this message in your log you have bypassed the token check and authenticated you successfull or not. What about adding this info (bypassed the security checks) to the log?

> "Failled to authenticate to complete the Joomla update.

Failled is a typo? Same as above.

Thanks!

**Comment by brianteeman** [comment]
Fixed the typo

I guess I dont understand when you would see this in your logs or what it is supposed to mean.

**Comment by zero-24** [comment]
> I guess I dont understand when you would see this in your logs or what it is supposed to mean.

In com_joomlaupdate the JSST implemented a Sec / Token check.

But if we come from a older version the needed token is not added to the URL. So we have implemented a fallback that allows us to pass that check even if we have no token, by a authenticate you as Super User. This message should told you that you are gone that route. (bypass that token check because you are comming from a older version)

**Comment by zero-24** [comment]
Yes. Sorry for my englisch than. This is what i meant.

**Comment by brianteeman** [comment]
Sorry but i am still confused what the string should be

**Comment by mbabker** [comment]
Apparently the intent is to log a message if during the update process the CSRF token validation fails and you are required to reauthenticate.  The log message is based on the success/fail of that authentication step.

What that means the message should say, I'm still not entirely sure on.

**Comment by zero-24** [comment]
> What that means the message should say, I'm still not entirely sure on.

What about the seccond option and just remove it (log + string) if there is no reason to log such event?

**Comment by mbabker** [comment]
That works too

**Comment by zero-24** [comment]
see: https://github.com/joomla/joomla-cms/pull/14576

**Comment by brianteeman** [comment]
closing as we have decided not to have a message

**Comment by zero-24** [comment]
Thanks @brianteeman

**Pull request closed without merging**
