### PR TITLE
Move JErrorPage to namespace

### PR DESCRIPTION
**Pull request by laoneo**
Move JErrorPage class to namespace. Additionally some doc blocks are changed to be inline with rest.

### CODE REVIEW

**Comment by mbabker** [comment]
I know so far this has been just a straight "move to namespace" effort, but with this one class, can we take the opportunity to rename it to something more logical?  `Joomla\Cms\ExceptionHandler` perhaps?

It really isn't an error page renderer (even though that's what it is doing), it's the default global exception handler.

**Comment by laoneo** [comment]
That's the reason why I do a pr per folder that we can do some cleanup during the move.

What about moving it to `Joomla\Cms\Exception\ExceptionHandler`? When we will have some more gloabal exceptions then we can put them all into that folder. Even JException.

**Comment by mbabker** [comment]
I don't care if it's in a subnamespace, I just prefer the class name to not be `ErrorPage` 😄

**Comment by laoneo** [comment]
Done

**Review by yvesh — APPROVED** [review]

**Pull request merged**
