### PR TITLE
[4.0] Httpheader language

### PR DESCRIPTION
**Pull request by brianteeman**
Capitalisation and missing period

Sorry I missed these before

### CODE REVIEW

**Comment by ReLater** [comment]
I have tested this item :white_check_mark: successfully on 5cf4f13b2fd89186716128fe1e5caf4a9df3726a<br /><br />Code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20690">issues.joomla.org/tracker/joomla-cms/20690</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 5cf4f13b2fd89186716128fe1e5caf4a9df3726a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20690">issues.joomla.org/tracker/joomla-cms/20690</a>.</sub>

**Comment by infograf768** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20690">issues.joomla.org/tracker/joomla-cms/20690</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
