### PR TITLE
[5.2] Add missing Toggle inline help button to plugin modal / dialog

### PR DESCRIPTION
**Pull request by Ruud68**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/43289#issuecomment-2063290211 .

### Summary of Changes
plugin modal was missing Toggle inline help button

### Testing Instructions
a. add a description to a field in the file ./plugins/system/redirect/redirect.xml
e.g. to this field:
```
				<field
					name="collect_urls"
					type="radio"
					layout="joomla.form.field.radio.switcher"
					label="PLG_SYSTEM_REDIRECT_FIELD_COLLECT_URLS_LABEL"
					description="PLG_SYSTEM_REDIRECT_FIELD_COLLECT_URLS_LABEL"
					default="1"
					filter="integer"
					>
					<option value="0">JDISABLED</option>
					<option value="1">JENABLED</option>
				</field>
```
(line 6: description = has been added)

1. disable the system redirect plugin
image

2. goto com_redirect
3. in the alert telling you that the system redirect plugin is disabled, click on the link > the plugin will open in a modal
image

### Actual result BEFORE applying this Pull Request
The modal had three buttons: Save, Save & Close and Close
image

### Expected result AFTER applying this Pull Request
The modal has 4 buttons: Save, Save & Close, Close and Toggle inline help
image

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by dautrich** [comment]
I have tested this item :red_circle: unsuccessfully on 9ed546c8f5c13aaded187f8f411f868c2ebb32b0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43296">issues.joomla.org/tracker/joomla-cms/43296</a>.</sub>

**Comment by brianteeman** [comment]
Are you sure that is a good test instruction. That plugin doesnt show the toggle inline help button in a normal view either

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 9ed546c8f5c13aaded187f8f411f868c2ebb32b0<br /><br />after testing with a plugin that does have inline help I am changing my test result to successfull.



Please provide better testing instructions!!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43296">issues.joomla.org/tracker/joomla-cms/43296</a>.</sub>

**Comment by dautrich** [comment]
@brianteeman   How did you test? Which plugin?

**Comment by brianteeman** [comment]
i edited the code so that I could test the sef plugin

**Comment by Ruud68** [comment]
Sorry everybody, instructions updated. Toggle inline Help button is hidden when there are no descriptions in the XML file. I have added a step to add a description to the redirect plugin.
I also added visuals for what and where to click / what it will show.

Hope this makes it clear. Sorry for the confusion!

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 9ed546c8f5c13aaded187f8f411f868c2ebb32b0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43296">issues.joomla.org/tracker/joomla-cms/43296</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43296">issues.joomla.org/tracker/joomla-cms/43296</a>.</sub>

**Comment by Ruud68** [comment]
Thanks for testing everybody! Appreciate you taking the time for it.

**Comment by LadySolveig** [comment]
Thank you for this great idea! 
As it is not yet available in other modals either, such as article new/edit or contact new/edit, I see it as a new feature. Since we only deal with bug fixes in 5.1, I will pass it on to the 5.2 team @pe7er @woluweb 
Could you imagine adding it to the other components as well @Ruud68 ? That would be wonderful!

**Comment by brianteeman** [comment]
> Could you imagine adding it to the other components as well @Ruud68 ? That would be wonderful!

What other components?

**Comment by LadySolveig** [comment]
We have also dialogs for adding and editing contacts, articles and it would be nice if we could have it here also.

grafik
grafik

Not sure if I am missing something, where this could also be useful.

**Comment by brianteeman** [comment]
Sorry I must have confused this PR with another one as I was sure I had seen changed across all modals

**Comment by pe7er** [comment]
Thanks @Ruud68 ! It's a nice improvement! 
Actually, we would like to have this improvement in all Modal views, 
so we've created a new issue for that: https://github.com/joomla/joomla-cms/issues/43501
Could you please help out with that?

**Pull request merged**
