### PR TITLE
[4.0] Change all

### PR DESCRIPTION
**Pull request by PhilETaylor**
### Summary of Changes

Change all `<?=` to `<?php echo` in line with the [Joomla Code Standards ](https://developer.joomla.org/coding-standards/php-code.html)

### Testing Instructions

Just look at the code. 

### Actual result BEFORE applying this Pull Request

Everything works but some views use `<?=`

### Expected result AFTER applying this Pull Request

Everything works and all code uses `<?php echo`

### Documentation Changes Required

none

### CODE REVIEW

**Comment by brianteeman** [comment]
Good luck changing Niks code

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 788487f9efc07e87e68dd4ffddadd5f94940f05f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30089">issues.joomla.org/tracker/joomla-cms/30089</a>.</sub>

**Comment by PhilETaylor** [comment]
The 6 files in this PR are all headed as copyright OSM under GPL - I dont see any of Niks copyright at the top of these files. 

I deliberately excluded vendors from my fixes and I'm fully away of the stupidity of the Joomla Code Standard refusing php short tags `<?` and `<?=` tags when its included vendor code (including symfony code) contains them.

**Comment by brianteeman** [comment]
https://github.com/joomla/joomla-cms/pull/28094#discussion_r384554608

**Comment by PhilETaylor** [comment]
Well that's an argument for those above my pay grade and unrelated to this PR. 

The current published Joomla Code Standards state to not use shorthand tags, therefore all I have done is bring code in line with those, regardless of the stupidity of the Joomla Code Standards which are ancient and do not take modern PHP into account (PHP 7+ stuff) 

> Always use the full <?php ... ?> to delimit PHP code, not the <? ... ?> shorthand

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 788487f9efc07e87e68dd4ffddadd5f94940f05f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30089">issues.joomla.org/tracker/joomla-cms/30089</a>.</sub>

**Comment by infograf768** [comment]
rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30089">issues.joomla.org/tracker/joomla-cms/30089</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 788487f9efc07e87e68dd4ffddadd5f94940f05f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30089">issues.joomla.org/tracker/joomla-cms/30089</a>.</sub>

**Pull request merged**
