### PR TITLE
Use number_format() on stats module

### PR DESCRIPTION
**Pull request by mbabker**
#### Summary of Changes

Runs the article hit count through `number_format()` for better display of the hit count.
#### Testing Instructions

Apply patch and note the better formatted numbers.

screen shot 2016-06-10 at 10 57 09 am

screen shot 2016-06-10 at 10 57 49 am

### CODE REVIEW

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 031fe626f405539ee124916bd516bd7ac660667d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10784">issues.joomla.org/joomla-cms/10784</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 031fe626f405539ee124916bd516bd7ac660667d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10784">issues.joomla.org/joomla-cms/10784</a>.</sub>

**Comment by brianteeman** [comment]
RTC <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10784">issues.joomla.org/joomla-cms/10784</a>.</sub>

**Comment by bertmert** [comment]
I have tested this item :white_check_mark: successfully on 031fe626f405539ee124916bd516bd7ac660667d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10784">issues.joomla.org/joomla-cms/10784</a>.</sub>

**Comment by zero-24** [comment]
@brianteeman did you not add the milestone for a reason?

**Comment by brianteeman** [comment]
@wilsonge said only bugs when the beta was released so I'm not setting it
on any as I think everything is a bug and @wilsonge can make up his own
mind if it's a bug or feature.

**Comment by zero-24** [comment]
Ah OK thanks :)

**Pull request merged**
