### PR TITLE
[4.0] Fix styling of cancel button in com_content batch. Fixes #22886

### PR DESCRIPTION
**Pull request by wilsonge**
Updated PR of #22886 without the extra stuff added

Check the cancel button of the batch modal in com_content, before patch not styled, after patch styled

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 465b25dc34a23262f8cd75af99dd8b2367e4f5e6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23137">issues.joomla.org/tracker/joomla-cms/23137</a>.</sub>

**Comment by PhilETaylor** [comment]
https://github.com/joomla/joomla-cms/issues/22781

**Comment by PhilETaylor** [comment]
@wilsonge does this fix https://github.com/joomla/joomla-cms/issues/22781 ?

**Comment by wilsonge** [comment]
yes it does :) sorry missed that issue

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 465b25dc34a23262f8cd75af99dd8b2367e4f5e6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23137">issues.joomla.org/tracker/joomla-cms/23137</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23137">issues.joomla.org/tracker/joomla-cms/23137</a>.</sub>

**Pull request merged**
