### PR TITLE
Use javascript for placeholder fallback

### PR DESCRIPTION
**Pull request by wilsonge**
A slight improvement on #5453 keeping the code simpler by using the html5fallback library. We use this in all fields using JForm for the same purpose. And makes more sense than using JBrowser.

### CODE REVIEW

**Comment by zero-24** [comment]
@test success on Chrome,  IE11 and IE9 (use as per HTML code placeholder)

I have no Browser wich don't support it, so i can't test the fallback.

**Comment by brianteeman** [comment]
You can test with browserstack.com and XP and ie6

On 20 January 2015 at 10:32, zero-24 <notifications@github.com> wrote:

> @test <https://github.com/test> success on Chrome, IE11 and IE9 (use as
> per HTML code placeholder)
>
> I have no Browser wich don't support it, so i can't test the fallback.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/5828#issuecomment-70633999>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by dgt41** [comment]
@test Success on IE8
screen shot 2015-01-20 at 6 59 34

I like this change!
Would be perfect if we could inject the script like this
`JFactory::getDocument()->addCustomTag('<!--[if lt IE 9]><script src="/media/system/js/html5fallback.js"></script><![endif]—>');`

**Comment by zero-24** [comment]
@wilsonge can you have a look into @dgt41 's suggestion? So we can move this forward. Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5828">issues.joomla.org/joomla-cms/5828</a>.</sub>

**Comment by dgt41** [comment]
@zero-24 my suggestion is plain wrong! This PR is fine as is!

**Comment by zero-24** [comment]
Thanks for the update @dgt41 moving to RTC!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5828">issues.joomla.org/joomla-cms/5828</a>.</sub>

**Comment by ggppdk** [comment]
Hello, please see this issue:   #5411

**Pull request merged**
