### PR TITLE
[4.0] Fix subform default value filtering, and warning while string foreach()

### PR DESCRIPTION
**Pull request by Fedik**
### Summary of Changes

The same as #31399 but for J4

### Testing Instructions

Add subform field in to any xml in params section, example `mod_custom.xml`

```xml
<field name="subform_test2" type="subform" label="Subform field"
  multiple="true"
  default='[{"child_field": "Default text field value"}]'
>
    <form>
        <field
            name="child_field"
            type="text"
            label="Text field"
        />
    </form>
</field>
```
Open the form, remove all subform rows, and save.

### Actual result BEFORE applying this Pull Request
Subform field is empty, with zero rows

### Expected result AFTER applying this Pull Request
Subform field should show 1 row of default value

### Documentation Changes Required
none

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 09da9c8607ae990cca5d5fea19b8bc154bf6a407<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31400">issues.joomla.org/tracker/joomla-cms/31400</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 09da9c8607ae990cca5d5fea19b8bc154bf6a407<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31400">issues.joomla.org/tracker/joomla-cms/31400</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31400">issues.joomla.org/tracker/joomla-cms/31400</a>.</sub>

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
