### PR TITLE
[4.0] Smart Search: Fixing ordering, order direction and disabled button

### PR DESCRIPTION
**Pull request by Hackwar**
This again fixes several issues in Smart Search:
- This adds the GUI option to sort also by title, besides relevance and the other options. The code was already in the model, but not accesible by GUI.
- The ordering itself was broken and could not be influenced by the URI. A URL parameter was handed over, but never read.
- #18358 Simply said, I don't really understand why we should add the class "disabled" to a button just because the search is empty. The button still works the same as without that class and thus I'm rather removing this altogether.
- The name from the button is removed, thus reducing the number of URL parameters.

Only works when #29428 is merged.

### CODE REVIEW

**Comment by Quy** [comment]
Add option to Global Configuration > Smart Search.

**Comment by Quy** [comment]
> PHP Warning:  mysqli_stmt::bind_param(): Number of variables doesn't match number of parameters in prepared statement in \libraries\vendor\joomla\database\src\Mysqli\MysqliStatement.php on line 420

```
() | JROOT\components\com_finder\src\View\Search\HtmlView.php:146
-- | --
2 | Joomla\Component\Finder\Site\View\Search\HtmlView->display() | JROOT\libraries\src\MVC\Controller\BaseController.php:691
3 | Joomla\CMS\MVC\Controller\BaseController->display() | JROOT\components\com_finder\src\Controller\DisplayController.php:59
4 | Joomla\Component\Finder\Site\Controller\DisplayController->display() | JROOT\libraries\src\MVC\Controller\BaseController.php:729
5 | Joomla\CMS\MVC\Controller\BaseController->execute() | JROOT\libraries\src\Dispatcher\ComponentDispatcher.php:146
6 | Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch() | JROOT\libraries\src\Component\ComponentHelper.php:384
7 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT\libraries\src\Application\SiteApplication.php:201
8 | Joomla\CMS\Application\SiteApplication->dispatch() | JROOT\libraries\src\Application\SiteApplication.php:240
9 | Joomla\CMS\Application\SiteApplication->doExecute() | JROOT\libraries\src\Application\CMSApplication.php:231
10 | Joomla\CMS\Application\CMSApplication->execute() | JROOT\includes\app.php:63
11 | require_once() | JROOT\index.php:36
```

**Comment by Hackwar** [comment]
> 
> 
> > PHP Warning:  mysqli_stmt::bind_param(): Number of variables doesn't match number of parameters in prepared statement in \libraries\vendor\joomla\database\src\Mysqli\MysqliStatement.php on line 420
> 

As I wrote, this PR doesn't work without the other PR being merged. This has happened in the meantime. This PR has been updated. Please test again.

**Comment by Quy** [comment]
Installed sample testing data.
Set Title for Sort Field.
Search results are not sorted by title.

**Comment by Hackwar** [comment]
@Quy should work now. Please test again.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on bb2b68801c87ce4c518a4240f88f9a81c9ebad8f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29474">issues.joomla.org/tracker/joomla-cms/29474</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on bb2b68801c87ce4c518a4240f88f9a81c9ebad8f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29474">issues.joomla.org/tracker/joomla-cms/29474</a>.</sub>

**Comment by jwaisner** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29474">issues.joomla.org/tracker/joomla-cms/29474</a>.</sub>

**Comment by richard67** [comment]
Thanks!

**Pull request merged**
