### PR TITLE
[4.0] Fix JS error in codemirror

### PR DESCRIPTION
**Pull request by C-Lodder**
Pull Request for Issue comment in https://github.com/joomla/joomla-cms/issues/28211#issuecomment-594197682

### Summary of Changes

Note: This does NOT close the issue above, it's just a fix.

In JS, you cannot call a static function from within the instance using `this.foo()`.

### Testing Instructions

1. Go to the Plugin manager
2. Open the Codemirror plugin and navigate to the "Appearance" tab
3. Click anywhere in the gutter (within red box in screenshot below)
screeny

### Expected result

Clicking the gutter should add a dot marker

### Actual result

JS error

### CODE REVIEW

**Comment by brianteeman** [comment]
I "guess" the issue arose when the code was converted from jquery in j3 to es6 here

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on fff28f63b1efea23915fc86ad05037592b9298d7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28696">issues.joomla.org/tracker/joomla-cms/28696</a>.</sub>

**Comment by BertaOctech** [comment]
I have tested this item :red_circle: unsuccessfully on fff28f63b1efea23915fc86ad05037592b9298d7<br /><br />I got the js error mentioned at https://github.com/joomla/joomla-cms/issues/28211#issuecomment-594197682 when making click on the grey area just next to the code 

When I tried to apply this patch from the patch tester, I got the following error

>The patch could not be applied because it would break the site. Check the pull request to see if it is up-to-date.

I was using Patch Tester component version 4.0.0-rc2 	04-April-2020 

My Joomla version is Joomla version, ‎4.0.0-beta1-dev. 

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28696">issues.joomla.org/tracker/joomla-cms/28696</a>.</sub>

**Comment by C-Lodder** [comment]
@BertaOctech You need to run `node build.js --compile-js` from your terminal before testing

 Sorry I should have mentioned that before

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on fff28f63b1efea23915fc86ad05037592b9298d7<br /><br />No JS error now.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28696">issues.joomla.org/tracker/joomla-cms/28696</a>.</sub>

**Comment by jwaisner** [comment]
Looks like some drone errors. @C-Lodder can you look into those? They may be expected and not related to this PR.

**Comment by brianteeman** [comment]
They will probably be fixed if you update your branch to include the recent commit from George

**Comment by C-Lodder** [comment]
Merged 4.0-dev into my branch. No idea why Drone is still failing for MySQL tests, but not something I can do anything about as this PR only changes a JS file

**Comment by jwaisner** [comment]
Looks like the drone errors are not related to this PR. It is calling out a connectivity problem with Webdriver. I will retest just to confirm it works as expected.

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 1d78157f2573fbaaf413f7014f1cd2aee720ab71<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28696">issues.joomla.org/tracker/joomla-cms/28696</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28696">issues.joomla.org/tracker/joomla-cms/28696</a>.</sub>

**Comment by wilsonge** [comment]
Thanks. Drone failed to start the webdriver itself.

**Pull request merged**
