### PR TITLE
com_associations long titles

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #22522 .
### Steps to reproduce the issue
- create an article with a long name such as "A very very very very long loooooooooooooooooooooooooooooong long title and long alias will not wrap in com_associations"
- leave Alias blank and assign to a language
- save and search for it in com_associations

### Expected result
Text wrap the same as com_content

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 43e4d695c6c2d55e423ce347b32060c194043266<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22523">issues.joomla.org/tracker/joomla-cms/22523</a>.</sub>

**Comment by jsubri** [comment]
I have tested this item :white_check_mark: successfully on 43e4d695c6c2d55e423ce347b32060c194043266<br /><br />working perfect.
Thank you<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22523">issues.joomla.org/tracker/joomla-cms/22523</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22523">issues.joomla.org/tracker/joomla-cms/22523</a>.</sub>

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
