### PR TITLE
[4.2] Remove duplicate WebAssetManager

### PR DESCRIPTION
**Pull request by heelc29**
### Summary of Changes

Remove duplicate access to WebAssetManager

Caused by conflicts in #36591 due #36373

### Testing Instructions

- open articles: test multiselect
- open featured articles: test multiselect
- open menues: test multiselect and site reload after position modal closed
- open scheduler: test multiselect, test run and display failed task

### Actual result BEFORE applying this Pull Request

Everything works

### Expected result AFTER applying this Pull Request

Everything works

### Documentation Changes Required

None

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 8331a2b105045ed5f261aa8765eb66b858244133<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37379">issues.joomla.org/tracker/joomla-cms/37379</a>.</sub>

**Comment by richard67** [comment]
@Quy Have you tested by review?

I ask because it seems the multiselect feature seems to be broken in 4.2 (and maybe previous 4.x) compared to 3.

On J3 when I check one item's check box e.g. in the articles list and then check another one with pressed shift key, all items in the list between these 2 are selected, too. That's how I understand that it shall work according to the comment in file "build/media_source/system/js/multiselect.es6.js".

But on my 4.2 here this does not work, not without this PR and not with this PR.

By review this PR is ok to me, and it also does not change that broken behaviour.

**Comment by richard67** [comment]
See also #25500 .

**Comment by richard67** [comment]
@heelc29 How did you test yourself the "test multiselect" parts in your testing instructions? I'm asking because it seems that it doesn't work as it should in J4 (regardless of this PR here which is right).

On J3 I select an item in a list and then with pressed shift key I select another one more up or down in the list and not just the next or previous one, and then all items between the first and the 2nd selection get selected, too.

On J4 this seems not to work anymore.

So how did you test that? Did you just test that the "select all" check box still works?

Am only asking to understand that issue better. Nothing wrong with your PR here.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 8331a2b105045ed5f261aa8765eb66b858244133<br /><br />Code review: The PR is right.

Real test: Multiselect seems to be broken in J4, see my previous comments. This PR doesn't change anything on that and so does not break anything further.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37379">issues.joomla.org/tracker/joomla-cms/37379</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37379">issues.joomla.org/tracker/joomla-cms/37379</a>.</sub>

**Comment by heelc29** [comment]
> @heelc29 How did you test yourself the "test multiselect" parts in your testing instructions?

@richard67 I click somewhere in the row and check if the checkbox will go to checked. 

> On J3 I select an item in a list and then with pressed shift key I select another one more up or down in the list and not just the next or previous one, and then all items between the first and the 2nd selection get selected, too.

This feature I've not known until yet ;)

**Comment by brianteeman** [comment]
@richard67 multiselect has been broken since the beginning of j4 alpha. I opened an issue for it at the time. https://github.com/joomla/joomla-cms/issues/25500

**Comment by richard67** [comment]
> @richard67 multiselect has been broken since the beginning of j4 alpha. I opened an issue for it at the time. #25500

@brianteeman Yes, I have noticed that meanwhile.

**Comment by fancyFranci** [comment]
Thank you :)

**Pull request merged**
