### PR TITLE
[4.0] Move options from grid to column layout

### PR DESCRIPTION
**Pull request by ciar4n**
Pull Request for Issue #27136.

### Summary of Changes
This PR creates some column-count classes and applies them to the `joomla.edit.params` layout.

Basically means that fields get ordered vertically (J3) instead of horizontally which is the case when using grid.

If this gets merged then I will apply on all other forms.

### Testing Instructions
Apply this patch and run node build.js --compile-css for updating the changed SCSS. Alternatively, you can run npm i.

Navigate to article edit -> Options tab

### Before PR
o4grXhrkUc

### WIth PR
iydq12lHd0

### CODE REVIEW

**Comment by brianteeman** [comment]
THANK YOU

**Comment by Quy** [comment]
Go to Content >Categories 
Edit Uncategorised
Go to Options
Select is in the next column

**Comment by ciar4n** [comment]
Thx @Quy. That should be ok now.

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on c746736429c2b085278f38ff9b81df6700a52329<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27141">issues.joomla.org/tracker/joomla-cms/27141</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on c746736429c2b085278f38ff9b81df6700a52329<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27141">issues.joomla.org/tracker/joomla-cms/27141</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27141">issues.joomla.org/tracker/joomla-cms/27141</a>.</sub>

**Comment by Quy** [comment]
Administrator Template Styles > autum > Image Settings

27141a

**Comment by ciar4n** [comment]
@Quy Should be ok now. XML update so no need to recompile css.

**Comment by Quy** [comment]
> If this gets merged then I will apply on all other forms.

Is this related to my last comment?

The before and after look differently. Is this the expected behavior?

27141-before

27141-after

**Comment by ciar4n** [comment]
> Is this related to my last comment?

There is another 60+ files that use the current grid based forms. A follow-up PR would apply the changes here across all such files and remove the old grid based forms CSS. The Atum XML from your last comment was created for the grid based forms so the field order was different. Most XMLs have been created with the column based forms used in Joomla 3 and therefore should be better suited to the changes here.

> The before and after look differently. Is this the expected behavior?

Yes. There will be differences. Currently, forms are placed in a grid so forms are inline with each other both vertically and horizontally. This PR changes forms to a column layout.

#### Grid layout...

image

#### Column layout...
image

Look at any multi-column form outside of Joomla and they will always be in a column layout and read vertically, never a grid.

**Comment by wilsonge** [comment]
Thanks @ciar4n happy to move onto doing this elsewhere

**Comment by ciar4n** [comment]
Thank you for the tests.

**Comment by ciar4n** [comment]
To complete I need some tests on #27141. Otherwise, this should be reverted.

**Comment by wilsonge** [comment]
That got merged two months ago?

**Comment by ciar4n** [comment]
Ah sorry .. wrong pr... this one.. #27153

**Pull request merged**
