### PR TITLE
[4.0] [mod_multilangstatus] Improvements

### PR DESCRIPTION
**Pull request by C-Lodder**
### Summary of Changes

This is for the administrator menu module

- Use namespaced classes everywhere
- Remove jQuery call
- Add minified file

### CODE REVIEW

**Comment by C-Lodder** [comment]
@infograf768 - Does this directory need to be here?

> administrator\modules\mod_multilangstatus\language\en-GB

If not I'll remove it in this PR

**Comment by dgrammatiko** [comment]
Add the non minified js file

**Comment by C-Lodder** [comment]
@dgt41 - It already exists. The minified file was just missing

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 714f20f046da3ce9104ce2600cbd0b4466da1286<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18947">issues.joomla.org/tracker/joomla-cms/18947</a>.</sub>

**Comment by infograf768** [comment]
@C-Lodder 

> If not I'll remove it in this PR

I guess you can. In 2.5 we added this to demonstrate the possibility of settings a language folder in an extension root.
If you do, then also modify the xml which contains `<folder>language</folder>`

Note: we should keep these extension language folders imho for templates as they could be deleted and re-installing them would not reinstall the language strings.

**Comment by infograf768** [comment]
Test OK here btw. At last it works 👍

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
