### PR TITLE
[4.0] Changelogurl: modify conditional

### PR DESCRIPTION
**Pull request by infograf768**
Pull Request for Issue https://github.com/joomla/joomla-cms/pull/25311#issuecomment-506706427

### Summary of Changes
Mofifying conditional as it is preferred

### Testing Instructions
See https://github.com/joomla/joomla-cms/pull/2531
The result should be the same.

@hgh-esn @wilsonge

### CODE REVIEW

**Comment by hgh-esn** [comment]
we also should  change the `<?php if ($item->version !== '') : ?>`  to ` if (!emtly(`$item->version)) : ?>` or **better delete the whole statement**
```
<?php if ($item->version !== '') : ?>`
........ **this code must stay !**
<?php else :
     echo '&#160;';
endif; ?>
```
because we do not do anything with  `$item->version ` except that we display its value.

**Comment by infograf768** [comment]
version is out of this scope. It works fine as is. If you are not happy with that please propose a new PR where the decision can be taken to modify or not. I do not see the need for it personally (The version should be displayed even if there is no changelog url)

Therefore please test this PR which is limited to changelogurl following the discussion we had formerly.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 6d9ca8dfd08e0a39497c5e254f0d9d6f4ccbf073<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25363">issues.joomla.org/tracker/joomla-cms/25363</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by hgh-esn** [comment]
I have tested this item :white_check_mark: successfully on 6d9ca8dfd08e0a39497c5e254f0d9d6f4ccbf073<br /><br />It works as expected. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25363">issues.joomla.org/tracker/joomla-cms/25363</a>.</sub>

**Pull request merged**
