### PR TITLE
[4.0] Remove deprecated lang stings

### PR DESCRIPTION
**Pull request by zero-24**
Pull Request for Joomla 4
### Summary of Changes

Remove the language strings as per comment on the ini files.
### Testing Instructions

Code review
### Documentation Changes Required

None

### CODE REVIEW

**Comment by brianteeman** [comment]
@zero-24 this has broken com_banners clients http://localhost/github-joomla-cms/administrator/index.php?option=com_banners&view=clients

So either the strings were still being used or more likely when @wilsonge created the 4.0 branch he missed the PR that renamed those strings

**Comment by Bakual** [comment]
Actually I think the PR which replaced the values wasn't perfect and missed that place. Shame on the writer of that PR (https://github.com/joomla/joomla-cms/pull/8300)

**Comment by zero-24** [comment]
no problem i'm on it enjoy your holiday :) @Bakual

**Comment by Bakual** [comment]
I'm not yet on holidays, one day to go 😄

**Comment by Bakual** [comment]
#12209 should fix that.

**Pull request merged**
