### PR TITLE
Update web.config.txt

### LINKED ISSUE #6392: web.config
The file web.config is missing the `</location>` on it.
I think.

### PR DESCRIPTION
**Pull request by brianteeman**
This adds a missing  location tag and fixes #6392 

I tested the syntax and validity of the web.config.txt using https://webconfigtransformationtester.apphb.com/

### CODE REVIEW

**Comment by patrickzemke** [comment]
Test confirmed - location tag is addeted<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6398">issues.joomla.org/joomla-cms/6398</a>.</sub>

**Comment by tecpromotion** [comment]
Test confirmed - location tag is closing at the end.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6398">issues.joomla.org/joomla-cms/6398</a>.</sub>

**Comment by knoby2015** [comment]
/location tag is in<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6398">issues.joomla.org/joomla-cms/6398</a>.</sub>

**Comment by continga** [comment]
Test confirmed - location closing tag is added

**Comment by Bakual** [comment]
Thanks all!

**Comment by Yorgoz** [comment]
closed

**Pull request merged**
