### PR TITLE
[5.1] Convert mod_post_installation_messages to service provider

### PR DESCRIPTION
**Pull request by joomlaweby**
### Summary of Changes

Converts the administrator post installation messages module to service provider.

### Testing Instructions

1. Make sure you have administrator module mod_post_installation_messages published and have some not hidden post installation messages - click on Reset messages button in Post Installation Messages component
2. You should see module output in administrator area

mod_post_installation_messages

### Actual result BEFORE applying this Pull Request

Module works as expected

### Expected result AFTER applying this Pull Request

Module works same way as before applying pull request

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by sandewt** [comment]
I have tested this item :white_check_mark: successfully on 6a3a01c58170524aeeb4b8df441564c133096eee<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42987">issues.joomla.org/tracker/joomla-cms/42987</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 6a3a01c58170524aeeb4b8df441564c133096eee<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42987">issues.joomla.org/tracker/joomla-cms/42987</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42987">issues.joomla.org/tracker/joomla-cms/42987</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
