### PR TITLE
[4.0 dev] : added a test to JHighlighter

### PR DESCRIPTION
**Pull request by yasirunilan**
Pull Request for Issue # .

### Summary of Changes
Added a javascript test to unhighlight method of JHighlighter library

### Actual result
Code coverage increment

### CODE REVIEW

**Comment by C-Lodder** [comment]
Drone tests are failing. You've mispelled the function name. 

Change:

```
highlighter.unhighlights("textarea");
```
to:
```
highlighter.unhighlight("textarea");
```

**Comment by yvesh** [comment]
@yasirunilan can you look into this? :-) Thanks

**Comment by yasirunilan** [comment]
@C-Lodder @yvesh  I will look into this and commit again 👍

**Review by C-Lodder — APPROVED** [review]

**Comment by yasirunilan** [comment]
@C-Lodder this can be merged right?

**Review by dgrammatiko — APPROVED** [review]

**Pull request merged**
