### PR TITLE
Check if com_fields is installed

### PR DESCRIPTION
**Pull request by Bakual**
Pull Request for Issue #15401 .

### Summary of Changes
Simple fix to prevent the message `Warning Error loading component: com_fields, Component not found.` from showing.
It doesn't necessary fix the potential underlying issue that com_fields isn't installed

### Testing Instructions
If you got that message after updating, apply this PR and the message is gone

### Documentation Changes Required
None

### CODE REVIEW

**Comment by mbabker** [comment]
Can you do this so `JComponentHelper::isInstalled('com_fields')` is only called once?  `JComponentHelper::isInstalled()` doesn't cache results so this in effect is adding two duplicate database queries to every admin page load right now, putting it in a variable at least brings it down to one non-duplicate (at least generated by this source).

**Comment by zero-24** [comment]
In oder to fix the drone error and the comment by michael what about using: `$fields   = JComponentHelper::isInstalled('com_fields') && JComponentHelper::isEnabled('com_fields');`

And later: `if ($fields && JComponentHelper::getParams('com_users')->get('custom_fields_enable', '1'))` or `if ($fields && JComponentHelper::getParams('com_content')->get('custom_fields_enable', '1'))`

**Comment by Bakual** [comment]
Done. I've chosen a different variable name so it's more clear.

**Comment by zero-24** [comment]
:+1: Can you get that in 3.7.0 @rdeutz ?

**Comment by rdeutz** [comment]
@zero-24 did you test if it works?

**Comment by rjcf18** [comment]
I have tested this item :white_check_mark: successfully on f61d85bb2489bfc0b28e9a26867da41f19a97f8f<br /><br />Seems to have fixed the message that appears after updating.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15465">issues.joomla.org/tracker/joomla-cms/15465</a>.</sub>

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on f61d85bb2489bfc0b28e9a26867da41f19a97f8f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15465">issues.joomla.org/tracker/joomla-cms/15465</a>.</sub>

**Comment by zero-24** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15465">issues.joomla.org/tracker/joomla-cms/15465</a>.</sub>

**Comment by zero-24** [comment]
yes @rdeutz<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15465">issues.joomla.org/tracker/joomla-cms/15465</a>.</sub>

**Comment by mcintyro** [comment]
I did the production upgrade to 3.7.0 from 3.6.5 and I have this warning on my admin console.  The update was delivered using the Joomla Updater - I am not a developer so not sure if this issue was expected in 3.7.0 production or how to resolve it.

**Comment by l-arnold** [comment]
Ditto to Mcintyro above  "production upgrade to 3.7.0 from 3.6.5"

Coupled with this I suspect FlexiContent is also problmatic with new com_fields behavior  Basically I cannot find any "com_fields" but Joomla keeps giving the error:

> Warning
> Error loading component: com_fields, Component not found.

**Pull request merged**
