### PR TITLE
[4.0] Change global configuration icon

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
Match global configuration icon with icon in dashboard.

### Testing Instructions
Click Global Configuration icon in dashboard,
See slider icon.
Click Articles under Component.
See slider icon.
Apply PR.
Repeat steps.
See cog icon.

### Actual result BEFORE applying this Pull Request
gc-slider

### Expected result AFTER applying this Pull Request
gc-cog

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on b9379aa014c2d6f32cf1241f2f6f8fb93d0b1115<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33747">issues.joomla.org/tracker/joomla-cms/33747</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on b9379aa014c2d6f32cf1241f2f6f8fb93d0b1115<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33747">issues.joomla.org/tracker/joomla-cms/33747</a>.</sub>

**Comment by chmst** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33747">issues.joomla.org/tracker/joomla-cms/33747</a>.</sub>

**Comment by drmenzelit** [comment]
Thanks

**Pull request merged**
