### PR TITLE
Calendar fixes

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/13166.

### Summary of Changes
- Add one more class
- Remove some useless padding in the css
- Drop the vanilla word from the filenames (css and js) 
 
### Testing Instructions
Apply the test and try the calendar (e.g. article edit

### Preview:
LTR
screen shot 2016-12-14 at 16 49 47
screen shot 2016-12-14 at 16 50 10

RTL
screen shot 2016-12-14 at 16 51 10
screen shot 2016-12-14 at 16 51 28

### Documentation Changes Required

---
This change is [Reviewable](https://reviewable.io/reviews/joomla/joomla-cms/13181)

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
@dgt41 didn't test this, but can't we get a better color than this lime fluorescent green ... ?

**Comment by dgt41** [comment]
Sure, any suggestion?

**Comment by andrepereiradasilva** [comment]
will not make any proposal, desing is really not by strong ... just think this lime is not good because flurescent colors in screend are very bright
Maybe @ciar4n can do a color proposal :wink:

**Comment by ciar4n** [comment]
@andrepereiradasilva I'll do a general style clean up once @dgt41 is happy with the rest!  😄 

@dgt41 Did you have a chance to look at the colspan count in the time tr when there is no 'wk' column..

```
<tr class="time">
	<td class="time time-title" colspan="1">Time:</td>
	<td class="time hours-select" colspan="2"> .. </td>
	<td class="time minutes-select" colspan="2"> .. </td>
	<td class="time ampm-select" colspan="3"> </td>
</tr>
```


All colspan should total 7 not 8. This would allow us to fix the un-even column widths.

**Comment by dgt41** [comment]
@ciar4n the colspan is fixed!

**Comment by ciar4n** [comment]
@dgt41 Cool.. should get a chance to look at this tomorrow.

**Comment by ciar4n** [comment]
@dgt41 Could you checkout https://github.com/dgt41/joomla-cms/pull/46

calendar1

**Comment by schnuti** [comment]
Did I miss something? I installed staging from 2016-12-12 + patch 13153 and this 13181.
Result is that the top of the pop-up is missing.  Screen size 1366x768 - Firefox.
created-date
start-publishing

**Comment by ciar4n** [comment]
@schnuti Nothing missed.. you have highlighted a potential issue.

The calendar displays above the field if there is not enough space in the viewport to display below it...

3cb30b6b25f8cd6e8ebf56b7f92e1b96

@dgt41 Would it be possible to disable this in the JS? Appears to be adding a minus margin-top if the space below is not available. If not you could override it with CSS...


```
.js-calendar {
    margin-top: 0 !important;
}
```

**Comment by dgt41** [comment]
@ciar4n I can revert that part or even better improve it so that the calendar actually moves within the given viewport (?)

**Comment by infograf768** [comment]
Here the display above happens when one has increased the window size and did not reload the page. After reload, the calendar displays normally.

**Comment by schnuti** [comment]
My screenshots above come from my "normal" full screen Firefox. (Bootstrap is not collapsed) I now tested to enlarge the viewport. After clicking CTRL + - three (3) times and page reload, the pop-ups appears in full below the fields. 

In frontend (Protostar as is) "Create Article" shows the "Start Publishing" above and "Finish Publishing" below the field.  "Finish Publishing" enlarges the scrollable area. A trick is, that you can't scroll by clicking the scrollbar. By using the mouse-wheel I can scroll down (or up) to see the pop-up in full.

**Comment by ciar4n** [comment]
@dgt41 Personally I wouldn't be a fan of moving the calendar with the viewport. My reasoning been that if a user decides to scroll while the calendar is opened, one can only presume that the calendar is no longer their focus.

A solution to the issue would be to only display the calendar above the field if the space is not available within the entire page rather than just the viewport.

**Comment by PhilETaylor** [comment]
I have tested this item :white_check_mark: successfully on deacf6f73e23b75f2d0ff26f1a4a23901049272c<br /><br />This fixes the issue I reported in #13166 

Just one note, when I click "Today" I would assume I would be taken to today, highlighted, and the calendar stay open. It closes. This is against my expectation, dunno if others think that way though. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13181">issues.joomla.org/tracker/joomla-cms/13181</a>.</sub>

**Comment by anibalsanchez** [comment]
I have tested this item :white_check_mark: successfully on deacf6f73e23b75f2d0ff26f1a4a23901049272c<br /><br />Test OK<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13181">issues.joomla.org/tracker/joomla-cms/13181</a>.</sub>

**Comment by jeckodevelopment** [comment]
@dgt41 can you please look at the conflicts?

**Comment by dgt41** [comment]
@jeckodevelopment done

**Comment by genesisfan** [comment]
I have tested this item :white_check_mark: successfully on 6c78362549e50e152d7e4debdfe7d981dfdba532<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13181">issues.joomla.org/tracker/joomla-cms/13181</a>.</sub>

**Comment by jeckodevelopment** [comment]
again conflicts Dimitris!

**Comment by bertmert** [comment]
I have tested this item :red_circle: unsuccessfully on 6c78362549e50e152d7e4debdfe7d981dfdba532<br /><br />I cannot set year of Created Date. Zoom is 100%.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13181">issues.joomla.org/tracker/joomla-cms/13181</a>.</sub>

**Comment by laoneo** [comment]
@bertmer, I can't reproduce the issue. Did you try it with the latest staging?

image

**Comment by ciar4n** [comment]
If there is not enough space in the viewport below the field, the calendar position flips to above it.

@dgt41 I think disabling this is the way to go. At least then the calendar will always be accessible even thou in some cases the user may have to scroll.

**Comment by dgt41** [comment]
@ciar4n we discussed this in London, so shall I change the position to relative and the calendar will expand below the input?

**Comment by ciar4n** [comment]
Only issue there is your effecting the remaining content of the page which may cause some random issues depending on the content following the calendar field.

**Comment by dgt41** [comment]
@ciar4n ehm, having the input field always visible narrows down the possible solutions

**Comment by ciar4n** [comment]
@dgt41 Agreed

That considered, I feel simply disabling the flip is the best option so the calendar always displays below. It is expected behavior and would resolve the issue of the calendar ever been inaccessible outside of the viewport.

**Comment by schnuti** [comment]
Quote
> I think disabling this is the way to go. At least then the calendar will always be accessible even thou in some cases the user may have to scroll.

Be still aware that **clicking** the scrollbar closes the pop-up and any expanded part of the viewport. i.e. If there is not enough space in the viewport **below** the field the user has to use alternative scrolling methods. If available - mouse wheel or ...?

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on fb315d93bc8bf4341753d64bf92ef7419d64d468<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13181">issues.joomla.org/tracker/joomla-cms/13181</a>.</sub>

**Comment by rmittl** [comment]
I have tested successfully ✅in different browser and size windows.

**Comment by widmann-it** [comment]
I have tested this item :white_check_mark: successfully on fb315d93bc8bf4341753d64bf92ef7419d64d468<br /><br />We have testet succesfully on Firefox and Chrome on Windows and Linux 
testet by jc17de<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13181">issues.joomla.org/tracker/joomla-cms/13181</a>.</sub>

**Comment by csthomas** [comment]
Please fix travis error.
1) JHtmlTest::testCalendar

Line:1509 JS file "calendar-vanilla.min.js" should be loaded
Failed asserting that an array has the key '/media/system/js/fields/calendar-vanilla.min.js'.
/home/travis/build/joomla/joomla-cms/tests/unit/suites/libraries/cms/html/JHtmlTest.php:1510

**Comment by rdeutz** [comment]
I fixed the test

**Comment by csthomas** [comment]
Great

**Comment by dgt41** [comment]
Thanks @rdeutz, somehow I messed one of the rebases

**Pull request merged**
