### PR TITLE
Fix a bug of web assets file joomla.asset.json registration/parsing

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue #41421 .

### Summary of Changes

Make sure that all registry files is parsed, before doing any action.

### Testing Instructions
Please follow #41421

### Actual result BEFORE applying this Pull Request
Asset missing

### Expected result AFTER applying this Pull Request
All works

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: 
- [x] No documentation changes for docs.joomla.org needed
- [ ] Pull Request link for manual.joomla.org: 
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by HLeithner** [comment]
This pull request has been automatically rebased to 4.4-dev.

**Comment by JonasAtZwetschke** [comment]
I have tested this item :white_check_mark: successfully on bfdc471d2caa0fad3d06439a65262a3a241afd71<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41431">issues.joomla.org/tracker/joomla-cms/41431</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on bfdc471d2caa0fad3d06439a65262a3a241afd71<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41431">issues.joomla.org/tracker/joomla-cms/41431</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41431">issues.joomla.org/tracker/joomla-cms/41431</a>.</sub>

**Pull request merged**
