### PR TITLE
[4.1] spelling identifer/identifier

### PR DESCRIPTION
**Pull request by brianteeman**
code review

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 83061e889428f9dba75073fa000dcf7ad0125bd7<br /><br />review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38055">issues.joomla.org/tracker/joomla-cms/38055</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 83061e889428f9dba75073fa000dcf7ad0125bd7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38055">issues.joomla.org/tracker/joomla-cms/38055</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38055">issues.joomla.org/tracker/joomla-cms/38055</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
