### PR TITLE
Add ability to refresh cached JTable fields (getFields patch)

### PR DESCRIPTION
**Pull request by alex7r**
#### Summary of Changes

Add ability to refresh cached JTable fields
#### Testing Instructions

No built-in use cases
But needed in advanced features coding

### CODE REVIEW

**Comment by alex7r** [comment]
Will some one looks at this and say something?

**Comment by brianteeman** [comment]
I guess that the people you need to review this have all been really busy
the last few weeks preparing the release of 3.6

**Comment by ggppdk** [comment]
I have tested this item :white_check_mark: successfully on cbe90902663c970fe0e8e3a9c71a7d2306652621<br /><br />Tested this in my software, also various Joomla views

Did a code review too and change is correct.
Did a quick look for Joomla built-in code using the method, none of the method calls is currently passing any parameters, this should be safe change

@alex7r 
About title of this PR:  "JTable getFields patch" Should be changed to ? : "Add ability to refresh cached JTable fields"<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11046">issues.joomla.org/joomla-cms/11046</a>.</sub>

**Comment by alex7r** [comment]
@ggppdk Thanks for testing and reviewing.

Now that 3.6 is released may be this can be merged?

**Comment by brianteeman** [comment]
The general rule is that all PR require at least two tests

**Comment by alex7r** [comment]
Is my test is counting?

**Comment by brianteeman** [comment]
Sadly not - we assume that you wouldnt submit non working code ;)

**Comment by alex7r** [comment]
@brianteeman so it makes 3 Human Tests
Ok, I'll try to bring someone in to test this.

**Comment by timofey-l** [comment]
I've successfully tested this.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11046">issues.joomla.org/joomla-cms/11046</a>.</sub>

**Comment by truptikagathara** [comment]
I have tested this item :white_check_mark: successfully on 4e91e1dc0c9a158bb55c7767eb338f5dbe360700<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11046">issues.joomla.org/joomla-cms/11046</a>.</sub>

**Comment by ggppdk** [comment]
I have tested this item :white_check_mark: successfully on 4e91e1dc0c9a158bb55c7767eb338f5dbe360700<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11046">issues.joomla.org/joomla-cms/11046</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11046">issues.joomla.org/joomla-cms/11046</a>.</sub>

**Comment by wilsonge** [comment]
Merged to the 3.7 branch with https://github.com/joomla/joomla-cms/commit/4c630e582ae86e84be54a769360c4bfdbf11b431 - thanks :)

**Comment by alex7r** [comment]
Well, 2 days before 2 months, pretty quick. =)

**Pull request closed without merging**
