### PR TITLE
Appended input fields

### PR DESCRIPTION
**Pull request by brianteeman**
PR for #12448

## Steps to reproduce the issue

Effects all appended input fields. Eg. Navigate to a single article menu item (Menus -> MainMenu -> Home) and resize the screen below 767px. Input fields extend outside the viewport.

### CODE REVIEW

**Comment by ghost** [comment]
between 481 
screen shot 2018-07-25 at 15 34 36

and ~550:
screen shot 2018-07-25 at 15 34 59
### System information
- 3.8.11-dev
- Template: Protostar
- macOS Sierra, 10.13.6
- Firefox 61 (64-bit)
#### CloudAccess.net
- PHP 7.2.3
- MySQLi 5.7.18-cll-lve

**Comment by brianteeman** [comment]
I think thats a different issue. As you can see at > 480 width the label is on the left but on < 480 the label is on the top

@ciar4n your advice please

**Comment by ciar4n** [comment]
You can probably put the wrapping title input down as expected behavior. There is no reasonable solution to this without refactoring the control-groups or using flex.

**Comment by brianteeman** [comment]
So is this pr good enough? You were the one that raised the issue.

**Comment by ciar4n** [comment]
I have tested this item :white_check_mark: successfully on 82df44bbda509666ea53a0f1b1e44ddfc2ce8fda<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21257">issues.joomla.org/tracker/joomla-cms/21257</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 82df44bbda509666ea53a0f1b1e44ddfc2ce8fda<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21257">issues.joomla.org/tracker/joomla-cms/21257</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
