### PR TITLE
Missing help buttons

### PR DESCRIPTION
**Pull request by brianteeman**
The help button was missing for the options screen of both Scheduled Tasks and Media

Testing is easy. Apply the pr
go to the component and c;lick on options
before this PR thwere is no help button - now there is

Pull Request for Issue #38430

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 254f646a26a3f53d1bb7daf2be97c29acee309bb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38435">issues.joomla.org/tracker/joomla-cms/38435</a>.</sub>

**Comment by Franzwohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 254f646a26a3f53d1bb7daf2be97c29acee309bb<br /><br />@brianteeman thanks for the pr.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38435">issues.joomla.org/tracker/joomla-cms/38435</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38435">issues.joomla.org/tracker/joomla-cms/38435</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
