### PR TITLE
[3.7.x] Subform.Repeatable styling

### PR DESCRIPTION
**Pull request by ciar4n**
### Summary of Changes

A PR to add a small amount of styling to repeatable subforms (joomla.form.field.subform.repeatable). Adds some definition between repeated forms and a slight repainting.
### Testing Instructions

Create ../modules/mod_login/test.xml to which add the following...

```
<?xml version="1.0" encoding="UTF-8"?>
<form>
    <fieldset name="sample" class="sample-subform">
        <field name="image" type="media" default="" label="Sample Field 1"  description="Desc1" size="30" />
        <field name="text" type="text" default="" label="Sample Field 2" description="Desc2" />
        <field name="color" type="color" default="#dddddd" label="Sample Field 2" description="Desc2" />
    </fieldset>
</form>
```

Add the following to the ../modules/mod_login/mod_login.xml file:

```
<field name="subformtest" type="subform" formsource="modules/mod_login/test.xml" class="advancedSelect" min="0" max="50" multiple="true" layout="joomla.form.field.subform.repeatable" groupByFieldset="true" label="Repeatable Subform" description="Desc" />
```

**Before Patch**
repeatable1

**After Patch**
repeatable2

Test with the various options available (https://docs.joomla.org/Subform_form_field_type)
### Documentation Changes Required

None

### CODE REVIEW

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on 34d03a06f1a9ede05359e9032b7c5f5bf24a199a<br /><br />Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12419">issues.joomla.org/tracker/joomla-cms/12419</a>.</sub>

**Comment by coolcat-creations** [comment]
What about something like this:
image
or this: 
image

**Comment by ufuk-avcu** [comment]
I prefer the @coolcat-creations one and especially the full border around the subfields.

**Comment by widmann-it** [comment]
If I look at the three versions I would recommend version 3 version 2 of Elisa

**Comment by chmst** [comment]
I'd prefer te last example (version2 of coolcat). But with a not: the remove and add buttons should be together at the top of the box. Or even at the top and at the bottom. Why? Because a subform can be much linger than these examples. So it might be necessary to scroll from the add- to the remove-button.

**Comment by ciar4n** [comment]
Thank you @coolcat-creations 

There was a number of reasons why opted for such minimal styling, some of which would be... 

1. Keeping subform fields aligned with non subform fields.
2. To much styling may make the forms look a little busy if the subform contained a single field which might often be the case. 
3. Extension developers often add their own styling to their extension settings and considered it best practice to give them a relatively clean canvas to build from.

Obviously these are just my own personal opinions and I would be happy to create a PR with your suggestions (personally I like the your 2nd option) if you feel the above points irrelevant.

@chmst True however IMO for the same reason I would nearly go for having the 'add' at the bottom. Some reasons been...

1. User can visually see the new form been created which would not be the case if the 'add' was at the top of a long subform.
2. If a user is filling out a number of subforms, the 'add' at the bottom keeps the flow downwards rather than having to scroll back up, click 'add' and then down again after each form is filled.

**Comment by coolcat-creations** [comment]
@ciar4n that would be nice if you can do this.
@chmst - yes i have to agree to @ciar4n - when you have the add button at the bottom then you are at the position and in the need to create a new field. I would prefer to have this one at the bottom. And the delete icon at the top because that´s usually the place where you see that you want to delete the item. However if @ciar4n creates a PR with the suggestion we can test the behavior and see if it works good. Thanks everyone!

**Comment by ciar4n** [comment]
I've created an alternative PR (#12634) based on @coolcat-creations second suggestion.

**Comment by coolcat-creations** [comment]
I have tested this item :white_check_mark: successfully on f4a3406cdd48cc113851f0d35954287f72ff10f4<br /><br />Both tested successful (would prefer the other option though)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12419">issues.joomla.org/tracker/joomla-cms/12419</a>.</sub>

**Comment by ciar4n** [comment]
Closed in favor of #12634

**Pull request closed without merging**
