### PR TITLE
[5.2] Fix of unnecessary SQL query for Fields, get the field value already loaded by getFields()

### PR DESCRIPTION
**Pull request by Fedik**
### Summary of Changes

Remove unnecessary SQL query for the custom fields, during the form rendering.
`FieldsHelper::getFields()` load the field value, however `FieldsHelper::prepareForm()` also loading them wthout a reason.
Also removed some dead code.

### Testing Instructions

Enable debug and debug query.
Create a couple of Custom fields, let say 10.
Open article editing.

### Actual result BEFORE applying this Pull Request
Notice amount of query in debug.
Let say 75

### Expected result AFTER applying this Pull Request
The amount of query will be 10 less, 65

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed
- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by crommie** [comment]
I have tested this item :white_check_mark: successfully on 59bd3b70ca77b70223d0e755b8a50cac25debc99<br /><br />Before: 61 queries. After: 51 queries.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42861">issues.joomla.org/tracker/joomla-cms/42861</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 59bd3b70ca77b70223d0e755b8a50cac25debc99<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42861">issues.joomla.org/tracker/joomla-cms/42861</a>.</sub>

**Comment by adj9** [comment]
I have tested this item :white_check_mark: successfully on 59bd3b70ca77b70223d0e755b8a50cac25debc99<br /><br />Its ok Queries have decreased<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42861">issues.joomla.org/tracker/joomla-cms/42861</a>.</sub>

**Comment by chmst** [comment]
shuldn't that go into 4.4?

**Comment by richard67** [comment]
> shuldn't that go into 4.4?

Good question. @Fedik Is the unnecessary query an issue in 4.4, too?

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42861">issues.joomla.org/tracker/joomla-cms/42861</a>.</sub>

**Comment by Fedik** [comment]
>  Is the unnecessary query an issue in 4.4, too?

yeap,

**Comment by Fedik** [comment]
I will do another, later

**Comment by gilou103** [comment]
During PBF 
16 Content Article - Custom fields (my Group), 
before patch 67 queries, after patch 51 queries

**Comment by Fedik** [comment]
I moved to 4.4 branch:
- https://github.com/joomla/joomla-cms/pull/42882

**Comment by richard67** [comment]
I've restored the previous human test results as the PR was closed but then reopened, and there was no change since the successful tests.

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42861">issues.joomla.org/tracker/joomla-cms/42861</a>.</sub>

**Comment by bembelimen** [comment]
I moved it to 5.2 as a decision from maintainer

**Comment by pe7er** [comment]
Thanks @Fedik !

**Pull request merged**
