### PR TITLE
[5.1] Alert links system container [a11y]

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue https://github.com/joomla/joomla-cms/pull/42986#issuecomment-1987360423 .

### Summary of Changes
Adds the alert-link class to the string
Removes the color attribute on the link as it was overriding the specific classes for each type of alert

### Testing Instructions
You must be testing this with the latest branch!!

Go to System->Update sites and disable any update site
Go to System->Updates and check for updates

### Light Mode
image

### Dark Mode
image

### Light Mode
image

### Dark Mode
image

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by coolcat-creations** [comment]
thats strange, thats actually one of my last commits yesterday into the Main PR... Did it went lost?

**Comment by coolcat-creations** [comment]
ok, its confirmed my commit was removed because it did not work so well ;-) I will test yours now

**Comment by coolcat-creations** [comment]
grafik
grafik

**Comment by coolcat-creations** [comment]
In light mode, only the success link looks wrong

grafik

**Comment by bembelimen** [comment]
Thanks @brianteeman for fixing, I broke that thing and missed it (was too late). So will put it in the 5.1.0 milestone, it should be fir sure merged.

**Comment by ceford** [comment]
I can see the link change from plain to underlined. But I see a different colour scheme. I am using a cms clone and did git pull then npm ci; the Status bar shows 5.1.0-beta2-dev; and I use the Firefox Dark/Light mode switcher (on Mac OS). The backgrounds are all (nearly) black. What am I doing wrong?

**Comment by coolcat-creations** [comment]
> I can see the link change from plain to underlined. But I see a different colour scheme. I am using a cms clone and did git pull then npm ci; the Status bar shows 5.1.0-beta2-dev; and I use the Firefox Dark/Light mode switcher (on Mac OS). The backgrounds are all (nearly) black. What am I doing wrong?

best thing is if you download a package here in this PR and install this

**Comment by LadySolveig** [comment]
Thank you @brianteeman

**Pull request merged**
