### PR TITLE
[4.0] Provide empty string as default for empty protected fields when saving configuration.php

### PR DESCRIPTION
**Pull request by richard67**
Pull Request for Issue #31679 .

### Summary of Changes

See title.

### Testing Instructions

See issue #31679 .

### Actual result BEFORE applying this Pull Request

Instant 500 error.

In configuration.php:

```
public $ftp_pass = ;
public $smtppass = ;
public $redis_server_auth = ;
public $session_redis_server_auth = ;
```

### Expected result AFTER applying this Pull Request

Successfully saved.

In configuration.php:

```
public $ftp_pass = '';
public $smtppass = '';
public $redis_server_auth = '';
public $session_redis_server_auth = '';
```

### Documentation Changes Required

None.

### CODE REVIEW

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on 0c2a9c003264bd1377943d2739db5c243992c6b0<br /><br />Tested successfully in Beta6-dev of 17 December.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31683">issues.joomla.org/tracker/joomla-cms/31683</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 0c2a9c003264bd1377943d2739db5c243992c6b0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31683">issues.joomla.org/tracker/joomla-cms/31683</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31683">issues.joomla.org/tracker/joomla-cms/31683</a>.</sub>

**Comment by chmst** [comment]
Thanks!

**Comment by richard67** [comment]
Thanks!

**Pull request merged**
