### PR TITLE
[4.X] Improve media view by making control elements sticky

### PR DESCRIPTION
**Pull request by magnussinger**
Pull Request for Issue #36545

### Summary of Changes
Make the left sidebar and the top bar of the media manager sticky

### Testing Instructions
Install and try to scroll down on the media manager, the control elements will stick to the top

### Actual result BEFORE applying this Pull Request
The control elements will disappear when a user scrolls down

### Expected result AFTER applying this Pull Request
The control elements will stick on top when a user scrolls down so they are accessible everytime

### Documentation Changes Required
None

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 39c2a158ec98fdc81ecb72bc2f79347b27850f0f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37397">issues.joomla.org/tracker/joomla-cms/37397</a>.</sub>

**Comment by richard67** [comment]
@MagnusSinger Please check the scss code style error reported by drone: https://ci.joomla.org/joomla/joomla-cms/52847/1/24

**Comment by magnussinger** [comment]
@richard67 thanks for the hint, I fixed it

**Comment by richard67** [comment]
Thanks. I've restored the previous human test result so it's properly counted since the commits after that were only code style (order of CSS properties) and a clean branch update.

**Comment by magnussinger** [comment]
Thank you

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 4c98174e4a8cbc6c39703fd3898f5825af513dc2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37397">issues.joomla.org/tracker/joomla-cms/37397</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37397">issues.joomla.org/tracker/joomla-cms/37397</a>.</sub>

**Comment by Quy** [comment]
Thank you!

**Pull request merged**
