### PR TITLE
[4.0] Deprecate some component helper classes

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Deprecates some old component helper classes which are now just proxies to namespaced classes.

### Testing Instructions
Code review.

### Documentation Changes Required

IDK.

### CODE REVIEW

**Comment by ChristineWk** [comment]
@SharkyKZ Made Code Review.
The 1st one: successful.
2nd one: Didn't find in /administrator/components/com_users > Model ....<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27603">issues.joomla.org/tracker/joomla-cms/27603</a>.</sub>

**Comment by SharkyKZ** [comment]
There are no changes to `com_users` here.

**Comment by ChristineWk** [comment]
Hm, but when I click to: https://github.com/joomla/joomla-cms/commit/4f37fc6a973041836c976418f6e31bbce382d5d1, thought hv also to check. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27603">issues.joomla.org/tracker/joomla-cms/27603</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 0bc08e529e9ea782b072430dff429f3d42b4cb54<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27603">issues.joomla.org/tracker/joomla-cms/27603</a>.</sub>

**Comment by ChristineWk** [comment]
Sorry, I'm confused now, because I tested this here: https://github.com/joomla/joomla-cms/pull/27603/commits/97afb38aae4448aa6586b4fb08596e8ee1e4bd1b. So I hv to revert the result. My fault.  <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27603">issues.joomla.org/tracker/joomla-cms/27603</a>.</sub>

**Comment by ChristineWk** [comment]
I have not tested this item.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27603">issues.joomla.org/tracker/joomla-cms/27603</a>.</sub>

**Comment by wilsonge** [comment]
Merged on review. Thanks!

**Pull request merged**
