### PR TITLE
[4.0] Fix for #23629

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # .

### Summary of Changes
Self explanatory...

### Testing Instructions
See #23629

### CODE REVIEW

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on b5847ba5218f5afd56ca29014319c7b7da98d621<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23642">issues.joomla.org/tracker/joomla-cms/23642</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on b5847ba5218f5afd56ca29014319c7b7da98d621<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23642">issues.joomla.org/tracker/joomla-cms/23642</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23642">issues.joomla.org/tracker/joomla-cms/23642</a>.</sub>

**Comment by wilsonge** [comment]
Codestyle fix please

**Comment by dgrammatiko** [comment]
@wilsonge done

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
