### PR TITLE
[4.1] s/componets/components

### PR DESCRIPTION
**Pull request by brianteeman**
typo

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on c7313dc7035365ee0824b30b14190d90f52c6de2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36830">issues.joomla.org/tracker/joomla-cms/36830</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on c7313dc7035365ee0824b30b14190d90f52c6de2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36830">issues.joomla.org/tracker/joomla-cms/36830</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36830">issues.joomla.org/tracker/joomla-cms/36830</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Comment by brianteeman** [comment]
thank you

**Pull request merged**
