### PR TITLE
[4.0] CORS description …

### PR DESCRIPTION
**Pull request by brianteeman**
This is one of those where we do need a description as CORS is a pretty new thing that most people are not familiar with yet.
The PR also standardises the language keys

You will find this option in the global configuration

image

### CODE REVIEW

**Comment by Quy** [comment]
I have not tested this item.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33039">issues.joomla.org/tracker/joomla-cms/33039</a>.</sub>

**Comment by richard67** [comment]
> I have not tested this item.

@Quy Just forgotten to check the result before submitting? Or something wrong here?

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 9ed852362889a93e3db9465857938ce346d06dbe<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33039">issues.joomla.org/tracker/joomla-cms/33039</a>.</sub>

**Comment by Quy** [comment]
I must have selected the wrong choice. Fixed. Thanks.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 9ed852362889a93e3db9465857938ce346d06dbe<br /><br />Agree having a description here is useful.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33039">issues.joomla.org/tracker/joomla-cms/33039</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33039">issues.joomla.org/tracker/joomla-cms/33039</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33039">issues.joomla.org/tracker/joomla-cms/33039</a>.</sub>

**Comment by brianteeman** [comment]
thank you

**Pull request merged**
