### PR TITLE
[4.0] fix notice in httpheaders plugin

### PR DESCRIPTION
**Pull request by zero-24**
### Summary of Changes

fix notice in httpheaders plugin cc @wilsonge should be obvious on code review.

### CODE REVIEW

**Comment by Quy** [comment]
I get the following in the back end:

> Warning: hash() expects parameter 2 to be string, array given in \plugins\system\httpheaders\httpheaders.php on line 165

**Comment by zero-24** [comment]
hmm it seams something different is happening here: 

https://github.com/joomla/joomla-cms/blob/4.0-dev/plugins/system/httpheaders/httpheaders.php#L154-L178

That results into `$scriptContent` or `$styleContent` to be an array but i would like to keep that of for now. Can you please create an issue for that?

An fix could be to check that `$scriptContent` is an array and than do a loop over them to generate the hashes.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 7ea19508be04103f24ddf3019ba61825a3b9a4e9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28318">issues.joomla.org/tracker/joomla-cms/28318</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 7ea19508be04103f24ddf3019ba61825a3b9a4e9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28318">issues.joomla.org/tracker/joomla-cms/28318</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28318">issues.joomla.org/tracker/joomla-cms/28318</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
