### PR TITLE
[4.1] Fields - before display what

### PR DESCRIPTION
**Pull request by brianteeman**
Working with fields some of the automatic display options are meaningless

After Title - ok
Before Display - of what?
After Display - of what?
Do not automatically display - ok

This PR adds some more clarity to the options.

_yes i know that fields are used in contact etc as well as content but the event in code is still beforeDisplayContent_

## Before
image

## After
image

### CODE REVIEW

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on 0dedc75e3f476c21697f373f71ea85449da8e37d<br /><br />Tested successfully in Joomla 4.1.3-dev of 29 April.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37689">issues.joomla.org/tracker/joomla-cms/37689</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 0dedc75e3f476c21697f373f71ea85449da8e37d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37689">issues.joomla.org/tracker/joomla-cms/37689</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37689">issues.joomla.org/tracker/joomla-cms/37689</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
