### PR TITLE
update doc block

### PR DESCRIPTION
**Pull request by brianteeman**
Small update to fix a copy/past error in the doc blok

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on b10289185f4fe94aa0ca1503d4ae2eb7039a99d3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12569">issues.joomla.org/tracker/joomla-cms/12569</a>.</sub>

**Comment by csthomas** [comment]
I have tested this item :white_check_mark: successfully on b10289185f4fe94aa0ca1503d4ae2eb7039a99d3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12569">issues.joomla.org/tracker/joomla-cms/12569</a>.</sub>

**Comment by RonakParmar** [comment]
I have tested this item :white_check_mark: successfully on b10289185f4fe94aa0ca1503d4ae2eb7039a99d3<br /><br />Done code review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12569">issues.joomla.org/tracker/joomla-cms/12569</a>.</sub>

**Comment by zero-24** [comment]
i did have rebootet the travis build. lets hope it passes now :smile:

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on b10289185f4fe94aa0ca1503d4ae2eb7039a99d3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12569">issues.joomla.org/tracker/joomla-cms/12569</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12569">issues.joomla.org/tracker/joomla-cms/12569</a>.</sub>

**Comment by zero-24** [comment]
Merged.

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
