### PR TITLE
[4.1] s/occurence/occurrence

### PR DESCRIPTION
**Pull request by brianteeman**
typo

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on e68d8f7b9f67f164c0dd71b169758950da40472a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36815">issues.joomla.org/tracker/joomla-cms/36815</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on e68d8f7b9f67f164c0dd71b169758950da40472a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36815">issues.joomla.org/tracker/joomla-cms/36815</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36815">issues.joomla.org/tracker/joomla-cms/36815</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
