### PR TITLE
[3.9] Change the Label Server Time Zone to Website Time Zone

### PR DESCRIPTION
**Pull request by parthlawate**
Pull Request for Issue #21398

### Summary of Changes

The Joomla Global Configuration has a Field to set the 'Server Time Zone'
Saying Server time zone gives a very wrong impression. The timezone to be set here has to be the Timezone for the Primary Audience of the website. Saying Server can confuse the end users. I might have bought hosting in the US so my Server is there.. But my website's primary Audience is in India. The current nomenclature can confuse people into setting the wrong timezone

I propose changing this to say 'Website Time Zone'
### Testing Instructions

Go to Global Configuration & confirm that the label is changed

### Expected result

Label should say Website timezone
### Documentation Changes Required

Any documentation about the Global Configuration will need change in text and screenshots

### CODE REVIEW

**Comment by ghost** [comment]
changed Title to show its about 3.9.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21400">issues.joomla.org/tracker/joomla-cms/21400</a>.</sub>

**Comment by brianteeman** [comment]
my gut feeling is that this isnt corret

**Comment by laoneo** [comment]
It is also not a server timezone.

**Comment by laoneo** [comment]
Any other recommendations?

**Comment by softforge** [comment]
Parth is right in that its not the server that people are concerned about but the time zone that is wanted so the articles published time is correct.
Could just call it "Preferred Time Zone" As its more to do with who is viewing the website and the majority audience than the server or website designer per se.

**Comment by brianteeman** [comment]
This change will require a lot of documentation to be updated

**Comment by ufuk-avcu** [comment]
I have tested this item :white_check_mark: successfully on 74ffc47b7690d8bf7f36ec59817c1c49d0d2c4bf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21400">issues.joomla.org/tracker/joomla-cms/21400</a>.</sub>

**Comment by kneisel** [comment]
I have tested this item :white_check_mark: successfully on 74ffc47b7690d8bf7f36ec59817c1c49d0d2c4bf<br /><br />initially the field in "Locations Settings" was named "Server Time Zone"
after patch the field in "Locations Settings" is named "Website Time Zone"<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21400">issues.joomla.org/tracker/joomla-cms/21400</a>.</sub>

**Comment by sanderpotjer** [comment]
I have tested this item :white_check_mark: successfully on 74ffc47b7690d8bf7f36ec59817c1c49d0d2c4bf<br /><br />Works as expected. 

If "Website Time Zone" is not a wanted label change my suggestion would be "Time zone", so without Server or Website. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21400">issues.joomla.org/tracker/joomla-cms/21400</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after 3 successful tests.

**Comment by BurtNL** [comment]
I have tested this item :white_check_mark: successfully on 74ffc47b7690d8bf7f36ec59817c1c49d0d2c4bf<br /><br />Applied patch as instructed, text of label sucessfully changed to 'Website Time Zone'.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21400">issues.joomla.org/tracker/joomla-cms/21400</a>.</sub>

**Review by yvesh — APPROVED** [review]

**Pull request merged**
