### PR TITLE
Dob error message grammar

### PR DESCRIPTION
**Pull request by brianteeman**
### Before

"The date of birth you entered is invalid. Please enter valid date."        
### After

"The date of birth you entered is invalid. Please enter a valid date."

### CODE REVIEW

**Comment by MATsxm** [comment]
I have tested this item :white_check_mark: successfully on 7e1720370b195ecffbc1d41fd8a8f256de51005f<br /><br />on review - easy

Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9757">issues.joomla.org/joomla-cms/9757</a>.</sub>

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on 7e1720370b195ecffbc1d41fd8a8f256de51005f<br /><br />Thanks :+1: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9757">issues.joomla.org/joomla-cms/9757</a>.</sub>

**Comment by tkuschel** [comment]
I have tested this item :white_check_mark: successfully on 7e1720370b195ecffbc1d41fd8a8f256de51005f<br /><br />After review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9757">issues.joomla.org/joomla-cms/9757</a>.</sub>

**Comment by brianteeman** [comment]
RTC - thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9757">issues.joomla.org/joomla-cms/9757</a>.</sub>

**Pull request merged**
