### PR TITLE
The idea of having Search tools replaced by Filters.

### PR DESCRIPTION
**Pull request by shubhamnba2009**
Pull Request for Issue #9127  .
#### Summary of Changes

Made some changes regarding changing the name from search tools to filters.
#### Testing Instructions

1.Before applying the patch: Under article menu filtering the list item button is named as Search tools.
2.After applying patch: The button is renamed as Filters.

### CODE REVIEW

**Comment by pe7er** [comment]
I have tested this item :white_check_mark: successfully on d1d4ab255f60e74f7c2b0366eb398803a5c698e4<br /><br />Test successful. 

IMHO "Filters" is a better name for that button than "Search Tools".<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9319">issues.joomla.org/joomla-cms/9319</a>.</sub>

**Comment by louiswolf** [comment]
I have tested this item :white_check_mark: successfully on d1d4ab255f60e74f7c2b0366eb398803a5c698e4<br /><br />Tested succesfully<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9319">issues.joomla.org/joomla-cms/9319</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9319">issues.joomla.org/joomla-cms/9319</a>.</sub>

**Comment by shubhamnba2009** [comment]
Thanks pe7er and louiswolf for testing it.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9319">issues.joomla.org/joomla-cms/9319</a>.</sub>

**Comment by shubhamnba2009** [comment]
I am opening a seperate pull request for this one. By mistake made commit to this branch.

**Comment by JoomliC** [comment]
I'm sorry to be about to say no successful test...

Changing name "Search Tools" to "Filters" is just a way to kill future possibilities (both Joomla and extensions developers) and to limit its usage.
The main intention of Search Tools button was too simplify UX.
A good PR to improve Search Tools would be IMHO to migrate search field and ordering/limit fields to the Search Tools button (all in one).
In fact, as it is the case directly above, in our loved Joomla! Issue Tracker! ;-)
Search field + Filters + List Ordering + List nb of items = Search Tools

That is said... i really and sincerely don't think this change to be a good idea...

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9319">issues.joomla.org/joomla-cms/9319</a>.</sub>

**Comment by zero-24** [comment]
@brianteeman @rdeutz please remove the milestone from that closed and not merged issue.

**Comment by syntaxerror** [comment]
> Changing name "Search Tools" to "Filters" is just a way to kill future possibilities (both Joomla and extensions developers) and to limit its usage.

With all respect ... How is it even possible to conclude this way? Also it's not simplifying, if people don't understand where to look for the filters etc. ;)

If someone in future wants to extend/merge functions, please do, and then change the name to fit. It doesn't limit anyone to use a proper naming for the existing futures in it.

But even if you merge features it would still not be just 'Search Tools', as you can do more with it than just searching. So when you merge features, feel free to rename it to 'Filters & Search Tools' or whatever. But for now it's just 'Filters' in there ...
https://github.com/joomla/joomla-cms/issues/9127#issuecomment-185293987

> I am opening a seperate pull request for this one. By mistake made commit to this branch.

@shubhamnba2009 did you open a separate pull request for it, or was it forgotten? I don't find any references to it, thus asking.

**Pull request closed without merging**
