### PR TITLE
Fix colspan for com_content

### PR DESCRIPTION
**Pull request by zero-24**
This PR fixes the colspan for com_content Thanks goes to @pe7er for show here the way to fix such issue https://github.com/pe7er/joomla-cms/commit/d173053e77049081db56430e19ed9462470a46dc :+1: 
### How to test
- login into the backend
- access com_content
- switch to the `featured` view
- make sure that the colspan is not to the end see

bevor_content_featured
- apply the patch
- make sure the line is not to the end of the screen like:

fixed_content_featured
- similiar fix for com_content `articles` there this PR add the complete missing line there :smile: 
- success test.

### CODE REVIEW

**Comment by pe7er** [comment]
Thanks Tobias!

@test 

Patch fixes the colspan.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6937">issues.joomla.org/joomla-cms/6937</a>.</sub>

**Comment by roland-d** [comment]
@test not OK. Before the patch there is no tfoot on the article list, after the patch there is a tfoot but it is 1 column short. It should be 11 instead of 10 in this case. 

The tfoot on the featured view is OK.

**Comment by zero-24** [comment]
Thanks @roland-d it is fixed now we need 11 if we have assoc enabled else we need 10. Thanks :smile:

**Comment by roland-d** [comment]
@test all good now. The border runs to the end at the bottom.

**Comment by asika32764** [comment]
To my knowledge, maybe set `colspan="20"` can solve this problem?

**Comment by roland-d** [comment]
@asika32764 The solution is fine as it is. The colspan is expanded where needed. Thanks.

**Pull request closed without merging**
