### PR TITLE
[5.1] Api media test

### PR DESCRIPTION
**Pull request by brianteeman**
Corrects the description of a test for the media api endpoint

simple PR that can be "tested" by code review

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 79c66944e698e7df7e87a6989aa0742cc157fed8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42512">issues.joomla.org/tracker/joomla-cms/42512</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 79c66944e698e7df7e87a6989aa0742cc157fed8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42512">issues.joomla.org/tracker/joomla-cms/42512</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42512">issues.joomla.org/tracker/joomla-cms/42512</a>.</sub>

**Comment by LadySolveig** [comment]
Thank you @brianteeman and to the reviewers @Quy  and @alikon !

**Pull request merged**
