### PR TITLE
Fix tinyMCE modal close bug (again)

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue #11047.
#### Testing Instructions

Follow these steps before and after applying this patch:

Add this snippet to administrator/components/com_content/models/forms/article.xml:

``` xml
        <field name="extrafield" type="editor"
            label="An Extra Field" description="Whatever"
            filter="JComponentHelper::filterText" buttons="true" />
```

In administrator/components/com_content/views/article/tmpl/edit.php render the new field:

``` php
<?php echo $this->form->getInput('extrafield'); ?>
```

Go to any media form field (the "Images and links" tab works for this), select an image, and try to close the modal in any available manner (the insert/cancel buttons, the X icon, or clicking outside the modal).
#### Expected result

The modal is closed.
#### Actual result

The modal does not close. In the browser console is a "Uncaught RangeError: Maximum call stack size exceeded" message.
#### Note:

The problem is the way the scripts added to the document and consequently executed. Ideal solution will be to load and execute the overrides for jModalClose and SqueezeBox.close last but that is impossible with current Joomla API, therefore the ugly code in the behaviour.php.

### CODE REVIEW

**Comment by ggppdk** [comment]
I have tested this item :white_check_mark: successfully on 262a4aec4d1e91c52a505baa56d3b59ae378b563<br /><br />Tested both
  #10774  (tested in Joomla article form)
  #11047  (tested form with 2 tinymce editors, and custom code to open modal for selecting image)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11048">issues.joomla.org/joomla-cms/11048</a>.</sub>

**Comment by ggppdk** [comment]
This should be in J3.6.0 !

**Comment by tranduyhung** [comment]
I have tested this item :white_check_mark: successfully on 262a4aec4d1e91c52a505baa56d3b59ae378b563<br /><br />Thank you! The problem is fixed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11048">issues.joomla.org/joomla-cms/11048</a>.</sub>

**Comment by zero-24** [comment]
RTC. Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11048">issues.joomla.org/joomla-cms/11048</a>.</sub>

**Comment by mbabker** [comment]
I have tested this item :white_check_mark: successfully on 262a4aec4d1e91c52a505baa56d3b59ae378b563<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11048">issues.joomla.org/joomla-cms/11048</a>.</sub>

**Comment by brianteeman** [comment]
Manually added rtc label

**Comment by Kubik-Rubik** [comment]
Thank you @dgt41 and testers!

**Comment by mmefectiva** [comment]
Thanks for the info. I've tried to apply directly, but i don't find the exact node or place in the code to aply that.
Can'u explain where is the right place to put the snipet in article.xml and render the new field in edit.php? Thanks in advance.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11048">issues.joomla.org/joomla-cms/11048</a>.</sub>

**Comment by ggppdk** [comment]
@mmefectiva 

You are looking at the wrong place, this was a fix for J3.6.0,

the fix for J3.6.1 is here:
#11097

**Pull request merged**
