### PR TITLE
[CS] Small typo

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Changes `quotename` to `quoteName`. Merge on review.

### CODE REVIEW

**Review by jurihahn — APPROVED** [review]

**Comment by brianteeman** [comment]
@jurihahn please just mark tests using the issue tracker  https://issues.joomla.org

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 0432dae7e86674fbc7697bf6615c44de796aa5a5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22398">issues.joomla.org/tracker/joomla-cms/22398</a>.</sub>

**Comment by jurihahn** [comment]
I have tested this item :white_check_mark: successfully on 0432dae7e86674fbc7697bf6615c44de796aa5a5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22398">issues.joomla.org/tracker/joomla-cms/22398</a>.</sub>

**Comment by infograf768** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22398">issues.joomla.org/tracker/joomla-cms/22398</a>.</sub>

**Comment by brianteeman** [comment]
@infograf768 please add the milestone!!

**Pull request merged**
