### PR TITLE
[4.0] calendar button colour

### PR DESCRIPTION
**Pull request by brianteeman**
Change the button colour to match the other filter buttons

See banner->tracks filters for an example to test

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 1b327f537cb95517602e3ad250cb24a1dfbf948f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26041">issues.joomla.org/tracker/joomla-cms/26041</a>.</sub>

**Comment by uGE70** [comment]
I have tested this item :white_check_mark: successfully on 1b327f537cb95517602e3ad250cb24a1dfbf948f<br /><br />Tested "Begin" Date and "End Date" buttons (banner->tracks)
Before patch, bg color is var(--atum-bg-dark-50)
After patch applied, bg color is var(--atum-bg-dark)
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26041">issues.joomla.org/tracker/joomla-cms/26041</a>.</sub>

**Comment by ghost** [comment]
Status "Ready To Commit".

**Comment by wilsonge** [comment]
As this changes all calendar layouts - can someone just check this change is sensible in the edit view as well please

**Comment by Quy** [comment]
OK in edit view.

Before:
26041-before

After:
26041-after

**Comment by wilsonge** [comment]
Perfect. Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
