### PR TITLE
Fixes #13195: Added margin bottom to sidebar menu

### LINKED ISSUE #13195: com_media - impossible to reach items on sidebar menu
### Steps to reproduce the issue
Go to the media manager

### Expected result
even with a long list of items in the sidebar menu (position icon), we should be able to reach items scrolling down.

### Actual result
screen shot 2016-12-14 at 05 11 58

### System information (as much as possible)
3.6.5 tested on FF and Chrome

### PR DESCRIPTION
**Pull request by jajodiaraghav**
Pull Request for Issue #13195  .

### Summary of Changes
A long list of items in the sidebar menu of media manager was unreachable. A margin bottom fixes the issue

### Documentation Changes Required
None

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
I have tested this item :red_circle: unsuccessfully on eab161e1eb4b7bf5271bf4f289b7e76a2b6985a9<br /><br />Tested at Joomla! 3.7.0-alpha2 (latest nightly): With or without PR sidebar menu can scroll down and see folder, which is clickable.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13548">issues.joomla.org/tracker/joomla-cms/13548</a>.</sub>

**Comment by jajodiaraghav** [comment]
@franz-wohlkoenig So you mean this change is not required?

**Comment by franz-wohlkoenig** [comment]
@jajodiaraghav In my environment (macOS Sierra, 10.12.2, Firefox 50.1.0) i see no diferenc with, -out Patch. So i see it not required like described in #13195. 
I can click on folder, Name is not shown:
bildschirmfoto 2017-01-11 um 07 45 37
It would be better to see the name of the folder too. But that wass not the Point of #13195.

**Comment by infograf768** [comment]
@franz-wohlkoenig
One needs many more folders to see the issue.
Also 36px margin is not solving the issue;

screen shot 2017-01-12 at 12 01 48

Also, a css patch should be done in both .less files and CLI generatecss.php has to be used.

**Comment by franz-wohlkoenig** [comment]
I assumed 50 Folders on different Levels are "A long list of items…".

**Comment by infograf768** [comment]
We should be able to see the folder name which we can't. I am afraid we need more than this margin.

**Comment by infograf768** [comment]
the solution is not in the margin but the padding here

To test, just change padding bottom:
```css
.j-sidebar-container {
	position: absolute;
	display: block;
	left: -16.5%;
	width: 16.5%;
	margin: -10px 0 0 -1px;
	padding-top: 28px;
	padding-bottom: 40px; ////INSTEAD of 10px
	clear: both;
	background-color: #F0F0F0;
	border-bottom: 1px solid #dedede;
	border-right: 1px solid #dedede;
	-webkit-border-radius: 0 0 3px 0;
	-moz-border-radius: 0 0 3px 0;
	border-radius: 0 0 3px 0;
}```

**Comment by infograf768** [comment]
screen shot 2017-01-12 at 12 26 37

**Comment by franz-wohlkoenig** [comment]
@infograf768 With or without Patch same:
bildschirmfoto 2017-01-12 um 13 25 29

**Comment by jajodiaraghav** [comment]
Changing padding-bottom fixes the problem in my case. Here's a screenshot:
capture

**Comment by infograf768** [comment]
Have you manually changed the css for Isis the way I posted?

**Comment by infograf768** [comment]
And cleared caches?

**Comment by jajodiaraghav** [comment]
@infograf768 
Yes and yes

**Comment by genesisfan** [comment]
I have tested this item :red_circle: unsuccessfully on eab161e1eb4b7bf5271bf4f289b7e76a2b6985a9<br /><br />Changing the Isis css file recommended by @infograf768 did the trick, not the patch.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13548">issues.joomla.org/tracker/joomla-cms/13548</a>.</sub>

**Comment by infograf768** [comment]
as i said above, changes have to be done in both less files and then generatecss has to be run

**Comment by infograf768** [comment]
Folks, I am going to make a new PR to replace this one as we also have issues in RTL for the sidebar display.

**Comment by infograf768** [comment]
Please test https://github.com/joomla/joomla-cms/pull/13593
@jajodiaraghav
@genesisfan
@franz-wohlkoenig

**Comment by infograf768** [comment]
Closing, replaced by https://github.com/joomla/joomla-cms/pull/13593<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13548">issues.joomla.org/tracker/joomla-cms/13548</a>.</sub>

**Pull request closed without merging**
