### PR TITLE
Fix copying the source lang in association editing

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue #14562

### Summary of Changes
The patch sets the target language before doing the copy

### Testing Instructions
Please use info from #14562 for testing

@infograf768 @brianteeman

### CODE REVIEW

**Comment by infograf768** [comment]
@Fedik 
This works like a charm. :smiley:

Obviously if someone changes mind, does not Save the target, changes Target language or Clear the possible association, then the not-associated formerly created target is checked out.

Not sure we can do anything about that.
Test OK for me!

**Comment by brianteeman** [comment]
**Almost** resolves the issue. The language is correctly created but the association isnt saved<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14898">issues.joomla.org/tracker/joomla-cms/14898</a>.</sub>

**Comment by infograf768** [comment]
Once more, @brianteeman
The association should ONLY be created when the Target is saved.
This patch is fine.

**Comment by brianteeman** [comment]
You can keep saying that but if the UI tells me it is saved then as a user I have to assume that it has been saved. _As a user how am i supposed to mean that saved doesnt mean that everything has been saved._ Remember this use case and remember that what @fedik has done so far in this PR is something that you said was impossible. So i am sure it can be resolved.
https://cloud.githubusercontent.com/assets/1296369/24160470/d82c98e4-0e59-11e7-8163-3f937b41f3b4.gif

**Comment by Fedik** [comment]
> The language is correctly created but the association isnt saved

for me it is also confusing a bit , 
but I also have no idea how to solve it 😄

**Comment by dgt41** [comment]
@Fedik @infograf768 AJAX to the rescue?

**Comment by Fedik** [comment]
@dgt41 that's a nice joke 😄 after all these iframes 😉 

It seems not critical, and we can think about it later (how to improve the association editing)

**Comment by dgt41** [comment]
@Fedik If I was about to implement associations I would have done it way easier, this needs a PHD to even understand WTF is going on there...

**Comment by infograf768** [comment]
Folks, I think you may not be used to the workflow on a multilingual site.
I am going to try to explain why the item obtained by save2copy should not be associated until modified and saved. I am not only speaking of the contents (for an article) or some display parameters.

First example: Menu items.

I have an original item tagged to en-GB, part of a Menu which is displayed by a menu module tagged to en-GB. Let's call this menu MYMENU_EN. It will only display when the site is switched to en-GB.
Save2copy will create a new item (grace to this patch already tagged to the desired Target Language, let's say fr-FR), but it will also use the same Menu as the Reference. 
Not only that: save2copy does not publish the new Target tagged to fr-FR (which is the normal behaviour for save2copy).
Also, the title and alias will be appended with a figure (2) and then (3) etc. if changing target language without saving the first created item for fr-FR. In that case (2) which has not been saved will also be checked out.
Conclusion: this "Associated" new menu item absolutely needs to be modified and saved again (in 99% cases).
Also, the menu item created will not display in a French menu as it is part of a menu (MYMENU_EN) which is only displayed by a Menu module tagged to en-GB (That 'could' be desired but very unlikely in most cases).

Conclusion: the association will work when using the switcher, **once the item is published**, but it only will create confusion.

Second example: Articles.
In that case, we have similar issues with published, title and alias (and content most of the time...), but also with the Category (except if the category of the Reference item is tagged to ALL languages.)
One will get after save2copy an unpublished "Associated" new article part of a category which is tagged to en-GB.

When displaying that category via for example the Details=>Category link of the display of the reference article in the English interface, using the switcher for French will display the new French tagged article (with its (2) appended title, and then when using the Category link of that article display, we will NOT switch to the English interface but just reload the same article.

A lot of confusion...

Conclusion: the Association should never be created automatically when using Copy Reference to Target but ONLY when saving the Target after the necessary modifications.

Pleaaase, as the PR works fine, mark it OK on issues.joomla.org and let's get it in.

Thanks for your attention.

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 007277cbe2cdec6e2e531e8a55508b86ed53b363<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14898">issues.joomla.org/tracker/joomla-cms/14898</a>.</sub>

**Comment by AlexRed** [comment]
I have tested this item :white_check_mark: successfully on 007277cbe2cdec6e2e531e8a55508b86ed53b363<br /><br />Patch ok for me<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14898">issues.joomla.org/tracker/joomla-cms/14898</a>.</sub>

**Comment by infograf768** [comment]
RTC. Thanks @Fedik  :smiley: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14898">issues.joomla.org/tracker/joomla-cms/14898</a>.</sub>

**Pull request merged**
