### PR TITLE
Text area and edit field defaults

### PR DESCRIPTION
**Pull request by brianteeman**
The default values for these two fields was not being set during installation. This PR will fix that for new installs. We can't do updates as it would be changing user data

code review should be fine

### CODE REVIEW

**Comment by richard67** [comment]
@brianteeman Checking elsewhere in the SQL, the integer values are quoted with double quotes, too, e.g. here:

https://github.com/joomla/joomla-cms/pull/38617/files#diff-3a9a51c74db65d66b70dbd56c86e63882cfaa26701ef6ff3f88bd0ea2682bb9fR286

https://github.com/joomla/joomla-cms/pull/38617/files#diff-d6e22b9d36df769fc1e7f3e847faf6374793792fe81b73166837406587ab3348R292

On the other hand, when saving the parameters of that field or of the fields modified by your PR, the integer values are not quoted. I've tested with MySQL and MariaDB and PostgreSQL.

So your PR is right.

But it seems we could clean up the quotes elsewhere, too (of course not with this PR).

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 7f03618af0d90cf80896a22c2d39f852bfe69969<br /><br />Tested with MySQL and MariaDB and PostgreSQL (recent versions) that the "params" values saved in database when saving the plugins options without having made changes after a new install are equal to what this PR adds to the SQL.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38617">issues.joomla.org/tracker/joomla-cms/38617</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 7f03618af0d90cf80896a22c2d39f852bfe69969<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38617">issues.joomla.org/tracker/joomla-cms/38617</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38617">issues.joomla.org/tracker/joomla-cms/38617</a>.</sub>

**Comment by fancyFranci** [comment]
Good that you fixed that. Thank you!

**Comment by brianteeman** [comment]
thx

**Pull request merged**
