### PR TITLE
Update en-GB.tpl_beez3.sys.ini

### PR DESCRIPTION
**Pull request by aaleksanyants**
Same change as in language folder ini file

### CODE REVIEW

**Comment by waader** [comment]
I have tested this item :white_check_mark: successfully on 3e32b991a5bb289bc7fdfb5987db62c72e8f3720<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7365">issues.joomla.org/joomla-cms/7365</a>.</sub>

**Comment by brianteeman** [comment]
By adding the version number for joomla this fails the style guide for the use of the joomla name https://joomla.github.io/user-interface-text/?user-interface-text/joomla_name_usage.md<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7365">issues.joomla.org/joomla-cms/7365</a>.</sub>

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 3e32b991a5bb289bc7fdfb5987db62c72e8f3720<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7365">issues.joomla.org/joomla-cms/7365</a>.</sub>

**Comment by wojsmol** [comment]
@aaleksanyants @brianteeman  see https://github.com/aaleksanyants/joomla-cms/pull/1

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on f86bcea6c041dee5314506bbfbfa5480da0407ce<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7365">issues.joomla.org/joomla-cms/7365</a>.</sub>

**Comment by brianteeman** [comment]
Contacted Angie as the creator of the template to confirm the html5 change<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7365">issues.joomla.org/joomla-cms/7365</a>.</sub>

**Comment by brianteeman** [comment]
Confirmed with Angie Setting RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7365">issues.joomla.org/joomla-cms/7365</a>.</sub>

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 88047f2e582e480d1b76ab7dc02e83ef225c5e1f<br /><br />Only updated the branch to latest staging. All equal.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7365">issues.joomla.org/joomla-cms/7365</a>.</sub>

**Pull request merged**
