### PR TITLE
CodeMirror 5.13

### PR DESCRIPTION
**Pull request by okonomiyaki3000**
Keeping CodeMirror up-to-date.
#### Summary of Changes

http://codemirror.net/doc/releases.html

A few new features and bug fixes. Probably nothing that affects Joomla users.
#### Testing Instructions

Use CodeMirror.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 744911c27ede74b3894f79ae896792446bb5fe46<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9535">issues.joomla.org/joomla-cms/9535</a>.</sub>

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on 744911c27ede74b3894f79ae896792446bb5fe46<br /><br />Thanks @okonomiyaki3000 :+1: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9535">issues.joomla.org/joomla-cms/9535</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9535">issues.joomla.org/joomla-cms/9535</a>.</sub>

**Comment by infograf768** [comment]
@okonomiyaki3000 

Please see
https://github.com/joomla/joomla-cms/issues/9592

this is before this update

**Comment by infograf768** [comment]
The issue is still present with this PR

**Comment by okonomiyaki3000** [comment]
Hmm. I wasn't aware of this but no one hates windows line endings more than me. I'll try to look into it soon.

**Comment by okonomiyaki3000** [comment]
@infograf768 Just out of curiosity, does it make any difference whether you are using FTP for file writing or not?

**Comment by infograf768** [comment]
I work on localhost. No FTP.

**Pull request merged**
