### PR TITLE
Batch copy fields

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #37555

### Summary of Changes
Batch copy field did not generate new name and label and you end up with invalid data as you have multiple fields with the same name (but diffeerent id)

### Testing Instructions
Create three fields - one, two three
Use batch copy to copy those fields in the saame group
Verify that three new fields have been created - one (2), two (2), three, (3)
Publish all three fields
Open an article for editing

### Actual result BEFORE applying this Pull Request
The fields tab only has 3 fields not the expected 6

### Expected result AFTER applying this Pull Request
fields tab has 6 fields

### Documentation Changes Required
none

### CODE REVIEW

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on da66f71ee8eb2add0edffec28a933d7a8d5ab905<br /><br />Tested successfully in Joomla 4.2.3-dev of 5 September in Wampserver 3.2.9 and PHP 8.1.9.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38682">issues.joomla.org/tracker/joomla-cms/38682</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on da66f71ee8eb2add0edffec28a933d7a8d5ab905<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38682">issues.joomla.org/tracker/joomla-cms/38682</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38682">issues.joomla.org/tracker/joomla-cms/38682</a>.</sub>

**Comment by fancyFranci** [comment]
Thank you very much

**Pull request merged**
