### PR TITLE
Joomla 3.8.0: Disabled com_fields displayed in admin menu

### PR DESCRIPTION
**Pull request by n3t**
Pull Request for Issue #18046 .

### Summary of Changes
Added check to JAdminMenuCSS for disabled or not installed components.

### Testing Instructions
Disable com_fields, and see the menu. Links to fields components are present, leading to 404 page.
Apply this patch, and see the menu again.

### CODE REVIEW

**Comment by waader** [comment]
I have tested this item :white_check_mark: successfully on 0e0bdbf5f4f4efa281cf3d24208cdf7a7119a1e5<br /><br />Thanks n3t, work great!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18134">issues.joomla.org/tracker/joomla-cms/18134</a>.</sub>

**Comment by waader** [comment]
I have tested this item :white_check_mark: successfully on 0e0bdbf5f4f4efa281cf3d24208cdf7a7119a1e5<br /><br />Thanks n3t, works great!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18134">issues.joomla.org/tracker/joomla-cms/18134</a>.</sub>

**Comment by wojsmol** [comment]
@izharaazmi Please test this if you have a moment.

**Comment by izharaazmi** [comment]
I have tested this item :white_check_mark: successfully on 0e0bdbf5f4f4efa281cf3d24208cdf7a7119a1e5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18134">issues.joomla.org/tracker/joomla-cms/18134</a>.</sub>

**Comment by ghost** [comment]
RTC after two successful tests.

**Comment by infograf768** [comment]
The problem with this code is that it increases drastically the queries.
Any better way? May be by specifically targeting com_fields ?

**Comment by izharaazmi** [comment]
@infograf768 What do you mean?

**Comment by alikon** [comment]
@izharaazmi see #18264

**Comment by infograf768** [comment]
I guess we could have done
```
			// Exclude item if com_fields component is not installed or disabled
			if ($item->element == 'com_fields' && (!JComponentHelper::isInstalled($item->element) || !JComponentHelper::isEnabled($item->element)))
			{
				continue;
			}
```

**Comment by izharaazmi** [comment]
Your suggestion only checks for com_fields, however the current code checks for all components and excludes a menu item if the related component is disabled/not installed.

**Comment by infograf768** [comment]
@izharaazmi 
I tested disabling some components like com_associations, com_banners, etc., and it works fine with that code.
I suggest you test yourself.
com_fields is a specific case.

**Comment by izharaazmi** [comment]
Ok, I'll test it

**Comment by izharaazmi** [comment]
Okay. I tested it. The checks for items under component container are done internally so they are not needed, fine. For core (protected)  components they cannot be disabled from UI, fine.

If we do have any other situation with any components we need this test for them. One such is `com_fields`. Since a custom menu can have any components link anywhere they will need this tests I think.

@infograf768 I think we must work to minimise the duplicate queries but restricting to com_fields does not seem right. What do you suggest?

**Comment by infograf768** [comment]
@izharaazmi 
I suggest we discuss on https://github.com/joomla/joomla-cms/pull/18264.
See my comment there https://github.com/joomla/joomla-cms/pull/18264#issuecomment-334920886
as I think that we may not really need to check if a comp is installed.

**Pull request merged**
