### PR TITLE
[4] install language - an error message when no xml is returned

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #38110 .

### Summary of Changes
added a check if the xml is returned

### Testing Instructions
add a `$response->body= "";` on line 153 to simulate the case

### Actual result BEFORE applying this Pull Request

`PHP Warning:  Attempt to read property "extension" on bool in /shared/httpd/dev4/joomla-cms/administrator/components/com_installer/src/Model/LanguagesModel.php on line 158`

### Expected result AFTER applying this Pull Request

a proper error message

### CODE REVIEW

**Review by wilsonge — APPROVED** [review]

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 6d0afcf3846e4ce6448e213af16ecde2469fafe9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38113">issues.joomla.org/tracker/joomla-cms/38113</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 6d0afcf3846e4ce6448e213af16ecde2469fafe9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38113">issues.joomla.org/tracker/joomla-cms/38113</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38113">issues.joomla.org/tracker/joomla-cms/38113</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
