### PR TITLE
[4.0] [GSoC 2018] CLI Update Project

### PR DESCRIPTION
**Pull request by vuchkov**
Pull Request for Issue #21452 .

### Summary of Changes

Fix some some CodeSniffer (code-style) errors.

### Documentation Changes Required

### CODE REVIEW

**Comment by richard67** [comment]
@vuchkov Shall this Pull Request (PR) here replace PR #21452 ? Or was this PR here meant to propose changes to PR #21452 ?

In the latter case you should make a PR not against the 4.0-dev branch of the CMS repo like this PR here is now, but make a PR against the branch of PR #21452 , which is [https://github.com/bosunski/joomla-cms/tree/m1_copy](https://github.com/bosunski/joomla-cms/tree/m1_copy). See the green frame in following screenshot about how to do that:

snap-1

**Comment by vuchkov** [comment]
@richard67 Yes, it is. Thank you.

I created the PR in the right way.

**Comment by richard67** [comment]
@vuchkov Ok, I'll close this here for you.

**Comment by richard67** [comment]
Closing in favour of [https://github.com/bosunski/joomla-cms/pull/1](https://github.com/bosunski/joomla-cms/pull/1), see the 2 comments before this one here.

**Pull request closed without merging**
