### PR TITLE
[4.0] Fix tag edit layout

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue #25863.

### Summary of Changes

Removes reference to non-existing layout file. Also improves display on smaller screens.

### Testing Instructions

Edit a tag.

### Expected result

No errors.

### Actual result

>An error has occurred.
>500 Layout edit_metadata not found. 

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on eae802c8b73c226d4aa35b6d46301fe216c7752c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25880">issues.joomla.org/tracker/joomla-cms/25880</a>.</sub>

**Comment by ghazal** [comment]
I have tested this item :white_check_mark: successfully on eae802c8b73c226d4aa35b6d46301fe216c7752c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25880">issues.joomla.org/tracker/joomla-cms/25880</a>.</sub>

**Comment by ghost** [comment]
Status "Ready To Commit".

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
