### PR TITLE
Isis pagination

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #6557
#### Summary of Changes

Remove ... value from pagination as it makes no sense as reported by @spignataro
#### Testing Instructions

Set list limit to 5 on any view with many items and check the display of pagination at the bottom of the page. It should always have a value after the patch. Before the patch the middle value will always be ...

### CODE REVIEW

**Comment by SharkyKZ** [comment]
If active/current page is meant to be in the center, line 121 needs to be removed.

**Comment by brianteeman** [comment]
No - active/current is highlited and has not been changed in this PR

On 4 May 2016 at 21:08, SharkyKZ <notifications@github.com> wrote:

> If active/current page is meant to be in the center, line 121 needs to be
> removed.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/10240#issuecomment-216986275>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by SharkyKZ** [comment]
Sorry, removed my comment to test a bit more.

In that case line 121 should be deleted as it causes items to shift.

**Comment by brianteeman** [comment]
Maybe I dont understand what you mean - is this different to before?

**Comment by SharkyKZ** [comment]
See before and after:
untitled
untitled2

**Comment by brianteeman** [comment]
Other than only showing 5 not 10 and not showing the useless ... what is your point
maybe i am being thick i just dont get what you are saying

**Comment by SharkyKZ** [comment]
Added screenshots.

**Comment by brianteeman** [comment]
I saw them but i still dont understand

**Comment by SharkyKZ** [comment]
Patch causes an undesired effect. All items before 9 (the former ...) are removed, active item is no longer centered. This is because of a leftover statement on line 121.

**Comment by brianteeman** [comment]
Active item was NOT centered before

**Comment by BurtNL** [comment]
I applied the patch and gave it a test. It works, but without line 121 (as mentioned by @SharkyKZ) it is working much better.
In that case the active item stays 'centered' (when possible) or better: the active item stays in the same position, which is more convenient.



<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10240">issues.joomla.org/joomla-cms/10240</a>.</sub>

**Comment by brianteeman** [comment]
I will take another look to see if I "get it" now

**Comment by brianteeman** [comment]
Having looked at it with line 121 removed I see what you mean and I dont
like it for the following reason
Before this alteration
You click on 9 and 9 is highlited and your cursor is still over the 9
After this alteration
You click on 9 and 9 is highlited and your cursor is now over the 10 and
the 9 has shifted one to the left


On 5 May 2016 at 11:42, Brian Teeman <brian@teeman.net> wrote:

> I will take another look to see if I "get it" now
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by SharkyKZ** [comment]
That is the intention. This patch is only meant to change ... back to a number, right?

Before patch
After patch, line 121 removed

**Comment by brianteeman** [comment]
Closed - cant be bothered<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10240">issues.joomla.org/joomla-cms/10240</a>.</sub>

**Comment by zero-24** [comment]
I have just send you a pull request to remove that if line: https://github.com/brianteeman/joomla-cms/pull/22

**Comment by brianteeman** [comment]
Thanks!! I had enough coffee now and understand what has been said

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on 273898ee20e57ff422b2cffd7aae343d12ca044c<br /><br />Works thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10240">issues.joomla.org/joomla-cms/10240</a>.</sub>

**Comment by zero-24** [comment]
Im altering the test by @SharkyKZ as he just tested without the line 122 successfully.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10240">issues.joomla.org/joomla-cms/10240</a>.</sub>

**Comment by zero-24** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10240">issues.joomla.org/joomla-cms/10240</a>.</sub>

**Comment by BurtNL** [comment]
I have tested this item :white_check_mark: successfully on 273898ee20e57ff422b2cffd7aae343d12ca044c<br /><br />Tested successfully, thanks for reopening and solving.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10240">issues.joomla.org/joomla-cms/10240</a>.</sub>

**Pull request merged**
