### PR TITLE
Extension Manager>Install>Upload>Install Joomla Extension - Error is now shown in red.

### PR DESCRIPTION
**Pull request by prasoon2211**
The problem was as @infograf768 said. We're using the `$msg` way to show the message here.
Sample:
screen shot 2015-01-18 at 7 38 55 pm

### CODE REVIEW

**Comment by Kubik-Rubik** [comment]
Could you please optimize it to one line:

`
$app->enqueueMessage(JText::_('COM_INSTALLER_UNABLE_TO_FIND_INSTALL_PACKAGE'), 'error');
`

Thank you!

**Comment by prasoon2211** [comment]
@Kubik-Rubik Hey. I've changed the fix to be in one line. Anything else?

**Comment by Kubik-Rubik** [comment]
@prasoon2211 Thank you, looks good for me. One more tester required!

**Comment by prasoon2211** [comment]
Someone test this please?

**Comment by zero-24** [comment]
@test success moving to RTC Thanks @prasoon2211<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5809">issues.joomla.org/joomla-cms/5809</a>.</sub>

**Comment by Kubik-Rubik** [comment]
Thank you for the PR @prasoon2211 and the test @zero-24!

**Comment by zero-24** [comment]
wow cool quick merge :smile: Thanks @Kubik-Rubik

**Comment by Kubik-Rubik** [comment]
GitHub notification mails make it possible! ;-)

**Pull request merged**
