### PR TITLE
Text change <issue #14703>

### PR DESCRIPTION
**Pull request by sharan1**
Pull Request for Issue # .

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on bbe7921a0421c3d605d6f943863f44264af99b7b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14954">issues.joomla.org/tracker/joomla-cms/14954</a>.</sub>

**Comment by ggppdk** [comment]
The "Empty trash"button does not do what it says,
- that is it does not "Empty trash", instead it acts on the selected articles

But then "Delete" is not good either, as it can be confused / feel like to the word "Trash"

More appropriate and also commonly used in UIs is the word  "Permanent"
aka "Permanent delete"

**Comment by Quy** [comment]
In Windows, you `Delete` files and `Empty Recycled Bin` to delete all deleted files. You can go in the Recycled Bin to selectively delete files.

To follow suite:
Keep `Empty trash` button, but change its function to delete all trashed items without having to select.
Add another button `Delete` to delete selected items.

**Comment by brianteeman** [comment]
I am closing this as it doesnt improve things

**Pull request closed without merging**
