### PR TITLE
[mod_related_items] Remove unused code

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue # .

### Summary of Changes

Removes unused parts of the query.

### Testing Instructions

The module should work like before.

### Documentation Changes Required
No.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 3802ed7f9c9bdcc666139d781dab71e3f8e57deb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23292">issues.joomla.org/tracker/joomla-cms/23292</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 3802ed7f9c9bdcc666139d781dab71e3f8e57deb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23292">issues.joomla.org/tracker/joomla-cms/23292</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23292">issues.joomla.org/tracker/joomla-cms/23292</a>.</sub>

**Comment by mbabker** [comment]
This would need to be chucked into the 4.0 pile since it removes fields from the query result and this can impact layout overrides.

**Comment by SharkyKZ** [comment]
This doesn't affect layouts. The items returned are retrieved using the model:

https://github.com/joomla/joomla-cms/blob/3802ed7f9c9bdcc666139d781dab71e3f8e57deb/modules/mod_related_items/helper.php#L142

**Pull request merged**
