### PR TITLE
Fixed email validation issue

### PR DESCRIPTION
**Pull request by RonakParmar**
Hello,
I have found email validation issue in joomla 3.3.6, joomla 3.4.2 and joomla 3.4.3 versions.
I have fixed this issue and create PR of it, please review it.
I have changed validate.js file for email validation.
Right now, joomla consider "test@test" as a valid email address and I think this is not valid email address.

Testing Information:
- Log-in into site
- Goto Edit user profile page
- Enter wrong email address for example "test@test".
- Press submit button, user data will save.

Current Output:
- Email address is not valid still data will save.

Actual Output:
- Error message like Invalid email address.

### CODE REVIEW

**Comment by brianteeman** [comment]
It can be a valid address on an internet

On 6 August 2015 at 13:30, RonakParmar <notifications@github.com> wrote:

> Hello,
> I have found email validation issue in joomla 3.3.6, joomla 3.4.2 and
> joomla 3.4.3 versions.
> I have fixed this issue and create PR of it, please review it.
> I have changed validate.js file for email validation.
> Right now, joomla consider "test@test" as a valid email address and I
> think this is not valid email address.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/joomla/joomla-cms/pull/7644
> Commit Summary
>
>    - Fixed email validation issue
>
> File Changes
>
>    - *M* media/system/js/validate-uncompressed.js
>    <https://github.com/joomla/joomla-cms/pull/7644/files#diff-0> (2)
>    - *M* media/system/js/validate.js
>    <https://github.com/joomla/joomla-cms/pull/7644/files#diff-1> (2)
>
> Patch Links:
>
>    - https://github.com/joomla/joomla-cms/pull/7644.patch
>    - https://github.com/joomla/joomla-cms/pull/7644.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/7644>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Bakual** [comment]
@brianteeman I think you meant intranet?

**Comment by brianteeman** [comment]
autocorrect - yes

On 6 August 2015 at 13:56, Thomas Hunziker <notifications@github.com> wrote:

> @brianteeman <https://github.com/brianteeman> I think you meant intranet?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/7644#issuecomment-128353619>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Kubik-Rubik** [comment]
Thank you for your contribution, @RonakParmar!

Sorry, this is wrong. You mean a *fully qualified domain name* (https://en.wikipedia.org/wiki/Hostname#Restrictions_on_valid_host_names) but as @brianteeman said, an unqualified hostname (as root@localhost) is also valid depending on the system.

Closed.

**Comment by RonakParmar** [comment]
I was not aware about this, thanks for update me.
Should I close this PR, or wait for others to comment?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7644">issues.joomla.org/joomla-cms/7644</a>.</sub>

**Comment by RonakParmar** [comment]
Okay, Just refresh the page and see your comment.
Thanks for closing.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7644">issues.joomla.org/joomla-cms/7644</a>.</sub>

**Pull request closed without merging**
