### PR TITLE
Update composer and remove dummy random_compat

### PR DESCRIPTION
**Pull request by zero-24**
### Summary of Changes

Remove the dummy random_compat https://github.com/paragonie/random_compat#version-99999

Package operations: 0 installs, 19 updates, 0 removals
  - Updating psr/link (1.0.0 => 1.1.1): Loading from cache
  - Updating fig/link-util (1.1.2 => 1.2.0): Loading from cache
  - Updating laminas/laminas-zendframework-bridge (1.1.1 => 1.2.0): Loading from cache
  - Updating laminas/laminas-diactoros (2.4.1 => 2.6.0): Loading from cache
  - Updating symfony/polyfill-php80 (v1.22.1 => v1.23.0): Loading from cache
  - Updating symfony/polyfill-mbstring (v1.22.1 => v1.23.0): Loading from cache
  - Updating symfony/var-dumper (v5.2.6 => v5.2.8): Loading from cache
  - Updating symfony/polyfill-php72 (v1.22.1 => v1.23.0): Loading from cache
  - Updating psr/log (1.1.3 => 1.1.4): Loading from cache
  - Updating symfony/error-handler (v5.2.6 => v5.2.8): Loading from cache
  - Updating symfony/polyfill-php73 (v1.22.1 => v1.23.0): Loading from cache
  - Updating symfony/polyfill-ctype (v1.22.1 => v1.23.0): Loading from cache
  - Updating symfony/yaml (v5.2.5 => v5.2.9): Loading from cache
  - Updating symfony/polyfill-intl-normalizer (v1.22.1 => v1.23.0): Loading from cache
  - Updating symfony/polyfill-intl-grapheme (v1.22.1 => v1.23.0): Loading from cache
  - Updating symfony/string (v5.2.6 => v5.2.8): Loading from cache
  - Updating symfony/polyfill-iconv (v1.22.1 => v1.23.0): Loading from cache
  - Updating fgrosse/phpasn1 (v2.2.0 => v2.3.0): Loading from cache
  - Updating symfony/console (v5.2.6 => v5.2.8): Loading from cache

### Testing Instructions

install joomla
apply this patch
run composer install --no-dev (or use the generated package)
Make sure joomla still loads.

### Actual result BEFORE applying this Pull Request

There is an empty random_compat package while the 9.99.9 version is empty and does nothing anyway.

### Expected result AFTER applying this Pull Request

That package is gone and the other listed packages are updated.

### Documentation Changes Required

none

### CODE REVIEW

**Comment by brianteeman** [comment]
Unable to test as none of my installs contain this random_compat

**Comment by brianteeman** [comment]
Looking at the original post I would expect to see it listed as removed but there were zero removals

> Package operations: 0 installs, 19 updates, 0 removals

**Comment by zero-24** [comment]
> Unable to test as none of my installs contain this random_compat

Well i have just double checked the latest nightly build:
image

And when we check the package from the download section here random_compat is gone:
image

When you check the lib thats loaded there you see its empty as described in the docs linked above.

**Comment by zero-24** [comment]
> Looking at the original post I would expect to see it listed as removed but there were zero removals

Its clearly gone as you can see on my screenshots i dont know how that counter works within composer.

**Comment by brianteeman** [comment]
It looks like it is installed as its a required dependency of two packages (hence I didnt find it in composer.json and only in composer.lock)

**Comment by zero-24** [comment]
Correct. IIRC its from joomla/session and sodium_compat. But with php7 as minimum its empty anyway.

**Comment by brianteeman** [comment]
and I see now that replace command just prevents the dependency being loaded<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34252">issues.joomla.org/tracker/joomla-cms/34252</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on b015cc095ba31c234f1cb109bb51369fcf2569b2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34252">issues.joomla.org/tracker/joomla-cms/34252</a>.</sub>

**Comment by richard67** [comment]
@zero-24 Composer fails in appveyour and drone so there is definitely something wrong.

**Comment by brianteeman** [comment]
Sorry - my test results were just local checking that the removal of random_compat worked
I did not check the updates which is where drone is producing the errors as they are php 8

**Comment by brianteeman** [comment]
I have not tested this item.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34252">issues.joomla.org/tracker/joomla-cms/34252</a>.</sub>

**Comment by brianteeman** [comment]
@zero-24 please check #34267

**Pull request closed without merging**
