### PR TITLE
[4.0] Remove button Cancel from Registration form

### PR DESCRIPTION
**Pull request by tarot-ray**
For A11Y reasons, as reported by @zwiastunsw and because in Web browser situations, like this, a 'Cancel' button is not needed, as the user can simply navigate away, if they don't want to commit, the 'Cancel' button is removed. 

In any case, there is no 'cancel' type for the button element, in HTML, so this can only be done by using CSS to make a <a> element look like a button or by making a normal button and adding Javascript. Neither is a good solution for an unnecessary button.

Therefore, it is being removed.

### Summary of Changes

'Cancel' button is removed.

### Testing Instructions

Open the registration form and see that the 'Cancel' button no longer exists and that the screenreader behaves correctly.

### Expected result

Better screenreader behaviour.

### CODE REVIEW

**Comment by wojsmol** [comment]
I have tested this item :white_check_mark: successfully on 9a155e1a78633405cbfd8d3799dec6e42a2ebfa4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24000">issues.joomla.org/tracker/joomla-cms/24000</a>.</sub>

**Comment by zwiastunsw** [comment]
I have tested this item :white_check_mark: successfully on 9a155e1a78633405cbfd8d3799dec6e42a2ebfa4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24000">issues.joomla.org/tracker/joomla-cms/24000</a>.</sub>

**Comment by wojsmol** [comment]
@zero-24 Please fix the rips issue.

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24000">issues.joomla.org/tracker/joomla-cms/24000</a>.</sub>

**Comment by zwiastunsw** [comment]
thanks

**Comment by C-Lodder** [comment]
I'd really like to see the evidence/research to back this up.

**Comment by brianteeman** [comment]
I'm not convinced yet either

**Comment by zwiastunsw** [comment]
@C-Lodder : see: https://github.com/joomla/accessibility/issues/55#issuecomment-466802339

**Comment by C-Lodder** [comment]
Ok and my next question is. Is it easier for someone with disabilities (lets say someone blind in thise case) so find a cancel button (next to submit) or navigate back using the browser's back button?

Not saying this PR is right or wrong but want definitely curious

**Comment by zwiastunsw** [comment]
If a user (sighted or blind) wants to return to the previous page, he can only return using the browser function, because the Cancel button will not lead him to the previous page visited, but only to the homepage.
In addition:
The problem of whether this button is needed or not is not an accessibility problem. This is a UX problem.
Link/button will be accessible. The problem is that the button and the command on the button suggest an action (cancelling an action). But they don't perform actions, they just change the context (redirect to another page). And this is an aceesiibility error - do sth. other than what it announces.

**Comment by brianteeman** [comment]
As I said in the other repo

. If its a form with "personal data" many people will feel happier to actively "cancel" if they change their mind about completing the form

Regarding the a11y  of the button "doing something other than what it announces" that is easy to fix..

**Comment by zwiastunsw** [comment]
@brianteeman , forgive me, but this is not an argument. Many people will be happy when they get $500.

**Comment by brianteeman** [comment]
So far the only valid comment is that the current link going to the home page is wrong. that is easily fixed

**Comment by zwiastunsw** [comment]
> So far the only valid comment is that the current link going to the home page is wrong.

This is not the *only valid* comment. The valid comment is above all that this link/button *is unnecessary*. Other correct comments are those that show that in *other forms you have the Submit button*, but *do not have the Cancel button*.   
You do not need to cancel any operation in order not to send the form.

**Comment by C-Lodder** [comment]
Sorry but I'm going to have to agree with Brian here. He made a very good point:

> If its a form with "personal data" many people will feel happier to actively "cancel" if they change their mind about completing the form

which from a UX perspective, is important. It feels like everyone is focusing too much on a11y and disregarding general UX. Both are as important as eachother.

**Comment by zwiastunsw** [comment]
Forms very often contain personal data. And they do not contain the cancel button. You don't want to send them, you just don't send them.  Getting the Cancel button makes sense e.g. in the Backend of Joomla. You make settings for the options. But you don't want to save them and you want to leave the edit/new. The only way - the Close or Cancel button. In this case it makes sense.

**Comment by SharkyKZ** [comment]
You can use browser's back button in backend too.

**Comment by zwiastunsw** [comment]
@SharkyKZ : Do you want to propose to remove the Close/Cancel buttons from the backend? This is not a good idea. There these buttons are useful. 
Imagine a page where there is only a registration form. Where, in your opinion, should the button / link Cancel lead?

**Comment by dgrammatiko** [comment]
> You can use browser's back button in backend too.

Leaving a form without saving or canceling in the backend leaves the edit item in the "checked in" state. In other words the item is locked. There is no way to just remove the cancel buttons in the backend without some serious architectural changes. Obviously people suggesting that don't really understand the fundamentals that Joomla is build upon...

**Comment by zwiastunsw** [comment]
@dgrammatiko : This is already known from Joomla 1.0 and even from Mambo. But maybe @SharkyKZ  doesn't know.

**Comment by dgrammatiko** [comment]
@SharkyKZ @zwiastunsw this is a good reference: https://github.com/joomla/joomla-cms/pull/4773
Lots of valuable info there

**Comment by zwiastunsw** [comment]
Thank you @dgrammatiko. But I do not propose to remove the Cancel buttons from the backend. I used their example to show when the Cancel button is needed. I didn't point to the important aspect you pointed out so as not to complicate this unnecessary discussion.

The gentlemen are trying to prove to me that the Cancel button on the registration form has some magical, even necessary functions. I explain that this button does nothing good. I explain that it causes confusion and why. 

I explain that it is not needed for anything. I show examples that prove that it is unnecessary. No effect. I waste time discussing nothing.  

I know a lot of such minor faults and accessibility errors in Joomla. But when I think that there will be a discussion on every PR as during the defense of scientific dissertation, I don't know if I have the time, willingness and strength to do so.

**Comment by dgrammatiko** [comment]
@zwiastunsw I wouldn't commended in the first place but I see a lot of people suggesting/making PRs that are totally against the architecture of the system. I feel that these need to be turned down asap...
So my comment was **only** for the backend cancel button, I have no input/feedback on this actual PR so I'm muting myself

**Comment by SharkyKZ** [comment]
I'm suggesting the button should clear form data like in any other form. Especially since this concerns personal data.

**Comment by zwiastunsw** [comment]
@SharkyKZ wrote:
> I'm suggesting the button should clear form data like in any other form. Especially since this concerns personal data.

Really? I would be grateful for any references. 
Here are some of mine:
* [10 Tips for Optimizing Web Form Submission Usability](https://www.webfx.com/blog/web-design/10-tips-for-optimizing-web-form-submission-usability/), especially: 8. Your “Cancel” Button is a Major Distraction
* [10 Rules For Efficient Form Design](https://uxplanet.org/10-rules-for-efficient-form-design-e13dc1fb0e03). In the illustrations  you will find  5 of the "Create account" forms with personal data. Without Cancel buttons
* [58 Form Design Best Practices & Form UX Examples](https://www.ventureharbour.com/form-design-best-practices/). 58 best practices, but there is no advice to add a Cancel button to clear the data. If you read it, you'll find the opposite advice.
* [10 Best Practices for Designing User-Friendly Forms](https://medium.theuxblog.com/10-best-practices-for-designing-user-friendly-forms-fa0ba7c3e01f). There is no word on the subject of the Cancel button. But there is an interesting fragment about hiding passwords. I recommend it to those who recently debated this subject fervently. 
* [13 Empirically Backed Form Design Best Practices](https://conversionxl.com/blog/form-design-best-practices/). There is no word on the subject of the Cancel button. 

(Ladies and) gentlemen, thank you all for this discussion. I really have learned a lot. I promise that this is my last 2 cents.

**Comment by zwiastunsw** [comment]
thx

**Pull request merged**
