### PR TITLE
[4.0] Adding a Change button for article modal when field is required instead of the Clear button to simplify UX

### PR DESCRIPTION
**Pull request by infograf768**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/30289

### Summary of Changes
When the article field is required, which is the case in core only when used in a single article menu item, it is useless to first Clear the field and then Select again when modifying the menu item.

In such a case, a new Change button is added and used. The button is  basically using the same code as the Select button.
The reason the button is added is the fact that the code shows or hide buttons depending if the field is empty (new item then use Select) or not.
The `hidden` status is applied in the js depending on the situation.

When the field is NOT required, we keep the Clear button. When it is, it is now replaced by the `Change` button, therefore avoiding a 2 steps action.

### Testing Instructions
Patch. Run npm ci.
Edit an existing single article menu item.
Create a new single article menu item.

All other cases of the `modal_article` field are not required and therefore will keep the Clear button (including associations)

This is totally B/C

### Actual result BEFORE applying this Pull Request
When editing an existing item

Screen Shot 2020-08-10 at 10 42 57

### Expected result AFTER applying this Pull Request
fWhen editing an existing item

Screen Shot 2020-08-07 at 12 41 47

For a new menu item

Screen Shot 2020-08-07 at 12 42 20

We keep the Clear button for Associations and elsewhere when the field is not required and the element `change` is not set to true

Screen Shot 2020-08-07 at 12 21 34

### Documentation Changes Required
Yes

### Note
1. If this is accepted, it can be done for other components where such a `modal_xxx` is used and required.
2. It can also be backported to 3.x

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 1e62115ad5d56e683340fb2b82120d4e256e5482<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30331">issues.joomla.org/tracker/joomla-cms/30331</a>.</sub>

**Comment by infograf768** [comment]
@Quy
Just thought about something.
Once we are in the `Change` status, we do not have any more the `Create` possibility...
Not sure I can modify to add this, but trying now.

**Comment by richard67** [comment]
> Not sure I can modify to add this, but trying now.

@infograf768 Will there be any changes on this PR, or will it be a new one? Or in other words: Is this PR here ready?

**Comment by infograf768** [comment]
> Is this PR here ready?

Not after I discovered https://github.com/joomla/joomla-cms/pull/30331#issuecomment-672752951
Changing to Draft

**Comment by nadjak77** [comment]
I have tested this item :white_check_mark: successfully on 1e62115ad5d56e683340fb2b82120d4e256e5482<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30331">issues.joomla.org/tracker/joomla-cms/30331</a>.</sub>

**Comment by mqueme** [comment]
Tested. Works as expected

**Comment by richard67** [comment]
@mqueme Could you also mark your test result in the issue tracker? Just go to https://issues.joomla.org/tracker/joomla-cms/30331 , use the "Test this" button, select the right test result and submit. Thanks in advance.

**Comment by richard67** [comment]
@infograf768 As far as I understand you want to make changes on this PR so you had set it to draft status, right?

@nadjak77 @mqueme Thanks for testing so far, but it seems it might need to be tested again later when outstanding changes have been made.

**Comment by mqueme** [comment]
I have tested this item :white_check_mark: successfully on 1e62115ad5d56e683340fb2b82120d4e256e5482<br /><br />Works as expected<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30331">issues.joomla.org/tracker/joomla-cms/30331</a>.</sub>

**Comment by infograf768** [comment]
As it is, this can’t be merged. Did not have the opportunity to look if issue can be solved.

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 1e62115ad5d56e683340fb2b82120d4e256e5482<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30331">issues.joomla.org/tracker/joomla-cms/30331</a>.</sub>

**Comment by infograf768** [comment]
This can be closed.

**Pull request closed without merging**
