### PR TITLE
Fix batch menu items

### LINKED ISSUE #32375: Batch processing menu-items unable to select target menu-item
### Steps to reproduce the issue
Select a menu and all its items then try to batch move them to another menu and menu-item

### Expected result
Being able to select target menu-item

### Actual result

Only possible to select menu (no items)

### System information (as much as possible)
Joomla 3.9.24

### Additional comments
Works in 3.9.22 (not tested with 3.9.23)
**3.9.22**

**3.9.24**

### PR DESCRIPTION
**Pull request by joomdonation**
Pull Request for Issue #32375.

### Summary of Changes
This small PR fixes #32375.

### Testing Instructions
1. Access to Menus -> Main Menu
2. Select some menu items, then press Batch button in the toolbar
3. Before patch: On then popup, you only see unpublished menu item
4. After patch: Both published and unpublished menu items are being displayed

### CODE REVIEW

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on 641c3dad5353caa0a1fa50c1aa8f7af8bf3b1792<br /><br />Tested successfully in 3.9.25-dev of 11 February in Wampserver 3.2.4 using PHP 8.0.1.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32380">issues.joomla.org/tracker/joomla-cms/32380</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 641c3dad5353caa0a1fa50c1aa8f7af8bf3b1792<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32380">issues.joomla.org/tracker/joomla-cms/32380</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32380">issues.joomla.org/tracker/joomla-cms/32380</a>.</sub>

**Comment by infograf768** [comment]
Note: We have exactly the same issue in J4

**Comment by infograf768** [comment]
Tks

**Pull request merged**
