### PR TITLE
[4.2] Tinymce editor.css

### PR DESCRIPTION
**Pull request by brianteeman**
Ensures that a non-minified editor.css will be used if present even if debug is OFF

To test
1. Open an article for editing
2. Use your browser tools eg chrome inspector to verify that media\templates\site\cassiopeia\css\editor.min.css is loaded
3. Delete that file and check again. This time you should get the non-minified version of that file

Before this PR in step 3 you get the minified version from the system eg media\system\css\editor.min.css

After this PR in step 3 you correctly get media\templates\site\cassiopeia\css\editor.css

Pull Request for Issue (sorry I can't find it) 

No documentation change required as this is fixing a bug to make the code work the way it is documented.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by crystalenka** [comment]
I have tested this item :white_check_mark: successfully on afa6bc6899b0663dcd1d7cfd93213bcc3a15500e<br /><br />Was trying to figure out what was going on. Thank you for this!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39124">issues.joomla.org/tracker/joomla-cms/39124</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on afa6bc6899b0663dcd1d7cfd93213bcc3a15500e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39124">issues.joomla.org/tracker/joomla-cms/39124</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39124">issues.joomla.org/tracker/joomla-cms/39124</a>.</sub>

**Comment by roland-d** [comment]
Thank you

**Pull request merged**
