### PR TITLE
[com_contact] - featured/unfeatured messages fix

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #16059 .

### Summary of Changes
fixed the messages for featured/unfeatured 

### Testing Instructions
from the list of contacts click on the featured icon to toggle the featured status

### Expected result
Message displayed 

### Actual result
no message

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on bd6863c499453e71d30b8275543def2e052ec996<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16062">issues.joomla.org/tracker/joomla-cms/16062</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on bd6863c499453e71d30b8275543def2e052ec996<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16062">issues.joomla.org/tracker/joomla-cms/16062</a>.</sub>

**Comment by infograf768** [comment]
RTC. Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16062">issues.joomla.org/tracker/joomla-cms/16062</a>.</sub>

**Comment by infograf768** [comment]
Travis failure looks unrelated to this PR

**Pull request merged**
