### PR TITLE
[4.0] Add the requested new line & await en-GB review

### PR DESCRIPTION
**Pull request by zero-24**
### Summary of Changes

This PR adds the new line requested by @laoneo and is going to include the language changes that @brianteeman is going to request on https://github.com/joomla/joomla-cms/pull/20403

Language file in question is this one: https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/language/en-GB/en-GB.plg_system_httpheaders.ini

### Expected result

Passes @laoneo 's and @brianteeman 's review.

### CODE REVIEW

**Review by brianteeman — APPROVED** [review]

**Comment by zero-24** [comment]
@brianteeman this was about the language strings you want to change in that plugin. Or does this mean that the strings are fine now?

**Comment by brianteeman** [comment]
ah - i will do a pr for those strings but it wont be until i am back from france

**Comment by zero-24** [comment]
Ok thanks have a great time in France! Than this is ready to be merged cc @wilsonge ;)

**Comment by wilsonge** [comment]
Thanks :)

**Pull request merged**
