### PR TITLE
[4.4] alphabetical sorting string JLIB_FORM_VALIDATE_FIELD_URL_INJECTION_DETECTED

### PR DESCRIPTION
**Pull request by tecpromotion**
With commit https://github.com/joomla/joomla-cms/commit/55f2082f32860eef1810da4a92214a557ad789d6#diff-c49e9cb15f6c5226c3c3e6c457b7d9871239f0779c3b52fa6f95dee7bf551703
the new language string `JLIB_FORM_VALIDATE_FIELD_URL_INJECTION_DETECTED` was added.

### Summary of Changes

alphabetical sorting

### Testing Instructions

.

### Actual result BEFORE applying this Pull Request

JLIB_FORM_VALIDATE_FIELD_RULE_MISSING="Validation Rule missing: %s"
JLIB_FORM_VALIDATE_FIELD_URL_SCHEMA_MISSING="Invalid URL: URL schema is missing in %1$s. Please add one of the following at the beginning: %2$s."
JLIB_FORM_VALIDATE_FIELD_URL_INJECTION_DETECTED="Invalid URL: A code injection has been detected in %1$s."
JLIB_FORM_VALUE_CACHE_APCU="APC User Cache"

### Expected result AFTER applying this Pull Request

JLIB_FORM_VALIDATE_FIELD_RULE_MISSING="Validation Rule missing: %s"
JLIB_FORM_VALIDATE_FIELD_URL_INJECTION_DETECTED="Invalid URL: A code injection has been detected in %1$s."
JLIB_FORM_VALIDATE_FIELD_URL_SCHEMA_MISSING="Invalid URL: URL schema is missing in %1$s. Please add one of the following at the beginning: %2$s."
JLIB_FORM_VALUE_CACHE_APCU="APC User Cache"

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Quy** [comment]
I have not tested this item.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42855">issues.joomla.org/tracker/joomla-cms/42855</a>.</sub>

**Comment by richard67** [comment]
> I have not tested this item.

@Quy Forgotten to select the test result before submitting? Or something wrong with this PR?

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 002f8318ceb2c049436e9ce10ba3731c4899014d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42855">issues.joomla.org/tracker/joomla-cms/42855</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42855">issues.joomla.org/tracker/joomla-cms/42855</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 002f8318ceb2c049436e9ce10ba3731c4899014d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42855">issues.joomla.org/tracker/joomla-cms/42855</a>.</sub>

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
