### PR TITLE
[SEO] rel attribute for external url menu item

### PR DESCRIPTION
**Pull request by Devportobello**
This PR add the ability to set "[rel](http://www.w3schools.com/tags/att_a_rel.asp)" attribute of a link when you setup a menu item type of external url.
SEO purpose.
###### Before patch

Create a menu item type of "External url", go to tab "Link type", there is no way to setup an rel attribute.
###### After patch
- Create a menu item type of "External url", add title, link (eg: https://www.google.fr/) then go to tab "Link type", there is a field "Link Rel Attribute" to setup (eg: Nofollow);
- Save.
- Go to frontend, look at html rendered by a module menu (eg: ul > li > a)

this should seem like this:

``` html
<a href="https://www.google.fr/" rel="nofollow">My external url</a>
```

Try switching different rel value, for "None" there is no rel attribute:

``` html
<a href="https://www.google.fr/">My external url</a>
```

### CODE REVIEW

**Comment by 1apweb** [comment]
I have tested this item :red_circle: unsuccessfully on 3d35139cd06efb02f095ca4670111a464b138b8d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9282">issues.joomla.org/joomla-cms/9282</a>.</sub>

**Comment by 1apweb** [comment]
I have tested this item :white_check_mark: successfully on 3d35139cd06efb02f095ca4670111a464b138b8d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9282">issues.joomla.org/joomla-cms/9282</a>.</sub>

**Comment by shubhamnba2009** [comment]
I have tested this item :white_check_mark: successfully on https://github.com/joomla/joomla-cms/commit/3d35139cd06efb02f095ca4670111a464b138b8d
After applying this patch I tested with every Link attribute(None,Alternate,Author,bookmark,etc) and they were applied succesfully on frontend.

**Comment by grhcj** [comment]
@shubhamnba2009 Please mark your test result as described in https://docs.joomla.org/Testing_Joomla!_patches.

**Comment by shubhamnba2009** [comment]
I have tested this item :white_check_mark: successfully on 3d35139cd06efb02f095ca4670111a464b138b8d<br /><br />After applying this patch I tested with every Link attribute(None,Alternate,Author,bookmark,etc) and they were applied succesfully on frontend.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9282">issues.joomla.org/joomla-cms/9282</a>.</sub>

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 3d35139cd06efb02f095ca4670111a464b138b8d<br /><br />works as described.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9282">issues.joomla.org/joomla-cms/9282</a>.</sub>

**Comment by infograf768** [comment]
RTC. Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9282">issues.joomla.org/joomla-cms/9282</a>.</sub>

**Comment by muhakh** [comment]
I have tested this item :white_check_mark: successfully on 3d35139cd06efb02f095ca4670111a464b138b8d<br /><br />This patch fixes the issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9282">issues.joomla.org/joomla-cms/9282</a>.</sub>

**Comment by infograf768** [comment]
I should not have RTC this...
The values are enough as these are html code and should not be translated:
I.e.
```
<option value="">JNONE</option>
+            <option value="alternate">COM_MENUS_FIELD_VALUE_ALTERNATE</option>
+            <option value="author">COM_MENUS_FIELD_VALUE_AUTHOR</option>
+            <option value="bookmark">COM_MENUS_FIELD_VALUE_BOOKMARK</option>
+            <option value="help">COM_MENUS_FIELD_VALUE_HELP</option>
+            <option value="license">COM_MENUS_FIELD_VALUE_LICENSE</option>
+            <option value="next">COM_MENUS_FIELD_VALUE_NEXT</option>
+            <option value="nofollow">COM_MENUS_FIELD_VALUE_NOFOLLOW</option>
+            <option value="noreferrer">COM_MENUS_FIELD_VALUE_NOREFERRER</option>
+            <option value="prefetch">COM_MENUS_FIELD_VALUE_PREFETCH</option>
+            <option value="prev">COM_MENUS_FIELD_VALUE_PREV</option>
+            <option value="search">COM_MENUS_FIELD_VALUE_SEARCH</option>
+            <option value="tag">COM_MENUS_FIELD_VALUE_TAG</option>
```
should have been

```
+			<option value="">JNONE</option>
+			<option value="alternate">alternate</option>
+			<option value="author">author</option>
+			<option value="bookmark">bookmark</option>
+			<option value="help">help</option>
+			<option value="license">license</option>
+			<option value="next">next</option>
+ 			<option value="nofollow">nofollow</option>
+			<option value="noreferrer">noreferrer</option>
+			<option value="prefetch">prefetch</option>
+			<option value="prev">prev</option>
+ 			<option value="search">search</option>
+ 			<option value="tag">tag</option>
```

**Comment by Bakual** [comment]
You could even just use
````
<option value="">JNONE</option>
<option value="alternate"/>
<option value="author"/>
<option value="bookmark"/>
<option value="help"/>
<option value="license"/>
<option value="next"/>
<option value="nofollow"/>
<option value="noreferrer"/>
<option value="prefetch"/>
<option value="prev"/>
<option value="search"/>
<option value="tag"/>
````

**Comment by infograf768** [comment]
Shall we change this before RC? (Language freeze now)

**Comment by Bakual** [comment]
I think removing them would make sense. And since you already told the translators to not translate them we could still rmeove them I think.

**Comment by Devportobello** [comment]
Did i need to patch this here?

**Comment by brianteeman** [comment]
No this has been merged it should be a new PR

**Comment by Devportobello** [comment]
ok, got issue with my fork, i got on local and origin "Merge remote-tracking branch 'upstream/master'" ... unable to do a PR actually against staging.

**Comment by Bakual** [comment]
See: #9300

**Pull request merged**
