### PR TITLE
filter  unpublished  categories from tagged item

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #5814 .
#### Summary of Changes

added a inner join on the categories table to filter unblished categories
#### Testing Instructions

see #5814

### CODE REVIEW

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on c9563bf78a31388a82b6acac0543e7e899c9055e<br /><br />Works. Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10304">issues.joomla.org/joomla-cms/10304</a>.</sub>

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on c9563bf78a31388a82b6acac0543e7e899c9055e<br /><br />Works as described and fixes the problem.

I would had a line of space before the comment, but that's a detail.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10304">issues.joomla.org/joomla-cms/10304</a>.</sub>

**Comment by roland-d** [comment]
Merged, thanks everybody.

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on bca582205ee0d0e718c60ccafc4cec88d2a6427a<br /><br />just cs<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10304">issues.joomla.org/joomla-cms/10304</a>.</sub>

**Comment by svenbluege** [comment]
Is a category assignment mandatory for a tagged item? If not this fix will cause issues with those items.

**Comment by roland-d** [comment]
@svenbluege Tags do not have any category assignment, it's basically a category system of it's own. UCM content always has a category, so this change is fine.

**Comment by Ssupreme** [comment]
I use Jtags for my personal component, which doesn't use categories, as the result, I have empty list of materials for tag. I had to comment out following "solution".

**Comment by alikon** [comment]
please test #13737

**Pull request merged**
