### PR TITLE
[4.0] Unused file in use section

### PR DESCRIPTION
**Pull request by astridx**
### Summary of Changes
I deleted a unused file in use section

### Testing Instructions
Code review

### CODE REVIEW

**Comment by wilsonge** [comment]
It's being used kinda - the doc block for the constructor needs to be modified to fix the typecasing https://github.com/joomla/joomla-cms/pull/28383/files#diff-95c09e0e76d96872426ab1238596e4a9L43 rather than the import removed

**Review by wilsonge — CHANGES_REQUESTED** [review]
per comment

**Comment by astridx** [comment]
OK

**Comment by astridx** [comment]
Accidentally closed.

**Comment by astridx** [comment]
I changed the PR.

**Comment by wilsonge** [comment]
LGTM!

**Pull request merged**
