### PR TITLE
[4.0] select subfolders

### PR DESCRIPTION
**Pull request by brianteeman**
PR for #29334

Adds the ability to specify sub folders that are not folders on the root as the places I want to store images

### CODE REVIEW

**Comment by Quy** [comment]
It takes 20 seconds to load using WAMP on Windows 10.

**Comment by infograf768** [comment]
And for me, Firefox freezes after a few seconds.

First time I test this plugin. Imho it should prevent choosing any core folder in root except the images one. I.e. it would let choose a custom root folder + images

**Comment by infograf768** [comment]
So, it would be OK if we do
```
					<field
							name="directory"
							type="folderlist"
							default="images"
							label="PLG_FILESYSTEM_LOCAL_DIRECTORIES_DIRECTORY_LABEL"
							folderFilter=""
							exclude="administrator|api|build|components|cache|includes|installation|language|libraries|logs|media|modules|node_modules|plugins|templates|tests|tmp|bin|cli|layouts"
							stripext=""
							recursive="true"
						/>
```

In that case we would get with this PR
Screen Shot 2020-06-20 at 08 06 48

**Comment by brianteeman** [comment]
I am going to close this. It is clearly not practical to have the full recursive folder tree and the suggestion of @infograf768 doesn't work either as it removes the possibility of using media manager on other folders.

**Comment by infograf768** [comment]
It does not make sense to display all core folders in this plugin, but it makes sense to use a custom image folder. So, even if we don't choose recursing, we still should limit the folders displayed in the dropdown to images and custom root folders.

**Comment by infograf768** [comment]
If no one makes a PR, I will.

**Comment by ceford** [comment]
Whilst looking at this, without applying the patch, I added templates to the Select Directories list. Worked as expected. Then I removed templates and Media displayed an internal error:

screen shot 2020-06-20 at 07 56 34

It went away after selecting the Local images folder.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29719">issues.joomla.org/tracker/joomla-cms/29719</a>.</sub>

**Comment by infograf768** [comment]
@ceford 
This means that we do not check for the existence of folders before displaying them.
I think it can be solved, but it is a different issue.

EDIT, looks like we only use
`throw new FileNotFoundException;` and no message/error
or `InvalidPathException` which is empty

**Pull request closed without merging**
