### PR TITLE
[4.0]mod_related strings

### PR DESCRIPTION
**Pull request by brianteeman**
Remove an unused string.

Code review

### CODE REVIEW

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on 3df4481b9cc1d2e33431513a84ee4e15b5c1eb6e<br /><br />Tested successfully in Beta6-dev of 13 December.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31639">issues.joomla.org/tracker/joomla-cms/31639</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 3df4481b9cc1d2e33431513a84ee4e15b5c1eb6e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31639">issues.joomla.org/tracker/joomla-cms/31639</a>.</sub>

**Comment by infograf768** [comment]
rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31639">issues.joomla.org/tracker/joomla-cms/31639</a>.</sub>

**Comment by infograf768** [comment]
tks

**Pull request merged**
