### PR TITLE
Improve Joomla.submitform

### PR DESCRIPTION
**Pull request by Fedik**
Currently `Joomla.submitform` method do not trigger native 'submit' DOM event, that make a lot problem.
And this pull allow to do this.

Some benefits:
- it trigger native 'submit' DOM event
- it use vanilla javascript
- it can trigger HTML5 input validation (by default disabled for BC reason)

**how to test**
put this code into `index.php` in the template:

``` html
<script>
jQuery(document).ready(function($){
    var form = document.getElementById('item-form');
    if(!form){
        return;
    }

    // test native
    var method = document.addEventListener ? 'addEventListener' : 'attachEvent',
        event  = document.addEventListener ? 'submit' : 'onsubmit';
    form[method](event, function(){
        alert('Well done! Push OK!');
    });

    // test jquery, any other library
    $(form).on('submit', function(){
        return confirm('Continue ???');
    });
});
</script>
```

go to edit article form, and try save/cancel/apply ...

**expected result**
after each push on toolbar button you should get 2 popup,
and if on question 'Continue ???' you push "Cancel" form should not be submitted.

**actual result**
nothing happens 

Also this pull require more than 2 simple test,
Need make sure that other forms also works as before,
Need make sure that this work in IE, and other browser that Joomla! promised to support.

I hope this finally solve such problems #6580, #3484, #5914, #6384

### CODE REVIEW

**Comment by dgt41** [comment]
@test ok 
also with code:
```php
JFactory::getDocument()->addScriptDeclaration('
jQuery(document).ready(function() {
	jQuery("#item-form").bind("submit", function() {
		console.log("works");
	});
});
');
```
And with the last iteration of #6207
Nice one @Fedik Thanks!

**Comment by phproberto** [comment]
Cool :+1: 

@test ok

**Comment by Fedik** [comment]
sorry guys, I did one more update,
because if you have form `<form id="adminForm" novalidate>` and try submit it `Joomla.submitform('task', 'adminForm', true);` validation still will be disabled
my last commit fix it

**Comment by dgt41** [comment]
@test still ok

**Comment by dgt41** [comment]
@wilsonge Can I ask for a 3.4.2 milestone here. The reason is that a regression due to removal of mootools needs this, the issue is here: #6207 with a working solution but with a dependency for this code. Thanks

**Comment by dgt41** [comment]
Wow, that was fast! 👍

**Pull request merged**
