### PR TITLE
[5.1] Change redirect url (from headers['Location']) from array to string in CurlTransport

### PR DESCRIPTION
**Pull request by sergeytolkachyov**
The problem was discovered when using HTTP Factory for an external request to the server that performs redirection. The `request` method executes a request to the specified url of the `string` type. If the response code indicates a redirect, then the redirect url is obtained from the `Location` header. After that, another request is executed with a new url. 

image

The redirect url is an instance of the `Uri` class. During the operation of this class, the `UrlHelper` class is called, in which the url is parsed. When making the first request, the url type is a **string**. However, in the case of redirection, **the url is an array with one element**, since `$response->headers['Location']` is passed immediately as an argument. Therefore, when trying to make a second request for a new URl, the error **parse_url() occurs: Argument #1 ($url) must be of type string, array given** in the `UriHelper` class line 38. 

image

This screenshot shows that the content of the Location header is an array, not a string. Which is the reason for the error.
image

The problem was found only when using the `CURLOPT_FOLLOWLOCATION = false` parameter. In this case, Joomla executes the redirect url request on its own.

### Summary of Changes
Change a `$redirect_uri = new Uri($response->headers['Location']);` to `$redirect_uri = new Uri($response->headers['Location'][0]);`

### Testing Instructions
It may not be the most correct, but the fastest way to check the result of this change is to run the query directly from the template `index.php` file.

1. Open it index.php Your frontend template
2. Add the following code to it
```php
use Joomla\CMS\Http\HttpFactory;

$options = new Registry();
$options->set(
	'transport.curl',
	[
		CURLOPT_FOLLOWLOCATION   => false, 
	]
);

$http = (new HttpFactory)->getHttp($options, ['curl', 'stream']);

$url = 'enter here any URL with redirect ';

$response = $http->get($url);
echo '<pre>';
print_r($response->body);
echo '</pre>';

```
3. Run the request (refresh the page) and you will see an error `parse_url(): Argument #1 ($url) must be of type string, array given` 
4.  Apply this PR (download the build and update Joomla 5.0.2) 

image

or in the file `libraries/src/Http/Transport/CurlTransport.php` find the line `$redirect_uri = new Uri($response->headers['Location'])` and replace it to `$redirect_uri = new Uri($response->headers['Location'][0]);`
5. Run the request again (refresh the page again)
6. Error has gone

### Actual result BEFORE applying this Pull Request
An error `parse_url(): Argument #1 ($url) must be of type string, array given` in ROOT\libraries\vendor\joomla\uri\src\UriHelper.php:38

image

### Expected result AFTER applying this Pull Request
Error has gone

### Link to documentations
Please select:
- [x] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [x] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by gug2** [comment]
I have tested this item :white_check_mark: successfully on d1032db65215b90e37bf318a7b9584a32d0e47c3<br /><br />Tested successfully<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42769">issues.joomla.org/tracker/joomla-cms/42769</a>.</sub>

**Comment by progreccor** [comment]
I have tested. Work ok

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42769">issues.joomla.org/tracker/joomla-cms/42769</a>.</sub>

**Comment by sergeytolkachyov** [comment]
@Quy

**Comment by sergeytolkachyov** [comment]
@Quy Joomla 5.1.0 Alpha 4 has been released at 20 February 2024. This pr was RTC 2 weeks ago but stll not merged.

**Comment by HLeithner** [comment]
> @Quy Joomla 5.1.0 Alpha 4 has been released at 20 February 2024. This pr was RTC 2 weeks ago but stll not merged.

RTC doesn't mean that it get automatically merged, it in only means that the pr has 2 tests. But still a maintainer has to check the pr and consider side effects. So it could take some time till a maintainer has time to validate the issue and check if the fix is the correct way.

**Comment by HLeithner** [comment]
releated to this is https://github.com/joomla/joomla-cms/pull/43130/files#diff-eaa7b598c95837c0e0230852d37007e28938d2bfe13048b42462ce106803447fL133 on Pr #43130

**Comment by LadySolveig** [comment]
Thank you @sergeytolkachyov and also for testing @gug2 @progreccor

**Pull request merged**
