### PR TITLE
[3.5] [imp] Add the ability to use a custom CSS file with beez3 & make the other similiar checks consistend see #4211

### PR DESCRIPTION
**Pull request by zero-24**
This backports the `user.css` that we have in protostar back to beez3. For the backed we can use a custom.css file.
#### How to test
- set beez3 as default template
- access the frontend
- see all is good.
- apply the patch
- add a user.css with custom styling to this folder `/templates/bezz3/css/user.css`
- reload the page
- see that the file gets loaded.
#### Other changes

Make the checks consistent and use `if (file_exists($file) && filesize($file) > 0)` and `$doc->addStyleSheetVersion($file);`

### CODE REVIEW

**Comment by brianteeman** [comment]
The title says Beez but there are changes in all 4 templates?

**Comment by zero-24** [comment]
yes as the "new feature" is only in beez and the others are just changed to be consistend. But to avoid confusing i will fix the title

**Comment by SiteOp** [comment]
Test Beez/Protostar. It works.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7621">issues.joomla.org/joomla-cms/7621</a>.</sub>

**Comment by crommie** [comment]
I have tested this item :white_check_mark: successfully on bb1f1308c0d43a5708c3701663d73ecf3e8cc5d3<br /><br />Tested. Works as described.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7621">issues.joomla.org/joomla-cms/7621</a>.</sub>

**Comment by crommie** [comment]
I have tested this item :white_check_mark: successfully on bb1f1308c0d43a5708c3701663d73ecf3e8cc5d3<br /><br />Tested. Works as described.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7621">issues.joomla.org/joomla-cms/7621</a>.</sub>

**Comment by crommie** [comment]
I have tested this item :white_check_mark: successfully on bb1f1308c0d43a5708c3701663d73ecf3e8cc5d3<br /><br />Tested. Works as described.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7621">issues.joomla.org/joomla-cms/7621</a>.</sub>

**Comment by crommie** [comment]
I have tested this item :white_check_mark: successfully on bb1f1308c0d43a5708c3701663d73ecf3e8cc5d3<br /><br />Tested. Works as described.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7621">issues.joomla.org/joomla-cms/7621</a>.</sub>

**Comment by snarf007** [comment]
I have not tested this item.<br /><br />Applied patch and created the user.css file via the template manager.
Added the following code in the css file:
body {
    background: pink;
}

Result a pink backgound in the frontend.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7621">issues.joomla.org/joomla-cms/7621</a>.</sub>

**Comment by snarf007** [comment]
I have tested this item :white_check_mark: successfully on bb1f1308c0d43a5708c3701663d73ecf3e8cc5d3<br /><br />Applied patch and created the user.css file via the template manager.
Added the following code in the css file:
body {
    background: pink;
}

Result a pink backgound in the frontend.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7621">issues.joomla.org/joomla-cms/7621</a>.</sub>

**Comment by zero-24** [comment]
RTC. Thanks for testing!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7621">issues.joomla.org/joomla-cms/7621</a>.</sub>

**Comment by roland-d** [comment]
Thanks all, change has been merged.

**Comment by zero-24** [comment]
Thnaks

**Pull request merged**
