### PR TITLE
[4.0] FilelistField/FolderlistField conflicting filter attribute

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue #14899 .

### Summary of Changes

This replaces conflicting `filter` attribute in `Joomla\CMS\Form\Field\FilelistField` and `Joomla\CMS\Form\Field\FolderlistField` with new `fileFilter` and `folderFilter` attributes, respectively.

### Testing Instructions

Code review is fine, I guess. Or add filelist/folderlist field to a form, set fileFilter/folderFilter attribute and check that files/folders are filtered correctly. E.g.:

```
<field
	name="image"
	type="filelist"
	fileFilter="\.png$"
	directory="images/banners"
/>
```

### Documentation Changes Required

Yes. B/C break: existing forms using affected fields need to be updated with new attributes. Fields extending these fields need to be updated.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on e0ce991091f175ae787d3156c0bf7674a009ef9c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24977">issues.joomla.org/tracker/joomla-cms/24977</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on e0ce991091f175ae787d3156c0bf7674a009ef9c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24977">issues.joomla.org/tracker/joomla-cms/24977</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24977">issues.joomla.org/tracker/joomla-cms/24977</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by wilsonge** [comment]
https://docs.joomla.org/Filelist_form_field_type
https://docs.joomla.org/Folderlist_form_field_type
https://docs.joomla.org/Potential_backward_compatibility_issues_in_Joomla_4#Form

Docs pages updated

**Pull request merged**
