### PR TITLE
[4.0] empty state mod_latest and mod_popular

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #34370 

### Before
image

### After
image

### CODE REVIEW

**Comment by infograf768** [comment]
Same _issue_ for popular articles

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on ac3652cfd92bcf8a887171acf6a61f3adad33a06<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34373">issues.joomla.org/tracker/joomla-cms/34373</a>.</sub>

**Comment by brianteeman** [comment]
Updated to include mod_popular

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 9305f367b1d580076c63c5a7a29c94e48a47dfcd<br /><br />Test on mod_latest and mod_popular.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34373">issues.joomla.org/tracker/joomla-cms/34373</a>.</sub>

**Comment by Abernyte-Git** [comment]
I have tested this item :white_check_mark: successfully on 9305f367b1d580076c63c5a7a29c94e48a47dfcd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34373">issues.joomla.org/tracker/joomla-cms/34373</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34373">issues.joomla.org/tracker/joomla-cms/34373</a>.</sub>

**Comment by PhilETaylor** [comment]
NO! DONT MERGE THIS! ITS WRONG...

**Comment by richard67** [comment]
Back to pending.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34373">issues.joomla.org/tracker/joomla-cms/34373</a>.</sub>

**Comment by richard67** [comment]
@PhilETaylor Could you provide details about what's wrong?

**Comment by PhilETaylor** [comment]
I screwed up in https://github.com/joomla/joomla-cms/pull/34319 and despite three people testing - no one realised.

**Comment by PhilETaylor** [comment]
Actually never mind, Im going to leave my screw up there, and this one can be merged. We dont have many modules with empty state at the moment, and the `textSuffix` provided is not actually being used (we lost those language strings along the way somehow...) 

What should happen - by design - was that the mod_popular empty state should say something like "There are no popular articles at the moment" and the mod_latest should say "There are no latest articles at the moment" - whereas this PR will make them both say "No articles have been created yet" which is technically true, but the idea was to make the empty state module layout generic and that it can be reused, with `textPrefix` and `textSuffix` to provide different language strings based on the module purpose. 

No idea where the two custom language strings went, but now that they have done, removing the  `textSuffix` from the two modules will do, and my screw up is actually good as it will allow  `textSuffix` to be used correctly in the future if any other modules want to use it.

Please set back to RTC.

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34373">issues.joomla.org/tracker/joomla-cms/34373</a>.</sub>

**Comment by PhilETaylor** [comment]
https://github.com/joomla/joomla-cms/pull/33472#issuecomment-830688621  

> I have removed the module override language strings for the empty state to allow them to inherit from the components empty state language tites.

**Comment by brianteeman** [comment]
The layout is still generic and the prefix and suffix can still be used. This PR doesnt effect that

**Comment by chmst** [comment]
Thanks

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
