### PR TITLE
Remove Karma

### PR DESCRIPTION
**Pull request by brianteeman**
#11420 added a file to the root for the javascript tests but it was not added to the list of files to be excluded from the build

### CODE REVIEW

**Comment by dgt41** [comment]
I have tested this item :white_check_mark: successfully on ae16a2d213650e1b2169e35f295c56edad7ac109<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11774">issues.joomla.org/joomla-cms/11774</a>.</sub>

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on ae16a2d213650e1b2169e35f295c56edad7ac109<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11774">issues.joomla.org/joomla-cms/11774</a>.</sub>

**Comment by zero-24** [comment]
Rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11774">issues.joomla.org/joomla-cms/11774</a>.</sub>

**Comment by zero-24** [comment]
Thanks @rdeutz :smile:

**Comment by brianteeman** [comment]
Why thanks @rdeutz ?

**Comment by brianteeman** [comment]
Never mibd

**Comment by zero-24** [comment]
Thanks @brianteeman @dgt41 @wilsonge :smile:

**Pull request merged**
