### PR TITLE
[staging]Wrong link for Help in User Actions Log Options

### PR DESCRIPTION
**Pull request by wojsmol**
Pull Request for Issue https://github.com/joomla/joomla-cms/pull/30594#issuecomment-688768863 .

### Summary of Changes

Help link fix

### Testing Instructions
Go to System -> Global Configuration -> User Actions Log
Select the Help button

### Actual result BEFORE applying this Pull Request
The Help screen for the User Actions Log page.

### Expected result AFTER applying this Pull Request
A Help screen for the Options page

### Documentation Changes Required

N/A

Backport of https://github.com/joomla/joomla-cms/pull/30594 to staging

### CODE REVIEW

**Comment by ChristineWk** [comment]
Hours ago I already tested above. Tried now again.

The result before & after Patch is:
Help
Company Actionlogs
User Actions Log interface
etc.
I'm not sure, maybe the reason is, that I hv a (former) updated Joomla to: 3.9.21-rc
Sorry about. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30595">issues.joomla.org/tracker/joomla-cms/30595</a>.</sub>

**Comment by wojsmol** [comment]
@ChristineWk I tested this on 3.9.21 and it's working as expected.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 23a2ace57d9bb6983121eab2b7a4cee01bf81341<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30595">issues.joomla.org/tracker/joomla-cms/30595</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 23a2ace57d9bb6983121eab2b7a4cee01bf81341<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30595">issues.joomla.org/tracker/joomla-cms/30595</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30595">issues.joomla.org/tracker/joomla-cms/30595</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
