### PR TITLE
[4.3] Remove an extra space on the XTD-article

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/39988 .

### Testing Instructions

Click on Article button in article edit mode and choose any article. And see the code of inserted article:
<a  href="index.php?option=com_content&view=article&id=314&catid=15">Creating a Multilingual site on Joomla</a>

### Actual result BEFORE applying this Pull Request

There is extra space <a href ...

### Expected result AFTER applying this Pull Request

There is NO extra space <a href ...

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on bce76b1d32e105164f2e85588a28dd13d4dd7431<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39989">issues.joomla.org/tracker/joomla-cms/39989</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on bce76b1d32e105164f2e85588a28dd13d4dd7431<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39989">issues.joomla.org/tracker/joomla-cms/39989</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39989">issues.joomla.org/tracker/joomla-cms/39989</a>.</sub>

**Comment by roland-d** [comment]
Thank you

**Pull request merged**
