### PR TITLE
[4.3] package.json version bump

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue # .

### Summary of Changes
package.json must contain a semver versioning number. This PR updates the `build\bump.php` script so that the version in the package.json is updated correctly. Currently the version number is static at 4.0.0

also removed the comment about updating the copyright date as we dont do that anymore

### Testing Instructions
Code review
or
`php build\bump.php -v 9.9.9`

### Actual result BEFORE applying this Pull Request
contents of package.json
```
{
  "name": "joomla",
  "version": "4.0.0",
  "description": "Joomla CMS",
  "license": "GPL-2.0-or-later",
```

### Expected result AFTER applying this Pull Request
```
{
  "name": "joomla",
  "version": "9.9.9",
  "description": "Joomla CMS",
  "license": "GPL-2.0-or-later",
```

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by laoneo** [comment]
You can do that also without regex https://stackoverflow.com/a/70034831. Not sure if you need to regenerate the lock file afterwards as well.

**Comment by laoneo** [comment]
Or load and write the json with the native PHP json functions.

**Comment by brianteeman** [comment]
> You can do that also without regex https://stackoverflow.com/a/70034831.

I am aware of that but it makes no sense to do it this way from inside a php script. At the end of the day this is just following the codestyle of all the other actions the file.

**Comment by laoneo** [comment]
Makes sense, but json_encode and json_decode would probably be safer to produce valid JSON.

**Comment by laoneo** [comment]
@brianteeman are you going to change the code to use the json functions from PHP. It is much safer then instead of dealing with regex.

**Comment by brianteeman** [comment]
no i am not going to change it. makes no sense to me when everything else in the file is using regex.

**Pull request closed without merging**
