### PR TITLE
[4] remove unused import

### PR DESCRIPTION
**Pull request by PhilETaylor**
Codereview

### CODE REVIEW

**Comment by bembelimen** [comment]
> 
> 
> Codereview

After the last "codereview" PRs, wouldn't it be better to write test instruction how people can test it?

**Comment by PhilETaylor** [comment]
Test instructions

1) Learn PHP
2) Open Eye
3) Use a decent IDE
4) Have maintainers check code before its merged
5) USE AUTOMATION
6) Have Unit Tests
7) Have Integration Tests. 

8... Bedtime.

**Comment by PhilETaylor** [comment]
> After the last "codereview" PRs, wouldn't it be better to write test instruction how people can test it?

and thanks... the "last code review PR" that screwed up Joomla was TESTED by two other people, and (one assumes) a maintainer who merged it... so.. yeah... if you are going to throw shade at least throw it at the processes and not the person.

**Comment by PhilETaylor** [comment]
And for the record, I apologised - a lot - for my own screw up - and took ownership of the problem I caused.

**Comment by bembelimen** [comment]
> 
> 
> Test instructions
> 
>     1. Learn PHP
> 
>     2. Open Eye
> 
>     3. Use a decent IDE
> 
>     4. Have maintainers check code before its merged
> 
>     5. USE AUTOMATION
> 
>     6. Have Unit Tests
> 
>     7. Have Integration Tests.
> 
> 
> 8... Bedtime.

Translated: Activate the metismenu-dropdown layout in mod_menu and check if it still works.

**Comment by PhilETaylor** [comment]
> Translated: Activate the metismenu-dropdown layout in mod_menu and check if it still works.

What a complete waste of time. Get real.

**Comment by joomdonation** [comment]
I have tested this item :white_check_mark: successfully on 3c18c369e7a7ae10a6ff7a922bd542dcd7208f96<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35409">issues.joomla.org/tracker/joomla-cms/35409</a>.</sub>

**Comment by joomdonation** [comment]
> After the last "codereview" PRs, wouldn't it be better to write test instruction how people can test it?

@bembelimen That last **codereview** was really an accident. For that, event if we did real test (I did), we might not see the problem. The reason is because that modified file is only used for next update which not many of us here know.

> What a complete waste of time. Get real. We are meant to be PHP Developers, if we cannot peer review such a change then this project has ZERO chance of making a future for itself.

@PhilETaylor Agree. The only thing I want to ask is next time, could you please consider putting all the change like this into a single PR ? Like your 3 last PRs could be merged into single one. That should save time of all of us. Thanks !

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 3c18c369e7a7ae10a6ff7a922bd542dcd7208f96<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35409">issues.joomla.org/tracker/joomla-cms/35409</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35409">issues.joomla.org/tracker/joomla-cms/35409</a>.</sub>

**Comment by richard67** [comment]
Thanks.

**Pull request merged**
