### PR TITLE
Remove trash button from article toolbar

### PR DESCRIPTION
**Pull request by bembelimen**
Pull Request for Issue #21527 .

### Summary of Changes
As with the workflow, there is no direct trash function anymore but the trash transition will be defined with a workflow itself.

### Testing Instructions
Look into the article list (backend)

### Expected result
No trash button anymore

### Actual result
Trashbutton without functionality

### CODE REVIEW

**Comment by brianteeman** [comment]
NO NO NO - this is not a fix

**Comment by brianteeman** [comment]
Seriously of you think that removing the delete button is the solution then I really give up.

**Comment by brianteeman** [comment]
This solution is as sensible as me doing a pull request to remove workflows as the way to solve all the issues with it.

**Comment by bembelimen** [comment]
As there is no "trash" state anymore, that is indeed the solution, because the article have to follow the execution flow, no direct jump (same for published/unpublished)

**Comment by brianteeman** [comment]
Congratulations then on breaking every component in joomla

**Comment by infograf768** [comment]
@bembelimen 

We can evidently trash ONE article at a time via the status of the article itself, but we can't trash anymore multiple articles at the same time, which indeed is not acceptable.

Same for other states...

**Comment by bembelimen** [comment]
@infograf768 as I said above, there is absolutly no sense in having a "publish", "unpublish" or "trash" button anymore, because you (as "the user") have to follow the workflow sequence and there are a lot of scenarios, where the article in the current status has no publish/unpublish/trash route at the moment. Or you have multiple trash opportunities at the same time, so that makes the trash button useless again.

But: if you (as "the user" again) want to skip the sequence and trash multiple articles as "batch", then you can now use the batch functionallity. There is a new option for batching multiple articles with a new state.

**Comment by brianteeman** [comment]
This is just plain wrong. No other way to put it. In fact even with this stupid and broken workflow code one can still have a delete button. You chose to reSolve the issue by simply deleting the button instead of adopting the sensible solution of checking the workflow to see if the user is able to delete something and then deciding to display the button or not.

**Comment by brianteeman** [comment]
Let's look at another scenario. Almost every component that exists in the joomlasphere has delete, publish and unpublished buttons in the toolbar. Unless they rewrite their code to use your workflow code they will all have those buttons. So after 15 years of an expected button that no one has ever suggested changing you are removing it, without consultation, discussion or testing just because it was easier for you to delete it than to fix it.

**Comment by infograf768** [comment]
Also, if we keep workflow in core, there will be —I hope— a way to disable it completely, which means that the toolbar buttons should remain in that case.

**Comment by bembelimen** [comment]
The trash button is still unnecessary at this position, because it's now in the dropdown menu. So the button can still be removed with this PR.

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 5e51aec3b500aa5eb97acde799102f0588995b35<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21532">issues.joomla.org/tracker/joomla-cms/21532</a>.</sub>

**Comment by brianteeman** [comment]
so how do you trash multiple articles at once and how do you address the UI issue where every other list view has a trash button but com_content does not

**Comment by bembelimen** [comment]
Why does com_content have no trash button?
This PR just removed the non-working button...

**Comment by infograf768** [comment]
> so how do you trash multiple articles at once

Select articles, click on Change Status TOOLBAR button and select Trash

**Comment by infograf768** [comment]
@wilsonge
I guess this can go in.

**Pull request merged**
