### PR TITLE
Solved the category order list

### PR DESCRIPTION
**Pull request by nawarajshah**
Pull Request for Issue #39532 .

### Summary of Changes
Now the categories while creating the article will appear in an ordered manner

### Testing Instructions
make sure you have sufficient categories then while creating the article you can see the categories in order manner

### Actual result BEFORE applying this Pull Request
Screenshot (145)

### Expected result AFTER applying this Pull Request
Screenshot (144)

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :red_circle: unsuccessfully on ca5058886846820cd9953efb3caae0ec1b32770c<br /><br />does not take into account any subcategories when sorted in this way<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40631">issues.joomla.org/tracker/joomla-cms/40631</a>.</sub>

**Comment by brianteeman** [comment]
cat

**Comment by nawarajshah** [comment]
> cat

i understand the problem
i also see that is not working for the subcategory
also, is necessary to sort them?
thank you for pointing out that mistake even though my answer is not the correct answer for the issue posted

**Comment by HLeithner** [comment]
Thanks for you contribution, as brian mentioned in the referenced issue this PR has unrelated. 

For this PR, the ordering now is how the user ordered the categories, this is expected behavior. I'm closing the pr for now. To solve the issue you referenced please open a new PR.

thanks

**Pull request closed without merging**
