### PR TITLE
[4.0] namespace

### PR DESCRIPTION
**Pull request by brianteeman**
Minor tweaks after merge https://github.com/joomla/joomla-cms/commit/964d90f3a6cc5ca7d195599788dec09f5f72ffd1

code review

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on c7b00b52c46b00110d3e880ca106127268eda5d7<br /><br />Code review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33511">issues.joomla.org/tracker/joomla-cms/33511</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on c7b00b52c46b00110d3e880ca106127268eda5d7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33511">issues.joomla.org/tracker/joomla-cms/33511</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33511">issues.joomla.org/tracker/joomla-cms/33511</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
