### PR TITLE
[4.0] Bump PHP minimum to 7.2.5

### PR DESCRIPTION
**Pull request by zero-24**
Pull Request for Motion: PROD2019/012

### Summary of Changes

As of https://volunteers.joomla.org/departments/production/reports/1128-production-dept-meeting-november-05-2019 (PROD2019/012) the minimum PHP for Joomla 4.0 is 7.2.5

Minimum PHP Version for Joomla 4.0 set to PHP 7.2.5 (PROD2019/012)
Proposed by George Wilson
The motion passed with unanimous consent.

### Testing Instructions

Try to install on a php version lower than 7.2.5

### Expected result

error message

### Actual result

minimum is 7.2.0

### Documentation Changes Required

This needs to be updated in the docs. cc @wilsonge

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 9cf4f5e9597c6194d48e0e703f13439522b10c61<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27191">issues.joomla.org/tracker/joomla-cms/27191</a>.</sub>

**Comment by mbabker** [comment]
Please don’t link external things as an issue, even if it is a Joomla owned resource.  More than once a pull request has been based on something external (like a Twitter thread or a closed access Facebook group) and the external source is removed, which also removes any context of the issue report.

An issue tracker should be a canonical source of information about a project’s issues and changes.  Relying on external sources is a great way to break that information history.

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 9cf4f5e9597c6194d48e0e703f13439522b10c61<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27191">issues.joomla.org/tracker/joomla-cms/27191</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27191">issues.joomla.org/tracker/joomla-cms/27191</a>.</sub>

**Comment by zero-24** [comment]
@mbabker something like i did above now? Or do you have something else in mind?

**Comment by HLeithner** [comment]
Thanks Tobias

**Comment by mbabker** [comment]
@zero-24 yeah, that works.  Having the link is fine if you want to refer to a source for more info, but it's a good idea to make sure the most pertinent bits are inlined into the issue just so things don't get lost.

**Pull request merged**
