### PR TITLE
Meter field using JLayouts

### PR DESCRIPTION
**Pull request by dgrammatiko**
#### Separate logic/ output

Base work for better templating
#### Summary of Changes

Introduce a  layout for this field
#### Testing Instructions

Apply patch and rename any backend input to meter
eg

``` XML
<field name="mytextvalue" type="meter" default="Some text" label="Enter some text" description=""  />
```

Also consult: https://docs.joomla.org/Standard_form_field_types

### CODE REVIEW

**Comment by RonakParmar** [comment]
I have changed article title field text to meter and got warning. please check screen-screen shot 2016-07-05 at 00 01 02dump for that.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11007">issues.joomla.org/joomla-cms/11007</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 220de10a29e58534da9c2eab6d52095105e3676e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11007">issues.joomla.org/joomla-cms/11007</a>.</sub>

**Comment by brianteeman** [comment]
@ronakParmar did you make sure the field had all the values https://docs.joomla.org/Meter_form_field_type<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11007">issues.joomla.org/joomla-cms/11007</a>.</sub>

**Comment by RonakParmar** [comment]
I have tested this item :white_check_mark: successfully on 220de10a29e58534da9c2eab6d52095105e3676e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11007">issues.joomla.org/joomla-cms/11007</a>.</sub>

**Comment by RonakParmar** [comment]
@brianteeman  Thanks for the URL, works fine.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11007">issues.joomla.org/joomla-cms/11007</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11007">issues.joomla.org/joomla-cms/11007</a>.</sub>

**Comment by wilsonge** [comment]
Merged with d04024a - thanks!

**Pull request closed without merging**
