### PR TITLE
[4.1] Action Log comments

### PR DESCRIPTION
**Pull request by brianteeman**
English grammar corrections

code review only

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 7c1f3cb738ad36da521e8d1653516f6fc2dc3755<br /><br />By review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37558">issues.joomla.org/tracker/joomla-cms/37558</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 7c1f3cb738ad36da521e8d1653516f6fc2dc3755<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37558">issues.joomla.org/tracker/joomla-cms/37558</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37558">issues.joomla.org/tracker/joomla-cms/37558</a>.</sub>

**Comment by Quy** [comment]
Thanks.

**Pull request merged**
