### PR TITLE
[4.0] npm update

### PR DESCRIPTION
**Pull request by brianteeman**
Before this update there were quite a few vulnerabilities

+ babel-loader@8.2.2
+ eslint-config-airbnb-base@14.2.1
+ cross-env@7.0.3
+ @babel/preset-env@7.12.11
+ @babel/core@7.12.10
+ @babel/plugin-transform-runtime@7.12.10
+ file-saver@2.0.5
+ eslint-plugin-vue@7.5.0
+ ini@1.3.8
+ jquery-migrate@3.3.2
+ selenium-standalone@6.23.0
+ fs-extra@9.1.0
+ tinymce@5.6.2
+ vuex@3.6.0
+ vue-loader@15.9.6
+ vuex-persistedstate@3.2.0
+ eslint@7.18.0
+ codemirror@5.59.2
+ webpack@4.46.0
+ stylelint@13.9.0
+ sass@1.32.5
+ @fortawesome/fontawesome-free@5.15.2

added 113 packages from 97 contributors, removed 79 packages, updated 95 packages, moved 3 packages and audited 1519 packages in 50.73s

found 0 vulnerabilities

### Notes
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.

### CODE REVIEW

**Comment by dgrammatiko** [comment]
@brianteeman please move the font awesome to the deps, it's not a dev dependency

**Comment by dgrammatiko** [comment]
Thanks, this was something that I tried to commit in various PRs but I guess they were the ones rejected 😄

**Comment by wilsonge** [comment]
Thanks! Happy to merge this with drone passing. Although npm audit didn't give any errors on my macbook which is kinda weird

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
