### PR TITLE
[5.1] Fix Fontend language multilingual without compatibility plugin

### PR DESCRIPTION
**Pull request by bembelimen**
### Summary of Changes
Fix wrong field name for multilingual sites in user profile

### Testing Instructions
- Disable the "Behaviour - Backward Compatibility" plugin
- Enable the "System - Language Filter" plugin
- Check User profile (frontend/backend)

### Actual result BEFORE applying this Pull Request
- Language field is a text field

### Expected result AFTER applying this Pull Request
- Language field is a select

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on a1a927a60432be68844142aa6a05c6318b66b9b7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43791">issues.joomla.org/tracker/joomla-cms/43791</a>.</sub>

**Comment by richard67** [comment]
@bembelimen Do you know what this is good for, and is it somehow related to the issue? https://github.com/joomla/joomla-cms/blob/4.4-dev/libraries/src/Form/Field/FrontendlanguageField.php#L26-L32

**Comment by dautrich** [comment]
I have tested this item :white_check_mark: successfully on a1a927a60432be68844142aa6a05c6318b66b9b7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43791">issues.joomla.org/tracker/joomla-cms/43791</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43791">issues.joomla.org/tracker/joomla-cms/43791</a>.</sub>

**Comment by bembelimen** [comment]
> @bembelimen Do you know what this is good for, and is it somehow related to the issue? https://github.com/joomla/joomla-cms/blob/4.4-dev/libraries/src/Form/Field/FrontendlanguageField.php#L26-L32

Should not have any effect on it

**Comment by richard67** [comment]
> > @bembelimen Do you know what this is good for, and is it somehow related to the issue? https://github.com/joomla/joomla-cms/blob/4.4-dev/libraries/src/Form/Field/FrontendlanguageField.php#L26-L32
> 
> Should not have any effect on it

@bembelimen Should it be changed to `public $type = 'Frontendlanguage';` in 6.0-dev so it is like for the other fields? Or should that `$type` variable be deprecated for all fields because it has no effect at all?

**Comment by brianteeman** [comment]
> > > @bembelimen Do you know what this is good for, and is it somehow related to the issue? https://github.com/joomla/joomla-cms/blob/4.4-dev/libraries/src/Form/Field/FrontendlanguageField.php#L26-L32
> > 
> > 
> > Should not have any effect on it
> 
> @bembelimen Should it be changed to `public $type = 'Frontendlanguage';` in 6.0-dev so it is like for the other fields? Or should that `$type` variable be deprecated for all fields because it has no effect at all?

it confused me

**Comment by LadySolveig** [comment]
Thanks @bembelimen and also for testing and review @brianteeman @dautrich @richard67

**Pull request merged**
