### PR TITLE
[4.1] Logout Direct

### PR DESCRIPTION
**Pull request by brianteeman**
This is my fault for changing the value of JDEFAULT to "home" some time ago although for consistency that should never have been the string used here.

### Summary of Changes
Use the correct string so it is clear if there is a menu item selected or not

### Testing Instructions
Create a menu item of type Users-> Logout (do not save or edit anything)
Go to the Options tab

### Actual result BEFORE applying this Pull Request
image

### Expected result AFTER applying this Pull Request
image

### CODE REVIEW

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on f7cbd1bdec5bb792acfc9b41f30bb8daa264ee0d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37761">issues.joomla.org/tracker/joomla-cms/37761</a>.</sub>

**Comment by Webdongle** [comment]
I have tested this item :white_check_mark: successfully on f7cbd1bdec5bb792acfc9b41f30bb8daa264ee0d<br /><br />Success<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37761">issues.joomla.org/tracker/joomla-cms/37761</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37761">issues.joomla.org/tracker/joomla-cms/37761</a>.</sub>

**Comment by Quy** [comment]
Thanks

**Pull request merged**
