### PR TITLE
Color of the error message (Admin-menu)

### PR DESCRIPTION
**Pull request by akritianand**
Pull Request for Issue #17729.

### Summary of Changes
Color of the error message after attempting to delete a Admin-menu - SOLVED
Changed 'alert-success' to 'alert-danger' in line 14

### CODE REVIEW

**Comment by akritianand** [comment]
I have tested this item :white_check_mark: successfully on 47b0630bfcf0491c34316d5fb408362a3f0988b7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17734">issues.joomla.org/tracker/joomla-cms/17734</a>.</sub>

**Comment by ghost** [comment]
@akritianand test own Pull Request don't count as it is expected that Dev. test PR before send on Github.

**Comment by ghost** [comment]
I have tested this item :red_circle: unsuccessfully on 47b0630bfcf0491c34316d5fb408362a3f0988b7

Applying PR in Patchtester got red Message "Patch successfully applied" as it is usually green:


bildschirmfoto 2017-08-27 um 13 58 26

bildschirmfoto 2017-08-27 um 13 59 58

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17734">issues.joomla.org/tracker/joomla-cms/17734</a>.</sub>

**Comment by brianteeman** [comment]
This is obviously not correct as it changes all messages

**Comment by C-Lodder** [comment]
You need to change type of that specific alerts. What you PR does it change all default (`message`) alerts to red.

**Comment by akritianand** [comment]
I am so sorry. I'll correct it ASAP.

**Comment by infograf768** [comment]
The code is in 2 places.
It uses setError()

https://github.com/joomla/joomla-cms/blob/staging/libraries/src/Table/MenuType.php#L195

https://github.com/joomla/joomla-cms/blob/staging/libraries/src/Table/MenuType.php#L212

**Pull request closed without merging**
