### PR TITLE
Advanced MSSQL query workaround for  limit, offset and for sql with aggregate functions

### PR DESCRIPTION
**Pull request by csthomas**
Competition for https://github.com/joomla/joomla-cms/pull/11938

### Summary of Changes
Fix various  problems with sqlsrv queries:

* Add alias to column (or expression) which does not have it, but it is required if query will use `OFFSET`, which means use wrapped query to emulate offset. **Every column in `SELECT` statement required alias if it is placed in subquery.**
* If `SELECT` contains a wild column `x.*` then load and put all columns from x table to `GROUP BY`
* If `GROUP BY` contains alias to (column or expression) then replace it with expression. 
Ex:
`SELECT LOWER(name) AS name, catid AS cc, count(*) ... GROUP BY name, cc`
will be replaced to
`SELECT LOWER(name) AS name, count(*) ... GROUP BY LOWER(name), catid`
* Add column from `ORDER BY` to GROUP BY if not yet exists. If this is an alias then replace it with expression as mentioned earlier.
* Add columns from `SELECT` to `GROUP BY` if missing (related to mysql `ONLY_FULL_GROUP_BY`). Probably it would be better to fix joomla queries than create such workaround.
Example of fixed query:
`SELECT id, name, COUNT(*) FROM #__x GROUP BY id`
    will be replaced by:
`SELECT id, name, COUNT(*) AS columnAlias0 FROM #__x GROUP BY id, name`

Fixed issue: https://github.com/joomla/joomla-cms/issues/11279

Removes notices, warnings and errors from:
* /administrator/index.php?option=com_banners
* /administrator/index.php?option=com_categories&extension=com_banners
* /administrator/index.php?option=com_banners&view=clients
* /administrator/index.php?option=com_finder&view=maps
* /administrator/index.php?option=com_categories&extension=com_newsfeeds
* /administrator/index.php?option=com_categories&extension=com_contact
* /administrator/index.php?option=com_postinstall

Fix issue with Popular Tags module on the front end.

### Testing Instructions
Be sure that you can see PHP Notices.
Test above links and module Popular Tags before and after patch.

* Install a new staging version of joomla (without sample data because currently joomla on mssql is broken - menu assets)
* Create a category and two articles with a few tags.
* Be sure that you have module Popular Tags enabled (ex. position-7)
* Go to the front page
* I should see some similar sql error as on image but with less details

joomla_win_3 6 6

### Documentation Changes Required
No

### CODE REVIEW

**Comment by csthomas** [comment]
@waader Which URL page or sql query did not work?

**Comment by waader** [comment]
With current staging, testing data and your patch applied just go to the frontend. There are a lot of notices (something in the module helper). I have already shutdown my test pc, so I could give you the exact messages tomorrow.

**Comment by csthomas** [comment]
I have found a few errors and I fixed it.
Please inform me if you find some errors.

**Comment by alikon** [comment]
i'm testing on backend and seems ok, unfortunately even if is not caused by  this pr i see issues on frontend too as reported by @waader 
can you have a look at frontend with current staging  and testing data
thanks in advance

**Comment by waader** [comment]
With testing data installed frontend gives an "404 Component not found" error. Starting with index.php?option=com_content the page loads. The module helper notices are also present and no modul content is displayed.

In backend I get an error when deleting Banner Tracks:
An expression of non-boolean type specified in a context where a condition is expected, near ')'.

**Comment by waader** [comment]
Can you have a look at Smart Search > Content Maps:

[Microsoft][SQL Server Native Client 11.0][SQL Server]Column "d.branch_title" is invalid in the ORDER BY clause because it is not contained in either an aggregate function or the GROUP BY clause.

**Comment by csthomas** [comment]
I will take a look. Are you sure do you use the last commit in this PR, I added it today morning (night)?

**Comment by waader** [comment]
I have several patches for mssql installed now and also this patch and now the problem with content map has gone away. 

Frontend is broken nonetheless.

**Comment by csthomas** [comment]
On test database I have found two 404 links because mssql table does not have 2 articles for:
* Popular Tags (Alias: popular-tags)
* Similar Tags (Alias: similar-tags)

- one in news-feed - ??
- and search component has some error. ??

but home page work for me ok.

**Comment by wilsonge** [comment]
@waader and @alikon is this patch in a mergable state?

**Comment by csthomas** [comment]
This PR have to wait for #13585
I have to remove `escaping` chars from this PR which was done in #13585
After #13585 will be merged then it can go to tests and merge.

**Comment by csthomas** [comment]
There is also PR https://github.com/joomla/joomla-cms/pull/13895 which has part of code from this PR and could be merged probably by code review (unit tests pass).

**Comment by csthomas** [comment]
This PR is ready to test:)

**Comment by waader** [comment]
I tested with current staging with no samples data installed and clicked through the cms. I did not work out if it has anything to do with this patch:

Frontend - Home:
 Serialization of 'Closure' is not allowed 

Backend:
Multilingual Associations
Warning: ksort() expects parameter 2 to be long, string given in C:\Program Files (x86)\Ampps\www\joomla37\administrator\components\com_associations\models\fields\itemtype.php on line 57

Smart Search Indexer:
[Microsoft][SQL Server Native Client 11.0][SQL Server]Unclosed quotation mark after the character string 'O:19:"FinderIndexerResult":19:{s:11:"'.

Manage > Install Languages
[Microsoft][SQL Server Native Client 11.0][SQL Server]Unclosed quotation mark after the character string 'O:19:"FinderIndexerResult":19:{s:11:"'.

**Comment by wilsonge** [comment]
Frontend issue is a separate issue with a fix here: https://github.com/joomla/joomla-cms/pull/14057

**Comment by csthomas** [comment]
> Warning: ksort() expects parameter 2 to be long
I assume this is php 5.3 issue, I have created an issue.

**Comment by waader** [comment]
@wilsong #14057 resolves the problem - thanks
@csthomas You are right. My mssql-test system run´s on 5.3.29

**Comment by wilsonge** [comment]
@csthomas that redirect plugin error might be related to this pr :)

**Comment by csthomas** [comment]
> By the way: with the redirect plugin enabled I get 500 - PLG_SYSTEM_REDIRECT_ERROR_UPDATING_DATABASE

`[Microsoft][ODBC Driver 13 for SQL Server][SQL Server]Cannot insert the value NULL into column 'comment', table 'joomla.dbo.j37_redirect_links'; column does not allow nulls. INSERT fails.`
This is unrelated. 

I have found a big problem with sqlsrv updates in joomla (administrator/components/com_admin/sql/updates/sqlazure/*.sql).
**A lots of that ALTER TABLE ALTER COLUMN has invalid syntax.**

https://msdn.microsoft.com/en-us/library/ms190273.aspx

**They are not executed to database at all.** At least for my environment. 
I need a little time to create an issue.

**Comment by csthomas** [comment]
The above problems should be fixed with referenced my PRs.

**Comment by waader** [comment]
@csthomas: Can you sychronize this patch with the changes made in other yet commited sqlserver-patches.

**Comment by csthomas** [comment]
OK. Please wait a moment

**Comment by csthomas** [comment]
I have rebased it. It should work but you can not use sample data, because it is broken, I'm working on that now (#13981).

But you can get sample data from #7680

**Comment by csthomas** [comment]
Please ignore errors like:
```
Cannot insert the value NULL into column 'term_id', table 'joomla.dbo.#__finder_tokens_aggregate'; column does not allow nulls. INSERT fails.
```

It is unrelated, and it is waiting for new PR.

**Comment by csthomas** [comment]
There is not need to combine this PR for tests with #14102 in the same time.

But if someone want to test 2 PRs at once then:
- first apply #14102 and upgrade joomla database to latest version,
- remove above patch from Patch Tester,
- apply this PR (this PR has common, identical file `database/driver/sqlsrv.php` with PR #14102)
- test this PR.

**Comment by waader** [comment]
I have tested this item :white_check_mark: successfully on 00fd4a9a1e518f8d4e63d1b0925697c8df8d96a9<br /><br />Fixes these problems:
    /administrator/index.php?option=com_banners
    /administrator/index.php?option=com_categories&extension=com_banners
    /administrator/index.php?option=com_banners&view=clients
    /administrator/index.php?option=com_finder&view=maps
    /administrator/index.php?option=com_categories&extension=com_newsfeeds
    /administrator/index.php?option=com_categories&extension=com_contact
    /administrator/index.php?option=com_postinstall

Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13262">issues.joomla.org/tracker/joomla-cms/13262</a>.</sub>

**Comment by csthomas** [comment]
Last commit fix error on "sample testing" for menu items:
> Compact tagged: should show one record
> Tagged items: should show one record

**Comment by csthomas** [comment]
For All tags the is other error which has to be resolved by separate PR.

> DB function failed with error number 169
> [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]A column has been specified more than once in the order by list. Columns in the order by list must be unique.
> SQL =
> 
> SELECT TOP 20 a.*
> FROM [#__tags] AS a
> WHERE [a].[access] IN (1,5,1) AND [a].[parent_id] <> 0 AND [a].[title] LIKE N'%[gl]%' AND . [a].[published] = 1
> ORDER BY [title] ASC, a.title ASC
> 
> [Microsoft][ODBC Driver 13 for SQL Server][SQL Server]A column has been specified more than once in the order by list. Columns in the order by list must be unique.

**Comment by wilsonge** [comment]
Merged with waaders test given this is only affecting mssql

**Comment by csthomas** [comment]
Thanks

**Comment by photodude** [comment]
@csthomas Will you consider making these changes to [the Framework](https://github.com/joomla-framework/database) also?

**Pull request merged**
