### PR TITLE
[4.0] Added missing target attribute to parseXmlNode

### PR DESCRIPTION
**Pull request by HRIT-Florian**
Required for the backend template for external links, like menuitem type url!

Pull Request for Issue # .

### Summary of Changes

Added missing target attribute to parseXmlNode() method

### Documentation Changes Required

No

### CODE REVIEW

**Comment by bembelimen** [comment]
I have tested this item :white_check_mark: successfully on b6c346eb647f71ae8a4cf2050b41aebe4ba2460c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25007">issues.joomla.org/tracker/joomla-cms/25007</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on b6c346eb647f71ae8a4cf2050b41aebe4ba2460c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25007">issues.joomla.org/tracker/joomla-cms/25007</a>.</sub>

**Comment by ghost** [comment]
Status "Ready To Commit".

**Comment by HLeithner** [comment]
Thx

**Pull request merged**
