### PR TITLE
Remove chmod to 444

### PR DESCRIPTION
**Pull request by n9iels**
See #6126

### CODE REVIEW

**Comment by infograf768** [comment]
please correct whitespace

**Comment by n9iels** [comment]
Which white space you mean?

**Comment by roland-d** [comment]
FILE: ...a/joomla-cms/administrator/components/com_templates/models/template.php

--------------------------------------------------------------------------------

FOUND 1 ERROR(S) AFFECTING 1 LINE(S)

--------------------------------------------------------------------------------

507 | ERROR | Whitespace found at end of line

--------------------------------------------------------------------------------

That Niels, there is a space at the end of that line.

**Comment by infograf768** [comment]
still incorrect
```
FILE: ...a/joomla-cms/administrator/components/com_templates/models/template.php

--------------------------------------------------------------------------------

FOUND 1 ERROR(S) AFFECTING 1 LINE(S)

--------------------------------------------------------------------------------

507 | ERROR | Whitespace found at end of line
```

**Comment by infograf768** [comment]
Oh, I see, we have a new PR. 
Closing in favor of: https://github.com/joomla/joomla-cms/issues/6146

**Pull request closed without merging**
