### PR TITLE
[3.9-dev] Alpha order the language strings for the new pre update checker

### PR DESCRIPTION
**Pull request by zero-24**
### Summary of Changes

Alpha order the language strings for the new pre update checker

### Testing Instructions

Review & notice the pre update checker still works ;)

### Expected result

strings alpha order

### Actual result

strings are not in alpha order

### Documentation Changes Required

None

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 0203ed92ab24896a8d81b2ee535a8ebdd3a3dc16<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18551">issues.joomla.org/tracker/joomla-cms/18551</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 0203ed92ab24896a8d81b2ee535a8ebdd3a3dc16<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18551">issues.joomla.org/tracker/joomla-cms/18551</a>.</sub>

**Comment by ghost** [comment]
RTC after two successful tests.

**Comment by zero-24** [comment]
@mbabker as this has been merged into the old 3.9-dev branch and is now moved to 3.10 how do you want to handle the milestone? Should we just assign 3.10 or remove the milestone completely?

**Comment by wilsonge** [comment]
changed milestone

**Pull request merged**
