### PR TITLE
[4.0] Fix WebAuthn white icons

### PR DESCRIPTION
**Pull request by C-Lodder**
Pull Request for Issue #29700

### Summary of Changes

- Replace the `icon-` prefix with `fa-`
- Remove the `icon-white` class so that icons inherit the colour of the parent

### Testing Instructions

Code review

### CODE REVIEW

**Comment by PhilETaylor** [comment]
This is not for #29701 it’s for #29700

**Comment by PhilETaylor** [comment]
This is not for #29701 it’s for #29700

**Comment by C-Lodder** [comment]
Thanks. Link updated

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on c0a5a19f206a358d3cc32563373fed54bbfdbf24<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29704">issues.joomla.org/tracker/joomla-cms/29704</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
