### PR TITLE
[4.0] Correct tinymce/langs path

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue #18650

### Summary of Changes
Correct tinymce/langs path

### Testing Instructions
please see #18650

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 137705f7c2fe90f2b1df8f38a9ec917919d04034<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18652">issues.joomla.org/tracker/joomla-cms/18652</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 137705f7c2fe90f2b1df8f38a9ec917919d04034<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18652">issues.joomla.org/tracker/joomla-cms/18652</a>.</sub>

**Comment by ghost** [comment]
RTC after two successful tests.

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
