### PR TITLE
UI/UX Review for com_messages on mobile devices

### PR DESCRIPTION
**Pull request by zero-24**
see: #5628

This is a proposal UI/UX review on mobile for the messaging component.

Bevor this Patch

mobile_com_messages_bevor

After this Patch
mobile_com_messages_after

### CODE REVIEW

**Comment by brianteeman** [comment]
Do you think read is more important than the date of the message?

**Comment by zero-24** [comment]
hmm no both fileds are importent but the date is so long (5 lines) and you can see the date if you open the message. Thats the reasons why i remove it.

**Comment by brianteeman** [comment]
@test all good<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5666">issues.joomla.org/joomla-cms/5666</a>.</sub>

**Comment by waader** [comment]
@test works!

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5666">issues.joomla.org/joomla-cms/5666</a>.</sub>

**Pull request merged**
