### PR TITLE
[5.0] Implement Schema.org support for Menu Items

### PR DESCRIPTION
**Pull request by krileon**
### Summary of Changes
Implements same Article and Contact Schema.org parameters and parsing into JSON-LD for Menu Items. This allows extensions and other custom pages to leverage Schema.org JSON-LD without needing any additional development.

### Testing Instructions
1. Edit, publish, and save "Content - Joomla" plugin
2. Edit, publish, and save "System - Schema.org" plugin
3. Create or edit a new menu item
4. Configure and save data under the Schema tab as you would with an Article
5. Navigate to that menu item on frontend
6. Press F12 to open your browsers developer tools
7. Review the <head> to make sure your JSON-LD Schema data is present

This is dependent on the menu id being explicitly loaded. So with SEO off that would be Itemid in the URL. Schema data is also cached by default so if you accessed the menu item before saving your schema data be sure to clear your cache or turn off caching of schema data.

### Actual result BEFORE applying this Pull Request
No Schema tab in menu edit/create

### Expected result AFTER applying this Pull Request
Schema tab in menu edit/create

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed
- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :red_circle: unsuccessfully on 6a897e84dd5f9e605ca9cc04d271f279a19f07f5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42695">issues.joomla.org/tracker/joomla-cms/42695</a>.</sub>

**Comment by brianteeman** [comment]
The only thing I was able to confirm was that the schema tab appeared in the menu edit.

Nothing was created<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42695">issues.joomla.org/tracker/joomla-cms/42695</a>.</sub>

**Comment by krileon** [comment]
> The only thing I was able to confirm was that the schema tab appeared in the menu edit.
> 
> Nothing was created
> 
> This comment was created with the [J!Tracker Application](https://github.com/joomla/jissues) at [issues.joomla.org/tracker/joomla-cms/42695](https://issues.joomla.org/tracker/joomla-cms/42695).

It's entirely menu item based. You need to be sure you're on the correct menu item. So Itemid will matter. You need to of course ensure the Schema plugins are all enabled and working as it's using the same behavior and implementation that articles and contacts use.

**Comment by brianteeman** [comment]
> It's entirely menu item based. You need to be sure you're on the correct menu item. So Itemid will matter. 

Confirmed

> The Schema data should also exist in _schemaorg table for that menu item attached to its menu id with a com_menus.item context.

Confirmed

Nothing in the front end

**Comment by krileon** [comment]
> > It's entirely menu item based. You need to be sure you're on the correct menu item. So Itemid will matter.
> 
> Confirmed
> 
> > The Schema data should also exist in _schemaorg table for that menu item attached to its menu id with a com_menus.item context.
> 
> Confirmed
> 
> Nothing in the front end

Edit and save "Content - Joomla" and "System - Schema.org" plugins. Then clear Joomla cache. Had this same issue with Articles.

It's working for me in my tests. So beyond that I don't know what to suggest.

Menu:
image

JSON-LD:
image

**Comment by brianteeman** [comment]
> Edit and save "Content - Joomla" and "System - Schema.org" plugins. Then clear Joomla cache. Had this same issue with Articles.

Already done

> This allows extensions and other custom pages to leverage Schema.org JSON-LD without needing any additional development.

Are you sure that you tested this with a menu item that was NOT for com_content - your screenshot implies that you were testing com_content

**Comment by krileon** [comment]
> > Edit and save "Content - Joomla" and "System - Schema.org" plugins. Then clear Joomla cache. Had this same issue with Articles.
> 
> Already done
> 
> > This allows extensions and other custom pages to leverage Schema.org JSON-LD without needing any additional development.
> 
> Are you sure that you tested this with a menu item that was NOT for com_content - your screenshot implies that you were testing com_content

That's a good point. Yeah I only tested com_content menu items. So there's probably a check somewhere checking the component. Probably isSupported in the Schemaorg plugin.

**Comment by brianteeman** [comment]
it does work for com_content but thats all.

I suggest you close this for now (saves other people from wasting their time) and then re-open it when you have tested this

**Comment by LadySolveig** [comment]
Thank you for your work on this @krileon. A nice idea to have this also in menu items. I would appreciate it if you could reopen this PR in the 5.1-dev branch, as it is a new feature. Please mark it as draft while you are still working on it until the other components are also supported. It is not necessary to close it.

**Comment by krileon** [comment]
> Thank you for your work on this @krileon. A nice idea to have this also in menu items. I would appreciate it if you could reopen this PR in the 5.1-dev branch, as it is a new feature. Please mark it as draft while you are still working on it until the other components are also supported. It is not necessary to close it.

I'm going to have to completely rebase this to 5.1 then. I didn't know 5.0 was feature locked.

**Comment by krileon** [comment]
New PR specifically for 5.1 done. #42703

**Pull request closed without merging**
