### PR TITLE
Start of 3.8.12 merge

### PR DESCRIPTION
**Pull request by wilsonge**
This is the first half of the commits give or take. I'll finish the rest tomorrow

Please don't ever squash merge these commits as it ruins the git history which i need preserved to be able to keep doing this effectively

### CODE REVIEW

**Comment by wilsonge** [comment]
@rdeutz @yvesh Going to need some help with drone here tomorrow to figure out why it's installation is failing. Works locally for me :(

**Comment by rdeutz** [comment]
@puneet0191 any idea, is this part of joomla-browser?

**Comment by puneet0191** [comment]
Seems like a security failure on the latest commit, system tests were passing. `analysis4x`

**Comment by rdeutz** [comment]
Where did you see this?

**Comment by yvesh** [comment]
I restarted the build this morning and it's failing for RIPS / analysis4x now - not the system tests.. (Just one of the usual drone hickups before)

**Comment by wilsonge** [comment]
I reran drone 4 times!? But glad to hear it's sorted now

**Pull request merged**
