### PR TITLE
[5.1] replace web-token/signature-pack with web-token/jwt-library

### PR DESCRIPTION
**Pull request by heelc29**
Possible Pull Request for Issue #42952 .

### Summary of Changes

replace abandoned composer packages

### Testing Instructions

run composer install

### Actual result BEFORE applying this Pull Request

warning
image

### Expected result AFTER applying this Pull Request

no warning

### Additional comments

Removed packages do not contain relevant files
image

only web-token/jwt-experimental ...
image

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on e9bf761e89c79c8c1e807c8f7eb55fdff5871d79<br /><br />The removed sub-dependencies consisted only of a readme file, the PHP files were already removed with the update from PR #42945 .

So we lose nothing with this PR here.

Unit tests, integration tests and system tests are successful, too.

However it needs to add some more deleted files and folders to script.php. I will make a follow-up PR for that.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42954">issues.joomla.org/tracker/joomla-cms/42954</a>.</sub>

**Comment by richard67** [comment]
Follow-up PR for the deleted files and folders is PR #42955 .

**Comment by laoneo** [comment]
I have tested this item :white_check_mark: successfully on e9bf761e89c79c8c1e807c8f7eb55fdff5871d79<br /><br />No abandoned warnings<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42954">issues.joomla.org/tracker/joomla-cms/42954</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42954">issues.joomla.org/tracker/joomla-cms/42954</a>.</sub>

**Comment by bembelimen** [comment]
Thanks

**Pull request merged**
