### PR TITLE
[4.1] Changed blog modifiers on Cassiopeia

### PR DESCRIPTION
**Pull request by drmenzelit**
Pull Request for Issues found by @woluweb 
https://slides.woluweb.be/cassiopeia/cassiopeia.html#5-2-issue-2-the-read-more-button-partially-hidden
https://slides.woluweb.be/cassiopeia/cassiopeia.html#5-3-issue-3-layout-in-blog-view

### Summary of Changes
Changed the _modifiers.scss file and added a media query for the code that controls the display of image and content on blog layout with images positioned left (image-left) or right (image-right) or alternating (image-alternate).

### Testing Instructions
Create some articles with intro images and read more, at least one article with a very short text. Create a menu item of type category blog and use the classes `image-left`, `image-right` alone and in combination with `image-alternate`

### Actual result BEFORE applying this Pull Request
See issues description on the links above
On mobiles: Read more buttons are not displaying completely, too much space between image and content, images over and below the text (by using class `image-alternate`)

Screenshot 2022-02-10 at 18-36-08 Blog

On desktops: By short text the position of the images is weird

Screenshot 2022-02-10 at 18-44-27 Blog

### Expected result AFTER applying this Pull Request
Buttons are ok, no space between image and content, no weird distribution of image and content. Using `image-alternate` the image will display always on top of the article on mobiles

Screenshot 2022-02-10 at 19-33-31 Blog

Screenshot 2022-02-10 at 18-48-47 Blog

### CODE REVIEW

**Comment by woluweb** [comment]
I have tested this item :white_check_mark: successfully on f9844431de39b89baeb6efd5c6bde7558b29bede<br /><br />Txs very much for taking the time of this PR @drmenzelit !
Tested successfully during our tests/exchanges yesterday on Glip on my own J4 site in construction.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36998">issues.joomla.org/tracker/joomla-cms/36998</a>.</sub>

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on f9844431de39b89baeb6efd5c6bde7558b29bede<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36998">issues.joomla.org/tracker/joomla-cms/36998</a>.</sub>

**Comment by RickR2H** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36998">issues.joomla.org/tracker/joomla-cms/36998</a>.</sub>

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
