### PR TITLE
[4.0] change layout of select in search (frontend)

### PR DESCRIPTION
**Pull request by rjharishabh**
Pull Request for Issue #32982.

### Summary of Changes
added class `form-select`, `w-auto` and `mb-2`

### Testing Instructions
Just visit `http://localhost/joomla-cms/index.php/search` and see the changes

### Actual result BEFORE applying this Pull Request
search-before

### Expected result AFTER applying this Pull Request
search-after

### Documentation Changes Required
No

### CODE REVIEW

**Comment by rjharishabh** [comment]
@sandramay0905 please test

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 64c640a4bb9fb9ba447f1522a6d082a84f342262<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33220">issues.joomla.org/tracker/joomla-cms/33220</a>.</sub>

**Comment by rjharishabh** [comment]
Thanks @sandramay0905 for testing

**Comment by rjharishabh** [comment]
@Quy @richard67  Please test this
Anything needs to change here, **thanks in advance.**

**Comment by richard67** [comment]
@rjharishabh Sometimes it needs to be a bit patient with testers. If everybody who wants to have a test would notify me, I would soon have to set up some kind of spam filter or just ignore it.

**Comment by rjharishabh** [comment]
Sorry, I would be take care of it in future. 
Thanks

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 64c640a4bb9fb9ba447f1522a6d082a84f342262<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33220">issues.joomla.org/tracker/joomla-cms/33220</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33220">issues.joomla.org/tracker/joomla-cms/33220</a>.</sub>

**Comment by richard67** [comment]
Thanks!

**Comment by ChristineWk** [comment]
@richard67 

OT: I think @rjharishabh wanted to ask if the code was ok - _"Anything needs to change here"_ missing the ? :-)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33220">issues.joomla.org/tracker/joomla-cms/33220</a>.</sub>

**Pull request merged**
