### PR TITLE
[com_menus] items list view: show menu type title instead of menu type

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Summary of Changes

For consistency, changes the menu type to Menu Type Title in the menu items list view.
##### Before

image
##### After

image
#### Testing Instructions

Easy test:
- Use latest staging
- Apply patch
- Go to menus and check the "Menu" column now shows the Menu Type Title, instead of the menu type.

### CODE REVIEW

**Comment by bertmert** [comment]
I have tested this item :white_check_mark: successfully on 829f775f86b47eeae0e38082204f9fefbfacc027<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11160">issues.joomla.org/joomla-cms/11160</a>.</sub>

**Comment by grhcj** [comment]
I have tested this item :white_check_mark: successfully on 829f775f86b47eeae0e38082204f9fefbfacc027<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11160">issues.joomla.org/joomla-cms/11160</a>.</sub>

**Comment by grhcj** [comment]
I have tested this item :white_check_mark: successfully on 829f775f86b47eeae0e38082204f9fefbfacc027<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11160">issues.joomla.org/joomla-cms/11160</a>.</sub>

**Comment by zero-24** [comment]
RTC. Based on testing.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11160">issues.joomla.org/joomla-cms/11160</a>.</sub>

**Pull request merged**
