### PR TITLE
[4.0] [plg_system_highlight] Update return types

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

`onAfterDispatch` should return void.

### Testing Instructions

Code review.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by Eriiond** [comment]
I have tested this item :white_check_mark: successfully on bcfb885a2ba67b8dc0d1e8855dd7a1133acbf8dd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26224">issues.joomla.org/tracker/joomla-cms/26224</a>.</sub>

**Comment by sanderpotjer** [comment]
I have tested this item :white_check_mark: successfully on bcfb885a2ba67b8dc0d1e8855dd7a1133acbf8dd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26224">issues.joomla.org/tracker/joomla-cms/26224</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26224">issues.joomla.org/tracker/joomla-cms/26224</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
