### PR TITLE
Fix MFA Authentication Code by Email plugin's Force Enable feature

### PR DESCRIPTION
**Pull request by nikosdion**
Pull Request for issue reported in https://github.com/joomla/joomla-cms/pull/37912#issuecomment-1152577174

### Summary of Changes

The MFA plugin's “Force Enable” option didn't do anything. This PR addresses that.

### Testing Instructions

* Set up MFa for your user account using any method _except_ ‘Code by Email’.
* Edit the ‘Multi-factor Authentication - Authentication Code by Email’ plugin
* Set Force Enable to Yes
* Save & Close
* Log out
* Log back in
* When you see the MFA page click choose another method

### Actual result BEFORE applying this Pull Request

You do not see an “Authentication Code by Email” option

### Expected result AFTER applying this Pull Request

You see an (automatically added) “Authentication Code by Email” option.

### Documentation Changes Required

None

### CODE REVIEW

**Comment by Kostelano** [comment]
I have tested this item :white_check_mark: successfully on 155f332fd0e0b49bde8496db7784eeecebb3391a<br /><br />Prior to the first use of "mail authentication code" as a fallback, the method was INACTIVE. As soon as we specifically "forgot / lost access" to our configured methods, and also did not save backup codes, but used the "authentication code by mail" method during authorization, it became available in our profile as configured.

Everything is great, thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38029">issues.joomla.org/tracker/joomla-cms/38029</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 155f332fd0e0b49bde8496db7784eeecebb3391a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38029">issues.joomla.org/tracker/joomla-cms/38029</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38029">issues.joomla.org/tracker/joomla-cms/38029</a>.</sub>

**Comment by nikosdion** [comment]
Thank you!

**Comment by richard67** [comment]
> Thank you!

Was a pleasure 😄

**Comment by laoneo** [comment]
Thanks!

**Comment by nikosdion** [comment]
Thank you!

**Pull request merged**
