### PR TITLE
Small review/cleanup in JHtml

### PR DESCRIPTION
**Pull request by mbabker**
#### Summary of Changes
- Replaces use of deprecated `JArrayHelper`
- Removes some else conditions
- Improves method documentation and variable names to better document what's happening
#### Testing Instructions

`JHtml` still functions correctly

### CODE REVIEW

**Comment by hardiktasol** [comment]
I have tested this item :white_check_mark: successfully on 8a08a39a5b64016ad7310e14bfa9f9f60c59f8ae<br /><br />Works correctly.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10771">issues.joomla.org/joomla-cms/10771</a>.</sub>

**Comment by truptikagathara** [comment]
I have tested this item :white_check_mark: successfully on 9478324ad4653b1b4007e0e24a9728f1478c24af<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10771">issues.joomla.org/joomla-cms/10771</a>.</sub>

**Comment by brianteeman** [comment]
RTC as we have two tests - the first was before a branch update<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10771">issues.joomla.org/joomla-cms/10771</a>.</sub>

**Comment by wilsonge** [comment]
Merged with https://github.com/joomla/joomla-cms/commit/b888ab0ae595633031184bf14806b903e97f3e0d

**Pull request closed without merging**
