### PR TITLE
Add `Url` fieldtype to Repeatable Field

### PR DESCRIPTION
**Pull request by janschoenherr**
### Summary of Changes

Add `Url` fieldtype to Repeatable Field

### Testing Instructions

Use the `Url` fieldtype in a repeatable field.

### Documentation Changes Required

no.

### CODE REVIEW

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 0b962a0b15263ee2cb53c584f5ac7a0ff6cfc8ac<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27167">issues.joomla.org/tracker/joomla-cms/27167</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 0b962a0b15263ee2cb53c584f5ac7a0ff6cfc8ac<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27167">issues.joomla.org/tracker/joomla-cms/27167</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27167">issues.joomla.org/tracker/joomla-cms/27167</a>.</sub>

**Comment by AndySDH** [comment]
Ehm in case you guys didn't notice, the goal is to deprecate Repeatable fields in Joomla 4, because the more robust Subfields have been implemented: see https://github.com/joomla/joomla-cms/pull/24711
(which has support for EVERY field type, with all their params too).

It has already been merged, so it would be great if more people would test and improve that instead!

PS: Plus this PR doesn't really make sense by looking at the changes, this URL field is no different than the already present text field, there's no point, it's literally just the same option with a different language string

**Comment by janschoenherr** [comment]
@AndySDH Subfields sounds like a nice feature. However, if it's only deprecated, it would still be nice to see this PR being merged.

The URL field renders an Input field of type `url`.  It also provides context. When rendering the field, you know it is a link and can render it differently than a text field.

**Comment by wilsonge** [comment]
I’m not so fussed about repeatable being deprecated going forward. I’m more concerned about the lack of validation (an ongoing issue in general with our repeatable fields support both in JForm and com_fields). Is there any relatively simple way we can add server side validation to this?

**Comment by SharkyKZ** [comment]
Subform field supports filtering and validation since 3.9.7.

**Comment by janschoenherr** [comment]
@wilsonge Is there some form of validation with the current none repeatable `url` field? It seems only text filters are applied to it.

**Comment by HLeithner** [comment]
Sorry no new features in j3, we try to focus on j4.
 It also seams nobody missed it the last 2 years. Now with the upcoming release of j4 this should be solved with subfields.

**Pull request closed without merging**
