### PR TITLE
[4.0] Fixed duplicated use.

### PR DESCRIPTION
**Pull request by Schmidie64**
Pull Request for Issue #22077.

### Summary of Changes
Removed duplicated Code line. 

### Testing Instructions
See issue.

### Expected result
See issue.

### Actual result
See issue.

### Documentation Changes Required
None

### CODE REVIEW

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on dfc9e3384a870fefa06a6c163e856eeb55288ea4<br /><br />Code review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22078">issues.joomla.org/tracker/joomla-cms/22078</a>.</sub>

**Comment by eXsiLe95** [comment]
I have tested this item :white_check_mark: successfully on dfc9e3384a870fefa06a6c163e856eeb55288ea4<br /><br />Glad you found it! I tested it.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22078">issues.joomla.org/tracker/joomla-cms/22078</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
