### PR TITLE
[4.0] showon comment

### PR DESCRIPTION
**Pull request by brianteeman**
Adds the requested comment to the code.

PR for #34084 using the comment from @dgrammatiko

### CODE REVIEW

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on b9581a90ae5a350084723eee853ac8354e9f36ff<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34680">issues.joomla.org/tracker/joomla-cms/34680</a>.</sub>

**Comment by ricardo1709** [comment]
I have tested this item :white_check_mark: successfully on b9581a90ae5a350084723eee853ac8354e9f36ff<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34680">issues.joomla.org/tracker/joomla-cms/34680</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34680">issues.joomla.org/tracker/joomla-cms/34680</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thx

**Pull request merged**
