### PR TITLE
[4.0] Fix overflow in modal

### PR DESCRIPTION
**Pull request by Quy**
Pull Request for Issue #26638.

### Summary of Changes
Fix text from overflowing in modal.

### Testing Instructions
Go to System > Site Templates > Cassiopeia Details and Files
Edit error.php
Click on `New File`
Apply PR
Run `npm i`

### Actual result

67140193-ada6dc80-f275-11e9-89b3-83fcf6174e4a

### CODE REVIEW

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on de8049339f15f6d0de7dd5dc45ef014970911447<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28487">issues.joomla.org/tracker/joomla-cms/28487</a>.</sub>

**Comment by roland-d** [comment]
I have tested this item :white_check_mark: successfully on de8049339f15f6d0de7dd5dc45ef014970911447<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28487">issues.joomla.org/tracker/joomla-cms/28487</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28487">issues.joomla.org/tracker/joomla-cms/28487</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
