### PR TITLE
Router options

### PR DESCRIPTION
**Pull request by brianteeman**
We cant keep calling it the New or Advanced router. Lets give it a name and move forward with that - it will help documentation for developers and marketing etc as well

For the purpose of this PR I have changed it from Use New URL routing yes/no 
To URL routing Modern/Legacy

I am not tied to those names I just want to get rid of the word new or advanced as they are not appropriate.

hbva 1

hbva 1

### CODE REVIEW

**Comment by chrisdavenport** [comment]
I'm happy with that.  Can't think of anything better anyway.

**Comment by brianteeman** [comment]
Just made a small change from the screenshot to put the sentence about Modern before the sentence about legacy.

**Comment by chrisdavenport** [comment]
I have tested this item :white_check_mark: successfully on 50072106ff345c78e2a6f10b61716adbf510ea30<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11962">issues.joomla.org/joomla-cms/11962</a>.</sub>

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
