### PR TITLE
[4.3] Double Translation cancel button

### PR DESCRIPTION
**Pull request by brianteeman**
### Summary of Changes
Simple code error causing a double translation in the select view for schedule tasks

### Testing Instructions
Enable language debug

### Actual result BEFORE applying this Pull Request
image

### Expected result AFTER applying this Pull Request
image

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 8fb2bb28551e046a0abf4cf1cc9cec743b55790f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40506">issues.joomla.org/tracker/joomla-cms/40506</a>.</sub>

**Comment by alikon** [comment]
there is one more

image

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 8fb2bb28551e046a0abf4cf1cc9cec743b55790f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40506">issues.joomla.org/tracker/joomla-cms/40506</a>.</sub>

**Comment by brianteeman** [comment]
@alikon yes the actions button is a long standing issue that no one has been able to resolve

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40506">issues.joomla.org/tracker/joomla-cms/40506</a>.</sub>

**Comment by sdwjoomla** [comment]
Thanks brianteeman

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
