### PR TITLE
[5.1] add language deprecation for #37320

### PR DESCRIPTION
**Pull request by heelc29**
### Summary of Changes

Add back the removed strings of #37320 and deprecate them @AndySDH @Razzo1987
Update language constant of custom field `subform` to not use deprecate string

### Testing Instructions

add new custom field of type `subform`
open tab `options`

### Actual result BEFORE applying this Pull Request

untranslated string
image
image

### Expected result AFTER applying this Pull Request

string translated
image

### Link to documentations
Please select:
- [x] No documentation changes for docs.joomla.org needed
- [x] Pull Request link for manual.joomla.org: https://github.com/joomla/Manual/pull/211

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 055caefab7c8953657c4604c0e593ad94091d731<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42584">issues.joomla.org/tracker/joomla-cms/42584</a>.</sub>

**Comment by tecpromotion** [comment]
I have tested this item :white_check_mark: successfully on 055caefab7c8953657c4604c0e593ad94091d731<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42584">issues.joomla.org/tracker/joomla-cms/42584</a>.</sub>

**Review by tecpromotion — APPROVED** [review]

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42584">issues.joomla.org/tracker/joomla-cms/42584</a>.</sub>

**Comment by Razzo1987** [comment]
Thanks!

**Pull request merged**
