### PR TITLE
Protostar: Correcting classes for alert messages (Solves #7786)

### PR DESCRIPTION
**Pull request by infograf768**
See https://github.com/joomla/joomla-cms/issues/7786
Edit and save an article in frontend in protostar.
After patch the alert message will now be in green for success.
screen shot 2015-08-31 at 09 08 13

### CODE REVIEW

**Comment by Bakual** [comment]
Agree with the change and tested succesfully. It also makes output in backend and frontend more consistent.
The only thing I find less optimal is that this only fixes it for Protostar. Each (Bootstrap based) template which wants to do the same, needs to create an override as well. Which imho isn't optimal. Our core should output Bootstrap compatible markup by default.

I wonder if we instead can change the default system layout. Instead of replacing the class, add an additional one to the output.
So instead of
`<div class="alert <?php echo $alert[$type]; ?>">`
make it 
`<div class="alert alert-<?php echo $type; ?> <?php echo $alert[$type]; ?>">`
Imho that should work and shouldn't break existing templates as the existing classes would still be present for templates which supported them.

What do you think?

**Comment by infograf768** [comment]
I did not do the change there (we also have to add the `$alert = array( etc.` because I feared not being B/C.
You folks decide. The PR is easy to change.

**Comment by MAT978** [comment]
successfully tested - thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7788">issues.joomla.org/joomla-cms/7788</a>.</sub>

**Comment by mbabker** [comment]
@Bakual If you wanted to do that you'd have to make sure that the non-prefixed names aren't used elsewhere in Bootstrap as contextual class helpers.

**Comment by Bakual** [comment]
@mbabker The current code produces already prefixed classnames (see https://github.com/joomla/joomla-cms/blob/staging/layouts/joomla/system/message.php#L19).
The table below shows what will change with this PR. All classes currently used aren't used in Bootstrap, except `alert-error`.

| Type | Default Class | Bootstrap Class | Comment |
|--------|------------------|----------------------|--------------|
| message | alert-message | alert-success | Broken, currently yellow, becomes green |
| notice | alert-notice | alert-info | Broken, currently yellow, becomes blue |
| warning | alert-warning | | No change, shows yellow (default) |
| error | alert-error | alert-error | No change, shows red |

My proposal would add both classes, the existing and the bootstrap one. Which should make sure existing templates still work as expected.

On a sidenote: #7070 added `alert-message` for the body part of the alert. This was of course badly named as it's already a possible value (default one) of the whole message container.

**Comment by mbabker** [comment]
So there's two options:

- This PR, which only changes Protostar, and assumes other templates are styling messages based on the classes being pushed in unconverted
- Your idea, which adds additional classes to the default layout, and based on what order the classes may appear in or whether there is CSS defined for them, may affect the display of template's message containers

Personally, I'd go with this PR as is.  Yes, it's bad enough that our defaults are inconsistent, but adding another class to the div container (so you may have `<div class="alert alert-notice alert-info">` has more issues than it potentially solves (if the template has a styling for `alert-notice` it may be overridden by `alert-info` based on the order of CSS rules or class names).

**Comment by Bakual** [comment]
Ok, so let's go with this PR and do it better with J4 :+1:

**Comment by infograf768** [comment]
I guess therefore that this can go rtc and Merged

**Comment by Bakual** [comment]
Set it RTC. Someone else has to merge it :-)

**Comment by Kubik-Rubik** [comment]
Thank you @infograf768! Merged.

**Pull request merged**
