### PR TITLE
[4.0] add module permissions

### LINKED ISSUE #29372: [4.0] Hide "Add module to the dashboard" from Manager group
### Steps to reproduce the issue
Log in to the Administration backend as a manager.
Click `Add module to the dashboard` icon.

### PR DESCRIPTION
**Pull request by brianteeman**
Applies the suggestion from @chmst to fix #29372

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 9eb742461dd64027886d0aa379d6d02c0ade2728<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29718">issues.joomla.org/tracker/joomla-cms/29718</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 9eb742461dd64027886d0aa379d6d02c0ade2728<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29718">issues.joomla.org/tracker/joomla-cms/29718</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29718">issues.joomla.org/tracker/joomla-cms/29718</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thx

**Pull request merged**
