### PR TITLE
Another subform fix for IE compatibility

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue #25194 
Simplified version of #25200 from @ventsonge

### Testing Instructions

Apply patch and make sure the subform works as before, plus it works in IE.

@Quy instruction for IE testing:

Use IE11

Go System > Global Configuration > Users > Email Domain Options
Template should not be displayed in the bottom left corner.

Go Extensions > Plugins > System - Redirect
Template should not be displayed at the bottom initially.

Additionally, a new rows should be added without an issue.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on e4fe691c9305a64869cfc5086ce7e90f6e1eb8f1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25325">issues.joomla.org/tracker/joomla-cms/25325</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on e4fe691c9305a64869cfc5086ce7e90f6e1eb8f1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25325">issues.joomla.org/tracker/joomla-cms/25325</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25325">issues.joomla.org/tracker/joomla-cms/25325</a>.</sub>

**Comment by HLeithner** [comment]
thx

**Pull request merged**
