### PR TITLE
[4.0] Namespace Editors - CodeMirror plugin

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Namespaces Editors - CodeMirror plugin.

### Testing Instructions

Delete `libraries/autoload_psr4.php` file.
Edit Editors - CodeMirror plugin.
In Appearance tab check that Font selector still appears.

### Documentation Changes Required

IDK.

### CODE REVIEW

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 7a3f6fede9bb1aa6a97e12972d385218bbf5f446<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27643">issues.joomla.org/tracker/joomla-cms/27643</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 7a3f6fede9bb1aa6a97e12972d385218bbf5f446<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27643">issues.joomla.org/tracker/joomla-cms/27643</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27643">issues.joomla.org/tracker/joomla-cms/27643</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
