### PR TITLE
[3.10] Allow to set redis server port to 0

### PR DESCRIPTION
**Pull request by wojsmol**
Pull Request for Issue # .

### Summary of Changes
Allow redis server port  to be set to 0 - for some hostings strange setups

### Testing Instructions
Code review or try set redis server port to 0

### Actual result BEFORE applying this Pull Request
Global Configuration can't be successfully saved when redis server port is set to 0.

### Expected result AFTER applying this Pull Request
Global Configuration can be successfully saved when redis server port is set to 0.

### Documentation Changes Required
N/A

### CODE REVIEW

**Comment by zero-24** [comment]
Hmm its a reserverd port ([RFC1700](http://www.faqs.org/rfcs/rfc1700.html)) and from what I found its used to be a dynamic port:

> Under normal circumstances, you will also not encounter a client-server connection that uses this port, because in socket programming, port 0 is synonymous with a dynamic port assigned by the operating system -- port 0 is used as a so-called wild card. When the bind() function is called, the socket is bound to a free, randomly chosen port.

https://www.heise.de/newsticker/meldung/Port-0-hilft-beim-OS-Fingerprinting-82937.html

According to this [bug report](https://github.com/redis/redis/issues/1477) and the [current code](https://github.com/redis/redis/blob/4d8700786e2f198f9ef44961196122bbb80ee640/src/server.c#L4199) from redis it also is not intended behavior to run on port 0.

Have you confirmed that it actually works when you set the port to 0?

edit: Its also documented on the [redis.conf](https://github.com/redis/redis/blob/unstable/redis.conf#L113-L115) that:
> If port 0 is specified Redis will not listen on a TCP socket.

**Comment by wojsmol** [comment]
@zero-24 I contacted technical support of affected hosting and requested informations here on github or via ticket - they checking this.

**Comment by PhilETaylor** [comment]
Its impossible for redis to listen on port 0 ! This is the wrong solution for sure!

**Comment by PhilETaylor** [comment]
see https://github.com/joomla/joomla-cms/blob/6801293f0e6e7645af79e0cab860a85555d00b82/libraries/src/Cache/Storage/RedisStorage.php#L84

This is how Joomla allows connecting to redis over a sock rather than a port. You dont need to specify the port in Joomla global config if you are connecting over a socket.

**Comment by PhilETaylor** [comment]
related https://github.com/joomla/joomla-cms/pull/18395

**Comment by wojsmol** [comment]
@PhilETaylor You are right, but unfortunately this behaviour is not mentioned in Joomla! Documentation.

**Pull request closed without merging**
