### PR TITLE
[4.0] switcher lables color changed 

### PR DESCRIPTION
**Pull request by puneeth-chanda**
Pull Request for Issue #23863

### Summary of Changes
Changed the color of field switcher labels.

### CODE REVIEW

**Comment by wojsmol** [comment]
@puneeth2001 Please resolve merge conflict.

**Comment by C-Lodder** [comment]
We don't use black font colours by default incase they're ever mixed with a white background which poses an a11y issue. Please use `var(--dark)` instead.

Please also add `[4.0]` to the title so everyone knows it's for Joomla 4

**Comment by C-Lodder** [comment]
@puneeth2001 still incorrect. Replace `color: var(--dark, $gray-600);` with `color: var(--dark);`

You also have a merge conflict which needs fixing.

**Comment by Puneet-Jain-18** [comment]
Has'nt issue #23863 solved by this PR?? as the changes have been applied to the code but issue is still open.

**Comment by ghost** [comment]
@wilsonge ?

**Comment by wilsonge** [comment]
I think so

**Pull request closed without merging**
