### PR TITLE
[4.1] Removed version="x" in xml

### PR DESCRIPTION
**Pull request by Kostelano**
Pull Request for Issue # .

### Summary of Changes
[Manifest files](https://docs.joomla.org/Manifest_files):

> String that identifies the version of Joomla for which this extension is developed. This is not used in Joomla 3.x and has been removed from Joomla 4.0 and higher.

These are the only places where the tag remains.

### Testing Instructions
Code review

### CODE REVIEW

**Comment by ChristineWk** [comment]
@Kostelano 
Which version?
Got message: "The file marked for modification does not exist: administrator/manifests/packages/pkg_search.xml" and didn't find under Code review. 4.1.4-rc2-dev<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37854">issues.joomla.org/tracker/joomla-cms/37854</a>.</sub>

**Comment by Kostelano** [comment]
@ChristineWk This is when upgrading from 3x and using basic search.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 47eb005c808760f2932a7a442714544fcab0b746<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37854">issues.joomla.org/tracker/joomla-cms/37854</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on d9fd4df6d0ae5ce794b7a68f4214a6d15261938e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37854">issues.joomla.org/tracker/joomla-cms/37854</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37854">issues.joomla.org/tracker/joomla-cms/37854</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
