### PR TITLE
Simplify tooltip

### PR DESCRIPTION
**Pull request by brianteeman**
simplify this important message - kiss principle

### CODE REVIEW

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on 530e6df1e43775206c3166809f76437187738fae<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14534">issues.joomla.org/tracker/joomla-cms/14534</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
@brianteeman where is this Tooltip to find?

**Comment by brianteeman** [comment]
@franz-wohlkoenig it is in the admin menu module settings

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 530e6df1e43775206c3166809f76437187738fae<br /><br />thanks for Hint, @brianteeman <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14534">issues.joomla.org/tracker/joomla-cms/14534</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC as there are 2 successfully Tests?

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14534">issues.joomla.org/tracker/joomla-cms/14534</a>.</sub>

**Pull request merged**
