### PR TITLE
Prettify 4.0-dev/build/media_source/templates/administrator/atum/js/template.es6.js

### PR DESCRIPTION
**Pull request by Stuartemk**
Pull Request for Issue # .
https://github.com/Stuartemk/joomla-cms/pull/2
### Summary of Changes
Prettify the css and js files allows a better reading and understanding of the code so you can develop faster and avoid errors.

### CODE REVIEW

**Comment by brianteeman** [comment]
Not sure what you were trying to do here but its clearly not correct as you have changed 47 files and none of them are the one in the title

**Comment by dgrammatiko** [comment]
@Stuartemk just for your information there are already linters in place for the 4.0 repo:
- scss/css: https://github.com/joomla/joomla-cms/blob/4.0-dev/build/.stylelintrc.json
- js: https://github.com/joomla/joomla-cms/blob/4.0-dev/build/.eslintrc

Also there are commands to automate the fixing of anything not compliant with the current linters: https://github.com/joomla/joomla-cms/blob/4.0-dev/build/README.md

**Comment by Stuartemk** [comment]
Thank you for your responses. It is clear that I made a terrible mistake, and that these PRs are totally wrong, so I close them right now. It was only a single file to modify.
Although the error is so obvious, the answers could also be less aggressive, since for that reason there are almost no contributors, not very tolerant answers take away the desire to contribute.

https://github.com/Stuartemk/joomla-cms/pull/2/files

**Comment by dgrammatiko** [comment]
> not very tolerant answers take away the desire to contribute.

I have no clue if this was towards my response but anyhow I just pointed out that there are Code Styles guidelines that the project adheres to and I pointed to the files that control the rules. I see that you want 4 spaces for intention  but for some time now the project is opted for 2 spaces for indentation for the css/scss and js for the simple fact that this is the industry standard (also it's what Bootstrap is using and all the other external dependencies the project uses).

**Pull request closed without merging**
