### PR TITLE
[4.0] Fix SQL Code

### PR DESCRIPTION
**Pull request by amitranjan2**
Pull Request for Issue # .

### Summary of Changes
changed DEFAULT Value 

### Testing Instructions
See the code 

### Expected result

same as before 

### Actual result
same as before 

### Documentation Changes Required
NO

### CODE REVIEW

**Comment by amitranjan2** [comment]
@chmst As you told me to do that, Please kindly test this PR

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 884eae34171d3300f1ecc77765ba5242de902eb8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24060">issues.joomla.org/tracker/joomla-cms/24060</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 884eae34171d3300f1ecc77765ba5242de902eb8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24060">issues.joomla.org/tracker/joomla-cms/24060</a>.</sub>

**Comment by ghost** [comment]
Status "Ready To Commit".

**Comment by wilsonge** [comment]
Thankyou very much for your first PR to Joomla :)

**Comment by amitranjan2** [comment]
> Thankyou very much for your first PR to Joomla :)

@wilsonge Thanks, but it was not my first PR to Joomla  :stuck_out_tongue_closed_eyes: :stuck_out_tongue:

**Comment by wilsonge** [comment]
github lies :P

**Pull request merged**
