### PR TITLE
[6.0] $this: Cleanup of typehints for phpstan

### PR DESCRIPTION
**Pull request by Hackwar**
### Summary of Changes
When typehinting $this in our layouts, we use both the full qualified name and a shortened version with an import. phpstan unfortunately does not currently understand the version with the import and thus this unifies this to the long version.

### Testing Instructions
Codereview

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by HLeithner** [comment]
Then we should disable the rule in phpstan, is there an issue to check at phpstan for this feature?

**Comment by brianteeman** [comment]
> Then we should disable the rule in phpstan, is there an issue to check at phpstan for this feature?

exactly

**Comment by Hackwar** [comment]
https://github.com/phpstan/phpstan/issues/10936

**Comment by Bodge-IT** [comment]
Issue deferred to PHPStan, change not required in Joomla.  Thanks Hannes.

**Comment by Hackwar** [comment]
no, it isn't.

**Pull request closed without merging**
