### PR TITLE
Overridden File

### PR DESCRIPTION
**Pull request by brianteeman**
See discussion at #38497

Overridden file means the file that has been overridden - not the file which is the override

image

### CODE REVIEW

**Comment by Abernyte-Git** [comment]
I have tested this item :white_check_mark: successfully on 7c2ec46aee178d99b6a3db2c5e74d427f256e6aa<br /><br />This ensures clarity in what is being changed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38541">issues.joomla.org/tracker/joomla-cms/38541</a>.</sub>

**Comment by tecpromotion** [comment]
I have tested this item :white_check_mark: successfully on 7c2ec46aee178d99b6a3db2c5e74d427f256e6aa<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38541">issues.joomla.org/tracker/joomla-cms/38541</a>.</sub>

**Review by tecpromotion — APPROVED** [review]

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38541">issues.joomla.org/tracker/joomla-cms/38541</a>.</sub>

**Comment by sandewt** [comment]
Thanks

**Comment by roland-d** [comment]
Thank you

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
