### PR TITLE
[4.0] fields xtd-editor button

### PR DESCRIPTION
**Pull request by brianteeman**
Corrects the svg icon that is used in the button so that its the same as used on the menus etc.

### Before
image

image

### After
image

image

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on bd403ee48352bc2a529a26293438522624ee6ce1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31739">issues.joomla.org/tracker/joomla-cms/31739</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on bd403ee48352bc2a529a26293438522624ee6ce1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31739">issues.joomla.org/tracker/joomla-cms/31739</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31739">issues.joomla.org/tracker/joomla-cms/31739</a>.</sub>

**Review by laoneo — APPROVED** [review]

**Comment by laoneo** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
