### PR TITLE
[4.0] doc site links

### PR DESCRIPTION
**Pull request by brianteeman**
All links go the docs.joomla.org web site should use  `Special:MyLanguage` in the url as this enables the user to be automatically redirect to the correct language version of the linked page.

Code Review

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on ef2623af262ae7a98840f95e7f6dc4e4e02b3ea7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34762">issues.joomla.org/tracker/joomla-cms/34762</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on ef2623af262ae7a98840f95e7f6dc4e4e02b3ea7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34762">issues.joomla.org/tracker/joomla-cms/34762</a>.</sub>

**Comment by zero-24** [comment]
Merging thanks.

**Comment by brianteeman** [comment]
thank you

**Pull request merged**
