### PR TITLE
[5.1] Dark Mode Web Installer List

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #43016 .

### Summary of Changes
Add missing hover

### Testing Instructions
In dark mode go to Install from Web, Switch to list mode and hover on any item

### Actual result BEFORE applying this Pull Request
image

### Expected result AFTER applying this Pull Request
image

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on ae6bcbb1f3cb110b9ae53c84d39e38e9fd94ce12<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43017">issues.joomla.org/tracker/joomla-cms/43017</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on ae6bcbb1f3cb110b9ae53c84d39e38e9fd94ce12<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43017">issues.joomla.org/tracker/joomla-cms/43017</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43017">issues.joomla.org/tracker/joomla-cms/43017</a>.</sub>

**Comment by LadySolveig** [comment]
Thank you @brianteeman and also for finding and testing @Quy @viocassel

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
