### PR TITLE
[4.2] com_media (Mediamanager) configuration view. Text fields to textarea.

### PR DESCRIPTION
**Pull request by GHSVS-de**
### Summary of Changes
Changed field types `text` to `textarea`:
- restrict_uploads_extensions
- image_extensions
- audio_extensions
- video_extensions
- doc_extensions
- ignore_extensions
- upload_mime
- ~~upload_mime_illegal~~

Checked that `array_map('trim', explode())` is used consistently at all relevant code points and adapted the code if not. To clarify that step: Joomla core uses `array_map('trim', explode())` nearly at all code points when reading these parameters. I took it over where not.

I haven't included field `upload_mime_illegal` because I couldn't find any usage in core (https://github.com/joomla/joomla-cms/issues/38280).

### Testing Instructions
- Go to mediamanager component > Options.
- Change configuration options.
- Test uploads if settings are respected.
- & code review.

### BEFORE applying this Pull Request

See that some fields are really hard to configure if you use higher window zoom and/or smaller devices:

image

image

### Expected result AFTER applying this Pull Request

Nothing changed but the UI view.

image

image

- Easier to read and configure.
- Even spaces and/or newlines are possible because of consistent usage of `array_map('trim', explode())` in core now.

Change some configuration settings and test if uploads still work like configured even if you add spaces or newlines after commas in textarea. Commas as separators are still mandatory as before!

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 5373646e00129b58a1ddcca19451fb7fb6a510fa<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38281">issues.joomla.org/tracker/joomla-cms/38281</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 5d534b93423b6d3b4c2ba004e62261201b9e101e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38281">issues.joomla.org/tracker/joomla-cms/38281</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38281">issues.joomla.org/tracker/joomla-cms/38281</a>.</sub>

**Comment by roland-d** [comment]
Thank you

**Pull request merged**
