### PR TITLE
nested form in com_joomlaupdate default view

### PR DESCRIPTION
**Pull request by nppsbh**
I think there are nested forms inside com_joomlaupdate default view, getting validation error on https://validator.w3.org/ or just check HTML source code of the page

Correct nested forms inside com_joomlaupdate default view.

### CODE REVIEW

**Comment by brianteeman** [comment]
Updated title<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11232">issues.joomla.org/joomla-cms/11232</a>.</sub>

**Comment by ggppdk** [comment]
> I think there are nested forms inside com_joomlaupdate default view, getting validation error on https://validator.w3.org/ or just check HTML source code of the page

This PR does well to fix this

Now about nesting forms, they are allowed by HTML5 they only need the tag attibute form="..." , after adding it, 

- we can use nested forms, without validation errors  (i am using this)
- we can place fields outside the form TAG  (i am using this) 

e.g. in a modal that is placing form fields directly under body, because of z-index limitations (you have no control of other elements* in document), validating them and then placing them back in their original position

and it used to be that Joomla validation JS supported this,
but then during mootools code removal it was broken

also it is time that JFormField* classes add support for form TAG attribute, and start adding it when flagged to do it

**Comment by ggppdk** [comment]
I can do a couple of PRs if there is agreement about the above

(PRs which are not relevant to current PR now)

 if we add support for form="..." tag attribute then in future the forms can be nested again

**Comment by hardiktailored** [comment]
@ggppdk I had tried form tag too but note that this does not support any IE browsers.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11232">issues.joomla.org/joomla-cms/11232</a>.</sub>

**Comment by ggppdk** [comment]
You mean the  tag attribute "form"

```
<input form="tagid_of_form_tag" ... />
```

Yes you are right, but the updated version of IE10 supporting it
so you have IE10 and IE11 supporting it

**Comment by ggppdk** [comment]
About

> that this does not support any IE browsers.

Even if Joomla will not make use of it yet (i agree on this), since no support of it in IE8 / IE9 and earlier version of IE10

still the JS code **needs to be patched to be ready for it**

**Comment by hardiktailored** [comment]
I have tested this item :white_check_mark: successfully on a483302adc10e715191ffde8182a121c04a6ec7e<br /><br />Patch removes parent form and everything working as expected.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11232">issues.joomla.org/joomla-cms/11232</a>.</sub>

**Comment by hardiktailored** [comment]
@ggppdk Agree.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11232">issues.joomla.org/joomla-cms/11232</a>.</sub>

**Comment by hans2103** [comment]
I have tested this item :white_check_mark: successfully on a483302adc10e715191ffde8182a121c04a6ec7e<br /><br />patch will move form outside form and still works<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11232">issues.joomla.org/tracker/joomla-cms/11232</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11232">issues.joomla.org/tracker/joomla-cms/11232</a>.</sub>

**Comment by jeckodevelopment** [comment]
@brianteeman there's a conflict with this PR
` administrator/components/com_joomlaupdate/views/default/tmpl/default.php `

**Comment by roland-d** [comment]
Merged with commit eb4ddb4a9c836c0f7904f8721d35ffaaa410e4f2

**Pull request closed without merging**
