### PR TITLE
Correct Alt text language string

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #11259
#### Summary of Changes

The tootltip is incorrect (confirmed by @bertmert on #11259)
#### Before

> COM_CONTENT_FIELD_IMAGE_ALT_DESC="Alternative text used for visitors without access to images. Replaced with caption text if it is present."
#### After

> COM_CONTENT_FIELD_IMAGE_ALT_DESC="Alternative text used for visitors without access to images."

### CODE REVIEW

**Comment by bertmert** [comment]
I have tested this item :white_check_mark: successfully on 20d22e1fc434d263ea7a24dbad7292c56cf50e3a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11275">issues.joomla.org/joomla-cms/11275</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 20d22e1fc434d263ea7a24dbad7292c56cf50e3a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11275">issues.joomla.org/joomla-cms/11275</a>.</sub>

**Comment by brianteeman** [comment]
RTC thanks for testing<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11275">issues.joomla.org/joomla-cms/11275</a>.</sub>

**Comment by sonalitailored** [comment]
I have tested this item :white_check_mark: successfully on 20d22e1fc434d263ea7a24dbad7292c56cf50e3a<br /><br />Tested successfully<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11275">issues.joomla.org/joomla-cms/11275</a>.</sub>

**Pull request merged**
