### PR TITLE
php 7.2 fix for count

### PR DESCRIPTION
**Pull request by brianteeman**
PR for #19125
PR for #19126

Can you please test this @quy - I dont have php 7.2 installed yet

If these work then there are lots of other places to be fixed

### CODE REVIEW

**Comment by mbabker** [comment]
We've got type inconsistency problems here.  [`$_items` is initialized as a null value](https://github.com/brianteeman/joomla-cms/blob/804271dec1a5a39f11d365e07a41ae8af3b52318/components/com_contact/models/categories.php#L37) and the `getItems` method sets it to be either an array or a boolean false.  Only the array can be counted.

An empty check might silence the warning, but it really isn't a great fix.  If we're going to keep setting that value as something other than an array, then I'd make the check `!is_array($this->_items)` otherwise we need to do something so it is always an array and handle error cases another way (which probably has B/C issues).

**Comment by brianteeman** [comment]
I suspect that there are a lot of places that a fix will be needed. What I did was just to test. I found two different methods being used in other projects. The one I used here and the one you suggest.

As I dont have php 7.2 installed yet its hard for me to test

**Comment by brianteeman** [comment]
I have changed the pr to use the !is_array check instead of the empty

**Review by mbabker — APPROVED** [review]

**Comment by joomdonation** [comment]
@mbabker isn't **if ($this->_items === null)** better check?

**Comment by mbabker** [comment]
Honestly, both would result in the same right now.  We really should refactor this code to use a consistent type and implement better error handling logic, but that type of work would need to go into 4.0 because there will be B/C implications (`getItems()` should not be able to return an array or boolean false, it should always be an array but then we need to communicate error state too, whether that means use of `getError()`/`setError()` or throwing an exception is to be determined).

**Comment by joomdonation** [comment]
Yes. Both would prevent the warning. However, in theory, if someone creates the model object and calls the method gettems() two times (stupid, I know)

$model->getItems();
$model->getItems();

With is_array check, the second call, the code will still be executed. But with === null, the method will just return $this->_items directly, that's why I think === null is a better check

**Comment by brianteeman** [comment]
@mbabker I just installed 7.2 so I can now check the other possible occurrences. So should I go with your or @joomdonation suggestion

**Comment by brianteeman** [comment]
Looks like the other things I thought might be a problem were not

**Comment by mbabker** [comment]
Use `if ($this->_items === null)`.

**Comment by anuragteapot** [comment]
Can we also use 
<code>if (!is_array($this->_items) && !count($this->_items))</code>
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19135">issues.joomla.org/tracker/joomla-cms/19135</a>.</sub>

**Comment by joomdonation** [comment]
@brianteeman Could you change the code to **if ($this->_items === null)** as it was agreed by Michael?

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 97e3740d5cf2036e06ba19464a75cc13c38e4f38<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19135">issues.joomla.org/tracker/joomla-cms/19135</a>.</sub>

**Comment by joomdonation** [comment]
I have tested this item :white_check_mark: successfully on 97e3740d5cf2036e06ba19464a75cc13c38e4f38<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19135">issues.joomla.org/tracker/joomla-cms/19135</a>.</sub>

**Comment by Quy** [comment]
RTC

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
