### PR TITLE
[4.0] [mod_privacy_status] Parameterized queries

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue # .

### Summary of Changes

Adds parameterized queries and cleans up queries in `mod_privacy_status`.

### Testing Instructions

Go to Privacy Dashboard. View Privacy Status module.

### Expected result

Works like before.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 0ccdc1d762d108c6e8d6a382737870160bd29b38<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27110">issues.joomla.org/tracker/joomla-cms/27110</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on d09283a15940734c7ce8b4ebf1606b455568b2eb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27110">issues.joomla.org/tracker/joomla-cms/27110</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27110">issues.joomla.org/tracker/joomla-cms/27110</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
