### PR TITLE
[4.0] Remove hardcoded extension ID from Update Notification plugin

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue # .

### Summary of Changes

Removes hardcoded Joomla extension ID. See #22374 for background.

### Testing Instructions

Code review.

### Documentation Changes Required
No.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on b81bbc635eb3ee4d657ced05fc6e8c32d2022375<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25412">issues.joomla.org/tracker/joomla-cms/25412</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on b81bbc635eb3ee4d657ced05fc6e8c32d2022375<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25412">issues.joomla.org/tracker/joomla-cms/25412</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25412">issues.joomla.org/tracker/joomla-cms/25412</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
