### PR TITLE
[5.2] [Guided tours] Increase the width and adjust the height of the popup

### PR DESCRIPTION
**Pull request by obuisard**
### Summary of Changes

When creating tours, media content is very limited with the size of the popup.
Shepherd forces a popup width to be 400px max.
This PR proposes to increase the width to 600px and a popup that resizes according to its content.
In the case of a popup positioned a the center of the window, the max width could be increased even more (up to 1200px).

### Testing Instructions

Run a few tours and see if the popups resize properly with different window sizes.
Add an image to a tour, run the tour and look at the result, either in a central position or at a bottom position.

### Actual result BEFORE applying this Pull Request

image

image

image

### Expected result AFTER applying this Pull Request

The content dictates the width of the popups, up to 600px, except for the center popups, up to 1200px.

image

image

image

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
How do you add an image. Every time I insert an image into the description and then save it is removed

**Comment by obuisard** [comment]
> How do you add an image. Every time I insert an image into the description and then save it is removed

Hi Brian, I use 
image

I have not seen the behavior you are experiencing so far.

**Comment by brianteeman** [comment]
tried on two different installs on different servers and the image is removed on save
Even tried without any editor and still no luck

tour

**Comment by obuisard** [comment]
> tried on two different installs on different servers and the image is removed on save Even tried without any editor and still no luck

I believe that is because you left the language key in the content. Have you tried without it? The language key takes precedence over the rest.

**Comment by brianteeman** [comment]
yes that was it. strange that you can add text to the language key but not an image

**Comment by obuisard** [comment]
> yes that was it. strange that you can add text to the language key but not an image

Yes, it has to be improved...

**Comment by brianteeman** [comment]
I have tested this item :red_circle: unsuccessfully on 3a992431e71e6ea1a14357262f5a98199a33d43b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43810">issues.joomla.org/tracker/joomla-cms/43810</a>.</sub>

**Comment by brianteeman** [comment]
It works fine when using a landscape image as shown in your instructions. However if you have a large portrait image it causes problems. Not least of which is that you can not exit the tour as you cannot reach the buttons. 


## Before PR
image

## After PR
image

**Comment by obuisard** [comment]
> It works fine when using a landscape image as shown in your instructions. However if you have a large portrait image it causes problems. Not least of which is that you can not exit the tour as you cannot reach the buttons.

Yes, we had the problem before, even before this PR. The PR increases the width, so it makes the behavior even worse.
So I have added a fix for the height, so every tall popup shows 'elegantly'.

image

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on ed67f8dcb9357aa1d965db315a825ce82332e33e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43810">issues.joomla.org/tracker/joomla-cms/43810</a>.</sub>

**Comment by Kostelano** [comment]
It is not entirely clear what the width of the window depends on. I just used the basic greeting tour and the blocks with roughly the same amount of text were very different in width. In addition, the buttons also “stretched out”.

There is no indentation below from the main block to the buttons. Previously he was.

Screenshot_2

Screenshot_3

**Comment by obuisard** [comment]
> It is not entirely clear what the width of the window depends on. I just used the basic greeting tour and the blocks with roughly the same amount of text were very different in width. In addition, the buttons also “stretched out”.

The popup resizes according to its content with this PR.
When targeting an element on the page, the popup resizes and is not allowed to be bigger than 600px (going over 600px is problematic when the popup needs to show on the left or the right of an element, it can go out of space really fast).
When NOT targeting any element on the page (the popup is showing in the center of the page), the popup can resize up to 1200px (depending also on how large the viewport is).

This is meant to allow more verbose content, images and videos ('what's new' tours -coming soon - will be more verbose). 

People creating tours can visually tweak the tours to show 'elegantly' with this new behavior. It really depends on how the step content is formatted.
All core tours show 'nicely' out of the box with this new change, except for the welcome tour which could use a couple <br /> tags in the content of the 1st and 3rd steps to avoid a long line and expand to full width.

I should probably create a welcome tour PR to that effect.

**Comment by obuisard** [comment]
> There is no indentation below from the main block to the buttons. Previously he was.

> Screenshot_2
> 

I put the padding back, even though it was fixed in PR #43809. Padding needs to be set in both PRs so that content shows as intended when PRs are run separately.

**Comment by webiedesign** [comment]
I have tested this item :white_check_mark: successfully on 479d165521c6b22d80f9b915b426e81b07203143<br /><br />I added images to 2 guided tours and they adapted to my screen resolution up to aprox 1200. Mobile display resized appropriately and the targets remained where they should have.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43810">issues.joomla.org/tracker/joomla-cms/43810</a>.</sub>

**Comment by AboutTimeIT** [comment]
I have tested this item :white_check_mark: successfully on 49065578d59c1392172ba69ec0619246ac734ddb<br /><br />Tested it in ‎5.2.0-alpha3 with a 1280x683 image and a 1070x4182.
The landscape image is resized within the instructionswindow. The portrait image eil get scrollbars on the side of the main window so that the buttons stay available.
The Guided Tours windows stay on their positions when the images are inserted.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43810">issues.joomla.org/tracker/joomla-cms/43810</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43810">issues.joomla.org/tracker/joomla-cms/43810</a>.</sub>

**Comment by pe7er** [comment]
Thanks @obuisard !

**Pull request merged**
