### PR TITLE
[#33687] Fix: Cannot upload file to sub-folder in Media Manager

### PR DESCRIPTION
**Pull request by zero-24**
Tracker:
http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=33687&start=0
http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=33413&start=0
one more:
http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_id=8103&tracker_item_id=33692

Fix based on (german):
http://www.joomlaportal.de/joomla-3-x-installation/309865-sammelthread-joomla-3-3-0-released-2.html#post1534645
http://www.joomla-bugs.de/forum/index.php?topic=582.0

### CODE REVIEW

**Comment by Wequips** [comment]
Could anyone explain to me what a patch is. I'm struggling with the same issue as you all do. The Media Manager. The final step is: apply patch. But I don't know how to do that...

**Comment by sovainfo** [comment]
Sounds like you need to apply #3575 using com_patchtester.

**Comment by Wequips** [comment]
Thanks for messaging!
And this sounds already difficult for me...

**Comment by Bakual** [comment]
This issue is resolved. Updating to the lastest version of Joomla should fix this.

If not, please open a new issue so it can get fixed.

**Comment by Wequips** [comment]
I have this version: Joomla! 3.4.1 

Two weeks ago I was able to make a sub-folder, but now I can't anymore...

**Comment by wilsonge** [comment]
Then you should update to 3.4.3 - which got released yesterday!

**Comment by Wequips** [comment]
OK, I see. Solved. Thaks a lot!

**Pull request closed without merging**
