### PR TITLE
Correct spelling

### PR DESCRIPTION
**Pull request by mbabker**
### Summary of Changes

The word `information` is incorrectly spelled.
### Testing Instructions

Check the diff against a dictionary to ensure the correct spelling is used 😉 
### Documentation Changes Required

N/A

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on b476524df286cb6481ad94414af3f21e9b0e9763<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12564">issues.joomla.org/tracker/joomla-cms/12564</a>.</sub>

**Comment by brianteeman** [comment]
This error came from #8607

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on b476524df286cb6481ad94414af3f21e9b0e9763<br /><br />Ups...<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12564">issues.joomla.org/tracker/joomla-cms/12564</a>.</sub>

**Comment by brianteeman** [comment]
Rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12564">issues.joomla.org/tracker/joomla-cms/12564</a>.</sub>

**Pull request merged**
