### PR TITLE
[Smart Search] Limit memory used by tokeniser

### PR DESCRIPTION
**Pull request by chrisdavenport**
### Summary of Changes

Running the Smart Search indexer on a medium-sized site often results in "out of memory" failures which can only be addressed by running the CLI indexer with more memory allocated, like this:

`php -d memory_limit=256M finder_indexer.php`

However, this option is not usually available for web-based indexing.

It turns out that the problem is largely due to the tokeniser attempting to reduce execution time by caching all previous tokenisations under 128 bytes long.  This PR addresses that issue by limiting the number of cached tokenisations to 100.  Note: the number could be made configurable, but I am doubtful of the benefit to be gained so that is not part of this PR.

Hat tip to @mahagr for pointing out the problem with the tokeniser.

Since this might conceivably be of use elsewhere, the fix has been implemented by adding a new storage class to the JCache library.  The new JCacheStorageMemory class uses a regular PHP array to store cached items.  A maxBuffers option allows you to define the maximum number of items to cache (default 100).  If an attempt is made to store a new item when the cache is already full, the least recently used item will be deleted to make room.
### Testing Instructions

Find or construct a site with enough content that the CLI indexer fails with an out of memory error.  As a rough guide you'll probably need over 1,000 articles to trigger the error.  The size of the articles doesn't matter much because tokenisations of strings more than 128 bytes long are not cached and most articles are likely to be longer than that.

Apply the PR and run the indexer again.  Hopefully you won't get the out of memory error!

I am aware that unit tests need to be added for JCacheStorageMemory and I'd appreciate help in writing them.
### Documentation Changes Required

None.

### CODE REVIEW

**Comment by mahagr** [comment]
I think you meant to thank you someone else than me on this as I wasn't the one who pointed out the issue. :)

**Comment by brianteeman** [comment]
> Find or construct a site with enough content that the CLI indexer fails with an out of memory error.

So is this PR for testing/fixing the CLI or the web indexer

**Comment by chrisdavenport** [comment]
@mahagr I had to dig deep to find it, but here it is: https://developer.joomla.org/joomlacode-archive/issue-28669.html

**Comment by chrisdavenport** [comment]
Both, since they share the same code.  But if you only use the web indexer you're not going to be certain that the failure was caused by an out of memory error.  I don't think the web indexer provides any feedback when it fails.

**Comment by brianteeman** [comment]
ok - I just tried 1500 articles on the web index with 128m ram and it worked before the patch

**Comment by mahagr** [comment]
@chrisdavenport Oh wow, that's like 4 years ago! Now that you did show that to me, I honestly thought it was already fixed a while ago.

I think we were testing smart search support for Kunena back then and had like 250 000 messages to play with. I think the code may still be around somewhere (maybe old revision/version), but it was never used as we couldn't get it to work with indexer.

**Comment by chrisdavenport** [comment]
@brianteeman Thanks for testing.  I think that's on the cusp of failing.  I have a site with 1491 articles (451,506 terms) where it fails.  On another site I have 2509 articles (751,746 terms) where I have to restart the indexer 3 times to get it to index all the content.  Both sites have 128Mb RAM.  With this PR both sites are indexed without running out of memory.

Anyway I thought of another way of testing this PR.  Instead of trying to get it to actually fail, just look at the amount of memory being used.

I have added a couple of PRs to output peak memory usage information:
https://github.com/joomla/joomla-cms/pull/12679 Adds it to the CLI indexer output.
https://github.com/joomla/joomla-cms/pull/12680 Adds it to the web indexer log.

You should see a dramatic reduction in the memory usage.

**Comment by brianteeman** [comment]
OK I will test that approach

**Comment by alikon** [comment]
i've tested in the other way via CLI
cli
first run without PR second with PR
something like 10% less memory

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on b6e14c4b8fc48b351533b2279ffcea2cabed022c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12649">issues.joomla.org/tracker/joomla-cms/12649</a>.</sub>

**Comment by tonypartridge** [comment]
I have tested this item :white_check_mark: successfully on c0482b2d86c35f711aa92599dcb6c7224c8a68c0<br /><br />I've tested this on Joomla! 3.7.2 with a smaller number of articles, but saw a good reduction in execution time. .716 seconds to .541 seconds. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12649">issues.joomla.org/tracker/joomla-cms/12649</a>.</sub>

**Comment by zero-24** [comment]
RTC. Needs to be synced with staging before the merge.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12649">issues.joomla.org/tracker/joomla-cms/12649</a>.</sub>

**Comment by brianteeman** [comment]
branch updated ;)

**Comment by rdeutz** [comment]
@nikosdion because it is an addition, it looks good for me. But you offered help to have a look at library code, so here we are :-)

**Review by nikosdion — CHANGES_REQUESTED** [review]
The new cache storage handler will appear in Joomla's Global Configuration. See JFormFieldCacheHandler::getOptions() which calls JCache::getStores(). Unfortunately, the new cache handler only offers volatile caching which is not committed anywhere after the application shutdown _and_ increases the memory usage by as much as the output will be in the case of the CMS. It is bad UX and a source of potential confusion and issues for the CMS users.

Proposed solution: JCache::getStores() should have an optional parameter $persistentOnly set by default to false. When it's true only cache storage adapters with the isPersistent flag should be returned.

JCacheStorage should have a protected static property $isPersistent set by default to true. Non-persistent storage adapters, like JCacheStorageMemory, should override that flag, setting it to false. 

Moreover, JCacheStorage should have a static method isPersistent() which returns the content of said flag.

Finally, JFormFieldCacheHandler should replace line 46 with `$options = array_merge(parent::getOptions(true), $options);`

I would also ask @mbabker to chip in, in case I am missing something with relation to the Framework.

**Comment by rdeutz** [comment]
set to needs review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12649">issues.joomla.org/tracker/joomla-cms/12649</a>.</sub>

**Comment by brianteeman** [comment]
something isnt right @chrisdavenport with 950 changed files

**Comment by rdeutz** [comment]
@chrisdavenport you need to rebase your branch and not merge staging into your branch

**Comment by chrisdavenport** [comment]
Grrr.  I have no idea how to fix that.  Any clues?

**Comment by nikosdion** [comment]
Create a new local branch out of your repo branch. Hard reset to your last commit before the merge. Then you should be able to rebase it to staging.

**Comment by chrisdavenport** [comment]
Thanks @nikosdion I'll try that tonight after work.

**Comment by chrisdavenport** [comment]
Closing in favour of #16621 as I wasn't able to fix the git problem despite @nikosdion 's generous assistance.

**Pull request closed without merging**
