### PR TITLE
[4.1] 'isset' can be replaced with coalesce

### PR DESCRIPTION
**Pull request by PhilETaylor**
Code review

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 51c206dc1b198eb56aec593a112000a090d6f695<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36377">issues.joomla.org/tracker/joomla-cms/36377</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 069704abd6f9324f8c783731bdcb05897d74c0b4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36377">issues.joomla.org/tracker/joomla-cms/36377</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36377">issues.joomla.org/tracker/joomla-cms/36377</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
