### PR TITLE
[4.2] Improve description for Users MFA configuration

### PR DESCRIPTION
**Pull request by chmst**
### Summary of Changes
Descriptions are shown after the input field. So the word "following" for selected entries is not correct and replaced by "selected"

### Testing Instructions
Go to Global Configuration - users - Tab Multi Factor Authentication
Click the toggle inline help button (top right)

### Actual result BEFORE applying this Pull Request
grafik

### Expected result AFTER applying this Pull Request
grafik

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 8aefaa958f63f3c3a7f6a0125649ef7cd34128a1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38537">issues.joomla.org/tracker/joomla-cms/38537</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 8aefaa958f63f3c3a7f6a0125649ef7cd34128a1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38537">issues.joomla.org/tracker/joomla-cms/38537</a>.</sub>

**Comment by jwaisner** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38537">issues.joomla.org/tracker/joomla-cms/38537</a>.</sub>

**Review by tecpromotion — APPROVED** [review]

**Comment by roland-d** [comment]
Thank you

**Pull request merged**
