### PR TITLE
[4.1][bugfix] Fix language inheritance for child template

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue #36218 .

### Summary of Changes
- Load the language files similar to https://github.com/joomla/joomla-cms/blob/40eff93677773b400fddcc4123af06a7216eec52/administrator/components/com_templates/src/Model/StyleModel.php#L420-L425 so that inheritance is followed correctly.

### Testing Instructions
Goto /administrator/index.php?option=com_templates&view=template and check the description for a child template

### Actual result BEFORE applying this Pull Request

Weird text

### Expected result AFTER applying this Pull Request

Readable text

### Documentation Changes Required

No, this is a bug

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on dcf0bcf7895ce183982daeafb3cbc1be32e082a4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36219">issues.joomla.org/tracker/joomla-cms/36219</a>.</sub>

**Comment by khu5h1** [comment]
I have tested this item :white_check_mark: successfully on dcf0bcf7895ce183982daeafb3cbc1be32e082a4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36219">issues.joomla.org/tracker/joomla-cms/36219</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36219">issues.joomla.org/tracker/joomla-cms/36219</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
