### PR TITLE
Prevent duplicate message output

### PR DESCRIPTION
**Pull request by bembelimen**
Sometimes, Joomla! outputs the same message twice.
## Test:
1. Create a link to the user profile and set the access to "registered" (make sure, that you have no other link to the user component)
2. Activate the login module (public)
3. Log in
4. Go to the profile and log out over the module
5. The message "Please login first" should be shown twice
6. Apply patch => try again

### CODE REVIEW

**Comment by chmst** [comment]
@test successful on 3.4.5

**Comment by jduerscheid** [comment]
sorry can not repoduce the error.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8152">issues.joomla.org/joomla-cms/8152</a>.</sub>

**Comment by bembelimen** [comment]
It's important, that the menu entry, you redirect after the log out is set to registered. But in general, it should work in every case, where two identic messages are triggered.

**Comment by designbengel** [comment]
Sorry tried like described and can´t reproduce also<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8152">issues.joomla.org/joomla-cms/8152</a>.</sub>

**Comment by chmst** [comment]
To make it more simple: Forget the profile-stuff from bembelimens instruction,
-  just set your homepage to registered.
You will get something like this 
before-patch

Apply the patch 
You will get only one message-line
patch-applied

**Comment by zero-24** [comment]
I can reproduce it with the following steps.

- go to the frontend login form from com_user
- enter some none sense login information (z.B. aa/bb)
- hit the "login" button lets say 10 times (very fast)
- see the dublicated messages
- apply the patch
- try it again
- see that the dublicate messages are gone


Importend for testig hitting the login button 10 times don't mean that we get 10 messages i just got between 3 and 5 messages if i hit the login buton 10 times :smiley: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8152">issues.joomla.org/joomla-cms/8152</a>.</sub>

**Comment by bembelimen** [comment]
Hello,
the bug is not the logout but multiple messages in general. That "logout trick" was just anice example. But as @zero-24 showed,it can happen on multiple places.

**Comment by n9iels** [comment]
I have tested this item :white_check_mark: successfully on cc80adf4064a4a4d24b107cd554ee6a8823ac07a<br /><br />I can reproduce the issue, and the patch solves it :)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8152">issues.joomla.org/joomla-cms/8152</a>.</sub>

**Comment by zero-24** [comment]
RTC Travis fails just on the known "now" problem. Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8152">issues.joomla.org/joomla-cms/8152</a>.</sub>

**Pull request merged**
