### PR TITLE
[5.0] Move from static Text access to the text function of the view

### PR DESCRIPTION
**Pull request by laoneo**
### Summary of Changes
The `_` function should be used in view template files to translate strings. This eliminates the static use of `Text::_`. When template files start to use functionality from the current context it will allow them to be reusable.

### Testing Instructions
Browse around in joomla in the back and front end.

### Actual result BEFORE applying this Pull Request
All views have translated strings.

### Expected result AFTER applying this Pull Request
All views have translated strings.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by HLeithner** [comment]
still not happy polluting the view class with a none meanful function name '_'

**Comment by laoneo** [comment]
Then please come up with a better name.

**Comment by HLeithner** [comment]
Our framework language class uses  `translate` as function name

**Comment by brianteeman** [comment]
> Our framework language class uses `translate` as function name

or simply `text`

**Comment by laoneo** [comment]
I like `text`! This never popped up in my mind as I did #40614.

**Comment by brianteeman** [comment]
to me it makes more sense than translate as that will confuse some people who say "but i only want one language" - its also shorter and easier to type

**Comment by laoneo** [comment]
Here we go #41079.

**Comment by nikosdion** [comment]
I find all these changes actively harmful, impractical, and beyond reason.

They break a long standing convention of 17 years for translating strings. It breaks existing tooling which was based on the unambiguous use of `Text::_()` to detect language strings. It makes it harder for site integrators, especially given that there will be a mix of methods during Joomla 5's lifetime at the very least i.e. until the end of _2027_. It encourages 3PDs to create their own abstraction frameworks, like I had done with FOF, to isolate themselves from the constant nonsensical changes in Joomla, promoting further fragmentation.

In the end of the day, having Text as a static helper class is a good thing. There is only one language, and it's global throughout the CMS. You can call `Text::_()` no matter if you are in a view template of a component, module, or plugin, in a Model, Controller, or View Controller (what Joomla! calls "View"), or any other kind of code. 

Having to think about how to get the global language in each place is an unnecessary burden on the developer. There's not a single framework or CMS out there, from Laravel to WordPress, which asks you to solve a puzzle as to how to get the language object to output a translated string.

**Comment by brianteeman** [comment]
i keep asking the same question - why?

**Comment by nikosdion** [comment]
I also notice other changes which are pointless, and have unintended consequences. 

For example, the signature of the CMSPlugin constructor changed from `public function __construct(&$subject, $config = [])` to `public function __construct(DispatcherInterface $dispatcher, array $config = [])` which breaks PHP 8 calling conventions e.g. `$plugin = new MyPluginClass(subject: $dispatcher, config: $pluginParams)`. There was no practical reason to make this change.

All these are pointless changes which create an artificial burden for developers and site integrators. It would make perfect business sense for 3PDs to not support Joomla 5 until they absolutely have to, around the time Joomla 5.3 or 5.4 is released in two years. Then core maintainers will complain that 3PDs don't support new Joomla versions, overlooking the fact that this is a problem caused by their own pointless _and undocumented_ changes which make supporting a new major version not make any business sense for 3PDs.

**Comment by laoneo** [comment]
And you have pointed out the biggest issue which was leading to this change. We are still using code which was written 17 years ago. Because of this we should recap if it is still the right what we do nowadays. I mean, we give plenty of time to adapt, there is no rush for 3rd party extension developers here. As long as `Text` is widely used in the eco system, it makes no sense to remove it. Even when it is Joomla 6,7 or 8. We learned from the mistakes in the past and do give the developers enough time for adoption.

**Comment by laoneo** [comment]
We will come up with another solution which is less context aware.

**Pull request closed without merging**
