### PR TITLE
[Sql azure] Normalize joomla install sample blog sql file

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
### Summary of Changes

Normalizes all sql azure joomla install file.
- always use `SET IDENTITY_INSERT [#__xxxx] ON/OFF;`
- `INSERT` to `INSERT INTO`
- Quote all table names and db field names
- Always use `'` to quote string values.
- Code style
### Testing Instructions

Mainly code review. (to many changes need to check code in raw) 
https://github.com/andrepereiradasilva/joomla-cms/blob/sqlazure-sample-blog/installation/sql/sqlazure/sample_blog.sql
If anyone could test an install 3.6.x would be great. Don't have sql azure to test,
### Documentation Changes Required

None.

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 6bbeaa1155555b16e43742896f23f5de0b71cce1<br /><br />on code review still unable to test on MSSQL<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11726">issues.joomla.org/joomla-cms/11726</a>.</sub>

**Comment by waader** [comment]
I have not tested this item.<br /><br />I get this error:

[Microsoft][SQL Server Native Client 11.0][SQL Server]Incorrect syntax near the keyword 'UNION'. SQL=INSERT INTO [#__categories] ([id], [asset_id], [parent_id], [lft], [rgt], [level], [path], [extension], [title], [alias], [note], [description], [published], [checked_out], [checked_out_time], [access], [params], [metadesc], [metakey], [metadata], [created_user_id], [created_time], [modified_user_id], [modified_time], [hits], [language], [version]) UNION ALL SELECT 1, 0, 0, 0, 17, 0, '', 'system', 'ROOT', 'root', '', '', 1, 0, '1900-01-01 00:00:00', 1, '{}', '', '', '', 628, '2011-01-01 00:00:00', 0, '1900-01-01 00:00:00', 0, '*', 1 UNION ALL SELECT 2, 27, 1, 1, 2, 1, 'uncategorised', 'com_content', 'Uncategorised', 'uncategorised', '', '', 1, 0, '1900-01-01 00:00:00', 1, '{"target":"","image":""}', '', '', '{"page_title":"","author":"","robots":""}', 628, '2011-01-01 00:00:00', 0, '1900-01-01 00:00:00', 0, '*', 1 UNION ALL SELECT 3, 28, 1, 3, 4, 1, 'uncategorised', 'com_banners', 'Uncategorised', 'uncategorised', '', '', 1, 0, '1900-01-01 00:00:00', 1, '{"target":"","image":"","foobar":""}', '', '', '{"page_title":"","author":"","robots":""}', 628, '2011-01-01 00:00:00', 0, '1900-01-01 00:00:00', 0, '*', 1 UNION ALL SELECT 4, 29, 1, 5, 6, 1, 'uncategorised', 'com_contact', 'Uncategorised', 'uncategorised', '', '', 1, 0, '1900-01-01 00:00:00', 1, '{"target":"","image":""}', '', '', '{"page_title":"","author":"","robots":""}', 628, '2011-01-01 00:00:00', 0, '1900-01-01 00:00:00', 0, '*', 1 UNION ALL SELECT 5, 30, 1, 7, 8, 1, 'uncategorised', 'com_newsfeeds', 'Uncategorised', 'uncategorised', '', '', 1, 0, '1900-01-01 00:00:00', 1, '{"target":"","image":""}', '', '', '{"page_title":"","author":"","robots":""}', 628, '2011-01-01 00:00:00', 0, '1900-01-01 00:00:00', 0, '*', 1 UNION ALL SELECT 7, 32, 1, 11, 12, 1, 'uncategorised', 'com_users', 'Uncategorised', 'uncategorised', '', '', 1, 0, '1900-01-01 00:00:00', 1, '{"target":"","image":""}', '', '', '{"page_title":"","author":"","robots":""}', 628, '2011-01-01 00:00:00', 0, '1900-01-01 00:00:00', 0, '*', 1 UNION ALL SELECT 9, 35, 1, 15, 16, 1, 'blog', 'com_content', 'Blog', 'blog', '', '', 1, 0, '1900-01-01 00:00:00', 1, '{"category_layout":"","image":""}', '', '', '{"author":"","robots":""}', 628, '2011-01-01 00:00:00', 0, '1900-01-01 00:00:00', 0, '*', 1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11726">issues.joomla.org/joomla-cms/11726</a>.</sub>

**Comment by andrepereiradasilva** [comment]
fixed, can you test again?

**Comment by waader** [comment]
I have tested this item :white_check_mark: successfully on 1ab684e65894fb42f2f042364cc742e6e0b94cfc<br /><br />Works now, thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11726">issues.joomla.org/joomla-cms/11726</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11726">issues.joomla.org/joomla-cms/11726</a>.</sub>

**Pull request merged**
