### PR TITLE
Rename incorrectly cased files on updates or when fixing database

### PR DESCRIPTION
**Pull request by richard67**
Pull Request for Issues https://github.com/joomla/joomla-cms/issues/23725 and  https://github.com/joomla/joomla-cms/issues/30736 .

Replaces Pull Request #30802 .

### Summary of Changes

This pull request (PR) attempts to implement case sensitive file rename and rename some incorrectly cased files.

It is based on PR #30802 plus my corrections for OSX.

Thanks to @SharkyKZ for the original PR #30802.

### Testing Instructions

Testers please report back which server operating system (Linux, Windows, OSX) you have used for your test. If you have several available, test with all of them.

Install Joomla! <= 3.9.23 => check the following files: https://github.com/joomla/joomla-cms/blob/f3666c8062d4dd7f4b204cda28967bba6ed7f04f/administrator/components/com_admin/script.php#L2670-L2674
Use the [update package built by drone for this PR](https://ci.joomla.org/artifacts/joomla/joomla-cms/staging/32006/downloads/39020/Joomla_3.9.24-dev+pr.32006-Development-Update_Package.zip) for Update
- Update with the Joomla Updater 
- Copy the files via FTP and use "Fix Database"
- Install the [installation package built by drone for this PR](https://ci.joomla.org/artifacts/joomla/joomla-cms/staging/32006/downloads/39020/Joomla_3.9.24-dev+pr.32006-Development-Full_Package.zip) as a fresh installation

Now check the file list again => files should in all three test cases have the correct name.

### Actual result BEFORE applying this Pull Request

Incorrectly cased files present.

### Expected result AFTER applying this Pull Request

No incorrectly files after update or database fix or new installation.

### Documentation Changes Required

None.

### CODE REVIEW

**Comment by richard67** [comment]
@bembelimen @chmst @softforge @wilsonge Please test.

**Comment by jsubri** [comment]
I have tested this item :white_check_mark: successfully on 4d0ca0f01f660c8ccd4e70067b892a5af2ee0e7c<br /><br />I restored a 3.9.23 site that was upgraded over the years. Upload & Update "Joomla_3.9.24-dev+pr.32006-Development-Update_Package.zip" via Joomla Update.
Before: Stringcontroller.php after: StringController.php
Before: Xsalsa20.php after: XSalsa20.php
Before: no si_LK.gif file (the file might have been forgoten in some 3.x upgrade packages), after: si_lk.gif is present

Windows 10, PHP 8.0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32006">issues.joomla.org/tracker/joomla-cms/32006</a>.</sub>

**Comment by PhilETaylor** [comment]
> use "Fix Database"

The "Fix Database" button really needs to be renamed to "Fix everything" and possibly relocated somewhere else, as it now does a lot more than just apply any pending database schema changes which was its original aim.

**Comment by richard67** [comment]
> The "Fix Database" button really needs to be renamed to "Fix everything" and possibly relocated somewhere else, as it now does a lot more than just apply any pending database schema changes which was its original aim.

Sure, but that's outside the scope of this PR.

**Comment by brianteeman** [comment]
Using the "Fix database" button for this is fundamentally wrong. 

Joomla 4 has already changed its name to Database: update structure to try to make it clearer that it only touches database structure changes and not any content changes.

Adding a fix files functionality to this button is a step backwards not forwards.

**Comment by richard67** [comment]
> Joomla 4 has already changed its name to Database: update structure to try to make it clearer that it only touches database structure changes and not any content changes.

And that was wrong because currently it still does other stuff, too.

> Adding a fix files functionality to this button is a step backwards not forwards.

Yes, but it wasn't in the scope of the original PR #30802 either to fix that all.

**Comment by wilsonge** [comment]
I have tested this item :white_check_mark: successfully on 4d0ca0f01f660c8ccd4e70067b892a5af2ee0e7c<br /><br />Works on OSX for me PHP 7.3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32006">issues.joomla.org/tracker/joomla-cms/32006</a>.</sub>

**Comment by richard67** [comment]
Would be nice to get a test on Linux, too.

**Comment by HLeithner** [comment]
Tested on Linux works as expected.

**Comment by ghost** [comment]
RTC?

**Comment by richard67** [comment]
@gostn Please stop to tell us maintainers and JBS members what we shall do. We know it by ourselves.

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32006">issues.joomla.org/tracker/joomla-cms/32006</a>.</sub>

**Comment by ghost** [comment]
Please stop your personal attacks. I was asking (!) for RTC cause sometimes it is forgotton.

**Comment by richard67** [comment]
@gostn If you see a personal attack (I don't see some) feel free to contact conflict resolution team and report a CoC violation.

**Comment by gostn** [comment]
> Please stop to tell us maintainers and JBS members what we shall do. We know it by ourselves.

Please stop to tell us community members what we shall do. We know it by ourselves.

**Comment by ghost** [comment]
> Please stop to tell us maintainers and JBS members what we shall do. We know it by ourselves.

Please stop to tell us volunteers what we shall do. We know it by ourselves.

**Pull request merged**
