### PR TITLE
[4.0] Media manager compiled using rollup

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # .

### Summary of Changes
The main course here is the remove of webpack and compiling Media Manager with Rollup, but there are couple more:
- drop the dependency `FileSaver`, we can do that in few lines: 
Screenshot 2021-02-18 at 15 31 14
- drop the `path` dependency (the reason is that it is commonJS and ruins the whole package) for own implementation (based on the actual code of NODEJS)
- Moved the scss files in the build/media_source/com_media where is the appropriate place
- drop webpack with all the related dependencies
- Move the javascript tests to it's own package.json
- Move the `selenium-standalone` dependency directly to done.yml

### Testing Instructions
On a clean locally git cloned repo run `npm install` (or `npm ci`)
Check that the media manager has no bugs (create a folder, delete it, rename a folder, upload a file, rename a file, delete a file, download a file, edit a file)

### CODE REVIEW

**Comment by brianteeman** [comment]
> The installation process will be a bit verbose about the polyfills the Media manager needs for the IE11 version, this is expected

I thought we weren't supporting ie?

**Comment by dgrammatiko** [comment]
> I thought we weren't supporting ie?

Well, the build tools still produce IE compatible scripts, but there is a discussion about this https://github.com/joomla/joomla-cms/discussions/32148 In short I'm just fixing things without imposing decisions, if the PT decides to drop IE scripts it will be a modification of few lines...

**Comment by dgrammatiko** [comment]
@richard67 can you accept the Drone.yml changes in the Drone GUI?

**Comment by richard67** [comment]
@dgrammatiko You mean if I can re-sign that with a new checksum? Theoretically (privileges) I think yes, practically (experience) not yet. Maybe @HLeithner can help faster than I could?

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on b295c559931c801361e25f4c281c5bc4ccf1c10f<br /><br />Media manager works as expected.

Created folder
Deleted folder
Renamed folder and files
Uploaded a file
Deleted files
Edited multiple files
Downloaded files<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32459">issues.joomla.org/tracker/joomla-cms/32459</a>.</sub>

**Comment by richard67** [comment]
@jwaisner Your test doesn't include the last 2 commits. The test shows commit b295c55 , but meanwhile we have a6adafc . Could you just pull the patch again and test again? Thanks in advance.

**Comment by richard67** [comment]
@dgrammatiko Can't help you with signing the .drone.yml file, sorry.

**Comment by richard67** [comment]
@dgrammatiko Ahh wait, I did not read right .. you wrote drone GUI. Am checking now and see I have an "approve" buttons, so seems I can ;-)

**Comment by richard67** [comment]
Hmm, no, doesn't work for me.

**Comment by dgrammatiko** [comment]
> Hmm, no, doesn't work for me.

Yeah some changes require the changes from https://github.com/joomla/joomla-cms/pull/32315. Reverted that part, will do another PR for those

**Comment by richard67** [comment]
@dgrammatiko My "Hmm, no, doesn't work for me." was referring to that drone signature thing, not to testing your PR.

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 21d25790357e873665c92b17acb8006a4371fba2<br /><br />Testing is still good after changes.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32459">issues.joomla.org/tracker/joomla-cms/32459</a>.</sub>

**Comment by dgrammatiko** [comment]
@HLeithner could you unlock the drone here? Thanks

**Comment by wilsonge** [comment]
Can we leave the tests in the main package.json please. After our previous experience I think it's a bad thing to have this separated. I understand it makes most people's build times faster - but I'm sure it's bad from an overall maintenance perspective

**Comment by dgrammatiko** [comment]
sure

@wilsonge done

**Comment by wilsonge** [comment]
Tests are passing here on media manager so I'm happy with this

**Comment by wilsonge** [comment]
Thanks!

**Comment by dgrammatiko** [comment]
Thanks
@wilsonge I'm pretty confident that Media manager is now usable on IE (I mean the js part) but I'll ask @Fedik to check it

**Comment by Fedik** [comment]
well, Media manager works "very clear" in IE :smile: 
Screenshot_2021-02-21_15-15-26

**Comment by dgrammatiko** [comment]
@Fedik try again with https://github.com/joomla/joomla-cms/pull/32485 I missed a rollup plugin 🤦‍♂️

But the question is: do you get errors in the console?

**Comment by Fedik** [comment]
errors I posted in another PR, they all the same on every page,
but I did not seen errors related to MediaManager scripts

**Comment by Fedik** [comment]
I tried to clear cache, a couple times, all the same,
but guess it not much important :smile: 

if you like to play with it, you can use this https://developer.microsoft.com/en-us/microsoft-edge/tools/vms/
as I made

**Pull request merged**
