### PR TITLE
[com_redirect] Improve disabled redirect plugin message

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Summary of Changes

Simple PR to improve the disable redirect system plugin message in com_redirect.

Before (message is an error and the link is to the plugin list with harcoded text search)
image

After (message is a warning and the link is now to edit the redirect system plugin)
image
#### Testing Instructions

Code review, or:
1. Use latest staging
2. Disable redirect systme plugin
3. Go to Components -> Redirect and check the error message. Click the link, you'll be redirected to the plugin manager list view with a search.
4. Apply patch
5. Go to Components -> Redirect and check the warning message. Click the link, you'll be redirected to directly edit the redirect plugin.

### CODE REVIEW

**Comment by brianteeman** [comment]
Other than the obvious change from an error to a warning what is the benefit of the code change to stop it being a hard link in the language file? And presumably if accepted you will be doing the same for other hard coded links in language strings.

**Comment by andrepereiradasilva** [comment]
> what is the benefit of the code change to stop it being a hard link in the language file?

IMO you shouldn't depend on the translate for the links to be correct.
We have ids for the extensions, so we should use it.

> And presumably if accepted you will be doing the same for other hard coded links in language strings.

right

**Comment by BurtNL** [comment]
I have tested this item :white_check_mark: successfully on a5c8ade19523c35be191ffe90711b19acc57d777<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10688">issues.joomla.org/joomla-cms/10688</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on a5c8ade19523c35be191ffe90711b19acc57d777<br /><br />Indeed, we should manage to use non hardcoded links when possible in language strings.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10688">issues.joomla.org/joomla-cms/10688</a>.</sub>

**Comment by infograf768** [comment]
RTC. Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10688">issues.joomla.org/joomla-cms/10688</a>.</sub>

**Comment by roland-d** [comment]
Thanks everybody

**Pull request merged**
