### PR TITLE
Multilanguage: joomla installation without localised content ignored

### PR DESCRIPTION
**Pull request by infograf768**
Ths PR to solve https://github.com/joomla/joomla-cms/issues/8192
screen shot 2015-10-29 at 17 02 18

To test, verify that installing Joomla as a multilanguage site can be done with and without localised content.

### CODE REVIEW

**Comment by javigomez** [comment]
I can confirm the issue: https://www.youtube.com/watch?v=XdGPuIM0ios

testing the patch...<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8203">issues.joomla.org/joomla-cms/8203</a>.</sub>

**Comment by javigomez** [comment]
I have tested this item :white_check_mark: successfully on 83cc0d65dcc834ce536fed6b74e118e956d542b8<br /><br />I haven't checked the code, just tested the patch and it works

With this patch the:

'Install localised content', 'Yes'
Creates dummy articles in different languages

'Install localised content', 'No'
No dummy articles are created


<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8203">issues.joomla.org/joomla-cms/8203</a>.</sub>

**Comment by jancinert** [comment]
I reviewed the code and it passed my review.

**Comment by infograf768** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8203">issues.joomla.org/joomla-cms/8203</a>.</sub>

**Comment by Kubik-Rubik** [comment]
Thank you @infograf768 and testers! Merged.

**Pull request merged**
