### PR TITLE
[4.0] Plugin description

### PR DESCRIPTION
**Pull request by brianteeman**
Updates the description of the Language Filter plugin. The recommendation is not valid in J4 as the module will be automatically displayed. The information in bold is not correct.

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 468c7f38eb2f649a5c10e4968ad6cb894889fbd9<br /><br />"Code" review: Is all correct, statement is decription about why this change is done is correct, too.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25249">issues.joomla.org/tracker/joomla-cms/25249</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 468c7f38eb2f649a5c10e4968ad6cb894889fbd9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25249">issues.joomla.org/tracker/joomla-cms/25249</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25249">issues.joomla.org/tracker/joomla-cms/25249</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
