### PR TITLE
Added the missing a close tag

### PR DESCRIPTION
**Pull request by rdeutz**
Added the missing a close tag

### CODE REVIEW

**Comment by Hackwar** [comment]
@test success via codereview. Could you please add one empty line at the end of the file?

**Comment by zero-24** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5723">issues.joomla.org/joomla-cms/5723</a>.</sub>

**Comment by zero-24** [comment]
moving back to pending as the missing line that was find by @Hackwar <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5723">issues.joomla.org/joomla-cms/5723</a>.</sub>

**Comment by rdeutz** [comment]
How I get this fixed? I did a commit with an empty line (amend) it with the one I already did. In my branch the file  has 193 lines so there is a new line at the end of the file. If I delete the local file and pull from my branch I get a file with an empty line at the end. So anything looks fine. Does github not showing the empty line at the end of the file?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5723">issues.joomla.org/joomla-cms/5723</a>.</sub>

**Comment by Hackwar** [comment]
It's okay the way it is. If there is no linebreak after the last command, github shows a red error behind the last command. So this is fixed and ready to be merged.

**Comment by zero-24** [comment]
Thanks @Hackwar moving back to RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5723">issues.joomla.org/joomla-cms/5723</a>.</sub>

**Pull request merged**
