### PR TITLE
[4] Requesting to be added to code owners

### PR DESCRIPTION
**Pull request by PhilETaylor**
Requesting to be added to code owners for tests/Unit

### CODE REVIEW

**Comment by PhilETaylor** [comment]
Drone failure unrelated to PR content

**Comment by wilsonge** [comment]
Enjoy!

**Comment by PhilETaylor** [comment]
Gulp! haha Thanks.

**Comment by HLeithner** [comment]
What's the reason for your request?

**Comment by PhilETaylor** [comment]
"Code owners are automatically requested for review when someone opens a pull request that modifies code that they own"

Own is a harsh word. Contribute to and have experience of is a better phrase. 

Seriously though - something has to be done about the low quality of code in Joomla - if Joomla is to survive as a Modern PHP Application (rather than a shiny frontend) - and Unit Testing is something I have considerable experience in for huge projects. I guess I just had a moment of pity. 

There are only a few people providing any unit tests at all recently - and certainly there is a lot to do at the Joomla 4+ level (Im not touching 3 unit tests, I know you are refactoring those)

What is your reason for questioning my involvement? 

However:

"The people you choose as code owners must have write permissions for the repository"

Oh well that means this should be reverted ... oh well nice while it lasted..

**Comment by brianteeman** [comment]
it doesnt work if you dont have  the correct permissions

**Comment by PhilETaylor** [comment]
Like I said. 

> "The people you choose as code owners must have write permissions for the repository"
> Oh well that means this should be reverted ... oh well nice while it lasted..

And I don't want write permissions to this repo. Ever.

**Comment by HLeithner** [comment]
@PhilETaylor that's the reason I asked, with out the permissions it doesn't work. But george should know that...

Anyway yes you are right we need more tests, but we shouldn't do this uncoordinated. Doesn't mean your help isn't appreciated, actually it is.

I revert the pr since as you already found out too it doesn't work as expected.

**Pull request merged**
