### PR TITLE
[4.1] Enabled to focus in media files

### PR DESCRIPTION
**Pull request by khu5h1**
Pull Request for Issue #35229 .

### Summary of Changes
I have enabled focus on media files by changing their `tabindex` from -1 to 0.

### Testing Instructions
Check out issue #35229 for testing and reproducing the PR.

### Actual result BEFORE applying this Pull Request
Unable to focus on media files while using the tab button.

### Expected result AFTER applying this Pull Request
Enabled to focus in media files using the tab button.

### CODE REVIEW

**Comment by manav014** [comment]
I have tested this item :white_check_mark: successfully on 4bd85f51673562d5ca6ae89bf964feecdf38b3f3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35911">issues.joomla.org/tracker/joomla-cms/35911</a>.</sub>

**Comment by richard67** [comment]
@khu5h1 Shouldn't it be changed here, too? https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_media/resources/scripts/components/tree/drive.vue#L45

**Comment by Fedik** [comment]
@khu5h1 as I see from code you change tabindex to `-1` when `isActive` that meant tab index is disabled.
the fix does not looks right, there probably error in another place

**Comment by brianteeman** [comment]
Does it even need a tabindex - ever?

**Comment by Fedik** [comment]
> Does it even need a tabindex - ever?

If it non interactive element (like a, button, input), and need "tab navigation" then yes.

**Comment by Fedik** [comment]
@khu5h1 change your code to:
```
getTabindex() {
  return  0;
}
```
Then all be good

**Comment by brianteeman** [comment]
> If it non interactive element (like a, button, input), and need "tab navigation" then yes

buttons and inputs are interactive

**Comment by Fedik** [comment]
> buttons and inputs are interactive

yes, I meant: .. if not like a button or input ;)

**Comment by richard67** [comment]
> @khu5h1 change your code to:
> 
> ```
> getTabindex() {
>   return  0;
> }
> ```
> 
> Then all be good

@Fedik Should that also be done at the other place which I‘ve mentioned in my previous comment?

**Comment by Fedik** [comment]
there can stay as is, if it works

**Comment by richard67** [comment]
Silly question: Why is this PR targeted for 4.1? Is it a new feature? If it's a bug fix it should go into 4.0.

**Comment by khu5h1** [comment]
Thank you @Fedik for your suggestion and I have committed the desired change. 
And as per @richard67 's comment, I am not sure that whether we shall commit the change to `drive.vue`  or not. As IMO that won't have any impact on the issue.
Regards

**Comment by khu5h1** [comment]
> Silly question: Why is this PR targeted for 4.1? Is it a new feature? If it's a bug fix it should go into 4.0.

I am not sure about that, If that's the case, I will have to rebase my PR to `4.0-dev`. I may do that if that sounds good.

**Comment by encrypt3r12** [comment]
I have tested this item :white_check_mark: successfully on 7a8a0d3047e31167b3ba2441f8bbc111324ecfc0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35911">issues.joomla.org/tracker/joomla-cms/35911</a>.</sub>

**Comment by manav014** [comment]
I have tested this item :white_check_mark: successfully on 7a8a0d3047e31167b3ba2441f8bbc111324ecfc0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35911">issues.joomla.org/tracker/joomla-cms/35911</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35911">issues.joomla.org/tracker/joomla-cms/35911</a>.</sub>

**Comment by richard67** [comment]
@khu5h1 Why do you update your branch without any need? Any new commit resets the human test counter and we have to set the test result again then for the tests being properly counted. To update the branch is only needed when GitHub shows conflicting files.

**Comment by khu5h1** [comment]
@richard67 I was not aware of the same. Thanks for your comment. I will keep this in mind for future PRs.

Also, I would request @encrypt3r12 and @manav014 to please test this PR again.

**Comment by encrypt3r12** [comment]
I have tested this item :white_check_mark: successfully on cf80dbcca616bdad4583fc9c3af9fede600681ac<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35911">issues.joomla.org/tracker/joomla-cms/35911</a>.</sub>

**Comment by khu5h1** [comment]
I have tested this item :white_check_mark: successfully on cf80dbcca616bdad4583fc9c3af9fede600681ac<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35911">issues.joomla.org/tracker/joomla-cms/35911</a>.</sub>

**Comment by manav014** [comment]
I have tested this item :white_check_mark: successfully on cf80dbcca616bdad4583fc9c3af9fede600681ac<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35911">issues.joomla.org/tracker/joomla-cms/35911</a>.</sub>

**Comment by khu5h1** [comment]
Thanks, everyone :)

**Comment by brianteeman** [comment]
I have tested this item :red_circle: unsuccessfully on cf80dbcca616bdad4583fc9c3af9fede600681ac<br /><br />Sorry this is completely wrong.

Firstly the expected behaviour for a tree view is to navigate between the tree items with the arrow keys and not the tab key

Secondly while this pr does appear to navigate between tree items with a tab it does not allow you to select a tree item using the keyboard

Thirdly If you have a nested tree then the tab key will select the entire nested tree as a single item<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35911">issues.joomla.org/tracker/joomla-cms/35911</a>.</sub>

**Comment by richard67** [comment]
Back to pending after unsuccessful test.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35911">issues.joomla.org/tracker/joomla-cms/35911</a>.</sub>

**Comment by richard67** [comment]
> @richard67 I was not aware of the same. Thanks for your comment. I will keep this in mind for future PRs.

@khu5h1 Thank you. It was not a big problem, I only wanted to let you know that it was not necessary. And thanks for your contributions and testing other PR's. It's really appreciated, regardless of the unsuccessful test above (that can happen to anybody of us).

**Comment by khu5h1** [comment]
> Firstly the expected behaviour for a tree view is to navigate between the tree items with the arrow keys and not the tab key
>Secondly while this pr does appear to navigate between tree items with a tab it does not allow you to select a tree item using the keyboard
>Thirdly If you have a nested tree then the tab key will select the entire nested tree as a single item

@brianteeman Actually, I thought that the expected behavior is to navigate with tab key. I will modify this PR to make it compatible to move across items with arrow key. Also, I just realized that it is not allowing me to select nested tree items so that's also is to be done.

May anyone please suggest me some code pointers or references to solve the problem.

**Comment by khu5h1** [comment]
@richard67 Thanks for the appreciation. I totally understand that it is common for tests to be failed and I will modify my PR accordingly to pass the tests.

**Comment by brianteeman** [comment]
Maybe this information will help you https://www.levelaccess.com/creating-an-accessible-aria-tree-control/

**Comment by richard67** [comment]
Needs some more work.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35911">issues.joomla.org/tracker/joomla-cms/35911</a>.</sub>

**Comment by Quy** [comment]
Closing in favor of #37152. Thanks.

**Pull request closed without merging**
