### PR TITLE
[4.0] calendar buttons

### PR DESCRIPTION
**Pull request by brianteeman**
pr for #25896

After

image

### CODE REVIEW

**Comment by C-Lodder** [comment]
I have tested this item :white_check_mark: successfully on cbd05706f2a480660892375fa561a84057a3c545<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26142">issues.joomla.org/tracker/joomla-cms/26142</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on cbd05706f2a480660892375fa561a84057a3c545<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26142">issues.joomla.org/tracker/joomla-cms/26142</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26142">issues.joomla.org/tracker/joomla-cms/26142</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
