### PR TITLE
Fix the URL for technical requirements on joomla.org

### PR DESCRIPTION
**Pull request by MATsxm**
Fix the URL for technical requirements link on joomla.org
following:
https://github.com/joomla/joomla-websites/issues/333 and https://github.com/joomla/joomla-cms/pull/10446#issuecomment-219108807
#### Testing Instructions

Easy fix, on code review

### CODE REVIEW

**Comment by wojsmol** [comment]
I have tested this item :white_check_mark: successfully on 7d4d2ec4288e5908789d227604d42b3d223fb289<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10461">issues.joomla.org/joomla-cms/10461</a>.</sub>

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on 7d4d2ec4288e5908789d227604d42b3d223fb289<br /><br />Thanks <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10461">issues.joomla.org/joomla-cms/10461</a>.</sub>

**Comment by zero-24** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10461">issues.joomla.org/joomla-cms/10461</a>.</sub>

**Comment by brianteeman** [comment]
As this link has been around for a very long time it would be better to make sure the link works than to change it here

**Comment by MATsxm** [comment]
@brianteeman it is already redirected but this one is the one for Google

**Comment by brianteeman** [comment]
Really? This file should never exist on a live site so how is it anything
for google

On 14 May 2016 at 19:07, Marc-Antoine Thevenet <notifications@github.com>
wrote:

> @brianteeman <https://github.com/brianteeman> it is already redirected
> but this one is the one for Google
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/10461#issuecomment-219234632>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by MATsxm** [comment]
What I mean is that:
https://www.joomla.org/about-joomla/technical-requirements.html
does exist
https://www.joomla.org/technical-requirements.html is not indexed by google anymore (redirect to about one in august 2015)

**Comment by brianteeman** [comment]
So if the redirect exists great - google is irrelevant to this

On 14 May 2016 at 19:11, Marc-Antoine Thevenet <notifications@github.com>
wrote:

> What I mean is that:
> https://www.joomla.org/about-joomla/technical-requirements.html
> does exist
> https://www.joomla.org/technical-requirements.html is not indexed by
> google anymore (redirect to about one in august 2015)
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/10461#issuecomment-219234836>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by MATsxm** [comment]
didn't expected anything else from you

**Comment by Sandra97** [comment]
The URL https://www.joomla.org/technical-requirements.html does not exist anymore since August 23rd, 2015, not even for search engines. 
The correct URL is https://www.joomla.org/about-joomla/technical-requirements.html

**Pull request merged**
