### PR TITLE
Fix for #4314 Wrong URL when search sub-category by tag if SEF is on

### PR DESCRIPTION
**Pull request by oneumyvakin**
#### Steps to reproduce the issue
1. Enable SEF.
2. Create "category1" with ID 1 and alias "alias1"
3. For "category1" create child "category2" with ID 2 and alias "alias2"
4. Create "tag1" and assign it to "category2"
5. Try to search by "tag1"
#### Expected result

In search result there will be right URL to "category2" like:
/index.php/component/content/category/1-alias1/2-alias2
or
/index.php/component/content/category/2-alias2
or
/index.php/component/content/category/alias1/2-alias2
or
/index.php/component/content/category/2-alias1/2-alias2
#### Actual result

In search result category2 has a wrong URL which gives 404 error
/index.php/component/content/category/2-alias1/alias2
#### System information (as much as possible)

Joomla 3.3.3
PHP 5.4
#### Additional comments

only if SEF is On
only if search by tag

### CODE REVIEW

**Comment by MPompejus** [comment]
Added Patch and tried it the Problem still exist.
The ID for categorie 2 will set in the URL one step forward as id for categorie 1
http://127.0.0.1/bugtesting/index.php/component/content/category/79-alias1/alias2
number 79 is mine ID of categorie 2.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4448">issues.joomla.org/joomla-cms/4448</a>.</sub>

**Comment by kathastaden** [comment]
I tested it with Joomla version: 3.4.4-dev development
- SEF is enabled
- Patch was installed successful

1) Created category1 (ID is set by system - mine is 78) with alias1
2) Created category2 (ID is set by system - mine is 79) with alias2 and category1 as the parent
3) Created a tag named tag1
4) Assigned tag1 to category2 
5) Searched for tag1 and got this link as a result to category2
http://localhost/wpw2/bugtesting/index.php/component/content/category/79-alias1/alias2

6) Still Error 404 - So the test was not successful

**Comment by roland-d** [comment]
@oneumyvakin Can you follow up on the test results and make the needed changes to your pull request? Thank you.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/4448">issues.joomla.org/joomla-cms/4448</a>.</sub>

**Comment by oneumyvakin** [comment]
@roland-d to be clear, i've submitted this bug and patch two years ago for version 3.3.3, and it works for this version, and it was abandoned for the one year, and after the one year, on version 3.4.4, suddenly, fix became not working. This situation is not ok for me. So I've decide to do not contributing to Joomla any more.

**Comment by roland-d** [comment]
@oneumyvakin Thank you for your response. The behavior you described happens when the same files you changed are changed by someone else. I will close this PR now as we have a new router merged for Joomla 3.6.

**Pull request closed without merging**
