### PR TITLE
[5.2] mod_articles : missing onContentPrepare plugin event

### PR DESCRIPTION
**Pull request by conseilgouz**
### Summary of Changes

In mod_articles_news, there's a trigger event onContentPrepare (line 170 in ArticlesNewsHelper.php). 

It's missing in mod_modules.

This PR adds this missing event.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Kostelano** [comment]
If this should be controlled by this option, please add the information to the language line:

`MOD_ARTICLES_FIELD_TRIGGER_EVENTS_DESC="Enable this option to trigger three plugin events (afterDisplayTitle, beforeDisplayContent, afterDisplayContent) for each article in the results list."`

**Comment by conseilgouz** [comment]
mod_articles.ini file has been updated.
@Kostelano  : thank you for telling me about this.

**Comment by Fedik** [comment]
The event already trigered by https://github.com/joomla/joomla-cms/blob/15e03a3f9d57fff766ea00b36aae93c01a04e589/modules/mod_articles/src/Helper/ArticlesHelper.php#L363

**Comment by Fedik** [comment]
The problem, that the even will be triggered TWICE now.
This need a complex solution.

**Pull request closed without merging**
