### PR TITLE
[4.0] No results styling

### PR DESCRIPTION
**Pull request by brianteeman**
In j4 we use alert-warning and not alert-no-items

### Before
image

### After
image

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 97bbf1b6eb9457a1c370143cef3c20c5c8468782<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24680">issues.joomla.org/tracker/joomla-cms/24680</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 97bbf1b6eb9457a1c370143cef3c20c5c8468782<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24680">issues.joomla.org/tracker/joomla-cms/24680</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24680">issues.joomla.org/tracker/joomla-cms/24680</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
