### PR TITLE
[4.0] Correct com_config links in testing sample data

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Corrects com_config links in Sample Data - Testing plugin.

### Testing Instructions

Install Testing sample data.
Login to frontend as admin.
In `All Front End Views` module click `Site Settings` or `Template Settings`

### Expected result

Works.

### Actual result
Errors:
>Invalid controller class: config.display.config
>Invalid controller class: config.display.templates

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 099770240dfc95aba6c35d3603b6d829077ec913<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27617">issues.joomla.org/tracker/joomla-cms/27617</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 099770240dfc95aba6c35d3603b6d829077ec913<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27617">issues.joomla.org/tracker/joomla-cms/27617</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27617">issues.joomla.org/tracker/joomla-cms/27617</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
