### PR TITLE
[4.0] Constant unused in J4 / com_admin

### PR DESCRIPTION
**Pull request by Kostelano**
### Summary of Changes
Unused constant in J4 because there is no old search component.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 1b19e3398197ab9c1953b2e37121c99cc8a1357f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34578">issues.joomla.org/tracker/joomla-cms/34578</a>.</sub>

**Comment by rjharishabh** [comment]
I have tested this item :white_check_mark: successfully on 1b19e3398197ab9c1953b2e37121c99cc8a1357f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34578">issues.joomla.org/tracker/joomla-cms/34578</a>.</sub>

**Comment by richard67** [comment]
@wilsonge Do you remember if there was a reason to keep that language string e.g. for updates from 3.10?

**Comment by brianteeman** [comment]
The com_admin_help strings are used when building the helpTOC

as com_search is not in the helpTOC then the string is not used and can be deleted

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34578">issues.joomla.org/tracker/joomla-cms/34578</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
