### PR TITLE
Support issue/PR templates

### PR DESCRIPTION
**Pull request by mbabker**
Supports GitHub's new templates feature and `.github` hidden folder - https://github.com/blog/2111-issue-and-pull-request-templates

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
Cool feature.
Is there any instructions how we could test this? Or it will be merged by review?

**Comment by 810** [comment]
I have tested this item :white_check_mark: successfully on 941640c7a9328f7f50a57e4014dc79e72f1370ab<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9177">issues.joomla.org/joomla-cms/9177</a>.</sub>

**Comment by mbabker** [comment]
> Is there any instructions how we could test this? Or it will be merged by review?

Review the text.  GitHub will automagically turn it on when merged.

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 941640c7a9328f7f50a57e4014dc79e72f1370ab<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9177">issues.joomla.org/joomla-cms/9177</a>.</sub>

**Pull request merged**
