### PR TITLE
[4.0] Improving Quickcons display in CPanel

### PR DESCRIPTION
**Pull request by infograf768**
Pull Request for Issue #23103 .

### Summary of Changes
Improving Quickicons in CPanel by using a greenish background when no need to update and plain icons for the Overrrides, Extension Update(s) and Joomla Update (for that one backrgound only.

This adds a new color variable which can therefore be used for other parts of Admin if needed.
The green color chosen is the same which is used in the Messages background (alert.css).

### Testing Instructions
Patch.
Run npm ci for the css changes. Load Cpanel

### After patch
screen shot 2019-02-01 at 11 40 16

As we have an extension Update in the example above, its background color remains white, which is expected.

@acvmultimedia @C-Lodder @hardik-codes

### CODE REVIEW

**Comment by brianteeman** [comment]
Isn't this something that is so "design" specific that it should be left for the template team

**Comment by acvmultimedia** [comment]
@brianteeman The error may be mine, I am new to the community. I signed up for Joomladay Madrid in 2018. If you tell me how to help in the design team, I would love it.

**Comment by infograf768** [comment]
The suggestion was appreciated by quite a few people. See https://github.com/joomla/joomla-cms/issues/23103.

Whether it is in contradiction or not with a so-called admin template team is irrelevant here.
Please test and mark your test OK or not (if there is an error) on https://issues.joomla.org/tracker/joomla-cms/23733
@wilsonge will decide to merge or not.

**Comment by brianteeman** [comment]
> Whether it is in contradiction or not with a so-called admin template team is irrelevant here.

Not really if that team are designing something different etc as its just a waste of your and others time

**Comment by acvmultimedia** [comment]
Sorry for the inconvenience, I will take into account what you tell me. Thank you

**Comment by Bakual** [comment]
> Not really if that team are designing something different etc as its just a waste of your and others time

Doesn't matter at all.
If that team has a different idea for this specific issue (which I honestly doubt), they can always comment here and give their suggestions. Or create an own PR which can be tested.
We're not stopping development just because there may be another PR in the future. That would be quite stupid.

**Comment by wilsonge** [comment]
@coolcat-creations This makes sense to me but giving you an option to reject this if you feel it breaks the design.

**Comment by infograf768** [comment]
@coolcat-creations 
Please reply.

**Comment by coolcat-creations** [comment]
Sorry haven’t been getting notifications from github, no idea why. I was just directed to this issue. I worked long time on color calculations for the backend and it’s a really complicated job regarding a11y. So far I managed to have the main - blue color with its shades and next will be Buttons and alerts. So before testing and finishing this PR we need a stronger definition of the colors which will be available in the next days or few weeks. We need to take into account all the contrast issues etc. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23733">issues.joomla.org/tracker/joomla-cms/23733</a>.</sub>

**Comment by brianteeman** [comment]
@coolcat-creations this has been waiting for you for a few months now

**Comment by coolcat-creations** [comment]
Yes and we worked on it

**Comment by wilsonge** [comment]
Closing as this is going to be refactored in the new backend template repo which is planned on being merged into the main trunk next week. This will be contained there

**Pull request closed without merging**
