### PR TITLE
Fix PluginHelper::getLayoutPath to work in non Web context, like Cli, Api

### PR DESCRIPTION
**Pull request by Fedik**
Fix for stuff like https://github.com/joomla/joomla-cms/pull/38222 and https://github.com/joomla/joomla-cms/issues/38214 .

### Summary of Changes

Prevent crashing of plugin renderers in non Web context

### Testing Instructions

Have to apply all PR, this one, then #38585 then #38650
Then run test from #38650

### Actual result BEFORE applying this Pull Request
Error

### Expected result AFTER applying this Pull Request
Works

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Fedik** [comment]
I think `PluginHelper::getLayoutPath` we should deprecate to remove in 6.x, in favor of use `layout`

**Comment by richard67** [comment]
@Fedik Have you mixed up actual and expected result in the description? Or is it just me not understanding why expected result is error and actual result is it works?

**Comment by Fedik** [comment]
> Have you mixed up actual and expected result in the description? 

Yeap, that was me :smile:

**Comment by carlitorweb** [comment]
For next tester, to reproduce the error go to the terminal and type: `php cli/joomla.php finder:index`

As result you will get:
Captura

I not sure if through the administrator the mass indexer in the smart search component need throw an error, was not my case.

**Comment by carlitorweb** [comment]
I have tested this item :white_check_mark: successfully on a4a0338d5319984deee5caac2bf4d1d742cef740<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39550">issues.joomla.org/tracker/joomla-cms/39550</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39550">issues.joomla.org/tracker/joomla-cms/39550</a>.</sub>

**Comment by HLeithner** [comment]
This pull request has been automatically rebased to 4.3-dev.

**Comment by obuisard** [comment]
Thanks Fedir @Fedik for this PR :-)

**Pull request merged**
