### PR TITLE
Changing loading order between Redirect and Logout system plugins at install time

### PR DESCRIPTION
**Pull request by infograf768**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/19486

### Summary of Changes
Changing the order of these plugins in joomla.sql for the Redirect plugin to load first by default.

### Testing Instructions
Make a Joomla clean install including this PR.
Check the plugins Manager, filter by system plugins.
Now the Redirect plugin is displayed before the Logout plugin when filtering by Type Ascending or Ordering ascending.
Enable the Redirect plugin.
Test the issue described https://github.com/joomla/joomla-cms/pull/19233 i.e. logout via the Login Form Module while editing an article.

### Expected result
No 403, but a clean redirect to the Home page

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 93137d3f599cf4213fdbee6ac1beeef5154ea3db<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19489">issues.joomla.org/tracker/joomla-cms/19489</a>.</sub>

**Comment by anuragteapot** [comment]
I have tested this item :white_check_mark: successfully on 93137d3f599cf4213fdbee6ac1beeef5154ea3db<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19489">issues.joomla.org/tracker/joomla-cms/19489</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19489">issues.joomla.org/tracker/joomla-cms/19489</a>.</sub>

**Comment by zero-24** [comment]
Merged 👍

**Pull request merged**
