### PR TITLE
[5.1] Useless isset argument

### PR DESCRIPTION
**Pull request by Denitz**
### Summary of Changes

Remove useless isset argument.

### Testing Instructions

Apply patch.

### Actual result BEFORE applying this Pull Request

Useless isset argument.

### Expected result AFTER applying this Pull Request

No useless isset arguments.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by HLeithner** [comment]
This pull request has been automatically rebased to 5.1-dev.

**Review by rdeutz — APPROVED** [review]

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 54bfe19339646ae9baf036bdd081c180aa3c1464<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41968">issues.joomla.org/tracker/joomla-cms/41968</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 54bfe19339646ae9baf036bdd081c180aa3c1464<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41968">issues.joomla.org/tracker/joomla-cms/41968</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41968">issues.joomla.org/tracker/joomla-cms/41968</a>.</sub>

**Comment by LadySolveig** [comment]
Thank you @Denitz

**Pull request merged**
