### PR TITLE
[4.2] Fix indents in installation

### PR DESCRIPTION
**Pull request by Kostelano**
Pull Request for Issue # .

### Summary of Changes
PR corrects the balance of padding between fields/buttons. Some moments:

Screenshot_1

Screenshot_2

Screenshot_3

Screenshot_4

### Testing Instructions
Just install Joomla, make sure everything works as before.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 41edd000a28b03173cc78c57927b780d5a7c999b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38367">issues.joomla.org/tracker/joomla-cms/38367</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 41edd000a28b03173cc78c57927b780d5a7c999b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38367">issues.joomla.org/tracker/joomla-cms/38367</a>.</sub>

**Comment by chmst** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38367">issues.joomla.org/tracker/joomla-cms/38367</a>.</sub>

**Comment by fancyFranci** [comment]
Thank you for your work!

**Pull request merged**
