### PR TITLE
Small correction with links have not been escape &

### PR DESCRIPTION
**Pull request by zero-24**
redo of https://github.com/joomla/joomla-cms/pull/1978 against staging thanks @brunobatista
### how to test

Just test that the links still work as expected.

### CODE REVIEW

**Comment by wilsonge** [comment]
Please can you remove the code style affecting the isis error page. It's completely unrelated to the PR :)

**Comment by zero-24** [comment]
reverted @wilsonge

**Comment by wilsonge** [comment]
Merged on review

**Comment by zero-24** [comment]
:+1:

**Pull request merged**
