### PR TITLE
[5.x] Corrected headings ordering in contact

### PR DESCRIPTION
**Pull request by drmenzelit**
Pull Request for Issue # .
If "Show Page Heading" in a single contact is set to "Hide", you will get errors with the accessibility checker, because the headings are skipping a level.

### Summary of Changes
Added a new `htag2 `variable to replace the hard-coded `<h3>` elements.

### Testing Instructions
Create a contact and a menu item for it.
Activate the Accessibility Checker Plugin in the frontend and check the output with and without Page Heading.

### Actual result BEFORE applying this Pull Request
Without Page Heading
2023-07-10 15_58_10-Contact – Mozilla Firefox

### Expected result AFTER applying this Pull Request
With Page Heading
2023-07-10 15_58_38-Contact – Mozilla Firefox

Without Page Heading
2023-07-10 16_07_35-Contact – Mozilla Firefox

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 3ddca9ab6514c644747fedbffd8b9ff2396ab526<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41133">issues.joomla.org/tracker/joomla-cms/41133</a>.</sub>

**Comment by Quy** [comment]
`Links` should  be `H2`.

Before PR:
41133-before

After PR:
41133-after

Maybe rewrite the following:

`<<?php echo $htag2; ?>><?php echo Text::_('COM_CONTACT_DETAILS'); ?></<?php echo $htag2; ?>>`

to the following for easier code reading??:

`<?php echo '<' . $htag2 . '>' . Text::_('COM_CONTACT_DETAILS') . '</' . $htag2 . '>'; ?>`

**Comment by drmenzelit** [comment]
Good spotted @Quy, thank you!
I moved the title to the default.php to be consistent with the other titles

**Comment by Quy** [comment]
Under Contact Display Options, set `Name` to `Hide`.

41133-name

**Comment by drmenzelit** [comment]
Hmm... I will have to check the logic again ...

**Comment by drmenzelit** [comment]
I hope I got all combinations correctly:
Show page heading & Show name -> Page Heading = h1 | Name = h2 | Others = h3
Show page heading & Hide name -> Page Heading = h1 | Others = h2
Hide page heading & Show name -> Name = h1 | Others = h2
Hide page heading & Hide name -> Others = h2 and you get an error "missing h1", that is the same we have in a category blog

**Comment by Quy** [comment]
> Hide page heading & Hide name -> Others = h2 and you get an error "missing h1", that is the same we have in a category blog

Beyond the  scope of this PR? If yes, I will mark it successful.

**Comment by drmenzelit** [comment]
> Beyond the scope of this PR? If yes, I will mark it successful.
Yes, and I don't know, if there is a solution for that.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 26ff6f7ec2f7f4b5ed0091ca5b35c1cf7a245de3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41133">issues.joomla.org/tracker/joomla-cms/41133</a>.</sub>

**Comment by simbus82** [comment]
But if i have 3 Authors and i enable the Page Heading AFTER applying this Pull Request, now i have 3 pages with the same H1, and this is wrong.
For me Page Heading in this case is only a visual element, nothing to do with the semantic of page, in an author's page the H1 must be always the "The Author" (that is unique)

**Comment by drmenzelit** [comment]
You have the same behaviour without the PR, because the page heading comes from the menu. And you have the same behaviour on a blog layout. I'm not saying it is correct or not.

**Comment by rachelwalraven** [comment]
I have tested this item :white_check_mark: successfully on 26ff6f7ec2f7f4b5ed0091ca5b35c1cf7a245de3<br /><br />On Joomla 5.0 with PHP 8.1.22<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41133">issues.joomla.org/tracker/joomla-cms/41133</a>.</sub>

**Comment by HLeithner** [comment]
thanks

**Pull request merged**
