### PR TITLE
[com_fields] Allow zero as value in fields

### PR DESCRIPTION
**Pull request by Bakual**
Pull Request for allowing `0` as value in com_fields fields.

### Summary of Changes
Changing the value checks from a generic boolean check to one that triggers on an empty string (or null).

### Testing Instructions
1. Create a custom field. If it's a list type with at least one option containing a 0 as value. Eg 
yesno
2. Select the 0 value (eg "No") in the item and save.
3. Check the item in frontend. Before PR the field will not be shown, after the PR the field will show with proper option.

Further testing:
Check with different options (eg no value entered), enable the "multiple" feature, set a default value.
Check with other formfields like text and enter a 0.

### Documentation Changes Required
None

### CODE REVIEW

**Comment by mahagr** [comment]
Are values always strings? I guess so, because of if they are ever integers, `0 == ''`.

**Comment by ggppdk** [comment]
That will not work with if $value is an empty array()
also == '' is not good , you need strlen, e.g. integer value 0 is not an empty value

correct is:
```php
if (  (!is_array($value) && !strlen($value)) || (is_array($value) && !$value)  )
```

**Comment by ggppdk** [comment]
Also the fix needs to go to all layouts, not only to the radio / checkboxes / list fields

**Comment by Bakual** [comment]
> Are values always strings? 

I think so, yes. I wasn't able to get a different type.

> That will not work with if $value is an empty array()

I wasn't able to get an empty array there. Do you know a way to get that?

>  integer value 0 is not an empty value

As said above, the value always was a string when I debugged. So no integers and no arrays.
I prefer that simple code vs your code solution because it is much more readable. As long as it does the job of course.
If the value may be an empty array, I'd rather cast it to array before the check and simplify the code again (it's cast to array afterwards anyway).

**Comment by Bakual** [comment]
> Also the fix needs to go to all layouts, not only to the radio / checkboxes / list fields,
i mean that i suggest to change titile of this PR and apply fix to all fields ?

Hmm, you're right. Text is also affected and probably others as well.

**Comment by Bakual** [comment]
Added the other formfields as well and found some other places were it also needed to be changed so the text formfield works with 0 as value.

**Comment by laoneo** [comment]
In #12886 if checked additionally if the value is null like `$field->value === '' || $field->value === null` as `$field->value == ''` doesn't let '0' pass.

**Comment by Bakual** [comment]
> as $field->value == '' doesn't let '0' pass.

It worked fine for me. Because '0' is a string an not an integer (not 0) the comparision work perfect. The value also never was a null for me, it was always empty if not set. I don't think JForm will ever return a null or an integer there, it's always a string (or an array of strings).
Were you able to break that code or is that just based on reviewing it?

**Comment by laoneo** [comment]
Just by review, to be on the safe side as JForm was not involved, only database query stuff.

**Comment by Bakual** [comment]
> as JForm was not involved,

Ah, I was assuming it is coming from there but I didn't track it down.
Since we store the values in the database as text, I wouldn't expect it magically become an integer or null anyway. As long as there is no case where it could become `null`, I don't see why we should add check for `null`. But maybe I missed a case? I just did some tests and debugged it :smile:

**Comment by laoneo** [comment]
I like to be on the safe side :wink:

**Comment by Bakual** [comment]
I prefer simpler code :smile: 

But in the end I don't care that much as long as it works.

**Comment by laoneo** [comment]
I have tested this item :white_check_mark: successfully on e162c06cbc6e42ef0af9e27f707385874bb8e702<br /><br />Tested with lists and texts<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12807">issues.joomla.org/tracker/joomla-cms/12807</a>.</sub>

**Comment by ggppdk** [comment]
I have tested this item :red_circle: unsuccessfully on e162c06cbc6e42ef0af9e27f707385874bb8e702<br /><br />It only works with radio and list, 
-- it does not work with checkboxes

More specifically:
-- it does not work when you only select the zero-value checkbox element (and do not select other checkbox elements)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12807">issues.joomla.org/tracker/joomla-cms/12807</a>.</sub>

**Comment by Bakual** [comment]
That's actually a different issue. See PR https://github.com/joomla/joomla-cms/pull/12886 from Allon for that.

**Comment by Bakual** [comment]
Ah and can you mark a successfull test here please? 😄

**Comment by ggppdk** [comment]
I have tested this item :white_check_mark: successfully on e162c06cbc6e42ef0af9e27f707385874bb8e702<br /><br />yes, since the case described in my last post, is being fixed in a different PR,
arguably it could have been in this one<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12807">issues.joomla.org/tracker/joomla-cms/12807</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12807">issues.joomla.org/tracker/joomla-cms/12807</a>.</sub>

**Pull request merged**
