### PR TITLE
[5.2] Typo Update UrlRule.php

### PR DESCRIPTION
**Pull request by brianteeman**
Simple pr to fix a comment typo. Spotted while reviewing code for a new feature.

Code review

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 44bc05366c0f161791bc9f7d813d1027f4822054<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44227">issues.joomla.org/tracker/joomla-cms/44227</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 44bc05366c0f161791bc9f7d813d1027f4822054<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44227">issues.joomla.org/tracker/joomla-cms/44227</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44227">issues.joomla.org/tracker/joomla-cms/44227</a>.</sub>

**Comment by rdeutz** [comment]
@brianteeman I merged this one by mistake and had to revert the commit, sorry! Can you make the PR again and assign it to me I will take it from there.

**Pull request merged**
