### PR TITLE
[4.0] Fix obsolete class and badge background color

### PR DESCRIPTION
**Pull request by Quy**
Pull Request for Issue #34852 .

### Summary of Changes
Replace obsolete class and change badge background color for readability.

### Testing Instructions
Install plugin; https://github.com/GHSVS-de/plg_system_changelogtest/archive/refs/tags/0.0.1.zip
Go to System > Update > Extensions
See Changelog button smaller size.
See below screenshots.

### Actual result BEFORE applying this Pull Request
34852-before

### Expected result AFTER applying this Pull Request
34852-after

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on de27587f98b15057de811854a7409a0d1948b023<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34858">issues.joomla.org/tracker/joomla-cms/34858</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on de27587f98b15057de811854a7409a0d1948b023<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34858">issues.joomla.org/tracker/joomla-cms/34858</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34858">issues.joomla.org/tracker/joomla-cms/34858</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on de27587f98b15057de811854a7409a0d1948b023<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34858">issues.joomla.org/tracker/joomla-cms/34858</a>.</sub>

oups, I was too late

**Comment by alikon** [comment]
always good to have more than 2 test

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
