### PR TITLE
[4.0] Normalizing authentication joomla plugin strings

### PR DESCRIPTION
**Pull request by infograf768**
### Summary of Changes
Following up on https://github.com/joomla/joomla-cms/pull/29666

 As title says

### CODE REVIEW

**Comment by brianteeman** [comment]
I have not tested this item.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29668">issues.joomla.org/tracker/joomla-cms/29668</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on a09942a260601326d691ae1ad1d97e0b6c245d46<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29668">issues.joomla.org/tracker/joomla-cms/29668</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on a09942a260601326d691ae1ad1d97e0b6c245d46<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29668">issues.joomla.org/tracker/joomla-cms/29668</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29668">issues.joomla.org/tracker/joomla-cms/29668</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
