### PR TITLE
[5.1] Replace deprecated substr() with substring()

### PR DESCRIPTION
**Pull request by C-Lodder**
### Summary of Changes

Javascript's `substr()` method has been deprecated for ages now (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/substr) and this PR replaces it with `substring()`

### Testing Instructions

1. Inline Help should still work as expected.
2. Add a simple colour field to any XML file (`<field name="foo" type="color" label="Test" control="simple" />`) and ensure the field works as expected.
3. Ensure toggling the TineMCE presets within the Plugin Manager still works as expected.

I was unable to test the calendar changes as the code has no comments to assist developers, so this might need to be a code review instead.

### CODE REVIEW

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on a68b18a9d7e4d019d33922a4fd0a1a50d25fbee6<br /><br />All checked - calendar field in Article edit worked normally.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42726">issues.joomla.org/tracker/joomla-cms/42726</a>.</sub>

**Comment by steffans** [comment]
I have tested this item :white_check_mark: successfully on a68b18a9d7e4d019d33922a4fd0a1a50d25fbee6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42726">issues.joomla.org/tracker/joomla-cms/42726</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on a68b18a9d7e4d019d33922a4fd0a1a50d25fbee6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42726">issues.joomla.org/tracker/joomla-cms/42726</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42726">issues.joomla.org/tracker/joomla-cms/42726</a>.</sub>

**Comment by exlemor** [comment]
I have not tested this item.<br /><br />Not testable...

Using Download / Details at the bottom of the Patch page,
https://artifacts.joomla.org/drone/joomla/joomla-cms/5.1-dev/42726/downloads/73221 you receive an error message:

Not Found

The requested URL was not found on this server.

Additionally, a 404 Not Found error was encountered while trying to use an ErrorDocument to handle the request.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42726">issues.joomla.org/tracker/joomla-cms/42726</a>.</sub>

**Comment by richard67** [comment]
@exlemor Possibly the downloads are not available anymore because some time after a PR has been updated last time, the downloads are deleted. As the PR already has 2 good tests I have set it to RTC (ready to commit), so it doesn't need any more tests. But I will trigger a new build of the testing packages now by updating the branch so a bit later new downloads will be available.

**Comment by LadySolveig** [comment]
Thank you @C-Lodder and also to the testers @ceford @steffans and @viocassel

**Pull request merged**
