### PR TITLE
Add Hound to staging to prevent any code linting

### PR DESCRIPTION
**Pull request by C-Lodder**
As requested by @mbabker here: https://github.com/joomla/joomla-cms/pull/16947#issuecomment-312655011

### CODE REVIEW

**Comment by wilsonge** [comment]
On a serious note do we want to enable js stuff? I get that our current js isn't compliant but I don't see a reason to disable it either. This also needs to be removed from Joomla builds (I.e. Add it to the array of excluded files in build/build.php)

**Comment by C-Lodder** [comment]
I'm not bothered if it's enabled or disabled on staging. Release manager can decide.

Had to do the `build.php` as a separate PR: https://github.com/joomla/joomla-cms/pull/16957

**Comment by dgt41** [comment]
> On a serious note do we want to enable js stuff?

Sure! BUT we need to review all files (in a sprint or something) otherwise whenever anyone creates a new PR will be facing a lot of failures for strict comparisons etc., which will cause a lot of confusion. I guess this is a task for the JS group: @Fedik @dneukirchen @yvesh

**Comment by C-Lodder** [comment]
If you want to enable JS linting, then this PR doesn't need to be merged.

**Comment by photodude** [comment]
I would say merge with the expectation that a sprint will take care of the current failures in the JS code then enable JS linting on staging as @dgt41 suggested.

**Comment by C-Lodder** [comment]
@photodude - That's double the work. We've rewritten most of the JS in 4.0. Is it really worth wasting resources linting on both branches?

**Comment by mbabker** [comment]
> That's double the work. We've rewritten most of the JS in 4.0. Is it really worth wasting resources linting on both branches?

IMO no

**Pull request merged**
