### PR TITLE
[4] Add system information quickicon to Home Dashboard

### PR DESCRIPTION
**Pull request by PhilETaylor**
Pull Request for Issue # .

### Summary of Changes

Fill the wasted space in the System module on Home Dashboard, by default, with 4 boxes and not just 3 by introducing the System Information quick icon (after all, this is the SYSTEM module of quick icons!) 

### Testing Instructions

See Home Dashboard - toggle the new icon on/off

### Actual result BEFORE applying this Pull Request

A Missed opportunity of space

Screenshot 2021-05-14 at 21 46 02

### Expected result AFTER applying this Pull Request

By default, on new installation, there are now 4 icons in the System box on Home Dashboard. 

Screenshot 2021-05-14 at 21 44 28

There is a new option that can be toggled on the edit screen:

Screenshot 2021-05-14 at 21 42 17

### CODE REVIEW

**Comment by PhilETaylor** [comment]
Note the "Items with count" configuration is NOT part of this PR, and is my bad with screenshot taking... this PR only concerns the System Information icon and not the numbers on the others.

**Comment by richard67** [comment]
@PhilETaylor You should change also the params for the quickicon in the `4.0.0-2019-07-13.sql` script so they are created in the right way when updating from 3.10-dev:

https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_admin/sql/updates/mysql/4.0.0-2019-07-13.sql#L70

https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_admin/sql/updates/postgresql/4.0.0-2019-07-13.sql#L69

The params there should be exactly the same as in the base.sql for the same module.

But as I can see the params are outdated there also for other quickicons, e.g. "header_icon" values differ to a new installation.

So maybe I have to make a separate PR for that if you don't want to clean that up here.

**Comment by PhilETaylor** [comment]
Ive turned a complete blind eye to `3.10` on purpose in my life :) If you are going to be cleaning those up anyway, and if this gets merged then please add this for me :)

**Comment by richard67** [comment]
The next question is if something to be done for updating 4.0 Beta 7 or earlier. But that's always a hairy thing, updating json parameters, so I have to think about that.

**Comment by PhilETaylor** [comment]
if you update, we dont need to turn this "on" by default...the option is there for them to turn it on if they want...

**Comment by richard67** [comment]
I wanted to put at least some awareness on these update aspects because people are messing around much recently with params here and there and don't care about the update script, so what I find when digging deeper is a mess.

**Comment by PhilETaylor** [comment]
Got it. I'll try harder in future to make your job easier :)

**Comment by brianteeman** [comment]
> A Missed opportunity of space

Massively depends on your screen size.

On my screen this PR just created extra space

**Comment by richard67** [comment]
We want to have a 4.0 RC soon and things like this PR may look easy at a first look .. but only if you don't care about updating and leave all database stuff alone.

Do we really need this so soon before we want to go RC?

I currently think all that stuff should be labelled as new feature and shifted to 4.1.

We should focus on bugs now.

But that's just my personal opinion.

**Comment by PhilETaylor** [comment]
I think the actual maths will show that I have reported and worked on many bugs as well as things like this. You cannot be in the zone, deep in layers and layers of code and bugs hunting and fixing all of the time. Sometimes you just need to work on something light, enjoyable￼￼, while sitting in a car outside your daughters extra curricular activities with a laptop balanced on your knees watching the Sun go down￼...

It's not up to me if things are merged, or to which branch they are merged into.￼

**Comment by brianteeman** [comment]
Much more interested in your mail template thing

**Comment by PhilETaylor** [comment]
> Much more interested in your mail template thing

Which no one else was interested in.

**Comment by PhilETaylor** [comment]
ok so lets revert all the "by default show it" and just have it as an optional opt in feature like all the other icons in the list - that way its easy for everyone.

**Comment by richard67** [comment]
> I think the actual maths will show that I have reported and worked on many bugs as well as things like this.

@PhilETaylor That's right, and that's much appreciated, and I haven't said anything else.

**Comment by brianteeman** [comment]
There is another PR that adds a lot more optional quickicons but I think it was merged into 4.1 as the maintainers deemed it a new feature

**Comment by richard67** [comment]
The one which was merged into 4.1-dev was a small one, #32223 . The bigger one for 4.1-dev is still open: #32671 .

**Comment by PhilETaylor** [comment]
Ill take a look when im home

 #32671  looks like it will never be merged - its 129 files and some (skiptp.php) are totally unrelated to the pr

**Comment by PhilETaylor** [comment]
and #32223 has others (@infograf768) disagreeing over whether it should have been in 4.0 and not 4.1 ;-) so its not always clear cut

**Comment by PhilETaylor** [comment]
> We want to have a 4.0 RC soon

Is there actually a decision and a date or is this pie in the sky still?

**Comment by richard67** [comment]
> Is there actually a decision and a date or is this pie in the sky still?

I'd say it's something in between those 2 :-)

**Comment by PhilETaylor** [comment]
And no one seems to see that for the real problem it is :-( /facepalm.

**Comment by richard67** [comment]
@PhilETaylor It's only me being a normal maintainer and not official speaker so I don't want to make official statements. All I can say is we are close to it.

**Comment by PhilETaylor** [comment]
Heard it all before :) ...

**Pull request closed without merging**
