### PR TITLE
Improved count method of registry nodes

### PR DESCRIPTION
**Pull request by ghost**
.

### CODE REVIEW

**Comment by nonumber** [comment]
I don't see the ```count``` method in the framework, so not sure if it is even used & supposed to be here.

**Comment by wilsonge** [comment]
https://github.com/joomla-framework/registry/blob/master/src/Registry.php#L99

**Comment by mbabker** [comment]
It's in the repo George linked you too.  Method is needed to implement the Countable interface (a new feature in Registry for this CMS release).

**Comment by nonumber** [comment]
Moved: https://github.com/joomla-framework/registry/pull/24

**Pull request closed without merging**
