### PR TITLE
[4.2] ExtensionManagerTrait.php. Comments cosmetic.

### PR DESCRIPTION
**Pull request by GHSVS-de**
### Summary of Changes
Only in some comment lines:
- Removed double "to".
- Changed "module" to "plugin" in `bootPlugin()`

### Testing Instructions
Code review.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 826988abfe91a1bf06769a8b13ff94ea73a57a9c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38275">issues.joomla.org/tracker/joomla-cms/38275</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 826988abfe91a1bf06769a8b13ff94ea73a57a9c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38275">issues.joomla.org/tracker/joomla-cms/38275</a>.</sub>

**Comment by alikon** [comment]
rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38275">issues.joomla.org/tracker/joomla-cms/38275</a>.</sub>

**Comment by Quy** [comment]
Thank you.

**Pull request merged**
