### PR TITLE
[4.0] xml codestyle

### PR DESCRIPTION
**Pull request by brianteeman**
Spotted a few issues while working on another PR

code review should be enough

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 70c869c97323e4b6d6535bf7b32709b7d6d81e34<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33043">issues.joomla.org/tracker/joomla-cms/33043</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 70c869c97323e4b6d6535bf7b32709b7d6d81e34<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33043">issues.joomla.org/tracker/joomla-cms/33043</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33043">issues.joomla.org/tracker/joomla-cms/33043</a>.</sub>

**Comment by Quy** [comment]
Thanks

**Comment by brianteeman** [comment]
Thanks - if we all fix these little things when we find them ...

**Pull request merged**
