### PR TITLE
[5.1] Fix tooltips in categories

### PR DESCRIPTION
**Pull request by chmst**
Pull Request for Issue Comment (https://github.com/joomla/joomla-cms/pull/38787#issuecomment-1975094577) .

### Summary of Changes
Change language string to generic "items"

### Testing Instructions
Have a look on tooltips in contact categories 

### Actual result BEFORE applying this Pull Request
see https://github.com/joomla/joomla-cms/pull/38787#issuecomment-1975094577

### Expected result AFTER applying this Pull Request
Tooltip says "published items" and so on

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by ChristineWk** [comment]
With Patch, I see this:

pr

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 8102b8f079b39d406a77448ad1e8a06ae471b4ef<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42944">issues.joomla.org/tracker/joomla-cms/42944</a>.</sub>

**Comment by ChristineWk** [comment]
pr2

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 8102b8f079b39d406a77448ad1e8a06ae471b4ef<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42944">issues.joomla.org/tracker/joomla-cms/42944</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42944">issues.joomla.org/tracker/joomla-cms/42944</a>.</sub>

**Comment by heelc29** [comment]
@chmst Trashed is missing
image

https://github.com/joomla/joomla-cms/blob/8102b8f079b39d406a77448ad1e8a06ae471b4ef/administrator/components/com_categories/tmpl/categories/default.php#L241

**Comment by richard67** [comment]
Back to pending due to previous comment.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42944">issues.joomla.org/tracker/joomla-cms/42944</a>.</sub>

**Comment by richard67** [comment]
@heelc29 Could you check again and maybe give it a test? And @viocassel or @ChristineWk Could one of you also test again? Thanks in advance.

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 9b6c42d4dbd3bb8f3307ac84da3f7584a9c22027<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42944">issues.joomla.org/tracker/joomla-cms/42944</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 9b6c42d4dbd3bb8f3307ac84da3f7584a9c22027<br /><br />👍<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42944">issues.joomla.org/tracker/joomla-cms/42944</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42944">issues.joomla.org/tracker/joomla-cms/42944</a>.</sub>

**Comment by bembelimen** [comment]
Thank you!

**Pull request merged**
