### PR TITLE
Fix for issue #11163

### PR DESCRIPTION
**Pull request by csthomas**
Pull Request for Issue #11163

### Summary of Changes

This PR is for multilingual joomla installation with plugin language filter enabled.
Take  a look at the issue.

### Testing Instructions
 #11163

### Expected result
Links to tag works and are generated in the same way (I mean the same result) from various places:
- article view
- module tag popular
- module menu 
- feed tag view

### Actual result
- Tag link generated in Menu module may be different to the same tag generated from article view.

### Documentation Changes Required
No

### CODE REVIEW

**Comment by infograf768** [comment]
can't test right now, but have you taken into account the fact that, to be ok for multilingual, tags general options should set the filter language to the right param?

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 65bee28ed79c898a73ea4958bde6bc0337d3e763<br /><br />With and -out PR click on Tag in Article-View works as expected, didn't get Issue described in #11163 "If you click on a tag below an article you are forwarded to: component/tags/tag/tagname"<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15539">issues.joomla.org/tracker/joomla-cms/15539</a>.</sub>

**Comment by brianteeman** [comment]
@franz-wohlkoenig if you cannot replicate the issue you cannot successfully test that the change has fixed anything

**Comment by csthomas** [comment]
@infograf768 I have found option language filter in menu item form options (All, current, en-GB, ...) but this option is not used to generate URL.
I only enabled plugin "System - Language Filter".

**Comment by csthomas** [comment]
This PR is closed. A little related PRs are #18407 and #15479

**Pull request closed without merging**
