### PR TITLE
[4.0] [Banners] One button for similar actions

### PR DESCRIPTION
**Pull request by Kostelano**
Pull Request for Issue # .

### Summary of Changes
PR improves the display of reset buttons in the Banners component (see screenshot) + adds a constant that can be used in the future for similar actions.

**BEFORE / AFTER**

Screenshot_1

### Testing Instructions
Go to the banners component and create a new banner. On the second tab, pay attention to the reset buttons.

### Documentation Changes Required
Not

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on d8d42eed524d38dbb174418a338a1cbb1cee1a26<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33878">issues.joomla.org/tracker/joomla-cms/33878</a>.</sub>

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on d8d42eed524d38dbb174418a338a1cbb1cee1a26<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33878">issues.joomla.org/tracker/joomla-cms/33878</a>.</sub>

**Comment by richard67** [comment]
@brianteeman Do I assume right that the change made by this PR here is ok regarding a11y because the buttons have `aria-hidden="true"` so a screen reader won't read them anyway?

**Comment by Quy** [comment]
`aria-hidden="true"` applies to the icon and not the button.

**Comment by richard67** [comment]
Oh, then maybe someone really should check with a screen reader.

**Comment by brianteeman** [comment]
Changing to just say reset is no different to similar fields where we have create/edit

**Comment by brianteeman** [comment]
But you don't need to keep asking me for accessibility issues you can ask the accessibility team

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33878">issues.joomla.org/tracker/joomla-cms/33878</a>.</sub>

**Comment by Quy** [comment]
Thank you!

**Pull request merged**
