### PR TITLE
Use the fixed menu item for open search url

### PR DESCRIPTION
**Pull request by wilsonge**
Pull Request for Issue #14163 .

### Summary of Changes
Uses the menu item id when calculating the open search url. i have no clue if this is a good fix or not :D 

For testing instructions see original issue

### CODE REVIEW

**Comment by AndySDH** [comment]
Tested this, but doesn't work as it is:

JRoute::_('&option=com_search&format=opensearch&**itemId**=' . $mitemid), 'search', 'rel',

needs to be changed to:

JRoute::_('&option=com_search&format=opensearch&**Itemid**=' . $mitemid), 'search', 'rel',

**Comment by wilsonge** [comment]
I think I already fixed that 10 minutes ago :P

**Comment by AndySDH** [comment]
Oh nice! Great, it works with that fix :)

**Comment by ghost** [comment]
@AndySDH please mark your Test as successfully:

- open [Issue Tracker](https://issues.joomla.org/tracker/joomla-cms/21713)
- Login with your github-Account
- Click on blue "Test this"-Button above Authors-Picture
- mark your Test as successfully
- hit "submit test result"

**Comment by AndySDH** [comment]
I have tested this item :white_check_mark: successfully on d0ef52bb1bc83e7d3ba3b72b375dde2941caad4f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21713">issues.joomla.org/tracker/joomla-cms/21713</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on d0ef52bb1bc83e7d3ba3b72b375dde2941caad4f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21713">issues.joomla.org/tracker/joomla-cms/21713</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Pull request merged**
