### PR TITLE
[4.0] Fix schema updates for com_finder with PostgreSQL database

### PR DESCRIPTION
**Pull request by richard67**
Pull Request for Issue #24769 .

### Summary of Changes

Fix the schema update changes from PR #20561 for PostgreSQL so they are consistent with a new installation.

### Testing Instructions

1. Pull current (May 1, 2019) 4.0-dev branch and do `composer install` and `npm ci`, or use nightly build from tonight. Both include PR #24747, which is needed to install on PostgreSQL. Alpha 8 does not include that yet, so please don't use Alpha 8.
2. Run installation using a PostgreSQL database.
3. After installation has finished with success, login to backend, confirm the statistics dialog, then goto the system panel and check section "Information - Database". Result: You see that there is 1 database problem.
4. Click "Database" to get to the Database view. Result: See section "Actual result" below.
5. Apply changes from this PR.
6. Leave database view and go back to it again. Result: See section "Expected result" below.

### Expected result

No database problems.

### Actual result

screen shot 2019-05-01 at 09 59 15

### Documentation Changes Required

None.

### CODE REVIEW

**Comment by richard67** [comment]
@alikon Could you test?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24771">issues.joomla.org/tracker/joomla-cms/24771</a>.</sub>

**Comment by richard67** [comment]
Drone failure is not related to this PR. Phpcs was successful. It was the prepare step which failed.

**Comment by richard67** [comment]
@twister65 I noticed you test with PostgreSQL, too. If you have time, could you test my PR here? Thanks in advance if so.

**Comment by richard67** [comment]
Drone failure again is not related to this PR. Phpcs was successful. This time it was analysis4x which failed.

**Comment by twister65** [comment]
I have tested this item :white_check_mark: successfully on 74bc831c8d16132908bbc3e0427ad2aea0b764c1<br /><br />Tested with Joomla_4.0.0-alpha9-dev nightly build.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24771">issues.joomla.org/tracker/joomla-cms/24771</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 9b469559f072196a16220f9847c1c3d6aaf43f4a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24771">issues.joomla.org/tracker/joomla-cms/24771</a>.</sub>

**Comment by alikon** [comment]
RTC <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24771">issues.joomla.org/tracker/joomla-cms/24771</a>.</sub>

**Comment by wilsonge** [comment]
@zero-24 @snipersister rips please

**Comment by richard67** [comment]
@wilsonge What means "rips"? Rest in pieces? ;-)

**Comment by wilsonge** [comment]
It’s the tool we use for the security analysis part of drone (which was failing). It’s now passing so I can merge this! Thanks!

**Comment by richard67** [comment]
Thanks!

**Pull request merged**
