### PR TITLE
backdrop deleted

### PR DESCRIPTION
**Pull request by puneeth-chanda**
Pull Request for Issue #23636 

### Summary of Changes
The backdrop which is getting overlapped is deleted so that it has a workable UI.

### CODE REVIEW

**Comment by brianteeman** [comment]
As @C-Lodder says we need the backdrop

**Comment by dgrammatiko** [comment]
@puneeth2001 I'm afraid this is not an acceptable solution

**Comment by ciar4n** [comment]
@dgrammatiko Is it possible to echo the modal before the closing body tag? I believe this is the only real solution here.

**Comment by dgrammatiko** [comment]
@dgrammatiko but I did that already: https://github.com/joomla/joomla-cms/pull/21852
and the dinos said no. Go figure...

**Comment by ciar4n** [comment]
@wilsonge @HLeithner

**Comment by ciar4n** [comment]
Common sense failing, there is only 2 other possible options that I see. Neither of which are ideal.

1.  Echo the backdrop with the modal and set `z-index: -1;` on the backdrop.
2.  Have the body tag the only relative element on the tree to the modal (remove `position:sticky` on the `.subhead`)

**Comment by dgrammatiko** [comment]
@ciar4n as far as I remember the goal was to move all the server side rendered modals before the closing body tag. Also, this was a decision because we want to move to `<dialog>` which at some part will require 0 js on all browsers. People against this were talking about losing the ability to style those and that's totally stupid because you can pass any unique class to each modal, thus that reason was completely boll**ks...
People are trying hard to resist any needed changes...

**Comment by ciar4n** [comment]
Your pr really needs to be reconsidered.

**Comment by brianteeman** [comment]
yes please to just dropping modals and moving to dialog - semantically they are more correct and they are much more accessible

**Comment by ReLater** [comment]
> As @C-Lodder says we need the backdrop

And why do we need backdrops? Any comprehensible reasons?

**Comment by C-Lodder** [comment]
@ReLater check my comment on the issue.

It's UX related.

**Comment by C-Lodder** [comment]
Im all for dialogs. Shame more browsers dont support them yet but polyfills can be used.

If we keep the modals for now, then the markup needs to be injected before the closing body tag. All these z-index fixes will eventually cause problems in the future

**Comment by bembelimen** [comment]
> @dgrammatiko but I did that already: #21852
> and the dinos said no. Go figure...

Not sure, were you saw someone against it...If you mean my comment, I just wrote something which should be considered, nothing more.
This PR is definitely not the solution, yours would have been, if you wouldn't be offended by nothing and would have improved instead of closing it.

**Comment by brianteeman** [comment]
This works great and works for all supported browsers http://edenspiekermann.github.io/a11y-dialog/example/

**Comment by bembelimen** [comment]
> This works great and works for all supported browsers http://edenspiekermann.github.io/a11y-dialog/example/

Look good, but the backdrop problem will be there, too? So we need two changes: implement the new script + fix the backdrop.

**Comment by ciar4n** [comment]
> This works great and works for all supported browsers http://edenspiekermann.github.io/a11y-dialog/example/

This example injects the backdrop with the modal which should resolve the backdrop issue.

**Comment by brianteeman** [comment]
@ciar4n exactly right - and its much more accessible etc etc

**Comment by Quy** [comment]
Closing for reasons stated. Maybe PR #24369 is a possible solution.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23906">issues.joomla.org/tracker/joomla-cms/23906</a>.</sub>

**Comment by infograf768** [comment]
Please look at https://github.com/joomla/joomla-cms/pull/25147

**Pull request closed without merging**
