### PR TITLE
[4.0] Bring the Tests Back Home

### PR DESCRIPTION
**Pull request by dgrammatiko**
This PR just bings back the javascript tests

Pull Request for Issue # .

### Summary of Changes
- Tests are back in the main repo
- `npm test` runs the tests locally

### Testing Instructions
- `npm test` still performs the js tests { run `npm install` before!!!, deps have changed!!}
screenshot 2019-02-28 at 11 14 11

### Documentation Changes Required

This needs some adjustments in the drone files. Pinging @rdeutz here as we already discussed the idea of utilising Sauce Labs https://github.com/joomla/test-javascript/pull/11

@dneukirchen

### CODE REVIEW

**Comment by wilsonge** [comment]
You can't delete the package lock. sorry!

**Comment by Hackwar** [comment]
Please bring back an updated package.lock file. Otherwise this looks good. Please also see @dneukirchen s PR for the unittests and how he described the tests in the Readme.md.

**Comment by dgrammatiko** [comment]
> You can't delete the package lock. sorry!

I wasn't deleting that file, it just removed a lot of lines due to the fact that we removed on dependency...
The .lock is still there

**Review by wilsonge — APPROVED** [review]

**Comment by wilsonge** [comment]
LGTM will wait for a testing team member to actually do the merge

**Comment by ghazal** [comment]
I have tested this item :white_check_mark: successfully on d4095f81e88a0c9ab5f7a2bf420fb9f646831826<br /><br />Finally, node works ie Terminal found karma.conf.js.
Tks.
Docs should be updated too.
Like this one : https://docs.joomla.org/JavaScript_Tests_for_Joomla4
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24044">issues.joomla.org/tracker/joomla-cms/24044</a>.</sub>

**Comment by dneukirchen** [comment]
I have tested this item :white_check_mark: successfully on https://github.com/joomla/joomla-cms/pull/24044/commits/d4095f81e88a0c9ab5f7a2bf420fb9f646831826

bildschirmfoto 2019-03-06 um 15 41 59

**Comment by dneukirchen** [comment]
I have tested this item :white_check_mark: successfully on d4095f81e88a0c9ab5f7a2bf420fb9f646831826<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24044">issues.joomla.org/tracker/joomla-cms/24044</a>.</sub>

**Comment by ghost** [comment]
Status "Ready To Commit".

**Pull request merged**
