### PR TITLE
[4.0] Send Email

### PR DESCRIPTION
**Pull request by brianteeman**
It is a button so it should be consistent with all other buttons and be capitalised

### Before
image

### After
image

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 214121ad716ae7020bfe5662b3890297b7bd7ba7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22486">issues.joomla.org/tracker/joomla-cms/22486</a>.</sub>

**Comment by bembelimen** [comment]
I have tested this item :white_check_mark: successfully on 214121ad716ae7020bfe5662b3890297b7bd7ba7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22486">issues.joomla.org/tracker/joomla-cms/22486</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22486">issues.joomla.org/tracker/joomla-cms/22486</a>.</sub>

**Comment by laoneo** [comment]
Thanks

**Pull request merged**
