### PR TITLE
com_users User Notes - Moved sidebar Filters to STools

### PR DESCRIPTION
**Pull request by pe7er**
This PR moves Filters from left sidebar to Search Tools.
# Testing instructions
## Before this PR

Users > **User Notes**
1. Left sidebar has 2 filter options (Select: Status, Category) that cannot be reset easily to original state with one button.
2. On the top right there are two duplicate ordering fields: "Sort Table By" & "Select the ordering" (for the direction of the ordering).

usernotes-before
## After this PR

Users > **User Notes**
1. the Filters from sidebar should be moved to the middle under "Search Tools" option. All filters can be reset with the "Clear" button.
2. the "Sort Table By" & "Select the ordering" have been removed. The ordering field + ordering direction can be set by clicking on a column header (fieldname).

usernotes-after

### CODE REVIEW

**Comment by watchfulli-dev** [comment]
@test after applying the patch the top right ordering option is removed, and the filters from the left side are moved inside "Search tools" on top, but now seams the filters are not working, for example if I try to filter them by "Trashed" items, the published user note is still displayed after applying the filter<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7708">issues.joomla.org/joomla-cms/7708</a>.</sub>

**Comment by kesh52** [comment]
I have an issue like by **watchfulli-dev**.
If I filter by status and need only "Unpublished" items, all items are displayed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7708">issues.joomla.org/joomla-cms/7708</a>.</sub>

**Comment by pe7er** [comment]
Thank you for testing @watchfulli-dev & @kesh52 !
I was able to reproduce the issue you both reported & corrected it in my patch.
Now the Status filter should work correctly...

**Comment by bullet64** [comment]
Hello, i have installed the patch but i have issues.

I have created 4 user-notes.
- published
- unpublished
- trashed
- archived

Filter all - works
Filter published - shows published & unpublished
Filter trashed - ok
Filter archived - ok

**Comment by YouriiM26** [comment]
I have the same as @bullet64. Published and unpublished shows the same thing.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7708">issues.joomla.org/joomla-cms/7708</a>.</sub>

**Comment by pe7er** [comment]
Thank you @bullet64 @YouriiM26 for testing & reporting the problem. 
I've fixed it with a new patch.

**Comment by YouriiM26** [comment]
I have tested this item :white_check_mark: successfully on a9bce891c5b667a721c0dfd164d5b7dc0f438b75<br /><br />The new patch worked for me. The published and unpublished aren't the same anymore. Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7708">issues.joomla.org/joomla-cms/7708</a>.</sub>

**Comment by RemcoJanssen** [comment]
I have tested this item :white_check_mark: successfully on a9bce891c5b667a721c0dfd164d5b7dc0f438b75<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7708">issues.joomla.org/joomla-cms/7708</a>.</sub>

**Comment by zero-24** [comment]
RTC for 3.5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7708">issues.joomla.org/joomla-cms/7708</a>.</sub>

**Comment by Kubik-Rubik** [comment]
@pe7er Thank you for the contribution. The move from the sidebar is good but we decided to not remove the ordering fields in the PLT. Could you please remove this part from your PR and we can add this PR to the 3.5 version.

This needs a review to be merged!

**Comment by pe7er** [comment]
@Kubik-Rubik I know about not removing the ordering fields.
I corrected that in some other PRs I did list night.
I'll correct it in this patch too...

**Comment by pe7er** [comment]
I've corrected the PR to add the ordering fields back (via the filter_notes.xml that is used by Search Tools)

com_users-notes-afterv2

**Comment by Kubik-Rubik** [comment]
I have tested this item :white_check_mark: successfully on 78f1f4f071a4ba48bba9bf87fa9123640b41b769<br /><br />Works as described. Thank you @pe7er!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7708">issues.joomla.org/joomla-cms/7708</a>.</sub>

**Comment by dgt41** [comment]
I have tested this item :white_check_mark: successfully on 78f1f4f071a4ba48bba9bf87fa9123640b41b769<br /><br />Small note here: there is no ordering option so no drag and drop to reorder. maybe in another PR<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7708">issues.joomla.org/joomla-cms/7708</a>.</sub>

**Comment by dgt41** [comment]
I have tested this item :white_check_mark: successfully on 78f1f4f071a4ba48bba9bf87fa9123640b41b769<br /><br />Small note here: there is no ordering option so no drag and drop to reorder. maybe in another PR<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7708">issues.joomla.org/joomla-cms/7708</a>.</sub>

**Comment by zero-24** [comment]
@Kubik-Rubik this gets tested twice please do the final review and move to RTC if ok ;)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7708">issues.joomla.org/joomla-cms/7708</a>.</sub>

**Pull request closed without merging**
