### PR TITLE
Banned text strings consistency

### PR DESCRIPTION
**Pull request by brianteeman**
The text used for the banned fields in com_contacts is different in the component options and the individual contact options. Irrelevant of if the information is needed or not we should be consistent. So on the basis that it is important to have the extra information I have updated the individual contact strings to match the component ones.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on bd1459833f032256d9a0059c675746cbfce2d162<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17108">issues.joomla.org/tracker/joomla-cms/17108</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on bd1459833f032256d9a0059c675746cbfce2d162<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17108">issues.joomla.org/tracker/joomla-cms/17108</a>.</sub>

**Comment by ghost** [comment]
RTC after two successful tests.

**Comment by brianteeman** [comment]
Thanks for merging

**Pull request merged**
