### PR TITLE
Fix mod_articles_categories caching, allow CategoryNode serialization

### PR DESCRIPTION
**Pull request by Denitz**
Pull Request for Issue #38782.

### Summary of Changes

1. Caching of Articles Categories module fails because `CategoryNode` tries to serialize `Categories` with database layer instance which is not technically serialazable due to presence of `Closure` and i.e. `PDOStatement` objects.
We need to allow `CategoryNode` serialization.

### Testing Instructions

1. Enable Joomla caching.
2. Create Articles Categories module to display lots of categories.
3. Browse website as a guest.

### Actual result BEFORE applying this Pull Request

See serialization error.

### Expected result AFTER applying this Pull Request

No errors, module is cached.

### Link to documentations

No documentation changes for docs.joomla.org needed
No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by joomdonation** [comment]
@Denitz Many thanks for your work. May I suggest splitting your PR into two smaller ones

- The bug fix in one PR
- The improvement in another PR

That would make it easier to test. I think the bug fix could go into 4.3 and the improvement could go to 4.4. As the current state of 4.3, Release Lead might not want to take the risk of too many changes.

**Comment by Denitz** [comment]
@joomdonation Done, preload PR is https://github.com/joomla/joomla-cms/pull/40279

**Comment by joomdonation** [comment]
Great, thanks @Denitz. We will test this PR ASAP.

**Comment by joomdonation** [comment]
I have tested this item :white_check_mark: successfully on 85292dd42205a6557045472e5a5638c5056a89cb<br /><br />Works well for both cache on and off. Also tried to test the menu items which uses categories and it is still working well.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40275">issues.joomla.org/tracker/joomla-cms/40275</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 85292dd42205a6557045472e5a5638c5056a89cb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40275">issues.joomla.org/tracker/joomla-cms/40275</a>.</sub>

**Comment by Vegaturk** [comment]
Hi Denitz, these fixes seem to have been committed to version 4.3.0 I updated to version 4.3.0 my module cache was disabled, I activated it again and it keeps returning the same error "0 Serialization of 'Closure' is not allowed"

**Comment by obuisard** [comment]
Thank you @Denitz for this PR!

**Pull request merged**
