### PR TITLE
[4.3] Batch Copy Contacts

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #40263 .

### Summary of Changes
ensure that $published is an integer

Pull Request for Issue #40261 .

### Summary of Changes
ensure that $published is an integer

### Testing Instructions
Create a contact and then try a batch action. It should look like this
image

Then apply any filter and/or sort by any column and try to batch action again

### Actual result BEFORE applying this Pull Request
image

### Expected result AFTER applying this Pull Request
image

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 9d21e0eb35b34a64f5ed96fb5979b705e37f52ac<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40264">issues.joomla.org/tracker/joomla-cms/40264</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 9d21e0eb35b34a64f5ed96fb5979b705e37f52ac<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40264">issues.joomla.org/tracker/joomla-cms/40264</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40264">issues.joomla.org/tracker/joomla-cms/40264</a>.</sub>

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
