### PR TITLE
[4.0] Improve Layout of workflowfield in articles batch

### PR DESCRIPTION
**Pull request by chmst**
### Summary of Changes
Add class "custom-select" to the workflow field in articles batch.
At the moment, the width of custom-select is defined with 240px. 
So the text must be shortened to fit the width. For a solution, it needs mor opinions: Shorten text or enlarge width at least for this modal batch?

batch-articles-after

### Testing Instructions
Have at least one article. Mark it and click the batch button. 

### Expected result
The layout of the workflow field is the same as for other fields. 

### Actual result
The workflow field is old fashioned.

### CODE REVIEW

**Comment by coolcat-creations** [comment]
I'd say we need a wider field because we need flexibility when language strings are longer.

**Comment by lavipr** [comment]
I have tested this item :white_check_mark: successfully on 0f2d97438dec119766a9fc7a6aaa719c734247f4<br /><br />Testing steps: 
- have at least one article
- marked one article and clicked the batch button
-> the layout of the workflow field is the same as for the others<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22067">issues.joomla.org/tracker/joomla-cms/22067</a>.</sub>

**Comment by coolcat-creations** [comment]
I have tested this item :white_check_mark: successfully on 0f2d97438dec119766a9fc7a6aaa719c734247f4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22067">issues.joomla.org/tracker/joomla-cms/22067</a>.</sub>

**Comment by Schmidie64** [comment]
I have tested this item :white_check_mark: successfully on 0f2d97438dec119766a9fc7a6aaa719c734247f4<br /><br />@icampus<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22067">issues.joomla.org/tracker/joomla-cms/22067</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after 3 successful tests.

**Comment by brianteeman** [comment]
triggered an update to retest with drone

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
