### PR TITLE
[WIP][4.0] - workwflow mysql schema

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #workflow .

### Summary of Changes
still work in progress - "normalize" the schema

### CODE REVIEW

**Comment by bembelimen** [comment]
I have tested this item :white_check_mark: successfully on 66acf98ee182dd65aba36a2e4df97ae229540290<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21499">issues.joomla.org/tracker/joomla-cms/21499</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by alikon** [comment]
BTW it wasn't complete.....

**Comment by wilsonge** [comment]
Oops :) I should read PR titles more carefully in the morning :( sorry!

**Comment by alikon** [comment]
@wilsonge if you really want to merge something already ready  please look at https://github.com/joomla/joomla-cms/pull/19707 🙏

**Pull request merged**
