### PR TITLE
[Fix #6876] Regression: Routing errors when "Remove URL Language Code" is set in "Language filter"

### LINKED ISSUE #6876: Routing errors when "Remove URL Language Code" is set in "Language filter"
#### Steps to reproduce the issue
- Have a multilingual site for which the default language code (e.g. en-UK) is hidden and a secondary language (e.g.: it-IT)
- have two valid URLs, one for the primray, one for the secondary language (e.g.: `http://nuovaicona.org/exhibitions-and-events/other-venues/luna-d-acqua` and `http://nuovaicona.org/it/mostre-ed-eventi/altre-sedi/luna-d-acqua`) The two URLs are associated, but that doesn't matter much.
- Assuming you already are *"in the primary language"* visit the first URL
- Now switch language to the secondary one using the language switcher
- Paste the primary language URL in the address bar of your browser

#### Expected result
The page should be displayed

#### Actual result
You get a 404

#### System information (as much as possible)
PHP Built On: 	Windows NT SMZ 6.3 build 9200 (Windows 8.1 Business Edition) i586
Database Version: 	5.6.23
Database Collation: 	utf8_general_ci
PHP Version: 	5.4.39
Web Server: 	Apache
WebServer to PHP Interface: 	apache2handler
Joomla! Version: 	Joomla! 3.4.1 Stable [ Ember ] 21-March-2015 20:30 GMT
Joomla! Platform Version: 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent: 	Mozilla/5.0 (Windows NT 6.3; WOW64; rv:37.0) Gecko/20100101 Firefox/37.0 

#### Additional comments
This bug creates **huge issues** when you are set in a secondary language, get an URL for the primary language from another source (e.g.: Google Search) and click on it. Instead of being routed to the correct page you get a 404.

No problems if the "Remove URL Language Code" options is **not** set in "Language filter".

### PR DESCRIPTION
**Pull request by infograf768**
See https://github.com/joomla/joomla-cms/issues/6876 for testing instructions.

Looking for a cookie should be done only when loading the pure tld.
This checks if we have anything after the tld before looking for an existing cookie.

Thank you for testing.

### CODE REVIEW

**Comment by smz** [comment]
It seems to work (with SEF URLs turned on), but...
- you are in the secondary language
- you click on a primary-language URL (*OK, you get it*)
- you navigate away to other "internal" links (*you stay in the primary language*)
- you go to the "naked domain" (*you are now back into the secondary language*)

I'm unsure if this should be the expected behavior...

**Comment by infograf768** [comment]
>you go to the "naked domain" (you are now back into the secondary language)

Not here as we have a cookie set for the primary language. Please test again.

**Comment by smz** [comment]
You're right JM: I can't reproduce what I've initially seen... curious...  :-/
Disregard my previous comment!
Thanks!

**Comment by infograf768** [comment]
One more test and we can solve this regression in 3.4.2  :+1:

**Comment by dgt41** [comment]
@test success
Thanks JM!
Sergio, I am glad to see you around

**Comment by smz** [comment]
Thanks Dimitris!
You know how it is... *Sometimes They Come Back*! :smile:

**Comment by zero-24** [comment]
RTC'ing Thanks :smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6881">issues.joomla.org/joomla-cms/6881</a>.</sub>

**Comment by infograf768** [comment]
@smz and @dgt41

Please test
https://github.com/joomla/joomla-cms/pull/6746

**Pull request merged**
