### PR TITLE
[4.0] Move Searchtools styling to template

### PR DESCRIPTION
**Pull request by Fedik**
### Summary of Changes

This will move searchtools styling to the template files.
More info in #27384 comments.

### Testing Instructions

Apply patch, run `npm install`

### Expected result
All works

### Actual result
Almost works, with some rtl issue

@infograf768 please check

### CODE REVIEW

**Comment by infograf768** [comment]
Let's go for it.
We can correct some more stuff after merge.
Some are in _toolbar.scss

@wilsonge @HLeithner

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 789eabc603813c3bb2c9afa9d987a8e9c778eb6c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27416">issues.joomla.org/tracker/joomla-cms/27416</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 789eabc603813c3bb2c9afa9d987a8e9c778eb6c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27416">issues.joomla.org/tracker/joomla-cms/27416</a>.</sub>

**Comment by SharkyKZ** [comment]
RTC.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27416">issues.joomla.org/tracker/joomla-cms/27416</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Comment by infograf768** [comment]
@Fedik 
To help figure any remaining issue in RTL, what have you remarked? (Please use screenshot)
To be sure, first please patch with https://github.com/joomla/joomla-cms/pull/27384

**Comment by Fedik** [comment]
@infograf768 it looks good to me:
LTR:
screen 2020-01-07 11 10 00 1560x281

RTL:
screen 2020-01-07 11 14 15 1570x283

**Comment by infograf768** [comment]
Thanks. Remains therefore after https://github.com/joomla/joomla-cms/pull/27384 is merged, some aspects from toolbar css dealing with margins in mobile view (rtl/ltr).
Will look at these later.

**Comment by infograf768** [comment]
See https://github.com/joomla/joomla-cms/pull/27443 for follow-up

**Pull request merged**
