### PR TITLE
[RFC] Run PHP Syntax checker on travis

### PR DESCRIPTION
**Pull request by zero-24**
### Summary of Changes

This should run a php -l on the code
### Testing Instructions

See that travis not fails
### Documentation Changes Required

None
### Suggestions?

Any suggestions here for the Script?
### Credits

Travis script based on: https://hakre.wordpress.com/2015/11/10/linting-php-files-in-parallel-on-travis/

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
IMHO, for consistency, you should use a variable like `RUN_PHPSYNTAXCHECK="yes"` and then is that var is yes run the bash script

Also doesn't php systax check result be difference across php versions? if so,, so it needs to be checked in all supported php version.

**Comment by mbabker** [comment]
> Also doesn't php systax check result be difference across php versions? if so,, so it needs to be checked in all supported php version.

Yep.  Because each branch has different deprecation warnings and allowed syntax (like the report at https://github.com/joomla/joomla-cms/issues/12380 will only happen with PHP 7.x but not 5.x, likewise if we tried linting https://github.com/joomla/joomla-cms/blob/staging/libraries/vendor/composer/autoload_static.php it would fail on PHP 5.5 and earlier but it's not an issue because that file isn't included by Composer on those PHP versions).

**Comment by andrepereiradasilva** [comment]
with something like this
```php
if [[ $RUN_PHP_SYNTAX_CHECK == "yes" ]]; then bash build/travis/php-syntax-check.sh; fi
```

#### build/travis/php-syntax-check.sh
```bash
#!/bin/bash
# Script for php/hhvm syntax check in Joomla!

RUN_COMMAND="php -d display_errors=stderr -n -l"

if [[ $TRAVIS_PHP_VERSION = hhvm ]]; then RUN_COMMAND="hhvm -d display_errors=stderr -l"; fi

find . \( -path ./libraries/vendor -o -path ./libraries/phpass -o -path ./libraries/fof -o -path ./tests -o -wholename './administrator/components/com_joomlaupdate/restore.php' \) -prune -o -type f -name "*.php" -print | xargs -n1 -P8 $RUN_COMMAND 1>/dev/null
```

we can faster lint tests (around 75s in php7 - was 107s here) and test also in hhvm
notice i removed the lint test for fof and unit tests
maybe it could be faster, by messing with the find command

**Comment by zero-24** [comment]
Thanks @andrepereiradasilva It works now.

See here for a systax error: https://travis-ci.org/joomla/joomla-cms/jobs/167874647
And here if it works without problems: https://travis-ci.org/joomla/joomla-cms/jobs/167876323

I have also added excluded more 3rd Party folders.

So i think we are good to go here?

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 8469b8a05ea349703044e15cb37907cb8c0c3c3a<br /><br />works fine.
the only "issue" here is that it delays all unit tests more than 75s
but i guess we have to live with that ...<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12379">issues.joomla.org/tracker/joomla-cms/12379</a>.</sub>

**Comment by zero-24** [comment]
Any reason to not merge this?

**Comment by zero-24** [comment]
Is there no interest in merging this so we can close here? @rdeutz @wilsonge ?

**Comment by rdeutz** [comment]
travis runs already long enough so adding more stuff to it makes it run even longer

**Comment by zero-24** [comment]
Closing than :smile:

**Comment by andrepereiradasilva** [comment]
@zero-24 maybe you can add this to drone, instead of travis. not sure if possible.

At least PHP CS is way faster in drone (around 25s) that was in travis (around 150s)

**Comment by rdeutz** [comment]
we have an infrastructure sprint in tow weeks and we will look if we ca run syntax checks as part of the pipeline we than have setup

**Pull request closed without merging**
