### PR TITLE
Update blog.php

### PR DESCRIPTION
**Pull request by uglyeoin**
Pull Request for Issue # .
#### Summary of Changes

added the class art-featured to featured articles in category blog view
#### Testing Instructions

Create a featured leading article & intro article, then create non-featured articles for leading / intro.  See if the class art-featured appears on the featured articles only.

### CODE REVIEW

**Comment by brianteeman** [comment]
As this is only for the beez template I assume that really what you meant to do was to ADD it to your existing pull request and not to create a brand new one.

When you are using github.com to create a pull request you do not need to create a new PR for each individual file that you are editing. Once you have made your first edit then github will have created a branch in your own fork of joomla. If you then switch to use that then any changes made to that branch will be added to your first pull request

**Comment by uglyeoin** [comment]
You are entirely right.  Is there a way for me to make this change now?

**Comment by brianteeman** [comment]
Do it as I described. Your original Pull Request will show the nam of the branch on your own repo that you need to edit.

Closing this here

**Comment by uglyeoin** [comment]
Does that mean I need to go to the other branch and amend the files there?

**Comment by brianteeman** [comment]
yes that is what I wrote

On 20 April 2016 at 19:19, uglyeoin <notifications@github.com> wrote:

> Does that mean I need to go to the other branch and amend the files there?
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/10014#issuecomment-212542898>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by rdeutz** [comment]
@uglyeoin all commits to the branch will show up in the PR, amend might not work

**Comment by brianteeman** [comment]
@rdeutz it does ;)

**Comment by rdeutz** [comment]
@brianteeman it only works for me when I haven't push something to a remote repo, anyway, can be me

**Comment by uglyeoin** [comment]
I am still unsure as to how to achieve what you want me to achieve.  I tried to amend it but I couldn't find the answer.  If I go to the other pull request and press amend it shows me the file I already amended.  Is there some information somewhere that I can follow?

**Comment by rdeutz** [comment]
* check out the other branch
* copy the file you have changes here into the brach
* commit
* push

**Comment by uglyeoin** [comment]
I assume that is all possible via the browser?

**Comment by brianteeman** [comment]
To do it by the browser do it EXACTLY as you did it here but on your own
branch

On 20 April 2016 at 19:29, uglyeoin <notifications@github.com> wrote:

> I assume that is all possible via the browser?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/10014#issuecomment-212546703>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by uglyeoin** [comment]
image

That is my branch right?  And I have made the changes there, so I've done the right thing?

It is set to "patch 3" as the branch.  Is that right, or should it be staging or something else?

I really struggle to find my own branch... :|

**Comment by brianteeman** [comment]
Patch 3 is THIS branch but you want to be making the change to your original PR(10011) which in this case is your staging branch

o9e9

cejo

**Pull request closed without merging**
