### PR TITLE
Fix the calendar to work in the subform field

### PR DESCRIPTION
**Pull request by Fedik**
### Summary of Changes
This patch fix new calendar field to work in the subform field

### Testing Instructions
Make sure that calendar field work in the subform 
Example xml, can place in "Custom HTML" module xml (somwhere in params fieldset):
```xml
<field name="items" type="subform"  multiple="true"  label="Subform Field" >
  <form>
    <field name="something"  type="calendar" label="Calendar" />
  </form>
</field>
```

### Documentation Changes Required
none

### CODE REVIEW

**Comment by Fedik** [comment]
can we have some test here? so the calendar field will be fully working in J3.7

**Comment by franz-wohlkoenig** [comment]
@Fedik can you please instruct where to place the example.xml or put Code in and where to look if calendar work in subform field?

**Comment by Fedik** [comment]
I have updated description a bit,
can place in "Custom HTML" module xml, somewhere in params fieldset

**Comment by joomdonation** [comment]
It works:

1. Before patch: We could not select a date from calendar form field in sub-form

2. After path: We can select a date from calendar

The only thing is the sub-form container looks too large (both before and after patch - unrelated to this PR), not sure if we have to care about it or not. If not, let me know and I will mark the test success

sub-form-calendar-test

**Comment by joomdonation** [comment]
@franz-wohlkoenig 

Put the XML code above to the file **modules/mod_login/mod_login.xml** after this line, https://github.com/joomla/joomla-cms/blob/staging/modules/mod_login/mod_login.xml#L130

Then edit the Login module, check that sub form field, make sure you can select date from the calendar

**Comment by Fedik** [comment]
@joomdonation I did not touched the styling, in theory it should be the same as in other places

**Comment by joomdonation** [comment]
I have tested this item :white_check_mark: successfully on 50b83cfd17cf3427dd52455ca3dcee5b8a0b7285<br /><br />It works:

1. Before patch: We could not select a date from calendar form field in sub-form

2. After path: We can select a date from calendar. Also, the standard calendar form field still works as before<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13153">issues.joomla.org/tracker/joomla-cms/13153</a>.</sub>

**Comment by joomdonation** [comment]
@Fedik : Yes, I know and mentioned that it is unrelated to this PR. Marked my test as success.

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 50b83cfd17cf3427dd52455ca3dcee5b8a0b7285<br /><br />Thanks for helping on instructions.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13153">issues.joomla.org/tracker/joomla-cms/13153</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13153">issues.joomla.org/tracker/joomla-cms/13153</a>.</sub>

**Comment by seanjermey** [comment]
Issue is still present when the subform is in the menu type xml file.

## Testing Instructions

Put the XML code above to the file components/com_content/views/article/tmpl/default.xml after this line 35 - https://github.com/joomla/joomla-cms/blob/staging/components/com_content/views/article/tmpl/default.xml#L35

Then make a new menu item of type article, go to the options tab, add a new subform instance and click the calendar button<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13153">issues.joomla.org/tracker/joomla-cms/13153</a>.</sub>

**Comment by zero-24** [comment]
Please open a new issue that contains a way to reproduce the problem on the last version. As this comment on a closed / merged issue will get lost soon. Thanks!

**Comment by seanjermey** [comment]
Thank you zero-24 and apologies. I am unfamiliar with the process as this is my 1st bug report on joomla. 

New issue added - https://issues.joomla.org/tracker/joomla-cms/15842<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13153">issues.joomla.org/tracker/joomla-cms/13153</a>.</sub>

**Comment by zero-24** [comment]
No need to apologies. I just want to be sure this does not get missed 😄

**Pull request merged**
