### PR TITLE
Contact form loses data after postback with error

### PR DESCRIPTION
**Pull request by sandewt**
Pull Request for issue #17126.

### Summary of Changes
Some code.

### Testing Instructions
Instructions, see issue #17126
* Go to Single Contact. 
* Fill in the form. 
* Do not fill in captcha.
* Send email.

### Expected result
Warning + textboxes are NOT empty. 

### Actual result
All textboxes are empty, so the user has to fill in AGAIN all textboxes.

### Documentation Changes Required
No.

### Thanks to
@pascal-910

### CODE REVIEW

**Comment by sandewt** [comment]
I'm new on Github.
If I have downloaded the code and look to the characters.
So I see in my editer, that after the "{" and the "}" braces (accolades) is a tab. In line 76 and 78. (NOK.)
How can I avoid this in github by making a PR?

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17743">issues.joomla.org/tracker/joomla-cms/17743</a>.</sub>

**Comment by sandewt** [comment]
**Ask for input.**

Is the following code nessecary?
```php
empty($item->catid)

```
In the DB table xxx_content is defined:
```
`catid` int(10) UNSIGNED NOT NULL DEFAULT '0'
```
So the catid may not be empty !?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17743">issues.joomla.org/tracker/joomla-cms/17743</a>.</sub>

**Comment by n9iels** [comment]
The patch works fine for me.

> Is the following code nessecary?

There is never a problem with extra test :-). However in this situation only `!empty($item->catid)` is enough. `!isset($item->catid)` will only check  if the `$item` object has a 'catid' property. `!empty($item->catid)` will check if the `$item` object has a 'catid' property, and this property is not empty. See this post for more information: 

https://stackoverflow.com/questions/7191626/isset-and-empty-what-to-use#answer-7191642

If you change this I can conform the test via the J!Issue tracker.

**Comment by sandewt** [comment]
Thanks, interesting post.

Do you mean`!empty($item->catid)` or `empty($item->catid)` is enough? Because catid is not empty.
The function `$app->setUserState(..)` may not be executed in this situation!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17743">issues.joomla.org/tracker/joomla-cms/17743</a>.</sub>

**Comment by sandewt** [comment]
> Do not fiil in captcha. After send all data form loses after postback !!!

contactform

**Comment by sandewt** [comment]
Sorry, a mistake for closing!!

**Comment by sandewt** [comment]
Please test this PR #17126 or give comment.

**Comment by conconnl** [comment]
I have tested this item :white_check_mark: successfully on 8004b7ad6d1be7db1dbf0348c4c13ef688f095ef<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17743">issues.joomla.org/tracker/joomla-cms/17743</a>.</sub>

**Comment by slibbe** [comment]
I have tested this item :white_check_mark: successfully on 8004b7ad6d1be7db1dbf0348c4c13ef688f095ef<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17743">issues.joomla.org/tracker/joomla-cms/17743</a>.</sub>

**Comment by ghost** [comment]
RTC after two successful tests.

**Comment by wojsmol** [comment]
@franz-wohlkoenig Please see @n9iels https://github.com/joomla/joomla-cms/pull/17743#issuecomment-325452844 
@sandewt Can you address this  https://github.com/joomla/joomla-cms/pull/17743#issuecomment-325452844?

**Comment by ghost** [comment]
@wojsmol means this Comment not RTC?

**Comment by wojsmol** [comment]
@franz-wohlkoenig Let's leve desicion to one of maainterners. Code my to be a little simpler, but both versions works.

**Comment by sandewt** [comment]
On closer inspection and the comments, the following:

In the Joomla! core rarely used the combination of 'isset and empty', and not for no reason.
So I choise for the proposal of @Niels that one test is enough.
I expect a string for $item->catid (gettype) which is p.e. '16'. And not '' or '0'. 
So I prefer 'empty' in stead of '!isset' if the user state ($app->setUserState) is not yet set.
See also: http://php.net/manual/en/types.comparisons.php

 So I changed the code, PLEASE TEST AGAIN.

**Comment by sandewt** [comment]
Sorry for closing, issue should be open @franz-wohlkoenig.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17743">issues.joomla.org/tracker/joomla-cms/17743</a>.</sub>

**Comment by brianteeman** [comment]
re-opened

**Comment by sandewt** [comment]
Thanks Brian, and @niels should be @n9iels.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17743">issues.joomla.org/tracker/joomla-cms/17743</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 9377adb102b4d407c0d5da9097b567ef87d5d812<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17743">issues.joomla.org/tracker/joomla-cms/17743</a>.</sub>

**Comment by ghost** [comment]
@conconnl @slibbe can one of you please test?

**Comment by Sieger66** [comment]
I have tested this item :white_check_mark: successfully on 9377adb102b4d407c0d5da9097b567ef87d5d812<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17743">issues.joomla.org/tracker/joomla-cms/17743</a>.</sub>

**Comment by Quy** [comment]
RTC

**Comment by ReLater** [comment]
Looks like this pr has opened another issue. See https://github.com/joomla/joomla-cms/issues/20195 please.

**Comment by infograf768** [comment]
@sandewt 
Please look at https://github.com/joomla/joomla-cms/issues/20195#issuecomment-383330786

**Pull request merged**
