### PR TITLE
Client/MenuType selector in Menu and Modules administrator list views (mobile xs)

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Description

This PR solves https://github.com/joomla/joomla-cms/issues/9031.
#### How to test
1. Install latest staging
2. Go to com_menus items view or com_modules modules view and reduce the browser width so you be in mobile xs size.
3. How will see that the selector (client or menutype, depending on the view) disappeared
4. Apply this patch
5. Repeat 2 and 3 you will see now the selector (client or menutype, depending on the view) is there.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 964c9e260739fffc0d72a08a8b602ac5dc88fd05<br /><br />Perfect - thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9151">issues.joomla.org/joomla-cms/9151</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@brianteeman i forgot to say but i also added jquery to reset the filter form when changing menutype (menu items) or client (modules). See https://github.com/andrepereiradasilva/joomla-cms/blob/menu-modules-views-mobile-xs-selector/administrator/components/com_menus/models/forms/filter_items.xml#L8
Please check that too.

**Comment by brianteeman** [comment]
oh - not sure I like that.

**Comment by andrepereiradasilva** [comment]
My view has, for UX, to maintain the same behavior when using a view selector. "Location" in several views and "MenuType" in menu items view.

For "Location" IMHO it make sense, not entirety sure that is useful in the case of the menu items types.

I can remove it if you guys prefer.

**Comment by brianteeman** [comment]
Can you remove it from this PR and propose it in a new pr on its own. For
me it would be very annoying if I have set the menu to display 1 max level
for me to switch menu and have to do that all over again. Others may
disagree but i really feel it is out of scope of this PR

On 18 February 2016 at 17:13, andrepereiradasilva <notifications@github.com>
wrote:

> My view has, for UX, to maintain the same behavior when using a view
> selector. "Location" in several views and "MenuType" in menu items view.
>
> For "Location" IMHO it make sense, not entirety sure that is useful in the
> case of the menu items types.
>
> I can remove it if you guys prefer.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/9151#issuecomment-185819504>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by andrepereiradasilva** [comment]
Done. Reseted to previous behaviour.

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 761925a0cb21c9fdcd9fcdf41e58151ef9b9e51d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9151">issues.joomla.org/joomla-cms/9151</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 761925a0cb21c9fdcd9fcdf41e58151ef9b9e51d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9151">issues.joomla.org/joomla-cms/9151</a>.</sub>

**Comment by brianteeman** [comment]
RTC thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9151">issues.joomla.org/joomla-cms/9151</a>.</sub>

**Comment by wilsonge** [comment]
Merged - thanks!

**Pull request closed without merging**
