### PR TITLE
[4.0] Global Config: correcting Text filters display

### PR DESCRIPTION
**Pull request by infograf768**
### Summary of Changes 
Following up on https://github.com/joomla/joomla-cms/pull/27684#issuecomment-580189119
`custom-select` should be auto instead of 100%

### Testing Instructions
Display Global Configuration Text Filters tab. Reduce window width.
See before patch. Patch and use npm

### Before patch
beforeconfig

### After patch
afterconfig

### CODE REVIEW

**Comment by brianteeman** [comment]
I dont get the scroll bar on my phone or on chrome mobile emulation on my desktop - but maybe thats an OS thing as its not unique to this screen<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27731">issues.joomla.org/tracker/joomla-cms/27731</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 2efd2eefd8052c5b2e5384691b494bd60253e99c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27731">issues.joomla.org/tracker/joomla-cms/27731</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 2efd2eefd8052c5b2e5384691b494bd60253e99c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27731">issues.joomla.org/tracker/joomla-cms/27731</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27731">issues.joomla.org/tracker/joomla-cms/27731</a>.</sub>

**Comment by Quy** [comment]
@infograf768 Table not full width.

**Comment by infograf768** [comment]
> @infograf768 Table not full width.

will look tomorrow.

**Comment by infograf768** [comment]
@Quy 
Indeed, table is not full width in very wide screens because was added the class `table-responsive` in https://github.com/joomla/joomla-cms/pull/27684
which was the only way to solve the display in mobile view.

We could solve the issue using @media queries, but we have a problem with the sidebar menu which can be toggled and therefore change drastically the width.
maybe this could be solved by js to only depend on the parent element.


@ciar4n
Can you look at this?

**Comment by ciar4n** [comment]
The `table-responsive` class would set the display to `block` which will not play nice with 100% width tables. If possible try applying the `table-responsive` class to a parent div of the table, not the table itself.

```
<div class="table-responsive">
  <table class="table"> .. </table>
</div> 
```

**Comment by infograf768** [comment]
will try now

**Comment by infograf768** [comment]
Works great.
Please test
https://github.com/joomla/joomla-cms/pull/27754

**Pull request merged**
