### PR TITLE
Update tinymce 4.5.2

### PR DESCRIPTION
**Pull request by dgrammatiko**
Version 4.5.2 - January 4, 2017

- ADDED missing keyboard shortcut description for the underline menu item in the format menu.
- FIXED bug where external blob urls wasn't properly handled by editor upload logic. Patch contributed by David Oviedo.
- FIXED bug where urls wasn't treated as a single word by the wordcount plugin.
- FIXED bug where nbsp characters wasn't treated as word delimiters by the wordcount plugin.
- FIXED bug where editor instance wasn't properly passed to the format preview logic. Patch contributed by NullQuery.
- FIXED bug where the fake caret wasn't hidden when you moved selection to a cE=false element.
- FIXED bug where it wasn't possible to edit existing code sample blocks.
- FIXED bug where it wasn't possible to delete editor contents if the selection included an empty block.
- FIXED bug where the formatter wasn't expanding words on some international characters. Patch contributed by Martin Larochelle.
- FIXED bug where the open link feature wasn't working correctly on IE 11.
- FIXED bug where enter before/after a cE=false block wouldn't properly padd the paragraph with an br element.
- FIXED so font size and font family select boxes always displays a value by using the runtime style as a fallback.
- FIXED so missing plugins will be logged to console as warnings rather than halting the initialization of the editor.
- FIXED so splitbuttons become normal buttons in advlist plugin if styles are empty. Patch contributed by René Schleusner.
- FIXED so you can multi insert rows/cols by selecting table cells and using insert rows/columns.

Pull Request for Issue # .

### Summary of Changes
- Update tinymce to latest version
- Correct file permissions

### Testing Instructions
Apply patch, select tinyMCE as your default editor and edit an article (try to use as much of the editor's functionality as possible)

### Documentation Changes Required
None

---
This change is [Reviewable](https://reviewable.io/reviews/joomla/joomla-cms/13481)

### CODE REVIEW

**Comment by infograf768** [comment]
Version change missing in the xml

**Comment by dgt41** [comment]
@infograf768 thanks, I keep forgetting things...

**Comment by infograf768** [comment]
Works fine here. Although some files permissions are corrected which do not concern TinyMCE.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13481">issues.joomla.org/tracker/joomla-cms/13481</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 17821a07fd71bcf9ad17f744f4de972b9261f763<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13481">issues.joomla.org/tracker/joomla-cms/13481</a>.</sub>

**Comment by anibalsanchez** [comment]
I have tested this item :white_check_mark: successfully on 17821a07fd71bcf9ad17f744f4de972b9261f763<br /><br />Test OK<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13481">issues.joomla.org/tracker/joomla-cms/13481</a>.</sub>

**Comment by dgt41** [comment]
Thanks @infograf768 @anibalsanchez 
RTC

**Pull request merged**
