### PR TITLE
Remove link in language code doc

### PR DESCRIPTION
**Pull request by brianteeman**
This link is not relevant

Pull Request for Issue #25808

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on ec624eb266bd5e4b69a0b0030b15a8f054dc5089<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25811">issues.joomla.org/tracker/joomla-cms/25811</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on ec624eb266bd5e4b69a0b0030b15a8f054dc5089<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25811">issues.joomla.org/tracker/joomla-cms/25811</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25811">issues.joomla.org/tracker/joomla-cms/25811</a>.</sub>

**Comment by zero-24** [comment]
Merging. Thanks all for keeping everything up-to-date and correct 👍

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
