### PR TITLE
[4.0] setMetaData

### PR DESCRIPTION
**Pull request by brianteeman**
The function is called setMetaData but in some places it was written as setMetadata

This fixes that. Just test to make sure that there is metadata being set in the components

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 782095041adf8cd65175f92426856a799e7fb160<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20779">issues.joomla.org/tracker/joomla-cms/20779</a>.</sub>

**Comment by carlitorweb** [comment]
I have tested this item :white_check_mark: successfully on 782095041adf8cd65175f92426856a799e7fb160<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20779">issues.joomla.org/tracker/joomla-cms/20779</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20779">issues.joomla.org/tracker/joomla-cms/20779</a>.</sub>

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
