### PR TITLE
[5.2] Only register hits on items when GET or POST request

### PR DESCRIPTION
**Pull request by Hackwar**
Pull Request for Issue #40476 .

### Summary of Changes
Right now, Joomla registers every call to the URL of a content item as a hit. However, there are cases where for example FeedBurner does HEAD requests to the URL, which isn't really a real request to get the content item. This PR filters the requests to only be registered as a hit when triggered by GET or POST.

### Testing Instructions
Install the testing sample data and visit an article of your choice, for example "Content Component". See the hit counter. Request the same URL with a tool like Postman as a HEAD request.

### Actual result BEFORE applying this Pull Request
The HEAD request is counted as a hit.

### Expected result AFTER applying this Pull Request
The HEAD request is not counted as a hit.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Ruud68** [comment]
Hi @Hackwar , can you eleborate what is the reason for doing these changes in the controller / view and not in the model  or table hit function?

**Comment by Hackwar** [comment]
The model and table do the actual work of registering the hit. The decision if the hit should be counted has to be done by the controller/view. Normally, the code should be unified to check this either in the controller or in the view and not one time in the controller and the other time in the view. I can't say which solution is the right one right now. In the end, you might want to use the model or table in another context (a JSON API or CLI code) and register that as a hit, which would then create problems when you have the additional checks in there.

**Comment by crommie** [comment]
I have tested this item :white_check_mark: successfully on 98a9ed5f5c62df52adf84b21628226c6e59bc917<br /><br />Works as described. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43231">issues.joomla.org/tracker/joomla-cms/43231</a>.</sub>

**Comment by TLWebdesign** [comment]
I have tested this item :white_check_mark: successfully on 98a9ed5f5c62df52adf84b21628226c6e59bc917<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43231">issues.joomla.org/tracker/joomla-cms/43231</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43231">issues.joomla.org/tracker/joomla-cms/43231</a>.</sub>

**Pull request merged**
