### PR TITLE
[4.0] Fix modal data attributes

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/35624 .

### Summary of Changes

Attributes need to be renamed to  `data-bs-*` from `data-*` for BS5 

### Testing Instructions

Modal backdrop works

### CODE REVIEW

**Comment by Kubik-Rubik** [comment]
I have tested this item :red_circle: unsuccessfully on e5954a98e9c70e3b0095ecacc5ec552df088ab7f<br /><br />The modal is still closed when clicked outside the window, even though the option names are correct for BS5.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35626">issues.joomla.org/tracker/joomla-cms/35626</a>.</sub>

**Comment by dgrammatiko** [comment]
@Kubik-Rubik might be related to the fact that BS is 2 versions behind in the repo, if you could test this in conjunction to https://github.com/joomla/joomla-cms/pull/35518

EDIT, no there was a bug the backdrop needs to be `string` or `false` when is passed from php to js

**Comment by Kubik-Rubik** [comment]
I have tested this item :white_check_mark: successfully on ed474932c7b74a6c8edb45ed565118c129036559<br /><br />Now it works as expected! Thank you @dgrammatiko.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35626">issues.joomla.org/tracker/joomla-cms/35626</a>.</sub>

**Review by thednp — COMMENTED** [review]
Looks good to me

**Comment by alikon** [comment]
@thednp can you please mark it as successfully tested on https://issues.joomla.org/tracker/joomla-cms/35626
thanks in advance

**Comment by thednp** [comment]
I have tested this item :white_check_mark: successfully on ed474932c7b74a6c8edb45ed565118c129036559<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35626">issues.joomla.org/tracker/joomla-cms/35626</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35626">issues.joomla.org/tracker/joomla-cms/35626</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
