### PR TITLE
[3.7.x] Update js polyfills to 3.13.0

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
### Summary of Changes

In 3.7.x we have the new polyfill behavior to load js polyfills for old browsers.

When https://github.com/joomla/joomla-cms/pull/11686 was made we needed to make a custom change for DomContentLoaded polyfill to work (see the PR for details).

Meanwhile i made a PR in the polyfill repo https://github.com/Financial-Times/polyfill-service/pull/862 to solve the issue. Was accepted and it's integrated in version 3.1.30 (current live version) of the polyfill service.

So this PR removes that custom change to use the 3º party library without any custom changes and also updates the polyfills from 3.9.2 to 3.13.0 (current live version).

More info https://cdn.polyfill.io/v2/docs/
### Testing Instructions

After patch. Js polyfills (event, classlist) still work.
### Documentation Changes Required

None.

@dgt41 @Fedik please test.

### CODE REVIEW

**Comment by Fedik** [comment]
test is good,

but cannot set it "good" via issues.joomla.org, got strange error:
screen 2016-10-22 19 08 32 625x391

**Comment by dgt41** [comment]
Tested ok as well!
@andrepereiradasilva what is the npm package for the polyfiills (so I can add them to the automation in j4)?

**Comment by mbabker** [comment]
@andrepereiradasilva and @Fedik 

Try clearing your browser caches there.  I made a couple of changes in the last few days to stop it from saving a test without a commit SHA and found one of the JavaScript paths wasn't including the SHA in its processing (fixed now).

**Comment by andrepereiradasilva** [comment]
yeah it works now thanks @mbabker 

@Fedik @dgt41 please mark tested with success

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on df474dfda1870524711a3fbffde114c99966c5d3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12513">issues.joomla.org/tracker/joomla-cms/12513</a>.</sub>

**Comment by dgt41** [comment]
I have tested this item :white_check_mark: successfully on df474dfda1870524711a3fbffde114c99966c5d3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12513">issues.joomla.org/tracker/joomla-cms/12513</a>.</sub>

**Comment by dgt41** [comment]
RTC
Thanks @andrepereiradasilva

**Comment by zero-24** [comment]
I merge now for 3.7 Thanks!

**Comment by andrepereiradasilva** [comment]
thanks all!

**Comment by brianteeman** [comment]
Congrats and good stuff on your pr being merged upstream

**Pull request merged**
