### PR TITLE
Update Install from Web plugin text

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #11108 

simple PR to correct the language string to remove the word obsolete as identified by @PhilETaylor 
#### Testing Instructions

Its quite tricky to test. To display the message do the following
1. Install the Install from web plugin
2. Edit /plugins/installer/webinstaller/webinstaller.xml to set the < version > tag to 0.9
3. Go to Extensions install and you should now see the error message
4. Apply the patch and see the changed message

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 961446066db1d106cd382ec7d6b891b165090872<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11112">issues.joomla.org/joomla-cms/11112</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 961446066db1d106cd382ec7d6b891b165090872<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11112">issues.joomla.org/joomla-cms/11112</a>.</sub>

**Comment by rahultomar** [comment]
I have tested this item :red_circle: unsuccessfully on 961446066db1d106cd382ec7d6b891b165090872<br /><br />Not able to apply the patch<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11112">issues.joomla.org/joomla-cms/11112</a>.</sub>

**Comment by rahultomar** [comment]
Getting this error in localhost : Could not connect to GitHub: No commit found for the ref obsolete<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11112">issues.joomla.org/joomla-cms/11112</a>.</sub>

**Comment by brianteeman** [comment]
@rahultomar that sounds like an issue with your connection room to github and not related to this pr. Can you please try agaim

**Comment by RonakParmar** [comment]
I have tested this item :white_check_mark: successfully on 961446066db1d106cd382ec7d6b891b165090872<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11112">issues.joomla.org/joomla-cms/11112</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11112">issues.joomla.org/joomla-cms/11112</a>.</sub>

**Comment by killoltailored** [comment]
I have tested this item :white_check_mark: successfully on 961446066db1d106cd382ec7d6b891b165090872<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11112">issues.joomla.org/joomla-cms/11112</a>.</sub>

**Comment by zero-24** [comment]
bot please ;)

**Pull request merged**
