### PR TITLE
[4.0] Template layout select

### PR DESCRIPTION
**Pull request by brianteeman**
If the label is "Fluid Layout" then the options should be "Yes/No"

But thats not very descriptive so this PR instead changes the label to "Layout" and keeps the options to "Fluid/Static"

### Before
before

### After
after

### CODE REVIEW

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on c1d3f9bedb4e1ab9de15aa636123391347882dcd<br /><br />Tested successfully in Beta5-dev of 25 September.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30772">issues.joomla.org/tracker/joomla-cms/30772</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on c1d3f9bedb4e1ab9de15aa636123391347882dcd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30772">issues.joomla.org/tracker/joomla-cms/30772</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30772">issues.joomla.org/tracker/joomla-cms/30772</a>.</sub>

**Comment by Quy** [comment]
Thanks

**Comment by brianteeman** [comment]
thx

**Pull request merged**
