### PR TITLE
[4.0] Fix for #17449

### PR DESCRIPTION
**Pull request by kavadas**
Pull Request for Issue #17449

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 9d77b889ef94948434f3c45496b3046b3e465dc9<br /><br />"No Images" is shown.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17472">issues.joomla.org/tracker/joomla-cms/17472</a>.</sub>

**Comment by brianteeman** [comment]
While this is correct I wonder why we didn't have the problem before

**Comment by kavadas** [comment]
@brianteeman Because in 3.x the main module file ( mod_random_image.php )  had a check for empty images array. In 4.0 this check is moved inside the layout file:

https://github.com/joomla/joomla-cms/commit/73c0563a5489de83ad29a46ce6ffeda632e3ab7b#diff-25a5f460170324ee12ce61f62d09f6b8

**Comment by laoneo** [comment]
Which is how it should be.

**Comment by laoneo** [comment]
I have tested this item :white_check_mark: successfully on 9d77b889ef94948434f3c45496b3046b3e465dc9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17472">issues.joomla.org/tracker/joomla-cms/17472</a>.</sub>

**Comment by ghost** [comment]
RTC after two successful tests.

**Comment by brianteeman** [comment]
Ok thanks

**Comment by wilsonge** [comment]
Thanks!

**Comment by zero-24** [comment]
Please notice: https://github.com/joomla/joomla-cms/commit/3fc0ac2e88411a32911a8917308410c7eac1045a

**Pull request merged**
