### PR TITLE
[4.0] CSP vs. Content Security Policy

### PR DESCRIPTION
**Pull request by zero-24**
### Summary of Changes

As done in some places already. Replaces the CSP acronym with Content Security Policy

### Testing Instructions

Check the com_csp component backend views and make sure we use Content Security Policy over CSP

### Expected result

CSP from the title etc should be replaced by Content Security Policy

### Actual result

There are some places were we use CSP and some where we use Content Security Policy

### Documentation Changes Required

none

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 1217b3e6cafd8bb408239f4395fa9edb818aadac<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23412">issues.joomla.org/tracker/joomla-cms/23412</a>.</sub>

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on 1217b3e6cafd8bb408239f4395fa9edb818aadac<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23412">issues.joomla.org/tracker/joomla-cms/23412</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23412">issues.joomla.org/tracker/joomla-cms/23412</a>.</sub>

**Comment by wilsonge** [comment]
Thanks :)

**Pull request merged**
