### PR TITLE
[4.0] Remove deprecated file

### PR DESCRIPTION
**Pull request by brianteeman**
Removes an unused layout marked as deprecated 3.2 and marked for removal with #17094

Pull Request for Issue # .

### CODE REVIEW

**Review by matrikular — APPROVED** [review]

**Comment by matrikular** [comment]
I have tested this item :white_check_mark: successfully on 27d1b7191f60169da13659aa04f6d5d36ba74944<br /><br />Couldn't find any reference to "Layout Helper::render('joomla.edit.details".<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17095">issues.joomla.org/tracker/joomla-cms/17095</a>.</sub>

**Comment by brianteeman** [comment]
as #17094 has been merged now this can be merged as well

**Comment by brianteeman** [comment]
RTC?

**Comment by ghost** [comment]
RTC as stated above.

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
