### PR TITLE
[4.0] Fix database name validation for MySQL in installation app

### PR DESCRIPTION
**Pull request by SniperSister**
Pull Request for Issue #23041 .

### Summary of Changes
Moved the generic "does the database name start with a letter"-check into a more specific condition, where it's connected with postgresql. For MySQL, a more generic check is implemented (no \ / . characters allowed).

### Testing Instructions
Try to install Joomla into a database that starts with a number as first character. You'll get an error. Apply the patch and retry, the error is now gone.

### Expected result
Works

### Actual result
Error is thrown

### Documentation Changes Required
None

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on b4bad80690db5535b930c57f367a705556aa3604<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23704">issues.joomla.org/tracker/joomla-cms/23704</a>.</sub>

**Comment by wojsmol** [comment]
@SniperSister Please make dron happy.

**Comment by flo1212** [comment]
No, the problem is not solved für mysql/mysqli
The same patch must also be in this file:
installation/src/model/SetupModel.php
Line 330

**Comment by flo1212** [comment]
No, the problem is not solved für mysql/mysqli
The same patch must also be in this file:
installation/src/model/SetupModel.php
Line 330

**Comment by chmst** [comment]
I have tested this item :red_circle: unsuccessfully on 88a7cf6447eac387b8402670ecfed2dd3cf5f08d<br /><br />I am working in a local environment using xampp and MariaDB. Here it is not necessary to install a new database, the installer uses to install it. Here the rule is still active. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23704">issues.joomla.org/tracker/joomla-cms/23704</a>.</sub>

**Comment by SniperSister** [comment]
@flo1212 @chmst I updated the PR accordingly, please retest

**Comment by flo1212** [comment]
I have testet this patch [0df73fb](https://github.com/joomla/joomla-cms/pull/23704/commits/0df73fb23d17ca33211029b21e6e1c08ff01d3b4) successfully

**Comment by ghazal** [comment]
I have tested this item :white_check_mark: successfully on 0df73fb23d17ca33211029b21e6e1c08ff01d3b4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23704">issues.joomla.org/tracker/joomla-cms/23704</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 0df73fb23d17ca33211029b21e6e1c08ff01d3b4<br /><br />Successful with xampp, Maridb, win10. 
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23704">issues.joomla.org/tracker/joomla-cms/23704</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 0df73fb23d17ca33211029b21e6e1c08ff01d3b4<br /><br />Successful with xampp, Maridb, win10. 
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23704">issues.joomla.org/tracker/joomla-cms/23704</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23704">issues.joomla.org/tracker/joomla-cms/23704</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by wilsonge** [comment]
@SniperSister We need to adapt the com_config filter to use this too please

**Pull request merged**
