### PR TITLE
[4.0] Move custom fields from submenu to main menu in contact

### PR DESCRIPTION
**Pull request by bembelimen**
### Summary of Changes
At the moment the custom fields are in the submenu for contact. With this PR The two submenu items are moved to the main menu like in the other extensions.

### Testing Instructions
- Apply patch
- Reinstall Joomla!
- Check menu items for contact
- disable/enable custom fields for contact to check display/hide

### CODE REVIEW

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 1846d32ba96af993b00d28fb43b25014ed18fdfb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23366">issues.joomla.org/tracker/joomla-cms/23366</a>.</sub>

**Comment by Hackwar** [comment]
I have tested this item :white_check_mark: successfully on 1846d32ba96af993b00d28fb43b25014ed18fdfb<br /><br />Tested successfully. We shouldd really merge in the testing sample data plugin and drop the SQL files.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23366">issues.joomla.org/tracker/joomla-cms/23366</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23366">issues.joomla.org/tracker/joomla-cms/23366</a>.</sub>

**Comment by brianteeman** [comment]
can you fix the conflicts please

**Comment by brianteeman** [comment]
@bembelimen can you fix the conflicts please and then we can get this merged

**Comment by wilsonge** [comment]
Removing rtc until conflicts are fixed. Mainly just to avoid me re-reading this PR every 2 weeks when I go through the RTC pile. Whenever they are fixed someone can mark this back as RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23366">issues.joomla.org/tracker/joomla-cms/23366</a>.</sub>

**Comment by brianteeman** [comment]
@bembelimen please can you fix the conflicts

**Comment by brianteeman** [comment]
I tried to test this with the view to resolving the conflicts and submitting it as a new pr but it is not a correct PR or the code required has changed since this was created

1. disable/enable custom fields for contact to check display/hide
This had no effect

2. The separator between contacts and fields is not rendered correctly
```<li class="divider" role="presentation"><a class="no-dropdown" href="#"><span class="sidebar-item-title"></span></a></li>```
Should be
```<li class="divider" role="presentation"><span></span></li>```
Otherwise it becomes a clickable and focusable item

**Comment by ghost** [comment]
Please resolve conflicting files so this PR can get tested at Worldwide Pizza, Bugs & Fun, October 19th

**Comment by brianteeman** [comment]
Found the reason that
disable/enable custom fields for contact to check display/hide did not work

The value for the component_id in the sql was 33 - it should be the id of the com_fields component in the extensions table which is 30

**Comment by brianteeman** [comment]
@bembelimen has obviously abandoned this important PR so if one of the sql gurus could create a new pr that would be awesome and then people will be able to create fields for com_contacts again

cc / @alikon @richard67 @quy

**Comment by alikon** [comment]
please test #26540

**Pull request closed without merging**
