### PR TITLE
[5.1] Use Dialog for scheduler task "Run test"

### PR DESCRIPTION
**Pull request by Fedik**
### Summary of Changes

Use Dialog for scheduler task run

### Testing Instructions
Run `npm install`
Go to "Scheduled Tasks" page, and run any existing task.

### Actual result BEFORE applying this Pull Request
Works with BS Modal

### Expected result AFTER applying this Pull Request
Works with Joomla Dialog

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed
- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

References:

- https://github.com/joomla/joomla-cms/pull/40150

### CODE REVIEW

**Comment by fgsw** [comment]
I have tested this item :white_check_mark: successfully on 3cd7dd7436b6fa3bbe3445a95b7fe9ee9ef6b72f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42746">issues.joomla.org/tracker/joomla-cms/42746</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 3cd7dd7436b6fa3bbe3445a95b7fe9ee9ef6b72f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42746">issues.joomla.org/tracker/joomla-cms/42746</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42746">issues.joomla.org/tracker/joomla-cms/42746</a>.</sub>

**Comment by LadySolveig** [comment]
Thank you @Fedik and also for testing @fgsw @viocassel

**Pull request merged**
