### PR TITLE
[4.0] remove extra spaces

### PR DESCRIPTION
**Pull request by brianteeman**
Spotted while checking something else. Can be merged on review

### CODE REVIEW

**Comment by wojsmol** [comment]
I have tested this item :white_check_mark: successfully on f58cba4ea1f7d9f6905e4433d2170e3197bc184e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35695">issues.joomla.org/tracker/joomla-cms/35695</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on f58cba4ea1f7d9f6905e4433d2170e3197bc184e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35695">issues.joomla.org/tracker/joomla-cms/35695</a>.</sub>

**Comment by chmst** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35695">issues.joomla.org/tracker/joomla-cms/35695</a>.</sub>

**Comment by Quy** [comment]
Thanks!

**Comment by brianteeman** [comment]
thx

**Pull request merged**
