### PR TITLE
[4.0] Remove libraries/cms/html/language/en-GB/en-GB.jhtmldate.ini

### PR DESCRIPTION
**Pull request by Bakual**
### Summary of Changes
This PR removes the language file libraries/cms/html/language/en-GB/en-GB.jhtmldate.ini.
The file isn't in a regular language folder where it could be loaded, and the strings in it are also present in the lib_joomla.ini one.

### Testing Instructions
Check the Users -> Users Action Logs view
The column "Date" uses the strings in that file.

### Expected result
image

### Actual result
Same as expected

### Documentation Changes Required
None

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on a97ca73e6fddc70dfb2c669159b03dbe6fd33b44<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23653">issues.joomla.org/tracker/joomla-cms/23653</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on a97ca73e6fddc70dfb2c669159b03dbe6fd33b44<br /><br />Weird. Wonder why we had the same situation (strings in both files) in 2.5...<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23653">issues.joomla.org/tracker/joomla-cms/23653</a>.</sub>

**Comment by infograf768** [comment]
RTC.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23653">issues.joomla.org/tracker/joomla-cms/23653</a>.</sub>

**Comment by brianteeman** [comment]
It could be being used by an extension. 
This should not be in a patch update as it would not be in accordance with semver.
Even if the logger wont pick it up it should be deprecated before removal

**Comment by Bakual** [comment]
> It could be being used by an extension.

How? You can't load this file as it is not in a supported folder. And even if that worked, the file just wouldn't be loaded but the strings are still there.
But then I don't mind if this goes into 3.x or 4.0. Just let me know when I have to rebase the PR.

**Comment by brianteeman** [comment]
If the file exists then someone can use it (even if they shouldn't or have to jump through hoops)

**Comment by Bakual** [comment]
Redone against 4.0 branch.

**Comment by mbabker** [comment]
> How? You can't load this file as it is not in a supported folder.

```php
$language->load('jhtmldate', JPATH_LIBRARIES . '/cms/html');
```

The only restriction in the language API (which I never liked but `¯\_(ツ)_/¯`) is that there must be a directory named "language" within the path you specify.  Other than that, you can put language files anywhere in the filesystem.  Whether the CMS UI supports those locations is another story.

> Wonder why we had the same situation (strings in both files) in 2.5...

When the Platform was a standalone thing it was decided to put language files into the library packages.

**Comment by Bakual** [comment]
> Other than that, you can put language files anywhere in the filesystem.

Thanks. I wasn't even aware you can do that.

**Comment by infograf768** [comment]
Restarted drone.

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
