### PR TITLE
[staging] Fix jalali calendar javascript

### PR DESCRIPTION
**Pull request by infograf768**
https://github.com/joomla/joomla-cms/issues/28698

### Summary of Changes
Adding missing return

### Testing Instructions
Switch to Persian in administrator and edit/create an article Look at the calendar fields in the Publishing tab.

I personally have not remarked any differences in the calendar but code makes sense

@balvard
Would be interested in learning what is modified in the calendar display after the patch.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 3f6edf0e2459f762236457983bbf665b765714af<br /><br />Code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28700">issues.joomla.org/tracker/joomla-cms/28700</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 3f6edf0e2459f762236457983bbf665b765714af<br /><br />Code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28700">issues.joomla.org/tracker/joomla-cms/28700</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28700">issues.joomla.org/tracker/joomla-cms/28700</a>.</sub>

**Comment by zero-24** [comment]
Merging thanks :)

**Pull request merged**
