### PR TITLE
[4.0] Add markup to move buttons to next line

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
Add markup to move buttons to next line.

### Testing Instructions
Go to Global Configuration > Installer
Change `Updates Caching (in hours)` to 0.
Go to Post Installation Messages.
See other messages where buttons are below messages.

update-notification

### CODE REVIEW

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 6f9debec2b6af784cd08e0d1efbe7a7eeb1dd82a<br /><br />Work as expected.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29368">issues.joomla.org/tracker/joomla-cms/29368</a>.</sub>

**Comment by C-Lodder** [comment]
You should really avoid adding HTML to the language files

**Comment by Quy** [comment]
Yes, however, other strings already have markup. For example:

https://github.com/joomla/joomla-cms/blob/5e137dbf254da94d605fe39ea0b68f0fe1f60f64/administrator/language/en-GB/com_cpanel.ini#L23

**Comment by Quy** [comment]
How to do the following without markup?

stats

**Comment by wilsonge** [comment]
Given it makes things consistent good enough for me

**Pull request merged**
