### PR TITLE
[3.x] Update registration.php

### PR DESCRIPTION
**Pull request by brianteeman**
Send mail to all administrators with access to com_users and set to receive system emails instead of sending the mail to all users with "receive system emails"

Please test very carefully with all 3 user registration options

### CODE REVIEW

**Comment by coolcat-creations** [comment]
Tested unsuccessful

My steps:

Using my own website I created two users

1) Testuser1, registered, system mails enabled
2) Testuser2, registered, system mails disabled

I set the "Send Mail to Administrators" Option in the User Options to yes

I registered from the Frontend with a new user
Newuser1

- The Administrator got an email
- The registered user with system mails enabled got an email


I downloaded the prebuilt package [Joomla_3.10.5_to_3.10.6-rc2-dev+pr.36993-Development-Patch_Package.zip](https://ci.joomla.org/artifacts/joomla/joomla-cms/3.10-dev/36993/downloads/51603/Joomla_3.10.5_to_3.10.6-rc2-dev+pr.36993-Development-Patch_Package.zip) and updated Joomla with it.

I registered from the Frontend with a new user
Newuser2

- The Administrator got an email
- The registered user with system mails enabled got an email

**Comment by brianteeman** [comment]
Could you check the other options as well please

**Comment by brianteeman** [comment]
image

I may have missed one

**Comment by coolcat-creations** [comment]
Tested now with:

Self - Failed
None - Failed
Administrator - Success

**Comment by brianteeman** [comment]
and can you confirm you had three fail before?

**Comment by coolcat-creations** [comment]
I tested now the other two options without the patch and its the same. 

Self - Users with no Admin rights get the mail
None - Users with no Admin rights get the mai
Administrator - Only Admin gets the mail

**Comment by brianteeman** [comment]
ok I will take a real look. I only tested it on j4 so probably made a mistake when just typing it into j3

**Comment by coolcat-creations** [comment]
Thank you. Could there be something wrong with the prebuilt package, can I use it as an update like I did?

**Comment by brianteeman** [comment]
no - its more likely to be me

**Comment by brianteeman** [comment]
please try #36997

**Comment by RickR2H** [comment]
Open en closed to try fix issues with the issue tracker

**Pull request closed without merging**
