### PR TITLE
Build query only if 'select' and 'from' attributes are set and don't execute blank query

### PR DESCRIPTION
**Pull request by izharaazmi**
#### Summary of Changes

The new implementation of `JFormFieldSQL` that supports Joomla query builder format should not generate any query if the parameters are not sufficient in the field element. However it builds a blank query `SELECT FROM` anyway that causes error.
#### Testing Instructions

Load a form with following field definition (note the missing `query` attribute):

``` xml
<field
    name="sql_test"
    type="sql"
>
    <option value="none">None</option>
</field>
```

Without this patch there is a mysql error.
After patch there is a list with single option taken from xml definition only.

### CODE REVIEW

**Comment by izharaazmi** [comment]
There is a single test case defined for this class. Where and how should I add another failing test case? Please advise.

**Comment by izharaazmi** [comment]
Can we have some test here please.

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 83ad277911131b034e10976e6260bc687994acae<br /><br />Followed test instructions and works as described.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10087">issues.joomla.org/tracker/joomla-cms/10087</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
@izharaazmi shouldn't this PR be updatet cause Installation shows 3.6-Design?

**Comment by izharaazmi** [comment]
Pardon me. I didn't get you.

**Comment by franz-wohlkoenig** [comment]
sorry, i would ask: Can i test this PR on these Settings:
### System information
3.7.3-dev (latest nightly build)
Multilanguage Site
macOS Sierra, 10.12.5
Firefox 53 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by coolcat-creations** [comment]
I have tested this item :red_circle: unsuccessfully on 83ad277911131b034e10976e6260bc687994acae<br /><br />Tested unsuccessfully on latest staging.
- In Custom Fields
- In Article View override<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10087">issues.joomla.org/tracker/joomla-cms/10087</a>.</sub>

**Comment by coolcat-creations** [comment]
I have tested this item :white_check_mark: successfully on 83ad277911131b034e10976e6260bc687994acae<br /><br />Sorry i tested wrong... 
test successful.

It breaks in Custom Fields when you build a query "SELECT FROM" - but i guess it´s another issue<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10087">issues.joomla.org/tracker/joomla-cms/10087</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
@coolcat-creations can you please open an Issue about "breaks custom Fields"?

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Comment by rdeutz** [comment]
@izharaazmi can you have a look at the conflicts, thanks

**Comment by izharaazmi** [comment]
@mbabker I just noticed the 'conflicting-files' label here and now the conflict is resolved. Please check whether we need tests again before merge?

**Comment by zero-24** [comment]
I have just removed the label

**Pull request merged**
