### PR TITLE
[4.0] Move to updated flying-focus package

### PR DESCRIPTION
**Pull request by C-Lodder**
### Summary of Changes

I've moved the forked flying-focus repo into a new one and started utilising grunt.
This PR simply replaces the old package with the new one

### CODE REVIEW

**Comment by C-Lodder** [comment]
@wilsonge conflicts fixed. Please merge when possible

**Comment by dgrammatiko** [comment]
@C-Lodder can we instead of this sugar-on-broken-system actually implement something meaningful: https://github.com/joomla/joomla-cms/pull/15906

I mean by default bootstrap *is really bad* for accessibility on all their buttons, so one way or another we need to fix it, so why not use CSS4 a little bit earlier?

**Comment by C-Lodder** [comment]
I don't really mind what gets used tbh

**Comment by brianteeman** [comment]
flyingfocus was much more than just the outline

**Comment by dgrammatiko** [comment]
@brianteeman what do you mean? Flying focus is a visual effect on top of the focus ring, what else was there?

**Comment by brianteeman** [comment]
it does the flying part - the transition - which is very useful to indicate where the focus has been moved to without having to search the screen for just the outline

**Comment by dgrammatiko** [comment]
Ok, so it's just the visual effect, which might not be that inclusive after all (for those with good vision the effect is a nice hint, but I guess for some visually impaired people the animation might be really annoying or not even visible). Anyways I'm not against flying focus **if** we first implement the css4 focus-ring (with the provided polyfill ATM)

**Comment by brianteeman** [comment]
if it is good enough for webaim.org then it should be good enough for joomla ;)

**Comment by dgrammatiko** [comment]
I guess webaim.org is not using Bootstrap (which totally messes the focus ring). So in fact my proposal for css4 focus ring is more a patch to this annoying approach of BS4's `outline: 0;` and you can still have the sugar (effect) on top of it, if that is needed

**Comment by brianteeman** [comment]
I dont know why this was closed. The fix is required

**Comment by C-Lodder** [comment]
I closed this in favour of a better approach

**Pull request closed without merging**
