### PR TITLE
Namespace punicode

### PR DESCRIPTION
**Pull request by laoneo**
Namespaces the punicode class and is deprecating the wrappers. The classmap helper section got reordered to be inline with the filesystem.

### CODE REVIEW

**Comment by mbabker** [comment]
I don't see why this is moving to the helper namespace instead of staying in a string namespace, other than that seems fine.

**Comment by laoneo** [comment]
For me it looks like one of this gazillion helper classes we have in core which has only static functions. That's why I put it into the helper folder.

**Comment by wilsonge** [comment]
All of String is static. I'm with Michael on this - it belongs with the string package

**Comment by laoneo** [comment]
Done.

**Pull request merged**
