### PR TITLE
[4.0] Remove duplicate scss lines for form stylings

### PR DESCRIPTION
**Pull request by eyvazahmadzada**
Pull Request for Issue #33829 .

### Intro
Hello, I'm one of the applicants for GSoC 2021 for the **Media Manager** project and I'm glad to start contributing to Joomla by creating a pull request for this small issue.

### Summary of Changes
Removed stylings from line 78-108 in /administrator/templates/atum/scss/blocks/_form.scss

### Testing Instructions
Go to any page that contains a form (for example Administrator > Articles > New > Images and Links) and everything will work normally.

### Actual result BEFORE applying this Pull Request
Duplicate scss code in /administrator/templates/atum/scss/vendor/bootstrap/_form.scss (from line 18-48) and in /administrator/templates/atum/scss/blocks/_form.scss (from line 78-108)

### Expected result AFTER applying this Pull Request
No duplicate stylings

### CODE REVIEW

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on 9753763582f9891bc9007d828a9516c88d9e279a<br /><br />To test I searched template.css before and after npm run build:css and saw the duplicate styles disappear.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33834">issues.joomla.org/tracker/joomla-cms/33834</a>.</sub>

**Comment by YatharthVyas** [comment]
I have tested this item :white_check_mark: successfully on 9753763582f9891bc9007d828a9516c88d9e279a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33834">issues.joomla.org/tracker/joomla-cms/33834</a>.</sub>

**Comment by drmenzelit** [comment]
Thank you @eyvazahmadzada for your contribution. You need to check the classes before removing the duplicates: if a class is a Bootstrap class (e.g. `form-check`) a override of the class should be in the file `administrator/templates/atum/scss/vendor/bootstrap/_form.scss`, if the class is specific for Atum, the class should be in `administrator/templates/atum/scss/blocks/_form.scss`. At least that is the logic I would expect from the scss files in the template.

**Comment by eyvazahmadzada** [comment]
> Thank you @eyvazahmadzada for your contribution. You need to check the classes before removing the duplicates: if a class is a Bootstrap class (e.g. `form-check`) a override of the class should be in the file `administrator/templates/atum/scss/vendor/bootstrap/_form.scss`, if the class is specific for Atum, the class should be in `administrator/templates/atum/scss/blocks/_form.scss`. At least that is the logic I would expect from the scss files in the template.

Yes, you're right, that makes more sense. I've made a new commit to place stylings in their appropriate file.

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on e84d2d91e4a55eba6a7a06aa95ff3f6eb00758f9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33834">issues.joomla.org/tracker/joomla-cms/33834</a>.</sub>

**Pull request closed without merging**
