### PR TITLE
[4.1] c/matchs/matches

### PR DESCRIPTION
**Pull request by brianteeman**
typo & code quality

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 4e6dcd281f356aa9a4b42429003ef1012624e9ce<br /><br />@bembelimen Could be merged by review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36845">issues.joomla.org/tracker/joomla-cms/36845</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 4e6dcd281f356aa9a4b42429003ef1012624e9ce<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36845">issues.joomla.org/tracker/joomla-cms/36845</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36845">issues.joomla.org/tracker/joomla-cms/36845</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
