### PR TITLE
Correct SQL error when deleting banner tracks on PostgreSQL databases

### PR DESCRIPTION
**Pull request by richard67**
Pull Request for Issue #24679 .

### Summary of Changes

Correct the initial where clause so it resolves to a boolean true on every kind of SQL database before other conditions are concatenated with " AND ...".

### Testing Instructions

See issue #24679 + some testers with MySQL database test if things work like before.

### Documentation Changes Required

None.

### CODE REVIEW

**Comment by twister65** [comment]
I have tested this item :white_check_mark: successfully on 8bdcadbd11f2099506195a5f9f6b371fa67c3f2c<br /><br />Successfully tested with PostgreSQL and MySQL databases.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24682">issues.joomla.org/tracker/joomla-cms/24682</a>.</sub>

**Comment by richard67** [comment]
Drone failure not related to this PR. Is caused by javascript stuff.

**Comment by zero-24** [comment]
Lets see whether drone gets happy now ;)

**Comment by richard67** [comment]
@zero-24 Can you also set back the result of twister65's test?

**Comment by richard67** [comment]
Now drone succeeded, but Travis failed for reasons not related to this PR.

**Comment by zero-24** [comment]
Re startet travis https://travis-ci.org/joomla/joomla-cms/builds/523027749

**Comment by zero-24** [comment]
CI is happy now merging on review. Thanks.

**Comment by richard67** [comment]
Thanks.

**Comment by richard67** [comment]
And thanks to @twister65 who found the mistake.

**Pull request merged**
