### PR TITLE
[4.0] Mail templates

### PR DESCRIPTION
**Pull request by brianteeman**
Two strings were the wrong way around

Config should say "Allow ..."

Not the individual template

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 053687134f3a7934b7f22e73a160a943cd1a87ad<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26471">issues.joomla.org/tracker/joomla-cms/26471</a>.</sub>

**Comment by bembelimen** [comment]
I have tested this item :white_check_mark: successfully on 053687134f3a7934b7f22e73a160a943cd1a87ad<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26471">issues.joomla.org/tracker/joomla-cms/26471</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26471">issues.joomla.org/tracker/joomla-cms/26471</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
