### PR TITLE
[4.1] Proper cache invalidation for css urls

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue #32573 (partially) .

### Summary of Changes
- Adds one more PostCSS plugin https://www.npmjs.com/package/postcss-url-version
- Adjust the 2 scripts to use the above plugin

### Testing Instructions
Make a copy of the media and also the `css` folder of cassiopeia, atum and installtion
On this PR's code you need to run `npm install`
Then compare the produced css with the one you've backup before for example: search for `url(`, The new css files should have someting like `?v=13423-random-alphanumeric` at the end (only for local images/fonts)  

### Actual result BEFORE applying this Pull Request
Urls don;t have a hash

### Expected result AFTER applying this Pull Request
Urls have a hash

Screenshot 2021-03-03 at 16 33 38

### Documentation Changes Required
No

One comment here, although at the original issue I mentioned another plugin there were bugs and also it's abandoned for some years. (I didn't either wanted to write a plugin, ok less than 100locs, but still)

@wilsonge is this ok for 4.0.x or should I rebase it to 4.0.x?

### CODE REVIEW

**Comment by alikon** [comment]
please fix conflict

**Comment by dgrammatiko** [comment]
@alikon done

**Comment by socke300** [comment]
I have tested this item :white_check_mark: successfully on 0977e1e948d8e2093ef0b3e82a43d140878ca949<br /><br />

## First of all

Hey, it's cool that you developed the plugin "postcss-url-version" yourself and have now integrated it into Joomla.



## That's how I tested it

I cloned your project and installed it. Then I went through various css files and also checked whether the version number changes depending on the URL.



## These files were checked

fontawesome.min.css
template.min.css (in the "Home Dashboard" view)



## Result

The test was successful, I did not notice any problems during the test. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32574">issues.joomla.org/tracker/joomla-cms/32574</a>.</sub>

**Comment by scout507** [comment]
I have tested this item :white_check_mark: successfully on 0977e1e948d8e2093ef0b3e82a43d140878ca949<hr />

Checked all css files. Hash values were applied correctly.

<sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32574">issues.joomla.org/tracker/joomla-cms/32574</a>.</sub>

**Comment by richard67** [comment]
@dgrammatiko We have again a conflict here in the package-lock.json.

**Comment by dgrammatiko** [comment]
@socke300 @scout507 can you repeat your tests?

Thanks

**Comment by dgrammatiko** [comment]
@bembelimen something for 4.1?

**Comment by bembelimen** [comment]
Yes, if we get the two tests, for sure it's something for 4.1

**Comment by dgrammatiko** [comment]
@bembelimen I rebased on 4.1 and fixed the conflicts, this should be ready for testing again

**Comment by dgrammatiko** [comment]
@bembelimen is there any chance to get this for 4.1?

**Comment by bembelimen** [comment]
@dgrammatiko it's still valid for 4.1(.1), we just need some tests, probably the @joomla/bug-squad can help with it?

**Comment by dgrammatiko** [comment]
I will re open this after the 4.1 release

**Pull request closed without merging**
