### PR TITLE
Cassiopeia template - changing Tagline to Tagline - Optional text to show as a subheading parameter - ALTERNATIVE (35720)

### PR DESCRIPTION
**Pull request by PhocaCz**
This is an alternative for following request: https://github.com/joomla/joomla-cms/pull/35720

### CODE REVIEW

**Comment by PhilETaylor** [comment]
9 security insights?

**Comment by PhocaCz** [comment]
> 9 security insights?

Sorry, I don't understand.

**Comment by PhilETaylor** [comment]
That was in the title of the PR when it was opened and emailed 

image

**Comment by PhocaCz** [comment]
Now I understand, this was some copy/paste error. Now fixed.

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 69ecc1ca8eeabf342eb9710ffcac835b2bc4de73<br /><br />For me it doesn't matter whether: tagline or description. But CSS belong to site-description: 
```
.container-header .site-description {
    font-size: 1rem;
    color: #fff;
    white-space: normal;
}
```
```
<div class="site-description">Hier kann ein Text stehen</div>
```

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35729">issues.joomla.org/tracker/joomla-cms/35729</a>.</sub>

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on 69ecc1ca8eeabf342eb9710ffcac835b2bc4de73<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35729">issues.joomla.org/tracker/joomla-cms/35729</a>.</sub>

**Comment by RickR2H** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35729">issues.joomla.org/tracker/joomla-cms/35729</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35729">issues.joomla.org/tracker/joomla-cms/35729</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
