### PR TITLE
[4.0] Change .center to .text-center

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
`center` is not a valid class. Use `text-center`.

### Testing Instructions
Code review.

### CODE REVIEW

**Comment by grantg182** [comment]
I have tested this item :red_circle: unsuccessfully on 91af993755844ef06e59d8a21461937975698a44<br /><br />"text-center" is a Bootstrap helper class which only works on "display: inline" elements, in both Bootstrap 3 and 4. I don't see how this fixes the fundamental issue here because Bootstrap is not a front-end requirement. Furthermore, I suspect the actual problem with this code is the fact it is using "class" and not "align" (i.e. <td align="center"> was probably the intention) as per some dinosaur HTML spec.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29044">issues.joomla.org/tracker/joomla-cms/29044</a>.</sub>

**Comment by Quy** [comment]
This PR changes administration files only where Bootstrap 4 is allowed and applies to table cells. Please don't assume and actually test.

**Comment by richard67** [comment]
@Quy I have reset the test result of @grantg182 to "Not tested" in the issue tracker, since it was definitely not a valid test but just a statement based on wrong assumptions.

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on 91af993755844ef06e59d8a21461937975698a44<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29044">issues.joomla.org/tracker/joomla-cms/29044</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 91af993755844ef06e59d8a21461937975698a44<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29044">issues.joomla.org/tracker/joomla-cms/29044</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29044">issues.joomla.org/tracker/joomla-cms/29044</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 91af993755844ef06e59d8a21461937975698a44<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29044">issues.joomla.org/tracker/joomla-cms/29044</a>.</sub>

**Pull request merged**
