### PR TITLE
[5.0] Updating joomla/filesystem to fix File::write() issue

### PR DESCRIPTION
**Pull request by Hackwar**
Pull Request for Issue #40503.

### Summary of Changes
This fixes the issue from #40503 by applying the fix that was made in the CMS 6 years ago to the framework as well... For reference: https://github.com/joomla/joomla-cms/pull/11952
I applied that fix to the framework package and now the CMS needs to update its dependencies to pull those new changes. The fix for 4.4-dev will be upmerged sometime soon, I guess.

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on aff15fa6e0848a692208f06a82c18eabf4c2b639<br /><br />**Important hint for other testers:**

When having done the test without the patch to reproduce the issue, you should either delete the session cookie with your broswer's developer tools or close the browser window to make sure that the browser session is cleared before testing the patch.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40515">issues.joomla.org/tracker/joomla-cms/40515</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on aff15fa6e0848a692208f06a82c18eabf4c2b639<br /><br />With Prebuilt Package<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40515">issues.joomla.org/tracker/joomla-cms/40515</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40515">issues.joomla.org/tracker/joomla-cms/40515</a>.</sub>

**Comment by HLeithner** [comment]
Thx

**Pull request merged**
