### PR TITLE
[5.0] core extensions remove captcha plugins

### PR DESCRIPTION
**Pull request by heelc29**
Pull Request for Issue https://github.com/joomla/joomla-cms/pull/41530#issuecomment-1699616466 .

### Summary of Changes

> It should the also be removed from the list of core extensions in the ExtensionsHelper

### Testing Instructions

update from 4.4 to 5.0 nightly and check core extensions
image

### Actual result BEFORE applying this Pull Request

captcha plugin(s) are still listed as core extension

### Expected result AFTER applying this Pull Request

captcha plugins are no longer listed as core extension

### Link to documentations
Please select:
- [x] No documentation changes for docs.joomla.org needed
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Review by richard67 — APPROVED** [review]

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on a6d3a4e9cf28ff5e5ab93c6659596a8845052a60<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41563">issues.joomla.org/tracker/joomla-cms/41563</a>.</sub>

**Comment by ChristineWk** [comment]
After installation of a clean Joomla 4.4 & Patchtester I had both captchas.

After update to 5.0.0-beta1-dev the result is now:
recaptcha is uninstalled, 
invisible one is unlocked 
Is that correct?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41563">issues.joomla.org/tracker/joomla-cms/41563</a>.</sub>

**Comment by heelc29** [comment]
> Is that correct?

Yes

**Comment by richard67** [comment]
> > Is that correct?
> 
> Yes

Yes

**Comment by ChristineWk** [comment]
than it's OK. I thought both should gone.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41563">issues.joomla.org/tracker/joomla-cms/41563</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on a6d3a4e9cf28ff5e5ab93c6659596a8845052a60<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41563">issues.joomla.org/tracker/joomla-cms/41563</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41563">issues.joomla.org/tracker/joomla-cms/41563</a>.</sub>

**Comment by HLeithner** [comment]
thx

**Pull request merged**
