### PR TITLE
Banner filter order

### PR DESCRIPTION
**Pull request by brianteeman**
#### Summary of Changes

Changed the order of the filters for banners to match the order of the columns below to be consistent with all other filters

### CODE REVIEW

**Comment by MATsxm** [comment]
I have tested this item :white_check_mark: successfully on d886722f64f670c16b8df56ead41863571d6b4f7<br /><br />Right order now - Thanks

**for Articles?** <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9862">issues.joomla.org/joomla-cms/9862</a>.</sub>

**Comment by brianteeman** [comment]
@MAT978  I did articles just for you ;)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9862">issues.joomla.org/joomla-cms/9862</a>.</sub>

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on d886722f64f670c16b8df56ead41863571d6b4f7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9862">issues.joomla.org/joomla-cms/9862</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9862">issues.joomla.org/joomla-cms/9862</a>.</sub>

**Pull request merged**
