### PR TITLE
[4.0] Replace input with button

### PR DESCRIPTION
**Pull request by C-Lodder**
### Summary of Changes

Use an actual button for the "login button", rather than an input.

### Testing Instructions

Make sure you can still logout via `mod_login`

### CODE REVIEW

**Comment by brianteeman** [comment]
probably should be changed in the three other places as well

**Comment by C-Lodder** [comment]
@brianteeman Only found two other references to `input type="submit"` in the whole repo. Could you let me know where the third is, so I can change it?

**Comment by brianteeman** [comment]
It was in a js script

**Comment by C-Lodder** [comment]
Only one I can see is in `core.js`, but that's a hidden input.

**Comment by brianteeman** [comment]
my bad - i missed that it was hidden

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 2804424b7f18bfc16d7dadc112dcac04796366f5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36386">issues.joomla.org/tracker/joomla-cms/36386</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 2804424b7f18bfc16d7dadc112dcac04796366f5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36386">issues.joomla.org/tracker/joomla-cms/36386</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36386">issues.joomla.org/tracker/joomla-cms/36386</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
