### PR TITLE
Isis: Navbar dropdowns are now scrollable

### PR DESCRIPTION
**Pull request by C-Lodder**
This is a Pull Request for the initial start that @brianteeman made here https://github.com/joomla/joomla-cms/pull/9347

Same testing instructions apply

This PR includes RTL support and solves the issue with 3rd level submenus being cropped

### CODE REVIEW

**Comment by brianteeman** [comment]
I seem to have an issue with the position of the submenu screen shot 2016-03-11 at 11 32 45<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9375">issues.joomla.org/joomla-cms/9375</a>.</sub>

**Comment by C-Lodder** [comment]
Hmm, ok, I'll look into this over the weekend

**Comment by infograf768** [comment]
Another small glitch in RTL (double box):

screen shot 2016-03-12 at 08 47 17

**Comment by C-Lodder** [comment]
@brianteeman - I've fixed the left offset issue you mentioned.
@infograf768 - Fixed the RTL issue

**Comment by ot2sen** [comment]
Applied patch to latest stating. The scroll effect doesn´t appear.
j35_scroll_menu_after

**Comment by C-Lodder** [comment]
@ot2sen - This was only supposed to be for the "Components" dropdown.

@brianteeman - Does this need to be applied to all dropdowns?

**Comment by ot2sen** [comment]
Perhaps it only is for the Components menu as the title says? Tested the menus menu, which would have same issue often :)

**Comment by infograf768** [comment]
We also need it indeed for other dropdowns. The menus one is very important.

**Comment by brianteeman** [comment]
@C-Lodder yes it will need to be for all menus (well actually just the menu and components but might as well make it for all)

**Comment by C-Lodder** [comment]
Okies, fixing it up now

**Comment by C-Lodder** [comment]
Applied to all dropdowns

**Comment by ot2sen** [comment]
I have tested this item :white_check_mark: successfully on 85278b90bcf627cee30ba62ee90016c6a5a83a42<br /><br />Tested successful with latest patch. Menu now scrollable<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9375">issues.joomla.org/joomla-cms/9375</a>.</sub>

**Comment by ot2sen** [comment]
Thanks @C-Lodder  works now :)
j35_scroll_menu_new_after_ok

**Comment by C-Lodder** [comment]
@ot2sen - There was a slight issue which is now fixed. If you to go "Extensions" >> "Manage" the dropdown a scrollbar will be added to the dropdown. This was caused by the origin `<ul>` element still technically there. This has been fixed with: https://github.com/joomla/joomla-cms/commit/f18c4560c7c40dbc1139831aac5c3342f3b2322a

**Comment by ot2sen** [comment]
I have tested this item :white_check_mark: successfully on f18c4560c7c40dbc1139831aac5c3342f3b2322a<br /><br />Retested with fix for extensions manage. That extra scrollbar is now gone and the intended scrollbars is a menus.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9375">issues.joomla.org/joomla-cms/9375</a>.</sub>

**Comment by MATsxm** [comment]
I have tested this item :white_check_mark: successfully on f18c4560c7c40dbc1139831aac5c3342f3b2322a<br /><br />This is just fabulous and a real improvement!

Thanks all and of course @C-Lodder <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9375">issues.joomla.org/joomla-cms/9375</a>.</sub>

**Comment by brianteeman** [comment]
Working great - do you think there should be some sort of visual indicator at the end of the column to indicate there is more if you scroll?
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9375">issues.joomla.org/joomla-cms/9375</a>.</sub>

**Comment by C-Lodder** [comment]
@brianteeman - I like to think they people have at least _some_ common sense and know what a scroll bar is for :) 

I can add otherwise though

**Comment by brianteeman** [comment]
You only see the scollbar when you over over the menu itself. If you only
click on Menu (or) Component then the scrollbar does not appear so you dont
know the list is truncated

On 14 March 2016 at 16:14, Lodder <notifications@github.com> wrote:

> @brianteeman <https://github.com/brianteeman> - I like to think they
> people have at least *some* common sense and know what a scroll bar is
> for :)
>
> I can add otherwise though
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/9375#issuecomment-196389149>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
In this screencapture the scrollbar ONLY appears when i try to scroll. Moving up and down or even oving to the end of the menu doesnt indicate there is anything to scroll to 

dropdown-menu-bug

**Comment by C-Lodder** [comment]
@brianteeman - Oh sorry, that's a Safari feature isn't it?

Could you try adding the following to the template.css file:

```
.navbar .nav > li ul::-webkit-scrollbar {
    -webkit-appearance: none;
    width: 7px;
}
.navbar .nav > li ul::-webkit-scrollbar-thumb {
    border-radius: 4px;
    background-color: rgba(0,0,0,.5);
    -webkit-box-shadow: 0 0 1px rgba(255,255,255,.5);
}
```

**Comment by brianteeman** [comment]
Thats perfect- a scrollbar is permanently displayed if there is a scroll available

**Comment by C-Lodder** [comment]
@brianteeman - Applied

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 284ebd1bd30059c95e36172ca148c8f1bf0cb4ba<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9375">issues.joomla.org/joomla-cms/9375</a>.</sub>

**Comment by Gerlof** [comment]
I have tested this item :white_check_mark: successfully on 284ebd1bd30059c95e36172ca148c8f1bf0cb4ba<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9375">issues.joomla.org/joomla-cms/9375</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9375">issues.joomla.org/joomla-cms/9375</a>.</sub>

**Comment by Djshubh** [comment]
I have tested this item :white_check_mark: successfully on 284ebd1bd30059c95e36172ca148c8f1bf0cb4ba<br /><br />the scrollbar works for small screens too.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9375">issues.joomla.org/joomla-cms/9375</a>.</sub>

**Pull request merged**
