### PR TITLE
Fixing validation of emails by changing 'error-handling' in EmailRule.php (related to 26637)

### PR DESCRIPTION
**Pull request by sebenns**
Pull Request for Issue #26637.

### Summary of Changes
Good evening/night. I wanted to go to bed 2 or 3 hours ago, now I am here. 
I started to work on the issue #26637. First of all I thought it's just a small change in the request.xml of the com_privacy module, until I determine that this wasn't the case.

After switching from class to class I got into the validate() method of the FormModel, afterwards into the validate() method of [FormField](https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/Form/FormField.php#L1117). Here I found the 'testing' rules part which got packed into a try catch block.

Tl;dr in conclusion: I changed `return` statements to `throw` statements in the [EmailRule](libraries/src/Form/Rule/EmailRule.php) for fitting into the try catch block of FormField.php, which catches these exceptions. Other rules are doing that as well as far as I could observe.

### Testing Instructions

Thats the awesome part: It's working everywhere, where you have to test if an email address is valid.

You can test it like this (#26637 ):

1. open your admin control panel
2. navigate to `users` -> `privacy` -> `requests`
3. press `new` on the top left
4. enter a non valid e-mail address
5. save&close it.

### Expected result

image

### Documentation Changes Required

I added a `throw` paragraph. Hope that's enough for that.

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 71b13d97f47adbc1e2cb9461453a06ffc8892e7d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26810">issues.joomla.org/tracker/joomla-cms/26810</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 401ceb51f0f22ddb585fea90f9e9b8f038673971<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26810">issues.joomla.org/tracker/joomla-cms/26810</a>.</sub>

**Comment by richard67** [comment]
@datsepp Good catch 👍 Only the introduction of the summary of changes reads a bit long at the beginning 😛

**Comment by richard67** [comment]
@Quy RTC please.

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26810">issues.joomla.org/tracker/joomla-cms/26810</a>.</sub>

**Comment by deepa-g** [comment]
I have tested this item :white_check_mark: successfully on 77a71a76c178648fc6e684acb50cedacfb037376<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26810">issues.joomla.org/tracker/joomla-cms/26810</a>.</sub>

**Comment by rajnish-dargan** [comment]
I have tested this item :white_check_mark: successfully on 77a71a76c178648fc6e684acb50cedacfb037376<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26810">issues.joomla.org/tracker/joomla-cms/26810</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
