### PR TITLE
custom fields html rendering not the same

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for #16594

This is the code of @ced1870 as he doesnt appear to be submitting his own code as a PR

### CODE REVIEW

**Comment by laoneo** [comment]
Is this not a revert of #15968? Ping @matrikular.

**Comment by brianteeman** [comment]
I don't know? It's not !y code I am just trying to clean the teacker

**Comment by ghost** [comment]
Thanks for cleaning, @brianteeman

**Comment by matrikular** [comment]
Thanks @laoneo 
It seems that way, yes.

As far as I can tell by looking at the issue / proposed code, I will probably create another PR for it, as the solution to the "problem" (there are more*) is not that simple. Well, it is simple, but would require us to have a common understanding of how the fields should be rendered first.

_*This PR removes the mandatory dt tag, we have obsolete whitespace in the class attribute when no class was given + in this case: custom fields in contact add a prefix to the class attribute._

**Comment by brianteeman** [comment]
OK i will close this then and await your PR @matrikular

**Pull request closed without merging**
