### PR TITLE
Remove extra underline space in the links of table headings with ordering

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Description

This very simple PR just removes an extra space in the links of table headings with ordering.
This normally happens when tabs or spaces exist inside HTML anchor tags.
#### How to test
1. Go to any listing table (articles for instance) and click on the table heading "Title" to order the contents by title.
2. Mouse over the title (there is an extra space underlined in the link)
3. Apply the patch
4. Mouse over the title (there aren't extra space in the link now).

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 287035b3918039913457ab2c285dbf32154e0db0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8831">issues.joomla.org/joomla-cms/8831</a>.</sub>

**Comment by NLRoosj** [comment]
I have tested this item :white_check_mark: successfully on 287035b3918039913457ab2c285dbf32154e0db0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8831">issues.joomla.org/joomla-cms/8831</a>.</sub>

**Comment by brianteeman** [comment]
RTC - thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8831">issues.joomla.org/joomla-cms/8831</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@brianteeman @NLRoosj thanks for testing.

**Pull request closed without merging**
