### PR TITLE
[4.0] Workflow parameterized queries

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Adds parameterized queries to `Joomla\CMS\Workflow`.

### Testing Instructions

Create, edit, delete, publish/unpublish some articles.

### Expected result

Works like before.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on fddb592dc5a70be8c0af6c9c3ba1d34bf99e6d97<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27552">issues.joomla.org/tracker/joomla-cms/27552</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on fddb592dc5a70be8c0af6c9c3ba1d34bf99e6d97<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27552">issues.joomla.org/tracker/joomla-cms/27552</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27552">issues.joomla.org/tracker/joomla-cms/27552</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
