### PR TITLE
Fix: What can I use as the default value in com_fields field imagelist

### PR DESCRIPTION
**Pull request by ReLater**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/15173

### Summary of Changes
- After comparing the issue with behavior of `com_fields` field `media` that extends `FieldsPlugin` but not `FieldsListPlugin` like imagelist does:
- - Using `FieldsListPlugin` leads to validation via `OptionsRule.php` because line https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_fields/models/field.php#L261 returns a type=`options` instead of `imagelist`.
(In media field the $type = media.)
- - There are no options in the element whwn you create the field. Thus the validation always fails.

### Testing Instructions
- Please read comment https://github.com/joomla/joomla-cms/issues/15173#issue-220385171

### Expected result
- Field can be saved.
- You can select an image in articles and the default value is respected when you don't select another one.
- Image is displayed in frontend in article view.

### Actual result
- Field can't be saved when you fill the `Default Value` field because validation fails.

@laoneo please check.

### CODE REVIEW

**Comment by ghost** [comment]
@astridx @joomdonation can you please test?

**Comment by ReLater** [comment]
No tests.
No comments of pinged experts here and in > 2 years old issue.
TBH i never use com_fields.
Closing.

**Comment by infograf768** [comment]
I tested this patch OK here.
See https://github.com/joomla/joomla-cms/issues/26350#issuecomment-532592098

Please @ReLater can you reopen?

**Comment by infograf768** [comment]
No time to wait if we want to get this in for 3.9.12
Thanks @ReLater I have redone the patch here https://github.com/joomla/joomla-cms/pull/26352

**Comment by EJBJane** [comment]
I have made 4 screenshots here to show the process. I have purged the cache now also at CDN level and turned it off. The problem of the default image not showing up in frontend persists with me, however the validation error is now solved with patch #26352 .
 
[screencapture-1-field.pdf](https://github.com/joomla/joomla-cms/files/3625760/screencapture-1-field.pdf)
[screencapture-2-field.pdf](https://github.com/joomla/joomla-cms/files/3625761/screencapture-2-field.pdf)
[screencapture-3-field.pdf](https://github.com/joomla/joomla-cms/files/3625763/screencapture-3-field.pdf)
[screencapture-4-field.pdf](https://github.com/joomla/joomla-cms/files/3625764/screencapture-4-field.pdf)

**Comment by infograf768** [comment]
@EJBJane 
Please now post in https://github.com/joomla/joomla-cms/pull/26352
Looks like your display problem is not related to Joomla core.
The test is to be done with Protostar and default com_content

**Comment by EJBJane** [comment]
okay get it

**Pull request closed without merging**
