### PR TITLE
Skip calling callback cache controller if caching is disabled

### PR DESCRIPTION
**Pull request by Denitz**
### Summary of Changes

No need to render a module via callback cache controller if caching is disabled.

### Testing Instructions

Enable Joomla caching, apply patch, see no changes except slight cached module rendering time improvement for logged users.

### Actual result BEFORE applying this Pull Request

The module is rendered or the module data is loaded via callback cache without storing the data, even if caching is disabled.

### Expected result AFTER applying this Pull Request

The callback is executed directly.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by Fedik** [comment]
This method does not used when cache is disabled
https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/Document/Renderer/Html/ModuleRenderer.php#L36

So your changes does not make sense.

**Comment by Denitz** [comment]
@Fedik Enable conservative caching in Joomla, ensure that module setting Caching is enabled, log-in and see

**Comment by Fedik** [comment]
That may happen if the module itself also use cache, because `$params->get('cache') == 1`.

**Comment by HLeithner** [comment]
This pull request has automatically rebased to 4.2-dev.

**Comment by HLeithner** [comment]
@Denitz thanks for this pr but I think @Fedik is right and the module it self could be responsible for this.

I'm closing this for now.

**Pull request closed without merging**
