### PR TITLE
[4.1] cassiopeia btn-group

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue # .

### Summary of Changes
Remove incorrect margin bottom

### Testing Instructions
Add this markup into an article - taken directly from [bootstrap docs](https://getbootstrap.com/docs/5.0/components/button-group/#nesting)
```
<div class="btn-group" role="group" aria-label="Button group with nested dropdown">
  <button type="button" class="btn btn-primary">1</button>
  <button type="button" class="btn btn-primary">2</button>

  <div class="btn-group" role="group">
    <button id="btnGroupDrop1" type="button" class="btn btn-primary dropdown-toggle" data-bs-toggle="dropdown" aria-expanded="false">
      Dropdown
    </button>
    <ul class="dropdown-menu" aria-labelledby="btnGroupDrop1">
      <li><a class="dropdown-item" href="#">Dropdown link</a></li>
      <li><a class="dropdown-item" href="#">Dropdown link</a></li>
    </ul>
  </div>
</div>
```

### Actual result BEFORE applying this Pull Request
image

### Expected result AFTER applying this Pull Request
image

### Documentation Changes Required
none

## NOTE
dont worry that the dropdown doesnt work. its unrelated and because the relevant js is not loaded in an article

### CODE REVIEW

**Comment by richard67** [comment]
@brianteeman As far as I've seen, the code which is removed by your PR has been added with [this PR in the Cassiopeia repo](https://github.com/joomla/cassiopeia/pull/197) due to [this issue in the same repo](https://github.com/joomla/cassiopeia/issues/172). So I have checked if your PR reverts that fix, and it seems it does.

Without this PR here:
j4 1-test-pr-37259_filter-fields-before

With your PR:
j4 1-test-pr-37259_filter-fields-after

Is this intended?

**Comment by brianteeman** [comment]
no. that explains why the margin was present but in the wrong place. Updating ...

**Comment by brianteeman** [comment]
@richard67 took a different approach should be correct in both places now

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 8c3e5cff847ab5e53e9072bc53d161bde24740d1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37259">issues.joomla.org/tracker/joomla-cms/37259</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 8c3e5cff847ab5e53e9072bc53d161bde24740d1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37259">issues.joomla.org/tracker/joomla-cms/37259</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37259">issues.joomla.org/tracker/joomla-cms/37259</a>.</sub>

**Comment by laoneo** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
