### PR TITLE
[4.0] Feature/com associations model view

### PR DESCRIPTION
**Pull request by roland-d**
### Summary of Changes
This is a cleanup of the HtmlView code to use the model and since there were so many variables missing I have added them as well. Some other cleanup done as well.

### Testing Instructions
1. Apply patch
2. Use the Multilingual associations
3. Check that no errors occur

### Expected result
Multilingual associations work as expected

### Documentation Changes Required
None

### CODE REVIEW

**Comment by infograf768** [comment]
will check tomorrow

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 8e0661932c8d2f5b9fd35f6c9214dedf9f3d5a3c<br /><br />No change in behavior.

Note: Check-in is still not working in a similar way as in 3.x<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26290">issues.joomla.org/tracker/joomla-cms/26290</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on e1b46bb472bd759f631ef458e190e772f1ff7ced<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26290">issues.joomla.org/tracker/joomla-cms/26290</a>.</sub>

**Comment by ghost** [comment]
Status "Ready To Commit".

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
