### PR TITLE
Update en-GB.com_users.ini

### PR DESCRIPTION
**Pull request by brianteeman**
When the change was made from clicking to selecting this english error was introduced

code review

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on b1367314eba9b5e247ad5cca3a4f2eb8e4c4483b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31358">issues.joomla.org/tracker/joomla-cms/31358</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on b1367314eba9b5e247ad5cca3a4f2eb8e4c4483b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31358">issues.joomla.org/tracker/joomla-cms/31358</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31358">issues.joomla.org/tracker/joomla-cms/31358</a>.</sub>

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
