### PR TITLE
[4.0] Information link -contrast [a11y]

### PR DESCRIPTION
**Pull request by brianteeman**
This fixes a colour contrast accessibility failure by applying the already existing class that was created for this purpose.
image

cc @carcam

### CODE REVIEW

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on 41fed5e2cd452391161016aed1c696f439ad0e47<br /><br />Tested successfully in Beta6-dev of 27 November<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31503">issues.joomla.org/tracker/joomla-cms/31503</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 41fed5e2cd452391161016aed1c696f439ad0e47<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31503">issues.joomla.org/tracker/joomla-cms/31503</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31503">issues.joomla.org/tracker/joomla-cms/31503</a>.</sub>

**Comment by HLeithner** [comment]
thanks

**Pull request merged**
