### PR TITLE
[4.0] Backend: use default bootstrap tabs styling for .nav-tabs

### PR DESCRIPTION
**Pull request by Fedik**
### Summary of Changes

Since of last backend restyling, all tabs was replaced to joomla-tab.
However in a css still left an old style for .nav-tabs, and it looks bad.

### Testing Instructions

Apply patch, run `node build.js --compile-css`
Edit `administrator/templates/atum/index.php`, before `<jdoc:include type="message" />` add:
```html
<div class="bg-white p-3">
<ul class="nav nav-tabs">
  <li class="nav-item">
    <a class="nav-link active" href="#">Active</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#">Link</a>
  </li>
  <li class="nav-item">
    <a class="nav-link" href="#">Link</a>
  </li>
  <li class="nav-item">
    <a class="nav-link disabled" href="#">Disabled</a>
  </li>
</ul>
</div>
```
then open any backend page.

### Actual result BEFORE applying this Pull Request
There an old tabs

Screenshot_2020-10-18_15-12-16

### Expected result AFTER applying this Pull Request
There a default bootstrap tabs 
Screenshot_2020-10-18_15-07-23

### Documentation Changes Required
none

### CODE REVIEW

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on 8ac6d9b9e37982fc4f3c34cd1de3d76f6ec1473a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31145">issues.joomla.org/tracker/joomla-cms/31145</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 8ac6d9b9e37982fc4f3c34cd1de3d76f6ec1473a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31145">issues.joomla.org/tracker/joomla-cms/31145</a>.</sub>

**Comment by jwaisner** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31145">issues.joomla.org/tracker/joomla-cms/31145</a>.</sub>

**Comment by richard67** [comment]
Thanks!

**Pull request merged**
