### PR TITLE
Fix for Codemirror Cant Type Forward Slash

### LINKED ISSUE #6181: Codemirror Can't Type Forward Slash
#### Steps to reproduce the issue
Set Codemirror as default editor.
Either create a new article or edit an existing article.
Type a forward slash ( / ) in the editor window.

#### Expected result
A forward slash appears in the editor window

#### Actual result
Nothing appears in the editor window.

#### System information (as much as possible)
PHP Built On 	Linux 908539.vps-10.com 2.6.32-431.17.1.el6.x86_64 #1 SMP Wed May 7 23:32:49 UTC 2014 x86_64
Database Version 	5.5.42-cll-lve
Database Collation 	utf8_general_ci
PHP Version 	5.5.13
Web Server 	Apache
WebServer to PHP Interface 	cgi-fcgi
Joomla! Version 	Joomla! 3.4.0 Stable [ Ember ] 24-February-2015 23:00 GMT
Joomla! Platform Version 	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent 	Mozilla/5.0 (Macintosh; Intel Mac OS X 10.10; rv:35.0) Gecko/20100101 Firefox/35.0

### LINKED ISSUE #6277: Cannot type forward slash in Joomla 3.4 template editor
#### Steps to reproduce the issue
I try to edit index.php under Joomla > Extensions > Templates but cannot type forward slash

### PR DESCRIPTION
**Pull request by PhilETaylor**
This PR applies an upstream bug fix to CodeMirror
see: https://github.com/codemirror/CodeMirror/commit/076afcb14e8be6
# Steps to reproduce the issue

Set Codemirror as default editor.
Either create a new article or edit an existing article.
Type a forward slash ( / ) in the editor window.
# Expected result

A forward slash appears in the editor window
# What happens

No slash....
# To test this PR

Apply patch - set CodeMirror as active editor see if you can type a slash in editor window

Closes #6277
Closes #6181

### CODE REVIEW

**Comment by brianteeman** [comment]
Is this issue in an external library or our implementation of it?
If it is in the codemirror code then we shouldnt be touching it and should
instead just report upstream


On 3 March 2015 at 16:55, Phil Taylor <notifications@github.com> wrote:

> This PR applies an upstream bug fix to CodeMirror
> Steps to reproduce the issue
>
> Set Codemirror as default editor.
> Either create a new article or edit an existing article.
> Type a forward slash ( / ) in the editor window.
> Expected result
>
> A forward slash appears in the editor window
> What happens
>
> No slash....
> To test this PR
>
> Apply patch - set CodeMirror as active editor see if you can type a slash
> in editor window
>
> Closes #6277 <https://github.com/joomla/joomla-cms/issues/6277>
> Closes #6181 <https://github.com/joomla/joomla-cms/issues/6181>
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/joomla/joomla-cms/pull/6280
> Commit Summary
>
>    - Fix for Codemirror Cant Type Forward Slash
>
> File Changes
>
>    - *M* media/editors/codemirror/addon/edit/closetag.js
>    <https://github.com/joomla/joomla-cms/pull/6280/files#diff-0> (2)
>
> Patch Links:
>
>    - https://github.com/joomla/joomla-cms/pull/6280.patch
>    - https://github.com/joomla/joomla-cms/pull/6280.diff
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/6280>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by n9iels** [comment]
@test confirmed, but the patch doesn't solve the issue for me.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6280">issues.joomla.org/joomla-cms/6280</a>.</sub>

**Comment by PhilETaylor** [comment]
This has already been reported and fixed in the upstream project. This PR is a cherrypick of their own solution as referenced in https://github.com/codemirror/CodeMirror/commit/076afcb14e8be6

**Comment by PhilETaylor** [comment]
Ok I have now upgraded CodeMirror to 5.0.0 released 11 days ago in this PR for testing - this includes all upstream bugfixes

**Comment by brianteeman** [comment]
Please see #6150

**Comment by PhilETaylor** [comment]
hmm ok - well after upgrading with this PR I can now type a forward slash

screen shot 2015-03-03 at 17 12 10

**Comment by n9iels** [comment]
I'm not able to test this patch via the Pacht tester component. When I apply I get a white screen. Not sure if this is a problem with my localhost or the patch..

**Comment by PhilETaylor** [comment]
well as we already have a PR for upgrading CodeMirror, maybe this one can just die? :-(

**Comment by n9iels** [comment]
The PR brian mentioned is planned for Joomla! 3.5.0 (am I right?).
Should be nice if you can find a fix for this for Joomla! 3.4.1, because it is a very irritating bug. Things like typing a css path are impossible now.

**Comment by PhilETaylor** [comment]
When/If this gets merged is not my call... as is the way, you can spend years on a PR but its up to others if it will even be tested, or checked, or merged, and when - out of my hands... 

All I know is that with this PR I can now type slashes and I cannot see any other issues created by the changes proposed.

**Comment by wilsonge** [comment]
As we already have a open PR upgrading to Codemirror 5 (https://github.com/joomla/joomla-cms/pull/6150) may I suggest we focus efforts there. If you want to test that it would be hugely appreciated :)

**Pull request closed without merging**
