### PR TITLE
Add chosen to module order field

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue #11984
### Summary of Changes

Adds chosen to the select element (really minor, but already two requests for this)
### Testing Instructions

Go to admin->modules
Create a new module
Change the position
Check the ordering
save
Change the position
Check the ordering
save

The select element should have chosen style applied and should be functioning as before
### Documentation Changes Required

None

### CODE REVIEW

**Comment by 810** [comment]
I have tested this item :white_check_mark: successfully on 699585258145890b5679f390cc93e59b4c1e2ac5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11992">issues.joomla.org/joomla-cms/11992</a>.</sub>

**Comment by Minei3oat** [comment]
I have tested this item :white_check_mark: successfully on 699585258145890b5679f390cc93e59b4c1e2ac5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11992">issues.joomla.org/joomla-cms/11992</a>.</sub>

**Comment by zero-24** [comment]
RTC. Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11992">issues.joomla.org/joomla-cms/11992</a>.</sub>

**Comment by dgt41** [comment]
@wilsonge you have merged this to 3.7, but the base of this https://github.com/joomla/joomla-cms/pull/11991 is merged into staging. Is there any reason to introduce this as plain and wait for another update to apply chosen?

**Pull request merged**
