### PR TITLE
[com_users] debuguser & debuggroup: use the same tree level visual

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Summary of Changes

This PR does for users debug & user groups debug, the same visual change in the tree structure as done:
- for categories https://github.com/joomla/joomla-cms/pull/10213
- for tags https://github.com/joomla/joomla-cms/pull/10526
- for user group https://github.com/joomla/joomla-cms/pull/10528

After PR (example)
image
#### Testing Instructions
1. Use latest staging
2. Apply patch https://github.com/joomla/joomla-cms/pull/10528 (to have the layout) and then this patch
3. Go to Global config and enable System Debug
4. Go to Users -> Manage, click "Debug Permission report" on any user and check the tree structure visual
5. Go to Users -> Groups, click "Debug Permission report" on any user group and check the tree structure visual

### CODE REVIEW

**Comment by brianteeman** [comment]
> Apply patch #10526 (to have the layout) and then this patch

I think this is supposed to say #10528 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10530">issues.joomla.org/joomla-cms/10530</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 68bc2026a320fac8a327102f87d913650df5198f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10530">issues.joomla.org/joomla-cms/10530</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 68bc2026a320fac8a327102f87d913650df5198f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10530">issues.joomla.org/joomla-cms/10530</a>.</sub>

**Comment by andrepereiradasilva** [comment]
yes, you're right! corrected.

**Comment by BurtNL** [comment]
I have tested this item :white_check_mark: successfully on 68bc2026a320fac8a327102f87d913650df5198f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10530">issues.joomla.org/joomla-cms/10530</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10530">issues.joomla.org/joomla-cms/10530</a>.</sub>

**Comment by Kubik-Rubik** [comment]
Thank you @andrepereiradasilva!

**Pull request merged**
