### PR TITLE
[5.1] The item can be null in FieldsHelper

### PR DESCRIPTION
**Pull request by laoneo**
### Summary of Changes
As we want to get rid of the `CMSObject` traces, this pr removes an obsolete instantiation in FieldsHelper.

### Testing Instructions
- Create a text custom field
- Create an article and fill the test custom field with the value "Test"
- Open the article on the front

### Actual result BEFORE applying this Pull Request
Test is rendered in the custom field.

### Expected result AFTER applying this Pull Request
Test is rendered in the custom field.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on c2eb98919438752231bcae18c92f0e2bb42aa05f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43007">issues.joomla.org/tracker/joomla-cms/43007</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on c2eb98919438752231bcae18c92f0e2bb42aa05f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43007">issues.joomla.org/tracker/joomla-cms/43007</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43007">issues.joomla.org/tracker/joomla-cms/43007</a>.</sub>

**Comment by LadySolveig** [comment]
Thank you @laoneo and also for testing @ceford @viocassel

**Pull request merged**
