### PR TITLE
[4.0][CLI] com_finder use console command

### PR DESCRIPTION
**Pull request by alikon**
### Summary of Changes
move com_finder from cli to console command

### Testing Instructions

`php cli/joomla.php finder:index purge`  to index and rebuilds
`php cli/joomla.php finder:index`  to index  only
`php cli/joomla.php finder:index  --pause=10`  to index  with a pause of 10 seconds

### Actual result BEFORE applying this Pull Request

`php finder_indexer.php --purge`

### Expected result AFTER applying this Pull Request

`php cli/joomla.php finder:index purge`

image

### Documentation Changes Required
yes

### CODE REVIEW

**Comment by richard67** [comment]
@alikon PHPCS: [https://ci.joomla.org/joomla/joomla-cms/35730/1/8](https://ci.joomla.org/joomla/joomla-cms/35730/1/8)

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on 2b42e5ebd82a3568b8b843f199577d192ade6e96<br /><br />In the testing instructions the before test is incomplete - it should be php cli/finder_indexer.php --purge
And the first of the Testing Instructions has a stray p - php cli/joomla.php finder:indexp purge
In the second test I got a skipping pause message so I guess there is a default pause
>   * Skipping pause, as previous batch had a very low processing time (0.134s < 1s)

But all worked as described. I did not understand the PHPCS link.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30768">issues.joomla.org/tracker/joomla-cms/30768</a>.</sub>

**Comment by richard67** [comment]
> I did not understand the PHPCS link.

@ceford For every pull request, automatic tests like e.g. unit tests or system tests are run, and also code style tests (PHP, javasript, scss, ...). The results to the tests can be found on GitHub at the bottom of each PR in a section for the checks. If all checks were successfukll, that box is hidden, but it can be expanded with the link "Show all checks". There you see all checks, failed ones marked with a red mark. The link "Details" right beside each check leads to a page with a log file, where you can see at the left hand side which step of a test has failed, in this case it was "PHPCS". By clicking on the failed test step you can see then details about the failures. I had linked the log of the PHPCS test for Nicola so he can check and fix. Proper code style is necessary for good maintenance, and passing the PHPCS test is also necessary for later running the (more important) unit and system tests.

**Comment by sandewt** [comment]
>Skipping pause, as previous batch had a very low processing time (0.134s < 1s)

## Pause = 10


## Pause = 0.1


Pause is skipping. How should I interpret this?

**Comment by alikon** [comment]
pause is skipping cause the elab time is already very low (0.1 sec)

**Comment by sandewt** [comment]
>pause is skipping cause the elab time is already very low (0.1 sec)



Indeed, works so properly.

**Comment by sandewt** [comment]
I have tested this item :white_check_mark: successfully on 2b42e5ebd82a3568b8b843f199577d192ade6e96<br />


>In the testing instructions the before test is incomplete - it should be php cli/finder_indexer.php --purge

Tested before with:
php cli/finder_indexer.php --purge
<br />Joomla! 4.0.0-beta5-dev Development [ Mañana ] 15-September-2020 19:15 GMT<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30768">issues.joomla.org/tracker/joomla-cms/30768</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30768">issues.joomla.org/tracker/joomla-cms/30768</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Comment by HLeithner** [comment]
@alikon can you update the documentation? and the upgrade site for J4, should be too much I think it's updating the filename and parameters in the original documentation and in upgrade path.

**Comment by ceford** [comment]
> > I did not understand the PHPCS link.
> 
> @ceford For every pull request, automatic tests like

@richard67 Once again, thank you for the explanation - I see it now and have read a few more articles on testing.

**Pull request merged**
