### PR TITLE
Incorect value specifier in language strings

### PR DESCRIPTION
**Pull request by yild**
Pull Request for Issue # .
### Summary of Changes

Simple change from string specifier %s to integer specifier %d in multiple strings. 

Values for place holders are integers not strings - second param for JText::plurar() function, i.e. https://github.com/joomla/joomla-cms/blob/b2a4b483995875373da5b385011225358abeb571/libraries/legacy/controller/admin.php#L237
### Testing Instructions

Code review

### CODE REVIEW

**Comment by infograf768** [comment]
Although this is indeed correct theoretically speaking, it has no effect whatsoever on the resulting display. Is it really worth changing?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11662">issues.joomla.org/joomla-cms/11662</a>.</sub>

**Comment by yild** [comment]
I don't know if its truly necessary - I just wanted to post this 'issue', ignore it (close) or not is not my call :)

**Comment by ggppdk** [comment]
I would be against using %d,
unless it is really 100% sure that we will never need to pass a string to it ...

e.g.  i am doing this in my views (but i am not using Joomla language strings)
4 out of 7 articles were deleted

notice the:
4 out of 7

so **if you want to make an addition to the existing code**, you will have to change the language strings back to %s,

but then you have a problem:
- **think of all the translations** that will have been updated to have %d

unless existing strings are causing a problem, it is best not to do this, reverting it in the future, would be problematic !

**Comment by yild** [comment]
I was thinking about it, that best way would be to use %s in every single key when param is passed to a string. But again it would be a pain for translators OR not replace %d with %s in multiple files is a simple procedure, even at Crowdin.

**Comment by brianteeman** [comment]
I am setting this to needs review so a decision can be made. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11662">issues.joomla.org/joomla-cms/11662</a>.</sub>

**Comment by rdeutz** [comment]
Seems to me not worth the change, @yild you are correct here but at the end of the day it will change nothing but it will be work for the translation team. Thanks for bringing it up.

**Pull request closed without merging**
