### PR TITLE
FinderIndexerHelper::addContentType fix error: duplicate entry 'xx' for key 'title'

### PR DESCRIPTION
**Pull request by Fedik**
### Summary of Changes
The pull fix static caching in `FinderIndexerHelper::addContentType`, wich used for cache the ContentType ids

### Testing Instructions
run next code:
```php
JLoader::register('FinderIndexerHelper', JPATH_ADMINISTRATOR . '/components/com_finder/helpers/indexer/helper.php');
$name = uniqid();
var_dump(FinderIndexerHelper::addContentType($name));
var_dump(FinderIndexerHelper::addContentType($name));
```

### Expected result
you will get 2 same id

### Actual result
Error 'Duplicate entry 'xx' for key 'title''..

### CODE REVIEW

**Comment by JonasAtZwetschke** [comment]
I have tested this item :white_check_mark: successfully on 5902a882f312bed4bc8be1aac8dd9698f851ea19<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15181">issues.joomla.org/tracker/joomla-cms/15181</a>.</sub>

**Comment by finim** [comment]
Successfully integraded the fix it into staging.

**Comment by franz-wohlkoenig** [comment]
@finim is this a succesfully Test?

**Comment by Fedik** [comment]
one more test please :neckbeard:

**Comment by twister65** [comment]
I have not tested this item.<br /><br />I can't reproduce the error 'Duplicate entry 'xx' for key 'title'',
I got the expected result (same two identifiers) without applying this patch.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15181">issues.joomla.org/tracker/joomla-cms/15181</a>.</sub>

**Pull request closed without merging**
