### PR TITLE
Fix smart search indexer for mysql - part only for J4

### PR DESCRIPTION
**Pull request by csthomas**
### Summary of Changes
* Fix smart search indexer for mysql, related to #14811 for J3
* Fix a few lines in front end template for smart search, take a look at code.

### Testing Instructions
Go to backend - Smart Search extension.
Click on button "Index" 
Test front end search form at `index.php?option=com_finder&view=search`
(type 'red' or 'green') - before patch there is `error page`, after patch joomla finds an item.

### Expected result
All works, front end search form too.

### Actual result
`Expression #3 of SELECT list is not in GROUP BY clause and contains nonaggregated column 't1.stem' which is not functionally dependent on columns in GROUP BY clause; this is incompatible with sql_mode=only_full_group_by`

### Documentation Changes Required
No

### CODE REVIEW

**Comment by marcodings** [comment]
I have tested this item :white_check_mark: successfully on d807fdb9f50af41aeca4604291734e4ee0f75443<br /><br />Tested successfully aga8nst J37b3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14783">issues.joomla.org/tracker/joomla-cms/14783</a>.</sub>

**Comment by wilsonge** [comment]
@csthomas can you rebase here please?

**Comment by brianteeman** [comment]
@wilsonge why does it need rebasing this is for J4 and github reports no conflicts ?
@marcodings this is for J4 but you have tested on J3?

**Comment by wilsonge** [comment]
There were conflicts after #14782. It already got rebased since I asked which is why github doesn't show any conflicts now

**Comment by wilsonge** [comment]
I have tested this item :red_circle: unsuccessfully on a397af6ea2a6f28fee8849b8b69d1dfb91352e4f<br /><br />This fixes the `term_id` issue but I cannot index fully still. On running index with sample data I now get the error: 

`Field 'map_suffix' doesn't have a default value`<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14783">issues.joomla.org/tracker/joomla-cms/14783</a>.</sub>

**Comment by csthomas** [comment]
You can test if everything was indexed at front end  `/index.php?option=com_finder&view=search`

**Comment by csthomas** [comment]
Please do not merge it for now. I'm working on version for J3

**Comment by waader** [comment]
I have tested this item :white_check_mark: successfully on 10848bd9b8fec55906adad49c9a614df30d9aa31<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14783">issues.joomla.org/tracker/joomla-cms/14783</a>.</sub>

**Pull request merged**
