### PR TITLE
[adminmenu] - content menu same order as sidebar

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #18905 .

### Summary of Changes
moved  Featured Articles item after Categories item like sidebar

### Testing Instructions
before pr
1. Articles
2. Categories
3. Field 
4. Field Groups
5. **Featured Articles**

apply pr 

1. Articles
2. Categories
3. **Featured Articles**
4. Fields
5. Field Groups

### Expected result
same order as sidebar menu

### Actual result

image

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 04f35e569a175f251c34e47de586c13a3c390c71<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18908">issues.joomla.org/tracker/joomla-cms/18908</a>.</sub>

**Comment by infograf768** [comment]
restarted Travis

**Comment by infograf768** [comment]
See also https://github.com/joomla/joomla-cms/pull/18918
What is best?

**Comment by ladyjer** [comment]
Hi,

I've tested #18918 5 minutes ago. It seems the same issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18908">issues.joomla.org/tracker/joomla-cms/18908</a>.</sub>

**Comment by Quy** [comment]
The other PR is more comprehensive and includes changes in this PR. 

For further details: https://github.com/joomla/joomla-cms/pull/18918#issuecomment-348258341

**Comment by infograf768** [comment]
@alikon 
Shall we close this one in favour of https://github.com/joomla/joomla-cms/pull/18918 ?

**Comment by alikon** [comment]
closed for #18918

**Pull request closed without merging**
