### PR TITLE
[com_contacts] contacts view: Adds max level filter

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
Pull Request for Improvement.
#### Summary of Changes

All backend views that are or are associated with tree like structures (e.g. menus, categories) should have a max level filter.

This is valid currently for:
- com_menus items view
- com_content articles view
- com_content featured view
- com_tags tags view

So, this PR is a part of series of PR to add that filter in the views that use categories:
- com_contacts contacts view (**this PR**)
- com_banners banners view (RTC https://github.com/joomla/joomla-cms/pull/9977)
- com_newsfeeds newsfeeds view (RTC https://github.com/joomla/joomla-cms/pull/9978)
- com_notes notes view (RTC https://github.com/joomla/joomla-cms/pull/9984)
- com_banners tracks view (https://github.com/joomla/joomla-cms/pull/10009)

image
#### Testing Instructions
1. Use latest staging and apply this patch
2. Create some contact categories with at least two levels
3. Create some contacts and associate them to the categories created in 2..
4. Test the new max levels filter.

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 3b9c05911bf9d72383d5ea9cd47bac80ab5fbffe<br /><br />Used test data so not needed to create the contacts for the test.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9975">issues.joomla.org/joomla-cms/9975</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 3b9c05911bf9d72383d5ea9cd47bac80ab5fbffe<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9975">issues.joomla.org/joomla-cms/9975</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9975">issues.joomla.org/joomla-cms/9975</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@richard67 @brianteeman thanks for testing!

**Comment by rdeutz** [comment]
technically this is a new feature and it doesn't fix a bug so it has to go into 3.6.0

**Pull request merged**
