### PR TITLE
Fix W3C Warning for breadcrumbs: role="navigation" is unnecessary for element nav

### PR DESCRIPTION
**Pull request by RickR2H**
### Summary of Changes
The breadcrumbs have the ARIA role="navigation", but this is unnecessary for nav elements. Also added a class to the breadcrumbs nav element for easy styling.

### Testing Instructions
Look at the code of the breadcrumbs and see if the the role element is there. Apply the patch and check if the role element is gone and the class added.

### Actual result BEFORE applying this Pull Request
breadcrumbs nav has role="navigation"

### Expected result AFTER applying this Pull Request
breadcrumbs nav has no role="navigation" and has class="breadcrumbs-container"

### Documentation Changes Required
No

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 3ef4a3310afb9c99205c1cb3e6ed2c58a774c4a4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34470">issues.joomla.org/tracker/joomla-cms/34470</a>.</sub>

**Comment by infograf768** [comment]
Looks fine.
Other places concerned, first one concerns media breadcrumbs
```
joomla40/administrator/components/com_media/resources/scripts/components/breadcrumb/breadcrumb.vue:4:     role="navigation"

joomla40/layouts/joomla/pagination/links.php:56: 	<nav role="navigation" aria-label="<?php echo Text::_('JLIB_HTML_PAGINATION'); ?>">

joomla40/layouts/joomla/pagination/list.php:17: <nav role="navigation" aria-label="<?php echo Text::_('JLIB_HTML_PAGINATION'); ?>">

joomla40/libraries/vendor/codeception/codeception/ext/Recorder.php:139:         <nav class="navbar navbar-expand-lg navbar-light bg-light" role="navigation">

joomla40/libraries/vendor/codeception/codeception/ext/Recorder.php:219:     <nav class="navbar navbar-expand-lg navbar-light bg-light" role="navigation">
```

**Comment by RickR2H** [comment]
@infograf768 Thanks for the search! Made some changes to the mentioned files. The only problem is that joomla40/libraries/vendor/codeception/codeception/ext/Recorder.php is excluded from the repo. I don't know how to add this to the code. Can you help?

**Comment by infograf768** [comment]
codeception is third party. I guess the only way would be to propose a patch https://github.com/codeception/codeception/issues. The rest is fine.

**Review by hans2103 — APPROVED** [review]

**Comment by hans2103** [comment]
I have tested this item :white_check_mark: successfully on 5f39e0080920e3e97818642429e5a59bcc133c1c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34470">issues.joomla.org/tracker/joomla-cms/34470</a>.</sub>

**Comment by RickR2H** [comment]
@infograf768 I also added a PR to codeception.

**Comment by brianteeman** [comment]
for future reference creating a nav with a role=navigation used to be needed for browsers that did not support html5

**Comment by brianteeman** [comment]
For new specific classes it would be best if you adopted BEM naming convention. There is a good explanation here https://github.com/joomla/joomla-cms/pull/32267

**Comment by RickR2H** [comment]
> For new specific classes it would be best if you adopted BEM naming convention. There is a good explanation here #32267

@brianteeman I agree! But the child element of nav has already the Block Element Class. If the previous implementation was done right, the nav should have the Block Element Class. Not the first child. Me not trying to mess up the styling of the template, I implemented a container class.

**Review by hans2103 — APPROVED** [review]

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 5f39e0080920e3e97818642429e5a59bcc133c1c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34470">issues.joomla.org/tracker/joomla-cms/34470</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34470">issues.joomla.org/tracker/joomla-cms/34470</a>.</sub>

**Comment by richard67** [comment]
@RickR2H It seems you have merged the staging branch into the branch for this PR, so this PR now changes more than it should. That was wrong. Please revert, or maybe it's easier if you make a new PR.

**Comment by RickR2H** [comment]
@richard67 Sorry my mistake! Was working in the wrong branch.

**Comment by richard67** [comment]
@RickR2H It's still wrong because the other commit "update" after the merge of staging was wrong, too. Your PR had 2 good tests and was RTC and so should not have been touched further.

**Comment by richard67** [comment]
Back to pending as the branch of this PR has received new, wrong commits.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34470">issues.joomla.org/tracker/joomla-cms/34470</a>.</sub>

**Comment by RickR2H** [comment]
@richard67 I'll create a new PR. That's quicker

**Comment by RickR2H** [comment]
Closed this PR due to merging errors. Opened a new PR #34483

**Pull request closed without merging**
