### PR TITLE
Fix unittest on cache - 5 seconds less

### PR DESCRIPTION
**Pull request by csthomas**
### Summary of Changes
Currently `JCacheTest->testGc()` method work with cache disabled, without configured storage, but take 5 seconds.

Changes:
- enable caching
- set storage to file
- remove `sleep(5)` and use `TestReflection` to change modification time of cached file.
- After garbage collection:
  - add test for file exists before check cache data. File storage deletes expired file on `get` method so we have to check file exists before `get` to be sure that `gc` works as expected.
  - add additional test for non expired data

### Testing Instructions

Travis passed.
Require code review.

### Documentation Changes Required
None

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
see https://github.com/csthomas/joomla-cms/pull/3

**Comment by andrepereiradasilva** [comment]
@csthomas can you check my patch were too?

**Comment by andrepereiradasilva** [comment]
@csthomas i prefer my https://github.com/csthomas/joomla-cms/pull/3/files because it makes sure we only delete expired cache.

**Comment by csthomas** [comment]
May be you have rights that on JCacheTest we should not use low level var like `handler->_now`

**Comment by andrepereiradasilva** [comment]
> May be you have rights that on JCacheTest we should not use low level var like handler->_now

Did not understood

**Comment by csthomas** [comment]
Sorry I say about something else.

**Comment by csthomas** [comment]
I agree with you that some value should stay after gc.

**Comment by andrepereiradasilva** [comment]
ok will wait for the changes them.

**Comment by andrepereiradasilva** [comment]
Latest staging (your other patch already merged)

Before Patch:
Time: 5.38 seconds, Memory: 10.00MB

After Patch:
Time: 835 ms, Memory: 10.00MB

So almost 5 seconds less in all unit tests.

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 6488d472db12c0f55336bca0050232ec99771738<br /><br />as comments above<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11872">issues.joomla.org/joomla-cms/11872</a>.</sub>

**Comment by andrepereiradasilva** [comment]
wow just check a php 7 travis build and the unit test runned in 20 sec, even without this PR that will decrease that time in more 5 sec

image
https://travis-ci.org/joomla/joomla-cms/jobs/157294479#L1248

**Comment by andrepereiradasilva** [comment]
can we have another test or review here so we can make all unit tests 5 seconds faster?

**Review by andrepereiradasilva — APPROVED** [review]

**Comment by csthomas** [comment]
This PR is only for unittest speed up - 5 seconds less.  
Is no one is interested?

**Review by mbabker — APPROVED** [review]

**Comment by andrepereiradasilva** [comment]
@zero-24 can you test also?

**Comment by photodude** [comment]
I have tested this item :white_check_mark: successfully on 6488d472db12c0f55336bca0050232ec99771738<br /><br />Looks good, by code review <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11872">issues.joomla.org/tracker/joomla-cms/11872</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11872">issues.joomla.org/tracker/joomla-cms/11872</a>.</sub>

**Pull request merged**
