### PR TITLE
[4.1] s\preset\present

### PR DESCRIPTION
**Pull request by brianteeman**
Fix copy [paste error. Corrects the copyright date as its a new file.

Looks like all the `@since ` values also need to be corrected as well

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 8661a6a6e7b80312652083a4a59e0796103c4ba9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37402">issues.joomla.org/tracker/joomla-cms/37402</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 8661a6a6e7b80312652083a4a59e0796103c4ba9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37402">issues.joomla.org/tracker/joomla-cms/37402</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37402">issues.joomla.org/tracker/joomla-cms/37402</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
