### PR TITLE
[4.0] Batch fieldset markup [a11y]

### PR DESCRIPTION
**Pull request by brianteeman**
A fieldset should have a legend not a label. There is no visible change its just in the markup which is now valid.

image

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 447f87f98931dfcf669f5f77fbb0ed34127968aa<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30694">issues.joomla.org/tracker/joomla-cms/30694</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 447f87f98931dfcf669f5f77fbb0ed34127968aa<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30694">issues.joomla.org/tracker/joomla-cms/30694</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30694">issues.joomla.org/tracker/joomla-cms/30694</a>.</sub>

**Comment by richard67** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
