### PR TITLE
[4.0] Replace inline style width 30%, 40%, 60%, 80% with w-30, w-40, w-60, …

### PR DESCRIPTION
**Pull request by Quy**
Continuation of PR #28692

### Summary of Changes
Replace inline style widths % with w-.

### Testing Instructions
Code review.

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on ff04b70d48f23ddfaa37d0643e789365336cbd5e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29012">issues.joomla.org/tracker/joomla-cms/29012</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on ff04b70d48f23ddfaa37d0643e789365336cbd5e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29012">issues.joomla.org/tracker/joomla-cms/29012</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29012">issues.joomla.org/tracker/joomla-cms/29012</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
