### PR TITLE
Remove unused variable

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
Remove `$fullWidth` as it is not being used.

### Testing Instructions
Code review.

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on df6cc4bbf260c6eb2d9bf1dbb196e282902d7881<br /><br />I can confirm that the variable is not used anywhere in J3 core.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26361">issues.joomla.org/tracker/joomla-cms/26361</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on df6cc4bbf260c6eb2d9bf1dbb196e282902d7881<br /><br />code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26361">issues.joomla.org/tracker/joomla-cms/26361</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26361">issues.joomla.org/tracker/joomla-cms/26361</a>.</sub>

**Comment by brianteeman** [comment]
I am wary of this being committed in a patch release

**Comment by alikon** [comment]
i'm afraid we will only have 3.10 .... what i'm missing ?

**Comment by SharkyKZ** [comment]
It's just a local variable. Fine to go in 3.9.xx.

**Comment by infograf768** [comment]
As we have been living with it since 3.0.0 without any side effects and @HLeithner wants to minimize changes in the stable vs RC, let's just merge in 3.10.0 ;)

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
