### PR TITLE
Fix the missing lang strings for com_media

### LINKED ISSUE #7751: 2 missing language keys
There are 2 language keys which I can't find them anywhere in Joomla language files

JLIB_APPLICATION_ERROR_CREATE_NOT_PERMITTED - used in

https://github.com/joomla/joomla-cms/blob/master/administrator/components/com_media/controllers/folder.php#L168

JERROR_CORE_CREATE_NOT_PERMITTED - used in 

https://github.com/joomla/joomla-cms/blob/master/administrator/components/com_templates/models/style.php#L169 and https://github.com/joomla/joomla-cms/blob/master/administrator/components/com_modules/models/module.php#L398

If they are really missing. What language ini file should we add them to? Can we just simply say "Create not permitted." just like in com_media?

    COM_MEDIA_ERROR_CREATE_NOT_PERMITTED="Create not permitted."

### PR DESCRIPTION
**Pull request by zero-24**
This fixes: https://github.com/joomla/joomla-cms/issues/7751 Thanks @tranduyhung and @infograf768 

---

There are 2 language keys which I can't find them anywhere in Joomla language files

JLIB_APPLICATION_ERROR_CREATE_NOT_PERMITTED - used in

https://github.com/joomla/joomla-cms/blob/master/administrator/components/com_media/controllers/folder.php#L168

JERROR_CORE_CREATE_NOT_PERMITTED - used in 

https://github.com/joomla/joomla-cms/blob/master/administrator/components/com_templates/models/style.php#L169 and https://github.com/joomla/joomla-cms/blob/master/administrator/components/com_modules/models/module.php#L398

If they are really missing. What language ini file should we add them to? Can we just simply say "Create not permitted." just like in com_media?

```
COM_MEDIA_ERROR_CREATE_NOT_PERMITTED="Create not permitted."
```

### CODE REVIEW

**Comment by chrisdavenport** [comment]
Missing full stops at the end?  Do we have a standard for that?

**Comment by zero-24** [comment]
Thanks just fixed based on: https://github.com/joomla/user-interface-text/blob/master/punctuation.md#period

**Comment by chrisdavenport** [comment]
Thanks. :-)

**Comment by zero-24** [comment]
Based on @chrisdavenport 's en-GB Review and the comments by @tranduyhung and @infograf768 on https://github.com/joomla/joomla-cms/issues/7751 I'm going to RTC here. Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7752">issues.joomla.org/joomla-cms/7752</a>.</sub>

**Comment by Kubik-Rubik** [comment]
@zero-24 You use two different language constants. Is it on purpose?

**Comment by infograf768** [comment]
Yes. One exists already in lang packs and can't be used globally. The new one is global.

**Comment by Kubik-Rubik** [comment]
@infograf768 Okay, I understand. Then it's good to be merged.

Thank you @zero-24!

**Pull request merged**
