### PR TITLE
Update controller.php

### PR DESCRIPTION
**Pull request by philip-sorokin**
Logical error?

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
this is duplicate of https://github.com/joomla/joomla-cms/pull/10702

can be closed

**Comment by brianteeman** [comment]
Closed as requested

**Comment by addondev** [comment]
It is not a duplicate - there are two errors: in the com_tags controller and in the com_newsfeed controller.

**Comment by andrepereiradasilva** [comment]
ok, but your both PR are for com_tags see the "Files Changed" in both PR

**Comment by zero-24** [comment]
@addondev but both PRs change the same files:
https://github.com/joomla/joomla-cms/pull/10703/files
https://github.com/joomla/joomla-cms/pull/10702/files

Can you add the seccond file to this PR? or create a new on for com_newsfeed :smile:

**Comment by addondev** [comment]
I will make a new one.

**Comment by zero-24** [comment]
:+1:

**Pull request closed without merging**
