### PR TITLE
Added an id to the submit buttons in both login modules (frontend / b…

### PR DESCRIPTION
**Pull request by yvesh**
### Summary of Changes

Adds an id to the two login modules (frontend and backend). It follows the naming style of the other elements in the modules (...). This improves multi-language testability..

### Testing Instructions

Code review

### Documentation Changes Required

None.

### CODE REVIEW

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on 8657723f921395e4c321909688a6b8950d2a593c<br /><br />Code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13352">issues.joomla.org/tracker/joomla-cms/13352</a>.</sub>

**Comment by Bakual** [comment]
Having an ID attribute in a module is actually bad idea as they may appear on a page multiple times and thus produce invalid HTML.
If you need an id (eg a class doesn't work for some reason), make sure to add the $module->id to the ID generation so you end up with an unique identifier.

**Comment by yvesh** [comment]
@Bakual when you look at the two login modules, they have both only ids.. Else i would have made a class.. I definitely know that, but didn't want to clean up that ** with this PR :)

**Comment by mbabker** [comment]
If you do something where the login module is rendered multiple times on the page, then you're technically generating invalid HTML with this as is because you'll have multiple DOM elements with the same ID.  Although we already have this problem with both modules so `¯\_(ツ)_/¯`

**Comment by Bakual** [comment]
I don't care about existing IDs. They can be cleaned up with J4. But lets not introduce additional ones :)

**Comment by yvesh** [comment]
@Bakual we need that for system testing.. But okay, going to change it to class selector then.

**Comment by yvesh** [comment]
Closing in favour of a class selector..

**Pull request closed without merging**
