### PR TITLE
com_contact. Rm unused order_up, order_dn

### PR DESCRIPTION
**Pull request by ReLater**
`order_up` and `order_dn` are not used in Joomla core. Garbage from Joomla 1.6 or so.

### Summary of Changes
Removed lines from com_contact list view.

```
// Preprocess the list of items to find ordering divisions.
// @todo: Complete the ordering stuff with nested sets
foreach ($this->items as &$item) {
 $item->order_up = true;
 $item->order_dn = true;
}
```

### Testing Instructions
- Check the Joomla core if you find somewhere a code place where properties `order_up` or `order_dn` are used. You won't find one.
- Check that `com_contact` list view in Joomla backend works like before when these lines are removed.
- @Kubik-Rubik [confirmed in german Joomla forum that these lines are garbage](https://forum.joomla.de/thread/20144-item-order-up-item-order-dn-in-komponente-was-ist-das/?postID=146525#post146525) from Joomla 1.6 or so.

### Actual result BEFORE applying this Pull Request
- Unused garbage in file.

### Expected result AFTER applying this Pull Request
- No functional changes. Garbage removed.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on f1ac63ee33d16b6811e6c85fc600d6ac849b9810<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42581">issues.joomla.org/tracker/joomla-cms/42581</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on f1ac63ee33d16b6811e6c85fc600d6ac849b9810<br /><br />Joomla 5.1.0-alpha2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42581">issues.joomla.org/tracker/joomla-cms/42581</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42581">issues.joomla.org/tracker/joomla-cms/42581</a>.</sub>

**Comment by richard67** [comment]
RTC as it has 2 successful tests ... but it needs to be clarified with maintainers or release managers if this should be rebased to 5.1-dev.

**Comment by bembelimen** [comment]
Yes, 5.1 please

**Comment by LadySolveig** [comment]
Thank you @ReLater and also for testing @ChristineWk and @Quy !

**Pull request merged**
