### PR TITLE
[4.0] Update the polyfills, fix other deps

### PR DESCRIPTION
**Pull request by dgrammatiko**
Updates the webcomponents polyfills and also corrects the last update resources as it was wrong since no minification of the css and js was applied

Pull Request for Issue # .

### Documentation Changes Required

@wilsonge please merge this!

### CODE REVIEW

**Comment by astridx** [comment]
With this patch I neither see the warning in the console of the browser nor in the javascript tests. So it is fine.
But I wonder where the file /media/system/js/polyfills/webcomponents/webcomponents-ce.js comes from. Is it a special file for Joomla! ?

**Comment by dgrammatiko** [comment]
@astridx the polyfills come from the repo Joomla-projects/custom-elements(https://github.com/joomla-projects/custom-elements/tree/master/dist/polyfills), check these lines that copy the files from the node_modules folder to the media/system/js/polyfills: https://github.com/joomla/joomla-cms/blob/b6c882875df4f1b9b04880b6ef4a68cfd5134f89/build/build-modules-js/update.js#L209-L212

**Comment by astridx** [comment]
@dgt41 Thank you for the link and the explanation.

**Comment by zero-24** [comment]
Ok looks like just one warning is still showing up in drone until he is happy (http://ci.joomla.org/joomla/joomla-cms/2749/5):
```
+ node_modules/karma/bin/karma start karma.conf.js --single-run
30 01 2018 09:41:06.646:WARN [watcher]: Pattern "/drone/src/github.com/joomla/joomla-cms/media/system/webcomponents/joomla-alert.min.js" does not match any file.
```

Looks like a file that don't exist anymore?

**Comment by astridx** [comment]
This file is moved to another folder.
This PR made the correction: https://github.com/joomla/joomla-cms/pull/19426
[Here](https://github.com/joomla/joomla-cms/commit/d9d988a6e413ce692c3e9e2990b1087ff27f0e52) you can find the line.

**Comment by zero-24** [comment]
ok so the other PR needs to be merged first and this one updated or a owner hit merge here as this is a required status check 😄

**Pull request merged**
