### PR TITLE
Remove show_tag_num_items

### PR DESCRIPTION
**Pull request by brianteeman**
com_tags has an option that "Shows the number of items with a given tag."
Except **there is no code anywhere to use that option** which makes sense as we display the items with the tag and not the number items for each tag. That is something the tags-popular module does not the tags component ir tags menu item

This PR removes this useless option

### CODE REVIEW

**Comment by alikon** [comment]
For the display of the number items for each tag  we may have this pr #10895 in addition to the tags-popular module

**Comment by brianteeman** [comment]
Yes that's correct but unaffected by this pr (I hope)

**Comment by coolcat-creations** [comment]
I have tested this item :white_check_mark: successfully on <br /><br />Tested successful - All appearances are gone. 
But will it break B/C if anyone used it in own overrides ? <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11478">issues.joomla.org/joomla-cms/11478</a>.</sub>

**Comment by mbabker** [comment]
> But will it break B/C if anyone used it in own overrides ?

Yes and no.  Yes in that there is no longer a value to check the next time the parameters for one of these sections are saved (it'll still persist in the database even though it's no longer in the XML file).  No in that all the parameter code has a default value to use in case the parameter's value isn't set, so whatever the default in the PHP file is will be used in those cases.

@brianteeman there's a merge conflict in `installation/sql/sqlazure/sample_testing.sql` (and GitHub finally tells us this, yay for small miracles)

**Comment by slibbe** [comment]
Tested succesfully, with MySQL.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11478">issues.joomla.org/tracker/joomla-cms/11478</a>.</sub>

**Comment by slibbe** [comment]
I have tested this item :white_check_mark: successfully on 5a488f5e5132646070be25c7d32f9f0aceb1f4a7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11478">issues.joomla.org/tracker/joomla-cms/11478</a>.</sub>

**Comment by BiancaCrown** [comment]
I have tested this item :white_check_mark: successfully on 5a488f5e5132646070be25c7d32f9f0aceb1f4a7<br /><br />Tested successfully<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11478">issues.joomla.org/tracker/joomla-cms/11478</a>.</sub>

**Comment by BiancaCrown** [comment]
I have tested this item succesfully<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11478">issues.joomla.org/tracker/joomla-cms/11478</a>.</sub>

**Comment by jeckodevelopment** [comment]
@brianteeman can you please look at conflicts?

**Comment by brianteeman** [comment]
Closed - it was quicker to redo than look at the merge conflict

See #13013

**Pull request closed without merging**
