### PR TITLE
[4.0] Update Bootstrap to 5.1.1

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # .

### Summary of Changes
- Update to 5.1.1
- refactor the root colours to use the custom ones
- remove the empty mixin file and all the calls to it

### Testing Instructions
Apply the patch
Run `npm ci`

Check that ALL 3 templates are ok, not broken **AND** customising the colours still works as expected

### Documentation Changes Required

NO

Some short explanations of what's happening here:
- We override the _root.scss of the bootstrap
- In the variables, we place all the Atum specific variables in an array `$atum-colors`
- The $body-color is removed from the variables as it's already converted to CSS VAR in the bootstrap source https://github.com/twbs/bootstrap/blob/1df098361cac04217d6a464c80e890c4335ecb5c/scss/_root.scss#L47 and we assign it to the Atum custom CSS Var
- The root loops the `$atum-colors` and appends the CSS VARS to the `:root`
- The mixin part was just a cleanup

### CODE REVIEW

**Comment by PhilETaylor** [comment]
Doesnt this need to be based on `4.1-dev` and not `4.0-dev` ?

**Comment by dgrammatiko** [comment]
> Doesnt this need to be based on 4.1-dev and not 4.0-dev ?

I didn't break anything (I hope) and it's just an update of some dependency so it should be fine for 4.0.x

**Comment by PhilETaylor** [comment]
Im pretty sure Teeman said it could not go in 4.0.x somewhere.

**Comment by dgrammatiko** [comment]
> Im pretty sure Teeman said it could not go in 4.0.x somewhere.

I thought also that it couldn't be done in a B/C way, but here we are...

**Comment by PhilETaylor** [comment]
If you are happy, then cool. I was just repeating what I had read elsewhere.

**Comment by dgrammatiko** [comment]
> If you are happy, then cool. I was just repeating what I had read elsewhere.

I'm never happy when it comes to BS 😂

**Comment by Quy** [comment]
Unrelated changes in ` templates/system/`?

**Comment by dgrammatiko** [comment]
> Unrelated changes in templates/system/?

These files need to be committed anyways. Check https://github.com/joomla/joomla-cms/issues/35413 and https://github.com/joomla/joomla-cms/pull/35098#issuecomment-900697028, in short, the Github actions should do that or someone needs to create a PR whenever the Github action runs...

**Comment by brianteeman** [comment]
```
Processing Legacy js file: template.es5.js...
Error: $color: var(--template-text-dark) is not a color.
   ╷
37 │   @return red($value), green($value), blue($value);
   │           ^^^^^^^^^^^
   ╵
  media\vendor\bootstrap\scss\_functions.scss 37:11                  to-rgb()
  media\vendor\bootstrap\scss\_variables.scss 423:13                 @import
  administrator\templates\atum copy\scss\vendor\_bootstrap.scss 6:9  @import
  administrator\templates\atum copy\scss\template.scss 11:9          @import
  administrator\templates\atum copy\scss\template-rtl.scss 1:9       root stylesheet
npm ERR! code 1
npm ERR! path C:\htdocs\joomla-cms
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c node build/build.js --prepare
```

**Comment by dgrammatiko** [comment]
> atum copy

@brianteeman in your custom template (atum copy) do the following 
- apply the changes in variables 
- add the _root.scss in the template's scss root folder (copy from here and diff it)
- in your scss/vendor/_bootstrap.scss edit the line for the root to point in your template/scss/_root.scss

**Comment by brianteeman** [comment]
You have better eyes than me. I didnt even realise it was "atum copy". Something left over from a previous test. As its not relevant for testing this PR I deleted it and reran npm ci and it now completes. I can now test and make sure all the core templates work etc

**Comment by brianteeman** [comment]
The admin template seems to work fine and the color settings in the styles all work.
The site template seems to work fine and the font settings all work
The installation template seems to work fine.

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 574932a3a0b7c5d8d0f37ce39afebc330b5944a5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35518">issues.joomla.org/tracker/joomla-cms/35518</a>.</sub>

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on 574932a3a0b7c5d8d0f37ce39afebc330b5944a5<br /><br />Everything seems to work! Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35518">issues.joomla.org/tracker/joomla-cms/35518</a>.</sub>

**Comment by RickR2H** [comment]
I have tested this item :red_circle: unsuccessfully on 574932a3a0b7c5d8d0f37ce39afebc330b5944a5<br /><br />@dgrammatiko I noticed that the installer template now has an issue with the header color<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35518">issues.joomla.org/tracker/joomla-cms/35518</a>.</sub>

Also the border of the dropdown is gone.

Image 3

**Comment by dgrammatiko** [comment]
@RickR2H Nice catch, should be ok now with https://github.com/joomla/joomla-cms/pull/35518/commits/e2580b050cbcc4f33ae7d0bd0a4af05dc9f0cda2

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on 076461f8513be8f7dbfe6af7e2da4621d1ef7f9e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35518">issues.joomla.org/tracker/joomla-cms/35518</a>.</sub>

**Comment by RickR2H** [comment]
@dgrammatiko Much better :smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35518">issues.joomla.org/tracker/joomla-cms/35518</a>.</sub>

**Comment by dgrammatiko** [comment]
@wilsonge you probably want to merge this for 4.0.3

**Comment by PhilETaylor** [comment]
4.0.3-rc1 has already been cut, surely its now too late to slip in a major css framework update before the release?

**Comment by dgrammatiko** [comment]
> its now too late to slip in a major css framework update

It's not a major update, it's a patch and it doesn't break anything. Also provides a handful of fixes for bugs. Reminder: BS is already 2 releases behind in J4.

**Comment by PhilETaylor** [comment]
If this (or anything that is not a fix of something already in the RC) is merged after a Release Candidate is released, then that makes a mockery of the RC status. 

But then, Joomla does that all the time /facepalm....

**Comment by dgrammatiko** [comment]
Never mind, I missed the RC part...

**Comment by PhilETaylor** [comment]
[Joomla! 4.0.3 Release Candidate](https://github.com/joomla/joomla-cms/releases/tag/4.0.3-rc) @wilsonge wilsonge released this 32 minutes ago

**Comment by RickR2H** [comment]
We choose BS and imho falling behind is not the best way to go. We should at least keep external frameworks as updated as possible or not choose them at all. Technically it is a fix, as it is fixing BS issues.

**Comment by PhilETaylor** [comment]
Its not my decision thankfully. 

Joomla commits to SemVer - however a release candidate is not part of the definition in SemVer it seems, apart from it being called a "pre-release" version which can have a version number appended by an identifier. 

A release candidate "is a beta version with potential to be a stable product, which is **ready to release** unless significant bugs emerge" according to wikipedia. 

The clue is in the word "candidate" - [it is a "candidate" to be released as the official](https://www.drupal.org/docs/8/understanding-drupal-version-numbers/what-are-alpha-and-beta-releases-and-release-candidates#s-release-candidates) stable version. 

But Im sure the Joomla project will just run roughshod through established software lifecycle processes and merge this before next tuesday, it has repeatedly done so in the past.

**Comment by wilsonge** [comment]
Targeting this for 4.0.4. It was too late for 4.0.3 

FWIW normally release candidates are 1 week before the stable (for patch versions) - but I was massively late cutting it due to coming back from holiday and being hit with a mega backlog at work on my return.

**Comment by dgrammatiko** [comment]
@wilsonge copy that. I'll guess we have to hold this for a bit as 5.1.2 is `ante portas` https://github.com/twbs/bootstrap/projects/43

**Comment by wilsonge** [comment]
It's fine let's get this in. Bug fix versions should be a very simple `npm update`. I'd rather give people as much time as possible to report any potential issues with the CSS vars

**Comment by dgrammatiko** [comment]
@wilsonge your call

**Comment by richard67** [comment]
@dgrammatiko This PR has a merge conflict now in the package-lock.json file. It comes from the recently merged PR #35605 . Could you solve that and update your branch? Thanks in advance.

**Comment by dgrammatiko** [comment]
I will run again `npm I` but maybe we should add `package-lock.json` and `composer.lock` to the `.gitignore` and update them using an action on every PR merge (assuming there's some changes that need to be committed). My 2c for this as it keeps bothering, to put it nicely, every contributor...

**Comment by thednp** [comment]
Let's get this done. Adding the `package-lock.json` to .gitignore is a great idea. I would get built on any `npm install` / `npm update` command anyways.

**Comment by thednp** [comment]
Guys can we please push this in? I have a couple PRs depending on it.

**Comment by dgrammatiko** [comment]
@thednp it still needs 2 tests...

**Comment by thednp** [comment]
OK now that the conflicts have been solved, let's get to testing.

**Comment by thednp** [comment]
I cannot find the PR on JTracker.

**Comment by dgrammatiko** [comment]
> I cannot find the PR on JTracker.

https://issues.joomla.org/tracker/joomla-cms/35518

**Comment by thednp** [comment]
image

Build successful on my local clone of your branch.

Should I also perform a quick install?

**Comment by dgrammatiko** [comment]
> Should I also perform a quick install?

Yes, you need to confirm that all 3 templates (installation, front end, back end) are still good

Edit: irrelevant but what are the specs of your machine? (I'm concerned that the tools took 72 seconds to finish)

**Comment by thednp** [comment]
Win 10, 8 core CPU, latest XAMPP APACHE server v3.3.0.

BTW, how do you guys create those sample data plugins?

**Comment by thednp** [comment]
OK my test looks good, installer, admin template and front-end template, all looking good. I should confirm the test on the tracker now?

**Comment by thednp** [comment]
Unrelated: I couldn't install "Testing Sample Data" for some reason, there was an AJAX error.

**Comment by dgrammatiko** [comment]
> Unrelated: I couldn't install "Testing Sample Data" for some reason, there was an AJAX error.

As you said, unrelated, but maybe it's a good idea to create an issue for that

> BTW, how do you guys create those sample data plugins?

Well, the core has a different way but I have my own https://github.com/dgrammatiko/sloth-pkg/tree/main/plg_sampledata The sampledata is for the sloth template (an SPA-PWA template+, totally different thing than the usual MPA stuff people do with Joomla) https://github.com/dgrammatiko/sloth

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on dcfde0d374f88253893449532a8e4c04fe48ee62<br /><br />Tested all 3 templates and could not find irregularities.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35518">issues.joomla.org/tracker/joomla-cms/35518</a>.</sub>

**Comment by dgrammatiko** [comment]
@thednp could you mark your test as successful in the tracker so this could be finally merged?

**Comment by thednp** [comment]
I have tested this item :white_check_mark: successfully on dcfde0d374f88253893449532a8e4c04fe48ee62<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35518">issues.joomla.org/tracker/joomla-cms/35518</a>.</sub>

**Comment by thednp** [comment]
RTC

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35518">issues.joomla.org/tracker/joomla-cms/35518</a>.</sub>

**Comment by dgrammatiko** [comment]
@wilsonge friendly reminder 😆

**Comment by wilsonge** [comment]
I'm so sorry - one last merge conflict fix?

**Comment by dgrammatiko** [comment]
@wilsonge done

**Comment by wilsonge** [comment]
Thanks!

**Comment by peteruoi** [comment]
https://blog.getbootstrap.com/2021/10/05/bootstrap-5-1-2/

**Comment by dgrammatiko** [comment]
@peteruoi well, that was expected: https://github.com/joomla/joomla-cms/pull/35518#issuecomment-921250255
The PR for updating to 5.1.2 should be fairly easy for anyone, the 5.1 was harder as there were breaking changes in the templates

EDIT: @peteruoi please test https://github.com/joomla/joomla-cms/pull/35766

**Pull request merged**
