### PR TITLE
[privacy] Style com-privacy 'wells' to match com-cpanel

### PR DESCRIPTION
**Pull request by ciar4n**
Pull Request for Issue # .

### Summary of Changes
What it says on the tin

### Testing Instructions
Navigate to Users -> Privacy

### Before
image

### After
image

### CODE REVIEW

**Comment by brianteeman** [comment]
From the screenshot it appears that you have removed the alternate row background. All the modules on the control panel have that

**Comment by mbabker** [comment]
It's still there (you can see it on the Mail Sending row at the bottom), it looks like the mouse in the second screenshot is hovered on the menu item check which darkens the background.

**Comment by ciar4n** [comment]
Looks like I hovered one of the items when taking the screenshot. Screenshot updated.

**Comment by brianteeman** [comment]
That's what happens when I try to review pr on a tablet :)

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on a291f297affac48b29f680a75400e7711c237913<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22274">issues.joomla.org/tracker/joomla-cms/22274</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on a291f297affac48b29f680a75400e7711c237913<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22274">issues.joomla.org/tracker/joomla-cms/22274</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22274">issues.joomla.org/tracker/joomla-cms/22274</a>.</sub>

**Pull request merged**
