### PR TITLE
[4.0] Invalid data in installation sql

### PR DESCRIPTION
**Pull request by brianteeman**
The asset title being created is COM_WORKFLOW_DEFAULT_WORKFLOW but it should be "Joomla Default"

The data in this table is used in the debug permissions view.

PR for #23794

### CODE REVIEW

**Comment by SharkyKZ** [comment]
No, it shouldn't be translated. If you create a new workflow, its title won't be translated.

**Comment by brianteeman** [comment]
Sorry I don't understand your comment.

**Comment by SharkyKZ** [comment]
If you create a new workflow with language constant as title, it will appear untranslated in debug permissions view anyways. The same is true for workflow stages and component names.

**Comment by infograf768** [comment]
See:
https://github.com/joomla/joomla-cms/issues/23794#issuecomment-461741375

the issue is not only for that string.

**Comment by infograf768** [comment]
To solve this specific issue and most other not translated, we need to add
`Factory::getLanguage()->load('com_workflow', JPATH_ADMINISTRATOR);
in `/administrator/components/com_users/Model/DebuguserModel.php`

populate state method
as well as add `<?php echo $this->escape(Text::_($item->title)); ?>`
in
`administrator/components/com_users/tmpl/debuguser/default.php`
It will not translate all assets possible, but many.

**Comment by infograf768** [comment]
If anyone interested I can make PR

**Comment by infograf768** [comment]
In fact, will do patch as we also need to add some new strings in com_users.ini to cope for all the Unpublished, Published, etc.

**Comment by infograf768** [comment]
Please test https://github.com/joomla/joomla-cms/pull/23992

**Pull request closed without merging**
