### PR TITLE
[5.2] Fix public folder path when trailing slash is added

### PR DESCRIPTION
**Pull request by bembelimen**
### Summary of Changes
Remove any trailing slashes for public folder path constant

### Testing Instructions
- Install a Joomla! 5.2 via the console using a public folder (description here: https://github.com/joomla/joomla-cms/pull/41446 )
- make sure you add a slash at the end of your public folder path
- finish installation
- check e.g. if the scheduler ajax call works (via the browser console)

### Actual result BEFORE applying this Pull Request
- error: Site not found

### Expected result AFTER applying this Pull Request
- ajax call works
- no trailing slash in the defines.php in your public folder

@dgrammatiko probably you could check if you agree

thanks @HLeithner for helping debugging.

### CODE REVIEW

**Review by dgrammatiko — APPROVED** [review]

**Review by HLeithner — APPROVED** [review]

**Comment by dgrammatiko** [comment]
@bembelimen probably worth mentioning that this happens on windows based OSes

**Comment by HLeithner** [comment]
I have tested this item :white_check_mark: successfully on 54beab800f9d5c05a6b2fefa09c2ccce952e604d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44340">issues.joomla.org/tracker/joomla-cms/44340</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 54beab800f9d5c05a6b2fefa09c2ccce952e604d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44340">issues.joomla.org/tracker/joomla-cms/44340</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44340">issues.joomla.org/tracker/joomla-cms/44340</a>.</sub>

**Pull request merged**
