### PR TITLE
Set correct default values for user creation in the backend

### PR DESCRIPTION
**Pull request by zero-24**
### Summary of Changes

https://github.com/joomla/joomla-cms/blob/3.6.4/administrator/components/com_users/config.xml#L45-L68

Default values should be send mail to admin and admin activation.

That comes form here: https://github.com/joomla/joomla-cms/commit/cedd2d2e518b733c5fabfab45ce099709faccf69 and got reverted between that. This implements it back.
### Testing Instructions

install https://github.com/zero-24/joomla-cms/archive/install_SQL.zip
confirm the settings are equal to the XML
### Documentation Changes Required

None.

### CODE REVIEW

**Comment by brianteeman** [comment]
wow that was a really old patch of mine https://developer.joomla.org/joomlacode-archive/issue-31319.html

**Comment by zero-24** [comment]
Corrcet and anyhow this got reverted in the SQL files ;)

**Comment by zero-24** [comment]
As this prevents using wrong and insecure default configurations I hope we can get this tested?

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on ba0b2ae13ecd80755cc62b4543809cecdf926302<br /><br />on code review. the default in xml is 2 (https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_users/config.xml#L48) so makes sense it's 2 also in sql<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12589">issues.joomla.org/tracker/joomla-cms/12589</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on ba0b2ae13ecd80755cc62b4543809cecdf926302<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12589">issues.joomla.org/tracker/joomla-cms/12589</a>.</sub>

**Comment by zero-24** [comment]
Thanks RTC. 👍 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12589">issues.joomla.org/tracker/joomla-cms/12589</a>.</sub>

**Pull request merged**
