### PR TITLE
[4.0] Remove unused files

### PR DESCRIPTION
**Pull request by brianteeman**
These files are not used in j4 and were only kept in j3 for potential b/c issues with 3pd admin templates so they can be safely deleted now.

Better to delete them than to continually keep updating them when they're not being used

### CODE REVIEW

**Comment by brianteeman** [comment]
It would be great if this could be tested and merged soon. It makes life so much easier if we're not looking at or trying to fix unused views

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 27b1f1c983cb16b9f9ad91d8f77dfa93c14a33a9<br /><br />Applied pr and played a bit on backed without noticing fault for missing files<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25635">issues.joomla.org/tracker/joomla-cms/25635</a>.</sub>

**Comment by Hackwar** [comment]
Please also remove
- administrator/components/com_categories/tmpl/category/edit_metadata.php
- administrator/components/com_contact/tmpl/contact/edit_metadata.php
- administrator/components/com_content/tmpl/article/edit_metadata.php

Please restore
- administrator/components/com_newsfeeds/tmpl/newsfeed/edit.php
- administrator/components/com_newsfeeds/tmpl/newsfeed/edit_associations.php
- administrator/components/com_newsfeeds/tmpl/newsfeed/edit_display.php
- administrator/components/com_newsfeeds/tmpl/newsfeed/modal.php

**Comment by brianteeman** [comment]
@Hackwar thanks for testing. There is another PR which iirc is for the contact files but I will double check - I will also double check the newsfeeds files

**Comment by brianteeman** [comment]
@Hackwar should be all ok now - thanks

**Comment by Hackwar** [comment]
Looking at the associations file, that is pretty much useless. That one line can very well be moved to the main file and all that boilerplate code could be removed. Haven't looked at the other association files, but I fear they are all the same. In that case that is a bunch of files that could go as well, but maybe in a different PR.

**Comment by brianteeman** [comment]
agree but in a different pr

**Comment by brianteeman** [comment]
This PR is for unused files - another PR for changed files. Single purpose PR :)

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
