### PR TITLE
[4.1] Check if var to escape is null

### PR DESCRIPTION
**Pull request by laoneo**
### Summary of Changes
On PHP 8.1 `htmlspecialchars` is not allowing anymore null values. The `HTMLView` escape function needs to handle this.

### Testing Instructions
- Run the webserver on PHP 8.1
- Create an article custom field
- Open the fields list in the back end

### Actual result BEFORE applying this Pull Request
Warning is displayed:
_:  htmlspecialchars(): Passing null to parameter #1 ($string) of type string is deprecated in /libraries/src/MVC/View/HtmlView.php on line 257_

### Expected result AFTER applying this Pull Request
Field group value is empty.

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 19a4a28b816b01c7d329099400bd3fb235e888c3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37319">issues.joomla.org/tracker/joomla-cms/37319</a>.</sub>

**Comment by dgrammatiko** [comment]
I have tested this item :white_check_mark: successfully on 19a4a28b816b01c7d329099400bd3fb235e888c3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37319">issues.joomla.org/tracker/joomla-cms/37319</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37319">issues.joomla.org/tracker/joomla-cms/37319</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37319">issues.joomla.org/tracker/joomla-cms/37319</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
