### PR TITLE
[4.0] Move the XML forms out of the model folder

### PR DESCRIPTION
**Pull request by laoneo**
### Summary of Changes
With the move to namespaces, we didn't touch the location of the component form files, eg. _article.xml_. They are still in a folder like _/components/com_content/models/formsl_. This location was valid when we had the models in that folder. Now the model classes are in a different folder. So I think the form files should be moved to a location where it makes more sense and obvious for new component developers.

This pr moves the form files to the root **forms** folder within the component root folder. So _/components/com_content/models/forms/article_ becomes _/components/com_content/forms/article.xml_.

This pr was inspired by #15221 and is fully BC compatible as all the rest of the edit forms should work as before. If this pr get accepted, we need to move all the form files of all the namespaced components.

### Testing Instructions
- Open an article in the back end and save it
- Edit an article on the front

### Expected result
All should work as before.

### Actual result
Nothing is broken all should work.

### Documentation Changes Required
This new location needs to be documented.

### CODE REVIEW

**Comment by izharaazmi** [comment]
Great. I always wanted this change. However, I'd prefer the singular `Form` over `forms`.

For field path and rule path, I'd suggest them to be inside this `form` folder like `Form/Field` and `Form/Rule` which IMO also agrees to the namespace pattern.

**Comment by mbabker** [comment]
Eventually the PHP classes should move to a file path where they get autoloaded.  But there is a fair bit of work needed with `JForm` to get there (including support for namespaced classes and deciding when we're going to do the B/C break of not having every core extension's form classes using the `JForm` class prefix).

**Comment by izharaazmi** [comment]
Alright. I can't say I get that exactly. Since I've not yet stepped into 4.x dev I find myself ineligible to speak much. My `joomla.todo` is still filled with 3.x stuffs. All the best everyone here. I'll be catching up soon. ☺

**Comment by laoneo** [comment]
An approach how to namespace JForm can be found in this pr https://github.com/joomla/joomla-cms/pull/15893. I would not mix xml files and PHP classes in the same folder. Thats why the forms folder is lowercase and should only contain xml files. IMO the field classes should belong into the Field folder.

**Comment by mbabker** [comment]
FWIW in the Framework repo we actually deprecated and removed in full support for looking up class objects using the file path lookups in favor of full autoloading support, so the only file path stuff left there is for the XML files (for obvious reasons).  That should be our long term goal with the CMS, it's just going to be a painfully long transition.

**Pull request merged**
