### PR TITLE
[4.0] [Atum] Unused constants

### PR DESCRIPTION
**Pull request by Kostelano**
### Summary of Changes
Unused constants in the Atum template.

### CODE REVIEW

**Comment by rjharishabh** [comment]
I have tested this item :white_check_mark: successfully on cf55c7fcb3af3c19b0f06e920b080a21d1cf7c6b<br /><br />Confirmed, not used anywhere<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34186">issues.joomla.org/tracker/joomla-cms/34186</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on cf55c7fcb3af3c19b0f06e920b080a21d1cf7c6b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34186">issues.joomla.org/tracker/joomla-cms/34186</a>.</sub>

**Comment by chmst** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34186">issues.joomla.org/tracker/joomla-cms/34186</a>.</sub>

**Comment by Quy** [comment]
Thank you!

**Pull request merged**
