### PR TITLE
[4.0] Size is not a valid attribute for number

### PR DESCRIPTION
**Pull request by brianteeman**
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/number

Attribute 'size' is only allowed when the input type is 'text', 'search', 'url', 'tel', 'email' or 'password'.

<input> elements of type "number" don't support form sizing attributes such as size.

### CODE REVIEW

**Comment by cyrez** [comment]
We may remove size from layout too, so : https://github.com/joomla/joomla-cms/blob/4.0-dev/layouts/joomla/form/field/number.php#L53

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on c8ab9fc09da3d1a69763b4a8fc1ae5e12f466081<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20973">issues.joomla.org/tracker/joomla-cms/20973</a>.</sub>

**Comment by cyrez** [comment]
I have tested this item :white_check_mark: successfully on c8ab9fc09da3d1a69763b4a8fc1ae5e12f466081<br /><br />@brianteeman You're welcome!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20973">issues.joomla.org/tracker/joomla-cms/20973</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20973">issues.joomla.org/tracker/joomla-cms/20973</a>.</sub>

**Comment by brianteeman** [comment]
Thanks for the fast tests and merge

**Pull request merged**
