### PR TITLE
[4.0] Delete unused password lang strings + update api joomla.ini

### PR DESCRIPTION
**Pull request by infograf768**
Pull Request for Issue https://github.com/joomla/joomla-cms/pull/32506#issuecomment-785745439

### Summary of Changes
Delete 2 unused strings
```
JFIELD_PASSWORD_NOTE_DESC="%1 symbol(s), %2 uppercase letter(s), %3 lowercase letter(s), %4 number(s)"
JFIELD_PASSWORD_NOTE_LBL="Password must contain:"
```
Also updating api joomla.ini which should be in sync with administrator joomla.ini

Can be merged on review.

### CODE REVIEW

**Comment by brianteeman** [comment]
This is as a result of https://github.com/joomla/joomla-cms/pull/30473/

**Comment by particthistle** [comment]
I have tested this item :white_check_mark: successfully on 8729603ca75dfbf0bf0941dafd0db8598945e596<br /><br />I concur that I can't find the strings proposed to be removed in use anywhere else.
Additions to API Joomla.ini also look correct.

_I'll get some more language string education later to work out why there needs to be api/language/en-GB/joomla.ini when all those strings are in language/en-GB/joomla.ini_<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32546">issues.joomla.org/tracker/joomla-cms/32546</a>.</sub>

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on 8729603ca75dfbf0bf0941dafd0db8598945e596<br /><br />Tested successfully in Beta8-dev of 3 March.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32546">issues.joomla.org/tracker/joomla-cms/32546</a>.</sub>

**Comment by infograf768** [comment]
rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32546">issues.joomla.org/tracker/joomla-cms/32546</a>.</sub>

**Comment by Quy** [comment]
Thanks

**Pull request merged**
