### PR TITLE
Merge branch 4.2 into 4.3

### PR DESCRIPTION
**Pull request by obuisard**

### CODE REVIEW

**Comment by richard67** [comment]
Why is this PR deleting the 4.2 update SQL scripts?

**Comment by obuisard** [comment]
Hi Richard, it was not meant to. I am just doing an up merge and I have not taken any action on this yet (setting up my local environment to deal with the conflicts).

**Comment by richard67** [comment]
@obuisard The 2 update SQL scripts have been deleted in the 4.2-dev branch when reverting PR #38244 . But that was maybe not right. I do not have the time today to check that deeper.

**Comment by obuisard** [comment]
> @obuisard The 2 update SQL scripts have been deleted in the 4.2-dev branch when reverting PR #38244 . But that was maybe not right. I do not have the time today to check that deeper.

@richard67 I will take a look today and see if I can lift the doubt on this deletion. Thank you Richard!

**Comment by obuisard** [comment]
Apparently, as @richard67 posted in the CMS Maintenance team, the deleted files need to be added to script.php so they are removed on update.

**Comment by richard67** [comment]
> Apparently, as @richard67 posted in the CMS Maintenance team, the deleted files need to be added to script.php so they are removed on update.

Yes but that should have been done in the 4.2-dev branch. And it would have been better not to delete the files but just to comment out the content, and possibly it would even have been necessary to add new update SQL scripts which delete the records added by the deleted script on a 4.2.0. RC1.

@roland-d I would have expected to be contacted when such a thing happens, reverting a PR which has update SQL scripts.

**Comment by richard67** [comment]
And when we remove them again on update, the database checker will complain about not matching schema version. As this will only happen when updating a 4.2.0 RC 1, I tend to ignore that for now, i.e. do nothing and leave things as they are.

**Comment by obuisard** [comment]
Ok, I am taking note so that I remember that next time I run into such issue

**Pull request merged**
