### PR TITLE
[4.3] Replace Factory::getUser() by $this->getCurrentUser() in components models

### PR DESCRIPTION
**Pull request by joomdonation**
Pull Request for Issue # .

### Summary of Changes
With https://github.com/joomla/joomla-cms/pull/37498/ being merged into 4.2, we can now replace deprecated method `Factory::getUser()` in components model classes with new method `$this->getCurrentUser()`

### Testing Instructions
1. Use Joomla 4.2 nightly build
2. Apply patch
3. Access to random pages (frontend, backend), make sure nothing is broken.

### Actual result BEFORE applying this Pull Request
Works, but uses deprecated methods.

### Expected result AFTER applying this Pull Request
Works, without using deprecated methods.

### CODE REVIEW

**Review by laoneo — APPROVED** [review]

**Comment by laoneo** [comment]
I'm wondering if we should fallback [here](https://github.com/joomla/joomla-cms/blob/4.2-dev/libraries/src/User/CurrentUserTrait.php#L46) to `Factory::getUser` instead of an empty user?

**Comment by joomdonation** [comment]
`Factory::getUser` would be more safe, I think (I believe in site, administrator and api applications, the fallback is not needed). I just don't know how it is used in installation and console apps.

**Comment by laoneo** [comment]
Do you want to do it here or a separate one?

**Comment by joomdonation** [comment]
Better in the separate PR, please

**Comment by laoneo** [comment]
Here we go #38106.

**Comment by laoneo** [comment]
Would be good to postpone this for 4.3. What do you think @joomdonation?

**Comment by joomdonation** [comment]
@laoneo Yes, no rush. Let's give maintainers more time to review to see if there is any flow with this change.

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on c19a04a8be0571d3aee6e3e9a046ad8c1be8a727<br /><br />Tested good on frontend and backend pages in Joomla 4.3 dev

Drone is erroring out but looks like a timeout issue so I do not believe this related.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38090">issues.joomla.org/tracker/joomla-cms/38090</a>.</sub>

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on c19a04a8be0571d3aee6e3e9a046ad8c1be8a727<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38090">issues.joomla.org/tracker/joomla-cms/38090</a>.</sub>

**Comment by RickR2H** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38090">issues.joomla.org/tracker/joomla-cms/38090</a>.</sub>

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
