### PR TITLE
Adjusting the order of two strings

### PR DESCRIPTION
**Pull request by tecpromotion**
### Summary of Changes

Sorting alphabetically.

### Expected result

COM_CONFIG_FIELD_DEBUG_CONST_LANG_DESC
COM_CONFIG_FIELD_DEBUG_CONST_LANG_LABEL

### Actual result

COM_CONFIG_FIELD_DEBUG_CONST_LANG_LABEL
COM_CONFIG_FIELD_DEBUG_CONST_LANG_DESC

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on ef8929b91b9e64b159e72b3a78c73acec24b3c22<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22131">issues.joomla.org/tracker/joomla-cms/22131</a>.</sub>

**Review by brianteeman — COMMENTED** [review]
Approve language change

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on ef8929b91b9e64b159e72b3a78c73acec24b3c22<br /><br />review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22131">issues.joomla.org/tracker/joomla-cms/22131</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22131">issues.joomla.org/tracker/joomla-cms/22131</a>.</sub>

**Pull request merged**
