### PR TITLE
[4.3] mod_article_news logical css operators

### PR DESCRIPTION
**Pull request by brianteeman**
Simple PR to change to use logical css operators thus avoiding any potential issues with RTL sites

code review should be enough as there is no visible change

### CODE REVIEW

**Comment by ReLater** [comment]
I have tested this item :white_check_mark: successfully on 3d4377efee3fc8c07027ea24bc0519f691d19708<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39294">issues.joomla.org/tracker/joomla-cms/39294</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 3d4377efee3fc8c07027ea24bc0519f691d19708<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39294">issues.joomla.org/tracker/joomla-cms/39294</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39294">issues.joomla.org/tracker/joomla-cms/39294</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
yay - thanks

**Pull request merged**
