### PR TITLE
[4.0] Composer update

### PR DESCRIPTION
**Pull request by brianteeman**
Package operations: 0 installs, 16 updates, 0 removals
  - Updating symfony/polyfill-php73 (v1.11.0 => v1.12.0): Downloading (100%)
  - Updating sebastian/exporter (3.1.0 => 3.1.1): Downloading (100%)
  - Updating symfony/polyfill-ctype (v1.11.0 => v1.12.0): Downloading (100%)
  - Updating myclabs/deep-copy (1.9.1 => 1.9.3): Downloading (100%)
  - Updating phpunit/phpunit (8.2.5 => 8.3.4): Downloading (100%)
  - Updating joomla-projects/selenium-server-standalone (v3.14.0 => 3.141.59): Downloading (100%)
  - Updating symfony/polyfill-mbstring (v1.11.0 => v1.12.0): Downloading (100%)
  - Updating doctrine/lexer (1.0.2 => 1.1.0): Downloading (100%)
  - Updating doctrine/annotations (v1.6.1 => v1.7.0): Downloading (100%)
  - Updating symfony/polyfill-php70 (v1.11.0 => v1.12.0): Downloading (100%)
  - Updating symfony/polyfill-php72 (v1.11.0 => v1.12.0): Downloading (100%)
  - Updating composer/ca-bundle (1.1.4 => 1.2.3): Downloading (100%)
  - Removing joomla/console (dev-master 58b6a55)
  - Installing joomla/console (dev-master 7032ec0): Downloading (100%)
  - Removing joomla/database (dev-2.0-dev 60a7df9)
  - Installing joomla/database (dev-2.0-dev b87b90e): Downloading (100%)
  - Removing joomla/registry (dev-2.0-dev e3bf30e)
  - Installing joomla/registry (dev-2.0-dev dd6397b): Downloading (100%)
  - Removing joomla/string (dev-2.0-dev 2e09dff)
  - Installing joomla/string (dev-2.0-dev d36c15c): Downloading (100%)

### CODE REVIEW

**Comment by wilsonge** [comment]
System tests are failing and it seems reliably. Can we force the selenium version back to v3.14.0 please? I have a feeling that version is causing us problems because of the force to the browser w3c events. Been having similar issues on the weblinks repo with that selenium version

`composer install joomla-projects/selenium-server-standalone== v3.14.0`

**Comment by richard67** [comment]
The joomla/database package meanwhile has a newer version (commit b90d2c2) than the one mentioned in the description (commit b87b90e). It contains a few recent fixes which should be fetched.

**Comment by brianteeman** [comment]
Updated database and downgraded selenium as requested

**Comment by brianteeman** [comment]
(sorry @wilsonge no idea how to fix this conflict) - tried to do this https://akrabat.com/a-few-composer-tips/

**Pull request closed without merging**
