### PR TITLE
[4.3] Checksum string

### PR DESCRIPTION
**Pull request by brianteeman**
PR for #40303

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on fe998a2209721b39c09ae3f811737041da1c04c7<br /><br />The changed string is less scary and less misleading.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40304">issues.joomla.org/tracker/joomla-cms/40304</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on fe998a2209721b39c09ae3f811737041da1c04c7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40304">issues.joomla.org/tracker/joomla-cms/40304</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40304">issues.joomla.org/tracker/joomla-cms/40304</a>.</sub>

**Comment by obuisard** [comment]
Thank you Brian @brianteeman !

**Comment by brianteeman** [comment]
thx

**Pull request merged**
