### PR TITLE
CSS for flags

### PR DESCRIPTION
**Pull request by brianteeman**
Fix for #13678 reported by @gwsdesk

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 386b9e6e75e8f8be68b3cb818fd520e79357a520<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21254">issues.joomla.org/tracker/joomla-cms/21254</a>.</sub>

**Comment by gwsdesk** [comment]
I have tested this item :white_check_mark: successfully on 386b9e6e75e8f8be68b3cb818fd520e79357a520<br /><br />I have tested this item ✅ successfully on [386b9e6](https://github.com/joomla/joomla-cms/commit/386b9e6e75e8f8be68b3cb818fd520e79357a520 "386b9e6")Thanks for the fix<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21254">issues.joomla.org/tracker/joomla-cms/21254</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
