### PR TITLE
com_plugin - Moved Filters from sidebar to Search Tools

### PR DESCRIPTION
**Pull request by pe7er**
This PR moves Filters from left sidebar to Search Tools.
### Before this PR
1. left side bar has 3 filter options that cannot be reset easily
2. middle column has 2 filter options for ordering that duplicate the ordering of column headers.

plugins_filters_before
### This PR should
1. move Filters from sidebar to Search Tools in middle column. All filters can be reset with the "Clear" button.
2. remove left sidebar
3. remove "Type" + "Ascending" (Sort Table by + Select the ordering) fields because they are duplicate. The ordering field + ordering direction can be set by clicking on a column header (fieldname).

plugins_filters_after

### CODE REVIEW

**Comment by pe7er** [comment]
Thanks for all your Code Style corrections! @zero-24

**Comment by nonumber** [comment]
Wasn't the whole idea to move away from the Search Tools and use the side bar instead?

**Comment by kathastaden** [comment]
1. Move Filters from sidebar to Search Tools in middle column --> **Done**
2. All filters can be reset with the "Clear" button --> **Worked fine**
3. remove left sidebar --> **Is removed**
4. remove "Type" + "Ascending" (Sort Table by + Select the ordering) fields because they are duplicate. The ordering field + ordering direction can be set by clicking on a column header (fieldname) --> **They are removed and the ordering works fine with the column headers**
5. Search Tools --> **Worked fine, search was correct**
6. I did not find any new bugs<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7699">issues.joomla.org/joomla-cms/7699</a>.</sub>

**Comment by watchfulli-dev** [comment]
@test success, after applying the patch the filters from the left side now appear on top under "Search tools", tested filters and they work as expected.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7699">issues.joomla.org/joomla-cms/7699</a>.</sub>

**Comment by zero-24** [comment]
Thanks for the tests and coding :smile: RTC'ing now<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7699">issues.joomla.org/joomla-cms/7699</a>.</sub>

**Comment by pe7er** [comment]
Thanks for testing! @kathastaden & @watchfulli-dev<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7699">issues.joomla.org/joomla-cms/7699</a>.</sub>

**Comment by compojoom** [comment]
@nonumber - that's what I'm wondering as well. Do we have a "design guide" or something. It would be stupid to have the filters once in search tools, then on the right. We should decide what we want to use and then stick to it.

**Comment by pe7er** [comment]
New PR #8146 to replace this one.

**Pull request closed without merging**
