### PR TITLE
Fix comment typo

### PR DESCRIPTION
**Pull request by brianteeman**
categoryg should be category

### CODE REVIEW

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on d092258f3d51f8c5d0b769930a568b953557b5a0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17758">issues.joomla.org/tracker/joomla-cms/17758</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on d092258f3d51f8c5d0b769930a568b953557b5a0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17758">issues.joomla.org/tracker/joomla-cms/17758</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17758">issues.joomla.org/tracker/joomla-cms/17758</a>.</sub>

**Comment by zero-24** [comment]
Thanks.

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
