### PR TITLE
Backend - list views: Alignment fixes for almost all core components (similar to #7384)

### PR DESCRIPTION
**Pull request by manojLondhe**
1. Backend - list views: Table columns alignment fixes for almost all core components (similar to [#7384](https://github.com/joomla/joomla-cms/pull/7384))
2. Remove "." from the end of table heading text for com_checkin

@brianteeman @genesisfan @larapetersen Guys, please check this when you get time...

### CODE REVIEW

**Comment by zero-24** [comment]
@manojLondhe here is a quick CS PR: https://github.com/manojLondhe/joomla-cms/pull/1

**Comment by manojLondhe** [comment]
thanks @zero-24

**Comment by brianteeman** [comment]
The language change is fine - good spot<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7421">issues.joomla.org/joomla-cms/7421</a>.</sub>

**Comment by genesisfan** [comment]
@test @manojLondhe unsuccesfully tested.

I found these issues...
Extentions Manager - Update:
7421 extentions - update
Extentions Manager - Manage
7421 extentions - manage
Extentions Manager - Install Languages
7421 extentions - install languages
Extentions Manager - Update Sites
7421 extentions - update sites
Extentions Manager - Template Manager - Styles
7421 extentions - template manager - styles
Extentions Manager - Template Manager - Templates
7421 extentions - template manager - templates

**Comment by manojLondhe** [comment]
@genesisfan Those are already fixed in [#7384](https://github.com/joomla/joomla-cms/pull/7384)

**Comment by genesisfan** [comment]
Right @manojLondhe <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7421">issues.joomla.org/joomla-cms/7421</a>.</sub>

**Comment by genesisfan** [comment]
@test succesfully tested:
Components > Banners
Components > Contacts > Contacts
Components > Contacts > Categories
Components > News Feeds > News Feeds
Components > News Feeds > Categories
Components > Redirect
Components > Search 
Components > Tags
Content > Category Manager
Menus > Menu Manager > Menus
Menus > Menu Manager > Menu Items
Users > Users Manager > Users / User Groups / Viewing Access Levels / Note Categories
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7421">issues.joomla.org/joomla-cms/7421</a>.</sub>

**Comment by matthewbaylor** [comment]
@test Successful for me in all of the core list views.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7421">issues.joomla.org/joomla-cms/7421</a>.</sub>

**Comment by manojLondhe** [comment]
@matthewbaylor @genesisfan Thanks guys :)

**Comment by zero-24** [comment]
RTC based on testing :smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7421">issues.joomla.org/joomla-cms/7421</a>.</sub>

**Comment by Kubik-Rubik** [comment]
Thank you @manojLondhe and testers. Merged with https://github.com/joomla/joomla-cms/commit/ae3efb07e6085558883e9e5f768b0ca7090bf25b

**Comment by manojLondhe** [comment]
:smile: 
@Kubik-Rubik OK, noted!

**Pull request closed without merging**
