### PR TITLE
[4.0] Remove double spaces

### PR DESCRIPTION
**Pull request by brianteeman**
Looks like this came from a search and replace when converting to bs5

code review

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 717b1159fe2d79ecc1d7426b56436c704c30bcd6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32931">issues.joomla.org/tracker/joomla-cms/32931</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 717b1159fe2d79ecc1d7426b56436c704c30bcd6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32931">issues.joomla.org/tracker/joomla-cms/32931</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32931">issues.joomla.org/tracker/joomla-cms/32931</a>.</sub>

**Comment by Quy** [comment]
Thanks

**Pull request merged**
