### PR TITLE
[4.4] Determine the next task run date with the timezone of the site

### PR DESCRIPTION
**Pull request by laoneo**
### Summary of Changes
When using Cron expressions in a task, then they are always executed in UTC timezone. This leads to an issue when the cron ob should run on a specific time on the day and the Joomla site is in a timezone where the there are DST changes. This pr calculates the next run date according to the timezone of Joomla and displays the next execution date in the same time when editing the task (it is the same time as in the tasks list then).

### Testing Instructions
- Define a timezone in Joomla, other than UTC
- Create a new sleep task and define a cron expression like  
image
- Open the execution history tab

### Actual result BEFORE applying this Pull Request
It shows the UTC time as next execution date.

### Expected result AFTER applying this Pull Request
It shows the correct time as next execution date.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by hytsch** [comment]
checked, works fine, thanks :)

**Comment by fgsw** [comment]
I have tested this item :white_check_mark: successfully on 2a56945fddc07c3a227de65ec77634eeff8ea956<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43259">issues.joomla.org/tracker/joomla-cms/43259</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43259">issues.joomla.org/tracker/joomla-cms/43259</a>.</sub>

**Comment by Quy** [comment]
@laoneo Please fix phpcs. Thanks.

**Comment by MacJoom** [comment]
Thank you!

**Pull request merged**
