### PR TITLE
Fix logic in file upload check introduced in 3.9.5

### PR DESCRIPTION
**Pull request by SolutioAndy**
Pull Request for Issue #24544

### CODE REVIEW

**Comment by zero-24** [comment]
@SniperSister can you please double check this one here.

**Comment by ghost** [comment]
@SolutioAndy thanks for your first.time contribution.

**Review by SniperSister — APPROVED** [review]

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 104f6c71725121a2e38d9dd7595d786ddad4ccce<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24637">issues.joomla.org/tracker/joomla-cms/24637</a>.</sub>

**Comment by hardik-codes** [comment]
I have tested this item :white_check_mark: successfully on 104f6c71725121a2e38d9dd7595d786ddad4ccce<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24637">issues.joomla.org/tracker/joomla-cms/24637</a>.</sub>

**Comment by ghost** [comment]
Status "Ready To Commit".

**Comment by HLeithner** [comment]
thx

**Pull request merged**
