### PR TITLE
[5.1] EmptyState Help links

### PR DESCRIPTION
**Pull request by brianteeman**
### Summary of Changes
Updates the "learn more" links on the emptystate pages to use the J5 version of the infornmation.

If you find any additional J4 links for the emptystate this is probably because a j5 version of the page does not exist on the docs site. Otherwise its a bug and I missed it.

### Testing Instructions
image

### Actual result BEFORE applying this Pull Request
some links go to j4 pages

### Expected result AFTER applying this Pull Request
links go to j5 pages

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 9d002152c7066aa6aebace3888365446afa1e999<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43371">issues.joomla.org/tracker/joomla-cms/43371</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 9d002152c7066aa6aebace3888365446afa1e999<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43371">issues.joomla.org/tracker/joomla-cms/43371</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43371">issues.joomla.org/tracker/joomla-cms/43371</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
