### PR TITLE
en-GB style guide (website)

### PR DESCRIPTION
**Pull request by brianteeman**
the style guide states

> website   One word not capitalised

https://joomla.github.io/user-interface-text/?user-interface-text/words2watch.md
#### Summary of Changes

Simple PR that changes references in strings and sample data to comply with the style guide

### CODE REVIEW

**Comment by MATsxm** [comment]
I have tested this item :white_check_mark: successfully on 895ed76e5918a11f238ddba05dc66415d4021a56<br /><br />Ouch... :+1: 

On code review, Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11294">issues.joomla.org/joomla-cms/11294</a>.</sub>

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on 895ed76

**Comment by brianteeman** [comment]
RTC - thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11294">issues.joomla.org/joomla-cms/11294</a>.</sub>

**Comment by rdeutz** [comment]
@brianteeman could you have a look at the merge conflicts, thanks.

**Comment by wilsonge** [comment]
Merged with https://github.com/joomla/joomla-cms/commit/0f22f7d7c35e114aab6cd09e9134a13ff26059bd

**Pull request closed without merging**
