### PR TITLE
[4.0] Composer update 10Aug

### PR DESCRIPTION
**Pull request by brianteeman**
Package operations: 0 installs, 8 updates, 0 removals
  - Updating maximebf/debugbar (v1.17.0 => v1.17.1)
  - Updating phpunit/phpunit (8.5.18 => 8.5.19)
  - Updating doctrine/annotations (1.13.1 => 1.13.2)
  - Updating composer/xdebug-handler (2.0.1 => 2.0.2)
  - Updating friendsofphp/php-cs-fixer (v2.19.0 => v2.19.1)
  - Updating guzzlehttp/psr7 (1.8.2 => 2.0.0)
  - Updating codeception/codeception (4.1.21 => 4.1.22)
  - Updating ramsey/uuid (3.9.3 => 3.9.4)

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 30150a5fb354ed6fd33f0533a952de037a6761e4<br /><br />Looks all right and works. It only might need to be done again because @wilsonge plans to tag framework packages and update them later, as far as I know.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35081">issues.joomla.org/tracker/joomla-cms/35081</a>.</sub>

**Comment by richard67** [comment]
After this commit in the 4.0-dev branch for updating framework packages, this PR here has merge conflicts which would be hard to solve, I think. https://github.com/joomla/joomla-cms/commit/2be3108fc3206b6a396899d84f4ac9b97a206157

It maybe would be easier to make it new.

**Comment by richard67** [comment]
This PR has been meanwhile replaced by this commit, as far as I can see: https://github.com/joomla/joomla-cms/commit/38469e30ed8807c1f641ddfc5d7fb6897df8128c

**Comment by wilsonge** [comment]
Directly made these changes with https://github.com/joomla/joomla-cms/commit/38469e30ed8807c1f641ddfc5d7fb6897df8128c

**Pull request closed without merging**
