### PR TITLE
Implementing "No Matching Results" in Users modal Fixes #7236 

### PR DESCRIPTION
**Pull request by Kubik-Rubik**
This is a code style review of Brian's PR #7236.

Kudos to @brianteeman and @infograf768!

### CODE REVIEW

**Comment by brianteeman** [comment]
You could have just done a pr against my branch!!

**Comment by Kubik-Rubik** [comment]
@brianteeman Please check my change and add it to your PR. I will close this PR then. Thanks!

**Comment by brianteeman** [comment]
Done

On 23 June 2015 at 13:45, Viktor Vogel <notifications@github.com> wrote:

> @brianteeman <https://github.com/brianteeman> Please check my change and
> add it to your PR. I will close this PR then. Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/7253#issuecomment-114482290>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Kubik-Rubik** [comment]
Thank you, @brianteeman! I close this PR in favor of #7236.

**Pull request closed without merging**
