### PR TITLE
Replaced rand() with mt_rand() projectwide

### PR DESCRIPTION
**Pull request by frankmayer**
mt_rand() is a drop-in replacement for rand() and should be preferred.

Since this is a drop-in replacement, it should not cause any problems to the existing codebase

### CODE REVIEW

**Comment by zero-24** [comment]
Thanks @frankmayer for your PR. There are 3 places i have too revert your change as they are in 3party code.

The framework session package don't use rand in the last version: https://github.com/joomla-framework/session So if we pull the new session package we are ok. Thanks!

**Review by zero-24 — APPROVED** [review]

**Comment by frankmayer** [comment]
Oh, yes, thanks for reminding me - totally forgot about that. So should I do PR's against those external ones, or will you commit those changes?

**Comment by zero-24** [comment]
@frankmayer fof 2.x (which is included in the core) is not active maintained anymore but you can try it at https://github.com/akeeba/fof/tree/fof-2.x

The framework don't use rand anymore: https://github.com/joomla-framework/session/blob/master/Session.php so if we get synced with that we are ok :smile:

**Comment by mbabker** [comment]
The master branch for the session package is the 2.0 branch, there's a
1.x-dev branch which probably still has it since that's basically untouched
beyond having added the deprecation notices for 2.0 and the 3.4 security
fixes.

**Comment by zero-24** [comment]
where is the 1.x-dev branch @mbabker ?
https://github.com/joomla-framework/session/branches/all I can just see a master and 2.0-dev branch

**Comment by mbabker** [comment]
Oh, Nevermind.  Getting confused with other repos.

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 2d830b38a0e68ddce88bde2386d77e81a9e5008f<br /><br />on code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12169">issues.joomla.org/tracker/joomla-cms/12169</a>.</sub>

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on 2d830b38a0e68ddce88bde2386d77e81a9e5008f<br /><br />on review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12169">issues.joomla.org/tracker/joomla-cms/12169</a>.</sub>

**Comment by zero-24** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12169">issues.joomla.org/tracker/joomla-cms/12169</a>.</sub>

**Comment by brianteeman** [comment]
Milestone changed to 3.7 as it is now not planned to have a 3.6.4 release

**Pull request merged**
