### PR TITLE
[4] s/JTable/Table

### PR DESCRIPTION
**Pull request by PhilETaylor**
Code review

### CODE REVIEW

**Comment by joomdonation** [comment]
I have tested this item :white_check_mark: successfully on b4dafa20be2216182ac09f939ae5f7818a0c016e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34009">issues.joomla.org/tracker/joomla-cms/34009</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on b4dafa20be2216182ac09f939ae5f7818a0c016e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34009">issues.joomla.org/tracker/joomla-cms/34009</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34009">issues.joomla.org/tracker/joomla-cms/34009</a>.</sub>

**Comment by richard67** [comment]
Thanks.

**Pull request merged**
