### PR TITLE
Fix non gregorian calendars inconsistencies pt2

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue #16794 .

### Summary of Changes
- Fix the parser for Jalali calendar
- Fix the `data-alt-value` to be always Gregorian!
- Bonus: Run the on submit event only one time!

### Testing Instructions
Create a new article and fill the publishing fields with different methods (manual using the UI)
save the article
Edit again the fields (try clearing the filed with backspace, the clear button) and also change the values manually and using the UI

Repeat the tests with fa-IR as your admin language

Report any remaining inconsistencies, if any

### Expected result
Values are always consistent!

### Actual result
Inconsistent values when a value was typed in 

@farzadtaheri @farhadst can you please test here!

### CODE REVIEW

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 83ff2fb399b10cccdc68b7944194fb2dd79c3b4d<br /><br />Works fine now !

Test instructions for non-Persian speakers.
Install Persian language.
Apply patch on staging or RC2.
Create a new article and save. Keep the page open on the Publishing tab.

Then switch to Persian by opening a new instance of admin in the browser and go back to the page displaying the article just created, reload the page.

In the Finish Publishing Calendar Field enter a date in the future `۱۳۹۶-۰۶-۲۶ ۱۴:۳۰:۰۰` which is the equivalent of `2017-09-17 14:30:00` for en-GB.
Save again. The calendars fields will display for a second the UNIX date i.e. `2017-09-17 14:30:00` and then the new Jalali date which has been entered.


<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16922">issues.joomla.org/tracker/joomla-cms/16922</a>.</sub>

**Comment by infograf768** [comment]
jalali_corrected

**Comment by farhadst** [comment]
I have test this item and manual date is works fine by persian number or latin number, just in edit manual date, after save item, day change to 1 day ago
i think this issue is for calculate 30 or 31 day month
screencapture_17-07-01_11 47 25

**Comment by farhadst** [comment]
I can not select the first month manually. After changing to first month and saving the month, it changes to the second month
screencapture_17-07-01_12 07 49

**Comment by infograf768** [comment]
@farhadst 
Not sure you tested correctly
The start Publishing date can't be set to a date older than the Created date.
Please try using a date = or >Created date

Test this case:
Created date = Start Publishing date.
Created date is `۱۳۹۶-۰۴-۰۹ ۱۳:۵۷:۰۰` (this will be displayed as rtl when Persian language is used. (Equivalent Gregorian is `2017-06-30 13:57:00`)

screen shot 2017-07-01 at 10 43 35

Now, in Start Publishing change the day only by pasting `۱۰` to replace `۰۹` (i.e. `10` to replace `09` and save.

I get here while it is saving:
screen shot 2017-07-01 at 10 49 46

Which is the correct Gregorian date as we have 30 days in June, so 1 day more (today in fact here) is July 1. (2017-07-01 13:57:00)
And when jalali displays again

screen shot 2017-07-01 at 10 52 02

Which is exactly what is desired at the beginning.

As far as months are concerned
Is'nt `۰۴` before `۰۵` ? In this case, when you modify the Start publishing and the Created  Date is `۰۴` , you should use `۰۵` . This works fine here.

This why **I tested the Finish Publishing field with a future date**, to be independent from the Created vs Start vs Finish

**Comment by farhadst** [comment]
@infograf768
I do not think it's related to Created date
(I changed the numbers to Latin to be clearer)
I test again 
create date is before published and no effect in result
I think this issue is for calculate 30 or 31 days month
In the Jalali calendar, the first 6 months are 31 days (Apr-May-Jun-Jul-Aug-Sep) and 5 months later are 30 days and Twelfth month are 29 days

And still The first month can not be set manual even in Created date

screencapture_17-07-01_16 04 05

**Comment by dgt41** [comment]
@farhadst can you edit the layout and remove these lines: https://github.com/joomla/joomla-cms/blob/staging/layouts/joomla/form/field/calendar.php#L98-L104

Of course you will not have a jallali date, but can you try doing the same test there? What's the results?

**Comment by farhadst** [comment]
@dgt41 
after remove lines from 98 to 104 on calendar.php the calendar is displayed as Gregorian
d

**Comment by farhadst** [comment]
@dgt41
after remove lines from 98 to 104 on calendar.php the calendar is displayed as Gregorian
And edit manual date by Gregorian calendar to any date work fine but if set invalid date like 2017-02-30 12:10:00 ,after save calendar change to next valid date.

screencapture_17-07-01_19 15 51

**Comment by dgt41** [comment]
@farhadst so to compare that to jallali calendar, what's different? Was the value (in the jallali test) a valid date, if not then this was expected (nothing to do with the calendar, this is the php side validation.

**Comment by farhadst** [comment]
@dgt41 I have check again
The value of selected date in the Jalalil calendar is correct
This problem happens when the value is set manually and there is no problem if the same value of pop-up is added.
I reviewed many days in different months by manual
If one of the January (12/10 to 11/11 jalali) days is chosen according to Jalali, one day will be added
to date, for example if set 1396-10-13 (3January) and save it, date change to 1396-10-14
any date In February, 1 day is added to the selected date
any date In March, 2 days from the chosen date will be reduced
any date In April, no day can be chosen and if set any date, this change to the first of may
any date In may, 1 days from the chosen date will be reduced
There is no problem in June
any date In july, 1 days from the chosen date will be reduced
There is no problem in August and September
any date In October, 1 days from the chosen date will be reduced
any date In November, 1 day is added to the selected date 
There is no problem in December

screencapture_17-07-02_12 41 04

**Comment by dgt41** [comment]
@farhadst I think I had an error in this patch, now should be ok, please test again!
Thanks

**Comment by farhadst** [comment]
@dgt41 i have replace new file but get new issue
In this case, after manually entering the date and saving it, the year will not be converted and changed incorrectly
but in set date by popup no problem

screencapture_17-07-03_10 48 26

**Comment by infograf768** [comment]
@rdeutz 
This should not be merged if this https://github.com/joomla/joomla-cms/pull/16922/commits/bc6492842b42660f8bc36537b478083ceb97ad79 is included.
That part should be reverted

**Comment by farhadst** [comment]
@dgt41 This problem not fix and still exists in the new version of joomla 3.7.3

**Comment by infograf768** [comment]
@farhadst 
We do know there are still issues when entering dates manually in the field for fa-IR.
We decided to merge what we had to at least let use the Calendar popup correctly.
It will not be solved either in 3.7.4

I suggest you create a new Issue which would contain https://github.com/joomla/joomla-cms/pull/16922#issuecomment-312477460 in order to try to solve it in the future.

**Comment by davenlife** [comment]
There's an issue in Joomla 3.7.4, published time is different than time in server and in global configuration. When you modify an article appears "published but pending". I've tried almost everything, changed server time, global settings in joomla, change user time settings, and so on. I guess it is a bug because it started happening with 3.7.4 version... Any idea? 

I am using Joomla! 3.7.4 , PHP 7.0.22, cPanel.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16922">issues.joomla.org/tracker/joomla-cms/16922</a>.</sub>

**Comment by zero-24** [comment]
@davenlife please open a new issue as this is already closed and your comment will be missed. Thanks.

**Pull request merged**
