### PR TITLE
Converting /includes/framework.php to a Class & refactoring

### PR DESCRIPTION
**Pull request by izharaazmi**
Converting /includes/framework.php from linear php file to use class structure. Simplifying the two separate files `framework.php` in **site** and **administrator** each, using inheritance.

Introduce constant `JPATH_ADMINISTRATOR_DIR` to eliminate hardcoding of the backend directory name everywhere. Not used anywhere yet, but strongly intended to.

**TEST INSTRUCTION**
Download Joomla with this patch. You should be able to:
1. Open installation page at first launch and until installation is done.
2. Remove "Installation" directory without installing, it should show error message "... not found... exiting."
3. After successful installation it should not allow site / administrator navigation unless "Installation" directory is removed.
4. After removal of "installation" directory it should open site and administrator as usual with no difference.

### CODE REVIEW

**Comment by mbabker** [comment]
What benefit is there to having the application bootstrap within a class structure?  There are indeed ways to refactor the bootstrap to be a single source versus each app (site, admin, install) have their own logic and duplicated code, but I'm not convinced a class based approach is any good.

**Comment by Hackwar** [comment]
I don't see a value in this either. It also adds additional lines of code instead of reducing the necessary code... Can we get a decision by the PLT on this?

**Comment by brianteeman** [comment]
Set to Needs Review as requested<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8692">issues.joomla.org/joomla-cms/8692</a>.</sub>

**Comment by wilsonge** [comment]
I agree about not really seeing the value too. So closing

**Pull request closed without merging**
