### PR TITLE
[4.0] JSON capitalisation

### PR DESCRIPTION
**Pull request by brianteeman**
JSON is an acronym and as such should be capitalised.

code review

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 3b5bb9196000ea0544e8673d41685cae2832ff14<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31612">issues.joomla.org/tracker/joomla-cms/31612</a>.</sub>

**Comment by wilsonge** [comment]
Does core actually treat these examples as case sensitive? Before we merge this - because these are specific examples of formats that can be passed into the ajax component

**Comment by brianteeman** [comment]
>  because these are specific examples of formats that can be passed into the ajax component

There are?

Whatever it is the word is JSON and should be written as JSON

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 3b5bb9196000ea0544e8673d41685cae2832ff14<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31612">issues.joomla.org/tracker/joomla-cms/31612</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31612">issues.joomla.org/tracker/joomla-cms/31612</a>.</sub>

**Pull request closed without merging**
