### PR TITLE
[4.0] Override-Manager fix

### PR DESCRIPTION
**Pull request by astridx**
# Summary of Changes

At the moment you can not see in the template manager what function the Switches have. It looks like this to me. 

Templates  Customise  Cassiopeia    test   Administration(3)

I have also corrected the alignment. For `ltr` it was only needed to remove a margin. The alignment is OK. For `rtl` I added the correct alignment.

The label is not inserted. We would have to use 
`echo $this→form→renderField('show_core');`
for this.

I tried to display the label. However, it is difficult to position the switcher with label correctly at this point. Therefore I think it is good to only display the `input` and to adapt the description text.

### Testing Instructions
1. Create an override in the Template Manager and open it for editing. You see two switches. You don't know what these switches do.

2. Apply this patch

3. Switch back to the template manager and see that the description text of the switches now shows the current status. You now know what switch is responsible for.

### Expected result
You can see the function that a switch performs based on the label or description.

قالب ها  اختصاصی سازی قالب  Cassiopeia    test   مدیریت

Templates  Customise  Cassiopeia    test   Administration(2)

### Actual result
You see switches but you do not know what the switch `hide` or `show`.

### Additional information

Because of  https://github.com/joomla/joomla-cms/blob/9f68e6e9950fbdb07cbc9ce5a8e90ff676dec845/administrator/templates/atum/scss/template-rtl.scss#L209 we need the change in the CSS-file.

This is a redo of parts of this PR: https://github.com/joomla/joomla-cms/pull/26359/

### CODE REVIEW

**Comment by carcam** [comment]
I have tested this item :white_check_mark: successfully on 7619bb8b40d5e8a87344c0e6851ab16630d1bda0<br /><br />I have successfully tested this patch ;) Thank you!!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28396">issues.joomla.org/tracker/joomla-cms/28396</a>.</sub>

**Comment by maikol-ortigueira** [comment]
I have tested this patch successfully. Thank you!!!
[screen shot 2020-03-19 at 16 42 00](https://issues.joomla.org/uploads/1/b257658493fb1a6c6596efa28484776d.png)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28396">issues.joomla.org/tracker/joomla-cms/28396</a>.</sub>

**Comment by maikol-ortigueira** [comment]
I have tested this item :white_check_mark: successfully on 7619bb8b40d5e8a87344c0e6851ab16630d1bda0<br /><br />Tested successfully, thank you!!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28396">issues.joomla.org/tracker/joomla-cms/28396</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28396">issues.joomla.org/tracker/joomla-cms/28396</a>.</sub>

**Comment by infograf768** [comment]
Can the wording « diff » be modified to « differences » ?

**Comment by astridx** [comment]
Yes, but I like the shorter form. What do others say?

**Comment by maikol-ortigueira** [comment]
I think it might look better "differences"

**Comment by astridx** [comment]
OK, done.

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
