### PR TITLE
Undefined variable $app and $data fixed. Fixes #12768

### LINKED ISSUE #12768: Undefined variables in ConfigControllerModulesSave
https://github.com/joomla/joomla-cms/blob/staging/components/com_config/controller/modules/save.php#L84

The variables $app and $data aren't defined in scope. I don't know the context hence could not attempt a fix. May be someone can do that.

PS: Code review based only.

### PR DESCRIPTION
**Pull request by izharaazmi**
Pull Request for Issue #12768 

### Summary of Changes
Added the missing definition for `$data` and replace` $app` with `$this->app`

### Testing Instructions
Please do a code review, should be enough. I am fixing this just to avoid the other issue closed. Will add instructions later if really needed.

### Documentation Changes Required
None

### CODE REVIEW

**Comment by joomdonation** [comment]
I have tested this item :white_check_mark: successfully on a0c2dbef66717f26f56efed5dae3d21824a0b13d<br /><br />Code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19003">issues.joomla.org/tracker/joomla-cms/19003</a>.</sub>

**Comment by ghost** [comment]
reading "Code Review" thinking @Quy. Can you please?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19003">issues.joomla.org/tracker/joomla-cms/19003</a>.</sub>

**Comment by csthomas** [comment]
I have tested this item :white_check_mark: successfully on a0c2dbef66717f26f56efed5dae3d21824a0b13d<br /><br />Code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19003">issues.joomla.org/tracker/joomla-cms/19003</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Pull request merged**
