### PR TITLE
[plg_search_tags] Search results now don't include unpublished, archived or trashed tags

### PR DESCRIPTION
**Pull request by EmilMassey**
Pull Request for Issue #10712 .
#### Summary of Changes

Select only published tags from the database by adding `$query->where('a.published = 1');.`
#### Testing Instructions
1. Make sure Search - Tags plugin is enabled
2. Create a tag
3. Unpublish, archive or trash it
4. Type a tag name in a mod_search module
5. Only published tags should be listed.

### CODE REVIEW

**Comment by infograf768** [comment]
Looking at code, I think you should separate the query for published, and leave alone the code with `if ($app->isSite() && JLanguageMultilang::isEnabled())` as this is done in the other search plugins.
I.e. should be:
```
		$query->where('a.published = 1');
		
		if ($app->isSite() && JLanguageMultilang::isEnabled())
		{
			$tag = JFactory::getLanguage()->getTag();
			$query->where('a.language in (' . $db->quote($tag) . ',' . $db->quote('*') . ')');
		}
```

**Comment by hardiktasol** [comment]
I have tested this item :white_check_mark: successfully on c0b829b3eba8e464219158b9f6dcc438742baf9e<br /><br />I have tested in Joomla 3.5.1 and patch works perfectly.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10713">issues.joomla.org/joomla-cms/10713</a>.</sub>

**Comment by gunjanpatel** [comment]
I have tested this item :white_check_mark: successfully on c0b829b3eba8e464219158b9f6dcc438742baf9e<br /><br />It works perfect after applying path.
It has two successful tests, but as per @infograf768 suggestion, I agree that $query->where('a.published = 1'); should be outside of the condition. Also, I would like to suggest below code to use `quoteName`.
```php
$query->where($db->qn('a.published') . ' = 1');
```

Thanks for fixes.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10713">issues.joomla.org/joomla-cms/10713</a>.</sub>

**Comment by brianteeman** [comment]
rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10713">issues.joomla.org/joomla-cms/10713</a>.</sub>

**Comment by wojsmol** [comment]
@brianteeman Please remove RTC, see comments by @infograf768 and @gunjanpatel .

**Comment by brianteeman** [comment]
Done

**Comment by brianteeman** [comment]
Back to pending<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10713">issues.joomla.org/joomla-cms/10713</a>.</sub>

**Comment by infograf768** [comment]
@EmilMassey 

Please update your PR

**Comment by gunjanpatel** [comment]
I have tested this item :white_check_mark: successfully on db7e77ed165925e9885b0b32fc0fe1674a96fd50<br /><br />Tested successfully.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10713">issues.joomla.org/joomla-cms/10713</a>.</sub>

**Comment by brianteeman** [comment]
As the previously tested PR has been updated and confirmed by @gunjanpatel I am setting this back to RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10713">issues.joomla.org/joomla-cms/10713</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10713">issues.joomla.org/joomla-cms/10713</a>.</sub>

**Comment by EmilMassey** [comment]
Thank you @infograf768, @gunjanpatel for your suggestions.

**Comment by wilsonge** [comment]
Merged :) Thanks very much!

**Pull request merged**
