### PR TITLE
added tag filter functionality to articles

### PR DESCRIPTION
**Pull request by kburwieck**

### CODE REVIEW

**Comment by losedk** [comment]
Travis is failing because you should use indents instead of spaces:

  40 | ERROR | Tabs must be used to indent lines; spaces are not allowed
 242 | ERROR | Tabs must be used to indent lines; spaces are not allowed
 243 | ERROR | Tabs must be used to indent lines; spaces are not allowed
 244 | ERROR | Tabs must be used to indent lines; spaces are not allowed
 245 | ERROR | Tabs must be used to indent lines; spaces are not allowed
 246 | ERROR | Tabs must be used to indent lines; spaces are not allowed
 247 | ERROR | Tabs must be used to indent lines; spaces are not allowed
 528 | ERROR | Tabs must be used to indent lines; spaces are not allowed
 529 | ERROR | Tabs must be used to indent lines; spaces are not allowed
 530 | ERROR | Tabs must be used to indent lines; spaces are not allowed
 531 | ERROR | Tabs must be used to indent lines; spaces are not allowed
 532 | ERROR | Tabs must be used to indent lines; spaces are not allowed
 533 | ERROR | Tabs must be used to indent lines; spaces are not allowed
 534 | ERROR | Tabs must be used to indent lines; spaces are not allowed
 535 | ERROR | Tabs must be used to indent lines; spaces are not allowed
 536 | ERROR | Tabs must be used to indent lines; spaces are not allowed
 537 | ERROR | Tabs must be used to indent lines; spaces are not allowed
 538 | ERROR | Tabs must be used to indent lines; spaces are not allowed
 539 | ERROR | Tabs must be used to indent lines; spaces are not allowed
 540 | ERROR | Tabs must be used to indent lines; spaces are not allowed

**Comment by Fedik** [comment]
@kburwieck  usually no one cares about pull request without description :wink:

**Comment by brianteeman** [comment]
Or test instructions

On 2 February 2015 at 16:35, Fedir Zinchuk <notifications@github.com> wrote:

> @kburwieck <https://github.com/kburwieck> usually no one cares about pull
> request without description [image: :wink:]
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/5947#issuecomment-72488260>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by kburwieck** [comment]
new pull request: #5949

**Pull request closed without merging**
