### PR TITLE
[4.0] Namespace tags popular

### PR DESCRIPTION
**Pull request by C-Lodder**
### Summary of Changes

Namespace tags popular

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :red_circle: unsuccessfully on 88595d026c556da79d70aacb063cfe7303e11498<br /><br /><b>Warning</b>:  Invalid argument supplied for foreach() in <b>C:\Apache24\htdocs\cms4\components\com_tags\View\Tag\Html.php</b> on line <b>320</b><br />
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17281">issues.joomla.org/tracker/joomla-cms/17281</a>.</sub>

**Comment by C-Lodder** [comment]
That error isn't related to this PR.

If you checkout to the `4.0-dev` branch then refresh the page, then error will still be there

**Comment by brianteeman** [comment]
yes - sorry i should have checked that - you are correct

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 88595d026c556da79d70aacb063cfe7303e11498<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17281">issues.joomla.org/tracker/joomla-cms/17281</a>.</sub>

**Pull request merged**
