### PR TITLE
[4.0] Update atum preview images

### LINKED ISSUE #29832: [4.0] Atum screenshot needs updating ;-)
### Steps to reproduce the issue

/administrator/index.php?option=com_templates&view=templates&client_id=1

### Expected result

Screenshot needs updating as the Modules look different now after redesigning

### Actual result

administrator/templates/atum/template_preview.png

image

### System information (as much as possible)

Joomla 4 beta 1

### PR DESCRIPTION
**Pull request by brianteeman**
fixes #29832

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on d8f91a16b9209d2be8f9e24e028aefd7842e45bb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29834">issues.joomla.org/tracker/joomla-cms/29834</a>.</sub>

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on d8f91a16b9209d2be8f9e24e028aefd7842e45bb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29834">issues.joomla.org/tracker/joomla-cms/29834</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29834">issues.joomla.org/tracker/joomla-cms/29834</a>.</sub>

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
