### PR TITLE
[4.0] [a11y] Move search label

### PR DESCRIPTION
**Pull request by brianteeman**
Simple PR to move the search label (visually hidden) to being in the same div as the search input in the toolbar. This will help to improve accessibility

### CODE REVIEW

**Comment by zwiastunsw** [comment]
I have tested this item :white_check_mark: successfully on 4f74674b11cab14c97a2e07ee702df2af02e5968<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21985">issues.joomla.org/tracker/joomla-cms/21985</a>.</sub>

**Comment by baernm** [comment]
I have tested this item :white_check_mark: successfully on 48185374ec9d7f2e5868b8ff966b07ac78ae11dd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21985">issues.joomla.org/tracker/joomla-cms/21985</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Comment by laoneo** [comment]
Thanks

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
