### PR TITLE
[4.1] Space at bottom of sidebar for non logged user.

### PR DESCRIPTION
**Pull request by anmode**
Pull Request for Issue #37171
Backend Login page -> There's a little space below the left blue bar. I believe this only shows when there are NO buttons in the top header. We have disabled all those buttons for not logged in users

### Summary of Changes
Just changed the viewport height so after disabling the login button at the top of the bar.

### Testing Instructions
I made changes in the scss folder so after recreating the media folder(creating CSS files) the changes will be reflected on the localhost.

### Expected result AFTER applying this Pull Request

https://user-images.githubusercontent.com/88332977/157408733-9afaf5ad-363d-4df9-8227-a0409ba202d6.mp4

### Documentation Changes Required
No changes required

### CODE REVIEW

**Comment by mohdabbas955** [comment]
I have tested this item :white_check_mark: successfully on 3f4927358509602659f3590ffd947febd34c97b0<br /><br />I have tested this item ✅ successfully on b1fa223<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37236">issues.joomla.org/tracker/joomla-cms/37236</a>.</sub>

**Comment by anmode** [comment]
@bembelimen   Sorry to tag you! But actually, It's been a long generating this PR. I had successfully applied the solution to the issue. #37171. Would you please review this PR?

**Comment by Quy** [comment]
Another solution is to add `flex-grow-1` to:
https://github.com/joomla/joomla-cms/blob/cb07dbda22c8a8a8f4ced200ff9c079fec8a2f27/administrator/templates/atum/login.php#L121

**Comment by anmode** [comment]
> Another solution is to add `flex-grow-1` to:
> 
> https://github.com/joomla/joomla-cms/blob/cb07dbda22c8a8a8f4ced200ff9c079fec8a2f27/administrator/templates/atum/login.php#L121

yes, This can be we add here too and that was working fine. what am I supposed to do now? Do I have to add here? or b1fa223 commit is fine

**Comment by Quy** [comment]
Either use class or css, but not both. Since there is a class for it, use it instead of adding css, but that is just my opinion.

**Comment by anmode** [comment]
> Either use class or CSS, but not both. Since there is a class for it, use it instead of adding CSS, but that is just my opinion.

I just add CSS  and the class is already defined may be used somewhere else in the codebase.

**Comment by Quy** [comment]
`flex-grow-1` is a standard Bootstrap class. Either way will work. It is up to the release maintainer to decide.

**Comment by anmode** [comment]
> `flex-grow-1` is a standard Bootstrap class. Either way will work. It is up to the release maintainer to decide.

oh okay thanks a lot.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 5066719797097d18ba6967e79d34b6b0f0f661ed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37236">issues.joomla.org/tracker/joomla-cms/37236</a>.</sub>

**Review by chmst — APPROVED** [review]

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 5066719797097d18ba6967e79d34b6b0f0f661ed<br /><br />I have tested this item ✅ successfully on 5066719<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37236">issues.joomla.org/tracker/joomla-cms/37236</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37236">issues.joomla.org/tracker/joomla-cms/37236</a>.</sub>

**Comment by laoneo** [comment]
Thanks!!

**Pull request merged**
