### PR TITLE
Fix right click hiding topnav dropdown

### PR DESCRIPTION
**Pull request by C-Lodder**
Pull Request for Issue #11457 
### Summary of Changes

This PR fixes the right click event hiding the dropdown menu, on Firefox (Windows)
### Testing Instructions

Apply the patch. Once done, open one of the topnav dropdown and right click. It shouldn't hide the dropdown:

joomla
### Documentation Changes Required

**None**

/cc: @fr56 @yild @ggppdk

### CODE REVIEW

**Comment by ciar4n** [comment]
I have tested this item :white_check_mark: successfully on <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11951">issues.joomla.org/joomla-cms/11951</a>.</sub>

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on fad8070c275c3c45ecf581a849154aae1777ea05<br /><br />reproduce the issue in firefox on windows and this fixes it.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11951">issues.joomla.org/joomla-cms/11951</a>.</sub>

**Comment by brianteeman** [comment]
RTC - thanks for testing<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11951">issues.joomla.org/joomla-cms/11951</a>.</sub>

**Comment by fr56** [comment]
I am the OP for Issue #11457, and have tested this item successfully.

This was my first posting on Github. Thanks guys!

**Comment by C-Lodder** [comment]
Thanks for testing guys

**Pull request merged**
