### PR TITLE
[com_fields] Remove home option in media form field

### PR DESCRIPTION
**Pull request by laoneo**
Pull Request for Issue #13878.

### Summary of Changes
Removes the home option as it can lead to a misunderstanding that the folder the media form field is initially loaded with, is restricted.

### Testing Instructions
- Create a media custom field
- Set Home to yes

### Expected result
Home options should nto be there to select from.

### Actual result
There is a home button in the media custom field.

### CODE REVIEW

**Comment by beat** [comment]
I would prefer have this setting renamed than removed. See https://github.com/joomla/joomla-cms/issues/13878#issuecomment-277277777

**Comment by coolcat-creations** [comment]
I think this feature has too much issues. Also with the decision how the folder should be named (security issues) 

+1 for removing in favour of maybe a better solution in 3.8 with the new mediamanager<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13893">issues.joomla.org/tracker/joomla-cms/13893</a>.</sub>

**Comment by SniperSister** [comment]
+1 for removing, mainly from a security perspective

**Comment by yvesh** [comment]
+1 remove it, makes no sense the way it's implemented.. Or rename it to start directory whatever :-)

**Comment by beat** [comment]
+1 to remove it or to rename it to "Start directory" or "Default directory". "Home directory" is clearly misleading as it implies restrictions outside of it and/or a user-specific directory.

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 268792370b73cf39d6c4872d0d9760dd97965da8<br /><br />Applied PR Message `No Images Found` is gone, Folders like `Banners`, `Headers`, ... are shown.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13893">issues.joomla.org/tracker/joomla-cms/13893</a>.</sub>

**Pull request merged**
