### PR TITLE
Fix for #11070 (tag-category) - Improve also views newsfeed-category …

### PR DESCRIPTION
**Pull request by rvbgnu**
…and category-list

Pull Request for Issue #11070.

### Summary of Changes

There is a width issue on the filter-search field. Especially for the tag view, where there are two buttons beside the field. The other filters usually have no button. This is the case for newsfeed-category and category-list.
The width comes from the general rule here:
```
input,
textarea,
.uneditable-input {
	width: 206px;
}
```
https://github.com/joomla/joomla-cms/blob/staging/templates/protostar/css/template.css#L936

### Testing Instructions

» Go to the front-end with latest joomlacms (Test website using the Sample Data TEST to more views).
» In the Menu **All Front End Views**, click on **Tagged items**
» View on small device screen
» Repeat with **Article Category List** and **News Feed Category** menu items

### Expected result

» Filter search is inside the container, and the select limit drop-down gracefully displays on the next line with a margin.

(Test website using the Sample Data TEST to more views).

Tag-category AFTER:
screen shot 2017-06-12 at 21 50 10  

Category-list AFTER:
screen shot 2017-06-12 at 21 50 26  

Newsfeed-category AFTER:
screen shot 2017-06-12 at 21 50 42  

### Actual result

The filter search and the buttons are a bit outside the container on a small device.
On Mac Firefox/Chrome, the issue is there until 328px wide. Fixed above.

Tag-category BEFORE:
screen shot 2017-06-12 at 21 53 30

Category-list BEFORE:
screen shot 2017-06-12 at 21 52 39

Newsfeed-category BEFORE:
screen shot 2017-06-12 at 21 52 16

### CODE REVIEW

**Comment by rvbgnu** [comment]
I'm doing some frontend design, but I am not an expert.
If a UX or template designer could look and finding a better way, that will help ;-)

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on d7413e2646277cab93770b85ea518e061e33dabc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16627">issues.joomla.org/tracker/joomla-cms/16627</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
@kalpeshtailored can you please test?

**Comment by franz-wohlkoenig** [comment]
@rvbgnu can you please make for each Change (tag-view, newsfeed-category, category-list) an own PR?

**Comment by brianteeman** [comment]
Please don't edit the css directly. You should edit the less file and run generatecss.php 

https://docs.joomla.org/Joomla_LESS

**Comment by rvbgnu** [comment]
Oops, sorry @brianteeman , I will edit the PR and create separate ones for the other view, thanks @franz-wohlkoenig !<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16627">issues.joomla.org/tracker/joomla-cms/16627</a>.</sub>

**Comment by brianteeman** [comment]
It would be better as just a single pr

**Comment by rvbgnu** [comment]
Now .LESS file added, and better description for the three views concerned.
Generatecss.php also modified isis .css, but not used (filter-search is spelled filter_search)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16627">issues.joomla.org/tracker/joomla-cms/16627</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 13cdbbe63d5bd2d3d8c6f66be5b93ad4f41f07fd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16627">issues.joomla.org/tracker/joomla-cms/16627</a>.</sub>

**Comment by ghost** [comment]
@kalpeshtailored please test this PR if it solves your reported Issue #11070.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16627">issues.joomla.org/tracker/joomla-cms/16627</a>.</sub>

**Comment by ghost** [comment]
@kalpeshtailored @killoltailored please test so we get needed second Test.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16627">issues.joomla.org/tracker/joomla-cms/16627</a>.</sub>

**Comment by fancyFranci** [comment]
I have tested this item :white_check_mark: successfully on 13cdbbe63d5bd2d3d8c6f66be5b93ad4f41f07fd<br /><br />Result is like in the instruction.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16627">issues.joomla.org/tracker/joomla-cms/16627</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Pull request merged**
