### PR TITLE
fix for User Group column to Users: Viewing Access Levels

### PR DESCRIPTION
**Pull request by pe7er**
Pull Request for solving merge conflict of PR #10224. 
I've redone this pr for the current Joomla! 3.6.0-dev code base.

Thanks @andrepereiradasilva for your advice to hide it on mobile phones!

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on b63d47f4258aea9481b395bfbe9c5cbc85a7f52d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10276">issues.joomla.org/joomla-cms/10276</a>.</sub>

**Comment by pe7er** [comment]
Codefix: I've added some empty lines before & after the if statement. Thanks @zero-24 for this correction!

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on b63d47f4258aea9481b395bfbe9c5cbc85a7f52d<br /><br />Works good. Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10276">issues.joomla.org/joomla-cms/10276</a>.</sub>

**Comment by zero-24** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10276">issues.joomla.org/joomla-cms/10276</a>.</sub>

**Comment by zero-24** [comment]
Can we get the New Feature label here?

**Pull request merged**
