### PR TITLE
[5.2] Harden FormattedTextLogger against object injection attacks

### PR DESCRIPTION
**Pull request by SniperSister**
### Summary of Changes
The current implementation of the FormattedTextLogger class creates a potential code execution vulnerability if either Joomla core itself or a third party extension would have an object injection vulnerability via unserialization of user supplied input. This PR adds an exception message for that very specific case, preventing that such an attack payload would be written.

YES, I'm aware that this is a theoretical b/c break. However, weighting the pros and cons of the current implementation, I think that it's a useful change nonetheless.

### Credits:
The general mechanism was reported by [Drew Webber / mcdruid](http://mcdruid.co.uk/)

### Testing Instructions
Apply patch, create a log message by trying to log in into the administrator site with wrong credentials.

### Actual result BEFORE applying this Pull Request
Log file is written

### Expected result AFTER applying this Pull Request
Log file is written

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by ramalama** [comment]
Tested successfully as described. 
Log Entries before and after identical.

**Review by ramalama — APPROVED** [review]
Tested successfully as described.
Log Entries before and after identical.

**Comment by fgsw** [comment]
@ramalama  can you open https://issues.joomla.org/tracker/joomla-cms/44428 and 
- login with your github-account
- click button "Test this"
- mark "Tested successfully"

Now the test count as successfull.

**Comment by ramalama** [comment]
I have tested this item :white_check_mark: successfully on 4982fc90bfe720500367575becf1d1bc2e1faf3c<br /><br />Tested successfully as described.
Log Entries before and after identical.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44428">issues.joomla.org/tracker/joomla-cms/44428</a>.</sub>

**Comment by Quy** [comment]
The test instruction doesn't appear to run the new method. Please confirm.

**Comment by SniperSister** [comment]
As described, there is no option to execute the method in core. That’s why the purpose of the instructions is to confirm that legitimate use cases of that class are unaffected.

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 2ed7d8485477aeab6ac1bd30a3298b46fef38551<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44428">issues.joomla.org/tracker/joomla-cms/44428</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44428">issues.joomla.org/tracker/joomla-cms/44428</a>.</sub>

**Comment by Hackwar** [comment]
Thank you for your contribution!

**Pull request merged**
