### PR TITLE
Added a Cypress test for creating an Article

### PR DESCRIPTION
**Pull request by rajputanuj31**
Added a Cypress test for creating an Article.

### CODE REVIEW

**Comment by brianteeman** [comment]
> Test in frontend that the Article can create an article

This makes no sense

**Comment by laoneo** [comment]
@brianteeman corrected the description, can you check again?

**Comment by laoneo** [comment]
@rajputanuj31 can you also add a test to create an article without a menu item? Probably you have to take as visit url `index.php?option=com_content&task=article.add`.

**Comment by brianteeman** [comment]
description is good now

**Comment by rajputanuj31** [comment]
> @rajputanuj31 can you also add a test to create an article without a menu item? Probably you have to take as visit url `index.php?option=com_content&task=article.add`.

Sure.

**Pull request merged**
