### PR TITLE
[3.5] [Imp] Remove useless tags sidebar

### PR DESCRIPTION
**Pull request by zero-24**
### What is changed?

This PR removes the useless Sidebar for Tags and fixes some mirror CS
### Bevor the change

bevor_tags_removal
### After the change

after_tags_removal
### How to test
- install 3.5
- access com tags
- see `Bevor the change`
- apply the patch
- access com tags
- see `After the change`

### CODE REVIEW

**Comment by Bakual** [comment]
Looks fine, allthough I will miss that funny helper class :laughing:

**Comment by zero-24** [comment]
Thanks for the tip about that helper class @Bakual

**Comment by n9iels** [comment]
I got the following errors when applying the patch:
```
Warning: require_once(C:\MAMP\htdocs\joomla-cms\administrator/components/com_tags/helpers/tags.php): failed to open stream: No such file or directory in C:\MAMP\htdocs\joomla-cms\administrator\components\com_tags\controller.php on line 31

Fatal error: require_once(): Failed opening required 'C:\MAMP\htdocs\joomla-cms\administrator/components/com_tags/helpers/tags.php' (include_path='.;C:\php\pear') in C:\MAMP\htdocs\joomla-cms\administrator\components\com_tags\controller.php on line 31
```

**Comment by zero-24** [comment]
thanks @n9iels  :smile: should be fixed now ;)

**Comment by n9iels** [comment]
Nearly fixed, do the same for the `views/tag/view.html.php`. Now you get the same error over there

**Comment by dgt41** [comment]
@zero-24 Tobias better make a search for all the places this helper might exist 😜  Too hard to die…

**Comment by zero-24** [comment]
Yes I can do this tomorrow.

**Comment by Bakual** [comment]
Ouch. The line to remove is https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_tags/views/tag/view.html.php#L78

That line doesn't make any sense at all. `TagsHelper` isn't used anywhere there.

I haven't found any other occurance of it. Hopefully it really is the last one.

**Comment by zero-24** [comment]
Fixed: https://github.com/zero-24/joomla-cms/commit/409218f62d036c036642bef597a69311729b5bcb  

BTW: Why tags always load the language file? Any reason for this?
https://github.com/zero-24/joomla-cms/blob/remoaveTagsSidebar/administrator/components/com_tags/views/tag/view.html.php#L71-L74

**Comment by Bakual** [comment]
I doubt that makes sense. The language will already be loaded by the system anyway. I never had to load the component language file manually for my extension.

**Comment by mbabker** [comment]
A fair majority of the tags code was copied from com_categories, to include all of its extra quirks.

**Comment by roland-d** [comment]
@zero-24 Can you fix the merge conflicts?

**Comment by zero-24** [comment]
done @roland-d

**Comment by roland-d** [comment]
Thanks everybody, merged.

**Pull request merged**
