### PR TITLE
[com_plugins] User not allowed to core.manage? Use 403 php custom exception (instead of a 404 JError)

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
Pull Request for Improvement.
#### Summary of Changes

Replace com_plugins existing 404 JError for a 403 php exception when the user does not have access to "Access Administration Interface" (core.manage).

Also adds a custom exception `JControllerExceptionNotallowed` for this effect.
##### Before

image
##### After

image
#### Testing Instructions
1. Use latest staging
2. Create a user and add it to "Administrator" group
3. Go to com_plugins and set "Access Administration Interface" (core.manage) to "Denied" for "Administrator" group
4. Login with the Administrator user in a private window and go to /administrator/index.php?option=com_plugins
5. See the red message (Before)
6. Apply patch
7. Repeat step 4, you'll see now a 403 error (After).

When/If merged i can do it for the other components.

thanks @mbabker

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11593">issues.joomla.org/joomla-cms/11593</a>.</sub>

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on e1253ed826fd62f28ea371e134b966716a54297b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11593">issues.joomla.org/joomla-cms/11593</a>.</sub>

**Comment by MATsxm** [comment]
I have tested this item :white_check_mark: successfully on e1253ed826fd62f28ea371e134b966716a54297b<br /><br />Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11593">issues.joomla.org/joomla-cms/11593</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC please<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11593">issues.joomla.org/joomla-cms/11593</a>.</sub>

**Pull request merged**
