### PR TITLE
[4.0] Translate com_finder modal titles

### PR DESCRIPTION
**Pull request by Quy**
Fix modal titles not translated.

### Testing Instructions
Go to Smart Search > Content Maps
Click Statistics button
See modal title not translated
Go to Smart Search > Filters
Click Statistics button
See modal title not translated
Apply PR
Modal titles translated

### CODE REVIEW

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 1df6b26e4b8a3bfa338c237e0bc8f3194a02c089<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27852">issues.joomla.org/tracker/joomla-cms/27852</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 1df6b26e4b8a3bfa338c237e0bc8f3194a02c089<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27852">issues.joomla.org/tracker/joomla-cms/27852</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27852">issues.joomla.org/tracker/joomla-cms/27852</a>.</sub>

**Comment by infograf768** [comment]
Tks.

**Pull request merged**
