### PR TITLE
Adding CDATA to description in en-GB language package manifest.

### PR DESCRIPTION
**Pull request by Bakual**
In Crowdin, when a translator tries to add a CDATA tag to the description it will be blocked because it isn't present in the source string. This PR adds it to the source string so the translators have an easier life on Crowdin.
### Summary of Changes

Adds `<![CDATA[ ... ]]>` to the `<description>` tag in the en-GB package manifest.
### Testing Instructions
1. Go to Extension Manager -> Manager and filter for "eng" to get the en-GB packages.
2. Select all three of them and click "Refresh Cache".
3. Check the tooltips that they still work as expected.
### Documentation Changes Required

None

### CODE REVIEW

**Comment by brianteeman** [comment]
Fine by me

**Comment by andrepereiradasilva** [comment]
Is this only needed in this particular pkg_xx-XX.xml manifest? Or should be applied to all xmls?

> - [Installation Language MetaFile](https://github.com/joomla/joomla-cms/blob/staging/installation/language/en-GB/en-GB.xml)
> - [Site Language MetaFile](https://github.com/joomla/joomla-cms/blob/staging/language/en-GB/en-GB.xml)
> - [Site Language Manifest](https://github.com/joomla/joomla-cms/blob/staging/language/en-GB/install.xml)
> - [Admin Language MetaFile](https://github.com/joomla/joomla-cms/blob/staging/administrator/language/en-GB/en-GB.xml)
> - [Admin Language Manifest](https://github.com/joomla/joomla-cms/blob/staging/administrator/language/en-GB/install.xml)
> - [Language Package Manifest](https://github.com/joomla/joomla-cms/blob/staging/administrator/manifests/packages/pkg_en-GB.xml)

**Comment by Bakual** [comment]
I thought the description is only used during installation, and thus the package manifest would be the only place it is needed. But checking further you're right, it is used also in the extension manager in a tooltip. I'm going to update the en-GB.xml files as well.
I don't know if the description in the install.xml manifests are used for anything.
The files in the installation folder don't have the description tag anyway.

Also found a way to test this:
1. Go to Extension Manager -> Manager and filter for "eng" to get the en-GB packages.
2. Select all three of them and click "Refresh Cache".
3. Check the tooltips that they still work as expected.

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on fa60cfe1976db788422648c4b36c1bcc54c1cb94<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11954">issues.joomla.org/joomla-cms/11954</a>.</sub>

**Comment by andrepereiradasilva** [comment]
created a fake lp to check what is used where (there are so many ...)
[xx-XX-languagepackage.zip](https://github.com/joomla/joomla-cms/files/456901/xx-XX-languagepackage.zip)

it confirms what you say, install.xml `description` is not used anywhere in the core.

Also made the test described and works as expected.

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on fa60cfe1976db788422648c4b36c1bcc54c1cb94<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11954">issues.joomla.org/joomla-cms/11954</a>.</sub>

**Comment by brianteeman** [comment]
Rtx<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11954">issues.joomla.org/joomla-cms/11954</a>.</sub>

**Comment by MATsxm** [comment]
I have tested this item :white_check_mark: successfully on fa60cfe1976db788422648c4b36c1bcc54c1cb94<br /><br />Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11954">issues.joomla.org/joomla-cms/11954</a>.</sub>

**Pull request merged**
