### PR TITLE
[5.1] Api categories tests

### PR DESCRIPTION
**Pull request by brianteeman**
Corrects the description of all API categories tests. For the api tests the terminology uses id "deliver" not "display"

simple PR that can be "tested" by code review

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 5a3ffa4a180bf842dfec4cde1bc1d6c72b92b897<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42513">issues.joomla.org/tracker/joomla-cms/42513</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 5a3ffa4a180bf842dfec4cde1bc1d6c72b92b897<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42513">issues.joomla.org/tracker/joomla-cms/42513</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42513">issues.joomla.org/tracker/joomla-cms/42513</a>.</sub>

**Comment by Razzo1987** [comment]
Thanks you!

**Pull request merged**
