### PR TITLE
[4.0][a11y] Labels Module Assignment are not associated with forms

### PR DESCRIPTION
**Pull request by brianteeman**
PR for #23889

### CODE REVIEW

**Comment by zwiastunsw** [comment]
Working perfectly!

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 1ce9feb4027e2102d622a1bd8eec8e3dd1a66e23<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23922">issues.joomla.org/tracker/joomla-cms/23922</a>.</sub>

**Comment by zwiastunsw** [comment]
@brianteeman : Will you correct errors in this PR also for the cases indicated here: https://github.com/joomla/joomla-cms/issues/23888#issuecomment-464055866 ?

**Comment by zwiastunsw** [comment]
I have tested this item :white_check_mark: successfully on 1ce9feb4027e2102d622a1bd8eec8e3dd1a66e23<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23922">issues.joomla.org/tracker/joomla-cms/23922</a>.</sub>

**Comment by brianteeman** [comment]
@zwiastunsw I "think" some of them are already done and for the others I will need to check further as the problem is different so I will probably do them in (if i can) in  a different PR - tomorrow

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23922">issues.joomla.org/tracker/joomla-cms/23922</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
