### PR TITLE
MSSQL fix sql syntax in  administrator/components/com_admin/sql/updates/sqlazure

### PR DESCRIPTION
**Pull request by csthomas**
### Summary of Changes

Update sql files for mssql database has invalid syntax.
This PR fix files from 3.5.0 and one older to correct syntax.

### Testing Instructions
* Install Joomla 3.5.0 on sqlsrv (mssql) database in folder `joomla`
* Download and extract Joomla from `https://github.com/csthomas/joomla-cms/archive/msfixupdate.zip` to folder `joomla37`
* Move `joomla` to `joomla_old`
* Move `joomla37` to `joomla`
* Copy `joomla_old/configuration.php` to `joomla/configuration.php`
* Download `postupdate.php` file from `https://gist.github.com/mbabker/d7bfb4e1e2fbc6b7815a733607f89281#file-postupdate-php` and save it in `joomla/administrator/` folder.
* [optional] Add a few changes as on below diff file to debugging if you like:
```diff
diff --git a/libraries/joomla/database/driver/sqlsrv.php b/libraries/joomla/database/driver/sqlsrv.php
index a0b4285cfb..d2a2097a3d 100644
--- a/libraries/joomla/database/driver/sqlsrv.php
+++ b/libraries/joomla/database/driver/sqlsrv.php
@@ -630,7 +630,7 @@ class JDatabaseDriverSqlsrv extends JDatabaseDriver
                {
                        $array = array();
                }
-
+echo "$query\n\n";
                // Execute the query. Error suppression is used here to prevent warnings/notices that the connection has been lost.
                $this->cursor = @sqlsrv_query($this->connection, $query, array(), $array);
 
@@ -685,7 +685,7 @@ class JDatabaseDriverSqlsrv extends JDatabaseDriver
                        {
                                // Get the error number and message from before we tried to reconnect.
                                $this->errorNum = $errorNum;
-                               $this->errorMsg = $errorMsg;
+                               $this->errorMsg = $errorMsg;echo "\n\n $errorMsg\n\n";
 
                                // Throw the normal query exception.
                                JLog::add(JText::sprintf('JLIB_DATABASE_QUERY_FAILED', $this->errorNum, $this->errorMsg), JLog::ERROR, 'database-error');
```
* run `php -f administrator/postupdate.php`
* From time to time if you apply diff file to see debug info you may see:
```
DELETE 
FROM [j37_session]
WHERE [time] < N'1487235471'

Error displaying the error page: Application Instantiation Error: Failed to start the session because headers have already been sent by ".../libraries/joomla/database/driver/sqlsrv.php" at line 633.
```
Then try again run `php` file, after a few times it won't failed:) 
* At the end of logs you should see:
```
Update to 3.7.0-beta3 completed successfully.
```
or if this PR is still not perfect then (TEST FAILED):
```
Failed to finalize the upgrade, please check the logs for additional details.
```

Alternative way to test for git users:
```
git clone ...
git checkout -f 3.5.0
rm configuration.php # if exists
# Install Joomla 3.5.0 on sqlsrv
git checkout -f staging
curl https://patch-diff.githubusercontent.com/raw/joomla/joomla-cms/pull/14102.diff | git apply
# Apply above diff file
php -f administrator/postupdate.php
...
```

**I have tested only from Joomla 3.5.0 because I have not php 5.6 or less.**

### Expected result
Upgrade from Joomla 3.5.0 to 3.7 will go without errors.

### Actual result
Upgrade fails.

### Documentation Changes Required
None

### CODE REVIEW

**Comment by alikon** [comment]
i've followed first test info 
upgraded from 3.6.5 to Joomla! 3.7.0-beta3 dev [ Amani ] 8-February-2017 14:11 GMT
on  Microsoft SQL Server 12.00.2000
successfully

but after visiting home page  got a **404 Component not found.**

**Comment by alikon** [comment]
as previous reported issues are present on current staging i'll mark this pr as successfull test

**Comment by alikon** [comment]
I have not tested this item.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14102">issues.joomla.org/tracker/joomla-cms/14102</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 2ec04fa55c46a5880187ec1b755e80d503827086<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14102">issues.joomla.org/tracker/joomla-cms/14102</a>.</sub>

**Comment by csthomas** [comment]
Backend error become from `$query->group()`  which I fixed at #13262.

The 404 error is unrelated, but I do not see it on linux. 
I get only error message from joomla generated by some plugin (default enabled).
I have to turn on windows on virtual machine:)

**Comment by csthomas** [comment]
The 404 error also appears on staging joomla installation on mssql. So it is not related.

**Comment by waader** [comment]
I tried it with Joomla 3.4.8 and php 5.3.29. postupdate.php gives some warnings on each invocation. After logging into backend I get 
Error loading component: com_fields, Component not found.
and Manage > Database gives this list, that is not fixable:
    Database schema version (None) does not match CMS version (3.7.0-2017-02-02).
    Database update version (3.7.0-beta2) does not match CMS version (3.7.0-beta3).
    Table N'epik2_fields' does not exist. (From file 3.7.0-2016-08-29.sql.)
    Table N'epik2_fields_categories' does not exist. (From file 3.7.0-2016-08-29.sql.)
    Table N'epik2_fields_groups' does not exist. (From file 3.7.0-2016-08-29.sql.)
    Table N'epik2_fields_values' does not exist. (From file 3.7.0-2016-08-29.sql.)

**Comment by csthomas** [comment]
@waader I have fixed one another file from 3.5.0. your upgrade stop on this file, there is a reason of above problems.

**Comment by csthomas** [comment]
I have merged branch 'staging' into 'msfixupdate' in order to add #14133 changes.

**Comment by csthomas** [comment]
Now you can upgrade from joomla >= 3.4.0 but there is still a few bugs in updates files IIRC 3.03, 3.2.x and 3.4.0

**Comment by waader** [comment]
Upgrade from Joomla 3.4.8 works now.

**Comment by csthomas** [comment]
There is two success tests for 3.4.8 and above. 

My last commit added only query fix for versions between 3.0.3 and 3.2.2.
I have tested it on windows on Joomla 3.0.0.

Please accept the last commit by code review or otherwise we have to wait for somebody who want to test it on Joomla version between 3.0 and 3.2.

**Comment by csthomas** [comment]
I have to rebase this patch, there is not changes. No should be easier to test by Patch Tester.

**Comment by waader** [comment]
I have tested this item :white_check_mark: successfully on d441d0def5c4196885ccbe828924e8dfdf82ada6<br /><br />Could it be that mssql didn´t work for joomla3.0.2 at all. I tried to install this version but couldn´t reach the second tab (database). As upgrade from 3.4.8 works I mark this as successfull.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14102">issues.joomla.org/tracker/joomla-cms/14102</a>.</sub>

**Comment by csthomas** [comment]
When I choose no sample then it works better but you should not use Database -> Fix button on that PR.
After you `Fix` button then probably not all queries will be perform.

I do it in different way on windows. In general it is described at the Test Instruction above.
But for wamp installation my last command looks like:
```
C:\wamp\www\joomla370>..\..\bin\php\php5.6.25\php.exe -c ..\..\bin\php\php5.6.25
\phpForApache.ini -f administrator\postupdate.php
Update to 3.7.0-beta3 completed successfully.
```

**Comment by csthomas** [comment]
Can someone with privilege can merge this PR. This is for mssql only with last success test.
There are only sql updates files. Last php file is already merged.

It is blocking me from creating a next PR.

**Comment by franz-wohlkoenig** [comment]
pinging @infograf768

**Comment by infograf768** [comment]
RTC, as it is unlikely that we will get more MSSQL testers.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14102">issues.joomla.org/tracker/joomla-cms/14102</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
thanks @infograf768

**Pull request merged**
