### PR TITLE
[3.9] Update ru-RU installation to 3.9.16

### PR DESCRIPTION
**Pull request by Kostelano**
Pull Request for Issue # .

### Summary of Changes
- many constants added (~30 pcs, checked the data with the original en-GB file - Joomla 3.9.16),
- translation errors and inaccuracies fixed,
- all quotes are in one form. Screenshot as it was:
Screenshot_1

### Documentation Changes Required
Not required.

### CODE REVIEW

**Comment by b2z** [comment]
Hello.

Joomla is using Crowdin as a translation management tool. The Russian language is located [here](https://crowdin.com/project/joomla-cms/ru).

But for Russian language changes please use [this repository](https://github.com/JPathRu/localisation), where we are managing issues and accepting changes before moving them to Crowdin. 

Thank you.

**Comment by Bakual** [comment]
Installation language changes have to go through the official process and are only accepted when coming from the russian translation team (https://community.joomla.org/translations/joomla-3-translations.html#ru-ru).
So this PR should be closed or approved by the TT leader @SergeyLitvinov

**Comment by infograf768** [comment]
@b2z
As far as I know by comparing files your repo is NOT the repo used by the Russian TT leader.

**Comment by zikkuratvk** [comment]
Is an. Localization has been going from it for several years now, actually I am collecting localization, before me Arkady collected it. You can ask Sergey.

**Comment by b2z** [comment]
Hi guys. @SergeyLitvinov is not active at least several years. Me and @zikkuratvk currently managing all the localisation stuff.

Due to sanctions his account is blocked at Github and almost everywhere :( Please advise how to change Russian TT leader.

**Comment by b2z** [comment]
@infograf768 we are collecting changes in our repo and then moving them directly to Crowdin.

**Comment by infograf768** [comment]
Folks, the TT coordination was not informed about Sergey not being active for "several years".
We know the ru-RU installation ini (as well as the last available ru-RU lang pack) are not up-to-date but I can see here on Joomlacode that Sergey was the one who posted the last ru-RU pack on joomlacode, and that is a few months back, not several years.

Screen Shot 2020-03-20 at 08 44 52

Evidently, if your updated pack is not present on joomlacode, it is quite useless.

We are going to try to contact Sergey.
In the mean while please contact Mig ASAP at
https://forum.joomla.org/memberlist.php?mode=viewprofile&u=224484
so that we can solve the situation

**Comment by zikkuratvk** [comment]
Sergey places, but the package is collected and localized by other people.
Dates and versions are set automatically when the package is built.

https://github.com/JPathRu/localisation/blob/master/package.json

**Comment by infograf768** [comment]
@zikkuratvk 
We have no reason not to believe what you say but the change in lang TT leader has to go through the TT Coordination, so that we give access to joomlacode and the Translation Private Forum to the new one.
Please contact Mig who is in charge so that he has your forum credentials, mails while we try to contact Sergey.

**Comment by b2z** [comment]
@infograf768 ok, contacted Mig through forum.

**Comment by jwaisner** [comment]
Closing as this has been directed to the correct group.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28400">issues.joomla.org/tracker/joomla-cms/28400</a>.</sub>

**Pull request closed without merging**
