### PR TITLE
Add email to contacts list

### PR DESCRIPTION
**Pull request by roland-d**
## Goal

The goal of this pull request is to show the email address of the linked user.
## Test instructions
1. Go to the contact list and make sure there is at least 1 contact with a linked Joomla user
2. See that only the linked username is displayed
3. Apply patch
4. Refresh the contact list, now you will see the linked user email address below the username
5. Test finished

### CODE REVIEW

**Comment by vinespie** [comment]
@test Succes <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6931">issues.joomla.org/joomla-cms/6931</a>.</sub>

**Comment by pe7er** [comment]
@test success, after the patch the e-mail address is displayed under the users name<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6931">issues.joomla.org/joomla-cms/6931</a>.</sub>

**Comment by sovainfo** [comment]
Suggest to add the mail to line 168 instead of 162.

**Comment by roland-d** [comment]
@sovainfo Good point. I have moved the field and updated the rest of the query to use the query builder.

**Comment by pe7er** [comment]
@test works as advertised :smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6931">issues.joomla.org/joomla-cms/6931</a>.</sub>

**Comment by zero-24** [comment]
@test works. Great work RTC'ing again :smile:

**Comment by Kubik-Rubik** [comment]
Merged. Thank you for your contribution @roland-d!

**Pull request closed without merging**
