### PR TITLE
[mod_feed] - strip html from string truncate

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #15095 .

### Summary of Changes
strip html from string truncate

### Testing Instructions
Go to Components > Post-install Messages.
View page source.
Scroll to the bottom of the page.

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 7d571c6e55f0db5af3b5556bd5e65740482f1a41<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15170">issues.joomla.org/tracker/joomla-cms/15170</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 7d571c6e55f0db5af3b5556bd5e65740482f1a41<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15170">issues.joomla.org/tracker/joomla-cms/15170</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Comment by Quy** [comment]
This strips `<p class="lead">` which makes the font-size of the description smaller from 19.5px to 13px. Are we okay with this?

**Pull request merged**
