### PR TITLE
[4.0] Replace inline style width 3%, 6%, 7% with w-3, w-6, w-7

### PR DESCRIPTION
**Pull request by Quy**
Continuation of PR #28692

### Summary of Changes
Add w- classes.
Replace inline style widths % with w-.

### Testing Instructions
Code review.

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 2b79b2e029bfe6f0da98b64b6e907c6b86495d3e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29027">issues.joomla.org/tracker/joomla-cms/29027</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 2b79b2e029bfe6f0da98b64b6e907c6b86495d3e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29027">issues.joomla.org/tracker/joomla-cms/29027</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29027">issues.joomla.org/tracker/joomla-cms/29027</a>.</sub>

**Comment by brianteeman** [comment]
I understand and agree with the addition of the larger numbers - but this is really going too far. Why stop at w-3, w-6,  w-7 whats wrong with w-4, w-8 and w-9

**Comment by Quy** [comment]
I am just going through the existing values. There is one more round to do. ~~Then these can be adjusted/rounded up if desired to reduce the number of sizes.~~

**Comment by Quy** [comment]
Maybe change `3` to `5`, and `6,7` to `10`.

**Comment by Quy** [comment]
I am going to keep it as it. The only difference is that it is now `class` and not `style`.

**Comment by infograf768** [comment]
tks

**Pull request merged**
