### PR TITLE
Syntax error rectified in SQL query

### PR DESCRIPTION
**Pull request by GABBAR1947**
Pull Request for Issue #9926

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on e3e2bcc3c9745f83a92f48ec26d2585156b87287<br /><br />by code review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9946">issues.joomla.org/joomla-cms/9946</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@brianteeman please remove the composer label.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on e3e2bcc3c9745f83a92f48ec26d2585156b87287<br /><br />Tested by code review - it in fact corrects an SQL syntax error.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9946">issues.joomla.org/joomla-cms/9946</a>.</sub>

**Comment by infograf768** [comment]
rtc. ok for 3.5.2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9946">issues.joomla.org/joomla-cms/9946</a>.</sub>

**Pull request merged**
