### PR TITLE
Remove unused imports in MFA

### PR DESCRIPTION
**Pull request by nikosdion**
Pull Request for Issue #38483 .

### Summary of Changes

Removes unnecessary imports in com_users classes and view templates touched by the MFA feature.

This is a code quality PR @HLeithner @roland-d 

### Testing Instructions

Install a site and use the MFA feature.

### Actual result BEFORE applying this Pull Request

Everything works.

### Expected result AFTER applying this Pull Request

Everything still works.

### Documentation Changes Required

None.

### CODE REVIEW

**Comment by HLeithner** [comment]
Thanks but I think @fancyFranci should be mentioned here as release lead. Would expect that get merged after we have a stable 4.2 release.

**Comment by nikosdion** [comment]
Thanks! I didn't have both their GitHub handles :)

**Comment by brianteeman** [comment]
Thanks @nikosdion I was a bit scared to rely on my ide without fully understanding it to create the pr myself

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 53567ab987ff64a88569a2b5547a9aa3e912253b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38498">issues.joomla.org/tracker/joomla-cms/38498</a>.</sub>

**Comment by nikosdion** [comment]
@brianteeman You're welcome! This was easy for me, I could even tell why these `use` statements were left behind. I had started this as a standalone component, moved it to a com_users feature then went into two major refactoring rounds. The leftovers were indeed from the three refactoring rounds.

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 53567ab987ff64a88569a2b5547a9aa3e912253b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38498">issues.joomla.org/tracker/joomla-cms/38498</a>.</sub>

**Pull request merged**
