### PR TITLE
Correct active file highlight in Template Manager

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue #25395.

### Summary of Changes

Corrects active file detection in file editor.

### Testing Instructions

Create two files in template directory. One file name should contain the file name of another file. E.g. `menu.php` and `newmenu.php`.
Edit `menu.php` in Template Manager.
Check highlighted files on the left.

### Expected result

`menu.php` highlighted.

### Actual result

`menu.php` and `newmenu.php` are highlighted.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by n9iels** [comment]
I have tested this item :white_check_mark: successfully on e59a42088b952ba8011c754fb599cb662a035d0d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25399">issues.joomla.org/tracker/joomla-cms/25399</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on e59a42088b952ba8011c754fb599cb662a035d0d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25399">issues.joomla.org/tracker/joomla-cms/25399</a>.</sub>

**Comment by ghost** [comment]
Status "Ready To Commit".

**Comment by HLeithner** [comment]
thx

**Pull request merged**
