### PR TITLE
[com_associations] Do not use Copy reference to an existing target

### PR DESCRIPTION
**Pull request by infograf768**
Pull Request for Issue #13812

### Summary of Changes
Prevent displaying the Copy Reference to Target toolbar button when the Target already exists
### Testing Instructions
See #13812

After patch you will get:
screen shot 2017-01-31 at 11 48 22

### CODE REVIEW

**Comment by infograf768** [comment]
@rdeutz @alikon

**Comment by alikon** [comment]
yes make sense 'to hide'

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on b3935bb860d6011a75e6bc87034dbdd242a60bf2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13819">issues.joomla.org/tracker/joomla-cms/13819</a>.</sub>

**Comment by AlexRed** [comment]
I have tested this item :white_check_mark: successfully on b3935bb860d6011a75e6bc87034dbdd242a60bf2<br /><br />Patch ok for me<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13819">issues.joomla.org/tracker/joomla-cms/13819</a>.</sub>

**Comment by infograf768** [comment]
RTC. Thanks for testing<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13819">issues.joomla.org/tracker/joomla-cms/13819</a>.</sub>

**Pull request merged**
