### PR TITLE
[4.0] Make meta description and meta keywords have defaults

### LINKED ISSUE #26650: [4.0] Error saving articles with Publishing Options disabled
### Steps to reproduce the issue

Go to Articles: Options -> Editing Layout tab and switch Publishing Options to **Hide**

Create a new article and save.

### Expected result

Article is saved.

### Actual result

Error message
**Save failed with the following error: Field 'metakey' doesn't have a default value**

Screenshot 2019-10-19 11 00 42

### System information (as much as possible)

Joomla! 4.0.0-alpha12 Alpha [ Amani ] 17-October-2019 20:13 GMT
PHP 7.3.10
MySQL 5.7 (10.4.6-MariaDB)

### Additional comments

thanks @brianteeman https://github.com/joomla/joomla-cms/pull/26629

### PR DESCRIPTION
**Pull request by wilsonge**
- Fixes #26650
- Makes fields optional when creating articles in the API

### Summary of Changes
Makes metakey and metadesc have default values of empty string in the table. Also means these fields aren't required for the API (so I've amended that test to reflect)

### Testing Instructions
Disable the Publishing tabset from being displayed in component options. Try and save an article. Before patch you get a warning metakey is required. After patch article saves successfully.

### Documentation Changes Required
None

### CODE REVIEW

**Comment by uglyeoin** [comment]
I have tested this item :white_check_mark: successfully on 28659b42ce28424eb5b0726e73c6e67fe97ac579<br /><br />I have tested this successfully.  Before there was an error on patch there was none.  <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26714">issues.joomla.org/tracker/joomla-cms/26714</a>.</sub>

**Comment by richard67** [comment]
I have not tested this item.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26714">issues.joomla.org/tracker/joomla-cms/26714</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 28659b42ce28424eb5b0726e73c6e67fe97ac579<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26714">issues.joomla.org/tracker/joomla-cms/26714</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26714">issues.joomla.org/tracker/joomla-cms/26714</a>.</sub>

**Comment by wilsonge** [comment]
Thanks guys!

**Pull request merged**
