### PR TITLE
[4.0] API change PUT to PATCH

### PR DESCRIPTION
**Pull request by brianteeman**
The specification says that updating a record should use the verb PATCH

This PR simply swaps the verb

To test ensure that a json request to update a record that worked with PU now works instead with PATCH

### Documentation

The docs will need to be updated - I will do this once the PR is merged

### Testing Instructions
https://docs.joomla.org/J4.x:Joomla_Core_APIs

### CODE REVIEW

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks. Still got 4 pages of fixes to go:)

**Comment by brianteeman** [comment]
I have updated the documentation so the label can be removed now

**Comment by zero-24** [comment]
Done thanks Brian

**Comment by brianteeman** [comment]
Thanks @zero-24

**Pull request merged**
