### PR TITLE
Change language string

### PR DESCRIPTION
**Pull request by brianteeman**
Change "notification" to "send"
It doesnt change the meaning but it does fix the layout
#### Before

o9ws
#### After

7fes

### CODE REVIEW

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on 9dc6c4be54ca43ed6a96038275f73c012ecebe80<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12364">issues.joomla.org/tracker/joomla-cms/12364</a>.</sub>

**Comment by grhcj** [comment]
I have tested this item :white_check_mark: successfully on 9dc6c4be54ca43ed6a96038275f73c012ecebe80<br /><br />On Review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12364">issues.joomla.org/tracker/joomla-cms/12364</a>.</sub>

**Comment by zero-24** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12364">issues.joomla.org/tracker/joomla-cms/12364</a>.</sub>

**Comment by brianteeman** [comment]
Milestone changed to 3.7 as it is now not planned to have a 3.6.4 release

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
