### PR TITLE
[4.0] Remove vendor prefixes from scss-lint.yml

### PR DESCRIPTION
**Pull request by C-Lodder**
### Summary of Changes

Remove vendor prefixes from `scss-lint.yml` unless they are browser specific properties

### CODE REVIEW

**Comment by brianteeman** [comment]
Do you know what the origin of tht file is? ie is it a set of rules maintained somewhere

**Comment by C-Lodder** [comment]
It was originally a copy of Bootstraps rules but they have moved to stylelint and extended the default rule set

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 4452e176cb73efb3e59394b7364ad5acc067eb3e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25631">issues.joomla.org/tracker/joomla-cms/25631</a>.</sub>

**Comment by Hackwar** [comment]
I have tested this item :white_check_mark: successfully on 4452e176cb73efb3e59394b7364ad5acc067eb3e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25631">issues.joomla.org/tracker/joomla-cms/25631</a>.</sub>

**Comment by ghost** [comment]
Status "Ready To Commit".

**Comment by HLeithner** [comment]
thx

**Pull request merged**
