### PR TITLE
Update cacert.pem to latest Mozilla version

### PR DESCRIPTION
**Pull request by nicksavov**
Pull Request for Issue #: N/A
#### Summary of Changes

Update cacert.pem to latest Mozilla version
#### Testing Instructions

None. It's just syncing the file with the official one at http://curl.haxx.se/ca/cacert.pem

Examples of three previous PRs for it that were merged without testing:
#6878
#4296
#3634
#### Documentation Changes Required

None.
#### Additional info

Need a clarification if I should be using the Centos cacert.pem or Mozilla's. See conversation at https://github.com/joomla/joomla-cms/issues/9367#issuecomment-195097669

### CODE REVIEW

**Comment by brianteeman** [comment]
From my perspective this should NOT be using the Mozilla cert

**Comment by zero-24** [comment]
becarfull @wilsonge switched it to centos here: https://github.com/joomla/joomla-cms/commit/838a459601e6007068ffb8e94b23764039e253b7

**Comment by wilsonge** [comment]
I think we stick with the centos pack. Sadly mozilla time and time again has removed certificates when big entities are still using them (e.g. captcha and AWS previously). Using the centos pack seems to have resolved these problems fairly conclusively.

**Comment by ggppdk** [comment]
@wilsonge 
@brianteeman 

please check your email

**Comment by brianteeman** [comment]
@ggppdk I check my mail all day - dont have anything about cacert in my mail<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11545">issues.joomla.org/joomla-cms/11545</a>.</sub>

**Comment by ggppdk** [comment]
please forget of the mail about cacert, i was wrong about it, lack of sleep ...

**Pull request closed without merging**
