### PR TITLE
Some deprecated methods replacement

### PR DESCRIPTION
**Pull request by frankmayer**
### Summary of Changes
Some deprecated methods replacement

### Testing Instructions
Code review only

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
corrected Title.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16675">issues.joomla.org/tracker/joomla-cms/16675</a>.</sub>

**Comment by wilsonge** [comment]
You can't do this in 3.x - you already tried once and I explained why we couldn't :P https://github.com/joomla/joomla-cms/pull/13164

**Comment by brianteeman** [comment]
Closed for the reason stated above

**Comment by frankmayer** [comment]
Actually this started out as a PR for setlayout() but then I saw the refreshIncludePaths(), without remembering I had done that in the past. Just an idea, it might be a good idea to remark those to not be changed, before anyone else tries to do that.

**Comment by wilsonge** [comment]
I mean `setLayout` still kinda suffers from the same problem as the `refreshIncludePaths` (although admittedly it's far less likely to be overridden)

**Pull request closed without merging**
