### PR TITLE
Directory Listing

### PR DESCRIPTION
**Pull request by ErvisTusha**
CWE-548: Exposure of Information Through Directory Listing

https://cwe.mitre.org/data/definitions/548.html

### CODE REVIEW

**Comment by brianteeman** [comment]
Thank you for your first (public) pull request to joomla. Good to see that you are still checking joomla. I will let the maintainers explain why the files were removed

**Comment by Bakual** [comment]
Imho the index.html files were removed because this is actually a server confguration issue. The index files just were a bandaid around a misconfigured server. Nowadays servers should have directory listing disabled by default and we should not be needed to ship >1000 empty index.html files.

**Comment by HLeithner** [comment]
As Thomas said, I don't believe that they come back. Anyway thanks for your contribution. 

Releated PR https://github.com/joomla/joomla-cms/pull/3788

**Comment by ErvisTusha** [comment]
intitle:"index of /" inurl:components/com_banners/

**Comment by brianteeman** [comment]
Interestingly the first of those that I came across had an index.html and yet still displayed the folder. I guess you really can't fix bad hosting

https://www.heliciculture.net/components/com_banners/models/
image

**Pull request closed without merging**
