### PR TITLE
[4.0] Filtered by - accessibility

### PR DESCRIPTION
**Pull request by brianteeman**
In a previous pull request I added code which adds a caption to every table AND indicates how the table is sorted. This is only visible to screen readers

To improve this further we should also include how the table is filtered.

This **DRAFT** pr which I hope the javascript gurus can help with adds the filtered information.

I have only enabled this for the table of contacts at this time while in draft

Currently the output is like this
```
<caption id="captionTable" class="sr-only">
Table of Contacts
<span id="orderedBy">Sorted by:Title - descending</span>
<span id="filteredBy">Filtered by:Public3</span>
</caption>

```
As you can see the filtered by is displaying just the selected value of the selected filters, which is kind of ok when its text but is meaningless when it is a number.

Ideally it would say
`Filtered by: Access level = Public, Max Levels =3
`

(as this is javascript it will require either` npm i ` or `node build.js --compile-js` to test it)

### CODE REVIEW

**Comment by angieradtke** [comment]
that makes sense .-)

**Comment by brianteeman** [comment]
Maybe someone can convince the accessibility team to test this

**Comment by angieradtke** [comment]
Christiane helped Stefan. He knows what do do - still waiting   for results (1 week).

**Comment by brianteeman** [comment]
Closed - let the accessibility team fix it

**Comment by wilsonge** [comment]
https://github.com/joomla/joomla-cms/compare/4.0-dev...wilsonge:feature/filtered-items-a11y?expand=1

Javascript here for you hopefully. It's enough to work - although as the labels seem weird right now the text could be improved. But hopefully that's enough for someone to run with

**Comment by brianteeman** [comment]
Thanks. Will check it out over the weekend

**Pull request closed without merging**
