### PR TITLE
Delete unnecessary code

### PR DESCRIPTION
**Pull request by eopws**
### Summary of Changes

Delete extra if block.
This pull request is not assigned with any issue as it makes the code more redable

### Testing Instructions

No testing instruction is specified as the pull request doesn't change the application logic, but makes code more readable

### CODE REVIEW

**Comment by brianteeman** [comment]
What makes you think the code isnt required?

Where is it used? That way people will be able to test it.

**Comment by eopws** [comment]
> What makes you think the code isnt required?

Because the code has inner if block with the same condition (`!isset($paths[$dispatcherHash][$path])`) as the outer if block has (`!isset($paths[$dispatcherHash][$path])`)

**Comment by brianteeman** [comment]
That's exactly the sort of information that should have been in your first post explaining the change. Remember that a diff/patch/ will not always show enough code for it to be obvious

**Comment by eopws** [comment]
Sory, if I provided not enough information. I thought this pull request has too small changes to write a lot to description.

**Comment by ReLater** [comment]
I have tested this item :white_check_mark: successfully on 44ba3bc3a111bace8a6d07eb2ed0983b7de1e351<br /><br />Code review. Obviously redundant code after checking line 247 (outer if{})<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33115">issues.joomla.org/tracker/joomla-cms/33115</a>.</sub>

**Comment by joomdonation** [comment]
I have tested this item :white_check_mark: successfully on 44ba3bc3a111bace8a6d07eb2ed0983b7de1e351<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33115">issues.joomla.org/tracker/joomla-cms/33115</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33115">issues.joomla.org/tracker/joomla-cms/33115</a>.</sub>

**Comment by eopws** [comment]
Does anybody know how to delete that second commit that I added accidentally?

**Comment by richard67** [comment]
@eopws I've reverted your last commit for you. Maybe one thing you should keep in mind when making again a pull request in future: Please always first create a new branch based on the branch for which the PR shall be made, which is in this case staging, and then use that new branch for the PR. Golden rule: For each PR a separate branch.

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
