### PR TITLE
CodeStyle - use caps

### PR DESCRIPTION
**Pull request by brianteeman**
All language constants should be in uppercase - some were lowercase in error

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on d48860f50fdeb12aa96db24ea7edbc3c14bd0dd0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23558">issues.joomla.org/tracker/joomla-cms/23558</a>.</sub>

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on d48860f50fdeb12aa96db24ea7edbc3c14bd0dd0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23558">issues.joomla.org/tracker/joomla-cms/23558</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC
Thank you<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23558">issues.joomla.org/tracker/joomla-cms/23558</a>.</sub>

**Comment by zero-24** [comment]
Merging thanks!

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
