### PR TITLE
Apply PHPCS to the build tools and remove unused md5/sha1 hashes

### PR DESCRIPTION
**Pull request by zero-24**
### Summary of Changes

Apply PHPCS to the build tools and remove unused md5/sha1 hashes

### Testing Instructions

- make sure the builds (below this page) still works.
- code review

### Actual result BEFORE applying this Pull Request

Some phpcs issues as well as the generation of the not used md5 & sha1 hashes

### Expected result AFTER applying this Pull Request

Lesser phpcs issues as well as no md5 nor sha1 hashes anymore

### Documentation Changes Required

none

### CODE REVIEW

**Comment by PhilETaylor** [comment]
see https://github.com/zero-24/joomla-cms/pull/49

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 8958b6cd1b51b7c39a881c42080a8ae2f72cabec<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34290">issues.joomla.org/tracker/joomla-cms/34290</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 8958b6cd1b51b7c39a881c42080a8ae2f72cabec<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34290">issues.joomla.org/tracker/joomla-cms/34290</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34290">issues.joomla.org/tracker/joomla-cms/34290</a>.</sub>

**Pull request merged**
