### PR TITLE
[4.0] Field category (custom fields + create new category on the fly)

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # .

### Summary of Changes
- Remove the dead code, chosen that is
- Remove the inline script from custom fields

### TODO
- Restore the ability to add categories on the fly
- Enhance the category creation so user can create child category (now only root cats 😸 are allowed)
- Restore the search functionality

### Testing Instructions
On an article with fields enabled try to change the category. Page reloads with or without the custom fields depending if they are assigned

### Documentation Changes Required
???

@laoneo

### CODE REVIEW

**Comment by brianteeman** [comment]
Is this still a WIP or is it ready for testing?

**Comment by dgrammatiko** [comment]
@brianteeman this is ready for testing

**Comment by brianteeman** [comment]
@dgrammatiko so is the "todo" stuff done?

**Comment by dgrammatiko** [comment]
Nope, this needs to be a three step process, as the other 2 todos are gonna be also custom elements (but less attached to this particular field) and thus they need to be developed in their own PRs. Just to clear things here, we still need:
- a way to add new category (a11y compliant etc)
- a way to search a long select list (probably by introducing our own joomla-select, based on the repo you pointed in that other issue)

**Comment by dgrammatiko** [comment]
@brianteeman how hard will it be to make chosen accessible and mobile friendly?
I mean converting it to vanilla and custom element is not a big deal: https://codepen.io/dgt41/pen/bvOdZp

**Comment by brianteeman** [comment]
why are you even thinking of that. I have already given you recommendations for fully accessible options

**Comment by brianteeman** [comment]
https://github.com/joomla/joomla-cms/issues/16041

**Comment by dgrammatiko** [comment]
@brianteeman I'm gonna replace the awesomplete with the one that you are proposing in that issue but that script has nothing to do with chosen and the 3 ways we're using it in joomla. It's not even a candidate for chosen replacement...

**Comment by dgrammatiko** [comment]
OK @brianteeman here's something for you to evaluate:
screen shot 2018-04-08 at 23 55 23

The only problem with the suggest script (apart that it's dragging the whole PREACT with it) is that once you select something and you need to change your selection you have to manually delete (thats a lot of backspace keystrokes) to get the full list of options
screen shot 2018-04-08 at 23 55 33

We still have to implement a way to add a new category!
And also this script doesn't really work with multiple selects so for tags we need another solution...
Anyways let me know if this is something we should consider here otherwise I will revert the last commit

**Comment by brianteeman** [comment]
sorry I didnt realise you had updated this to use accessible-autocomplete - i expected to see it as a separate file. will take a look tomorrow

**Comment by brianteeman** [comment]
@dgrammatiko can you fix the conflicts please so it can be tested

**Comment by dgrammatiko** [comment]
@brianteeman the create new category is WIP, let me know what you think about the idea (obviously it needs a lot of polishing if this is what we want)
screenshot 2018-07-22 at 21 41 33
screenshot 2018-07-22 at 21 41 51
screenshot 2018-07-22 at 21 42 01

**Comment by TobsBobs** [comment]
I have tested this item :red_circle: unsuccessfully on ab881f4ede56844a99f02055b7d82548cb8b1565<br /><br />
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19671">issues.joomla.org/tracker/joomla-cms/19671</a>.</sub>

**Comment by TobsBobs** [comment]
screen shot 2018-08-04 at 12 15 48<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19671">issues.joomla.org/tracker/joomla-cms/19671</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on ab881f4ede56844a99f02055b7d82548cb8b1565<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19671">issues.joomla.org/tracker/joomla-cms/19671</a>.</sub>

**Comment by ghost** [comment]
@TobsBobs i didn't get the Warning (on com_fields i used a Text-Field).

**Comment by TobsBobs** [comment]
I retest this patch and it is not working. I have created some categories but I can't change the category of the article. On com_fields i also used a Text-Field.

**Comment by ghost** [comment]
- create Category on the fly: works.
- change Category: works. In the Thread above is written how: delete Category by hit Backspace, then you get existing Categories.

Test Instructions should be in first Comment.

**Pull request closed without merging**
