### PR TITLE
[5.0]Com admin remove deprecated strings

### PR DESCRIPTION
**Pull request by brianteeman**
Removes strings marked as deprecated
- [x] Pull Request link for manual.joomla.org: https://github.com/joomla/Manual/pull/101/

### CODE REVIEW

**Comment by heelc29** [comment]
not all strings listed in https://github.com/joomla/Manual/pull/101

**Comment by brianteeman** [comment]
Will update in the morning

**Comment by brianteeman** [comment]
> not all strings listed in [joomla/Manual#101](https://github.com/joomla/Manual/pull/101)

updated

**Comment by heelc29** [comment]
I have tested this item :white_check_mark: successfully on 68e64863bc62d0b3c345ec5f91494399045cb73c<br /><br />code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41576">issues.joomla.org/tracker/joomla-cms/41576</a>.</sub>

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
