### PR TITLE
[4.0] TFA google authenticator

### PR DESCRIPTION
**Pull request by brianteeman**
I am not going to pretend to understand the line that was removed. Other than it being an inline style that we dont want anyway for CSP reasons.

### Summary of Changes
Make it possible to see the google tfa options for a user

### Testing Instructions
enable the google tfa plugin
go to your user setting and you will now see a Two factor Authentication tab
Change the setting from Disabled to Google Authenticator

### Expected result
tfanew

### Actual result
The hidden div is never revealed

### Documentation Changes Required
none

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 8b033d7ff187003d2c7f32f1a60a27bcef40e2b1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27367">issues.joomla.org/tracker/joomla-cms/27367</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 8b033d7ff187003d2c7f32f1a60a27bcef40e2b1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27367">issues.joomla.org/tracker/joomla-cms/27367</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27367">issues.joomla.org/tracker/joomla-cms/27367</a>.</sub>

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
