### PR TITLE
Ensure calendar field displays seconds values

### PR DESCRIPTION
**Pull request by paul-muckypuddle**
Pull Request for Issue #16084.

### Summary of Changes
Added switch case to capture seconds value to date helpers. Updated minified helpers.

### Testing Instructions
1. Load any form with a calendar field
2. Modify the seconds portion of the field
3. Save the form
4. Seconds field should be retained and rendered

### Expected result
Seconds field displayed with actual value (not just 00)

### Actual result
Displays as expected.

### Documentation Changes Required
NA

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on b8ef7bfd37eaea0450d742b9ed147e71f4928aff<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17703">issues.joomla.org/tracker/joomla-cms/17703</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on b8ef7bfd37eaea0450d742b9ed147e71f4928aff<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17703">issues.joomla.org/tracker/joomla-cms/17703</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on b8ef7bfd37eaea0450d742b9ed147e71f4928aff<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17703">issues.joomla.org/tracker/joomla-cms/17703</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Comment by ghost** [comment]
RTC after two successful tests.

**Pull request merged**
