### PR TITLE
[4.0] Normalize sample data plugins to use Joomla default workflow

### PR DESCRIPTION
**Pull request by infograf768**
### Summary of Changes
As we now have a Joomla Default workflow, there is no reason anymore to create custom workflows when installing blog or multilang sample data via their plugins. 

### Testing Instructions
Install a clean Joomla.
Patch.

Install French, German or/and Farsi languages.

In Control panel install Multilingual Sample data and then Blog sample Data

### After patch
The content categories created will all have Joomla Default as workflow.
Only Joomla Default will display in the Workflows manager
`/index.php?option=com_workflow&extension=com_content`

@bembelimen

### CODE REVIEW

**Comment by infograf768** [comment]
NOTE: I also found out that without this patch, we have issues with `show associations`, i.e. we need to log in frontend to see them which is pretty weird...

**Comment by bembelimen** [comment]
I have tested this item :white_check_mark: successfully on 76b60dbc2d1ee7368f33172d2a2a291495895858<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23719">issues.joomla.org/tracker/joomla-cms/23719</a>.</sub>

**Comment by imanickam** [comment]
I have tested this item :white_check_mark: successfully on 76b60dbc2d1ee7368f33172d2a2a291495895858<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23719">issues.joomla.org/tracker/joomla-cms/23719</a>.</sub>

**Comment by infograf768** [comment]
RTC. Thanks for testing.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23719">issues.joomla.org/tracker/joomla-cms/23719</a>.</sub>

**Comment by imanickam** [comment]
I have tested this item :white_check_mark: successfully on 56ad8f40f50b83689919ae85c6aba99d376c712c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23719">issues.joomla.org/tracker/joomla-cms/23719</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
