### PR TITLE
[4.0] Use "CREATE TABLE IF EXISTS" in SQL scripts for Postgresql

### PR DESCRIPTION
**Pull request by richard67**
Pull Request for no issue.

### Summary of Changes

This PR adds the "IF EXISTS" condition to all "CREATE TABLE" statements in any SQL scripts for Postgresql as supported since Postgresql version 9.1, so the Postgresql SQL scripts work in the same way as the SQL scripts for mysql.

See [http://stackoverflow.com/questions/1766046/postgresql-create-table-if-not-exists](http://stackoverflow.com/questions/1766046/postgresql-create-table-if-not-exists) and [https://www.postgresql.org/docs/9.2/static/sql-createtable.html](https://www.postgresql.org/docs/9.2/static/sql-createtable.html) regarding the "CREATE TABLE IF EXISTS" support in Postgresql.

Following kinds of scripts are affected:
- Joomla installation script joomla.sql or Postgresql
- All present schema update SQL scripts for Postgresql
- All present special installation SQL scripts for Postgresql (currently only one for com_finder)

These 3 kinds of changes have been added with separate commits so they can be cherry-picked by a maintainer if this PR is not acceptable completely, e.g. in case PLT hates changes on old schema update SQL scripts.

The database schema manager's change item class for Postgresql already supports the "CREATE TABLE IF EXISTS" statements and so does not need to be changed, see [https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/CMS/Schema/ChangeItem/PostgresqlChangeItem.php#L194](https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/CMS/Schema/ChangeItem/PostgresqlChangeItem.php#L194)

### Testing Instructions

- Code review: Check e.g. with findstr on MS Windows or grep on Linux or in an editor with a search function that all "CREATE TABLE" statements in the changed files have been changed, no statement has been forgotten.
- New Joomla installation: All works like before, result is same as without this PR.
- Joomla Update: Works like before, result is same as without this PR.
- Database schema manager: Extensions -> Manage -> Database shows same results and same number of statements as without this PR.

### Expected result

All works like before, result is same as without this PR.

### Actual result

Same as expected result.

### Documentation Changes Required

None.

### CODE REVIEW

**Comment by richard67** [comment]
Corrected grammar in description.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15446">issues.joomla.org/tracker/joomla-cms/15446</a>.</sub>

**Comment by richard67** [comment]
Added half sentence to explain motivation of this PR (make SQL scripts for Postgresql work the same way as for mysql).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15446">issues.joomla.org/tracker/joomla-cms/15446</a>.</sub>

**Comment by richard67** [comment]
Typo corrected.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15446">issues.joomla.org/tracker/joomla-cms/15446</a>.</sub>

**Comment by zero-24** [comment]
looks good from review but why do you send this against 4.0-dev and not staging (to be included in 3.7.1?

**Comment by richard67** [comment]
@zero-24 Because pre-4.0 Joomla has to support pre-9.1 Postgresql ;-)

**Comment by zero-24** [comment]
Ah ok ignotre my question. @wilsonge requested it to be against 4.0-dev

**Pull request merged**
