### PR TITLE
[4.0] validate=email

### PR DESCRIPTION
**Pull request by brianteeman**
All fields with type=email also have a validate=email rule
This one field was missing the validation

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 41867f5c691dcf1cc5461631c3eb3245eee4f73d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25733">issues.joomla.org/tracker/joomla-cms/25733</a>.</sub>

**Comment by dgrammatiko** [comment]
If you add a validate rule also means that the field should be required as it cannot(?) be empty. I don't know if this is the case here

**Comment by brianteeman** [comment]
@dgrammatiko no its not - test it and you will see

**Comment by wilsonge** [comment]
> If you add a validate rule also means that the field should be required as it cannot(?) be empty

https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/Form/Rule/EmailRule.php#L54-L60 

If it's not required and empty then it passes just fine

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks

**Comment by dgrammatiko** [comment]
@wilsonge I was referring to the js part not the php

**Comment by brianteeman** [comment]
@wilsonge as already mentioned numerous times - that code you refer to is not being used

**Pull request merged**
