### PR TITLE
[4.0] Add all stylesheet formatting order to Editorconfig

### PR DESCRIPTION
**Pull request by N6REJ**
Pull Request for Issue # .

### Summary of Changes
adds styling order to all stylesheets per https://developer.joomla.org/coding-standards/scss.html

### Testing Instructions
reformat stylesheet

### Expected result
reformats to the proper order.

### Documentation Changes Required
explain how to use .editorconfig in phpstorm and other ide's.

### CODE REVIEW

**Comment by brianteeman** [comment]
aren't all the ij_ properties unique to jetbrains products?

**Comment by N6REJ** [comment]
idk.

**Comment by brianteeman** [comment]
The answer is that they are specific rules only for phpstorm

**Comment by N6REJ** [comment]
if you have a better way of doing it I"m all ears.

**Comment by mbabker** [comment]
> if you have a better way of doing it I"m all ears.

This is the type of thing that is probably good to add to https://github.com/joomla/coding-standards/tree/master/Joomla/IDE but for the main repo it's probably a better idea to not add things to the `.editorconfig` file that only apply to a single IDE from a single vendor (the intent behind `.editorconfig` is to be a bit more universal than "hey let's optimize the experience for PhpStorm users").

**Comment by N6REJ** [comment]
@mbabker gotcha, I thought it was ..universal?... since phpstorm had it as an export but @roland-d looked and editorconfig doesn't seem to support css/scss etc.. 
I'll do my best to update jdoc tomorrow.  No gray matter left today.

**Pull request closed without merging**
