### PR TITLE
Update tinyMCE to 4.5.3

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/14005 .

### Summary of Changes
Usual update of tinyMCE's code
 
### Testing Instructions
Apply patch and check that everything works as expected, especially the reported bug!

### Documentation Changes Required

---
This change is [Reviewable](https://reviewable.io/reviews/joomla/joomla-cms/14024)

### CODE REVIEW

**Comment by AlexRed** [comment]
I have tested this item :white_check_mark: successfully on 7202d20fd0d1fc638bcc568432aa0c11fed98d2e<br /><br />Patch ok for me, solve #14005
but https://github.com/joomla/joomla-cms/issues/14005#issuecomment-279140582  remains a problem<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14024">issues.joomla.org/tracker/joomla-cms/14024</a>.</sub>

**Comment by JoshuaLewis** [comment]
I have tested this item :white_check_mark: successfully on 7202d20fd0d1fc638bcc568432aa0c11fed98d2e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14024">issues.joomla.org/tracker/joomla-cms/14024</a>.</sub>

**Comment by dgt41** [comment]
The last commit is just an update of the tinyMCE creation date (2016->2017)
Thanks Brian Teeman for this: https://twitter.com/brianteeman/status/830488622679855106

There is no need for removing RTC, a simple review is enough

**Comment by zero-24** [comment]
:+1:

**Pull request merged**
