### PR TITLE
[5.0] %s for strings/floats in sprintf

### PR DESCRIPTION
**Pull request by heelc29**
Pull Request for Issue #41710 .

### Summary of Changes

revert parts from #41710
@brianteeman @HLeithner

com_finder: uses `number_format`
https://github.com/joomla/joomla-cms/blob/d3589c94c0b7e40a1d10314f6aa59591e5165dd0/administrator/components/com_finder/tmpl/statistics/default.php#L18

plg_content_vote: is float
https://github.com/joomla/joomla-cms/blob/d3589c94c0b7e40a1d10314f6aa59591e5165dd0/plugins/content/vote/tmpl/rating.php#L53-L58

finderindex: uses round
https://github.com/joomla/joomla-cms/blob/d3589c94c0b7e40a1d10314f6aa59591e5165dd0/libraries/src/Console/FinderIndexCommand.php#L403

### Testing Instructions

com_finder/statistics: values above 1000
plg_content_vote: two votes (5+4)/2=4.5
finderindex: run cli/joomla.php findex:index

### Actual result BEFORE applying this Pull Request

image
image
image

### Expected result AFTER applying this Pull Request

image
image
image

### Link to documentations
Please select:
- [x] No documentation changes for docs.joomla.org needed
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by tecpromotion** [comment]
I have tested this item :white_check_mark: successfully on 081e91396a63318b290f37d8eeedaaf2c61ea39e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41740">issues.joomla.org/tracker/joomla-cms/41740</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 081e91396a63318b290f37d8eeedaaf2c61ea39e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41740">issues.joomla.org/tracker/joomla-cms/41740</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41740">issues.joomla.org/tracker/joomla-cms/41740</a>.</sub>

**Comment by HLeithner** [comment]
does %f work @heelc29 ?

**Comment by heelc29** [comment]
> does %f work @heelc29 ?

The first one com_finder.ini: No because it is a string - see https://www.php.net/manual/de/function.number-format.php

The others: There is a different for number of digits to be printed after the decimal point (by default, this is 6) https://www.php.net/manual/en/function.sprintf.php

Example:
```
value: 45.12
output (s) 45.12
output (f) 45.120000
```

**Comment by Quy** [comment]
No as it displays `.0`.

For example:
`PLG_VOTE_STAR_RATING="Rating: %.1f out of 5"`

`Rating: 2.0 out of 5`

**Comment by HLeithner** [comment]
I merge this for now

**Pull request merged**
