### PR TITLE
Namespace JRoute class and deprecate it

### PR DESCRIPTION
**Pull request by laoneo**
Namespaces the `JRoute` class. Additionally it deprecates it and moves the single `_` function to the router class in a none static way.

### CODE REVIEW

**Comment by mbabker** [comment]
If you're really going to move it like this, find a better name than `_`.

**Comment by mbabker** [comment]
Also, not merging this one until we have https://github.com/joomla/joomla-cms/pull/16879 in place.  That will probably require re-reviewing your deprecation.

**Comment by laoneo** [comment]
Makes sense...honestly I was not sure how to name that function so I took the easy way. But I'm up for suggestions.

**Comment by mbabker** [comment]
Closing, as is this is heavily out of date and after #16879 it needs to be rethought how to handle such a deprecation if it's going to be proposed and accepted.

**Pull request closed without merging**
