### PR TITLE
Rename form fields to lowercase

### PR DESCRIPTION
**Pull request by laoneo**
Pull Request for Issue #17460.

### Summary of Changes
Because of autoloading the class names and their corresponding files must match the scheme first character uppercase then all lowercase and `Field` as suffix. This pr changes the core fields to that.

### Testing Instructions
- Log in on the back end
- Go to Users -> Manage
- Click on the "Search Tools" button

### Expected result
Proper select boxes do appear.

### Actual result
Only input text fields are shown.

### CODE REVIEW

**Comment by alikon** [comment]
this pr with com_patchtester
screenshot from 2017-08-17 20-22-52

should be patched without com_patchtester?

**Comment by laoneo** [comment]
Guess you need to update your staging branch.

**Comment by alikon** [comment]
the test was made with the current staging (at the test time), i'll redo the test ex-novo without patchtester

**Comment by laoneo** [comment]
I'v also merged staging int this branch. So now it should be even.

**Comment by alikon** [comment]
thanks and sorry for the extra work  :smile:

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 0fd02414a0b7d859145c47e7f865dee595e8f12f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17584">issues.joomla.org/tracker/joomla-cms/17584</a>.</sub>

**Comment by laoneo** [comment]
The issue of this pr had a release blocker label, should this pr then also get it?

**Comment by CiverBlack** [comment]
I have tested this item :red_circle: unsuccessfully on 0fd02414a0b7d859145c47e7f865dee595e8f12f<br /><br />I went to the Users -> Manage and i didn't get the problem you described. After that i installed the patch via patch tester and nothing changed. I was also unable to revert the patch via patch tester so something went wrong there but i couldn't find out what.

@iCampus<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17584">issues.joomla.org/tracker/joomla-cms/17584</a>.</sub>

**Comment by laoneo** [comment]
I'm not sure if the problem is because of the different file names. Please install joomla from here https://github.com/Digital-Peak/joomla-cms/archive/form/fields/lowercase.zip and test it again.

**Comment by CiverBlack** [comment]
I have tested this item :white_check_mark: successfully on 0fd02414a0b7d859145c47e7f865dee595e8f12f<br /><br />Yes now it works

@iCampus<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17584">issues.joomla.org/tracker/joomla-cms/17584</a>.</sub>

**Comment by laoneo** [comment]
Thanks for testing!

**Comment by ghost** [comment]
RTC after two successful tests.

**Comment by SharkyKZ** [comment]
@laoneo is it correct that RedirectStatusField.php was not renamed? The field works but this looks inconsistent.

**Pull request merged**
