### PR TITLE
[4.0] Webinstaller

### PR DESCRIPTION
**Pull request by N6REJ**
Pull Request for Issue # .
#26716
### Summary of Changes
The installer isn't a "web" installer like whmcs et al so lets not call it that.

### Testing Instructions
Do a clean install of 4.0-dev.
Check Installer title
Apply patch
Test again.

### Expected result
image

### Actual result
image

### CODE REVIEW

**Comment by brianteeman** [comment]
It is a web installer when compared to a command line installer

**Comment by N6REJ** [comment]
@brianteeman
> Online/Web Installer
Online/web installer is a small setup which downloads the remaining components after it is run. You need Internet access every time you want to install the Web/Online Installer of any program or software.

**Comment by brianteeman** [comment]
Disagree,

Anyway you must remove the package lock from this PR

**Comment by N6REJ** [comment]
that damn lock was not there when I committed and pushed  *grrrrrrrrrrrrrrr*

**Comment by uglyeoin** [comment]
I have tested this successfully and I think this change is sensible.  <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26721">issues.joomla.org/tracker/joomla-cms/26721</a>.</sub>

**Comment by uglyeoin** [comment]
I have tested this item :white_check_mark: successfully on c9936cd8f299672e48f0b2b518fc791d956bf54d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26721">issues.joomla.org/tracker/joomla-cms/26721</a>.</sub>

**Comment by N6REJ** [comment]
see #26723

**Comment by softforge** [comment]
I have tested this item :white_check_mark: successfully on c9936cd8f299672e48f0b2b518fc791d956bf54d<br /><br />It removed the web...<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26721">issues.joomla.org/tracker/joomla-cms/26721</a>.</sub>

**Pull request closed without merging**
