### PR TITLE
[4.0] Workflow missing string

### PR DESCRIPTION
**Pull request by brianteeman**
PR for #30807

### Steps to reproduce the issue

Enable com_workflow in Backend, open an Article in Frontend, open Tab 'Publishing'

### Expected result
Translated Constant.

### Actual result
Constant

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on f709c8489c3a91dd68147b2e8d0a121cb20c9ddc

thanks @brianteeman
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30811">issues.joomla.org/tracker/joomla-cms/30811</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on f709c8489c3a91dd68147b2e8d0a121cb20c9ddc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30811">issues.joomla.org/tracker/joomla-cms/30811</a>.</sub>

**Comment by zero-24** [comment]
Merged thanks

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
