### PR TITLE
Using the Canadian flag for the fr-CA code

### PR DESCRIPTION
**Pull request by MATsxm**
Using the flag of the Province of Québec for the language code fr-CA is not appropriate.

Either the flag must be considered from the language point of view and then the French flag should be used and also the en-CA should then use the Union Jack or we take as reference the location.
In this case, and following the logic of the en-CA code, the flag should be the one of Canada.

Indeed, the flag of Québec should be used for the language code fr-QC and as a side note, Québec is not the only Province of Canada having French as official language, then there is no justification to use the flag of Québec, once again except if you decide to use it for fr-QC.

### CODE REVIEW

**Comment by infograf768** [comment]
No, again...
**One can change if desired, and specially in frontend**. 
The icon is just there to differentiate the languages when installing Joomla as multilang.
The en-CA flag is already using the Canadian flag.
QC is not an ISO country code.

**Comment by infograf768** [comment]
AND this is not B/C.
See https://github.com/joomla/joomla-cms/pull/12014 for a correct implementation.

Can be closed

**Comment by Bakual** [comment]
It indeed is not backward compatible as it would change the flags on existing sites from a Quebec flag to Canadian flag. Even if I understand the request :smile:

**Comment by MATsxm** [comment]
Sorry @infograf768 but I know and understand what you're saying the thing is that you are using for years the **WRONG** flag even in Backend.
It is the same as using Kenyan flag , what would you say: "this is not B/C"?.This dones't even respect YOUR logic.

> Trust me, there is no proper flag to be used for de-CH. Everything else will be a joke or even offensive to Swiss people.
Strange how you can understand this for Swiss and don not taking care of people living in the Nouveau Brunswik...

**Comment by Bakual** [comment]
If we merge my PR, we *could* do it in a B/C way for new installations, by just removing the file completely. Then it would use the `ca.gif` as no `fr_ca.gif` is present but wouldn't change all existing sites on an update (which we can't do).

**Comment by MATsxm** [comment]
Sorry to say that but this is quite a better argument than saying "because it was wrong for years without complain on the forum we won't try to find a solution".

**Comment by infograf768** [comment]
@MATsxm 
It looks like you still do not understand the need, when a Content Language is automatically created, to get a flag/icon different for every Content Language, specially in back-end.
I don't know what to do to get this concept clearer to you.

Yes, I don't like so much de-CH using the pure Swiss flag/icon, because we may not get any difference with a possible fr-CH or it-CH, BUT AT LEAST the ch.gif flag/icon —for now— IS DIFFERENT from all the other flags/icons.

In any case, once a Content Language has been automatically created, a user can change the icon at will and I am pretty sure that user is not going to use the same flag/icon for 2 different languages.

A New Brunswick multilang site wanting to present French and English language will, if he prefers icons to sef code, just use the fr.gif for French and en.gif for English and NOT the Canadian flag at all.

One can do what one wants in frontend, icons or sef code: already explained multiple times.

You do not need to reply if that simple notion can't get its way to the New Indies.

**Comment by infograf768** [comment]
I now unsubscribe from this PR

**Comment by MATsxm** [comment]
I guess you wanted to say **WEST** Indies ;)

**Comment by Hils** [comment]
As this seems at an impasse, has anyone thought of asking a Canadian what their view is? Joe Sonne, ex OSM, could arbitrate perhaps. https://joejoomla.com/joe-sonne-marketing

**Comment by Hils** [comment]
@JoeJoomla

**Comment by MATsxm** [comment]
Sorry @Hils but no need to be Canadian to be logical and contrary to what JM wants other to think, I do understand that I have the choice to use in FRONTEND the Italian flag (or icon which is a flag but not quite a flag but a bit of flag anyway....) for a site in German but this is not the point.
But surprises.... not at all....

**Comment by JoeJoomla** [comment]
Hi there,

I got the notification of this discussion. I'm by no means an International expert in regards to this topic and the following represents my personal opinion only.

Here is an official Canadian government website on the topic of "Flags of La Francophonie" http://canada.pch.gc.ca/eng/1443808632954

You'll note down that page the topic "The flags of Canada, Quebec and New Brunswick officially represent the Canadian Francophonie"

See "The flag of La Francophonie" which appears on that page. Here's a link to the image: http://canada.pch.gc.ca/DAMAssetPub/DAM-PCH2-Identity-AnthemsSymbols/STAGING/images-images/drapeau_francophonie-francophonie_flag_1443808771858_eng.jpg

The Canadian flag https://en.wikipedia.org/wiki/Flag_of_Canada is for all of Canada which nationally represents a bilingual country, English and French.

So if you use the Canada flag it's both English and French.

The flag of Quebec, the Fleurdelisé https://en.wikipedia.org/wiki/Flag_of_Quebec , is a provincial flag representing one province. Quebec has provincial language laws designed to preserve the French language culture of Quebec.

I've become accustomed to using the British flag for English and the flag of France for French because it distinguishes specifically between the English and French languages.

In a Joomla site If I needed French and French Canadian French I would personally use the French flag for the French language icon and the Fleurdelisé for the French Canadian language icon since I doubt the flag of La Francophonie would be available.

I'm not sure how many people even in Canada would recognize or understand what the flag of La Francophonie is but according to that website it's official.

**Pull request closed without merging**
