### PR TITLE
[imp] Categories Manager: Adding tooltip to the category title

### PR DESCRIPTION
**Pull request by infograf768**
After patch we will get:

screen shot 2015-01-21 at 08 53 39

### CODE REVIEW

**Comment by brianteeman** [comment]
Is it really necessary to have a tooltip to say that if you click on something that is obviously a link then the link will open<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5846">issues.joomla.org/joomla-cms/5846</a>.</sub>

**Comment by infograf768** [comment]
As stated elsewhere, this is just to normalise.

**Comment by brianteeman** [comment]
Normalise with what. I just had a quick look and I didn't see any instances
of the title field having a tooltip in any manager

**Comment by infograf768** [comment]
Just hover any link to edit an article. The Title exists there and therefore a tip shows, why not for categories?

**Comment by phproberto** [comment]
I agree with adding the title attribute which is the correct and accessible way. I don't agree with showing tooltips.

**Comment by infograf768** [comment]
Yes, obviously, we should have a Title attribute, that's why I added one in this PR.
Concerning the tip: we have a sort of tip by default if we do not add the class, it is the black text on yellow background (Firefox).

tooltip

Is'nt it better to also normalize this and show it as white on black, as for other tips?

**Comment by phproberto** [comment]
> Is'nt it better to also normalize this and show it as white on black, as for other tips?

I don't think so. What you are seeing is rendered by the browser and does not require any javascript. Perfect for me.

**Comment by rmittl** [comment]
The patch is working fine, but I think this feature does not have really a advantage, due to the categorie above is hidden from the tooltip.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5846">issues.joomla.org/joomla-cms/5846</a>.</sub>

**Comment by Wilma999** [comment]
I have tested this item :white_check_mark: successfully on 4e2c5920663b3e411a25ce4eb8c52328aa443c39<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5846">issues.joomla.org/joomla-cms/5846</a>.</sub>

**Comment by snarf007** [comment]
I have tested this item :white_check_mark: successfully on 4e2c5920663b3e411a25ce4eb8c52328aa443c39<br /><br />Before applying the patch no tooltip. After applying the patch the tooltip (edit) pops-up on hover.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5846">issues.joomla.org/joomla-cms/5846</a>.</sub>

**Comment by zero-24** [comment]
RTC based on testing. The maintainer should take the decision on this Closing or Merging. Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5846">issues.joomla.org/joomla-cms/5846</a>.</sub>

**Pull request merged**
