### PR TITLE
[4.1] Support class attribute in media custom field

### PR DESCRIPTION
**Pull request by laoneo**
Pull Request for pr #27712.

### Summary of Changes
The accessible media form field doesn't support the class property. This pr fixes it.

### Testing Instructions
- Create a media custom field
- In the options of the field set the "Field Class" attribute to `testclass`
- Save the field
- Edit an article
- Inspect the `joomla-field-media` element of the custom field in the dev tools of the browser

### Actual result BEFORE applying this Pull Request
No `testclass` is added to the element.

### Expected result AFTER applying this Pull Request
`testclass` is added to the element.

### CODE REVIEW

**Comment by laoneo** [comment]
@astridx can you have a look here if all is correct?

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on e4f4e2df48e48f0685814e2cc1131cb08d23b458<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36593">issues.joomla.org/tracker/joomla-cms/36593</a>.</sub>

**Comment by HusiBT** [comment]
I have tested this item :white_check_mark: successfully on 87ab096ea4ed0f219e467fd1f0058782fe41d845<br /><br />Tested successfully.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36593">issues.joomla.org/tracker/joomla-cms/36593</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36593">issues.joomla.org/tracker/joomla-cms/36593</a>.</sub>

**Comment by wilsonge** [comment]
This looks kinda weird because the class is already being set on the input element within the custom form field. Does it really make sense to have it in both places?

**Comment by laoneo** [comment]
Did you actually test it? The class is not set, as it is not passed into the subform group. It is not rendered at all in any of the elements.

**Comment by wilsonge** [comment]
Yes I understand that the FormField layout is clearly correct. I'm asking specifically about the JLayout change as the class is also used here https://github.com/joomla/joomla-cms/pull/36593/files#diff-ffc48fe23d772f6461955e77801148ec01945822ae6574126b6cece7f7bccd26R54 and you're now adding it again on the custom element.

**Comment by laoneo** [comment]
The class is only added to the custom element and nowhere else. The class is delegated to the element from the Formfield but never used there as you can see here https://github.com/joomla/joomla-cms/blob/4.1-dev/layouts/joomla/form/field/media/accessiblemedia.php. So where should then the class being used in your opinion?

**Comment by laoneo** [comment]
Made another test and indeed you are right, the class is used on the input. So it would be wrong to render it two times.

**Pull request closed without merging**
