### PR TITLE
Menus: All Menu Items - Component Filter

### PR DESCRIPTION
**Pull request by pe7er**
Pull Request to add a Component filter to the "Menus: Items" overview.

### Summary of Changes
This PR adds a **Component filter to the menu items overview** so that you can filter on specific Components.

### Before Patch
menu-component-filter-before

### Testing Instructions
Install the PR.
Open the Menus: All Menu Items page (Menus > All Menu Items), 
click on "Search Tools",
select a component (e.g. Newsfeeds).

menu-component-filter1

### Expected result
The list of menu items should be filtered to only show menu items to views of that selected Component.

menu-component-filter2

### CODE REVIEW

**Comment by roland-d** [comment]
Joomla 4 version: https://github.com/joomla/joomla-cms/pull/21358

**Comment by pe7er** [comment]
@roland-d ah, thanks. Maybe this can still be added to the 3.x series?

**Comment by infograf768** [comment]
> Maybe this can still be added to the 3.x series?

Not sure as this is a new feature.

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 24d6ce97daf3048dd7cf781855e1f88132c279d4<br /><br />tested on J3.9.2
@pe7er & @infograf768 .. ah I also see. Maybe in addition for planning 3.10 in connection Joomla4 (roadmap)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23566">issues.joomla.org/tracker/joomla-cms/23566</a>.</sub>

**Comment by brianteeman** [comment]
is there an official statement anywhere about new features and 3.10

**Comment by Sandra97** [comment]
As far as I know, these statements about features in 3.10 are still valid:

https://joom.la/jQH
> If  you want to propose a new feature for Joomla, we invite you to do it toward the Joomla 4 branch.

https://joom.la/hDN
> At this point most feature proposals should be directed toward the 4.0 release; minor features may be evaluated and included in one of the final 3.x releases. This will be at the discretion of the release leads.

We will remind in the Alpha 7 blog post that new features are expected to be pointed at the 4.0-dev branch

**Comment by pe7er** [comment]
Thank you all for the feedback!

@infograf768 Isn't it a small fix to fix an existing overview? 
It does not have any database changes or influences on other part of Joomla.
I always thought that features would be bigger and have more impact...

Thanks @ChristineWk for testing!

**Comment by ChristineWk** [comment]
@pe7er graag gedaan :-)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23566">issues.joomla.org/tracker/joomla-cms/23566</a>.</sub>

**Comment by mbabker** [comment]
> I always thought that features would be bigger and have more impact...

The very basic definition of a feature is adding a new capability that didn't exist before.  So adding a new list filter fits that basic definition.

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 24d6ce97daf3048dd7cf781855e1f88132c279d4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23566">issues.joomla.org/tracker/joomla-cms/23566</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23566">issues.joomla.org/tracker/joomla-cms/23566</a>.</sub>

**Comment by ghost** [comment]
Closed in favor of #24665

**Comment by pe7er** [comment]
I've re-done this PR for Joomla 4: https://github.com/joomla/joomla-cms/pull/24665

**Pull request closed without merging**
