### PR TITLE
Remove unnecessary condition

### PR DESCRIPTION
**Pull request by nvyush**
The check ```!empty($this->item)``` is unneeded at this point.
It is possible to join the statements of if conditions at the lines 72 and 77.

Pull Request for Issue #16409.

### Summary of Changes
Unnecessary condition is removed.
The statements of equivalent conditions is joined.

### Testing Instructions
Code review.

### Documentation Changes Required
Not needed.

### CODE REVIEW

**Comment by Bakual** [comment]
Not sure if that is accurate.
Because the first check `!empty($this->item->id)`is only true when the item already has an id set and other than 0/false (means we edit an existing item).
The second check `!empty($this->item) && isset($this->item->id)` will be true if the item is valid, but the ID may also be 0 (means it can also be a new item).

**Comment by nvyush** [comment]
Well, but check ```!empty($this->item)``` is not needed and can be removed. Are you agree?
I can update the commit.

**Comment by nvyush** [comment]
I do not understand, why commit 5ed1d17 is valid, but 6b585ae is not. I simple removed white spaces.

**Review by Bakual — APPROVED** [review]

**Comment by Bakual** [comment]
Imho, the isset should indeed be sufficient, because it will also return false if the item doesn't exist. So we gain nothing by explictiely checking the existence of the item prior to it.

I tried to restart the drone test. looks like an unrelated error to me.

**Comment by nvyush** [comment]
@Bakual, why ```continuous-integration/jenkins/pr-merge``` reported an error? What I must do?

**Comment by rdeutz** [comment]
@nvyush you can ignore the jenkins failure for now, we are testing a new setup. It is important that the Required checks pass and the drone test (code styles) should also pass.

**Comment by nvyush** [comment]
@rdeutz, thanks

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 60788fde2cfe58e786c8c16cc997bddd403603cb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16412">issues.joomla.org/tracker/joomla-cms/16412</a>.</sub>

**Comment by fancyFranci** [comment]
For new items the ID is always NULL. Even by saying a_id=0 in the url. So why not joining the two if-conditions?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16412">issues.joomla.org/tracker/joomla-cms/16412</a>.</sub>

**Comment by Quy** [comment]
@FPerisa You're right. They can be combined and remove the second if statement.

**Comment by Quy** [comment]
See PR #20254<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16412">issues.joomla.org/tracker/joomla-cms/16412</a>.</sub>

**Pull request closed without merging**
