### PR TITLE
[4.0] Save button margin

### PR DESCRIPTION
**Pull request by brianteeman**
Simple PR to adjust the margin - see screenshots. 
Apply PR and rebuild the css

### Before
image

### After
image

### CODE REVIEW

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 8997feea7a5ff6005276dffafae717524394e616<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32551">issues.joomla.org/tracker/joomla-cms/32551</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 8997feea7a5ff6005276dffafae717524394e616<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32551">issues.joomla.org/tracker/joomla-cms/32551</a>.</sub>

**Comment by Quy** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
