### PR TITLE
[4] View user profile. aria-hidden="true" for icon-user

### PR DESCRIPTION
**Pull request by ReLater**
### Summary of Changes
- See code changes. Obvious.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on f916d4ac43f2ecfa73b10119a8a717de44c11d70<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31553">issues.joomla.org/tracker/joomla-cms/31553</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on f916d4ac43f2ecfa73b10119a8a717de44c11d70<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31553">issues.joomla.org/tracker/joomla-cms/31553</a>.</sub>

**Comment by chmst** [comment]
RTC

**Comment by brianteeman** [comment]
The bot has removed the RTC label ;(

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
