### PR TITLE
Add Tests Scenarios in .txt format

### PR DESCRIPTION
**Pull request by javigomez**
This .txt are created with the Codeception Generate Scenarios feature:

```
php vendor/bin/codecept generate:scenarios acceptance
```

And have been cleaned manually to document the current tests.

### CODE REVIEW

**Comment by brianteeman** [comment]
Does it matter for this of the english is not great?

**Comment by wilsonge** [comment]
"I do administrator login('admin', 'admin')" part is deliberate. As I understand everything starts with "I do", "I click", "I wait" etc. to make the tests 'human friendly'.

The stuff we have control over is the test name in caps at the top of the files

**Comment by rdeutz** [comment]
George is right, it is some kind on programming language or better a language to describe a behaviour.

**Comment by brianteeman** [comment]
Thanks I was just checking

**Comment by javigomez** [comment]
Hi, they are the English descriptive files taken from the PHP tests: https://github.com/joomla/joomla-cms/blob/staging/tests/codeception/tests/acceptance/installation/InstallJoomlaCept.php and https://github.com/joomla/joomla-cms/blob/staging/tests/codeception/tests/acceptance/administrator/setDevelopmentErrorReportingCept.php

Is just a tool for help reading the tests. And is autogenerated, but the generator is not yet perfect, so we can hack them and make fix the english issues.

This is just a starting point. There is also the option of generating HTML reports. Maybe we could add also some snapshots later on too... 

What are the english errors that you saw @brianteeman?

**Comment by brianteeman** [comment]
The english is "good enough" for its purpose.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6735">issues.joomla.org/joomla-cms/6735</a>.</sub>

**Pull request merged**
