### PR TITLE
[4.0] Add target _blank to display icon link as external

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
Add icon to indicate link is external.

### Testing Instructions
Go to Post Installation Messages
See links with external icon.

### CODE REVIEW

**Comment by brianteeman** [comment]
if you're going to change it then you also need to add the noreferrer stuff

**Review by hans2103 — APPROVED** [review]

**Comment by hans2103** [comment]
I have tested this item :white_check_mark: successfully on f0adaa8ee13adad291842670b5ec4258adda3076<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34760">issues.joomla.org/tracker/joomla-cms/34760</a>.</sub>

**Comment by sandewt** [comment]
I have tested this item :white_check_mark: successfully on f0adaa8ee13adad291842670b5ec4258adda3076<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34760">issues.joomla.org/tracker/joomla-cms/34760</a>.</sub>

**Comment by sandewt** [comment]
Oops, missing here: **noopener noreferrer**

`<a href="https://en.wikipedia.org/wiki/Google_Authenticator" target="_blank">Google Authenticator</a>`

**Comment by hans2103** [comment]
> 
> 
> Oops, missing here: **noopener noreferrer**
> 
> `<a href="https://en.wikipedia.org/wiki/Google_Authenticator" target="_blank">Google Authenticator</a>`

out of scope for this PR. 
Language string for this post-install message comes from plg_system_httpheaders.ini
https://github.com/joomla/joomla-cms/blob/4730efc2433d0440d7b2259570dd8fc9b72bff57/administrator/language/en-GB/plg_system_httpheaders.ini#L56
And already contains `noopener noreferrer`

**Comment by sandewt** [comment]
>out of scope for this PR.

I agree.

I see that this problem also occurs with the external links under the help function.

**Comment by sandewt** [comment]
> And already contains noopener noreferrer

I agree, apparently something went wrong for me when I upgraded to J 4.0.0-rc3 !?

**Comment by richard67** [comment]
> I agree, apparently something went wrong for me when I upgraded to J 4.0.0-rc3 !?

@sandewt So is your successful test still valid or not?

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on f0adaa8ee13adad291842670b5ec4258adda3076<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34760">issues.joomla.org/tracker/joomla-cms/34760</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34760">issues.joomla.org/tracker/joomla-cms/34760</a>.</sub>

**Comment by sandewt** [comment]
@hans2103 / @richard67

It concerns the `plg_twofactorauth_totp.ini` and NOT the `plg_system_httpheaders.ini`

See: missing **noopener noreferrer**
https://github.com/joomla/joomla-cms/blob/4730efc2433d0440d7b2259570dd8fc9b72bff57/administrator/language/en-GB/plg_twofactorauth_totp.ini#L11

>out of scope for this PR.

So I think, this is not out of the scope

>@sandewt So is your successful test still valid or not?

 NO

**Comment by richard67** [comment]
> See: missing **noopener noreferrer**
> 
> https://github.com/joomla/joomla-cms/blob/4730efc2433d0440d7b2259570dd8fc9b72bff57/administrator/language/en-GB/plg_twofactorauth_totp.ini#L11
> 
> > out of scope for this PR.
> 
> So I think, this is not out of the scope
> 
> > @sandewt So is your successful test still valid or not?
> 
> NO

@Quy Should we fix this in staging or here?

**Comment by hans2103** [comment]
Created a PR in this PR
Because discussing about it takes more time than fixing it. 
https://github.com/Quy/joomla-cms/pull/3

**Comment by sandewt** [comment]
>Because discussing about it takes more time than fixing it.

:smiley:

**Comment by richard67** [comment]
Well I had noticed that but I thought the reason why it has not been made in this PR was because it should be fixed in staging.

**Comment by brianteeman** [comment]
With the language string freeze tomorrow it will need to happen here

**Comment by Quy** [comment]
#24337 discusses this issue globally for J4.

@HLeithner will have to decide if for J3.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 96cb627464c0f415b42c8fd4187451c45122062e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34760">issues.joomla.org/tracker/joomla-cms/34760</a>.</sub>

**Comment by richard67** [comment]
@hans2103 Could you test again? Thanks in advance.

**Comment by hans2103** [comment]
I have tested this item :white_check_mark: successfully on 96cb627464c0f415b42c8fd4187451c45122062e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34760">issues.joomla.org/tracker/joomla-cms/34760</a>.</sub>

**Comment by richard67** [comment]
2 good tests, so RTC is valid again.

**Comment by zero-24** [comment]
Merging

**Comment by HLeithner** [comment]
> #24337 discusses this issue globally for J4.
> 
> @HLeithner will have to decide if for J3.

+1

**Comment by sandewt** [comment]
See: missing **noopener noreferrer** (occurs twice)

`<a href=\"https://freeotp.github.io/\" target=\"_blank\">FreeOTP</a>`

https://github.com/Quy/joomla-cms/blob/96cb627464c0f415b42c8fd4187451c45122062e/administrator/language/en-GB/plg_twofactorauth_totp.ini#L24

@Quy 

[EDIT]

**Comment by Quy** [comment]
@sandewt This PR fixed only external links in the Post Installation Messages page. There are other instances like the ones you mentioned to be fixed in a separate PR to address #24337.

**Comment by sandewt** [comment]
@Quy , thanks for your explanation.

**Pull request merged**
