### PR TITLE
Adds jlayout searchtools to com_users view levels

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Description

This PR adds, for consistency, as it exists in so many other views in the backoffice, the search tools to com_users view levels.
###### Before PR

image
###### After PR

image
#### How to test
1. Install latest staging and apply this patch
2. Go to Users -> Viewing Access Levels
3. Check the ordering select box and search is working fine.

### CODE REVIEW

**Comment by ghazal** [comment]
I have tested this item :white_check_mark: successfully on 4505519bc2feddc5e4e271cf192290f296165f8b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9092">issues.joomla.org/joomla-cms/9092</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 4505519bc2feddc5e4e271cf192290f296165f8b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9092">issues.joomla.org/joomla-cms/9092</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 4505519bc2feddc5e4e271cf192290f296165f8b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9092">issues.joomla.org/joomla-cms/9092</a>.</sub>

**Comment by brianteeman** [comment]
RTC - thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9092">issues.joomla.org/joomla-cms/9092</a>.</sub>

**Pull request merged**
