### PR TITLE
Use the renamed field in the TagsHelper

### PR DESCRIPTION
**Pull request by zero-24**
Pull Request for Issue #17363

### Summary of Changes

In the query we rename the `name` to author. But later we use the old name which result in some cases to an SQL error.

Thanks  @LivioCavallo

### Testing Instructions

basicly review.

### Expected result

use the renamed field name

### Actual result

use the original field name

### Documentation Changes Required

none

### CODE REVIEW

**Review by wilsonge — APPROVED** [review]

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 8797e5cda93f9825fda862db929f192f33b792f9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17364">issues.joomla.org/tracker/joomla-cms/17364</a>.</sub>

**Comment by LivioCavallo** [comment]
I see that there is a check pending, commit cannot be built, there seems to be a conflict?
What can I do to solve this?

**Comment by zero-24** [comment]
@LivioCavallo Sorry i had vacation until now. I have just fixed the merge conflict (as the files got moved again)

The only thing you can do to move this thing forward is to mark a successfull test unsing the issue tracker: https://issues.joomla.org/tracker/joomla-cms/17364 there you find after login via github this blue button:
image

There you can mark your test as successfull so a maintainer can merge this into 3.8.0

**Comment by LivioCavallo** [comment]
I have tested this item :white_check_mark: successfully on 8797e5c

**Comment by zero-24** [comment]
RTC. Thanks @LivioCavallo and @alikon<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17364">issues.joomla.org/tracker/joomla-cms/17364</a>.</sub>

**Pull request merged**
