### PR TITLE
com_installer "Install languages" UX Improvements

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Description

This PR does some UX improvements to com_installer -> Install Languages:
- Use Jlayout Search Tools
- Adds colors to translation versions (lower - orange : Same - green)
- Moves warning message to the version tooltip.
- Adds a new column language code (with ordering)
###### Before PR

image
###### After PR

image
#### How to test
1. Install PR with latest staging
2. Go to Extensions -> Manage -> Install languages
   (check before and after PR)
3. Check if every filter if working fine
#### Observations

All version coluns are orange because you are in version 3.5.0 and there is no translation yet for 3.5.0.

Suggestions and improvements are welcome.

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
@infograf768 check this one too please.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on d58155557bc2d8fbe98376d45427e7d270342304<br /><br />Tested with success, works as described (green version number could not be tested, as explained in description).

@andrepereiradasilva There is missing the flag for one language: "Sinhala Sinhala" (si-LK). Should be the flag of Sri Lanka I guess.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9089">issues.joomla.org/joomla-cms/9089</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :red_circle: unsuccessfully on d4e73aaa29be5ce41a1d42bbe725ccdf09e4cca2<br /><br />Sorry, have to alter my test result.

When I enter as search text in the search box anything which cannot be found in the list, e.g. "gaga" or the name of an installed language, e.g. "German", then the search tools and sort tools disappear, and the only thing shown at the top of the empty list is the message "There are no available languages to install at the moment ....", as if no languages could be found at all. Pressing "Find languages" button or navigating to another page and then back does not help. I have to log out of the backend and log in again to see the list of available languages again.

Before this patch it worked with current staging.

What works well is searching for something which can be found in the list, e.g. "English" will find Australian, Canadian and US English.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9089">issues.joomla.org/joomla-cms/9089</a>.</sub>

**Comment by Bakual** [comment]
Do we even need the "Type" column? I think all are of type "Package" anyway, or not?

**Comment by richard67** [comment]
P.S.: Screenshots to my recent unsuccessful test result:

Entering something which cannot be found in the list, e.g. name of installed language (if no other variant with search sting in its name), enter or search button not pressed/clicked yet:

screen shot 2016-02-09 at 11 50 13

After enter or click on search button:

screen shot 2016-02-09 at 11 51 38

Is is then necessary to logout and then login again to see the available languages list again.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9089">issues.joomla.org/joomla-cms/9089</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@richard67 you are right. check now.

@Bakual i don't think is needed. But can you confirm is not needed?

**Comment by andrepereiradasilva** [comment]
> @andrepereiradasilva There is missing the flag for one language: "Sinhala Sinhala" (si-LK). Should be the flag of Sri Lanka I guess.

@richard67 That is because the language image file is "si_LK.gif" (see https://github.com/joomla/joomla-cms/blob/staging/media/mod_languages/images/si_LK.gif), not "si_lk.gif" as it should.
Since i use windows (which does not make distinction between uppercase and lowercasse) in github i cannot correct this. Maybe someone can make a PR to change that flag filename.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 64d38358051c38da938e44c5fe4ccbb1409dda9e<br /><br />Tested again after latest commit. Now it works. When a search text is entered which results in nothing found, the search tools not disappear now, and there is shown that there are no matches. See screenshots following with my next comment.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9089">issues.joomla.org/joomla-cms/9089</a>.</sub>

**Comment by richard67** [comment]
P.S. to my last successful test result:

1st screenshot shows the page when no matches found for text search:

screen shot 2016-02-09 at 12 10 49

2nd screenshot shows the page if no languages found at all (because of invalid update sites URL):

screen shot 2016-02-09 at 12 11 44

Question @andrepereiradasilva : The text COM_INSTALLER_MSG_LANGUAGES_NOLANGUAGES will be obsolete after this PR as it is now, it is not used anymore in any file except the language ini file itself. Is this desired? If so, should it be marked as obsolete somehow in the language file?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9089">issues.joomla.org/joomla-cms/9089</a>.</sub>

**Comment by brianteeman** [comment]
The policy for unused language strings is to just leave them as they are.

**Comment by richard67** [comment]
@andrepereiradasilva For renaming the image file from si_LK.gif to si_lk.gif I just have created a PR against your branch for this PR in your repository. Can you check if this is OK?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9089">issues.joomla.org/joomla-cms/9089</a>.</sub>

**Comment by brianteeman** [comment]
I "think" I brought up the question about "type" before and the answer was it is possible for a language to be available as only site or admin

**Comment by richard67** [comment]
P.S. @andrepereiradasilva See [https://github.com/andrepereiradasilva/joomla-cms/pull/10](https://github.com/andrepereiradasilva/joomla-cms/pull/10 "https://github.com/andrepereiradasilva/joomla-cms/pull/10")<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9089">issues.joomla.org/joomla-cms/9089</a>.</sub>

**Comment by andrepereiradasilva** [comment]
merged thanks!

**Comment by andrepereiradasilva** [comment]
@brianteeman the "type" is if it is a "package" or other type of extension, i.e., is the extension type in the extensions table.

AFAIK all language packs are of the "package" type, but i'm not 100% sure of that.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on ba48c6ef243f67e0d59026a2ad6dbdd7df7607b5<br /><br />Still all works as desired, and now the flag for  "Sinhala Sinhala" (si-LK) is found, too :smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9089">issues.joomla.org/joomla-cms/9089</a>.</sub>

**Comment by richard67** [comment]
In my opinion we should keep the type column. In case if some language's details XML one day contains a different wrong type we could see this, right?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9089">issues.joomla.org/joomla-cms/9089</a>.</sub>

**Comment by Bakual** [comment]
> I "think" I brought up the question about "type" before and the answer was it is possible for a language to be available as only site or admin

Afaik, even if it only contains site or admin, it still needs to be delivered as a package. Otherwise you couldn't uninstall it anymore due to the funny check we have in the uninstaller.

**Comment by infograf768** [comment]
Works, but 2 comments

The same flag is used for Notwegian Bokmal and Norwegian Nynorsk
Also the same flag is used for Uyghur and Simplified chinese

This would be an issue in a multilingual site using both languages and flags in the switcher.

We should find/make up different flags to represent these languages, without introducing political issues.

**Comment by andrepereiradasilva** [comment]
And that why i always ask you to check the language PR  :)

Can i ask you to check that those two flags? Can the translators of that languages help with that?

**Comment by infograf768** [comment]
Will ask them.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 1a86bc7be4f52ce70eb3a6abd52edceda68b7124<br /><br />Still all works as desired, and with default values in code being equal to defaults in the XML, the sorting stays the same when paging or changing items per page.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9089">issues.joomla.org/joomla-cms/9089</a>.</sub>

**Comment by syntaxerror** [comment]
Flags isn't related to languages normally, but to countries. For Norwegian it makes no sense to "make up some new flag", and I have to this date not seen anyone doing so.

If anyone uses both Nynorsk and Bokmål they should use text instead, or relay on the hover. Chances for anyone using both is anyhow really small.

**Comment by richard67** [comment]
I can confirm what @syntaxerror said (have some friend in Norway and also a good memory and never have seen any special flags for Nynorsk and Bokmål anywhere).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9089">issues.joomla.org/joomla-cms/9089</a>.</sub>

**Comment by brianteeman** [comment]
Its also a political nightmare showing the flags here - thats why we let the user define the flag themselves in the content language.

Arabic for example - you are showing a specific country flag but the language is generic.

My -1 on this change<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9089">issues.joomla.org/joomla-cms/9089</a>.</sub>

**Comment by richard67** [comment]
Well with Uyghur it indeed a political issue:

China will never allow Uyghurs to have their own flag, and many Uyghurs do not want to use the Chinese flag.

So whichever we use for this language, Chinese flag or the (inofficial and as far as I know in China even forbidden) flag of the East Turkestan Independence movement ([see wikipedia](https://en.wikipedia.org/wiki/East_Turkestan_independence_movement "https://en.wikipedia.org/wiki/East_Turkestan_independence_movement")), it will be a political statement.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9089">issues.joomla.org/joomla-cms/9089</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@brianteeman i understand what you mean, because flags are for countries not languages.

Knowing that i added the flags because if there are no flags you have, for instance: English, English, English for the 3 types of english.

I will remove the flags from this PR, but the language names in the XML language files should be updated so the language name is more clear.

**Comment by infograf768** [comment]
@brianteeman
>Arabic for example - you are showing a specific country flag but the language is generic.

Wrong. The flag is the Arab League one, not any country.

Now, we can do for flags nn-no and ug-cn what we did for Tamil or Sinhala (as these are used in different countries), i.e create an image with the native name of the language in respectively Tamil and Sinhala on a white background.

**Comment by andrepereiradasilva** [comment]
reggarding the flags, from a code point of view is just change this line https://github.com/andrepereiradasilva/joomla-cms/blob/installer-languages-imrpovements/administrator/components/com_installer/views/languages/tmpl/default.php#L85

So, since this is also a Joomla! policy question, i let you guys decide if you want flags here or not.

**Comment by infograf768** [comment]
We anyway need the missing flags as well as the correction for the sinhala one.

**Comment by richard67** [comment]
From my point of view, infograf768's suggestion solves the political problem with Uyghur language, +1 for this.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9089">issues.joomla.org/joomla-cms/9089</a>.</sub>

**Comment by richard67** [comment]
@infograf768 For variants of the language name in native language and diverse scripts (cyrillic, arab and latin) see [http://www.uyghurensemble.co.uk/en-html/uy-language.html](http://www.uyghurensemble.co.uk/en-html/uy-language.html "http://www.uyghurensemble.co.uk/en-html/uy-language.html")

It seems all 3 scripts can be used, so not easy to decide which one to use for the new flag image.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9089">issues.joomla.org/joomla-cms/9089</a>.</sub>

**Comment by brianteeman** [comment]
its still a political statement to decide on a flag and its not needed here
- where it is needed the site owner gets to decide

Lets not open a can of worms

On 10 February 2016 at 12:19, Richard Fath <notifications@github.com> wrote:

> @infograf768 <https://github.com/infograf768> For variants of the
> language name in native language and diverse scripts (cyrillic, arab and
> latin) see http://www.uyghurensemble.co.uk/en-html/uy-language.html
>
> It seems all 3 scripts can be used, so not easy to decide which one to use
> for the new flag image.
> ------------------------------
> This comment was created with the J!Tracker Application
> <https://github.com/joomla/jissues> at issues.joomla.org/joomla-cms/9089
> <https://issues.joomla.org/tracker/joomla-cms/9089>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/9089#issuecomment-182342843>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by syntaxerror** [comment]
Norwegian Bokmål nor Norwegian Nynorsk is used in different countries JM, they are only used in Norway and share the same flag - period.

-1 to flag changes

**Comment by infograf768** [comment]
Unrelated to this PR, we do need flags/images for each language in our UI in 3.5.0

It can be done in another urgent PR:
Ok for Norway flag for Nynorsk. No P for me.
Here is one for Uygur ug-CN (rename ug_zn.gif)
ug_cn
and changing the Sinhala flag name.

**Comment by infograf768** [comment]
@richard67 
The gif I made is using the Arabic/Persian script as it is the one used by the Uyghur package.

**Comment by infograf768** [comment]
@syntaxerror 
Rune, we still need a specific flag for Nynorsk, even if this is the same as Bookmal.
This is necessary when first Joomla install with multilanguage.

@andrepereiradasilva 
Please take off the flags files adds/changes from this PR. I am now creating a specific PR only for the flags. https://github.com/joomla/joomla-cms/pull/9097

**Comment by andrepereiradasilva** [comment]
ok will do later. This PR will have no flags at all.

**Comment by infograf768** [comment]
I like it with flags...

**Comment by richard67** [comment]
Me too...

**Comment by andrepereiradasilva** [comment]
Ok all language related images were removed.

Current preview:
image

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 6fc60cf4ad2f927fcdd0bea81792e0696c3dd5de<br /><br />Tested with success, still works.

@andrepereiradasilva I liked it with the flags being displayed in the list, like it was before the last changes. I think @infograf768 only meant to remove the adding and renaming of flag image files from this PR, not the display of the flags in the list.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9089">issues.joomla.org/joomla-cms/9089</a>.</sub>

**Comment by brianteeman** [comment]
Can you try it with the Language code column left aligned please - I think
it will be easier to scan

On 10 February 2016 at 21:28, andrepereiradasilva <notifications@github.com>
wrote:

> Ok all language related images were removed.
>
> Current preview:
> [image: image]
> <https://cloud.githubusercontent.com/assets/9630530/12962426/2b24631c-d03d-11e5-9b96-fcc9832e9368.png>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/9089#issuecomment-182589106>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by MATsxm** [comment]
I have tested this item :white_check_mark: successfully on 6fc60cf4ad2f927fcdd0bea81792e0696c3dd5de<br /><br />Works as describe

+1 for the Language code column left aligned from Brian
+1 without the flags

Thanks

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9089">issues.joomla.org/joomla-cms/9089</a>.</sub>

**Comment by andrepereiradasilva** [comment]
left align now

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 42ad3988eaf910e396d54aa961ed94b3fb0f0d50<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9089">issues.joomla.org/joomla-cms/9089</a>.</sub>

**Comment by MATsxm** [comment]
I have tested this item :white_check_mark: successfully on 42ad3988eaf910e396d54aa961ed94b3fb0f0d50<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9089">issues.joomla.org/joomla-cms/9089</a>.</sub>

**Comment by infograf768** [comment]
We do not need the Type column as all language packs have to be of type Package.
Also, I would solve the width of the Language Code column as it always shows in 2 lines.
This means using the nowrap class and normalize the hidden-phone one as there are issues when reducing the window width.

I.e.
```
[...]
						<th class="nowrap">
							<?php echo JHtml::_('searchtools.sort', 'JGRID_HEADING_LANGUAGE', 'name', $listDirn, $listOrder); ?>
						</th>
						<th width="5%" class="nowrap hidden-phone">
							<?php echo JHtml::_('searchtools.sort', 'COM_INSTALLER_HEADING_LANGUAGECODE', 'element', $listDirn, $listOrder); ?>
						</th>
						<th width="5%" class="center">
							<?php echo JText::_('JVERSION'); ?>
						</th>
[...]
						<td>
							<label for="cb<?php echo $i; ?>">
								<?php echo $language->name; ?>
							</label>
						</td>
						<td class="small hidden-phone">
							<?php echo $language->code; ?>
						</td>
						<td class="center small">
								<?php // Display a Note if language pack version is not equal to Joomla version ?>
```


This would give:

screen shot 2016-02-11 at 08 41 27

**Comment by brianteeman** [comment]
Great that we can remove the type column.

Personally I prefer the result of the two line "language code" but I am not
a designer

**Comment by infograf768** [comment]
@brianteeman
The issue is that if we do not use the "nowrap" we could also get the arrow alone on its own line for some languages...

**Comment by brianteeman** [comment]
:(

On 11 February 2016 at 08:11, infograf768 <notifications@github.com> wrote:

> @brianteeman <https://github.com/brianteeman>
> The issue is that if we do not use the "nowrap" we could also get the
> arrow alone on its own line for some languages...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/9089#issuecomment-182758229>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by infograf768** [comment]
I have tested this item :red_circle: unsuccessfully on 42ad3988eaf910e396d54aa961ed94b3fb0f0d50<br /><br />It should be "Language Tag" and not "Language Code".
+ "hidden-phone" should be present OR absent from both the heading and the row.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9089">issues.joomla.org/joomla-cms/9089</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@infograf768 thanks for the comments and changes. Will correct the issues later

**Comment by andrepereiradasilva** [comment]
Done, @infograf768, @MATsxm, @richard67 chan you test the changes

**Comment by richard67** [comment]
@andrepereiradasilva Hmm, the column header still shows "Language Code" and not "Language Tag" as requested by @infograf768.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9089">issues.joomla.org/joomla-cms/9089</a>.</sub>

**Comment by andrepereiradasilva** [comment]
ups you're right

**Comment by richard67** [comment]
In the drowdown for the sort options it has to be changed, too.

**Comment by andrepereiradasilva** [comment]
Language Tag now. Done.

image

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on e984017446b86781ddde51a5b7a4a52cfa540963<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9089">issues.joomla.org/joomla-cms/9089</a>.</sub>

**Comment by MATsxm** [comment]
I have tested this item :white_check_mark: successfully on e984017446b86781ddde51a5b7a4a52cfa540963<br /><br />I really like this way :+1: - Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9089">issues.joomla.org/joomla-cms/9089</a>.</sub>

**Comment by infograf768** [comment]
RTC. Thanks.



Note @andrepereiradasilva 

You may want to also change some aspects of the languages install when installing Joomla, i.e the colour of the Tag (orange/green and the use of the tip on the button instead of below the language name. Another PR imho. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9089">issues.joomla.org/joomla-cms/9089</a>.</sub>

**Comment by infograf768** [comment]
Ooops, @andrepereiradasilva you forgot to delete
en-GB.com_installer.ini:43: COM_INSTALLER_HEADING_LANGUAGECODE="Language Code"
en-GB.com_installer.ini:44: COM_INSTALLER_HEADING_LANGUAGECODE_ASC="Language Code ascending"
en-GB.com_installer.ini:45: COM_INSTALLER_HEADING_LANGUAGECODE_DESC="Language Code descending"

**Comment by andrepereiradasilva** [comment]
> You may want to also change some aspects of the languages install when installing Joomla, i.e the colour of the Tag (orange/green) and the use of the tip on the button instead of below the language name. Another PR imho.

I have many Pr to do. So i leave that installer changes to other person ...

> Ooops, @andrepereiradasilva you forgot to delete ...

oh, ok. i will remove them later.

**Comment by infograf768** [comment]
Taking of RTC for now<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9089">issues.joomla.org/joomla-cms/9089</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on b02b0a0f25ef2998dfc65609b289344bb71ea03a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9089">issues.joomla.org/joomla-cms/9089</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on b02b0a0f25ef2998dfc65609b289344bb71ea03a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9089">issues.joomla.org/joomla-cms/9089</a>.</sub>

**Comment by infograf768** [comment]
RC. Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9089">issues.joomla.org/joomla-cms/9089</a>.</sub>

**Comment by rdeutz** [comment]
@andrepereiradasilva could you please have a look at the merge conflicts, thanks

**Comment by andrepereiradasilva** [comment]
ignore the unit tests label, somehow my git changed the filename of the xcache unit test, i reverted. all good now and no conflicts.

**Comment by richard67** [comment]
I will be able to test again tomorrow if still necessary.

**Comment by brianteeman** [comment]
I have removed that label

**Comment by andrepereiradasilva** [comment]
can anyone restart travis here?

**Pull request merged**
