### PR TITLE
[4.0] Make Install from Web looking better

### PR DESCRIPTION
**Pull request by rdeutz**
Pull Request for Issue #19429 last bits and #30018 but changed my mind about the buttons.

### Summary of Changes

* Tries to make install from web look like the other Joomla4 backend stuff
* Some javascript magic for the clean button
* Added a legend like the other tabs

### Testing Instructions

* apply patch
* npm build:css
* npm build:js
* look if search works as expected

### Actual result BEFORE applying this Pull Request

grafik

### Expected result AFTER applying this Pull Request
grafik

grafik

grafik

**Note: Seems the language pack doesn't contain a translation for the install from web tab.**

### Documentation Changes Required

don't think so

### CODE REVIEW

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on a82dbe8fb2072e2afa39e6a321cde6c8cf3e35ef<br /><br />Thank you for the work on cleaning this up. Works as expected and looks much better.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32851">issues.joomla.org/tracker/joomla-cms/32851</a>.</sub>

**Comment by infograf768** [comment]
> Note: Seems the language pack doesn't contain a translation for the install from web tab.

This string is new in j4, therefore not avalable in j3 packs
`PLG_INSTALLER_WEBINSTALLER_TAB_LABEL="Install from Web"`

In J3 it was
`COM_INSTALLER_INSTALL_FROM_WEB="Install from Web"`

**Comment by brianteeman** [comment]
Everything looks great.

Is it expected that it is not possible to select an extension to install when using the keyboard?

**Comment by rdeutz** [comment]
> Is it expected that it is not possible to select an extension to install when using the keyboard?

short answer: yes

To add this we need to change the install-from-web server, because we only show the HTML. This is more or less a mistake in the design of the functionality. I looked into this but this is a huge task. 

My changes here are more cosmetic and make sure it looks like the other parts of Joomla4.

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on a82dbe8fb2072e2afa39e6a321cde6c8cf3e35ef<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32851">issues.joomla.org/tracker/joomla-cms/32851</a>.</sub>

**Comment by drmenzelit** [comment]
Thanks

**Pull request merged**
