### PR TITLE
[4.0] Correct the doc blocks of rules layout

### PR DESCRIPTION
**Pull request by anuragteapot**
### Summary of Changes
Used variables explained in the doc block of the JLayout
And remove unwanted variables.

### Testing Instructions
Code review

### Expected result
Same as before

### Actual result
Same as before

### CODE REVIEW

**Comment by anuragteapot** [comment]
@dgt41 Please review

**Comment by dgrammatiko** [comment]
Looking good

**Comment by anuragteapot** [comment]
@wilsonge take a look here which was left in #19507

**Comment by wilsonge** [comment]
Looks good. One day I'll do a proper code review of the first PR 😑 😆

**Comment by anuragteapot** [comment]
@wilsonge sure, it was necessary because this was my first time when I have written whole file code 😊😊
If some mistake sorry for that
Thanks

**Pull request merged**
