### PR TITLE
[5][com_joomlaupdate] Deprecated: Creation of dynamic property php 8.2

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue # .

### Summary of Changes

declare variables

### Testing Instructions

set error report to maximum
go to Joomla Updatde
and / or `php cli/joomla.php update:extensions:check`

### Actual result BEFORE applying this Pull Request

image

image

### Expected result AFTER applying this Pull Request

no more deprecations

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by HLeithner** [comment]
doesn't this problem also exists in 4.3 and 4.4?

**Comment by alikon** [comment]
i didn't check, discovered when #41117

**Comment by HLeithner** [comment]
can you please check and rebase for at least 4.4

**Comment by alikon** [comment]
wrong rebase, i'll switch it back to 5

**Comment by heelc29** [comment]
> doesn't this problem also exists in 4.3 and 4.4?

I think it's only 5.x ...

https://github.com/joomla/joomla-cms/pull/40999

**Comment by HLeithner** [comment]
@alikon can I merge this or do you have further plans?

**Comment by alikon** [comment]
yes please, as long as i'll discover some more i'll do another pr

**Comment by HLeithner** [comment]
thanks, I tested it and worked for me.

**Pull request merged**
