### PR TITLE
[4.2] Module >> Menu Assignment >> chevrons not working correctly fix

### PR DESCRIPTION
**Pull request by vorayash**
Pull Request for Issue #37593

### Summary of Changes
1. To select chevrons, 'i' was used instead of 'span' because of that it was not selecting anything.

### Testing Instructions
Go to Modules >> any module >> Menu Assignment tab >> Only on the pages selected
Click on one or two menus to expand them
The chevrons on the left change from .icon-chevron-right to .icon-chevron-down correctly
Now click on >> Expand the Menu Subtrees >> None

### Actual result BEFORE applying this Pull Request
The chevrons do not change so some are incorrect

### Expected result AFTER applying this Pull Request
The chevrons change correctly.
1go1wg5NDk

### CODE REVIEW

**Comment by brianteeman** [comment]
This is a bugfix so andnot a new feature so really should be rebased on 4.1

**Comment by vorayash** [comment]
So I am supposed to make pull request on 4.1, right?

**Comment by brianteeman** [comment]
you should be able to just rebase it without creating a new pr.

rebase

**Comment by vorayash** [comment]
Closed due to conflicts.

**Pull request closed without merging**
