### PR TITLE
update to phpass 0.5

### PR DESCRIPTION
**Pull request by photodude**
Pull Request for Issue new version of phpass .

### Summary of Changes
Update to current version of phpass found at http://cvsweb.openwall.com/cgi/cvsweb.cgi/projects/phpass/PasswordHash.php?r1=1.9#rev1.9

additional release note information in the official announcment
http://www.openwall.com/lists/announce/2017/05/07/1
- Dropped PHP 3 & 4 support in favor of PHP 7 friendliness (no deprecation warnings).  Specifically:
  - Added the new-php5-style constructor.
- Just assume md5() supports a second argument, which it does since PHP 5.
- Use the === and !== comparison operators.
- While at it, dropped the fallback to CRYPT_EXT_DES (if there's no working CRYPT_BLOWFISH, fallback to the portable hashes right away).

### Testing Instructions
unit tests pass / code review

### Documentation Changes Required
none

### Note
Remember within Joomla, this is only used to verify then migrate old passwords to the new hashing methods.

/CC @mbabker @wilsonge @rdeutz

### CODE REVIEW

**Comment by photodude** [comment]
Please ignore the php5.6 failure on AppVeyor. One of the required downloads to run SQLSRV seems to be having DNS issues.

**Comment by laoneo** [comment]
I like the "Dropped PHP 3 & 4 support" changelog :smile:

**Comment by photodude** [comment]
This is now an official phpass release 
http://www.openwall.com/lists/announce/2017/05/07/1

**Comment by photodude** [comment]
@mbabker will you restart the appveyor tests.

**Comment by photodude** [comment]
@demis-palma @zero-24 please consider reviewing this PR so we can get the PHPASS lib updated.

**Comment by PhilETaylor** [comment]
I have tested this item :white_check_mark: successfully on f59f9c6474b167ca281620242f8d09cb3029f175<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15704">issues.joomla.org/tracker/joomla-cms/15704</a>.</sub>

**Comment by mbabker** [comment]
> @mbabker will you restart the appveyor tests.

So either I'm signing into the wrong account or there's a limit on how after a build you can re-run it, I can't retrigger this one.

**Comment by rdeutz** [comment]
restartet /cc @mbabker

**Comment by photodude** [comment]
@mbabker I think when you restart an appveyor build the build is put back into the bottom of the queued stack as the builds do not run in parallel like they do on travis. This PR currently shows that it has a queued status, so it's "restarted" just pending when it gets to the top of the stack.

**Comment by photodude** [comment]
@mbabker thanks for restarting. All green as expected. 
@rdeutz do we just want to merge on review here?

**Comment by photodude** [comment]
@rdeutz is there a reason to wait for 3.7.3 rather than merging for 3.7.2? This is just a library update.

**Comment by rdeutz** [comment]
@photodude yes, 3.7.2 will only include fixes for regressions or bugs we introduce with 3.7.[0|1]. We still need to stabilize 3.7 so I am not taking any risk on merging other PR

**Comment by photodude** [comment]
understood, thanks for the explanation.

**Comment by photodude** [comment]
Thanks for merging @rdeutz 
One more PHP 7 improvement done. No more depreciation notices related to PasswordHash.

**Pull request merged**
