### PR TITLE
[Isis] Flush tables in cpanel wells

### PR DESCRIPTION
**Pull request by ciar4n**
Pull Request for Issue #13879 .

### Summary of Changes
Makes 'tables' flush with well edges in cpanel. Also some responsive improvements on the same tables.

### Testing Instructions
Open cpanel and check modules containing wells (Popular Articles etc.)

### Before Patch
cpanel-well1

### After Patch
cpanel-well2

### Documentation Changes Required
None

### CODE REVIEW

**Comment by tonypartridge** [comment]
I have tested this item :white_check_mark: successfully on 3403d005d8f64aa07c7879df334a6397e11a9d73<br /><br />Working perfectly. Great work @ciar4n <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13890">issues.joomla.org/tracker/joomla-cms/13890</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 3403d005d8f64aa07c7879df334a6397e11a9d73<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13890">issues.joomla.org/tracker/joomla-cms/13890</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13890">issues.joomla.org/tracker/joomla-cms/13890</a>.</sub>

**Comment by tonypartridge** [comment]
Thanks again @ciar4n :D

**Comment by wilsonge** [comment]
Nice work!

**Pull request merged**
