### PR TITLE
Fixes php warning when asset id (ancestor) is not found for whatever …

### PR DESCRIPTION
**Pull request by regularlabs**
.

### CODE REVIEW

**Comment by sovainfo** [comment]
Suggest code below instead:
```
if (isset(self::$assetPermissionsById[$extensionName][$id]))
{
	$collected[] = self::$assetPermissionsById[$extensionName][$id]->rules
}
```
Consider this a nobrainer, it fixes a rookie mistake referencing data that is unknown to exist.
Should be accepted based on code review!

**Comment by regularlabs** [comment]
I prefer to use ifs for negative exceptions only (as much as possible).

So the returns/continues are inside ifs. And the code you want the thing (function/method/loop) to do is outside (under) the ifs/exceptions.

**Comment by sovainfo** [comment]
Noticed that, don't mind it that much, but do consider my code better to read.
The important thing is that this is accepted based on code review.

**Comment by brianteeman** [comment]
> Please add more information to your issue. Without test instructions and/or any description we will close this issue within 4 weeks. Thanks.

No reply so closed

**Pull request closed without merging**
