### PR TITLE
[Calendar] B/C Setting weeknumbers to display per default

### PR DESCRIPTION
**Pull request by infograf768**
Pull Request replacing https://github.com/joomla/joomla-cms/pull/16104

### Summary of Changes
As title says.

### Testing Instructions

Patch and make sure all calendar fields display weeknumbers.

### Expected result

screen shot 2017-05-18 at 11 48 37

### CODE REVIEW

**Comment by infograf768** [comment]
Setting to 3.7.2 as it is a B/C issue.

**Comment by ot2sen** [comment]
I have tested this item :white_check_mark: successfully on 35d352bec22e5c27b8a39dae26cf214172ca4227<br /><br />Works. Weeknumbers now shown in modules and also in the 3 article settings for start/finish/created.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16117">issues.joomla.org/tracker/joomla-cms/16117</a>.</sub>

**Review by rdeutz — APPROVED** [review]
looks good

**Comment by infograf768** [comment]
Note: as explained in #16104 
It would now be a voluntary act to NOT display it for a 3rd party by adding `weeknumbers="false"` in their xmls or any user in the layout (/layouts/joomla/form/field/calendar.php)

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 35d352bec22e5c27b8a39dae26cf214172ca4227<br /><br />Tests on Articles and Modules.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16117">issues.joomla.org/tracker/joomla-cms/16117</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Comment by dgt41** [comment]
Really?
B/C break to have a calendar without the confusing week number?
Joomla will never, ever get a good UI/UX.-

**Comment by rdeutz** [comment]
No it is not a b/c break it is just different as it was before

**Comment by dgt41** [comment]
There was a reason for this change: most calendars don't display week numbers (for most users this is confusing and just a cluttered display). One user complains and we ruin the UI/UX for the majority to satisfy the minority?
I give up...

**Comment by C-Lodder** [comment]
Why on earth would we need to display the week number by default? It's just cluttering up the calendar display and making the click space for the dates smaller. THAT is bad UX

**Comment by brianteeman** [comment]
Please can this pr be reverted. As stated this is not a b/c issue. If it
was then we could never change anything ever!

**Comment by rdeutz** [comment]
I have read the original issue and I don't see that there was an agreement that removing the week numbers is the way to go. So in this cases I go with "how it was in the past".

I see arguments for and against enabled by default and I don't know what is the majority and what the minority. So further discussion here will lead to nowhere. There is always the option to open a PR, discuss the topic, come to an agreement and then go from there.

**Comment by Bakual** [comment]
Actually, it's easier for the user to hide the weeknumbers (could be done with CSS) than to add them (needs a JLayout or JS override).

**Pull request merged**
