### PR TITLE
[4.0] Dashboard colour

### PR DESCRIPTION
**Pull request by brianteeman**
This PR changes the colour of the icons etc on the dashboard to blue from the washed out grey(?)

It makes the icons etc look active and not disabled

### Before
after

### After
after

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on e1cc4ae051eb65554ff1a8f55fb5524864b0be84<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27376">issues.joomla.org/tracker/joomla-cms/27376</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on e1cc4ae051eb65554ff1a8f55fb5524864b0be84<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27376">issues.joomla.org/tracker/joomla-cms/27376</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27376">issues.joomla.org/tracker/joomla-cms/27376</a>.</sub>

**Comment by HLeithner** [comment]
You are right looks more active. Thanks

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
