### PR TITLE
[4] webservice categories add description field

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #41291

### Summary of Changes

return the description field

### Testing Instructions

Do an API call and set the category description:

### Actual result BEFORE applying this Pull Request
the  description field is not returned

### Expected result AFTER applying this Pull Request

 the description field is present

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Razzo1987** [comment]
I have tested this item :white_check_mark: successfully on 29706868e496cc0cf518c729935b732639fd6f4f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41307">issues.joomla.org/tracker/joomla-cms/41307</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 29706868e496cc0cf518c729935b732639fd6f4f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41307">issues.joomla.org/tracker/joomla-cms/41307</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41307">issues.joomla.org/tracker/joomla-cms/41307</a>.</sub>

**Comment by laoneo** [comment]
Can you rebase this to 4.4 and add a system test?

**Comment by alikon** [comment]
rebased to 4.4
aren't system test already there https://github.com/joomla/joomla-cms/blame/4.3-dev/tests/Codeception/api/com_content/ContentCest.php#L97  ?

**Comment by alikon** [comment]
wrong rebase i'll switch it back to 4.3

**Comment by obuisard** [comment]
Thank you Nicola @alikon for the PR.

**Comment by laoneo** [comment]
> rebased to 4.4 aren't system test already there https://github.com/joomla/joomla-cms/blame/4.3-dev/tests/Codeception/api/com_content/ContentCest.php#L97 ?

In 4.4 we do the system tests on cypress [here](https://github.com/joomla/joomla-cms/blob/4.4-dev/tests/System/integration/api/com_content/Articles.cy.js).

**Comment by obuisard** [comment]
I am reverting, will re-create it for 4.4. I apologize @alikon, I will link the new PR to this one.

**Pull request merged**
