### PR TITLE
[com_fields] Use plugin specific language strings for the default value

### PR DESCRIPTION
**Pull request by laoneo**
Pull Request for Issue #14674.

### Summary of Changes
Sets different language strings fro the user default field. Fixes the all problem introduced in #14404.

### Testing Instructions
- Create a text field.
- Create a user field.

### Expected result
- On the text field the standard default text is shown.
- On the user field a different, user specific text is shown for the default field.

### Actual result
- On the text field the user specific text is shown for the default field.
- On the user field the user specific text is shown for the default field.

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 7af57e03bd7030fe4d88df6ffdff9a51ebd78364<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14679">issues.joomla.org/tracker/joomla-cms/14679</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 7af57e03bd7030fe4d88df6ffdff9a51ebd78364<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14679">issues.joomla.org/tracker/joomla-cms/14679</a>.</sub>

**Comment by infograf768** [comment]
RTC. Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14679">issues.joomla.org/tracker/joomla-cms/14679</a>.</sub>

**Comment by infograf768** [comment]
Forgot
@laoneo Please alpha order the new strings

**Pull request merged**
