### PR TITLE
[4.0] Dropdowns don't drop OVER the items below

### PR DESCRIPTION
**Pull request by N6REJ**
Pull Request for Issue # .

### Summary of Changes
changes z-index so dropdowns go OVER the content below

### Testing Instructions
install latest 4.0-dev.
go to components and click on the cog on "tags"
dropdown will be partially hidden.
install patch
run `node build.js --compile-css`
dropdown now fully visible

### Expected result
image
image

### Actual result
image
image

### Documentation Changes Required
None

### CODE REVIEW

**Comment by brianteeman** [comment]
Dupliy tepott

**Comment by brianteeman** [comment]
Oops. 

Duplicate report

**Comment by Thomsterdam** [comment]
I tested the patch and it does not have the required effect. 

The issue was not identical to what is described above: The Tags drop-down showed correct: it dropped down over the grey area but the Smart Search drop-down showed as above in the issue.  

I tested in both Firefox 69.0.1 (Linux) and Chromium 77.0.3865.90 (Linux) and the results are the same. See picture. So after applying the patch, the issue is **NOT** fixed. 

screen shot 2019-10-01 at 12 08 29<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26371">issues.joomla.org/tracker/joomla-cms/26371</a>.</sub>

**Comment by Thomsterdam** [comment]
I have tested this item :red_circle: unsuccessfully on 0ddb2f3127959e21feb7f61c5e80046dbdb60052<br /><br />I tested the patch and it does not have the required effect.

The issue was not identical to what is described above: The Tags drop-down showed correct: it dropped down over the grey area but the Smart Search drop-down showed as above in the issue.

I tested in both Firefox 69.0.1 (Linux) and Chromium 77.0.3865.90 (Linux) and the results are the same. See picture. So after applying the patch, the issue is NOT fixed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26371">issues.joomla.org/tracker/joomla-cms/26371</a>.</sub>

**Comment by richard67** [comment]
Testing instructions are not complete, it needs to run “npm install” after having applied the patch. Or am I wrong?

**Comment by brianteeman** [comment]
Yes the test instructions are wrong

No need to do a full npm install - it is enough to run
`node build.js --compile-css `

This will compile all the scss defined files and also create a minified version of the css

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 0ddb2f3127959e21feb7f61c5e80046dbdb60052<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26371">issues.joomla.org/tracker/joomla-cms/26371</a>.</sub>

**Comment by richard67** [comment]
Yes, `node build.js --compile-css` is absolutely sufficient ... but `npm install` is easier to remember for me ;-)

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 0ddb2f3127959e21feb7f61c5e80046dbdb60052<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26371">issues.joomla.org/tracker/joomla-cms/26371</a>.</sub>

**Comment by richard67** [comment]
@Thomsterdam Please change your test result in the issue tracker to "Not tested" so maintainers don't get confused by the negative test (which was wrong due to wrong testing instructions).

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26371">issues.joomla.org/tracker/joomla-cms/26371</a>.</sub>

**Comment by N6REJ** [comment]
do I need to change something guys?

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
