### PR TITLE
[com_tags] All Tags default layout

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue # .

### Summary of Changes

This fixes the issue of default all tags layout setting not being respected. Also removes some misplaced code.

### Testing Instructions

Create an alternative All Tags layout (in /components/com_tags/views/tags/tmpl/ or /templates/protostar/html/com_tags/tags/).
Go to `com_tags` configuration and select new layout under `Default List All Tags Layout` setting.
Enter all tags view directly (`index.php?option=com_tags&view=tags`).

### Expected result

Selected layout is used.

### Actual result

Selected layout not used.

### Documentation Changes Required
No.

### CODE REVIEW

**Comment by ghost** [comment]
Can't get this PR working:

#### As wroting in Test Instructions created an alternative All Tags layout:

bildschirmfoto 2018-07-11 um 16 03 23

#### In "Tag Options" selected the new Layout:

bildschirmfoto 2018-07-11 um 16 05 19

#### Entered all tags view directly (index.php?option=com_tags&view=tags) but get with and -out PR same Result:

bildschirmfoto 2018-07-11 um 16 02 05

### System information
- 3.8.11-dev
- Template: Protostar
- macOS Sierra, 10.13.6
- Firefox 61 (64-bit)
#### CloudAccess.net
- PHP 7.0.28
- MySQLi 5.7.18-cll-lve

**Comment by ghost** [comment]
I have tested this item :red_circle: unsuccessfully on 9be6cfcd188442d658aeac99d83502ece885ca05<br /><br />as described above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21031">issues.joomla.org/tracker/joomla-cms/21031</a>.</sub>

**Comment by SharkyKZ** [comment]
@franz-wohlkoenig did you make any changes to custom layout? You need something to tell the two layouts apart.

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 9be6cfcd188442d658aeac99d83502ece885ca05<br /><br />Thanks for Info, @SharkyKZ 

I changed the Size of Tag-Title from h3 up to h1; using PR at "index.php?option=com_tags&view=tags" Title is shown in h1.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21031">issues.joomla.org/tracker/joomla-cms/21031</a>.</sub>

**Comment by fancyFranci** [comment]
I have tested this item :white_check_mark: successfully on 9be6cfcd188442d658aeac99d83502ece885ca05<br /><br />My test layout has a new paragraph and I can see it only after applying this patch.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21031">issues.joomla.org/tracker/joomla-cms/21031</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Pull request merged**
