### PR TITLE
Small review on docs & code structure in JModelLegacy library classes

### PR DESCRIPTION
**Pull request by mbabker**
#### Summary of Changes
- Improves doc blocks
- Calls non-static methods using `$this` instead of static accessor
- Simplify some lines as able
- Access database object from within the model instance versus JFactory
- Access database object via getter versus direct property use
#### Testing Instructions

Review

### CODE REVIEW

**Comment by RonakParmar** [comment]
I have tested this item :white_check_mark: successfully on 73d752891f6731c98862df3ec1c1ccf810c38155<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11057">issues.joomla.org/joomla-cms/11057</a>.</sub>

**Comment by wilsonge** [comment]
Conflicts here please

**Comment by brianteeman** [comment]
@mbabker thanks for fixing the merge conflicts

**Comment by wilsonge** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11057">issues.joomla.org/joomla-cms/11057</a>.</sub>

**Comment by truptikagathara** [comment]
I have tested this item :white_check_mark: successfully on 5d859ca2614a77b8b6edcdf0b21a93219633f4fa<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11057">issues.joomla.org/joomla-cms/11057</a>.</sub>

**Pull request merged**
