### PR TITLE
[com_tags] review config global default options

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
### Summary of Changes

This PR intends to normalize config global default options in com_tags.

The method used was:
1. Review cs of the config.xml file - also add missing default values
2. Check the current params in installation joomla.sql mysql
3. Add missing defaults to install sql

### Testing Instructions

0. Code review
1. Apply patch
2. Delete configuration.php
3. Install Joomla (no sample)
4. Create tag menu items and check all "Use Global"  have the global value.

### Documentation Changes Required

None.

### Added/changed defaults in the xml

changed:
- history_limit: 10 (was 5 - uniformize with articles)
- tag_list_orderby: c.core_title (was `title` - which doesn't exist)

added:
- tag_list_image: *empty*
- tag_list_show_item_description: 1 (the first option of the list)
- tag_list_item_maximum_characters: 0 (not sure about this one please confirm)
- all_tags_tag_maximum_characters: 0 (not sure about this one please confirm)

Note: also correct the parameter `all_tags_show_tag_descripion` by `all_tags_show_tag_description` this was nto working because the parameter was badly named in the xml files

### CODE REVIEW

**Comment by brianteeman** [comment]
>tag_list_image: empty
tag_list_show_item_description: 1 (the first option of the list)
tag_list_item_maximum_characters: 0 (not sure about this one please confirm)
all_tags_tag_maximum_characters: 0 (not sure about this one please confirm)

On a current clean install the values are
tag_list_show_item_description: 0 - even though the default in the xml is 1 - not sure if there is a b/c issue with changing it

I couldnt find tag_list_item_maximum_characters or all_tags_tag_maximum_characters<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12979">issues.joomla.org/tracker/joomla-cms/12979</a>.</sub>

**Comment by andrepereiradasilva** [comment]
> On a current clean install the values are tag_list_show_item_description: 0 - even though the default in the xml is 1 - not sure if there is a b/c issue with changing it

installation can have diferent values than the default in xml. AFAIK there is no B/C issue with that.
Anyway i didn't change that in the installation.
Also you can see that in the php the default is `1` https://github.com/joomla/joomla-cms/blob/staging/components/com_tags/views/tag/tmpl/default_items.php#L97

> I couldnt find tag_list_item_maximum_characters or all_tags_tag_maximum_characters

besides xml and sql:
```
# egrep -n -R "tag_list_item_maximum_characters" /path/to/joomla-staging/

/path/to/joomla-staging/components/com_tags/views/tag/tmpl/default_items.php:101
/path/to/joomla-staging/components/com_tags/views/tags/tmpl/default_items.php:116

# egrep -n -R "all_tags_tag_maximum_characters" /path/to/joomla-staging/

(none)
```

**Comment by conconnl** [comment]
I have test #12979 and #12981 
Menu Item: Compact list of tagged items
Does not show the Global setting for:
# Items to List (Tab List Layouts)

The other two menu items are OK:
Tagged Items
List of all tags<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12979">issues.joomla.org/tracker/joomla-cms/12979</a>.</sub>

**Comment by ghost** [comment]
If this Issue get no Response, it will be closed at 22th September 2018.

**Comment by ghost** [comment]
This has been closed due to lack of response to the requests above – it can always be reopened.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12979">issues.joomla.org/tracker/joomla-cms/12979</a>.</sub>

**Pull request closed without merging**
