### PR TITLE
Do not distribute /libraries/fof/LICENSE.txt

### PR DESCRIPTION
**Pull request by PhilETaylor**
as its only deleted by script.php once installed anyway and is just a duplicate GPL v2 License

Part of #22219

### CODE REVIEW

**Comment by mbabker** [comment]
Actually the line should be removed from the delete array, not the file removed from the repo.  Especially in the case of a third party's LICENSE file...

**Comment by PhilETaylor** [comment]
So you want to keep multiple versions of the GPL text?

**Comment by mbabker** [comment]
We keep the license file for every external package we pull in (check `libraries/vendor`), even though that results in several copies of at least the GPL and MIT licenses being included.  The other option is to concatenate and have a single LICENSE file for the entire distribution with the text of all applicable licenses.

**Comment by PhilETaylor** [comment]
No worries - forked to #22585

**Pull request closed without merging**
