### PR TITLE
[5.2] Update jooa11y checker [a11y]

### PR DESCRIPTION
**Pull request by brianteeman**
This PR updates the sa11y accessibility script used in the joomla accessibility checker.

Together with several minor bug fixes there is now a new feature showing the images in the checker itself

See https://github.com/ryersondmp/sa11y/releases for a full list of changes since the current 3.1.3 release

New Images Tab
image

### Testing Instructions
As this is a change in an npm script you will need to either test a prebuilt release or run npm i on this branch

Thanks to @adamchaboryk for continued development

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on a3b7850592858c55f0c2c1eb8414dae53524ae54<br /><br />Tested by checking different errors and looks good. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43831">issues.joomla.org/tracker/joomla-cms/43831</a>.</sub>

**Comment by brianteeman** [comment]
Thanks for testing

**Comment by fgsw** [comment]
I have tested this item :white_check_mark: successfully on a3b7850592858c55f0c2c1eb8414dae53524ae54<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43831">issues.joomla.org/tracker/joomla-cms/43831</a>.</sub>

**Comment by chmst** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43831">issues.joomla.org/tracker/joomla-cms/43831</a>.</sub>

**Comment by brianteeman** [comment]
Closing as the pr was ignored and was rolled into generic updates

**Pull request closed without merging**
