### PR TITLE
[4.0] Templates Preview image

### PR DESCRIPTION
**Pull request by brianteeman**
When you click on the thumbnail image of a template you see a larger image of the template. The current title of that popup is "Template Preview". This is not the correct string as you might have on the same row a message saying "Preview not available" or a link called "preview" which does something different. In addition the value of the string being incorrect it was also using the same key as the preview button in the toolbar which does something different - so might cause translation issues.

This PR introduces a new string to use for the popup which correctly identifies the image as a screenshot and includes the name of the template

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 8cc5971bd85b64a546497a4c5e4a310b8131f54b<br /><br />After Patch, it's called: Cassiopeia Screenshot<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26814">issues.joomla.org/tracker/joomla-cms/26814</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 8cc5971bd85b64a546497a4c5e4a310b8131f54b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26814">issues.joomla.org/tracker/joomla-cms/26814</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26814">issues.joomla.org/tracker/joomla-cms/26814</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
