### PR TITLE
[4.1] Update protected library folders

### PR DESCRIPTION
**Pull request by brianteeman**
Update the list of core folders

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 2df5d91f9093a7d051b387aca6d6c0f016f8c48d<br /><br />I can confirm that only the remaining folders exist as sub-folders of the libraries folder, the removed ones don't exist.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36820">issues.joomla.org/tracker/joomla-cms/36820</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 2df5d91f9093a7d051b387aca6d6c0f016f8c48d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36820">issues.joomla.org/tracker/joomla-cms/36820</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36820">issues.joomla.org/tracker/joomla-cms/36820</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Comment by brianteeman** [comment]
Thank you

**Pull request merged**
