### PR TITLE
Validated type=number in Administrator Modules

### PR DESCRIPTION
**Pull request by Shubhamverma2796**
### Pull request for 

Pull request for issue #36096 

### Summary of Changes

Validated type=number for the administration modules.

### Testing Instructions

1. Select Content-->Administrator module.
2. Try to create new modules by setting -ve values in where type="number"

### Actual result BEFORE applying this Pull Request

Modules will be saved successfully with -ve values

### Expected result AFTER applying this Pull Request

Invalid field message is displayed.

### CODE REVIEW

**Comment by Ravi-chandra69** [comment]
I have not tested this item.<br /><br />Followed the testing instructions and the patch worked successfully.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36100">issues.joomla.org/tracker/joomla-cms/36100</a>.</sub>

**Comment by Ravi-chandra69** [comment]
I have tested this item :white_check_mark: successfully on e9f4a76ef3666bc9863eb3a2b90fc079fe4a08fa<br /><br />Followed the testing instructions and the patch worked successfully.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36100">issues.joomla.org/tracker/joomla-cms/36100</a>.</sub>

**Comment by richard67** [comment]
@Shubhamverma2796 When making a pull request to solve an issue, please refer to the issue at the top of the PR description. In this case here it should be:

Pull request for issue #36096 .

Thanks in advance.

**Comment by pritam825** [comment]
I have tested this item :white_check_mark: successfully on e9f4a76ef3666bc9863eb3a2b90fc079fe4a08fa<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36100">issues.joomla.org/tracker/joomla-cms/36100</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36100">issues.joomla.org/tracker/joomla-cms/36100</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
