### PR TITLE
[5.0] Animation for new dialog

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue # .

### Summary of Changes

A litle animation for dialog, very similar to bs modal

### Testing Instructions
Apply patch, run `npm install`
Go to menu, edit menu Single Article, and select Artcile

### Actual result BEFORE applying this Pull Request
Dialog without animation

### Expected result AFTER applying this Pull Request
Dialog with animation

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed
- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

References:
- https://github.com/joomla/joomla-cms/pull/40150

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on a827687eb5534047f19a45cff8d07e33303b1ae9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41748">issues.joomla.org/tracker/joomla-cms/41748</a>.</sub>

**Comment by wilsonge** [comment]
We need a media query to be turn off the animation similar to https://github.com/joomla/joomla-cms/blob/78bb192670753c46b374cbaf56440a00266892e9/build/media_source/system/scss/joomla-core-loader.scss#L120C1-L124

**Comment by Fedik** [comment]
Added

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 0d44b065d042ab5c89bab44b18ada10ca2c4eeb7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41748">issues.joomla.org/tracker/joomla-cms/41748</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41748">issues.joomla.org/tracker/joomla-cms/41748</a>.</sub>

**Comment by HLeithner** [comment]
thx

**Pull request merged**
