### PR TITLE
[5.0][RFC] Joomla.Editor and Joomla.EditorButton client side API

### PR DESCRIPTION
**Pull request by Fedik**
### Summary of Changes

This is an atempt to improve our client side API for Editor and Editor XTD buttons.
In addittion to #40082 for server side.

~I made it for 4.x to be able easily test on "production" codebase. However main target > 5.x~

Currently it conflicts with #40082, that will be need to adjust depending which one will be merged first.
To run this PR need to apply changes from #40150.

### What and why

Currently we have `Joomla.editors.instances` which just a collection of bare Objects.
And no easy way to determine active/interacted editor.
The XTD Buttons is very limited and not able to work in Subform.

**Main idea is next:** Editor script register an Instance in `JoomlaEditor`, mark this instance  as `active` whenever User interact with editor or an XTD button. When User click XTD button then `JoomlaEditorButton` (or Editor which integrated this XTD buttons like we do in TinyMCE) will run registered action. The action will be applied to `active` editor instance.

### JoomlaEditor
`JoomlaEditor` is for managing an Editors on the page: register, unregister, retrieve active instance.

I have replaced a bare Object of editors with `JoomlaEditorDecorator`, with set of specific methods for correct "cross-editor" interaction. The Decorator is basicaly a wrapper around Editor (TinyMCE, Codemirror etc) instance.
The Decorator should be implemented by Editor script and registered in `JoomlaEditor.register()`.

Also Editor script now should set an active instance, everytime when User intercat with editor or with one of editor XTD button, with `JoomlaEditor.setActive(<decorator|id>)`.

**Example:**
`TinyMCEDecorator` https://github.com/joomla/joomla-cms/blob/9e6b08b9dd4c04450842f92371c4707a62a8613e/build/media_source/plg_editors_tinymce/js/tinymce.es6.js#L27
TinyMCE set active: https://github.com/joomla/joomla-cms/blob/9e6b08b9dd4c04450842f92371c4707a62a8613e/build/media_source/plg_editors_tinymce/js/tinymce.es6.js#L107-L109

### JoomlaEditorButton
`JoomlaEditorButton` is for managing an actions that can be executed by XTD button.
From now each button will run specific "action", which should be registered with `JoomlaEditorButton.registerAction()`.
This allows more transparent "cross-editor" integration.

**Example:**
`insert` action: https://github.com/joomla/joomla-cms/blob/207467bf97b6d4632723bab25f07a075fb7c50a4/build/media_source/system/js/editors.es6.js#L350
`modal` action:
PHP: https://github.com/joomla/joomla-cms/blob/28ea48a995e84bd2abc5efdb19e3c0d073f06d4f/plugins/editors-xtd/contact/src/Extension/Contact.php#L60
JavaScript: https://github.com/joomla/joomla-cms/blob/207467bf97b6d4632723bab25f07a075fb7c50a4/build/media_source/system/js/editors.es6.js#L355

### Backward compatibility

I tried to address potential issues that may break older editors. 
However it still may fail, example when editor does not provide Active instance and "b.c. code" cannot find it then XTD button will fail.

### Notes
Here still a room for improve, and work to do. Example it will be need to update all our "modal-select" scripts, which accessing old `Joomla.editors.instances` directly.

### Testing Instructions

Apply patch and apply #40150.
Run `npm install`.
Try to use diferent editors, and XTD buttons.
Try run the test within subform.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: TBD
- [x] Pull Request link for manual.joomla.org: https://github.com/joomla/Manual/pull/97

### CODE REVIEW

**Comment by Fedik** [comment]
Note: the test will fail, because the PR depend from  https://github.com/joomla/joomla-cms/pull/40150.

**Comment by laoneo** [comment]
I guess it is better to rebase this pr to the 5.0-dev branch, as it will get more attention for new features. Thanks for understanding.

**Comment by Fedik** [comment]
The ESM version with use of importmap https://github.com/joomla/joomla-cms/compare/5.0-dev...Fedik:joomla-cms:editor-js-api2

**Comment by Fedik** [comment]
Note: Need to update PR to use ES modules

**Review by dgrammatiko — APPROVED** [review]

**Comment by HLeithner** [comment]
thanks, merging this for beta1 to get real world feedback

**Comment by Ruud68** [comment]
After this change my editor-xtd plugin stopped working. it was working on J3 / J4.
Note, that this is a plugin that will show a modal that I construct myself as there is no possibility to construct the modal via an iframe (like all other Joomla buttons are doing (as these have components generating the content of the iframe).

So the button is displaying, the modal window is constructed correctly (hidden), but clicking the button doesn't show / open the modal.

I have worked around this by setting the button->modal to true (which would then display an empty modal and not the one I created and setting the $button->options = ['confirmCallback' => true];

Now the modal I created works again.


So as far i can see this is just a workaround for having a button in the editor displaying your own modal when you do not have the option to.

Not even sure as to what the confirmCallback option will do, or if it is even possible to have a editor button open a custom BS modal without triggering the 'legacyModal' modus (which I presume is called legacy because it will be removed some day.

**Comment by Fedik** [comment]
How is your button looks like?

The following "legacy code" should produce iframe:
```php
$button  = new CMSObject();
$button->modal  = true;
$button->link = $link;
```

**Comment by Ruud68** [comment]
Hi @Fedik thanks for following up.
there is no $button->link as this is plugin does not have a way to produce the contents of an iFrame. Instead it produces the modal itself.

```
        $button          = new CMSObject();
        $button->modal   = true;
        $button->editor  = $name;
        $button->text    = Text::_('PLG_EDITORS-XTD_OCHELEMENTS_BUTTON_OCHELEMENTS');
        $button->name    = $this->_type . '_' . $this->_name;
        $button->icon    = 'code';
        $button->iconSVG = '<svg viewBox="0 0 24 24" style="fill:none;" width="24" height="24" fill="none" stroke="currentColor" focusable="false"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 20l4-16m4 4l4 4-4 4M6 16l-4-4 4-4"></path></svg>';
        $button->options = ['confirmCallback' => true];

        // Create the Bootstrap Modal, the Joomla Helper class for this is to limited
        $modalId         = $button->editor . '_' . $button->name . '_modal';
        $modalLayout     = new FileLayout('modal', JPATH_PLUGINS . '/editors-xtd/ochelements/layouts/');
        $modalBodyLayout = new FileLayout('buttons', JPATH_PLUGINS . '/editors-xtd/ochelements/layouts/');
        $modalBody       = $modalBodyLayout->render(['editor' => $button->editor, 'content' => $pluginResults]);
        echo $modalLayout->render(['modalId' => $modalId, 'modalBody' => $modalBody]);

        return $button;
```

So the above code works because I added the confirmCallback option, without it the button shows, but will not open the modal.

I took a quick look at the new api and this is not an option for me: 70% of my customers is still on J3, and I do not want to maintain 3 versions of my extensions: Already noticed other B/C that required refactoring going to 5.0 for some of my extensions. So I need to be able to do it the way it was in J4 (which worked in J3) without B/C or with a workaround that will not break things.

**Comment by Fedik** [comment]
@Ruud68 Please test https://github.com/joomla/joomla-cms/pull/41633 that should keep old behavior untill Joomla 6.

**Comment by Ruud68** [comment]
Just to understand what is happening here:
previously we had (bootstrap) modals, you are replacing these with (custom Joomla) dialogs. Correct?

If so, would it then not make more ense to have the $button->action have the values:

- modal > which will then me the templates (bootstrap) modal
- dialog > the (custom joomla) dialogs

That makes more sense (at least to me) then trying to figure out what the difference is between $button->modal = true and $button->action = modal

Another benefit is that there is no need to deprecate things, as both template (bootstrap) modals are supported (also beyond v6) and the nw (custom Joomla) dialogues can perfectly coexist and then the developer can decide what to use without being forced into dialogues.

Just my 2cts.

**Comment by Fedik** [comment]
> $button->modal = true

This is old way to make modal.

The problem with existing BS modals, in the way they are rendered they does not work properly when the field is used in repeatable mode, example in a subform field.
That why I would not do `$button->action = 'modal'` and `$button->action = 'dialog'`

> $button->action = 'foobar'

This is a new API to asign specific action to your button.
In core Joomla provide `modal` action, that will display a Dialog.
Hovewer you can do your custom action, and it will run when user click the button

Look the link https://manual.joomla.org/docs/next/building-extensions/plugins/editors-xtd-plugin
There you can find how to do `$button->action = 'insert-cat';`

**Comment by HLeithner** [comment]
for consistent we only should support one look and feel, if 3rd party would like to use another popup tool then they can do it. It's not nice but possible. For us we fixed the subform issue with the new dialog, so "bug fixed" for us. If you or someone else provide a b/c fix for the bootstrap issue we will of course consider it. But it's hard to support multiple ways to do the same thing with our resources.

anyway thanks for bringing this up and I hope the solution provided by Fedir works at least the same as before without b/c break.

**Pull request merged**
