### PR TITLE
[4.0] Separate system dashboard and menu

### PR DESCRIPTION
**Pull request by bembelimen**
### Summary of Changes
With Joomla! 4 we have the new system dashboard with all the unimportant extensions/links. Some links are still in the main menu and the new dashboard. This PR makes a real cut, a menu entry is either in the main menu or in the system dashboard.

- Redirect (component menu) is removed from the system dashboard
- Modules (Content submenu) are removed from the system dashboard
- Post-Install-Message does (imho) not deserve a link in the mainmenu, it's not that important

### Testing Instructions
Check main menu + system dashboard.

### CODE REVIEW

**Comment by brianteeman** [comment]
It shouldnt be about if it is important or not but what type of thing it is, it's not a junk link for everything else. It is called System so I would expect to find all things related to the system there. So I agree with you about removing "site modules" from system and to removing post-install from the menu. But I believe redirects should be in system not menu. they are a system functionality not a site functionality

**Comment by brianteeman** [comment]
As Redirects, joomla update and Post Installation Messages are now correctly in the system control panel they should be removed from the actual components menu.

**Comment by wilsonge** [comment]
I agree with @brianteeman with them being in system control (although I would add that it comes with the caveat we still obviously need the quickicon for postinstall on the main dashboard so it's obvious when there are messages)

**Comment by wilsonge** [comment]
Can you fix the conflicts here and I'll get this in :)

**Comment by brianteeman** [comment]
@bembelimen please fix the conflicts so that this important pr can be merged

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
