### PR TITLE
[4.0] redesigned media-browser-actions-list

### PR DESCRIPTION
**Pull request by bahl24**
Pull Request for Issue #https://github.com/joomla-projects/media-manager-improvement/issues/567.

Will also help to solve https://github.com/joomla/joomla-cms/issues/23968

### Summary of Changes
Screenshot from 2019-03-25 15-26-38
Small changes in actions - list

### Testing Instructions
Build vue files & clear cache.

##### This Pull Request can only be tested by [NPM](https://docs.joomla.org/J4.x:Setting_Up_Your_Local_Environment) only on a local environment and not by using Patchtester.

### CODE REVIEW

**Comment by infograf768** [comment]
New display works here. Is it what admin template workgroup desires? @ciar4n

**Comment by ghost** [comment]
is this Test using Patchtester?

**Comment by ciar4n** [comment]
I did style the original media manager UI for the old template design but I'm not part of the @rdeutz  template group. Last I checked that group was private. So short answer..  I don't know.

IMO since the template design has changed, the media manager looks out of place with the rest of the template and needs a total overhaul. But any changes is probably pointless IF this is been worked elsewhere.

**Comment by ciar4n** [comment]
@franz-wohlkoenig Not possible to test with patchtester

**Comment by ghost** [comment]
@ciar4n thanks, can you please provide a Link how to use NPM? Haven't found at https://docs.joomla.org/Special:MyLanguage/Portal:Joomla!_Code_Contributors

**Comment by brianteeman** [comment]
Follow the link in the reader for j4 which takes you to 
 https://docs.joomla.org/J4.x:Setting_Up_Your_Local_Environment

You can only do this on a local environment. It is not possible on a remote like launch.joomla.org

**Comment by bahl24** [comment]
@franz-wohlkoenig  you can run `npm run dev` in administrator/components/com_media folder & then clear browser cache after applying the patch.

**Comment by ghost** [comment]
@brianteeman thanks for Links and Info. 

I updated the Test Instructions so non-Dev know how to test. If this is fine, i would append this Informations on all PR which need NPM for test.

**Comment by wilsonge** [comment]
@ciar4n it's public now ;) https://github.com/joomla/backend-template/tree/release (make sure you're on the release branch if you clone down). but no they haven't worked on the media manager

**Comment by wilsonge** [comment]
I don't think this is going to be acceptable from an a11y perspective @brianteeman @zwiastunsw as i assume all the elements need to be in the same `ul` element

**Comment by brianteeman** [comment]
@wilsonge thats correct but it can be resolved very easily  - you can display a single list in two columns with just css using the html5 columns styling https://www.w3.org/TR/css-multicol-1/

**Comment by wilsonge** [comment]
OK Let's do that then. @bahl24 can you do the columns in CSS then please

**Comment by Quy** [comment]
Closing in favor of #25123<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24423">issues.joomla.org/tracker/joomla-cms/24423</a>.</sub>

**Pull request closed without merging**
