### PR TITLE
[4.0][api][com_content] complete the list of fields to render

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #30145 .

### Summary of Changes
complete the list of com_content fields to render via API GET
fixed the Notice reported https://github.com/joomla/joomla-cms/pull/30134#pullrequestreview-455898216

### Testing Instructions

call the api

--for article list
`{{base_url}}api/index.php/v1/content/article`

--for article item
`{{base_url}}api/index.php/v1/content/article/{id} `

### Actual result BEFORE applying this Pull Request

these fields are not rendered:
               

- alias
- note
- publish_up
- publish_down
- urls
- created
- created_by
- created_by_alias
- modified
- modified_by
- hits
- version
- featured_up
- featured_down

### Expected result AFTER applying this Pull Request
fields are rendered

```json
{
    "links": {
        "self": "http://localhost/4beta/api/index.php/v1/content/article/6"
    },
    "data": {
        "type": "articles",
        "id": "6",
        "attributes": {
            "typeAlias": "com_content.article",
            "id": 6,
            "asset_id": 91,
            "title": "Your Template",
            "alias": "your-template",
            "state": 1,
            "created": "2020-07-26 09:35:57",
            "created_by": 223,
            "created_by_alias": "",
            "modified": "2020-07-26 09:51:30",
            "modified_by": 223,
            "publish_up": "2020-07-26 09:35:57",
            "publish_down": "2020-07-31 11:43:29",
            "images": {
                "image_intro": "",
                "float_intro": "",
                "image_intro_alt": "",
                "image_intro_caption": "",
                "image_fulltext": "",
                "float_fulltext": "",
                "image_fulltext_alt": "",
                "image_fulltext_caption": ""
            },
            "urls": {
                "urla": "http://alikonweb.it/A",
                "urlatext": "alikonweb",
                "targeta": "0",
                "urlb": "http://alikonweb.it/b",
                "urlbtext": "alikonweb",
                "targetb": "0",
                "urlc": "http://alikonweb.it/c",
                "urlctext": "alikonweb",
                "targetc": "0"
            },
            "version": 5,
            "metakey": "",
            "metadesc": "",
            "access": 1,
            "hits": 0,
            "metadata": {
                "robots": "",
                "author": "",
                "rights": ""
            },
            "featured": 0,
            "language": "*",
            "note": "a Note",
            "tags": [],
            "featured_up": null,
            "featured_down": null,
            "text": "<p>Templates control the look and feel of your website.</p>\r\n<p>This blog is installed with the Protostar template.</p>\r\n<p>You can edit the options by selecting the Working on Your Site, Template Settings link in the top menu (visible when you login).</p>\r\n<p>For example you can change the site background color, highlights color, site title, site description and title font used.</p>\r\n<p>More options are available in the site administrator. You may also install a new template using the extension manager.</p> "
        },
        "relationships": {
            "category": {
                "data": {
                    "type": "categories",
                    "id": "8"
                }
            },
            "author": {
                "data": {
                    "type": "users",
                    "id": "223"
                }
            }
        }
    }
}
```

### CODE REVIEW

**Comment by chetanmadaan** [comment]
Awesome, I have verified the new fields render.

Before:
```
    "data": {
        "type": "articles",
        "id": "6",
        "attributes": {
            "typeAlias": "com_content.article",
            "id": 6,
            "asset_id": 91,
            "title": "Your Template",
            "state": 0,
            "created": "2020-06-01 21:23:07",
            "images": {
                "image_intro": "",
                "float_intro": "",
                "image_intro_alt": "",
                "image_intro_caption": "",
                "image_fulltext": "",
                "float_fulltext": "",
                "image_fulltext_alt": "",
                "image_fulltext_caption": ""
            },
            "metakey": "Keyword One, Keyword two, Keyword #3",
            "metadesc": "This is my Meta Description",
            "metadata": {
                "robots": "index, nofollow",
                "author": "Author of Article",
                "rights": "Copyright 2020 All rights, Reserved!"
            },
            "language": "*",
            "tags": [],
            "text": "<p>Templates control the look and feel of your website.</p>\r\n<p>This blog is installed with the Protostar template.</p>\r\n<p>You can edit the options by selecting the Working on Your Site, Template Settings link in the top menu (visible when you login).</p>\r\n<p>For example you can change the site background color, highlights color, site title, site description and title font used.</p>\r\n<p>More options are available in the site administrator. You may also install a new template using the extension manager.</p> "
        },
        "relationships": {
            "category": {
                "data": {
                    "type": "categories",
                    "id": "8"
                }
            },
            "author": {
                "data": {
                    "type": "users",
                    "id": "30"
                }
            }
        }
    }
```

After:
```
   "data": {
        "type": "articles",
        "id": "6",
        "attributes": {
            "typeAlias": "com_content.article",
            "id": 6,
            "asset_id": 91,
            "title": "Title of Article goes here",
            "alias": "your-template",
            "state": 1,
            "created": "2020-07-18 10:47:32",
            "created_by": 815,
            "created_by_alias": "",
            "modified": "2020-07-18 11:14:33",
            "modified_by": 815,
            "publish_up": "2020-07-18 10:47:32",
            "publish_down": null,
            "images": {
                "image_intro": "",
                "float_intro": "",
                "image_intro_alt": "",
                "image_intro_caption": "",
                "image_fulltext": "",
                "float_fulltext": "",
                "image_fulltext_alt": "",
                "image_fulltext_caption": ""
            },
            "urls": {
                "urla": "",
                "urlatext": "",
                "targeta": "",
                "urlb": "",
                "urlbtext": "",
                "targetb": "",
                "urlc": "",
                "urlctext": "",
                "targetc": ""
            },
            "version": 5,
            "metakey": "This is this",
            "metadesc": "This",
            "access": 1,
            "hits": 0,
            "metadata": {
                "robots": "noindex, follow",
                "author": "Author",
                "rights": "No Rights possible"
            },
            "featured": 1,
            "language": "*",
            "note": "",
            "tags": [],
            "featured_up": null,
            "featured_down": null,
            "text": "My text "
        },
        "relationships": {
            "category": {
                "data": {
                    "type": "categories",
                    "id": "8"
                }
            },
            "author": {
                "data": {
                    "type": "users",
                    "id": "815"
                }
            }
        }
    }
```

The warnings from Joomla backend is gone too.

**Comment by chetanmadaan** [comment]
I have tested this item :white_check_mark: successfully on 797a1736989f7946cd88a0d4e59afcc966b82c7b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30202">issues.joomla.org/tracker/joomla-cms/30202</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 797a1736989f7946cd88a0d4e59afcc966b82c7b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30202">issues.joomla.org/tracker/joomla-cms/30202</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30202">issues.joomla.org/tracker/joomla-cms/30202</a>.</sub>

**Pull request merged**
