### PR TITLE
[4.0] Fix module form buttons in frontend

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/29140.

### Summary of Changes

Fixes module form buttons in frontend.

### Testing Instructions

Run `node build.js --compile-js`.

Edit a module in frontend.
Click on the icon within one of the form buttons.

### Expected result

Form submitted.

### Actual result

JS error:

>TypeError: form is undefined validate.js:265:22

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by C-Lodder** [comment]
Still not working.
If you click on the "x" icon within the Cancel button, the error still appears

**Comment by SharkyKZ** [comment]
@C-Lodder did you run `node build.js --compile-js`?

**Comment by C-Lodder** [comment]
I just made the change directly in the compiled file

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 362179fcab1db58cea5f9bf80713a9290fdbd0af<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29141">issues.joomla.org/tracker/joomla-cms/29141</a>.</sub>

**Comment by SharkyKZ** [comment]
@C-Lodder are you sure you edited the correct file?

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 362179fcab1db58cea5f9bf80713a9290fdbd0af<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29141">issues.joomla.org/tracker/joomla-cms/29141</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29141">issues.joomla.org/tracker/joomla-cms/29141</a>.</sub>

**Comment by zero-24** [comment]
@C-Lodder could you made this work? Or do you still see an issue here?

**Comment by C-Lodder** [comment]
It's working

**Comment by zero-24** [comment]
Thanks for confiming. Merging now.

**Pull request merged**
