### PR TITLE
[4.0] added missing class in buttons

### PR DESCRIPTION
**Pull request by bahl24**
Pull Request for Issue -Required class missing for `Cancel` button leading to inconsistency from other modals in Joomla.

### Summary of Changes
Added class

### Testing Instructions
Build vue files in com_media before testing

### Expected result
Screenshot from 2019-03-11 21-21-16

### Actual result
Screenshot from 2019-03-11 21-23-53

### CODE REVIEW

**Comment by SharkyKZ** [comment]
This is intentional. That's why these buttons have `btn-link` class. If the change is accepted, then `btn-link` class should be removed.

**Comment by bahl24** [comment]
@SharkyKZ Ok, but does `btn-link` offers some additional functionality in addition to style?
Because, I think the buttons should be consistent as it is in other modals across J4, such as
Screenshot from 2019-03-11 22-04-59

**Comment by SharkyKZ** [comment]
No, it just makes buttons look like links. I don't know which class should be used. But it should be one or the other, not both at the same time.

**Comment by Quy** [comment]
Remove `btn-link` to be consistent with other Cancel buttons.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 57ade006f34490bfae15eeffa5121f2893a05c2d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24160">issues.joomla.org/tracker/joomla-cms/24160</a>.</sub>

**Comment by bahl24** [comment]
@SharkyKZ Kindly test

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on 57ade006f34490bfae15eeffa5121f2893a05c2d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24160">issues.joomla.org/tracker/joomla-cms/24160</a>.</sub>

**Comment by bahl24** [comment]
@franz-wohlkoenig Is there any problem, with RTC?

**Comment by ghost** [comment]
All fine. Sometimes its not synchronized between Tracker and Github but i don't remember what happens 2 Hours ago :-)

**Comment by SharkyKZ** [comment]
@franz-wohlkoenig Thanks. But RTC label is still missing on Github.

**Comment by ghost** [comment]
Its shown on Issue Tracker (green Background too) and Github on right Side top.

**Comment by brianteeman** [comment]
image

image

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
