### PR TITLE
[4.0] Remove Migration Script

### PR DESCRIPTION
**Pull request by himanshu007-creator**
Pull Request for Issue #33379

### Summary of Changes
Remove migration script for blog layout as now the function is no longer needed.

### Testing Instructions
Install J3.10 and make some blogs with entries in num_columns. Update to J4.0
in J4.0, blog must have same same columns as there were in J3.10

### Documentation Changes Required
none

### CODE REVIEW

**Comment by chmst** [comment]
@Harmageddon could you please have a look here? As we now have a param num_columns, the script is no longer needed.

**Comment by richard67** [comment]
@himanshu007-creator Please change the title of this PR to something more meaningful about what the changes are good for.

**Comment by joomdonation** [comment]
Please remove some un-used use statements at the top of file:

```php
use Joomla\CMS\Component\ComponentHelper;
use Joomla\CMS\Uri\Uri;
use Joomla\Component\Config\Administrator\Model\ComponentModel;
```

**Comment by joomdonation** [comment]
@chmst In the original PR, some parameters were added as global class classes https://github.com/joomla/joomla-cms/pull/31570/files#diff-250b59d27f418e931b052803c0a6089439df3f1ada6db18096ec9f9e5edb095cR717-R731 .Do we need to keep these parameters or it should be reverted?

**Comment by Harmageddon** [comment]
I don't have time today, but am going to have a look at this tomorrow. On a first glance: Looks good to me, thanks for taking care of this one!

**Comment by Harmageddon** [comment]
I have tested this item :white_check_mark: successfully on 182ceb15385b842f7a956f828d6f5d6632b2b116<br /><br />Tested upgrade from 3.9.26 (with column settings) and from 4.0-beta8 (with CSS classes). Nothing seems to break. PR does a clean removal of the upgrade functionality in #31570.

@joomdonation I'd keep those global parameters, as there may be use cases for setting CSS classes globally, and I don't see any disadvantages.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33428">issues.joomla.org/tracker/joomla-cms/33428</a>.</sub>

**Comment by richard67** [comment]
> Tested upgrade from 3.9.26 (with column settings) ...

@Harmageddon Did you do that directly from 3.9.26 to 4 and not with an intermediate 3.10? That might work when using "Upload & Update" but is not officially supported. It's ok for the test here, but I thought I should spread the information that it's not the official way.

(Sorry I've first mentioned the wrong person here, so @himanshu007-creator please ignore the notification.)

**Comment by Harmageddon** [comment]
> @Harmageddon Did you do that directly from 3.9.26 to 4 and not with an intermediate 3.10? That might work when using "Upload & Update" but is not officially supported. It's ok for the test here, but I thought I should spread the information that it's not the official way.

Ah yes, you're perfectly right there. I couldn't find my old backup I used for upgrade tests, that was probably on 3.10, and just picked a new download package. Sorry for that, still it worked! :-D

**Comment by ChristineWk** [comment]
Had already successfully used this procedure J 3.10 to J 4.0 a few times ... and at that time in the course of #31570 etc.
As described here: https://www.joomla.org/announcements/release-news/5833-joomla- 4-0-0-beta7-and-joomla-3-10-alpha5.html
Unfortunately it doesn't work at the moment. Success was: Error 500 etc.

Backup today of my J 3.10 imported again.
The current status is: Version of the database schema (in #__schemas): 3.10.0-2020-08-10
Update version (in #__extensions): 3.10.0-alpha6-dev
Sorry about that. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33428">issues.joomla.org/tracker/joomla-cms/33428</a>.</sub>

**Comment by joomdonation** [comment]
I have tested this item :white_check_mark: successfully on 182ceb15385b842f7a956f828d6f5d6632b2b116<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33428">issues.joomla.org/tracker/joomla-cms/33428</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33428">issues.joomla.org/tracker/joomla-cms/33428</a>.</sub>

**Comment by Quy** [comment]
Thank you!

**Pull request merged**
