### PR TITLE
[5.2] SEF URLs: Check if SEF plugin is published

### PR DESCRIPTION
**Pull request by Hackwar**
Pull Request for Issue #44270.

### Summary of Changes
The new changes for SEF URLs check the options in the SEF plugin. If the plugin is unpublished/disabled, the plugin data is not loaded and results in notices in the output if error reporting is turned up high enough.

### Testing Instructions
Install 5.2 and set error reporting to maximum, as well as debugging to on. Unpublish the SEF system plugin.

### Actual result BEFORE applying this Pull Request
Warning: Attempt to read property "params" on array in [ROOT]libraries/src/Component/Router/Rules/MenuRules.php

### Expected result AFTER applying this Pull Request
Nothing.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
I am not up to date with 3rd party sef extensions but what if they require the core sef plugin to be disabled?

**Comment by Hackwar** [comment]
That is the goal of this PR to allow this.

**Comment by fgsw** [comment]
I have tested this item :white_check_mark: successfully on 1ac14e897d4e7960dfd9c2020bd4659d29537d50<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44283">issues.joomla.org/tracker/joomla-cms/44283</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 1ac14e897d4e7960dfd9c2020bd4659d29537d50<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44283">issues.joomla.org/tracker/joomla-cms/44283</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44283">issues.joomla.org/tracker/joomla-cms/44283</a>.</sub>

**Comment by pe7er** [comment]
Thanks @Hackwar !

**Pull request merged**
