### PR TITLE
[4.0] Wrap mod-articles-news items

### PR DESCRIPTION
**Pull request by ciar4n**
Pull Request for Issue # .

### Summary of Changes
Wraps individual mod-articles-news items to allow some kind of styling (default layout)

### Testing Instrauctions
Code Review

### Before
image

### After
image

### CODE REVIEW

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on 32f0efe9f68e74b1e4eb0cef513bd3f4d1a0fb2d<br /><br />Why the double underline: class="mod-articlesnews__item" ? Should the article class be an Option parameter?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32267">issues.joomla.org/tracker/joomla-cms/32267</a>.</sub>

**Comment by drmenzelit** [comment]
@ceford the double underline in css classes is following the BEM methodology: http://getbem.com/naming/

Which article class do you mean?

**Comment by ciar4n** [comment]
> Why the double underline: class="mod-articlesnews__item" ?

This would be typical of BEM class naming which was adopted in https://github.com/joomla/joomla-cms/pull/20147

> Should the article class be an Option parameter?

The current **Module Class** would cover all requirements for applying style to these items

**Comment by ceford** [comment]
Thanks for the info on BEM. I learned something today!

> Should the article class be an Option parameter?

What I meant was: should class="mod-articlesnews__item" be hard-coded to this name or should it be a parameter filled out by the user in the Articles - Newsflash Advanced tab. No need to answer - it was a passing thought.

**Comment by richard67** [comment]
@ciar4n Why only for the default layout (sorry if silly question)?

**Comment by ciar4n** [comment]
@richard67 The other layouts put each item as a list item which makes them manageable. It was only the default layout that had all content flat in a single div.

**Comment by richard67** [comment]
> @richard67 The other layouts put each item as a list item which makes them manageable. It was only the default layout that had all content flat in a single div.

I see. Yes, I can confirm they are all lists. Thanks for feedback.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 32f0efe9f68e74b1e4eb0cef513bd3f4d1a0fb2d<br /><br />Beside code review I've tested the default layout also in a real test and can confirm it looks the same with and without the PR.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32267">issues.joomla.org/tracker/joomla-cms/32267</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32267">issues.joomla.org/tracker/joomla-cms/32267</a>.</sub>

**Comment by Quy** [comment]
Thanks

**Comment by ciar4n** [comment]
Thank you

**Pull request merged**
