### PR TITLE
[4.1] Tiny UX improvement

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # .

### Summary of Changes

Add 2 buttons so that an admin could move from install to manage, and vice versa, without reaching fro the main menu

### Testing Instructions

Check the views Extension: install and Extensions: manage

### Actual result BEFORE applying this Pull Request

Screenshot 2021-12-29 at 12 06 10

Screenshot 2021-12-29 at 12 05 56

### Expected result AFTER applying this Pull Request

Screenshot 2021-12-29 at 12 05 26

Screenshot 2021-12-29 at 12 05 17

### Documentation Changes Required

No

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 66a62cb6b675de3a47b2e6aa6230777a01d9666e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36474">issues.joomla.org/tracker/joomla-cms/36474</a>.</sub>

**Comment by brianteeman** [comment]
Please update to match the similar functionality in languages

eg put the install button at the end and rename it Install Extensions and Manage Extensions

**Comment by dgrammatiko** [comment]
> eg put the install button at the end and rename it Install Extensions and Manage Extensions

@brianteeman  done

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 88b0be0988aa36d59636104edade82f4ad105b31<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36474">issues.joomla.org/tracker/joomla-cms/36474</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 88b0be0988aa36d59636104edade82f4ad105b31<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36474">issues.joomla.org/tracker/joomla-cms/36474</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36474">issues.joomla.org/tracker/joomla-cms/36474</a>.</sub>

**Comment by ChristineWk** [comment]
result
screen shot 2021-12-29 at 17 57 46
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36474">issues.joomla.org/tracker/joomla-cms/36474</a>.</sub>

**Comment by dgrammatiko** [comment]
@ChristineWk that's expected as per @brianteeman 's comment https://github.com/joomla/joomla-cms/pull/36474#issuecomment-1002579843

**Comment by ChristineWk** [comment]
of course I know that it was expected, so I wanted to show a successful part of it via screenshot. :-)
unfortunately there are currently i-net server problems. therefore had overlapped with rtc.

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
