### PR TITLE
[5.1] CodeMirror 6 Javascript highlighting not working

### PR DESCRIPTION
**Pull request by OctavianC**
Pull Request for Issue #43113 .

### Summary of Changes
Added an alias for 'js' so that CodeMirror understands what language package to load.

### Testing Instructions
See issue #43113 

### Actual result BEFORE applying this Pull Request
image

### Expected result AFTER applying this Pull Request
image

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on d54448f053e2ccf0dff57b9e0adb3a7e47f78127<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43114">issues.joomla.org/tracker/joomla-cms/43114</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43114">issues.joomla.org/tracker/joomla-cms/43114</a>.</sub>

**Comment by Linkedla** [comment]
image

It is working after applying the patch.
Applied Commit SHA: d54448f053

**Comment by brianteeman** [comment]
Thank you for testing - please go to https://issues.joomla.org/tracker/joomla-cms/43114 and record your test there

**Comment by Linkedla** [comment]
I have tested this item :white_check_mark: successfully on d54448f053e2ccf0dff57b9e0adb3a7e47f78127<br /><br />Tested successfully.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43114">issues.joomla.org/tracker/joomla-cms/43114</a>.</sub>

**Comment by HLeithner** [comment]
This pull request has been automatically rebased to 5.1-dev.

**Comment by LadySolveig** [comment]
Thank you @OctavianC and for the tests @Fedik @viocassel and @Linkedla !

**Pull request merged**
