### PR TITLE
[4.0] Remove title on some buttons

### PR DESCRIPTION
**Pull request by brianteeman**
The fields used for creating/editing/selecting an article etc in the menu manager have title attributes that are not needed. They don't add anything for accessibility.

image

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on afdb97e572bd21de46e97f3f7ada0eb3db9580f0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25233">issues.joomla.org/tracker/joomla-cms/25233</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on afdb97e572bd21de46e97f3f7ada0eb3db9580f0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25233">issues.joomla.org/tracker/joomla-cms/25233</a>.</sub>

**Comment by ghost** [comment]
Status "Ready To Commit".

**Comment by brianteeman** [comment]
@franz-wohlkoenig could you put the 4.0 label back please.

**Comment by zero-24** [comment]
@brianteeman the branch label is done by the tracker no manual interaction required ;)

**Comment by brianteeman** [comment]
@zero-24 I know but for some reason he removed it
image

Updating the branch triggered the bot again ;)

**Comment by zero-24** [comment]
Yes when the PR is set faster to RTC (or any other change) than the bot syncs the labels this can happen.

**Comment by ghost** [comment]
Changing Status from "Pending" > "RTC" in Issue Tracker removes this Label.

**Comment by ghost** [comment]
> PR is set faster to RTC

@zero-24 means if i wait longer to save this label-thing didn't happen?

**Comment by zero-24** [comment]
> @zero-24 means if i wait longer to save this label-thing didn't happen?

Yes. I have just done a PR that you can see that label and milestone option too: https://github.com/joomla/jissues/pull/1062

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
