### PR TITLE
[4.0] Add support to view typed password in input field

### PR DESCRIPTION
**Pull request by C-Lodder**
### Summary of Changes

This PR adds a small icon/trigger to the password input fields, allowing you to view the password you've typed in. Make life much easier for those who use very long and complex passwords

### Testing Instructions

- Apply PR
- Go to edit your profile in the backend or view the front-end login form
- Type in your password, then click the "eye" icon to the right of the input

### Notes:
- This is part 1 of the password field on forms.
- Part 2 will be removing any password confirmation fields from core as they won't be needed after this.

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :red_circle: unsuccessfully on 69e8dc37717de6b01cc0ba3bd5afeb0d172ed57b

Test on "My Profile", Backend:
Password isn't shown in Field `Password`
Password is shown in Field `Confirm Password`
### System information
4.0.0-dev
macOS Sierra, 10.12.5
Firefox 54 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17069">issues.joomla.org/tracker/joomla-cms/17069</a>.</sub>

**Comment by C-Lodder** [comment]
@franz-wohlkoenig seems fine for me.

screeny2

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 69e8dc37717de6b01cc0ba3bd5afeb0d172ed57b<br /><br />ReLogin, Browser-Cache cleared > works.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17069">issues.joomla.org/tracker/joomla-cms/17069</a>.</sub>

**Comment by C-Lodder** [comment]
@franz-wohlkoenig perfect, thanks :)

**Comment by wilsonge** [comment]
Need to fix travis

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on f7044e890e486aa174a8d0bc17a5c48a39a2b045<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17069">issues.joomla.org/tracker/joomla-cms/17069</a>.</sub>

**Comment by C-Lodder** [comment]
@wilsonge unit tests updated

**Pull request merged**
