### PR TITLE
[4.0] Allow for FA icons in toolbar buttons

### PR DESCRIPTION
**Pull request by ciar4n**
Pull Request for Issue # .

### Summary of Changes
Currently the toolbar button icons are only styled for 'icon-'. This PR allows you to also use FontAwesome classes.

### Testing Instructions
Navigate to view containing a toolbar (Content -> Articles). Inspect toolbar buttons and replace icon class (eg. icon-publish) with FontAwesome classes (fa fa-coffee). 

### Before patch
toolbar-fa1

### After patch
toolbar-fa2

### Documentation Changes Required
No

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
With or -out PR Toolbar looks like:
bildschirmfoto 2017-03-31 um 09 55 25

**Review by C-Lodder — APPROVED** [review]

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 1951ff23f29482b47feb6745c450a55d2f8a923b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15021">issues.joomla.org/tracker/joomla-cms/15021</a>.</sub>

**Comment by C-Lodder** [comment]
RTC ?

**Comment by bembelimen** [comment]
Not sure about this, why not compile/setup your fontAwesome stuff with "icon-" instead of "fa-"? Is one line in the settings. Otherwise we have to support other prefixes, too?

**Comment by ciar4n** [comment]
I hear ya. Personally I would sooner fa- over icon- simply because it is what people are more familiar with in regards to using FA. Most of FAs documentation references fa-. @C-Lodder what do you think?

**Comment by C-Lodder** [comment]
To be honest, we should be supporting both. The agreement with using FA was that we still keep BC, by mapping the styling of `icon-xxx` to the correct FA class.

As for the prefix, we can grab the variable and apply it like so:

```
[class^="icon-"],
 [class*=" icon-"],
 [class^="#{$fa-css-prefix}-"],
[class*=" #{$fa-css-prefix}-"] {
  ...
}
```

Be sure to test that as I haven't done so.

**Comment by ciar4n** [comment]
@C-Lodder Updated.. tests fine.

**Pull request merged**
