### PR TITLE
[cpanel modules] Add tooltips to dates and align

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
Pull Request for Improvement.
#### Summary of Changes

In CPanel modules:
- Adds and uniformizes tooltip (with date and hour) on dates. mod_logges, mod_latest and mod_popular.
- Uniformizes mod_logged alignment (to be like the others).

Before
image

After
image
#### Testing Instructions
1. Use joomla staging with test sample data
2. Go to CPanel check the align and the date tooltips in the 3 modules
3. Apply patch
4. Go to CPanel check the align and the date tooltips in the 3 modules

### CODE REVIEW

**Comment by brianteeman** [comment]
I am not in favour of this change. I find it very useful to see the time
that all my users logged in. This change makes that really hard to do on a
busy site with many logged in users

On 10 May 2016 at 12:15, andrepereiradasilva <notifications@github.com>
wrote:

> Pull Request for Improvement.
> Summary of Changes
>
> In CPanel modules:
>
>    - Adds and uniformizes tooltip (with date and hour) on dates.
>    mod_logges, mod_latest and mod_popular.
>    - Uniformizes mod_logged alignment (to be like the others).
>
> Before
> [image: image]
> <https://cloud.githubusercontent.com/assets/9630530/15144655/c89097b8-16a8-11e6-948c-febf3b3db1c8.png>
>
> After
> [image: image]
> <https://cloud.githubusercontent.com/assets/9630530/15144658/cc93670a-16a8-11e6-900d-ff4290c7bcbe.png>
> Testing Instructions
>
>    1. Use joomla staging with test sample data
>    2. Go to CPanel check the align and the date tooltips in the 3 modules
>    3. Apply patch
>    4. Go to CPanel check the align and the date tooltips in the 3 modules
>
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/joomla/joomla-cms/pull/10382
> Commit Summary
>
>    - mod_latest: add tooltip to date
>    - mod_logged: add tooltip to date
>    - mod_popular: add tooltip to date
>
> File Changes
>
>    - *M* administrator/modules/mod_latest/tmpl/default.php
>    <https://github.com/joomla/joomla-cms/pull/10382/files#diff-0> (4)
>    - *M* administrator/modules/mod_logged/tmpl/default.php
>    <https://github.com/joomla/joomla-cms/pull/10382/files#diff-1> (10)
>    - *M* administrator/modules/mod_popular/tmpl/default.php
>    <https://github.com/joomla/joomla-cms/pull/10382/files#diff-2> (7)
>
> Patch Links:
>
>    - https://github.com/joomla/joomla-cms/pull/10382.patch
>    - https://github.com/joomla/joomla-cms/pull/10382.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/10382>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
Also this hard codes the date format which means it can not be localised

**Comment by andrepereiradasilva** [comment]
ok i see and understand your point. will think of a better way to achieve the goals.

**Comment by andrepereiradasilva** [comment]
keeping this in standby.

**Comment by brianteeman** [comment]
I am going to close it. You can always re-open it when you have found a way to achieve your goal. Really want to stop us using the tracker as personal todo lists. It makes it hard for people to see what should be tested or now

**Comment by andrepereiradasilva** [comment]
ok

**Comment by andrepereiradasilva** [comment]
you're right

**Pull request closed without merging**
