### PR TITLE
 [5.2] sprintf as compiler optimized function

### PR DESCRIPTION
**Pull request by tkuschel**
Preparation for an update of friendsofphp/php-cs-fixer v3.59.3 to v3.64.0
A compiler optimization has been added for sprintf in PHP 8.4.
***Note:*** *php 7.x, and older php 8.x is not affected by this.*

### Summary of Changes
Replace all `sprintf` with `\sprintf` ,
`namespace {` instead of
```
namespace
{
```
### Testing Instructions
unit test with friendsofphp/php-cs-fixer v3.64.0

### Actual result BEFORE applying this Pull Request
A test with friendsofphp/php-cs-fixer v3.64.0 fails,

### Expected result AFTER applying this Pull Request
A test with friendsofphp/php-cs-fixer v3.64.0 passes.

### Link to documentations
- [X] No documentation changes for docs.joomla.org needed
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by laoneo** [comment]
Thanks, can you ad the rule to the cs config file as this should be controlled as well
https://cs.symfony.com/doc/rules/function_notation/native_function_invocation.html

**Comment by tkuschel** [comment]
Hi @laoneo, I never did that cs config file before. I would have to work for it first, with little time budget. Maybe you can show me how to do it.

**Comment by laoneo** [comment]
Its already there, in the root of the Repository

**Comment by laoneo** [comment]
Just realized that we have that already from #41427. So we are all good here. Sorry for the noise.

**Review by laoneo — APPROVED** [review]

**Review by Hackwar — APPROVED** [review]

**Comment by Hackwar** [comment]
Thank you for your contribution @tkuschel!

**Pull request merged**
