### PR TITLE
[4.0] Redo of the custom elements Alert and Tab

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # .

# WIP don't test yet

# This is a PROXY only to get human tests. The real PRs are on the other repo.

### Summary of Changes
- A refactor of these two elements as the code is nowhere near production grade
- PR on the real repo: https://github.com/joomla-projects/custom-elements/pull/162

### Testing Instructions

Check that alerts working fine. Check that tabs work fine.

### CODE REVIEW

**Comment by brianteeman** [comment]
and the real repo is where?

**Comment by dgrammatiko** [comment]
https://github.com/joomla-projects/custom-elements

**Comment by ceford** [comment]
Read some of the docs and noting interest - an alternative/replacement for Bootstrap components.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33234">issues.joomla.org/tracker/joomla-cms/33234</a>.</sub>

**Comment by dgrammatiko** [comment]
> Read some of the docs and noting interest - an alternative/replacement for Bootstrap components.

So, what did you expect? These components were created to replace the Bootstrap ones. Also, I don't really get your comment

**Comment by ceford** [comment]
I was just noting interest to monitor progress; and the similarity with bs components. Nothing more was intended - I like to follow your work.

**Comment by dgrammatiko** [comment]
Well https://github.com/joomla/joomla-cms/issues/34492#issuecomment-860043076

**Pull request closed without merging**
