### PR TITLE
Small grammatical error in message

### PR DESCRIPTION
**Pull request by chrisdavenport**
Title says it all. :-)

Just in case you didn't spot it: "effecting" should be "affecting".

### CODE REVIEW

**Comment by wilsonge** [comment]
RTC for 3.5.1

**Comment by Hils** [comment]
"...to review the changes in the robots.txt.dist file and implement **these change** in their own robots.txt file." 
Should be this change or these changes - not sure which will be appropriate here.

**Comment by brianteeman** [comment]
@Hils good spot it should be "these"

Can you create a new PR for that

**Comment by Hils** [comment]
Will do :)

**Comment by brianteeman** [comment]
RTC(again)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9413">issues.joomla.org/joomla-cms/9413</a>.</sub>

**Pull request merged**
