### PR TITLE
[4.0] Fix template preview JS error

### PR DESCRIPTION
**Pull request by Quy**
Pull Request for Issue #20492.

### Summary of Changes
Listing pages allow for multi-select except on the Templates page. This PR prevents the JS error when there are no checkboxes for multi-select.

### Testing Instructions
install 4.0-dev
login to admin
go to template manager
click templates
click the image

See #20492 for video recording of error.

### Expected result
No JS error

### Actual result
JS error

> multiselect.min.js?132339e72563fafc2a9b345f445e4d39:1 Uncaught TypeError: Cannot read property 'checked' of null

### Documentation Changes Required
none

### CODE REVIEW

**Comment by ReLater** [comment]
I have tested this item :white_check_mark: successfully on d4e2d76553838cf40312d6eb0d46bf1a795b180a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20659">issues.joomla.org/tracker/joomla-cms/20659</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on d4e2d76553838cf40312d6eb0d46bf1a795b180a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20659">issues.joomla.org/tracker/joomla-cms/20659</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20659">issues.joomla.org/tracker/joomla-cms/20659</a>.</sub>

**Review by dgrammatiko — APPROVED** [review]

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
