### PR TITLE
[4.0] Order field

### PR DESCRIPTION
**Pull request by brianteeman**
Menu items are displayed differently to plugins in the ordering field. This PR makes the display consistently and at the same time fixes a UX issue whereby the numbers displayed can become non-contigious.

### Plugin ordering (editors-xtd)
image
Note the numbers. the first is always 0 and the last is always +1 but as the numbers are displayed from the database we can easily end up with two 0 entries and nothing between 3 and 6. The numbers are not important.

### Menu item ordering
image

### Plugin ordering (editors-xtd)
image

### CODE REVIEW

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on fc8434469fae22c1429bcc79c02fbb03221b86d1<br /><br />Tested successfully in Beta6-dev of 4 January.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31850">issues.joomla.org/tracker/joomla-cms/31850</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on fc8434469fae22c1429bcc79c02fbb03221b86d1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31850">issues.joomla.org/tracker/joomla-cms/31850</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31850">issues.joomla.org/tracker/joomla-cms/31850</a>.</sub>

**Comment by ceford** [comment]
For the editors-xtd type the ordering displayed in the table, with Ordering Ascending selected, is not the same as the ordering seen when selecting one item to edit. I find that confusing!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31850">issues.joomla.org/tracker/joomla-cms/31850</a>.</sub>

**Comment by richard67** [comment]
> For the editors-xtd type the ordering displayed in the table, with Ordering Ascending selected, is not the same as the ordering seen when selecting one item to edit. I find that confusing!

@ceford Do I understand right that this issue is not related to this PR? If so: @brianteeman Do you think you can make another PR to fix that, too?

**Comment by richard67** [comment]
Thanks!

**Comment by brianteeman** [comment]
The order of the xtd-editor plugins in the editor is unrelated to the order in the plugin manager.

**Comment by brianteeman** [comment]
Thanks for merging

**Pull request merged**
