### PR TITLE
[5.3] Removing calls to legacy ->set()

### PR DESCRIPTION
**Pull request by Hackwar**
### Summary of Changes
This PR removes a series of calls to `LegacyPropertyManagement::set()` where easily possible. The method is deprecated.

### Testing Instructions
Codereview and testing numerous changes. There should be no change.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Review by rdeutz — APPROVED** [review]
can we remove the use statement?

**Comment by Hackwar** [comment]
No, since that would change the interface of the respective object and be a b/c break.

**Comment by laoneo** [comment]
Can you fix the conflicts here?

**Comment by Hackwar** [comment]
done.

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
