### PR TITLE
[Sql azure] Normalize joomla install sql file

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
### Summary of Changes

Normalizes all sql azure joomla install file.
- always use `SET IDENTITY_INSERT [#__xxxx] ON/OFF;`
- `INSERT` to `INSERT INTO`
- Quote all table names and db field names
- Always use `'` to quote string values.
- Code style
### Testing Instructions

Mainly code review. (easier to check code diff without white spaces changes) https://github.com/joomla/joomla-cms/pull/11725/files?w=1
If anyone could test an install 3.6.x would be great. Don't have sql azure to test,
### Documentation Changes Required

None.

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on d4b33d025a2dbaf60db4f13f9ad11337a270c302<br /><br />on code review still unable to test on MSSQL<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11725">issues.joomla.org/joomla-cms/11725</a>.</sub>

**Comment by waader** [comment]
I have not tested this item.<br /><br />I get this error message when installing additional languages:

[Microsoft][SQL Server Native Client 11.0][SQL Server]Cannot insert the value NULL into column 'custom_data', table 'joomla35.dbo.#__extensions'; column does not allow nulls. INSERT fails. SQL=INSERT INTO [#__extensions] ([name],[type],[element],[folder],[client_id],[enabled],[access],[protected],[manifest_cache],[params]) VALUES ('EnglishAustralia','language','en-AU','','1','1','0','0','{"name":"English (Australia)","type":"language","creationDate":"August 2016","author":"stevec4","copyright":"Copyright (C) 2005 - 2016 Open Source Matters. All rights reserved.","authorEmail":"stevec4@comcast.net","authorUrl":"www.joomla.org","version":"3.6.2.2","description":"en-AU administrator language","group":"","filename":"install"}','{}')
[Microsoft][SQL Server Native Client 11.0][SQL Server]Cannot insert the value NULL into column 'custom_data', table 'joomla35.dbo.#__extensions'; column does not allow nulls. INSERT fails. SQL=INSERT INTO [#__extensions] ([name],[type],[element],[folder],[client_id],[enabled],[access],[protected],[manifest_cache],[params]) VALUES ('Belarusian','language','be-BY','','0','1','0','0','{"name":"Belarusian","type":"language","creationDate":"2012-11-20","author":"Dennis Hermatski","copyright":"Copyright (C) 2005 - 2012 Open Source Matters. All rights reserved","authorEmail":"sirdionisiy@gmail.com","authorUrl":"www.joomla.com","version":"3.0.2","description":"be-BY site language","group":"","filename":"install"}','{}')
[Microsoft][SQL Server Native Client 11.0][SQL Server]Cannot insert the value NULL into column 'custom_data', table 'joomla35.dbo.#__extensions'; column does not allow nulls. INSERT fails. SQL=INSERT INTO [#__extensions] ([name],[type],[element],[folder],[client_id],[enabled],[access],[protected],[manifest_cache],[params]) VALUES ('Basque','language','eu-ES','','0','1','0','0','{"name":"Basque","type":"language","creationDate":"August 2016","author":"Joomla! Basque Translation Team","copyright":"Copyright (C) 2005 - 2016 Open Source Matters. All rights reserved.","authorEmail":"joomlaeuskaraz@gmail.com","authorUrl":"","version":"3.6.2.1","description":"eu-ES site language","group":"","filename":"install"}','{}')<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11725">issues.joomla.org/joomla-cms/11725</a>.</sub>

**Comment by andrepereiradasilva** [comment]
This does not seems related to this PR.
This PR does not changes that, you probably already have that issue before  thsi PR.

So you probably can't install any language right? even in backend "Install languages" right?

```
[Microsoft][SQL Server Native Client 11.0][SQL Server]
Cannot insert the value NULL into column 'custom_data', table 'joomla35.dbo.#__extensions';
column does not allow nulls.

INTO #__extensions VALUES ('EnglishAustralia','language','en-AU','','1','1','0','0','{"name":"English (Australia)","type":"language","creationDate":"August 2016","author":"stevec4","copyright":"Copyright (C) 2005 - 2016 Open Source Matters. All rights reserved.","authorEmail":"stevec4@comcast.net","authorUrl":"www.joomla.org","version":"3.6.2.2","description":"en-AU administrator language","group":"","filename":"install"}','{}')
```

@alikon any idea why this happens?

**Comment by waader** [comment]
I have tested this item :white_check_mark: successfully on d4b33d025a2dbaf60db4f13f9ad11337a270c302<br /><br />You are right! This problem existed already.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11725">issues.joomla.org/joomla-cms/11725</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11725">issues.joomla.org/joomla-cms/11725</a>.</sub>

**Comment by alikon** [comment]
@andrepereiradasilva  MSSQL is right
the extensions table field 
`[custom_data] [nvarchar](max) NOT NULL,`
is declared NOT NULL but without default

so we need to provide a value to that field as it is now in sql script  nothing is provided for that field

**Comment by andrepereiradasilva** [comment]
ok so i added the default value
https://github.com/joomla/joomla-cms/pull/11725/commits/b875501fe8f38f6e6c2f5afebe9f8da08cf579bd

because it exists in joomla.sql in postgresql
https://github.com/joomla/joomla-cms/blob/staging/installation/sql/postgresql/joomla.sql#L460

@waader @alikon please check

**Comment by alikon** [comment]
You should add the usual alter table for the update too...

**Comment by andrepereiradasilva** [comment]
ok so i reverted that change will wait for this to et merged and then will make a PR to put that right.

**Comment by csthomas** [comment]
I only remind
`[custom_data] [nvarchar](max) NOT NULL,` still does not have DEFAULT ''

**Pull request merged**
