### PR TITLE
[4.0] [plg_api-authentication_basic] Relax input filtering for credentials

### LINKED ISSUE #27243: [4.0] API login
### Steps to reproduce the issue

Create a user with:
Username: `api`
Password: `Aa1Bb2Cc3Dd4Ee5!`

Do a API call: GET {{base_path}}/api/index.php/v1/content/article

### Expected result

The List of Articles

### Actual result

```
{
    "errors": [
        {
            "title": "Forbidden"
        }
    ]
}
```

### System information (as much as possible)

Tested with Joomla_4.0.0-beta1-dev-Development-Full_Package

### Additional comments

If you use a password like "api123" it works correctly

### PR DESCRIPTION
**Pull request by SharkyKZ**
Fixes #27243.

### Summary of Changes

Use appropriate filters for username and password.

### Testing Instructions

Create a user with username and/or password containing special characters like `!`.
Try to connect to API using username and password.

### Expected result

Works.

### Actual result

HTTP 401 Unauthorized error.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on c0f3056e7c86965b27dabe92340a89c4aac4c379<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27245">issues.joomla.org/tracker/joomla-cms/27245</a>.</sub>

**Comment by Razzo1987** [comment]
I have tested this item :white_check_mark: successfully on c0f3056e7c86965b27dabe92340a89c4aac4c379<br /><br />I done a API call: GET {{base_path}}/api/index.php/v1/content/article
Now retrieve the List of Articles<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27245">issues.joomla.org/tracker/joomla-cms/27245</a>.</sub>

**Comment by SharkyKZ** [comment]
RTC.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27245">issues.joomla.org/tracker/joomla-cms/27245</a>.</sub>

**Comment by SharkyKZ** [comment]
RTC.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27245">issues.joomla.org/tracker/joomla-cms/27245</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
