### PR TITLE
Load jQuery in associations edit layout

### PR DESCRIPTION
**Pull request by laoneo**
### Summary of Changes
The [associations JS edit script](https://github.com/joomla/joomla-cms/blob/staging/media/system/js/associations-edit-uncompressed.js) needs jQuery. This pr loads jQuery in the layout itself to ensure it is always loaded. Mostly the view itself does load jQuery so nothing crashes, but when it is not the case, then a jQuery not found JS error is thrown.

Guess can be merged on review.

### Testing Instructions
Edit an article on a multilingual site and change the association.

### Expected result
All works as expected.

### Actual result
All works as expected.

### Documentation Changes Required
None.

### CODE REVIEW

**Comment by infograf768** [comment]
would it not also be necessary for the component
https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_associations/views/association/tmpl/edit.php

as the sidebyside js uses jquery ?

**Comment by laoneo** [comment]
Guess so, didn't test it yet.

**Comment by infograf768** [comment]
could you test?

**Comment by dgt41** [comment]
@infograf768 chosen is loading jQuery in that view, so no extra call needed

**Comment by infograf768** [comment]
:smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16240">issues.joomla.org/tracker/joomla-cms/16240</a>.</sub>

**Comment by wilsonge** [comment]
Merged on review

**Pull request merged**
