### PR TITLE
Sync sql install and samples files

### PR DESCRIPTION
**Pull request by csthomas**
Pull Request for Issue #13981

### Summary of Changes

* Mysql Samples: add helpful comments for graphic diff app to compare correct lines.
* Mysql Samples: I have removed IGNORE from INSERT clause and it still work.
* Postgrsql install: add comments, move down/up a few tables in order to sync with mysql install
* Postgrsql samples: add comments and sync with mysql samples
* Mssql: sync with postgresql install and samples, replace all [] quotes to "".
* Mssql: replace INSERT ... SELECT UNION ALL ... to insert with values INSERT ... VALUES (...), (...);
Why I did it: https://blog.sqlauthority.com/2008/07/02/sql-server-2008-insert-multiple-records-using-one-insert-statement-use-of-row-constructor/

### Testing Instructions
Install each sample per database, install should success. 

On postgresql and mssql please check front page and backend (specially Component lists).

### Expected result
All as before, on postgresql and mssql after sync there may be more samples/items.

### Actual result
Joomla with samles on postgresql and mssql does not work. 
Take a look at backend->Components.

### Documentation Changes Required
None

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
> Install each sample per database

how is this be done in phpMyAdmin?

**Comment by csthomas** [comment]
Install joomla with each samples. DO NOT REMOVE INSTALL FOLDER.

Install joomla with "none - sample", test and at the end remove configuration.php file.
Then refresh page and install again next one, fields should be auto filled up, but password you have to retype.

**Comment by csthomas** [comment]
Suggestion: always use the same prefix for tables and set to remove (not backup) tables on installation process.

**Comment by franz-wohlkoenig** [comment]
@csthomas will test today.

**Comment by zero-24** [comment]
@franz-wohlkoenig you need to use: https://github.com/csthomas/joomla-cms/archive/sync_sql_install_samples.zip as ` Using Joomla_3.7.0-rc1-dev-Full_Package?` does not contain the changes here in that PR 😄

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 4c32beb157bd3aa3374825b9f3e97978d026b059<br /><br />Test on MySQLi each Sample including "None".<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14223">issues.joomla.org/tracker/joomla-cms/14223</a>.</sub>

**Comment by waader** [comment]
I started testing with mssql and the testing data using current staging. Here are my findings:

Testing Data - Frontend:
- Home: An error has occurred.
- Content Modules: [Microsoft][SQL Server Native Client 11.0][SQL Server]Incorrect syntax near ')'.
- Archiv: An error has occurred.
- Similar Tags: An error has occurred.
- Popular Tags: [Microsoft][SQL Server Native Client 11.0][SQL Server]Incorrect syntax near ')'.
- Compact tagged: should show one record
- Tagged items: should show one record 

Trying to install multiple languages I get: 
[Microsoft][SQL Server Native Client 11.0][SQL Server]Cannot insert the value NULL into column 'custom_data', table 'joomla37.dbo.#__extensions'; column does not allow nulls. INSERT fails.

Backend looks pretty good.

**Comment by csthomas** [comment]
Thank for details @waader.

>    Home: An error has occurred.

Unrelated query in mod_tags_similar. You mentioned that a few times before in other PRs. Fixed in #13262.
>    Content Modules: [Microsoft][SQL Server Native Client 11.0][SQL Server]Incorrect syntax near ')'.

Unrelated. query problem solved by #13262
>    Archiv: An error has occurred.

Which link or menu?

>    Similar Tags: An error has occurred.
    Popular Tags: [Microsoft][SQL Server Native Client 11.0][SQL Server]Incorrect syntax near ')'.

Unrelated. Query syntax problem fixed in #13262
>    Compact tagged: should show one record
>    Tagged items: should show one record

I will check.

> Trying to install multiple languages I get:
[Microsoft][SQL Server Native Client 11.0][SQL Server]Cannot insert the value NULL into column 'custom_data', table 'joomla37.dbo.#__extensions'; column does not allow nulls. INSERT fails.

This PR won't fix columns types or php code on mssql.

**Comment by csthomas** [comment]
All mentioned errors are unrelated. IMO  you can mark test on sqlsrv as success.

It would be good to have one test on postgresql.

**Comment by waader** [comment]
When I try to install the Blog English (GB) Sample Data on mssql I get this message:
[Microsoft][SQL Server Native Client 11.0][SQL Server]The number of columns for each row in a table value constructor must be the same.

Installing the different data sets on postgresql went fine.

**Comment by csthomas** [comment]
I confirm, I'm working on it.

**Comment by csthomas** [comment]
Fixed. I have rebased PR in order to add changes from merged PR #13262.

**Comment by waader** [comment]
I have tested this item :white_check_mark: successfully on f8e8ee9528221856e1ba44795149e9311c06552f<br /><br />Works for mssql and postgresql. Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14223">issues.joomla.org/tracker/joomla-cms/14223</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC as there are 2 successfully Tests?

**Comment by csthomas** [comment]
It would be good to test again on mysql and maybe on postgresql for make easier decision to approvers.

**Comment by franz-wohlkoenig** [comment]
will test on mysqli

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on f8e8ee9528221856e1ba44795149e9311c06552f<br /><br />all types of sample files can be installed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14223">issues.joomla.org/tracker/joomla-cms/14223</a>.</sub>

**Comment by waader** [comment]
I have tested this item :white_check_mark: successfully on f8e8ee9528221856e1ba44795149e9311c06552f<br /><br />Works also with mysql.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14223">issues.joomla.org/tracker/joomla-cms/14223</a>.</sub>

**Pull request merged**
