### PR TITLE
Regression user notes in modal layout

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Summary of Changes

This PR solves a regression in users notes modal view.
###### Before PR

before-pr
###### After PR

after-pr
#### Testing Instructions
1. Use latest staging
2. Create some notes for a user.
3. Go to users list and click in show user notes.
4. You will see the problem described in image above.
5. Apply this patch
6. Repeat 3. and you'll see the correct notes.

### CODE REVIEW

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 8b2a77690bf512e70a32f209e9ebf3e44d22d5a9<br /><br />Confirm issue and solution.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9215">issues.joomla.org/joomla-cms/9215</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 8b2a77690bf512e70a32f209e9ebf3e44d22d5a9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9215">issues.joomla.org/joomla-cms/9215</a>.</sub>

**Comment by brianteeman** [comment]
Wondering why we have the double numbering - it looks particularly odd when it can end up being displayed as in the screenshot below

screen shot 2016-02-26 at 02 45 17

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9215">issues.joomla.org/joomla-cms/9215</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@brianteeman yeah it doesn't make sense, but that is not a regression.
IMHO, this one can be RTC.

Later i will make a PR to remove the "#X" part of each note.

**Comment by brianteeman** [comment]
thats true and normally I would say a PR should tackle one issue at a time
but ...

On 26 February 2016 at 10:09, andrepereiradasilva <notifications@github.com>
wrote:

> @brianteeman <https://github.com/brianteeman> yeah it doesn't make sense,
> but that is not a regression.
> IMHO, this one can be RTC.
>
> Later i will make a PR to remove the "#X" part of each note.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/9215#issuecomment-189203782>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by andrepereiradasilva** [comment]
lol, ok i will do it here.

**Comment by andrepereiradasilva** [comment]
ok done

image

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 70d5cee85799e66b484de18c6b7a2c2124864de8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9215">issues.joomla.org/joomla-cms/9215</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@infograf768 please test this one again.

**Comment by infograf768** [comment]
may i rather suggest to keep the id and use the class "unstyled" for the list ?

**Comment by andrepereiradasilva** [comment]
done.
image

**Comment by infograf768** [comment]
much better as no change to language string (b/c).

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on b1f7529c83043621aaac1e8d1545188fb7832ac5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9215">issues.joomla.org/joomla-cms/9215</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on b1f7529c83043621aaac1e8d1545188fb7832ac5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9215">issues.joomla.org/joomla-cms/9215</a>.</sub>

**Comment by andrepereiradasilva** [comment]
RTC?

**Comment by andrepereiradasilva** [comment]
thanks bot

**Comment by dgt41** [comment]
@andrepereiradasilva so did the bot get some AI?

**Comment by andrepereiradasilva** [comment]
don't now, but i wrote RTC and magically it appeared.

The question is if "magically" is some AI or a very very fast mantainer :)

**Comment by mbabker** [comment]
I don't remember anymore but IIRC you have to set status on the issue
tracker AND comment RTC for the label to get processed.  But there's a lot
of stuff like that happening and it's hard to keep track anymore.

**Comment by brianteeman** [comment]
Yes @mbabker is correct. I forgot to comment when I changed the status<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9215">issues.joomla.org/joomla-cms/9215</a>.</sub>

**Pull request merged**
