### PR TITLE
Lifetime validation

### PR DESCRIPTION
**Pull request by jackkum**
Pull Request for Issue #5619 .
#### Summary of Changes
- Added validator behavior
- Created client side validator for the number field
- Minified uncompressed file
#### Testing Instructions
1. Go to the Joomla administration
2. Then: System => Global Configuration => System (Tab) => Session Settings 
3. Try input in the field 'Session Lifetime' zero or negative value

You should see error (red border around and title on mouseover)

### CODE REVIEW

**Comment by jackkum** [comment]
mysql_connect(): The mysql extension is deprecated and will be removed in the future: use mysqli or PDO instead: 1x

    1x in JDatabaseDriverMysqlTest::testDropTable

/home/travis/build.sh: line 45:  3440 Segmentation fault      (core dumped) libraries/vendor/bin/phpunit --configuration travisci-phpunit.xml
:confused:

**Comment by brianteeman** [comment]
Has this been resolved elsewhere? Withthe current staging I get the red border before applying this PR<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9997">issues.joomla.org/joomla-cms/9997</a>.</sub>

**Comment by andrepereiradasilva** [comment]
this? https://github.com/joomla/joomla-cms/pull/9336

**Comment by andrepereiradasilva** [comment]
or this? https://github.com/joomla/joomla-cms/commit/3caf10182165d61d96af7092d7ca7c097a229b59

**Comment by brianteeman** [comment]
I am closing this at this time as it appears to have been resolved elsewhere and  there has been no response to the comments. It can always b reopened if that is done.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9997">issues.joomla.org/joomla-cms/9997</a>.</sub>

**Pull request closed without merging**
