### PR TITLE
[5.0] CLI install fix public folder language string

### PR DESCRIPTION
**Pull request by heelc29**
### Summary of Changes

- remove description form `public_folder`; language string not defined
- fix language string for `public_folder` in help command

### Testing Instructions

execute `php installation/joomla.php install -h`

### Actual result BEFORE applying this Pull Request

untranslated string
image

### Expected result AFTER applying this Pull Request

translated
image

### Link to documentations
Please select:
- [x] No documentation changes for docs.joomla.org needed
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Review by tecpromotion — APPROVED** [review]

**Comment by HLeithner** [comment]
I think all of them should be DESC to be consistent with the other language strings in this file

**Comment by tecpromotion** [comment]
I have tested this item :white_check_mark: successfully on 28bc032c7d803f77b8673d79932bfb6a4f46675f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41623">issues.joomla.org/tracker/joomla-cms/41623</a>.</sub>

**Comment by tecpromotion** [comment]
> I think all of them should be DESC to be consistent with the other language strings in this file

You mean

INSTL_DATABASE_ENCRYPTION_CA_LABEL_SHORT
INSTL_DATABASE_ENCRYPTION_CERT_LABEL_SHORT
INSTL_DATABASE_ENCRYPTION_CIPHER_LABEL_SHORT
INSTL_DATABASE_ENCRYPTION_KEY_LABEL_SHORT
INSTL_DATABASE_ENCRYPTION_MODE_LABEL_SHORT
INSTL_DATABASE_ENCRYPTION_VERIFY_SERVER_CERT_LABEL_SHORT

**Comment by HLeithner** [comment]
yeah ok then I only saw them where I added the new strings and was already confused whats a DESC and a DESC_SHORT is but no LABEL exists...

so happy with anything we have

**Comment by tecpromotion** [comment]
Uniform processing of the strings makes the most sense from a translation point of view, of course.

**Comment by tecpromotion** [comment]
I have tested this item :white_check_mark: successfully on bdf22010bcc5898bfe301d7d5e10719311327b96<br /><br />thanks @heelc29<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41623">issues.joomla.org/tracker/joomla-cms/41623</a>.</sub>

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on bdf22010bcc5898bfe301d7d5e10719311327b96<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41623">issues.joomla.org/tracker/joomla-cms/41623</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41623">issues.joomla.org/tracker/joomla-cms/41623</a>.</sub>

**Comment by tecpromotion** [comment]
Thanks @heelc29 and @HLeithner

**Pull request merged**
