### PR TITLE
[4.1] Modal Buttons :focus [a11y]

### PR DESCRIPTION
**Pull request by brianteeman**
When you are navigating the admin using the keyboard all the buttons should indicate when they have focus. For toolbar buttons this has been done correctly and the display of the button changes exactly the same on focus and on hover. This is the bootstrap default behaviour.

Unfortunately the buttons in the modals do not use the bootstrap defaults (_I don't know why_) and there is no styling for on focus.

This PR resolves that so the buttons in modals are styled correctly on focus. Displaying a visual indicator of the current focus is a fundamental accessibility issue.

This PR changes the scss so to test either use a prebuilt package or make sure you remember to `npm run build:css`

Open any modal and using the keyboard tab key navigate to the buttons. Before the PR you don't have any indicator when you are on a button. After the PR the button is styled exactly the same as if  you were hovering with your mouse.

### Before - keyboard focus on close button
image

### After - keyboard focus on close button
image

cc @chmst

### CODE REVIEW

**Comment by ChristineWk** [comment]
Used Prebuilt Package (installed) https://ci.joomla.org/artifacts/joomla/joomla-cms/4.1-dev/36880/downloads/51222/pr_list.xml 
but still actual result.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36880">issues.joomla.org/tracker/joomla-cms/36880</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :red_circle: unsuccessfully on 74907fda9353518c374fcc6d841812334f29f6fb<br /><br />Tested on the 4.1dev branch. Same as @ChristineWk. No focus is visible on the close button.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36880">issues.joomla.org/tracker/joomla-cms/36880</a>.</sub>

**Comment by brianteeman** [comment]
ok - will recheck - maybe something went wrong with the commit. thanks for testing so far.

**Comment by brianteeman** [comment]
Which modal were you checking? I just rechecked these two

menu2

menu1

**Comment by chmst** [comment]
I had menu - select menu item type. Firefox and edge. 
Will re-test with categories.

**Comment by drmenzelit** [comment]
I have tested this item :white_check_mark: successfully on 74907fda9353518c374fcc6d841812334f29f6fb<br /><br />Works as described<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36880">issues.joomla.org/tracker/joomla-cms/36880</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 74907fda9353518c374fcc6d841812334f29f6fb<br /><br />Test with prebuild package works as described<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36880">issues.joomla.org/tracker/joomla-cms/36880</a>.</sub>

**Comment by chmst** [comment]
No clue why it does not work on my dev environment with npm. Will have ru rebuild my local repo.

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36880">issues.joomla.org/tracker/joomla-cms/36880</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Comment by brianteeman** [comment]
Thank you - I hope the other RTC fixes will be merged as well.

**Pull request merged**
