### PR TITLE
[com_menus] Showon (show page heading in component config)

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Summary of Changes

Just one more showon in com_menus components config.
###### Yes selected

image
###### No selected

image
#### Testing Instructions

Code review, or:
1. Apply patch
2, Menus -> Options
3. Test Yes/No

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on e95a2dfbb9fe486c954efc694f24b6f3b40639e9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10226">issues.joomla.org/joomla-cms/10226</a>.</sub>

**Comment by pe7er** [comment]
I have tested this item :white_check_mark: successfully on e95a2dfbb9fe486c954efc694f24b6f3b40639e9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10226">issues.joomla.org/joomla-cms/10226</a>.</sub>

**Comment by andrepereiradasilva** [comment]
thanks for testing @pe7er @brianteeman !

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10226">issues.joomla.org/joomla-cms/10226</a>.</sub>

**Pull request merged**
