### PR TITLE
[5.0][RFC] Upgrade to bs53 (nightly) + new feature `prefers_color_scheme`

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # .

### Summary of Changes

- Upgrade to BS 5.3
- Import my own theme switcher (just for the demo)
- Patch tinyMCE to support switching themes (this needs some PHP code on picking up the override themes and a decision on the convention, I just went with the `-dark` but maybe it's not ideal)
- Patched com_users to add a new a11y field `prefers_color_scheme` with possible values: `null`, `dark`, `light` and also created a JSON endpoint so that the toggler could sync the actual user state with the DB value.
- Patched the Atum template to respect the user setting above (or fallback to light, this probably needs an option on the template level)
- At the moment there is no way to listen for OS changes and adapt but it's an easy addition

And here's a little demo:

https://user-images.githubusercontent.com/3889375/207887169-4dfd1e97-20f5-4a19-83b8-2b2f2600a052.mp4
 

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by dgrammatiko** [comment]
@HLeithner could you sync the v5.0 branch so there would be an installable package? I would like to have some feedback from people here and having an installable zip would help. Thanks

**Comment by HLeithner** [comment]
> @HLeithner could you sync the v5.0 branch so there would be an installable package? I would like to have some feedback from people here and having an installable zip would help. Thanks

done

**Comment by Bond97** [comment]
Prebuilt zip package is unable to download.
изображение
изображение

**Comment by HLeithner** [comment]
I will have a look what's wrong with the build script.

**Comment by dgrammatiko** [comment]
@nikosdion did you just reviewed the code without actually testing it?

So couple of quick answers here:
- `prefers-colour-scheme` by definition **is** an accessibility option: https://www.w3.org/TR/css-color-adjust-1/ 
- The solution for the `prefers-colour-scheme` **DERIVES** from the work the Bootstrap people did, I'm not implementing something **my way** as you keep repeating and contrary to what you have done in your PR...
- So much JS: actually for tinyMCE, which **IS** a Client Side Render App, we already use JS to render the app, what I did was wrap the render parts to a function that can be called whenever the MeqiaQuery event is fired (can listen to the actual event or a propagated one). Same goes for Codemirror, the reason I didn't touched it is plain simple: the code needs to be updated to the latest major version so, the changes would have to be redone for that version (so I left it for the own Codemirror major update PR)
- There is no need for JS: that's **IF** you can assure that none of the pages have any CSR apps (tinyMCE, CM, etc) but since the implementation affects the backend which is **requiring** JS by default, listening for the event in JS sounds the best option. The other is to refresh the page, which is not what users expect in 2023 for some client side functionality (and neither should be an acceptable solution for the project)...

**Comment by dgrammatiko** [comment]
FWIW @wilsonge already created the joomla.org template that is using the same approach as I did here (with the only exception that this PR due to the early alpha version of Bootstrap is not supporting the CSS media query for automatically switching the themes but that was fixed upstream already) and could be viewed [here](https://developer.joomla.org)

This PR still contains a lot of the required changes, although the [Muta template](https://muta.dgrammatiko.dev) (once updated to the latest Bootstrap) would be an easier path to upgrade the Atum template. The only part that might be worth keeping from this PR is the way the switcher directly saves the state of the user to the DB (maybe creating a theme switcher module is a better fit)

**Pull request closed without merging**
