### PR TITLE
[4.0] Views UI overflow fixed.

### PR DESCRIPTION
**Pull request by ThisIsFaar**
(Updated Pull Request of #34387)

Pull Request for Issue #32820 .

Summary of Changes
Views overflow fixed, now any number of columns can be added without worsening UI.

Before Fix
Before

After Fix
After

### CODE REVIEW

**Comment by brianteeman** [comment]
image

Source https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar

**Comment by ThisIsFaar** [comment]
> image
> 
> Source https://developer.mozilla.org/en-US/docs/Web/CSS/::-webkit-scrollbar

compatibility issues for `::-webkit-scrollbar` found in firefox, internet explorer.

image


**So for firefox, IE:-**


image

**Mozilla Testing✔**


mozilla firefox

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 9d3a5a0f484744564bc9124d9181a33da8444483<br /><br />Test views of 
- articles, 
- categories, 
- featured articles, 
- fields
- modules
- banners + categories + clients
- contacts + categories + fields
- feeds + categories
- smart search + index + content maps
- tags
- users + fields 
- templates

System:
- database
- extensions
- languages
- content languages
- plugins
- redirects
- update sites
- user permissions > settings<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34426">issues.joomla.org/tracker/joomla-cms/34426</a>.</sub>

**Comment by Fedik** [comment]
The fix looks a bit strange, why do you hide scrollbars?

**Comment by ThisIsFaar** [comment]
> The fix looks a bit strange, why do you hide scrollbars?

because I was told to hide, check out some last comments of the conversation from the issue  #34387

**Comment by Fedik** [comment]
okay, and do you see why did you got scrollbars that you have to hide? 

please looks there https://developer.mozilla.org/en-US/docs/Web/CSS/overflow

**Comment by Fedik** [comment]
Remove `scrollbar-width` stuff and  `.container-main::-webkit-scrollbar`.
And use `overflow:auto;` instead of `scroll`.

**Comment by ThisIsFaar** [comment]
hello @Fedik, overflow auto-added. please test and verify

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on 5b7ccc676fb0569b249278069564a2de74a3bdc2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34426">issues.joomla.org/tracker/joomla-cms/34426</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 5b7ccc676fb0569b249278069564a2de74a3bdc2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34426">issues.joomla.org/tracker/joomla-cms/34426</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34426">issues.joomla.org/tracker/joomla-cms/34426</a>.</sub>

**Comment by bembelimen** [comment]
Thank you!

**Comment by Quy** [comment]
See #34793 for regression.

**Pull request merged**
