### PR TITLE
[com_categories] add searchtools to modal layout and solves bugs

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Description

This PR adds searchtools to com_categories modal layout categories view.

Also, in normal layout:
- correct bug: the modal on mobile xs show a column without title.
- correct bug: ordering the view for Association doesn't add the arrow icon (removed ordering in this column).
- improves responsive visual (mobile/tablet/desktop)
- solves other minor graphical issues.
- minor code style improvements
###### Before PR (modal)

before-pr
###### After PR  (modal)

after-pr
#### How to test

Normal view:
1. Install latest staging and apply this patch
2. Go to Content -> Categories
3. Check if search, filters, ordering and pagination are working properly
4. Test on mobile and tablet (ex: reduce browser width)

Modal view:
1. Enable language associations.
2. Create some categories in several languages.
3. Edit one of those categories and go to "Associations" tab and click on "Select" on any language.
4. Check if search, filters, ordering and pagination are working properly in modal.
5. Test on mobile and tablet (ex: reduce browser width)

Should be also tested in other extensions that use categories (ex: User Notes, Contacts, Banners and News Feeds)

### CODE REVIEW

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 4ce7fae82eb331944f9e2870b272d195c48a260d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9208">issues.joomla.org/joomla-cms/9208</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 4ce7fae82eb331944f9e2870b272d195c48a260d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9208">issues.joomla.org/joomla-cms/9208</a>.</sub>

**Comment by brianteeman** [comment]
RTC - thanks once again<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9208">issues.joomla.org/joomla-cms/9208</a>.</sub>

**Comment by rdeutz** [comment]
@andrepereiradasilva could you have a look at the merge conflicts, thanks.

**Comment by andrepereiradasilva** [comment]
conflicts fixed.
@brianteeman can you remove the Unit tests label again? sorry

**Pull request merged**
