### PR TITLE
[4.0] rules field inline style

### PR DESCRIPTION
**Pull request by brianteeman**
This PR replaces the inline styles used for the permissions with classes. This replacement was done everywhere but it looks like the change was missed here.

There is no visible change as the widths are the same

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 30b22b8f31416fc7d583e5f74e489c747f944f23<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32226">issues.joomla.org/tracker/joomla-cms/32226</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 30b22b8f31416fc7d583e5f74e489c747f944f23<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32226">issues.joomla.org/tracker/joomla-cms/32226</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32226">issues.joomla.org/tracker/joomla-cms/32226</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thx

**Pull request merged**
