### PR TITLE
[4] Cleanup comments to comply with coding standards

### PR DESCRIPTION
**Pull request by PhilETaylor**
Code review

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 897f6235ab360ee257153352c2ee00263cdbdf81<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35141">issues.joomla.org/tracker/joomla-cms/35141</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 897f6235ab360ee257153352c2ee00263cdbdf81<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35141">issues.joomla.org/tracker/joomla-cms/35141</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35141">issues.joomla.org/tracker/joomla-cms/35141</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
