### PR TITLE
WIP:autoloading router fix

### PR DESCRIPTION
**Pull request by alex7r**
Don't use autoloader if you want to include 'router.php' manually

### Summary of Changes
Excluding router autoloader as Joomla have no in itself.

### Testing Instructions

Issues can appear on case insensitive file systems as autoloader can try to load 'Router.php' according to passed 'ComponentRouter'.
If file would be found but without class in it there is gonna be Fatal error as Joomla requires 'router.php'.
And on case insensitive system it will lead to file loaded twice.

### CODE REVIEW

**Comment by alex7r** [comment]
Can somebody explain why build is failed?

**Comment by photodude** [comment]
Follow the link to the tests on travis then look at one of the failed versions such as this link
https://travis-ci.org/joomla/joomla-cms/jobs/195243081

```php
1) JRouterSiteTest::testGetComponentRouter
Failed asserting that JComponentRouterLegacy Object (...) is an instance of class "SearchRouter".
/home/travis/build/joomla/joomla-cms/tests/unit/suites/libraries/cms/router/JRouterSiteTest.php:1347
```

Seems something in your change has broken the code result of the object being an instance of class "SearchRouter".

**Comment by alex7r** [comment]
@photodude Yes, but by what means? 

It's just it's modification inside method and is not causing SearchRouter not to load...

**Comment by photodude** [comment]
Try some general Unit testing debugging on Travis (or just do the same in your local from the command line)

1. set up Travis to test your Repo of Joomla CMS (sign in to Travis with github and set it to test your fork)
2. duplicate your branch
3. in your duplicate branch Try doing a var_dump in testGetComponentRouter() to see what the object actually is (or if there is even an object)
4. push to github (commit on github) to start a travis build to run the unit tests and see if you are getting what you expect in the object

**Comment by franz-wohlkoenig** [comment]
@alex7r can you please explain how to test this PR?

**Comment by alex7r** [comment]
It's really isn't ready for tests yet as I've ended up with tests fail that was unclear to me and seems that time I had no moment to investigate this. So It's marked as work in progress.

I will add test instructions and common used way to reproduce as soon as possible.

**Comment by franz-wohlkoenig** [comment]
@alex7r now i know what "WIP" means.

**Comment by photodude** [comment]
>It's just it's modification inside method and is not causing SearchRouter not to load...

@alex7r, It's how the unit test tests this method see this
https://github.com/joomla/joomla-cms/blob/master/tests/unit/suites/libraries/cms/router/JRouterSiteTest.php#L1319-L1355

**Comment by brianteeman** [comment]
It has been over six months the since this wip pr was created/updated . I am closing this at this time. It can always be reopened when updated.

**Comment by ghost** [comment]
@brianteeman close Issue?

**Comment by alex7r** [comment]
Seems like it more 3rd party issue than the Joomla after deep testing, so for now let's ignore this.

**Pull request closed without merging**
