### PR TITLE
[5.1] Guided Tours button

### PR DESCRIPTION
**Pull request by brianteeman**
### Summary of Changes
Changes the button class on the count of the steps in a guided tour so that it is the same as the counts in com_categories.

### Expected result AFTER applying this Pull Request
image

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Review by wilsonge — APPROVED** [review]

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 9be4e0c603eb04d7bec99f326078182a6200178d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43120">issues.joomla.org/tracker/joomla-cms/43120</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 9be4e0c603eb04d7bec99f326078182a6200178d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43120">issues.joomla.org/tracker/joomla-cms/43120</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43120">issues.joomla.org/tracker/joomla-cms/43120</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
