### PR TITLE
[3] s/cachtimeout/cachetimeout

### PR DESCRIPTION
**Pull request by PhilETaylor**
[3] s/cachtimeout/cachetimeout

### CODE REVIEW

**Review by tecpromotion — APPROVED** [review]

**Comment by tecpromotion** [comment]
I have tested this item :white_check_mark: successfully on 0503d296bc56cd34bfff8526764443d849ff336c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35348">issues.joomla.org/tracker/joomla-cms/35348</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 0503d296bc56cd34bfff8526764443d849ff336c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35348">issues.joomla.org/tracker/joomla-cms/35348</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35348">issues.joomla.org/tracker/joomla-cms/35348</a>.</sub>

**Comment by zero-24** [comment]
Merging thanks

**Pull request merged**
