### PR TITLE
[4.3] joomla alert icons

### PR DESCRIPTION
**Pull request by brianteeman**
It always bugs me that the icon and text in the alert are off-center. (and someone else because there was an issue in the past but I cant find it now).

This simple PR sets the correct line height which re-centers the icon which I assume was the original intent based on the original css and the bootstrap alert it is inspired by.

To test you will need to either use a prebuilt package or apply the pr and `npm run build:css`

## Before
image

## After
image

### Link to documentations
Please select:
- [x] No documentation changes for docs.joomla.org needed
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by rachelwalraven** [comment]
I have tested this item :white_check_mark: successfully on 8489df22e21eda7c3aa9996340036329d6720185<br /><br />On Joomla 4.4.dev with php 8.1.22<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39312">issues.joomla.org/tracker/joomla-cms/39312</a>.</sub>

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on 8489df22e21eda7c3aa9996340036329d6720185<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39312">issues.joomla.org/tracker/joomla-cms/39312</a>.</sub>

**Comment by RickR2H** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39312">issues.joomla.org/tracker/joomla-cms/39312</a>.</sub>

**Comment by obuisard** [comment]
Thank you Brian @brianteeman !

**Pull request merged**
