### PR TITLE
User Profile validation grammar

### PR DESCRIPTION
**Pull request by brianteeman**
Small grammar correction

> PLG_USER_PROFILE_ERROR_INVALID_DOB="The date of birth you entered is invalid. Please enter valid date."

==>

> PLG_USER_PROFILE_ERROR_INVALID_DOB="The date of birth you entered is invalid. Please enter a valid date."

### CODE REVIEW

**Comment by MATsxm** [comment]
I have tested this item :white_check_mark: successfully on 4891d1eb91bec787998877e412b14234719b5928<br /><br />on review - Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9505">issues.joomla.org/joomla-cms/9505</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@brianteeman it seems you also changed punnycode.js?

**Comment by brianteeman** [comment]
yes just spotted that - its a corruption in my fork - fixing it

On 21 March 2016 at 14:53, andrepereiradasilva <notifications@github.com>
wrote:

> @brianteeman <https://github.com/brianteeman> it seems you also changed
> punnycode.js?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/9505#issuecomment-199324221>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
The extra punycode file has been removed - thanks @wilsonge

**Comment by MATsxm** [comment]
I have tested this item :white_check_mark: successfully on 588d71ac33bd0fd3ee8f829905ff189fd5d66677<br /><br />Don't know if I have to "test" it again but, success on review - thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9505">issues.joomla.org/joomla-cms/9505</a>.</sub>

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 588d71ac33bd0fd3ee8f829905ff189fd5d66677<br /><br />Tested by review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9505">issues.joomla.org/joomla-cms/9505</a>.</sub>

**Comment by brianteeman** [comment]
RTC - thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9505">issues.joomla.org/joomla-cms/9505</a>.</sub>

**Pull request merged**
