### PR TITLE
[4.0] Set color for text and links in position topbar

### PR DESCRIPTION
**Pull request by drmenzelit**
Pull Request for Issue #33388  .

### Summary of Changes
Defined color for content inside position topbar.

### Testing Instructions
Create a custom module in position topbar, with text and a link

### Actual result BEFORE applying this Pull Request
Text and link not discernible 

### Expected result AFTER applying this Pull Request
Text and link are white

### CODE REVIEW

**Comment by infograf768** [comment]
so simple...

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 849e3b61ac093d114009463e079d2b39615c2613<br /><br />Thanks @drmenzelit <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33394">issues.joomla.org/tracker/joomla-cms/33394</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 849e3b61ac093d114009463e079d2b39615c2613<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33394">issues.joomla.org/tracker/joomla-cms/33394</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33394">issues.joomla.org/tracker/joomla-cms/33394</a>.</sub>

**Comment by Quy** [comment]
Thanks

**Pull request merged**
