### PR TITLE
[4.0] Download key merge error

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #33699

### Summary of Changes
Merge error from j3

### Testing Instructions
Install an extension that uses a download key

### Before
image

### After
image

### CODE REVIEW

**Comment by Abernyte-Git** [comment]
I have tested this item :white_check_mark: successfully on 458a17c27e615fc86de0f199695aacc26c0bb081<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33705">issues.joomla.org/tracker/joomla-cms/33705</a>.</sub>

**Comment by PhilETaylor** [comment]
I have tested this item :white_check_mark: successfully on 458a17c27e615fc86de0f199695aacc26c0bb081<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33705">issues.joomla.org/tracker/joomla-cms/33705</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33705">issues.joomla.org/tracker/joomla-cms/33705</a>.</sub>

**Comment by richard67** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
