### PR TITLE
Rebuild coding standards ruleset and eliminate sniffs in favor of standards

### PR DESCRIPTION
**Pull request by photodude**
This brings in some of the changes from the [Joomla coding standards](https://github.com/joomla/coding-standards)
- https://github.com/joomla/coding-standards/pull/99

and some of suggested changes from the Joomla coding standard
- https://github.com/joomla/coding-standards/issues/104

A number of temporary exclude patterns were added following the pattern currently established, these should be eliminated as the coding standard deviations are corrected.

These changes build a foundation to facilitate a move to PHPCS 2.x

### CODE REVIEW

**Comment by photodude** [comment]
@zero-24 Should this PR get the "Code Style" label too?

**Comment by zero-24** [comment]
@photodude this has the label already :smile:

**Comment by photodude** [comment]
@zero-24   I see `Unit/System Tests` and `PR-staging` but I don't see `Code Style` :squirrel:

**Comment by zero-24** [comment]
Woops my eyes only read what they expect :smile: 

To answer your question

>@zero-24 Should this PR get the "Code Style" label too?

We label PRs that fix only codestyle issues with `Code Style`. This PR updates the tests for codestyle so it has the `Unit/System Tests` label :smile:

**Comment by photodude** [comment]
@zero-24 Thanks for the clarification

**Comment by javigomez** [comment]
Thanks very much @photodude for working on this :smile:

**Comment by photodude** [comment]
@javigomez you're welcome. It looked like a good place to get my feet really wet with the the project. Still a lot to do to our custom sniffs up to get up to speed and running with PHPCS-2. So far the custom commenting sniffs are still failing in my test branch, https://github.com/photodude/joomla-cms/tree/PHPCS-2

**Comment by photodude** [comment]
I have rebased this PR to the current Stagging and fixed the merge conflicts so this can be reconsidered.

The PHPCS checks are failing since this PR is more accurately finding the code issues. As such, it looks like I need to adjust more of the exclusion rules to temporarily account for the existing failures.

**Comment by photodude** [comment]
@javigomez @zero-24 @mbabker @wilsonge 

This PR should now be in a state ready for review and consideration.

**Comment by wilsonge** [comment]
Can you ping me on this as soon as 3.5 ships. Moving to PHPCS 2 is rapidly rising up my priority list and would love to get this into 3.5.1!

**Comment by photodude** [comment]
Sure, But I do want to be clear _this PR doesn't make the move to PHPCS 2 yet_. This just cleans up the existing PHPCS 1.5 standards following what was done for the draft of the coding standards for PHPCS 2.

There is a [Draft for the full Joomla Coding standard running PHPCS 2](https://github.com/joomla/coding-standards/pull/109), it does need some additional work to fix some consistency issues.

There is also a [Draft version for composer based install](https://github.com/joomla/coding-standards/pull/122) that builds on the Work done for the [Draft for the full Joomla Coding standard running PHPCS 2](https://github.com/joomla/coding-standards/pull/109) 

So Ideally the [Draft for the full Joomla Coding standard running PHPCS 2](https://github.com/joomla/coding-standards/pull/109) should be completed and then brought over to the CMS either directly or via composer

**Comment by mbabker** [comment]
Just on a quick glance, things seem fine here.  :+1:

**Comment by brianteeman** [comment]
Can we get this merged? @wilsonge its not something that can really be tested at the CMS level<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6956">issues.joomla.org/joomla-cms/6956</a>.</sub>

**Comment by wilsonge** [comment]
@photodude can you fix the conflicts please? Let's get this show on the road :)

**Comment by photodude** [comment]
@wilsonge Is it worth fixing this PR? Would it be better to just put the effort into finishing the [Draft for the full Joomla Coding standard running PHPCS2](https://github.com/joomla/coding-standards/pull/109) and bring that in with composer?

**Comment by photodude** [comment]
@wilsonge I have fixed the merge conflicts. This PHPCS1.5.x improvement is again ready for consideration.

I do feel that effort should go into finishing the [PR for running PHPCS2](https://github.com/joomla/coding-standards/pull/109) and bring that in with composer. (The Full PHPCS2 version mostly needs testing and validation of the fixers) 

In any case, this PR is an improvement in the PHPCS1.5.x code standards for the CMS, and will be beneficial until the PHPCS2.x version is ready.

**Comment by wilsonge** [comment]
At a quick look over this looks good. But going to go through over the weekend to assure myself we aren't loosing any checks here :)

**Comment by wilsonge** [comment]
Was easier than i thought to go through everything. Nice work :) Look forward to sitting down and trying to sort out v2

**Pull request merged**
