### PR TITLE
Fix background on loading joomlaupdate

### PR DESCRIPTION
**Pull request by 810**
#### Issue

When you install the update package you see a spinner with a background, only
the height and weight are wrong
#### Test instructions

•Go to Components > Joomla Update, Select "Upload & Update" tab and send a big file (any file with 1MB, for instance, works). You'll notice the white layer with joomla logo it's cropped (not full height). Press Cancel on next screen.

or use developer tools to disable  `display:none;` class

### CODE REVIEW

**Comment by 810** [comment]
maybe this one can be merged by code review. Same as https://github.com/joomla/joomla-cms/pull/10343

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 11c575b6e6d3287ac4f0965391dc3963ae20d88b<br /><br />Since the test instructions are missing this is what i did.

- Go to Components > Joomla Update, Select "Upload & Update" tab and send a big file (any file works).
 You'll notice the white layer with joomla logo it's cropped (not full height). Press Cancel on next screen.
- Apply this patch repeat the same process. Now ok.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10392">issues.joomla.org/joomla-cms/10392</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@810 you should review the description.

**Comment by 810** [comment]
@andrepereiradasilva updated

**Comment by andrepereiradasilva** [comment]
"When you install a component" ? this is joomla update :)

**Comment by roland-d** [comment]
I have tested this item :white_check_mark: successfully on 49bc345cbf0eafc4ab2f5c6e3b120599e9932c1e<br /><br />First using the updater only the top part is blurred with the logo, after applying the patch, the full screen is blurred with the logo.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10392">issues.joomla.org/joomla-cms/10392</a>.</sub>

**Comment by C-Lodder** [comment]
I really don't think we should be using jQuery to apply styling to the `#loading` element. It would be better to simply add a class, then use CSS for the styling

**Comment by C-Lodder** [comment]
Please also test on mobile. The `top` position is too big

**Comment by 810** [comment]
@C-Lodder 

@andrepereiradasilva has started to do this way: https://github.com/joomla/joomla-cms/pull/10396

Only we need a solution for spinning on IE/Edge

**Comment by brianteeman** [comment]
Is this ready for being merged or is there an update coming?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10392">issues.joomla.org/joomla-cms/10392</a>.</sub>

**Comment by sandstorm871** [comment]
I have tested this item :white_check_mark: successfully on 49bc345cbf0eafc4ab2f5c6e3b120599e9932c1e<br /><br />As with the previous test this is what I did;

Went to Components > Joomla Update, Select "Upload & Update" tab and attached a big file. _Took screenshot to prove issue_

Applied patch & repeated the process & now all OK _Again proved with screenshot as the spinner was showing up fast_<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10392">issues.joomla.org/joomla-cms/10392</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10392">issues.joomla.org/joomla-cms/10392</a>.</sub>

**Comment by roland-d** [comment]
Thanks everybody<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10392">issues.joomla.org/joomla-cms/10392</a>.</sub>

**Pull request merged**
