### PR TITLE
Use unicode rather than general encoding

### PR DESCRIPTION
**Pull request by wilsonge**
#### Summary of Changes

This changes the utf8mb4 general encoding to uft8mb4 unicode encoding - it is generally encouraged over general encoding because it sorts better in foreign languages (see http://stackoverflow.com/a/766996 for example)
#### Testing Instructions

This shouldn't affect either installation or upgrading from a previous version of Joomla.

### CODE REVIEW

**Comment by richard67** [comment]
Ah, just opened #9245 for the same issue. My code is already ok.

Question: What about init tests?

I found "utf8_general_ci" in following files:

tests\unit\suites\database\driver\mysql\JDatabaseDriverMysqlTest.php:           'utf8_general_ci',
tests\unit\suites\database\driver\mysql\JDatabaseExporterMysqlTest.php:         'Collation' => 'utf8_general_ci',
tests\unit\suites\database\driver\mysql\JDatabaseImporterMysqlTest.php:         'Collation' => 'utf8_general_ci',
tests\unit\suites\database\driver\mysqli\JDatabaseDriverMysqliTest.php:         $this->equalTo('utf8_general_ci'),
tests\unit\suites\database\driver\mysqli\JDatabaseExporterMysqliTest.php:       'Collation' => 'utf8_general_ci',
tests\unit\suites\database\driver\mysqli\JDatabaseImporterMysqliTest.php:       'Collation' => 'utf8_general_ci',
tests\unit\suites\database\driver\pdomysql\JDatabaseDriverPdomysqlTest.php:     $this->equalTo('utf8_general_ci'),
tests\unit\suites\database\driver\pdomysql\JDatabaseExporterPdomysqlTest.php:   'Collation' => 'utf8_general_ci',
tests\unit\suites\database\driver\pdomysql\JDatabaseImporterPdomysqlTest.php:   'Collation' => 'utf8_general_ci',
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9246">issues.joomla.org/joomla-cms/9246</a>.</sub>

**Comment by richard67** [comment]
And if we use yours, not forget to change the create table statement I have added to the installer's database model, and this one is still created as utf8_ ..., not as utf8mb4, same as my new update sql, see my files in PR #9245

**Comment by wilsonge** [comment]
We'll use yours

**Comment by richard67** [comment]
And what shall we do with the unit tests?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9246">issues.joomla.org/joomla-cms/9246</a>.</sub>

**Comment by richard67** [comment]
Does the database used for those support utf8mb4?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9246">issues.joomla.org/joomla-cms/9246</a>.</sub>

**Comment by wilsonge** [comment]
We use SQLite for the unit tests. This Drupal issue suggests that it is supported https://www.drupal.org/node/1314214

**Comment by richard67** [comment]
Does it mean we should change the unit tests, too, to either utf8mb4_**unicode**_ci?

And if so, in this or in a new PR?

Or leave them untouched because they just check what they created before themselves, e.g. test tables, so what Joomla! Core tables normally have is not relevant for them?

I did not look into them yet and also not know anything about Joomla!'s unit tests.

**Comment by mbabker** [comment]
The MySQL servers on Jenkins and Travis should be running MySQL 5.5 so for
MySQL specific tests it should be safe to change.  Basically only the
database driver tests should still be using MySQL connections.  Everything
else in the unit test suite should be using a SQLite in-memory database
that's set up when the tests start and goes away when it ends.

Presumably, the tests should validate both utf8 and utf8mb4 configurations
at some point.

**Comment by wilsonge** [comment]
The problem is the filter runs based on whether the database supports utf8mb4. Not whether they are actually set up with that configuration or not... :(

**Comment by richard67** [comment]
Oh my god ... gets too complicated for me ... have no knowledge about unit testing of Joomla! ... I think I am out here ... all I hope is that our recent fixes for unicode collations and utf8mb4 not break any unit tests.

**Pull request closed without merging**
