### PR TITLE
[4.3] Update com_users.ini

### PR DESCRIPTION
**Pull request by brianteeman**
Quick cosmetic change to the com_users list as seen in the screenshots below. 

I have made this against 4.3 so that we can quickly address it now and then hopefully the entire view can be reimagined for j5.

### Actual result BEFORE applying this Pull Request
image

### Expected result AFTER applying this Pull Request
image

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 9010162f4d539c497e72b458fd9b8568f9fd46c9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40698">issues.joomla.org/tracker/joomla-cms/40698</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40698">issues.joomla.org/tracker/joomla-cms/40698</a>.</sub>

**Comment by obuisard** [comment]
Thank you Brian @brianteeman for the PR!

**Comment by brianteeman** [comment]
thanks for merging this temp fix

**Pull request merged**
