### PR TITLE
[com_fields] Update default_custom.php

### PR DESCRIPTION
**Pull request by coolcat-creations**
Change fields to jcfields like it has to be

### Summary of Changes
Changed $this->data->fields to $this->data->jcfields, because otherwise the intended mapping of the fieldname wouldn´t work otherwise.

### Testing Instructions
Create an override of default_custom.php
Add another Field at the bottom with 
`<?php echo $customFields['fieldname']->value; ?>`
Where fieldname has to have the fieldname...

### CODE REVIEW

**Review by laoneo — APPROVED** [review]

**Comment by coolcat-creations** [comment]
Can someone test this, actually this seemed to be just forgotten when changing alias to name and fields to jcfields...

**Comment by Quy** [comment]
@coolcat-creations I did not follow your testing instructions, however, it fixed the following. Is this PR related to this issue?

## Before:
profile-before

## After:
profile-after

**Comment by coolcat-creations** [comment]
@Quy I don´t know if that is fixed by my PR because normally the field would not be shown at all  before. But i see the lable is shown there. Maybe just follow the instructions too and mark it as tested :) Would be great! It´s actually a logical change/bugfix because the name fields was changed to jc fields in the development process and this one was forgotten.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 84a03403add96c8e6cb7fd5ee232c81f8c6c5342<br /><br />In the revised file, I added a `var_dump($tmp)`. Before the change, empty array. After the change, an array of the custom fields.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16028">issues.joomla.org/tracker/joomla-cms/16028</a>.</sub>

**Comment by Quy** [comment]
@franz-wohlkoenig Can this be RTC? It has 1 successful test and the developer of the custom fields has approved it.

**Comment by laoneo** [comment]
I have tested this item :white_check_mark: successfully on 84a03403add96c8e6cb7fd5ee232c81f8c6c5342<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16028">issues.joomla.org/tracker/joomla-cms/16028</a>.</sub>

**Comment by laoneo** [comment]
Now you have your second test. But the branch needs to fix a merge conflict.

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Pull request merged**
