### PR TITLE
[4.0] template-rtl codestyle

### PR DESCRIPTION
**Pull request by brianteeman**
The scc-lint is not running :(

This PR fixes as many issues as I can according to our codestyle rules found in scss-lint.yml

Code review and check scss compiles

Feel free to fix other files

### CODE REVIEW

**Comment by C-Lodder** [comment]
How are you trying to run the linter?

**Comment by brianteeman** [comment]
these changes were made by running the linter locally and then following the reports

**Comment by brianteeman** [comment]
> The scc-lint is not running :(

I meant its not running on pull requests see #26800

**Comment by C-Lodder** [comment]
Oh Hound. Hmm I'll try and look into this

**Comment by brianteeman** [comment]
Thanks - I would really appreciate it as my local lint report is humungous

**Comment by C-Lodder** [comment]
@brianteeman `ROOT/scss-lint.yml`

Replace:

```
scss_files:
  "administrator/components/com_media/resources/**/*.scss"
  "administrator/templates/**/*.scss"
  "build/media_source/**/*.scss"
  "templates/**/*.scss"
```

with:

```
scss_files: [
  "administrator/components/com_media/resources/**/*.scss",
  "administrator/templates/**/*.scss",
  "build/media_source/**/*.scss",
  "templates/**/*.scss"
]
```

You'll probably want to undo all your changes in this PR though as they go against the linter rules :)

**Comment by C-Lodder** [comment]
The linter wasn't actualy working at all. It threw an error due to an invalid YML file on my fork but doesn't appear to do so on here for some reason.

**Pull request closed without merging**
