### PR TITLE
Fix ordering of language strings

### PR DESCRIPTION
**Pull request by Bakual**
Pull Request for Issue https://crowdin.com/translate/joomla-cms/1250/engb-fr#46173

### Summary of Changes
While language strings should be alpha ordered, the strings which are only plural forms of eachother have to stay together. Otherwise tools like Crowdin get issues. So don't blindly alpha-order :-)

### Testing Instructions
Nothing really to test as it's just moving a language string few lines higher.

Can be merged on review.

### CODE REVIEW

**Comment by brianteeman** [comment]
To avoid someone "fixing" this again could you add a comment in the file

**Comment by HLeithner** [comment]
Thanks

**Comment by Bakual** [comment]
> To avoid someone "fixing" this again could you add a comment in the file

I'd rather remove the strings completely (if they aren't already in J4) since they actually aren't used anymore.

**Comment by brianteeman** [comment]
@Bakual in the next 2.5 years of supported life for j3 I'm sure someone will try to fix this ;)

**Pull request merged**
