### PR TITLE
[5.0] Merge 4.3 dev

### PR DESCRIPTION
**Pull request by wilsonge**
This doesn't include any dependency updates to composer.json and package.json. These can be done separately by @HLeithner as the dependencies in 5.0 are generally a way ahead anyhow

### CODE REVIEW

**Comment by Hackwar** [comment]
.drone.yml still needs to be signed.

**Comment by wilsonge** [comment]
Are you able to do that? I haven't set up drone cli on my laptop (haven't sorted it out since I my old one broke at christmas)

**Comment by HLeithner** [comment]
signed it

**Comment by HLeithner** [comment]
@laoneo I have not the feeling that the  --diff option for phpcs makes it easier to find the issue, at least I didn't found the problem in the current run...

**Comment by laoneo** [comment]
Just run it locally without the dry run and then it will fix the issue automatically.

**Comment by wilsonge** [comment]
> @laoneo I have not the feeling that the --diff option for phpcs makes it easier to find the issue, at least I didn't found the problem in the current run...

It's all just indentation fixes. I'll take a look later on today. I'll probably just use the tool like allon says. but not hard to fix by hand either

**Pull request merged**
