### PR TITLE
[4.0] Make login module IDs unique

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue #23538 and followup to #24757.

### Summary of Changes

Appends module ID to ID attribute to prevent duplicate IDs when multiple login modules are published on one page.

### Testing Instructions

Code review.
Or publish multiple login modules and validate HTML.

### Expected Result

No validation errors.

### Actual Result

Validation errors like:

> Error: Duplicate ID modlgn-username.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 1dc4ebc333aa30455946801eda93a480a0713607<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24933">issues.joomla.org/tracker/joomla-cms/24933</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 8b5ae78345787ea52a9ea64845e6d375430587e4<br /><br />1. Code review: All instances for duplicate ids and corresponding `<label for=...` have been corrected by this PR, nothing was forgotten.
2. W3C validator: Without this PR duplicate ID errors, with this PR no such errors.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24933">issues.joomla.org/tracker/joomla-cms/24933</a>.</sub>

**Comment by richard67** [comment]
PR has 2 good tests now. @Quy 's test result was lost in issue tracker due to rebase. But that rebase was clean, no changes, so the test result should still be valid. Drone errors seem not to be related to this PR. => RTC?

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24933">issues.joomla.org/tracker/joomla-cms/24933</a>.</sub>

**Pull request merged**
