### PR TITLE
[4.2] Fix uninitialized version variable in installer library

### PR DESCRIPTION
**Pull request by richard67**
Pull Request for Issue #37934 .

### Summary of Changes

Move the log of the version number on schema updates to below the code where the version number is set.

### Testing Instructions

See issue #37934 .

But code review should be sufficient.

See also my comment in the issue why it is only a 4.2-dev issue and ok in 4.1-dev: https://github.com/joomla/joomla-cms/issues/37934#issuecomment-1142096060

### Actual result BEFORE applying this Pull Request

No installer error.

### Expected result AFTER applying this Pull Request

PHP warning about uninitialized variable $version being used at line 1334 of file libraries/src/Installer/Installer.php.

### Documentation Changes Required

None.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 4b0ee24f318a02d5ce9fee53d1b5023834dd05d9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37941">issues.joomla.org/tracker/joomla-cms/37941</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 4b0ee24f318a02d5ce9fee53d1b5023834dd05d9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37941">issues.joomla.org/tracker/joomla-cms/37941</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37941">issues.joomla.org/tracker/joomla-cms/37941</a>.</sub>

**Comment by roland-d** [comment]
Thanks everybody

**Pull request merged**
