### PR TITLE
Remove duplicate params entry and move this to the right place

### PR DESCRIPTION
**Pull request by zero-24**
Pull Request for Issue #15212

### Summary of Changes

Shows the hits for com_newsfeeds

### Testing Instructions

Go to the setting of a neewsfeed, see the hits are now showed

### Expected result

Hits are showed

### Actual result

hits are not showed

### Documentation Changes Required

none.

### Additional info

I have not found yet a way how to fill that field with a value.

For me it looks like a `did never work` or `copy and paste error` from weblinks as also the description language key is from weblinks. This also needs to be fixed if needed at all.

I would vote for removal that from the GUI as it was nerver displayed in isis nor does it make sense nor does it work.

### CODE REVIEW

**Comment by Quy** [comment]
Sorry I highlighted its location in the wrong place. Here it is in the Weblinks plugin:
weblinks

**Comment by brianteeman** [comment]
> For me it looks like a did never work or copy and paste error from weblinks as also the description language key is from weblinks. This also needs to be fixed if needed at all.

see #15201 which i did some time ago

**Comment by zero-24** [comment]
Thanks. So i don't need to take care about that here. If we decide to keep that field in.

**Comment by franz-wohlkoenig** [comment]
@zero-24 so com_newsfeed is to test, not weblinks?

**Comment by zero-24** [comment]
Correct.

**Comment by franz-wohlkoenig** [comment]
"Hits" are shown, but Tooltip is about "Weblinks":
bildschirmfoto 2017-04-22 um 11 33 13

**Comment by zero-24** [comment]
Correct this is fixed by the PR brian linked above.

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 323c7e9c4b9501ad0c3fcff1cd1b81369f980ef7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15464">issues.joomla.org/tracker/joomla-cms/15464</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
Why is "PR-staging" removed if i set "Easy Test" on "Yes"?

**Comment by zero-24** [comment]
Looks like there are hickups. Can you dokument the exact issue number + the exact steps you took as issue to the issue trackers issue tracker. ;)

**Comment by franz-wohlkoenig** [comment]
done: https://github.com/joomla/jissues/issues/962

**Comment by zero-24** [comment]
:+1:

**Comment by sanderpotjer** [comment]
I have tested this item :white_check_mark: successfully on 323c7e9c4b9501ad0c3fcff1cd1b81369f980ef7<br /><br />The PR does indeed display the field, but without a value. 

So while the test is successful, I would recommend to either fix the display of the hits value too or remove the display of this hits field completely. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15464">issues.joomla.org/tracker/joomla-cms/15464</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Comment by rdeutz** [comment]
@zero-24 please check the conflicts

**Pull request merged**
