### PR TITLE
[4.0] RTL no need for ml2 or mr2 in well.php

### PR DESCRIPTION
**Pull request by infograf768**
Pull Request for Issue https://github.com/joomla/joomla-cms/pull/27409#issuecomment-571464842

### Summary of Changes
As `ml-2` has been corrected for RTL in https://github.com/joomla/joomla-cms/pull/27409 , we should not use it anymore in atum layouts/chromes/well as mr-2 was already overriden for rtl

{EDIT] see below https://github.com/joomla/joomla-cms/pull/27444#issuecomment-575043155

### Testing Instructions
Install Persian (fa-IR) language and set admin language to Persian.
Display Control Panel Look at the quickicons

### Before patch
Screen Shot 2020-01-09 at 10 30 44

### After patch
Screen Shot 2020-01-09 at 10 34 02

@brianteeman

### CODE REVIEW

**Comment by Quy** [comment]
We may not need `mr-2`. See the markup between the following.

Home Dashboard:
```
<h2><span class="fa fa-sync mr-2" aria-hidden="true"></span>Update Checks</h2>
```

Content Dashboard:
```
<h2 class="card-header">
        <span class="fa fa-cog" aria-hidden="true"></span>				Content Settings			</h2>
```

Change line 71 to fix the issue and add class `card-header` to be consistent with other dashboards.
```
						<h2<?php echo $headerClass; ?>>
							<?php echo $headerIcon; ?>
							<?php echo htmlspecialchars($module->title); ?>
						</h2>
```

**Comment by infograf768** [comment]
@Quy 
In fact we do not need to add `card-reader` at all as it already present in well.php in the `<div>`
For the content dashboard, the code is in the mod_submenu tmpl

Therefore I just deleted the useless mr2 indeed and used your multiple echo.
Modifying PR title now.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 02229ea6e2f6c3c22ffb540faeb2bf6a29640a18<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27444">issues.joomla.org/tracker/joomla-cms/27444</a>.</sub>

**Comment by richard67** [comment]
@infograf768 I don't really see a difference in the before and after screenshots, except maybe that the "+" bar is a bit wider compared to the rest of the button in the after screenshot, but this might be caused by lower screen width. So what should I check when testing?

**Comment by brianteeman** [comment]
before the patch the icon is touching the word in the title in the top right 
image

**Comment by richard67** [comment]
Ahhh, how could I miss that? Think I need glasses ;-)

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 7ab8e09283c707300c881aa4707a8bfb4cc101bd<br /><br />Thanks god the logout button is easy to find so I can quickly logout and return to my default language. Not easy to test in Persian when not being able to read Persian.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27444">issues.joomla.org/tracker/joomla-cms/27444</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27444">issues.joomla.org/tracker/joomla-cms/27444</a>.</sub>

**Comment by richard67** [comment]
@Quy 's test was still valid because the only 2 commits since then were clean branch update to base branch. Therefore RTC now with 2 good tests.

**Comment by infograf768** [comment]
@richard67 
> Thanks god the logout button is easy to find so I can quickly logout and return to my default language. Not easy to test in Persian when not being able to read Persian.

This is my trick when I have to test RTL:
I use multiple windows, one of them being the Installed Languages.
Then I display in another window (in en-GB ) the page where I have to test a patch or use dev tools to find out where an error comes from.
Then I switch languages in the other window, back and forth.

**Pull request merged**
