### PR TITLE
[4.0] Display true/false instead 1/blank in system information

### PR DESCRIPTION
**Pull request by Quy**
Pull Request for Issue #27553.

### Summary of Changes
Display true/false instead 1/blank respectively to match in the configuration file.

### Testing Instructions
Go to System > System Information > Configuration File
`offline` is blank.
`mailonline` is 1.
Apply PR.
`offline` is false.
`mailonline` is true.

### CODE REVIEW

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 46a9ad56fb246d02a472c294b96d5e6c36ca04dd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27588">issues.joomla.org/tracker/joomla-cms/27588</a>.</sub>

**Comment by jwaisner** [comment]
@Quy Will we be looking to correct the` display_offline_message`, `captcha`, and `access` fields to reflect similar? It may need to be a separate PR for that.

**Comment by Quy** [comment]
No as these are dropdowns with several options.

Offline Message
Default Captcha
Default Access Level

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 46a9ad56fb246d02a472c294b96d5e6c36ca04dd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27588">issues.joomla.org/tracker/joomla-cms/27588</a>.</sub>

**Comment by infograf768** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27588">issues.joomla.org/tracker/joomla-cms/27588</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
