### PR TITLE
[4.0] [a11y] enable system plugin skip-to-navigation by default

### PR DESCRIPTION
**Pull request by hans2103**
Pull Request for Issue # .

### Summary of Changes

While installing Joomla the database is filled with some extensions and settings. 
The Joomla system plugin _System - Skip-To Navigation_ is enabled for Administrator only. 
Frontend would benefit too. This PR will change the default setting from _Administrator_ into _Both_ 
The plugin css takes care of showing/hiding the Skip-To implementation

### Testing Instructions

- Install Joomla 
- Go to Joomla Administrator > System > Plugins 
- Open _System - Skip-To Navigation_ 
- Read setting

### Actual result BEFORE applying this Pull Request

Before this PR is applied the default setting of this extension will be `Administrator (Backend only)`

### Expected result AFTER applying this Pull Request

After this PR is applied and a reinstall of Joomla, the default setting will be `Both`.

### CODE REVIEW

**Comment by brianteeman** [comment]
I would be very reluctant to enable this by default on the frontend. I did seriously consider it when I wrote the plugin but the problem is that many site templates already have this functionality. Even if it is in a more limited form in their template the two cannot work together. That is why I left this as an optional setting.

**Comment by hans2103** [comment]
I would like to suggest to enable it by default, since Cassiopeia is the first template to be shown. 
Perhaps _many site templates_ will remove their implementation once they see that J4 has the option available by default. 

It shouldn't be a new slide on https://www.slideshare.net/brianteeman/hidden-joomla-secrets :-)
(that was a long time ago... )

**Comment by brianteeman** [comment]
> Cassiopeia is the first template to be shown.

Only on new sites, not on upgrades

> Perhaps many site templates will remove their implementation
I hope they will do too as this plugin is pretty unique.  

On a site with a skipto already present then this plugin will conflict. Remember that this is a system plugin and not something just for cassiopeia and we dont have a method to enable a plugin based on the template being used. (If we did then I would absilutely agree with this)

**Comment by unmk28** [comment]
Tested Successfully

**Comment by vdfk13** [comment]
test succesfully

**Comment by ceford** [comment]
With update to Beta4-Dev this morning Patchtester says:
Message
There are no files to patch from this pull request. This may mean that the files in the pull request are not present in your installation.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30263">issues.joomla.org/tracker/joomla-cms/30263</a>.</sub>

**Comment by brianteeman** [comment]
I assume that is because you deleted the installation folder

**Comment by hans2103** [comment]
I'm closing this issue to prevent a lot of potential questions on forum.joomla.org regarding not working skip-to-links due to possible conflicts with 3th party template implemented skip-to-links

**Pull request closed without merging**
