### PR TITLE
[3.10] Pre-update check

### PR DESCRIPTION
**Pull request by brianteeman**
1. Back port the headings and string changes from #26178
2. Added a check for non-core extensions before displaying that table

cc @zero-24

### CODE REVIEW

**Comment by zero-24** [comment]
Works good to me thanks @brianteeman 
image

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on bef99923bf374c12b39471bb206ccbe295f1d595<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26277">issues.joomla.org/tracker/joomla-cms/26277</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on cfb0feeba5c02bb7f25bbe63eea7a2af19d94d5b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26277">issues.joomla.org/tracker/joomla-cms/26277</a>.</sub>

**Comment by ghost** [comment]
Status "Ready To Commit".

**Comment by zero-24** [comment]
Merging thanks for Backporting the pre-update checker Improvements down to 3.10 👍

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
