### PR TITLE
Update Tinymce 4.5.8

### PR DESCRIPTION
**Pull request by brianteeman**
Update to 4.5.8

Version 4.5.8 (2017-10-05)
	Fixed bug where paste on Edge wouldn't paste UTF characters since Microsoft didn't implement the html5 clipboard api correctly.
	Fixed bug where it was hard to focus the editor on IE 10 since the body element didn't have full height.
	Fixed bug where malformed blob urls wouldn't be handled correctly by the editor.

### test instructions
just apply the patch and make sure tinymce still works as expected

### CODE REVIEW

**Comment by Razzo1987** [comment]
I have tested this item :red_circle: unsuccessfully on e465560674672e1a091dbc40002dfd3f29253553<br /><br />I try to past "qfascasààààùùùùèèèììììì" in new article with Microsoft Edge 40.15063.674.0, but after (at the seme before) the patch the tinyCME give "qfascasÃ Ã Ã Ã Ã¹Ã¹Ã¹Ã¹Ã¨Ã¨Ã¨Ã¬Ã¬Ã¬Ã¬Ã¬"<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18574">issues.joomla.org/tracker/joomla-cms/18574</a>.</sub>

**Comment by brianteeman** [comment]
Do you mean that the problem exists before AND after the patch?

**Comment by Razzo1987** [comment]
Sorry Brian,


I'm at the JWC and I have done my first debug test.

The first time I try the patch it doesn't work, but now it is work correctly.


I think it doesn't work for cache problems...


now the patch work correctly.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18574">issues.joomla.org/tracker/joomla-cms/18574</a>.</sub>

**Comment by Razzo1987** [comment]
I have tested this item :white_check_mark: successfully on e465560674672e1a091dbc40002dfd3f29253553<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18574">issues.joomla.org/tracker/joomla-cms/18574</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on e465560674672e1a091dbc40002dfd3f29253553<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18574">issues.joomla.org/tracker/joomla-cms/18574</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
