### PR TITLE
[4.0] Safari fix

### PR DESCRIPTION
**Pull request by brianteeman**
PR for #29621

apply the safari fix from the admin template #28921 to the installer

@nikosdion @philetaylor please test as I don't have access to safari

Dont forget to npm i or node build.js --compile-css

### CODE REVIEW

**Comment by C-Lodder** [comment]
The reboot is already being imported from inside the core BS SCSS file: https://github.com/joomla/joomla-cms/blob/b0d7d59e03b7096e5a1da81ee229e66794ba3f5d/installation/template/scss/template.scss#L6

```
@import "reboot";
```

**Comment by brianteeman** [comment]
It may well  be but the fix is NOT in that file.

**Comment by C-Lodder** [comment]
I know, so you can just add:

```
th {
  text-align: -webkit-match-parent;
}
```

Rather than importing the entire `reboot.scss` again

**Comment by brianteeman** [comment]
> Rather than importing the entire reboot.scss again

I am not doing that - check the paths

**Comment by C-Lodder** [comment]
Ah wrong template, sorry.

**Comment by dgrammatiko** [comment]
> I am not doing that - check the paths

Actually you **are** doing exactly that. the line 6:

```scss
@import "../../../media/vendor/bootstrap/scss/bootstrap";
```

Already includes reboot, so you're including the same (-ish) file twice. Either:
- what @C-Lodder proposed above 
- or unpack `@import "../../../media/vendor/bootstrap/scss/bootstrap";` to the individual imports and replace the reboot with the preferred one...

**Comment by brianteeman** [comment]
please read the pr before commenting!!
even better test it

**Comment by dgrammatiko** [comment]
@brianteeman I'm sorry but the naming is really poor here. The file is not `reboot` rather an add-on to reboot, so, unless someone really digs into the code it's rather frustrating. You could have named that as `reboot-safari-fix` or something similar and things would be obvious. Naming that file as a known Bootstrap module and expect people to understand what's inside that file is a bit stressed to say the least...

**Comment by brianteeman** [comment]
it is named reboot because it follows the existing naming convention that I did not create. 

I can't help it if people like to comment that something is wrong and doesnt work when they dont test it

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks @wilsonge

**Pull request merged**
