### PR TITLE
Fix to Sub Form Field Frontend Save Deleted and Reordered Params

### PR DESCRIPTION
**Pull request by JamesNGarrett**
Pull Request for Issue #12006 
### Testing Instructions
1. Install a module with a subform field in its config params
   - I made a minimal module here for example:
   - https://github.com/JamesNGarrett/mod_joomla_subformfield_test
2. Make a module of this type on yr site
3. Edit it in the frontend and add some items to the options
4. Save
5. Delete some items
6. Save
7. Deleted item is gone

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
I have tested this item :red_circle: unsuccessfully on a3e1569efb9043c0a14ba929d0ddbef03f287f88<br /><br />Got on installing example module:
- `JInstaller: :Install: File does not exist __/Joomla/tmp/install_587627ed56ddd/mod_joomla_subformfield_test-master/mod_joomla_subformfield_test/index.html
Module %s: Could not copy files from the source.`
- `Error installing module`<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12007">issues.joomla.org/tracker/joomla-cms/12007</a>.</sub>

**Comment by JamesNGarrett** [comment]
whoops - i forgot to include the index.html file called in the manifest.  I have removed the line from the manifest so it should now install fine.

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on a3e1569efb9043c0a14ba929d0ddbef03f287f88<br /><br />**For Testers:** To see Module on Frontend you have to make a new Item in Module at Backend. Then you can test at Frontend.

With Patch deleted Item is gone. Without Patch after saving Module there is a copy of an Item.

There are no Tooltipp – what are the blue Botton for?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12007">issues.joomla.org/tracker/joomla-cms/12007</a>.</sub>

**Comment by coolcat-creations** [comment]
Test successful, but remark:

The layouts should be the same in Frontend and backend.
image
image

**Comment by coolcat-creations** [comment]
I have tested this item :white_check_mark: successfully on a3e1569efb9043c0a14ba929d0ddbef03f287f88<br /><br />see my comment regarding layout<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12007">issues.joomla.org/tracker/joomla-cms/12007</a>.</sub>

**Pull request merged**
