### PR TITLE
use https on docs.joomla.org

### PR DESCRIPTION
**Pull request by J0WI**
Referring to https://github.com/joomla/joomla-cms/pull/5478#issuecomment-69810813

I split this in multiple commits. Most changes are comments and sample data.
I also changed the links in /tests now.

### CODE REVIEW

**Comment by brianteeman** [comment]
As far as I can see this is all ok as @mbabker has stated that the docs site is now on https<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5717">issues.joomla.org/joomla-cms/5717</a>.</sub>

**Comment by mbabker** [comment]
Looks fine to me.

For those looking at this PR and thinking "it's just doc blocks, why does it matter?", the doc blocks are utilized to generate the content for our API site.  One of the files changed in this case is the JLayout interface, which is listed at https://api.joomla.org/cms-3/classes/JLayout.html.  Note the link in the class info block.

**Comment by brianteeman** [comment]
Setting to RTC - thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5717">issues.joomla.org/joomla-cms/5717</a>.</sub>

**Comment by anibalsanchez** [comment]
@test OK

I has applied it and I have been working on the patched site. All links go to https://docs.joomla.org/<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5717">issues.joomla.org/joomla-cms/5717</a>.</sub>

**Pull request merged**
