### PR TITLE
[4.0][bugfix] Fix Figure misbehaviour in tinyMCE

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue, sorry couldn't found the one...

### Summary of Changes
- Adds a class `image` to the `figure` element as tinyMCE expects that to enable the editing of the `figcaption` text

### Testing Instructions
This Pr needs NPM
- Fetch and run npm install
- Try to select an image using the Joomla dropdown icon and then selecting media
- Add some figure class and some text for the figure caption
- You should have a boxed area around the image and clicking in the caption text you should be able to edit it

Screenshot 2021-12-05 at 18 56 31

Screenshot 2021-12-05 at 18 56 48

### Actual result BEFORE applying this Pull Request

Editing a figure element is kinda broken

### Expected result AFTER applying this Pull Request

Editing a figure element is easier

### Documentation Changes Required

No

@brianteeman @N6REJ

### CODE REVIEW

**Comment by N6REJ** [comment]
I have tested this item :white_check_mark: successfully on c54a3fe1b40dfa589204a2354d235c6f01855a14<br /><br />Works exactly as expected<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36221">issues.joomla.org/tracker/joomla-cms/36221</a>.</sub
Screenshot 2021-12-05 122245
>

**Comment by N6REJ** [comment]
@dgrammatiko nice and simple.  If I could make a user request might be handy to have a.. switch(?)... to move caption before/after image.

**Comment by dgrammatiko** [comment]
> if I could make a user request might be handy to have a.. switch(?)... to move caption before/after image.

Do you mean something like:
```html
<!-- before -->
<figure>
  <figcaption>
  <img ... >
</figure>

<!-- after -->
<figure>
  <img ... >
  <figcaption>
</figure>
```

TBH I had to check MDN as I had the impression that `figcaption` could only go as the last element of the `figcaption`, and clearly, that's not what the specs say: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/figcaption. Give me some time to think how that could be done

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on c54a3fe1b40dfa589204a2354d235c6f01855a14<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36221">issues.joomla.org/tracker/joomla-cms/36221</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :red_circle: unsuccessfully on c54a3fe1b40dfa589204a2354d235c6f01855a14<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36221">issues.joomla.org/tracker/joomla-cms/36221</a>.</sub>

**Comment by dgrammatiko** [comment]
@brianteeman what failed here?

**Comment by brianteeman** [comment]
oops sorry I meant to change it to untested

**Comment by brianteeman** [comment]
I have not tested this item.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36221">issues.joomla.org/tracker/joomla-cms/36221</a>.</sub>

**Comment by brianteeman** [comment]
tested correctly now<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36221">issues.joomla.org/tracker/joomla-cms/36221</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on c54a3fe1b40dfa589204a2354d235c6f01855a14<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36221">issues.joomla.org/tracker/joomla-cms/36221</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36221">issues.joomla.org/tracker/joomla-cms/36221</a>.</sub>

**Comment by N6REJ** [comment]
> > if I could make a user request might be handy to have a.. switch(?)... to move caption before/after image.
> 
> Do you mean something like:
> 
> ```
> 
> <figure>
>   <figcaption>
>   
> </figure>
> 
> 
> <figure>
>   
>   <figcaption>
> </figure>
> ```
> 
> TBH I had to check MDN as I had the impression that `figcaption` could only go as the last element of the `figcaption`, and clearly, that's not what the specs say: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/figcaption. Give me some time to think how that could be done

ty, thats exactly what I meant.  I appreciate you doing the extra effort

**Comment by Quy** [comment]
Thanks

**Pull request merged**
