### PR TITLE
typo

### PR DESCRIPTION
**Pull request by PhilETaylor**
typo

### CODE REVIEW

**Comment by Twincarb** [comment]
I have tested this item :white_check_mark: successfully on ee5ded2bc21de58bb0cfa99bb2d65cc301639041<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19910">issues.joomla.org/tracker/joomla-cms/19910</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on ee5ded2bc21de58bb0cfa99bb2d65cc301639041<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19910">issues.joomla.org/tracker/joomla-cms/19910</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19910">issues.joomla.org/tracker/joomla-cms/19910</a>.</sub>

**Comment by zero-24** [comment]
Thanks. Yesterday there was a issue with a travis build but after a reboot this looks solved now.

**Pull request merged**
