### PR TITLE
Adds jlayout searchtools to com_users user groups

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Description

This PR adds, for consistency, as it exists in so many other views in the backoffice, the search tools to com_users user groups.

As an extra also added a badge and a link in the number of users in that group.
###### Before PR

image
###### After PR

image
#### How to test
1. Install latest staging and apply this patch
2. Go to Users -> User Groups
3. Check the ordering select box and search is working fine.

### CODE REVIEW

**Comment by ghazal** [comment]
Test OK.
(PHP7).

**Comment by andrepereiradasilva** [comment]
@ghazal please mark tested in https://issues.joomla.org/tracker/joomla-cms/9093 (after login the Test button appears). See https://docs.joomla.org/Testing_Joomla!_patches#Recording_test_results

**Comment by ghazal** [comment]
I have tested this item :white_check_mark: successfully on 6aa24ec04b0e6cce29b272688f80b1b9072a8724<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9093">issues.joomla.org/joomla-cms/9093</a>.</sub>

**Comment by andrepereiradasilva** [comment]
thanks

**Comment by richard67** [comment]
I have tested this item :red_circle: unsuccessfully on 6aa24ec04b0e6cce29b272688f80b1b9072a8724<br /><br />Column for ordering is not shown (and was not shown before this patch), so the ordering should not be among the sorting options, and so it should not be the default option.

So either the default sorting should be changed to something else than ordering, and ordering should be removed from the sorting options, or a column for the ordering should be shown.  <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9093">issues.joomla.org/joomla-cms/9093</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@richard67 i asked myself that in this one.

I decided to not change the default ordering (from Public to Super User) because people are used to that. 
A ordering (e.g. drag and drop) behaviour for this view does not exist before and after the PR.

Please notice that before this PR the issue you described exists. This PR has not changed that.

So i didn't change the behaviour of the view, so in my view your test of the changes i made is successfully.

I suppose a new PR should be made to add ordering columns and behaviour to groups, if it makes sense at all.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 6aa24ec04b0e6cce29b272688f80b1b9072a8724<br /><br />I am convinced now.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9093">issues.joomla.org/joomla-cms/9093</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 6aa24ec04b0e6cce29b272688f80b1b9072a8724<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9093">issues.joomla.org/joomla-cms/9093</a>.</sub>

**Comment by brianteeman** [comment]
RTC - thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9093">issues.joomla.org/joomla-cms/9093</a>.</sub>

**Pull request merged**
