### PR TITLE
[imp] Articles Manager: adding class hasTooltip to title and author rows

### PR DESCRIPTION
**Pull request by infograf768**
Similar to https://github.com/joomla/joomla-cms/pull/5835

After patch, we will get

screen shot 2015-01-21 at 08 31 16

and 

screen shot 2015-01-21 at 08 30 59

### CODE REVIEW

**Comment by infograf768** [comment]
Note: similar patches can be done in many managers.

**Comment by brianteeman** [comment]
Do we really need to create some of these tooltips. I know its the author because it is in the author column. Adding a tooltip to remind me of that 20 times on the page doesnt help it just clutters<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5844">issues.joomla.org/joomla-cms/5844</a>.</sub>

**Comment by infograf768** [comment]
The `title="<?php echo JText::_('JACTION_EDIT'); ?>"` already exists in the code and the tooltip displayed is not conform
It displays in black over yellow as it was here before patch

capture

This ONLY adds the right class to the link to display white text on black background.

If you consider that these are unnecessary, the title and author (and maybe others) should be removed all over the back-end.

**Comment by Bakual** [comment]
I agree it should be either a proper tooltip like JM suggests or completely remove it if deemed unnecessary.

**Comment by brianteeman** [comment]
I agree that this should be a proper tooltip

I dont agree with adding tooltips to things that dont already have them (or
need them)

For this specific one I only agree it needs something because the icons
used are not consistent with the UI and are not easy to understand. I would
prefer they were changed completely but for speed and a first step I agree
in changing to a proper tooltip

On 22 January 2015 at 09:08, Thomas Hunziker <notifications@github.com>
wrote:

> I agree it should be either a proper tooltip like JM suggests or
> completely remove it if deemed unnecessary.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/5844#issuecomment-70990693>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by wilsonge** [comment]
I agree that we should probably consistently remove these 'useless' tooltips. But for consistency merging this.

@test works fine

**Comment by brianteeman** [comment]
Why are you merging something that you say is useless. If you want
consistency, and we all do, then remove the other useless tooltips dont add
more. This makes no sense at all

On 1 February 2015 at 16:30, George Wilson <notifications@github.com> wrote:

> Merged #5844 <https://github.com/joomla/joomla-cms/pull/5844>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/5844#event-228151393>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by wilsonge** [comment]
I personally don't have the time to go through and remove all these tooltips and in the meantime this PR has sat here for 11 days with no alternatives being submitted (and it's not like it's a big b/c thing where it can't be easily reverted next release). If you want to spend some time doing the PR then feel free else I'm going to go for consistency.

**Pull request merged**
