### PR TITLE
[4.0] Improve a11y for systeminformation

### PR DESCRIPTION
**Pull request by chmst**
JAT has found several a11y issues in the SystemInformation View:

This PR replaces #21628 which I have deleted - my mistake. Could someone please close the old PR? Sorry for inconvenience.

### Summary of Changes
Remove the < form > tag, as this is not a form.
Remove empty Table Footers
Replace the < fieldset > Tag by < div >
Remove the < legend > by Table < caption >
Improve the Table header with some css, add a new scss file for com_admin

### CODE REVIEW

**Comment by ghost** [comment]
#21628 is closed as requested.

**Comment by brianteeman** [comment]
Looks good - can you fix hound please

**Comment by wojsmol** [comment]
Additionally we have a merge conflict in this files:
```
administrator/templates/atum/css/template-rtl.min.css
administrator/templates/atum/css/template.min.css 
```

**Comment by chmst** [comment]
@wojsmol can you help me? I don't know how to resolve conflicts in .min.css files.

**Comment by wojsmol** [comment]
@chmst see https://github.com/chmst/joomla-cms/pull/1

**Comment by wojsmol** [comment]
@chmst I send PR reverting my last changes.

**Comment by chmst** [comment]
All right. I don't understand the conflicts, because the .css and min.css files should be generated from the scss files.

**Comment by wojsmol** [comment]
accept my last PR then I prepare good one.

**Comment by chmst** [comment]
It is merged. Is there something else I have to do?

**Comment by wojsmol** [comment]
https://github.com/chmst/joomla-cms/pull/3

**Comment by wojsmol** [comment]
@chmst All conflicting css files can be deleted from this PR because they are added to .gitignore in the current 4.0-dev. Additionally please delete following files and folders
```
administrator/templates/atum/html/com_patchtester_meins
nbproject
administrator/components/com_media/package-lock.json
```

**Comment by chmst** [comment]
cannot find dthe package-lock.json any more.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21724">issues.joomla.org/tracker/joomla-cms/21724</a>.</sub>

**Comment by wojsmol** [comment]
Ok, then we have following conflicting files list
```
administrator/components/com_admin/tmpl/sysinfo/default.php
administrator/templates/atum/css/bootstrap.css
administrator/templates/atum/css/bootstrap.min.css
administrator/templates/atum/css/template-rtl.css
administrator/templates/atum/css/template-rtl.min.css
administrator/templates/atum/css/template.css
administrator/templates/atum/css/template.min.css
installation/template/css/template.css
installation/template/css/template.min.css
```
see my previous comment https://github.com/joomla/joomla-cms/pull/21724#issuecomment-417986313

**Comment by wojsmol** [comment]
@chmst If you need any help then simply write

**Comment by chmst** [comment]
I'm trying right now, but cannot reproduce the branch. I had done the npm for testing other pr's.

**Comment by chmst** [comment]
@wojsmol I cannot reproduce the conflicts in my repo. The simple way sowud be to close this pr and make a new one?

**Comment by wojsmol** [comment]
Simply merge 4.0-dev from  joomla/joomla-cms into this PR branch. Then you revise conflicts.

**Comment by wojsmol** [comment]
@chmst Please see https://github.com/chmst/joomla-cms/pull/4

**Comment by wojsmol** [comment]
@chmst I must miss same changes in `administrator/components/com_admin/tmpl/sysinfo/default.php`. Please compare with https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_admin/tmpl/sysinfo/default.php

**Comment by chmst** [comment]
@wojsmol - Thank you, I will resolve this when I am back home. The < form > tag is not needed.

**Comment by chmst** [comment]
@wojsmol hope that the conflict is resolved now. Thank you for your patience

**Comment by baernm** [comment]
I have tested this item :white_check_mark: successfully on cd203adf4c399d218350f893783dd9af91de6dd6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21724">issues.joomla.org/tracker/joomla-cms/21724</a>.</sub>

**Comment by wojsmol** [comment]
@chmst Please remove `administrator/components/com_media/package-lock.json` from this PR.

**Comment by laoneo** [comment]
@brianteeman all ok here from your side?

**Comment by brianteeman** [comment]
@laoneo it was good when I first checked it - not sure if there have been significant changes since

**Comment by laoneo** [comment]
Do you mind to have another look?

**Comment by chmst** [comment]
Wait a moment. There is another PR which has changed something in the library. I can resolve this as soon as the other change is merged.

**Comment by brianteeman** [comment]
@laoneo I will put it on my todo for tonight

**Comment by carcam** [comment]
I have tested this item :white_check_mark: successfully on cf368e54c2657dca08dbc58dee395c8f1c95fa6b<br /><br />I have tested this change in Joomla 4 Alpha 5 release succesfully. There are no visible differences in the View System Information before and after patch.

I have also tested with Wave Automatic Test and I got the error of an empty th which belongs to the php info about mysqlnd statistics which was empty in my server but I do not think it's related with this PR.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21724">issues.joomla.org/tracker/joomla-cms/21724</a>.</sub>

**Comment by chmst** [comment]
@carcam thank you for testing. And good finding of the empty <th> in the php-info. Let's make another PR for the sysinfo model, to avoid empty table headers.

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21724">issues.joomla.org/tracker/joomla-cms/21724</a>.</sub>

**Comment by zwiastunsw** [comment]
I tested this patch. Fieldset and legend elements have been rightly removed. But...
The "caption" element should be used in the table instead of the legend element. Without the caption element, users of screen readers will not get the information contained in the table.

**Comment by wilsonge** [comment]
I'm going to merge this as a good piece of progress even though it would appear there's some more to do here from the comments by @zwiastunsw

**Comment by chmst** [comment]
@wilsonge thank you! So I can continue without raising conflicts ;)

**Pull request merged**
