### PR TITLE
[4.0] Install from folder

### PR DESCRIPTION
**Pull request by brianteeman**
Clarify the description

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on a552cb2e78ab468115ee111f5a39f35479ec950c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33767">issues.joomla.org/tracker/joomla-cms/33767</a>.</sub>

**Comment by PhilETaylor** [comment]
I have tested this item :white_check_mark: successfully on a552cb2e78ab468115ee111f5a39f35479ec950c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33767">issues.joomla.org/tracker/joomla-cms/33767</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33767">issues.joomla.org/tracker/joomla-cms/33767</a>.</sub>

**Comment by Quy** [comment]
Thanks

**Comment by brianteeman** [comment]
Thank you

**Pull request merged**
