### PR TITLE
[4.0] Always render module layout

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue # .

### Summary of Changes

Per discussion in https://github.com/joomla/joomla-cms/pull/20811, module layouts should always be rendered to allow overrides.

### Testing Instructions

Code review should suffice.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by richard67** [comment]
Does this replace PR #24956 ?

**Comment by SharkyKZ** [comment]
No, that one is for `mod_articles_category`. This one is for other article modules.

**Comment by richard67** [comment]
I see, you are right. I mixed up "...category" and "...categories".

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on a38921220bc23054fa58fc3e19059ef8ac964b11<br /><br />Code review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25071">issues.joomla.org/tracker/joomla-cms/25071</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on a38921220bc23054fa58fc3e19059ef8ac964b11<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25071">issues.joomla.org/tracker/joomla-cms/25071</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25071">issues.joomla.org/tracker/joomla-cms/25071</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
