### PR TITLE
[4.0] System Database

### PR DESCRIPTION
**Pull request by brianteeman**
This PR proposes to move the Database check (and fix) from the Notifications group to the Maintenance group on the system dashboard. It seems more logical to me for it to be in this group where you perform actions rather than a purely informational group

image

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 6ece46455da5f7bf1ec131f8c74213a867225cf8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34366">issues.joomla.org/tracker/joomla-cms/34366</a>.</sub>

**Comment by Abernyte-Git** [comment]
I have tested this item :white_check_mark: successfully on 6ece46455da5f7bf1ec131f8c74213a867225cf8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34366">issues.joomla.org/tracker/joomla-cms/34366</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34366">issues.joomla.org/tracker/joomla-cms/34366</a>.</sub>

**Comment by chmst** [comment]
Thanks

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
