### PR TITLE
[4.1] Category and Menu Item. Add fancy-select to fields parent_id (possibility to search entries).

### PR DESCRIPTION
**Pull request by ReLater**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/36916 .

### Summary of Changes
- Add `layout="joomla.form.field.list-fancy-select"` to fields `parent_id`.

### Testing Instructions
See https://github.com/joomla/joomla-cms/issues/36916

### Actual result BEFORE applying this Pull Request
No search field in fields `Parent Item (com_menus)` and `Parent (com_categories)`.

### Expected result AFTER applying this Pull Request
grafik

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 7e180e0998aaa53ae59c3f35642cdc149acbc6bb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36925">issues.joomla.org/tracker/joomla-cms/36925</a>.</sub>

**Comment by khu5h1** [comment]
I have tested this item :white_check_mark: successfully on 7e180e0998aaa53ae59c3f35642cdc149acbc6bb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36925">issues.joomla.org/tracker/joomla-cms/36925</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36925">issues.joomla.org/tracker/joomla-cms/36925</a>.</sub>

**Comment by brianteeman** [comment]
Can I ask why you closed this?

**Pull request closed without merging**
