### PR TITLE
Remove unnecessary conditional check in category and article views

### PR DESCRIPTION
**Pull request by joomdonation**
## PR Summary

This PR simply remove unnecessary condition check in elseif command. That check always return true (if it return false, the code in if block will be run), so it is not needed. 
## Testing

This can be seen easily from code review. So I think we just need to a maintainer to review and merge it.

I will do the the same modification for other components (has this same unnecessary code) if this PR is approved.

### CODE REVIEW

**Comment by Bakual** [comment]
RTC based on review. Needs to be squashed before merging.

**Comment by joomdonation** [comment]
Thanks Thomas for reviewing the code. I made the same fix for other views and a small bug fix (in my last commit). Please help review it again.

**Comment by Bakual** [comment]
Merged into `staging`, however without your last commit which is a complete unrelated change.

Please do a new PR with that fix as that one needs to be tested. Currently, the `id` always will be 0 (since $menu isn't defined). After your change it will have a value which may change the following checks.
Also the suppressed error (`@$menu->query['id']`)  should be removed. If $menu isn't defined, we have a problem in the code we actually want to see :smile:

**Comment by joomdonation** [comment]
OK :D. For some reasons, your commit seems doesn't include the fix for article view? Could you check it or should I do it again for article view ?

**Comment by Bakual** [comment]
Hmm, I didn't include the commit which you reverted with "Sorry, I updated wrong file before".
Feel free to create a new PR for that, I can merge it on review as well.

**Comment by joomdonation** [comment]
OK. I made a new PR https://github.com/joomla/joomla-cms/pull/7164. Please help checking and merge it.

**Pull request closed without merging**
