### PR TITLE
[4.3] fix media manager breadcrumb

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue #39921 .

### Summary of Changes

Fixes some weirdness of the breadcrumb

### Testing Instructions

Create a folder `images` inside the `images` folder on media manager.

EDIT: Create some nested folders all named `images`

Try to navigate with the breadcrumbs to that folder
Also test that all the nested paths still work

### Actual result BEFORE applying this Pull Request

Broken

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on eab0985bec350b779049c0787f73e26c8b11e5f1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39922">issues.joomla.org/tracker/joomla-cms/39922</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on eab0985bec350b779049c0787f73e26c8b11e5f1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39922">issues.joomla.org/tracker/joomla-cms/39922</a>.</sub>

**Comment by alikon** [comment]
rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39922">issues.joomla.org/tracker/joomla-cms/39922</a>.</sub>

**Comment by obuisard** [comment]
Thank you Dimitris @dgrammatiko !

**Comment by toonetcreation** [comment]
tested from my side and works fine.
thank you

**Pull request merged**
