### PR TITLE
[4.2] Initialize the installer script variable correctly

### PR DESCRIPTION
**Pull request by laoneo**
### Summary of Changes
#37091 adds the possibility for extensions to deliver the installer script differently than by a predefined class name. Pr #37374 broke that while adding a deprecated notice. This pr correctly instantiates the installer variable.

### Testing Instructions
- Install the container based script [mod_installer_container.zip](https://github.com/joomla/joomla-cms/files/8099215/mod_installer_container.zip)
- Install the script based script [mod_installer_script.zip](https://github.com/joomla/joomla-cms/files/8099234/mod_installer_script.zip)
- Install the legacy script [mod_installer_legacy.zip](https://github.com/joomla/joomla-cms/files/8099220/mod_installer_legacy.zip)

### Actual result BEFORE applying this Pull Request
- The container module shows no text "Installed by container!!"
- The container module shows no text "Installed by script!!"
- The container module shows text "Installed by legacy!!"

### Expected result AFTER applying this Pull Request
- The container module shows text "Installed by container!!"
- The container module shows text "Installed by script!!"
- The container module shows text "Installed by legacy!!"

### CODE REVIEW

**Comment by N6REJ** [comment]
I have tested this item :white_check_mark: successfully on 9aba88a3efad812821d74e00e563dd36ef46eb43<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38629">issues.joomla.org/tracker/joomla-cms/38629</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 9aba88a3efad812821d74e00e563dd36ef46eb43<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38629">issues.joomla.org/tracker/joomla-cms/38629</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38629">issues.joomla.org/tracker/joomla-cms/38629</a>.</sub>

**Comment by fancyFranci** [comment]
Nice fix, thank you!

**Pull request merged**
