### PR TITLE
[4.0] Move 4.0 update server back to the stable state

### PR DESCRIPTION
**Pull request by zero-24**
Pull Request for Issue #18533

### Summary of Changes

This reverts this PR #18533 which introduced the 4.0-dev standalone update server. This moves the updateserver back to the original state. So this is required to be merged before 4.0 stable

### Testing Instructions

reverts #18533 as described

### Expected result

using stable updateserver

### Actual result

using 4.0-dev updateserver

### Documentation Changes Required

none

### CODE REVIEW

**Comment by zero-24** [comment]
@wilsonge as it seams we are not going to use this update server at all I think it would be wise to move the updateserver back to it's original value. And if we need we can use a custom URL anyway. So please merge here 👍

**Comment by zero-24** [comment]
@wilsonge here a quick reminder. Thanks

**Comment by zero-24** [comment]
Thanks.

**Comment by wilsonge** [comment]
Thankyou - and I'm sorry!

**Pull request merged**
