### PR TITLE
[4.3][Guided Tours] Make filter search tooltip consistent

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
Make filter search tooltip consistent with other tooltips.

### Testing Instructions
Code review.

### CODE REVIEW

**Comment by brianteeman** [comment]
The PR is correct for consistency but if you  check you will see that there is no code for searching the descrption

**Comment by Quy** [comment]
Please see this merged PR #40118 to see code for description search.

**Comment by brianteeman** [comment]
The query still fails with that merged pr

backend

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 498f435f02d34839d8698590dd0a249ecc6d9e6a<br /><br />the change to the string is correct<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40197">issues.joomla.org/tracker/joomla-cms/40197</a>.</sub>

**Comment by brianteeman** [comment]
no thats not it. the query is supposed to take account of that (and it works for the title)

**Comment by Kostelano** [comment]
I have tested this item :white_check_mark: successfully on 498f435f02d34839d8698590dd0a249ecc6d9e6a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40197">issues.joomla.org/tracker/joomla-cms/40197</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40197">issues.joomla.org/tracker/joomla-cms/40197</a>.</sub>

**Pull request merged**
