### PR TITLE
3.6.x - Improve "show_root" option for category form field

### PR DESCRIPTION
**Pull request by garkell**
No issue created as this is a suggested improvement for the show_root option for the category form field.  Currently this switch, if used doesn't actually do anything other than show the word "root" as the first available option in the list.  This being translatable from the JGLOBAL_ROOT text.  So a user/developer can't change the wording for individual categories where required using the language overrides.
#### Summary of Changes

Replace line 81 in libraries/legacy/form/field/category.php

```
        array_unshift($options, JHtml::_('select.option', '0', JText::_('JGLOBAL_ROOT')));

```

With

```
        $root_option = JText::_('JOPTION_ROOT_' . strtoupper(str_replace(".","_",$extension)));
        array_unshift($options, JHtml::_('select.option', '0', $root_option));

```
#### Testing Instructions

Set any category formfield field with show_root option and the overriding text for JOPTION_ROOT_COM_MYCOMPONENT will display as the first available option.

My limited knowledge of other implications may mean that this could cause some issues elsewhere. but to have the word "root" displayed doesn't seem to be helpful IMHO.

### CODE REVIEW

**Comment by garkell** [comment]
Further testing indicates that the if statement still gives a false positive???

**Comment by mbabker** [comment]
As is this pull request isn't valid because it's trying to merge the 3.6
branch to staging.

Aside from that, if I'm reading your proposal right IMO it makes things
less clear.  ROOT (ID 1) is the absolute root item in any of the nested
tables.  It's not a root for a specific branch, i.e. an extension in the
case of categories.

**Comment by garkell** [comment]
Hi Michael,
    Ok, thanks for the clarification and apologies
        for doing this in the wrong area.  I will close it.  Cheers.
    Glenn
    
    
    On 30/May/2016 11:50 AM, Michael Babker
      wrote:
    
    As is this pull request isn't valid because it's
      trying to merge the 3.6
      branch to staging.
      
      Aside from that, if I'm reading your proposal right IMO it makes
      things
      less clear. ROOT (ID 1) is the absolute root item in any of the
      nested
      tables. It's not a root for a specific branch, i.e. an extension
      in the
      case of categories.
      
      On Sunday, May 29, 2016, Glenn Arkell
      <notifications@github.com> wrote:
      
      > Further testing indicates that the if statement still gives a
      false
      > positive???
      >
      > —
      > You are receiving this because you are subscribed to this
      thread.
      > Reply to this email directly, view it on GitHub
      >
<https://github.com/joomla/joomla-cms/pull/10673#issuecomment-222394699>,
      > or mute the thread
      >
<https://github.com/notifications/unsubscribe/AAWfoXsFPtwc4kori2gNluux_z1v_lB3ks5qGjqbgaJpZM4Ipaky>
      > .
      >
      —
        You are receiving this because you authored the thread.
        Reply to this email directly, view
          it on GitHub, or mute
          the thread.

**Comment by garkell** [comment]
Will close this as I have mis-interpreted the purpose of the root option.  Cheers.

**Pull request closed without merging**
