### PR TITLE
Update en-GB.tpl_beez3.sys.ini

### PR DESCRIPTION
**Pull request by aaleksanyants**
Updated template description

### CODE REVIEW

**Comment by brianteeman** [comment]
This changes the description from html 4 to html5

Is this template actually html5?

**Comment by aaleksanyants** [comment]
yes it is :-)

**Comment by waader** [comment]
I have tested this item :white_check_mark: successfully on 4b9a1588fcb07ee826ff6ed8e8bae25136e25695<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7359">issues.joomla.org/joomla-cms/7359</a>.</sub>

**Comment by brianteeman** [comment]
By adding the version number for joomla this fails the style guide for the use of the joomla name https://joomla.github.io/user-interface-text/?user-interface-text/joomla_name_usage.md<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7359">issues.joomla.org/joomla-cms/7359</a>.</sub>

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 4b9a1588fcb07ee826ff6ed8e8bae25136e25695<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7359">issues.joomla.org/joomla-cms/7359</a>.</sub>

**Comment by wojsmol** [comment]
@aaleksanyants  see https://github.com/aaleksanyants/joomla-cms/pull/3

**Comment by andrepereiradasilva** [comment]
@aaleksanyants this one still needs the "!"

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on d08004bebd02d9be76e2a6a5d64584424e2bef31<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7359">issues.joomla.org/joomla-cms/7359</a>.</sub>

**Comment by brianteeman** [comment]
Contacted Angie as the creator of the template to confirm the html5 change<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7359">issues.joomla.org/joomla-cms/7359</a>.</sub>

**Comment by brianteeman** [comment]
Confirmed with Angie Setting RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7359">issues.joomla.org/joomla-cms/7359</a>.</sub>

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 16b72f4639bf9f98d947eaa4ca9f6d08ea410b1e<br /><br />Only updated the branch to latest staging. All equal.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7359">issues.joomla.org/joomla-cms/7359</a>.</sub>

**Pull request merged**
