### PR TITLE
[5.0] TinyMCE highlighter plugin with CodeMirror 6

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue #41278 .

### Summary of Changes

(Re)Writing a plugin for TinyMCE code highlighting with CodeMirror 6.

### Testing Instructions
Apply patch, run `npm install`.
Enable "code highlighting" in TinyMCE plugin parameters.
Open article editing and check that  "code highlighting" is working

### Actual result BEFORE applying this Pull Request
working

### Expected result AFTER applying this Pull Request
working

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: 
- [x] No documentation changes for docs.joomla.org needed
- [ ] Pull Request link for manual.joomla.org: 
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by dgrammatiko** [comment]
@Fedik wasn't the reason that the original version used an iframe to not interfere with the tinyMCE styles?

Anyways, you could wrap the textarea into a web component with a slot (with Shadow DOM) to overcome the styling problem...

**Comment by Fedik** [comment]
> wasn't the reason that the original version used an iframe to not interfere with the tinyMCE styles?

I think it was more about avoid of loading codemirror scripts and styles, on initila load. But maybe also this.

> web component with a slot (with Shadow DOM) to overcome the styling problem

That what I want to avoid: shadow dom and iframe :)
It has own limitation. In any case will see, in the end can be on of that.
Also we can use own dialog #40150

**Comment by Fedik** [comment]
This is ready for testing

**Comment by HLeithner** [comment]
@brianteeman you may have time tomorrow for a quick look?

**Comment by HLeithner** [comment]
it works for me but looks different then 4.4 version right?

**Comment by HLeithner** [comment]
4.4
image
this pr:
image

shortcuts are working but a bit hard to know if they are not listed anywhere

**Comment by brianteeman** [comment]
1. Agree with  @HLeithner about it missing the legends for search
2. Needs code to remove the old plugin
3. The tab key is not usable in the editor (it was in j43)
4. Using the tab key the focus is not trapped in the modal. As a result you can tab away from the modal and it will stay open and youn cannot close it (a11y)

**Comment by HLeithner** [comment]
I'm merging this for now, but the tab issues is a bit annoying, I have read suggestions like key combination ESC and then TAB to escape from the editor area. Which sounds good to me.

**Comment by brianteeman** [comment]
The accessibility issue really must be fixed before merge

**Comment by Fedik** [comment]
> I'm merging this for now

Do not hurry, it is not that important feature, and it is optional anyway.
I will look in to tab thing some time, this or next week.

The tab escaping the modal is easy to fix with dialog modal (#40150), the browser automatically prevents the focus to leave the dialog.
But I think it also can be fixed when enable Codemirror to trap the tab, as it done in 4.x

**Comment by dgrammatiko** [comment]
@Fedik just switch to the Joomla modal and ask @HLeithner to finally merge that PR...

**Comment by Fedik** [comment]
I have enabled "tab" for codemirror in popup.
btw, a default combination for code indent in codemirror 6 is:
```
Mod + [ = indentLess
Mod + ] = indentMore
```

**Comment by HLeithner** [comment]
> I have enabled "tab" for codemirror in popup. This also fixing the tab escaping the modal.
> 
> btw, a default combination for code indent in codemirror 6 is:
> 
> ```
> Mod + [ = indentLess
> Mod + ] = indentMore
> ```

pretty sure that only works on english keyboards, but will test it thanks

**Comment by HLeithner** [comment]
strange behavior that tab change the indent and not makes a tab, but ok better then nothing.

one strange thing is that I can tab to add indention but shit+tab jumps out of the editor and I will never get into the editor again.

is this intended?

btw. for my suprise strg+alt gr+9 (]) works on german keyboard under linux. also less with [ works.

when we get back the shortcut help it maybe an alternative for tab?

**Comment by Fedik** [comment]
> I will never get into the editor again

At this point TinyMCE trap the tab.

**Comment by HLeithner** [comment]
> > I will never get into the editor again
> 
> At this point TinyMCE trap the tab.

I'm still in the modal and can tab between 3 modal buttons but can't get back into CM

**Comment by Fedik** [comment]
> I'm still in the modal and can tab between 3 modal buttons but can't get back into CM

That what I meant, TinyMCE "tab trap" does not allow for the focus to go in to content, in some reason.

**Comment by HLeithner** [comment]
but at this point in time tinymce isn't in charge of doing anything or?

**Comment by Fedik** [comment]
> but at this point in time tinymce isn't in charge of doing anything or?

It is, the modal is from tinymce API, it have a feature to "trap the tab", to avoind a bug when tab goes under the modal.
when you push shift+tab, the code changes the focus from codemirror to save/cancel button of tinymce, it is stuck there,

**Comment by HLeithner** [comment]
ok, now I understand, can this be solved with your own modal #40150 ?

**Comment by Fedik** [comment]
yeap, I tried a quick test, it is working.
Can do like this, if you like: you can merge current PR, at least it is usable.
I plan a litle changes for https://github.com/joomla/joomla-cms/pull/40150, then it also can be merged.
After that I can update the codemirror + tinymce to use our dialog instead of tinymce.

**Comment by HLeithner** [comment]
Ok then I merge this for now, even if it's not optimal and hope that with #40150 we get a proper working interface.

thanks

**Pull request merged**
