### PR TITLE
[4.0] Installation - create a name

### PR DESCRIPTION
**Pull request by brianteeman**
For historical reasons that I bet no one can remember Joomla doesn't currently let you enter the real name of the Super User when installing Joomla. As a result every site on installation has a user with the name "Super User". This regularly causes issues as it gets confused with the usergroup "Super Users". That might be a translation issue or simply because there is just one character difference I don't know and it doesnt really matter.

As today there is no valid reason to force the name to be "Super User" this PR prompts for the real name as well as the username during installation.

### To test.
Apply this PR using patchtester.
delete configuration.php
re-install joomla

image

image

(Please no bikeshedding about other issues in the installer)

### CODE REVIEW

**Comment by Quy** [comment]
Make the real name required?

**Comment by brianteeman** [comment]
oops I meant to do that - even if the entire required thing is foobar

**Comment by brianteeman** [comment]
It makes sense to me that this is failing the tests. 

Do I submit the pr to fix that here https://github.com/joomla-projects/joomla-browser/blob/develop/src/JoomlaBrowser.php

@Hackwar @wilsonge

**Comment by wilsonge** [comment]
v4.0.0 branch rather than develop but yes. relevent code is here https://github.com/joomla-projects/joomla-browser/blob/v4.0.0/src/JoomlaBrowser.php#L241-L247

**Comment by brianteeman** [comment]
See https://github.com/joomla-projects/joomla-browser/pull/186 for the tests

**Comment by wilsonge** [comment]
merged. can you update the composer dependency here please?

`composer install`
`composer update joomla-projects/joomla-browser`

**Comment by brianteeman** [comment]
Updated as requested

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 5919cdf5efd6426627c4e0cfe396ec5e4514a51d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25774">issues.joomla.org/tracker/joomla-cms/25774</a>.</sub>

**Comment by richard67** [comment]
Tested new install with MySQL 5.7 and PostgreSQL 10.9.

Thanks for this PR. It was time that it was done. One step less to do after a new installation.

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 5919cdf5efd6426627c4e0cfe396ec5e4514a51d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25774">issues.joomla.org/tracker/joomla-cms/25774</a>.</sub>

**Comment by wilsonge** [comment]
Looks like you made a slight mistake in the system tests jform_admin_name but in the xml there your is is jform_admin_user you need to either update the tests or the xml so they match

**Comment by brianteeman** [comment]
@wilsonge corrected and merged. Do I have to update composer again?

**Comment by brianteeman** [comment]
I assume I do so I did

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on ade86cb89a4e10a38f70e95625b1a85e93ede05d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25774">issues.joomla.org/tracker/joomla-cms/25774</a>.</sub>

**Comment by wilsonge** [comment]
You did. Looks happy now!

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Great - thanks

**Pull request merged**
