### PR TITLE
[ACL] Don't explicit add the parent asset permissions on creating a new item + other issues

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
Pull Request for ACL Issues (part 2).
#### Summary of Changes

What this PR does:
- Stop explicit writing the parent asset permissions on creating a new item (module, article, etc). Now all are created with Inhrited in all groups/actions so they Inhrited them.
- Displays the correct calculated permissions in item <-> section(s) <-> component <-> global config scenario.
- On create a new item (module, article, etc) and not saving the Permmission tab calculated are now the component ones.
- Further simplifies the ACL rules code to make it more undertstandable.
- Solves some other minor bugs.

To get the explicit item ACL permission in a item <-> section(s) <-> component <-> global config scenario i had to change JAccess::getAssetRules() behaviour.

**Mantainers** before merging please confirm this is correct and will not have side effects.
###### Information: ACL Inheritance Scenarios

There are four ACL Asset Inheritance scenarios:
- item <-> section(s) <-> component <-> global config
  (ex: article <-> category <-> com_content <-> global config)
- item <-> component <-> global config
  (ex: category <-> com_content <-> global config)
- component <-> global config
  (ex: com_content <-> global config)
- global config (no asset inheritance)

Besides inheriting from the asset(s), ACL also inherits from parent User Group(s).

**Mantainers** please confirm this are the scenarios at play.
###### Pre-requisites

Use latest staging.
Clean install.
###### Test 1: Testing default ACL Inheritance on creating a new iitem

This tests creating a new item without explicit inhreting permissions
- Create a new category "Test ACL" category, don't change anything and save
- Edit the category
- Check category permissions are inhreited form com_config + com_content
- Check there is no explict "Allowed" or "Denied" permission.
- Change one permission to "Denied" and exit
- Now create a new article assign to "Test ACL" category, don't change anything and save
- Now edit the article
- Check the com_config + com_content + category permissions are all inhrited as they should.
- Check there is no explict "Allowed" or "Denied" permission.

Note: You can also check that before the patch the item(s) have explicity "Allowed" or "Denied" permission on create.
###### Test 2: Testing ACL asset/groups Inheritance

This test should be made in sequence.

1: This tests Global config child groups Inherit
- Go to Global config
- Change Public "Delete" to Denied
- Change Public "Edit" to Allowed
- Refresh the page.
- Change Registered "Edit state" to Denied
- Change Registered "Edit Own" to Allowed
- Refresh the page
- Check all Global config Permissions are all inhrited as they should.

2: This tests Global config -> Component Inherit
- Go to Articles (com_content) Config 
- Check the com_config permission are all inhrited as they should.
- Change Author "Edit Own" to Denied
- Refresh the page
- Check the child groups permissions are all inhrited as they should.

3: This tests Global config -> Component -> Item Inherit
- Create new category, name it "Test ACL" don't change anything and save
- Now edit the category
- Check the com_config + com_content permissions are all inhrited as they should.
- Change Editor "Edit" to Denied
- Refresh the page
- Check the child groups  permissions are all inhrited as they should.

4: This tests Global config -> Component -> Section -> Item Inherit
- Create a new article assign to "Test ACL" category, don't change anything and save
- Now edit the article
- Check the com_config + com_content + category permissions are all inhrited as they should.
- Change Manager "Edit" to Denied
- Refresh the page
- Check the child groups  permissions are all inhrited as they should.

You can and should make other tests to confirm all is ok.
###### Test 3: code review

Do a code review.
#### Still known issues (that will not be solved by this PR)

1: When creating a new item (not saving) it uses the calculated permissions from the component (item <-> component <-> global config).
But if we have a section too (item <-> section(s) <-> component <-> global config) this is not correct.
This is a **incorrect info bug**.

2: In "1:", it uses the component permission, but should use the calculated permissions for achild of the component/section.
This is a **incorrect info bug**.

3: If a component as a permission that doesn't exists in global config (ex: frontend editing in com_modules) by default we get "Not Allowed (Inherited)" when we should get "Not Allowed (Default)".
In resume, if doesn't exist in the parent asset it can't Inherit from it.
This is a **incorrect info bug**.

4: When changing a permission of an item that doesn't have a row in the asset table the row a new row is created.
This works fine for item <-> component <-> global config scenario and component <-> global config scenario.
But doesn't work properly for item <-> section(s) <-> component <-> global config scenario because a wrong parent asset id (the component) is stored.
This is a **incorrect ACL bug**, happens when there is no row in the asset table (ex: deleted or not created on update).

Note: This known issues are marked in comments as todo in the code.

@infograf768 @roland-d thanks for all your help on checking this.
And please check.

### CODE REVIEW

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 58adad0345ab2fd8e2ab1c7bfc7737a0c49b12ce<br /><br />
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10894">issues.joomla.org/joomla-cms/10894</a>.</sub>

**Comment by infograf768** [comment]
This solves, among other issues, the default permissions for a child group when the component options denies explicitly.
Example for Modules
Component Permissions for a child of administrator group
screen shot 2016-06-22 at 07 57 57

For a single module for which No permissions have ever been set:

 BEFORE PATCH
screen shot 2016-06-22 at 07 58 41

AFTER PATCH
screen shot 2016-06-22 at 08 06 03

Great work!

**Comment by roland-d** [comment]
I have tested this item :white_check_mark: successfully on 58adad0345ab2fd8e2ab1c7bfc7737a0c49b12ce<br /><br />All tests are successful. Inheritance across children works as described. Inheritance across item -> section -> component -> global level works as expected. Super User status is shown correct as well.

The 4 described scenarios are the ones we have in play as far as I can see. Although a 5th scenario could be added that is for Super Users as they don't play by any rule but their own ;)

Job well done.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10894">issues.joomla.org/joomla-cms/10894</a>.</sub>

**Comment by infograf768** [comment]
We could set it RTC but better, as for the other one, get more testers in this.

**Comment by ggppdk** [comment]
@infograf768

If you would wait a day and i would like to test this too

**Comment by pritalpatel** [comment]
I have tested Test 1 and Test 2 -> 1 without applying patch and found it is already working. using the staging branch.

**Comment by Bodge-IT** [comment]
Also tested but didn't verify as wasn't clear on difference before or after patch, seemed to be same.  Now @pritalpatel has confirmed my suspicion and quelled my confusion.

Think test script: 
4: This tests Global config -> Component -> Extension -> Item Inherit

Should read:
4: This tests Global config -> Component -> Section -> Item Inherit
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10894">issues.joomla.org/joomla-cms/10894</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@pritalpatel @Bodge-IT yes Test 2, part 1, 2 and 3 shoudl already work fine in current staging.

The reason i alk to test all the ACL inhrance system is, is bacause this PR rewrotes some part of the code that affect those parts, and the test are to make sure there are no regressions on this.

If you already made all tests with succes please marthem as tested successfully.

> Think test script: 
> 4: This tests Global config -> Component -> Extension -> Item Inherit
> Should read:
> 4: This tests Global config -> Component -> Section -> Item Inherit

updated

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 58adad0345ab2fd8e2ab1c7bfc7737a0c49b12ce<br /><br />works as described<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10894">issues.joomla.org/joomla-cms/10894</a>.</sub>

**Comment by Bodge-IT** [comment]
I have tested this item :white_check_mark: successfully on 58adad0345ab2fd8e2ab1c7bfc7737a0c49b12ce<br /><br />Tested 1 and 2
All inheritances applied correctly.

Did not review code as per test 3.  I'm not a coder.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10894">issues.joomla.org/joomla-cms/10894</a>.</sub>

**Comment by infograf768** [comment]
@ggppdk 
Just waiting for you now. :)

**Comment by ggppdk** [comment]
I have tested this item :white_check_mark: successfully on 58adad0345ab2fd8e2ab1c7bfc7737a0c49b12ce<br /><br />Tested custom forms, with custom rules, it works !! ))))<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10894">issues.joomla.org/joomla-cms/10894</a>.</sub>

**Comment by pritalpatel** [comment]
I have tested this item :white_check_mark: successfully on 58adad0345ab2fd8e2ab1c7bfc7737a0c49b12ce<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10894">issues.joomla.org/joomla-cms/10894</a>.</sub>

**Comment by infograf768** [comment]
RTC. Thanks to all. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10894">issues.joomla.org/joomla-cms/10894</a>.</sub>

**Comment by RonakParmar** [comment]
While testing first Step after applying patch found JLIB_RULES_NOT_ALLOWED_INHERITED language variable missing. Without patch language variable working fine.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10894">issues.joomla.org/joomla-cms/10894</a>.</sub>

**Comment by RonakParmar** [comment]
I have tested this item :white_check_mark: successfully on 58adad0345ab2fd8e2ab1c7bfc7737a0c49b12ce<br /><br />After applied patch found : In Test 1: Testing default ACL Inheritance on creating a new item JLIB_RULES_NOT_ALLOWED_INHERITED missing language variable.

In Test 2: Testing ACL asset/groups Inheritance found JLIB_RULES_NOT_ALLOWED_DEFAULT, JLIB_RULES_NOT_ALLOWED_INHERITED, JLIB_RULES_ALLOWED_INHERITED missing language variables.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10894">issues.joomla.org/joomla-cms/10894</a>.</sub>

**Comment by RonakParmar** [comment]
Missing language variables.screen shot 2016-06-24 at 07 54 03<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10894">issues.joomla.org/joomla-cms/10894</a>.</sub>

**Comment by brianteeman** [comment]
It is not a successful test then

On 24 June 2016 at 13:54, RonakParmar <notifications@github.com> wrote:

> Missing language variables.[image: screen shot 2016-06-24 at 07 54 03]
> <https://camo.githubusercontent.com/9d49e4d867fc727eb69f52720114b69273ffddf8/68747470733a2f2f6973737565732e6a6f6f6d6c612e6f72672f75706c6f6164732f312f66623938666162343764366333646338343038643662373133356132393066642e706e67>
> ------------------------------
> This comment was created with the J!Tracker Application
> <https://github.com/joomla/jissues> at issues.joomla.org/joomla-cms/10894
> <https://issues.joomla.org/tracker/joomla-cms/10894>.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/10894#issuecomment-228337881>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABPH8Q3UKtZVLEkJYLqjBcXjvMzkfUGiks5qO9N5gaJpZM4I63bF>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by RonakParmar** [comment]
Given steps are working fine as described. So, I have made it successful test.

**Comment by andrepereiradasilva** [comment]
@RonakParmar are you using the latest staging?

That language vars where added in a recent PR. See
https://github.com/joomla/joomla-cms/commit/b982eece934793d64d72f9ab66b40ab823a44878#diff-fa3a45e6746f58d4a54e42207ee8f4adR669

**Comment by brianteeman** [comment]
If you are seeing untranslated strings then it is not a successful test

**Comment by RonakParmar** [comment]
Here is my System Information:

Joomla! Version : Joomla! 3.6.0-beta2-dev Development [ Noether ] 9-June-2016 12:33 GMT 
Joomla! Platform Version: Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT 
User Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:47.0) Gecko/20100101 Firefox/47.0 

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10894">issues.joomla.org/joomla-cms/10894</a>.</sub>

**Comment by RonakParmar** [comment]
@andrepereiradasilva Thank you to update me, I have downloaded current staging branch zip and installed in my system, Language variable are working fine with latest zip.

**Comment by andrepereiradasilva** [comment]
ok thanks. so all ok.

**Comment by andrepereiradasilva** [comment]
As an additional info, please notice this PR, as it is, also solves a regression from latest ACL PR (already merged).

To check it do the following.

Use a clean 3.5.1 install
- New category "Test ACL Category", don't change anything and save
- Edit category "Test ACL Category" and change "Editor" "Edit" action from "Allowed" to "Denied" and save
- Create a new article "Test ACL Article", don't change anything and save
- Edit article "Test ACL Article" and check "Editor" calculated permission for "Edit" action check is "Not Allowed (Locked)".

Do the same steps on Joomla staging (check the calculated permission is "Allowed").
This is the regression. The section -> item ACL calculated permissions inheritance.

Apply patch, check the calculated permission is "Not Allowed (Locked)".

**Comment by wilsonge** [comment]
Thanks guys

**Pull request merged**
