### PR TITLE
[4.0] editor-xtd buttons - cassiopeia

### PR DESCRIPTION
**Pull request by brianteeman**
Same as #32200 but for the frontend cassiopeia template

### CODE REVIEW

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on e3b78bfda22313cf31680c717c6c69b6c0d92b0f<br /><br />on review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32221">issues.joomla.org/tracker/joomla-cms/32221</a>.</sub>

**Comment by brianteeman** [comment]
Please do a real test as the structure in cassiopeia _might_ be different

**Comment by infograf768** [comment]
I had already tested when I commented https://github.com/joomla/joomla-cms/pull/32200#issuecomment-770345391

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on e3b78bfda22313cf31680c717c6c69b6c0d92b0f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32221">issues.joomla.org/tracker/joomla-cms/32221</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32221">issues.joomla.org/tracker/joomla-cms/32221</a>.</sub>

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
