### PR TITLE
[4.3] Media manager: add the missing lock component

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # .

### Summary of Changes

- Adds the missing tabs-lock component
- Fixes accessibility issues on media manager modals

### Testing Instructions

- Apply the PR and run `npm ci`
- Open the rename, create new folder, preview, get link and delete modals and check that the tab is locked inside the modal. That's it

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

Side effect the codemirror is updated because of the ranges in the package.json

### CODE REVIEW

**Comment by brianteeman** [comment]
I assume the codemirror changes are not part of this pr?

**Comment by dgrammatiko** [comment]
> I assume the codemirror changes are not part of this pr?


Actually the lock **already uses the 5.65.11** https://github.com/joomla/joomla-cms/blob/7f7e2324b62562b8872142cc68d6422a30a2dd62/package-lock.json#L3152-L3156 I just added the missing XML parts here. This is related to the allowed ranges in the package.json which leads to such inconsistencies (and most of the times they're unnoticed). Just switch to specific versions, whatever is written in the can (package.json) is getting installed!!!

**Comment by richard67** [comment]
Hmm, the package lock shows also an update of the skipto plugin from 4.1.6 to 4.1.7. Ok for me, but not related to this PR and I'm not sure if ok regarding our rules for beta phase.

**Comment by dgrammatiko** [comment]
> Hmm, the package lock shows also an update of the skipto plugin from 4.1.6 to 4.1.7

Richard, this is once again a problem deriving from the decision to use ranges in the versions when, for a project of this scale, the `npm i` and `npm ci` should return the **SAME** node_modules folder. FWIW the package.json has the correct version `4.1.7` https://github.com/joomla/joomla-cms/pull/39833/files#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R66 which for whatever reason was reflected wrongly in the lock file. The production team needs to set some rules on how and by whom the package-lock.json and the package.json could be modified. There are too many mistakes...

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 3a204290574de137fe7549ebb988c4cf80e78d05<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39833">issues.joomla.org/tracker/joomla-cms/39833</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 3a204290574de137fe7549ebb988c4cf80e78d05<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39833">issues.joomla.org/tracker/joomla-cms/39833</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39833">issues.joomla.org/tracker/joomla-cms/39833</a>.</sub>

**Comment by obuisard** [comment]
Thank you Dimitris @dgrammatiko for the PR!

**Pull request merged**
