### PR TITLE
[4.0] Alpha sort use statements

### PR DESCRIPTION
**Pull request by Quy**
### Testing Instructions

Merge on code review.

### CODE REVIEW

**Comment by joomdonation** [comment]
I have tested this item :white_check_mark: successfully on 71391995ceea06252dfbf6fb50360c4755d48d50<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34103">issues.joomla.org/tracker/joomla-cms/34103</a>.</sub>

**Comment by PhilETaylor** [comment]
I have tested this item :white_check_mark: successfully on 71391995ceea06252dfbf6fb50360c4755d48d50<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34103">issues.joomla.org/tracker/joomla-cms/34103</a>.</sub>

**Comment by joomdonation** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34103">issues.joomla.org/tracker/joomla-cms/34103</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34103">issues.joomla.org/tracker/joomla-cms/34103</a>.</sub>

**Comment by Quy** [comment]
Thank you!

**Pull request merged**
