### PR TITLE
[4.0] [tpl_protostar] Delete pagination.php in protostar template (deprecated)

### PR DESCRIPTION
**Pull request by coolcat-creations**
### Summary of Changes
This PR just removes the pagination.php for the new installations because this method to override the pagination is deprecated and might be confusing.

The new place to override this is in the path layouts/joomla/pagination/

### Testing Instructions

Apply patch and see if still all paginations are shown correctly.

image

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on c153c0ce54994c5cb4442a0adb8fb1dfe2f2f44f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14191">issues.joomla.org/tracker/joomla-cms/14191</a>.</sub>

**Comment by dgt41** [comment]
@coolcat-creations can you add the file you are removing also here: https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_admin/script.php#L580

thanks

**Comment by coolcat-creations** [comment]
@dgt41 done - but if someone is using the deprecated method it will hopefully not be deleted with that? Thanks!

**Comment by wilsonge** [comment]
Umm protostar isn't using the new methods. If you're going to delete this file you need to replace it with the 'correct' way of doing things with JLayout's :)

**Comment by zero-24** [comment]
> Umm protostar isn't using the new methods. If you're going to delete this file you need to replace it with the 'correct' way of doing things with JLayout's :)

Does protostar not just using the default? So there is no need to override it via the template? @wilsonge

**Comment by wilsonge** [comment]
I don't think protostar is using the default (hence why it has an override and why @franz-wohlkoenig is seeing a change in the behaviour). I don't know if the override is really necessary tho? @coolcat-creations is the designer amongst us :)

**Comment by coolcat-creations** [comment]
The pagination.php is deprecated but still can be used due to BC.

You see it in the pagination/pagination.php among others in line 526
`		// Keep B/C for overrides done with chromes
		$chromePath = JPATH_THEMES . '/' . $this->app->getTemplate() . '/html/pagination.php';`

In fact jLayout is the way to do it. I don´t want to delete existing pagination.php with this PR, i just want to remove these deprecated files. 

As Protostar is not using overrides it does use the core layouts which are already all rewritten for the frontend. The pagination.php in isis still has to remain.

**Comment by coolcat-creations** [comment]
Any decision on this?

**Comment by mbabker** [comment]
Honestly, I'd say just leave it alone until 4.0.  It's not hurting anything right now.

**Comment by coolcat-creations** [comment]
It wouldn´t hurt either to remove it :-) It´s deprecated as written in the file comments and useless... ;) But you decide...

**Comment by mbabker** [comment]
There are markup differences between what https://github.com/joomla/joomla-cms/blob/staging/layouts/joomla/pagination/link.php produces and what the current file produces.  So it will hurt to remove it by causing changes to the output (the most glaring change is the `hidden-phone` class on items).

**Comment by coolcat-creations** [comment]
ok

**Comment by brianteeman** [comment]
Re-opening and marking to be re-evaluate for J4.

**Comment by mbabker** [comment]
Protostar's gone in 4.0, what's to re-evaluate?

**Comment by brianteeman** [comment]
\libraries\src\CMS\Pagination\Pagination.php

so that we are sure that we are using the layout now and that the deprecated code there is in fact removed

**Comment by mbabker** [comment]
https://github.com/joomla/joomla-cms/tree/4.0-dev/templates/aurora/html - No override there, so we're good on that part.

https://github.com/joomla/joomla-cms/tree/4.0-dev/administrator/templates/atum/html - That one's using the file, need to get that right.

Then, we just need to finish the removal of deprecated code in the class supporting the `html/pagination.php` file in templates.

**Comment by coolcat-creations** [comment]
And we need to check all the core views where pagination is implemented.  It´s implemented always in a slightly different way.

**Comment by brianteeman** [comment]
Closing. As far as i can tell j4 is no longer using an override anywhere

**Pull request closed without merging**
