### PR TITLE
[4.0] add missing quote i incomplete.html

### PR DESCRIPTION
**Pull request by wojsmol**
Pull Request for Issue # .
### Summary of Changes
Adding missing `"`
### Testing Instructions
code review
### Documentation Changes Required

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 2354751180270f045c44a4522906163c5a7ce4ad<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21352">issues.joomla.org/tracker/joomla-cms/21352</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 2354751180270f045c44a4522906163c5a7ce4ad<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21352">issues.joomla.org/tracker/joomla-cms/21352</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Comment by dgrammatiko** [comment]
Can we please close this PR as there is another one already that covers a bit more than the quote: 
https://github.com/joomla/joomla-cms/pull/21331

**Pull request closed without merging**
