### PR TITLE
Password field using JLayout

### PR DESCRIPTION
**Pull request by dgrammatiko**
#### Separate logic/ output

Base work for better templating
#### Summary of Changes

Introduce a  layout for this field
#### Testing Instructions

Apply patch and rename any backend input to password
eg

``` XML
<field name="mytextvalue" type="password" default="Some text" label="Enter some text" description="" size="10" />
```

Also consult: https://docs.joomla.org/Standard_form_field_types

### CODE REVIEW

**Comment by RonakParmar** [comment]
I have tested this item :white_check_mark: successfully on 0600cc4408b81fce7ddf74db928b0a7a629d40d0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11003">issues.joomla.org/joomla-cms/11003</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 0600cc4408b81fce7ddf74db928b0a7a629d40d0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11003">issues.joomla.org/joomla-cms/11003</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11003">issues.joomla.org/joomla-cms/11003</a>.</sub>

**Comment by wilsonge** [comment]
Merged with 02ccfa2 - Thanks!

**Pull request closed without merging**
