### PR TITLE
[4.0] namespace JCache

### PR DESCRIPTION
**Pull request by brianteeman**
Fix some missing namespace changes or JCache

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on cad5e16cd86103e9092cb08db098ea8975b73b3d<br /><br />Code review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27365">issues.joomla.org/tracker/joomla-cms/27365</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on cad5e16cd86103e9092cb08db098ea8975b73b3d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27365">issues.joomla.org/tracker/joomla-cms/27365</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27365">issues.joomla.org/tracker/joomla-cms/27365</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
