### PR TITLE
[5.1] New Article site

### PR DESCRIPTION
**Pull request by brianteeman**
If you are authorised to create content on the front end of the site then in a category list view you have an edit button for each article and a button to create a new article

If you are authorised to create content on the front end of the site then in a category blog view you have an edit button for each article and NO button to create a new article

This PR adds a new article button to a category blog view

To test
Apply PR
Log in to the front end of your site and go to any blog category page and you will now have a new article button at the bottom

image

### CODE REVIEW

**Comment by Kostelano** [comment]
It works. But the button looks so out of place that I will leave my vote against. Without speaking in principle about the button at the very end of the page, when there can be quite a lot of articles on it like for a blog, there is also an option when the blog is the main page and this button also looks out of place. As for me - the ability to create articles is better controlled by any menu item in any menu in the right place. In principle, the same situation applies to the LIST layout, where we currently have a create button.

**Comment by brianteeman** [comment]
Going to ignore those comments. This is no different to the list view

**Comment by Catriona** [comment]
See issue  [#39558](https://issues.joomla.org/tracker/joomla-cms/39558 "link to issue"), there is a problem with the New Article button on the list view in that it uses the wrong category. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39506">issues.joomla.org/tracker/joomla-cms/39506</a>.</sub>

**Comment by HLeithner** [comment]
This pull request has been automatically rebased to 5.1-dev.

**Comment by dorisdreher** [comment]
I have tested this item :white_check_mark: successfully on b2c6654cb329b6c28a955a60e1cd0d7b9ccca863<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39506">issues.joomla.org/tracker/joomla-cms/39506</a>.</sub>

**Comment by faustonenci** [comment]
I have tested this item :white_check_mark: successfully on b2c6654cb329b6c28a955a60e1cd0d7b9ccca863<br /><br />good work<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39506">issues.joomla.org/tracker/joomla-cms/39506</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39506">issues.joomla.org/tracker/joomla-cms/39506</a>.</sub>

**Comment by brianteeman** [comment]
That is expected behaviour

**Comment by hl-dev-DE** [comment]
I have tested this item :white_check_mark: successfully on b2c6654cb329b6c28a955a60e1cd0d7b9ccca863<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39506">issues.joomla.org/tracker/joomla-cms/39506</a>.</sub>

**Comment by pe7er** [comment]
I have tested this item :white_check_mark: successfully on b2c6654cb329b6c28a955a60e1cd0d7b9ccca863<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39506">issues.joomla.org/tracker/joomla-cms/39506</a>.</sub>

**Comment by walturbo** [comment]
I have tested this item :white_check_mark: successfully on b2c6654cb329b6c28a955a60e1cd0d7b9ccca863<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39506">issues.joomla.org/tracker/joomla-cms/39506</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Comment by brianteeman** [comment]
Thanks all

**Pull request merged**
