### PR TITLE
[HTTPS] Sample data

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Summary of Changes

This PR changes all http:// URI in sample data that use sites exclusive in HTTPS to https://
#### Testing Instructions
1. Install Joomla staging with sample data from this PR (https://github.com/andrepereiradasilva/joomla-cms/archive/promote-https-sampledata.zip)
2. Check the URLs of sample data after install are HTTPS
#### Observations

After this PR, the only URI that are not in HTTPS in sample data are:
- http://forum.joomla.org/*
- http://extensions.joomla.org/*
- http://community.joomla.org/*
- http://resources.joomla.org/*
- http://feeds.joomla.org/*
- http://friendfeed.com/joomla (this seems to not exist anymore)

I didn't change this ones because they are still only HTTP or not exclusive HTTPS.

### CODE REVIEW

**Comment by brianteeman** [comment]
Friendfeed was only used as a sample contact link - we could replace it but not worth the effort<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9385">issues.joomla.org/joomla-cms/9385</a>.</sub>

**Comment by andrepereiradasilva** [comment]
ok

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 82d9b6d09ff9d3d21e31f17c6518b085796bce05<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9385">issues.joomla.org/joomla-cms/9385</a>.</sub>

**Comment by waader** [comment]
I have tested this item :white_check_mark: successfully on 82d9b6d09ff9d3d21e31f17c6518b085796bce05<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9385">issues.joomla.org/joomla-cms/9385</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9385">issues.joomla.org/joomla-cms/9385</a>.</sub>

**Pull request merged**
