### PR TITLE
[5.2] Spelling

### PR DESCRIPTION
**Pull request by brianteeman**
attachement => attachment

code review only

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 3c8c9d87c671a063546149cf3f1319b313cc2c93<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43985">issues.joomla.org/tracker/joomla-cms/43985</a>.</sub>

**Comment by sandewt** [comment]
I have tested this item :white_check_mark: successfully on 3c8c9d87c671a063546149cf3f1319b313cc2c93<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43985">issues.joomla.org/tracker/joomla-cms/43985</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43985">issues.joomla.org/tracker/joomla-cms/43985</a>.</sub>

**Comment by Quy** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
