### PR TITLE
[4.2] contact fields remove layout override

### PR DESCRIPTION
**Pull request by brianteeman**
com_contact has two types of fields mail and contact. mail are for fields that are added to the contact form. contact is for fields that are displayed with the contact details.

at some point in time a layout override was added for this. Its fubar and not actually needed because the rendering of the different field contexts is already handled in the views (defaulkt_form and default_custom_user_fields)

the main issues caused by these overrides is that the contact fields are not rendered the same as they would have been for an article (dt not dl) and the display of subforms is obviously completely wrong.

#### 1. Com content

- Create 3 text fields
- Create 1 subform field containing the 3 text fields
- create article and complete the fields

#### 2.  com contact - context contact

- Create 3 text fields
- Create 1 subform field containing the 3 text fields
#### 3. com contact - context mail
- Create 3 text fields
- Create 1 subform field containing the 3 text fields

##### 4. test
- create contact and complete the fields
- compare the display of the fields in the front end 

### Expected result
Fields are displayed the same across the two components

### Actual result
com_contact has a field layout override that uses a dl etc instead of a ul AND the subform display is fubar

#### com_content
image

#### com_contact
image

image

### After PR
image

### Additional comments
@richard67 I cant remember if i am supposed to add these removed files to script.php or if you deal with it?

@bembelimen @roland-d to me this is a bug fix and should be in 4.1 but I suspect you will say it needs to go in 4.2?

### CODE REVIEW

**Comment by richard67** [comment]
> @richard67 I cant remember if i am supposed to add these removed files to script.php or if you deal with it?

@brianteeman I will deal with it.

**Comment by brianteeman** [comment]
looks like the psr12 pull requests completely messed up this pr :(

**Comment by brianteeman** [comment]
fixed the issues from the psr12 pr

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on ba7d87f82d59f02b1d1c2e231d744c6c5f9f059b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37716">issues.joomla.org/tracker/joomla-cms/37716</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on ba7d87f82d59f02b1d1c2e231d744c6c5f9f059b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37716">issues.joomla.org/tracker/joomla-cms/37716</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37716">issues.joomla.org/tracker/joomla-cms/37716</a>.</sub>

**Comment by richard67** [comment]
@brianteeman Could you dove the conflict? Thanks in advance.

**Comment by brianteeman** [comment]
> @brianteeman Could you solve the conflict? Thanks in advance.

done as requested

**Comment by richard67** [comment]
RTC is still valid because the commit after the human tests was a clean conflict resolution. The conflict was in file "render.php" and came from PR #39616 , which changed array syntax in that file which is then removed with this PR here.

**Comment by fancyFranci** [comment]
Thank you! :)

**Comment by laoneo** [comment]
This pr broke the way custom fields are rendered in mails. Now the contain the HTML code as when they get rendered in a web page. Please test #40557 which restores the old behavior while keeping the new feature from this pr when rendered in a web page.

**Pull request merged**
