### PR TITLE
Correct username in plg_actionlog

### PR DESCRIPTION
**Pull request by tecpromotion**
### Summary of Changes

In the User Actions Log extension, the user is always used in the output. The exception is the log entries related to the cache. Here, the user name is always used instead of the user.

With the change now value username is used instead of value name.

### Testing Instructions

Create a new user with
name = Super User
and
username = test

### Expected result

User **test** deleted cache group all

### Actual result

User **Super User** deleted cache group all

### Documentation Changes Required

--

### CODE REVIEW

**Comment by brianteeman** [comment]
Also see #24862

**Comment by degobbis** [comment]
I have tested this item :white_check_mark: successfully on c3f150075119dc79c0a3a2b18bde25c010bebb24<br /><br />thx<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24992">issues.joomla.org/tracker/joomla-cms/24992</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on c3f150075119dc79c0a3a2b18bde25c010bebb24<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24992">issues.joomla.org/tracker/joomla-cms/24992</a>.</sub>

**Comment by zero-24** [comment]
Merging thanks.

**Comment by infograf768** [comment]
The filter by user is still using `name` and not `username`
This PR implies changes to the `logcreator` field.

Without a modification here I get
Screen Shot 2019-06-22 at 09 16 48

Issue solved if modifying the query to use `username` and not `name`
```
// Construct the query
			$query = $db->getQuery(true)
				->select($db->quoteName('u.id', 'value'))
				->select($db->quoteName('u.username', 'text'))
				->from($db->quoteName('#__users', 'u'))
				->join('INNER', $db->quoteName('#__action_logs', 'c') . ' ON ' . $db->quoteName('c.user_id') . ' = ' . $db->quoteName('u.id'))
				->group($db->quoteName('u.id'))
				->group($db->quoteName('u.username'))
				->order($db->quoteName('u.username'));
```

**Comment by zero-24** [comment]
@infograf768 can you send the required changes as PR?

**Comment by infograf768** [comment]
TBH, I am not sure about the whole thing
Yes, what is logged should be consistent BUT imho it should be the name and not the username displayed in the logs.
The reason is that the `username` is also the Login Name and this could be a security breach.
What do you think?

**Comment by infograf768** [comment]
This means that we have to do the reverse of that PR, i.e. use ->name everywhere and keep the filter as is.

**Comment by degobbis** [comment]
I do not see a security breach here. If you can see the action logs, then you can also access the users component and see the usernames. The improvement is that the username is unique and therefore faster to allocate.

**Comment by infograf768** [comment]
You are right that the name is not unique indeed (which is weird btw...).

Note: it is always the Name which is displayed in the Managers and Created by field (and its modal), which imho demonstrates that we should make the Name unique too...

**Comment by degobbis** [comment]
I don't think the name should be unique. 
For a clear identification we already have 2 values, username and e-mail address. That's enough, or not?

But if it causes such far-reaching changes, is it perhaps sufficient to write the username in parentheses after the names in the output?
What do you all mean?

**Comment by infograf768** [comment]
Please test
https://github.com/joomla/joomla-cms/pull/25291

Going further would need more important changes and should imho be reserved to J4.

**Comment by infograf768** [comment]
BTW, why keep using `->name` in `onUserAfterRemind($user)`
It is not consistent imho.

**Comment by HLeithner** [comment]
username is unique, the name isn't. so imo it's better to use username

**Comment by brianteeman** [comment]
we must not make "name" unique. That would be terribly restrictive. Even with my almost unique family name there are two "brian teeman"

**Comment by HLeithner** [comment]
thats the reason that we stay with username instead using name.

**Comment by infograf768** [comment]
Understood that. Tks.

**Pull request merged**
