### PR TITLE
Update Tinymce

### PR DESCRIPTION
**Pull request by brianteeman**
#### Summary of Changes

Update tinymce to the latest version
#### Testing Instructions

Check that tnymce works as before and dont forget to test simple, advanced and extended modes which you can choose in the plugin options

### CODE REVIEW

**Comment by brianteeman** [comment]
Because this pull request includes binary files you can not test this with com_patchtester. You will either have to use git directly OR you can download a complete joomla install with this patch already applied from https://github.com/brianteeman/joomla-cms/archive/tinymce.zip

**Comment by infograf768** [comment]
version? 4.3.9 I guess. Needs change in the xml.

**Comment by brianteeman** [comment]
4.3.10 - and done - thanks for spotting

On 16 April 2016 at 20:48, infograf768 <notifications@github.com> wrote:

> version? 4.3.9 I guess. Needs change in the xml.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/9948#issuecomment-210872817>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by mikeveeckmans** [comment]
I have tested this item :white_check_mark: successfully on 6120898d613dd0bbdb517c766a8a45c6086501bb<br /><br />tested with provided joomla install<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9948">issues.joomla.org/joomla-cms/9948</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 6120898d613dd0bbdb517c766a8a45c6086501bb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9948">issues.joomla.org/joomla-cms/9948</a>.</sub>

**Comment by brianteeman** [comment]
Set RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9948">issues.joomla.org/joomla-cms/9948</a>.</sub>

**Pull request merged**
