### PR TITLE
Improve PR #37772 - inlineHelp Toggle Button control

### PR DESCRIPTION
**Pull request by cyrez**
Improve Pull Request #37819 for Issue #37772 

### Summary of Changes
Following @nikosdion comment https://github.com/joomla/joomla-cms/pull/35610#issuecomment-1132808982 and https://github.com/joomla/joomla-cms/pull/35610#issuecomment-1129741641 

This PR removes the ability to set an attribute inlineHelp to the form field xml element.

I agree with @nikosdion on his statement, and so i have improved and simplified here my previous PR to only focus on fixing issue with hidden descriptions if no inlinehelp toggle button integrated.

### Testing Instructions
**Same as for previous PR #37819**
- Check if descriptions are hidden by default in com_config and com_content options.
- Check if descriptions are shown by default everywhere else (where toggle button is not integrated) : component options, item edition, plugins manager... and in third-party extensions not integrating the toggle button.
- Toggle button works as expected in com_config and com_content

### CODE REVIEW

**Comment by Kostelano** [comment]
I have tested this item :white_check_mark: successfully on 12d907661e2d27bb6618c9d910b41332a00b28d8<br /><br />Everything still works well.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37849">issues.joomla.org/tracker/joomla-cms/37849</a>.</sub>

**Comment by nikosdion** [comment]
I approve of this change. Having been the one asking for it I am not sure if it's proper for me to provide a test? If so, let me know and I will.

**Comment by conseilgouz** [comment]
I have tested this item :white_check_mark: successfully on 12d907661e2d27bb6618c9d910b41332a00b28d8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37849">issues.joomla.org/tracker/joomla-cms/37849</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37849">issues.joomla.org/tracker/joomla-cms/37849</a>.</sub>

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
