### PR TITLE
[4.0] menu dashboard

### PR DESCRIPTION
**Pull request by brianteeman**
Add the missing title to the add new site and new admin menu items on the menus dashboard

image

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on c70e6877028682d18651c4b71ca386006edca1bf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27290">issues.joomla.org/tracker/joomla-cms/27290</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on c70e6877028682d18651c4b71ca386006edca1bf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27290">issues.joomla.org/tracker/joomla-cms/27290</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27290">issues.joomla.org/tracker/joomla-cms/27290</a>.</sub>

**Comment by infograf768** [comment]
tks

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
