### PR TITLE
Send Test Mail button - Ajax call has always smtpauth = 1

### PR DESCRIPTION
**Pull request by anibalsanchez**
Pull Request for Issue #9768 / #9803
#### Summary of Changes

Send Test Mail button does not correctly evaluate "SMTP Authentication" radio. Then, mails are sent via SMTP even when "SMTP Authentication" is disabled.

Fix: smtpauth : $('input[name="jform[smtpauth]"]:checked').val(),

The problem is found when your fill all SMTP credentials and keep "SMTP Authentication"=No... it applies the credentials even when it is disabled.

In this PR, I have modified the code to really check for the "SMTP Authentication" radio value.

_Steps to reproduce the issue_
- Fill all SMTP fields in Mail Settings for a SMTP server that requires authentication
- But, don't enable SMTP Authentication
- Send Test Mail button sends emails even when the radio is disabled
#### Testing Instructions
1. Fill all SMTP fields in Mail Settings for a SMTP server that requires authentication
2. Test it, click on 'Send Test Mail' button to receive an email
3. Disable "SMTP Authentication" radio
4. Test it, click on 'Send Test Mail' button ... email must not be received and error is shown about the failed authentication

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
Ok. I tested this.

Without patch i get. Mail is sent (i think is sent with php mail fallback - see https://github.com/joomla/joomla-cms/issues/9680) and i get:

> The email was sent successfully to config-from-email@example.com using SMTP. You should check that you've received the test email.

With patch i get. Mail is not sent and i get:

> Test mail could not be sent.
> SMTP Error: The following recipients failed: config-from-email@example.com: : Recipient address rejected: Access denied

So is this a success?

**Comment by anibalsanchez** [comment]
@andrepereiradasilva Yes, it is a success! Mail must be rejected when authentication is disabled and the server requires authentication.

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 81e541c7fee95bd1604cefb6d5744a581d67c00c<br /><br />as comments above<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9904">issues.joomla.org/joomla-cms/9904</a>.</sub>

**Comment by henkrijneveld** [comment]
I have tested this item :white_check_mark: successfully on 81e541c7fee95bd1604cefb6d5744a581d67c00c<br /><br />Mail without authentication is now send with the "send test e-mail" button. 

Thx for solving this, I ran into this issue earlier.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9904">issues.joomla.org/joomla-cms/9904</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9904">issues.joomla.org/joomla-cms/9904</a>.</sub>

**Pull request merged**
