### PR TITLE
[4.4] Improve message when author is deleted

### PR DESCRIPTION
**Pull request by chmst**
Pull Request for Issue # .

### Summary of Changes
If a user record  has been deleted his articles cannot be stored any more. Now the message says what the user can do to solve the problem. 

### Testing Instructions
Simplest way:
Open #__content table and  change the created_by id of an article to a non-existing userId. 
Then try to change this article in the backend. 

### Actual result BEFORE applying this Pull Request

grafik

### Expected result AFTER applying this Pull Request

grafik

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
This works correctly for the author field

However it displays the same message for the modified field. That one cannot be corrected as its readonly. Just saving the article fixes that one.

**Comment by Fedik** [comment]
This is general message, which comes from User class, anytime it cannot find a user https://github.com/joomla/joomla-cms/blob/1e7527b60ec42032abe7bfb9c000bacf38f65845/libraries/src/User/User.php#L819

To me, this message should not be show up, maximum just logged. But in past someone complain "that it is right to show it up". I do not remember detail anymore :)

**Comment by chmst** [comment]
There were long discussions and and as long as we don't have a solution how to process deletion of users, We could only improve the message. 
BTW: my opinion is: Don't allow to delete userenties, just trash and make anonymous. 

@brianteeman thanks, I did not see that. So me need different messages for different cases.

**Comment by Fedik** [comment]
> It always looks likee a bug when it is not possible to save an article.

Yeah I understood. I think it can be a message for each user field. Kind of:
```xml
<field
  name="created_by"
  type="user"
  label="COM_CONTENT_FIELD_CREATED_BY_LABEL"
  validate="UserId"
  message="A valid User ID is required, please make sure User is selected."
/>
```

**Comment by chmst** [comment]
A rule on the field looks good. 
I ask myself why we need to check the modified_id? It is overwritten by the current users id on save and has no relevance on other places. Or am I missing something?

**Comment by brianteeman** [comment]
> A rule on the field looks good. 

Agreed - a nice solution that allows better error messages

> I ask myself why we need to check the modified_id? It is overwritten by the current users id on save and has no relevance on other places. Or am I missing something?

It _might_ be useful to know that the last person who modified the content is no longer an active member. But only as an information.

**Comment by Fedik** [comment]
The rule already in that form (I copied form there), only need to add an attribute `message="Blabla validation error"`

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on 8b325982356a464b0db7c6b7d81ed90973c81f30<br /><br />Tested succcessfully in Joomla 4.3.0-rc3-dev of 4 April using PHP 8.1.16<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40269">issues.joomla.org/tracker/joomla-cms/40269</a>.</sub>

**Comment by chmst** [comment]
Sorry to say that but this pr is not ready and I set it to draft. The messag is misleading if the modified_by user is deleted.

**Comment by HLeithner** [comment]
This pull request has been automatically rebased to 4.4-dev.

**Comment by chmst** [comment]
Closing see #41048

**Pull request closed without merging**
