### PR TITLE
Drone errors

### PR DESCRIPTION
**Pull request by zero-24**
### Summary of Changes

fix drone errors after #17481

### Testing Instructions

review

### Expected result

drone passes 

### Actual result

http://213.160.72.75/joomla/joomla-cms/7764

### Documentation Changes Required

none

### CODE REVIEW

**Comment by Quy** [comment]
Shouldn't it be one less tab?

**Comment by richard67** [comment]
I think Quy is right.

**Comment by zero-24** [comment]
Done

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 1293b814a5d9a8cc7fdf506b122e646b15c5bc12<br /><br />Code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17526">issues.joomla.org/tracker/joomla-cms/17526</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 1293b814a5d9a8cc7fdf506b122e646b15c5bc12<br /><br />Code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17526">issues.joomla.org/tracker/joomla-cms/17526</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17526">issues.joomla.org/tracker/joomla-cms/17526</a>.</sub>

**Comment by wilsonge** [comment]
Thanks Tobias :)

**Comment by zero-24** [comment]
Thanks 😄

**Pull request merged**
