### PR TITLE
Deprecating "new" MVC for 4.0 instead of 5.0

### PR DESCRIPTION
**Pull request by Hackwar**
This is an accompanying PR to #24714. The aim is to deprecate the "new" MVC classes for 4.0 instead of 5.0.

### CODE REVIEW

**Comment by mbabker** [comment]
Concerns with this PR addressed in the accompanying "remove this crap" PR.

**Comment by richard67** [comment]
@Hackwar Still wanna leave this and #24714 open after feedback as in #24714 ?

**Comment by Hackwar** [comment]
yes

**Comment by SharkyKZ** [comment]
Closing this as https://github.com/joomla/joomla-cms/pull/24714 was closed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24715">issues.joomla.org/tracker/joomla-cms/24715</a>.</sub>

**Pull request closed without merging**
