### PR TITLE
[4.0] Change spacer text to fieldset description

### PR DESCRIPTION
**Pull request by infograf768**
### Summary of Changes
When a spacer field of class text is used to give information when creating some menu items, the display used is a 3 columns and text may be truncated.

This PR deletes these spacer fields and adds the necessary text as a description of the fieldset.
To prevent that description to be displayed as a block which may not be aligned to the fieldset fields, it is moved over the 3 columns layout and margin is modified to fit (margin test needs using npm).

### Testing Instructions
Edit some items containing such spacers.
Example below is `List All Categories` `Category` tab.

**Note:** 
1. The `Shared` tab is already using a fieldset description, therefore its display is also modified to be shown on top of the 3 columns.
2. The string `JGLOBAL_SUBSLIDER_DRILL_CATEGORIES_LABEL` does not need anymore the `<br>` in the value to force new lines which was useful in 3.x but unecessary in J4 with this PR.

### Before patch
fieldset_spacer_before

### After patch

fieldset_spacer_after

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 401e24cc767c1ecf50cace08266d2fa2aee777d6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28737">issues.joomla.org/tracker/joomla-cms/28737</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 401e24cc767c1ecf50cace08266d2fa2aee777d6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28737">issues.joomla.org/tracker/joomla-cms/28737</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28737">issues.joomla.org/tracker/joomla-cms/28737</a>.</sub>

**Comment by zero-24** [comment]
Merged thanks :+1:

**Pull request merged**
