### PR TITLE
[4.0] Remove variable for 0 items for language strings

### PR DESCRIPTION
**Pull request by brianteeman**
PR for #27173

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on c5c759c5a7435ce9a0bedd841a0b123c201bb624<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27177">issues.joomla.org/tracker/joomla-cms/27177</a>.</sub>

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on c5c759c5a7435ce9a0bedd841a0b123c201bb624<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27177">issues.joomla.org/tracker/joomla-cms/27177</a>.</sub>

**Comment by SharkyKZ** [comment]
RTC.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27177">issues.joomla.org/tracker/joomla-cms/27177</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thank you

**Pull request merged**
