### PR TITLE
MSSQL - fix install extensions crash

### PR DESCRIPTION
**Pull request by alikon**
#### Steps to reproduce the issue

try to install an extension for example the com_patchtester or the pkg_weblinks or....
#### Expected result

extension installed or some error msgs
#### Actual result

joomla crash 
the issue is better described here #5890
#### System information

Windows 2008 R2 10.50.4033
Apache  2.4.7
PHP 5.5.9
Joomla! 3.4.2-dev
#### Additional comments

now handle the exception that was unhandled  #5890

  Installation of a module  #5850
  Add a new menu item to the Main Menu #4207

### CODE REVIEW

**Comment by wilsonge** [comment]
Merge conflicts

**Comment by alikon** [comment]
should be resolved

**Comment by waader** [comment]
As I don´t know how to make a package of the weblinks component from the github repository I tested with com_patchtester. I could reproduce the problem and successfully install the component after applying the patch.

With the patch applied I tested also mysql and postgres. On postgres the installation of com_patchtester went well in the first place but when I invoked patchtester an error showed that the table patchtesters_tests wasn´t installed.

Error 0 SQL=SELECT COUNT(*) FROM "ejx7v_patchtester_pulls" AS "a" LEFT JOIN "ejx7v_patchtester_tests" AS "t" ON t.pull_id = a.pull_id 

Doing the same without the patch com_patchtester works, well sort of.

**Comment by alikon** [comment]
i've started with a fresh postgresql install and installed the patchtester without this PR , then i've applyed this PR and then unistalled the patchtester.  After i've installed the patchtster without issues  so i'm unable to reproduce your issue , what path have you followed to test this PR on  different environment ?

**Comment by joomlacorner** [comment]
Tested with install com_patchtester it's work fine for me.
before this patch it's not work.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7145">issues.joomla.org/joomla-cms/7145</a>.</sub>

**Comment by wilsonge** [comment]
Can you fix the conflicts please?

**Comment by wilsonge** [comment]
I've merged #7778 as this still has conflicts and I wanted at least a partial fix for 3.4.4. Can we fix up the conflicts in here as this seems to touch a bit more than #7778 did

**Comment by alikon** [comment]
@wilsonge reworked to remove conflicts and merge with #7778

**Comment by alikon** [comment]
i'm closing cause of merge #7778,#7832

**Pull request closed without merging**
