### PR TITLE
Add placeholders for easy sed-ing

### PR DESCRIPTION
**Pull request by vtolstov**
This pull request provides ability to auto fill joomla settings with predefined values.

Signed-off-by: Vasiliy Tolstov v.tolstov@selfip.ru

### CODE REVIEW

**Comment by zero-24** [comment]
Moving to `Needs Review` as we need a top level decision here.

BTW: I don't think we should use a placeholder for the prefix as the prefix should be random. Also i guess that the paceholders will confuse the user more than it helps. But I cant take the decision here. Thanks :smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6967">issues.joomla.org/joomla-cms/6967</a>.</sub>

**Comment by vtolstov** [comment]
@zero-24 Maybe joomla core can autogenerate and use default values in case of sees placeholders, so for user nothing changed, but for devs that try to provide joomla as SaaS this can helps very much.

**Comment by Bakual** [comment]
I don't see the reason for this.

If you want to set up Joomla using a script, you can do that easy without using the installation application at all. All you need to do is create the database, apply the SQL which creates the tables, create the configuration.php file and delete the installation folder.

cPanel and co are already doing that just fine.

**Comment by vtolstov** [comment]
@Bakual in this have we have predefined site name, emails and other unneded stuff, in my case - user have installation gui that have filled inputs for database connection.

**Comment by Bakual** [comment]
The scripts cPanel and co usually use let the user define the site name and email. Not much else needed and it's a simple form they use.

Your solution uses language strings, but doesn't define them. Which is obviously wrong already.
Let's assume you define them with an empty value (or `localhost` for the server), that would still mean your SaaS needs to hack core (all language files) to achieve what you want.
If they however need to hack the core anyway, they can as well just hack one XML file and add the defaults there, and make them readonly, hidden, or whatever to prevent the user from changing them.

I would still go the route with creating a custom script. It's much simpler in the end.

**Pull request closed without merging**
