### PR TITLE
#11234 fixed hide color issue

### PR DESCRIPTION
**Pull request by RonakParmar**
Pull Request for Issue #11234  .
#### Summary of Changes

Added css and class to change the color to red to maintain consistency. 
#### Testing Instructions
- Apply this PR.
  -Try to add/edit contact at administrator side 
- Goto "Display" tab.
- Change " Show Category" field options. in hide option, background is red color, and in another two options background is green color.
- Check Contact global configuration-> check same changes for "Contact Category" field.

Follow instructions of #11234

### CODE REVIEW

**Comment by NeerajTailored** [comment]
I have tested this item :white_check_mark: successfully on cf9fe7c1cfc7e1d5109f7d080c4b82d9fceddcf3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11241">issues.joomla.org/joomla-cms/11241</a>.</sub>

**Comment by brianteeman** [comment]
Sorry this is not correct. You cannot edit the template css file directly you must edit the less file and then use the script to generate the css

**Comment by brianteeman** [comment]
I have tested this item :red_circle: unsuccessfully on cf9fe7c1cfc7e1d5109f7d080c4b82d9fceddcf3<br /><br />It does make the one option red - but if it is to do that then it also needs to make the other two green which it doesnt<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11241">issues.joomla.org/joomla-cms/11241</a>.</sub>

**Comment by RonakParmar** [comment]
I'll write the code to change color of other two option to green and update this PR using less file.

**Comment by brianteeman** [comment]
Thanks- can you also check for other com_contact xml files which could have the same change made

**Comment by gunjanpatel** [comment]
I have tested this item :white_check_mark: successfully on 9f45de80cf82bf8a48f29b8f8557a530a524b06d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11241">issues.joomla.org/joomla-cms/11241</a>.</sub>

**Comment by killoltailored** [comment]
I have tested this item :white_check_mark: successfully on 9f45de80cf82bf8a48f29b8f8557a530a524b06d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11241">issues.joomla.org/joomla-cms/11241</a>.</sub>

**Comment by truptikagathara** [comment]
I have tested this item :white_check_mark: successfully on 9f45de80cf82bf8a48f29b8f8557a530a524b06d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11241">issues.joomla.org/joomla-cms/11241</a>.</sub>

**Comment by brianteeman** [comment]
rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11241">issues.joomla.org/joomla-cms/11241</a>.</sub>

**Pull request merged**
