### PR TITLE
Allow filtering by archived in Redirect Manager

### PR DESCRIPTION
**Pull request by wilsonge**
### Summary of Changes
Allows filtering by the archived state in the redirect component.

### Testing Instructions
In search tools of the redirect component there is now an archived option in the dropdown which allows filtering by archived options

### Documentation Changes Required
n/a

### CODE REVIEW

**Comment by brianteeman** [comment]
I created a pr some time ago to remove the archived state from com_redirects as it has no purpose that I could see

**Comment by wilsonge** [comment]
That's fine. But as it's currently still there it should work properly :)

**Comment by brianteeman** [comment]
or just merge mine to remove it ;)

there is no function in setting a redirect to archived so better to remove a useless function than to add features to a broken function

**Comment by ghost** [comment]
mentioned Pull Requests are #17417 (j3) and #17586 (j4)

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on efbce0cb3f434017798b9998f681d728ade373f0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21673">issues.joomla.org/tracker/joomla-cms/21673</a>.</sub>

**Comment by brianteeman** [comment]
I still dont see any reason to have the archive state for redirects as they have no function - so no need to filter etc

**Comment by ReLater** [comment]
> to remove a useless function

as discussed in https://github.com/joomla/joomla-cms/pull/17417 that's your private opinion because you don't accept workflows of other users.

I still see no reason to remove archived status. Don't use it if you don't want to. Use it if you want to.

**Comment by mbabker** [comment]
Provide examples of valid workflows where a distinction between a published and an archived redirect link should be supported.  As pointed out in that issue, what you are using archived for is exactly what unpublished is, archived is not a "we've reviewed this link and decided to not redirect it anywhere" state.  If anything, if archived is going to exist as a state it should be consistent with the state as used in other core components (i.e. archived in com_redirect and com_content should have a loosely similar definition).

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on efbce0cb3f434017798b9998f681d728ade373f0<br /><br />As discussed I still think it is wrong to have an archived state which does nothing but this PR does do what it aims to do<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21673">issues.joomla.org/tracker/joomla-cms/21673</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Pull request merged**
