### PR TITLE
Update jQuery Autocomplete to 1.4.1

### PR DESCRIPTION
**Pull request by viocassel**
### Summary of Changes
This PR updates [jQuery Autocomplete](https://github.com/devbridge/jQuery-Autocomplete) library to version [1.4.0](https://github.com/devbridge/jQuery-Autocomplete/releases/tag/v1.4.0) for _com_finder_ and _mod_finder_.

### Testing Instructions
1. Apply patch
2. Test the _com_finder_ and _mod_finder_ typing any word in search field (for example, _joomla_  :wink:)
3. Make sure there are no JS errors and the list dropdown displayed correctly.

### Result
**com_finder**
com_finder

**mod_finder**
mod_finder

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
I have tested this item :red_circle: unsuccessfully on 074c0c9d5e11f50d23d9901588f70ec828e0c87b<br /><br />No JS-Errors in Console, but Dropdown isn't shown with PR.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15078">issues.joomla.org/tracker/joomla-cms/15078</a>.</sub>

**Comment by viocassel** [comment]
Thanks @franz-wohlkoenig 
Updated to version 1.4.1 which resolves the bug.
Please try again.

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 58cd498faf07812996cc3ff086a331cc2e9ebea0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15078">issues.joomla.org/tracker/joomla-cms/15078</a>.</sub>

**Comment by yasirunilan** [comment]
what is meant by this ?
Test the com_finder and mod_finder typing any word in search field (for example, joomla 😉)
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15078">issues.joomla.org/tracker/joomla-cms/15078</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
@yasirunilan yes, you should test com_finder and mod_finder (see Screenshots above) if Dropdown-Field is shown correct.

**Comment by yasirunilan** [comment]
@franz-wohlkoenig  yeah. what my question was how to go to com_finder?

**Comment by franz-wohlkoenig** [comment]
for com_finder you have to create the Menu and test.

**Comment by yasirunilan** [comment]
I have tested this item :red_circle: unsuccessfully on 58cd498faf07812996cc3ff086a331cc2e9ebea0<br /><br />can't see the dropdown.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15078">issues.joomla.org/tracker/joomla-cms/15078</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on acfa0bddb35ee003eef6dc07d6b307a4fb8fabbb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15078">issues.joomla.org/tracker/joomla-cms/15078</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :red_circle: unsuccessfully on acfa0bddb35ee003eef6dc07d6b307a4fb8fabbb<br /><br />Smart search works, no Dropdown in Module "Search".<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15078">issues.joomla.org/tracker/joomla-cms/15078</a>.</sub>

**Comment by brianteeman** [comment]
@franz-wohlkoenig are you sure you are testing the smart search component and module. They both work correctly for me. It sounds to me that you are testing the regular search module which is not related to this pr.

As a general tip if you cant confirm that something is working after a PR its always a good idea to test without the PR as well.

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on acfa0bddb35ee003eef6dc07d6b307a4fb8fabbb<br /><br />you're right, @brianteeman, i tested also module "search".<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15078">issues.joomla.org/tracker/joomla-cms/15078</a>.</sub>

**Comment by ghost** [comment]
RTC after two successful tests.

**Pull request merged**
