### PR TITLE
[4.0] fix typo in translator note

### PR DESCRIPTION
**Pull request by tecpromotion**
### Summary of Changes

Space placed in the correct position

### Testing Instructions

not required

### Actual result BEFORE applying this Pull Request

 ; Note : %date% will be auto replaced by current year !Don't translate

### Expected result AFTER applying this Pull Request

 ; Note : %date% will be auto replaced by current year! Don't translate

### Documentation Changes Required

.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 472758a4f9ad6dc1b555e9547fcb0cad699e5311<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35064">issues.joomla.org/tracker/joomla-cms/35064</a>.</sub>

**Comment by rjharishabh** [comment]
I have tested this item :white_check_mark: successfully on 472758a4f9ad6dc1b555e9547fcb0cad699e5311<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35064">issues.joomla.org/tracker/joomla-cms/35064</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35064">issues.joomla.org/tracker/joomla-cms/35064</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
