### PR TITLE
[4.0] TinyMCE languages fix

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request alternative to #35878

### Summary of Changes

Load either minified or non minified language files depending on the JDEBUG constant (same as the rest scripts/styles in the core)

### Testing Instructions
Same as  #35878

### Actual result BEFORE applying this Pull Request

Broken

### Expected result AFTER applying this Pull Request

Fixed
Screenshot 2021-10-23 at 20 30 22

Screenshot 2021-10-23 at 20 33 31

### Documentation Changes Required

No bug fix

@brianteeman

### CODE REVIEW

**Comment by brianteeman** [comment]
similar problem with the editor.min.css

**Comment by dgrammatiko** [comment]
> similar problem with the editor.min.css

There's a PR for the editor.css that needs some refactoring to handle also the `.min.css case`: https://github.com/joomla/joomla-cms/pull/31785

**Comment by brianteeman** [comment]
yes but this pr is for 4.0 and that pr is for 4.whenever

**Comment by chmst** [comment]
If testing instructions are the same as for #35878, the PR fails. Both min.js and .js are present after npm.

**Comment by dgrammatiko** [comment]
@chmst the 3rd option from #35878 is not valid with this pr, we do have both min and unminified files. I think you have to check if the list of languages doesn’t have any files with extension and if you peek one then check that is correctly loaded. The images I shared in the description should help. Oh and enabling debug should load the non mini field language script

**Comment by laoneo** [comment]
I have tested this item :white_check_mark: successfully on 8180880520a2d8bf2d1a746462d4cca5e0aa8b22<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35883">issues.joomla.org/tracker/joomla-cms/35883</a>.</sub>

**Comment by Quy** [comment]
I am getting the following when in edit mode of an article. Please update your branch to rebuilt the package that I can test instead with patch tester. Thanks.
```
Notice: Trying to get property '0' of non-object in \plugins\editors\tinymce\tinymce.php on line 200

Notice: Trying to get property '2' of non-object in \plugins\editors\tinymce\tinymce.php on line 200
```

**Comment by dgrammatiko** [comment]
@Quy should be synced now

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 8180880520a2d8bf2d1a746462d4cca5e0aa8b22<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35883">issues.joomla.org/tracker/joomla-cms/35883</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35883">issues.joomla.org/tracker/joomla-cms/35883</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Comment by dgrammatiko** [comment]
Thank you, Ben, just be careful with this one when you push it to 4.1 (in 4.1 the tinyMCE is refactored so you might have to do a bit of copy pasting)

**Pull request merged**
