### PR TITLE
Deprecate parts of com_modules

### PR DESCRIPTION
**Pull request by brianteeman**
Add deprecated comments

the preview view has not been used for a very very long time if ever

the select view has only been used for hathor which will not be present in j4

Pull request for #12401

### CODE REVIEW

**Comment by zero-24** [comment]
timme vs time?

**Comment by brianteeman** [comment]
typos - lol

**Review by dgrammatiko — APPROVED** [review]

**Comment by tonypartridge** [comment]
I have tested this item :white_check_mark: successfully on 7f46eab36f59bd48c2f6e094229b4b2795b162a5<br /><br />On code review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16152">issues.joomla.org/tracker/joomla-cms/16152</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 7f46eab36f59bd48c2f6e094229b4b2795b162a5<br /><br />Code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16152">issues.joomla.org/tracker/joomla-cms/16152</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Comment by brianteeman** [comment]
Thanks

**Comment by brianteeman** [comment]
Oops this needs to be reverted - I deprecated the wrong selects

**Comment by brianteeman** [comment]
it should have been positions not select - mea culpa

**Comment by tonypartridge** [comment]
Lol! @wilsonge please revert 😂

**Comment by wilsonge** [comment]
Can you just do a fresh PR removing deprecated notice from the wrong view and adding to the right view?

**Comment by brianteeman** [comment]
will do - this afternoon - thanks

**Pull request merged**
