### PR TITLE
[4.0] media manager breadcrumbs

### PR DESCRIPTION
**Pull request by brianteeman**
The RTL specific css was wrong as can be seen in the before screenshot

This PR removes the RTL specific css (should have been scss) and updates the scss to use logical properties instead.

This PR also removes an unused class `breadcrumb-item`.

To test RTL you will need to install arabic or persian.

and dont forget to npm ci

There is no visible change in LTR and the RTL changes are as shown below

## Before LTR
image

## Before RTL
image

## After LTR
image

## After RTL
image

### CODE REVIEW

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on 0f096617cd9d2f2a6056b4897558c5e11425f7cc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36154">issues.joomla.org/tracker/joomla-cms/36154</a>.</sub>

**Comment by pritam825** [comment]
I have tested this item :white_check_mark: successfully on 0f096617cd9d2f2a6056b4897558c5e11425f7cc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36154">issues.joomla.org/tracker/joomla-cms/36154</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36154">issues.joomla.org/tracker/joomla-cms/36154</a>.</sub>

**Comment by khu5h1** [comment]
I have tested this item :white_check_mark: successfully on 0f096617cd9d2f2a6056b4897558c5e11425f7cc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36154">issues.joomla.org/tracker/joomla-cms/36154</a>.</sub>

**Comment by Quy** [comment]
Thanks

**Pull request merged**
