### PR TITLE
[codestyle] a or an

### PR DESCRIPTION
**Pull request by brianteeman**
### Summary of Changes

When to write a or an
If the following word starts with a consonant **sound**, then we say a:
If the following word starts with a vowel **sound**, then we say an:
### Testing Instructions

Code Review
### Documentation Changes Required

None

### CODE REVIEW

**Comment by brianteeman** [comment]
@andrepereiradasilva especially for you ;)

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on d1ae4e41175847ec6383cd43c989cc3629a63b5a<br /><br />did a code review and learned ;)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12393">issues.joomla.org/tracker/joomla-cms/12393</a>.</sub>

**Comment by brianteeman** [comment]
I learn from you everyday so this is me returning the favour.

**Comment by ot2sen** [comment]
@brianteeman Thanks for adding a missing piece in my puzzle. That extra highlighted word added after consonant and vowel was an aha moment to me. **Sounds** like, note taken. :)

**Comment by grhcj** [comment]
I have tested this item :white_check_mark: successfully on d1ae4e41175847ec6383cd43c989cc3629a63b5a<br /><br />On Review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12393">issues.joomla.org/tracker/joomla-cms/12393</a>.</sub>

**Comment by brianteeman** [comment]
@ot2sen The only time it gets a little tricky is with URL

Most people pronounce it _"you-are-el"_ so it is **A**
Some people pronounce it  _"earl"_ so it would be **AN**

**Comment by infograf768** [comment]
RTC. Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12393">issues.joomla.org/tracker/joomla-cms/12393</a>.</sub>

**Pull request merged**
