### PR TITLE
[4.0] Typo in js comments

### PR DESCRIPTION
**Pull request by brianteeman**
Simple PR to correct a typo

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 1269b31c5f62d85d6bda9e4088fcf38541594253<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23676">issues.joomla.org/tracker/joomla-cms/23676</a>.</sub>

**Comment by amitranjan2** [comment]
I have tested this item :white_check_mark: successfully on 1269b31c5f62d85d6bda9e4088fcf38541594253<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23676">issues.joomla.org/tracker/joomla-cms/23676</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23676">issues.joomla.org/tracker/joomla-cms/23676</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
