### PR TITLE
JS typo in sortable

### PR DESCRIPTION
**Pull request by brianteeman**
Small typo in the js for sortable.js

### CODE REVIEW

**Comment by anibalsanchez** [comment]
I have tested this item :white_check_mark: successfully on bc949c9996388963e5fa035998e0350be72f823d<br /><br />Test OK<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9050">issues.joomla.org/joomla-cms/9050</a>.</sub>

**Comment by ghazal** [comment]
Tested OK :white_check_mark: .

**Comment by brianteeman** [comment]
RTC thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9050">issues.joomla.org/joomla-cms/9050</a>.</sub>

**Comment by wilsonge** [comment]
Merged - thanks all!

**Comment by anibalsanchez** [comment]
@wilsonge You're welcome. Thank you to you. ;-)

PD: Planning to visit some museums today!

**Pull request merged**
