### PR TITLE
[4] sprintf called with single string argument incorrectly

### PR DESCRIPTION
**Pull request by PhilETaylor**
code review

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 0d95f69d9cc45042fb6d339497c68620f2405471<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33967">issues.joomla.org/tracker/joomla-cms/33967</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 0d95f69d9cc45042fb6d339497c68620f2405471<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33967">issues.joomla.org/tracker/joomla-cms/33967</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33967">issues.joomla.org/tracker/joomla-cms/33967</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
