### PR TITLE
Fixes header image logo - Isis - Issue #5270

### PR DESCRIPTION
**Pull request by victorparanhos**
Fixes #5270 issue.

### CODE REVIEW

**Comment by brianteeman** [comment]
Works for me in LTR and RTL<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5432">issues.joomla.org/joomla-cms/5432</a>.</sub>

**Comment by infograf768** [comment]
This patch does not keep the image proportions. It cuts it.
screen shot 2015-01-03 at 08 48 37

original image:

apple

**Comment by brianteeman** [comment]
@infograf768 I thought that was the intention?

**Comment by infograf768** [comment]
Not as we discussed it previously.
https://github.com/joomla/joomla-cms/issues/5270#issuecomment-65076093

https://github.com/joomla/joomla-cms/pull/5330#issuecomment-65892706

This solution 
https://github.com/joomla/joomla-cms/pull/5335#issuecomment-66241016 
scales the image to fit.

**Comment by infograf768** [comment]
TBH, I think that people who want to add their logo to Isis should just create a correct sized image... at least with the correct proportions.

**Comment by victorparanhos** [comment]
When I tried to keep the proportions, were reported problems with IE... Then, my intention was just to cut the image with this fix. But which solution do you think is better in this case?

**Comment by infograf768** [comment]
I am in favour of keeping proportions. A cut off image may not have any use at all imho.

**Comment by anibalsanchez** [comment]
@test OK

It fixes the original toolbar position issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5432">issues.joomla.org/joomla-cms/5432</a>.</sub>

**Comment by joomla-agency** [comment]
Test OK
The toolbar is now like excepted. The image is css resized to width: 143px and the height was cropped from bottom. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5432">issues.joomla.org/joomla-cms/5432</a>.</sub>

**Comment by Julia-Mi** [comment]
@victorparanhos Please look at my pull request for your repository:
https://github.com/victorparanhos/joomla-cms/pull/2

**Comment by zero-24** [comment]
Moving to `Information Required` until @victorparanhos get a chance to review the PR by @Julia-Mi
https://github.com/victorparanhos/joomla-cms/pull/2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5432">issues.joomla.org/joomla-cms/5432</a>.</sub>

**Comment by roland-d** [comment]
Hello @victorparanhos 

Thank you for your contribution.

The last comment here was on June 12th. Can you please follow-up on this issue?

Thanks for understanding! <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5432">issues.joomla.org/joomla-cms/5432</a>.</sub>

**Comment by brianteeman** [comment]
As it has been over a month since the request for follow up I am closing this at this time - it can always be reopened<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5432">issues.joomla.org/joomla-cms/5432</a>.</sub>

**Pull request closed without merging**
