### PR TITLE
[4.0] Replaced JText occurrences

### PR DESCRIPTION
**Pull request by marcochirienti**
### Summary of Changes
Replaced JText occurrences.

### CODE REVIEW

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on c32b33b19f71283c40d5e48d22ddd531fb9e510a<br /><br />OK on review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26966">issues.joomla.org/tracker/joomla-cms/26966</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on c32b33b19f71283c40d5e48d22ddd531fb9e510a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26966">issues.joomla.org/tracker/joomla-cms/26966</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26966">issues.joomla.org/tracker/joomla-cms/26966</a>.</sub>

**Comment by infograf768** [comment]
Tks

**Pull request merged**
