### PR TITLE
[5.2] complete recaptcha removal

### PR DESCRIPTION
**Pull request by brianteeman**
#41530 Remove outdated captcha for new installation

This completes that pr by removing the google library and plugin js and css

code review should be enough _i think_

### CODE REVIEW

**Comment by Fedik** [comment]
Thanks. 
Please change the target to 6.0-dev, because we still need to fix that issue 
- https://github.com/joomla/joomla-cms/issues/44294

**Comment by brianteeman** [comment]
@fedik why? That is for 5.2 and this PR is for 5.2. Why would I rebase it to 6

**Comment by Fedik** [comment]
To fix the linked issue we still need to serve these js files. 
If we remove it now Users will stay with broken js code released with 5.2.0

**Comment by brianteeman** [comment]
This just removes those files from NEW installs of 5.2 which dont have the plugin and should have been done with #41530

The problem of the missing files was because they were removed on update 
https://github.com/joomla/joomla-cms/blob/59b1341c503ce431382a52561e48efaf03af9d2f/administrator/components/com_admin/script.php#L1247-L1249

That is a different issue and needs a different PR to this

**Comment by richard67** [comment]
> This just removes those files from NEW installs of 5.2 which dont have the plugin and should have been done with #41530
> 
> The problem of the missing files was because they were removed on update
> 
> https://github.com/joomla/joomla-cms/blob/59b1341c503ce431382a52561e48efaf03af9d2f/administrator/components/com_admin/script.php#L1247-L1249
> 
> That is a different issue and needs a different PR to this

If they shall not be removed on update, they need to be removed from script.php, and in addition it needs to add them to the list of exceptions in the deleted files check like I had done it with my PR #42936 for other files.

**Comment by Fedik** [comment]
@brianteeman you refering to es5 files. I am talking about regular. 
We do not delete them on update, because we do not uninstall invisible reCaptcha.

The issue that this files should not be released for update/install packges, but I forgot to delete them in my PR.

**Comment by brianteeman** [comment]
> And for update package

They are not needed in the update package as they are already installed. The problem was that the existing installed files were removed by script.php on update which is the error

**Comment by brianteeman** [comment]
To be clear there are multiple errors

1. The pr to remove captcha was incomplete and this PR addresses that
2. The files were removed on update - they should not have been

**Comment by Fedik** [comment]
> The pr to remove captcha was incomplete and this PR addresses that

yes, but we cannot remove them anymore, untill 6.0. Because we still need to release the fix for  #44294

> The files were removed on update - they should not have been

They were NOT removed, becase we do not remove the invisible captcha, only older recaptcha v2 was removed.
That was intended.

@richard67 made everything right. It just me forgot to remove them in original PR, to prevent further release of these files.

**Comment by brianteeman** [comment]
no point in me continuing here as you are not listening or reading

**Comment by Fedik** [comment]
hm? Your PR is fine, it just need to be to 6.0

**Comment by brianteeman** [comment]
As I said you are not reading. this is needed for 5.2 but I have better things to do with my time than to repeat the obvious

**Comment by Fedik** [comment]
Look, we remove `build/media_source/plg_captcha_recaptcha_invisible/js/recaptcha.es6.js` now, in 5.2.
Question: how do we release the fix for #44294 then?

**Comment by Fedik** [comment]
@brianteeman do you reopen the PR for 6.0 or should I copy?

**Pull request closed without merging**
