### PR TITLE
[Bug fix] Correct issue 9292 syntax error in joomla.sql for PostrgeSQL

### PR DESCRIPTION
**Pull request by richard67**
Pull Request for Issue #9292  .
#### Summary of Changes

This PR corrects a silly syntax error in the installation sql script joomla.sql for PostgreSQL I've made with my PR #9269 .

When removing the unique key definition at the end of the create table, I forgot to remove also the comma (shame).
#### Testing Instructions

Only relevant for PostgreSQL database users.

Do a new installation either with Joomla! 3.5.0 Beta 3 or current staging, but before you start, replace the file installation/sql/postgresql/joomla.sql by the one from this PR.

Result: The syntax error described in issue #9292 does not happen anymore, and the table for the redirect links is created.

If no other errors, installation should succeed, otherwise if new erros let me know here.

If all OK, please mark your test result in the issue tracker for this PR.

### CODE REVIEW

**Comment by richard67** [comment]
Changed title to being more descriptive<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9294">issues.joomla.org/joomla-cms/9294</a>.</sub>

**Comment by richard67** [comment]
@alikon It seems there failed some unit test for PHP 5.4, but it seems not related to this PR, or is it? Cab you check, or have an idea who can?

**Comment by andrepereiradasilva** [comment]
not expert, but maybe "header" INTEGER should be integer?

**Comment by richard67** [comment]
@andrepereiradasilva Thanks, this fixed it.

**Comment by richard67** [comment]
@Dygear Could you mark your test result as success then at the issue tracker? Just go to [https://issues.joomla.org/tracker/joomla-cms/9294](https://issues.joomla.org/tracker/joomla-cms/9294l), click the "Test this" button at the to left area and then select the test result. Thanks.

**Comment by Dygear** [comment]
I have tested this item :white_check_mark: successfully on f57d30a41533d07e2102fad67cf92ddab1b0104d<br /><br />Now install under PostgreSQL 9.5.1 with PHP 7.0.3 without issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9294">issues.joomla.org/joomla-cms/9294</a>.</sub>

**Comment by richard67** [comment]
Thanks for testing. One more tester with a PostgreSQL database available, please. Maybe @alikon ?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9294">issues.joomla.org/joomla-cms/9294</a>.</sub>

**Comment by alikon** [comment]
I'll do this evening , now busy ;)

**Comment by richard67** [comment]
Thanks in advance.

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on f57d30a41533d07e2102fad67cf92ddab1b0104d<br /><br />### tested on
PHP 5.5.30
PostgreSQL 9.4.5

p.s.
very happy to see attention about PostgreSQL<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9294">issues.joomla.org/joomla-cms/9294</a>.</sub>

**Comment by richard67** [comment]
Thanks for testing to all testers.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9294">issues.joomla.org/joomla-cms/9294</a>.</sub>

**Comment by brianteeman** [comment]
Rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9294">issues.joomla.org/joomla-cms/9294</a>.</sub>

**Pull request merged**
