### PR TITLE
Email Cloaking fires when @ in filename (image) #39786

### PR DESCRIPTION
**Pull request by LukasHH**
Pull Request for Issue #39786

### Summary of Changes
Change the last pattern to exclude email addresses that are in a source attribute. Example in image or pictures tag

### Testing Instructions
Please test all variants of email obfuscation. I have a source code for an article for testing at https://github.com/LukasHH/other-test/blob/main/email_cloaking_test_source.html.
Copy the source code and paste this source code into a new article. Save the new article and call it in the frontend.

Or:
Create an article and include an image whose filename contains an @.

Apply the suggested change to the file here:
https://github.com/joomla/joomla-cms/pull/39932/files

You can also use the Patch Tester components for testing. A tutorial is available here: https://docs.joomla.org/Component_Patchtester_for_Testers

### Actual result BEFORE applying this Pull Request
Images that have a filename in the form of a valid email address or contain an @ in the filename will be cloaked and not displayed.

Example without this change here under Sample 21
https://j4-test.it-conserv.de/test/issiu

### Expected result AFTER applying this Pull Request
These filenames should be excluded from email cloaking and displayed correctly.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by LukasHH** [comment]
@formfranska please test the PR

**Comment by formfranska** [comment]
> 

Sorry, Not sure exactly what I'm supposed to do. I wasn't able to copy the text from your test article (couldn't scroll all the way down). Complete newbie in github. Sorry 😅

**Comment by LukasHH** [comment]
> > 
> 
> Sorry, Not sure exactly what I'm supposed to do. I wasn't able to copy the text from your test article (couldn't scroll all the way down). Complete newbie in github. Sorry 😅

You can use the "Raw" button, then the raw data will be displayed. Or the button "Copy", then the source text is copied.
image

Otherwise simply set an article in which an image is included, whose file name contains an @ sign.

**Comment by richard67** [comment]
@LukasHH Could you extend your testing instructions so that people paste the test content multiple times? We should have each test object multiple times to make sure that each occurrence of a pattern is cloaked, not only the first one, and that we don’t get into an endless loop with that while loop which we recently discussed at another place.

**Comment by formfranska** [comment]
> > > 
> > 
> > 
> > Sorry, Not sure exactly what I'm supposed to do. I wasn't able to copy the text from your test article (couldn't scroll all the way down). Complete newbie in github. Sorry 😅
> 
> You can use the "Raw" button, then the raw data will be displayed. Or the button "Copy", then the source text is copied. image
> 
> Otherwise simply set an article in which an image is included, whose file name contains an @ sign.

Thank you! OK, so I didn't have the Copy button but the Raw button was present so used that.
Screenshot 2023-02-25 at 10 07 55

I published the article and only Sample 21 looks broken to me:
---
**Sample 21:**

Image filename in the form of an email

This email address is being protected from spambots. You need JavaScript enabled to view it." width="215" height="121" loading="lazy" data-path="local-images:/demofiles/[test@image.png](mailto:test@image.png)" />

This email address is being protected from spambots. You need JavaScript enabled to view it." alt="" width="215" height="121" loading="lazy" data-path="local-images:/demofiles/[test@image.png](mailto:test@image.png)" />

This email address is being protected from spambots. You need JavaScript enabled to view it." width="100" height="100" loading="lazy" data-path="local-images:/demofiles/[test@image.svg](mailto:test@image.svg)" />

This email address is being protected from spambots. You need JavaScript enabled to view it." alt="" width="100" height="100" loading="lazy" data-path="local-images:/demofiles/[test@image.svg](mailto:test@image.svg)" />

This email address is being protected from spambots. You need JavaScript enabled to view it." alt="[test@image.svg](mailto:test@image.svg)" width="100" height="100" loading="lazy" data-path="local-images:/demofiles/[test@image.svg](mailto:test@image.svg)" />

test@image.svg

<picture><source srcset="local-images:/demofiles/[test@image.svg](mailto:test@image.svg)" media="(min-width: 38em)" /> <source srcset="local-images:/demofiles/[test@image.svg](mailto:test@image.svg)" />  </picture>

This email address is being protected from spambots. You need JavaScript enabled to view it." media="(min-width: 38em)" /> This email address is being protected from spambots. You need JavaScript enabled to view it." /> This email address is being protected from spambots. You need JavaScript enabled to view it." alt="" />
---
Screenshot 2023-02-25 at 10-15-27 Source Code for Test Email cloaking - TESTAR

Was this helping you in any way? Or did I do it wrong?

**Comment by LukasHH** [comment]
This is the initial situation without the patch, which allows you to test all variants. You would now have to apply the changes and then it should be displayed correctly.
https://github.com/joomla/joomla-cms/pull/39932/files

You can also use the Patch Tester component for testing: https://docs.joomla.org/Component_Patchtester_for_Testers

**Comment by formfranska** [comment]
> This is the initial situation without the patch, which allows you to test all variants. You would now have to apply the changes and then it should be displayed correctly. https://github.com/joomla/joomla-cms/pull/39932/files
> 
> You can also use the Patch Tester component for testing: https://docs.joomla.org/Component_Patchtester_for_Testers

OK, thanks of your help every step of the way 🤣

Applied patch
Screenshot 2023-02-25 at 11 47 14

Sample 21 now looks like this (with patch enabled)
Screenshot 2023-02-25 at 11 48 39

Please note that when I try to look at the images I get
<quote>
404 Not Found The resource requested could not be found on this server!
</quote>

**Comment by LukasHH** [comment]
I have just updated and extended the page with the test code. Here I have also added the sample images. I have also added a readme with further explanation.
https://github.com/LukasHH/other-test

The images are currently not displayed for you, because they are not available. It is important that the file name is not disguised.

**Comment by formfranska** [comment]
> I have just updated and extended the page with the test code. Here I have also added the sample images. I have also added a readme with further explanation. https://github.com/LukasHH/other-test
> 
> The images are currently not displayed for you, because they are not available. It is important that the file name is not cloaked.

Thank you! OK, so with this https://github.com/LukasHH/other-test it looks like this:

Screenshot 2023-02-25 at 18 47 58

Is that how it should look?

**Comment by LukasHH** [comment]
Yes - this is how it should look. In the browser source code you can also see that the images with an @ are not cloaked, while emails are still cloaked by the plugin.

You can also test it with the as you had described in the forum.
https://forum.joomla.org/viewtopic.php?p=3683408#p3683408

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on cd6ae6b6424fd13066bda94c96e705b43a4ef76b<br /><br />Tested successfully using the sample page in Joomla 4.2.9-dev of 26 February using PHP 8.1.10 in Wampserver<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39932">issues.joomla.org/tracker/joomla-cms/39932</a>.</sub>

**Comment by ChristineWk** [comment]
@LukasHH 

Status now: Everything done OK so far. Also images loaded etc. 

But when applying Patchtester, get response:
The file marked for modification does not exist: plugins/content/emailcloak/emailcloak.php 

But: Content – Email Cloacking is enabled!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39932">issues.joomla.org/tracker/joomla-cms/39932</a>.</sub>

**Comment by richard67** [comment]
@ChristineWk Can it be that you have tested on a 4.3-dev installation where that plugin has been converted to the new structure with PR #38466 ? This would explain your problem with the patchtester. This PR here is for the 4.2-dev branch where the file still is at the old place.

**Comment by ChristineWk** [comment]
@richard67 
Yes, you're right, I had the thought too... sorry.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39932">issues.joomla.org/tracker/joomla-cms/39932</a>.</sub>

**Comment by richard67** [comment]
@ChristineWk Hmm unfortunately you can't really test this PR on a 4.3-dev. But thanks for trying. Do you have a 4.2.8 or so for testing, too? On that you could test this PR.

**Comment by ChristineWk** [comment]
I have a 4.2.9-dev, because for 4.2.8 there was a security release. Will try. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39932">issues.joomla.org/tracker/joomla-cms/39932</a>.</sub>

**Comment by ChristineWk** [comment]
@LukasHH 

Could you check again my test-site please? It seems OK now. Tks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39932">issues.joomla.org/tracker/joomla-cms/39932</a>.</sub>

**Comment by LukasHH** [comment]
> @LukasHH
> 
> Could you check again my test-site please? It seems OK now. Tks
> This comment was created with the [J!Tracker Application](https://github.com/joomla/jissues) at [issues.joomla.org/tracker/joomla-cms/39932](https://issues.joomla.org/tracker/joomla-cms/39932).

Hello Christine,

I just see on your page that the Sample 17a and Sample 17b versions are not cloaked. They should still be cloaked.
I'll have a look at it again to see if it's the same for me.

image

**Comment by LukasHH** [comment]
I need to undo the change in line 444.
https://github.com/joomla/joomla-cms/pull/39932/commits/1e46b07613e77278740a795b6bb4b527f288fb4d

I have noticed that this change no longer cloaks the versions under Sample 17. Even without the change, this does not affect functionality with images that contain an @ in the filename.

**Comment by ChristineWk** [comment]
@LukasHH 

Hv reverted Patch, fetched and applied again. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39932">issues.joomla.org/tracker/joomla-cms/39932</a>.</sub>

**Comment by LukasHH** [comment]
> @LukasHH
> 
> Hv reverted Patch, fetched and applied again.
> This comment was created with the [J!Tracker Application](https://github.com/joomla/jissues) at [issues.joomla.org/tracker/joomla-cms/39932](https://issues.joomla.org/tracker/joomla-cms/39932).

This looks better now.

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on e033de6300b2b4a97b62fbbadb09256e36058475<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39932">issues.joomla.org/tracker/joomla-cms/39932</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on e033de6300b2b4a97b62fbbadb09256e36058475<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39932">issues.joomla.org/tracker/joomla-cms/39932</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39932">issues.joomla.org/tracker/joomla-cms/39932</a>.</sub>

**Comment by roland-d** [comment]
Thank you

**Pull request merged**
