### PR TITLE
Fixed: Consistency of "unpublished" -i con colours #43375

### PR DESCRIPTION
**Pull request by mabdelaziz77**
Fixed the inconsistency of the unpublished icon colour of the articles in the associations modal window.

Pull Request for Issue #43375 .

### Summary of Changes
Changed the unpublished icon from _icon-times_ (red) to _icon-unpublish_ (grey) in the article associations modal window.

### Testing Instructions

1. Make sure the multi-language feature is enabled by enabling the **System - Language Filter** plugin.
2. Install a second language if you have only one language installed.
3. Create an article for each language, set their state to **unpublished**.
4. Edit one of the two articles, go to the **Associations** tab and click the **Select** button to select an article.
5. Make sure the unpublished icon is grey.

### Actual result BEFORE applying this Pull Request
The unpublished icon color is red.
unpublished icon is red

### Expected result AFTER applying this Pull Request
The unpublished icon is grey.
unpublished icon is grey

### CODE REVIEW

**Comment by Quy** [comment]
There are more instances. Please find the following and apply the same change. Thank you!

`0  => 'icon-times',`

**Review by chmst — APPROVED** [review]

**Comment by mabdelaziz77** [comment]
> There are more instances. Please find the following and apply the same change. Thank you!
> 
> `0 => 'icon-times',`

Replaced the other instances.

**Comment by brianteeman** [comment]
not that simple

image

you also need to change icon-folder to icon-archive

**Comment by Quy** [comment]
Also, please change `icon-check` to `icon-publish`.

**Comment by mabdelaziz77** [comment]
I noticed that all the modal windows have the same issue. Is this look intentional? 
I'm not sure if it’s supposed to be like this, so is there any reference we can check to see if this is the expected behavior? 
Let me know!

**Comment by chmst** [comment]
@mabdelaziz77 thank you very much for your work! 
Differences are not intentional, they should look same as the noemal views. Probably testers forgot testing modal views in recent versions.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 73643025a84c179a346df5becb596087b8a3eccb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43424">issues.joomla.org/tracker/joomla-cms/43424</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 7cb128d0afdd183622cc1ee6eec765262c5e1024<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43424">issues.joomla.org/tracker/joomla-cms/43424</a>.</sub>

**Comment by mabdelaziz77** [comment]
I have tested this item :white_check_mark: successfully on 7cb128d0afdd183622cc1ee6eec765262c5e1024<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43424">issues.joomla.org/tracker/joomla-cms/43424</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43424">issues.joomla.org/tracker/joomla-cms/43424</a>.</sub>

**Comment by gacompa** [comment]
I have tested this item :white_check_mark: successfully on 7cb128d0afdd183622cc1ee6eec765262c5e1024<br /><br />I tested successfully both for articles and categories
- unpublished
- trashed
- archived<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43424">issues.joomla.org/tracker/joomla-cms/43424</a>.</sub>

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
