### PR TITLE
Backend login, remove the dot in link

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Summary of Changes

very simple PR just to remove the dot in backend login panel "Go to site home page." link.
#### Testing Instructions

Go to the bottom of the backend login screen, there in a "Go to site home page." link, after patch the dot is removed.
Or just check code difference.

### CODE REVIEW

**Comment by brianteeman** [comment]
Personally its a sentence so needs the .

**Comment by andrepereiradasilva** [comment]
A link with a dot? How about just "View Site" like when you're logged in?

**Comment by brianteeman** [comment]
@chrisdavenport any thoughts?
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9869">issues.joomla.org/joomla-cms/9869</a>.</sub>

**Comment by chrisdavenport** [comment]
Technically, it's a complete sentence in its own right, so it should have a full stop.  But in this case it's being used purely as link text which just happens to be a full English sentence.  As a link it certainly does look odd with the full stop, so I tend to agree with @andrepereiradasilva and I think it should be removed.

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 5558da9c5e80ee7b5fbfa56fd4946dfb1c0eed5e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9869">issues.joomla.org/joomla-cms/9869</a>.</sub>

**Comment by brianteeman** [comment]
RTC using @chrisdavenport as a successful test ;)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9869">issues.joomla.org/joomla-cms/9869</a>.</sub>

**Pull request merged**
