### PR TITLE
Introduce JLayout for JHtml tag

### PR DESCRIPTION
**Pull request by dgrammatiko**
#### What is this?

Well, we use JHtml for injecting the javascript for the tag field. By moving this code to JLayout we enable an easier way to override this part.
Also this PR introduces another two layouts for the formbehavior functions chosen and ajaxchosen.
#### Testing

Apply this PR
Edit an article in the backend and check if the tag field still works.
Also in the Articles view (the listing view) check if the dropdown on the right side work (for ajax ajaxchosen type some ordering, for simple chosen just select one option on the dropdown)

### CODE REVIEW

**Comment by balzercomp** [comment]
I have tested this item :white_check_mark: successfully on ce9b36a2b92926add126908ddf1da1cb0285c500<br /><br />Tags work as expected. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8101">issues.joomla.org/joomla-cms/8101</a>.</sub>

**Comment by balzercomp** [comment]
I have tested this item :white_check_mark: successfully on ce9b36a2b92926add126908ddf1da1cb0285c500<br /><br />Tags work as expected. Tags can be selected in the Tags Search Tool<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8101">issues.joomla.org/joomla-cms/8101</a>.</sub>

**Comment by coolman01** [comment]
I have tested this item :white_check_mark: successfully on ce9b36a2b92926add126908ddf1da1cb0285c500<br /><br />works as described<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8101">issues.joomla.org/joomla-cms/8101</a>.</sub>

**Comment by svom** [comment]
I have tested this item :white_check_mark: successfully on ce9b36a2b92926add126908ddf1da1cb0285c500<br /><br />Tested successfully on Joomla 3.4.5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8101">issues.joomla.org/joomla-cms/8101</a>.</sub>

**Comment by zero-24** [comment]
Thanks --> RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8101">issues.joomla.org/joomla-cms/8101</a>.</sub>

**Comment by Kubik-Rubik** [comment]
Thank you @dgt41 and testers! Merged.

**Comment by infograf768** [comment]
@dgt41 
We have a Notice here.
See: https://github.com/joomla/joomla-cms/issues/8220

**Pull request merged**
