### PR TITLE
Update en-GB.plg_fields_media.ini

### PR DESCRIPTION
**Pull request by stellainformatica**
I suggest to change this language string because there's no path to insert, just a drop down menu with a list of folders

Pull Request for Issue # .

### Summary of Changes
Changed 
PLG_FIELDS_MEDIA_PARAMS_DIRECTORY_DESC="The filesystem path to the directory containing the image files to be listed relative to the default image folder."
to 
PLG_FIELDS_MEDIA_PARAMS_DIRECTORY_DESC="The directory containing the image files to be listed relative to the default image folder (set in Media > Options)."

and 
PLG_FIELDS_IMAGELIST_PARAMS_DIRECTORY_DESC="The filesystem path to the directory containing the image files to be listed relative to the default image folder."
to
PLG_FIELDS_IMAGELIST_PARAMS_DIRECTORY_DESC="The directory containing the image files to be listed relative to the default image folder (set in Media > Options)."

### Testing Instructions
Create a new Field type Media or Imagelist and look the tooltip of Directory parameter

### CODE REVIEW

**Comment by brianteeman** [comment]
Good spot. This was missed when the field was changed. Personally I wouldn't put the `(set in Media > Options)` but its fine i guess

**Comment by zero-24** [comment]
@brianteeman so we can RTC here for 3.7.1? As we are in language freez now?

**Comment by brianteeman** [comment]
Don't see why not

**Comment by franz-wohlkoenig** [comment]
RTC as discussed above.

**Comment by stellainformatica** [comment]
Also the tooltip of Images Directory of TinyMCE plugin has to be corrected, I commit the new correction.

**Pull request merged**
