### PR TITLE
[4.1] s/submited/submitted

### PR DESCRIPTION
**Pull request by brianteeman**
typo

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on ee0f12c8e88be582d64b718740a5b029b07e934a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36829">issues.joomla.org/tracker/joomla-cms/36829</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on ee0f12c8e88be582d64b718740a5b029b07e934a<br /><br />Code review: These typos appear only at the places fixed by this PR.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36829">issues.joomla.org/tracker/joomla-cms/36829</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36829">issues.joomla.org/tracker/joomla-cms/36829</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Comment by brianteeman** [comment]
thank you

**Pull request merged**
