### PR TITLE
[6.0] Deprecated lang strings

### PR DESCRIPTION
**Pull request by brianteeman**
Found three additional files with strings marked as to be removed in 6

code review

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on a78a41d818f0d8156160aa986c0a87f763832d50<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44103">issues.joomla.org/tracker/joomla-cms/44103</a>.</sub>

**Comment by brianteeman** [comment]
@Kostelano thanks - added those

**Comment by Kostelano** [comment]
I have tested this item :white_check_mark: successfully on 4f131d838773510afe79e5bc4bb345a80a1b7ff4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44103">issues.joomla.org/tracker/joomla-cms/44103</a>.</sub>

**Comment by tecpromotion** [comment]
I have tested this item :white_check_mark: successfully on 4f131d838773510afe79e5bc4bb345a80a1b7ff4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44103">issues.joomla.org/tracker/joomla-cms/44103</a>.</sub>

**Review by tecpromotion — APPROVED** [review]
Thanks @brianteeman

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44103">issues.joomla.org/tracker/joomla-cms/44103</a>.</sub>

**Comment by softforge** [comment]
Thank you for all your work on this PR

**Pull request merged**
