### PR TITLE
[com_search] Refactoring + fixing results-highlighting

### PR DESCRIPTION
**Pull request by frankmayer**
New issue: 
Positioning of highlighting was off sometimes when special characters were used.
Also the css padding for highlighting feels 'unnatural'.

Please look below for example images showing the before and after the patch.

### Summary of Changes
- [com_search] Refactoring + fixing results-highlighting 
- Fixed css sitewide to display highlight more naturally.

### Testing Instructions
1) Do not apply patch. Do some searches using words with ascii and non-ascii. 
2) Apply patch. Check that the correct words are highlighted.

### Documentation Changes Required
None 

Note: It would probably be better to make the functionality of highlighting reusable in it's own class. It then could also be reused from other parts of Joomla itself or extensions. It would also allow us to extend its functionality.
I would do that, in another PR, if this one gets merged.

#### Examples:

Notice the wrong positioning of the highlighting in the text at some places and the unnatural padding on the highlight. Both issues are fixed in the image after this one, where the patch is applied.

__The word to search for, in these examples, was: Österreich__

__(image showing the issues)__

screenshot-joomla-patch-tester-1 2017-01-07 03-59-27

__(image showing issues fixed)__

screenshot-joomla-patch-tester-1 2017-01-07 04-46-57

### CODE REVIEW

**Comment by jsubri** [comment]
This is a really nice improvement. see picture below

screen shot 2017-01-07 at 02 50 52<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13498">issues.joomla.org/tracker/joomla-cms/13498</a>.</sub>

**Comment by jsubri** [comment]
I have tested this item :white_check_mark: successfully on a3946ac25c1a16065d08220ffb5893ea1900dbf2<br /><br />Very welcome patch :-) 
Thank you<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13498">issues.joomla.org/tracker/joomla-cms/13498</a>.</sub>

**Comment by frankmayer** [comment]
@jsubri thanks for testing and confirming it works correctly with French text

**Comment by genesisfan** [comment]
I have tested this item :red_circle: unsuccessfully on a3946ac25c1a16065d08220ffb5893ea1900dbf2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13498">issues.joomla.org/tracker/joomla-cms/13498</a>.</sub>

**Comment by frankmayer** [comment]
@genesisfan did this work without the patch? Could you post a screenshot without the patch?

**Comment by frankmayer** [comment]
@genesisfan Thank you for testing and finding this problem.
However, since the problem pre-existed and was not introduced by the patch, I would propose to create a separate issue for that. That way this specific improvement can be merged and a fix for the other issue can be worked on, after that.

**Comment by waader** [comment]
I have tested this item :white_check_mark: successfully on a3946ac25c1a16065d08220ffb5893ea1900dbf2<br /><br />Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13498">issues.joomla.org/tracker/joomla-cms/13498</a>.</sub>

**Comment by frankmayer** [comment]
So can this be merged then? The unsuccessful human test is not related to the fix this PR is proposing. Since another issue has already be created for that, I think it would be better to merge this PR in order to avoid conflicts in future work for the other issue.

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on a3946ac25c1a16065d08220ffb5893ea1900dbf2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13498">issues.joomla.org/tracker/joomla-cms/13498</a>.</sub>

**Comment by coolcat-creations** [comment]
I have tested this item :white_check_mark: successfully on a3946ac25c1a16065d08220ffb5893ea1900dbf2<br /><br />Issue confirmed,

Test successful - Works as described<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13498">issues.joomla.org/tracker/joomla-cms/13498</a>.</sub>

**Comment by joomlamarco** [comment]
I have tested this item :white_check_mark: successfully on a3946ac25c1a16065d08220ffb5893ea1900dbf2<br /><br />patch works as descripted.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13498">issues.joomla.org/tracker/joomla-cms/13498</a>.</sub>

**Pull request merged**
