### PR TITLE
Accessibility for title on article tool [issue #8694]

### PR DESCRIPTION
**Pull request by infograf768**
See https://github.com/joomla/joomla-cms/issues/8694

After patch, the title of the link will be different from the text displayed.
For example, for Print Icon, one will get:
`title="Print article < First Blog Post >"`
instead of `Print`

screen shot 2016-03-11 at 10 32 14

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 02092f6c6d3143ebfcc6969ed2e24815ae0de7e0<br /><br />Tested with success.

Before patch: Link titles "Print" for print, "Email" for email and none for edit.

After patch: Meaningful and helpful link titles for all of them show what the particular icon/item is good for.

In case of the" Print" item, the title includes also the article title (so we not forget it on the way to the office printer and then know what to search for in the big paper stack :smile: ).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9372">issues.joomla.org/joomla-cms/9372</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 02092f6c6d3143ebfcc6969ed2e24815ae0de7e0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9372">issues.joomla.org/joomla-cms/9372</a>.</sub>

**Comment by brianteeman** [comment]
RTC thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9372">issues.joomla.org/joomla-cms/9372</a>.</sub>

**Comment by brianteeman** [comment]
RTC thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9372">issues.joomla.org/joomla-cms/9372</a>.</sub>

**Comment by cr2a-graphique** [comment]
nice thanks a lot

**Pull request merged**
