### PR TITLE
[4.2] Template Details and Files (tabs)

### PR DESCRIPTION
**Pull request by Kostelano**
Pull Request for Issue # .

### Summary of Changes
The PR moves the override update tab next to the create override tab, which seems much more logical to me. Accordingly - the description of the template - to the end.

Also reduced the indentation to the one used in other tabs (mt-2).

Screenshot_1

### Testing Instructions
System - Site Templates, Cassiopeia Details and Files, check the tabs.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on b13f523842efdb89abc7ee109cbe11c48df625f6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37855">issues.joomla.org/tracker/joomla-cms/37855</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on b30960f227f0b78359a5751d97a4eadb2aa15f4b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37855">issues.joomla.org/tracker/joomla-cms/37855</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37855">issues.joomla.org/tracker/joomla-cms/37855</a>.</sub>

**Comment by bembelimen** [comment]
Fine for me, but for 4.2 then

**Comment by roland-d** [comment]
Thanks everybody

**Pull request merged**
