### PR TITLE
Remove linkname continued

### PR DESCRIPTION
**Pull request by brianteeman**
PR for #16196

Linknames was removed but it is still there in the sql sample data. This simple PR removes the unused param

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 2207dabf2b16294ed0c98dc98d754174ff9254c8<br /><br />Code review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16331">issues.joomla.org/tracker/joomla-cms/16331</a>.</sub>

**Comment by tonypartridge** [comment]
I have tested this item :white_check_mark: successfully on 2207dabf2b16294ed0c98dc98d754174ff9254c8<br /><br />Code review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16331">issues.joomla.org/tracker/joomla-cms/16331</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
