### PR TITLE
[4.3] Com_banners string [a11y]

### PR DESCRIPTION
**Pull request by brianteeman**
### Summary of Changes
The language key used to provide the aria label on the banner edit form is incorrect. This PR corrects that

### Testing Instructions
in the admin view the source of the banner edit form and the client edit form

Note that if it is a new banner or an edit banner the string is slightly different

### Actual result BEFORE applying this Pull Request
image

### Expected result AFTER applying this Pull Request
image

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 97c5f7091cfea818f4b03a911875fdfed931c5e3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40496">issues.joomla.org/tracker/joomla-cms/40496</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40496">issues.joomla.org/tracker/joomla-cms/40496</a>.</sub>

**Comment by obuisard** [comment]
Thank you Brian @brianteeman :-)

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
