### PR TITLE
Updated korean installation language

### PR DESCRIPTION
**Pull request by Bakual**
Hopefully last instalaltion language update for 3.7.4 :smile: 

Merge by review once Travis passes.

### CODE REVIEW

**Comment by zero-24** [comment]
I have just rebooted travis as it is failing.

**Comment by zero-24** [comment]
hmm Is something wrong with travis?
```
ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/var/run/mysqld/mysqld.sock' (2)
```

**Comment by wilsonge** [comment]
OK I restarted builds. The mysql is dead. This is running on the new linux architecture which means no PHP 5.3 :( so that's failing. I've no clue why apc is failing on PHP 5.4 though. @mbabker any ideas?

**Comment by zero-24** [comment]
I have rebooted travis already a few times. With no luck.

**Comment by Bakual** [comment]
Added nb-NO to the mix.

**Comment by infograf768** [comment]
still can' merge...

**Pull request merged**
