### PR TITLE
Update create-translation-pull-request-v4.yml

### PR DESCRIPTION
**Pull request by alexandreelise**
Might found a typo on SYNC_VERSION environment variable

Pull Request for Issue # .

### Summary of Changes
Might found a typo on SYNC_VERSION environment variable. I might be wrong. Just trying to help.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on e9794128c7d47379d6553244c3dfee0478708ff8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37344">issues.joomla.org/tracker/joomla-cms/37344</a>.</sub>

**Comment by alexandreelise** [comment]
Thanks @brianteeman . Have a great day.

**Comment by zero-24** [comment]
@bembelimen on merging here please remember to fix the bot as he by his self is not allowed to change workflow files and will fail on that error after any change to the workflow files.
cc @HLeithner

**Comment by HLeithner** [comment]
thanks @alexandreelise

**Comment by alexandreelise** [comment]
No problem @HLeithner. I am here to help as much as I can. Enjoy your day super joomlers!

**Pull request merged**
