### PR TITLE
[4.0] Sidebar hover fix

### PR DESCRIPTION
**Pull request by brianteeman**
PR #28289

Pull Request for Issue #28289 

Hover background size on sidebar dashboard and quicklink icons .

### CODE REVIEW

**Comment by jwaisner** [comment]
@brianteeman The issue referenced for this PR was never confirmed. I could not replicate.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28290">issues.joomla.org/tracker/joomla-cms/28290</a>.</sub>

**Comment by Quy** [comment]
@jwaisner This is reproducible with the nightly build.

**Comment by Quy** [comment]
On hover, the icon is smaller resulting in flickering.

**Comment by jwaisner** [comment]
@Quy Flickering? I guess I didnt understand the issue cited for this PR being related to overlap.

**Comment by Quy** [comment]
The reported issue with overlapping is reproducible with the nightly build. The flickering is a separate issue from this PR.

**Comment by jwaisner** [comment]
as of commit a46cafa3fc0379af38577743525b1f72730e67a2 (latest pull from this morning) I was not able to reproduce the issue cited in the nightly build. This could have been corrected by another PR. Can you confirm with latest pull from the repo?

**Comment by Quy** [comment]
It appears that you did not run `npm i` as the menu icons in your screenshot are not larger.

**Comment by jwaisner** [comment]
I run `npm ci` after pulling from the repo. I stand corrected though. I reset the files and clean installed again and I see the issue. I will test the fix.

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 2c685257a81f835fbd459cc356b4ddfa6b78a1d6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28290">issues.joomla.org/tracker/joomla-cms/28290</a>.</sub>

**Comment by jwaisner** [comment]
I have not tested this item.<br /><br />After reviewing this again if you move your cursor in between the dashboard icons the selector will jump between them constantly. I don't have a way to pull video of this but I don't think that is intended. Might need to adjust the hover size a bit more to prevent it.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28290">issues.joomla.org/tracker/joomla-cms/28290</a>.</sub>

**Comment by brianteeman** [comment]
Try to record it with licecap. It's cross platform and open source

**Comment by Quy** [comment]
Put cursor between the dashboards. It will toggle between the two dashboards and the icon is smaller on hover.

dashboard

**Comment by brianteeman** [comment]
I can see the problem now and will update this PR to resolve it

**Comment by brianteeman** [comment]
updated

**Comment by brianteeman** [comment]
Drone errors are unrelated to this PR and hopefully fixed with #28293

**Comment by brianteeman** [comment]
@wilsonge can you restart drone please

**Comment by wilsonge** [comment]
done

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 509805143147a6f9b89548bb584d007462459867<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28290">issues.joomla.org/tracker/joomla-cms/28290</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 509805143147a6f9b89548bb584d007462459867<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28290">issues.joomla.org/tracker/joomla-cms/28290</a>.</sub>

**Comment by jwaisner** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28290">issues.joomla.org/tracker/joomla-cms/28290</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
