### PR TITLE
Fix language debug on multilingual sites

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Pass language debug setting to new language instance.

### Testing Instructions

Set up a multilingual site.
Enable `Debug Language` option in Global Configuration.
View frontend in any language other than default.

### Expected result

Language debug working, i.e. translatable strings are wrapped with `**`.

### Actual result

Language debug not working.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on df6331dc8ccd8acfc3b5586525317c280acfce79<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27209">issues.joomla.org/tracker/joomla-cms/27209</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on d2a944a83871aee0eff303279da708e018b7f406<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27209">issues.joomla.org/tracker/joomla-cms/27209</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27209">issues.joomla.org/tracker/joomla-cms/27209</a>.</sub>

**Comment by infograf768** [comment]
Restarting drone.

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
