### PR TITLE
Plugin-definable fields in login modules / views

### PR DESCRIPTION
**Pull request by nikosdion**
This PR contains the PLT-accepted portion of gh-11778  See that PR for the history of this feature.

Pinging @wilsonge and @jeckodevelopment 

The changes made allow authentication plugins to render their own fields in the login modules and the login views of com_users. This is necessary for social network authentication, single sign on integration and generally any authentication method which does not rely on a Joomla-provided username/password pair.

No further instructions provided as this feature has already been approved by the PLT.

### CODE REVIEW

**Comment by zero-24** [comment]
Thank you for doing this! I can have a look into the travis problems and provide a PR if i'm back from #jd16de :+1: Thanks.

**Comment by jeckodevelopment** [comment]
Thank you very much @nikosdion 
I'd be very happy to see the other part of the PR as "official extension". Let me know if you are interested! :)

**Comment by nikosdion** [comment]
@jeckodevelopment Yes, I am interested in doing that. I won't have time before mid-October as I'm about to do the single most important commit of my life: getting married :D Please let me know what is the best way to contact you when I'm back to normal so we can set up a repository and I can start committing code there.

**Comment by jeckodevelopment** [comment]
@nikosdion happy to read both that news: leading the extension and the wedding :smile: 
Best way to get in touch with me? email luca.marzo[at]community.joomla.org or via Glip. 
We'll setup the repository so you can work at the extension.
Thank you for the help!

**Comment by zero-24** [comment]
@nikosdion FYI https://github.com/nikosdion/joomla-cms/pull/2

**Comment by nikosdion** [comment]
I refuse to participate in this project due to lack of transparency and respect to its contributors. I forbid you from using the code in this PR in future versions of Joomla!.

**Pull request closed without merging**
