### PR TITLE
[5.1] Add main region on error page

### PR DESCRIPTION
**Pull request by Razzo1987**
Pull Request related to #42652 .
Read comment https://github.com/joomla/joomla-cms/pull/42652#discussion_r1452413376
Now whe are changing the semantic.

### Summary of Changes
Add `<main>` on `error.php` template page.
Also when there is a module in the `error-*` position

### Testing Instructions

Case 1: Go on page error and see the source
Case 2: Add module to `error-403` or `error-404` position. Go on page error and see the source

### Actual result BEFORE applying this Pull Request
Case 1 and Case 2: There is no `<main>` element

### Expected result AFTER applying this Pull Request
Case 1: Now the error message is inside the `<main>` element
Case 2:  Now the module is inside the `<main>` element

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

Thanks to @brianteeman and @richard67 for the brainstorming ;)

### CODE REVIEW

**Comment by brianteeman** [comment]
You should also add the `main` region for the regular use

**Comment by richard67** [comment]
> You should also add the `main` region for the regular use

@Razzo1987 Yes, Brian is right, it should also be added in the else branch like I wrote in [my comment which you referred to](https://github.com/joomla/joomla-cms/pull/42652#discussion_r1452413376):

> I think the `<main>` should go to line 163 of the file changed by this PR, just after the `<jdoc:include type="message" />`, and it should be closed in line 177 (or 178 after adding the opening tag) just after the `</blockquote>` and before the `</div>`.

Here in 5.1-dev the line numbers stilll fit to my comment.

**Comment by Razzo1987** [comment]
Correct, thanks!

**Comment by richard67** [comment]
@Razzo1987 Now it needs to adapt the testing instructions so that both cases are checked, with and without any module on an error-403 or error-404 position.

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on c6d4534d2f31aeddeb887a80d90a7d2e1b7810d2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42719">issues.joomla.org/tracker/joomla-cms/42719</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on c6d4534d2f31aeddeb887a80d90a7d2e1b7810d2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42719">issues.joomla.org/tracker/joomla-cms/42719</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42719">issues.joomla.org/tracker/joomla-cms/42719</a>.</sub>

**Comment by LadySolveig** [comment]
Thank you @Razzo1987 and also for testing to @brianteeman and @viocassel

**Pull request merged**
