### PR TITLE
working link to license

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #38326

### Summary of Changes
Change the link from gnu.org which now orevents access in an iframe to the help site where @ceford created the correct page

### Testing Instructions
Make sure the licence link works

image

### CODE REVIEW

**Comment by sandewt** [comment]
I have tested this item :red_circle: unsuccessfully on 9f07308c464c7825e7f9d4021835cff2405886a1<br /><br />Header is set to X-Frame-Options "SAMEORIGIN" of the Joomla docs help file.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38366">issues.joomla.org/tracker/joomla-cms/38366</a>.</sub>

**Comment by brianteeman** [comment]
Sorry - forgot to commit the last change

**Comment by sandewt** [comment]
I have tested this item :white_check_mark: successfully on d106e0693b0714163073cf6ee7fb805deafd1cf2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38366">issues.joomla.org/tracker/joomla-cms/38366</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on d106e0693b0714163073cf6ee7fb805deafd1cf2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38366">issues.joomla.org/tracker/joomla-cms/38366</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38366">issues.joomla.org/tracker/joomla-cms/38366</a>.</sub>

**Comment by roland-d** [comment]
Thank you

**Pull request merged**
