### PR TITLE
Joomla 3.9.0 Part 12

### PR DESCRIPTION
**Pull request by wilsonge**
Takes us to 3.9.0 beta

Merge with a merge commit don't squash or rebase

### CODE REVIEW

**Comment by wilsonge** [comment]
@SniperSister @zero-24 RIPS please

**Comment by zero-24** [comment]
reboot is runnig at: http://ci.joomla.org/joomla/joomla-cms/16775

**Comment by zero-24** [comment]
Rips is happy now cc @wilsonge

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
