### PR TITLE
[4.0] Use getBase64 filter

### PR DESCRIPTION
**Pull request by Quy**
Pull Request for Issue #26651.

### Summary of Changes
Use `getBase64` filter. 
`getCmd` accepts only `A-Za-z0-9.-_` therefore `=` and `/` are stripped in the below return URL.

`aHR0cDovL2xvY2FsaG9zdC9qb29tbGEtY21zLTQuMC1kZXYvYWRtaW5pc3RyYXRvci9pbmRleC5waHA/b3B0aW9uPWNvbV9jb250ZW50JnZpZXc9YXJ0aWNsZXM=`

### Testing Instructions

* go to Content > Articles
* go to User Menu > Edit Account (in the upper right hand corner)
* click Close button

### Actual result
```
Error: "500 "http://localhost/joomla-cms-4.0-dev/administrator/index.php�[ۏX��W��۝[� ��Y]�X\�X�\" is not valid header value" is not valid header value: "http://localhost/joomla-cms-4.0-dev/administrator/index.php�[ۏX��W��۝[� ��Y]�X\�X�\" is not valid header value
```

### CODE REVIEW

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on d3a3fe65f52ec4eab3d81907a499adb30f1a2099<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26776">issues.joomla.org/tracker/joomla-cms/26776</a>.</sub>

**Comment by infograf768** [comment]
Can't reproduce the error here with super user account, therefore can't test.

**Comment by SharkyKZ** [comment]
@infograf768 This only happens on specific URLs. When they contain `/` once Base64 encoded.

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on ab267bf61f6dea94826996796822b932441be649<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26776">issues.joomla.org/tracker/joomla-cms/26776</a>.</sub>

**Comment by SharkyKZ** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26776">issues.joomla.org/tracker/joomla-cms/26776</a>.</sub>

**Comment by priyankaSahutekdi** [comment]
I have tested this item :white_check_mark: successfully on 2612c07e144a72282c3082ef7cba39039a395565<br /><br />issue fixed <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26776">issues.joomla.org/tracker/joomla-cms/26776</a>.</sub>

**Comment by thite-amol** [comment]
I have tested this item :white_check_mark: successfully on 2612c07e144a72282c3082ef7cba39039a395565<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26776">issues.joomla.org/tracker/joomla-cms/26776</a>.</sub>

**Comment by wilsonge** [comment]
Makes a lot of sense. Thanks!

**Pull request merged**
