### PR TITLE
[4.0] Omit default arguments when loading language files

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Default values for 3-5 arguments of `Joomla\CMS\Language\Language::load()` are `null`, `false`, `true`.

https://github.com/joomla/joomla-cms/blob/a9f80d608f0c0e00abf6cdf04c1c4f9932c44c42/libraries/src/Language/Language.php#L684

We can omit them when making the calls.

### Testing Instructions

Code review.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 10b5a6453b09fa15bbb129dd0f50a989c41bcb80<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27720">issues.joomla.org/tracker/joomla-cms/27720</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 10b5a6453b09fa15bbb129dd0f50a989c41bcb80<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27720">issues.joomla.org/tracker/joomla-cms/27720</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27720">issues.joomla.org/tracker/joomla-cms/27720</a>.</sub>

**Comment by richard67** [comment]
@SharkyKZ Drone failure seems not to be related to this PR, but if you wanna be sure: Use the update to base branch button ;-)

**Pull request merged**
