### PR TITLE
Fix logging in in PHP 5.3

### PR DESCRIPTION
**Pull request by wilsonge**
Pull Request for Issue #11428 .
#### Summary of Changes

Fixes login in PHP 5.3
#### Testing Instructions

Test logging in and logging out. In PHP 5.4+ continues to work in 5.3 it starts working again

### CODE REVIEW

**Comment by wilsonge** [comment]
Marking test of @sarsami from #11428<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11430">issues.joomla.org/joomla-cms/11430</a>.</sub>

**Comment by mediosweb** [comment]
i have made suggested modfications, and still get same error:
Se ha producido un error.

    0 Failed to start the session: already started by PHP ($_SESSION is set).

**Comment by Sandhie** [comment]
Works for me... Thank you!

**Comment by mediosweb** [comment]
Has worked !
sorry i missed line 154
now its ok!
thanks!!!

**Comment by missnene** [comment]
IT WORKS!!! 👍  Thanks!
I think if I saw that failed to start session error one more time, I wouldn't own a laptop anymore.  😂

**Comment by Flow1976** [comment]
I have a same problem :(
0 Failed to start the session: already started by PHP ($_SESSION is set).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11430">issues.joomla.org/joomla-cms/11430</a>.</sub>

**Comment by Flow1976** [comment]
👍 Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11430">issues.joomla.org/joomla-cms/11430</a>.</sub>

**Comment by joomdonation** [comment]
I have tested this item :white_check_mark: successfully on cfcaac3b7bf553a33a6bced765f3b8bdcb2f41fb<br /><br />Tested on two test sites:

1. One site running on PHP 5.3: Before patch, we had issue with Login. After patch, login works.

2. One site running on PHP 5.6: Login still works after applying the patch.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11430">issues.joomla.org/joomla-cms/11430</a>.</sub>

**Comment by khanhlh** [comment]
The fix works. Anyway, set default value for `$started` as `false` and `$closed` as `true` is enough to fix the issue.

**Comment by joomla-ua** [comment]
PHP 5.3.17 after apply patch work perfect!

**Comment by wilsonge** [comment]
Thanks guys. I've merged this. I'll hold until this evening to make sure there are no more issues that are going to crop up. But probably will be a 3.6.2 tonight with this in

**Comment by PhilETaylor** [comment]
If you are running PHP 5.3 then you have bigger issues than just this. Pathetic.

**Comment by jrmain** [comment]
@PhilETaylor - in my case, as it likely is with many other people still technically running PHP 5.3, what I'm actually running is a version of PHP 5.3 that's had relevant post-5.3 security fixes applied to it, such as the versions available for Ubuntu LTS releases. I actually prefer to run tried and tested version of PHP, rather than the latest versions with new features and changes that are typically the source of new security vulnerabilities. Of course, eventually I'll have to upgrade when certain new features become necessary.

**Comment by jrmain** [comment]
This fix worked perfectly for me. Looking forward to the official fix in 3.6.2. Thanks!

**Comment by PhilETaylor** [comment]
There is no reason at all for running PHP 5.3 in July 2016... its all excuses I have heard time and again.

**Comment by elistina** [comment]
IT WORKS!!! Thanks a lot!

**Comment by jrmain** [comment]
@PhilETaylor - Yeah, well, that's just, like, your opinion, man. I would rather run a secure server than one that supports features I don't need.

**Comment by smu77** [comment]
Thx a lot. Works fine!

**Comment by mbabker** [comment]
Not sure how a server running unsupported software is secure but that's neither here nor there regarding this issue.

**Comment by Luisriveraa** [comment]
Great. I works fine. Thanks a lot.

**Comment by Nexthought** [comment]
How can I apply the patch ? I have no directory where to put it and can't open the joomla session. Please help !! 😰

**Comment by wojsmol** [comment]
@Nexthought Please see https://github.com/joomla/joomla-cms/pull/11430/files

**Comment by Nexthought** [comment]
@wojsmol I saw it but I don't know where/how to apply it to make it effective. I am just beggining in this stuff.

**Comment by lalapo1** [comment]
@Nexthought go here and copy:
https://raw.githubusercontent.com/joomla/joomla-cms/cfcaac3b7bf553a33a6bced765f3b8bdcb2f41fb/libraries/joomla/session/handler/native.php

replace

public_html/libraries/joomla/session/handler/native.php

**native.php**

regards

**Comment by PhilETaylor** [comment]
I have not tested this item.<br /><br />I used Joomla 3.6.1 Stable, ***PHP 5.3.29***, on attempting to Login to frontend as super admin I get the common reported error message

I then manually applied patch from https://patch-diff.githubusercontent.com/raw/joomla/joomla-cms/pull/11430.patch with `patch -p0 < patch` and retested.

I was able to login in and out on the frontend and the admin console with a super admin with no errors. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11430">issues.joomla.org/joomla-cms/11430</a>.</sub>

**Comment by PhilETaylor** [comment]
I have tested this item :white_check_mark: successfully on cfcaac3b7bf553a33a6bced765f3b8bdcb2f41fb<br /><br />I used Joomla 3.6.1 Stable, ***PHP 5.3.29***, on attempting to Login to frontend as super admin I get the common reported error message

I then manually applied patch from https://patch-diff.githubusercontent.com/raw/joomla/joomla-cms/pull/11430.patch with `patch -p0 < patch` and retested.

I was able to login in and out on the frontend and the admin console with a super admin with no errors. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11430">issues.joomla.org/joomla-cms/11430</a>.</sub>

**Comment by microtribe** [comment]
I applied this fix and it worked running PHP 5.3. But upgrading to PHP 5.6 worked too and didn't require this fix.

**Comment by brianteeman** [comment]
On 4 Aug 2016 7:55 p.m., "Tony" <notifications@github.com> wrote:
>
> I applied this fix and it worked running PHP 5.3. But upgrading to PHP
5.6 worked too and didn't require this fix.
>

Obviously because this is only needed on 5.3

**Comment by PhilETaylor** [comment]
>I applied this fix and it worked running PHP 5.3. But upgrading to PHP 5.6 worked too and didn't require this fix.

Which is actually the CORRECT reaction to hitting a bug like this - well done. Upgrading is FTW.

**Comment by eduardocfs** [comment]
Works for me... Thank you!
I will follow the @PhilETaylor  advice and upgrade my PHP.

**Comment by ninj1766** [comment]
what file name and where do I need to paste in this patch? Please.
Do I need to edit/replace any other code?

**Comment by ninj1766** [comment]
Also I am using PHP 5.39 right now

**Comment by PhilETaylor** [comment]
> Also I am using PHP 5.39 right now

There is no such version! 

5.3.9?   5.3.29? Those are valid (albeit end of life, insecure, buggy, historic, ancient) versions.

**Comment by ninj1766** [comment]
5.4 now at the time of the error it was 5.3 so should I revert back to 5.3 to use this patch and where do I place it? Please. I am not a coder but I can manage my C-Panel file manager and copy and paste.

**Comment by Nexthought** [comment]
@ninj1766 do you have your ftp set up?

**Comment by motofficina** [comment]
I encountered the same problem yesterday when I was trying to log in on the back end. An error message appears as **"Failed to start the session: already started by PHP ($_SESSION is set)"**

I don't know technically what I need to do especially about erasing or adding a code in a php or whatever file it may be because I am not familiar with the programming language... but I'm willing to learn step by step.  Please help me!!!

Urgent...

**Comment by brianteeman** [comment]
@motofficina please use the forum for support http://forum.joomla.org

**Comment by wilsonjda** [comment]
Hello everybody, I have a problem, I tried to fix the file native.php but now I had a blank page.

**Comment by ggppdk** [comment]
> Hello everybody, I have a problem, I tried to fix the file native.php but now I had a blank page.

while trying to apply the fix you have broken the SYNTAX of the file 
- error is not displayed by default thus it is hidden

**Just restore the file**

Now , **If you have J3.6.1 !!**

1. Edit file 
libraries/joomla/session/handler/native.php

2. Delete all contents (do not save yet)

3. Carefully copy paste ALL text from here:
https://raw.githubusercontent.com/joomla/joomla-cms/cfcaac3b7bf553a33a6bced765f3b8bdcb2f41fb/libraries/joomla/session/handler/native.php

4. Save file , now you can login and update to J3.6.2


You can also do "Save as" in your browser for the above link and replace the file too

For anything more, please post here:
http://forum.joomla.org

**Comment by wilsonjda** [comment]
Hello ggppdk, thanks for your answer, I did what you said, but it doesn't work, blank page and in the Chrome console said: Error 500.

**Comment by ggppdk** [comment]
are you sure that you copy pasted the exact text ?
are you sure that you have not editted ANY other files ?

**also you may need to close all browser windows and re-open the browser**,

Do the above and if it does not work then do this:

1. Rename the file libraries/joomla/session/handler/native.php
2. Do a "save as"  of:  https://raw.githubusercontent.com/joomla/joomla-cms/3.6.2/libraries/joomla/session/handler/native.php
3. Save it as: **native.php** Copy it to:  libraries/joomla/session/handler/native.php
4. Close all browsers windows, restart your browser, login and upgrade to J3.6.2

---

Finally it is possible to see the error of the "blank" page

Edit (you may need to make it writable (temporarily))
- configuration.php

change:
public $error_reporting = 'default';

to:
public $error_reporting = 'simple';

Please post to: http://forum.joomla.org
i will not answer any further

**Comment by wilsonjda** [comment]
I changed error reporting and there a problem with Akeeba Backup, I'm going talk to my client in order to they update PHP version. Thanks for your advice it is not a joomla issue, excuse me.

**Comment by motofficina** [comment]
hey, thanks! it worked :D

**Comment by Belaswan** [comment]
I can't login from frontend after upgrade from joomla 3.6.1 to joomla 3.6.2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11430">issues.joomla.org/joomla-cms/11430</a>.</sub>

**Pull request merged**
