### PR TITLE
Add Yandex search engine to the robots list

### PR DESCRIPTION
**Pull request by jurihahn**
Pull Request for Issue # .

### Summary of Changes
Yandex search engine bots are not in the robots list. This PR add it.
https://yandex.com/support/webmaster/robot-workings/check-yandex-robots.html

### Testing Instructions
Code review

### Expected result
Yandex Bot is in the robots list

### Actual result
Yandex Bot is NOT in the robots list

### Documentation Changes Required
No

### CODE REVIEW

**Review by wilsonge — APPROVED** [review]

**Review by brianteeman — APPROVED** [review]

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 32e148d1fb80f0c0472aace56f4b3c9986c516a2<br /><br />Code review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22337">issues.joomla.org/tracker/joomla-cms/22337</a>.</sub>

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on 32e148d1fb80f0c0472aace56f4b3c9986c516a2<br /><br />Code review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22337">issues.joomla.org/tracker/joomla-cms/22337</a>.</sub>

**Comment by jurihahn** [comment]
thanks for tests and reviews

**Comment by jurihahn** [comment]
need i to close this PR?

**Pull request merged**
