### PR TITLE
MSSQL - Pagination fix

### PR DESCRIPTION
**Pull request by alikon**
#### Steps to reproduce the issue

use pagination and set a limit
example go to Administration   Article Manager  Articles and set a limit for show only 5 articlesper page
#### Expected result

pagination works well  show only 5 articles per page
#### Actual result

don't work  show more articles

jmssql pagination administration article manager articles
#### System information (as much as possible)

PHP Version  5.5.9
Web Server  Apache/2.4.7 (Win32) 
Joomla! Version Joomla! 3.4.1 
Database MSSQL 2008 R2
#### Additional comments

fixed the process limit query on sqlsrv 

```
  SELECT * FROM ( 
   the old $query
) A WHERE A.RowNumber  BETWEEN start AND end;
```

### CODE REVIEW

**Comment by wilsonge** [comment]
This exact code was removed in https://github.com/joomla/joomla-cms/pull/5293 - are we sure that we aren't introducing new bugs elsewhere?

**Comment by alikon** [comment]
i've followed these
 http://blogs.msdn.com/b/sqlserver/archive/2006/10/25/limit-in-sql-server.aspx
 https://technet.microsoft.com/en-us/library/ms186734.aspx

don't know about #5293 and  azure

**Comment by sovainfo** [comment]
@test OK
Issue confirmed on MS SQL. PR resolves issue.
Fixes the regression introduced by #5293 reported in #6414 !

Considering Azure works the same, it should be applied there as well.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7149">issues.joomla.org/joomla-cms/7149</a>.</sub>

**Comment by designbengel** [comment]
Is there any free webhost service for testing MS SQL? I just tried somee.com but have some issues creating the ms sql Database there... :(<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7149">issues.joomla.org/joomla-cms/7149</a>.</sub>

**Comment by alikon** [comment]
i can recommend to use on  a localhost the "express"  edition  is a free version of MSSQL

**Comment by waader** [comment]
@test works!

**Comment by zero-24** [comment]
RTC Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7149">issues.joomla.org/joomla-cms/7149</a>.</sub>

**Comment by wilsonge** [comment]
Merged - thanks!

**Pull request closed without merging**
