### PR TITLE
Codestyle tinymce xml

### PR DESCRIPTION
**Pull request by zero-24**
#### Summary of Changes

Codestyle for the tinymce xml file
#### Testing Instructions
- apply the patch
- go to the tinymce options
- confirm that all still there
- or code review

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
> The four attributes name, type, label and description should be written in this order and at the top of the element definition.

See http://joomla.github.io/coding-standards/?coding-standards/chapters/xml.md

**Comment by zero-24** [comment]
here you go: https://github.com/joomla/joomla-cms/pull/10386/commits/abad7274e0c554b012d205f96c98e6b4b4ec7960 we should get rid of all that option :P

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on abad7274e0c554b012d205f96c98e6b4b4ec7960<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10386">issues.joomla.org/joomla-cms/10386</a>.</sub>

**Comment by MATsxm** [comment]
I have tested this item :white_check_mark: successfully on abad7274e0c554b012d205f96c98e6b4b4ec7960<br /><br />everything looks :+1:  - thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10386">issues.joomla.org/joomla-cms/10386</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10386">issues.joomla.org/joomla-cms/10386</a>.</sub>

**Comment by zero-24** [comment]
Thanks

**Pull request merged**
