### PR TITLE
[4.1] scheduler toolbar

### PR DESCRIPTION
**Pull request by brianteeman**
Updates the code for the enaable/disable action buttons for consistency and simplicity with all other similar uses.

To test apply the pr, create one or more tasks. Make sure you can enable and disable the tasks from the action dropdown

### CODE REVIEW

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 2105191d2e3129a8adc2bb9aca9f981dd27d22cd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36675">issues.joomla.org/tracker/joomla-cms/36675</a>.</sub>

**Comment by drmenzelit** [comment]
I have tested this item :white_check_mark: successfully on 2105191d2e3129a8adc2bb9aca9f981dd27d22cd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36675">issues.joomla.org/tracker/joomla-cms/36675</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36675">issues.joomla.org/tracker/joomla-cms/36675</a>.</sub>

**Comment by pritam825** [comment]
I have tested this item :white_check_mark: successfully on 2105191d2e3129a8adc2bb9aca9f981dd27d22cd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36675">issues.joomla.org/tracker/joomla-cms/36675</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
