### PR TITLE
[5.1] Installer manage: ignore clientid for plugin and library

### PR DESCRIPTION
**Pull request by chmst**
Pull Request for Issue # .

### Summary of Changes
Plugins and libraries are extensions independent from client_id. 
It looks like a bug when filtering for Administrator Plugins is empty but Site plugins gives a complete set of Plugins.

We can ignore the type when filtering for these extensions.

### Testing Instructions
Go to manage extensions, set filter to Administrator.
Filter for type plugins or libraries.

### Actual result BEFORE applying this Pull Request
Result is empty

### Expected result AFTER applying this Pull Request
Result is the same for type site and administrator

### Link to documentations
Please select:
- [x] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [x] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by exlemor** [comment]
I have tested this item :white_check_mark: successfully on 2ecee24f5fd2a3978b06cfed502c36fe7435a9f1<br /><br />I have tested this successfully @chmst :)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43458">issues.joomla.org/tracker/joomla-cms/43458</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 2ecee24f5fd2a3978b06cfed502c36fe7435a9f1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43458">issues.joomla.org/tracker/joomla-cms/43458</a>.</sub>

**Comment by ChristineWk** [comment]
Tried also PR on J 4.4.4 as issue also affects J 4.4 (= OK)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43458">issues.joomla.org/tracker/joomla-cms/43458</a>.</sub>

**Comment by richard67** [comment]
@chmst Could you restore the test results of the human testers in the issue tracker? You have invalidated the test count with your branch update.

**Comment by richard67** [comment]
@chmst Other question (I haven't tested it myself): Is it sill possible to set a filter on the client_id for libraries and plugins with this PR? If yes, then it might be confusing some 50% if the users when they have set that filter and it is not really applied because the client_id is ignored. The other 50% of the users may be confused by how it is now without this PR and may favour this PR.

So either with or without this PR some users might be confused.

If that is the case that the filter still can be selected for libraries and plugins with this PR, then I think we should discuss it in the weekly maintainers meeting.

**Comment by chmst** [comment]
Thx for the hin. I restored the Tests. 


<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43458">issues.joomla.org/tracker/joomla-cms/43458</a>.</sub>

**Comment by richard67** [comment]
RTC as it has 2 successful human tests ... but I think we should discuss this PR in the weekly CMS maintainers meetings due to reasons stated in my previous comment, so I also set the RMDQ (release managers decision queue) label.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43458">issues.joomla.org/tracker/joomla-cms/43458</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :red_circle: unsuccessfully on c214409cba87c8730b787cf7a39d16bd2c133b1b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43458">issues.joomla.org/tracker/joomla-cms/43458</a>.</sub>

**Comment by brianteeman** [comment]
> It looks like a bug when filtering for Administrator Plugins is empty but Site plugins gives a complete set of Plugins.

It also looks like a bug when Filtering for API Plugins and you get a complete set of plugins which is what this PR produces. I "get" the problem this PR is trying to solve but the way it is done does not solve it,

### Without PR
image

### With PR
image

**Comment by brianteeman** [comment]
If you insist on going down the path of "ignoring" the location when the type is Plugin or Package then you should also start to "ignore" the folder when the Type is anything other than plugin

**Comment by richard67** [comment]
Back to pending due to unsuccessful test.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43458">issues.joomla.org/tracker/joomla-cms/43458</a>.</sub>

**Comment by chmst** [comment]
The filter is messy but nobody cares since years so it is not worth a discussion. Closing.

**Pull request closed without merging**
