### PR TITLE
[staging] Correcting User Actions Log Manager when debug language is enabled

### PR DESCRIPTION
**Pull request by infograf768**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/24164

### Summary of Changes
Preventing translating urls

### Testing Instructions
Enable Debug language in Global Configuration
Enable the Action Log - Joomla plugin
Go to Global Configuration
Click Save & close
Go to User -> User Action Log

### Before patch
As urls pass through `Text::_`, they include ?? and links are broken.

### After patch
All is fine.
Screen Shot 2019-03-13 at 07 18 14

@roland-d @alikon @HLeithner

### CODE REVIEW

**Comment by roland-d** [comment]
I have tested this item :white_check_mark: successfully on 14e90798bc2de0f0d151d51feeb337bb69354549<br /><br />After applying the patch, the username links work as expected by opening the user edit page.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24178">issues.joomla.org/tracker/joomla-cms/24178</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 14e90798bc2de0f0d151d51feeb337bb69354549<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24178">issues.joomla.org/tracker/joomla-cms/24178</a>.</sub>

**Comment by infograf768** [comment]
RTC. Thanks for testing.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24178">issues.joomla.org/tracker/joomla-cms/24178</a>.</sub>

**Comment by zero-24** [comment]
rebooted drone on this one.

**Comment by zero-24** [comment]
Merging thanks @infograf768

**Pull request merged**
