### PR TITLE
[4.0] Added php8 to list of filtered extensions

### PR DESCRIPTION
**Pull request by SniperSister**
### Summary of Changes
Added PHP8 to the hardcoded list of executables 

### Testing Instructions
Verify by code review

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 4d73fbcdcd4c25f393a28234b3ed81d1ea311278<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35001">issues.joomla.org/tracker/joomla-cms/35001</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 4d73fbcdcd4c25f393a28234b3ed81d1ea311278<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35001">issues.joomla.org/tracker/joomla-cms/35001</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35001">issues.joomla.org/tracker/joomla-cms/35001</a>.</sub>

**Comment by richard67** [comment]
@SniperSister It's not sufficient to set the RTC label on GitHub to get the right status shown in the issue tracker. It needs to use the tracker and change status there. I've done that here now.

**Comment by brianteeman** [comment]
Why is the list shorter than in #34999

**Comment by brianteeman** [comment]
I have not tested this item.<br /><br />reverting my successful test<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35001">issues.joomla.org/tracker/joomla-cms/35001</a>.</sub>

**Comment by richard67** [comment]
Back to pending.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35001">issues.joomla.org/tracker/joomla-cms/35001</a>.</sub>

**Comment by richard67** [comment]
> Why is the list shorter than in #34999

These lists serve different purpose. The one in #34999 is for media so it e.g. disallows "js", while here it is for the input filter so we shall not disallow js because we don't know what the field might be used for.

**Comment by brianteeman** [comment]
#34999 blocks .php
#35001 blocks .php, .php3, .php4, .php5, .php6, .php7, .php8

I don't see the logic behind this difference

**Comment by richard67** [comment]
> #34999 blocks .php
> #35001 blocks .php, .php3, .php4, .php5, .php6, .php7, .php8
> 
> I don't see the logic behind this difference

@brianteeman Me neither ... but that's the other way round. You had complained the list here in #35001 is shorter than the other one in #34999 .

=> Ping @SniperSister : Should be add .php3, .php4, .php5, .php6, .php7, .php8 and possibly others to #34999 , too?

**Comment by brianteeman** [comment]
>@brianteeman Me neither ... but that's the other way round. You had complained the list here in #35001 is shorter than the other one in #34999 .

Because the entire list is shorter ;)

Just this part is longer

**Comment by richard67** [comment]
> Because the entire list is shorter ;)

@brianteeman About this aspect see my comment above https://github.com/joomla/joomla-cms/pull/35001#issuecomment-890340819 .

**Comment by brianteeman** [comment]
i disagree completely with that comment - its either secure or not. its not dependant on where it is used.

**Comment by SniperSister** [comment]
I have added the extensions for php3-8, good catch!

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on 4d73fbcdcd4c25f393a28234b3ed81d1ea311278<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35001">issues.joomla.org/tracker/joomla-cms/35001</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35001">issues.joomla.org/tracker/joomla-cms/35001</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :red_circle: unsuccessfully on 4d73fbcdcd4c25f393a28234b3ed81d1ea311278<br /><br />The reasoning behind this list makes it incomplete<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35001">issues.joomla.org/tracker/joomla-cms/35001</a>.</sub>

**Comment by richard67** [comment]
Back to pending.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35001">issues.joomla.org/tracker/joomla-cms/35001</a>.</sub>

**Comment by RickR2H** [comment]
@brianteeman @richard67 This PR is set as Release Blocker... But is this really the case?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35001">issues.joomla.org/tracker/joomla-cms/35001</a>.</sub>

**Comment by wilsonge** [comment]
Merging this one. And #34999 will clean up the discrepancies in the lists

**Pull request merged**
