### PR TITLE
[4.2] Media manager improvements

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # .

### Summary of Changes
- add another script in the list of package.json scripts for compiling MM for development (dev tools friendly)
- add the package `dotenv` that is required for the above
- replace the abandoned [vuex-persistedstate](https://www.npmjs.com/package/vuex-persistedstate) with [vuex-persist](https://www.npmjs.com/package/vuex-persist)
- minor CS on the entry of the app

### Testing Instructions

- Run the commands `npm ci`, `npm run build:com_media` and `npm run build:com_media:dev` and verify that media manager works on all of them
- Create an article and select an intro image (preferably one that is inside a deep nested folder)
- Observe that the localSession has a value for the `joomla.mediamanager`
- Try to select an image for the full image input and verify that the media manager opened in the previous selected folder (ie the one you chose for the intro image)

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

The new command is documented in the build/README.md

### CODE REVIEW

**Comment by wilsonge** [comment]
We definitely need to swap the persistence plugin out. I also think @laoneo probably should give this a good test against DP Media :)

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on 946a99f7b6ad471278948230d56ac20767a2dbec<br /><br />I was not sure about the sequence to apply the npm commands - but the media manager worked after npm ci and after npm ci + both others. I could see local session change as different folders were selected. The full image folder opened either with the folder containing the existing image or with the folder from the session storage - is that right. Complicated, but I could not see anything wrong.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39409">issues.joomla.org/tracker/joomla-cms/39409</a>.</sub>

**Comment by dgrammatiko** [comment]
@ceford thanks for testing this.

> Complicated,

Yeah it's weird but somehow we needed to keep in memory the state of the last visited folder and localSession was a good solution. FWIW I'm not changing anything in the logic of the media manager here, I'm just swapping a plugin for another one

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 946a99f7b6ad471278948230d56ac20767a2dbec<br /><br />👍<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39409">issues.joomla.org/tracker/joomla-cms/39409</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39409">issues.joomla.org/tracker/joomla-cms/39409</a>.</sub>

**Comment by wilsonge** [comment]
Two good tests and seeing a thumbs up from @laoneo so merging. Thanks!

**Pull request merged**
