### PR TITLE
Update removefolder.php

### PR DESCRIPTION
**Pull request by donald-pg**
Thanks to the help of Chris D, we determined the real issue is that some redundant code is in this file for FTP but that screen has been removed during the installation.

edit (by @zero-24)
### Testinstructions

Install Joomla on two webservers, one requiring FTP to be used, the other not requiring FTP to be used.
Upon completion in both situations:
- the installation folder must be removed without problem.
- Verify content of robots.txt, unchanged if existing before installation, otherwise equal to content of robots.txt.dist.
- no joomla.xml may exist in root folder.

### CODE REVIEW

**Comment by brianteeman** [comment]
After considerable time without update I am closing this. If you feel this is still an issue please provide further information and it can always be reopened<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5025">issues.joomla.org/joomla-cms/5025</a>.</sub>

**Comment by Hackwar** [comment]
Hi @brianteeman, the issue is still valid and should be tested. As far as I can see, this code is still up-to-date and should be merged if possible. Simply needs testers...

**Comment by brianteeman** [comment]
Donald said he would revise the patch and hasn't

**Comment by Hackwar** [comment]
I can offer to work on this some time in this month and provide a new PR, but that would require that I remember this PR and that it be left open. :wink: Would that be acceptable?

**Comment by brianteeman** [comment]
Let's not do silly things like that. We can't and shouldnt keep stale
issues open for ever. If you want to create a new PR then make a note in
your calendar.

**Comment by Hackwar** [comment]
ok

**Comment by rummybocom** [comment]
[rummy circle]( https://rummybo.com/blog/18.html "rummy circle")
[rummy]( https://rummybo.com/blog/19.html "rummy")
[rummy wealth]( https://rummybo.com/blog/20.html "rummy wealth")
[rummy nabob]( https://rummybo.com/blog/21.html "rummy nabob")
[rummy glee]( https://rummybo.com/blog/22.html "rummy glee")
[rummy gold]( https://rummybo.com/blog/23.html "rummy gold")
[rummy modern]( https://rummybo.com/blog/24.html "rummy modern")
[junglee rummy]( https://rummybo.com/blog/25.html "junglee rummy")
[holy rummy]( https://rummybo.com/blog/26.html "holy rummy")
[rummy east]( https://rummybo.com/blog/27.html "rummy east")
[rummy ola]( https://rummybo.com/blog/28.html "rummy ola")
[rummy ares]( https://rummybo.com/blog/29.html "rummy ares")
[royally rummy]( https://rummybo.com/blog/30.html "royally rummy")
[rummy culture]( https://rummybo.com/blog/31.html "rummy culture")
[rummy noble]( https://rummybo.com/blog/32.html "rummy noble")
[rummy joy]( https://rummybo.com/blog/33.html "rummy joy")
[rummy mate]( https://rummybo.com/blog/34.html "rummy mate")
[rummy perfect]( https://rummybo.com/blog/35.html "rummy perfect")
[all rummy app]( https://rummybo.com/blog/36.html "all rummy app")
[rummy meet]( https://rummybo.com/blog/37.html "rummy meet")
[yono rummy]( https://rummybo.com/blog/38.html "yono rummy")
[rummy 51 bonus]( https://rummybo.com/blog/39.html "rummy 51 bonus")
[rummy time]( https://rummybo.com/blog/40.html "rummy time")
[rummy star]( https://rummybo.com/blog/41.html "rummy star")
[rummy yes]( https://rummybo.com/blog/42.html "rummy yes")
[rummy golds]( https://rummybo.com/blog/43.html "rummy golds")
[rummy loot]( https://rummybo.com/blog/44.html "rummy loot")
[rummy game]( https://rummybo.com/blog/45.html "rummy game")
[rummy holy]( https://rummybo.com/blog/46.html "rummy holy")
[rummy gold apk]( https://rummybo.com/blog/47.html "rummy gold apk")
[rummy all app]( https://rummybo.com/blog/48.html "rummy all app")
[rummy app]( https://rummybo.com/blog/49.html "rummy app")
[a23 rummy]( https://rummybo.com/blog/50.html "a23 rummy")
[rummy best]( https://rummybo.com/blog/51.html "rummy best")
[royal rummy]( https://rummybo.com/blog/52.html "royal rummy")
[rummy royally]( https://rummybo.com/blog/53.html "rummy royally")
[rummy circle app download]( https://rummybo.com/blog/54.html "rummy circle app download")
[rummy satta]( https://rummybo.com/blog/55.html "rummy satta")
[vip rummy]( https://rummybo.com/blog/56.html "vip rummy")
[rummy vip]( https://rummybo.com/blog/57.html "rummy vip")
[rummy modern apk]( https://rummybo.com/blog/58.html "rummy modern apk")
[joy rummy]( https://rummybo.com/blog/59.html "joy rummy")
[all rummy app list]( https://rummybo.com/blog/60.html "all rummy app list")
[top 20 rummy 51 bonus]( https://rummybo.com/blog/61.html "top 20 rummy 51 bonus")
[rummy mars]( https://rummybo.com/blog/62.html "rummy mars")
[rummy most]( https://rummybo.com/blog/63.html "rummy most")
[rummy apk]( https://rummybo.com/blog/64.html "rummy apk")
[rummy deity]( https://rummybo.com/blog/65.html "rummy deity")
[online rummy]( https://rummybo.com/blog/66.html "online rummy")
[rummy tour]( https://rummybo.com/blog/67.html "rummy tour")
[holy rummy apk]( https://rummybo.com/blog/68.html "holy rummy apk")
[all rummy app list 51 bonus]( https://rummybo.com/blog/69.html "all rummy app list 51 bonus")
[rummy rules]( https://rummybo.com/blog/70.html "rummy rules")
[ek rummy]( https://rummybo.com/blog/71.html "ek rummy")
[rummy master]( https://rummybo.com/blog/72.html "rummy master")
[rummy wealth apk]( https://rummybo.com/blog/73.html "rummy wealth apk")
[rummy meta]( https://rummybo.com/blog/74.html "rummy meta")
[rummy all]( https://rummybo.com/blog/75.html "rummy all")
[rummy passion]( https://rummybo.com/blog/76.html "rummy passion")
[new rummy app 2023 51 bonus]( https://rummybo.com/blog/77.html "new rummy app 2023 51 bonus")
[rummy leader]( https://rummybo.com/blog/78.html "rummy leader")
[rummy star apk]( https://rummybo.com/blog/79.html "rummy star apk")
[rummy circle download]( https://rummybo.com/blog/80.html "rummy circle download")
[rummy rani]( https://rummybo.com/blog/81.html "rummy rani")
[rummy list]( https://rummybo.com/blog/82.html "rummy list")
[rummy online]( https://rummybo.com/blog/83.html "rummy online")
[rummy model]( https://rummybo.com/blog/84.html "rummy model")
[rummy royal]( https://rummybo.com/blog/85.html "rummy royal")
[rummy circle app]( https://rummybo.com/blog/86.html "rummy circle app")
[rummy club]( https://rummybo.com/blog/87.html "rummy club")
[rummy bloc]( https://rummybo.com/blog/88.html "rummy bloc")
[rummy circle apk]( https://rummybo.com/blog/89.html "rummy circle apk")
[hello rummy]( https://rummybo.com/blog/90.htm "hello rummy")
[all rummy]( https://rummybo.com/blog/91.html "all rummy")
[rummy ola apk]( https://rummybo.com/blog/92.html "rummy ola apk")
[rummy nabob apk]( https://rummybo.com/blog/93.html "rummy nabob apk")
[rummy circle login]( https://rummybo.com/blog/94.html "rummy circle login")
[rummy 51 apk]( https://rummybo.com/blog/95.html "rummy 51 apk")
[deccan rummy]( https://rummybo.com/blog/96.html "deccan rummy")
[rummy go]( https://rummybo.com/blog/97.html "rummy go")
[color rummy]( https://rummybo.com/blog/98.html "color rummy")
[new rummy app]( https://rummybo.com/blog/ "new rummy app")
[rummy all list]( https://rummybocom.blogspot.com/2024/05/indias-most-trusted-rummy-app.html "rummy all list")
[yono rummy apk]( https://rummybocom.blogspot.com/2024/05/rummybocom-indian-rummy-gives-away-51.html "yono rummy apk")
[rummy glee max]( https://rummybocom.blogspot.com/2024/05/blog-post.html "rummy glee max")
[rummy ares apk]( https://rummybocom.blogspot.com/2024/05/thomas-and-uber-cup-final-china-womens.html "rummy ares apk")
[rummy moment]( https://rummybocom.blogspot.com/2024/05/india-witnesses-wedding-like-no-other.html "rummy moment")
[modern rummy]( https://rummybocom.blogspot.com/2024/05/snowboard-size-explained-what-size.html "modern rummy")
[rummy app download]( https://rummybo.com/how-to-play-rummy-online/index.html "rummy app download")
[rummy download]( https://rummybo.com/rummy-offers/index.html "rummy download")
[indian rummy]( https://rummybo.com/refer-and-earn-rummy/index.html "indian rummy")
[g rummy]( https://rummybo.com/rummy-leaderboards/index.html "g rummy")
[rummy east apk]( https://rummybo.com/blog/ "rummy east apk")
[rummy blast]( https://rummybo.com/about-us/index.html "rummy blast")
[holi rummy]( https://rummybo.com/contact-us/index.html "holi rummy")
[rummy game download]( https://rummybo.com/download-rummy-game-app/index.html "rummy game download")
[111 rummy 51 bonus]( https://rummybo.com/download-rummy-game-app/indian-rummy-apk/index.html "111 rummy 51 bonus")
[bappa rummy]( https://rummybo.com/download-rummy-game-app/points-rummy-apk/index.html "bappa rummy")
[rummy gold 51]( https://rummybo.com/download-rummy-game-app/points-rummy-apk/index1.html "rummy gold 51")
[rummy bindaas]( https://rummybo.com/download-rummy-game-app/pool-rummy-apk/index.html "rummy bindaas")
[rummy grand]( https://rummybo.com/fastest-rummy-withdrawals/index.html "rummy grand")
[rummy mate apk]( https://rummybo.com/free-rummy-online/index.html "rummy mate apk")
[classic rummy]( https://rummybo.com/how-to-play-rummy/rules-of-rummy/index.html "classic rummy")
[rummy league]( https://rummybo.com/how-to-play-rummy/rummy-points-scoring-system/index.html "rummy league")
[colour rummy]( https://rummybo.com/how-to-play-rummy-online/index.html "colour rummy")
[rummy cafe]( https://rummybo.com/how-to-play-rummy-online/joker-card-rummy/index.html "rummy cafe")
[rummy holi]( https://rummybo.com/how-to-play-rummy-online/rummy-sequence/index.html "rummy holi")
[how to play rummy]( https://rummybo.com/how-to-play-rummy-online/rummy-sets/index.html "how to play rummy")
[rummy gold - indian]( https://rummybo.com/how-to-play-rummy-online/rummy-tips-tricks/index.html "rummy gold - indian")
[rummy golds apk]( https://rummybo.com/join-telegram/index.html "rummy golds apk")
[rummy bonus 51 rupees free]( https://rummybo.com/online-rummy-faqs/index.html "rummy bonus 51 rupees free")
[rainbow rummy]( https://rummybo.com/online-rummy-tournament/index.html "rainbow rummy")
[rummy morden]( https://rummybo.com/privacy-policy/index.html "rummy morden")
[ultimate rummy]( https://rummybo.com/refer-and-earn-rummy/index.html "ultimate rummy")
[rummy games]( https://rummybo.com/responsible-gaming/index.html "rummy games")
[all rummy game]( https://rummybo.com/rng-certificate-for-rummy/index.html "all rummy game")
[rummy bonus]( https://rummybo.com/rummy-100-deposit-bonus/index.html "rummy bonus")
[play rummy]( https://rummybo.com/rummy-50-deposit-bonus/index.html "play rummy")
[best rummy app]( https://rummybo.com/rummy-cash-games-online/index.html "best rummy app")
[rummy yes apk]( https://rummybo.com/rummy-glossary/index.html "rummy yes apk")
[wow rummy]( https://rummybo.com/rummy-leaderboards/index.html "wow rummy")
[rummy palace]( https://rummybo.com/rummy-legality/index.html "rummy palace")
[rummy glee apk]( https://rummybo.com/rummy-offers/index.html "rummy glee apk")
[rummy glee 51 bonus]( https://rummybo.com/rummy-signup-bonus-250rs/index.html "rummy glee 51 bonus")
[rummy apps]( https://rummybo.com/rummy-welcome-bonus/index.html "rummy apps")
[rummy glee 51]( https://rummybo.com/tds-policy/index.html "rummy glee 51")
[rummy culture download]( https://rummybo.com/terms-and-conditions/index.html "rummy culture download")
[rummy nobob]( https://rummybo.com/terms-of-service/index.html "rummy nobob")
[rummy teen patti]( https://rummybo.com/types-of-rummy-games/21-card-rummy/index.html "rummy teen patti")
[rummy 100 rupees free]( https://rummybo.com/types-of-rummy-games/deals-rummy-game/index.html "rummy 100 rupees free")
[holly rummy]( https://rummybo.com/types-of-rummy-games/gin-rummy-online/index.html "holly rummy")
[rummy all app list]( https://rummybo.com/types-of-rummy-games/how-to-play-chinchon/index.html "rummy all app list")
[teen patti rummy]( https://rummybo.com/types-of-rummy-games/how-to-play-contract-rummy/index.html "teen patti rummy")
[rummy circle customer care number]( https://rummybo.com/types-of-rummy-games/index.html "rummy circle customer care number")
[rummy app list]( https://rummybo.com/types-of-rummy-games/indian-rummy-online/index.html "rummy app list")
[royally rummy apk]( https://rummybo.com/types-of-rummy-games/play-rummy-500/index.html "royally rummy apk")
[mpl rummy]( https://rummybo.com/types-of-rummy-games/points-rummy-game/index.html "mpl rummy")
[all rummy app list 41 bonus]( https://rummybo.com/types-of-rummy-games/pool-rummy-game/index.html "all rummy app list 41 bonus")
[rummy meet apk]( https://gravatar.com/wxingxing821 "rummy meet apk")
[rummy noble apk]( https://heylink.me/all_rummy "rummy noble apk")
[rummy nobel]( https://link.space/@rummy "rummy nobel")
[rummy time download]( https://rummybocom.blogspot.com/2024/05/rummybocom-indian-rummy-gives-away-51.html "rummy time download")
[rummy loot apk]( https://bit.ly/rummybo "rummy loot apk")
[rummy joy apk]( https://bit.ly/Rummy-blog "rummy joy apk")
[royal rummy apk]( https://bit.ly/How-to-Play-Rummy "royal rummy apk")
[rummy pro]( https://bit.ly/rummy-offers "rummy pro")
[rummy gold -]( https://bit.ly/refer-and-earn-rummy "rummy gold -")
[rummy gold download]( https://bit.ly/3UThhO6 "rummy gold download")
[playship rummy]( https://bit.ly/3JVDa9l "playship rummy")
[rummy welth]( https://bit.ly/4acibK5 "rummy welth")
[rummy buddy]( https://bit.ly/4dDgUP6 "rummy buddy")
[rummy gold apk download]( https://bit.ly/3UZDJFu "rummy gold apk download")
[rummy wealth yes]( https://bit.ly/3QHOadU "rummy wealth yes")
[new gold rummy]( https://docs.google.com/forms/d/e/1FAIpQLScjBM63R-xGwOJK12AEC659uoU5_SE6iwWIvG_LK1F8n0jbiw/viewform "new gold rummy")
[rummy nabob 777]( https://drive.google.com/file/d/1bquiY2f5Zqh6Es85K9ZDeMink0i4UTHu/view?usp=sharing "rummy nabob 777")
[rummy culture app]( https://podcasters.spotify.com/pod/show/rummy-bo/episodes/rummy-ola-rummy-ares-royally-rummy-rummy-culture-rummy-noble-rummy-joy-rummy-mate-rummy-perfect-e2kb1rn "rummy culture app")
[rummy sun 51 bonus]( https://podcasters.spotify.com/pod/show/rummy-bo/episodes/rummy-circle-rummy-rummy-wealth-rummy-nabob-rummy-glee-rummy-gold-rummy-modern-e2ka0el "rummy sun 51 bonus")
[rummy wealth 51 bonus]( https://rummybocom.blogspot.com/2024/05/rummybocom-indian-rummy-gives-away-51.html "rummy wealth 51 bonus")
[rummy all apk]( https://rummybocom.blogspot.com/2024/05/blog-post.html "rummy all apk")
[a23 rummy download]( https://rummybocom.blogspot.com/2024/05/thomas-and-uber-cup-final-china-womens.html "a23 rummy download")
[rummy cash game]( https://rummybocom.blogspot.com/2024/05/india-witnesses-wedding-like-no-other.html "rummy cash game")
[rummy king]( https://rummybocom.blogspot.com/2024/05/indias-most-trusted-rummy-app.html "rummy king")
[rummy joy 51 bonus]( https://rummybocom.blogspot.com/2024/05/snowboard-size-explained-what-size.html "rummy joy 51 bonus")
[rummy circle game]( https://docs.google.com/document/d/1T3qc7pyL0uCC8GvsEBrF7V_30gUGEzpn9ugBF8hmAQI/edit "rummy circle game")
[rummy rummy]( https://docs.google.com/document/d/1IQtsZjC__VHllSGFdxrz8DVllYnnXNIlhpyXbuwbI1E/edit#heading=h.11kv79mjv49b "rummy rummy")
[rummy culture apk]( https://vimeo.com/956456188?share=copy "rummy culture apk")
[rummy gold 100]( https://www.tumblr.com/wwwrummybocom/ "rummy gold 100")
[gold rummy]( https://ameblo.jp/rummybocom/entry-12855791616.html "gold rummy")
[rummy teen patti joy]( https://ameblo.jp/rummybocom/entry-12855828887.html "rummy teen patti joy")
[culture rummy](https://heylink.me/all_rummy "culture rummy")
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5025">issues.joomla.org/tracker/joomla-cms/5025</a>.</sub>

**Pull request closed without merging**
