### PR TITLE
[com_modules] positions view: client_id selector naming

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Summary of Changes

The `client_id` seletor is named `client_id`, not `filter.client_id.`. This was uniformized in 3.6.0 across all modules, cache, templates and languages views (the ones that have the client_id selector).

One view remain: the positions view in com_modules. I think this view is unused in the core but still should be changed. So, this PR changes it.
#### Testing Instructions
- Apply patch
- Test `/administrator/index.php?option=com_modules&view=positions&layout=modal&tmpl=component&client_id=0`

(should show the site template positions)
- Test `/administrator/index.php?option=com_modules&view=positions&layout=modal&tmpl=component&client_id=1`

(should show the admin template positions)
- Test `/administrator/index.php?option=com_modules&view=positions&layout=modal&tmpl=component`

(should show the admin template positions, since it was the last one used)

### CODE REVIEW

**Comment by JoomliC** [comment]
This modal is used in Hathor ;-)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10695">issues.joomla.org/joomla-cms/10695</a>.</sub>

**Comment by andrepereiradasilva** [comment]
lol always hathor ...

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 62fb58feef3297172593c92b13c8f27903701a86<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10695">issues.joomla.org/joomla-cms/10695</a>.</sub>

**Comment by chmst** [comment]
I've tested this successfully<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10695">issues.joomla.org/joomla-cms/10695</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 62fb58feef3297172593c92b13c8f27903701a86<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10695">issues.joomla.org/joomla-cms/10695</a>.</sub>

**Comment by brianteeman** [comment]
Rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10695">issues.joomla.org/joomla-cms/10695</a>.</sub>

**Pull request merged**
