### PR TITLE
[4.0] deprecate layout

### PR DESCRIPTION
**Pull request by brianteeman**
Deprecates an unused layout as requested https://github.com/joomla/joomla-cms/pull/34601#issuecomment-871175212

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 977980a9ceb78bf29824ade82c406bfc54c8229d<br /><br />Review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34656">issues.joomla.org/tracker/joomla-cms/34656</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 977980a9ceb78bf29824ade82c406bfc54c8229d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34656">issues.joomla.org/tracker/joomla-cms/34656</a>.</sub>

**Comment by chmst** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34656">issues.joomla.org/tracker/joomla-cms/34656</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Comment by brianteeman** [comment]
thx

**Pull request merged**
