### PR TITLE
[4.0] Mail Templates descriptions

### PR DESCRIPTION
**Pull request by brianteeman**
Updates the text used to describe the mail templates to simplify the text (less is more) and comply with the guidelines

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 8f27a0b5087875398dd53624d0d7911f69c4ddf6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29417">issues.joomla.org/tracker/joomla-cms/29417</a>.</sub>

**Comment by carcam** [comment]
I have tested this item :white_check_mark: successfully on 8f27a0b5087875398dd53624d0d7911f69c4ddf6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29417">issues.joomla.org/tracker/joomla-cms/29417</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29417">issues.joomla.org/tracker/joomla-cms/29417</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
