### PR TITLE
#26664 - Onhover text is not completed for workflows menu

### PR DESCRIPTION
**Pull request by Mayaank12**
Pull Request for Issue # .
[#26664] - Onhover text is not completed for workflows menu

### Expected result
Onhover text should be displayed completely

### Actual result
Onhover text should be displayed partially

### CODE REVIEW

**Comment by manojLondhe** [comment]
I have tested this item :white_check_mark: successfully on 6554681e0d2507b7797efc3c9bc5079c661b8c34<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26673">issues.joomla.org/tracker/joomla-cms/26673</a>.</sub>

**Comment by uthorat** [comment]
I have tested this item :white_check_mark: successfully on 6554681e0d2507b7797efc3c9bc5079c661b8c34<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26673">issues.joomla.org/tracker/joomla-cms/26673</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26673">issues.joomla.org/tracker/joomla-cms/26673</a>.</sub>

**Comment by HLeithner** [comment]
thx

**Pull request merged**
