### PR TITLE
[Isis] Use getInt over get as we just accept integers here

### PR DESCRIPTION
**Pull request by zero-24**
### Summary of Changes

Use getInt over get as we just accept integers here

### Testing Instructions

- review
- check that using isis still work

### Expected result

Isis still work

### Actual result

we not cast to int

### Documentation Changes Required

None

### CODE REVIEW

**Comment by Quy** [comment]
Would this be closed in light of this PR #15448?

**Comment by Bakual** [comment]
It's a valid PR.
The current `$input->get('Itemid', '');` is wrong as there is only the default filtering.
We should either use `$input->getInt('Itemid', 0);` or `$input->get('Itemid', 0, 'int');` since we only accept integers here.

**Comment by zero-24** [comment]
I'm going to update this PR in a minute.

**Comment by zero-24** [comment]
done with https://github.com/joomla/joomla-cms/pull/15376/commits/355e2100c696ecd8a550daeefa9eca149f8507fe thanks for the reminder.

**Comment by Quy** [comment]
Before: 
`<body class="admin com_content view- layout- task- itemid-" data-basepath="/joomla-cms-staging">`

After:
`<body class="admin com_content view- layout- task- itemid-0" data-basepath="/joomla-cms-staging">`

The difference is `itemid-` vs `itemid-0`. I am wondering if `Itemid` should be `id`.

**Comment by mbabker** [comment]
`Itemid` and `id` in the context of Joomla are two different things.

**Comment by Quy** [comment]
Here is a URL:
```
http://localhost/joomla-cms-staging/administrator/index.php?option=com_content&view=article&layout=edit&id=1
```
Here is the code to get values in the URL. As you can see it is `id` so `Itemid` will always be 0.
```
// Detecting Active Variables
$option   = $input->get('option', '');
$view     = $input->get('view', '');
$layout   = $input->get('layout', '');
$task     = $input->get('task', '');
$itemid   = $input->get('Itemid', '');
```

**Comment by mbabker** [comment]
`Itemid` doesn't actually apply in the backend context at all (unless we're suddenly routing to menu items in the backend) so I'm honestly not sure why it's used in the template.  But for the frontend they are different things.

**Comment by Quy** [comment]
So deprecate it, change to `id` or leave it as is?

**Comment by mbabker** [comment]
This PR as is is fine.  I'd suggest the 4.0 admin template doesn't need an `Itemid` based HTML class though unless we're opening the can of worms needed to support SEF routing for the admin app.

**Comment by Quy** [comment]
In error.php, `$itemid` is declared but not utilized.

**Comment by zero-24** [comment]
Any update here so we can move this forward to be included in the 3.7.3?

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 0baff403efb00b8ffa492df49bd41a2f6ae27879<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15376">issues.joomla.org/tracker/joomla-cms/15376</a>.</sub>

**Comment by roland-d** [comment]
I have tested this item :white_check_mark: successfully on 2360b16fa3db37f97230bff1a711f66acbe953ea<br /><br />Code review and tested, Itemid is now returned as 0 after applying patch.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15376">issues.joomla.org/tracker/joomla-cms/15376</a>.</sub>

**Comment by Quy** [comment]
@franz-wohlkoenig RTC

**Comment by ghost** [comment]
RTC as stated above.

**Pull request merged**
