### PR TITLE
[4.2] Discover Install

### PR DESCRIPTION
**Pull request by brianteeman**
### Summary of Changes
Consistent use of style for install success

### Testing Instructions
Install an extension via the discover functionality

### Actual result BEFORE applying this Pull Request
image
image
image

### Expected result AFTER applying this Pull Request
image
image
image

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by sandewt** [comment]
I have tested this item :white_check_mark: successfully on 089b7f58b9fbe1080db8ee2fb366b873d54018c9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39795">issues.joomla.org/tracker/joomla-cms/39795</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 089b7f58b9fbe1080db8ee2fb366b873d54018c9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39795">issues.joomla.org/tracker/joomla-cms/39795</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39795">issues.joomla.org/tracker/joomla-cms/39795</a>.</sub>

**Comment by fancyFranci** [comment]
Thanks!

**Pull request merged**
