### PR TITLE
[4.0] Namespace com_messages

### PR DESCRIPTION
**Pull request by joomdonation**
Pull Request for Issue # .

### Summary of Changes
This simply PR converts com_messages to namespace MVC for Joomla 4

### Testing Instructions
Unfortunately, this is currently not testable because the popup window to select a user to send private message is broken in Joomla 4. I had to change the value using inspector to test the extension while working o this conversion

For now, guess @wilsonge will have to review the code to merge.

### CODE REVIEW

**Comment by dgt41** [comment]
@joomdonation the base code for fixing the modals is already RTC: https://github.com/joomla/joomla-cms/pull/15374
Then we need to specify the width/height for each modal to have a workable modal

**Comment by joomdonation** [comment]
George needs to merge it then. There is also a SQL error when a user group is selected in the popup, but of course, it is not related to your PR.

**Comment by wilsonge** [comment]
Fixed the SQL Error :) Still needs @dgt41 's fix for the javascript issue

**Comment by joomdonation** [comment]
He said it is RTC.  So maybe you can check and merge that one. People have been opening issues related to it.

**Pull request merged**
