### PR TITLE
a11y regression fix outline on toolbar fix

### PR DESCRIPTION
**Pull request by ciar4n**
Pull Request for Issue #12894  .

### Summary of Changes
Brings back #11723 to the Isis template which was lost along the way...

### Testing Instructions
Apply patch and tab through navbar menu items

a11y

### Documentation Changes Required
None

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on c8aa8f6d3e3d135612229399ffe4d75fcc3069f1<br /><br />works as described<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12935">issues.joomla.org/tracker/joomla-cms/12935</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on c8aa8f6d3e3d135612229399ffe4d75fcc3069f1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12935">issues.joomla.org/tracker/joomla-cms/12935</a>.</sub>

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on c8aa8f6d3e3d135612229399ffe4d75fcc3069f1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12935">issues.joomla.org/tracker/joomla-cms/12935</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12935">issues.joomla.org/tracker/joomla-cms/12935</a>.</sub>

**Comment by zero-24** [comment]
Thanks merged

**Pull request merged**
