### PR TITLE
[4.0] Fix for Article Batch Modal Display

### PR DESCRIPTION
**Pull request by jonasgonka**
### Summary of Changes
Added one line of code in the `batch-language.js` to hide the copy/move radio buttons by default, until you select a category.

### Testing Instructions
Compile the javascript code.
Create some Articles and Categories.
Go to Content -> Articles.
Select one or more Articles.
Click on Batch.

### Expected result
In the modal the radiobuttons for move and copy should be hidden until you select a category.

### Actual result
Buttons are visible.

### Documentation Changes Required
None.

### CODE REVIEW

**Comment by wilsonge** [comment]
Sorry we had a small restructure of the javascript files yesterday which has lead to conflicts with this PR. Can you please fix them :)

**Comment by jonasgonka** [comment]
Merged the changes, cant keep up with all the new restructures (:

**Comment by roland-d** [comment]
@jonasgonka You are not alone ;)

**Comment by laoneo** [comment]
Once we are over it, then all will be back to normal. Thanks for the patience.

**Comment by nurcihandem** [comment]
I have tested this item :white_check_mark: successfully on 8640dfff020f1e84511affc1430ba945c3392063<br /><br />everything perfect<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21340">issues.joomla.org/tracker/joomla-cms/21340</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
