### PR TITLE
Adding option to show/hide phrases areas

### PR DESCRIPTION
**Pull request by Devportobello**
Adding option to show / hide phrases areas without the need of overriding.
## how to test
- Create menu item "Search Form or Search Results" and look "options"
- Go to frontend to inspect
- Apply patch, go to menu item created earlier, use the new "options"
  "Use Phrases areas"
- Go to frontend to inspect
### Questioning
- Maybe this en-gb translation is bad.
- Did we need to separe the "phrases-box" and "ordering-box" with each
  option ?

### CODE REVIEW

**Comment by jduerscheid** [comment]
This patch works.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7062">issues.joomla.org/joomla-cms/7062</a>.</sub>

**Comment by brianteeman** [comment]
Phrases is definitely not the correct en-GB for this.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7062">issues.joomla.org/joomla-cms/7062</a>.</sub>

**Comment by brianteeman** [comment]
Phrases is just one of the three options that are enabled or disabled with this option.

To me these three radios are search options so I would suggest replaceing the word phrases with search options
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7062">issues.joomla.org/joomla-cms/7062</a>.</sub>

**Comment by Preview** [comment]
@test The patch works. I tested it by following the instructions above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7062">issues.joomla.org/joomla-cms/7062</a>.</sub>

**Comment by zero-24** [comment]
@brianteeman so you suggest the following strings?

```
+COM_SEARCH_FIELD_SEARCH_PHRASES_DESC="Show the search options"
+COM_SEARCH_FIELD_SEARCH_PHRASES_LABEL="Use search options"
```

If yes @Devportobello can you implement it? So we can move this to RTC and merge into the core?

**Comment by brianteeman** [comment]
@zero-24 @Devportobello yes that would appear to make more sense<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7062">issues.joomla.org/joomla-cms/7062</a>.</sub>

**Comment by zero-24** [comment]
Thanks @brianteeman so @Devportobello can implement the change? If done please give us a quick comment so we can move this to RTC :smile: Thanks!

**Comment by shre001** [comment]
@ this works fine

**Comment by Devportobello** [comment]
Translation modified.

**Comment by brianteeman** [comment]
Sorry please make the strngs
+COM_SEARCH_FIELD_SEARCH_PHRASES_DESC="Show the search options."
+COM_SEARCH_FIELD_SEARCH_PHRASES_LABEL="Use Search Options"

eg a Desc should have a fulltop at the end and a Label should be Capitalised

**Comment by Devportobello** [comment]
My bad, not noticed.
Done.

**Comment by zero-24** [comment]
Thanks @Devportobello, @brianteeman, @Preview, @jduerscheid, @m-b-o and @shre001 :smile: RTC'ing now :+1: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7062">issues.joomla.org/joomla-cms/7062</a>.</sub>

**Comment by smz** [comment]
Wouldn't it be better to change the language keywords (constants) name too?

**Comment by Kubik-Rubik** [comment]
Thank you @Devportobello! Merged.

**Pull request closed without merging**
