### PR TITLE
[4.3] Fix module Ajax broken behaviour

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # .

### Summary of Changes

There's an inconsistency in the com_ajax logic that prevents modules resolving correctly the Helper file (read the testing instructions below). The proposed fix is to use a `strtolower` for the db name of the module and let the other parts intact...

### Testing Instructions

To experience the bug you need to edit the file `administrator/modules/mod_guidedtours/src/Helper/GuidedToursHelper.php` and add on function named `toursAjax` ie: 

```php
    public function toursAjax()
    {
        return ["success" => true, "message" => "in a bottle"];
    }
```
Then in the cpanel open the browser console and run

```js

await fetch(new URL(`${Joomla.getOptions('system.paths').baseFull}index.php?option=com_ajax&module=guidedtours&method=tours&format=json`), { headers: { 'X-CSRF-Token': Joomla.getOptions('csrf.token') } }).then(x => x.json())

```

Note: the part `module=guidedtours` (prefixed with `mod_`) reflects the column `element` in the `#__extensions` table.

Screenshot 2023-05-14 at 12 05 57

The result is that the com_ajax will Look for a `GuidedtoursHelper` class, which will fail on any case sensitive filesystem:
Screenshot 2023-05-14 at 11 37 58

Apply the PR and run in the console the following (observe that the module now is defined as `GuidedTours`)

```js
await fetch(new URL(`${Joomla.getOptions('system.paths').baseFull}index.php?option=com_ajax&module=GuidedTours&method=tours&format=json`), { headers: { 'X-CSRF-Token': Joomla.getOptions('csrf.token') } }).then(x => x.json())
```

The class is correctly identified as `GuidedToursHelper`
Screenshot 2023-05-14 at 12 16 12

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

@laoneo

### CODE REVIEW

**Comment by richard67** [comment]
@dgrammatiko I have tested, but in opposite to your testing instructions I have tested both cases `&module=guidedtours` and `&module=GuidedTours` without and with the PR.

I've not seen any difference.

The `&module=guidedtours` returns the object with success=false and the message that the helper was not found, and the `&module=GuidedTours` returns your message in a bottle with success=true, regardless if I have the change from this PR applied or not.

Could you check if you can reproduce my finding?

**Comment by dgrammatiko** [comment]
> Could you check if you can reproduce my finding?

Are you on a case sensitive filesystem?

**Comment by richard67** [comment]
> > Could you check if you can reproduce my finding?
> 
> Are you on a case sensitive filesystem?

Server is Ubuntu, so yes.

**Comment by richard67** [comment]
@dgrammatiko Maybe I made some mistake when testing? I did everything as described, but who knows.

**Pull request closed without merging**
