### PR TITLE
[4.0] Update plg_sampledata_blog.ini

### PR DESCRIPTION
**Pull request by brianteeman**
Fixes an obvious copy/paste error

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 47f955de914319c54a0135bf768359bd7912e774<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32685">issues.joomla.org/tracker/joomla-cms/32685</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 47f955de914319c54a0135bf768359bd7912e774<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32685">issues.joomla.org/tracker/joomla-cms/32685</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32685">issues.joomla.org/tracker/joomla-cms/32685</a>.</sub>

**Comment by Quy** [comment]
Thanks

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
