### PR TITLE
Fix the read more std-button

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue #15862 .

### Summary of Changes
Readmore is targeted to parent window and it should be in the same (there is no modal). My bad :(

### Testing Instructions
```
Create new Menu Item
Choose "Single Article" type
Click "Create" button for article
Click "Read More" button

Also check that in normally created articles the button works correctly 
```

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on f39cc3ca9669c1a0976f62b5acf8fbab0dd755c8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15869">issues.joomla.org/tracker/joomla-cms/15869</a>.</sub>

**Comment by Webdongle** [comment]
I have tested this item :white_check_mark: successfully on f39cc3ca9669c1a0976f62b5acf8fbab0dd755c8<br /><br />Tested on latest Jstaging with Tinymce **Full Success**

JCE readmore still fails but that's not Joomla core<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15869">issues.joomla.org/tracker/joomla-cms/15869</a>.</sub>

**Comment by dgt41** [comment]
@Webdongle thanks, it seems I forget one parent there, updating

**Comment by dgt41** [comment]
@Webdongle can you test this once more with JCE?

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 12cfe7332a3d424e9b716f5c1fb036f5f54a880f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15869">issues.joomla.org/tracker/joomla-cms/15869</a>.</sub>

**Comment by Webdongle** [comment]
I have tested this item :white_check_mark: successfully on 12cfe7332a3d424e9b716f5c1fb036f5f54a880f<br /><br />Tested with Tiymce and JCE ... Full Success<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15869">issues.joomla.org/tracker/joomla-cms/15869</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Pull request merged**
