### PR TITLE
[4.0] Remove unused variables in template files

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Removes some unused variables in template files.

### Testing Instructions

Code review.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 00ccad33380e5d77a8665f2d0fdda637e8e82639<br /><br />As a first result I had differences in: /atum/error_login.php (line numbers). But it seems it's changed with the 2nd code.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29849">issues.joomla.org/tracker/joomla-cms/29849</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 00ccad33380e5d77a8665f2d0fdda637e8e82639<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29849">issues.joomla.org/tracker/joomla-cms/29849</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29849">issues.joomla.org/tracker/joomla-cms/29849</a>.</sub>

**Comment by infograf768** [comment]
Tks.

**Pull request merged**
