### PR TITLE
[5.2] Composer update joomla/database from 3.2.0 to 3.2.1 for PostgreSQL 16 support

### PR DESCRIPTION
**Pull request by richard67**
Pull Request for Issue #42335 .

### Summary of Changes

This pull request (PR) updates the database framework package from 3.2.0 to 3.2.1.

See https://github.com/joomla-framework/database/releases/tag/3.2.1 for the changes.

### Testing Instructions

Make a new installation of Joomla 5.2 using a PostgreSQL database server version 16.

Login to the administrator and go to the System Information.

### Actual result BEFORE applying this Pull Request

42704 42704, 7, ERROR: unrecognized configuration parameter "lc_collate"

### Expected result AFTER applying this Pull Request

System Information is shown.

### Link to documentations
Please select:
- [X] No documentation changes for docs.joomla.org needed

- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44316">issues.joomla.org/tracker/joomla-cms/44316</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on e3fe902ba145bdc831ed7f4ca01f6b4b039ac670<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44316">issues.joomla.org/tracker/joomla-cms/44316</a>.</sub>

**Comment by richard67** [comment]
@teoberi More helpful than thumbs up would be if you could test this pull request and then mark your test result in the issue tracker here https://issues.joomla.org/tracker/joomla-cms/44316 by using the blue "Test this" button at the top left corner.

A pull request needs 2 successful human tests for being accepted, and this one here still needs a test.

**Comment by teoberi** [comment]
I have tested this item :white_check_mark: successfully on e3fe902ba145bdc831ed7f4ca01f6b4b039ac670<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44316">issues.joomla.org/tracker/joomla-cms/44316</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44316">issues.joomla.org/tracker/joomla-cms/44316</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
