### PR TITLE
Support for input elements in the searchoolbar

### PR DESCRIPTION
**Pull request by laoneo**
The search toolbar should support ordinary input elements for filtering (mainly for clearing them). It basically works already, but the clear button doesn't clear the input elements, only the select boxes. This means adding an input field can't be cleared anymore after once filled with a value.
### Testing instructions

Testing it properly, can only be done with a component which does add input filters and not only select boxes. The following testing steps will add an input field to the articles manager of com_content. Please keep in mind that the article filter has no impact on the search result itself.
- Add the following XML tag to the file administrator/components/com_content/models/forms/filter_articles.xml
  `<field name="modal_id" type="modal_article"
              label="COM_CONTENT_FIELD_SELECT_ARTICLE_LABEL"
              required="true"
              edit="true"
              clear="false"
              description="COM_CONTENT_FIELD_SELECT_ARTICLE_DESC"
              onchange="this.form.submit();"
          />
  `
- Go to content articles on the back end.
- Click on "Search Tools" and select an article on the new input field.
- With the patch the input field gets cleared, without it stays with the selected article.

### CODE REVIEW

**Comment by manojLondhe** [comment]
I have tested this item :white_check_mark: successfully on 9caa49caa64a7de4a05461d5b0e09815dcb17973<br /><br />@test 
Applied patch, Cleared browser cache, Tested successfully.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8175">issues.joomla.org/joomla-cms/8175</a>.</sub>

**Comment by gunjanpatel** [comment]
I have tested this item :white_check_mark: successfully on 9caa49caa64a7de4a05461d5b0e09815dcb17973<br /><br />It works after applying patch. 
Thanks @laoneo for fix.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8175">issues.joomla.org/joomla-cms/8175</a>.</sub>

**Comment by ttplsachin** [comment]
I have tested this item :white_check_mark: successfully on 9caa49caa64a7de4a05461d5b0e09815dcb17973<br /><br />Working fine.

@test - Tested successfully.
I applied patch and it's working fine. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8175">issues.joomla.org/joomla-cms/8175</a>.</sub>

**Comment by laoneo** [comment]
Are you guys on a bug squash session at JWC15?

**Comment by manojLondhe** [comment]
@laoneo Yup!

**Pull request merged**
