### PR TITLE
[4.0] Move debug language setting

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
Move `Debug Language` above `Language Display`.

### Testing Instructions
Go to Global Configuration > System
Click `Debug Language`

### CODE REVIEW

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on dd095f26e252dc47772e6e46c695fd99105bd3bf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27652">issues.joomla.org/tracker/joomla-cms/27652</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on dd095f26e252dc47772e6e46c695fd99105bd3bf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27652">issues.joomla.org/tracker/joomla-cms/27652</a>.</sub>

**Comment by infograf768** [comment]
rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27652">issues.joomla.org/tracker/joomla-cms/27652</a>.</sub>

**Comment by infograf768** [comment]
tks

**Pull request merged**
