### PR TITLE
[4] language italian issue with php 8.1 %S should be %s

### PR DESCRIPTION
**Pull request by alikon**
despite i've made the same on Crowdin

image

### CODE REVIEW

**Comment by brianteeman** [comment]
Core doesn't have %S anywhere in a string and the only installation language file that does is Italian.

With one exception which is the date format and I assume still works
`DATE_FORMAT_CALENDAR_DATETIME="%Y-%m-%d %H:%M:%S"`

**Comment by brianteeman** [comment]
Just checked and it is nothing to do with php 8.1

Capital S has always been wrong and has never worked.

The only difference since 8.0 is that since 8.0 it no longer returns false on failure.

In php <8.0 using %S would not error but it would not do anything

**Comment by alikon** [comment]
before to switch on php 8.1 i was able to install joomla 4 .0 and 4.1 after i cannot

**Comment by brianteeman** [comment]
Thats because it no longer returns false on error. It has always been wrong just that previously it was a silent error

**Comment by infograf768** [comment]
In any case, that string has to be corrected ASAP for tomorrow's release. Patch by @alikon is correct. Reply by whoever is `Joomla CMS` is totally wrong.

**Comment by zero-24** [comment]
BTw if anything this should be patched via crowdin -> synced to core-translations -> updated the CMS and not directly via a PR against this repo. Else this issue will come back on the next release.

**Comment by HLeithner** [comment]
This change have to be made in crowdin in and merged thru the translation-bot, if not if will be overwritten with the next sync (and breaks the bot).

**Comment by dgrammatiko** [comment]
@HLeithner please consider merging https://github.com/joomla/joomla-cms/pull/36222 before the bot will run again. One of the error pages has no translations...

**Comment by alikon** [comment]
dears, i've already made the change 1st in crowdin but has been rejected, as I posted in the pr

**Comment by zero-24** [comment]
I have contacted wilco to check what went wrong on the crowdin side so this can be sorted.

**Comment by zero-24** [comment]
Just for the record this PR should not be directly merged as it is (yes I know the change is correct) but it has to go via crowdin, core-translations and the bot. ;)

**Comment by wilsonge** [comment]
Yeah we've pushed it back by a week - because of the stuff I had to merge on Sunday already put the release team on short notice plus then I have this plus Dimitris' one he linked plus this - it's just safer to push it back by a week and get everything properly tested and time to settle

**Comment by wilsonge** [comment]
Fixed in https://github.com/joomla/joomla-cms/pull/36226

**Pull request closed without merging**
