### PR TITLE
[4.0] Fancy selectbox fix

### PR DESCRIPTION
**Pull request by pdkpavankumar**
Pull Request for Issue # https://github.com/joomla/joomla-cms/issues/29846 .

### Summary of Changes
css changes for x alignment in fancy select box

### Testing Instructions
Article edit page
Category select box

### Actual result BEFORE applying this Pull Request

image

### Expected result AFTER applying this Pull Request

image

### Documentation Changes Required
NO

### CODE REVIEW

**Comment by Quy** [comment]
Persian language

Before PR:
30739-before

After PR:
30739-after

**Comment by infograf768** [comment]
Not sure it should be done through `.choices__list--single {`

Imho, it should be done via 
```
.choices[data-type*="select-one"] {
  .choices__button_joomla {
```

Please look at the cassiopea scss that I just modified (margin values would be different and atum variables should be used)
https://github.com/joomla/joomla-cms/blob/4.0-dev/templates/cassiopeia/scss/vendor/choicesjs/choices.scss#L47-L92

It implies refactoring atum choices.scss. Just compare both files.

**Comment by pdkpavankumar** [comment]
Persian language
image

**Comment by pdkpavankumar** [comment]
@infograf768 thanks for the review comment, updated the PR accordingly.

**Comment by Quy** [comment]
Sadly, it is still an issue on Safari for MacOS.

**Comment by infograf768** [comment]
Backend is slightly different from frontend
Margin-right for LTR: please modify to 50px instead of 45px
Margin-left for RTL: same

Safari screenshots are fine (as other browsers):
Screen Shot 2020-09-25 at 08 35 37
Screen Shot 2020-09-25 at 08 34 18

To test this patch correctly, make sure all caches are cleared. Quit the browser and launch again after npm ci.

**Comment by infograf768** [comment]
@Quy Can you test again? For me it is now fine.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on fc768294d4b0e32f398720335f81175b06e53747<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30739">issues.joomla.org/tracker/joomla-cms/30739</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on fc768294d4b0e32f398720335f81175b06e53747<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30739">issues.joomla.org/tracker/joomla-cms/30739</a>.</sub>

**Comment by infograf768** [comment]
RTC. Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30739">issues.joomla.org/tracker/joomla-cms/30739</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
