### PR TITLE
[3.10] Solve tag alias duplicate error if with different parents

### PR DESCRIPTION
**Pull request by simbus82**
### Summary of Changes

Same PR as #38576 but for J3.

### CODE REVIEW

**Comment by brianteeman** [comment]
Thank you for creating this pull request.

As already stated Joomla 3 is now in security only mode with no further bug fixes or new features.

cc @zero-24

**Comment by simbus82** [comment]
It will be useful to 75% of Joomla users who still have J3.

**Comment by rdeutz** [comment]
We only fix security releated problem as we are in security only mode.

**Comment by simbus82** [comment]
> We only fix security releated problem as we are in security only mode.

I know. No problem, the important thing is that everything remains tracked.
The important thing is to listen and help the community.

**Pull request closed without merging**
