### PR TITLE
[4.0] Use the right branch for AppVeyor badge

### PR DESCRIPTION
**Pull request by Hackwar**
What the title says. This just fixes the badge.

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 0260e1a02c0357f1181367fcd0b42fac8aa0ca52<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25241">issues.joomla.org/tracker/joomla-cms/25241</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 0260e1a02c0357f1181367fcd0b42fac8aa0ca52<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25241">issues.joomla.org/tracker/joomla-cms/25241</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25241">issues.joomla.org/tracker/joomla-cms/25241</a>.</sub>

**Comment by HLeithner** [comment]
thx

**Pull request merged**
