### PR TITLE
[Feature] Module to display a single image

### PR DESCRIPTION
**Pull request by Devportobello**
# New feature

I wanted to share this simple module, goal is to display an image by using media manager (some time better than relying from custom html (editor who add paragraph, hard tools to add image ...))
## Test
- Patch
- Goto Extensions -> Module manager
- Create new module, select **Single Image**
- Edit (use media manager, params...) and save then go to front end

### CODE REVIEW

**Comment by Bakual** [comment]
Thanks for that contribution. 
My personal opinion is that we should not add a new module to achieve something which can already be easily done with the custom html module.

**Comment by Devportobello** [comment]
Yeah, you right, but for many user this is not really easy to use the basic editor to add image. :)

**Comment by infograf768** [comment]
You can propose your module to download on JED.

**Comment by Devportobello** [comment]
Thinking that was an improvment for Joomla :)

**Pull request closed without merging**
