### PR TITLE
[5.2.] Fix Dark mode in user-captive view - Fix for Issue #43448

### PR DESCRIPTION
**Pull request by coolcat-creations**
Pull Request for Issue #43448 

### Summary of Changes
Changed the css classes so that the text is visible

### Testing Instructions

Create two 2FA Methods
Log out
Login without using a method
click on "Select a different method"

### Actual result BEFORE applying this Pull Request

grafik

### Expected result AFTER applying this Pull Request

grafik

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
please edit this to give a meaningful title

**Comment by dautrich** [comment]
I have tested this item :white_check_mark: successfully on 1b7f0387f01cf37b0b407e7d10f3e2e3fb1cedb7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44209">issues.joomla.org/tracker/joomla-cms/44209</a>.</sub>

**Comment by fgsw** [comment]
@coolcat-creations Can you add ```[5.2] ``` at begin of title so user don't have to open pull request to know on which branch it is to test?

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 1b7f0387f01cf37b0b407e7d10f3e2e3fb1cedb7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44209">issues.joomla.org/tracker/joomla-cms/44209</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44209">issues.joomla.org/tracker/joomla-cms/44209</a>.</sub>

**Comment by Hackwar** [comment]
Thank you for your contribution!

**Pull request merged**
