### PR TITLE
Use stored PW for Test Email feature

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue #31482 .

### Summary of Changes
Use stored PW for Email testing

### Testing Instructions
please follow #31482

### Actual result BEFORE applying this Pull Request
"Send Test Mail" does not work

### Expected result AFTER applying this Pull Request
"Send Test Mail" work

### Documentation Changes Required
none

### CODE REVIEW

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on e39681b6fbd766ecb17ddea2f553762bafce27a8<br /><br />Tested successfully in 3.9.23<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31515">issues.joomla.org/tracker/joomla-cms/31515</a>.</sub>

**Comment by HLeithner** [comment]
If we use that solution we have to explain it to the user. Another problem which was oversight by the jsst is that we can not unset a password.

**Comment by Fedik** [comment]
technically it work as before, not much to explain ;)
but can add some message somewhere, of course

> we can not unset a password

yeah, I also noticed that. can only replace

**Comment by HLeithner** [comment]
Any idea how to solve the "remove password" problem?

**Comment by Fedik** [comment]
No idea, currently

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on e39681b6fbd766ecb17ddea2f553762bafce27a8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31515">issues.joomla.org/tracker/joomla-cms/31515</a>.</sub>

**Comment by bembelimen** [comment]
Probably we should remove the username + pw when authentication is set to "no"?

**Comment by bayareajenn** [comment]
I have tested this item :white_check_mark: successfully on e39681b6fbd766ecb17ddea2f553762bafce27a8<br /><br />Phil and I tested this successfully.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31515">issues.joomla.org/tracker/joomla-cms/31515</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31515">issues.joomla.org/tracker/joomla-cms/31515</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
