### PR TITLE
[4.4] Fix SQL field, get the filter value from the linked filter field

### PR DESCRIPTION
**Pull request by Fedik**
### Summary of Changes

Due to bug in SQL field the feature ["Linked Fields as Filters"](https://docs.joomla.org/SQL_form_field_type) is broken. 
The PR is fixing this feature, by using the value directly from the form. 
Use of the value from Request should be deprecated in future.

Thanks @robbiejackson for the idea and code. I just copy pasting it in to the PR :)

### Testing Instructions
Add folowing field in to Custom HTML module:
```xml
<field
  name="catid"
  type="sql"
  label="Category"
  sql_select="id, title"
  sql_from="#__categories"
  sql_where="level=1 AND extension='com_content'"
  sql_order="lft"
  key_field="id"
  value_field="title"
  default="2"
  onchange="window['toolbar-apply'].buttonElement.click()"
>
  <option>- Select -</option>
</field>
<field
  name="subcat"
  type="sql"
  label="Article"
  sql_select="id, title"
  sql_from="#__content"
  sql_order="title"
  sql_filter="catid"
  key_field="id"
  value_field="title"
>
  <option>- Select -</option>
</field>
```
Create and save new Custom HTML module, or open existing.
Change the value of "Category" field.
After selecting new value and saving the form, the linked Article field should display only articles from the selected category.

### Actual result BEFORE applying this Pull Request
The Article field shows ALL articles.

### Expected result AFTER applying this Pull Request
The Article field shows only the articles froms the selected category.

### Link to documentations
Please select:
- [x] Documentation link for docs.joomla.org: https://docs.joomla.org/SQL_form_field_type
- [ ] No documentation changes for docs.joomla.org needed
- [x] Pull Request link for manual.joomla.org: https://github.com/joomla/Manual/pull/278
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by robbiejackson** [comment]
I've updated the documentation for the SQL form field to describe the Linked Field feature at http://pr-278.manual.joomlacode.org/docs/next/general-concepts/forms-fields/standard-fields/sql#linked-fields-as-filters (it's not yet merged into the Joomla Manual).

The documentation uses the example of a category field, and a SQL field which displays the titles of articles whose category matches that of the category field.

The documentation includes (at the bottom of the page) a link to a component com_sqlfield which can be downloaded and adapted for testing this PR.

The current version of the SQL field uses the user state to pass the linked field id to the SQL field (eg the category id to the SQL field displaying the list of titles). This involves:
- setting the 'context' attribute on the linked field
- setting the user state against the `<context>.filter` in the Controller, to pass the linked field id to the SQL field
 
It's a lot easier for the user if the SQL field code gets the linked field id from the Form object, rather than requiring the user to explicitly pass it in a state variable.

The com_sqlfield component still works when this PR is applied, showing that if someone has used the user state method to implement this feature then it should be backward compatible.

To test this PR I removed the 'context' attribute from the sql field in the xml form, and the setting of the "sqlfield.filter" state in the SqlfieldController and the component worked ok.

**Comment by robbiejackson** [comment]
I have tested this item :white_check_mark: successfully on 1febcafb6f4897224a97a1d670e0f6b379d5f6fe<br /><br />Just confirming the above tests by following the proper procedure.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43789">issues.joomla.org/tracker/joomla-cms/43789</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 1febcafb6f4897224a97a1d670e0f6b379d5f6fe<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43789">issues.joomla.org/tracker/joomla-cms/43789</a>.</sub>

**Comment by MacJoom** [comment]
Thank you!

**Pull request merged**
