### PR TITLE
[4.0] blog.php Scrabble96 patch 4 - featured

### PR DESCRIPTION
**Pull request by N6REJ**
Pull Request for Issue # .
#26160 
REQUIRES #26231, #26242 
### Summary of Changes

Removed IE support per #26160 

### Testing Instructions
Create or view a category blog.
View Source
blog-item-content class should be gone.

### Expected result
image

### Actual result
image

### CODE REVIEW

**Comment by ghost** [comment]
@N6REJ can you please comment what the Pull Request is for?

**Comment by N6REJ** [comment]
sorry, I thought the issue # took care of all that.  it's for #26160

**Comment by N6REJ** [comment]
@SharkyKZ PLEASE tell me this is finally right?

**Comment by N6REJ** [comment]
@brianteeman thanks for telling me it was deleted, idk wth happened, other then I suck @ this.

**Comment by N6REJ** [comment]
new pr #26263  containing all 3 since scrabble closed hers

**Pull request closed without merging**
