### PR TITLE
[4.0] fontawesome fixed width

### PR DESCRIPTION
**Pull request by brianteeman**
FA recommends that the css is in the format style-icon-modifier

this simple pr updates joomla's usage of fa-fw to match

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 62db688caa860edf8d181c7f1d2d11d71e636606<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26094">issues.joomla.org/tracker/joomla-cms/26094</a>.</sub>

**Comment by C-Lodder** [comment]
I have tested this item :white_check_mark: successfully on 8b9ac92ba3122e050adb0c756264920ca2593939<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26094">issues.joomla.org/tracker/joomla-cms/26094</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26094">issues.joomla.org/tracker/joomla-cms/26094</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
