### PR TITLE
Undefined class inspection

### PR DESCRIPTION
**Pull request by Denitz**
### Summary of Changes

Undefined class IDE inspection

### Testing Instructions

Apply patch

### Actual result BEFORE applying this Pull Request

See IDE warning

### Expected result AFTER applying this Pull Request

Class CacheModel identified

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by heelc29** [comment]
I have tested this item :white_check_mark: successfully on 0c2a7540bad9eac2b7c33622ba83a7927f588b4a<br /><br />code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41555">issues.joomla.org/tracker/joomla-cms/41555</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 0c2a7540bad9eac2b7c33622ba83a7927f588b4a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41555">issues.joomla.org/tracker/joomla-cms/41555</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41555">issues.joomla.org/tracker/joomla-cms/41555</a>.</sub>

**Comment by obuisard** [comment]
Thanks for the PR @Denitz

**Pull request merged**
