### PR TITLE
[#28401] Display child categories of every selected Category in Module Articles Category

### PR DESCRIPTION
**Pull request by pjmatos**
Fix to display all child categories of every selected Category in Module Articles Category by correcting the use of cache in the Categories model class
http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=28401

### CODE REVIEW

**Comment by n9iels** [comment]
@test confirmd, the patch solves the bug

**Comment by n9iels** [comment]
@test confirmd, the patch solves the bug

**Comment by zero-24** [comment]
Moving to RTC based on the succesful tests.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/3906">issues.joomla.org/joomla-cms/3906</a>.</sub>

**Comment by phproberto** [comment]
Merged. Thanks!

**Pull request closed without merging**
