### PR TITLE
[4.0] Namespace admin template Atum

### PR DESCRIPTION
**Pull request by brianteeman**
Continuing the namespace work

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on c77b2bdfaddcc18db00464e19edfcccc21645ba4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21246">issues.joomla.org/tracker/joomla-cms/21246</a>.</sub>

**Comment by brianteeman** [comment]
(currently unable to connect to ci.joomla.org to see what the drone errors are)

**Comment by brianteeman** [comment]
drone error is unrelated to this PR

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
