### PR TITLE
Revert "[5.0] Adding display of progress to installation"

### PR DESCRIPTION
**Pull request by HLeithner**
Trying to revert this PR to find an issue for new installations.

 @wilsonge since you experience this issue regularly can you please have a look for this install package?

Reverts joomla/joomla-cms#29376

### CODE REVIEW

**Comment by wilsonge** [comment]
image

Doesn't fix my problem of weird things happening. Although the error is much better than an error of `null` over a progress bar

**Comment by wilsonge** [comment]
I will say though - before this patch, I have to refresh the page and refill information. After patch I can just hit the submit button again and everything works

**Comment by HLeithner** [comment]
so this is fixed @wilsonge right?

**Comment by wilsonge** [comment]
I believe so with the two PR's raised last week

**Pull request closed without merging**
