### PR TITLE
Ucm Fixes

### PR DESCRIPTION
**Pull request by wilsonge**
This is an update of #3194 without the annoying codestyle in the constructor.
## Testing

To test ensure that tags and content history both continue to work as expected (this class is the base class for saving the data for content)

### CODE REVIEW

**Comment by snarf007** [comment]
I have tested this item :white_check_mark: successfully on a0b6dca7faaad9f2ef599620053f2667ce7dd02a<br /><br />Added an article and created some tags on the article. Changed the article and removed some tags. Checked versions and changes are marked. Tags are not in the versions.
Applied patch and executed the same actions. Behaviour is the same as before. Thats the expected result.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6466">issues.joomla.org/joomla-cms/6466</a>.</sub>

**Comment by zero-24** [comment]
@wilsonge can you sync to staging to fix the conflicts?

**Comment by BezouwenR** [comment]
I have tested this item :white_check_mark: successfully on a0b6dca7faaad9f2ef599620053f2667ce7dd02a<br /><br />Normal (pull request is mergable and has testinstructions)
Hello @wilsonge 

Thank you for your contribution.

The last comment here was on [2014-12-12]. So the question is, Is this issue/pull request still valid? 
If no reply is received within 4 weeks we will close this issue.

I have had several testing set to try to find any mistake, no annoying codestyle in the constructor.

Thanks for understanding!
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6466">issues.joomla.org/joomla-cms/6466</a>.</sub>

**Comment by roland-d** [comment]
@wilsonge We have 2 successful tests but there is a merge conflict. Can you update the PR please?

**Comment by wilsonge** [comment]
Merged in staging @roland-d

**Pull request merged**
