### PR TITLE
[4.0] Fix user notes state change

### PR DESCRIPTION
**Pull request by bembelimen**
### Summary of Changes
This PR fixes the user notes status change. It removes the outdated publish override and uses the default handling with all the triggers from Joomla! itself.

### Testing Instructions
Go to the user notes, create a new note and then try to trash/publish/unpublish it

### Expected result
Note is trashed/published/unpublished

### Actual result
Error occurs:
grafik

### CODE REVIEW

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on d3a05c848114079b00f4dd31bf07c38c84d7f226<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23384">issues.joomla.org/tracker/joomla-cms/23384</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on d3a05c848114079b00f4dd31bf07c38c84d7f226<br /><br />on alpha7dev<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23384">issues.joomla.org/tracker/joomla-cms/23384</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23384">issues.joomla.org/tracker/joomla-cms/23384</a>.</sub>

**Comment by PhocaCz** [comment]
I have tested this item :white_check_mark: successfully on d3a05c848114079b00f4dd31bf07c38c84d7f226<br /><br />on Joomla! 4.0.0-alpha7-dev

OK<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23384">issues.joomla.org/tracker/joomla-cms/23384</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
