### PR TITLE
Fix db schema manger for utf8mb4 type converstions

### PR DESCRIPTION
**Pull request by richard67**
Pull Request for Issue #9258  .

Related also to issue #9247 
#### Summary of Changes

This pull request does not fix everything for the general problem described in issue #9258 in one of the ways I suggested there.

It only makes the database schema manager be tolerant for the automatic column data type changes on conversion to utf8mb4 character set on systems supporting utf8mb4 when checking the schema.
#### Testing Instructions

On a system with a mysql or MariaDB database supporting utf8mb4 (mysql server version >= 5.5.3 or some new MariaDB):
1. Update a Joomla! 3.4.8 to 3.5.0 Beta 3.
2. After successful update go to "Extensions -> Manage -> Database"
3. You will see a database problem reported that the conversion to "UTF-8 Multibyte (utf8mb4)" has not been done yet.
4. Click the "Fix" button to solve the problem.

**Expected result**

All database problems are solved.

**Actual result**

A new problem occurs:

> Table '#__user_profiles' does not have column 'profile_value' with type 'TEXT'. (From file 3.3.4-2014)

(replace "#__" by your database prefix)

Now repeat the same with an update container patched by this PR.

You can find it here: [http://test5.richard-fath.de/Joomla_3.5.0-beta3-Beta-Update_Package_test3.zip](http://test5.richard-fath.de/Joomla_3.5.0-beta3-Beta-Update_Package_test3.zip)

You als can use following link as custom url when using Joomla! Update component: [http://test5.richard-fath.de/list_test3.xml](http://test5.richard-fath.de/list_test3.xml)

**Result:** The problem about the user_profiles table is not shown anymore after the 1st successful database Fix for the utf8mb4 conversion.

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
what's the test update package URI?

**Comment by richard67** [comment]
See above test description, just added it.

**Comment by richard67** [comment]
In issue tracker it may take a while until visible, check on GitHub view of the PR.

**Comment by andrepereiradasilva** [comment]
Upgrade path: 3.4.8 -> 3.5.0 beta3 (your patch version)
Upgrade method: Install from URL
Upgrade method: Install from URL

Results:
- Update ok
- Extensions -> Database

image

Pressed "Fix"

image

All tables converted to utf8mb4_unicode_ci.

So sucess.

**Comment by andrepereiradasilva** [comment]
BTW a warning is yellow not red ;)

**Comment by richard67** [comment]
@andrepereiradasilva Old issue with color, at the moment I don't care about that.

I would call your test a good test, but it would be prefect if you could confirm that without the patch, the problem happens as described.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9267">issues.joomla.org/joomla-cms/9267</a>.</sub>

**Comment by andrepereiradasilva** [comment]
Upgrade path: 3.2.7 -> 3.5.0 beta3 (your patch version)

Same results: Success.

**Comment by richard67** [comment]
No need to test old version, and 2.5. will not work with my custom URL because details XML is not prepared for that.

**Comment by andrepereiradasilva** [comment]
ok, will test without the patch, i.e. 3.4.8 to 3.5.0 beta3

**Comment by richard67** [comment]
Thanks

**Comment by andrepereiradasilva** [comment]
Upgrade path: 3.4.8 -> 3.5.0 beta3 (official version)
Upgrade method: Joomla Update

Results:
- Update ok
- Extensions -> Database
image

Pressed "Fix"
image

Pressed "Fix" again
image

All tables converted to utf8mb4_unicode_ci.

So yes, the problem existed before your patch.

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 48fd057134464dba5a8c87e2f824856aadff151a<br /><br />As results of tests in above comments<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9267">issues.joomla.org/joomla-cms/9267</a>.</sub>

**Comment by richard67** [comment]
Thanks for testing @andrepereiradasilva .

One more tester please.

**Comment by richard67** [comment]
@wilsonge Please test and check and if ok RTC, should be merged soon for getting rid of the annoying thing for other future tests of other PRs on current staging.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9267">issues.joomla.org/joomla-cms/9267</a>.</sub>

**Comment by anibalsanchez** [comment]
I have tested this item :white_check_mark: successfully on 48fd057134464dba5a8c87e2f824856aadff151a<br /><br />* Test OK

- Warning: Database is not up to date!
- The Joomla! Core database tables have not been converted yet to UTF-8 Multibyte (utf8mb4).

... Fix ...

- Database table structure is up to date.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9267">issues.joomla.org/joomla-cms/9267</a>.</sub>

**Comment by richard67** [comment]
@wilsonge RTC?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9267">issues.joomla.org/joomla-cms/9267</a>.</sub>

**Comment by wilsonge** [comment]
Merged - thanks @richard67  :)

**Pull request merged**
