### PR TITLE
Update jQuery Autocomplete to 1.4.7

### PR DESCRIPTION
**Pull request by viocassel**
### Summary of Changes
This PR updates [jQuery Autocomplete](https://github.com/devbridge/jQuery-Autocomplete) library to version [1.4.3](https://github.com/devbridge/jQuery-Autocomplete/releases/tag/v1.4.3) for **com_finder** and **mod_finder**.

### Testing Instructions
1. Apply patch
2. Test the **com_finder** and **mod_finder** typing any word in search field (for example, _joomla_)
3. Make sure there are no JS errors and the list dropdown displayed correctly.

### Result
**com_finder**
com_finder

**mod_finder**
mod_finder

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :red_circle: unsuccessfully on a9e3f6237d51a2350f887ce96dbb9362113d3a11<br /><br />
Test on Module "Smart Search" and Menu "Smart Search > Search" got Notice:

bildschirmfoto 2017-09-26 um 08 54 17
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18113">issues.joomla.org/tracker/joomla-cms/18113</a>.</sub>

**Comment by C-Lodder** [comment]
@franz-wohlkoenig - This is only a notice and not an error, so it should not result in an unsuccessful test

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on a9e3f6237d51a2350f887ce96dbb9362113d3a11<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18113">issues.joomla.org/tracker/joomla-cms/18113</a>.</sub>

**Comment by ghost** [comment]
This is an easy Test. Needs a second successfully Test.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18113">issues.joomla.org/tracker/joomla-cms/18113</a>.</sub>

**Comment by Quy** [comment]
How do you enable Autocomplete? I don't get the dropdown choices.

**Comment by ghost** [comment]
@Quy have you indexed the Articles?

**Comment by Quy** [comment]
Yes indexed under Smart Search >Indexed Content, but still no suggestions dropdown.

**Comment by ghost** [comment]
@ Tested again, it works:

- Module "Smart Search": Type "joo" and Dropdown is showing
- Menu "Smart Search": Type "joo" and Dropdown is showing

**Comment by Quy** [comment]
It is now up to v1.4.6.

**Comment by viocassel** [comment]
Updated jQuery Autocomplete to 1.4.7

Please test...

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on ca69b890eb75bada0e1ed6cd2530ef9b01289c33<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18113">issues.joomla.org/tracker/joomla-cms/18113</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on ca69b890eb75bada0e1ed6cd2530ef9b01289c33<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18113">issues.joomla.org/tracker/joomla-cms/18113</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Pull request merged**
