### PR TITLE
Fix overwrite by .table-striped

### PR DESCRIPTION
**Pull request by mansourcodes**
Fix overwrite by administrator/templates/isis/css/template.css line 1787

table.table-striped tbody > tr:nth-child(odd) > td,
table.table-striped tbody > tr:nth-child(odd) > th {
	background-color: #f9f9f9;
}

Pull Request for Issue # .

### CODE REVIEW

**Comment by brianteeman** [comment]
There was a reason that we ask you to complete the questions that you chose to ignore. Having looked at the pr and made a guess I dont see any changes in the resulting css. Please explain - perhaps with pictures. What the problem is and how this pr resolves it.

**Comment by ghost** [comment]
Closed as duplicate Pull Request of #20179.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20180">issues.joomla.org/tracker/joomla-cms/20180</a>.</sub>

**Comment by brianteeman** [comment]
Please re-open - it is not a duplicate. The change is on different files

**Comment by ghost** [comment]
Reopened as stated above.

Thought its a duplicate cause Description is same, haven't looked at different File.

**Comment by ReLater** [comment]
I needed some time to understand.
Whenever a field of type `calendar` is somewhere inside a `table.table-striped` the today date  is not readable.



- Create a `subform` field that uses layout `layout="joomla.form.field.subform.repeatable-table"`.
- Add a calendar field to the subform
- Something like this
```
<field name="fotos" type="subform" 
layout="joomla.form.field.subform.repeatable-table"
min="1" max="100" multiple="true"
label="Add date" description="">
 <form hidden="true" name="something" repeat="true">
  <field name="calendar" type="calendar" label="calendar" />
 </form>
</field>
```
- Then you have a [table.table-striped around the calendar field](https://github.com/joomla/joomla-cms/blob/staging/layouts/joomla/form/field/subform/repeatable-table.php#L78).
- See image above.
- Apply patch.
- Result

**Comment by ReLater** [comment]
I have tested this item :white_check_mark: successfully on ca17b9b9d604105b8153bbdea717069d1efbe2d3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20180">issues.joomla.org/tracker/joomla-cms/20180</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on ca17b9b9d604105b8153bbdea717069d1efbe2d3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20180">issues.joomla.org/tracker/joomla-cms/20180</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20180">issues.joomla.org/tracker/joomla-cms/20180</a>.</sub>

**Pull request merged**
