### PR TITLE
Fix the response from the AJAX ACL change to be correct

### PR DESCRIPTION
**Pull request by roland-d**
Related to #10755 
#### Summary of Changes

This change fixes the feedback given by the AJAX response when changing a permission.
#### Testing Instructions
1. Go to System -> Global configuration -> Permission
2. Click on Super User
3. Change the permission to Denied
4. The response is that the permission is Denied which is not true should be Allowed (Super User)
5. Click on Manager
6. Change Site Login to Denied
7. Click on Administrator
8. Change Site Login to Allowed
9. The response is that the permission is Allowed which is not true should be Conflict because the Denied of Manager overrules the Administrator setting
10. Apply the patch
11. Go to System -> Global configuration -> Permission
12. Click on Super User
13. Change the permission to Denied
14. The response is that the permission is Allowed (Super User). This is correct because the Super User setting overrules this.
15. Click on Manager
16. Change Site Login to Denied
17. Click on Administrator
18. Change Site Login to Allowed
19. The response is that the permission is in Conflict. This is correct because the Denied of Manager overrules the Administrator setting of Allowed

Calling @andrepereiradasilva and @infograf768 for special attention :)

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
> 9  The response is that the permission is Allowed which is not true should be Conflict because the Denied of Manager overrules the Administrator setting

IMHO "Conflict" is not the right word, should be "Denied (parent rule)" or something like that.

**Comment by roland-d** [comment]
@andrepereiradasilva Again, I agree with you but the current implementation doesn't support this. My goal is to fix the problems first and then improve what we have.

**Comment by andrepereiradasilva** [comment]
ok right!

**Comment by infograf768** [comment]
siesta time, will look later.. ;)

**Comment by andrepereiradasilva** [comment]
Just an additional comment.
Before doing
> 18 Change Site Login to Allowed

The administrator "Site Login" caculated permission is "Not Allowed (Locked)".
And when changed to "Allowed" we get "Conflict".

So, if i understand correctly, we have two text strings for the same thing ... that is rather confusing.
I guess this was nothing to do with this PR, but this could be better.

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 458adc073f2ee21f133a37c1c5048c72bb51c9c3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10757">issues.joomla.org/joomla-cms/10757</a>.</sub>

**Comment by roland-d** [comment]
@andrepereiradasilva You now see the quicksand I have been playing with :)

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 458adc073f2ee21f133a37c1c5048c72bb51c9c3<br /><br />OK here. I can't believe how bad ACL has gone...<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10757">issues.joomla.org/joomla-cms/10757</a>.</sub>

**Comment by infograf768** [comment]
RTC, <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10757">issues.joomla.org/joomla-cms/10757</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@roland-d you're makign a great work solving all this issues! Thanks!

**Comment by roland-d** [comment]
@infograf768 At least we are fixing it :)

@andrepereiradasilva Thanks.

**Comment by infograf768** [comment]
You are! I can't believe no one else tries. 😺

**Comment by infograf768** [comment]
back to siesta

**Pull request merged**
