### PR TITLE
IIS - Add woof mime type for media folder in web.config.txt

### PR DESCRIPTION
**Pull request by vinespie**
This PR add woof mime type for iis web.config because it is not configured by default. This causes 404 errors on files of type ".woff ". Only configure this for media folder.
## Actual result in "Article Manager: Edit Article"

2015-06-13 13_00_40-joomla-cms - administration - article manager_ edit article
## Actual result in "   Banner Manager Options"

2015-06-13 13_10_41-joomla-cms - administration - banner manager options
## Expected result

No 404 errors
## How to test

You must use IIS for test this PR
1. In administration, edit article,
2. You must see 404 errors,
3. Apply the patch and refesh the page,
4. There are more error.

### CODE REVIEW

**Comment by brianteeman** [comment]
There appears to be a lot of unrelated changes in this PR<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7168">issues.joomla.org/joomla-cms/7168</a>.</sub>

**Comment by zero-24** [comment]
@vinespie can you send a clean pull request with only the needed changes and without e.g. the javascript one?

I guess only the following here: web.config.txt?
```
+   <location path="media">
+       <system.webServer>
+           <staticContent>
+               <mimeMap fileExtension=".woff" mimeType="application/x-woff" />
+           </staticContent>
+       </system.webServer>
+   </location>
```

Github GUI: https://docs.joomla.org/Using_the_Github_UI_to_Make_Pull_Requests

**Comment by brianteeman** [comment]
Setting to information required until the PR is corrected so testers dont waste their time just yet<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7168">issues.joomla.org/joomla-cms/7168</a>.</sub>

**Comment by brianteeman** [comment]
Please see #7273 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7168">issues.joomla.org/joomla-cms/7168</a>.</sub>

**Pull request closed without merging**
