### PR TITLE
FoF and PHP 8

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Fixes a fatal error, a warning and deprecation notices on PHP 8.

```
Warning: Private methods cannot be final as they are never overridden by other classes in libraries\fof\controller\controller.php on line 2156
Deprecated: Required parameter $class follows optional parameter $column in libraries\fof\database\iterator.php on line 89
Deprecated: Required parameter $class follows optional parameter $column in libraries\fof\database\iterator.php on line 108
Fatal error: Declaration of FOFLayoutHelper::render($layoutFile, $displayData = null, $basePath = '') must be compatible with Joomla\CMS\Layout\LayoutHelper::render($layoutFile, $displayData = null, $basePath = '', $options = null) in libraries\fof\layout\helper.php on line 28
Deprecated: Required parameter $itemName follows optional parameter $pivot in libraries\fof\table\relations.php on line 901
Deprecated: Required parameter $tableClass follows optional parameter $pivot in libraries\fof\table\relations.php on line 901
Deprecated: Required parameter $localKey follows optional parameter $pivot in libraries\fof\table\relations.php on line 901
Deprecated: Required parameter $remoteKey follows optional parameter $pivot in libraries\fof\table\relations.php on line 901
Deprecated: Required parameter $ourPivotKey follows optional parameter $pivot in libraries\fof\table\relations.php on line 901
Deprecated: Required parameter $theirPivotKey follows optional parameter $pivot in libraries\fof\table\relations.php on line 901
Deprecated: Required parameter $pivotTable follows optional parameter $pivot in libraries\fof\table\relations.php on line 901
```

### Documentation Changes Required

Developers who extended `FOFLayoutHelper` should note they need to add an additional argument to its `render()` method to support PHP 8.

### CODE REVIEW

**Comment by zero-24** [comment]
> FOFLayoutHelper should note they need to add an additional argument to its render() method to support PHP 8.

Is that change also required on php 7 or only on  / for php 8?

**Comment by SharkyKZ** [comment]
PHP 7 only emits a warning.

**Comment by zero-24** [comment]
:+1:

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 0a0a4e7d00e63760e802286b168c9f48e0c1e744<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30922">issues.joomla.org/tracker/joomla-cms/30922</a>.</sub>

**Comment by Quy** [comment]
To reproduce, go to Components > Post-installation Messages.

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 0a0a4e7d00e63760e802286b168c9f48e0c1e744<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30922">issues.joomla.org/tracker/joomla-cms/30922</a>.</sub>

**Comment by jwaisner** [comment]
@SharkyKZ can you restart drone? Looks like it hasn't reported back on this PR.

I don't expect problems as it tested well but want to ensure all checks pass.

**Comment by SharkyKZ** [comment]
@jwaisner I don't see how to.

**Comment by zero-24** [comment]
> @jwaisner I don't see how to.

Usually you can trigger drone with a new commit or by updating the branch to the latest staging. Can you try whether that works?

**Comment by HLeithner** [comment]
Seems drone doesn't like the "build message". Please make a new commit

**Comment by SharkyKZ** [comment]
No dice. It doesn't appear on http://ci.joomla.org/joomla/joomla-cms/.

**Comment by HLeithner** [comment]
Can you please push again, I removed your emoji from the description...

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30922">issues.joomla.org/tracker/joomla-cms/30922</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
