### PR TITLE
Admin Joomla Version Module

### PR DESCRIPTION
**Pull request by brianteeman**
the string says that "joomla" will be displayed if set to show when using the Short Version

This is not correct. The string "joomla" will be displayed if set to show when using either the short or the long version

This pr corrects the string so that it shows the correct information

### CODE REVIEW

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on ad11c5a54153c7e7e2051b47611637d0d74d38c6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14568">issues.joomla.org/tracker/joomla-cms/14568</a>.</sub>

**Comment by zero-24** [comment]
Thanks. You are correct the option (Yes/No) is respected in the long and short version setting :smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14568">issues.joomla.org/tracker/joomla-cms/14568</a>.</sub>

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on ad11c5a54153c7e7e2051b47611637d0d74d38c6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14568">issues.joomla.org/tracker/joomla-cms/14568</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14568">issues.joomla.org/tracker/joomla-cms/14568</a>.</sub>

**Pull request merged**
