### PR TITLE
[4.0] Remove com_admin profile

### PR DESCRIPTION
**Pull request by brianteeman**
The users icon in the mod_status module links to a view of the logged in users profile. However because it is NOT using com_users any plugins that extend com_users are not displayed. For example TFA plugins when enabled are not accessible from this link and are only accessible from the users component. Maintaining this additional view makes no sense to me. Its a regular cause of bug reports etc.

This PR completely removes the com_admin profile and replaces the link in the module to use com_users. Now any plugins that extend com_users are accessible from the link which is what the user expects

### CODE REVIEW

**Comment by wilsonge** [comment]
Makes sense to me - are we aware why this view existed in the past?

**Comment by brianteeman** [comment]
I honestly dont know. I just know we "didnt remove it" because of b/c

**Comment by brianteeman** [comment]
Found it - and not sure you are going to believe the reason

https://developer.joomla.org/joomlacode-archive/issue-23347.html

**Comment by brianteeman** [comment]
BTW any idea why rips is failing all the time

**Comment by wilsonge** [comment]
No :( @zero-24 @SniperSister can you have a look please

**Comment by zero-24** [comment]
updated branch that let rips run again as this seams to be an issue fixed some time ago.

**Comment by brianteeman** [comment]
thanks @zero-24

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks

**Comment by wilsonge** [comment]
Documented https://docs.joomla.org/Potential_backward_compatibility_issues_in_Joomla_4#Components

**Pull request merged**
