### PR TITLE
[4.0] Namespace mod articles news

### PR DESCRIPTION
**Pull request by C-Lodder**
### Summary of Changes

Namespace mod articles news

### CODE REVIEW

**Comment by brianteeman** [comment]
tested it ok
this doesnt show up on the issue tracker?

**Comment by C-Lodder** [comment]
https://issues.joomla.org/tracker/joomla-cms/17285 It's there for me

**Comment by brianteeman** [comment]
as an issue not a pr i can mark my test result

**Comment by wilsonge** [comment]
@zero-24 @mbabker any reason this showed as an issue not a PR in the tracker?

**Comment by zero-24** [comment]
@wilsonge i don't get the question? It looks good to me?

image

**Comment by mbabker** [comment]
There's a flag in the issue tracker database (the `has_code` column on our issues table) that determines if something is an issue or PR and we use that flag to conditionally show some stuff that's only relevant to a PR.  For whatever reason, that flag never got set to true so it displays with issue logic versus PR logic.

**Pull request merged**
