### PR TITLE
[4.0] Fix duplicate class attribute

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
Combine class attributes so that there is only one.

### Testing Instructions
Code review.

### CODE REVIEW

**Comment by rjharishabh** [comment]
@Quy `CSS` missing in `cache-entry`

cache_entry

**Comment by rjharishabh** [comment]
@Quy  Is `cache-entry` class used for styling or for `Javascript` stuff

**Comment by Quy** [comment]
JavaScript, see https://github.com/joomla/joomla-cms/blob/7d02ff86b956064e1d12bc386f61ec28069c7633/build/media_source/com_cache/js/admin-cache-default.es6.js#L12

**Comment by rjharishabh** [comment]
I got it @Quy 
Thanks

**Comment by Quy** [comment]
Included in PR #33413

**Pull request closed without merging**
