### PR TITLE
[4.0] Remove unused scss file

### PR DESCRIPTION
**Pull request by Quy**
### Testing Instructions
Code review.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 5336a21ba1ed2ad7e1791ece22ceec7072b4819a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31210">issues.joomla.org/tracker/joomla-cms/31210</a>.</sub>

**Comment by N6REJ** [comment]
I have tested this item :white_check_mark: successfully on 5336a21ba1ed2ad7e1791ece22ceec7072b4819a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31210">issues.joomla.org/tracker/joomla-cms/31210</a>.</sub>

**Comment by SharkyKZ** [comment]
RTC.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31210">issues.joomla.org/tracker/joomla-cms/31210</a>.</sub>

**Comment by SharkyKZ** [comment]
Sorry, setting back to pending. Tests are failing. The file is still referenced in ``administrator/templates/atum/scss/vendor/choicesjs/choices.scss``<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31210">issues.joomla.org/tracker/joomla-cms/31210</a>.</sub>

**Comment by brianteeman** [comment]
Good spot. Annoyed I missed that<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31210">issues.joomla.org/tracker/joomla-cms/31210</a>.</sub>

**Comment by hans2103** [comment]
I have tested this item :white_check_mark: successfully on 9ab00664275962723e81040ff7af738a6d2fe7b6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31210">issues.joomla.org/tracker/joomla-cms/31210</a>.</sub>

**Comment by richard67** [comment]
@Quy Now drone says in the "npm" step:

```
Error: File to import not found or unreadable: ../../mixin.
        on line 7 of administrator/templates/atum/scss/vendor/joomla-custom-elements/joomla-tab.scss
>> @import "../../mixin";
```

**Comment by richard67** [comment]
So as we can see, a code review is NOT sufficient to test such PRs. It needs to run npm to see if scss files are still compiled without errors, or at least to check drone.

And if code review, then a simple `findstr /s /c:"../mixin" *.scss` in a Windows command shell or `find ./ -type f -name "*\.scss" -exec grep -Hn "../mixin" {} \;` in a Linux shell would have shown the remaining imports, too.

Code review doesn't mean to look only on the changes in a PR, it means also e.g. if something is removed from code to make sure it is not used anywhere else.

**Pull request closed without merging**
