### PR TITLE
[4.0] Fix calendar tweaks

### PR DESCRIPTION
**Pull request by hardik-codes**
Pull Request for Issue #23795 

### Summary of Changes
Changed the png clock icon to svg clock icon. 
Also the border above ```Sat``` and ```wk``` is reduced to its normal size

### Testing Instructions
1.Open an article in the Joomla backend
2. Open the calendar found under "Start Publishing"

### Documentation Changes Required
None

### CODE REVIEW

**Comment by C-Lodder** [comment]
There is still some sort of misalignment in the top line but everything seems fine for now.

**Comment by hardik-codes** [comment]
> There is still some sort of misalignment in the top line but everything seems fine for now.

Its because of ```border-collpase: collapse;``` property but I'm not able to find out in which file it is located

**Comment by infograf768** [comment]
@hardik-codes 
I suggest to add in both /build/media_source/system/css/fields/calendar.css and calendar-rtl.css 
```
.calendar-container table {
	border-collapse: separate;
}
```
that should override the default bootstrap `collapse` to get

screen shot 2019-02-18 at 16 54 18

Remains to correct the buttons Clear Today Close

**Comment by hardik-codes** [comment]
@infograf768 
In the comments of the above issue @C-Lodder has mentioned that the buttons will most likely be injected from the JS file and he'll be rewriting the calendar as a custom element soon.

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on e92514cde3aa66ac4e246806e2bbcb018daf77d4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23903">issues.joomla.org/tracker/joomla-cms/23903</a>.</sub>

**Pull request merged**
