### PR TITLE
[4.0] plg-editors-xtd description

### PR DESCRIPTION
**Pull request by brianteeman**
These plugins apply to any editor area not just to articles

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 5f717c24c49dd86fdf5c412fe07fc683214df136<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33770">issues.joomla.org/tracker/joomla-cms/33770</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33770">issues.joomla.org/tracker/joomla-cms/33770</a>.</sub>

**Comment by Quy** [comment]
Thanks

**Comment by brianteeman** [comment]
Thank you

**Pull request merged**
