### PR TITLE
[4.0] Fix typo

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Fixes typo.

### Testing Instructions

Code review.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 7a4cec673f7c30bd9355aa87686e4291675d4f15<br /><br />Ok on review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30326">issues.joomla.org/tracker/joomla-cms/30326</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 7a4cec673f7c30bd9355aa87686e4291675d4f15<br /><br />code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30326">issues.joomla.org/tracker/joomla-cms/30326</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30326">issues.joomla.org/tracker/joomla-cms/30326</a>.</sub>

**Comment by infograf768** [comment]
Restarted drone

**Comment by richard67** [comment]
Drone failure is related to an error which meanwhile has been fixed in 4.0-dev, but that's less than one hour ago so this PR doesn't have that fix yet. @SharkyKZ Could you update your branch of this PR to the latest 4.0-dev of the CMS? Thanks in advance.

**Comment by richard67** [comment]
Ah I see it is RTC and a clear change. No need to update your branch, @SharkyKZ .

**Comment by infograf768** [comment]
Tks

**Pull request merged**
