### PR TITLE
Make option desc into a label

### PR DESCRIPTION
**Pull request by brianteeman**
The label for one of the article options is more of a sentence than a label. Simple change to make it a label and be consistent

### Before
image

### After
image

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 6311d42bf4ebf3a0fbe44ed05dd44596109151b2<br /><br />p.s
when images tell more than words
i didn't  understand from pr title <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13119">issues.joomla.org/tracker/joomla-cms/13119</a>.</sub>

**Comment by brianteeman** [comment]
Yeah I realised it was going to be hard to describe -sorry but thanks for
testing

**Comment by cheesegrits** [comment]
Tested succesfully<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13119">issues.joomla.org/tracker/joomla-cms/13119</a>.</sub>

**Comment by cheesegrits** [comment]
I have tested this item :white_check_mark: successfully on 6311d42bf4ebf3a0fbe44ed05dd44596109151b2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13119">issues.joomla.org/tracker/joomla-cms/13119</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13119">issues.joomla.org/tracker/joomla-cms/13119</a>.</sub>

**Comment by wilsonge** [comment]
Thanks :)

**Pull request merged**
