### PR TITLE
[4.0] Pass value to language string

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
Pass value to language string instead of hard-coding in template.

### Testing Instructions
Go to System > System Information
Click `PHP Settings` tab.
Labels same before/after PR.

```
GD Available
iconv Available
intl Available
```

### CODE REVIEW

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 2cf77187fc40035a55301cbad388e410d2b8daa9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34178">issues.joomla.org/tracker/joomla-cms/34178</a>.</sub>

**Comment by brianteeman** [comment]
It was deliberate that the strings were written this way to avoid the situation where translators try to translate the gd, iconv and intl

Please do not do this

**Comment by Quy** [comment]
Won't this be an issue with RTL if not done this way?

**Comment by brianteeman** [comment]
no - why

**Comment by Quy** [comment]
Translators won't see these values in the language string to translate because before/after PR these values are in the template vs, the following where they might.

```
COM_ADMIN_XML_ENABLED="XML فعال"
COM_ADMIN_ZLIB_ENABLED="Zlib فعال"
```

**Comment by brianteeman** [comment]
we dont want them to see the strings. they will try to translate them. we saw that for years with the "installation" folder being translated etc etc.

This PR is wrong

**Comment by Quy** [comment]
Have you looked at the code? Sorry if my description gave you the wrong impression.

**Comment by brianteeman** [comment]
Sorry you are right your description gives the wrong impression completely

**Comment by Quy** [comment]
Updated title/description. Sorry for the confusion.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 2cf77187fc40035a55301cbad388e410d2b8daa9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34178">issues.joomla.org/tracker/joomla-cms/34178</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34178">issues.joomla.org/tracker/joomla-cms/34178</a>.</sub>

**Comment by richard67** [comment]
@brianteeman Could you revert your thumbs down on the PR description? It looks so ... sharkyesque 😉

**Comment by brianteeman** [comment]
also didnt help that I was checking the code locally for the update model where it was already a sprintf

**Comment by chmst** [comment]
Thanks!

**Pull request merged**
