### PR TITLE
Isis and hathor frontend links: Frontend uri scheme can be different from admin

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/8109 .
#### Summary of Changes

This updates Isis and hathor templates frontend links because joomla allows different schemes for admin and frontend site.
#### Testing Instructions
1. Use latest staging.
2. Set the site to "Force SSL" in "Administrator Only" in global config.
3. Notice, that you are in `https` in admin as you selected, but:
   - the frontend preview link (top right) is `https`
   - the "View site" link in (bottom left) of the admin panel is `https`
   -  the "Go to site home page." link in the backend login page is `https` (in isis and hathor templates)
4. Apply the patch.
5. Repeat steps 2 and 3 and you will notice the links are now `http` as they should.

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
@stellainformatica can you check this PR solves the issue?

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on f8c13c5d1d890e9e109415a7c14b6ee5d2a27f9b<br /><br />Tested with success for both Isis and Hathor templates.

@andrepereiradasilva  Maybe you should update the summary of changes ("This updates isis template preview links ..."= so it reflects that also Hathor has been changed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9712">issues.joomla.org/joomla-cms/9712</a>.</sub>

**Comment by andrepereiradasilva** [comment]
done

**Comment by zero-24** [comment]
@andrepereiradasilva can you have a look into the merge conflicts?

**Comment by andrepereiradasilva** [comment]
conflicts fixed

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on b33de49e9079d131508e0c834b2c890294e99838<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9712">issues.joomla.org/joomla-cms/9712</a>.</sub>

**Comment by AlexRed** [comment]
I have tested this item :white_check_mark: successfully on b33de49e9079d131508e0c834b2c890294e99838<br /><br />Fantastic!!

Thanks  :)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9712">issues.joomla.org/joomla-cms/9712</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9712">issues.joomla.org/joomla-cms/9712</a>.</sub>

**Comment by roland-d** [comment]
Thanks everybody

**Pull request merged**
