### PR TITLE
Save default field values [com_fields]

### PR DESCRIPTION
**Pull request by Arkadiy-Sedelnikov**
Pull Request for Issue #18546.

### Summary of Changes

Added saving of field values matching the default values.

### Testing Instructions

Set the default value for the field. In the article, select or enter the default value in the field. Save the article. Check preserved-whether the value and the correctness of its output at the front of the site.

### Expected result

In the website, nothing has changed, and a value equal to the default stored in the database in table #__fields_values.

### Actual result

In the website, nothing has changed, and a value equal to the default stored in the database in table #__fields_values.

### Documentation Changes Required

No

### CODE REVIEW

**Comment by Arkadiy-Sedelnikov** [comment]
The Travis CI crashed at last check. What do I do now?

**Comment by Bakual** [comment]
I've restarted the terminated job.

**Comment by effrit** [comment]
I have tested this item :white_check_mark: successfully on d8b4a99760e5cdffc57c92c148195b5999631de9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18891">issues.joomla.org/tracker/joomla-cms/18891</a>.</sub>

**Comment by Septdir** [comment]
Tested on radio type.  Now default value saved in the database

**Comment by ladyjer** [comment]
I have tested this item :white_check_mark: successfully on d8b4a99760e5cdffc57c92c148195b5999631de9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18891">issues.joomla.org/tracker/joomla-cms/18891</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on d8b4a99760e5cdffc57c92c148195b5999631de9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18891">issues.joomla.org/tracker/joomla-cms/18891</a>.</sub>

**Comment by infograf768** [comment]
RTC. Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18891">issues.joomla.org/tracker/joomla-cms/18891</a>.</sub>

**Comment by Septdir** [comment]
I have tested this item :white_check_mark: successfully on d8b4a99760e5cdffc57c92c148195b5999631de9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18891">issues.joomla.org/tracker/joomla-cms/18891</a>.</sub>

**Comment by Arkadiy-Sedelnikov** [comment]
I have tested this item :white_check_mark: successfully on d8b4a99760e5cdffc57c92c148195b5999631de9<br /><br />Tested in textgield.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18891">issues.joomla.org/tracker/joomla-cms/18891</a>.</sub>

**Pull request merged**
