### PR TITLE
[4.0]com_finder index missing string

### PR DESCRIPTION
**Pull request by brianteeman**
There was no label on the language filter

To test view source on the language and see that the label is not "language" or code review

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on b2433f9a9df23ebf17ba6b6e3d7726e97af7662c<br /><br />Code review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28189">issues.joomla.org/tracker/joomla-cms/28189</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on b2433f9a9df23ebf17ba6b6e3d7726e97af7662c<br /><br />Code Review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28189">issues.joomla.org/tracker/joomla-cms/28189</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28189">issues.joomla.org/tracker/joomla-cms/28189</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thank you

**Pull request merged**
