### PR TITLE
[5.1] Add missing import

### PR DESCRIPTION
**Pull request by Quy**
Pull Request for Issue #40131.

 `Class "Joomla\CMS\Installer\Path" not found`.

### Testing Instructions
Install PatchTester.
See error.

### CODE REVIEW

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on b9fbed2203cf9407f4046163b868c4c0886638d3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42947">issues.joomla.org/tracker/joomla-cms/42947</a>.</sub>

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on b9fbed2203cf9407f4046163b868c4c0886638d3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42947">issues.joomla.org/tracker/joomla-cms/42947</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on b9fbed2203cf9407f4046163b868c4c0886638d3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42947">issues.joomla.org/tracker/joomla-cms/42947</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42947">issues.joomla.org/tracker/joomla-cms/42947</a>.</sub>

**Comment by bembelimen** [comment]
Thy

**Pull request merged**
