### PR TITLE
[4.3] Remove last style

### PR DESCRIPTION
**Pull request by brianteeman**
PR for #36217

### Summary of Changes
Adds an action to the error message

### Testing Instructions
Create a child template of cassiopeia called fred
Go to the template styles and try to delete the template style for cassiopeia_fred

### Actual result BEFORE applying this Pull Request
image

### Expected result AFTER applying this Pull Request
Message now has a link
image

Link goes to the extension manage view prefiltered for templates
image

### Link to documentations
Please select:
- [x] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [x] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by ReLater** [comment]
I have tested this item :white_check_mark: successfully on 19c26509d1b2d4015d96f83968ad133c7cef7e6d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39491">issues.joomla.org/tracker/joomla-cms/39491</a>.</sub>

**Review by wilsonge — APPROVED** [review]

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on a7e31b8e01ee31506a9c7636e259a1bde5554f85<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39491">issues.joomla.org/tracker/joomla-cms/39491</a>.</sub>

**Comment by ReLater** [comment]
I have tested this item :white_check_mark: successfully on a7e31b8e01ee31506a9c7636e259a1bde5554f85<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39491">issues.joomla.org/tracker/joomla-cms/39491</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39491">issues.joomla.org/tracker/joomla-cms/39491</a>.</sub>

**Comment by brianteeman** [comment]
thx

**Pull request merged**
