### PR TITLE
Fixes str_replace deprecation warning in php 8.1+

### PR DESCRIPTION
**Pull request by N6REJ**
Pull Request for Issue # .

### Summary of Changes

Removes the deprecation warning when fetching data with patch_tester

### Testing Instructions
install https://github.com/joomla-extensions/patchtester/releases/tag/4.2.1
enter your credentials and apply this patch.
Now fetch your data.
a box will pop up with several errors.

### Actual result BEFORE applying this Pull Request

```
An error has occurred while fetching the data from GitHub.

Deprecated: strtoupper(): Passing null to parameter #1 ($string) of type string is deprecated in E:\Bearsampp\www\j4\libraries\src\MVC\Model\ListModel.php on line 543

Deprecated: mb_strlen(): Passing null to parameter #1 ($string) of type string is deprecated in E:\Bearsampp\www\j4\libraries\vendor\joomla\string\src\phputf8\mbstring\core.php on line 24

Deprecated: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in E:\Bearsampp\www\j4\libraries\src\HTML\Helpers\StringHelper.php on line 132
{"success":true,"message":"Processing page 2 of 3 pages of GitHub data","messages":null,"data":{"complete":false,"page":2,"lastPage":3}}
```

### Expected result AFTER applying this Pull Request
image
Notice warning is gone.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by toivo** [comment]
In my Wampserver and PHP 8.1.9 test site both 4.2.3 and 4.2.4-dev of 30 September (the latest Nightly Build - just reported the anomaly in Prod Dept Glip) reported only the error addressed in #38917:
Deprecated: strtoupper(): Passing null to parameter #1 ($string) of type string is deprecated in C:\www\joomla42\libraries\src\MVC\Model\ListModel.php on line 543

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38918">issues.joomla.org/tracker/joomla-cms/38918</a>.</sub>

**Comment by N6REJ** [comment]
@toivo there are 3 errors generated.  Each have their own pr's.

**Comment by toivo** [comment]
> @toivo can you please test and make sure the str_replace error is gone

I had to patch the two lines in StreingHelper.php because of the PatchTester error.  It did not help, the error is still displayed at the top of PatchTester and before any list of PRs is retrieved:
Deprecated: strtoupper(): Passing null to parameter #1 ($string) of type string is deprecated in ``C:\www\joomla4test\libraries\src\MVC\Model\ListModel.php on line 543``

The test environment was was Joomla 4.2.4-dev updated from Nightly Builds of 10 October, the latest available.  Apprently there will be a sprint to fix the issues, including the fault stopping the Nightly Builds from being released

**Comment by N6REJ** [comment]
@toivo you shouldn't have to replace anything.  I think your getting confused.  There are 3 errors currently.  This pr address ONLY the str_replace error.

**Comment by toivo** [comment]
> @toivo you shouldn't have to replace anything. I think your getting confused. There are 3 errors currently. This pr address ONLY the str_replace error.

I am not confused at all.  The bug stops the Patch Tester from working if Error Reporting is set to 'Maximum'.  That is why I edited the file manually.  Now I changed Error Reporting to 'Simple' to filter Deprecated messages, ran Patch Tester and applied the PR, then changed Error Reporting back to 'Maximum'.  Tried to run the Patch Tester and the same error occurs in line 543:
`` Deprecated: strtoupper(): Passing null to parameter #1 ($string) of type string is deprecated in C:\www\joomla4test\libraries\src\MVC\Model\ListModel.php on line 543``

**Comment by N6REJ** [comment]
@toivo 543 is not the error this patch fixes... 
```
Deprecated: str_replace(): Passing null to parameter #3 ($subject) of type array|string is deprecated in E:\Bearsampp\www\j4\libraries\src\HTML\Helpers\StringHelper.php on line 132
{"success":true,"message":"Processing page 2 of 3 pages of GitHub data","messages":null,"data":{"complete":false,"page":2,"lastPage":3}}
``` is the error.

**Comment by toivo** [comment]
@N6REJ, the str_replace error did not come up in my test before the PR was applied.  Your test environment must somehow be different.  Sorry, I did not read the description and thought that this PR was fixing strtoupper() in line 543 as well.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38918">issues.joomla.org/tracker/joomla-cms/38918</a>.</sub>

**Pull request closed without merging**
