### PR TITLE
[4.0] Fix Client dropdown mis-alignment

### PR DESCRIPTION
**Pull request by Arpit-24**
Pull Request for Issue #23807  .

### Summary of Changes

Change flex-end to flex-start to align to the left side

### Testing Instructions

administrator/index.php?option=com_modules&view=modules

### Expected result

Screenshot (1273)
Screenshot (1274)

### CODE REVIEW

**Comment by infograf768** [comment]
Not sure I understand.
What are you trying to solve? 
I can't reproduce https://github.com/joomla/joomla-cms/issues/23807 here (Firefox) whether I use `flex-start` or `flex-end`. The client is always floating as should (depending if lang is ltr or rtl).

**Comment by infograf768** [comment]
Oh, this concerns specially IE11...
I modify the title.

**Review by C-Lodder — CHANGES_REQUESTED** [review]
You will also need to ensure it works on RTL

**Comment by Arpit-24** [comment]
> You will also need to ensure it works on RTL

Tested by changing the html tag attribute dir from ltr to rtl. While not really a pleasure to look at but the same behavior is exhibited by both Chrome and IE11 so I think it works.

Screenshot (1277)
Screenshot (1276)

**Comment by infograf768** [comment]
To test rtl, please install the Persian language and use it in back-end.
One gets this (as the pack is 3.x, are missing some lang strings and en-GB string are used)

Screen Shot 2019-04-01 at 11 34 33

**Comment by ghost** [comment]
@C-Lodder as Issue opener please test.

**Comment by C-Lodder** [comment]
If @infograf768 is happy with the RTL result, I approve based on code review.

**Comment by Quy** [comment]
This is no longer an issue with the [new backend template](https://github.com/joomla/backend-template/tree/release).



24421rtl

**Pull request closed without merging**
