### PR TITLE
[4.0] return to dashboard link

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #30952  .

### Summary of Changes
Ensures the link on the error page works when your site is not on the standard ports

@philetaylor please test this - I doubt many of the regular testers will change their apache config

I am surprised you havent come across this in other places

### CODE REVIEW

**Comment by brianteeman** [comment]
@zero-24 please check the rips report

**Comment by PhilETaylor** [comment]
Sorry this is not right.

```php
$this->baseurl = Uri::base(true);
```

This gives "/administrator"

```php
$this->baseurl = Uri::base(false);
```
This gives "http://127.0.0.1:4444/administrator/"


The true/false param is for `pathonly` so it makes sense that it should be `false` whereas your PR has `true` :-)

**Comment by PhilETaylor** [comment]
Also once using 

```
$this->baseurl = Uri::base(false);
```
before the // template params line - This then makes the SVG paths with double // in the path 

"http://127.0.0.1:4444/administrator//templates/atum/images/logos/brand-small.svg"

**Comment by SharkyKZ** [comment]
I can't reproduce the issue.

**Comment by PhilETaylor** [comment]
> I can't reproduce the issue.

Sad to hear that. 

I have just retested in all three main browsers (safari, chrome, Firefox) and I can replicate in all 

Using the error page, on http with a web server on a custom port number, 
http://127.0.0.1:4444/administrator/index.php?option=com_media&task=file.edit&id=0

The link is then "/administrator" which when clicked goes to http://127.0.0.1/administrator/ losing the port number

**Comment by brianteeman** [comment]
I am closing this as I see now my code made zero change and it was actually working without it

**Comment by brianteeman** [comment]
and yes I also tested on an ip address and not just on localhost

**Pull request closed without merging**
