### PR TITLE
[4.2] Fix redirect on login url error

### PR DESCRIPTION
**Pull request by joomdonation**
Pull Request for Issue #38297.

### Summary of Changes
See https://github.com/joomla/joomla-cms/issues/38297 to understand the issue

### Testing Instructions
1. Install Joomla 4.2 nightly build
2. Confirm the issue https://github.com/joomla/joomla-cms/issues/38297
3. Apply patch, confirm that the issue fixed
4. If it is possible, test the login redirect on a multilingual website and make sure it is still working as expected.

### Actual result BEFORE applying this Pull Request
There is unnecessary lang variable with empty value in login, logout redirect URL

### Expected result AFTER applying this Pull Request
No unnecessary lang variable any,ore

### Documentation Changes Required
None

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on e4ac5c347a823ce1f97dc3215691c56b6a2bee0a<br /><br />quick test on a mono-lingual site only<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38299">issues.joomla.org/tracker/joomla-cms/38299</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on e4ac5c347a823ce1f97dc3215691c56b6a2bee0a<br /><br />Tested on multilingual site<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38299">issues.joomla.org/tracker/joomla-cms/38299</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38299">issues.joomla.org/tracker/joomla-cms/38299</a>.</sub>

**Comment by roland-d** [comment]
Thank you

**Pull request merged**
