### PR TITLE
Use application API for Smart Search suggestions

### PR DESCRIPTION
**Pull request by mbabker**
This PR updates the Smart Search suggestions controller methods to use the application API for setting the document MIME type and sending the response headers instead of the direct PHP method used before.
### Testing Instructions

Set up Smart Search, pre- and post- patch the suggestions should work correctly.

### CODE REVIEW

**Comment by wilsonge** [comment]
I have tested this item :white_check_mark: successfully on 42c4d0adcc169433d70a4dd5ea423fd87198dda4<br /><br />Successfully got the right data and as a bonus checked in chrome the correct mime type was being returned<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8046">issues.joomla.org/joomla-cms/8046</a>.</sub>

**Comment by oorzaak** [comment]
I have tested this item successfully during pbf at JUG030, Utrecht.

- Pre patch I've created the smart search index and created a smart search menu item. When using the search input field the suggestions were working correctly.
- Then I've installed the patch, emptied Joomla cache and browser cache (also made a second test using a different browser). Search field suggestions were working correctly.
- After that I removed indexed items form smart search index and re-indexed. Emptied Joomla cache and browser cache again.
Search field suggestions were working correctly. 

Frits<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8046">issues.joomla.org/joomla-cms/8046</a>.</sub>

**Comment by oorzaak** [comment]
I have tested this item :white_check_mark: successfully on 42c4d0adcc169433d70a4dd5ea423fd87198dda4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8046">issues.joomla.org/joomla-cms/8046</a>.</sub>

**Comment by wilsonge** [comment]
Merged - thanks :)

**Pull request merged**
