### PR TITLE
Site language now gets fetched on login

### PR DESCRIPTION
**Pull request by jjdelvalle**
This PR solves the issue at #4483 

It fetches the application language tag and ensures it's not empty or null before defaulting to the site's default language.

### CODE REVIEW

**Comment by clinchergt** [comment]
@infograf768 and @joomdonation: could I get you guys to test this again? I'm trying to get my PRs closed/merged after all this time. Sorry for taking so long to update them.

Thanks!

**Comment by infograf768** [comment]
We can't test this anymore as there were extensive changes in languagefilter.
I suggest you test again for the issue using staging.

In any case, the present code redirects the user to the site default language if no specific site language is set for the user who logins or the user site language does not exist anymore (When Automatic Change is set to Yes).

Solving the issue by always redirecting to the language in use would kill the Automatic Change functionality.

**Comment by infograf768** [comment]
Set to "closed" on behalf of @infograf768 by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4797">issues.joomla.org/joomla-cms/4797</a>

**Comment by infograf768** [comment]
Folks, I am closing this one as it is anyway obsolete and we have a working patch here:
https://github.com/joomla/joomla-cms/pull/6915

can be tested also with a single article menu item loading a registered article as https://github.com/joomla/joomla-cms/pull/6908 has been merged,

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4797">issues.joomla.org/joomla-cms/4797</a>.</sub>

**Pull request closed without merging**
