### PR TITLE
The Modal Category Field doesn't work if edit=false (Ref #8180)

### PR DESCRIPTION
**Pull request by eshiol**
#### Steps to reproduce the issue

Create a form with a modal category field

To test the issue you can change the file
administrator/components/com_content/models/forms/article.xml
45:         <field name="catid" type="categoryedit"

45:     <field name="catid" type="modal_category"
and open an article
cattura2
#### Expected result

When you click on the select button the modal popup should open
#### Actual result

When you click on the select button nothing happens

see

### CODE REVIEW

**Comment by zero-24** [comment]
Thanks @eshiol i have just copied your instructions in here. Thanks.

**Comment by zero-24** [comment]
I have just send you a codestyle fix for the both whitespaces. Thanks.

**Comment by zero-24** [comment]
@eshiol I can not exactly follow your issue.

I have just add your code but it end up with see:
your_code

This is with and without the patch and i used this code:

```
<field name="category123" type="modal_category" label="category123" labelclass="control-label" edit="false" addfieldpath="/administrator/components/com_contact/models/fields" />
```

**Comment by eshiol** [comment]
Sorry, my fault.
<field name="category" type="modal_category" label="category" labelclass="control-label" edit="false" />
cattura

**Comment by zero-24** [comment]
hmm i still go the same view as above and no select box?

**Comment by eshiol** [comment]
to test the issue you can change the file
administrator/components/com_content/models/forms/article.xml
45: 		<field name="catid" type="categoryedit"

45:		<field name="catid" type="modal_category"
and open an article
cattura2

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on f0212806e45e1adbec2b9e1b51e4ad0f4777d493<br /><br />Thanks @eshiol I go it. (I will update the instructions in the first post)

Works good now on my end.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8185">issues.joomla.org/joomla-cms/8185</a>.</sub>

**Comment by zero-24** [comment]
Just my CS Pull needs now to be merged that Travis will be happy with your code ;)

**Comment by n9iels** [comment]
I have tested this item :white_check_mark: successfully on 978e5135b8d1672c3be44379b8e47427436d5767<br /><br />Works fine for me!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8185">issues.joomla.org/joomla-cms/8185</a>.</sub>

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on 978e5135b8d1672c3be44379b8e47427436d5767<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8185">issues.joomla.org/joomla-cms/8185</a>.</sub>

**Comment by zero-24** [comment]
RTC thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8185">issues.joomla.org/joomla-cms/8185</a>.</sub>

**Pull request merged**
