### PR TITLE
[com_banners] Avoid running the query when no keywords are provided

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

When filtering by keywords but no keywords are provided `com_banners` runs a query that always returns no results. We can avoid running such query.

This also fixes query error on PostgreSQL and MS SQL described in #26789.

### Testing Instructions

Create some banners.
Publish a banner module.
Enable filtering by keywords in module.
Inspect the module when meta keywords are set and not set.

### Expected result

When keywords are set, banners appear like before.
When keywords are not set, banners don't appear (like before) and there's 1 query less.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on df78b3760770dc5cb3dee3b9dc989464a6ed900b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26875">issues.joomla.org/tracker/joomla-cms/26875</a>.</sub>

**Comment by alikon** [comment]
@SharkyKZ i've submitted  mine #26791 to you branch https://github.com/SharkyKZ/joomla-cms/pull/7  should be better to have 1 pr touching the same file, without don't work on postgresql/ms sql for the regexp issue

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on e2b9ec9e00b3b62c46c68b7e2597763be2a02d40<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26875">issues.joomla.org/tracker/joomla-cms/26875</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on e2b9ec9e00b3b62c46c68b7e2597763be2a02d40<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26875">issues.joomla.org/tracker/joomla-cms/26875</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26875">issues.joomla.org/tracker/joomla-cms/26875</a>.</sub>

**Comment by HLeithner** [comment]
Thanks for the optimization.

**Pull request merged**
