### PR TITLE
Use IpHelper to get IP in Logger

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue #25518 .

### Summary of Changes

Use IpHelper to get IP in `Joomla\CMS\Log\Logger\FormattedtextLogger`.

### Testing Instructions

Install Joomla behind a reverse proxy which provides both remote_addr and http_x_forwarded_for headers.
Perform a login failure on /administrator
Check the /logs/error.php log

### Expected result

To see the ip address from http_x_forwarded_for reported as the offending IP address.

### Actual result

To see the ip address from remote_addr reported as the offending IP address.

### Documentation Changes Required

No.

### CODE REVIEW

**Review by wilsonge — APPROVED** [review]

**Comment by SharkyKZ** [comment]
Failing tests related to framework. Submitted PR there https://github.com/joomla-framework/utilities/pull/23.

**Comment by richard67** [comment]
I can't test because I don't have a reverse proxy.

@twrhills As you had the issue handled by this PR, could you test?

**Comment by twrhills** [comment]
> I can't test because I don't have a reverse proxy.
> 
> @twrhills As you had the issue handled by this PR, could you test?

@richard67 I have tested this and it is the correct solution for my case. I am unfamiliar with github so if you need me to confirm in another way I would be grateful if you can link documentation / instructions.

**Comment by Quy** [comment]
Thank you for testing! 

Please mark your test here: https://issues.joomla.org/tracker/joomla-cms/25520

**Comment by richard67** [comment]
@twrhills Follow the link posted in comment before by Quy, then click the "Test this" button at the top left corner above the description, then in the "Submit test result" select your test result with the check box, then click "Submit test result" button below the text field for the (otional) comment.

**Comment by twrhills** [comment]
I have tested this item :white_check_mark: successfully on 6ed695e95a1b95e48d99ed7013ec74f146f819b0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25520">issues.joomla.org/tracker/joomla-cms/25520</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 6ed695e95a1b95e48d99ed7013ec74f146f819b0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25520">issues.joomla.org/tracker/joomla-cms/25520</a>.</sub>

**Comment by ghost** [comment]
Status "Ready To Commit".

**Comment by HLeithner** [comment]
@SharkyKZ can you please fix the error messages found by travis?

> 1) JLogLoggerFormattedTextTest::testAddEntry
Undefined index: REMOTE_ADDR
/home/travis/build/joomla/joomla-cms/tests/unit/core/helper.php:55
/home/travis/build/joomla/joomla-cms/libraries/vendor/joomla/utilities/src/IpHelper.php:488
/home/travis/build/joomla/joomla-cms/libraries/vendor/joomla/utilities/src/IpHelper.php:440
/home/travis/build/joomla/joomla-cms/libraries/vendor/joomla/utilities/src/IpHelper.php:57
/home/travis/build/joomla/joomla-cms/libraries/src/Log/Logger/FormattedtextLogger.php:195
/home/travis/build/joomla/joomla-cms/libraries/src/Log/Logger/FormattedtextLogger.php:171
/home/travis/build/joomla/joomla-cms/tests/unit/suites/libraries/joomla/log/loggers/JLogLoggerFormattedTextTest.php:174
> 2) JLogLoggerFormattedTextTest::testDeferWritingEntry
Undefined index: REMOTE_ADDR
/home/travis/build/joomla/joomla-cms/tests/unit/core/helper.php:55
/home/travis/build/joomla/joomla-cms/libraries/vendor/joomla/utilities/src/IpHelper.php:488
/home/travis/build/joomla/joomla-cms/libraries/vendor/joomla/utilities/src/IpHelper.php:440
/home/travis/build/joomla/joomla-cms/libraries/vendor/joomla/utilities/src/IpHelper.php:57
/home/travis/build/joomla/joomla-cms/libraries/src/Log/Logger/FormattedtextLogger.php:195
/home/travis/build/joomla/joomla-cms/libraries/src/Log/Logger/FormattedtextLogger.php:139
/home/travis/build/joomla/joomla-cms/tests/unit/suites/libraries/joomla/log/loggers/JLogLoggerFormattedTextTest.php:237
> 3) JLogLoggerW3CTest::testAddEntry
Undefined index: REMOTE_ADDR
/home/travis/build/joomla/joomla-cms/tests/unit/core/helper.php:55
/home/travis/build/joomla/joomla-cms/libraries/vendor/joomla/utilities/src/IpHelper.php:488
/home/travis/build/joomla/joomla-cms/libraries/vendor/joomla/utilities/src/IpHelper.php:440
/home/travis/build/joomla/joomla-cms/libraries/vendor/joomla/utilities/src/IpHelper.php:57
/home/travis/build/joomla/joomla-cms/libraries/src/Log/Logger/FormattedtextLogger.php:195
/home/travis/build/joomla/joomla-cms/libraries/src/Log/Logger/FormattedtextLogger.php:171
/home/travis/build/joomla/joomla-cms/tests/unit/suites/libraries/joomla/log/loggers/JLogLoggerW3CTest.php:37

**Comment by SharkyKZ** [comment]
@HLeithner need to update Framework's Utilities package to fix the notice. Submitted a separate PR #25601.

**Comment by HLeithner** [comment]
@SharkyKZ thx for the info so this is RTC when the composer update is merged.

**Comment by HLeithner** [comment]
I created pr #26000 please test.

**Comment by richard67** [comment]
@HLeithner Ist this a duplicate then to @SharkyKZ 's PR #25601 ?

**Comment by SharkyKZ** [comment]
@richard67 almost. But just realized my PR reverts some changes to Composer (I was using older version). So I'll close it.

**Comment by HLeithner** [comment]
@SharkyKZ IpHelper::getIp(); seams to behave different then the current code in the testing. Could you please have a look?

**Comment by SharkyKZ** [comment]
@HLeithner should I change the PR so it does not break tests or update tests?

**Comment by mbabker** [comment]
The tests should be updated.  I’m going to take a wild guess that superglobal values aren’t being properly set and reset.

**Comment by SharkyKZ** [comment]
There's also discrepancy between empty IP values. Before it was `null`, now it's an empty string 😕

**Comment by HLeithner** [comment]
The w3c logger returned - with the old code now it shows an empty stringand I think thats wrong. So the null seams to be right.

**Comment by SharkyKZ** [comment]
Added empty string check in the logger.

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
