### PR TITLE
[com_users] users view: corrects some minor bugs

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
Pull Request for New Issue.
#### Summary of Changes

Simple PR to solve minor issues.
- Corrects the default ordering in ordering list select.
- Corrects the footer colspan
- Minor code style changes
- Minor code improvements
- Removes the usage of deprecated JArrayHelper
- Improves the tablet view of com_users users view.

image
#### Testing Instructions
1. Use latest staging
2. Log out, login again and go directly to Users -> Manage. Check the value in the ordering column, it will "Sort table by:"
3. Apply patch
4. Repeat step 2. (check the value in the ordering column, it will be "Name ascending" as it should.
5. Perform some filtering/ordering tests.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on de75ec4cc588fe44004ee9f99cfcb27477c515f6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10002">issues.joomla.org/joomla-cms/10002</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on de75ec4cc588fe44004ee9f99cfcb27477c515f6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10002">issues.joomla.org/joomla-cms/10002</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@brianteeman @richard67 thanks for testing.

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10002">issues.joomla.org/joomla-cms/10002</a>.</sub>

**Pull request merged**
