### PR TITLE
[5.1] Dark Mode final Version

### PR DESCRIPTION
**Pull request by coolcat-creations**
This is a follow up of #42757 and #42010 for Joomla 5.1

### Summary of Changes
Dark mode modifications and improvements

### Testing Instructions
Turn on dark mode in your browser or O/S

### Actual result BEFORE applying this Pull Request
old dark mode

### Expected result AFTER applying this Pull Request
improved dark mode

### CODE REVIEW

**Comment by brianteeman** [comment]
https://github.com/joomla/joomla-cms/pull/42757#issuecomment-1976522934

**Comment by coolcat-creations** [comment]
@brianteeman thats very odd, for me it looks like this:

grafik

**Comment by brianteeman** [comment]
sorry for the noise that was a cacje issue

**Comment by coolcat-creations** [comment]
No Problem, thank you for testing!

**Comment by brianteeman** [comment]
placeholder font size and weight - changed?

before this pr
image

with this pr
image

**Comment by Quy** [comment]
Go to System > Administrator Templates
Click Atum Details and Files.
Click Create Child Template, Manage Folders, and New File buttons.
See buttons in white.

**Comment by brianteeman** [comment]
Multilingual Associations in dark mode is not showing tinymce toolbar in dark

image

**Comment by brianteeman** [comment]
RTL is fubar

Before PR
image

With PR
image

Before PR
image

With PR
image

**Comment by brianteeman** [comment]
at a guess I would think its related to usign the wrong select svg

**Comment by Quy** [comment]
42986-badge

**Comment by coolcat-creations** [comment]
@brianteeman I fixed the issue with the select

**Comment by coolcat-creations** [comment]
All new issues fixed. Only the editor issue I am not sure if its template related or plugin related?

**Comment by brianteeman** [comment]
from what I can see the editor is correct in dark mode in all the other instances

**Comment by coolcat-creations** [comment]
I really dont know what causes the editor issue in multilang and what the "skin.css" is controlled by

**Comment by brianteeman** [comment]
on care duty right now. will take another look tonight

**Comment by Quy** [comment]
Create a `GET Request` scheduled task.
Click `Run Test` button.

42986-scheduled-task-output

**Comment by korenevskiy** [comment]
> Sorry that was a mistake in my text, i meant link color on dark and white on link color. Cassiopeia is totally unrelated to the backend template.

I do not understand why there is a link in the dark theme in 2 varieties. I probably don't understand what this is about. But I wanted to suggest just changing the main color of the links to a lighter one, as I invented here https://github.com/joomla/joomla-cms/pull/42757?notification_referrer_id=NT_kwDOAGlDKrI5MzM1OTMyNzE2OjY4OTg0NzQ#issuecomment-1971998036

If this is not possible. I will ask you to add this to the future PR plan according to the template.

**Comment by coolcat-creations** [comment]
> > Sorry that was a mistake in my text, i meant link color on dark and white on link color. Cassiopeia is totally unrelated to the backend template.
> 
> I do not understand why there is a link in the dark theme in 2 varieties. I probably don't understand what this is about. But I wanted to suggest just changing the main color of the links to a lighter one, as I invented here #42757
> 
> If this is not possible. I will ask you to add this to the future PR plan according to the template.

already changed to your suggestion yesterday

**Comment by coolcat-creations** [comment]
> Create a `GET Request` scheduled task. Click `Run Test` button.
> 
> 42986-scheduled-task-output

Can you direct me to what to input into the get request? thanks

**Comment by Quy** [comment]
Install a language.
Change the loading background color.

42986-loading-bg

**Comment by coolcat-creations** [comment]
> Install a language. Change the loading background color.
> 
> 42986-loading-bg

Thats unfortunately a no fix for this PR - seems thats more complicated

**Comment by coolcat-creations** [comment]
@Quy can you open a separate issue about the loader? It's a whole separate "project" and not possible to take it into the scope of this PR

**Comment by brianteeman** [comment]
## LTR
image

## RTL
image

Same issue repeated in dark mode

**Comment by brianteeman** [comment]
## LTR
image

## RTL
image


Same issue repeated in dark mode

**Comment by Quy** [comment]
Go to Media Manager.
Click `Create New Folder` button.
Click `Rename`.
Both have white buttons.

**Comment by Quy** [comment]
https://github.com/joomla/joomla-cms/issues/42506

Install the plugin.
Go to Extensions.
Find `switch`.
Click a button under Version.

[pkg_switcheditor_2-2.2.4.zip](https://github.com/joomla/joomla-cms/files/14551353/pkg_switcheditor_2-2.2.4.zip)

**Comment by brianteeman** [comment]
image

image

**Comment by coolcat-creations** [comment]
> ## LTR
> 
> image
> ## RTL
> 
> image
> 
> Same issue repeated in dark mode

fixed for darkmode, lightmode needs to go into separate PR

**Comment by LadySolveig** [comment]
Thank you very much for the great work and your commitment @coolcat-creations and @MacJoom  ! 💟  🚀 
Many thanks also to all those who participated in testing and provided feedback - great to see this wonderful collaboration.

**Comment by Kostelano** [comment]
System -->  Guided Tours, when hovering the cursor

Screenshot_1

**Comment by coolcat-creations** [comment]
@Kostelano thank you for the finding. As this is merged, can you please open a new issue ?

**Pull request merged**
