### PR TITLE
[4.0] Use layout attribute to set field layout

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Use layout attribute to set layout in `Joomla\CMS\Form\Field\RadioField`.

### Testing Instructions

View some forms contain "switcher" fields.

### Expected result

Works like before.

### Documentation Changes Required

Form fields using `switcher` class need to be updated to use `joomla.form.field.radio.switcher` layout instead.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :red_circle: unsuccessfully on 3fbc5c367874d6dd8931f05fbf91b69a3b35e157<br /><br />The label is now doubled
The accessibility is now brokenn<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26214">issues.joomla.org/tracker/joomla-cms/26214</a>.</sub>

**Comment by SharkyKZ** [comment]
In which form is that?

**Comment by brianteeman** [comment]
every form

**Comment by SharkyKZ** [comment]
I can't reproduce your results.

**Comment by brianteeman** [comment]
I tested it twice

**Comment by zero-24** [comment]
hmm looks good to me.

without the patch
image

with the patch
image

How can we reproduce the issue you mention? Or I'm missing something here?

**Comment by brianteeman** [comment]
all i did was apply the PR with patchtester 
## after
image

## before
image

**Comment by zero-24** [comment]
hmm i have now looked into the screenshots more deeply. I have marked the differences, i found on mine. Does the additional `for="jform_link_titles"` break accessibility? Maybe I just not getting what the issue is as it seams to me that the label is there before and after two times, on both my and your screenshots.

after
image


before
image

**Comment by SharkyKZ** [comment]
I'll revert the related change.

**Comment by SharkyKZ** [comment]
We can't even use `hiddenLabel` attribute to actually hide labels anymore 🤷‍♂ .

**Comment by SharkyKZ** [comment]
Test again please.

**Comment by brianteeman** [comment]
Tried again with a pure git checkout instead of patchtester - dont get the double anymore but there is an empty div now

### after
image

### before
image

Otherwise its ok

**Comment by SharkyKZ** [comment]
Out of scope of this PR. Can happen with other fields because main layout doesn't check for empty input/label.

**Comment by brianteeman** [comment]
As its a change in behaviour created by this PR I dont see how its out of scope

**Comment by SharkyKZ** [comment]
This behavior is not specific to this field. Any field that returns an empty string in `getLabel()` or `getInput()` methods is going to cause empty divs to be rendered , e.g.

```
<field
	name="whatever"
	type="note"
/>
```
Outputs:

```
<div class="control-group">
	<div class="control-label"></div>
	<div class="controls">
			</div>
	</div>
```
If it was my call, I'd just drop all these workarounds and have #25085 reverted. It was done with good intentions but with wrong assumptions that the labels can only be hidden for cosmetic purposes.

**Comment by Quy** [comment]
Please fix conflicts.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on bd7ff1b1c50cd3b374b7dd3bad4e17d724e7e1cd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26214">issues.joomla.org/tracker/joomla-cms/26214</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on bd7ff1b1c50cd3b374b7dd3bad4e17d724e7e1cd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26214">issues.joomla.org/tracker/joomla-cms/26214</a>.</sub>

**Comment by jwaisner** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26214">issues.joomla.org/tracker/joomla-cms/26214</a>.</sub>

**Pull request merged**
