### PR TITLE
[4.0] Template Preview link new window

### PR DESCRIPTION
**Pull request by brianteeman**
Similar to other PR this adds a title to the link so that the user is informed that it opens in a new window.

Code review or just hover over the link

image

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 753f9c446c295e7f0cebe4a2736b8a7858de6fa8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28049">issues.joomla.org/tracker/joomla-cms/28049</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 753f9c446c295e7f0cebe4a2736b8a7858de6fa8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28049">issues.joomla.org/tracker/joomla-cms/28049</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28049">issues.joomla.org/tracker/joomla-cms/28049</a>.</sub>

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
