### PR TITLE
Install from web - rtl fix

### PR DESCRIPTION
**Pull request by brianteeman**
### Summary of Changes
Changes the css to use logical properties so that the sidebar is indented the same in RTL as it is in LTR

### Testing Instructions
This is a css change so either `run npm build:css` or use a [re-built package

### Before
LTR
image

RTL
image

### After
LTR
image

RTL
image

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on a95ec553e741392c0a67653713254c9ad1b32a3b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38349">issues.joomla.org/tracker/joomla-cms/38349</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on a95ec553e741392c0a67653713254c9ad1b32a3b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38349">issues.joomla.org/tracker/joomla-cms/38349</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38349">issues.joomla.org/tracker/joomla-cms/38349</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
