### PR TITLE
Redirect batch

### PR DESCRIPTION
**Pull request by brianteeman**
The redirect component has a batch function to allow you to mass insert a set of urls. However this uses the common batch.php layout which has some javascript to ensure that you have selected one or more items to batch edit first. 

As the batch functionality in com_redirect works completely differently to all other batch buttons and does not require (or need) you to select an existing item first it was not working correctly.

To resolve this I created a new layout "batchredirect" which doesnt have the javascript check.
### Test instructions

Go to com_redirect and click the batch button on the toolbar - you will get a message about selecting an item first
Select an item and click the batch button. The modal will open and you can type new links on each line and when you click process you will see that new links have been created without any reference to the item you selected.

Apply the patch and you can click the batch button as intended without preselecting an irrelevant link first
Also check that this works when you do not have any redirects created.

### CODE REVIEW

**Comment by brianteeman** [comment]
Note: it might be better to rename this button from batch to "bulk import"<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9858">issues.joomla.org/joomla-cms/9858</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on e4d0d6374e65101ee00be39bd733d392b75e1e21<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9858">issues.joomla.org/joomla-cms/9858</a>.</sub>

**Comment by roland-d** [comment]
@brianteeman Will you add a changed name for the button into this PR or that is for another PR?

**Comment by MATsxm** [comment]
I have tested this item :white_check_mark: successfully on e4d0d6374e65101ee00be39bd733d392b75e1e21<br /><br />Successful (still the name issue remains) - thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9858">issues.joomla.org/joomla-cms/9858</a>.</sub>

**Comment by brianteeman** [comment]
RTC - thanks


@roland-d no i will not be creating a PR to change the name of the button. Got too much abuse last time not going to do that again<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9858">issues.joomla.org/joomla-cms/9858</a>.</sub>

**Comment by wilsonge** [comment]
@brianteeman can we make this a component specific layout rather than a global one please?

**Comment by brianteeman** [comment]
Do not test yet

**Comment by brianteeman** [comment]
@wilsonge - tried to do what you asked but something isnt quite right. i
assumed i missed something obvious

On 14 April 2016 at 20:40, Joomla! CMS Bot <notifications@github.com> wrote:

> This PR has received new commits.
>
> *CC:* @franz-wohlkoenig <https://github.com/franz-wohlkoenig>, @MATsxm
> <https://github.com/MATsxm>
> ------------------------------
> This comment was created with the J!Tracker Application
> <https://github.com/joomla/jissues> at issues.joomla.org/joomla-cms/9858
> <https://issues.joomla.org/tracker/joomla-cms/9858>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/9858#issuecomment-210116253>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
Removed RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9858">issues.joomla.org/joomla-cms/9858</a>.</sub>

**Comment by brianteeman** [comment]
There is a problem that the toolbar will not do anything if you dont have any existing redirects. I cant see where this problem lies<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9858">issues.joomla.org/joomla-cms/9858</a>.</sub>

**Comment by brianteeman** [comment]
Fixed the bug it is ready for testing again<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9858">issues.joomla.org/joomla-cms/9858</a>.</sub>

**Comment by mikeveeckmans** [comment]
I have tested this item :white_check_mark: successfully on d5a9c917cca5ada3152f0c8e6e373065faf51e25<br /><br />TEST OK<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9858">issues.joomla.org/joomla-cms/9858</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on d5a9c917cca5ada3152f0c8e6e373065faf51e25<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9858">issues.joomla.org/joomla-cms/9858</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9858">issues.joomla.org/joomla-cms/9858</a>.</sub>

**Comment by MATsxm** [comment]
I have tested this item :white_check_mark: successfully on d5a9c917cca5ada3152f0c8e6e373065faf51e25<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9858">issues.joomla.org/joomla-cms/9858</a>.</sub>

**Comment by Luchen6** [comment]
I have tested this item :red_circle: unsuccessfully on d5a9c917cca5ada3152f0c8e6e373065faf51e25<br /><br />The Redirect Plugin is enabled. The option 'Collect URLs' is enabled. 
.htaccess should be used.

Batch process can be applied with and without any redirect records.

No pre-selection is required.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9858">issues.joomla.org/joomla-cms/9858</a>.</sub>

**Comment by Luchen6** [comment]
Sorry, I ment Succesfull test<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9858">issues.joomla.org/joomla-cms/9858</a>.</sub>

**Comment by BurtNL** [comment]
I have tested this item :white_check_mark: successfully on d5a9c917cca5ada3152f0c8e6e373065faf51e25<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9858">issues.joomla.org/joomla-cms/9858</a>.</sub>

**Pull request merged**
