### PR TITLE
Regression: module edit pre-select position field does not check for existing module [fix: #7056]

### PR DESCRIPTION
**Pull request by infograf768**
See
https://github.com/joomla/joomla-cms/issues/7056

When editing an existing module, the fields are set back to Null.
When using filters and the module is new the fields are filled by the filters settings but, once the module is saved once, go back to null.

Checking for an existing id was missing in https://github.com/joomla/joomla-cms/pull/6977

### CODE REVIEW

**Comment by sovainfo** [comment]
@test ok
While posting discovered you beat me to it.
Tested creating and modifying a module both in empty and filtered list. All tests passed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7058">issues.joomla.org/joomla-cms/7058</a>.</sub>

**Comment by Bakual** [comment]
Just wondering if a boolean check wouldn't be enough. So insteald of 
`if ($data->id == null)` use `if (!$data->id)`.
It would also catch cases where the ID would be `0` or `false`, which is less strict than `== null` but serves the same purpose.

**Comment by infograf768** [comment]
Used boolean. I guess it is RTC

**Comment by Bakual** [comment]
Looks fine, yes. Thanks!

**Pull request merged**
