### PR TITLE
[4.0] Removed language strings in reCaptcha plugins

### PR DESCRIPTION
**Pull request by Kostelano**
Pull Request for Issue # .

### Summary of Changes
One of the recaptcha plugins has descriptions for the KEY parameters. In the other, no. A light PR removes unnecessary language lines, since everything is clear even without them.

**BEFORE PR**

Screenshot_2

Screenshot_1

### CODE REVIEW

**Comment by Quy** [comment]
Maybe remove `The tabindex of the challenge. `.

**Comment by Kostelano** [comment]
@Quy DONE.

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 555a64134ee1dc39dbd656124f4cd7044b99421f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33645">issues.joomla.org/tracker/joomla-cms/33645</a>.</sub>

**Comment by ceford** [comment]
I have reservations about removing descriptions - they are useful for complete novices and if they are not there then there can be no local language overrides. It would be better to put the strings into the reCaptacha form rather than remove them from Invisible reCaptacha. Just my opinion.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33645">issues.joomla.org/tracker/joomla-cms/33645</a>.</sub>

**Comment by Kostelano** [comment]
@ceford I agree that hints are needed for beginners, but not in such obvious things. Otherwise, we need to return the huge mass of descriptions that were deleted earlier.

In the end, the mass of parameters of the entire Joomla is very NOT clear for beginners. All sorts of HTTP headers, progressive caches, load balancers, etc. :) So, whether you like it or not, you sometimes have to go to Google.

**Pull request closed without merging**
