### PR TITLE
Update joomla/image dependency

### PR DESCRIPTION
**Pull request by nibra**
Pull Request for Issue #31552 .

### Summary of Changes

Bump `joomla/image` from version 1.5.0 to 1.5.1

Files in `libraries/src/Image` don't need to be changed, since they inherit from the Framework package.

### CODE REVIEW

**Comment by xillibit** [comment]
You had forgot something in this PR https://github.com/joomla/joomla-cms/pull/31513 now composer update joomla/archive from 1.1.7 to 1.1.8 when i tried to just update the joomla/image package, but the 1.1.8 is already installed....

**Comment by 810** [comment]
I have tested this item :white_check_mark: successfully on 4152d207fe25a5e59ac9a4a2d41864e7e5469981<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31663">issues.joomla.org/tracker/joomla-cms/31663</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 4152d207fe25a5e59ac9a4a2d41864e7e5469981<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31663">issues.joomla.org/tracker/joomla-cms/31663</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
