### PR TITLE
Use renderField frontend com_config modules view

### PR DESCRIPTION
**Pull request by degobbis**
### Summary of Changes
Use renderField frontend com_contig modules view

### Testing Instructions
- go to the com_config modules frontend view (edit module)
- confirm all is working
- apply this patch
- confirm it is still working

#### Extra test
- repeat the steps from above on a multilangual site

### Expected result
We use renderField and not hardcode the field generation

### Actual result
We use a hardcoded field generation

### Documentation Changes Required
none

### CODE REVIEW

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on 49d56e5c5be9a70e3728ba91d2176b4642f2a91b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28817">issues.joomla.org/tracker/joomla-cms/28817</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 49d56e5c5be9a70e3728ba91d2176b4642f2a91b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28817">issues.joomla.org/tracker/joomla-cms/28817</a>.</sub>

**Comment by jwaisner** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28817">issues.joomla.org/tracker/joomla-cms/28817</a>.</sub>

**Comment by infograf768** [comment]
tks

**Comment by infograf768** [comment]
While testing/looking at this I found a potential problem with menu module edit in frontend:
We should normally not be able to modify the Published status if it contains the home page (have to check if the issue is only for multilingual sites) the problem being that one can have multiple menu modules using the same menutype.

**Pull request merged**
