### PR TITLE
[5.2][Events] Use event classes for Extension plugins

### PR DESCRIPTION
**Pull request by Fedik**
### Summary of Changes

Update `extension` and `installer` plugins to use `SubscriberInterface` event classes.

### Testing Instructions

Test that extension installation works as before.
Joomla update also works as before.

### Actual result BEFORE applying this Pull Request
Works

### Expected result AFTER applying this Pull Request
Works

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed
- [x] Pull Request link for manual.joomla.org: https://github.com/joomla/Manual/pull/177
- [ ] No documentation changes for manual.joomla.org needed

___

### **PR Type**
Enhancement

___

### **Description**
- Updated `extension` and `installer` plugins to use `SubscriberInterface` event classes.
- Introduced `AbstractJoomlaUpdateEvent` class and its concrete implementations `BeforeJoomlaUpdateEvent` and `AfterJoomlaUpdateEvent`.
- Modified Joomla update process to dispatch new event classes.
- Implemented `SubscriberInterface` for various extension plugins and updated their methods to use event classes.

___

### **Changes walkthrough** 📝
<table><thead><tr><th></th><th align="left">Relevant files</th></tr></thead><tbody><tr><td><strong>Enhancement
</strong></td><td><details><summary>9 files</summary><table>
<tr>
  <td>
    <details>
      <summary><strong>UpdateModel.php</strong><dd><code>Use event classes for Joomla update process</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
administrator/components/com_joomlaupdate/src/Model/UpdateModel.php

<li>Added dispatching of <code>BeforeJoomlaUpdateEvent</code> and <br><code>AfterJoomlaUpdateEvent</code> instead of triggering events directly.<br> <li> Included new event classes for Joomla update process.<br>

</details>
    

  </td>
  <td><a href="https://github.com/joomla/joomla-cms/pull/43617/files#diff-617530abeea53181b5e5f641ba3906dcbf758238861e8a5281422722533d8532">+8/-3</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>CoreEventAware.php</strong><dd><code>Map Joomla update events to core events</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
libraries/src/Event/CoreEventAware.php

<li>Added <code>onJoomlaBeforeUpdate</code> and <code>onJoomlaAfterUpdate</code> to the core event <br>mapping.<br>

</details>
    

  </td>
  <td><a href="https://github.com/joomla/joomla-cms/pull/43617/files#diff-f12a60e571bc8a2086bdb9b5b8849e0fbb07d92bbd4c8bf29ff8e28813e920bd">+2/-0</a>&nbsp; &nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>AbstractJoomlaUpdateEvent.php</strong><dd><code>Introduce abstract class for Joomla update events</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
libraries/src/Event/Extension/AbstractJoomlaUpdateEvent.php

<li>Introduced abstract class <code>AbstractJoomlaUpdateEvent</code> for Joomla update <br>events.<br>

</details>
    

  </td>
  <td><a href="https://github.com/joomla/joomla-cms/pull/43617/files#diff-d88052ca3cdabfaf529b3fff7125ae82431127bbde0de98003fd725a4e990ef6">+55/-0</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>AfterJoomlaUpdateEvent.php</strong><dd><code>Add AfterJoomlaUpdateEvent class</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
libraries/src/Event/Extension/AfterJoomlaUpdateEvent.php

<li>Added <code>AfterJoomlaUpdateEvent</code> class extending <br><code>AbstractJoomlaUpdateEvent</code>.<br>

</details>
    

  </td>
  <td><a href="https://github.com/joomla/joomla-cms/pull/43617/files#diff-d82126ad525c59a45d3eefa77fed4714eb765566c4c62384cea61c938d0d668b">+58/-0</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>BeforeJoomlaUpdateEvent.php</strong><dd><code>Add BeforeJoomlaUpdateEvent class</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
libraries/src/Event/Extension/BeforeJoomlaUpdateEvent.php

<li>Added <code>BeforeJoomlaUpdateEvent</code> class extending <br><code>AbstractJoomlaUpdateEvent</code>.<br>

</details>
    

  </td>
  <td><a href="https://github.com/joomla/joomla-cms/pull/43617/files#diff-bc61fe30c2ae8adaa9b726a146f8d01c9aa004fb56110c504287e3455ccaf43c">+23/-0</a>&nbsp; &nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>Finder.php</strong><dd><code>Implement SubscriberInterface for Finder plugin</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
plugins/extension/finder/src/Extension/Finder.php

<li>Implemented <code>SubscriberInterface</code> for the Finder extension plugin.<br> <li> Updated methods to use event classes.<br>

</details>
    

  </td>
  <td><a href="https://github.com/joomla/joomla-cms/pull/43617/files#diff-8ba98b1a62025f4a9e03ecba913981cf887fe91db27bf20c27e9000b25e13cc6">+35/-13</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>Joomla.php</strong><dd><code>Implement SubscriberInterface for Joomla plugin</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
plugins/extension/joomla/src/Extension/Joomla.php

<li>Implemented <code>SubscriberInterface</code> for the Joomla extension plugin.<br> <li> Updated methods to use event classes.<br>

</details>
    

  </td>
  <td><a href="https://github.com/joomla/joomla-cms/pull/43617/files#diff-5fb32f6d0fb4d77238448a24e7222ee8c7c9f3e3254ea56507c7deb6ec279355">+36/-13</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>NamespaceMap.php</strong><dd><code>Implement SubscriberInterface for NamespaceMap plugin</code>&nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
plugins/extension/namespacemap/src/Extension/NamespaceMap.php

<li>Implemented <code>SubscriberInterface</code> for the NamespaceMap extension plugin.<br> <li> Updated methods to use event classes.<br>

</details>
    

  </td>
  <td><a href="https://github.com/joomla/joomla-cms/pull/43617/files#diff-15b32bb4e9bfae034f0ee24954218e1099c5d05c6fe870254c5d5e80cbf5eb3e">+30/-15</a>&nbsp; </td>

</tr>                    

<tr>
  <td>
    <details>
      <summary><strong>Override.php</strong><dd><code>Implement SubscriberInterface for Override plugin</code>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; </dd></summary>
<hr>
      
plugins/installer/override/src/Extension/Override.php

<li>Implemented <code>SubscriberInterface</code> for the Override extension plugin.<br> <li> Added event subscription methods.<br>

</details>
    

  </td>
  <td><a href="https://github.com/joomla/joomla-cms/pull/43617/files#diff-d9e886d921f5cac68a5085e5edd9d9cbfd4e77e42a1bf6114f2ccdea91d5849a">+21/-1</a>&nbsp; &nbsp; </td>

</tr>                    
</table></details></td></tr></tr></tbody></table>

___

> 💡 **PR-Agent usage**:
>Comment `/help` on the PR to get a list of all available PR-Agent tools and their descriptions

### CODE REVIEW

**Comment by exlemor** [comment]
I have tested this item :white_check_mark: successfully on 24617139a33b6f03e64bc27dc370c6fd9b5ce7f8<br /><br />Installed multiple extensions (and updated 1 of them and uninstalled them - just in case) successfully..<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43617">issues.joomla.org/tracker/joomla-cms/43617</a>.</sub>

**Comment by crommie** [comment]
I have tested this item :white_check_mark: successfully on 24617139a33b6f03e64bc27dc370c6fd9b5ce7f8<br /><br />Installation extensions still works after applying patch. Site also still works.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43617">issues.joomla.org/tracker/joomla-cms/43617</a>.</sub>

**Comment by richard67** [comment]
@exlemor @crommie Have you also tested that Joomla Updates work as before? The testing instructions tell to do so. It could be done e.g. by applying the patch to a 5.2-dev and then updating to the patched package created by drone.

**Comment by crommie** [comment]
🙈 no. Can I do that on a PBF server site?

**Comment by richard67** [comment]
> 🙈 no. Can I do that on a PBF server site?

@crommie I think yes. They can later revert it to the initial state, as far as I know.

**Comment by degobbis** [comment]
I have not tested this item.<br /><br />Install and uninstall of Extension works as expected.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43617">issues.joomla.org/tracker/joomla-cms/43617</a>.</sub>

**Comment by degobbis** [comment]
I have tested this item :white_check_mark: successfully on 24617139a33b6f03e64bc27dc370c6fd9b5ce7f8<br /><br />Install and uninstall of Extension works as expected.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43617">issues.joomla.org/tracker/joomla-cms/43617</a>.</sub>

**Comment by crommie** [comment]
> > 🙈 no. Can I do that on a PBF server site?
> 
> @crommie I think yes. They can later revert it to the initial state, as far as I know.

Just checking: does "reinstall core files" use the same process or is that entirely different?

**Comment by richard67** [comment]
> > > 🙈 no. Can I do that on a PBF server site?
> > 
> > 
> > @crommie I think yes. They can later revert it to the initial state, as far as I know.
> 
> Just checking: does "reinstall core files" use the same process or is that entirely different?

@crommie Reinstall core is ok, that also uses the Joomla Update component as if it was an update.

**Comment by exlemor** [comment]
Hi @richard67,

Based on your comment, I tested the Joomla Update process for this PR.

Thanks.

**Comment by richard67** [comment]
@exlemor Could you submit again your test result? @obuisard has updated the branch but not restored the previous human tests in the issue tracker, so the test count got reset.

**Comment by exlemor** [comment]
Sure @richard67 , I will submit it again.

 Olivier just told me he didn't have rights to restore the human tests. ;(

**Comment by exlemor** [comment]
I have tested this item :white_check_mark: successfully on dcf15b1223af433538387c81b19681d159e0a603<br /><br />I have tested this item successfully

Installed multiple extensions (and updated 1 of them and uninstalled them - just in case) successfully..
I also tested the Joomla Update process. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43617">issues.joomla.org/tracker/joomla-cms/43617</a>.</sub>

**Comment by degobbis** [comment]
I have tested this item :white_check_mark: successfully on dcf15b1223af433538387c81b19681d159e0a603<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43617">issues.joomla.org/tracker/joomla-cms/43617</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43617">issues.joomla.org/tracker/joomla-cms/43617</a>.</sub>

**Comment by Hackwar** [comment]
Thank you for this contribution @Fedik.

**Pull request merged**
