### PR TITLE
[#32422] Multi option validation

### PR DESCRIPTION
**Pull request by okonomiyaki3000**
This is just #2335 but for staging instead of master.

Fixes this: http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=32422&start=0

### CODE REVIEW

**Comment by fvdn** [comment]
@test 
To test this i add in the file: mod_articles_catagories.xml (in the map modules) the next "test"field.
	<field
					name="show_description1"
					validate="options"
					multiple="true"
					type="checkboxes"
					class=""
					default="0"
					label="MOD_ARTICLES_CATEGORIES_FIELD_SHOW_DESCRIPTION_LABEL"
					description="MOD_ARTICLES_CATEGORIES_FIELD_SHOW_DESCRIPTION_DESC">
					<option value="2">TEST</option>
					<option value="1">JYES</option>
					<option value="0">JNO</option>
					
				</field>

I checked all three options.
Without patch i get a error.
With patch its works oke!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/3877">issues.joomla.org/joomla-cms/3877</a>.</sub>

**Comment by fvdn** [comment]
###### <field
####					name="show_description1"
####					validate="options"
####					multiple="true"
####					type="checkboxes"
####					class=""
####					default="0"
####					label="MOD_ARTICLES_CATEGORIES_FIELD_SHOW_DESCRIPTION_LABEL"
####					description="MOD_ARTICLES_CATEGORIES_FIELD_SHOW_DESCRIPTION_DESC">
####					<option value="2">TEST</option>
####					<option value="1">JYES</option>
####					<option value="0">JNO</option>
####					
####				</field> <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/3877">issues.joomla.org/joomla-cms/3877</a>.</sub>

**Comment by snarf007** [comment]
Added the following lines:
  <field
					name="show_description1"
					validate="options"
					multiple="true"
					type="checkboxes"
					class=""
					default="0"
					label="MOD_ARTICLES_CATEGORIES_FIELD_SHOW_DESCRIPTION_LABEL"
					description="MOD_ARTICLES_CATEGORIES_FIELD_SHOW_DESCRIPTION_DESC">
					<option value="1">JYES</option>
					<option value="0">JNO</option>
				</field>

Test succes

Able to save multiple selected checkbox items<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/3877">issues.joomla.org/joomla-cms/3877</a>.</sub>

**Comment by zero-24** [comment]
RTC'ing. Thanks :smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/3877">issues.joomla.org/joomla-cms/3877</a>.</sub>

**Pull request closed without merging**
