### PR TITLE
Gnu https

### PR DESCRIPTION
**Pull request by brianteeman**
Update the gnu.org links to use https

### CODE REVIEW

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on 941fb0297e4ab5df1e457e626d33340da39dd2c4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14450">issues.joomla.org/tracker/joomla-cms/14450</a>.</sub>

**Comment by yvesh** [comment]
I have tested this item :white_check_mark: successfully on 941fb0297e4ab5df1e457e626d33340da39dd2c4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14450">issues.joomla.org/tracker/joomla-cms/14450</a>.</sub>

**Comment by yvesh** [comment]
I have tested this item :white_check_mark: successfully on 941fb0297e4ab5df1e457e626d33340da39dd2c4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14450">issues.joomla.org/tracker/joomla-cms/14450</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14450">issues.joomla.org/tracker/joomla-cms/14450</a>.</sub>

**Comment by wilsonge** [comment]
Thankyou

**Pull request merged**
