### PR TITLE
Fix database schema checker for MySQL 8 on staging branch

### PR DESCRIPTION
**Pull request by richard67**
Pull Request for Issue #25452 for staging.

### Summary of Changes

Fix case in column type check of database schema checker for MySQL 8.

When you enter e.g. the SQL statement

`SHOW COLUMNS IN #__extensions WHERE field = 'enabled' AND type = 'TINYINT(3)';`

(using your db prefix of course and not `#__`)

in PhpMyAdmin on a Joomla 3.9.10 or staging database, you will get a result in MySQL 5.7 but not in MySQL 8.

But when you enter

`SHOW COLUMNS IN #__extensions WHERE field = 'enabled' AND UPPER(type) = 'TINYINT(3)';`

you get a result on both MySQL versions.

In both cases type names are lowercase in the result, but on MySQL 8 the search seems to be case-sensitive, while it is case-insensitive e.g. on MySQL 5.7.

### Testing Instructions

1. Install current staging using a MySQL db of version 8.0.something. After successsful finish, login on backend and go to "Extensions -> Manage -> Database".

Result: See section "Actual result" below.

2. Apply this patch, navigate to somwhere else in backend and then back to "Extensions -> Manage -> Database".

Result: See section "Expected result" below.

### Expected result

No database errors.

### Actual result

Database errors shown as described in issue #25452 , but when you check in the database and the schema update SQL mentioned in the error message, you will not see any reason because the data types match in all details those set by the schema update and also those in joomla.sql.

### Documentation Changes Required

None.

### CODE REVIEW

**Comment by richard67** [comment]
@wilsonge Question: Shall I do a PR for 4.0-dev, too, or shall we wait until this is merged and then 3.9.11 will be merged to 4.0-dev?

**Comment by richard67** [comment]
@MonkeyTrainer12 @breisig Please test.

@ReLater Please spread in forum people shall test this PR.

@mbabker Please review or at least notice desciption above about different behavior of "SHOW COLUMNS".

**Comment by richard67** [comment]
Drone failure is javascript and so not related to this PR.

**Comment by ReLater** [comment]
> @ReLater Please spread in forum people shall test this PR.

Done. Let's see how lazy they are.

And thank you for your efforts. I "bombed" my LInux with upgrading to MySQL 8 ;-)

**Comment by richard67** [comment]
yes i had struggle too

thanks god i bombed only a clone vm ;-)

**Comment by richard67** [comment]
Sorry, had forgotten most important part. Fixed now.

**Comment by richard67** [comment]
Grr, again mistake. Now it is really correct.

**Comment by breisig** [comment]
Will test out the patch very soon.

**Comment by richard67** [comment]
@breisig Did you already find time to test? If so, please mark your test result in the Joomla CMS issue tracker at [https://issues.joomla.org/tracker/joomla-cms/25658](https://issues.joomla.org/tracker/joomla-cms/25658). Just use the button "Test this", then select your test result and then submitt that with the corresponding button.

**Comment by frostmakk** [comment]
I have tested this item :white_check_mark: successfully on 30cd879ce6f9edbabdfe1c5219dc18de68496a01<br /><br />Tested on localhost wamp J 3.9.10 , PHP 7.3.7 ,  MySQL 8.0.15<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25658">issues.joomla.org/tracker/joomla-cms/25658</a>.</sub>

**Comment by richard67** [comment]
@MonkeyTrainer12 @breisig One more tester only needed. Thanks @frostmakk for testing.

**Comment by breisig** [comment]
@richard67 It looks like it works.

**Comment by ghost** [comment]
@breisig please mark your test as successfully (how to: https://docs.joomla.org/Testing_Joomla!_patches#Recording_test_results)

**Comment by richard67** [comment]
@MonkeyTrainer12 We still need one more tester because @breisig is either not willing or not able to mark his test result in the issue tracker like described e.g. here [https://github.com/joomla/joomla-cms/pull/25658#issuecomment-513544478](https://github.com/joomla/joomla-cms/pull/25658#issuecomment-513544478) or here [https://docs.joomla.org/Testing_Joomla!_patches#Recording_test_results](https://docs.joomla.org/Testing_Joomla!_patches#Recording_test_results) .

**Comment by richard67** [comment]
@breisig Thanks for your test, but please also mark your test result in the Joomla CMS issue tracker at https://issues.joomla.org/tracker/joomla-cms/25658. Just use the button "Test this", then select your test result and then submitt that with the corresponding button.

As long as not marked, it is not counted, and as long as no 2 test, this PR will not be ready for merge.

**Comment by breisig** [comment]
I have tested this item :white_check_mark: successfully on 30cd879ce6f9edbabdfe1c5219dc18de68496a01<br /><br />It worked for me.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25658">issues.joomla.org/tracker/joomla-cms/25658</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25658">issues.joomla.org/tracker/joomla-cms/25658</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by richard67** [comment]
Thanks to all testers and to reporters for your patience, and thanks for merging of course.

**Pull request merged**
