### PR TITLE
[4.0] Add htaccess and webconfig to the 4.0 root lib folder

### PR DESCRIPTION
**Pull request by zero-24**
### Summary of Changes

Add htaccess and webconfig to the 4.0 root lib folder as proposed here: https://github.com/joomla/joomla-cms/pull/15457#issuecomment-296298541

### Documentation Changes Required

Lib folder is not longer be a place for things you can call.

NginX need to include that in the configuration

### CODE REVIEW

**Comment by brianteeman** [comment]
On an update to j4 this will automatically replace any exisiting htaccess or webconfig

**Comment by mbabker** [comment]
While I agree with the intent of this, it needs to be made very clear with this change that Joomla will by default block any web request into the `libraries/` directory.  This means:

- No static assets (CSS, JS, images, fonts, etc. etc.)
- No direct access scripts (yes I realize people are going to respond with "they should go through `index.php` and the Joomla app" but not every developer is so irresponsible they can't handle the things that would make most advise to go that route

**Comment by zero-24** [comment]
> On an update to j4 this will automatically replace any existing htaccess or webconfig and presumably any future updated from 4.0 to 4.0.x etc will also overwrite the file.

We can also extend the default htaccess file in the root (without explizite adding it as .htaccess to the lib folder?

**Comment by C-Lodder** [comment]
2.0-2.2? really?

**Comment by brianteeman** [comment]
@C-Lodder more sites uses apache 2.0 - 2.2 than any other version https://w3techs.com/technologies/details/ws-apache/2/all

**Comment by zero-24** [comment]
Any news here? Should we go the `extend the default htaccess part` (IMO can be moved to staging than) or do we stay with the current proposal?

**Comment by brianteeman** [comment]
as nginx is a supported web server what happens

**Comment by zero-24** [comment]
Nothing as thy just ignore these files ;)

**Comment by brianteeman** [comment]
Sorry I wasnt clear. If the user is on nginx (a supported server) how are we going to offer them the same protection.

**Comment by zero-24** [comment]
IMO there is nothing we can do about that on a CMS level. As they do not offer such a configuration file. Same applys to the SEF stuff in our root htaccess / web.config

**Comment by brianteeman** [comment]
Maybe just add it to the relevant documentation then ?

**Comment by zero-24** [comment]
I have just included that request in the intial post. Thanks.

**Comment by zero-24** [comment]
@wilsonge can we get a final voice from you here?

**Pull request merged**
