### PR TITLE
Move Content Modal History from mootools to bootstrap

### PR DESCRIPTION
**Pull request by n9iels**
## What this PR does

This PR convert the old Mootools modal to a Bootstrap modal for the Content History button

Before:
before

After:
after
## How to test
1. Confirm all functions of content history are working like they have to do
2. Confirm the Bootstrap modal is also opening on the ContentHistory field type. You can test this to add the following code to a XML form:

```
<field type="contenthistory" name="contenthistory" label="Content History Test" />
```

Use the Global configuration for example, you can find this this form file here: `/administrator/components/com_config/model/form/application.xml`

### CODE REVIEW

**Comment by n9iels** [comment]
I'm aware of some untranslated language strings and a few problems on the front-end. So please wait with testing until I fix that :)

**Comment by n9iels** [comment]
Fixed, PR can be test now

**Comment by dgt41** [comment]
@n9iels is this one different than #5654? That one is RTC

**Comment by n9iels** [comment]
oeps, seems like I did work you already did.... :grin: I had to check that first....
I'm sorry :flushed:

**Comment by zero-24** [comment]
Closing than. Hopfully in the near future the PR #5654 gets merged ;)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7764">issues.joomla.org/joomla-cms/7764</a>.</sub>

**Comment by zero-24** [comment]
Thanks anyway @dgt41 & @n9iels <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7764">issues.joomla.org/joomla-cms/7764</a>.</sub>

**Pull request closed without merging**
