### PR TITLE
remove duplicated meaning comment

### PR DESCRIPTION
**Pull request by PhilETaylor**
Removed duplicated meaning comment

pretty obvious :)

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 33bedad8de6ad29e4d9aa2bfc8862f6a3af1ab6b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23049">issues.joomla.org/tracker/joomla-cms/23049</a>.</sub>

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on 33bedad8de6ad29e4d9aa2bfc8862f6a3af1ab6b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23049">issues.joomla.org/tracker/joomla-cms/23049</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23049">issues.joomla.org/tracker/joomla-cms/23049</a>.</sub>

**Comment by zero-24** [comment]
@wilsonge why did you tag this as 4.0 when it got merged into 3.10? Why at all was this be send against 3.10-dev and not against staging? @PhilETaylor

**Comment by PhilETaylor** [comment]
No idea - I was pretty sure everything was made against staging.

I'm kind confused what staging actually contains, as there is a 3.10 and 4.0 branch too - so always stick to staging or the 4.0-dev branch. 

Is there a document that helps developers understand what branches are being used for what purpose?

**Comment by rdeutz** [comment]
Always use staging for 3.x stuff, 3.10 is the bridge to 4. Release lead will merge staging in 3.10 when needed. If you do work for 4 the use 4.0-dev

**Comment by PhilETaylor** [comment]
well as 3.10 is over 200 commits behind staging, and 4.0-dev is over 5440 commits behind... someone has a lot of work to do!

**Comment by rdeutz** [comment]
not your problem

**Comment by mbabker** [comment]
Are you sure you're not looking at your fork?  There's no way in hell there have been 200 commits since 3.9.0 release, when I last branch merged to 3.10.

screen shot 2018-11-13 at 3 44 57 pm

https://github.com/joomla/joomla-cms/branches

**Comment by PhilETaylor** [comment]
> not your problem

What a bad attitude to have. Its all our problem. Its strange that so few people are actually working on Joomla development, so few ...

@mbabker Im just reporting what I see, and no, this is not my fork: 

screen recording 2018-11-13 at 09 46 pm

**Comment by mbabker** [comment]
Well, your image link is broken, but...

The left side of that bar is commits behind the default branch (staging), right side is commits ahead (and there's a tooltip explaining that).  So 3.10 is 27 commits behind and 202 ahead staging.

**Comment by PhilETaylor** [comment]
yup - I said that in my edit before your reply :) 

27 is a lot more managable I guess

But that still means 4.0 is over a 1000 !!

**Comment by rdeutz** [comment]
To point with your finger that someone has a lot of work to do, wasn't a better attitude. Look at yourself before you criticise others

**Comment by PhilETaylor** [comment]
Wow... simply pathetic attitude. And you wonder why people dont contribute to Joomla...

**Comment by rdeutz** [comment]
Luckily enough people find the right branch to contribute too and I am not wondering. Good, enough said here.

**Comment by zero-24** [comment]
> Is there a document that helps developers understand what branches are being used for what purpose?

Yes and GitHub shows you that all the time you do a PR, even when it is a bit hidden now days ;)

https://github.com/joomla/joomla-cms/blob/staging/.github/CONTRIBUTING.md

**Pull request merged**
