### PR TITLE
[4.0] Sort namespaces

### PR DESCRIPTION
**Pull request by 810**
Pull Request for Issue # .

### Summary of Changes

Sort the namespace by name.

### Testing Instructions

Delete administrator/cache/autoload_psr4.php, reload page.

### Expected result

That the list is alphabetically order.

### Actual result

List has no order.

### CODE REVIEW

**Comment by maikol-ortigueira** [comment]
I've tested the PR and looks ok. I've imported the whole list into excel and there are a couple of lines that don't exactly match the sorting that excel generates. Attached is a screenshot of the lines that don't match.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28869">issues.joomla.org/tracker/joomla-cms/28869</a>.</sub>

**Comment by maikol-ortigueira** [comment]
screen shot 2020-04-30 at 15 22 41<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28869">issues.joomla.org/tracker/joomla-cms/28869</a>.</sub>

**Comment by 810** [comment]
for me:

````
'Joomla\\Module\\Sampledata\\Administrator\\' => [JPATH_ADMINISTRATOR . '/modules/mod_sampledata/src'],
'Joomla\\Module\\StatsAdmin\\Administrator\\' => [JPATH_ADMINISTRATOR . '/modules/mod_stats_admin/src'],
'Joomla\\Module\\Stats\\Site\\' => [JPATH_SITE . '/modules/mod_stats/src'],
'Joomla\\Module\\Submenu\\Administrator\\' => [JPATH_ADMINISTRATOR . '/modules/mod_submenu/src'],
````

**Comment by maikol-ortigueira** [comment]
Sorry. I get the same list, too. The screenshot corresponds to the sorting done by excel. I don't think it's important, but I wanted to notify

**Comment by wilsonge** [comment]
Thanks!

**Comment by maikol-ortigueira** [comment]
I have tested this item :white_check_mark: successfully on 6eeba9a449583ab48eac0166082083a8dda672f1<br /><br />I've successfully completed the test. Everything works as it's supposed to.
Thank you!!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28869">issues.joomla.org/tracker/joomla-cms/28869</a>.</sub>

**Pull request merged**
