### PR TITLE
[4.0] Move addIncludePath from trait to class

### PR DESCRIPTION
**Pull request by rdeutz**
Pull Request for Issue #24559 .

### Summary of Changes
This moves the addIncludeMethod from the LeagcyModelLoaderTrait to the BaseModel and declare the $paths var as static member of the class

### Testing Instructions
Check components that are using the addIncludePath method, if they are still working 

### Expected result
It still works

### Documentation Changes Required
none

### CODE REVIEW

**Comment by richard67** [comment]
The linked issue at the top of the description is wrong. It is #24599 , but it should be #24559 .

**Comment by rdeutz** [comment]
Thanks fixed it

**Comment by richard67** [comment]
@rdeutz Not really, I still see ‘Pull Request for Issue #24599 .‘.

**Comment by rdeutz** [comment]
It's like cs fixes, it always takes two or more attempts to fix a trailing space :-)

**Comment by SharkyKZ** [comment]
```
Call to undefined method Joomla\CMS\MVC\Model\BaseModel::addIncludePath() 

Call stack
--
# | Function | Location
1 | () | JROOT\libraries\src\MVC\Controller\BaseController.php:186
2 | Joomla\CMS\MVC\Controller\BaseController::addModelPath() | JROOT\libraries\src\MVC\Controller\BaseController.php:460
3 | Joomla\CMS\MVC\Controller\BaseController->__construct() | JROOT\libraries\src\MVC\Factory\MVCFactory.php:77
4 | Joomla\CMS\MVC\Factory\MVCFactory->createController() | JROOT\libraries\src\Dispatcher\ComponentDispatcher.php:172
5 | Joomla\CMS\Dispatcher\ComponentDispatcher->getController() | JROOT\libraries\src\Dispatcher\ComponentDispatcher.php:145
6 | Joomla\CMS\Dispatcher\ComponentDispatcher->dispatch() | JROOT\libraries\src\Component\ComponentHelper.php:384
7 | Joomla\CMS\Component\ComponentHelper::renderComponent() | JROOT\libraries\src\Application\AdministratorApplication.php:115
8 | Joomla\CMS\Application\AdministratorApplication->dispatch() | JROOT\libraries\src\Application\AdministratorApplication.php:158
9 | Joomla\CMS\Application\AdministratorApplication->doExecute() | JROOT\libraries\src\Application\CMSApplication.php:230
10 | Joomla\CMS\Application\CMSApplication->execute() | JROOT\administrator\includes\app.php:63
11 | require_once() | JROOT\administrator\index.php:36
```

**Comment by SharkyKZ** [comment]
Last commit reintroduces the original issue.

**Comment by SharkyKZ** [comment]
This works but if we go this way the method should stay in `LeagcyModelLoaderTrait` (according to https://github.com/joomla/joomla-cms/issues/24559).

**Comment by jwaisner** [comment]
@rdeutz Can you clarify in your testing instructions what components are affected by the change? I want to ensure that this is tested properly.

**Comment by chmst** [comment]
I have tested this with differenc components: com_cache, com_users, com_content and looks good. 
But recommend more tests, especially with 3rd party components<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27998">issues.joomla.org/tracker/joomla-cms/27998</a>.</sub>

**Comment by jwaisner** [comment]
@rdeutz  Can you please resolve conflicts?

**Comment by wilsonge** [comment]
`LeagcyModelLoaderTrait` just realised this has a typo in xD

**Comment by wilsonge** [comment]
Confirmed with the weblinks module that this fixes the issue. Thankyou!

**Comment by SharkyKZ** [comment]
Wasn't this method supposed to stay in the trait?

**Comment by wilsonge** [comment]
Ideal world yes. But because of php internals it doesn’t work. See the original issue

**Comment by SharkyKZ** [comment]
It works either way. The fix was moving caching to class property. PR for moving back the method https://github.com/joomla/joomla-cms/pull/28322.

**Pull request merged**
