### PR TITLE
[4.0] Set color on quickicon titles - mobile

### PR DESCRIPTION
**Pull request by ciar4n**
Pull Request for Issue #17207 .

### Summary of Changes
Sets color on quickicon titles - mobile

### Testing Instructions
Check that #17207 has been resolved.

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on ac7ad98b7c88a9dfadea49f59cc2d5a3cebcb308<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17208">issues.joomla.org/tracker/joomla-cms/17208</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on ac7ad98b7c88a9dfadea49f59cc2d5a3cebcb308<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17208">issues.joomla.org/tracker/joomla-cms/17208</a>.</sub>

**Comment by ghost** [comment]
RTC after two successful tests.

**Comment by zero-24** [comment]
There are conflicts here can you fix them please?

**Review by C-Lodder — APPROVED** [review]

**Comment by ciar4n** [comment]
Conflicts fixed

**Comment by wilsonge** [comment]
I'm sorry I merged the @dgt41 validation PR and this is conflicting again :(

**Comment by C-Lodder** [comment]
@ciar4n do you want to close this in favour of the redesign (https://github.com/joomla/joomla-cms/pull/17348)?

**Comment by ciar4n** [comment]
Sure. Closing for #17348

**Pull request closed without merging**
