### PR TITLE
The JED language listings were removed in 2014

### PR DESCRIPTION
**Pull request by ot2sen**
See http://community.joomla.org/blogs/leadership/1793-the-jed-terms-of-service-updated.html for reference

### CODE REVIEW

**Comment by brianteeman** [comment]
Sorry for laughing. I just came to the JED to update my own issue #5987 and to create a PR to update that file and the first thing I saw was this. ;)

I am going to close this here shortly with a link to the PR that removes the text from the readme<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6059">issues.joomla.org/joomla-cms/6059</a>.</sub>

**Comment by ot2sen** [comment]
Yeah, looked like a good option to get the j+git setup at new machine. Did name a local branch as your original issue as you can see, but didnt quite make it right it seems :)

**Comment by brianteeman** [comment]
@ot2sen I corrected an extra issue with a missing line in the readme. in #6061 I hope its ok if I close this one of yours as mine covers this and one extra<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6059">issues.joomla.org/joomla-cms/6059</a>.</sub>

**Comment by ot2sen** [comment]
@brianteeman yes that is fine. Was good practice

**Pull request closed without merging**
