### PR TITLE
Move one `JFactory::getUser();` call.

### PR DESCRIPTION
**Pull request by zero-24**
This PR ~~fix a typo at the `ContactModelContact` and~~ move one `JFactory::getUser();` call.
#### Joomla-bugs reference

http://www.joomla-bugs.de/forum/index.php/topic,649.msg3050.html#new

### CODE REVIEW

**Comment by wilsonge** [comment]
This seems wrong? You're checking there is a valid contact id to delete. We have exactly the same check in all components (e.g. the one in com_content here https://github.com/zero-24/joomla-cms/blob/patch-10/administrator/components/com_content/models/article.php#L159)

**Comment by joomdonation** [comment]
The fix typo is wrong as George mentioned. However, the "move one JFactory::getUser(); call" is good and should be updated (how about calling return JFactory::getUser()->authorise('core.edit.state', 'com_contact.category.' . (int) $record->catid); directly ? )

**Comment by zero-24** [comment]
hmm ok so i revert  here and leave the moving of `JFactory::getUser();` call. So this is a simple CS PR :smile:

**Comment by wilsonge** [comment]
Merged on review

**Pull request merged**
