### PR TITLE
[4.0] com_checkin [a11y]

### PR DESCRIPTION
**Pull request by brianteeman**
Same issue as with #29902

Ensures that there is only one label and that it is correctly named

### CODE REVIEW

**Comment by Quy** [comment]
It is escaping `< >` so don' know how screenreaders will read it.

`<span class="sr-only">Select &lt;em&gt;cuka8_content&lt;/em&gt; table</span>`

**Comment by brianteeman** [comment]
I think its ok here to simply remove the sprintf from the label

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on dc56d8c70397d871224b7ffbb13dde4168a2985f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29905">issues.joomla.org/tracker/joomla-cms/29905</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on dc56d8c70397d871224b7ffbb13dde4168a2985f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29905">issues.joomla.org/tracker/joomla-cms/29905</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29905">issues.joomla.org/tracker/joomla-cms/29905</a>.</sub>

**Comment by richard67** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
