### PR TITLE
com_installer updatesites view: searchtools ordering and bug corrections

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Description

This PR adds, for consistency, as it exists in so many other views in the backoffice, the order select box of the search tools to com_installer updatesites view.

Also corrects bug where the folder filter and not selecting the search button, and other small graphical issues.
Also other small code changes/improvements.
###### Before PR

com_installer-updatesites-beforepr
###### After PR

com_installer-updatesites-afterpr
#### How to test
1. Install latest staging and apply this patch
2. Go to Extensions -> Manage -> Update Sites
3. Check the ordering select box and the filter are working fine.

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 0eb17429832e0e72df602d28dfc21f8ec951fc75<br /><br />Tested with success, ordering and filtering works fine, and the page looks well.

"Also corrects bug where order by name descending was not working" - this I could not verify: Here it worked well before and after the patch.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9107">issues.joomla.org/joomla-cms/9107</a>.</sub>

**Comment by richard67** [comment]
P.S.: The "folder filter and not selecting the search button" thing I could verify with success: After selecting the folder as only filter, the search tools are hidden without the patch of this PR, and with the patch they stay visible as it should be.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9107">issues.joomla.org/joomla-cms/9107</a>.</sub>

**Comment by andrepereiradasilva** [comment]
> "Also corrects bug where order by name descending was not working" - this I could not verify: Here it worked well before and after the patch.

Sorry copy/paste from other PR. I updated the description

**Comment by ghazal** [comment]
I have tested this item :white_check_mark: successfully on 0eb17429832e0e72df602d28dfc21f8ec951fc75<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9107">issues.joomla.org/joomla-cms/9107</a>.</sub>

**Comment by brianteeman** [comment]
RTC thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9107">issues.joomla.org/joomla-cms/9107</a>.</sub>

**Comment by wilsonge** [comment]
Merged - thanks all!

**Pull request merged**
