### PR TITLE
Revert routing changes in 3.8.4

### PR DESCRIPTION
**Pull request by csthomas**
Pull Request for Issue #19504

### Summary of Changes
Because I am responsible for this, I feel that I have to prepare a reverse PR.

I'm not a fan of this PR but I won't insist to stay without reversion. 

Each of reverted PRs are connected each other.
1. Revert URL changes.
2. Revert changes in language filter.

### Expected result
The same as on 3.8.3

### Actual result
New structured URLs.

### CODE REVIEW

**Comment by infograf768** [comment]
Works fine. Evidently, https://github.com/joomla/joomla-cms/issues/15730 is still an issue if no login form menu item is present.

**Comment by cavo789** [comment]
I have tested this item :white_check_mark: successfully on 335100c39c71c2e83bd9aed09ae05c1dab46767e<br /><br />It was impossible anymore to log in on the frontend on my multilingual website; ERR_INVALID_REDIRECT just after the submission of the log in screen. With #19512 applied, problem solved. Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19512">issues.joomla.org/tracker/joomla-cms/19512</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 335100c39c71c2e83bd9aed09ae05c1dab46767e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19512">issues.joomla.org/tracker/joomla-cms/19512</a>.</sub>

**Comment by infograf768** [comment]
@mbabker to decide

**Comment by mbabker** [comment]
Will look later when back from travel.

> Because I am responsible for this, I feel that I have to prepare a reverse PR.

As the saying goes, stuff happens.  Nobody's blaming you.

**Comment by infograf768** [comment]
I have created a PR to, at least, inform users of the necessity to create a login form when Home is set to registered. https://github.com/joomla/joomla-cms/pull/19535

**Comment by csthomas** [comment]
> As the saying goes, stuff happens. Nobody's blaming you.

Thanks

**Comment by tonypartridge** [comment]
Good work, your not to blame. You PR was valid, the issue is the lack of people testing the 3.8.4 release.

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Comment by GiottoVerducci** [comment]
I applied csthomas's guideline: removing the option parameter as suggested in his example.

> The correct code should be JRoute::_('index.php'); which do the same and it is correct.

I notice that JRoute does return the correct value, but when using that value as the form submit value (POST), I get a 303 "See other" code that redirects me towards "component/<mycomponent>/?<myparameters>"

Browsing to the url returned by JRoute works fine (GET).

Did anything change concerning re-routing with that (breaking) change?

**Comment by LukeDouglas2** [comment]
Installed 3.8.5 on 67 websites and everything seems fine. Great work.

I wanted to compliment the development team on the work since Joomla 3 was released.  Along with the Gantry Framework team, you have cut my maintenance time by at least 10% on websites.  That's extra time for the golf course. :)

**Pull request merged**
