### PR TITLE
[4.0] Rename Tags route helper class

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Renames `Joomla\Component\Tags\Site\Helper\TagsHelperRoute` to be consistent with other helper classes.

### Testing Instructions

Create an article. In the article create some tags on the fly.
View a list of tags and single in frontend.
Run Smart Search indexer.

### Expected result

Works like before.

### Documentation Changes Required

IDK.

### CODE REVIEW

**Comment by jwaisner** [comment]
I have tested this item :red_circle: unsuccessfully on 109659eb59749199813e785afe3a2caa4e00748b<br /><br />After applying patch, frontend breaks with errors.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27511">issues.joomla.org/tracker/joomla-cms/27511</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 109659eb59749199813e785afe3a2caa4e00748b<br /><br />repatching resolved missing files. All works as expected.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27511">issues.joomla.org/tracker/joomla-cms/27511</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
