### PR TITLE
Do not count all table rows if start offset is 0

### PR DESCRIPTION
**Pull request by csthomas**
A little speed up backend -> com_content -> articles view when you have set page 1 (means start=0).

How to test:
- enable joomla debug (list of sql queries)
- test without patch number queries
- test with patch number of queries (one count less)

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 881f44e796b91ec13030323be375f25fe2033ac5<br /><br />I can confirm with this patch there is one less query BUT I really dont know enough about this to understand if there can be other consequences<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9162">issues.joomla.org/joomla-cms/9162</a>.</sub>

**Comment by csthomas** [comment]
Thanks,

I created that patch some time ago, probably for 3.4.4 and 
today I try to show this duplicated query but it missing now.

After joomla 3.4.5 this patch do not change too much.
Anyway can be useful to not run getTotal() if not needed.

**Comment by grhcj** [comment]
I have tested this item :white_check_mark: successfully on 881f44e796b91ec13030323be375f25fe2033ac5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9162">issues.joomla.org/joomla-cms/9162</a>.</sub>

**Comment by csthomas** [comment]
New commit have not change anything, I only rebase to newer stagging branch.

* Method getStart() always run getTotal(), but when $start is 0 then calculating $start won't change anything, because $start can not be less than 0.

* I think that the patch will be useful for sort queries in order (select from table, select count)
when start=0 (first page)

* In the future - joomla should not run getTotal() at all if number of fetched rows is less than limit from query and $start is 0. Specially when there is a lots of filters and result contains only a few rows.

**Comment by brianteeman** [comment]
RTC (maintainer the tests were before a rebase so it should  be ok)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9162">issues.joomla.org/joomla-cms/9162</a>.</sub>

**Comment by roland-d** [comment]
Thanks everybody

**Pull request merged**
