### PR TITLE
Fix xml coding style

### PR DESCRIPTION
**Pull request by Quy**
Related to PR #17668

### Summary of Changes
Fix indentation

### Testing Instructions
Code review

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 94b5402ff2d6519df1a98338dbb141909ad79b2e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17748">issues.joomla.org/tracker/joomla-cms/17748</a>.</sub>

**Comment by nvyush** [comment]
I have tested this item ✅ successfully on 94b5402

**Review by nvyush — APPROVED** [review]

**Comment by nvyush** [comment]
I have tested this item :white_check_mark: successfully on 94b5402ff2d6519df1a98338dbb141909ad79b2e<br /><br />I have tested this item ✅ successfully on 94b5402<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17748">issues.joomla.org/tracker/joomla-cms/17748</a>.</sub>

**Comment by ghost** [comment]
RTC after two successful tests.

**Pull request merged**
