### PR TITLE
[4.0] Remove obsolete module class "_menu" from menu modules' parameters

### PR DESCRIPTION
**Pull request by richard67**
Pull Request for Issue #23023 .

### Summary of Changes

Remove unused module class (formerly called module class suffix) "_menu" from menu modules' parameters in new installation and sample data.

### Testing Instructions

Code review.

### Expected result

The module class "_menu" is not added to parameters of any menu modules on new installation and on any kind of sample data installation.

### Actual result

The module class "_menu" is added to the parameters of the default "Main Menu" on new installation of J4, of diverse menus in testing sample data and of the language-specific main menus in multilanguage sample data, but it has no effect on styling.
In comparison to that, when creating a new menu, the module class "_menu" is not added to the new menu.
This inconistency and the obsolete module class added in the cases mentioned above might confuse administrators who create or maintain menu modules.

### Documentation Changes Required

None.

### CODE REVIEW

**Comment by richard67** [comment]
@ciar4n Could you review or test this PR?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23054">issues.joomla.org/tracker/joomla-cms/23054</a>.</sub>

**Comment by ciar4n** [comment]
I have tested this item :white_check_mark: successfully on a8a484da8205bcd4cae4f7c82c7ec77231b9e262<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23054">issues.joomla.org/tracker/joomla-cms/23054</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on a8a484da8205bcd4cae4f7c82c7ec77231b9e262<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23054">issues.joomla.org/tracker/joomla-cms/23054</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23054">issues.joomla.org/tracker/joomla-cms/23054</a>.</sub>

**Comment by richard67** [comment]
Thanks to all testers.

**Comment by wilsonge** [comment]
Thanks!

**Comment by richard67** [comment]
Thanks, too.

**Pull request merged**
