### PR TITLE
[com_fields] Fields do not delete from the database when deleted from the back end

### PR DESCRIPTION
**Pull request by zero-24**
Pull Request for Issue #15230 

### Summary of Changes

delete the field if the uses which this.

### Testing Instructions

Create a new field
Delete the field

### Expected result

Cannot see the field in the database

### Actual result

The field remains in the database

### Documentation Changes Required

none

### CODE REVIEW

**Comment by uglyeoin** [comment]
It didn't say it failed, neither did the original.  But my DB stays the same.

**Comment by zero-24** [comment]
@uglyeoin this just do this for new "deletions" and not for the you allready did so you need to repeate the 
 creation and deletion ;)

**Comment by uglyeoin** [comment]
@zero-24 I thought that is what I did but I will try again

**Comment by zero-24** [comment]
Great. Please make sure the changes in the code are applyed 😄

**Comment by ot2sen** [comment]
Couldn´t reproduce issue - before - adding patch. The field was removed from database when emptying trash. This was for an article field. Does this happen elsewhere?

**Comment by alikon** [comment]
couldn't reproduce issue before patch, i've tested with user fields

**Comment by uglyeoin** [comment]
@ot2sen argh, don't tell me there was no issue

**Comment by ot2sen** [comment]
@uglyeoin  there might have been, I just couldn´t see it here and therefore unable to test a fix for something that didn´t happen :) 
It was removed from db when emptying trash without any fixes.

**Comment by Quy** [comment]
Unable to reproduce the issue before the patch. Created and deleted fields/field groups under Users, Content, and Contacts successfully without orphans.

**Comment by zero-24** [comment]
Closing than. Thanks for testing.

**Comment by uglyeoin** [comment]
@zero-24 sorry, tired eyes my bad

**Pull request closed without merging**
