### PR TITLE
[5.3] Send test mail to the logged-in user.

### PR DESCRIPTION
**Pull request by tecpromotion**
### Summary of Changes

In times of Microsoft 365, transactional mail services, SMTP relays and configurations where there is no easy access to the MailFrom mailbox, it makes sense for the test mail to be sent to the logged-in user.
Usually, the mailbox is accessible and the email settings can be tested with real live data.

### Testing Instructions

Log in to the backend with your user and go to Global Configuration.
In the Server tab, complete the email configuration and then click "Send Test Mail".

### Actual result BEFORE applying this Pull Request

The test mail is sent to the e-mail address (mailfrom) from the global configuration.

### Expected result AFTER applying this Pull Request

The test mail is sent to the logged-in user.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by tecpromotion** [comment]
@chmst and @coolcat-creations I have created a PR here for the topic from the DACH channel in Mattermost.
Thanks @bembelimen

**Comment by brianteeman** [comment]
I have always just changed the from address when testing - I guess this just automates it ;)

**Comment by coolcat-creations** [comment]
I have tested this item :white_check_mark: successfully on d2a07927728c59340a955192552a98f0f481d932<br /><br />tested successful, mail was sent to me (the tester / user) instead of smtp account<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44002">issues.joomla.org/tracker/joomla-cms/44002</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on d2a07927728c59340a955192552a98f0f481d932<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44002">issues.joomla.org/tracker/joomla-cms/44002</a>.</sub>

**Comment by chmst** [comment]
rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44002">issues.joomla.org/tracker/joomla-cms/44002</a>.</sub>

**Comment by laoneo** [comment]
I realy like it, but I think this needs a documentation entry as it is a change in behavior.

**Comment by brianteeman** [comment]
> I realy like it, but I think this needs a documentation entry as it is a change in behavior.

That was my first thought but the success/failure message is quite clear where the email is sent already

**Comment by laoneo** [comment]
I really think this should be documented. If done, I'm happy to merge it.

**Comment by coolcat-creations** [comment]
Which sentence would you change here or which one is not correct anymore? 

https://docs.joomla.org/How_to_debug_SMTP_mail_in_Joomla_4

I dont see it... @laoneo

**Comment by laoneo** [comment]
With this pr, the mail is sent to the current user and not anymore to the mail address from the config. The sentence is still ok, but the behavior changes and I think this should be mentioned in the documentation of the release. The pr itself is absolutely fine.

**Comment by coolcat-creations** [comment]
@laoneo where is the documentation of the release?

**Comment by laoneo** [comment]
To not delay this pr any longer, I'v added the documentation required label, so we will find it again when we do the release notes.

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
