### PR TITLE
[4] correct the namespace class

### PR DESCRIPTION
**Pull request by PhilETaylor**
code review

### CODE REVIEW

**Comment by joomdonation** [comment]
I have tested this item :white_check_mark: successfully on 81c0e8216a92d79bd920b8f13ce8003d9dda1d1e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34016">issues.joomla.org/tracker/joomla-cms/34016</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 81c0e8216a92d79bd920b8f13ce8003d9dda1d1e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34016">issues.joomla.org/tracker/joomla-cms/34016</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34016">issues.joomla.org/tracker/joomla-cms/34016</a>.</sub>

**Comment by richard67** [comment]
Thanks.

**Pull request merged**
