### PR TITLE
[4.0] Fix sample data styling in the backend

### PR DESCRIPTION
**Pull request by wilsonge**
CSS and JS fixes for styling sample data

### CODE REVIEW

**Comment by carlitorweb** [comment]
I have tested this item :white_check_mark: successfully on 8f31299a0e93aabd19ccedf2737c249fe3adacfd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20424">issues.joomla.org/tracker/joomla-cms/20424</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 8f31299a0e93aabd19ccedf2737c249fe3adacfd<br /><br />Thanks. At last it now displays fine.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20424">issues.joomla.org/tracker/joomla-cms/20424</a>.</sub>

**Comment by infograf768** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20424">issues.joomla.org/tracker/joomla-cms/20424</a>.</sub>

**Comment by laoneo** [comment]
Since the ES6 merge, this one has conflicts.

**Comment by wilsonge** [comment]
This got fixed by the es6 work

**Pull request closed without merging**
