### PR TITLE
[4.0] config load balancer

### PR DESCRIPTION
**Pull request by brianteeman**
updates the switch and corrects the filter after the merge from j3

PR for #33527

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 9147bf4dd69d51a5935e3542d69fc60e74e1ffa8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33539">issues.joomla.org/tracker/joomla-cms/33539</a>.</sub>

**Comment by rjharishabh** [comment]
I have tested this item :white_check_mark: successfully on 9147bf4dd69d51a5935e3542d69fc60e74e1ffa8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33539">issues.joomla.org/tracker/joomla-cms/33539</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33539">issues.joomla.org/tracker/joomla-cms/33539</a>.</sub>

**Comment by Quy** [comment]
Thanks

**Pull request merged**
