### PR TITLE
Free the cursor! (Prevent the cursor from getting stuck in nested blocks in TinyMCE)

### PR DESCRIPTION
**Pull request by crystalenka**
### Summary of Changes
This will be a familiar frustration for those who use templates in TinyMCE: inserting a template, and then not being able to get the cursor out of a block if it was nested or at the very end of the document, unless you inserted white space or other tags after too. That's not ideal.

This change enables an existing tinyMCE parameter, [end_container_on_empty_block](https://www.tiny.cloud/docs/configure/advanced-editing-behavior/#end_container_on_empty_block), which allows you to exit out of those blocks intentionally by pressing `enter` twice.

### Testing Instructions

Open somewhere with an editor field. Toggle to turn off the editor and insert the following HTML (as the ONLY content):

``` HTML
<div class="parent" style="background-color: #ddd; padding: 1em;">
  <div class="child" style="background-color: #efefef; padding:1em;">
    <p>Text goes here.</p>
  </div>
</div>
```

Toggle the editor and turn it back on. Optionally enable block visibility for better understanding of which div you are in.

Then, try to use the arrow keys or enter key to get out of the child and parent divs.

### Actual result BEFORE applying this Pull Request
You can't. You're stuck in the child div forever.

### Expected result AFTER applying this Pull Request
Pressing enter twice exits the child div and you can enter content in the parent div.
Pressing enter another two times exits the parent div and you can now add text in the main editor without blocks.

### Link to documentations
Please select:
- [x] No documentation changes for docs.joomla.org needed
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
LGTM - please note the link to the tiny docs you gave is for tiny6 where this option is enhanced. The correct link for tiny5 is https://www.tiny.cloud/docs/configure/advanced-editing-behavior/#end_container_on_empty_block

**Comment by crystalenka** [comment]
Thanks @brianteeman , updated it!

**Comment by crystalenka** [comment]
Has the build stuff broken? It's been pending a long time

**Review by wilsonge — APPROVED** [review]

**Comment by coolcat-creations** [comment]
I tested this and it works like expected. I think it should be added to the documentation, though. (I dont see any test this button in issues.joomla.org) thats why I am only commenting.

**Comment by crystalenka** [comment]
@richard67 do you have any idea why there wouldn't be a "test this" button on the issues site? I can't confirm since I am the author

**Comment by richard67** [comment]
@crystalenka A bug with the issue tracker which happens from time to time. The tracker treats the PR as if it was an issue and so doesn't show the button. Solution is either people report back their test result with a comment and we (maintainers or JBS) have a look on it and set it RTC when it has 2 tests reported in that way. Or you make a new PR and close this one.

**Comment by crystalenka** [comment]
Okay. Elisa tested it successfully, I'm not sure if @brianteeman or @wilsonge did?

**Comment by richard67** [comment]
@crystalenka By the way: Is your cursor named Willy?

**Comment by coolcat-creations** [comment]
> @crystalenka By the way: Is your cursor named Willy?

That joke took me too long, I would admit to.

**Comment by chmst** [comment]
Tested following the instruction and it works as described. We need a documentation for this change as it is not very known or self-explaining.

**Comment by crystalenka** [comment]
Thank you @chmst ! I am happy to document it but where?

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39418">issues.joomla.org/tracker/joomla-cms/39418</a>.</sub>

**Comment by richard67** [comment]
@chmst Assuming your [comment above](https://github.com/joomla/joomla-cms/pull/39418#issuecomment-1361483355) is a successful test, I have set RTC as that was the 2nd test.

**Comment by roland-d** [comment]
Thank you

**Pull request merged**
