### PR TITLE
Adjust version attribute in package manifest

### PR DESCRIPTION
**Pull request by Bakual**
Simple change to bring the version attribute of the english package manifest to 3.8.

### CODE REVIEW

**Comment by infograf768** [comment]
You may also update the version attribute for both en-GB.xml and install.xml for site and admin.

afaik, these are any way useless for installing or updating and do not display in back-end.

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on ddfb9db152e096fd4d675cc78d71370142af923d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18535">issues.joomla.org/tracker/joomla-cms/18535</a>.</sub>

**Comment by infograf768** [comment]
RTC as simple change.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18535">issues.joomla.org/tracker/joomla-cms/18535</a>.</sub>

**Comment by Bakual** [comment]
Done for the other files as well.
It's true that it doesn't matter currently. It may matter in future if we ever use that attribute as a "minimum" version or something.
Anyway, it makes sense to update it since it is there.

**Comment by infograf768** [comment]
> Anyway, it makes sense to update it since it is there.

Indeed.

**Comment by rvbgnu** [comment]
Great, thank you Thomas and Jean-Marie!

**Pull request merged**
