### PR TITLE
[4.0] Remove Atum overrides

### PR DESCRIPTION
**Pull request by brianteeman**
There is no need to have these overrides. We really shouldnt have to create overrides for the core templates and it is a maintenance headache.

This PR removes the overrides and puts the two tiny changes back into the core files.

For reference the changes are
1. Edit Article
Remove the box shadow around the wysiwyg area
2. Article Manager
Change the size of the text for the status text to small

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 3dbe6c87c82886d717ee328b8b6a5029816d5e03<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28052">issues.joomla.org/tracker/joomla-cms/28052</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 3dbe6c87c82886d717ee328b8b6a5029816d5e03<br /><br />Code review: The changes made by this PR to the core files are equal to the differences between the removed override files and their corresponding core files, plus the error with empty css class is corrected.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28052">issues.joomla.org/tracker/joomla-cms/28052</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28052">issues.joomla.org/tracker/joomla-cms/28052</a>.</sub>

**Comment by brianteeman** [comment]
Thanks everyone

**Pull request merged**
