### PR TITLE
Make js ajax error messages more useful when using Joomla.request

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
### Summary of Changes

There are some cases we get some strange message on ajax errors. Thsi happens when, for instance, when we use the new vannila js `Joomla.request` instead of the jquery ajax methods.

It seems this happens because jQuery ajax error returns different values than plain vanilla js methods do.

This PR intends to make those messages more useful in this contexts.
### Testing Instructions
1. Code review.
2. You need to make ajax errors to test this. Example:
3. Set session time to one minute so the keepalive ajax call takes one minute.
4. Now edit any content in admin and leave the edit view open so keepalive keep running
   . add the following code in https://github.com/joomla/joomla-cms/blob/3.7.x/administrator/components/com_ajax/ajax.php#L11 to make an ajax error

``` php
$app = JFactory::getApplication();
$app->setHeader('Content-Type', 'application/json; charset=utf-8');
$app->sendHeaders();
echo jason_encode('a');
$app->close();
die();
```
- Wait for keepalive and you will get something like this
  image
- Now apply patch, clear browsers cache and repeat the same steps. You should get soemthing like this
  image
### Documentation Changes Required

None.

@Fedik please review this, as you were the one that created the new Joomla.request method, and i could be missing something here.

@dgt41 please check too.

### CODE REVIEW

**Comment by Fedik** [comment]
thanks! looks good.
I try to test in next days

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on 8a15b13713671613d952108ab6576bd6f9e2eef1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12437">issues.joomla.org/tracker/joomla-cms/12437</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@dgt41 can you check this one please?

**Comment by dgt41** [comment]
I have tested this item :white_check_mark: successfully on 8a15b13713671613d952108ab6576bd6f9e2eef1<br /><br />Already using it in J4 😄<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12437">issues.joomla.org/tracker/joomla-cms/12437</a>.</sub>

**Comment by dgt41** [comment]
RTC

**Pull request merged**
