### PR TITLE
[4.0] Database Fix button

### PR DESCRIPTION
**Pull request by brianteeman**
Currently the button is called _Fix_ and based on the number of times I see people thinking they need to do this all the time and it will magically fix things this PR changes the name to _Update Structure_

Hopefully it will reduce the number of people who think its a solution to every possible bug

image

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 6690b2408468e0db55455437abdc9ef7751aecc6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26458">issues.joomla.org/tracker/joomla-cms/26458</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 6690b2408468e0db55455437abdc9ef7751aecc6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26458">issues.joomla.org/tracker/joomla-cms/26458</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26458">issues.joomla.org/tracker/joomla-cms/26458</a>.</sub>

**Comment by ChristineWk** [comment]
@brianteeman 
..."Hopefully it will reduce the number of people who think its a solution to every possible bug"

of course :-) OT: That's why I'm checking before: 
database
sorry, I didn't find the image button. 
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26458">issues.joomla.org/tracker/joomla-cms/26458</a>.</sub>

**Comment by wilsonge** [comment]
So the fun part is it does more than db structure :D it also deals with deleting unused files (also normally managed by joomla update and even a piece of 2.5 code migration - that can probably be removed than J4 https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_installer/Model/DatabaseModel.php#L268-L270)

Although in principal this should be separate of course. Some of this stuff is why we need a status page rather than this magic button

**Comment by brianteeman** [comment]
Stage 1 is to rename the button - this PR
Stage 2 is separate the non-database code
Stage 3 create the status page

**Comment by wilsonge** [comment]
Please make sure at least part 2 comes in the not too distant. else we'll need to revert it before going stable if it's still doing non database things

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
