### PR TITLE
Code mirror autofocus issue

### PR DESCRIPTION
**Pull request by okonomiyaki3000**
Pull Request for Issue #20228 .

### Summary of Changes

Get autofocus settings from the field xml instead of from the plugin settings.
Autofocus only one CodeMirror per page regardless of field settings.

### Testing Instructions

Open up a form with multiple CodeMirrors on it. One or more of their xml settings may include an `autofocus` attribute. 

### Expected result

At most, one CodeMirror will have focus when the page loads. 

### Actual result

Yes, this should be correct. 

### Documentation Changes Required

No.

### CODE REVIEW

**Review by dgrammatiko — APPROVED** [review]

**Review by brianteeman — DISMISSED** [review]
The stupid rules are that we dont delete a language string even if is unused - so can you just add a note above these lines that says 
;The following two strings are deprecated and will be removed in J4 

thanks

**Comment by Septdir** [comment]
I have tested this item :white_check_mark: successfully on 4d06775a740afa041fa009ea8573233c988937fc<br /><br />Nice. After changes ping me. I will test again.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20270">issues.joomla.org/tracker/joomla-cms/20270</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 94dccf289b8c52ef68ebf085ffcb1b126caaf67a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20270">issues.joomla.org/tracker/joomla-cms/20270</a>.</sub>

**Comment by okonomiyaki3000** [comment]
@Septdir :ping_pong: (there was no :ping:, this was as close as I could get)

**Comment by Septdir** [comment]
I have tested this item :white_check_mark: successfully on 94dccf289b8c52ef68ebf085ffcb1b126caaf67a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20270">issues.joomla.org/tracker/joomla-cms/20270</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Pull request merged**
