### PR TITLE
Add plugin events to com_contact (redo)

### PR DESCRIPTION
**Pull request by Harmageddon**
This is a redo of #3630, using the current staging branch and with some improvements.
### Contents

This PR implements the following plugin events for plugins (group: content):

| Event | Views |
| --- | --- |
| onContentPrepare | <ul><li>contact</li><li>category (for category title, category description and every contact)</li></ul> |
| onContentAfterTitle | <ul><li>contact</li><li>category (for every contact)</li></ul> |
| onContentBeforeDisplay | <ul><li>contact</li><li>category (for every contact)</li></ul> |
| onContentAfterDisplay | <ul><li>contact</li><li>category (for every contact)</li></ul> |
### Testing instructions
1. Install the patch.
2. If you don't have any plugin installed that targets com_contact, nothing should change in any view (especially in the com_contact views).
3. Install a content plugin that uses the events mentioned above in com_contact.
   You can either write a new one, modify one of the existing content plugins, or use [this small plugin for testing purposes](https://github.com/Harmageddon/plg_contact_events).
4. Make sure that the plugin works in the desired way.
5. Please test Beez (default and encyclopedia layout), too!

### CODE REVIEW

**Comment by Harmageddon** [comment]
Updated the PR with Beez support and a slightly different context for category descriptions.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8024">issues.joomla.org/joomla-cms/8024</a>.</sub>

**Comment by wilsonge** [comment]
Thankyou :) I'll try and find some time to test over the next week or so. But can't guarantee anything :(

**Comment by Rivaner** [comment]
Testing works!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8024">issues.joomla.org/joomla-cms/8024</a>.</sub>

**Comment by KlausKrippeit** [comment]
I have tested this item :white_check_mark: successfully on ccb17b03b64f006da2689e8e13c3b9153341a6df<br /><br />@test successfully tested.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8024">issues.joomla.org/joomla-cms/8024</a>.</sub>

**Comment by waader** [comment]
@test works for me too. Also saw some improvements. Thanks for that!

**Comment by yvesh** [comment]
I have tested this item :white_check_mark: successfully on ccb17b03b64f006da2689e8e13c3b9153341a6df<br /><br />@Test works fine<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8024">issues.joomla.org/joomla-cms/8024</a>.</sub>

**Comment by wilsonge** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8024">issues.joomla.org/joomla-cms/8024</a>.</sub>

**Comment by zero-24** [comment]
@Harmageddon can you fix the merge conflicts.

**Comment by Harmageddon** [comment]
@zero-24 Should be fine now.

**Comment by zero-24** [comment]
Thanks @Harmageddon

**Comment by roland-d** [comment]
Thanks everybody, this has now been merged into 3.5-dev with commit 88fb40b

Gosh what a brainkiller this was to merge :P

**Comment by mbabker** [comment]
This pull request has introduced two regressions:

1) Via https://github.com/joomla/joomla-cms/commit/88fb40b7ad4bbc2d525c63cadfa8b62e1307fb96#diff-075095e768ef950cf2dcc5f08cf5436aR148 plugin events are now being triggered twice for all items on the `com_content.category` view
2) https://github.com/joomla/joomla-cms/commit/88fb40b7ad4bbc2d525c63cadfa8b62e1307fb96#diff-075095e768ef950cf2dcc5f08cf5436aR159 is hardcoded to `com_contact.category` as the context instead of correctly determining the extension as is done with every other trigger

**Comment by Bakual** [comment]
@mbabker You know what comes. Can you open a new issue (or even PR) that references to this PR?
I'm sure this will get lost otherwise.

**Comment by wilsonge** [comment]
https://github.com/joomla/joomla-cms/pull/8581 PR for the context (part 2). Don't have time right at this second to look into number 1. Will do that later.

**Comment by mbabker** [comment]
> Can you open a new issue (or even PR) that references to this PR?

If I do it's taking the event triggers out of `JViewCategory` because it's damn near a B/C issue (extensions extending it and calling that method are now either getting new plugin events that weren't in place originally or in the case of com_content now causes events to be triggered twice).

This pull request should not have been merged without testing against ALL components because of the changes in JViewCategory at a minimum.  Also, the actual merge for this pull request (commit 88fb40b7ad4bbc2d525c63cadfa8b62e1307fb96) is so vastly different than the state this pull request was accepted in at this point I would practically demand that the original merge be reverted and the merge attempted again without all the extra changes (compare the changes for components/com_contact/views/contact/tmpl/default.php [from this pull request](https://github.com/joomla/joomla-cms/pull/8024/files#diff-d45144f87d62bf6574d28414d4e57c0a) with [the committed changes](https://github.com/joomla/joomla-cms/commit/88fb40b7ad4bbc2d525c63cadfa8b62e1307fb96#diff-d45144f87d62bf6574d28414d4e57c0a).  The diffs for these files alone do not align, not to mention the number of files changed in this pull request compared to the actual merge.

**Comment by ggppdk** [comment]
Any update on best way to fix the double event triggering ?

- will triggering be removed from the JViewLegacy class (and then the other relevant changes that depend on it) ?
- or all views like ContentViewCategory (extends JViewCategory) and other views in 3rd party extensions, will need to remove the triggering ?

Also 3 out of the 4 triggers are using ->core_params which does not exist
and 1 is using ->params that does exist

https://github.com/joomla/joomla-cms/blob/staging/libraries/legacy/view/category.php#L161-L168
```
$results = $dispatcher->trigger('onContentAfterTitle', array($this->extension . '.category', &$itemElement, &$itemElement->core_params, 0));
...
$results = $dispatcher->trigger('onContentBeforeDisplay', array($this->extension . '.category', &$itemElement, &$itemElement->core_params, 0));
...
$results = $dispatcher->trigger('onContentAfterDisplay', array($this->extension . '.category', &$itemElement, &$itemElement->core_params, 0));
...
```

Regarding the empty parameters, there is a report for it here:
https://github.com/joomla/joomla-cms/issues/8963

**Comment by ggppdk** [comment]
ok, my comment about 3rd party extensions is mostly wrong, only a very small number (if any) will need to be updated

because function commonCategoryDisplay which got the new code to trigger plugin event is inside JViewCategory and not inside JViewLegacy, and then double triggering is only if you call **parent::commonCategoryDisplay();**

**Comment by wilsonge** [comment]
I'm so sorry I forgot about this. I'm out today but will try and get back on this either this evening or tomorrow. Please ping me repeatedly on this if it feels like I've forgotten about the issue!

**Comment by ggppdk** [comment]
Besides fixing $itemElement->**core_params** (which does not exist) to be ->params

A simple and **clean** fix for the double category triggering is 
- add 1 parameter to the **signature** of method

**public function commonCategoryDisplay()**

at libraries/legacy/view/category.php   (class **JCategoryView**) so as to be:

**public function commonCategoryDisplay($trigger_events=false)**

----------------------------------------------------------------
Then update views that extend JCategoryView (and that also call **commonCategoryDisplay**) and for which default code for triggering events is good enough:
**com_weblinks\views\category\view.html.php
com_newsfeed\views\category\view.html.php
com_contact\views\category\view.html.php**
```
parent::commonCategoryDisplay($trigger_events=true);
```

And then views that **need a custom preparation** for plugin event triggering and want to do it **inside their own code**:
**com_content\views\category\view.html.php**
```
public function commonCategoryDisplay($trigger_events=false);
```

**Comment by ggppdk** [comment]
Also since plugin event trigger was added to the parent class (JViewCategory),
- adding this parameter is rather a **requirement** ??
otherwise it is rather inflexible, and any view wanting to do some extra preparation for plugin event triggering will need to skip the **commonCategoryDisplay** altogether and copy all its code inside the current view

**Comment by danyj** [comment]
Testing beta 2  this is still an issue #8963

**Comment by roland-d** [comment]
> Please ping me repeatedly on this if it feels like I've forgotten about the issue!

@wilsonge Pinging you as the discussion is still on-going.

**Comment by wojsmol** [comment]
Testing on latest staging double event triggering is still an issue see https://github.com/backbutton/content-plugin/issues/6

**Comment by wojsmol** [comment]
@wilsonge Pingig you regardig double event triggering.

**Comment by wilsonge** [comment]
Thankyou! I have left this up on my laptop and will have code to fix it on the way home from work this evening!

**Comment by wilsonge** [comment]
Fixed with https://github.com/joomla/joomla-cms/commit/fb4d375e14d33d2579e301c3e9d87d6115f94b97

**Pull request closed without merging**
