### PR TITLE
Emptystate layout is used for non-empty cache

### PR DESCRIPTION
**Pull request by Denitz**
### Summary of Changes

"You have no cached content." is displayed after deleting the filtered cache group.

### Testing Instructions

1. Ensure that Joomla caching is enabled, load frontend as guest
2. Go to Maintenance > Clear Cache in backend
3. Filter by any frontend-specific cache group, i.e. `com_content` in search field.
4. See single group filtered
5. Delete it
6. See "You have no cached content." layout without search field.

### Actual result BEFORE applying this Pull Request

Frustrating "You have no cached content." message on active search filter applied though we have non-filtered cache groups.
Search field is not visible.

### Expected result AFTER applying this Pull Request

See the usual empty table with "No Matching Results" message and visible search input.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by brianteeman** [comment]
I can confirm the issue.

Just wondering why its not the same as all the other emptystate with $this->get('IsEmptyState')

**Comment by Denitz** [comment]
@brianteeman Because `ListModel::getIsEmptyState()` uses a database query but com_cache is "databaseless" :)

**Comment by brianteeman** [comment]
Ok. Thanks for the explanation

**Comment by brianteeman** [comment]
tested ok

Its marked as an issue on the tracker so cant post  a result there

**Comment by Quy** [comment]
How about improving it by not displaying the first alert?

38671-clear-cache

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38671">issues.joomla.org/tracker/joomla-cms/38671</a>.</sub>

**Comment by obuisard** [comment]
Thank you @Denitz :-)

**Comment by Denitz** [comment]
Thank you! 1-line patch in 10 months, even after Brian's confirmation :(

**Comment by laoneo** [comment]
And this one line had a [bug](https://github.com/joomla/joomla-cms/pull/44349) :-)

**Pull request merged**
