### PR TITLE
[4.0][CLEAR CACHE] Build tools fixes

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # .

### Summary of Changes
- Replaces `build/build-modules-js/utils/rootpath.es6.js` with `const RootPath = process.cwd();`
- Replaces own script `build/build-modules-js/utils/make-dir.es6.js` with https://www.npmjs.com/package/fs-extra (18 million d/ls per week)
- Replaces own script `build/build-modules-js/utils/walk-sync.es6.js` with https://www.npmjs.com/package/walk-sync (1/2 million d/ls per week)

### Testing Instructions
Run `npm i` etc. Still get all the files in the media and templates

### Documentation Changes Required
NO

### But why?
When I was writing the build tools was extremely cautious to the number of dependencies that were required as I thought the less the faster the CI. In the meantime the project added quite a few more dependencies so it makes zero sense to keep the build tools lean if the same mentality is not shared across the board. Most importantly and quite honestly it should solve a problem on my other PR 

@wilsonge

### CODE REVIEW

**Comment by C-Lodder** [comment]
Why use `mkdirp` over `fs` (native)?
Just an FYI, you're creating directories with `0777` chmod permissions. Doesn't Joomla use `0755`?

**Comment by dgrammatiko** [comment]
@C-Lodder `mkdirp` Is creating all the given folders recursively. About permissions I was thinking how that thing will possibly react in the windows system but since I don’t do dos anymore I decided to leave the mode as is. You can test this with `mode: 0644` And let me know

**Comment by C-Lodder** [comment]
Check my template repo. Comitted something yesterday to build the folders recursively using FS

**Comment by dgrammatiko** [comment]
@C-Lodder nice but it seems that fs-extra already has this functionality so neither own code or another package is needed for recursive folder creation

**Comment by C-Lodder** [comment]
Shame Node don't use `fs-extra` natively. `fs` has some very annoying flaws in it :/

**Comment by wilsonge** [comment]
@brianteeman can you give this a quick run when you have a minute to ensure this still works on windows please

**Comment by brianteeman** [comment]
Will do after the 🏉

**Comment by wilsonge** [comment]
@SniperSister @rdeutz can you guys have a look at the ATT why drone isn't triggering for the last 2 builds of this PR please

**Comment by brianteeman** [comment]
@wilsonge npm i ran fine on windows. even seemed to be faster than before. Only thing to note is the following. No idea if its related to this PR or not so posting it

```
npm WARN acorn-dynamic-import@4.0.0 requires a peer of acorn@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN babel-loader@6.4.1 requires a peer of webpack@1 || 2 || ^2.1.0-beta || ^2.2.0-rc but none is installed. You must install peer dependencies yourself.
npm WARN sass-loader@5.0.1 requires a peer of webpack@^2.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN com_media@4.0.0 No repository field.
```

**Comment by dgrammatiko** [comment]
@brianteeman yes somehow we need to remove the node_modules in administrator/com_media. I can do it here or spin another PR

**Comment by rdeutz** [comment]
Just quick because ....

> The volume cache plugin reacts to special directives in a commit message to provide additional functionality. Include one of the following directives somewhere in your commit message to trigger their respective actions:
>
>[CLEAR CACHE]
    instruct the plugin to clear the entire cache. This only influences the restoring step, the plugin will still rebuild cache if instructed to do so.
>[NO CACHE]
    instruct the plugin not to restore or rebuild cache for this build.

**Comment by wilsonge** [comment]
@dgrammatiko looks like a legit drone failure now

**Comment by dgrammatiko** [comment]
But ESLint exists in the package.json

**Comment by wilsonge** [comment]
It's `mkdirp` that's missing from the dependencies according to the error?

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
