### PR TITLE
Add the correct exception after 11593 merge (was waiting for that merge)

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Summary of Changes

@rdeutz here you go.
Now with the correct exception (was waiting for https://github.com/joomla/joomla-cms/pull/11593 merge).
#### Testing Instructions

Just using the new exception.
Code review

### CODE REVIEW

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11606">issues.joomla.org/joomla-cms/11606</a>.</sub>

**Comment by andrepereiradasilva** [comment]
travis failure is relate dto JS tests, obviously not related to this PR.

**Comment by jeckodevelopment** [comment]
Travis is ok now!

**Comment by andrepereiradasilva** [comment]
ok thanks

**Comment by yvesh** [comment]
I have tested this item :white_check_mark: successfully on a4e363be41a577d0e5f3d6675f64d9c4ef57b875<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11606">issues.joomla.org/joomla-cms/11606</a>.</sub>

**Comment by brianteeman** [comment]
Setting RTC as we have two tests (one before a merge update)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11606">issues.joomla.org/joomla-cms/11606</a>.</sub>

**Pull request merged**
