### PR TITLE
Clean up the application.xml [codestyle]

### PR DESCRIPTION
**Pull request by zero-24**
#### Summary of Changes

I have just cleaned up the application.xml
#### Testing Instructions
- Go to the Global Configuration
- apply the patch
- Reload the Global Configuration
- confirm all looks still ok.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 57d3e4e7c1c1c135ddca89fe997c9253b3c9efc1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9670">issues.joomla.org/joomla-cms/9670</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 57d3e4e7c1c1c135ddca89fe997c9253b3c9efc1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9670">issues.joomla.org/joomla-cms/9670</a>.</sub>

**Comment by zero-24** [comment]
Thanks :smile: :+1:

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9670">issues.joomla.org/joomla-cms/9670</a>.</sub>

**Pull request merged**
