### PR TITLE
[4.0] cassiopeia font note

### PR DESCRIPTION
**Pull request by brianteeman**
Adds a title and formatting

Pull Request for Issue #33846 

### Before
image

### After
image

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 273fdc2949a973a33d193e51c47e063e4507c64a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33851">issues.joomla.org/tracker/joomla-cms/33851</a>.</sub>

**Comment by brianteeman** [comment]
grrrh

that was my (obviously) failed attempt at having an h4 in the same colour scheme as the message.

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 273fdc2949a973a33d193e51c47e063e4507c64a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33851">issues.joomla.org/tracker/joomla-cms/33851</a>.</sub>

**Comment by richard67** [comment]
@brianteeman Will you fix @Quy 's finding?

**Comment by brianteeman** [comment]
yes

**Comment by brianteeman** [comment]
As far as I can tell there is no option available to have a title AND for it to inherit the colors. So for now this PR just resolves the formatting issue and should look like
image

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on feff360a109d0883acec60f1f7f6bc3f24f21fef<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33851">issues.joomla.org/tracker/joomla-cms/33851</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on feff360a109d0883acec60f1f7f6bc3f24f21fef<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33851">issues.joomla.org/tracker/joomla-cms/33851</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33851">issues.joomla.org/tracker/joomla-cms/33851</a>.</sub>

**Comment by brianteeman** [comment]
thx

**Pull request merged**
