### PR TITLE
Add support for PHP-CS-Fixer

### PR DESCRIPTION
**Pull request by mbabker**
#### Summary of Changes

Adds support for the [PHP-CS-Fixer](https://github.com/FriendsOfPHP/PHP-CS-Fixer) tool as a means to help programmatically review and correct code style issues in PHP code.  This initial implementation only includes the non-third-party libraries directory code.
#### Testing Instructions

Review the package's documentation to ensure the selected fixers are in line with the project's code style rules and review the changes made (sorry it's a lot of files but it's either that or do a PR for a couple directories at a time) to ensure they are consistent with the project's code style rules.

Note some changes in here are more for consistency and behavior than a PHPCS enforcement such as changing `return null;` to `return;` or the trailing comma on multi-line arrays.

### CODE REVIEW

**Comment by photodude** [comment]
So this mostly just fixes coding standards issues related to PSR-1 and PSR-2?

**Comment by mbabker** [comment]
Without writing custom fixers pretty much.  It can also do some stuff we do
as a practice but not enforced in the standard like variable or array
key/value alignment.  Considering we're one of the few who have standards
vastly opposite of PSR-2 there's only so much that can be pulled from the
source repo.

**Comment by laoneo** [comment]
Thumbs up for the auto code fixer. To safely test this PR, why not breaking it into smaller peaces?

**Comment by photodude** [comment]
@laoneo We have another set of [auto code fixers with the in development update to PHPCS2](https://github.com/joomla/coding-standards/pull/109). There is still some work to be done verifying the code style coverage and testing/verifying the fixers.

**Comment by pritalpatel** [comment]
I have tested this item :red_circle: unsuccessfully on f4653fbebf9877c8ec392bf64412fde34f7e16ec<br /><br />While I was trying to apply patch using patch tester first it took long time to apply then suddenly getting white page. Enabled error reporting to development but still not showing any error and just showing white/blank page. There is nothing in view source as well. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10992">issues.joomla.org/joomla-cms/10992</a>.</sub>

**Comment by pritalpatel** [comment]
But when I have downloaded https://codeload.github.com/mbabker/joomla-cms/zip/phpcs-fixer and install joomla using it that works. 
I have tested joomla backend using gherkin scenarios and found it working.
screen shot 2016-07-04 at 09 12 57



_Note: I haven't tested as per given testing info._
> Review the package's documentation to ensure the selected fixers are in line with the project's code style rules

_but I have tested that after this patch joomla admin works normally or not._<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10992">issues.joomla.org/joomla-cms/10992</a>.</sub>

**Comment by pritalpatel** [comment]
I have tested this item :white_check_mark: successfully on f4653fbebf9877c8ec392bf64412fde34f7e16ec<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10992">issues.joomla.org/joomla-cms/10992</a>.</sub>

**Comment by pritalpatel** [comment]
Also wants to mention that I haven't checked all the area of admin. I have checked Users, Content, Category, Access Group and levels.

**Comment by bertmert** [comment]
I have tested this item :white_check_mark: successfully on f4653fbebf9877c8ec392bf64412fde34f7e16ec<br /><br />Checked all applied fixers with description at https://github.com/FriendsOfPhp/PHP-CS-Fixer
and compared with coding standards http://joomla.github.io/coding-standards/?coding-standards/chapters/php.md

Applied patch 2days ago. Joomla worked fine without any issues 'til now.

Code review for all files of this PR.

Tested .php_cs configuration with several 3rd-party libraries and custom extensions and added "wrong code styles". Success.

Couldn't find any break of Joomla Coding Standards produced by PHP-CS-Fixer. Just "nicer" code than before.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10992">issues.joomla.org/joomla-cms/10992</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10992">issues.joomla.org/joomla-cms/10992</a>.</sub>

**Comment by wilsonge** [comment]
@mbabker Rebase this please

**Comment by mbabker** [comment]
Done

**Pull request merged**
