### PR TITLE
[5.2] [REGRESSION] Fix menu and module list state filter

### PR DESCRIPTION
**Pull request by Hackwar**
Pull Request for Issue #43940 .

### Summary of Changes
This fixes a regression from #43230. When trashing a menu item or a module, it is still displayed in the list.

### Testing Instructions
Trash a menu item and a module.

### Actual result BEFORE applying this Pull Request
It is still displayed in the normal list view.

### Expected result AFTER applying this Pull Request
It is only displayed with filter set to "All" or "Trashed".

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by fgsw** [comment]
I have tested this item :white_check_mark: successfully on c8feb8a4342b50ac811a5422fc25fe7e3b671bdc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43941">issues.joomla.org/tracker/joomla-cms/43941</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on c8feb8a4342b50ac811a5422fc25fe7e3b671bdc<br /><br />Hope these are the last of the regressions<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43941">issues.joomla.org/tracker/joomla-cms/43941</a>.</sub>

**Comment by Hackwar** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43941">issues.joomla.org/tracker/joomla-cms/43941</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
