### PR TITLE
Add Bootstrap3 class names to debug plugin

### PR DESCRIPTION
**Pull request by stiplady**
Breaking changes were made between Bootstrap2.x and 3.0, http://getbootstrap.com/migration/

This commit adds the required changes to allow the debug panels to be useful when used with Bootstrap3 templates.

Bootstrap 2.x class names still intact for anyone still using Bootstrap 2.x

**Test instructions:**
Use a bootstrap 3 template
Enable debug in site configuration
View profile information
- Without this commit some of the labels and progress bars will be missing a background colour
- With this commit the labels and progress bars will be displayed with background colour

### CODE REVIEW

**Comment by nternetinspired** [comment]
:+1:  Good improvement. 

I know that the vast majority of commercial templates already use BS3 and this benefits all those template users today and without any appreciable detrimental affects to those using BS2.3.x templates, as there seem to be no css clashes.

Test successful; profile information in debug console is now useful again! Tested against Protostar and custom templates using BS3.2.1 and 3.2.2.

**Comment by 810** [comment]
+1

**Comment by N6REJ** [comment]
+1

Bear

**Comment by Bakual** [comment]
You need to fix codestyle issue for Travis to pass:
````
FILE: /home/travis/build/joomla/joomla-cms/plugins/system/debug/debug.php
--------------------------------------------------------------------------------
FOUND 0 ERROR(S) AND 1 WARNING(S) AFFECTING 1 LINE(S)
--------------------------------------------------------------------------------
 934 | WARNING | Line exceeds 150 characters; contains 156 characters
````

**Comment by Saurabh1** [comment]
That's a great improvement and I have tested too. It works as expected.
Yeah need to take care of code style issue. :-/

**Comment by stiplady** [comment]
@Bakual Code formatting updated, Travis has now passed.

**Comment by brianteeman** [comment]
Setting RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7560">issues.joomla.org/joomla-cms/7560</a>.</sub>

**Pull request merged**
