### PR TITLE
[4.0] Fix condition for php8 in articles, breadcrumbs

### PR DESCRIPTION
**Pull request by chmst**
Pull Request for Issue #31925 .

### Summary of Changes
Added casting to $category->id in condition

### Testing Instructions
see issue #31925

Test in php7 and php8

### CODE REVIEW

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on ab10d419c23daa58d2e32d46de5a14a3a8e6b4db<br /><br />Tested successfully in Beta7-dev of 13 January with PHP 7.4.14 and 8.0.1.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32027">issues.joomla.org/tracker/joomla-cms/32027</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on ab10d419c23daa58d2e32d46de5a14a3a8e6b4db<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32027">issues.joomla.org/tracker/joomla-cms/32027</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32027">issues.joomla.org/tracker/joomla-cms/32027</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
