### PR TITLE
[5.1] Use Dialog field for Modal_Category

### PR DESCRIPTION
**Pull request by Fedik**
### Summary of Changes

Changing `Modal_Category` field to use new modal dialog.
The same as https://github.com/joomla/joomla-cms/pull/40462 but for Category.

### Testing Instructions

Create a menu for category, 
Select/edit value in "Choose a Category" field

### Actual result BEFORE applying this Pull Request

Works

### Expected result AFTER applying this Pull Request

Works

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed
- [x] Pull Request link for manual.joomla.org: https://github.com/joomla/Manual/pull/178
- [ ] No documentation changes for manual.joomla.org needed

Reference:
- https://github.com/joomla/joomla-cms/pull/40462

### CODE REVIEW

**Comment by Fedik** [comment]
Will rebase it later, currently there some conflict with dron file.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 88cb998f936607050fd21bdf802efc51ade1af29<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42293">issues.joomla.org/tracker/joomla-cms/42293</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 88cb998f936607050fd21bdf802efc51ade1af29<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42293">issues.joomla.org/tracker/joomla-cms/42293</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42293">issues.joomla.org/tracker/joomla-cms/42293</a>.</sub>

**Comment by LadySolveig** [comment]
Thank you @Fedik !
And thanks to the diligent testers @viocassel @Quy

**Pull request merged**
