### PR TITLE
[5.1] Adminmenu: Toggle for duplicate menus

### PR DESCRIPTION
**Pull request by richard67**
Pull Request for Issue #32934 .

### Summary of Changes

Same as the 4.4-dev PR #43192 , but this here is for 5.1-dev.

As the modified file has been refactored in the 5.1-dev branch with PR #42784 , the change from PR #43192 cannot be merged up from 4.4-dev into 5.1-dev as it is.

Therefore I've created this PR here which does the same change as PR #43192 but at a different place due to the refactoring.

### Testing Instructions

See #43192 :
1. Create a second menu module in the administrator, assign it to the menu position and select the "Joomla Main Menu" preset for the module.
2. Click on the toggle button to close the sidebar.
3. Click on the "Content" menu item in the second module.

### Actual result BEFORE applying this Pull Request

The sidebar stays closed.

### Expected result AFTER applying this Pull Request

The sidebar opens, like for the menu entries in the first menu module.

### Link to documentations
Please select:
- [X] No documentation changes for docs.joomla.org needed

- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by exlemor** [comment]
I have tested this item :white_check_mark: successfully on 5c5801873abbcb63cdeeb5a893cfabf046d76831<br /><br />Hi Richard,

I was able to test this successfully. :)

Thanks for your hard work.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43308">issues.joomla.org/tracker/joomla-cms/43308</a>.</sub>

**Comment by fgsw** [comment]
I have tested this item :white_check_mark: successfully on 5c5801873abbcb63cdeeb5a893cfabf046d76831<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43308">issues.joomla.org/tracker/joomla-cms/43308</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43308">issues.joomla.org/tracker/joomla-cms/43308</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
