### PR TITLE
Contact default parameter (images, filter,  pagination)

### PR DESCRIPTION
**Pull request by AlexRed**
Pull Request for Issue #10901 .
### Summary of Changes

Set hide by default the parameter which have no effect until the first saving
### Testing Instructions

Set hide by default the parameter which have no effect until the first saving: Filter Field, Display Select, Image, in the TAB "List Layouts" for the Contacts: Options
### Documentation Changes Required

the old PR  #10902 and  #10912  seems inadeguate for the team  :(

### CODE REVIEW

**Comment by JamalTailored** [comment]
I have tested this item :white_check_mark: successfully on <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11640">issues.joomla.org/joomla-cms/11640</a>.</sub>

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11640">issues.joomla.org/joomla-cms/11640</a>.</sub>

**Comment by mbabker** [comment]
The default values in the PHP code using these params should be changed too for this to be accepted.

**Comment by AlexRed** [comment]
an indication, an help please. Where are the PHP code using these params?

**Comment by Bakual** [comment]
@mbabker The point of this PR is to get the default values in the XML inline with the ones in the PHP code (where there is none specified, so `0`) :smile:

**Comment by mbabker** [comment]
Well that would've been good to point out 😉

**Comment by AlexRed** [comment]
:smile::smile::smile:

**Comment by jeckodevelopment** [comment]
Can we go to RTC?

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11640">issues.joomla.org/joomla-cms/11640</a>.</sub>

**Pull request merged**
