### PR TITLE
Update tinymce to 4.5.7

### PR DESCRIPTION
**Pull request by brianteeman**
Version 4.5.7 (2017-04-25)
	Fixed bug with selection around inline contenteditable false would get collapsed incorrectly.
	Fixed bug where pasting on Microsoft Edge 40+ would produce clipboard fragment headers.

### CODE REVIEW

**Comment by brianteeman** [comment]
The appveyor error is unrelated to this pr

**Comment by brianteeman** [comment]
Tinymce 4.6 is not compatible with Joomla 3 due to it dropping ie8-10 support 
From https://www.ephox.com/blog/tinymce-4-6-update-looks-to-the-future-of-rich-text-editing/

> If you require IE 8-9-10 support, you should run the 4.5.x version of TinyMCE. This will be under long-term support and any critical fixes will be backported to this version.

**Comment by brianteeman** [comment]
Does someone have the ability to restart appveyor?

**Comment by zero-24** [comment]
IIRC @rdeutz can do this?

**Comment by rdeutz** [comment]
Yes I can but I think this one is too old or there is another reason why I can't. Just push a change to the branch and it should start again

**Comment by brianteeman** [comment]
oh blast that didnt work

**Comment by brianteeman** [comment]
I will redo this pr later

**Comment by rdeutz** [comment]
You can reset the head of your branch

**Comment by brianteeman** [comment]
@rdeutz i tried that and it failed so I did a new pr :(

**Pull request closed without merging**
