### PR TITLE
[com_content] Add icons layout

### PR DESCRIPTION
**Pull request by grig0ry**
Pull Request for Issue #10421 .
#### Summary of Changes

Added layouts for article icons.

### CODE REVIEW

**Comment by Grigory90** [comment]
Hmm, i tested my PR on current codebase(staging branch), there were no problems...

**Comment by andrepereiradasilva** [comment]
Code style

> FILE: ...me/travis/build/joomla/joomla-cms/layouts/joomla/content/icons/edit.php
> --------------------------------------------------------------------------------
> FOUND 1 ERROR(S) AFFECTING 1 LINE(S)
> --------------------------------------------------------------------------------
>  36 | ERROR | Whitespace found at end of line
> --------------------------------------------------------------------------------

See https://travis-ci.org/joomla/joomla-cms/jobs/129449460#L1321

**Comment by Grigory90** [comment]
@andrepereiradasilva, Thank you!

**Comment by memonica** [comment]
Can you  provide testing instructions?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10423">issues.joomla.org/joomla-cms/10423</a>.</sub>

**Comment by Grigory90** [comment]
@memonica

**1.** Copy **layouts/joomla/content/icons** and **layouts/joomla/content/icons.php** to **templates/protostar/html/layouts/joomla/content** 

**2.** Edit layouts

**3.** Go to article page and check the result.

**Comment by Grigory90** [comment]
Has anyone checked?

**Comment by AnishaVora** [comment]
Hello,
I have applied this patch and overridden icons layout successfully, but encountered following issue: Language variable on hover of the icon text does not get translated as shown in the below screenshot.

screen shot 2016-07-09 at 05 10 47

I have tested this on clean copy (without any sample data) of Joomla! 3.5.1. If i remove the patch and recheck then the language variables on icons are getting translated. But if I apply the patch, then the language variables (JGLOBAL_EDIT_TITLE, JGLOBAL_EMAIL_TITLE, and JGLOBAL_PRINT_TITLE) do not get translated.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10423">issues.joomla.org/joomla-cms/10423</a>.</sub>

**Comment by Grigory90** [comment]
@AnishaVora Thanks for the feedback! I checked again, this problem is not found. Tested on a clean Joomla 3.5.1 installation.
screen

**Comment by AnishaVora** [comment]
@Grigory90 
I have retested it on clean Joomla! 3.5.1 installation with blog sample data. When I hover over the edit icon, tool-tip is showing up properly as you have shown in the screenshot.

screen shot 2016-07-10 at 22 58 54

The language issue comes when I hover over the text ('edit', 'email' and 'print'), please see the given screenshots.

screen shot 2016-07-10 at 22 59 23

screen shot 2016-07-10 at 22 59 37<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10423">issues.joomla.org/joomla-cms/10423</a>.</sub>

**Comment by gunjanpatel** [comment]
I have tested this item :white_check_mark: successfully on c87b61ddbf4b07d8dd3fbfac323aa5324c0118e3<br /><br />Everything works fine for me. No language issue.

screen shot 2016-07-11 at 01 21 35

screen shot 2016-07-11 at 01 21 35

screen shot 2016-07-11 at 01 21 34

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10423">issues.joomla.org/joomla-cms/10423</a>.</sub>

**Comment by AnishaVora** [comment]
I have tested this item :white_check_mark: successfully on c87b61ddbf4b07d8dd3fbfac323aa5324c0118e3<br /><br />Re-tested it on the Joomla! 3.6.0-rc2 and Joomla! 3.5.1 (downloaded the package again and installed) and no language issue found. I guess, there was an issue of language in the main joomla installation.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10423">issues.joomla.org/joomla-cms/10423</a>.</sub>

**Comment by gunjanpatel** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10423">issues.joomla.org/joomla-cms/10423</a>.</sub>

**Comment by brianteeman** [comment]
@AnishaVora  Please only test against the current staging. There have been over 400 commits since Joomla 3.5.1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10423">issues.joomla.org/joomla-cms/10423</a>.</sub>

**Comment by AnishaVora** [comment]
@brianteeman Yes, I have tested on current staging as well as on Joomla! 3.5.1 stable release.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10423">issues.joomla.org/joomla-cms/10423</a>.</sub>

**Comment by brianteeman** [comment]
There is no point in testing on 3.5.1 ;)

On 11 July 2016 at 09:12, Anisha Tailored <notifications@github.com> wrote:

> @brianteeman <https://github.com/brianteeman> Yes, I have tested on
> current staging as well as on Joomla! 3.5.1 stable release.
> ------------------------------
> This comment was created with the J!Tracker Application
> <https://github.com/joomla/jissues> at issues.joomla.org/joomla-cms/10423
> <https://issues.joomla.org/tracker/joomla-cms/10423>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/10423#issuecomment-231668740>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABPH8cBsWZoL09ccjLlV1W_1xg18uek8ks5qUfr8gaJpZM4IcK46>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by wilsonge** [comment]
Merged to the 3.7 branch with https://github.com/joomla/joomla-cms/commit/60bc67bb6105f317fc98cc206bde0e1b45830dc0

**Pull request closed without merging**
