### PR TITLE
stop onchange handler being called twice when changing calendar field…

### PR DESCRIPTION
**Pull request by GeraintEdwards**
… value - fixes issue #33538

Pull Request for Issue # .

### Summary of Changes

Remove onchange function call from calendar.js - this is no longer needed since we now have a disptachEvent for the change event

### Testing Instructions

edit the file administrator/components/com_content/forms/article.xml and find the publish_up field at line 129 and add the attrribute

onchange="alert(0);"

to this field and then edit an article and change the publish_up field (using the date picker) 

### Actual result BEFORE applying this Pull Request

you will get the alert(0) being called twice 

### Expected result AFTER applying this Pull Request

alert(0) is called once

### CODE REVIEW

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on 7bc066790afc1b2002cd84776bc32cf6b54a883a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33540">issues.joomla.org/tracker/joomla-cms/33540</a>.</sub>

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on 7bc066790afc1b2002cd84776bc32cf6b54a883a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33540">issues.joomla.org/tracker/joomla-cms/33540</a>.</sub>

**Comment by Fedik** [comment]
can you please make the same for joomla 4?

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33540">issues.joomla.org/tracker/joomla-cms/33540</a>.</sub>

**Comment by GeraintEdwards** [comment]
Please see https://github.com/joomla/joomla-cms/pull/33731 for mirrored changes in Joomla 4

**Comment by HLeithner** [comment]
thanks

**Pull request merged**
