### PR TITLE
Issue#17932 -- Inconsistent suffix while duplicating modules

### PR DESCRIPTION
**Pull request by akritianand**
Pull Request for Issue #17932 .

### Summary of Changes
Originally: Duplicate created module (2), module (3)... and Save & Copy created module (copy)
Now: Duplicate and Save & Copy both create module (2), module (3)...
However titles created by both these buttons are independent, i.e., duplicating module will give module (1) and Save & Copy of module will also give module (1) (irrespective of whether it exists or not).

### Testing Instructions
In Module Manager select/check a module.
-     Click button Duplicate.
-     The title of copy has a postfix (2).
-     Now open a module by clicking the title link.
-     Click button Save as Copy.
-     The title of copy gets a postfix (copy).

### Expected result
Uniform module title.

### Actual result
As mentioned above

### Documentation Changes Required
None.

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :red_circle: unsuccessfully on af24b7347d36cd1c50fcadaa3f3e2758fb1b5cab<br />
- by click on Button "Duplicate" got 2nd Module `Web Links (2)` (works)
- open Module `Web Links` and click `Save as Copy` got 3rd Module `Web Links (2)` (wrong):

bildschirmfoto 2017-09-14 um 08 09 28

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17951">issues.joomla.org/tracker/joomla-cms/17951</a>.</sub>

**Comment by akritianand** [comment]
I have a doubt in syntax.
I am trying to execute this:   
                             $var = $data['title'];
				$db    = $this->getDbo();
				$query = $db->getQuery(true);
				$query
				    ->select('title')
				    ->from('#__modules')
				    ->where('title = '. $var);
				$db->setQuery($query);
				try
				{
					$db->execute();
					while($row = $db->loadRowList()) {
					//some code
                                         }				
				}
				catch (RuntimeException $e)
				{
					$this->setError($e->getMessage());
					return false;
				}       
Now $var here is modulename (1). But it shows this error when excecuting: Save failed with the following error: SQLSTATE[42000]: Syntax error or access violation: 1305 FUNCTION joomla.modulename (1) does not exist. 
Can you tell me where I am wrong?
Thank you.

**Comment by akritianand** [comment]
In fact it is treating modulename (1) as a function. So if I remove (1) I get a different error: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'modulename' in 'where clause'. :/

**Comment by mbabker** [comment]
1) Commented code shouldn't be committed, that's what version control is for 😉 
2) Are the calendar JavaScript changes related to this?

**Comment by akritianand** [comment]
@mbabker 1. I didn't realise that I had left them as it is. 
2. They are part of previous pull request I had submitted.

**Comment by brianteeman** [comment]
@akritianand you need to use a separate branch for each pull request so that a PR only contains the changed files for this PR

**Comment by akritianand** [comment]
@brianteeman Oh sorry. I reverted all my changes. Now my pull request only contains the changes for this PR.

**Comment by brianteeman** [comment]
@akritianand as you can see that didnt work as it is now showing 195 changed files

**Comment by akritianand** [comment]
@brianteeman I updated my branch with the latest joomla repository. So that there are no conflicts.

**Comment by brianteeman** [comment]
screenshot_20170916-222920

**Comment by Quy** [comment]
This is no longer an issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17951">issues.joomla.org/tracker/joomla-cms/17951</a>.</sub>

**Pull request closed without merging**
