### PR TITLE
[4.0] Allowing client filtering in Installed languages manager

### PR DESCRIPTION
**Pull request by infograf768**
### Summary of Changes
As title says

### Before patch
No way to switch from site to admin client installed languages

Screen Shot 2019-04-13 at 07 27 38

### After patch
Filter display

Screen Shot 2019-04-13 at 07 25 31

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 364332917ad131e422f677b78ff9badb0accd70a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24572">issues.joomla.org/tracker/joomla-cms/24572</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 364332917ad131e422f677b78ff9badb0accd70a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24572">issues.joomla.org/tracker/joomla-cms/24572</a>.</sub>

**Comment by ghost** [comment]
Status "Ready To Commit".

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
