### PR TITLE
[5.1] Remove an unneeded variable

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # .

### Testing Instructions
Code review

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on c98bf4aaf98c963680be0fab9c0031fcf1c26af8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43763">issues.joomla.org/tracker/joomla-cms/43763</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on c98bf4aaf98c963680be0fab9c0031fcf1c26af8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43763">issues.joomla.org/tracker/joomla-cms/43763</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43763">issues.joomla.org/tracker/joomla-cms/43763</a>.</sub>

**Comment by LadySolveig** [comment]
Thank you @dgrammatiko  and for review @Quy  @viocassel

**Pull request merged**
