### PR TITLE
[4.1] s/formater/formatter

### PR DESCRIPTION
**Pull request by brianteeman**
Use english not german

I _think_ this also fixes a bug

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 91edb9939b3f1c6e353df5059323384d00e4882b<br /><br />Code review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36825">issues.joomla.org/tracker/joomla-cms/36825</a>.</sub>

**Comment by Quy** [comment]
There are more instances in other files.

**Comment by richard67** [comment]
> There are more instances in other files.

@Quy I've only found a lot in vendor files, libraries/vendor/maximebf/debugbar.

**Comment by Quy** [comment]
Nevermind.

**Comment by richard67** [comment]
Hmm, maybe a typo in the maximebf/debugbar requires us to use that typo in our debug plugin? In this case this PR here would break debugging.

E.g. in libraries/vendor/maximebf/debugbar/src/DebugBar/DataCollector/MessagesCollector.php is used `$this->dataFormater`.

**Comment by richard67** [comment]
I have not tested this item.<br /><br />Reverting my test since not sure anymore if it breaks debugging, since libraries/vendor/maximebf/debugbar has that typo, too. It could be just a copy and paste, or it could be that we use this 3rd party dependencies' objects, then we would have to keep that typo.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36825">issues.joomla.org/tracker/joomla-cms/36825</a>.</sub>

**Comment by Quy** [comment]
It breaks.

> PHP Notice:  Undefined property: Joomla\Plugin\System\Debug\DataCollector\SessionCollector::$dataFormatter in \plugins\system\debug\src\AbstractDataCollector.php on line 59

**Comment by brianteeman** [comment]
ok - closing as the upstream library is not under our control

**Pull request closed without merging**
