### PR TITLE
[4.0] com_tags unused strings

### PR DESCRIPTION
**Pull request by brianteeman**
This PR removes some legacy strings that are not used.

Code Review - search for any use of the strings

### CODE REVIEW

**Comment by adj9** [comment]
I have tested this item :white_check_mark: successfully on 19a6c402590bd47a7ecc2d730cf200d4a6db32a2<br /><br />code optimized :) <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31625">issues.joomla.org/tracker/joomla-cms/31625</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 19a6c402590bd47a7ecc2d730cf200d4a6db32a2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31625">issues.joomla.org/tracker/joomla-cms/31625</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31625">issues.joomla.org/tracker/joomla-cms/31625</a>.</sub>

**Comment by chmst** [comment]
Thanks!

**Comment by brianteeman** [comment]
thx

**Pull request merged**
