### PR TITLE
[4.0] More userfriendly description for menu Item type Category List

### PR DESCRIPTION
**Pull request by chmst**
Replace PR #31115

### Summary of Changes
Better description of list Categories List Views in contact,, news feed  and article.

category list

### Testing Instructions
Make new menu items for contact, news feed, articles

### Actual result BEFORE applying this Pull Request
grafik

### Expected result AFTER applying this Pull Request
The menu item description is clearer 

grafik

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 3f3655de1c521c84e23a9d42b1e31fd72e878cd6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32698">issues.joomla.org/tracker/joomla-cms/32698</a>.</sub>

**Comment by rdeutz** [comment]
@brianteeman could you have a look at the wording, thanks

**Comment by sksuryan** [comment]
image

Just one question, shouldn't it show "Article Category Tree" in the heading? Because I saw a change specifically for it in `administrator/language/en-GB/com_categories.sys.ini` if I'm not wrong.

**Comment by ChristineWk** [comment]
Not sure :-)
Maybe shorted to:
List All Categories in a Category Tree - because "Contacts" already there.

**Comment by brianteeman** [comment]
I prefer consistency but there are two different styles here
"Shows a list of all categories in the selected category tree."
"Shows a list of categories within a contact category tree"

technicaly it is "in" not "within" as it includes the top level item in the tree as within==inside
So can we please change them all to match the first example
ie "Shows a list of all categories in the selected contact category tree."


These two need to be swapped
COM_CONTENT_CATEGORIES_VIEW_DEFAULT_TITLE="List All Categories in a Category Tree"
COM_CATEGORIES_CATEGORIES_VIEW_DEFAULT_TITLE="List All Categories in an Article Category Tree"

**Comment by brianteeman** [comment]
and I agree with @ChristineWk about shortening all the titles

**Comment by webfeuerflo** [comment]
I tested it suscessfully with the patchtester on 4.0.0.-beta5

**Comment by sksuryan** [comment]
I think the intention was to keep it clear for the user once they have selected the option. It could be that the option in Article section was missed because Contacts and News feed have it. Rest, @chmst could comment on it better.

**Comment by chmst** [comment]
Thanks for testing and advice.  For articles, contacts and news feeds the strings should follow now  the suggestion of @brianteeman

**Pull request merged**
