### PR TITLE
[4.0] Codestyle: Cleaning up Generic.Strings.UnnecessaryStringConcat

### PR DESCRIPTION
**Pull request by Hackwar**
This fixes a few exclusions from the joomla/cms-coding-standards. This should only be a codereview.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 20f7a7c679a3254d2da9bbf7c782f7be1f729c62<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26627">issues.joomla.org/tracker/joomla-cms/26627</a>.</sub>

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on 20f7a7c679a3254d2da9bbf7c782f7be1f729c62<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26627">issues.joomla.org/tracker/joomla-cms/26627</a>.</sub>

**Comment by SharkyKZ** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26627">issues.joomla.org/tracker/joomla-cms/26627</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
