### PR TITLE
[4.0] Rename the MVC classes to fit the new suffix change

### PR DESCRIPTION
**Pull request by laoneo**
As changed in #17681, every MVC class in a component needs to end with it's corresponding type. So the articles model gets the name ArticlesModel. This pr changes all the core component classes to that change. Additionally it includes the neccessary controller changes intorduced in pr #17624.

### CODE REVIEW

**Comment by dgrammatiko** [comment]
@wilsonge can yo merge this? we need it for the Media manager sprint

**Comment by wilsonge** [comment]
Not without taking the time to merge up the corresponding staging commit - otherwise everything will be broken ;) Aim is to do it tonight as I told Allon yesterday

**Comment by laoneo** [comment]
This commit is included in the pr as well.

**Comment by laoneo** [comment]
https://github.com/joomla/joomla-cms/pull/17935/commits/2f54ca3cfafe723de10487f7b90997b9ad286337

**Comment by infograf768** [comment]
Looks this has broken the managers when changing status of an item.
For example articles
`An error has occurred.

    404 View not found [name, type, prefix]: articlescontroller, html, `

**Comment by laoneo** [comment]
@infograf768 #18063 should fix the issue.

**Pull request merged**
