### PR TITLE
Config Redirects - blue bar with Fieldset Description

### PR DESCRIPTION
**Pull request by pe7er**
Most **Component Configuration Options** have under the option tab **a blue bar with a description**

### Summary of Changes

This PR **adds a blue bar** with description **to Redirect: Options**.

#### Before the PR:
backend: System > Global Configuration > (in Left menu) Redirects > [**Advanced**]

info-label-options-redirect-advanced-before

#### After the PR:
backend: System > Global Configuration > (in Left menu) Redirects > [**Advanced**]

info-label-options-redirect-advanced-after

### CODE REVIEW

**Comment by ciar4n** [comment]
I have tested this item :white_check_mark: successfully on c3ebafa55e0ce05acd91282157eb362d66639ae9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12091">issues.joomla.org/joomla-cms/12091</a>.</sub>

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on c3ebafa55e0ce05acd91282157eb362d66639ae9<br /><br />Works<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12091">issues.joomla.org/joomla-cms/12091</a>.</sub>

**Comment by zero-24** [comment]
Can you have a look here @brianteeman ?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12091">issues.joomla.org/joomla-cms/12091</a>.</sub>

**Comment by RonakParmar** [comment]
I have tested this item :white_check_mark: successfully on c3ebafa55e0ce05acd91282157eb362d66639ae9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12091">issues.joomla.org/joomla-cms/12091</a>.</sub>

**Comment by brianteeman** [comment]
This string is not 100% accurate

**Comment by pe7er** [comment]
Thanks for testing @ciar4n @zero-24 @RonakParmar !
What string would be accurate? @brianteeman

**Comment by brianteeman** [comment]
Having looked at it again I just dont see the need for this blue bar text at all. Its not adding anything to the UI and its just text for the sake of having text

**Comment by pe7er** [comment]
Sorry, I do not agree.
**If every Options tab starts with a blue bar with some information**, the UI for Options **will be consistently the same** on all Option Tabs. That way an admin has an extra visual pointer (besides the "Options" in the Page Title) that they are on the Options page.

**Comment by brianteeman** [comment]
I don't agree in adding help text if it has no meaning or value. That has
the effect of users just ignoring it. It should only exist if it is
required information

**Comment by korneliusz401** [comment]
I has been tested succesfully ✅.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12091">issues.joomla.org/tracker/joomla-cms/12091</a>.</sub>

**Comment by brianteeman** [comment]
Closed for the reasons stated above and elsewhere

**Pull request closed without merging**
