### PR TITLE
[4.2] Fixes the watch build for media manager

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # .

### Testing Instructions

- Run the `npm run watch:com_media`

### Actual result BEFORE applying this Pull Request

Broken

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by carlitorweb** [comment]
@dgrammatiko thank you!

**Comment by carlitorweb** [comment]
I have tested this item :white_check_mark: successfully on 63d3b496cafb670f02aa3c30dfdb3031c82e76d0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39690">issues.joomla.org/tracker/joomla-cms/39690</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 63d3b496cafb670f02aa3c30dfdb3031c82e76d0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39690">issues.joomla.org/tracker/joomla-cms/39690</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39690">issues.joomla.org/tracker/joomla-cms/39690</a>.</sub>

**Comment by fancyFranci** [comment]
Thank you a lot! It is so much easier with the watch mode.

**Pull request merged**
