### PR TITLE
[4.1] TinyMCE option to initially paste text without formatting

### PR DESCRIPTION
**Pull request by laoneo**
Pull Request for forum post https://forum.joomla.org/viewtopic.php?t=971958.

### Summary of Changes
Adds an option that text pasted into an editor field of TinyMCE will be without formatting. This can be controlled on a set level.

Basically it controls this TinyMCE option https://www.tiny.cloud/docs/plugins/opensource/paste/#paste_as_text

### Testing Instructions
- Set the "Paste As Text" option to "On" in TinyMCE plugin in all sets.
- Open the article form
- Copy text from this pr description with links into the description field

### Actual result BEFORE applying this Pull Request
Formatting with links is inserted.

### Expected result AFTER applying this Pull Request
Only raw text is inserted with new lines.

### CODE REVIEW

**Comment by brianteeman** [comment]
do we really need another option when you can paste as text already

image

**Comment by laoneo** [comment]
Sure, because this is not a view where you can do an override. So the only way is to add new options.

Pasting text is especially helpful when you have a forum or ticket tool, where users paste blindly any kind HTML into the form.

**Comment by bembelimen** [comment]
I think this option is very useful, but I guess 4.1 as it's a feature?

**Comment by laoneo** [comment]
I would more say it is an enhancement

**Comment by laoneo** [comment]
Ok, changed to 4.1.

**Comment by dgrammatiko** [comment]
I have tested this item :white_check_mark: successfully on 2c00ed671fc22b66d132821a1b45c98d1a763b95<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36328">issues.joomla.org/tracker/joomla-cms/36328</a>.</sub>

**Comment by dgrammatiko** [comment]
I have tested this item :white_check_mark: successfully on db16d2d61eb44c12c00eb962ef0a26af5c608caf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36328">issues.joomla.org/tracker/joomla-cms/36328</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on db16d2d61eb44c12c00eb962ef0a26af5c608caf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36328">issues.joomla.org/tracker/joomla-cms/36328</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36328">issues.joomla.org/tracker/joomla-cms/36328</a>.</sub>

**Comment by laoneo** [comment]
@bembelimen the System tests errors are not related to this pr

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
