### PR TITLE
Add missing variable to light theme

### PR DESCRIPTION
**Pull request by coolcat-creations**
Pull Request for Issue [# .](https://github.com/joomla/joomla-cms/pull/42986#issuecomment-1991930151)

### Summary of Changes
Add missing variable in light mode

### Actual result BEFORE applying this Pull Request
Before this PR
grafik

### Expected result AFTER applying this Pull Request
grafik

### CODE REVIEW

**Comment by brianteeman** [comment]
should it not be the same as elsewhere eg com_categories
image

**Comment by coolcat-creations** [comment]
Yes it should. I dont know why people decide to use different classes for same things all over the backend. That makes things really hard. :-)

**Comment by brianteeman** [comment]
I would fix the markup to use the correct class rather than the css

**Comment by coolcat-creations** [comment]
Ok then I need a decision if this should be a btn-secondary or in all other views a btn-info
Anyway this PR is good to fix any appeareance of btn-info if used somewhere

**Comment by brianteeman** [comment]
I did an additional PR for the markup #43120

**Review by wilsonge — APPROVED** [review]

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 2d367a0a7ddfe352cde1f1b05b3a055867fb1888<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43117">issues.joomla.org/tracker/joomla-cms/43117</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 2d367a0a7ddfe352cde1f1b05b3a055867fb1888<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43117">issues.joomla.org/tracker/joomla-cms/43117</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43117">issues.joomla.org/tracker/joomla-cms/43117</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
