### PR TITLE
Testing Environment based on Codeception

### PR DESCRIPTION
**Pull request by nibra**
Pull Request for Issue #10744.

> Note: The great number of changed files is caused by updated dependencies in the vendor folder.
#### Summary of Changes

Current PHPUnit tests are moved to tests.phpunit.
Codeception was added as test framework.
Test structure for Codeception was added.
**Requires PHP 5.5**
#### Testing Instructions

Tests work in Travis, so no manual testing needed.

### CODE REVIEW

**Comment by mbabker** [comment]
This PR can't be tested/reviewed/acted upon until a proper 4.0 project has started somewhere.  Also this PR can't be considered for 3.x since it raises minimum PHP dependencies.  My suggestion is to close this until there's a proper 4.0 branch/project somewhere then this PR be opened against that.

// @wilsonge

**Comment by nibra** [comment]
Raising the PHP requirements is already in the pipeline.
So, instead of closing this, opening a 4.0-dev branch makes more sense to me.

**Comment by mbabker** [comment]
You'd still have to close & re-open the PR against that branch unless whomever is maintaining it will manually cherry-pick this PR onto it or GitHub finally added the feature that lets you change a PR's target branch.

I'm just trying to save time for folks looking at PRs right now so they aren't looking at or commenting on stuff that isn't applicable.

**Comment by nibra** [comment]
Ah ok, got you.

**Comment by brianteeman** [comment]
We really want to try and not turn the issue tracker into a to-do list

**Comment by mbabker** [comment]
Whatever space Joomla 4 ever ends up living in is either going to have a GitHub issue log full of todo tasks or require an external resource as a project management board for items like that.  It's not something that can be avoided unfortunately.

**Comment by mbabker** [comment]
@rdeutz As this is your team's area if this is something we want to work on IMO we probably should come up with a migration plan.

**Comment by rdeutz** [comment]
A proper plan would be great, maybe we can sit together at JAB17, closing it for now.

**Pull request closed without merging**
