### PR TITLE
[com_fields] Don't default to all user fields to show

### PR DESCRIPTION
**Pull request by laoneo**
Pull Request for Issue #14392.

### Summary of Changes
Don't default to all user groups to show on contact fields. Like it is now it is not possible to prevent to show the user custom fields on the contact details. This pr removes the hardcoded default value "All".

### Testing Instructions
Clear the "Show User Custom Fields" option in the contact options.
image

### Expected result
Keep empty.

### Actual result
Defaults the value to "All".

### CODE REVIEW

**Comment by gwsdesk** [comment]
I have tested this item :red_circle: unsuccessfully on d140e0faa390df31660039ba78535c7dc7ce5bdd<br /><br />I have tested this unsuccessfully See https://www.screencast.com/t/dDPWttlRH<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14407">issues.joomla.org/tracker/joomla-cms/14407</a>.</sub>

**Comment by gwsdesk** [comment]
See the reason and what is happening https://www.screencast.com/t/dDPWttlRH<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14407">issues.joomla.org/tracker/joomla-cms/14407</a>.</sub>

**Comment by laoneo** [comment]
I don't have flash :see_no_evil:

**Comment by gwsdesk** [comment]
Not sure @laoneo 
If I empty the field and save I get the broken cut text. If I load the options initially the "All"is given in the field entry. Changing it to empty and successively saving and reloading gives that behavior. So not sure actually what should be shown after empty and save.....should it show "all" or empty (with correct text)

**Comment by laoneo** [comment]
It should be an empty select box as in your screencast. The broken text is a "bug" in the template as discussed in #13594. So I guess we should handle the cut text problem in the issue. Is the rest working as expected?

**Comment by gwsdesk** [comment]
Correct works as expected for the prevention so will change the test result Thanks Allon

**Comment by gwsdesk** [comment]
I have tested this item :white_check_mark: successfully on d140e0faa390df31660039ba78535c7dc7ce5bdd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14407">issues.joomla.org/tracker/joomla-cms/14407</a>.</sub>

**Comment by coolcat-creations** [comment]
I have tested this item :red_circle: unsuccessfully on d140e0faa390df31660039ba78535c7dc7ce5bdd<br /><br />The userfields are still show, although nothing is selected<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14407">issues.joomla.org/tracker/joomla-cms/14407</a>.</sub>

**Comment by laoneo** [comment]
Is it empty in the menu configuration and the global contact options?

**Comment by coolcat-creations** [comment]
Yes both are empty, also created a completely new one as the existing failed, but also no luck

**Comment by brianteeman** [comment]
I have tested this item :red_circle: unsuccessfully on d140e0faa390df31660039ba78535c7dc7ce5bdd<br /><br />I created a user field group called testgroup
I create a user text field called textfield
I created a contsct and linked it to a user
I created a menu item to display a single contact
I checked that the option field did not have a category set
The contact is displayed on the front end with both the group and its fields

Just  a guess but instead of having it blank would it not be better to have a NONE setting
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14407">issues.joomla.org/tracker/joomla-cms/14407</a>.</sub>

**Comment by laoneo** [comment]
The important point is that the setting in the global contact options is not defaulted to all. So make sure that you can save it with no value selected and it stay like that:
image

As soon as I select a group or All, then the fields do show up, but when none is selected, then no fields should be shown.

**Comment by brianteeman** [comment]
As stated above in my report it is not enough for the options page to show no value. it actually has to work in that way which it doesnt

**Comment by laoneo** [comment]
I'v just tested it with your instructions and when the field is empty, then it shows no fields on the contact page. So for me it is working as expected. I'v just tested it with the latest staging.

**Comment by brianteeman** [comment]
ok let me test again with latest staging

**Comment by brianteeman** [comment]
Tested again

fields

**Comment by brianteeman** [comment]
Ignore me I was being an idiot. All good

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 691b8cfb80835060603b910f7a2ec546a0236aee<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14407">issues.joomla.org/tracker/joomla-cms/14407</a>.</sub>

**Comment by laoneo** [comment]
Glad to hear.

**Comment by laoneo** [comment]
@gwsdesk can you test it again as it doesn't count your test because of the upstream merge. Thanks.

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 691b8cfb80835060603b910f7a2ec546a0236aee<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14407">issues.joomla.org/tracker/joomla-cms/14407</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful testes.

**Pull request merged**
