### PR TITLE
[4] Solve Logo overflow over the header title

### PR DESCRIPTION
**Pull request by simbus82**
Pull Request for Issue #35264 .

### Summary of Changes
Added and overflow: hidden.

### Testing Instructions
Use the Toggle Menu and see effect

### Actual result BEFORE applying this Pull Request
issue-solved-joomla-2

### Expected result AFTER applying this Pull Request
issue-solved-joomla-3

### Documentation Changes Required

No

### CODE REVIEW

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on 0e24e687b3cf662d1e2e8f224188c162275174e5<br /><br />Not that obvious to spot as the menu opens rather quickly. Fix works. Don't forget to build the CSS.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35266">issues.joomla.org/tracker/joomla-cms/35266</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 0e24e687b3cf662d1e2e8f224188c162275174e5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35266">issues.joomla.org/tracker/joomla-cms/35266</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35266">issues.joomla.org/tracker/joomla-cms/35266</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Comment by simbus82** [comment]
Thanks!

**Pull request merged**
