### PR TITLE
Backport Possible missing break in bin\keychain.php at line 77? to the CMS

### PR DESCRIPTION
**Pull request by zero-24**
This Backports the fix from the framework into the CMS:
https://github.com/joomla-framework/keychain/commit/7e6488d7e3b395f47e202779f2a247318f5a3bad

Thanks goes to @photodude here: https://github.com/joomla/joomla-cms/issues/6672

### CODE REVIEW

**Comment by photodude** [comment]
@zero-24 Thanks for the acknowledgment. Glad to see this fix going into place.

**Comment by Kubik-Rubik** [comment]
@zero-24 You PR can not be merged because it produces merge conflicts. Your staging is over 300 commits behind the current state! Please update your fork and the PR against the current state. Thank you!

**Comment by brianteeman** [comment]
@Kubik-Rubik you need to look at the method you are using to apply this. There is only one file changed in this PR and that file has not been changed for 4 months. The merge issue is due to the way YOU are doing it. There is nothing wrong with the PR or any need for it to be updated

**Comment by mbabker** [comment]
Merge on review (and since it's the same fix applied in the Framework repo)

**Comment by roland-d** [comment]
@brianteeman I have tried to merge the same branch and I get the same errors. I am not doing this in any way different than the other PRs. Why should I? Perhaps I am doing it wrong as well and don't know how to do it. There are other ways to merge but we are trying to keep our log clean.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6883">issues.joomla.org/joomla-cms/6883</a>.</sub>

**Comment by brianteeman** [comment]
Well @mbabker managed to do it :)

**Comment by zero-24** [comment]
@roland-d @Kubik-Rubik hmm i guess the problem is that i have 2 accounts (zero-24 and zero24). One with push access and one without push access :smile: 

This branche is 300+ commits behind staging
https://github.com/zero-24/joomla-cms/tree/patch-5

But this (is the branche of the patch)
https://github.com/zero24/joomla-cms/tree/patch-5

is ok. Sorry that this is confused.

**Comment by brianteeman** [comment]
That shouldnt make any difference. It is not reasonable to expect all pull
requests to always be up to date with current staging.

**Comment by Kubik-Rubik** [comment]
@zero-24 Yes, this was the problem. We used the account that you use actively here... The "zero24" branch works without a problem.
@brianteeman Haha, yes, push the green button! :-D By the way, you can not know the way how we  in the PLT do the commits properly (no, not the merge button at GitHub), so your comments are acceptable!

**Comment by mbabker** [comment]
Just remember there are a few people not on PLT who may review/merge patches that should be kept in the loop on policy decisions...

**Comment by Kubik-Rubik** [comment]
@mbabker I'm talking about squashing all commits of the PR first in one on your local machine to avoid a mess in the history.

**Comment by mbabker** [comment]
Not always necessary, especially when the PR is only a single commit (like this one), unless you're trying to avoid the "merged PR whatever" commits, then someone decided something and forgot to tell me.

**Comment by Kubik-Rubik** [comment]
@mbabker This is something we want to discuss at the PLT summit after JAB and establish a policy rule.

**Comment by brianteeman** [comment]
As @mbabker said you need to make sure ALL people with commit rights know

**Pull request merged**
