### PR TITLE
Issue #26662: Admin section modal buttons do not have had any visual effects on hover. Added CSS to highlight the hovering.

### PR DESCRIPTION
**Pull request by vijaykhollam**
Pull Request for Issue #26662

### Summary of Changes

Admin section modal buttons do not have had any visual effects on hover. Added CSS to highlight the hovering.

### Testing Instructions

- Go to manage menu
- Click on edit module
- Hover on the Cancel, Save & close option

### Expected result

On the button hovering, it should highlight based on its type. Close should be red, save buttons should be green.

### Actual result

On the button hovering, colors are not changing.

### Documentation Changes Required

No

### CODE REVIEW

**Comment by pvdv63** [comment]
I have tested this item :red_circle: unsuccessfully on 23e49394c2d190819e8148e89fa4749221205a48<br /><br />After applying the test I got this message:

Warning: require(C:\xampp7310\htdocs\Joomla400\libraries\vendor\composer/../hoa/consistency/Prelude.php): failed to open stream: No such file or directory in C:\xampp7310\htdocs\Joomla400\libraries\vendor\composer\autoload_real.php on line 66

Fatal error: require(): Failed opening required 'C:\xampp7310\htdocs\Joomla400\libraries\vendor\composer/../hoa/consistency/Prelude.php' (include_path='C:\xampp7310\php\PEAR') in C:\xampp7310\htdocs\Joomla400\libraries\vendor\composer\autoload_real.php on line 66
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26678">issues.joomla.org/tracker/joomla-cms/26678</a>.</sub>

**Comment by joeykrop** [comment]
I have tested this item :white_check_mark: successfully on 23e49394c2d190819e8148e89fa4749221205a48<br /><br />Worked as expected.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26678">issues.joomla.org/tracker/joomla-cms/26678</a>.</sub>

**Comment by hildaabbing** [comment]
I have tested this item :white_check_mark: successfully on 23e49394c2d190819e8148e89fa4749221205a48<br /><br />It works!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26678">issues.joomla.org/tracker/joomla-cms/26678</a>.</sub>

**Comment by SharkyKZ** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26678">issues.joomla.org/tracker/joomla-cms/26678</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by klucon** [comment]
I have tested this item :white_check_mark: successfully on 23e49394c2d190819e8148e89fa4749221205a48<br /><br />Works! <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26678">issues.joomla.org/tracker/joomla-cms/26678</a>.</sub>

**Pull request merged**
