### PR TITLE
[4][com_actionlogs] missed load plugin languages

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #28540.

### Summary of Changes
load language from:

- plg_system_privacyconsent
- plg_user_terms

### Testing Instructions

enable user term plugin  - register a new user and consent to the terms and conditions during registration.
enable sytem privacy plugin - and consent to the privacy policy.

on dashboard Latest Actions module check that string are translated correctly

### Actual result BEFORE applying this Pull Request

image

### Expected result AFTER applying this Pull Request

image

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Kostelano** [comment]
I have tested this item :white_check_mark: successfully on d1456e9657281cfefbd40c97e66a38aaee12f9c9<br /><br />This works, thanks. A very old mistake.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42562">issues.joomla.org/tracker/joomla-cms/42562</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on d1456e9657281cfefbd40c97e66a38aaee12f9c9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42562">issues.joomla.org/tracker/joomla-cms/42562</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42562">issues.joomla.org/tracker/joomla-cms/42562</a>.</sub>

**Comment by MacJoom** [comment]
@alikon Thanks for the PR - can you think of reason why drone is failing at administrator/components/com_privacy/Consent.cy.js for psql?

**Comment by alikon** [comment]
somekind of "duplicate key value violates unique constraint cpostgres_users_pkey"

**Comment by richard67** [comment]
> somekind of "duplicate key value violates unique constraint cpostgres_users_pkey"

Reason could be that some users are inserted into the database with given ID in the insert statement, but on postgresql the sequence value for the ID column is not updated after that.

**Comment by MacJoom** [comment]
Thank you!

**Pull request merged**
