### PR TITLE
Module Positions not show in com_user settings - Fix for issue #38705

### PR DESCRIPTION
**Pull request by coolcat-creations**
Write the field type different to fix issue https://github.com/joomla/joomla-cms/issues/38705

Pull Request for Issue #38705 .

### Summary of Changes
Changed the field Name, maybe because of Case Sensitive Servers?

### Testing Instructions
If you experience that you have no Module Position selectable in the com_user Settings for Multifactor authentification like descriped here: https://github.com/joomla/joomla-cms/issues/38705
Apply the patch and see if the module Positions are listed now.

### Actual result BEFORE applying this Pull Request
No module positions are shown

### Expected result AFTER applying this Pull Request
Module Positions are shown.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by richard67** [comment]
Hmm according to this documentation it should be "moduleposition", lowercase but with singular "module" and not plural "modules": https://docs.joomla.org/ModulePosition_form_field_type

And in the form fields there is also no file with "modules" in plural, only this one: https://github.com/joomla/joomla-cms/blob/4.2-dev/libraries/src/Form/Field/ModulepositionField.php

@coolcat-creations What happens if you change `type="modulesposition"` to `type="moduleposition"` in the XML file?

**Comment by richard67** [comment]
Strange … maybe I’m missing something here.

**Comment by brianteeman** [comment]
did you already try what I had said https://github.com/joomla/joomla-cms/issues/38705#issuecomment-1446013203

**Comment by brianteeman** [comment]
Just to be complete - here is a recording of what I explained on the original issue. 
The behaviour is exactly the same with and without this PR

It is the intended behaviour of this field to only show positions that are in use. Exactly as you will see with the filter that is available in the module manager.

modules

**Comment by coolcat-creations** [comment]
I have the issue on my website where I have a lot of modules that are in use.

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on de5cdbb603f36bb0b4364f964174bd0a796f367f<br /><br />Sorry I wasnt testing it correctly. Issue replicated now and fix confirmed. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40040">issues.joomla.org/tracker/joomla-cms/40040</a>.</sub>

**Comment by coolcat-creations** [comment]
Thank you!

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on de5cdbb603f36bb0b4364f964174bd0a796f367f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40040">issues.joomla.org/tracker/joomla-cms/40040</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40040">issues.joomla.org/tracker/joomla-cms/40040</a>.</sub>

**Comment by HLeithner** [comment]
This pull request has been automatically rebased to 4.3-dev.

**Comment by obuisard** [comment]
Thank you Elisa @coolcat-creations for the PR :-)

**Pull request merged**
