### PR TITLE
[4.0] com_banners blank state

### PR DESCRIPTION
**Pull request by brianteeman**
image

See #33264 for instructions but this time for banners and not content

This PR requires the code from #33264 to be merged first - specifically the change in libraries/src/MVC/Model/ListModel.php

added a docs links

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 0e1b469a9b27e615cdca3ef2f51eda39a8b72f84<br /><br />Test was possible, after applying also the other PR in addition<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33269">issues.joomla.org/tracker/joomla-cms/33269</a>.</sub>

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on 0e1b469a9b27e615cdca3ef2f51eda39a8b72f84<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33269">issues.joomla.org/tracker/joomla-cms/33269</a>.</sub>

**Comment by alikon** [comment]
the drone failure is unrelated to this pr

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33269">issues.joomla.org/tracker/joomla-cms/33269</a>.</sub>

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
