### PR TITLE
Security Field for Menu Item Alias

### PR DESCRIPTION
**Pull request by tkuschel**
Add a Security Field inside the Metadata of the Menu Item Type "Menu Item Alias", as well as in the standard "Menu Item".
Problem:
Preconditions: Website have to support both http and https 
1.) Create a Menu Item "A" (e.g. inside a Menu location which is hidden on the template) to a component with the following additional settings:
    a) Metadata Options
        Secure : On
    b) Access: Registered
    that should switch the menu link from unsecure http to secure https connection. 
2.) Create a Menu Item "B" in the Main Menu with the Menu Item Type "Menu Item Alias" and pointing to the Menu Item which was created before.
    There is no "Metadata Options" for the "Menu Item Alias"
3.) You are not logged-in; and you are also switch to unsecure http://<your website>
4.) Clicking to the Menu "B" opens a login-Window but without https connection, only http!

### CODE REVIEW

**Comment by brianteeman** [comment]
If I understand correctly this is only useful in a site running partially
on http and partially on https.

As the current recommendation is to run a site on https only what is the
benefit of this PR?

**Comment by tkuschel** [comment]
Hi brianteeman,
I support a website which has to be both https and http (for an access of clients which only supports http - special hardware). So I need this field to switch security on some menu items. I already used this since 2 years with Joomla 2.5; and there is no other workaround. Nevertheless, the normal Menu Item has this built-in feature, to manually switch to security https (or unsecurity http, or ignore).
Thomas

**Comment by anibalsanchez** [comment]
I have tested this item :white_check_mark: successfully on 7ba94f765db2483773dee1da873074ac6764e79d<br /><br />Test OK. Quite handy!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8984">issues.joomla.org/joomla-cms/8984</a>.</sub>

**Comment by tkuschel** [comment]
How does this Pull Request merge into the joomla-cms, is there anything I can do for it?

 - I need this feature; and it's IMHO usefull:
*) Having a site with many "registered only menus" using alias menus to show the menu also for non-registered users.

**Comment by brianteeman** [comment]
Before a Pull Request can be merged it needs at least two successful tests

**Comment by tkuschel** [comment]
Thank you very much, IMHO it's not so an important feature, but pending since Jan 26. Hope it will be part sometime.

**Comment by tkuschel** [comment]
I have tested this item :white_check_mark: successfully on a53573fe9b62b9728b7a1c823f4941db2a23e5b7<br /><br />Running since Joomla 2.5, about 2 years now, same in Joomla 3.x 1/2 year.
Does not effect any other menu b/c it is already part of standard menu item.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8984">issues.joomla.org/joomla-cms/8984</a>.</sub>

**Comment by brianteeman** [comment]
@tkuschel but you cant test your own code - its assumed you would only ever submit tested code.

I will try to get some people to test this at the joomladay in the netherlands on friday<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8984">issues.joomla.org/joomla-cms/8984</a>.</sub>

**Comment by designbengel** [comment]
I have tested this item :white_check_mark: successfully on a53573fe9b62b9728b7a1c823f4941db2a23e5b7<br /><br />I tested this successfully, but in my opinion the menu item alias should take care of each setting from the item it refers to. No need to set it there once again? <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8984">issues.joomla.org/joomla-cms/8984</a>.</sub>

**Comment by Simonkloostra** [comment]
I have tested this item :white_check_mark: successfully on a53573fe9b62b9728b7a1c823f4941db2a23e5b7<br /><br />I have tested this patch succesfully. The logging in or not does not seem to make any difference for the test. I also agree with @designbengel that the desired setting should be taken over from the item that the alias is a copy off, no need to create new settings then.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8984">issues.joomla.org/joomla-cms/8984</a>.</sub>

**Comment by erikvandoorne** [comment]
I agree with @designbengel : the alias should append all settings from the menu item it is an alias of. Applying this patch makes it possible to set the secure setting different from the original, which is an (in my opinion) unwanted side-effect. It makes managing aliases more time-consuming and introduces the possibility to make unintended changes).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8984">issues.joomla.org/joomla-cms/8984</a>.</sub>

**Comment by brianteeman** [comment]
Based on the comments above I am setting this to Needs Review so the maintainers can make a decision<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8984">issues.joomla.org/joomla-cms/8984</a>.</sub>

**Comment by tkuschel** [comment]
>  the menu item alias should take care of each setting from the item it refers to.
You are right - thanks designbengel; it would be better when the security setting is taken from the original menu item not from the alias itself. On the other hand, you can create two different alias one secure, the other unsercure or not.

**Comment by tkuschel** [comment]
sorry I pressed the wrong button, and closed the PR

**Comment by chrisdavenport** [comment]
Agree that in this case the alias should adopt the settings of the menu item it is pointing to.  Closing as this PR does not address that issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8984">issues.joomla.org/joomla-cms/8984</a>.</sub>

**Comment by chrisdavenport** [comment]
Set to "closed" on behalf of @chrisdavenport by The <a href="https://github.com/joomla/jissues">JTracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8984">issues.joomla.org/joomla-cms/8984</a>

**Pull request closed without merging**
