### PR TITLE
improving Menus: Edit Item - moving Publishing fields v3 #36918

### PR DESCRIPTION
**Pull request by pe7er**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/36918
This PR is against 4.1-dev and makes my earlier PR https://github.com/joomla/joomla-cms/pull/36920 (against the 4.0-dev branch) obsolete.

### Summary of Changes
This PR moves in the **Menus: Edit Item** the **Start Publishing** and **Finish Publishing** date to the bottom,
so that the **Access** and **Language** are easier to use (like in Joomla 3.x)

### Actual result BEFORE applying this Pull Request

On a multilingual website, go to Menus > Main Menu (en-GB) > Create a new menu item.
You have to scroll a lot to reach the **Access** and **Language** fields:

menu_item

### Expected result AFTER applying this Pull Request

After the PR the **Access** and **Language** fields are easier to use because you don't have to scroll past the **Start Publishing** and **Finish Publishing** fields:

details-v2

### Documentation Changes Required

The screens in the documentation will have to be updated to reflect the new position of the **Start Publishing** and **Finish Publishing** date at the bottom right of the screen: https://help.joomla.org/proxy?keyref=Help4.x:Menu_Item:_New_Item/en

### CODE REVIEW

**Comment by brianteeman** [comment]
For future reference if you are asked to rebase a pr you do not need to close it and make a new one.

image

image

**Comment by brianteeman** [comment]
> > After the PR the Access and Language fields are easier to use because you don't have to scroll past the Start Publishing and Finish Publishing fields:
> 
Instead the Start Publishing and Finish Publishing fields are harder to use as you have to scroll past the access and language fields.

We really should be doing real testing before making changes

**Comment by pe7er** [comment]
I had some issues with git and the Joomla branches on my local system. So I checked out a crispy fresh 4.1-dev branch to redo my small patch. I didn't know the rebase function in Github. Thanks @brianteeman !

**Comment by drmenzelit** [comment]
I have tested this item :white_check_mark: successfully on 5e7b2edf003819bdbbc8eea58ea37c4f6ca29ccf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36923">issues.joomla.org/tracker/joomla-cms/36923</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 5e7b2edf003819bdbbc8eea58ea37c4f6ca29ccf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36923">issues.joomla.org/tracker/joomla-cms/36923</a>.</sub>

**Comment by bembelimen** [comment]
I think the position of publish up/down is wrong at all...we should stick with out standard we have in e.g. articles and have it in the correct follow up tabs. (Also for other fields which are everywhere)

**Comment by RickR2H** [comment]
@bembelimen are you suggesting an extra tab "Publishing" in the menu item with these options?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36923">issues.joomla.org/tracker/joomla-cms/36923</a>.</sub>

**Comment by RickR2H** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36923">issues.joomla.org/tracker/joomla-cms/36923</a>.</sub>

**Comment by brianteeman** [comment]
See the comment from @bembelimen this PR is not thee correct solution

**Comment by RickR2H** [comment]
Back to pending. @bembelimen can you decide on this issue?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36923">issues.joomla.org/tracker/joomla-cms/36923</a>.</sub>

**Comment by bembelimen** [comment]
Like I said, it should be streamlined with the other implementation we have in core already

**Comment by brianteeman** [comment]
> Like I said, it should be streamlined with the other implementation we have in core already

except modules also have this on the first tab as well. So we're not consistent there either

**Comment by HLeithner** [comment]
This pull request has automatically rebased to 4.2-dev.

**Comment by chmst** [comment]
As @bembelimen wrote, changes in global parts of our edit screen are against a1

**Pull request closed without merging**
