### PR TITLE
Typo fix on line 32

### PR DESCRIPTION
**Pull request by WimVDK**
possition > position

### CODE REVIEW

**Comment by sovainfo** [comment]
Might as well change it to the correct word: position

**Comment by infograf768** [comment]
Indeed

**Comment by WimVDK** [comment]
yay, my first pull request :p

**Comment by wilsonge** [comment]
Merged - thanks :) Congrats on the first PR :balloon:

**Comment by brianteeman** [comment]
Congrats @wilsonge I knew your english was bad but you just changed one typo with another typo

**Comment by wilsonge** [comment]
I blame crap screen resolution - i had to lean into my screen triple time before i noticed the second i was missing :(

**Comment by brianteeman** [comment]
@wilsonge while you are correcting it can you also add a period to the ed of the line to match the styleguide

**Comment by WimVDK** [comment]
lolz you're right. Fixed the typo in description but not swapped it out for another one :d

**Pull request merged**
