### PR TITLE
Update ru-RU.ini (installation)

### PR DESCRIPTION
**Pull request by Kostelano**
Error correction, minor corrections in the translation.

### CODE REVIEW

**Comment by infograf768** [comment]
Please be kind enough to contact the Russian language coordinator if changes are needed.
I see some which are not at all (for example in the header)

http://community.joomla.org/translations/joomla-3-translations.html#ru-ru

**Comment by infograf768** [comment]
Please do not commit this without a review by Serge, our Russian TT.

**Comment by SergeyLitvinov** [comment]
I've checked changes and agree with most of them (except header - in my mind the line about file encoding should be translated). Other changes fix some typos and common style of translation (for example quotes, removed extra spaces). So I think that this PR could be commited.

**Comment by Kostelano** [comment]
Translation encoding file corrected.

Quotes corrected because they are different everywhere :)

**Comment by infograf768** [comment]
Ok, as we do NOT customise the headers in installation ini files, I will merge the rest of the changes.

**Pull request closed without merging**
