### PR TITLE
[4.0] [a11y] Make ActionButton Featured accessible

### PR DESCRIPTION
**Pull request by chmst**
### Summary of Changes
Action Buttons for featuring articles for example in com_content/articles are Links, not Buttons.
This PR
- changes the a tag to button tag
- removes popver and replaces it by a sr-only class
- makes a separate column in the articles list 
- enables sorting the list by featured articles - see also #23497

### Testing Instructions
Apply the patch and see that the featured, unfeatured function works as before. 

featured-column-articles

NOTE:
When activating one featured button, the corresponding checkbox and the Status Change Dropdown are activated for a moment. #23717
### Documentation Changes Required
new screen

### CODE REVIEW

**Comment by brianteeman** [comment]
Almost perfect. woohoo

1. The td for the featured header should be a th
2. Needs some sort of onhover visual guide to indicate to a mouse user that this is clickable

**Comment by zwiastunsw** [comment]
1. It is a good idea to create a new column and separate the status and feaured buttons.
2. I wonder if a simple button is a good choice in this case. Shouldn't it be a toggle button?. Here we have a switchover of the position status. @dgrammatiko - What do you think about it? Maybe the toggle button change should be in a separate PR? 
3. I am not a programmer. It seems to me, however, that the attribute `href="javascript://"` is not allowed for the `button` tag. It causes the button to work as a link.
4. The action should not be followed by a change of context. The focus should remain on the button. When I use a screen reader, the focus jumps to a modal window with a status change message and then returns to the button (it is OK). But when I use only the keyboard (without the screen reader), the focus jumps to the modal window and remains at the top of the page when the window is turned off.  
5. If the button is a toggle button,then it has an `aria-pressed=”true/false”` state to let the screen reader user know when the button is pressed. Then you don't need to display a modal window with a message and move the focus to the modal window.

**Comment by dgrammatiko** [comment]
> Shouldn't it be a toggle button?. Here we have a switchover of the position status.

In sort I think no. The reason is that the effect is not realtime (you submitting a form each time you're clicking on any of these). If you change the front end logic so the form submission will happen with an Ajax then a switcher will be fine but with the current code the current approach is fine

**Comment by zwiastunsw** [comment]
@dgrammatiko : OK, thx. 
I understand that you now need to correct the code (remove the href attribute) and solve the focus problem. But I don't have an idea here.  
> Needs some sort of onhover visual guide to indicate to a mouse user that this is clickable

Add `cursor: pointer` in CSS?

**Comment by dgrammatiko** [comment]
@chmst @zwiastunsw here is some (untested) code:
```html
		<?php if (empty($disabled)): ?>
				onclick="return false;"
			<?php endif; ?>

			<?php if(!empty($task) && empty($disabled)): ?>
				onclick="return Joomla.listItemTask('<?php echo $checkboxName . $this->escape($row ?? ''); ?>', '<?php echo $this->escape(isset($task) ? $taskPrefix . $task : ''); ?>')"
                         <?php endif; ?>
```

**Comment by brianteeman** [comment]
> The action should not be followed by a change of context. The focus should remain on the button. When I use a screen reader, the focus jumps to a modal window with a status change message and then returns to the button (it is OK). But when I use only the keyboard (without the screen reader), the focus jumps to the modal window and remains at the top of the page when the window is turned off.

You are absolutely correct. But its really beyond the scope of this PR to address this as it is a bigger issue that I raised before. The information that the feature has been changed that takes the focus has **incorrectly** got a role of alert. It shouldnt be an alert as an alert will always "steal" the focus.

>> Needs some sort of onhover visual guide to indicate to a mouse user that this is clickable

>Add cursor: pointer in CSS?

Either that or an outline in CSS

**Comment by chmst** [comment]
Thank you for advices. I have prepared a new commit.
- No toggle button at the moment
- @dgrammatiko i've tested you code but "retun false" would block the change from unfeatured to featured if I understand this right. 
- cursor pointer is a good idea I will do some css for cursor and hover later

I have changed: 
If a user is not allowed to change the state, only an icon is displayed, it is not a button.

featured-disabled

About the message and the focus - as @brianteeman says, it is out of scope of this PR

**Comment by zwiastunsw** [comment]
I propose to add to the tag button title attribute calling the current status

**Comment by chmst** [comment]
I added a title instead of sr-only.
I'd like to make another PR for Cursor pointer and other css actions, this should be done in a own PR.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23718">issues.joomla.org/tracker/joomla-cms/23718</a>.</sub>

**Comment by zwiastunsw** [comment]
I'm sory. My mistake. I am withdrawing my positive test. 
**Please restore the label for screen readers**. 
The `title` attribute is not announced by screen readers.
Adding the `title` attribute means that the button also has a readable name for sighted users (e.g. when they point the icon with the mouse). The code should contain and attribute `title` and label for screen reader users (sr-only)

**Comment by chmst** [comment]
Please retest. Thank you for your patience. If this is all right, I will change other list views in the same way.

**Comment by zwiastunsw** [comment]
I suggested using the `title` attribute, because without this attribute the meaning of the button may not be understood by sighted users. Perhaps there is a better way to do this. I don't know. I remember what he said Karl Groves:
> If I found a genie and it gave me one wish, it would be that web developers stopped using the title attribute. 

(Karl Groves, December 15, 2017).

Now some screen readers will double the label. However, I think this is more accessible than without the `title` attribute. If it was a toggle buton, there would be no such problem :).
See: [The Trials and Tribulations of the Title Attribute](https://www.24a11y.com/2017/the-trials-and-tribulations-of-the-title-attribute/)
That is why I am testing successfully.

**Comment by zwiastunsw** [comment]
I have tested this item :white_check_mark: successfully on 390f47bc3b946488f61fc0c501462a423722428a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23718">issues.joomla.org/tracker/joomla-cms/23718</a>.</sub>

**Comment by chmst** [comment]
Thank you for testing. The title attribute is ugly. I have isolated the column for Featured, hoping that the meaning of the button is evident for sighted administrators. But if it is necessary ...

**Comment by zwiastunsw** [comment]
@brianteeman What is your opinion. Because @chmst  rightly says that the name of the column should be enough. Maybe I mixed up unnecessarily...

**Comment by brianteeman** [comment]
I agree 100% with @chmst

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 88111a32837a30740665dcc212ff2a933028ca24<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23718">issues.joomla.org/tracker/joomla-cms/23718</a>.</sub>

**Comment by brianteeman** [comment]
I have not tested this item.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23718">issues.joomla.org/tracker/joomla-cms/23718</a>.</sub>

**Comment by zwiastunsw** [comment]
I have tested this item :white_check_mark: successfully on c3772f9b77646911362ed6e995e5433aa0980867<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23718">issues.joomla.org/tracker/joomla-cms/23718</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on c3772f9b77646911362ed6e995e5433aa0980867<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23718">issues.joomla.org/tracker/joomla-cms/23718</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23718">issues.joomla.org/tracker/joomla-cms/23718</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
