### PR TITLE
[com_fields] Inherit url scheme restriction from fields plugin

### PR DESCRIPTION
**Pull request by laoneo**
Pull Request for comment https://github.com/joomla/joomla-cms/pull/13319#issuecomment-271272419.

### Summary of Changes
Checks if the parameter is NULL and then fetches the parameter from the plugin. Additionally the default scheme value is removed to allow any scheme initially.

### Testing Instructions
- In the Fields -> Url Plugin, the scheme should be set to HTTPS.
- Create an url field and leave the scheme empty.

### Expected result
When editing an article, only urls with the scheme https should be allowed.

### CODE REVIEW

**Comment by Bakual** [comment]
I have tested this item :red_circle: unsuccessfully on 3a564e66e9a19874de5e0049ce3f5afe3d56f929<br /><br />That doesn't seem to work yet.
When I set the schemes to "https" in the field, I get an error when I enter "http://www.joomla.org"
When I leave the schemes in the field empty and only set it in the plugin to "https", the article saves without any error.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13554">issues.joomla.org/tracker/joomla-cms/13554</a>.</sub>

**Comment by laoneo** [comment]
I'v added another commit which should fix the inheritance issue.

**Comment by Bakual** [comment]
I have tested this item :white_check_mark: successfully on 7a2ed693967b7445d4b5be7afcace556b95c7c7f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13554">issues.joomla.org/tracker/joomla-cms/13554</a>.</sub>

**Comment by anibalsanchez** [comment]
I have tested this item :white_check_mark: successfully on 7a2ed693967b7445d4b5be7afcace556b95c7c7f<br /><br />Test OK

.... the only observation is that there is no validation message about what field or why it is invalid.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13554">issues.joomla.org/tracker/joomla-cms/13554</a>.</sub>

**Comment by jeckodevelopment** [comment]
@laoneo could you please look at the conflicts?

**Comment by laoneo** [comment]
Conflicts resolved

**Comment by laoneo** [comment]
@jeckodevelopment can you set this to RTC please as we have two tests.

**Comment by jeckodevelopment** [comment]
rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13554">issues.joomla.org/tracker/joomla-cms/13554</a>.</sub>

**Pull request merged**
