### PR TITLE
[4.0] Missing language constants in 'User Actions Log => Export Selected / All as CSV' #pbf19 #codepatch

### PR DESCRIPTION
**Pull request by manojLondhe**
Pull Request for Issue #26661 .

### Summary of Changes
Load actionlog group plugin's language files

### Testing Instructions
- Apply patch
- Verify lang constants not seen in exported CSV

### Expected result
Lang constants not seen in exported CSV

### Actual result
Lang constants not seen in exported CSV

### Documentation Changes Required
No

### CODE REVIEW

**Comment by vijaykhollam** [comment]
I have tested this item :white_check_mark: successfully on 7a233739cce9694016bade15a84328626e556133
#pbf19 #test1
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26913">issues.joomla.org/tracker/joomla-cms/26913</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 7a233739cce9694016bade15a84328626e556133<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26913">issues.joomla.org/tracker/joomla-cms/26913</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26913">issues.joomla.org/tracker/joomla-cms/26913</a>.</sub>

**Comment by kishorchate** [comment]
I have tested this item :white_check_mark: successfully on 7a233739cce9694016bade15a84328626e556133<br /><br />26187<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26913">issues.joomla.org/tracker/joomla-cms/26913</a>.</sub>

**Comment by kishorchate** [comment]
I have tested this item :white_check_mark: successfully on 7a233739cce9694016bade15a84328626e556133<br /><br />#pbf19 #test1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26913">issues.joomla.org/tracker/joomla-cms/26913</a>.</sub>

**Comment by mbabker** [comment]
This is a bandaid fix for a deeper issue that I have explained probably a half dozen times now.  Fix the root issue, not apply bandaids.

**Comment by Quy** [comment]
Closing as it proper fix.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26913">issues.joomla.org/tracker/joomla-cms/26913</a>.</sub>

**Pull request closed without merging**
