### PR TITLE
Update screen notice and spacing

### PR DESCRIPTION
**Pull request by brianteeman**
The notice on the update page is in blue but all others are brown and it needs some spacing
## Before

before
## After

after

### CODE REVIEW

**Comment by Gerlof** [comment]
I have tested this item :white_check_mark: successfully on 7e7db7faef50c57fc26d43873fa661a79859fd64<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8654">issues.joomla.org/joomla-cms/8654</a>.</sub>

**Comment by NLRoosj** [comment]
I have tested this item :white_check_mark: successfully on 7e7db7faef50c57fc26d43873fa661a79859fd64<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8654">issues.joomla.org/joomla-cms/8654</a>.</sub>

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 7e7db7faef50c57fc26d43873fa661a79859fd64<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8654">issues.joomla.org/joomla-cms/8654</a>.</sub>

**Comment by brianteeman** [comment]
Thanks for testing setting RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8654">issues.joomla.org/joomla-cms/8654</a>.</sub>

**Comment by wilsonge** [comment]
Merged - thanks Brian!

**Pull request closed without merging**
