### PR TITLE
[4.2] Fix deprecated warnings in System - Privacy Consent plugin

### PR DESCRIPTION
**Pull request by joomdonation**
Pull Request for Issue #39468.

### Summary of Changes
This PR fixes some deprecated warnings in System - Privacy Consent plugin as described in issue https://github.com/joomla/joomla-cms/issues/39468.

### Testing Instructions
1. Enable System - Privacy Consent plugin
2. Go to System -> Global Configuration, set Error Reporting to Maximum
3. Login to frontend of your site 

### Actual result BEFORE applying this Pull Request
You see many deprecated warnings like:

Deprecated: substr(): Passing null to parameter https://github.com/joomla/joomla-cms/pull/1 ($string) of type string is deprecated in/home/…/plugins/system/privacyconsent/privacyconsent.php on line 304

Deprecated: substr(): Passing null to parameter https://github.com/joomla/joomla-cms/pull/1 ($string) of type string is deprecated in/home/…/plugins/system/privacyconsent/privacyconsent.php on line 305

Deprecated: substr(): Passing null to parameter https://github.com/joomla/joomla-cms/pull/1 ($string) of type string is deprecated in/home/…/plugins/system/privacyconsent/privacyconsent.php on line 306

Deprecated: substr(): Passing null to parameter https://github.com/joomla/joomla-cms/pull/1 ($string) of type string is deprecated in/home/…/plugins/system/privacyconsent/privacyconsent.php on line 307

### Expected result AFTER applying this Pull Request
No warnings anymore.

### Link to documentations
Please select:
- [x] No documentation changes for docs.joomla.org needed
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 0335db055856cef80ac95f29756bcb51e05958c7<br /><br />code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39475">issues.joomla.org/tracker/joomla-cms/39475</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 0335db055856cef80ac95f29756bcb51e05958c7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39475">issues.joomla.org/tracker/joomla-cms/39475</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39475">issues.joomla.org/tracker/joomla-cms/39475</a>.</sub>

**Comment by roland-d** [comment]
Thank you.

**Pull request merged**
