### PR TITLE
[4.0] Remove selenium.log from final build

### PR DESCRIPTION
**Pull request by zero-24**
### Summary of Changes

Remove selenium.log from final build

### Testing Instructions

download current beta https://developer.joomla.org/nightly-builds.html
notice the selenium.log file
apply this PR and run the build script again

### Expected result

no selenium.log

### Actual result

selenium.log

### Documentation Changes Required

none

### CODE REVIEW

**Comment by wilsonge** [comment]
Thanks!

**Comment by wilsonge** [comment]
This was to staging unlike the subject.... cc/ @HLeithner - doesn't actually affect the RC because it's to the build but

**Comment by zero-24** [comment]
oops was intended to be against 4.0-dev do you want me to do an individual patch for 4.0 or do you merge this up yourself?

**Comment by wilsonge** [comment]
Upto you. I'm going to be starting on merging 3.9.12 and 3.9.13 at the end of next week I think - depends if you think it's a priority for then or not

**Comment by zero-24** [comment]
nothing mission critical. End of next week is fine. Thanks :+1:

**Pull request merged**
