### PR TITLE
[com_ajax] - need to be protected

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #10700 .
#### Summary of Changes

protected the com_ajax
#### Testing Instructions

see #10700

### CODE REVIEW

**Comment by zero-24** [comment]
Do we not need the update sql too?

**Comment by alikon** [comment]
yes of course, i'm adding ....  @zero-24 you know i'm lazy/slow ;)

**Comment by zero-24** [comment]
Ahh sorry i had just saw the first two commits and was wondering ;)

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 55fb230ccfd64eda59ce41a240ce1cd00d1be7b2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10701">issues.joomla.org/joomla-cms/10701</a>.</sub>

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 55fb230ccfd64eda59ce41a240ce1cd00d1be7b2<br /><br />on code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10701">issues.joomla.org/joomla-cms/10701</a>.</sub>

**Comment by andrepereiradasilva** [comment]
I have not tested this item.<br /><br />on code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10701">issues.joomla.org/joomla-cms/10701</a>.</sub>

**Comment by andrepereiradasilva** [comment]
just remind me, shouldn't it be enabled also?

what happens if a user have a disabled com_ajax and them you protected it?

Can he enable it after?

**Comment by brianteeman** [comment]
yes - they are not related. Setting an extension to enabled or disabled is
not connected to it being protected. Protected only applies to uninstall

On 1 June 2016 at 10:16, andrepereiradasilva <notifications@github.com>
wrote:

> just remind me, shouldn't it be enabled also?
>
> what happens if a user have a disabled com_ajax and them you protected it?
>
> Can he enable it after?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/10701#issuecomment-222937691>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABPH8Vxc0dgWBUnaxMSr2DtwrXQIXw0Kks5qHU3ugaJpZM4IrL8z>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by andrepereiradasilva** [comment]
yes i know.
but let's see thsi usual scenario (i have similiar in a lot of sites).

i have com_ajax disabled. Now i update to 3.6.0 the extension is protected.

I get osmething like this in the extension manager:
image

Sicne it was disabled before the update, it still is, but now protected.

So, how do i enable it?

**Comment by brianteeman** [comment]
Ah I see what you mean now. The only option would be directly in the
database AND you have no way of knowing it is disabled

In this case all we have to do is to fix the update statement to make it
enabled AND protected. Setting it to protected without making it enabled
defeats the objective of this PR.

On 1 June 2016 at 11:34, andrepereiradasilva <notifications@github.com>
wrote:

> yes i know.
> but let's see thsi usual scenario (i have similiar in a lot of sites).
>
> i have com_ajax disabled. Now i update to 3.6.0 the extension is protected.
>
> I get osmething like this in the extension manager:
> [image: image]
> <https://cloud.githubusercontent.com/assets/9630530/15706640/8e76cf0c-27ec-11e6-859b-cdc9e646d4c1.png>
>
> Sicne it was disabled before the update, it still is, but now protected.
>
> So, how do i enable it?
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/10701#issuecomment-222955083>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABPH8dk-6wONO_f3yqa4kYMz9H5-aOnAks5qHWAogaJpZM4IrL8z>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by andrepereiradasilva** [comment]
exactly, thanks

**Comment by alikon** [comment]
I'll fix the update scripts to set enabled & protected
Thanks for reporting this scenario

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 2e01d5778df31a7bd4d003d7dcbf5c1c32de3e38<br /><br />code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10701">issues.joomla.org/joomla-cms/10701</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 2e01d5778df31a7bd4d003d7dcbf5c1c32de3e38<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10701">issues.joomla.org/joomla-cms/10701</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10701">issues.joomla.org/joomla-cms/10701</a>.</sub>

**Comment by roland-d** [comment]
Thanks everybody

**Pull request merged**
