### PR TITLE
[4.3] PHP8.2: Updating voku/portable-utf8

### PR DESCRIPTION
**Pull request by Hackwar**
Pull Request for Issue #39512.

### Summary of Changes
Our wamania/php-stemmer requires voku/portable-utf8, which in the 5.4 version is not compatible with PHP 8.2. Version 6.0 actually is and since the code for the stemmer is compatible, we can thus update voku/portable-utf8 now with this. php-stemmer will most likely not update it for the 2.x version we are using. For Joomla 5 this is probably going to be done through our dependency updates.

### Testing Instructions
Apply the change (together with composer install) and then run the indexer of smart search and afterwards search something in the frontend. Make sure that the stemmer is selected in the global options of Smart Search by setting "Default Language" to "Default Site Language". All of this in PHP 8.2

### Actual result BEFORE applying this Pull Request
You see a notice.

### Expected result AFTER applying this Pull Request
You don't see a notice.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by laoneo** [comment]
I have tested this item :white_check_mark: successfully on 44f9ff13ea961b54f95e0abf8674d61dd2d1ffa3<br /><br />When I run joomla in a webserver with xdebug enabled, like I do with DPDocker, then I get always on the first page load a deprecated warning from voku. With this patch not anymore.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39955">issues.joomla.org/tracker/joomla-cms/39955</a>.</sub>

**Comment by carlitorweb** [comment]
I have tested this item :white_check_mark: successfully on 44f9ff13ea961b54f95e0abf8674d61dd2d1ffa3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39955">issues.joomla.org/tracker/joomla-cms/39955</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39955">issues.joomla.org/tracker/joomla-cms/39955</a>.</sub>

**Comment by obuisard** [comment]
Thank you Hannes @Hackwar !

**Comment by infograf768** [comment]
We have the same problem in 4.2.9
 Impossible to install a new 4.2.9 and other issues.

**Comment by Hackwar** [comment]
This class is not used during installation of Joomla.

**Pull request merged**
