### PR TITLE
Codestyle - remove closing space

### PR DESCRIPTION
**Pull request by brianteeman**
Quick PR to fix a copy paste error where there is an extra space at the end of the class

### CODE REVIEW

**Comment by Quy** [comment]
I did a search on `class="width-20 text-area-order "` and found 5 occurrences . 3 more occurrences need to be fixed.

**Comment by brianteeman** [comment]
@quy thanks - I had a filter set when I did the search before in error.

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on d87ae6f619ae4c9ca1ead736569ac2fc5e99a48a<br /><br />OK on review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15847">issues.joomla.org/tracker/joomla-cms/15847</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on d87ae6f619ae4c9ca1ead736569ac2fc5e99a48a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15847">issues.joomla.org/tracker/joomla-cms/15847</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Pull request merged**
