### PR TITLE
Add check to Extension Manager to block upload of a Joomla core package

### PR DESCRIPTION
**Pull request by mbabker**
#### Summary of Changes

Utilizing the data made available by the Extension Manager uploading and extracting a package, we can determine if a user has uploaded a Joomla package and inform the user this does not work correctly.
#### Testing Instructions

Apply the patch then attempt to upload a Joomla 3.5 or newer package to the Extension Manager.  You will get a warning indicating this isn't allowed and instructed to go to the update component.

screen shot 2016-05-30 at 11 30 53 am

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 769e72ace3a35c38c2f7ae617aa51173e14f2823<br /><br />Works as described. Thanks!

Tested with install from URL with the 3.6.0 alpha update package URL (https://github.com/joomla/joomla-cms/releases/download/3.6.0-alpha/Joomla_3.6.0-alpha-Alpha-Update_Package.zip).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10677">issues.joomla.org/joomla-cms/10677</a>.</sub>

**Comment by brianteeman** [comment]
Please note this will obviously only prevent future users using the wrong
method. It obviously cannot go back in time and fix earlier versions of
joomla

**Comment by andrepereiradasilva** [comment]
obviously, there is no time travel yet. :smile:

**Comment by alikon** [comment]
Tested with install from URL and work as described
but should work the same  with Upload Package File ??
in that case don't work

**Comment by mbabker** [comment]
That's a separate issue, file a different report for it.  I'm trying to upload it and the model never triggers so something's blocking it before the controller.

**Comment by alikon** [comment]
thanks for the explanation

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 769e72ace3a35c38c2f7ae617aa51173e14f2823<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10677">issues.joomla.org/joomla-cms/10677</a>.</sub>

**Comment by zero-24** [comment]
RTC based on testing. Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10677">issues.joomla.org/joomla-cms/10677</a>.</sub>

**Comment by zero-24** [comment]
@joomla-cms-bot please do your job :smile:

**Pull request merged**
