### PR TITLE
[5.1] Convert mod_user to service provider

### PR DESCRIPTION
**Pull request by joomlaweby**
### Summary of Changes

Converts the user menu administrator module to service provider.

### Testing Instructions

1. Make sure you have administrator module mod_user published
2. You should see module output

mod_messages

### Actual result BEFORE applying this Pull Request

Module works as expected

### Expected result AFTER applying this Pull Request

Module works same way as before applying pull request

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by fgsw** [comment]
I have tested this item :white_check_mark: successfully on dbb9b929d0d2d9eaf304e9e15b93d31e898fa97a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42852">issues.joomla.org/tracker/joomla-cms/42852</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on dbb9b929d0d2d9eaf304e9e15b93d31e898fa97a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42852">issues.joomla.org/tracker/joomla-cms/42852</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42852">issues.joomla.org/tracker/joomla-cms/42852</a>.</sub>

**Comment by Nuyonuyonoina** [comment]
Tested successfully

**Comment by richard67** [comment]
> Tested successfully

@Nuyonuyonoina Thanks for testing. However, as this pull request has already 2 successful tests, it does not need any more tests. But if you test other pull requests please use the blue "Test this" button in the issue tracker to submit your test result so it's properly counted. Leaving just a comment is not sufficient. Thanks in advance.

**Pull request merged**
