### PR TITLE
[5.2] [Guided Tours] Fix help link and add inlinehelp tag to the global settings of the Guided Tours

### PR DESCRIPTION
**Pull request by obuisard**
Pull Request for Issue #44015.

### Summary of Changes

The Guided Tours global settings are missing the inline help and the correct link to the user help.
This PR addressed that.

### Testing Instructions

Go to Global Configuration -> Guided Tours under Joomla 5.2.

### Actual result BEFORE applying this Pull Request

The help link goes to https://help.joomla.org/proxy?keyref=Help52:&lang=en

### Expected result AFTER applying this Pull Request

The help link goes to https://help.joomla.org/proxy?keyref=Help52:Guided_Tours:_Options&lang=en.
The inline help button is visible and functional.

In both the before and after cases, the link results in a 404 page.
This is 'normal' for now that we are still in the beta phase for Joomla 5.2.
Try the link https://help.joomla.org/proxy?keyref=Help51:Guided_Tours:_Options&lang=en manually to confirm that the link will go to the right place once 5.2 is released.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by exlemor** [comment]
I have tested this item :white_check_mark: successfully on 4ae5a59e03509d960932ccfc5997e99e1b78499a<br /><br />I have successfully tested this :)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44026">issues.joomla.org/tracker/joomla-cms/44026</a>.</sub>

**Comment by brianteeman** [comment]
you need to run the helptoc script as well

**Comment by ceford** [comment]
For me the Options language strings are missing:
COM_GUIDEDTOURS_CONFIG_USER_ALLOWTOURAUTOSTART_LABEL
COM_GUIDEDTOURS_CONFIG_USER_ALLOWTOURAUTOSTART_DESCRIPTION
COM_GUIDEDTOURS_CONFIG_DELAYED_TIME_LABEL 
COM_GUIDEDTOURS_CONFIG_DELAYED_TIME_DESCRIPTION 
Is that because I am testing on 5.1.4? The Help button works fine.

**Comment by exlemor** [comment]
> For me the Options language strings are missing: COM_GUIDEDTOURS_CONFIG_USER_ALLOWTOURAUTOSTART_LABEL COM_GUIDEDTOURS_CONFIG_USER_ALLOWTOURAUTOSTART_DESCRIPTION COM_GUIDEDTOURS_CONFIG_DELAYED_TIME_LABEL COM_GUIDEDTOURS_CONFIG_DELAYED_TIME_DESCRIPTION Is that because I am testing on 5.1.4? The Help button works fine.
> 
> The Patchtester did not install properly on Joomla 5.2-dev. I get this error message:
> 
> ```
> 1146 Table 'jcms5.uxeu9_patchtester_pulls_labels' doesn't exist 
> ```

Hi @ceford, I would assume so - I was testing on Joomla 5.2 ßeta 2+

**Comment by obuisard** [comment]
> For me the Options language strings are missing: COM_GUIDEDTOURS_CONFIG_USER_ALLOWTOURAUTOSTART_LABEL COM_GUIDEDTOURS_CONFIG_USER_ALLOWTOURAUTOSTART_DESCRIPTION COM_GUIDEDTOURS_CONFIG_DELAYED_TIME_LABEL COM_GUIDEDTOURS_CONFIG_DELAYED_TIME_DESCRIPTION Is that because I am testing on 5.1.4? The Help button works fine.

Yes, Cliff, the new parameters are present in Joomla 5.2. There were only user permissions before that.

**Comment by obuisard** [comment]
> you need to run the helptoc script as well

Hi Brian, this is not a new page, that page exists since Joomla 4.3. It just never had a proper link (!).

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on 4ae5a59e03509d960932ccfc5997e99e1b78499a<br /><br />OK - I figures out how to run a test. And I have updated the screenshot in the Options Help page.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44026">issues.joomla.org/tracker/joomla-cms/44026</a>.</sub>

**Comment by obuisard** [comment]
> I have tested this item ✅ successfully on [4ae5a59](https://github.com/joomla/joomla-cms/commit/4ae5a59e03509d960932ccfc5997e99e1b78499a)OK - I figures out how to run a test. And I have updated the screenshot in the Options Help page.

Thank you!

**Comment by Hackwar** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44026">issues.joomla.org/tracker/joomla-cms/44026</a>.</sub>

**Comment by Hackwar** [comment]
Thank you for your contribution @obuisard!

**Pull request merged**
