### PR TITLE
[4] fix new article from frontend

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #36500 .

### Summary of Changes
credits @pjdevries 

### Testing Instructions

-   Create a Registered user.
-   Create a category and give the group the user belongs to the following permissions for that category: Create, Delete, Edit State & Edit Own.
-   Create a menu item of type 'Category List'.
-   Login in the front end as the new user.
-   Navigate to the Category List.
-   Click 'New Article'.
-   Enter at least the title and click 'Save'.

### Actual result BEFORE applying this Pull Request

Screenshot from 2022-01-03 09-19-35

### Expected result AFTER applying this Pull Request

article saved

### CODE REVIEW

**Comment by pjdevries** [comment]
I have tested this PR and it solves the mentioned bug.

**Comment by joomdonation** [comment]
I have tested this item :white_check_mark: successfully on 8480acb059b94cd5887681ff75bbea1108d98121<br /><br />Issue is fixed, adding/editing article still works OK for both frontend and backend.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36542">issues.joomla.org/tracker/joomla-cms/36542</a>.</sub>

**Comment by joomdonation** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36542">issues.joomla.org/tracker/joomla-cms/36542</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
