### PR TITLE
[4.2] Spelling s/successfull/successful

### PR DESCRIPTION
**Pull request by brianteeman**
error: `Sucessfull` should be `Successful`

### CODE REVIEW

**Comment by N6REJ** [comment]
whatever test is calling this function will fail because of the function rename.  You'll need to change that call also.

**Comment by brianteeman** [comment]
> whatever test is calling this function will fail because of the function rename. You'll need to change that call also.

shakes head in dismay

**Comment by laoneo** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks for merging @laoneo I knew you wouldnt be fooled by @N6REJ

**Comment by laoneo** [comment]
@N6REJ the test functions are standalone and are read and called by PHPUnit during execution run.

**Comment by N6REJ** [comment]
@brianteeman you can really stop the bullshit  I've had enough

**Comment by N6REJ** [comment]
> @N6REJ the test functions are standalone and are read and called by PHPUnit during execution run.

ah ok.. ty for clarifying that.  I didn't realize it would auto-detect a function name change.  Interesting.
How does it know the name changed?

**Comment by laoneo** [comment]
It doesn't need to know the changed name. PHPUnit just parses the classes and executes the function starting with the name test.

**Pull request merged**
