### PR TITLE
[4.0] a11y contrast on danger-bg

### PR DESCRIPTION
**Pull request by brianteeman**
Title: WCAG 1.4.3: Elements must have sufficient color contrast (.j-links-link)
Tags: Accessibility, WCAG 1.4.3, color-contrast

Issue: Elements must have sufficient color contrast (color-contrast - https://dequeuniversity.com/rules/axe/3.3/color-contrast?application=msftAI)
 Element has insufficient color contrast of 4.48 (foreground color: #495057, background color: #f9acaa, font size: 10.5pt (14px), font weight: normal). Expected contrast ratio of 4.5:1

Target application: Control Panel - 4.0 Evaluar - Administration - http://localhost/joomla-cms/administrator/index.php

Element path: #plg_quickicon_extensionupdate > .quickicon-text.align-items-center.d-flex > .j-links-link

Snippet: `<span class="j-links-link">Updates are available! <span class="badge badge-light">2</span></span>
`
### Testing Instructions
npm i

there is almost no visible difference
### Before
image

### After
image

### CODE REVIEW

**Comment by astridx** [comment]
If tested this successful.

I did the following:

1. I had checked the background for the Post Installation Hint
Control Panel   Test   Administration
 It was

`#f9acaa;`

```
.badge-danger {
    color: 
#3b0d0c;
background-color:
#f9acaa;
border: 1px solid
    #ba2926;
}
```
2. I run `git fetch origin pull/27357/head:qicon` and changed to `qicon` branch.

3. I run `npm i`

4. After reloading the site I did not realize a change. But in CSS I see the new background color.
`#f5b9b7;`
```
.badge-danger {
    color: 
#3b0d0c;
background-color:
#f5b9b7;
border: 1px solid
    #ba2926;
}
```

**Comment by astridx** [comment]
I have tested this item :white_check_mark: successfully on 0d3ee52836bc2dfedd780489bd94a27cce1cd450<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27357">issues.joomla.org/tracker/joomla-cms/27357</a>.</sub>

**Comment by HLeithner** [comment]
Thanks brian and thanks astrid for your perfect testing description I would like to see this from every tester ;-)

**Comment by brianteeman** [comment]
Thanks all

**Pull request merged**
