### PR TITLE
Solves issue #20195: [com_fields] Contact-Mail Custom field issue after joomla 3.8.3

### PR DESCRIPTION
**Pull request by degobbis**
Pull Request for Issue #20195

### CODE REVIEW

**Comment by ghost** [comment]
changed Title to be clear what this PR is about.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20214">issues.joomla.org/tracker/joomla-cms/20214</a>.</sub>

**Comment by sandewt** [comment]
I have tested this item :white_check_mark: successfully on d663127d5331b279aea2174df2f72ae6612a392b<br /><br />Joomla! 3.8.8-dev Development

Solved issue #20195 `Contact-Mail Custom field issue after joomla 3.8.3`

Solved issue #17743 `Contact form loses data after postback with error`

I have tested both issues.

Note: See also the test instructions for issue #17743.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20214">issues.joomla.org/tracker/joomla-cms/20214</a>.</sub>

**Comment by tonypartridge** [comment]
What if catid on item is empty? There was a check originally wrapping the whole state. But that’s being changed now and you are calling item catid directly, is it always set?!?! Seems strange that we were previously checking it if it is always set.

**Comment by degobbis** [comment]
@tonypartridge Yes, ist is always set. You can't create a contact without setting a category.

**Review by laoneo — APPROVED** [review]

**Comment by ReLater** [comment]
I have tested this item :white_check_mark: successfully on d663127d5331b279aea2174df2f72ae6612a392b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20214">issues.joomla.org/tracker/joomla-cms/20214</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20214">issues.joomla.org/tracker/joomla-cms/20214</a>.</sub>

**Comment by artur-stepien** [comment]
Why is it fixed in a view instead of model? Views aren't for that ...

**Pull request merged**
