### PR TITLE
[4.0] Fix group select in Mass Mail

### PR DESCRIPTION
**Pull request by brianteeman**
Simple PR to correct the size of the field

### Before
image

### After
image

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 0ee37a0d3afe0de6fbf21144c9c6249d09d2bfe6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24681">issues.joomla.org/tracker/joomla-cms/24681</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 0ee37a0d3afe0de6fbf21144c9c6249d09d2bfe6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24681">issues.joomla.org/tracker/joomla-cms/24681</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24681">issues.joomla.org/tracker/joomla-cms/24681</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
