### PR TITLE
[4.0] Improve accessibility of media manager modals

### PR DESCRIPTION
**Pull request by wilsonge**
- Adds a aria-labelledby element to the media manager modals
- Downgrades the role from `alertdialog` to `dialog`

@zwiastunsw @brianteeman

### CODE REVIEW

**Comment by brianteeman** [comment]
What is the modal title supposed to be for the preview 

image

**Comment by wilsonge** [comment]
Screenshot 2019-04-24 at 04 43 00

The name of the image. In the red box above (I haven't changed the titles here from what they were before this patch) - I've just linked the existing headers in the header slot to an aria-labelledby tag.

**Comment by brianteeman** [comment]
Try to use the keyboard to close the modal - you can't as the keyboard is trapped inside media manager. pressing tab you will see that the next image in the manager gets focus

**Comment by wilsonge** [comment]
Fixed. There was nothing to lock onto as it was a link rather than a button. Changed the close to be a button and it all worked nicely

**Pull request merged**
