### PR TITLE
Remove unused options in menu manager

### PR DESCRIPTION
**Pull request by brianteeman**
Go to Menu Manager and select options. You have 4 items that can be set but only one of those is something that can be set globally. This PR removes the three unused options

### CODE REVIEW

**Comment by infograf768** [comment]
"Page Heading" works when "Show Page Heading" is set to Yes.

**Comment by brianteeman** [comment]
Please describe the exact steps that you took to get a value entered in Page heading to display on the home page. I am completely unable to do this from the Menu Manager Options - So either I am missing something OR you are looking at the wrong thing - did you actually try<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6070">issues.joomla.org/joomla-cms/6070</a>.</sub>

**Comment by infograf768** [comment]
I always try before posting.

**Comment by infograf768** [comment]
My mistake. The same page heading was also entered in the menu item.
2 solutions: or we modify code to take care of the global options, or we indeed apply this PR.
To be able to apply a css suffix globally could be quite useful.

**Comment by brianteeman** [comment]
> To be able to apply a css suffix globally could be quite useful.

Not really - if you are going to apply a page class suffix to every page
then we already have Menu Class Suffix in the module.

This is simply a copy paste error that is being fixed

On 13 February 2015 at 07:18, infograf768 <notifications@github.com> wrote:

> My mistake. The same page heading was also entered in the menu item.
> 2 solutions: or we modify code to take care of the global options, or we
> indeed apply this PR.
> To be able to apply a css suffix globally could be quite useful.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/6070#issuecomment-74214543>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by infograf768** [comment]
Was not fully a copy/paste error for page_title. 
page_title was retrieved in 2.5 and it seems it is also in 3.x

see 
https://github.com/joomla/joomla-cms/blob/staging/libraries/cms/application/site.php#L346
https://github.com/joomla/joomla-cms/blob/staging/libraries/cms/application/site.php#L365

I guess we should find out about that one before deleting it in the Options.

**Comment by brianteeman** [comment]
The three options that do nothing that  I am removing  do NOT work in
2.5.28 either

On 13 February 2015 at 08:00, infograf768 <notifications@github.com> wrote:

> Was not fully a copy/paste error for page_title.
> page_title was retrieved in 2.5 and it seems it is also in 3.x
>
> see
>
> https://github.com/joomla/joomla-cms/blob/staging/libraries/cms/application/site.php#L346
>
> https://github.com/joomla/joomla-cms/blob/staging/libraries/cms/application/site.php#L365
>
> I guess we should find out about that one before deleting it in the
> Options.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/6070#issuecomment-74217829>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by infograf768** [comment]
That is possible. The point here is to take care at the same time of the code I quote above and not blindly deleting the field.

**Comment by brianteeman** [comment]
Go for it.

On 13 February 2015 at 08:16, infograf768 <notifications@github.com> wrote:

> That is possible. The point here is to take care at the same time of the
> code I quote above and not blindly deleting the field.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/6070#issuecomment-74219193>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by infograf768** [comment]
As I thought, `page_title` IS used.
Test: Create an article which is NOT displayed by a menu item, even when drilling down.
Enter something in the field (Here MYBROWSERTITLE)
screen shot 2015-02-14 at 06 40 33
NOTE: if field is left empty the site name will be used when there is no menu item.

Enter as url (my article here has id 1):
/index.php?option=com_content&view=article&id=1
screen shot 2015-02-14 at 06 39 56

**Comment by Bakual** [comment]
Closing this PR since the options are actually used, even not obvious.

**Comment by infograf768** [comment]
I indeed tested the other fields (Page Class and Page heading) and they are used in the case stated above.
Nevertheless, we do have an issue in the sense that the Tips are not clear.

**Pull request closed without merging**
