### PR TITLE
Changed return 0 to continue

### PR DESCRIPTION
**Pull request by ghost**
To prevent the entire function to quit, it just needs to go to the next file.
Fix https://github.com/joomla/joomla-cms/issues/17954

Pull Request for Issue #17954 .

### Summary of Changes
Changed return 0 to continue

### Testing Instructions
Create an install file and add multiple install sql files. The first one should be empty and the second one should have some sql. The second file is never executed

### Expected result
The second file with queries should be executed

### Actual result
The second file is not executed

### CODE REVIEW

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on 146422932644cfb426cb8f3034da87af97a8ec08<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20805">issues.joomla.org/tracker/joomla-cms/20805</a>.</sub>

**Comment by MSnoeren** [comment]
I have tested this item :white_check_mark: successfully on 146422932644cfb426cb8f3034da87af97a8ec08<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20805">issues.joomla.org/tracker/joomla-cms/20805</a>.</sub>

**Review by wilsonge — APPROVED** [review]

**Comment by wilsonge** [comment]
Looks good to me! Thanks! Congrats on your first PR to Joomla :)

**Comment by ghost** [comment]
:-) Thanks!

**Pull request merged**
