### PR TITLE
[4.0]Simplified -  add module to dashboard background

### PR DESCRIPTION
**Pull request by brianteeman**
~This may be personal preference but I found the background on the "add module to dashboard" too "in your face".~

With this PR you can now see the background pattern etc which I believe to be more accurate representation of the original design instead of the solid gray.

Simplified the PR to just replace the solid gray colour with the patterned background

### check the grey background here
before

dont forget to run rnom i or node build.js --compile-css

### CODE REVIEW

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 70d06e413290f7253421cd2e8458803238c8e856<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27468">issues.joomla.org/tracker/joomla-cms/27468</a>.</sub>

**Comment by jwaisner** [comment]
I agree with the subtle approach versus the harsh white.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27468">issues.joomla.org/tracker/joomla-cms/27468</a>.</sub>

**Comment by richard67** [comment]
I disagree with same color as background. Ok, the white is really too bright. But there should be some change beside the "+" disappearing when you hover it so you can see something is activated which you can click or tip on. Maybe a grey lighter than the background would be good?

**Comment by infograf768** [comment]
@richard67 
++

**Comment by Fedik** [comment]
I am not fun of both: not original, and not suggested.
tbh, the big plus icon that crosses with text looks to me as a bug. Would be cool to find a better design idea for it.

**Comment by richard67** [comment]
Yes, original is also not nice. But I have no idea right now what would be optimal.

**Comment by Fedik** [comment]
Maybe like this, with small "plus" and without "background fade"?
screen 2020-01-11 12 54 56 807x166

**Comment by infograf768** [comment]
Another possibility
dashboard

**Comment by Fedik** [comment]
one more idea :)
screen 2020-01-11 14 28 59 1597x271

**Comment by HLeithner** [comment]
I would like to get rid of this button and move it to a position out of the grid. One position could be in the cogs of an existing module and only the normal button if no module exists.
image

**Comment by brianteeman** [comment]
I definitely would not put it there as it would not be logical

**Comment by HLeithner** [comment]
> I definitely would not put it there as it would not be logical

I would prefer another position too

**Comment by brianteeman** [comment]
The suggestion here maintains the objectives of the original design

**Comment by HLeithner** [comment]
Only my opinion, it just looks unfinished if you always have a add more area that looks like a module.

**Comment by brianteeman** [comment]
I believe that was the designers intention

**Comment by infograf768** [comment]
@HLeithner 
Your proposal would not work as we can unpublish some dashboard modules.


Screen Shot 2020-01-12 at 08 29 19

**Comment by Fedik** [comment]
The button at bottom is good and intuitive, except its styling :smiley:

**Comment by N6REJ** [comment]
bs convention is for lighten/darken to be 10%

**Comment by HLeithner** [comment]
I don't say that my solution is good ;-)
I only hate this big Add button that looks like a module and I can't remove it.

Giving this to a customer looks like I forgot something. And to be honest the use case for this buttons is more or less after installation and configuration afterwards you it's really unlikely that you add another module.

Also if you create the perfect dashboard and want to use the full space you always have a scrollbar...

But I don't want to discuss this any longer, it is what it is.

**Comment by chmst** [comment]
Do we need the + icon? In general we have a + OR the word "Add ..." not both. 
If there is no +, then a 10% lightening would be sufficient and is not so "in your face".
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27468">issues.joomla.org/tracker/joomla-cms/27468</a>.</sub>

**Comment by brianteeman** [comment]
That was the design the designer created and tbh facebook people seem to like useless wizzbang stuff like this.

Removing it is not part of this PR. I was just fixing the background to be closer to the original design

**Comment by brianteeman** [comment]
simplified the pr so that it is super simple and an obvious merge

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on abb5d61d0d42b4545be15326ca8a64de877eb5f3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27468">issues.joomla.org/tracker/joomla-cms/27468</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on abb5d61d0d42b4545be15326ca8a64de877eb5f3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27468">issues.joomla.org/tracker/joomla-cms/27468</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27468">issues.joomla.org/tracker/joomla-cms/27468</a>.</sub>

**Comment by brianteeman** [comment]
Thanks all

**Pull request merged**
