### PR TITLE
TEST PR - IGNORE ME

### PR DESCRIPTION
**Pull request by wilsonge**
Testing rewriting tests that I can't do on my laptop because of OSX doing weird things with sed.

### CODE REVIEW

**Comment by richard67** [comment]
Hmm, for reading the “ignore me” it needs not to ignore it ... a vicious circle ;-)

**Comment by yvesh** [comment]
brew install gnu-sed (--with-default-names)

**Comment by wilsonge** [comment]
Yeah I found that out later - but still kinda wish I could run the bash file without requiring brew installs. But that's life. This works now 🎉

**Comment by yvesh** [comment]
@wilsonge check out "multipass" for mac os (from Canonical). It's still a Ubuntu VM, but way more integrated.

**Pull request closed without merging**
