### PR TITLE
Update Tinymce editor

### PR DESCRIPTION
**Pull request by brianteeman**
Update to latest release of tinymce 4.3.12
#### Summary of Changes

Version 4.3.12 (2016-05-10)
    Fixed bug where focus calls couldn't be made inside the editors PostRender event handler.
    Fixed bug where some translations wouldn't work as expected due to a bug in editor.translate.
    Fixed bug where the node change event could fire with a node out side the root of the editor.
    Fixed bug where Chrome wouldn't properly present the keyboard paste clipboard details when paste was clicked.
    Fixed bug where merged cells in tables couldn't be selected from right to left.
    Fixed bug where insert row wouldn't properly update a merged cells rowspan property.
    Fixed bug where the color input boxes preview field wasn't properly set on initialization.
    Fixed bug where IME composition inside table cells wouldn't work as expected on IE 11.
    Fixed so all shadow dom support is under and experimental flag due to flaky browser support.#### Testing Instructions

### CODE REVIEW

**Comment by smitshah81** [comment]
Hi ,
Can you please guide me how can I test this issue?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10719">issues.joomla.org/joomla-cms/10719</a>.</sub>

**Comment by brianteeman** [comment]
Apply the pull request and check that the editor still works as you expect. For extra credit create a table and merge some cells and then ake sure you can select them<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10719">issues.joomla.org/joomla-cms/10719</a>.</sub>

**Comment by dgt41** [comment]
@smitshah81 try to d/l https://github.com/brianteeman/joomla-cms/archive/tinymce.zip and then install joomla as usual. then check if tinymce still works. (that's in case com patch tester is not working and you are not familiar with git)

**Comment by bertmert** [comment]
I have tested this item :white_check_mark: successfully on 1ff9e491164186a8b5fd4f6c10d585eb75671c89<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10719">issues.joomla.org/joomla-cms/10719</a>.</sub>

**Comment by smitshah81** [comment]
Hi I have checked this issue and i found that it is not working in firefox 47.0  OS : Ubuntu 12.04,However it is working in chromium browser.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10719">issues.joomla.org/joomla-cms/10719</a>.</sub>

**Comment by brianteeman** [comment]
what is not working - thats a very broad statement

On 11 June 2016 at 13:55, smit shah <notifications@github.com> wrote:

> Hi I have checked this issue and i found that it is not working in firefox
> 47.0 OS : Ubuntu 12.04,However it is working in chromium browser.
> ------------------------------
> This comment was created with the J!Tracker Application
> <https://github.com/joomla/jissues> at issues.joomla.org/joomla-cms/10719
> <https://issues.joomla.org/tracker/joomla-cms/10719>.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/10719#issuecomment-225359766>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABPH8SktlAAUXBeFlYrwvcWmj_JrOc6eks5qKrBIgaJpZM4ItfzR>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by smitshah81** [comment]
I had tried to create table and merge cell and select them but I was not able to select them.But I can do same in chromium browser

**Comment by brianteeman** [comment]
Please make sure you have completely cleared your browser cache as that is
the bug that this version of tiny is supposed to fix

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 1ff9e491164186a8b5fd4f6c10d585eb75671c89<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10719">issues.joomla.org/joomla-cms/10719</a>.</sub>

**Comment by infograf768** [comment]
RTC. Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10719">issues.joomla.org/joomla-cms/10719</a>.</sub>

**Pull request merged**
