### PR TITLE
Create new form field type: countrylist.php

### PR DESCRIPTION
**Pull request by minitek**
Countries list with ISO 3166 alpha-3 codes as values

[countrylist.zip](https://github.com/joomla/joomla-cms/files/86040/countrylist.zip)

### CODE REVIEW

**Comment by bertmert** [comment]
I have tested this item :red_circle: unsuccessfully on 8a773ecac0e75217709a98beb33ca8ab594e6a9d<br /><br />Applied patch in current 3.5.0beta staging.

Added field countrylist in
/administrator/components/com_content/models/forms/article.xml
inside block
```
<fields name="attribs" label="COM_CONTENT_ATTRIBS_FIELDSET_LABEL">
```

```
<field
name="country"
type="countrylist"
label="countrylist"
description="countrylist" />
```

Opened article > Tabulator *Options*.

I see the field but all language placeholders are untranslated (e.g. JCOUNTRY_ARUBA)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8879">issues.joomla.org/joomla-cms/8879</a>.</sub>

**Comment by Bakual** [comment]
The language strings definitively need translations provided for en-GB.
ALso, is there a reason you use alpha-3 codes and not the alpha-2 ones? In Joomla we use two letter codes for our language-country codes (eg "en-GB"). I think we should follow that where possible.

**Comment by yannis79** [comment]
I changed
ISO 3166 alpha-3 codes
to
ISO 3166 alpha-2 codes

I will add translations in en-GB.ini

**Comment by renekorss** [comment]
I have tested this item :white_check_mark: successfully on 6f2883b5992985dc7c42594a5390ba8facf7afdf<br /><br />Since translations are in different branch, I still see `JCOUNTRY_ARUBA` etc. @yannis79 could you merge your patch-2 into patch-1?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8879">issues.joomla.org/joomla-cms/8879</a>.</sub>

**Comment by renekorss** [comment]
Sorry, meant to choose unsucessfully, can I somehow change test result?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8879">issues.joomla.org/joomla-cms/8879</a>.</sub>

**Comment by brianteeman** [comment]
You cant but I can ;)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8879">issues.joomla.org/joomla-cms/8879</a>.</sub>

**Comment by yannis79** [comment]
@renekorss, I would merge them but I really don't know how!

**Comment by renekorss** [comment]
@yannis79 What tool are you using? On command line it should look like this:

    git checkout patch-1
    git merge patch-2
    git push

**Comment by brianteeman** [comment]
In the current state this is not ready. Please update the PR as above or if you have issues please ask. If not this will have to be closed in a few weeks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8879">issues.joomla.org/joomla-cms/8879</a>.</sub>

**Comment by brianteeman** [comment]
As stated above this cannot be merged at this time and as there has been no update I am closing it. If it is updated as requested it can always be reopened<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8879">issues.joomla.org/joomla-cms/8879</a>.</sub>

**Pull request closed without merging**
