### PR TITLE
Frontend: New module order field isn't displayed

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue #12031 .
### Summary of Changes

Fix the path to the controller if the task is moduleOrdering
### Testing Instructions
- Login into fronted
- Click the Edit module-button of a module
- Look at the field Ordering
### Documentation Changes Required

None, bug fix

### CODE REVIEW

**Comment by Minei3oat** [comment]
I have tested this item :white_check_mark: successfully on 3636f2adabc7f94bf7b88646b46d6de78ed1e066<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12032">issues.joomla.org/joomla-cms/12032</a>.</sub>

**Comment by sonalitailored** [comment]
I have tested this item :white_check_mark: successfully on 3636f2adabc7f94bf7b88646b46d6de78ed1e066<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12032">issues.joomla.org/joomla-cms/12032</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 3636f2adabc7f94bf7b88646b46d6de78ed1e066<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12032">issues.joomla.org/joomla-cms/12032</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12032">issues.joomla.org/joomla-cms/12032</a>.</sub>

**Pull request merged**
