### PR TITLE
Consistency use of Components name and View in Title

### PR DESCRIPTION
**Pull request by marijkestuivenberg**
This applies to all use of the Components name in the respective views of those components. The template for it would be: components name: view 
Example:
In com-content the name is Articles, views can be New, Edit, Options, Categories, Featured. It will show the following titles:
Articles: New
Articles: Edit
Articles: Options
Articles: Categories
Articles: Featured

However there are a number of places where this is not used consistently. The component title is used in singular form instead of its original. Sometimes the view after clicking the button New is named different, where New would be more consistent. There are also places where the Title doesn’t match the Name of the (sub) menu items that leads to the view.

**Test instructions**

These are the places that should be checked before patch (BP) and after patch (AP):

**News Feeds**
Click on Option
(BP) News Feed: Options - change to plural (AP) News Feeds: Options

**Redirect**
On the overview page inconsistency in the title:
(BP) Redirects: Links vs Redirect in sub menu item name (in Topmenu: Components) - change both title and submenu to plural (AP) Redirects
Click Options:
(BP) Redirect: Options - (AP) Redirects: Options

**Messaging**
Inconsistency on the overview page title compared with the submenu title in components; (BP) Messaging in sub menu & title page Private Messages - (AP) Private Messages on both places
Click on the new button:
(BP) Private Messages: Write - (AP) Private Messages: New
Read a private message (sub sub menu item topmenu Components -> Messaging)
(BP) Private Messages: View - (AP) Private Messages: Read (more consistent with sub menu item Components -> Messaging -> Read Private Messages)
Click on Options:
(BP) Messages: Options - (AP) Private Messages: Options

**Menus**
Click New:
(BP) Menus: Add - (AP) Menus: New

**Web Links**
Sub menu name in Components is Weblinks while everywhere else it is called Web Links (BP) Weblinks, (AP) Web Links
Click on New:
(BP) Web Links - (AP) Web Links: New *
Click on Edit: 
(BP) - Web Links - (AP) Web Links: Edit *
Click on Options:
(BP) Web Links Manager Options - (AP) Web Links: Options
(*) will need changes in administrator/components/com_weblinks/views/weblink/view.html.php on line 61 change 
`JToolbarHelper::title(JText::_('COM_WEBLINKS_MANAGER_WEBLINK'), 'link weblinks');`

into
`JToolbarHelper::title($isNew ? JText::_('COM_WEBLINKS_MANAGER_WEBLINK_NEW') : JText::_('COM_WEBLINKS_MANAGER_WEBLINK_EDIT'), 'link weblinks');`

**Modules**
Click on New and select a random module:
(BP) Modules: Module Type - (AP) Modules: New Module Type *
Module Type is the name of the type of Module that was selected

Select a module to edit:
(BP) Modules: Module Type - (AP) Modules: Edit Module Type *
Module Type is the name of the Module that was selected

Click on Options:
(BP) Module: Options - (AP) Modules: Options

**Plugins**
Click on Options:
(BP) Plugin: Options - plural (AP) Plugins: Options

**Templates**
Click Options:
(BP) Template: Options - plural (AP) Templates: Options

**Languages**
(BP)In the sub menu item of Components it is called Language(s), Opposed to the Title of the overview page which shows Languages - (AP) Languages

Note that there are inconsistencies in all Category views, this issue is taken care of in #8070

### CODE REVIEW

**Comment by brianteeman** [comment]
I obviously agree that consistency between components is good. One of the problems is that sometimes the component is referred to as a singular and others a plural. Not just in the text displayed but also in the code. It is com_banners and com_categories but only com_content and com_contact.

Personally I believe there does not need to be a direct connection between the dropdown menu and the title. And if we are going to be correct then it should be Singular-edit not Plural-edit as you are only editing a singular not a plural. 
(this is the sort of PR I had hoped to do myself but I was told not to make any more useless language changes so good luck)

**Comment by brianteeman** [comment]
@marijkestuivenberg this PR fails the travis tests 

> administrator/components/com_modules/views/module/view.html.php
  67 | WARNING | Line exceeds 150 characters; contains 212 characters

If it is ok with you I will bring the topic of this PR up at the next en-GB meeting in 10 days time and if we decide to move forward with it then it might just be easier if we create a new pr <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8072">issues.joomla.org/joomla-cms/8072</a>.</sub>

**Comment by marijkestuivenberg** [comment]
All fine for me, travis complaints about the limit of characters in a line, so it needs to be on two lines probably. Let me know whenever I can help test

**Comment by conconnl** [comment]
@brianteeman and @marijkestuivenberg is this PR discussed and can we start testing it?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8072">issues.joomla.org/joomla-cms/8072</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
Asking @marijkestuivenberg @brianteeman if this is for testing, cause 8 Months later.

**Comment by jeckodevelopment** [comment]
@marijkestuivenberg and @infograf768 can you please look at this?

**Comment by franz-wohlkoenig** [comment]
any Thoughts on this PR by Maintainers?

**Comment by rdeutz** [comment]
closing this one, I think it is in important to use language consistent, I would also go with singular instead of plural so fixing the conflicts seems to me more work than making a new PR

**Pull request closed without merging**
