### PR TITLE
[4.4] Use .env files for the node tools

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # .

### Summary of Changes

- Adding a `production.env` and a `development.env` file for the build env variables
- Adjust the script tags on the package.json

### Testing Instructions

- add a `console.log(process.env.NODE_ENV)` after https://github.com/joomla/joomla-cms/blob/12ce681c526a3517c165ba1003246f9c01674808/build/build-modules-js/javascript/build-com_media-js.es6.js#L14
- Run the commands `npm run build:com_media` should see `PRODUCTION`
- Run the commands `npm run build:com_media:dev` should see `DEVELOPMENT`
- Run the commands `npm run update` should see `PRODUCTION`
- All commands produce the file `media/com_media/js/media-manager.min.js`

### Actual result BEFORE applying this Pull Request
???

### Expected result AFTER applying this Pull Request
All good

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Fedik** [comment]
Can it be without a 2 files for 1 line? :smile:

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on 85f5be7caef843f78c1acd77c017df1790ec0ff7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42340">issues.joomla.org/tracker/joomla-cms/42340</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42340">issues.joomla.org/tracker/joomla-cms/42340</a>.</sub>

**Comment by laoneo** [comment]
Why is this needed?

**Comment by Fedik** [comment]
Because `set NODE_ENV=PRODUCTION && node build/build.js --com-media` does not work for me.
But not realy critical, can stay as it is.

**Comment by dgrammatiko** [comment]
@laoneo there’s more nuance here about node 20 and env files (you can google it). The point is that although this is looking stupid is the right thing moving forward (there’s way more things that could be in those .env files, but little steps)

**Pull request merged**
