### PR TITLE
[5.2] Wrap long text to prevent layout displaying beyond viewport

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
Fix long text from displaying beyond viewport.

### Testing Instructions
Install  blog sample data.
Enable `Debug System`.
Go Components > Smart Search > Index.
Click `Index > Index Debugging`.
Select `Smart Search - Content`.
Click `Index` button.
See `Output` section.

### Actual result BEFORE applying this Pull Request
Horizontal scrollbar.

### Expected result AFTER applying this Pull Request
No horizontal scrollbar.

### CODE REVIEW

**Comment by fgsw** [comment]
I have tested this item :white_check_mark: successfully on 247b663c4f14c640b98f15d60b8ee2e8783e79ec<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44441">issues.joomla.org/tracker/joomla-cms/44441</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 247b663c4f14c640b98f15d60b8ee2e8783e79ec<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44441">issues.joomla.org/tracker/joomla-cms/44441</a>.</sub>

**Comment by chmst** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44441">issues.joomla.org/tracker/joomla-cms/44441</a>.</sub>

**Comment by Hackwar** [comment]
Thanks for this contribution. 😄

**Pull request merged**
