### PR TITLE
Update filter package to 1.1.6 -adds PHP 7 support

### PR DESCRIPTION
**Pull request by wilsonge**
Updates the filter package to 1.1.6 - adding some missing php 7 support to `OutputFilter`

### CODE REVIEW

**Comment by C-Lodder** [comment]
I have tested this item :white_check_mark: successfully on 39fd3f350689a75351ceee76a9a747419a3206a8<br /><br />Applied patch. No issues found.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8734">issues.joomla.org/joomla-cms/8734</a>.</sub>

**Comment by photodude** [comment]
Too bad the current master branch of the filter hasn't been released as a new 1.1.7 version. It has some important changes in it https://github.com/joomla-framework/filter/commit/de9a5a7a354621fb3f2941b7456c498881818dd3 .

Seems this goes hand in hand with my PR for the other filter library in the CMS https://github.com/joomla/joomla-cms/pull/8681

**Comment by mbabker** [comment]
@wilsonge Rebase this since one of your other Composer PRs was merged and use the 1.2.0 tag.

**Comment by brianteeman** [comment]
@wilsonge does this need to be merged before 3.5 for php7 compatibility<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8734">issues.joomla.org/joomla-cms/8734</a>.</sub>

**Comment by wilsonge** [comment]
It's not used to core so not 100% essential but yes I think it should be (will rebase this evening when back from work)

**Comment by brianteeman** [comment]
@wilsonge reminder<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8734">issues.joomla.org/joomla-cms/8734</a>.</sub>

**Comment by photodude** [comment]
I know there are other things in the mix, But it would be nice to see rebased.

**Comment by wilsonge** [comment]
I'm going to PR this update into your PR at #8681 and let's just get this upgrade all in one place :)

**Pull request closed without merging**
