### PR TITLE
JFormOption

### PR DESCRIPTION
**Pull request by okonomiyaki3000**
This is the same as #1192 but for staging instead of master.

### CODE REVIEW

**Comment by okonomiyaki3000** [comment]
Fix some merge conflicts in this old thing. This is still really cool, btw.

**Comment by zero-24** [comment]
Hmm looks like a unit test fails here?

Can you have a look? https://travis-ci.org/joomla/joomla-cms/builds/82667974

**Comment by okonomiyaki3000** [comment]
There was a bug in my code but I also found that the unit test was laughable. So it's a bit better now. However, it's using the `assertTag` test which may be a problem in the future. I think it's the best test for html because it doesn't fail on things like whitespace or other things that shouldn't matter in html but it seems to be removed in later version of `phpunit` so we may need to find a new way to test html output.

**Comment by mbabker** [comment]
It's removed from PHPUnit 5.  So either we need to eventually write something similar or pull in some third party library that has the ability to parse that stuff in a unit test run.

**Comment by okonomiyaki3000** [comment]
I'd rather just see all html removed from server-side code but that's kind of a pipe dream.

**Comment by dgt41** [comment]
@okonomiyaki3000 can you delete this file: libraries/joomla/form/options/index.html? Joomla dropped all the blank .html files long time ago

**Comment by okonomiyaki3000** [comment]
Yeah, I seem to have some vague recollection of that.

**Comment by roland-d** [comment]
@okonomiyaki3000 I know this is another old PR but I agree that this is still cool to implement. If you could update the PR to resolve the merge conflicts I will get some people to test this and we can implement it for 3.6. Thanks.

**Comment by okonomiyaki3000** [comment]
@roland-d Thanks, I was thinking of getting back to this one soon anyway. I'm glad to know there's interest in it. The usefulness of it might not be immediately obvious to everyone but I happen to think it's pretty great.

**Comment by roland-d** [comment]
@okonomiyaki3000 I have set the milestone for now to 3.7.0 as we are too late for 3.6.0.

**Comment by Edu20** [comment]
I have tested this item :red_circle: unsuccessfully on 742fa5e95b29e100ff8c6fc021f6a16c2bb139c3<br /><br />I tested this Patch with the [Patch Tester 2.0.1](https://github.com/joomla-extensions/patchtester/releases/tag/2.0.1 "Patch Tester 2.0.1") and it throws an error: "The file marked for modification does not exist: layouts/joomla/fields/radio.php"

Tested @icampus<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5147">issues.joomla.org/joomla-cms/5147</a>.</sub>

**Comment by wmchris** [comment]
I have tested this item :red_circle: unsuccessfully on 742fa5e95b29e100ff8c6fc021f6a16c2bb139c3<br /><br />Same error as Edu20 - file missing. Does this need another patch before?
@icampus<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5147">issues.joomla.org/joomla-cms/5147</a>.</sub>

**Comment by mbabker** [comment]
Make sure you've actually got that file in your local install.  Should be present as of 3.5.0.

**Comment by mbabker** [comment]
Oh, nevermind, I see the issue now.  This does need to be sync'd with staging it looks like; the file it's groaning about appears to have been renamed.

**Comment by okonomiyaki3000** [comment]
Sorry guys, this is really old and needs a lot of work. I'm glad it's getting some attention again because I still think it's a great idea but I need to find some time to to fix it up. 

Also, I never took into account grouped lists. Really I don't know why grouped lists need to be any different from ungrouped lists. I'll need to have that in mind when updating this I guess.

**Comment by roland-d** [comment]
@okonomiyaki3000 Yeah I know this is old but you know by now that I tend to drag these things out into the light ;) Shall we close this issue for now and can be re-opened or a new one can be made when you have time for it?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/5147">issues.joomla.org/joomla-cms/5147</a>.</sub>

**Comment by zero-24** [comment]
New PR: https://github.com/joomla/joomla-cms/pull/12288

**Comment by okonomiyaki3000** [comment]
@roland-d I finally got around to doing a little work on it. How do you think it's best to proceed? From here or with a new pr? Just so you know, I don't think it's quite ready to merge yet but anyway I'm ready to continue discussing and working on it.

**Comment by zero-24** [comment]
I have opend a new PR maybe you can fork that branch and do your own PR?

**Comment by okonomiyaki3000** [comment]
OK, that sounds good. has some work been done on it then? I guess I'd better go see.

**Comment by zero-24** [comment]
https://github.com/zero-24/joomla-cms/tree/5147

I have just fixed the conflicts

**Comment by okonomiyaki3000** [comment]
@zero-24 It looks like that branch needs to be rebased with staging. It might end up being a big hassle. I have a branch that's already been rebased, maybe it's best to make a new PR? or has some work been done on your branch already?

**Comment by zero-24** [comment]
No there is no additional work done.

**Pull request closed without merging**
