### PR TITLE
[4.0] Switch remaining options from grid to column layout

### PR DESCRIPTION
**Pull request by Quy**
More changes for PR #27153.

### Summary of Changes
Fix styling.

### Testing Instructions
Go to Global Configuration > Articles
See missing white background.

### Expected result
after

### Actual result
before

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on e6629d077869b92ca398abd972340782d4723876<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27628">issues.joomla.org/tracker/joomla-cms/27628</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 3c45a14048498c13b06a58719460316700ba503f<br /><br />tested Code View<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27628">issues.joomla.org/tracker/joomla-cms/27628</a>.</sub>

**Comment by richard67** [comment]
> tested Code View

@ChristineWk Does that mean you have tested by code review and not with a real test?

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 3c45a14048498c13b06a58719460316700ba503f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27628">issues.joomla.org/tracker/joomla-cms/27628</a>.</sub>

**Comment by richard67** [comment]
I suggest to wait with RTC until we know if the other was a real test or not. Code review is not a sufficient test in this case in my opinion.

**Comment by Quy** [comment]
I think she is referring to the additional commit after her initial test.

**Comment by richard67** [comment]
Well if you want, make it RTC.

**Comment by Quy** [comment]
RTC

**Comment by ChristineWk** [comment]
> 
> 
> I think she is referring to the additional commit after her initial test.

Yes. As I didn't remember the previous layout concerning column layout from 1st test, I checked Code review also.

**Comment by richard67** [comment]
@ChristineWk Thanks for testing and clarification.

**Pull request merged**
