### PR TITLE
[4.0] Searchtools works with selects only

### PR DESCRIPTION
**Pull request by Denitz**
### Summary of Changes

Currently, searchtools script is not 100% ready for having non-select filters.

### Testing Instructions

Use filter form with non-select fields, try `text` and `number` fields types.
The fastest way is to change an existing filter form and change field types.

### Actual result BEFORE applying this Pull Request

Once a filter has any value, the Clear button is disabled.

### Expected result AFTER applying this Pull Request

Once a filter has any value, the Clear button is not disabled.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by Quy** [comment]
Please fix: https://ci.joomla.org/joomla/joomla-cms/37654/1/21

**Comment by Denitz** [comment]
@Quy Fixed.

**Comment by ceford** [comment]
After applying the patch and changing Articles list Depth to Text I see that the Clear button is not disabled but it does not work either. I get this Javascript error:
Uncaught TypeError: Cannot read property 'undefined' of undefined
    at Searchtools.activeFilter (searchtools.js?213f32181bd1349a270e2048e65c8a57:326)
    at Searchtools.checkFilter (searchtools.js?213f32181bd1349a270e2048e65c8a57:222)
    at searchtools.js?213f32181bd1349a270e2048e65c8a57:167
    at Array.forEach (<anonymous>)
    at new Searchtools (searchtools.js?213f32181bd1349a270e2048e65c8a57:166)
    at HTMLDocument.onBoot (searchtools.js?213f32181bd1349a270e2048e65c8a57:538)
Is that what is expected?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31438">issues.joomla.org/tracker/joomla-cms/31438</a>.</sub>

**Comment by Denitz** [comment]
@ceford Sorry, found an issue, please re-try.

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on 0d084c4f240226cf348e072d451b380d15843168<br /><br />This time, setting Articles / Level to type Text I find that the clear button works and clears whatever I have entered in that field as well as drop-down list field. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31438">issues.joomla.org/tracker/joomla-cms/31438</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 0d084c4f240226cf348e072d451b380d15843168<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31438">issues.joomla.org/tracker/joomla-cms/31438</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 0d084c4f240226cf348e072d451b380d15843168<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31438">issues.joomla.org/tracker/joomla-cms/31438</a>.</sub>

**Comment by infograf768** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31438">issues.joomla.org/tracker/joomla-cms/31438</a>.</sub>

**Comment by drmenzelit** [comment]
Thanks

**Pull request merged**
