### PR TITLE
[com_cache] Delete all

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
Pull Request for Improvement.
#### Summary of Changes

This PR adds a "Delete All" method and toolbar button to com_cache.

image

This delete all current cache for the client selected.
#### Testing Instructions
1. Apply patch
2. Go to System -> Clear Cache
3. If you don't have any cache, activate cache in global config and navegate a little in the frontend.
4. Test the new "Delete All" button.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have not tested this item.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10246">issues.joomla.org/joomla-cms/10246</a>.</sub>

**Comment by BurtNL** [comment]
I have tested this issue and it works, but it only deletes the cache-items as shown on the active page.
If you have multiple pages the cache-items on the other pages are still there.
Is this how it is supposed to work?
Or do you want to delete all cache-items over all pages (even if not currenty visible) at once? (which would be great, i guess).

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10246">issues.joomla.org/joomla-cms/10246</a>.</sub>

**Comment by andrepereiradasilva** [comment]
> If you have multiple pages the cache-items on the other pages are still there.

What do you mean by "multiple pages"?

that i know of, in admin Clear Cache page we only have two subviews (Site or Administrator).
This Button deletes all cache groups in the selected subview.

**Comment by brianteeman** [comment]
Cache has a list limit just like all manager views

On 5 May 2016 at 11:49, andrepereiradasilva <notifications@github.com>
wrote:

> If you have multiple pages the cache-items on the other pages are still
> there.
>
> What do you mean by "multiple pages"?
>
> that i know of, in admin Clear Cache page we only have two subviews (Site
> or Administrator).
> This Button deletes all cache groups in the selected subview.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/10246#issuecomment-217123211>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by andrepereiradasilva** [comment]
oh! i see! of course. need coffeee...

Will check that.

thanks @BurtNL @brianteeman for the comments.

**Comment by andrepereiradasilva** [comment]
ok should work now

**Comment by BurtNL** [comment]
I have tested this item :white_check_mark: successfully on 66e23b5000c54afccc8931192ae66c698d5826eb<br /><br />Great! Now it deletes all cache-items over multiple list views/pages.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10246">issues.joomla.org/joomla-cms/10246</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 66e23b5000c54afccc8931192ae66c698d5826eb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10246">issues.joomla.org/joomla-cms/10246</a>.</sub>

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on 66e23b5000c54afccc8931192ae66c698d5826eb<br /><br />Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10246">issues.joomla.org/joomla-cms/10246</a>.</sub>

**Comment by wilsonge** [comment]
Merged - thanks @andrepereiradasilva :)

**Comment by andrepereiradasilva** [comment]
thanks all for testing and comments!

**Pull request merged**
