### PR TITLE
Update en-GB.ini

### PR DESCRIPTION
**Pull request by aaleksanyants**
1. INSTL_LANGUAGES_DESC contained "Choose your preferred languages by clicking in the checkboxes and then install them by clicking on the Next button." which has been replaced with "Choose your preferred languages by choosing the checkboxes and then install them by selecting the Next button." Why should I CHOOSE by CHOOSING, and how do i SELECT a button?!
2. Both INSTL_CONFPROBLEM and INSTL_NOTICEYOUCANSTILLINSTALL contained "Click in the text area to highlight all of the code and then paste into a new text file." which has been replaced with "Select in the text area to highlight all of the code and then paste into a new text file." I like the previous version much more as you should CLICK in the text area to have highlighted (which is equal to selected in this particular case) the whole code, and not to SELECT.

### CODE REVIEW

**Comment by infograf768** [comment]
All "Click" have been changed to "Select" under the pretext that one does not click when using a smartphone or a tablet... which indeed creates a lot of inconsistencies...

**Comment by aaleksanyants** [comment]
That's why I have replaced not with just "click" but with "click or tap"

**Comment by Hils** [comment]
When one clicks or taps in that context, isn't one selecting? Do we have to explain to people how to select?

**Comment by aaleksanyants** [comment]
Clicking is not selecting. When selecting, you make a click, than move the mouse woth hold left button, and then release it. To highlight the whole code in text area you do not select anything within it, you just click and release!

**Comment by aaleksanyants** [comment]
BTW, clicking and tapping is equal to give a command for doing something, while selecting is not, it just prepares for action related to the selected items, that's why we do not select a button but click it. otherwise it will remain selected but will not initiate any action.

**Comment by joo7** [comment]
@aaleksanyants Can it be formulated like this? (pick, check, hit)

INSTL_LANGUAGES_DESC="The Joomla interface is available in several languages. Choose your preferred languages by checking the appropriate checkboxes and then install them by hitting the _QQ_Next_QQ_ button.<br />Note: this operation will take about 10 seconds to download and install every language. To avoid timeouts please select no more than 3 languages to install at a time."

INSTL_CONFPROBLEM="Your configuration file or folder is not writable or there was a problem creating the configuration file. You will have to upload the following code by hand. Hit the text area to highlight all of the code and then copy and paste it into a new text file. Name this file 'configuration.php' and upload it to your site root folder."

INSTL_NOTICEYOUCANSTILLINSTALL="<br />You can still continue the installation as the configuration settings will be displayed at the end. You will have to manually upload the code. Hit the text area to highlight all of the code and then copy and paste it into a new text file. Name this file 'configuration.php' and upload it to your site root folder."

**Comment by joo7** [comment]
Github changed the text for the "Next"-button.

I tried to follow this:
Whenever you add a double quote ( " ) in the translation, you actually have to change it to (` _QQ_` ) and Joomla will replace that for a ( " ) .

I insert it as code, incase it is not working, it needs to be like this whitout spaces:
_ Q Q _ Next _ Q Q _
Or we just do it like this: 'Next'?

`INSTL_LANGUAGES_DESC="The Joomla interface is available in several languages. Choose your preferred languages by checking the appropriate checkboxes and then install them by hitting the _QQ_Next_QQ_ button.
Note: this operation will take about 10 seconds to download and install every language. To avoid timeouts please select no more than 3 languages to install at a time."`

**Comment by infograf768** [comment]
you can use ` the 'Next' button` or `the "_QQ_"Next"_QQ_" button`

**Comment by joo7** [comment]
Thank you! Since I'm not native english maybe someone can take a look at the text and decide and correct if needed? Or shall I change it in the en-GB.ini file and than it will be looked at?

**Comment by Bakual** [comment]
Usually @brianteeman will catch it and give his notes.

**Comment by joo7** [comment]
Ok, great, thank you for info.

**Comment by roland-d** [comment]
@brianteeman Can you give your input please? Thank you.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7853">issues.joomla.org/joomla-cms/7853</a>.</sub>

**Comment by brianteeman** [comment]
@roland-d  I am not in favour of this change  for the reasons explained by hils

**Comment by roland-d** [comment]
I am closing this issue because there is no support from the native speakers. Thank you for your contribution.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7853">issues.joomla.org/joomla-cms/7853</a>.</sub>

**Pull request closed without merging**
