### PR TITLE
[4.1] Tasks - empty state

### PR DESCRIPTION
**Pull request by brianteeman**
Updates the text as shown below

## Before
image

## After
image

### CODE REVIEW

**Comment by khu5h1** [comment]
I have tested this item :white_check_mark: successfully on 931728594ae9675565f6ebe677122da6caa983c2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36203">issues.joomla.org/tracker/joomla-cms/36203</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 931728594ae9675565f6ebe677122da6caa983c2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36203">issues.joomla.org/tracker/joomla-cms/36203</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36203">issues.joomla.org/tracker/joomla-cms/36203</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
