### PR TITLE
[4.0] Atum strings

### PR DESCRIPTION
**Pull request by brianteeman**
The strings for two module positions in the Atum template were missing.

To test enable language debug and create a new admin module and in the list of available positions ensure that they are all translated

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 54c51993fd4d4461d33e057f1fcf932eee174ab1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27715">issues.joomla.org/tracker/joomla-cms/27715</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 54c51993fd4d4461d33e057f1fcf932eee174ab1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27715">issues.joomla.org/tracker/joomla-cms/27715</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27715">issues.joomla.org/tracker/joomla-cms/27715</a>.</sub>

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
