### PR TITLE
[3.x] CodeMirror 5.52.2

### PR DESCRIPTION
**Pull request by brianteeman**
Updates codemirror to the latest release (we were a year out of date :(  ) using the https://github.com/okonomiyaki3000/joomla-codemirror-builder script by @okonomiyaki3000

### CODE REVIEW

**Comment by okonomiyaki3000** [comment]
Cool. I haven't thought about this in a while. Any great new features?

**Comment by brianteeman** [comment]
@okonomiyaki3000 not that I could see. There are a few new templates but its really just bug fixes

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 4e4ff72ca0aa9165770647287e72a1ab263f7cd3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28691">issues.joomla.org/tracker/joomla-cms/28691</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 4e4ff72ca0aa9165770647287e72a1ab263f7cd3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28691">issues.joomla.org/tracker/joomla-cms/28691</a>.</sub>

**Comment by jwaisner** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28691">issues.joomla.org/tracker/joomla-cms/28691</a>.</sub>

**Comment by brianteeman** [comment]
@zero-24 would be good to get this merged as we're really out of date

**Comment by zero-24** [comment]
Merged thanks :+1:

**Comment by brianteeman** [comment]
thx

**Pull request merged**
