### PR TITLE
Added Separate Section For SEO

### PR DESCRIPTION
**Pull request by pritam825**
It's Not an Issue, It's an suggestion

### Testing Instructions
go to administrator->Banners->Banners->New
### Actual result BEFORE applying this Pull Request

No Separate Section for SEO and  Metadata section is in publishing section

### Expected result AFTER applying this Pull Request

image

### 
If this is ok for everyone then will create for others also.

### CODE REVIEW

**Comment by brianteeman** [comment]
None of those fields are anything to do with SEO

**Comment by pritam825** [comment]
> None of those fields are anything to do with SEO

Metadata comes under seo

**Comment by brianteeman** [comment]
You should look at how the data is used. None of those fields are used for seo

**Comment by pritam825** [comment]
@brianteeman 
image
so, according to you this should be in separate section because of meta description part?

**Comment by Quy** [comment]
See discussion #15833

**Comment by pritam825** [comment]
@Quy I have read the discussion but not seeing any end-up of discussion , some people says it's good , some not, if you all are ok with this then I will create pr for every component, otherwise I will close this, Thanks :)

**Comment by Quy** [comment]
I don't see the point of moving just 3 fields to its own tab especially if they are not updated often.
What is your rationale to justify its own tab?
Why not do a text override to "Publishing/SEO" in your installation?

**Comment by pritam825** [comment]
> I don't see the point of moving just 3 fields to its own tab especially if they are not updated often. What is your rationale to justify its own tab? Why not do a text override to "Publishing/SEO" in your installation?

For example if I will have to add the meta description or keywords so first thing which comes in mind that there will be an separate SEO section where I can find the all functionality for SEO, how will I know that it will come under publishing

**Comment by Quy** [comment]
It may not be obvious at first, but once you know where these settings are under `Publishing` then I don't see the issue. Create a language override if you need a reminder.

**Comment by HLeithner** [comment]
This pull request has been automatically rebased to 5.0-dev.

**Comment by web-eau-net** [comment]
I have tested this item :white_check_mark: successfully on 1e8b03b7256b2e602d1f41fadbfd9898cab0b1fb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38124">issues.joomla.org/tracker/joomla-cms/38124</a>.</sub>

**Comment by Quy** [comment]
Thank you for the PR. Closing for now for reason stated. When there are additional SEO settings added, we will revisit this.

**Pull request closed without merging**
