### PR TITLE
[4.1] tab code style

### PR DESCRIPTION
**Pull request by brianteeman**
Looks like someones cat sat on the tab key

### CODE REVIEW

**Comment by richard67** [comment]
Yes, and it seems the cat was big 😄

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 7c3b77d2f1d250d17bc9a6a0b79ce616aebdb8a2<br /><br />By review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37363">issues.joomla.org/tracker/joomla-cms/37363</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 7c3b77d2f1d250d17bc9a6a0b79ce616aebdb8a2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37363">issues.joomla.org/tracker/joomla-cms/37363</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37363">issues.joomla.org/tracker/joomla-cms/37363</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Comment by brianteeman** [comment]
Thanks - can do some real work now ;)

**Pull request merged**
