### PR TITLE
[4.0][com_redirect] Fix title markup

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
Fix markup to display the title.

### Testing Instructions
Code review.

or 

Go to System > Redirects.
Create a new link.
There is no title link.

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on cd10d26aa9128c64bda0649bc8142ed08f17d9aa<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26429">issues.joomla.org/tracker/joomla-cms/26429</a>.</sub>

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on cd10d26aa9128c64bda0649bc8142ed08f17d9aa<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26429">issues.joomla.org/tracker/joomla-cms/26429</a>.</sub>

**Comment by SharkyKZ** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26429">issues.joomla.org/tracker/joomla-cms/26429</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
