### PR TITLE
Mail test message

### PR DESCRIPTION
**Pull request by brianteeman**
When you use the test mail setting n global configuration you will receive an email that says

COM_CONFIG_SENDMAIL_BODY="This is a test mail sent using "_QQ_"%s"_QQ_". If you receive it, then your email settings are correct!"

Clearly if you are reading it then you dont need the "If..

#### After
COM_CONFIG_SENDMAIL_BODY="This is a test mail sent using "_QQ_"%s"_QQ_". Your email settings are correct!"

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on f66dbd2c11456d35f49896cad4bbcb58a7e8848b<br /><br />obvious fix<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12767">issues.joomla.org/tracker/joomla-cms/12767</a>.</sub>

**Comment by PhilETaylor** [comment]
I have tested this item :white_check_mark: successfully on f66dbd2c11456d35f49896cad4bbcb58a7e8848b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12767">issues.joomla.org/tracker/joomla-cms/12767</a>.</sub>

**Comment by brianteeman** [comment]
Rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12767">issues.joomla.org/tracker/joomla-cms/12767</a>.</sub>

**Comment by zero-24** [comment]
:+1:

**Comment by zero-24** [comment]
Merged

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
