### PR TITLE
changing en-US color to default en-GB colour

### PR DESCRIPTION
**Pull request by MATsxm**
### Summary of Changes
changing en-US `color` to default en-GB `colour`
### Testing Instructions
on review
### Documentation Changes Required
none

### CODE REVIEW

**Comment by brianteeman** [comment]
I am a little torn on this one. On the one hand you are perfectly correct and it should have a U. On the other hand it is referring to a code element called color so it is correct without the U. 

(and to make it more fun we already use the U for a similar field in the template styles)

**Comment by Hils** [comment]
If it code it should be background-color but if it is narrative it should be Background colour, in my view

**Comment by brianteeman** [comment]
So which one is it Hils if it is text describing code?

**Comment by ot2sen** [comment]
When it is readable text for the user then 'colour' is to be used as
suggested in the PR.
Had it been a code value/text that the user had to enter in for example a
style override then it would need to use code standard 'color'

**Comment by Hils** [comment]
It's just describing what happens if a button is pushed isn't it? If so colour should be the way to go in Joomla.

**Comment by brianteeman** [comment]
Ok. Fine by me. As I said I was undecided on this one I am happy to go with
the majority

On 8 Dec 2016 1:15 p.m., "Hils" <notifications@github.com> wrote:

It's just describing what happens if a button is pushed isn't it? If so
colour should be the way to go in Joomla.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/joomla/joomla-cms/pull/13129#issuecomment-265737155>,
or mute the thread

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on c2b840504e7ae492d7e4a71c0a47f1d360765751<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13129">issues.joomla.org/tracker/joomla-cms/13129</a>.</sub>

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on c2b840504e7ae492d7e4a71c0a47f1d360765751<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13129">issues.joomla.org/tracker/joomla-cms/13129</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13129">issues.joomla.org/tracker/joomla-cms/13129</a>.</sub>

**Pull request merged**
