### PR TITLE
Fix Drag&Drop sorting

### LINKED ISSUE #8861: SortableList.js: Drag&Drop sorting does not work with lines/elements of different height
#### Steps to reproduce the issue

* create three articles
** two normal articles
** one with a very long title
* open the articles list in the back end
* place the article with the very long title in the middle of the two others
* reload the page
* now drag and drop the article with the very long title to the top
* check the xhr request which is going out

screen shot 2016-01-08 at 10 26 32

#### Expected result

Sorting lines with different heights should work

#### Actual result

If I sort lines with different heights I get random results since two item have the same ordering value.

### PR DESCRIPTION
**Pull request by renekorss**
Fix sorting if there is items with different heights. Bug occured only for moving higher item up. Now respects height of moved item.

fixes #8861

### CODE REVIEW

**Comment by brianteeman** [comment]
I can not replicate this issue

**Comment by renekorss** [comment]
@brianteeman You created on article with very long title and moving it up results in ordering 1, 2, 3? Not 1, 1, 3?

**Comment by brianteeman** [comment]
Yes and Yes

**Comment by brianteeman** [comment]
After playing a bit more and doublechecking with the database entries I was able to get it to misbehave once - where the DB entry did not match the visual display.

I applied the patch and retested and couldnt replicate the bug anymore so this is a good test

**Comment by brianteeman** [comment]
To anyone else testing make sure you check the value of the ordering column in the database<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9049">issues.joomla.org/joomla-cms/9049</a>.</sub>

**Comment by svenbluege** [comment]
With this fix applied I can't reproduce the issue in #8861. I confirm this fix is working.

**Comment by wojsmol** [comment]
@svenbluege Please mark test results on https://issues.joomla.org/tracker/joomla-cms/9049<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9049">issues.joomla.org/joomla-cms/9049</a>.</sub>

**Comment by svenbluege** [comment]
I have tested this item :white_check_mark: successfully on 4b8325e758ea98aadf8d99a9dd098446ece0f842<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9049">issues.joomla.org/joomla-cms/9049</a>.</sub>

**Comment by svenbluege** [comment]
@wojsmol Done. First time for me so let me know if there is more todo.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9049">issues.joomla.org/joomla-cms/9049</a>.</sub>

**Comment by wojsmol** [comment]
@svenbluege Now everything is correctly.

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 4b8325e758ea98aadf8d99a9dd098446ece0f842<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9049">issues.joomla.org/joomla-cms/9049</a>.</sub>

**Comment by brianteeman** [comment]
RTC - thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9049">issues.joomla.org/joomla-cms/9049</a>.</sub>

**Comment by wilsonge** [comment]
@renekorss There are conflicts here - can you please fix them :) If not then to confirm https://github.com/joomla/joomla-cms/pull/9049/files#diff-0f3028a8e62b1bde4dd60f2a5af107b0R225 is the only line that has changed right?

**Comment by renekorss** [comment]
@wilsonge Yes, correct. I can fix it, when I get to computer.

**Comment by renekorss** [comment]
@wilsonge Conflicts fixed.

**Pull request merged**
