### PR TITLE
[4.0] Add sticky information to banner

### PR DESCRIPTION
**Pull request by chmst**
Pull Request for Issue # .

### Summary of Changes
Banners can be displayed in a frontend module. 
But the modules does not know which banners are pinned (sticky).
This PR adds the information to the itmes.

### Testing Instructions
Code review or debug mod_banners

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on fc0a6d3e4ae3463ac7b7fdca63b8b6885d84b1ed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34567">issues.joomla.org/tracker/joomla-cms/34567</a>.</sub>

**Comment by BertaOctech** [comment]
I have tested this item :white_check_mark: successfully on fc0a6d3e4ae3463ac7b7fdca63b8b6885d84b1ed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34567">issues.joomla.org/tracker/joomla-cms/34567</a>.</sub>

**Comment by BertaOctech** [comment]
I have tested this item :white_check_mark: successfully on fc0a6d3e4ae3463ac7b7fdca63b8b6885d84b1ed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34567">issues.joomla.org/tracker/joomla-cms/34567</a>.</sub>

**Comment by Quiviro** [comment]
I have tested this item :white_check_mark: successfully on fc0a6d3e4ae3463ac7b7fdca63b8b6885d84b1ed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34567">issues.joomla.org/tracker/joomla-cms/34567</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34567">issues.joomla.org/tracker/joomla-cms/34567</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
