### PR TITLE
[4.0] Remove extra column in com_banners client

### PR DESCRIPTION
**Pull request by rjharishabh**
Pull Request for Issue #33813.

### Summary of Changes
remove row and column width to remove extra column

### Testing Instructions
Dashboard > Components > Banners > Client > Edit any client or create using New > Go to Metadata tab
Apply PR 
and see the difference

### Actual result BEFORE applying this Pull Request
banners-new-client-before

### Expected result AFTER applying this Pull Request
banners-new-client-after

### Documentation Changes Required
No

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 4f2c85639fc637f029c5615873969ce80811ad59<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33816">issues.joomla.org/tracker/joomla-cms/33816</a>.</sub>

**Comment by sandewt** [comment]
I wonder if this change is desirable. Who is in charge of the (final) design of joomla?

**Comment by rjharishabh** [comment]
> I wonder if this change is desirable. Who is in charge of the (final) design of joomla?

See #33800 and #33806

**Comment by rjharishabh** [comment]
Maybe there will be some reason to design like this.

**Comment by sandewt** [comment]
>Maybe there will be some reason to design like this.

I asked myself that question too.

**Comment by PhilETaylor** [comment]
Have you tested on small screen sizes/devices?

**Comment by rjharishabh** [comment]
> Have you tested on small screen sizes/devices?

Yes 
banners-small

**Comment by Kostelano** [comment]
I have tested this item :white_check_mark: successfully on 4f2c85639fc637f029c5615873969ce80811ad59<br /><br />Oh, I missed the point of testing. It works. Thank you. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33816">issues.joomla.org/tracker/joomla-cms/33816</a>.</sub>

**Comment by richard67** [comment]
@C-Lodder What's the reason for the thumbs down?

**Comment by C-Lodder** [comment]
Because whitespace doesnt need to be filled for the sake of it. Form fields shouldn't be nearly 100% of the viewport.

**Comment by rjharishabh** [comment]
@brianteeman should I revert this or change the width.
PR for similar issue #33806

**Comment by richard67** [comment]
> Because whitespace doesnt need to be filled for the sake of it. Form fields shouldn't be nearly 100% of the viewport.

@C-Lodder Thanks for explaining, and I think you are right.

But people opened issue about that and PR's were made and tested with success, so I have set the one or other RTC without having an own, deeper look into it, and without knowing if it was a design decision or not.

Am happy if you or @brianteeman can step in and point me (and maybe others, too) to the right direction.

Regarding the white space, maybe we should tell those who opened the issues how to make overrides which show nice cat pictures at that place (or puppies if they prefer that).

**Comment by Kostelano** [comment]
@richard67 You are very nice to your coworkers and NOT very nice (or NOT very witty) to other (less familiar) users. Stop this unless you intend to write your own documentation page for posting pictures of cats and dogs.

The request for the problem was submitted by analogy with the other, which was corrected and accepted.

**Comment by brianteeman** [comment]
_Humour is often lost in translation_

**Comment by richard67** [comment]
Sorry .. I did not want to offend anybody.

**Comment by C-Lodder** [comment]
@richard67 Personally, I'd leave the current width as it is. Form field widths should be set to that of the expected content length, **or** ideally no longer than 80-100 characters per row.

I'm not a UX expert, but have done lots of research on this in the past, so hopefully it's applicable here.

**Comment by brianteeman** [comment]
@c-lodder I agree 100% - that is exactly what the Nielson group say as well

**Comment by richard67** [comment]
@brianteeman @C-Lodder Do you think we should not only reject this PR here but also revert #33806 for being consistent again?

**Comment by brianteeman** [comment]
thats a maintainer decision but I would - also see #32874

**Comment by richard67** [comment]
Ahh ... maybe I got confused somehow ... PR #33806 was created by @C-Lodder so that might be ok, or not?

**Comment by brianteeman** [comment]
it was created by @ciar4n

**Comment by richard67** [comment]
> it was created by @ciar4n

Ahh .. I need glasses.

**Comment by Fedik** [comment]
_I see someone is against of a pictures of a cats._ 

About the issue. I agree with @C-Lodder.
To me it looks nicer when the fields is compact. They does not contain a lot of content, does not need to make them huge.
And 100% width on large screen looks bad.
I would not merge it.

UPD: the same about #33806
On  large screen User is forced to move eyes from left edge to right edge.
This actually the same why newspaper does not print the text in 100% width, but split in to columns, this is more easy to eyes.

**Pull request closed without merging**
