### PR TITLE
[5.0] Rework the com_messages message view

### PR DESCRIPTION
**Pull request by wilsonge**
Pull Request for Issue https://github.com/joomla/joomla-cms/pull/42124 .

### Summary of Changes
Rework of the HTML structure towards something geared towards more input'less elements. Physically separates the invisible form from the rendered HTML content.

### Testing Instructions
Whilst this ensures the view looks better in dark mode. It obviously changes the structure in light mode too. This too should be validated. Check with longer and shorter message lengths.

### Actual result BEFORE applying this Pull Request
dark-private-messages

### Expected result AFTER applying this Pull Request
image

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on 93a717fb855765f7f57f1800058df6ee3c35da9f<br /><br />Tested successfully in 5.0.0-rc3-dev of 14 October using PHP 8.2.11 in Wampserver 3.3.1, in Light mode and Dark mode in Chrome.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42135">issues.joomla.org/tracker/joomla-cms/42135</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 93a717fb855765f7f57f1800058df6ee3c35da9f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42135">issues.joomla.org/tracker/joomla-cms/42135</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42135">issues.joomla.org/tracker/joomla-cms/42135</a>.</sub>

**Comment by wilsonge** [comment]
If we want to treat this like a form field we should use formal input fields with labels as @dgrammatiko mentioned, close this PR and once #42124 is amended merge that one

If we’re happy rendering this without form field style rendering we should merge this PR and maintainers or a release lead should decide which approach

**Comment by dgrammatiko** [comment]
FWIW I'm in favour of this one

**Review by dgrammatiko — APPROVED** [review]

**Comment by Quy** [comment]
@HLeithner Why not v5.0.1 as it is unreadable as of now in dark mode?

**Comment by HLeithner** [comment]
because the screenshots looks like only refactorying the html and no dark mode fixes

**Comment by brianteeman** [comment]
the html has to be refactored to enable the appropriate dark mode changes

**Pull request merged**
