### PR TITLE
[4.4] Smart Search: Don't search for alternative images

### PR DESCRIPTION
**Pull request by Hackwar**
Pull Request for Issue #42320.

### Summary of Changes
When an articles intro image contains a blank space, our code to search for related files in the media folder strips the whole image from the output of the search results. This change prevents this. The images of a search result should be the exact images, not the potential compressed files or similar from the media folder.

### Testing Instructions
1. Add an image with a space in the filename in the /images folder
2. Edit an article and set the intro image to that image. By saving, the index should be updated.
3. Set the image to be displayed in the search results in the configuration of either the search menu item or in the smart search global configuration.
4. Search for the article

### Actual result BEFORE applying this Pull Request
The article is displayed without the image.

### Expected result AFTER applying this Pull Request
The article is displayed WITH the image.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 4127a3458d95d9cfd3782aef6b64042f06aa7c88<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42725">issues.joomla.org/tracker/joomla-cms/42725</a>.</sub>

**Comment by fgsw** [comment]
I have tested this item :white_check_mark: successfully on 4127a3458d95d9cfd3782aef6b64042f06aa7c88<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42725">issues.joomla.org/tracker/joomla-cms/42725</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42725">issues.joomla.org/tracker/joomla-cms/42725</a>.</sub>

**Comment by MacJoom** [comment]
Thank you!

**Pull request merged**
