### PR TITLE
[5.1] Changelog deprecation

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue # .

### Summary of Changes
declared `folder`

### Testing Instructions
php 8.2
Have a plugin extension with changelog
goto Extensions:Manage and click on the extension changelog button

### Actual result BEFORE applying this Pull Request
image

### Expected result AFTER applying this Pull Request
no more deprecation

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by cybersalt** [comment]
I could not duplicate this, but the only extension that I had a version to click on was a component, not a plugin. Do you know of a plugin I could install for testing?

**Comment by alikon** [comment]
this plugin from jed https://extensions.joomla.org/extension/content-export-article/

**Comment by exlemor** [comment]
I have tested this item :white_check_mark: successfully on 1a6a22fb615e7c25d0387c046aa0972ad99bc1ec<br /><br />I was able to test this successfully - thanks @alikon.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43219">issues.joomla.org/tracker/joomla-cms/43219</a>.</sub>

**Comment by cybersalt** [comment]
I have tested this item :white_check_mark: successfully on 1a6a22fb615e7c25d0387c046aa0972ad99bc1ec<br /><br />Tested this (after some help!) and it works.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43219">issues.joomla.org/tracker/joomla-cms/43219</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43219">issues.joomla.org/tracker/joomla-cms/43219</a>.</sub>

**Comment by HLeithner** [comment]
I expect that's also relevant for 4.4?  @MacJoom

**Comment by bembelimen** [comment]
Thanks

**Pull request merged**
