### PR TITLE
Update jQuery Autocomplete to 1.4.11

### PR DESCRIPTION
**Pull request by viocassel**
### Summary of Changes
This PR updates [jQuery Autocomplete](https://github.com/devbridge/jQuery-Autocomplete) library to version [1.4.11](https://github.com/devbridge/jQuery-Autocomplete/releases/tag/v1.4.11) for **com_finder** and **mod_finder**.

### Testing Instructions
1. Apply patch
2. Test the **com_finder** and **mod_finder** typing any word in search field (for example, _joomla_)
3. Make sure there are no JS errors and the list dropdown displayed correctly.

### Result
**com_finder**
com_finder

**mod_finder**
mod_finder

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on b32fd8cf6b63dbb16f11748de2ede7df35adedb9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28965">issues.joomla.org/tracker/joomla-cms/28965</a>.</sub>

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on b32fd8cf6b63dbb16f11748de2ede7df35adedb9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28965">issues.joomla.org/tracker/joomla-cms/28965</a>.</sub>

**Comment by SharkyKZ** [comment]
RTC.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28965">issues.joomla.org/tracker/joomla-cms/28965</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
