### PR TITLE
[4.0] JSON syntax error on PostgreSQL

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue # .

### Summary of Changes

Fixes JSON syntax error in PostgreSQL installation file.

### Testing Instructions

Only on PostgreSQL
On a clean installation edit `Home` menu item.

### Expected result

No errors.

### Actual result

JSON syntax error.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by alikon** [comment]
quite off-topic if you have can you look at #26297

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on fa9e1da047ccf87fd4cbf1e83313c8530ca01694<br /><br />Code review. Missing closing double quote

> "show_readmore_title":"

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26298">issues.joomla.org/tracker/joomla-cms/26298</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on fa9e1da047ccf87fd4cbf1e83313c8530ca01694<br /><br />Code review. Same result as Quy.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26298">issues.joomla.org/tracker/joomla-cms/26298</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26298">issues.joomla.org/tracker/joomla-cms/26298</a>.</sub>

**Comment by HLeithner** [comment]
Thanks for fixing postgres installation.

**Pull request merged**
