### PR TITLE
Open the Joomla Update Info URL in a new window

### PR DESCRIPTION
**Pull request by webmasterab**
Open in a new window

### CODE REVIEW

**Comment by webmasterab** [comment]
Vraag ik zie deze nu niet terug in mijn lcale GitHub programma?

Wie kan me hiermee helpen.

Of zie je eigen pulls niet in je locale omgeving?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7871">issues.joomla.org/joomla-cms/7871</a>.</sub>

**Comment by Kubik-Rubik** [comment]
@webmasterab Please write only in English here! Also provide a detailed description and a test instruction for your Pull Request (PR). Thanks!

**Comment by roland-d** [comment]
I am not sure this change is needed, you can open the link in a new window by right clicking it.

**Comment by webmasterab** [comment]
there I just in its response to the Dutch translation here

Question I see this now not back in my lcale GitHub program?

Who can help me with this.

Or do not see your own pulls in your local area?

**Comment by webmasterab** [comment]
@roland-d I understand your reaction, but ..
For people who do not often work with the computer it is nice that it is bound to come.
Then they do not get rid of the basic page

**Comment by 810** [comment]
for ux I say +1 for the change, all external links should be opened in a new tab.

for the question:
your commit should be on top.

**Comment by brianteeman** [comment]
It's an accessibility failure to force opening in a new window

**Comment by mbabker** [comment]
For UX it is nice, but actually there is an accessibility recommendation
that says to not force opening new windows (the JED implemented this
pattern based on that).

**Comment by brianteeman** [comment]
Reference http://webaim.org/techniques/hypertext/hypertext_links

**Comment by MAT978** [comment]
The externality of the link should not be the only criterion to be considered but also the "skill" of the "target" user. Each link case should be considered (despite what some "expert" want to assert as truth) but here, IMHO and regarding the user concerned, I am not in favor of _blank.

**Comment by zero-24** [comment]
Needs Review so the PLT have the last voice on this.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7871">issues.joomla.org/joomla-cms/7871</a>.</sub>

**Comment by Hackwar** [comment]
@brianteeman is right here. Forcing this is wrong. If the person doing an update is not knowledgeable enough to know what a right-click is, he/she should not manage a website in the first place. Sorry.

**Comment by webmasterab** [comment]
I know very well what is a right.
I am concerned about people using joomla who do not know.
But it is clear to me
Thanks for your answer

**Comment by roland-d** [comment]
@webmasterab As the consensus is to not force the link to open in a new window, I am going to close this issue. Thank you for your contribution.

**Pull request closed without merging**
