### PR TITLE
[4.0] incompatible.html

### PR DESCRIPTION
**Pull request by brianteeman**
I assume that this was a typo as its not valid

### CODE REVIEW

**Comment by mbabker** [comment]
Unless we're still supporting [massively dated browser hacks](https://stackoverflow.com/questions/1690642/purpose-of-asterisk-before-a-css-property/1690683) I agree.

**Comment by dgrammatiko** [comment]
nice catch! @laoneo please merge?

**Comment by brianteeman** [comment]
Thanks

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
