### PR TITLE
Tags Manager - Add count and link to tag items

### PR DESCRIPTION
**Pull request by alikon**
#### Goal

This PR adds the number of published, unpublished, archived and trashed "content type" in the Tag Manager for the "content type" that have a tag.
Something like  works with Categories Manager
#### After Patch

You can select the tag "content type"  alias article, contact, newsfeed, weblink ect
staging administration tags manager

and have a better idea where tags  are located
test administration tags manager2

### CODE REVIEW

**Comment by infograf768** [comment]
please alpha order the new language strings.

**Comment by alikon** [comment]
language string ordered

**Comment by anibalsanchez** [comment]
I have tested this item :white_check_mark: successfully on 11d355e4c9f59db02390475bb21cd163aab560b0<br /><br />It works OK<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8975">issues.joomla.org/joomla-cms/8975</a>.</sub>

**Comment by brianteeman** [comment]
Sorry I dont like - this - Even testing it I found it confusing that the new columns only appear when you have selected a "tag Type" - it is also confusing that you see all the tags when you have selected "tag type" even if the tag is not used for that type. It looks like a filter, its located in the search filters section but it is not a filter.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8975">issues.joomla.org/joomla-cms/8975</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :red_circle: unsuccessfully on 11d355e4c9f59db02390475bb21cd163aab560b0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8975">issues.joomla.org/joomla-cms/8975</a>.</sub>

**Comment by alikon** [comment]
> It looks like a filter, its located in the search filters section but it is not a filter.

yes brian is a strange "thing", but it is a wanted behaviour :satisfied:
you can have a better control/map of your tags in this way

how can be improved to be an easy feature ?

**Comment by genesisfan** [comment]
I have tested this item :white_check_mark: successfully on 11d355e4c9f59db02390475bb21cd163aab560b0<br /><br />Useful to me.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8975">issues.joomla.org/joomla-cms/8975</a>.</sub>

**Comment by brianteeman** [comment]
Set to Needs Review so the maintainers can make a decision<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8975">issues.joomla.org/joomla-cms/8975</a>.</sub>

**Comment by wilsonge** [comment]
"As is" this shouldn't be merged - we need to use helpers in each component so that custom components can hook into this functionality - look at how we did it for the categories.

**Comment by alikon** [comment]
closed  
please test the new one #10895 with helpers for custom components

**Pull request closed without merging**
