### PR TITLE
Hidden fieldsets

### PR DESCRIPTION
**Pull request by bembelimen**
#### Summary of Changes

If you create a repeatable field (via e.g. a plugin) and add it to differnt components (e.g. com_users), the fieldsets from the field are displayed as empty tabs
#### Testing Instructions

1, Add the XML code for a repeatable field to administrator/components/com_users/models/forms/user.xml (or write a plugin which loads a differnt XML into the user form). See here for the code: https://docs.joomla.org/Repeatable_form_field_type
2. Open the user component and create a new user
3. a "broken" tab should appear
4. Apply patch => try again

### CODE REVIEW

**Comment by chmst** [comment]
I've testet this successfully.  Before the patch: three Repeatable fields caused three "ghost" tabs. After applying the patch, no ghost tabs at all.

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on b06fa8ea02b982ec687cc6be9e04abe2096c155b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9960">issues.joomla.org/joomla-cms/9960</a>.</sub>

**Comment by poirierchristophe** [comment]
I have tested this item :white_check_mark: successfully on b06fa8ea02b982ec687cc6be9e04abe2096c155b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9960">issues.joomla.org/joomla-cms/9960</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9960">issues.joomla.org/joomla-cms/9960</a>.</sub>

**Pull request merged**
