### PR TITLE
[4] Remove unused imports

### PR DESCRIPTION
**Pull request by Quy**
### Testing Instructions
Code review.

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 8fd3a1df2417ec1d36312ca7a6f5e1fc0a55a8c0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34769">issues.joomla.org/tracker/joomla-cms/34769</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 8fd3a1df2417ec1d36312ca7a6f5e1fc0a55a8c0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34769">issues.joomla.org/tracker/joomla-cms/34769</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34769">issues.joomla.org/tracker/joomla-cms/34769</a>.</sub>

**Comment by chmst** [comment]
Thanks!

**Pull request merged**
