### PR TITLE
mod_menu: Allowing to exclude menu items from displaying in frontend menus

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Description

This PR adds the ability to exclude menu items from displaying in frontend in mod_menu.

Simple use case:
We have a menu where we have 5 items: Home; The company; Services; Portfolio; Contacts
But we don't want to show "Home" in the main menu, just: The company; Services; Portfolio; Contacts.

This PR will also allow to create "hidden" menu items that exist in the menu and the website but aren't displayed in the main menu without having to create another menu for those "hidden" menu items.
#### How to test
1. Fresh Joomla install with multilanguage.
2. Apply this patch
3. Go to the main menu module and use the new field "Exclude Menu Items" to exclude some menu items from displaying in the frontend menu.
4. Check in the frontend it those items are not displayed in the main menu.
#### Observations

Suggestions are welcome.

### CODE REVIEW

**Comment by Bakual** [comment]
Personal opinion: This would be a parameter which solves something that is already possible with the current menu modules. Just put those menu items into a menu that isn't attached to a menu module (hidden menu).

**Comment by brianteeman** [comment]
There are definite advantages to being able to "hide" individual menu items within the structure of an existing menu. It is not the same as having a specific menu for hiding all menu items.

I regularly have to do this either with CSS or an existing extension. It would be great to have this in the core.

**Comment by andrepereiradasilva** [comment]
@Bakual yes i know the hidden menu trick.

But if you try to that with the "Home page" menu item it gets complicated (you have to create multiple menus with menu items reference others). If you try to that in multilanguage menus is even more complex.

Another thing is, how do you hide, for instance, a level 2 (or deeper) menu item of the main menu with an hidden menu?

As @brianteeman i have the same problem in many sites.

**Comment by brianteeman** [comment]
Would it not make more sense from a usability perspective to set the exclusion in the menu item and not the module. This method is no different to existing alternative menu modules.

**Comment by justinherrin** [comment]
I vote that having a toggle yes/no switch in the menu item edit screen would make the most sense for usability and overall workflow.

**Comment by andrepereiradasilva** [comment]
The only problem i see with that is a less flexibility.

If the exclusion option is in the module you can have different modules (applied to different pages) showing the same menu with different levels and/or exclusions (like topmenu and sidemenu).

If the exclusion option is in the menu item you can't do that. The exclusion of the menu item is for all menu modules that call that menu.

**Comment by brianteeman** [comment]
http://extensions.joomla.org/extensions/extension/structure-a-navigation/menu-systems/menu-wrench does what this PR does and more.

**Comment by andrepereiradasilva** [comment]
@brianteeman i know that are a lot of extensions for menus.

I will check putting that option in the menu item itself.

**Comment by andrepereiradasilva** [comment]
@brianteeman @justinherrin closed this because opened https://github.com/joomla/joomla-cms/pull/8816 with the same behaviout but now with menu item option.

**Comment by andrepereiradasilva** [comment]
> Regarding #8814. I see this one has also great usability. Assume some case when we want to render same menu and show different set of menu items in different menu module positions!
> With that we could override/inherit the selections at will. 

@izharaazmi i agree with you. that's why in my first PR (this one) i use the module and not the menu item.
But i also agree with @brianteeman @justinherrin since i can see the use for both options.
I will not do more PR regarding this matter (i have other PR to do), but you are free to do it. And use this code if you want.

**Pull request closed without merging**
