### PR TITLE
[4.0] Fix overrides language strings

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
Change/match constant keys to values.
Fix sort dropdown to display correctly when sorting by text.

### Testing Instructions
Go to System > Language Overrides
Create overrides
Click Text header to sort
See `Sort Table by` dropdown not showing the selection

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on d646d86e5d37c16dd043a5511dd115279ea9caae<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27265">issues.joomla.org/tracker/joomla-cms/27265</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on febf70e4a28b91e93087611fa3d387c1635d6323<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27265">issues.joomla.org/tracker/joomla-cms/27265</a>.</sub>

**Comment by infograf768** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27265">issues.joomla.org/tracker/joomla-cms/27265</a>.</sub>

**Comment by infograf768** [comment]
tks

**Pull request merged**
