### PR TITLE
Missing space in Mod custom

### PR DESCRIPTION
**Pull request by N6REJ**
Pull Request for Issue # .
#### Summary of Changes

added the missing space between 'custom' and 'suffix'
#### Testing Instructions

create a custom module, look at the module class and you'll see "custom"
add a class suffix and you'll see "customYOURSUFFIX"  this is not as expected, nor consistent with the rest of the module class suffix behaviors.
after this patch you'll see that it is now "custom YOURSUFFIX"

### CODE REVIEW

**Comment by N6REJ** [comment]
not sure why its saying 3 commits but this is correct.

**Comment by mbabker** [comment]
This is the expected (even if anti-UX) behavior.  Leave no space and you
can completely remove the custom class and use it as a prefix for the
user's input class.  Add a space and it adds additional class(es) to the
div.

**Comment by ggppdk** [comment]
@N6REJ 
it is like this in all modules, not just for this module 
and it has been always like this

and it is consistent with the parameter name "...sfx" and description
plus this change would cancel custom styling rules for existing websites

**Comment by brianteeman** [comment]
Closing for the reasons stated above

**Comment by N6REJ** [comment]
the problem is that its inconsistent with the rest of class suffix's.  before it was like this for ALL suffix's ( components ) and modules, or am I mistaken?

**Comment by ggppdk** [comment]
You can do a recursive text search in the modules folder
```
<?php echo $moduleclass_sfx
```

you will see that all 
- Joomla modules 
- majority (but not all (their choice ...)) of 3rd party modules

**do not add space** 

and if you want to add a **new class** to it, just use the parameter like this:
_mySuffix  myClassName

thus this:
**custom<?php echo $moduleclass_sfx ?>**

will become:
**custom_mySuffix  myClassName**

**Comment by Mocha365** [comment]
It's 2017 and just found this Pull Request (which I see is closed), so am I missing something or has the missing space been put back in as missing? Joomla 3.7.4 has most if not all modules "still" missing the space. Example of what is still showing

`<div class="custom<?php echo $moduleclass_sfx; ?>`

There's no space after "custom" or in other modules. Right now, adding a class suffix to any module results in:

`moduletablemyclass `

instead of:

`moduletable myclass`

**Comment by mbabker** [comment]
As stated above, it's an explicit design decision.  With no space, you can suffix the class that comes before it in a layout (in this case, the `custom` class) which would let you completely remove that class from things, or you can prefix your input with a space and add additional classes.

**Pull request closed without merging**
