### PR TITLE
Convert IDNA_Convert library to be Composer managed, update to 0.9

### PR DESCRIPTION
**Pull request by mbabker**
This PR moves the IDNA_Convert library from a Joomla library extension to being managed via Composer (using https://github.com/phpWhois/idna-convert as the source).  It also runs an update to version 0.9 of the library and restores the accidentally deleted test class for our Punycode conversions (only affects the 3.5 branch).
### Testing

With the patch applied, things should still work as intended.  If you've got strings going through the Punycode library (I'm sure JM can tell us all where this is checked), those should still be processed correctly.

### CODE REVIEW

**Comment by infograf768** [comment]
e-mail fields and urls fields. 
Basically for example:
Entering in the field: `http://www.джумла-тест.рф/master`
will be saved in the db as:
`http://www.xn----7sblgc4ag8bhcd.xn--p1ai/master`
and will still display in the field as:
`http://www.джумла-тест.рф/master`

When it is used in a page, it is the punycoded version stored in the db which is used.
So we will see:
screen shot 2015-07-27 at 08 39 42

but the source will be:
```
>
		<span class="contact-webpage">
			<a href="http://www.xn----7sblgc4ag8bhcd.xn--p1ai/master" target="_blank" itemprop="url">
			http://www.джумла-тест.рф/master</a>
		</span>
```

**Comment by infograf768** [comment]
Found a small issue which is not related to this patch when displaying contact profile in front-end.
```
Website:</label></dt><dd><a href="http://www.xn----7sblgc4ag8bhcd.xn--p1ai/index.php">http://www.xn----7sblgc4ag8bhcd.xn--p1ai/index.php</a></dd>		</dl>
```
Will try to find where it is done.

**Comment by infograf768** [comment]
See https://github.com/joomla/joomla-cms/pull/7585

**Comment by mbabker** [comment]
Resubmitting against staging.

**Pull request closed without merging**
