### PR TITLE
[5.2] [Guided Tours] Arrows do not show properly, especially in dark mode

### PR DESCRIPTION
**Pull request by obuisard**
### Summary of Changes

When introducing dark mode, a border was added to the tour popups so that the tours would be more visible in dark mode.
Unfortunately, this 'cuts' the arrows off the popup and no border was added to the arrows themselves so that they are not visible in dark mode.

This is the first attempt in fixing that.

Although this PR fixes the arrows, there is more to be done, particularly that the colors for the tour popups are too dark and barely pop over the content. Check PR#43854.

### Testing Instructions

Run the welcome tour in light and dark mode and check that the arrows are showing properly.

### Actual result BEFORE applying this Pull Request

A popup in light mode.
The popup border shows over the arrow and the arrow is not of the color of the header background.

light_before

A popup in dark mode.
The border cuts off the arrow from the popup and is barely visible.

dark_before

### Expected result AFTER applying this Pull Request

A popup in light mode.
The border is gone and the arrow is of the right color.

light_after

A popup in dark mode.
The border no longer cuts off the arrow from the popup and the arrow is more visible.

image

image

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on da2ff39dfb2c6ae35304e07b8aab28553866cbd7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43825">issues.joomla.org/tracker/joomla-cms/43825</a>.</sub>

**Comment by LadySolveig** [comment]
I have tested this item :white_check_mark: successfully on da2ff39dfb2c6ae35304e07b8aab28553866cbd7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43825">issues.joomla.org/tracker/joomla-cms/43825</a>.</sub>

**Comment by obuisard** [comment]
I sincere apology, I did not refresh my page and did not see the latest test and RTC label.
I reverted the unnecessary change in background color of the popup header, which has no effect on the arrow fixes I made in this PR, therefore the tests would return the same results.

**Comment by pe7er** [comment]
Thanks @obuisard !

**Pull request merged**
