### PR TITLE
Notice:  Undefined index: cache_path in /administrator/components/com_config/model/application.php on line 289

### PR DESCRIPTION
**Pull request by infograf768**
As title says:

### Test instructions
Create a Site Settings menu item, display it in frontend.
Log as superadmin and save the site settings.
The Notice above will display in the PHP logs.

Patch. No more Notice.

### CODE REVIEW

**Comment by AlexRed** [comment]
I have tested this item :white_check_mark: successfully on 46be6bb7e4f03fce717a7d522d969ce0eb99486f<br /><br />Patch ok for me<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15757">issues.joomla.org/tracker/joomla-cms/15757</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 46be6bb7e4f03fce717a7d522d969ce0eb99486f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15757">issues.joomla.org/tracker/joomla-cms/15757</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Review by mbabker — DISMISSED** [review]
We shouldn't have client specific handling in our save global configuration routine.  Also, this now results in the `$path` variable being undefined when you get into the next check which would emit a PHP warning except for the fact we're using error suppression.

**Comment by infograf768** [comment]
@mbabker 
> We shouldn't have client specific handling in our save global configuration routine. Also, this now results in the $path variable being undefined when you get into the next check which would emit a PHP warning except for the fact we're using error suppression.

Would you prefer a simple:
```
if (isset($data['cache_path']))
			{
				$path = $data['cache_path'];
			}
			elseif (!empty($prev['cache_path']))
			{
				$path = $prev['cache_path'];
			}
			else
			{
				$path = JPATH_SITE . '/cache';
			}
```

**Comment by mbabker** [comment]
`isset` would be better and more consistent with the existing checks.

**Comment by infograf768** [comment]
Done.
@AlexRed @franz-wohlkoenig 
Please test again

**Review by mbabker — APPROVED** [review]

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 46be6bb7e4f03fce717a7d522d969ce0eb99486f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15757">issues.joomla.org/tracker/joomla-cms/15757</a>.</sub>

**Comment by AlexRed** [comment]
I have tested this item :white_check_mark: successfully on 46be6bb7e4f03fce717a7d522d969ce0eb99486f<br /><br />Patch ok for me<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15757">issues.joomla.org/tracker/joomla-cms/15757</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC

**Comment by infograf768** [comment]
@rdeutz this can now go in.

**Comment by demis-palma** [comment]
I have tested this item :red_circle: unsuccessfully on https://github.com/joomla/joomla-cms/commit/46be6bb7e4f03fce717a7d522d969ce0eb99486f
See https://github.com/joomla/joomla-cms/pull/15813

**Pull request merged**
