### PR TITLE
Update branches and fix some references still pointing to staging

### PR DESCRIPTION
**Pull request by zero-24**
### Summary of Changes

Update branches and fix some references still pointing to staging

### Testing Instructions

review

### Actual result BEFORE applying this Pull Request

some references still pointing to staging

### Expected result AFTER applying this Pull Request

references pointing to 3.10-dev

### Documentation Changes Required

none

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on c5aea50da4d07d73de330c5a2eaaca90b4ff257c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35073">issues.joomla.org/tracker/joomla-cms/35073</a>.</sub>

**Comment by richard67** [comment]
@zero-24 I've made a PR for you with further changes related to staging references in the 3.10-dev branch, see https://github.com/zero-24/joomla-cms/pull/50 . Let me know if you prefer that to be not in this PR, then I make an own one.

**Comment by zero-24** [comment]
Merged.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on cdadca14cd0d0cccaf30c3177fa3a4ec508196dd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35073">issues.joomla.org/tracker/joomla-cms/35073</a>.</sub>

**Comment by richard67** [comment]
@brianteeman Could you test (or review) again? Thanks in advance.

**Comment by brianteeman** [comment]
cant test only review ;)

I dont understand the non-feature-branch part so not confident to say yes or no to this pr

**Comment by richard67** [comment]
> I dont understand the non-feature-branch part so not confident to say yes or no to this pr

@brianteeman See https://getcomposer.org/doc/04-schema.md#non-feature-branches

**Comment by brianteeman** [comment]
lol - i read that twice before I commented

**Pull request merged**
