### PR TITLE
Redo Cosmetic Changes for the backend by @spignataro  and fix other CS in that file

### PR DESCRIPTION
**Pull request by zero-24**
This PR is a Redo of Cosmetic Changes for the backend (https://github.com/joomla/joomla-cms/pull/2591) by @spignataro  and fix other CS in that file.

It should be a CS only PR that don't change how the file works. May thanks @spignataro

### CODE REVIEW

**Comment by jessicadunbar** [comment]
Successful test<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6431">issues.joomla.org/joomla-cms/6431</a>.</sub>

**Comment by Kubik-Rubik** [comment]
Thank you @zero-24 and @spignataro!

We have successful tests and easy changes, I will merge it.

**Comment by zero-24** [comment]
Thanks @jessicadunbar and @Kubik-Rubik :+1:

**Comment by spignataro** [comment]
Thanks zero - totally slipped my mind on getting this updated and pushed through. Thanks for doing this :-)

**Pull request merged**
