### PR TITLE
Move component message to system-message-container

### PR DESCRIPTION
**Pull request by n9iels**
With the move of all the filter from the left sidebar to `joomla.serachtools` some component messages has a small layout issue. The messages are stick to the serachtools, without padding.

This PR moves all messages like "Enable this plugin", "This option is enabled" to a `JFactory::getApplication()->enqueueMessage()`. So they will be displayed above the serachtools. All messages like "There are no item available` stay below the searchtools.
## Test instructions

Compare the following screenshots
1) Go to Components -> Smart Search
Before the patch:
com_finder before

After the patch:
com_finder after

2) Go to Extensions -> Manage -> Database
Before the patch:
com_installer database before

After the patch:
com_install database after

3) Go to Extensions -> Install
Before patch:
com_install before

After patch:
com_install after

4) Go to Extensions -> update
Before patch:
com_install update before

After patch:
com_install update after

5) Go to Components -> Redirect
Before the patch:
com_redirect before

After the patch:
com_redirect after

6) Go to components -> Search
Before the patch:
com_search before

After the patch:
com_search after

7) Disable the plugin, and enable/disable the Gathering statistics options. Confirm the messages are the same before and after the patch
## Question

Does anybody know if the remove of `administrator/manifests/packages/pkg_weblinks.xml` in this PR is something I should care about?

### CODE REVIEW

**Comment by wilsonge** [comment]
The package is required to help people who previously had weblinks installed to transition to the new version. If weblinks doesn't exist when you update Joomla then the file is removed (https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_admin/script.php#L1435-L1443)

**Comment by n9iels** [comment]
@wilsonge thx for the explanation, I re-add that file :)

**Comment by brianteeman** [comment]
Looks like there are some language changes here that are unrelated

**Comment by n9iels** [comment]
That language change is correct. The new message for com_cache has the text "Warning" by default and is generated by `Factory::getApplication()->enqueueMessage()`. Without that language change, it say something like:
<b>Warning</b>
WARNING: This can be resource intensive on sites with a large number of items!

**Comment by brianteeman** [comment]
OK

**Comment by Bakual** [comment]
The one for the expired cache looks a bit wrong afterwards. Because the message relates to the other text. With this PR you first get the warning and only afterwards for what the warning actually is.
I would revert that as it makes more sense when the warning comes right AFTER the text it is tied to.

On a general note, I think the message generation (enqueueMessage) should be done in the view class and not in the layouts. Reason is mainly because the output isn't part of the layout anymore now and you want to show the message regardless of layout. In the view, you often also have the application object already available.

Other than that, I think it makes sense to use the API to show such warnings/notices.

**Comment by n9iels** [comment]
@Bakual agree with that.
I move the enqueueMessage to the `view.html.php` of the components. Better?

**Comment by Bakual** [comment]
Yep, looks better to me now.
I see you also moved CSS to the template. If you really want to do that, you need to do it in the LESS file (https://github.com/joomla/joomla-cms/blob/staging/administrator/templates/isis/less/template.less) and run https://github.com/joomla/joomla-cms/blob/staging/build/generatecss.php afterwards.
However I don't really see why we even have the CSS in place. The difference is only minor. Imho, we could remove the CSS and also the special class `j-jed-message`. Or does anyone know why that is there?

**Comment by n9iels** [comment]
I can't find why and when that class and css were add. My only guess is that the colour is done for usability, so you can see the difference between the links and the normal text. For the `line-height` I have no idea...
The other css class for that view is for the loader. I think that class can stay there, because the loader is not used for many page. So we don't have to load that images every time.

And yes off course, make the changes in LESS. How could I forget that.... :sweat_smile:

**Comment by datredweb** [comment]
I have tested this item :red_circle: unsuccessfully on 379b5136208be2a960df8ba6f25934d4a01913eb<br /><br />after clicking on Smart Search, there is error shown up:

JForm::getInstance could not load file<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8282">issues.joomla.org/joomla-cms/8282</a>.</sub>

**Comment by n9iels** [comment]
@datredweb I cannot reproduce that error. Also, this PR didn't change anything for

**Comment by 810** [comment]
@test +1

**Comment by infograf768** [comment]
The new css in Isis
```
+.j-jed-message {
+	line-height: 2em;
+	color:#333333;
+}
```
should be added in the less file and then cli generatecss has to be used.

**Comment by n9iels** [comment]
I add the css tot the less file. The change in the template.css less of protostar is someting from #7776. Seems like I made a mistake over there.

I will solve that merge conflicts later

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on e615b7346cdf954bcca7b37a2c81dc34d19ea7f3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8282">issues.joomla.org/joomla-cms/8282</a>.</sub>

**Comment by Bakual** [comment]
@n9iels It's what I had to fix in https://github.com/joomla/joomla-cms/pull/8174/files#diff-14ca7868cfa55fda9bc6a3b963e73541L398 as well :)

**Comment by n9iels** [comment]
uhm.... can anyone tell me what just happened?...
I tried to solve the merge conflicts and now it seems like I deleted all my changes for this branch :cry:

**Comment by zero-24** [comment]
yes. there are no changes now here. And the PR is closed. maybe you can revert the last commit and see what happens?

**Comment by n9iels** [comment]
well, that is exactly what I did. I tried to solve the merge conflicts, but the whole staging came up with it. So I revert that commit, and this happened.

I think I have a copy of the branch on my pc (working from a laptop now). I hope so....

**Comment by Bakual** [comment]
If you have the old state somewhere, just force push it, replacing the code on GitHub completely.

**Comment by infograf768** [comment]
And please post here the # of the new PR

**Comment by n9iels** [comment]
Please see #8399

**Pull request closed without merging**
