### PR TITLE
[4.3] Prevent modal from closing when showing an error

### PR DESCRIPTION
**Pull request by heelc29**
Pull Request for Issue #39150 .

### Summary of Changes

The modal is only closed if the iframe does not contain an element `joomla-alert[type="danger"]`.

### Testing Instructions

see #39150

The error also occurs with _Single Contact_ (if name contains only spaces):
image

### Actual result BEFORE applying this Pull Request

Modal is closed

### Expected result AFTER applying this Pull Request

Modal still open and show error message (like when only `Save` is clicked)

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by alikon** [comment]
@heelc29  can you please contact me vicepresident.at.opensourcematters.org

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on bc5f9c3fefbcbad88c691eb8e8b7c9885f7274ef<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39173">issues.joomla.org/tracker/joomla-cms/39173</a>.</sub>

**Comment by fancyFranci** [comment]
I have tested this item :white_check_mark: successfully on bc5f9c3fefbcbad88c691eb8e8b7c9885f7274ef<br /><br />I tested the case from the issue and the PR does not let the modal close.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39173">issues.joomla.org/tracker/joomla-cms/39173</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39173">issues.joomla.org/tracker/joomla-cms/39173</a>.</sub>

**Comment by obuisard** [comment]
Thank you @heelc29 for this PR

**Pull request merged**
