### PR TITLE
[4.0] namespace path

### PR DESCRIPTION
**Pull request by brianteeman**
PR for #29725

Updates the path of the autoloader in the plugin description

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 6a5dbb338fd083e3a43a7aba2760f9883b178858<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29726">issues.joomla.org/tracker/joomla-cms/29726</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 6a5dbb338fd083e3a43a7aba2760f9883b178858<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29726">issues.joomla.org/tracker/joomla-cms/29726</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29726">issues.joomla.org/tracker/joomla-cms/29726</a>.</sub>

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on 6a5dbb338fd083e3a43a7aba2760f9883b178858<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29726">issues.joomla.org/tracker/joomla-cms/29726</a>.</sub>

**Comment by brianteeman** [comment]
thx

**Pull request merged**
