### PR TITLE
PDO insertid does not return last inserted row id

### LINKED ISSUE #9534: Error when saving file after updating to Joomla 3.5
#### Steps to reproduce the issue
Update Joomla 3.4 with Joomla-Updater
Open an article and save it.

#### Expected result
No error messages.

#### Actual result
getting the following error:

`Fehler
Speichern fehlgeschlagen! Fehler: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0-11' for key 'PRIMARY'`

#### System information (as much as possible)
PHP 7.0 as CGI
MySQL 5.5.46

#### Additional comments
The good thing is: The article is saved to the database even if I get this error. 

How can I figure out where I have duplicate entries? How did this happen? Has it something to do with my recent update of Joomla to 3.5?
How can I solve this problem or should I just use a backup and try again?

### PR DESCRIPTION
**Pull request by chrisdavenport**
Found a way to make it work, I think.

Should fix #9534 and #9582.

### CODE REVIEW

**Comment by brianteeman** [comment]
Can you write some test instructions please.

**Comment by mbabker** [comment]
That works for PDO MySQL, but other PDO connections will fail.  The unit tests fail here because the function doesn't exist on SQLite (which is the engine most of the unit tests are running off of).

**Comment by chrisdavenport** [comment]
I had a feeling something like that might be the case.  Looks like the problem is in PDO itself and may not be fixable in Joomla without some hacky workarounds.

**Comment by wilsonge** [comment]
Can we not just put this in the PDOMySQL driver file then Chris?

**Comment by chrisdavenport** [comment]
I didn't know that file even existed!  I've never used PDO before.  It looks like it will need specific fixes for MSSQL and possibly others too, which surely defeats the object of using PDO in the first place.

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on 78c57c96b6a2bca34c7a7b55eb3dd7442dc8c012<br /><br />it also fixes #9572<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9601">issues.joomla.org/joomla-cms/9601</a>.</sub>

**Comment by mbabker** [comment]
Are we sure this isn't either a PHP bug or a Joomla implementation bug?  Seems odd that a method in a PHP extension would fail so catastrophically.

**Comment by chrisdavenport** [comment]
Closing in favour of #9610.

**Comment by zero-24** [comment]
can someone please remove the wrong milestone here? @brianteeman @wilsonge @mbabker

**Comment by wilsonge** [comment]
done - thanks :)

**Pull request closed without merging**
