### PR TITLE
[4.0] Postgres default date

### PR DESCRIPTION
**Pull request by brianteeman**
Postgres uses 1970 as the default date ;)

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on f73903fd54abd0b198308dfa8d50dfce2192a4b0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24136">issues.joomla.org/tracker/joomla-cms/24136</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on f73903fd54abd0b198308dfa8d50dfce2192a4b0<br /><br />Code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24136">issues.joomla.org/tracker/joomla-cms/24136</a>.</sub>

**Comment by ghost** [comment]
Status "Ready To Commit".

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
