### PR TITLE
[4.3][Guided Tours] Fixed News Feed tour and User tour target

### PR DESCRIPTION
**Pull request by khu5h1**
Pull Request for Issue #40001
Guided Tour Project #39902 

### Summary of Changes
Fixed News Feed Status target

### Actual result BEFORE applying this Pull Request
main

### CODE REVIEW

**Comment by Quy** [comment]
Please review the sql files in updates directory to see how it should  be done.

**Comment by obuisard** [comment]
Khushi @khu5h1 the latest SQL updates are incorrect. They will replace more than what needs to be replaced. You need to be more specific in the WHERE clause :-)
```
UPDATE `#__guidedtour_steps`
SET `target` = '#jform_published'
WHERE `target` = '#jform_state';
```

**Comment by khu5h1** [comment]
@obuisard Sure, Updating the WHERE clause. Thanks!

**Comment by obuisard** [comment]
I have tested this item :white_check_mark: successfully on 0dd13657e004753a4e5cbb9cc1c539cbc3f01bf6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40000">issues.joomla.org/tracker/joomla-cms/40000</a>.</sub>

**Comment by khu5h1** [comment]
Hi @Quy, It would be great if you could test this PR whenever you get time so, that we can merge it before the RC. Thanks!

**Comment by ChristineWk** [comment]
@obuisard 
Unfortunately I hv updated to 4.3.0-beta5-dev (before). Therefore response:
The patch could not be applied because it conflicts with a previously applied patch: administrator/components/com_admin/sql/updates/mysql/4.3.0-2023-02-15.sql

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40000">issues.joomla.org/tracker/joomla-cms/40000</a>.</sub>

**Comment by obuisard** [comment]
> @obuisard Unfortunately I hv updated to 4.3.0-beta5-dev (before). Therefore response: The patch could not be applied because it conflicts with a previously applied patch: administrator/components/com_admin/sql/updates/mysql/4.3.0-2023-02-15.sql
> 
> This comment was created with the [J!Tracker Application](https://github.com/joomla/jissues) at [issues.joomla.org/tracker/joomla-cms/40000](https://issues.joomla.org/tracker/joomla-cms/40000).

Hi @ChristineWk. Some times you cannot try patches simultaneously. Once you try a patch you should revert it so that the next patch does not rely on the previous one or create conflict.

**Comment by ChristineWk** [comment]
Hi @obuisard I tried the patch a few days before. It was unsuccessful. Checked also sql and was not sure about ....
Due to subsequent changes sql - I tried again today, but with an updated 4.3.0-beta5-dev
Had of course reverted before that.

**Comment by sdwjoomla** [comment]
I have tested this item :white_check_mark: successfully on d8a35b21bfcd1f48dca5e0f21ff8a1dcaf0d58ba<br /><br />Step 7 highlighted the Status field<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40000">issues.joomla.org/tracker/joomla-cms/40000</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40000">issues.joomla.org/tracker/joomla-cms/40000</a>.</sub>

**Comment by obuisard** [comment]
Thank you Khushi @khu5h1 !

**Pull request merged**
