### PR TITLE
Remove declaration of xml files in modules

### PR DESCRIPTION
**Pull request by shur**
This PR just ~~add missed declaration~~ remove declaration of the module xml file.

### CODE REVIEW

**Comment by zero-24** [comment]
I'm not sure. As far i know we don't need to add this via xml as we do it automatic?

**Comment by shur** [comment]
I was guided by how it's done in other modules.

**Comment by shur** [comment]
Most of xml files of modules contain this line.
So we must take a decision - if this line should be present, then it must be present in all modules.
If this line is unnecessary, then we must remove it from all modules.

**Comment by mbabker** [comment]
It is not required to list the XML as part of the manifest; it is always copied over.  As long as its consistent, the manifests can be updated either way to include or exclude the XML file.

**Comment by shur** [comment]
So what is your suggestion?
Right now it's not consistent - some module xmls have this line some don't. It's confusing for anyone who studies core Joomla modules as a base for his own module.

**Comment by mbabker** [comment]
It's not a requirement and I don't have it in any of my own extension manifests, so I would say remove it.

**Comment by shur** [comment]
Perhaps, I agree with you.
I made all modules xmls be consistent in this case.

**Comment by Bakual** [comment]
Merged into `staging` with https://github.com/joomla/joomla-cms/commit/eabb506b8f92cfdb1cd71ce2ce8e42a84894c259.
Thanks!

**Pull request closed without merging**
