### PR TITLE
[4.0] Fix Notice in edit account

### PR DESCRIPTION
**Pull request by chmst**
Pull Request for Issue #31734 .

### Summary of Changes
Remove  Line 91 	<?php echo LayoutHelper::render('joomla.edit.params', $this); ?>

This probably is the result of a merge conflict @wilsonge, after merging the PR #29251

### Testing Instructions
Set error reporting "maximum", open user - edit account 

### Actual result BEFORE applying this Pull Request
Lotes of Notices 

### Expected result AFTER applying this Pull Request
No Notices 

### Documentation Changes Required
no

### CODE REVIEW

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on 6de36f10c40904e6bdb37a5ed12067e248329b9b<br /><br />Updated Beta6-dev on 21 December but was unable to reproduce the PHP notice mentioned in #31734.  Editing user details and profile did not produce a single PHP notice.  Applied this PR and did not see any difference.  

Using PHP 8.0.0 in Wampserver 3.2.4 on Windows 10.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31744">issues.joomla.org/tracker/joomla-cms/31744</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 6de36f10c40904e6bdb37a5ed12067e248329b9b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31744">issues.joomla.org/tracker/joomla-cms/31744</a>.</sub>

**Comment by infograf768** [comment]
rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31744">issues.joomla.org/tracker/joomla-cms/31744</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
