### PR TITLE
mod_menu new option to show or hide icons

### PR DESCRIPTION
**Pull request by RoterNagel**
### Summary of Changes
I created a new option in the mod_menu. This option makes it possible to create a menu module without the defined icons from the menu item. 
Use case: main menu with icons and split menu in the sidebar without icons.

### Testing Instructions
You need 
- a joomla installation, 
- a menu with at least one menu item with a added icon,
- a module for this particular menu which is visible on the website.
menu-module-with-icon-on-website_112016_114727_am

1. Go to Extentions > modules,
2. Pick your menu module for the above mentioned menu,
3. Change settings from "Show Icons" to "no",
4. Save.

No icons in the menu module on the website.

menu-module-without-icon-on-website_112016_115201_am

optional:
5. Change settings from "Show Icons" to "Yes".
6. Save.

The icons should appear again.

### Documentation Changes Required
Maybe. Couldn't find a article about the settings from the module for the menu.

### CODE REVIEW

**Comment by brianteeman** [comment]
My personal gut feeling on this is that this should be a template override and not another option

**Comment by RoterNagel** [comment]
This is how I did this before. But I think it is not necessary to use an override when you just don't want the icons.

With an override you have to check for changes with a new joomla version. You don't get new features with an override.

**Comment by brianteeman** [comment]
without the override system we end up with a million options for everything even if they are rarely used use cases. This is what we should be really trying hard to avoid as it makes the UI very complicated for users. 
for me this is a power user feature ideally suited for overrides not for another option that is meaningless to the majority.

Anyway that is my personal opinion

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 6cf0cf448878b4ca32626363808d5803463f539b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12946">issues.joomla.org/tracker/joomla-cms/12946</a>.</sub>

**Comment by coolcat-creations** [comment]
I have tested this item :white_check_mark: successfully on 6cf0cf448878b4ca32626363808d5803463f539b<br /><br />Works as described. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12946">issues.joomla.org/tracker/joomla-cms/12946</a>.</sub>

**Comment by widmann-it** [comment]
I have tested this item :white_check_mark: successfully on 6cf0cf448878b4ca32626363808d5803463f539b<br /><br />Good testet at #JC17de<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12946">issues.joomla.org/tracker/joomla-cms/12946</a>.</sub>

**Comment by jeckodevelopment** [comment]
This PR is currently in "Needs review" status.
Please @joomla/cms-maintainers

**Comment by rdeutz** [comment]
You can do it with the current system so adding an option for this use case seems to my not a great idea. Closing this PR

**Pull request closed without merging**
