### PR TITLE
[4.0] Redirect plugin repeatable

### PR DESCRIPTION
**Pull request by brianteeman**
Use the new layout="joomla.form.field.subform.repeatable-table to be consistent with all other views.

## Before
image

## After
image

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 18f3a905426ddb625abf49d846e1ce46a2faeab1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33762">issues.joomla.org/tracker/joomla-cms/33762</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 18f3a905426ddb625abf49d846e1ce46a2faeab1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33762">issues.joomla.org/tracker/joomla-cms/33762</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33762">issues.joomla.org/tracker/joomla-cms/33762</a>.</sub>

**Comment by Quy** [comment]
Thanks

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
