### PR TITLE
Revert "[4.1] Add server timing response header in debug mode (#36231)"

### PR DESCRIPTION
**Pull request by bembelimen**
This reverts commit 360409f51cd81de6ca302ee3a51e718f26d3fa7b.

### Summary of Changes

Sorry, was to fast in merging. We should for new events only go with the new event system. So probably @laoneo you could just do the same PR with the new event system?

Sorry for the trouble.

### CODE REVIEW

**Comment by Fedik** [comment]
Also can just change `onBeforeRespond` to `onAfterRender`, that triggered almost before response.

**Comment by laoneo** [comment]
I do not agree. It uses the dispatcher which is new way. So should an empty event being introduced here or what?

**Comment by Fedik** [comment]
> So should an empty event being introduced here or what?

We have RFC for versioning https://github.com/joomla/rfc/pull/29 (though it still RFC)

> Changes that do not change signatures of functions or methods of the public API and do not add new ones can go
into a patch release.

New Event add a new public API, so it a new feature :wink: 
And new feature should not go in RC.

**Comment by laoneo** [comment]
@Fedik please read the sentence again. This is not a signature change! And it is a about patch releases and does not mention in any way RC.

**Comment by Fedik** [comment]
> This is not a signature change!

Correct, but a new public API.

**Comment by laoneo** [comment]
> Also can just change `onBeforeRespond` to `onAfterRender`, that triggered almost before response.

Actually I do not care which event is used. If there is an existing one, then this pr can change to it and revert the "new" event. But reverting a whole pr which adds some debug functionality is just ridiculous.

**Comment by laoneo** [comment]
> > This is not a signature change!
> 
> Correct, but a new public API.

Then make a pr which uses your suggested event and all is good. I will immediately test it.

**Comment by HLeithner** [comment]
Actually the original PR fixes a missing event (`onBeforeRespond`) which already exists in the abstracted class `WebApplication` (so it's not needed by allon to create the right event him self) but is missing in all abstracted and overridden classes. Beside this the event is also not triggered in the caching plugin and so would not add performance matrix when the page comes from the cache. 

So I revert my opinion on reverting this PR since the event already exists, only the PR doesn't do what would be expected if the page is full cached because of the missing `onBeforeRespond` in the caching plugin.

**Comment by laoneo** [comment]
Keep in mind, this is only something which should work in debug mode and hopefully the caching plugin is not running when debugging.

**Comment by HLeithner** [comment]
> Keep in mind, this is only something which should work in debug mode and hopefully the caching plugin is not running when debugging.

actually it does, looking at the code it also triggers the `onAfterResponse` event only in debugmode:
https://github.com/joomla/joomla-cms/blob/4.1-dev/plugins/system/cache/cache.php#L147-L155

**Comment by laoneo** [comment]
Wouldn't expect that...

**Pull request closed without merging**
