### PR TITLE
[4.0] Remove Bootstrap 2 grid classes

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Removes some old `row-fluid` and `span*` classes.

### Testing Instructions

🤷‍♂ 

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 5804934e40cbf6e2d0eb61e87202653f2ba7f161<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26420">issues.joomla.org/tracker/joomla-cms/26420</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 9e3cbee49f2b2bd9c4a446784111f84066fb5d93<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26420">issues.joomla.org/tracker/joomla-cms/26420</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26420">issues.joomla.org/tracker/joomla-cms/26420</a>.</sub>

**Comment by bembelimen** [comment]
Perhaps ```span12``` should be replaced with ```form-control``` (and additional ```form-control-sm``` if small)?

**Comment by SharkyKZ** [comment]
No need. `form-control` is  used by default and `form-control-sm` would add unintended styling.

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
