### PR TITLE
Update plg_multifactorauth_fixed.ini

### PR DESCRIPTION
**Pull request by particthistle**
### Summary of Changes
en-GB language correction: customized replaced with customised for correct localisation.

### Testing Instructions
Language change. Discovered while updating en-?? language packs today.

Strings are visible when making changes in the Multi-factor Authentication plugin.

### CODE REVIEW

**Comment by tecpromotion** [comment]
I have tested this item :white_check_mark: successfully on af6dfd9cb08a138a84e0fd0c7a3363e4ec47cbbb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38670">issues.joomla.org/tracker/joomla-cms/38670</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on af6dfd9cb08a138a84e0fd0c7a3363e4ec47cbbb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38670">issues.joomla.org/tracker/joomla-cms/38670</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38670">issues.joomla.org/tracker/joomla-cms/38670</a>.</sub>

**Comment by roland-d** [comment]
Thank you

**Pull request merged**
