### PR TITLE
[staging] Fix overrides usability

### PR DESCRIPTION
**Pull request by infograf768**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/22014
Replacing https://github.com/joomla/joomla-cms/pull/22105 (after picking some stuff from it, thanks @wilsonge 

### Summary of Changes
Separate the `language_client` field from searchtools to make it obvious what the user has to do to see the existing overrides.
(adding a bar.php for overrides)
Adding a `Select Language & Client` to the field to never have a default language/client already chosen when creating a new override (this was already extremely confusing for users with the old filter).
Taking off therefore the default site language/client and display a warning if trying to create a new override without choosing one in the dropdown.

### Testing Instructions
Install some languages.
Patch and test that creating overrides works for each language/client selected (files created in the correct overrides folder in admin and site), including when choosing "both" when creating an admin override.
Test that filtering and searching works.
Test that the warning is displayed when clicking on `New` while the language_client selection is set to `Select Language & Client`
Test filtering 

### Before patch

oldoverride

### After patch
Basic Manager new look

screen shot 2018-09-10 at 10 58 03

Dropdown choice

screen shot 2018-09-10 at 11 03 08

When a language/client has been selected (this one contains an override both in site and admin)

screen shot 2018-09-10 at 11 02 09

Creating a new override when the field is set to a specific language/client (Here French Administrator)

screen shot 2018-09-10 at 11 05 27

Displaying a Warning and redirected to the overrides view when the field is still set to `Select Language & Client`

overridewarning

Suggestions welcome to improve.

@wilsonge @mbabker

### CODE REVIEW

**Comment by infograf768** [comment]
drone failure unrelated

**Comment by wilsonge** [comment]
Why not default to the active language and site client like we did before?

**Comment by infograf768** [comment]
> Why not default to the active language and site client like we did before?

Because it was really confusing for the user. We have many forum posts about that issue since the first implementation of the overrides.
With the new select (with a null value), the user will be forced to choose the adequate language/client instead of defaulting to the site default when creating a new override.

EDIT: Basically, it means that we do not have to add a permanent Note in the overrides manager which would say: 
Beware, when creating a new override it will create it for the default site language if you have not set the filter to another one.
or, as some say:
Look at docs...

**Comment by coolcat-creations** [comment]
My clients have Usability Issues here too:
1) Why can they create an override for backend and frontend at once from context admin but not from context site?
2) Why isn't it possible to select language and context inside the edit view?
3) Why isn't it possible to search for all language keys inside the search tool?
Example: A german translation is missing and only available in english. Client has to close the edit view, change the context, go on new, search for the key and copy it, close again, change the context, click on new, paste the key.

A huge improvement would be to select the language and context inside the edit view, just like inside Menuitem edit or Article edit. This would mean that you don't have to filter the context first before editing anything. Would be great if this improvements could be considered.

**Comment by infograf768** [comment]
> Would be great if this improvements could be considered.

I have already been thinking at that. :)

This requires an important Refactoring.
In the Manager 2 separate fields, one for client and one for languages ONLY for filtering the manager.
In the edit view indeed ability to select the language and client with the search key
Add the possibility of saving a string for both clients when any client is selected.

It is quite an important change and can't be done fast.
May I suggest that we get this tessted/merged in 3.9 while we try to do the refactoring?

Not sure I understand your 3rd point though.

**Comment by coolcat-creations** [comment]
Would be great, I don't know how to code something like that but would appreciate it a lot.
For my Point 3: Certain Extensions have not complete translations for other languages. English is mostly 100 Percent and German maybe only 90 %.
So someone sees in Frontend a wrong word  means a translation is missing or wrong here. But in this situation the user does not know the language key. 
1) User goes into the overrides
2) Selects German - Site and clicks on Add
3) Is using the search tool to find the key
4) No key is found because the key only exists in english
5) Is switching to English - Site and clicks on Add
6) Is using the search tool to find the key
7) Is closing the Add View 
8) Selects German - Site and clicks on Add
9) Is pasting the language key and translates it correctly

**Comment by infograf768** [comment]
I guess your client is trying to do something which overrides are not designed for.
I try to explain:
Although they can indeed be used to add a missing string for a specific language (if one knows the constant/key) they are mostly meant to override. i.e. replace the value of an **existing** constant/key in the chosen language.

What your user wants is search for a specific `value`, not a constant. That one could be in **any** language installed on the site (think of a multilingual site). 
Searching that value for all languages in the override edit could be a long process and may be confusing. Some strings may have the same value than the one the user searches for.

It is much simpler to use the tool which is designed for that: enable debug lang, go to frontend and get the constant there, then in back-end  in the override edit view for German (site), paste the key and enter the value desired.
Beware though as a string displayed in frontend may come from a plugin. In that case, if the 3pd dev has done its work almost correctly, the string will start by `PLG_` and the user will know the "override" will have to be created in admin client.

EDIT: I do agree though that in both cases, it needs multiple actions to solve the issue.

**Comment by coolcat-creations** [comment]
Yes but for Example the Site shows a string calles "Web" which is completely legal in Germany, but the User wants to change this to "Internet". How should an Enduser know in this situation that Web comes from the english strings? Also it would not make sense to send them to the language debug on a live site. If you can select the language inside the edit view you can easyly switch between the languages without the need to leave this view. It would be solved by the refactoring :)

**Comment by infograf768** [comment]
> Yes but for Example the Site shows a string calles "Web" which is completely legal in Germany, but the User wants to change this to "Internet". How should an Enduser know in this situation that Web comes from the english strings? 

That is the job of the manager/admin, not of the enduser.

**Comment by infograf768** [comment]
> It would be solved by the refactoring :)

Partly yes, if someone helps with some AJAX magic. We are not there yet. ;)

**Comment by coolcat-creations** [comment]
> That is the job of the manager/admin, not of the enduser.

hm... overrides are imho a tool for endusers and not for admins. Admins would work with the ini files directly. But thats of course a subjective matter

**Comment by brianteeman** [comment]
If they work with the ini files directly then that would be very foolish as they would lose the changes on update

**Comment by coolcat-creations** [comment]
Never heard of lose changes of the override files at updates.

**Comment by infograf768** [comment]
Folks, while we wait for someone to work and propose a PR with Ajax totally refactoring overrides, this has to go in now. Pease test.

**Comment by B3nito** [comment]
I can't apply the patch, can you help?
grafik

**Comment by ghost** [comment]
@B3nito maybe this didn't work with Patchtester.

**Comment by infograf768** [comment]
@B3nito 
This patch is for staging, not 4.0 . 😃

**Comment by B3nito** [comment]
I updated to 3.9.0-beta2-dev now I can test.

**Comment by B3nito** [comment]
I have tested this item :white_check_mark: successfully on d1fe66e2689d720306f726fc4317c5a49cd470eb<br /><br />Tested and it is working like you described @infograf768 - thank you for more overview!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22107">issues.joomla.org/tracker/joomla-cms/22107</a>.</sub>

**Review by brianteeman — APPROVED** [review]
approve language string changes

**Comment by alikon** [comment]
I have not tested this item.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22107">issues.joomla.org/tracker/joomla-cms/22107</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on d1fe66e2689d720306f726fc4317c5a49cd470eb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22107">issues.joomla.org/tracker/joomla-cms/22107</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22107">issues.joomla.org/tracker/joomla-cms/22107</a>.</sub>

**Comment by infograf768** [comment]
@mbabker 
Can this be merged?

**Pull request merged**
