### PR TITLE
[5.0] Removing erroneous User::aid attribute

### PR DESCRIPTION
**Pull request by Hackwar**
### Summary of Changes
In Joomla 4.2.7, this attribute was added into the User class because a notice was thrown in PHP 8.2. This notice comes from a line of code which had been forgotten to remove in Joomla 1.6. https://github.com/joomla/joomla-cms/blob/3.10-dev/libraries/src/User/User.php#L255 This attribute was present in Joomla 1.5, but has been removed in Joomla 1.6, while that one line has remained throughout time. We are not filling that attribute with anything since then and instead of removing that line, that attribute was added back in instead.

For the mother of god and everything that is good and holy, can we PLEASE remove this right here and right now, before Joomla 4.3.0 is released without making a big fuss about this? I will literally go crazy if we have to pull this through to Joomla 6.0 now, just because the initial PR (#39620) was not checked properly. Yes, we have deprecation rules, but there are exemptions.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by laoneo** [comment]
I do agree that it should be a shame on us that we didn't remove this line which sets that property in all those years. But we have a BC policy and I'm in favor to follow it and remove the property not before 6.0.

**Comment by Fedik** [comment]
@Hackwar You missed one more https://github.com/joomla/joomla-cms/blob/c56fd165ca2537df8b4decfe9b3690bbf3ffbf46/libraries/src/User/User.php#L870

I am fine here, with removing.
But for compromise, we can rremove all instances of `$this->aid = 0`, and mark `aid` property as deprecated in 4.4, and remove in 5.0

**Comment by HLeithner** [comment]
Removing in 5.0 is ok for me, it wouldn't break any extension in 5.0 if it doesn't exists. I would go the @Fedik way.

**Comment by Hackwar** [comment]
I removed it from __wakeup.

It is an attribute which has no functionality and has been added in a patch release. Can we PLEASE stop this before people have 2 minor releases time to find stupid ways to use this?

**Comment by laoneo** [comment]
The property is already deprecated in 4.3 https://github.com/joomla/joomla-cms/pull/40109

**Comment by alikon** [comment]
> Removing in 5.0 is ok for me
of course but even on 4.3 is ok for me too 
it's from 1.5/6  so.....

**Comment by HLeithner** [comment]
thanks

**Pull request merged**
