### PR TITLE
[imp] Validate the default value against the field type validation rule

### PR DESCRIPTION
**Pull request by marrouchi**
Pull Request for Issue #13869.

### Summary of Changes
Added a JFormRule in com_fields to make sure default value is validated against the field type.

### Testing Instructions
1. Create a field (url, color, .. ) 
2. Set an invalid value  in default value field.
3. Submit and you should get a validation message.
4. Repeat with a valid default value and no validation message should appear.
### Expected result
Displays a validation message.
### Actual result
Does not validate the default value against the field type.
### Documentation Changes Required
No.

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on da3e46378a2bba60698deec0dd8f3d334bb808b8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13888">issues.joomla.org/tracker/joomla-cms/13888</a>.</sub>

**Comment by laoneo** [comment]
This works for the core form fields. But when a custom field like the gallery one is used, then the rule doesn't get found. But first let's get this one in and I will add then support for none core fields.

**Comment by laoneo** [comment]
I have tested this item :white_check_mark: successfully on da3e46378a2bba60698deec0dd8f3d334bb808b8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13888">issues.joomla.org/tracker/joomla-cms/13888</a>.</sub>

**Comment by marrouchi** [comment]
Thanks for the tests. RTC please !

**Comment by Bakual** [comment]
I couldn't test this yet but I think rhe approach doesn't work. For example the calendar allows a special case "NOW" for the defaulr value, which eesults in the current date/ime displayed by default. This PR will break that if I read thw code right.
There likely will be other such cases.

Imho, it's the responsibilty of each formfield to make sure the default value is allowed if needed. Custom Fields mostly directly extend from those library classes and don't implement own logic.

**Comment by Bakual** [comment]
Now had the chance to test this and looking at the code closer.
Actually calendar isn't affected because there is no JFormRuleCalendar. The whole code only works if the typename of the field matches the rulename, which for core is only the case for `color` and ùrl` as far as I see. So this doesn't make much sense to me.
For once the validation shouldn't be tied to the name of the field type and if we implement it in the component it should be more generic than only working for two fields.

I still think validation should be done in the formfield class itself and only if needed. And personally I think in most cases it's not needed at all. After all we currently don't sanitise the default values at all when set in the XML. It's the exact same code which "breaks" here when the default value is set wrong in the XML or in the custom field.

**Comment by zero-24** [comment]
I have just fixed two CS issues.

**Comment by franz-wohlkoenig** [comment]
@Bakual should this PR be tested again?

**Comment by marrouchi** [comment]
@franz-wohlkoenig i'm working on another PR that i'll submit soon.

**Comment by franz-wohlkoenig** [comment]
Thanks @marrouchi so this PR can be closed?

**Comment by marrouchi** [comment]
Okay

**Comment by franz-wohlkoenig** [comment]
Thanks @marrouchi

**Pull request closed without merging**
