### PR TITLE
[4.3] Update deleted files list in script.php for upcoming 4.3.0-alpha2

### PR DESCRIPTION
**Pull request by richard67**
Pull Request for Issue # .

### Summary of Changes

1. Update the section comments for deleted files and folders for 4.3 and to the current 4.3.0-alpha1.

2. Update deleted files to changes from following PRs:
- #38466 - file `/plugins/content/emailcloak/emailcloak.php`
- #38470 - file `/plugins/content/fields/fields.php`

3. Remove js files from PR #38823 from the deleted files list because we have to keep them for b/c of layout overrides.
For the same reason, the deleted js files from PR #39374 are not added to the list with change 2. above.
The broken build will be fixed with another PR, see discussion in my PR's #39408 and #39413 .

### Testing Instructions

Code review.

Or if you want to make a real test, update a 4.3.0-alpha1 or any older 4.x version to the last 4.3 nightly build to get the actual result, and update a 4.3.0-alpha1 or any older 4.x version to the update package built by Drone for this PR to get the expected result.

### Actual result BEFORE applying this Pull Request

Files and folders mentioned at item 2 of the description above are still present after updating from a 4.3.0-alpha1 or any older 4.x version.

### Expected result AFTER applying this Pull Request

All files and folders mentioned at item 2 of the description above have been deleted after updating from a 4.3.0-alpha1 or any older 4.x version.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by richard67** [comment]
We have discussed in the CMS Maintainers team. I will modify this PR here on Friday because I don't have the time today and tomorrow. As it looks now (still collecting opinions), the JS files will be removed from the list of files to be deleted on update.

**Comment by richard67** [comment]
I've updated this PR here in order not to delete the js files which were removed with PR's #38823 and #39374 . So this PR is ready now.

**Comment by obuisard** [comment]
> I've updated this PR here in order not to delete the js files which were removed with PR's #38823 and #39374 . So this PR is ready now.

Thank you Richard, very appreciated.

**Comment by obuisard** [comment]
Thank you, Richard @richard67, as always.

**Pull request merged**
