### PR TITLE
[4.0] Sample Data plugin images

### PR DESCRIPTION
**Pull request by brianteeman**
Updates the plugin to use the new image data used in lazy loading etc. This avoids confusion for users who see different source code for their created articles when compared to the same data plugins. Seen questions about this several times on the forum

To test. Just make sure the sample data still installs and works as expected

### CODE REVIEW

**Comment by richard67** [comment]
@brianteeman The PHP CS check complains about too long lines.

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on e135e68910e31b220f9a20aa71828145d98d78e7<br /><br />Testing instruction for new contributors:

If you have a Joomla installation and if there are installed the blog sample data: 
Go thourgh the site and see where are images.

Then make a fresh installation (you can enforce that by deleting the configuration.php and the database via phpmyadmin).
Apply the Patch.
Install Blog Sample Data. 
Now check the frontend if they are as in the old installation 



<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36237">issues.joomla.org/tracker/joomla-cms/36237</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on e135e68910e31b220f9a20aa71828145d98d78e7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36237">issues.joomla.org/tracker/joomla-cms/36237</a>.</sub>

**Comment by ChristineWk** [comment]
result - fresh installation

screen shot 2021-12-06 at 21 29 32<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36237">issues.joomla.org/tracker/joomla-cms/36237</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36237">issues.joomla.org/tracker/joomla-cms/36237</a>.</sub>

**Comment by khu5h1** [comment]
I have tested this item :white_check_mark: successfully on e135e68910e31b220f9a20aa71828145d98d78e7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36237">issues.joomla.org/tracker/joomla-cms/36237</a>.</sub>

**Comment by brianteeman** [comment]
@khu5h1 there is no way that you have tested this in the minute since your last test result. It is a physical impossibility

**Comment by wilsonge** [comment]
Luckily we have two other good tests as well so merging. Thanks!

**Pull request merged**
