### PR TITLE
[4.0] [com_config] Fix when saving configuration in frontend

### PR DESCRIPTION
**Pull request by SharkyKZ**
Partial Pull Request for Issue https://github.com/joomla/joomla-cms/issues/27283.

### Summary of Changes

Corrects parent classes in models.
Adds missing administrator form path.
Removes obsolete paths.

### Testing Instructions

Create menu items for `Configuration Manager » Site Configuration Options` and `Configuration Manager » Display Template Options` menu item types.
View them in frontend.
Save the forms.

### Expected result

Works.

### Actual result

>{"error":true,"code":0,"message":"Form::loadForm could not load file"}

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by infograf768** [comment]
Test:
Concerning site settings:
No more error but after Save we are redirected to the same page displaying the form, i.e. we have no Save and Close with a redirect to where we came from.

**Comment by SharkyKZ** [comment]
Same as in 3.x.

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on ded2751e16b1f5c5f9b3ac06afdb2a8e9bc01767<br /><br />

> Same as in 3.x.

yep. Would be good to improve this.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27284">issues.joomla.org/tracker/joomla-cms/27284</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on ded2751e16b1f5c5f9b3ac06afdb2a8e9bc01767<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27284">issues.joomla.org/tracker/joomla-cms/27284</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27284">issues.joomla.org/tracker/joomla-cms/27284</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
