### PR TITLE
[5.1] Field ModalSelect: make sure token in the URLs

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue # .

### Summary of Changes

Fix for the ModalSelect field, always add the token to the urls.

### Testing Instructions

Run `npm install`

Add ModalSelect field in to Custom HTML module XML:
```xml
<field
  type="ModalSelect"
  name="article"
  label="Article"

  select="true"
  titleSelect="Selecting the Article"
  urlSelect="index.php?option=com_content&amp;view=articles&amp;layout=modal&amp;tmpl=component"
  clear="true"
/>
```

Then open Custom HTML module editing on the site (not administrator). And try to select the article, using "select" button.

### Actual result BEFORE applying this Pull Request
An error, kind of "wrong token"

### Expected result AFTER applying this Pull Request
All works, you should be able to select the article

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed
- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 9b024034f7da31506a4376461a79337d781632c4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43745">issues.joomla.org/tracker/joomla-cms/43745</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 9b024034f7da31506a4376461a79337d781632c4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43745">issues.joomla.org/tracker/joomla-cms/43745</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43745">issues.joomla.org/tracker/joomla-cms/43745</a>.</sub>

**Comment by robbiejackson** [comment]
I have tested this item :white_check_mark: successfully on 1b734cdf2c85a56565bf579c342dd1efde63e09a<br /><br />Test form now works well on the site front-end.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43745">issues.joomla.org/tracker/joomla-cms/43745</a>.</sub>

**Comment by LadySolveig** [comment]
Thank you @Fedik and also for testing @Quy @viocassel @robbiejackson !

**Pull request merged**
