### PR TITLE
Don't need a closure, jQuery ready function is enough. Use strict.

### PR DESCRIPTION
**Pull request by okonomiyaki3000**
Pull Request for Issue # .
### Summary of Changes

Remove the enclosure, use the concise jQuery ready function syntax, use javascript strict mode.
### Testing Instructions

Go to the administrator (Isis) and open your browser's javascript console. You may see errors when performing any action that involves javascript (like using the menu) or just by loading a page.

This PR only exposes these errors. It does not fix them. The fix is in #12544, do not merge this PR. Merge that one. 

### Documentation Changes Required

Nope

### CODE REVIEW

**Comment by okonomiyaki3000** [comment]
See #12544 for the fixes.

**Comment by franz-wohlkoenig** [comment]
@okonomiyaki3000 Tested like written in instructions, see with or without Patch Errors or not. So don't know what exact to look for.

**Comment by okonomiyaki3000** [comment]
@franz-wohlkoenig It should not be difficult to find errors. Any page of the administrator should at least produce: `Uncaught SyntaxError: Octal literals are not allowed in strict mode.`

**Comment by franz-wohlkoenig** [comment]
I have tested this item :red_circle: unsuccessfully on 1914619e726d1a557ab8799964f9925c7a88d52c<br /><br />Tested in J3.7.0-alpha2-nightly on different Isis-Menues, got no `Uncaught SyntaxError: Octal literals are not allowed in strict mode`. With and without PR got Warnings like `getAttributeNode() shouldnt used. Use getAttribute()`.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12543">issues.joomla.org/tracker/joomla-cms/12543</a>.</sub>

**Comment by okonomiyaki3000** [comment]
Excellent. I think 'getAttributeNode()' has nothing to do with this file though. Where does your js console say it appears? 

The 'octal literals' bug is actually caused by a line like this:

```
var cls = this.className.replace(/^.(chzn-color[a-z0-9-_]*)$.*/, '\1');
```

You will notice that there are no octal literals here. The problem is the replacement string. It should be `'$1'`, not '`\1'`. This line still seems to be in 3.7 so I'm not sure why your browser is letting it go. May I ask which browsers you've tested this in? 

Anyway, keep in mind that this PR is not meant to fix anything and is not expected to be merged. It is here as a reference to expose problems which normally go unnoticed because strict mode is not used. The goal of this patch is to make things break. The fixes are in #12544. That is the PR that should actually be merged.

**Comment by franz-wohlkoenig** [comment]
@okonomiyaki3000 Used Firefox 50.1.0, thanks for explanation of this PR. Will test #12544

**Comment by fancyFranci** [comment]
I have tested this item :white_check_mark: successfully on 2392574d0ca01281bb4ecb2cd57412fa56b2b089<br /><br />Now I'm getting `Uncaught SyntaxError: Octal escape sequences are not allowed in strict mode.`<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12543">issues.joomla.org/tracker/joomla-cms/12543</a>.</sub>

**Comment by Tchangue** [comment]
@okonomiyaki3000 could you please look into: https://github.com/joomla/joomla-cms/pull/21233 Thanks

**Comment by okonomiyaki3000** [comment]
@Tchangue Yes, this PR has errors. That's actually the only point of it. It is not meant to be merged. It meant to expose the errors by invoking strict mode. The errors are actually fixed in #12544.

**Comment by okonomiyaki3000** [comment]
@FPerisa You got errors. Which means the patch works because it's supposed to expose errors. But I think you're supposed to mark it as failed because we actually do not want errors. Yes, it seems to make no sense. The problem is that the errors are there already, they're just not reported because we're not in strict mode. So in fact, this PR should be Failed and the current Joomla code should also be Failed. #12544 is correct.

**Comment by kneisel** [comment]
I have tested this item :white_check_mark: successfully on 2392574d0ca01281bb4ecb2cd57412fa56b2b089<br /><br />I think this issue can be closed together with #12544 because #12543 was only a patch to allow the test of #12544<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12543">issues.joomla.org/tracker/joomla-cms/12543</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Comment by okonomiyaki3000** [comment]
@franz-wohlkoenig Do not commit.

**Comment by okonomiyaki3000** [comment]
@kneisel you can't have tested this patch successfully. It intentionally has errors.

**Comment by ghost** [comment]
@okonomiyaki3000 you mean set RTC back on Pending?

**Comment by ghost** [comment]
sorry, this is closed.

**Comment by okonomiyaki3000** [comment]
This is fine, it was closed without merging. As it should be. We're all fine here now.

**Pull request closed without merging**
