### PR TITLE
[4.0] TinyMCE plugin layout

### PR DESCRIPTION
**Pull request by brianteeman**
There have been multiple issues raised about the UI of the tinymce plugin and the lack of clarity that the options are for different sets. It's also a very regular topic on the forum whereby users believe they have configured the plugin and it doesn't work. When the problem is that they are simply in the wrong set.

This is an attempt to improve this.

The basic concept of this change it to make it much clearer that there are multiple sets and you should be working in the correct set for your access group. 

Hopefully this will make it much much more obvious that you are completing a set of options for a usergroup and not for the entire plugin.

### Concept
image

### CODE REVIEW

**Comment by ghost** [comment]
Tabs on top are better. Changing the 4 coloured presets+Clear and green "Assign this Set to" to grey or make a preset-dropdown make all as first step in my eyes a little bit easier to understand:

image

**Comment by brianteeman** [comment]
I've had to out this on hold for a while as I can't work out how to get the top list of all buttons available in each tab

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 99e8537b0d50569ff9f7d9ea4a5fd2962c2c4028<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33177">issues.joomla.org/tracker/joomla-cms/33177</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 99e8537b0d50569ff9f7d9ea4a5fd2962c2c4028<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33177">issues.joomla.org/tracker/joomla-cms/33177</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33177">issues.joomla.org/tracker/joomla-cms/33177</a>.</sub>

**Comment by drmenzelit** [comment]
Thanks

**Comment by brianteeman** [comment]
Thanks -lets hope this reduced the support issues

**Comment by Fedik** [comment]
Sorry I did not seen it on review, 
This PR broke the params structure and so whole "access thing" is broken now.

The problem comes from `<fields name="basic">` which changes data structure of parameters.

**Comment by brianteeman** [comment]
@fedik can you do a quick fix please. I will not be at the computer for most of the day.

**Comment by Fedik** [comment]
yes, I will make PR

**Comment by brianteeman** [comment]
thanks - i see the cause now

**Comment by Fedik** [comment]
the PR #33464

**Pull request merged**
