### PR TITLE
[5.1] Replace deprecated Factory::getDbo() by $this->getDbo()

### PR DESCRIPTION
**Pull request by joomdonation**
Pull Request for Issue # .

### Summary of Changes
This PR makes small improvements to the code by replacing deprecated `Factory::getDbo()` with `$this->getDbo()`. Within the class, we can use `$this->getDbo()` to get database object, see https://github.com/joomla/joomla-cms/blob/5.1-dev/libraries/src/Updater/Updater.php#L196 for code using in same class.

### Testing Instructions
Code review should be enough.

### Actual result BEFORE applying this Pull Request
Works, but using deprecated code.

### Expected result AFTER applying this Pull Request
Works without using deprecated code.

### Link to documentations
Please select:
- [x] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on c2aac77a68d19738b6fc2f91c741208fc7e18b66<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42977">issues.joomla.org/tracker/joomla-cms/42977</a>.</sub>

**Comment by sandewt** [comment]
I have tested this item :white_check_mark: successfully on c2aac77a68d19738b6fc2f91c741208fc7e18b66<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42977">issues.joomla.org/tracker/joomla-cms/42977</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42977">issues.joomla.org/tracker/joomla-cms/42977</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
