### PR TITLE
[Isis] Template.less refactoring

### PR DESCRIPTION
**Pull request by ciar4n**
Pull Request for Issue # .

### Summary of Changes
This PR starts a process of refactoring the Isis template.less, proposing to split the template.less in separate less files. Currently the template.less looks like a long list of PRs with no real structure (with the exception of its initial creation). Breaking it in to its separate components (blocks) makes for more manageable code.

```
blocks
| _global.less
| _chzn-override.less
| _editors.less
| _forms.less
| _header.less
| _login.less
| _media.less
| _modals.less
| _navbar.less
| _quickicons.less
| _sidebar.less
| _status.less
| _tables.less
| _toolbar.less
| _treeselect.less
| _utility-classes.less
| _custom.less
pages
| _com_cpanel.less
| _com_postinstall.less
| _com_templates.less
template.less
```

### Testing Instructions
Apply patch a check admin for issues. Although I suspect not, it may cause some cascading issues and would require a thorough testing.

### CODE REVIEW

**Comment by laoneo** [comment]
Do we still want to touch that, when we hopefully after 3.7 focus on J4?

**Comment by mbabker** [comment]
There's still 2 and a half years support life for 3.x most likely, I think it's worth it.  Granted we hope there aren't many styling changes left at this point, but that's still a large enough chunk of time that something which makes maintaining the current resources a bit easier should be considered.

**Comment by ciar4n** [comment]
I think with better grouping, the resource will be easier to optimize and troubleshoot correctly. The current structure results in a bit of a hornets nest one pokes at their own peril. I'll finish what I started and it can be decided from there.

**Comment by ciar4n** [comment]
PR is now complete. 

#### Notes

- 'global' is first with remaining in alphabetical followed by 'custom' last.
- 'custom' contains all hacks and fixes
- Media queries have been (largely) split and are coupled with their corresponding elements. This I believe makes issues more apparent and easier to fix
- Ordering with in each block has been kept

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 6e1fd16088ae609b8f0df853681ebaecedae9bf9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14400">issues.joomla.org/tracker/joomla-cms/14400</a>.</sub>

**Comment by ciar4n** [comment]
Thank you @franz-wohlkoenig

**Comment by gwsdesk** [comment]
I have tested this item :white_check_mark: successfully on 6e1fd16088ae609b8f0df853681ebaecedae9bf9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14400">issues.joomla.org/tracker/joomla-cms/14400</a>.</sub>

**Comment by gwsdesk** [comment]
Isis still working as expected

I have tested this item ✅ successfully on [6e1fd16](https://github.com/joomla/joomla-cms/commit/6e1fd16088ae609b8f0df853681ebaecedae9bf9 "6e1fd16")<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14400">issues.joomla.org/tracker/joomla-cms/14400</a>.</sub>

**Comment by ciar4n** [comment]
Thank you @gwsdesk

**Comment by franz-wohlkoenig** [comment]
RTC as there are 2 successfully Tests?

**Comment by dgt41** [comment]
RTC

**Comment by infograf768** [comment]
Has this been tested with RTL?

**Comment by infograf768** [comment]
I am asking because I see no trace of
`@import "../../../../media/jui/less/bootstrap-rtl.less";`

**Comment by gwsdesk** [comment]
@infograf768 I did install http://joomlacode.org/gf/download/frsrelease/20444/163708/ar-AA_joomla_lang_full_3.6.5v2.zip, set it to default in administrator and it seems to work well with Arabic (seems to since I do not master Arabic ;-) But the template is running well for sure RTL

**Comment by ciar4n** [comment]
@infograf768 This wouldn't have any effect on RTL as the template-rtl.css would cascade over any changes in this PR (template.css).

**Comment by gwsdesk** [comment]
aa

**Comment by infograf768** [comment]
@ciar4n 
While you are there, can you look at this RTL issue:
screen shot 2017-03-08 at 15 59 28

We should have a float:none;
but the css
`.btn-group.btn-group-yesno > .btn, .btn-group > .btn + .dropdown-toggle {
	float: none;}`

does not work here and we get a float:right;

**Comment by infograf768** [comment]
Once corrected, we should have
screen shot 2017-03-08 at 16 13 11

**Comment by ciar4n** [comment]
Thank you @infograf768 

PR created.. https://github.com/joomla/joomla-cms/pull/14421

**Pull request merged**
