### PR TITLE
keep star on history

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #9287 .

### Summary of Changes
added field `ordering` to `ignoreChanges` on `#__content_types table`

### Testing Instructions
run the query via phpmyadmin
Create an article & save  (art1)
Do some changes in that article (art1)
Create another article (art2)

### Expected result
In the article Item Version History the last version is marked with a star

### Actual result
after creating art2 the star is missed on art1 article Item Version History

### credits
@wilsonge

### CODE REVIEW

**Review by wilsonge — APPROVED** [review]

**Comment by wilsonge** [comment]
Looks about right to me

**Comment by ghost** [comment]
I have tested this item :red_circle: unsuccessfully on 90a67eccf14d7d0b9e15b3495498b38e320ee8f9<br /><br />after creating art2 the star is missed on art1 article Item Version History<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24731">issues.joomla.org/tracker/joomla-cms/24731</a>.</sub>

**Comment by alikon** [comment]
did you fix the database ?

**Comment by ghost** [comment]
No, will retest (Fix Database after "apply Patch"?)

**Comment by alikon** [comment]
yes, sorry for uncomplete test info

**Comment by ghost** [comment]
Updated Instructions.

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 90a67eccf14d7d0b9e15b3495498b38e320ee8f9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24731">issues.joomla.org/tracker/joomla-cms/24731</a>.</sub>

**Comment by ChristineWk** [comment]
Before applying the Patch, I made following tests:
Created an article & saved (art1)
Some changes in that article (art1)
Created another article (art2) etc.

Actual result

after creating of art2 the star was not missed on art1 article Item Version History.
You can keep it as current version. Or to activate (select) required version for restoring (star).




<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24731">issues.joomla.org/tracker/joomla-cms/24731</a>.</sub>

**Comment by ghost** [comment]
@ChristineWk please mark your test as successfully > https://docs.joomla.org/Testing_Joomla!_patches#Recording_test_results

**Comment by ChristineWk** [comment]
@franz-wohlkoenig: I didn't use the Patch. My "Actual result" was without applying the Patch.

**Comment by chmst** [comment]
I have tested (patch applied via patchtester on a 3.9.5 installation).
Before patch, the issue is as described. 
After applying the patch and fixing the database - same issue as before, no star is displayed in versions of article1. 

So it was not successful for me.

**Comment by ghost** [comment]
@chmst please mark your test as unsuccessfully > https://docs.joomla.org/Testing_Joomla!_patches#Recording_test_results

**Comment by chmst** [comment]
I have tested this item :red_circle: unsuccessfully on c655a92f61eafe4f0473008159f9012d239028f0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24731">issues.joomla.org/tracker/joomla-cms/24731</a>.</sub>

**Comment by ReLater** [comment]
I have tested this item :red_circle: unsuccessfully on c655a92f61eafe4f0473008159f9012d239028f0<br /><br />I followed exactly the instructions here and there (https://github.com/joomla/joomla-cms/issues/9287) and also fixed the database.

Result: Always 2 version entries for "Article 1" but no star before and after patch.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24731">issues.joomla.org/tracker/joomla-cms/24731</a>.</sub>

**Comment by ChristineWk** [comment]
@chmst & @ReLater: Thanks for testing. Sorry, maybe I made some steps too much before patch.

**Comment by ChristineWk** [comment]
I have tested this item :red_circle: unsuccessfully on c655a92f61eafe4f0473008159f9012d239028f0<br /><br />Create an article & save (art1) > here was my failure (in previous test): I saved & closed & reopened
Do some changes in that article (art1) 
Create another article (art2)

Tested again now - Before Patch: Result: no star in versions of article 1.

After applying the patch and fixing the database - same as above: Test unsuccessfully.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24731">issues.joomla.org/tracker/joomla-cms/24731</a>.</sub>

Edit: Sorry, I don't know, why I have h2 above instead of p

**Comment by alikon** [comment]
that's weird if I run the same query in this patch via **phpmyadmin**  `administrator/components/com_admin/sql/updates/postgresql/3.9.7-2019-04-26.sql` i got the correct result

Screenshot from 2019-04-30 18-56-48
i.e ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time", "version", "hits", **"ordering"**]
viceversa

if I run via database fix  got wrong result  as you reported

i.e ignoreChanges":["modified_by", "modified", "checked_out", "checked_out_time", "version", "hits"]
without  **"ordering"**


need some more investigation... sorry

**Comment by ghost** [comment]
@alikon As i tested first Time got unsuccessfully Result, 2nd time got successfully Test so i thought i had Mistakes in 1st run.

**Comment by ReLater** [comment]
> that's weird if I run the same query in this patch via phpmyadmin administrator/components/com_admin/sql/updates/postgresql/3.9.7-2019-04-26.sql i got the correct result

Confirmed. The same with https://github.com/alikon/joomla-cms/blob/patch-92/administrator/components/com_admin/sql/updates/mysql/3.9.7-2019-04-26.sql . It works via phpMyAdmin.

**Comment by alikon** [comment]
Ok so that is the situation:
The Database Fix (com_installer) only work for DDL and not with DML (ie don't run UPDATE)
instead
The Joomla update (com_joomlaupdate) run both DDL and DML

so the easy way to test is to run the query via phpmyadmin

**Comment by ReLater** [comment]
I have tested this item :white_check_mark: successfully on c655a92f61eafe4f0473008159f9012d239028f0<br /><br />1. test via phpMyAdmin
2. test via installation of https://github.com/alikon/joomla-cms/archive/patch-92.zip<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24731">issues.joomla.org/tracker/joomla-cms/24731</a>.</sub>

**Comment by ReLater** [comment]
@alikon 
> The Database Fix (com_installer) only work for DDL and not with DML (ie don't run UPDATE)

Isn't that a new issue in Joomla 3? Because the database fix runs without any messages but didn't do its job and says "database Ok" afterwards.

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on c655a92f61eafe4f0473008159f9012d239028f0<br /><br />Test via phpMyAdmin<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24731">issues.joomla.org/tracker/joomla-cms/24731</a>.</sub>

**Comment by alikon** [comment]
@ReLater  some kind of messages is displayed after all

> 1 database changes did not alter table structure and were skipped.

so maybe something should be addressed in 4.x

**Comment by alikon** [comment]
thanks for testing folks

RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24731">issues.joomla.org/tracker/joomla-cms/24731</a>.</sub>

**Comment by ReLater** [comment]
> 1 database changes did not alter table structure and were skipped.

Ah, "structure" is the magic difference. Nice to know. I've overlooked that since ever. I've always messages like that when I fix a database and always thought "everything's OK now".
Thus when one updates a crashed website via FTP and uses the fix button which is (maybe) not sufficient  one should recommend a final `Joomla Update > Upload & Update.`

**Comment by SniperSister** [comment]
Merged, thanks!

**Pull request merged**
