### PR TITLE
Change type_alias to type_id in uc_ItemnameTagid

### PR DESCRIPTION
**Pull request by sovainfo**
See #4943 

Use type_id for PgSQL and MsSQL like with MySQL.

### CODE REVIEW

**Comment by alikon** [comment]
@test success on postgresql

**Comment by waader** [comment]
@test success on postgresql and doesn´t break anything on mssql that not already broken.

**Comment by zero-24** [comment]
RTC based on testing :smile:<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6748">issues.joomla.org/joomla-cms/6748</a>.</sub>

**Comment by mbabker** [comment]
Merged to `staging` via db71627

**Pull request closed without merging**
