### PR TITLE
[4.0] Parent Category

### PR DESCRIPTION
**Pull request by brianteeman**
Add some extra clarity to the label in the article options

### Before
image

### After
image

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on eb6001f10c84658c80a7ec997c81c3e0b6de901a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34199">issues.joomla.org/tracker/joomla-cms/34199</a>.</sub>

**Comment by ChristineWk** [comment]
Enabled Patch (Nightly building just now)
Parent category = OK.
Missing: Link Parent Category - so not sure:

screen shot 2021-05-25 at 14 05 17

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34199">issues.joomla.org/tracker/joomla-cms/34199</a>.</sub>

**Comment by ghost** [comment]
@ChristineWk You have to show parent category to see "link parent category".

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on eb6001f10c84658c80a7ec997c81c3e0b6de901a<br /><br />Ah OK & Done. Was a short circuit from me :-)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34199">issues.joomla.org/tracker/joomla-cms/34199</a>.</sub>

**Comment by Quy** [comment]
Thank you!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
