### PR TITLE
[4.0] Multilang associations: Display error when Content Language is trashed or deleted

### PR DESCRIPTION
**Pull request by infograf768**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/27236

### Summary of Changes
When a Content Language is trashed or deleted
1. Corrected Notice in com_associations Manager
2. Displaying a Warning in each Manager concerned
3. Do not display the concerned associated item in the associations column

### Testing Instructions
Install a multingual site with 3 or more languages using the multilingual sample data.
Trash or delete one of the Content Languages.
Display managers:
articles, categories, menus, contacts, newsfeeds (for contacts and newsfeeds make sure you have associated items including some tagged to the trashed Content Language)
Display Associations component manager after selecting a Type and a Language

-->Screenshots below are captured when the fa-IR content language is trashed.

### Before patch
In managers:
Associated Items tagged to the trashed/deleted Content Language do display.
In Associations component:
We get a Notice. `Notice: Undefined index: link in \layouts\joomla\content\associations.php on line 18`

### After patch
No more Notice.
Associated items which content language is trashed/deleted do not display in the associations column
A Warning is displayed informing the user about the issue.

Screen Shot 2019-12-23 at 09 56 00

Screen Shot 2019-12-23 at 10 09 32

@Quy @Fedik 

Note: PR for the other issue ( `LanguageHelper::getContentLanguages`) discussed in https://github.com/joomla/joomla-cms/issues/27236 is done separately.

### CODE REVIEW

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on e67ad3c9c57d5f656ee07025aaf3d2ef2ab0bcce<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27340">issues.joomla.org/tracker/joomla-cms/27340</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on e67ad3c9c57d5f656ee07025aaf3d2ef2ab0bcce<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27340">issues.joomla.org/tracker/joomla-cms/27340</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27340">issues.joomla.org/tracker/joomla-cms/27340</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
