### PR TITLE
[4.3] Hide promotion in TinyMCE

### PR DESCRIPTION
**Pull request by bembelimen**
### Summary of Changes
Removes the Ads link for TinyMCE.

### Testing Instructions
Apply PR and active TinyMCE as default editor

### Actual result BEFORE applying this Pull Request
grafik

### Expected result AFTER applying this Pull Request
grafik

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
What version of tinymce are you using? I have never seen that advert?

**Comment by brianteeman** [comment]
From what I can see in the docs this was added in Tinymce 6.2 while Joomla is using Tinymce 5.10

**Comment by laoneo** [comment]
So this should go then into the 5 branch.

**Comment by brianteeman** [comment]
> So this should go then into the 5 branch.

assuming I am correct and @bembelimen has somehow installed tiny6.2 on joomla 4.2

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on c81b53cebd728c60a4acb702d502ac7f566f9476<br /><br />Tested successfully in Joomla 4.3.0-beta2-dev of 16 February.

Couldn't see any promotion/upgrade link in the TinyMCE edit box, neither before nor after the patch, but the Patch Tester inserted the additional line in the right place, as intended.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39734">issues.joomla.org/tracker/joomla-cms/39734</a>.</sub>

**Comment by brianteeman** [comment]
@toivo That's not a succcessful test as you didn't observe the pull request hiding anything.

**Comment by toivo** [comment]
Ok, understood.  I tried to install embelimen:4.3/tinymce-promotion but it is far too complicated.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39734">issues.joomla.org/tracker/joomla-cms/39734</a>.</sub>

**Comment by bembelimen** [comment]
Update: https://github.com/joomla/joomla-cms/pull/39920

**Pull request closed without merging**
