### PR TITLE
[4.0] Mail templates - language

### PR DESCRIPTION
**Pull request by brianteeman**
Various changes to the language strings for this new component

Note the search string change is based on the code - I couldn't get it to actually work

### CODE REVIEW

**Comment by wilsonge** [comment]
Which bits couldn't you get to work (so i can try and test them). I had a functioning install when i merged it i believe

**Comment by brianteeman** [comment]
try to search for something in the fields that the code says it will search

**Comment by brianteeman** [comment]
conflicts fixed

**Comment by wilsonge** [comment]
Search successfully searched with either the mail body or the template id for me :/

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
