### PR TITLE
[4.0] Remove associations sub_template

### PR DESCRIPTION
**Pull request by brianteeman**
This PR removes the edit_associations.php file as it was only being used to directly call the layout.

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 7e435fcdd5913cfbf24f409b32d2933d3cbb8826<br /><br />Code review + test if things still work.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25708">issues.joomla.org/tracker/joomla-cms/25708</a>.</sub>

**Comment by Hackwar** [comment]
I have tested this item :white_check_mark: successfully on 7e435fcdd5913cfbf24f409b32d2933d3cbb8826<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25708">issues.joomla.org/tracker/joomla-cms/25708</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25708">issues.joomla.org/tracker/joomla-cms/25708</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
