### PR TITLE
[5.2] Fix display of empty state view in clear cache

### PR DESCRIPTION
**Pull request by Quy**
Pull Request for Issue #44247 .

### Summary of Changes
PR #38671 did not account for search filter to be null when not using search, thus, won't display the empty state view when the cache folder is empty.

### Testing Instructions
Go to System > Clear Cache.
See empty state view when the cache folder is empty.

### CODE REVIEW

**Comment by fontanil** [comment]
Hi,
Successfully tested on Joomla! 5.2.0
Thank you

**Comment by fgsw** [comment]
@fontanil Can you open [https://issues.joomla.org/tracker/joomla-cms/44349](https://issues.joomla.org/tracker/joomla-cms/44349) and 
- click button "Test this"
- mark "Tested successfully"

The test will count as successfull.

**Comment by fontanil** [comment]
I have tested this item :white_check_mark: successfully on 0cb0e400f6a4c6082330a09912b291f91682eb14<br /><br />Successfully tested on5.2.0
Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44349">issues.joomla.org/tracker/joomla-cms/44349</a>.</sub>

**Comment by uGE70** [comment]
I have tested this item :white_check_mark: successfully on 0cb0e400f6a4c6082330a09912b291f91682eb14<br /><br />Thanks a lot. My test site was using Gantry. It doesn't happen on Cassiopeia, because there's the _media_version folder.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44349">issues.joomla.org/tracker/joomla-cms/44349</a>.</sub>

**Pull request merged**
