### PR TITLE
[4.0 - Atum] Alternative template skin

### PR DESCRIPTION
**Pull request by ciar4n**
Pull Request for Issue # .

### Summary of Changes
A repaint of the Atum template using a more familiar blue tint along with some general styling changes (gutter widths, quickicons.... )

### Testing Instructions
4.0-dev branch

### Before PR
skin1

### After PR
skin2a

skin2c

### CODE REVIEW

**Review by C-Lodder — APPROVED** [review]

**Comment by C-Lodder** [comment]
I have tested this item :white_check_mark: successfully on 224a4b16e4b378c6d8e08df49146cca51c40f38a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13900">issues.joomla.org/tracker/joomla-cms/13900</a>.</sub>

**Comment by dgt41** [comment]
I have tested this item :white_check_mark: successfully on 224a4b16e4b378c6d8e08df49146cca51c40f38a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13900">issues.joomla.org/tracker/joomla-cms/13900</a>.</sub>

**Comment by dgt41** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13900">issues.joomla.org/tracker/joomla-cms/13900</a>.</sub>

**Comment by wilsonge** [comment]
Nice stuff!

**Pull request merged**
