### PR TITLE
[4.0] copy paste fix

### PR DESCRIPTION
**Pull request by brianteeman**
Just a codestyle thing really - removes space between open brackets

Looks like a simple copy paste

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 65f777d45514c2621bbca9e729e7ab219f612b10<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34342">issues.joomla.org/tracker/joomla-cms/34342</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 65f777d45514c2621bbca9e729e7ab219f612b10<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34342">issues.joomla.org/tracker/joomla-cms/34342</a>.</sub>

only now seen that fixed, since I was in the files in that time :-)

**Pull request merged**
