### PR TITLE
[4.0] Category list

### PR DESCRIPTION
**Pull request by brianteeman**
Remove extra div that is not needed

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on f26fa0c448a79ce5b10ea8b9c9af787ace75ae27<br /><br />To see only the changes, append `?w=1`:

https://github.com/joomla/joomla-cms/pull/36536/files?w=1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36536">issues.joomla.org/tracker/joomla-cms/36536</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on f26fa0c448a79ce5b10ea8b9c9af787ace75ae27<br /><br />Review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36536">issues.joomla.org/tracker/joomla-cms/36536</a>.</sub>

**Comment by chmst** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36536">issues.joomla.org/tracker/joomla-cms/36536</a>.</sub>

**Comment by Quy** [comment]
Thanks

**Pull request merged**
