### PR TITLE
Update en-GB.ini

### PR DESCRIPTION
**Pull request by diddipoeler**
JGLOBAL_BOTTOM

Pull Request for Issue # .

### CODE REVIEW

**Comment by chmst** [comment]
Please give some additinal information and testing instructions. Were is this Language key in use? 
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30199">issues.joomla.org/tracker/joomla-cms/30199</a>.</sub>

**Comment by diddipoeler** [comment]
Es sind diese Variablen vorhanden:
JGLOBAL_TOP="Top"
JGLOBAL_LEFT="Left"
JGLOBAL_RIGHT="Right"

Diese fehlt: 
JGLOBAL_BOTTOM

**Comment by chmst** [comment]
Please write English :) Where did you get the non-translated language key?

**Comment by Bakual** [comment]
I'd rather deprecate "JGLOBAL_TOP" (and remove in 4.0) as that one doesn't seem to be used in the project.
I'm not sure if it makes much sense to add another unused language string.

**Comment by Bakual** [comment]
Also, the strings should be alphaordered. So it should be between those two:
````
JGLOBAL_BLOG_LAYOUT_OPTIONS="Blog Layout"
JGLOBAL_CATEGORIES_OPTIONS="Categories"
````

**Comment by ghost** [comment]
Testing Instructions?

**Comment by brianteeman** [comment]
We shouldn't be adding strings that are not used

**Comment by chmst** [comment]
@diddipoeler sorry, but there is no reason for introducing an unused language key. Please give us information  which problem is be solved with your PR.

**Comment by Quy** [comment]
Closing for reasons stated above,

**Pull request closed without merging**
