### PR TITLE
[4] Code Style

### PR DESCRIPTION
**Pull request by PhilETaylor**
Fixing my own code style mistakes introduced in https://github.com/joomla/joomla-cms/pull/30056

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on de761c470b55666425183ceccdb92d4f43ce0e5e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35280">issues.joomla.org/tracker/joomla-cms/35280</a>.</sub>

**Comment by rjharishabh** [comment]
I have tested this item :white_check_mark: successfully on de761c470b55666425183ceccdb92d4f43ce0e5e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35280">issues.joomla.org/tracker/joomla-cms/35280</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35280">issues.joomla.org/tracker/joomla-cms/35280</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
