### PR TITLE
Fix PHP notice error issue

### PR DESCRIPTION
**Pull request by ShuraChow**
Pull Request for Issue # .

### CODE REVIEW

**Comment by wilsonge** [comment]
What PHP Notice is this fixing and how do you reproduce it. It's not obvious to me why reversing these arguments fixes anything

**Comment by ShuraChow** [comment]
sorry, please see latest commit.
$bars[0] might be empty

**Comment by photodude** [comment]
@ShuraChow Please fill out the fields in your PR
- Pull Request for Issue ______
- Summary of Changes
- Testing Instructions
- Documentation Changes Required

Filling out those fields will speed review and testing of your PR

**Comment by brianteeman** [comment]
@shurachow This will be closed in a few days if the required information is not provided<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12025">issues.joomla.org/joomla-cms/12025</a>.</sub>

**Comment by brianteeman** [comment]
As stated above this is now closed. It can always be reopened if the requested information is provided<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12025">issues.joomla.org/tracker/joomla-cms/12025</a>.</sub>

**Pull request closed without merging**
