### PR TITLE
Fix com_fields submenu regression

### PR DESCRIPTION
**Pull request by HLeithner**
Pull Request for Issue found by Philip Walton (cms release team) thx.

Fixes regression introduced in #25475

Testing
===

Check if com fields submenu exists and works, also check if com fields works in modal view.

### CODE REVIEW

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 25c4070a5533c962f24ef03a797d7af06dd3fad2<br /><br />ooops....<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25822">issues.joomla.org/tracker/joomla-cms/25822</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 25c4070a5533c962f24ef03a797d7af06dd3fad2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25822">issues.joomla.org/tracker/joomla-cms/25822</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25822">issues.joomla.org/tracker/joomla-cms/25822</a>.</sub>

**Comment by infograf768** [comment]
Tks Philip Walton!

**Pull request merged**
