### PR TITLE
[4.0] Remove popovers from com_installer&view=database

### PR DESCRIPTION
**Pull request by brianteeman**
This simple PR removes the two useless popovers from the Database and Manifest Version column headers. They are not accessible for screen readers and as the header is not focusable by the keyboard it can't be seen by keyboard users either.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 017e07b73dd43bb5e65b45fe95aa550ce897167e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24610">issues.joomla.org/tracker/joomla-cms/24610</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 017e07b73dd43bb5e65b45fe95aa550ce897167e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24610">issues.joomla.org/tracker/joomla-cms/24610</a>.</sub>

**Comment by ghost** [comment]
Status "Ready To Commit".

**Comment by HLeithner** [comment]
does we only remove documentation? or is this information anywhere else?

**Comment by brianteeman** [comment]
We remove any string that is useless

**Comment by HLeithner** [comment]
Ok

**Comment by wilsonge** [comment]
Thanks

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
