### PR TITLE
Make a proper string to display the PHP version check

### PR DESCRIPTION
**Pull request by mbabker**
There's a string in the InstallationModelSetup class to display what translates into "PHP Version >= 5.3.10" in the installer that is manually appending the ">= 5.3.10" part to the translated string.  This PR makes a new language string that puts the whole thing together using sprintf to inject the PHP version.
### Test Instructions

Make sure the string still displays in the installer and there aren't any parse errors.

### CODE REVIEW

**Comment by infograf768** [comment]
Good for RTL and languages generally speaking as they can place the variable the way they like.
For 3.4.2 I guess.

**Comment by brianteeman** [comment]
Is there a benefit to doing it this way over simply moving the >= into the current string

INSTL_PHP_VERSION="PHP Version >="
$option->label  = JText::_('INSTL_PHP_VERSION') . '5.3.10';<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6528">issues.joomla.org/joomla-cms/6528</a>.</sub>

**Comment by sovainfo** [comment]
Suggest to extend https://github.com/joomla/joomla-cms/pull/6529 to installation and use constant instead of '5.3.10'

**Comment by mbabker** [comment]
@brianteeman That still forces the version number to be at the end of the output.  By making it a sprintf, a language string could show the translated version of "PHP 5.3.10 or later" instead of being forced to be worded so the version is at the end of the text.

@sovainfo The constant is already in use in this same line of code in that PR, whichever of these two are accepted first (assuming either are) will cause the other to need an update.

**Comment by sovainfo** [comment]
@mbabker Can't believe I missed that!

**Comment by infograf768** [comment]
As this is a change in installation ini and we have issues with pagination which may require a fast 3.4.2 release, I guess we should wait to merge this as it is unlikely all TTs will be able to update their inis in a short notice.
A temporary solution could be to check if the new constant is present in the language and if not use the former one for now.
Otherwise, evidently, en-GB will take over.

**Comment by mbabker** [comment]
Unless 3.4.2 is coming like tomorrow, any reason this needs to keep waiting for 3.4.3?

**Comment by zero-24** [comment]
@test successful. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6528">issues.joomla.org/joomla-cms/6528</a>.</sub>

**Comment by waader** [comment]
@test works!

**Pull request merged**
