### PR TITLE
[4.0-dev] Back to the normal readme.md

### PR DESCRIPTION
**Pull request by zero-24**
### Steps to reproduce the issue

see: https://raw.githubusercontent.com/joomla/joomla-cms/4.0-dev/README.md

### Expected result

something similiar to 
image

### Actual result

image

cc @wilsonge

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :red_circle: unsuccessfully on 2b300085133b12d069f3848304e9f9a2c28c003e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16541">issues.joomla.org/tracker/joomla-cms/16541</a>.</sub>

**Comment by brianteeman** [comment]
The correct readme is this one
looks like @wilsonge merge destroyed the history as well

`Joomla! CMS™ [Analytics](https://github.com/igrigorik/ga-beacon)
====================

Build Status
---------------------
Travis-CI: [Build Status](https://travis-ci.org/joomla/joomla-cms)

Drone -CI: [Build Status](http://213.160.72.75/joomla/joomla-cms)

AppVeyor: [Build status](https://ci.appveyor.com/project/joomla/joomla-cms)

Jenkins: [Build Status](http://build.joomla.org/job/cms/)

What is this?
---------------------
* This is a Joomla! 4.x installation/upgrade package.
* Joomla's [Official website](https://www.joomla.org).
* Joomla! 4.0 [version history](https://docs.joomla.org/Joomla_4.0_version_history).
* Detailed changes are in the [changelog](https://github.com/joomla/joomla-cms/commits/master).

What is Joomla?
---------------------
* [Joomla!](https://www.joomla.org/about-joomla.html) is a **Content Management System** (CMS) which enables you to build websites and powerful online applications.
* It is a simple and powerful web server application which requires a server with PHP and either MySQL or PostgreSQL to run. You can find [full technical requirements here](https://downloads.joomla.org/technical-requirements).
* Joomla! is **free and Open Source software** distributed under the GNU General Public License version 2 or later.

Is Joomla! for you?
---------------------
* Joomla! is [the right solution for most content web projects](https://docs.joomla.org/Special:MyLanguage/Portal:Learn_More).
* View Joomla's [core features here](https://www.joomla.org/core-features.html).
* Try it out for yourself in our [online demo](https://demo.joomla.org).

How to find a Joomla! translation?
---------------------
* Repository of [accredited language packs](https://community.joomla.org/translations.html).
* You can also [add languages](https://docs.joomla.org/Special:MyLanguage/J4.x:Setup_a_Multilingual_Site/Installing_New_Language) directly to your website via your Joomla! administration panel.
* Learn how to [setup a Multilingual Joomla! Site](https://docs.joomla.org/Special:MyLanguage/J4.x:Setup_a_Multilingual_Site)

Learn Joomla!
---------------------
* Read ['Getting Started with Joomla!'](https://docs.joomla.org/Special:MyLanguage/J4.x:Getting_Started_with_Joomla!) to learn the basics.
* Before installing, read the ['Beginners' Guide'](https://docs.joomla.org/Special:MyLanguage/Portal:Beginners).

What are the benefits of Joomla?
---------------------
* The functionality of a Joomla! website can be extended by installing extensions that you can create (or download) to suit your needs.
* There are many ready-made extensions that you can download and install.
* Check out the [Joomla! Extensions Directory (JED)](https://extensions.joomla.org).

Is it easy to change the layout display?
---------------------
* The layout is controlled by templates that you can edit.
* There are a lot of ready-made professional templates that you can download.
* Template management information is [available here](https://docs.joomla.org/Special:MyLanguage/Portal:Template_Management).

Ready to install Joomla?
---------------------
* Check the [minimum requirements](https://downloads.joomla.org/technical-requirements). 
* How do you [install Joomla](https://docs.joomla.org/Special:MyLanguage/J4.x:Installing_Joomla)?
* You could start your Joomla! experience by [building your site on a local test server](https://docs.joomla.org/Special:MyLanguage/Installing_Joomla_locally).
When ready, it can be moved to an online hosting account of your choice.

Updates are free!
---------------------
* Always use the [latest version](https://downloads.joomla.org/latest).

Where can you get support and help?
---------------------
* [The Joomla! Documentation](https://docs.joomla.org/Special:MyLanguage/Main_Page);
* [Frequently Asked Questions](https://docs.joomla.org/Special:MyLanguage/Category:FAQ) (FAQ);
* Find the [information you need](https://docs.joomla.org/Special:MyLanguage/Start_here);
* Find [help and other users](https://www.joomla.org/about-joomla/create-and-share.html);
* Post questions at [our forums](https://forum.joomla.org);
* [Joomla Resources Directory](https://resources.joomla.org/) (JRD).

Do you already have a Joomla! site that isn't built with Joomla! 4.x?
---------------------
* What's [new in Joomla! 4.x](https://www.joomla.org/4)?
* What are the [main differences between 3.x and 4.x](https://docs.joomla.org/Special:MyLanguage/What_are_the_major_differences_between_Joomla!_3.x_and_4.x)?
* How to [migrate from 3.x to 4.x](https://docs.joomla.org/Special:MyLanguage/Joomla_3.x_to_4.x_Step_by_Step_Migration).
* How to [migrate from 2.5.x to 3.x](https://docs.joomla.org/Special:MyLanguage/Joomla_2.5_to_3.x_Step_by_Step_Migration).
* How to [migrate from 1.5.x to 3.x](https://docs.joomla.org/Special:MyLanguage/Joomla_1.5_to_3.x_Step_by_Step_Migration).

Do you want to improve Joomla?
--------------------
* Where to [request a feature](https://issues.joomla.org/)?
* How do you [report a bug](https://docs.joomla.org/Special:MyLanguage/Filing_bugs_and_issues) on the [Issue Tracker](https://issues.joomla.org/)?
* Get Involved: Joomla! is community developed software. [Join the community](https://volunteers.joomla.org/).
* Documentation for [Developers](https://docs.joomla.org/Special:MyLanguage/Portal:Developers).
* Documentation for [Web designers](https://docs.joomla.org/Special:MyLanguage/Web_designers).

Copyright
---------------------
* Copyright (C) 2005 - 2017 Open Source Matters. All rights reserved.
* [Special Thanks](https://docs.joomla.org/Special:MyLanguage/Joomla!_Credits_and_Thanks)
* Distributed under the GNU General Public License version 2 or later
* See [License details](https://docs.joomla.org/Special:MyLanguage/Joomla_Licenses)
`

**Comment by zero-24** [comment]
I'm not question the content anymore. Now it is just a revert to: https://raw.githubusercontent.com/joomla/joomla-cms/c556d86c60f1bb14787672d0734640f87b302f53/README.md ...

**Comment by wilsonge** [comment]
Ahh crud. Missed this. Thanks for spotting!

**Pull request merged**
