### PR TITLE
[4.0] Remove FOF From Joomla Core

### PR DESCRIPTION
**Pull request by wilsonge**
Moves the encryption libraries to the Joomla Namespace and removes FOF. Note as I've changed the functions to use native PHP functions rather than also porting `FOFUtilsPhpfunc` I've deliberately not classmapped the FOF classnames as there are b/c breaks

### Testing
Check 2FA works before and after PR

### CODE REVIEW

**Comment by eXsiLe95** [comment]
I have tested this item :white_check_mark: successfully on cf63da3ec43c8e6924fd867cc6b81ac58bff4780<br /><br />
# Testing

## System Information

* Running on xampp v3.2.2
* Windows 10 (1703: 15063:540)
* Chrome 60.0.3112.101 (64bit)
* PHP 7.1.7
* Joomla! 4.0-dev (joomla@4.0.0)
* <del>Patch Tester 3.0.0 Beta 3</del>

## Steps

1. Fresh installation of Joomla! 4.0-dev
1. Enable TFA in administrator
    1. Go to Extensions > Plugins
        1. Enable Two Factor Authentication - Google Authenticator
        1. Enable Two Factor Authentication - YubiKey
1. Create users
    1. Go to Users > Manage
    1. Create a new user
    1. Edit the new user and enable Two Factor Authentication
        1. Go to Two Factor Authentication Tab
        1. Select Google Authenticator as Authentication Method
        1. Follow the on screen instructions to set up Google Authenticator
    1. Create a new user
    1. Edit the new user and enable Two Factor Authentication
        1. Got to Two Factor Authentication Tab
        1. Select YubiKey as Authentication Method
        1. Follow the on screen instructions to set up YubiKey Authenticator
1. Go to frontend/site `<yourinstallpath>/index.php`
    1. Test without TFA
        1. Try to log in with superuser with wrong password
        1. Try to log in with superuser with additional secret key (is always wrong)
        1. Login with superuser without TFA
        1. Log out
        1. Go to `<youtinstallpath>/index.php/login`
        1. Try to log in with superuser with wrong password
        1. Try to log in with superuser with additional secret key (is always wrong)
        1. Login with superuser without TFA
        1. Log out
    1. Test with Google TFA
        1. Try to log in with Google TFA user with wrong password but no secret key
        1. Try to log in with Google TFA user with wrong password and wrong secret key
        1. Try to log in with Google TFA user with wrong password but correct secret key
        1. Try to log in with Google TFA user with correct password but no secret key
        1. Try to log in with Google TFA user with correct password but incorrect secret key
        1. Login with the user with Google TFA with the login box
        1. Log out
        1. Go to `<youtinstallpath>/index.php/login`
        1. Try to log in with Google TFA user with wrong password but no secret key
        1. Try to log in with Google TFA user with wrong password and wrong secret key
        1. Try to log in with Google TFA user with wrong password but correct secret key
        1. Try to log in with Google TFA user with correct password but no secret key
        1. Try to log in with Google TFA user with correct password but incorrect secret key
        1. Login with the user with Google TFA with the login box
        1. Log out
    1. Test with YubiKey
        1. Try to log in with YubiKey TFA user with wrong password but no secret key
        1. Try to log in with YubiKey TFA user with wrong password and wrong secret key
        1. Try to log in with YubiKey TFA user with wrong password but correct secret key
        1. Try to log in with YubiKey TFA user with correct password but no secret key
        1. Try to log in with YubiKey TFA user with correct password but incorrect secret key
        1. Login with the user with YubiKey TFA with the login box
        1. Log out
        1. Go to `<youtinstallpath>/index.php/login`
        1. Try to log in with YubiKey TFA user with wrong password but no secret key
        1. Try to log in with YubiKey TFA user with wrong password and wrong secret key
        1. Try to log in with YubiKey TFA user with wrong password but correct secret key
        1. Try to log in with YubiKey TFA user with correct password but no secret key
        1. Try to log in with YubiKey TFA user with correct password but incorrect secret key
        1. Login with the user with YubiKey TFA with the login box
        1. Log out
1. Go to backend/administrator `<yourinstallpath/administrator`
    1. Test without TFA
        1. Try to log in with superuser with wrong password
        1. Try to log in with superuser with wrong password and additional secret key (is always wrong)
        1. Try to log in with superuser with correct password and additional secret key (is always wrong)
        1. Login with superuser without TFA
        1. Log out
    1. Test with Google TFA
        1. Try to log in with Google TFA user with wrong password but no secret key
        1. Try to log in with Google TFA user with wrong password and wrong secret key
        1. Try to log in with Google TFA user with wrong password but correct secret key
        1. Try to log in with Google TFA user with correct password but no secret key
        1. Try to log in with Google TFA user with correct password but incorrect secret key
        1. Login with the user with Google TFA with the login box
        1. Log out
    1. Test with YubiKey TFA
        1. Try to log in with YubiKey TFA user with wrong password but no secret key
        1. Try to log in with YubiKey TFA user with wrong password and wrong secret key
        1. Try to log in with YubiKey TFA user with wrong password but correct secret key
        1. Try to log in with YubiKey TFA user with correct password but no secret key
        1. Try to log in with YubiKey TFA user with correct password but incorrect secret key
        1. Login with the user with YubiKey TFA with the login box
        1. Log out

## Expected result

Login attempts with wrong information will fail and throw an error accordingly. Login attempts with correct login data will be successfull. Installation of R/C should not affect this behavior.

## Result before PR

1. Frontend test (according to step 4)
    1. Without TFA
        1. Test: Works as expected.
        1. Test: Works as expected. (Secret Key field is ignored)
        1. Test: Works as expected.
        1. Test: Works as expected.
        1. Test: Works as expected.
        1. Test: Works as expected.
        1. Test: Works as expected. (Secret Key field is ignored)
        1. Test: Works as expected.
        1. Test: Works as expected.
    1. With Google TFA
        1. Test: Works as expected.
        1. Test: Works as expected.
        1. Test: Works as expected.
        1. Test: Works as expected.
        1. Test: Works as expected.
        1. Test: Works as expected.
        1. Test: Works as expected.
        1. Test: Works as expected.
        1. Test: Works as expected.
        1. Test: Works as expected.
        1. Test: Works as expected.
        1. Test: Works as expected.
        1. Test: Works as expected.
        1. Test: Works as expected.
        1. Test: Works as expected.
    1. With YubiKey TFA
        1. Test: Works as expected.
        1. Test: Works as expected.
        1. Test: Works as expected.
        1. Test: Works as expected.
        1. Test: Works as expected.
        1. Test: Works as expected.
        1. Test: Works as expected.
        1. Test: Works as expected.
        1. Test: Works as expected.
        1. Test: Works as expected.
        1. Test: Works as expected.
        1. Test: Works as expected.
        1. Test: Works as expected.
        1. Test: Works as expected.
        1. Test: Works as expected.
1. Backend test (according to step 5)
    1. Without TFA
        1. Test: Bug! Secret Key field is required, even though it's not needed (removing `required aria-required="true"` fixed the issue)
        1. Test: Works as expected.
        1. Test: Works as expected. Secret Key field is ignored, login successfull. A warning was displayed.
        1. Test: Bug! Secret Key field is required, even though it's not needed (removing `required aria-required="true"` fixed the issue)
        1. Test: Works as expected.
    1. With Google TFA
        1. Test: Works as expected. (Secret Key field is required, but not only for this user!)
        1. Test: Works as expected.
        1. Test: Works as expected.
        1. Test: Works as expected. (Secret Key field is required, but not only for this user!)
        1. Test: Works as expected.
        1. Test: Works as expected.
        1. Test: Works as expected.
    1. With YubiKey TFA
        1. Test: Works as expected. (Secret Key field is required, but not only for this user!)
        1. Test: Works as expected.
        1. Test: Works as expected.
        1. Test: Works as expected. (Secret Key field is required, but not only for this user!)
        1. Test: Works as expected.
        1. Test: Works as expected.
        1. Test: Works as expected.

## Result with PR

1. Frontend test (according to step 4)
    1. Without TFA
        1. Test: Works as expected.
        1. Test: Works as expected. (Secret Key field is ignored)
        1. Test: Works as expected.
        1. Test: Works as expected.
        1. Test: Works as expected.
        1. Test: Works as expected.
        1. Test: Works as expected. (Secret Key field is ignored)
        1. Test: Works as expected.
        1. Test: Works as expected.
    1. With Google TFA
        1. Test: Works as expected.
        1. Test: Works as expected.
        1. Test: Works as expected.
        1. Test: <del>Bug! `The requested page can't be found.` but login was unsuccessfull. Error: `Class 'Joomla\CMS\Encrypt\Aes' not found`</del> Works as expected
        1. Test: <del>Bug! `The requested page can't be found.` but login was unsuccessfull. Error: `Class 'Joomla\CMS\Encrypt\Aes' not found`</del> Works as expected
        1. Test: <del>Bug! `The requested page can't be found.` and login was unsuccessfull. Error: `Class 'Joomla\CMS\Encrypt\Aes' not found`</del> Works as expected
        1. Test: Works as expected.
        1. Test: Works as expected.
        1. Test: Works as expected.
        1. Test: Works as expected.
        1. Test: Works as expected.
        1. Test: <del>Bug! `The requested page can't be found.` but login was unsuccessfull. Error: `Class 'Joomla\CMS\Encrypt\Aes' not found`</del> Works as expected
        1. Test: <del>Bug! `The requested page can't be found.` but login was unsuccessfull. Error: `Class 'Joomla\CMS\Encrypt\Aes' not found`</del> Works as expected
        1. Test: <del>Bug! `The requested page can't be found.` and login was unsuccessfull. Error: `Class 'Joomla\CMS\Encrypt\Aes' not found`</del> Works as expected
        1. Test: Works as expected.
    1. With YubiKey TFA
        1. Test: Works as expected.
        1. Test: Works as expected.
        1. Test: Works as expected.
        1. Test: <del>Bug! `The requested page can't be found.` but login was unsuccessfull. Error: `Class 'Joomla\CMS\Encrypt\Aes' not found`</del> Works as expected
        1. Test: <del>Bug! `The requested page can't be found.` but login was unsuccessfull. Error: `Class 'Joomla\CMS\Encrypt\Aes' not found`</del> Works as expected
        1. Test: <del>Bug! `The requested page can't be found.` and login was unsuccessfull. Error: `Class 'Joomla\CMS\Encrypt\Aes' not found`</del> Works as expected
        1. Test: Works as expected.
        1. Test: Works as expected.
        1. Test: Works as expected.
        1. Test: Works as expected.
        1. Test: Works as expected.
        1. Test: <del>Bug! `The requested page can't be found.` but login was unsuccessfull. Error: `Class 'Joomla\CMS\Encrypt\Aes' not found`</del> Works as expected
        1. Test: <del>Bug! `The requested page can't be found.` but login was unsuccessfull. Error: `Class 'Joomla\CMS\Encrypt\Aes' not found`</del> Works as expected
        1. Test: <del>Bug! `The requested page can't be found.` and login was unsuccessfull. Error: `Class 'Joomla\CMS\Encrypt\Aes' not found`</del> Works as expected
        1. Test: Works as expected.
1. Backend test (according to step 5)
    1. Without TFA
        1. Test: Bug! Secret Key field is required, even though it's not needed (removing `required aria-required="true"` fixed the issue)
        1. Test: Works as expected.
        1. Test: Works as expected. Secret Key field is ignored, login successfull. A warning was displayed.
        1. Test: Bug! Secret Key field is required, even though it's not needed (removing `required aria-required="true"` fixed the issue)
        1. Test: Works as expected.
    1. With Google TFA
        1. Test: Works as expected. (Secret Key field is required, but not only for this user!)
        1. Test: Works as expected.
        1. Test: Works as expected.
        1. Test: Works as expected. (Secret Key field is required, but not only for this user!)
        1. Test: <del>Bug! `The requested page can't be found.` and login was unsuccessfull. Error: `Class 'Joomla\CMS\Encrypt\Aes' not found`</del> Works as expected
        1. Test: <del>Bug! `The requested page can't be found.` and login was unsuccessfull. Error: `Class 'Joomla\CMS\Encrypt\Aes' not found`</del> Works as expected
        1. Test: Works as expected.
    1. With YubiKey TFA
        1. Test: Works as expected. (Secret Key field is required, but not only for this user!)
        1. Test: Works as expected.
        1. Test: Works as expected.
        1. Test: Works as expected. (Secret Key field is required, but not only for this user!)
        1. Test: <del>Bug! `The requested page can't be found.` and login was unsuccessfull. Error: `Class 'Joomla\CMS\Encrypt\Aes' not found`</del> Works as expected
        1. Test: <del>Bug! `The requested page can't be found.` and login was unsuccessfull. Error: `Class 'Joomla\CMS\Encrypt\Aes' not found`</del> Works as expected
        1. Test: Works as expected.

## Testing results (in a nutshell)

* <del>The directory `Joomla\CMS\Encrypt\Aes`, located in `<yourinstallpath>\libraries\src\` does not exist. It is only available in the old folder of FOF. </del>
 Using the PatchInstaller 3.0.0, the files were not changed correctly. I now used an installation in which the PR was applied using the DIFF-URL and git apply
* There is a bug (pre and post PR) where the Secret Key field is always required, even though the user does not have TFA enabled. There needs to be a checke whether or not TFA is activated (according to username)

Tested @iCampus<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17687">issues.joomla.org/tracker/joomla-cms/17687</a>.</sub>

**Comment by brianteeman** [comment]
how can that be marked a successful test when it identifies numerous bugs?

**Comment by eXsiLe95** [comment]
@brianteeman The exclution of FOF works perfectly fine - it's another bug that encountered before. This should be another issue, I guess, since it has nothing to do with the topic or goal of this issue directly. Also, the testing procedure of this issue (exclution of FOF) is very huge, testing for this little bug is much easier in another issue with fewer steps. 

@wilsonge It could also be fixed here! But then I have to check the whole procedure again in the name of issue tracking ;)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17687">issues.joomla.org/tracker/joomla-cms/17687</a>.</sub>

**Comment by wilsonge** [comment]
I see you've updated your references. Does this mean it is or isn't working in entirety now?

**Comment by roland-d** [comment]
@wilsonge We just tested this on a clean 4.0-dev checkout. If you have 2FA enabled and want to login with a user that does not have 2FA enabled you cannot login on backend. You get this:

image

So this is an issue not related to your PR but a pre-existing issue.

Your PR works as expected.

**Comment by brianteeman** [comment]
ah i see what yu mean abut the aria-required

**Comment by wilsonge** [comment]
OK In that case I'm happy :) @roland-d do you want to get the students to open a separate issue for that (also is that an issue in 3.x or 4 only?)

**Comment by roland-d** [comment]
@wilsonge It is only an issue in 4.x. I will let @eXsiLe95 create a new PR with a fix for this issue as he found it.

**Comment by wilsonge** [comment]
:+1:

**Comment by Murat75** [comment]
I have tested this item ✅ successfully on cf63da3

System Information
Running on XAMPP 7.1.4-0
macOS Sierra Version 10.12.6
Safari Version 10.1.2 
PHP 4.7.0
Joomla! 4.0-dev (joomla@4.0.0)

Steps
1. Install XAMP 7.1.4-0 on macOS ✅

2. Install joomla on github with the branch 4.0-dev ✅

3. Clone this on your Mac with your SSHkey or Download an ZIP-File and put it on the htdocs ✅

4. XAMPP on mac is difficult with the user rights, you must be give on terminal the folder admin rights with "chmod 777" to continue install joomla-4 on Safari ✅

5. Install Joomla4 ✅

6. You must activate the Two Factor Authentication
	1. Backend -> Control Panel -> Extension -> Manage -> Manage and activate Google Authenticator and YubiKey ✅

7. create user
	1. Backend -> User -> Manage -> create 2 users (1. google, 2. yubi) ✅
	2. give user "google" the Google Authentication Method ✅
	3. give user "yubi" the Yubikey Authentication Method ✅

8. Go to frontend/site <yourinstallpath>/index.php
	1. Test without TFA
		1. Try to log in with superuser with wrong password -> it works ✅
		2. Try to log in with superuser with additional secret key -> it doestn work because the secret key must be enabled
		3. Login with superuser without TFA -> it works ✅
		4. Log out 
		5. Go to <youtinstallpath>/index.php/login 
		6. Try to log in with superuser with wrong password -> doesnt work, because wrong password
		7. Try to log in with superuser with additional secret key -> it doestn work because the secret key must be enabled
		8.	Login with superuser without TFA -> it works ✅
		9. Log out

	2. Test with Google TFA
		1. Try to log in with Google TFA user with wrong password but no secret key -> it doesnt work, Username and password do not match or you do not have an account yet.
		2. Try to log in with Google TFA user with wrong password and wrong secret key -> doenst work, Username and password do not match or you do not have an account yet.
		3. Try to log in with Google TFA user with wrong password but correct secret key -> doesnt work, Username and password do not match or you do not have an account yet.
		4. Try to log in with Google TFA user with correct password but no secret key -> doesnt work, The two factor authentication Secret Key is invalid.
		5. Try to log in with Google TFA user with correct password but incorrect secret key -> doesnt work, The two factor authentication Secret Key is invalid.
		6. Login with the user with Google TFA with the login box -> it works ✅
		7. Log out
		8. Go to <youtinstallpath>/index.php/login
		9. Try to log in with Google TFA user with wrong password but no secret key -> Username and password do not match or you do not have an account yet.
		10. Try to log in with Google TFA user with wrong password and wrong secret key -> Username and password do not match or you do not have an account yet.
		11. Try to log in with Google TFA user with wrong password but correct secret key -> Username and password do not match or you do not have an account yet.
		12. Try to log in with Google TFA user with correct password but no secret key -> The two factor authentication Secret Key is invalid.
		13. Try to log in with Google TFA user with correct password but incorrect secret key -> The two factor authentication Secret Key is invalid.
		14. Login with the user with Google TFA with the login box -> it works ✅
		15. Log out

	3. Test with YubiKey
		1. Try to log in with YubiKey TFA user with wrong password but no secret key -> Username and password do not match or you do not have an account yet.
		2. Try to log in with YubiKey TFA user with wrong password and wrong secret key -> Username and password do not match or you do not have an account yet.
		3. Try to log in with YubiKey TFA user with wrong password but correct secret key -> Username and password do not match or you do not have an account yet.
		4. Try to log in with YubiKey TFA user with correct password but no secret key -> The two factor authentication Secret Key is invalid.
		5. Try to log in with YubiKey TFA user with correct password but incorrect secret key -> The two factor authentication Secret Key is invalid.
		6. Login with the user with YubiKey TFA with the login box -> it works ✅
		7. Log out
		8. Go to <youtinstallpath>/index.php/login
		9. Try to log in with YubiKey TFA user with wrong password but no secret key -> Username and password do not match or you do not have an account yet.
		10. Try to log in with YubiKey TFA user with wrong password and wrong secret key -> Username and password do not match or you do not have an account yet.
		11. Try to log in with YubiKey TFA user with wrong password but correct secret key -> Username and password do not match or you do not have an account yet.
		12. Try to log in with YubiKey TFA user with correct password but no secret key -> The two factor authentication Secret Key is invalid.
		13. Try to log in with YubiKey TFA user with correct password but incorrect secret key -> The two factor authentication Secret Key is invalid.
		14. Login with the user with YubiKey TFA with the login box -> it works ✅
		15. Log out

9. Go to backend/administrator <yourinstallpath/administrator
	1. Test without TFA
		1. Try to log in with superuser with wrong password -> Username and password do not match or you do not have an account yet.
		2. Try to log in with superuser with wrong password and additional secret key -> Username and password do not match or you do not have an account yet.
		3. Try to log in with superuser with correct password and additional secret key -> it works ✅
		4. Login with superuser without TFA -> works
		5. Try to log in with superuser with correct password and incorrect secret key -> it works, but there are a Warning with this line: You need to enable two factor authentication in your user profile to use the secret code field. ✅
		5. Log out

	2. Test with Google TFA
		1. Try to log in with Google TFA user with wrong password but no secret key -> Username and password do not match or you do not have an account yet.
		2. Try to log in with Google TFA user with wrong password and wrong secret key ->Username and password do not match or you do not have an account yet.
		3. Try to log in with Google TFA user with wrong password but correct secret key -> Username and password do not match or you do not have an account yet.
		4. Try to log in with Google TFA user with correct password but no secret key -> The two factor authentication Secret Key is invalid.
		5. Try to log in with Google TFA user with correct password but incorrect secret key ->The two factor authentication Secret Key is invalid.
		6. Login with the user with Google TFA with the login box -> it works ✅
		7. Log out

	3. Test with YubiKey TFA
		1. Try to log in with YubiKey TFA user with wrong password but no secret key -> Username and password do not match or you do not have an account yet.
		2. Try to log in with YubiKey TFA user with wrong password and wrong secret key -> Username and password do not match or you do not have an account yet.
		3. Try to log in with YubiKey TFA user with wrong password but correct secret key -> Username and password do not match or you do not have an account yet.
		4. Try to log in with YubiKey TFA user with correct password but no secret key -> The two factor authentication Secret Key is invalid.
		5. Try to log in with YubiKey TFA user with correct password but incorrect secret YubiKey -> The two factor authentication Secret Key is invalid.
		6. Login with the user with YubiKey TFA with the login box -> it works ✅
		7. Log out

Now I install the joomla from Willsin with is fixedwrong PR and started the test again.

1. Go to frontend/site <yourinstallpath>/index.php
	1. Test without TFA
		1. Try to log in with superuser with  password -> it works ✅
		2. Try to log in with superuser with additional secret key -> it works, but give an Warning: You need to enable two factor authentication in your user profile to use the secret code field. ✅
		3. Login with superuser without TFA -> it works ✅
		4. Log out 
		5. Go to <youtinstallpath>/index.php/login 
		6. Try to log in with superuser with wrong password -> doesnt work, Username and password do not match or you do not have an account yet.
		7. Try to log in with superuser with additional secret key -> it works, You need to enable two factor authentication in your user profile to use the secret code field. ✅
		8.	Login with superuser without TFA -> it works ✅
		9. Log out

	2. Test with Google TFA
		1. Try to log in with Google TFA user with wrong password but no secret key -> it doesnt work, Username and password do not match or you do not have an account yet.
		2. Try to log in with Google TFA user with wrong password and wrong secret key -> doenst work, Username and password do not match or you do not have an account yet.
		3. Try to log in with Google TFA user with wrong password but correct secret key -> doesnt work, Username and password do not match or you do not have an account yet.
		4. Try to log in with Google TFA user with correct password but no secret key -> doesnt work, The two factor authentication Secret Key is invalid.
		5. Try to log in with Google TFA user with correct password but incorrect secret key -> doesnt work, The two factor authentication Secret Key is invalid.
		6. Login with the user with Google TFA with the login box -> it works ✅
		7. Log out
		8. Go to <youtinstallpath>/index.php/login
		9. Try to log in with Google TFA user with wrong password but no secret key -> Username and password do not match or you do not have an account yet.
		10. Try to log in with Google TFA user with wrong password and wrong secret key -> Username and password do not match or you do not have an account yet.
		11. Try to log in with Google TFA user with wrong password but correct secret key -> Empty password not allowed. A new Alert of Warning
		12. Try to log in with Google TFA user with correct password but no secret key -> The two factor authentication Secret Key is invalid.
		13. Try to log in with Google TFA user with correct password but incorrect secret key -> The two factor authentication Secret Key is invalid.
		14. Login with the user with Google TFA with the login box -> it works ✅
		15. Log out

	3. Test with YubiKey
		1. Try to log in with YubiKey TFA user with wrong password but no secret key -> Username and password do not match or you do not have an account yet.
		2. Try to log in with YubiKey TFA user with wrong password and wrong secret key -> Username and password do not match or you do not have an account yet.
		3. Try to log in with YubiKey TFA user with wrong password but correct secret key -> Username and password do not match or you do not have an account yet.
		4. Try to log in with YubiKey TFA user with correct password but no secret key -> The two factor authentication Secret Key is invalid.
		5. Try to log in with YubiKey TFA user with correct password but incorrect secret key -> The two factor authentication Secret Key is invalid.
		6. Login with the user with YubiKey TFA with the login box -> it works ✅
		7. Log out
		8. Go to <youtinstallpath>/index.php/login
		9. Try to log in with YubiKey TFA user with wrong password but no secret key -> Username and password do not match or you do not have an account yet.
		10. Try to log in with YubiKey TFA user with wrong password and wrong secret key -> Username and password do not match or you do not have an account yet.
		11. Try to log in with YubiKey TFA user with wrong password but correct secret key -> Username and password do not match or you do not have an account yet.
		12. Try to log in with YubiKey TFA user with correct password but no secret key -> The two factor authentication Secret Key is invalid.
		13. Try to log in with YubiKey TFA user with correct password but incorrect secret key -> The two factor authentication Secret Key is invalid.
		14. Login with the user with YubiKey TFA with the login box -> it works ✅
		15. Log out<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17687">issues.joomla.org/tracker/joomla-cms/17687</a>.</sub>

**Comment by Murat75** [comment]
Tested @icampus<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17687">issues.joomla.org/tracker/joomla-cms/17687</a>.</sub>

**Comment by Murat75** [comment]
I have tested this item :white_check_mark: successfully on cf63da3ec43c8e6924fd867cc6b81ac58bff4780<br /><br />I have tested this item ✅ successfully on cf63da3

System Information
Running on XAMPP 7.1.4-0
macOS Sierra Version 10.12.6
Safari Version 10.1.2 
PHP 7
Joomla! 4.0-dev (joomla@4.0.0)

Steps
1. Install XAMP 7.1.4-0 on macOS ✅

2. Install joomla from github with the branch 4.0-dev ✅

3. Clone this on your Mac with your Download an ZIP-File and put it on the htdocs ✅

4. XAMPP on mac is difficult with the user rights, you must be give on terminal the folder admin rights with "chmod 777" to continue install joomla-4  ✅

5. Install Joomla4 ✅

6. You must activate the Two Factor Authentication
	1. Backend -> Control Panel -> Extension -> Manage -> Manage and activate Google Authenticator and YubiKey ✅

7. create user
	1. Backend -> User -> Manage -> create 2 users (1. google, 2. yubi) ✅
	2. give user "google" the Google Authentication Method ✅
	3. give user "yubi" the Yubikey Authentication Method ✅

8. Go to frontend/site <yourinstallpath>/index.php
	1. Test without TFA
		1. Try to log in with superuser with wrong password -> it works ✅
		2. Try to log in with superuser with additional secret key -> it doestn work because the secret key must be enabled
		3. Login with superuser without TFA -> it works ✅
		4. Log out 
		5. Go to <youtinstallpath>/index.php/login 
		6. Try to log in with superuser with wrong password -> doesnt work, because wrong password
		7. Try to log in with superuser with additional secret key -> it doestn work because the secret key must be enabled
		8.	Login with superuser without TFA -> it works ✅
		9. Log out

	2. Test with Google TFA
		1. Try to log in with Google TFA user with wrong password but no secret key -> it doesnt work, Username and password do not match or you do not have an account yet.
		2. Try to log in with Google TFA user with wrong password and wrong secret key -> doenst work, Username and password do not match or you do not have an account yet.
		3. Try to log in with Google TFA user with wrong password but correct secret key -> doesnt work, Username and password do not match or you do not have an account yet.
		4. Try to log in with Google TFA user with correct password but no secret key -> doesnt work, The two factor authentication Secret Key is invalid.
		5. Try to log in with Google TFA user with correct password but incorrect secret key -> doesnt work, The two factor authentication Secret Key is invalid.
		6. Login with the user with Google TFA with the login box -> it works ✅
		7. Log out
		8. Go to <youtinstallpath>/index.php/login
		9. Try to log in with Google TFA user with wrong password but no secret key -> Username and password do not match or you do not have an account yet.
		10. Try to log in with Google TFA user with wrong password and wrong secret key -> Username and password do not match or you do not have an account yet.
		11. Try to log in with Google TFA user with wrong password but correct secret key -> Username and password do not match or you do not have an account yet.
		12. Try to log in with Google TFA user with correct password but no secret key -> The two factor authentication Secret Key is invalid.
		13. Try to log in with Google TFA user with correct password but incorrect secret key -> The two factor authentication Secret Key is invalid.
		14. Login with the user with Google TFA with the login box -> it works ✅
		15. Log out

	3. Test with YubiKey
		1. Try to log in with YubiKey TFA user with wrong password but no secret key -> Username and password do not match or you do not have an account yet.
		2. Try to log in with YubiKey TFA user with wrong password and wrong secret key -> Username and password do not match or you do not have an account yet.
		3. Try to log in with YubiKey TFA user with wrong password but correct secret key -> Username and password do not match or you do not have an account yet.
		4. Try to log in with YubiKey TFA user with correct password but no secret key -> The two factor authentication Secret Key is invalid.
		5. Try to log in with YubiKey TFA user with correct password but incorrect secret key -> The two factor authentication Secret Key is invalid.
		6. Login with the user with YubiKey TFA with the login box -> it works ✅
		7. Log out
		8. Go to <youtinstallpath>/index.php/login
		9. Try to log in with YubiKey TFA user with wrong password but no secret key -> Username and password do not match or you do not have an account yet.
		10. Try to log in with YubiKey TFA user with wrong password and wrong secret key -> Username and password do not match or you do not have an account yet.
		11. Try to log in with YubiKey TFA user with wrong password but correct secret key -> Username and password do not match or you do not have an account yet.
		12. Try to log in with YubiKey TFA user with correct password but no secret key -> The two factor authentication Secret Key is invalid.
		13. Try to log in with YubiKey TFA user with correct password but incorrect secret key -> The two factor authentication Secret Key is invalid.
		14. Login with the user with YubiKey TFA with the login box -> it works ✅
		15. Log out

9. Go to backend/administrator <yourinstallpath/administrator
	1. Test without TFA
		1. Try to log in with superuser with wrong password -> Username and password do not match or you do not have an account yet.
		2. Try to log in with superuser with wrong password and additional secret key -> Username and password do not match or you do not have an account yet.
		3. Try to log in with superuser with correct password and additional secret key -> it works ✅
		4. Login with superuser without TFA -> works
		5. Try to log in with superuser with correct password and incorrect secret key -> it works, but there are a Warning with this line: You need to enable two factor authentication in your user profile to use the secret code field. ✅
		5. Log out

	2. Test with Google TFA
		1. Try to log in with Google TFA user with wrong password but no secret key -> Username and password do not match or you do not have an account yet.
		2. Try to log in with Google TFA user with wrong password and wrong secret key ->Username and password do not match or you do not have an account yet.
		3. Try to log in with Google TFA user with wrong password but correct secret key -> Username and password do not match or you do not have an account yet.
		4. Try to log in with Google TFA user with correct password but no secret key -> The two factor authentication Secret Key is invalid.
		5. Try to log in with Google TFA user with correct password but incorrect secret key ->The two factor authentication Secret Key is invalid.
		6. Login with the user with Google TFA with the login box -> it works ✅
		7. Log out

	3. Test with YubiKey TFA
		1. Try to log in with YubiKey TFA user with wrong password but no secret key -> Username and password do not match or you do not have an account yet.
		2. Try to log in with YubiKey TFA user with wrong password and wrong secret key -> Username and password do not match or you do not have an account yet.
		3. Try to log in with YubiKey TFA user with wrong password but correct secret key -> Username and password do not match or you do not have an account yet.
		4. Try to log in with YubiKey TFA user with correct password but no secret key -> The two factor authentication Secret Key is invalid.
		5. Try to log in with YubiKey TFA user with correct password but incorrect secret YubiKey -> The two factor authentication Secret Key is invalid.
		6. Login with the user with YubiKey TFA with the login box -> it works ✅
		7. Log out

Now I install the joomla from Wilson with is fixedwrong PR and started the test again.

1. Go to frontend/site <yourinstallpath>/index.php
	1. Test without TFA
		1. Try to log in with superuser with  password -> it works ✅
		2. Try to log in with superuser with additional secret key -> it works, but give an Warning: You need to enable two factor authentication in your user profile to use the secret code field. ✅
		3. Login with superuser without TFA -> it works ✅
		4. Log out 
		5. Go to <youtinstallpath>/index.php/login 
		6. Try to log in with superuser with wrong password -> doesnt work, Username and password do not match or you do not have an account yet.
		7. Try to log in with superuser with additional secret key -> it works, You need to enable two factor authentication in your user profile to use the secret code field. ✅
		8.	Login with superuser without TFA -> it works ✅
		9. Log out

	2. Test with Google TFA
		1. Try to log in with Google TFA user with wrong password but no secret key -> it doesnt work, Username and password do not match or you do not have an account yet.
		2. Try to log in with Google TFA user with wrong password and wrong secret key -> doenst work, Username and password do not match or you do not have an account yet.
		3. Try to log in with Google TFA user with wrong password but correct secret key -> doesnt work, Username and password do not match or you do not have an account yet.
		4. Try to log in with Google TFA user with correct password but no secret key -> doesnt work, The two factor authentication Secret Key is invalid.
		5. Try to log in with Google TFA user with correct password but incorrect secret key -> doesnt work, The two factor authentication Secret Key is invalid.
		6. Login with the user with Google TFA with the login box -> it works ✅
		7. Log out
		8. Go to <youtinstallpath>/index.php/login
		9. Try to log in with Google TFA user with wrong password but no secret key -> Username and password do not match or you do not have an account yet.
		10. Try to log in with Google TFA user with wrong password and wrong secret key -> Username and password do not match or you do not have an account yet.
		11. Try to log in with Google TFA user with wrong password but correct secret key - > Username and password do not match or you do not have an account yet.
		12. Try to log in with Google TFA user with correct password but no secret key -> The two factor authentication Secret Key is invalid.
		13. Try to log in with Google TFA user with correct password but incorrect secret key -> The two factor authentication Secret Key is invalid.
		14. Login with the user with Google TFA with the login box -> it works ✅
		15. Log out

	3. Test with YubiKey
		1. Try to log in with YubiKey TFA user with wrong password but no secret key -> Username and password do not match or you do not have an account yet.
		2. Try to log in with YubiKey TFA user with wrong password and wrong secret key -> Username and password do not match or you do not have an account yet.
		3. Try to log in with YubiKey TFA user with wrong password but correct secret key -> Username and password do not match or you do not have an account yet.
		4. Try to log in with YubiKey TFA user with correct password but no secret key -> The two factor authentication Secret Key is invalid.
		5. Try to log in with YubiKey TFA user with correct password but incorrect secret key -> The two factor authentication Secret Key is invalid.
		6. Login with the user with YubiKey TFA with the login box -> it works ✅
		7. Log out
		8. Go to <youtinstallpath>/index.php/login
		9. Try to log in with YubiKey TFA user with wrong password but no secret key -> Username and password do not match or you do not have an account yet.
		10. Try to log in with YubiKey TFA user with wrong password and wrong secret key -> Username and password do not match or you do not have an account yet.
		11. Try to log in with YubiKey TFA user with wrong password but correct secret key -> Username and password do not match or you do not have an account yet.
		12. Try to log in with YubiKey TFA user with correct password but no secret key -> The two factor authentication Secret Key is invalid.
		13. Try to log in with YubiKey TFA user with correct password but incorrect secret key -> The two factor authentication Secret Key is invalid.
		14. Login with the user with YubiKey TFA with the login box -> it works ✅
		15. Log out<hr /><sub>This comment was created with the <a 

Tested @icampus
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17687">issues.joomla.org/tracker/joomla-cms/17687</a>.</sub>

**Pull request merged**
