### PR TITLE
[4.0] Advanced search filter by author

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #32901 .

### Summary of Changes
Change to sort by title

### Testing Instructions
Create a few articles all with different authors (or author alias)
In the front end go to the search component and open the advanced search to show the filters
Click on the Authors

### Actual result BEFORE applying this Pull Request
Authors listed non-alphabetically

### Expected result AFTER applying this Pull Request
Authors listed alphabetically

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 77e66ec45240dc620f4167c4c19e169cf448ae4b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34175">issues.joomla.org/tracker/joomla-cms/34175</a>.</sub>

**Comment by Abernyte-Git** [comment]
I have tested this item :white_check_mark: successfully on 77e66ec45240dc620f4167c4c19e169cf448ae4b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34175">issues.joomla.org/tracker/joomla-cms/34175</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34175">issues.joomla.org/tracker/joomla-cms/34175</a>.</sub>

**Comment by Quy** [comment]
Thank you!

**Comment by brianteeman** [comment]
thank you

**Pull request merged**
