### PR TITLE
Reverting #16403

### PR DESCRIPTION
**Pull request by Bakual**
This PR revert the PR "[4.0] Generate an autoload_psr4.php with extensions namespaces" #16403

### Summary of Changes
Just reverts said PR.

### Testing Instructions
Nothing to test as the whole thing got commented out in a later commit (https://github.com/joomla/joomla-cms/commit/63846d17f458d4a033fb22c4e7eff0882907a07c) by @wilsonge anyway

### Expected result
Everything works

### Actual result
Everything works

### Documentation Changes Required
None

### CODE REVIEW

**Comment by wilsonge** [comment]
I was not drunk. This work is gonna be finished by yves in the make it happen later. It turned out whilst this worked in the cms environment it was killing travis and we had to spend some time to work out why and how to fix it. But we have a plan now for this afternoon

**Comment by Bakual** [comment]
George, that's not how this works.
A PR has to be in a useable state before it gets merged. And of course one waits for Travis to finish before merging. Also stuff like this should get a chance for review by others. And of course the PR should actually state the goal and reasoning of it.

The J4 branch here isn't a playground anymore. Please keep that in mind.

**Comment by Bakual** [comment]
Please revert it. You can merge it again after it is finished and nobody objects to it.

**Comment by mbabker** [comment]
Some of the accusations and backhanded commentary in this thread can go away.  Yes, the approach is not agreed on by all individuals heavily involved in 4.0 work, but this is not just some random thing that George and Yves threw together and snuck into the code at a whim.  Yes, the PR was incomplete, and that is being addressed today.  Leave the commentary at technical issues without accusing people of merging code while drinking, that is a very insulting statement to be making on a public thread toward a release coordinator, especially as someone who is himself a prior leadership team member.

**Comment by Bakual** [comment]
Removed that sentence.

**Comment by laoneo** [comment]
I think the pr should be reverted and then properly done. Especially to give the community the chance to review it then. If we are going the path where we try to avoid the discussion then this is a bad sign to the community.

**Comment by Bakual** [comment]
@laoneo There is already a follow up PR merged which tries to improve this plugin but still doesn't get it to a working state.

But it made reverting the original PR superfluous and this PR does would need to be adjusted.
Given that there seems to be no interest to revert that thing and start a real feature PR which can be discussed and tested, I'm going to close this PR (read: I gave up on it).

**Comment by laoneo** [comment]
I still think all should be done in one pr and not spreading it across multiple ones. I'm not against the idea, but the way how it is done. But yeah, giving up is probably a good way to move forward.

**Comment by Bakual** [comment]
Exactly my thinking..

**Pull request closed without merging**
