### PR TITLE
Fix #5648 Menu Manager: Add Menu :: Display a correct error message

### LINKED ISSUE #5648: Menu Manager: Add Menu :: Display a correct error message for the better usability
-Go to menu manager:Add menu
-Enter valid title
-Click on menu type text field, enter press button[keyboard space] Do not write anything
-click on save 
-Check the message, **It should be error message instead of warning, It should work same as article works**

 screen shot 2015-01-09 at 08 36 28
screen shot 2015-01-09 at 08 36 40

### PR DESCRIPTION
**Pull request by pcmitsis**
```
This PR fixes this issue: Menu Manager: Add Menu :: Display a correct error message for the better usability #5648
```

### CODE REVIEW

**Comment by infograf768** [comment]
Correct change. As it is simple, RTC.

**Comment by pcmitsis** [comment]
@infograf768 I would like to ask you if you know when a PR is being merged?

Thank you!

**Comment by infograf768** [comment]
We are now in code freeze, except for major discovered bugs in the RC.
This one could go in after 3.4.0 is released.

**Comment by zero-24** [comment]
>This one could go in after 3.4.0 is released.

@infograf768 can you than add the 3.4.1 milestone, so this don't get lost?

**Pull request merged**
