### PR TITLE
Missing string in front end #6206

### PR DESCRIPTION
**Pull request by brianteeman**
As of Joomla 3.4 alias incrementing was implemented making it possible for users to more easily create articles with the same name. If an article named "joomla-tutorial" already existed and someone creates another one, the alias will automatically become "joomla-tutorial-1" and so on. In the backend when submitting an already existing alias it says "Warning Alias already existed so a number was added at the end. You can re-edit the article to customise the alias." which is an informative warning. However when submitting an article on the frontend it says "Warning COM_CONTENT_SAVE_WARNING". The language constant does not display the intended message for frontend users, but does for backend users.

### CODE REVIEW

**Comment by n9iels** [comment]
@test confirmed, this patch solves the bug

**Comment by dgt41** [comment]
@test success.

**Comment by zero-24** [comment]
Moving to RTC based on testing. Thanks! :+1: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6210">issues.joomla.org/joomla-cms/6210</a>.</sub>

**Comment by phproberto** [comment]
Merged. Thanks!

**Pull request closed without merging**
