### PR TITLE
[4.1] Add text COM_WORKFLOW_STAGE_FORM_NEW to com_workflow.ini

### PR DESCRIPTION
**Pull request by richard67**
Pull Request for Issue #37390 part 1 .

### Summary of Changes

Added the missing language string as discussed in the issue and removed the old one since it is not used anywhere directly or by string concatenation of the key.

### Testing Instructions

Edit a workflow stage.

In the edit view, use the action "Save & New".

After that the aria-label of the form should have changed from "Edit Stage" to "Add Stage".

### Actual result BEFORE applying this Pull Request

Aria label "COM_WORKFLOW_STAGE_FORM_ADD".

### Expected result AFTER applying this Pull Request

Aria label "Add Stage".

### Documentation Changes Required

None.

### CODE REVIEW

**Comment by brianteeman** [comment]
Can you delete the old string?

On my phone so can't check if it's used elsewhere

**Comment by richard67** [comment]
> Can you delete the old string?
> 
> On my phone so can't check if it's used elsewhere

@brianteeman Done. As far as I could see it is not used anywhere else directly or for building it by concatenation.

But I still don't find where the string has to appear, i.e. which element shall have that aria-label.

**Comment by brianteeman** [comment]
See #32060

**Comment by richard67** [comment]
> See #32060

@brianteeman I saw the issue but the description there is not clear. Meanwhile I found it: You have to be in the edit view of a stage and then use the action "Save & New". After that the aria-label of the form changes from "Edit Stage" to the untranslated text (when the PR is not applied).

**Comment by richard67** [comment]
Testing instructions updated. Please test.

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 7f86366f53702f44c369bc1f136a19ac89aa197a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37393">issues.joomla.org/tracker/joomla-cms/37393</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 7f86366f53702f44c369bc1f136a19ac89aa197a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37393">issues.joomla.org/tracker/joomla-cms/37393</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37393">issues.joomla.org/tracker/joomla-cms/37393</a>.</sub>

**Review by tecpromotion — APPROVED** [review]

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
