### PR TITLE
[4.1] Sort import

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
Alpha sort import

### Testing Instructions
Code review

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 8d159541ca100b2112c38031beed6108c7d41c76<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36174">issues.joomla.org/tracker/joomla-cms/36174</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 8d159541ca100b2112c38031beed6108c7d41c76<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36174">issues.joomla.org/tracker/joomla-cms/36174</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36174">issues.joomla.org/tracker/joomla-cms/36174</a>.</sub>

**Comment by chmst** [comment]
thanks

**Pull request merged**
