### PR TITLE
[4.3] Phan: Languagefilter plugin

### PR DESCRIPTION
**Pull request by Hackwar**
### Summary of Changes
These changes resulted from a static analysis run of phan. These are the changes:
1. The use statement is not used in the code anywhere
2. parseRule() returns null, not an array. The return statement and the $array can be removed.
3. onUserAfterSave() actually returns null and not boolean.
4. The way we are setting the cookie has been deprecated and this is now the new version how to call that.

### Testing Instructions
Codereview

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on d089a96871bb80851e27e5cb48eff41f94398be6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39983">issues.joomla.org/tracker/joomla-cms/39983</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on d089a96871bb80851e27e5cb48eff41f94398be6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39983">issues.joomla.org/tracker/joomla-cms/39983</a>.</sub>

**Comment by chmst** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39983">issues.joomla.org/tracker/joomla-cms/39983</a>.</sub>

**Comment by obuisard** [comment]
Thank you Hannes @Hackwar

**Pull request merged**
