### PR TITLE
Refactor com_postinstall from FOF to Joomla Core

### PR DESCRIPTION
**Pull request by Curtista**
#### Summary of Changes
- Refactor com_postinstall from FOF to Joomla core
- Remove dependencies to FOF
#### Testing Instructions
- Step 1: Go to the backend 
- Step 2: Navigate to Components->Post installation Messages
- Step 3: All available post install messages should be shown
- Step 4: Clicking the "Hide this message" button should hide the message
- Step 5: Clicking a blue action button will execute appropriated action
  (e.g. 2FA Message action button will activate the 2FA plugin)
- Step 6: If all messages are hidden a reset button will appear, clicking it will reset all messages
- Step 7: Clicking the "Help" Button in the toolbar will popup a help window
- Step 8: Clicking the "Options" Button in the toolbar will lead you to the component options
- Step 9: After applying the changes Step 1-8 should work the same.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11546">issues.joomla.org/joomla-cms/11546</a>.</sub>

**Comment by mbabker** [comment]
Unless I've missed a memo somewhere, I'm going to ask a simple question.  Why?

**Comment by zero-24** [comment]
FOF is not maintained any more? IIRC

**Comment by zero-24** [comment]
I have tested this item :red_circle: unsuccessfully on c27683ce14ded23cfb7690afca06707695529dcf<br /><br />It don't work for me. It looks like that the postinstall condichen method is not respected (e.g. `admin_postinstall_statscollection_condition()` https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_admin/postinstall/statscollection.php) check don't work. 

I'm on PHP7.0.8 but it shows me the PHP5.3 warning.
same applys for the language issue since 3.4.1
and for the stats collection.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11546">issues.joomla.org/joomla-cms/11546</a>.</sub>

**Comment by zero-24** [comment]
screen shot 2016-08-10 at 14 49 01<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11546">issues.joomla.org/joomla-cms/11546</a>.</sub>

**Comment by rdeutz** [comment]
FOF is still maintained, I made a PR some months ago and it got merged into 2.x. FOF will be part of 3.x and I don't think it is flagged as depreciated for 4. So there is no real need to recode this part at this moment.

**Comment by zero-24** [comment]
>FOF is still maintained

I'm not sure but it is up to the PLT but close the PR if will not be acceppted.

>Unfortunately FOF 2 is deprecated and on its way to being completely discontinued. For over a year we've been telling developers to upgrade to FOF 3. We are not going to address any further issues in FOF 2. My recommendation is to upgrade your components to FOF 3.

https://github.com/akeeba/fof/issues/593#issuecomment-201182780

**Comment by rdeutz** [comment]
We have to ship FOF2 as long as 3.x exists, if the original author doesn't supports FOF2 we have to fill the gap

**Comment by zero-24** [comment]
Ok. I mean upstream support. I know we need to ship it but there is no reason to not remove the dependency from FOF2 from core components or i miss something?

**Comment by rdeutz** [comment]
Remove the dependency is no problem, when it works :-)

**Comment by mbabker** [comment]
Unless you're going to refactor two factor authentication and possibly other features which are already using FOF as well, there's an inbuilt dependency to FOF code and I don't see that as being an issue right now.  To me there's no benefit in going through this exercise at this point in time; it'd be the same as saying we need to use our own mail library because PHPMailer 5.2 is close to being unsupported since they're about to release 6.0.  It'll have to be refactored at 4.x if a newer FOF version is shipped or FOF stops being included at all in either case, so right now it seems like a bit of premature work for the sake of doing so.  That's just my opinion.

**Comment by zero-24** [comment]
This is the reason for this PR?

**Comment by roland-d** [comment]
The reason for this PR is @wilsonge as he requested this to be able to deprecate FOF and remove it in the next major version of Joomla.

**Comment by Curtista** [comment]
@zero-24 

I fixed the issue. Could you test it again?

**Comment by laoneo** [comment]
I have tested this item :white_check_mark: successfully on 6527de1e304c23097b44841f64894ab3684302f2<br /><br />As pythagoras was intended to be Joomla 4 it was intended to remove FOF https://github.com/joomla-projects/joomla-pythagoras/issues/66.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11546">issues.joomla.org/joomla-cms/11546</a>.</sub>

**Comment by zero-24** [comment]
Works now for me. Just one thing to check, do we know any 3Party extension that use the Core com_postinstall?

**Comment by Curtista** [comment]
As long as the database entries are correct everything should work as before.

**Comment by mbabker** [comment]
> As long as the database entries are correct everything should work as before.

It's not just the database.  It's the hook functions that need to be 100% B/C as well.

> The reason for this PR is @wilsonge as he requested this to be able to deprecate FOF and remove it in the next major version of Joomla.

IMO this is setting bad precedent.  Right now it looks like pull requests are being submitted for the sake of removing dependencies to third party code which has reached end of support.  Without a proper roadmap or communication, there's no justification for this refactoring right now other than "well, we might do this later".  It also opens the door to actions such as writing a Joomla mailer library to replace PHPMailer because the version we're using is no longer supported, or forking Bootstrap, or jQuery, or one of about a dozen other libraries.

There is no need to 100% refactor all code away from existing dependencies in order to deprecate it.  A simple announcement of fact is all you have to do.  Yes, it's preferred to refactor away, but without a roadmap there's no guidance on what should be done.  Is the intent to not ship any version of FOF in 4.0?  Is the intent to ship FOF 3 in 4.0?  If there's an intention to deprecate FOF support in Joomla, why are we getting pull requests to first refactor the dependencies without any form of communication on why or intent?  This again screams leadership fail.

**Comment by andrepereiradasilva** [comment]
if the intention is to remove fof in joomla 4.0 this should be rebased to 4.0 branch

**Comment by Bakual** [comment]
Afaik it was decided long ago that J4 will no longer ship with FoF.
It is perfectly fine to do this PR already in J3.

**Comment by mbabker** [comment]
It all comes back to a subjective argument of B/C.  We refactored the MVC implementation in com_config at 3.2 and a couple of developers raised issues because of its restructuring.

**Comment by anibalsanchez** [comment]
Hi, one minor issue on labels:

- Post-installation Messages for COM_POSTINSTALL_TITLE_JOOMLA
- Showing messages for COM_POSTINSTALL_TITLE_JOOMLA
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11546">issues.joomla.org/tracker/joomla-cms/11546</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 6527de1e304c23097b44841f64894ab3684302f2<br /><br />Step 7: Clicking the "Help" Button in the toolbar popup a help window (see below) – with and without this PR.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11546">issues.joomla.org/tracker/joomla-cms/11546</a>.</sub>

**Comment by wilsonge** [comment]
This has been merged into the 4.0 branch with https://github.com/joomla/joomla-cms/commit/1de8d7a2816b723bd5d80142925ef46178d842d7

Thanks for being patient with this!

**Pull request closed without merging**
