### PR TITLE
Refresh changelog URL on manifest cache refresh

### PR DESCRIPTION
**Pull request by AlterBrains**
### Summary of Changes

Currently, extension manifest cache refresh doesn't update `<changelogurl>`

### Testing Instructions

Add or change `<changelogurl>https://site.com</changelogurl>` in any extension manifest XML.
Refresh manifest cache.

### Actual result BEFORE applying this Pull Request

`changelogurl` in `#__extensions` table is not updated.

### Expected result AFTER applying this Pull Request

`changelogurl` in `#__extensions` table is updated.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by AlterBrains** [comment]
@Ruud68 This PR is about refresh, not update. Here is PR for update, I've added your issue ID:
https://github.com/joomla/joomla-cms/pull/44564

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 18f33b82bd6e9545a5d66da95342d3bd966a94f4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44565">issues.joomla.org/tracker/joomla-cms/44565</a>.</sub>

**Comment by Hackwar** [comment]
I have tested this item :white_check_mark: successfully on 18f33b82bd6e9545a5d66da95342d3bd966a94f4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44565">issues.joomla.org/tracker/joomla-cms/44565</a>.</sub>

**Comment by Hackwar** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44565">issues.joomla.org/tracker/joomla-cms/44565</a>.</sub>

**Comment by pe7er** [comment]
Thanks @AlterBrains !

**Pull request merged**
