### PR TITLE
[4.0] [com_templates] Use target from event

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Minor code cleanup to use target from event instead of hardcoded variable.

### Testing Instructions

Go to template details.
In Editor tab check that clicking folder icons expand the directory tree.
Click "New File" button. In the modal click on some folder icon. Create a file. Check that the file is created in the correct location.

### Expected result

Works like before.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on b4e10d03104947f0d3c34f1e56ba27cba520ab35<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29144">issues.joomla.org/tracker/joomla-cms/29144</a>.</sub>

**Comment by bonzani** [comment]
I have tested this item :white_check_mark: successfully on b4e10d03104947f0d3c34f1e56ba27cba520ab35<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29144">issues.joomla.org/tracker/joomla-cms/29144</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29144">issues.joomla.org/tracker/joomla-cms/29144</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
