### PR TITLE
Remove Manager Part 1

### PR DESCRIPTION
**Pull request by brianteeman**
This is the Pull request for the first part of the work by @rgmears to remove the word manager which is pretty redundant https://github.com/joomla/user-interface-text/issues/42

This PR only looks at the top menu and the quicklinks. The screenshots below show you the before and after.

manager-rgmears-part1

manager-rgmears-part2

### CODE REVIEW

**Comment by zero-24** [comment]
Also this RTC Thanks Brian :smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7431">issues.joomla.org/joomla-cms/7431</a>.</sub>

**Comment by brianteeman** [comment]
Thanks for setting this RTC but I am removing the RTC label as this change needs testing and approval as it changes something that's been this way for over 10 years.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7431">issues.joomla.org/joomla-cms/7431</a>.</sub>

**Comment by MAT978** [comment]
successfully tested.

Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7431">issues.joomla.org/joomla-cms/7431</a>.</sub>

**Comment by wilsonge** [comment]
Personally this looks a lot better to me. I'll bring it up in the CMS Maintainers Group though for you Brian :)

**Comment by brianteeman** [comment]
If accepted I will make all the extra PR that are needed

**Comment by rdeutz** [comment]
Isn't for Users, Menu and Extension the word Users, Menu and Extension redundant?

Menu -> Manager -> ... makes more sense for me as Menu -> Menu

**Comment by brianteeman** [comment]
Thats an interesting idea. Is this how it is done in german?

On 14 July 2015 at 18:27, Robert Deutz <notifications@github.com> wrote:

> Isn't for Users, Menu and Extension the word Users, Menu and Extension
> redundant?
>
> Menu -> Manager -> ... makes more sense for me as Menu -> Menu
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/7431#issuecomment-121315523>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
And how would it be handled on the quick menu

**Comment by Bakual** [comment]
>  Is this how it is done in german?

In german it's "Menüs" -> "Menüs", "Benutzer" -> "Benutzer" and "Erweiterungen" -> "Erweiterungen".
Looks indeed a bit ugly, especially in the manager itself where you have "Menüs: Menüs" and "Benutzer: Benutzer" as the title.

**Comment by MAT978** [comment]
Agree that  having 'Menus : Menu(s)' inside the manager itself is a bit weird but then, what would it be on the Control panel?
"Structure
->Menu(s)"
?

**Comment by zero-24** [comment]
>Menu -> Manager -> 

Menu -> Manager -> Add New Menu?
Extensions -> Manager?
Users -> Manager -> Add new User?

For the Toolbar it means:
(old) Menu Manager: Menus
(new) Menu: Manager

Extensions (nothing changed)
Extensions: Install

(old) User Manager: Users
(new) User: Manager

Personaly I don't think this is much better.

**Comment by zero-24** [comment]
>In german it's "Menüs" -> "Menüs", "Benutzer" -> "Benutzer" and "Erweiterungen" -> "Erweiterungen".
Looks indeed a bit ugly, especially in the manager itself where you have "Menüs: Menüs" and "Benutzer: Benutzer" as the title.

Hmm for sure only these 3. The other components (under the Components Dropdown) don't have this issue ;)

**Comment by zero-24** [comment]
maybe we can remove the manager only particular for

Extensions -> Template Manager
Extensions -> Module Manager
...

And leave for the "Top entrys" like
Extensions -> Extensions Manager
Users --> User Manager
...

**Comment by rgmears** [comment]
Menus -> Menu(s) 
could be 
Menus -> Manage

Users -> Users 
could be
Users -> Manage

And Configuration -> Global Configuration 
should be
Configuration -> Global

**Comment by brianteeman** [comment]
But what would you do on the quicklinks module?
And when you drill down into the manager page (PR2) what should it then show?

**Comment by rgmears** [comment]
Do the same on the Quicklinks module. Except: 

Structure
-> Menu(s)
-> Modules

(However I would rather go to Menu Items than Menus from that quick link.)

Not sure what you mean. Drill down? PR2?

**Comment by wilsonge** [comment]
PR2 i think means the second PR part here https://github.com/joomla/joomla-cms/pull/7432

**Comment by brianteeman** [comment]
For drill down I mean #7432
If the menu is just Manager what does it say in the list view title

**Comment by rgmears** [comment]
Sorry for being so thick here. What is "list view title"?

**Comment by brianteeman** [comment]
This is the view I am referring to. 

articles

**Comment by rgmears** [comment]
This is how I think it should look.

mgr_menus

mgr_menu_items

**Comment by brianteeman** [comment]
But then you have a menu item called manager that loads a page with the
title menus.

That was the inconsistency I was trying to highlight

**Comment by rgmears** [comment]
Where is the menu item "manager" with the page title "menus"?

It might simplify matters to do this:

mgr_structure

Then the Main Menu reflects the organization of the Quick Links menu.

**Comment by brianteeman** [comment]
That was your suggestion several messages up

Menus -> Menu(s)
could be
Menus -> Manage

**Comment by brianteeman** [comment]
As for changing the names of the top level menus and the contents of the
menus I think that is best left to a separate issue

**Comment by rgmears** [comment]
Seemed silly to have Menus -> Menu(s) in the menu. 

In this context the Menus page is the same as Categories under Content. Perhaps changing the Menu item to Structure or Navigation (if Modules are left under Extensions) would work. Then you would have 
Navigation  v
    -> Menu(s)
    -> Menu Items

**Comment by rgmears** [comment]
Alternatively change the title on the Menus page to Manage Menu(s) and everybody's happy.

**Comment by RCheesley** [comment]
There's only one point here which I don't agree with, and that is the change from 'Access Levels' to 'Access'.  I think people would better understand what it means to include Access Levels, and I guess when translated that might also make it clearer in other languages.

Everything else I think is an improvement and de-clutters things.

**Comment by MAT978** [comment]
as a non native :p agree with @RCheesley for 'Access Level' & still agree with the originals screen shots from @brianteeman

**Comment by brianteeman** [comment]
I will prepare an updated PR - thanks

On 16 July 2015 at 01:33, Marc-Antoine Thevenet <notifications@github.com>
wrote:

> as a non native :p agree with @RCheesley <https://github.com/RCheesley>
> for 'Access Level' & still agree with the originals screen shots from
> @brianteeman <https://github.com/brianteeman>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/7431#issuecomment-121789416>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
Closing this while @rgmears and myself prepare the final complete PR

**Pull request closed without merging**
