### PR TITLE
[Drone] Make sure an copied repo don't run into issues with the rips step & add tests for 4.0-dev

### PR DESCRIPTION
**Pull request by zero-24**
Make sure an copied repo don't run into issues with the rips step

cc @rdeutz @wilsonge

### CODE REVIEW

**Comment by rdeutz** [comment]
I think there is a better way, @zero-24 can you have a look at this http://docs.drone.io/step-conditions/  We can limit steps based on the branch the build is running. So it is clearer what we are doing

**Comment by zero-24** [comment]
Well i'm more thinking about 1:1 copys of the cms repos like the privacy repo or all the other 4.0-dev clones out there like the gsoc repos. As far as I understand the branch etc would not help us here? It could help with the different app id's for sure.

**Comment by zero-24** [comment]
@rdeutz this is now fully working and all tests (rips 4.0-dev & staging) are in an single file now. When approved we can merge the .drone.yml up to the other branches so we don't mess up the config at the time Michael or George do branch merges. ;)

**Comment by rdeutz** [comment]
I will copy the change into the 4.0-dev branch

**Comment by zero-24** [comment]
Thanks @rdeutz

**Pull request merged**
