### PR TITLE
[4] Remove unnecessary curly braces

### PR DESCRIPTION
**Pull request by PhilETaylor**
Code review

### CODE REVIEW

**Comment by joomdonation** [comment]
I have tested this item :white_check_mark: successfully on b0ba86e950231cd628fe0b2a4ecc03b5c06d76bc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33999">issues.joomla.org/tracker/joomla-cms/33999</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on b0ba86e950231cd628fe0b2a4ecc03b5c06d76bc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33999">issues.joomla.org/tracker/joomla-cms/33999</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33999">issues.joomla.org/tracker/joomla-cms/33999</a>.</sub>

**Comment by Quy** [comment]
Thanks!

**Pull request merged**
