### PR TITLE
[4.3] Backport of Smart Search: Fixing taxonomy filter handling

### PR DESCRIPTION
**Pull request by obuisard**
Backport of PR #39751 that was merged into 5.0.
This should have been included in 4.3 and was overlooked. 
Our sincere apologies to the author of the original PR, Hannes @Hackwar.

### Summary of Changes

When the taxonomies were refactored to be a nested set, this part was overlooked. This means that nested taxonomies in filters don't work.

### Testing Instructions

1. Create an article in a category which is at least on the second level.
2. Create a filter which only searches in that articles parent category. 
3. Go to the frontend and search for a word in that article. You will get the article as result.
4. Add &f=[filter-id] to the URL to only show results from our category.
5. Notice that you get no result at all!
6. Apply changes.
7. Only the article appears again.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by wilsonge** [comment]
Just FYI backporting things like this is going to cause you major merge conflicts when you come back to putting these things back into 5.0

**Comment by Sabine-2023** [comment]
I have tested this item :white_check_mark: successfully on b1c9c9193b0ee15c490a495cc16464543592027f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40687">issues.joomla.org/tracker/joomla-cms/40687</a>.</sub>

**Comment by ceus1984** [comment]
I have tested this item :white_check_mark: successfully on b1c9c9193b0ee15c490a495cc16464543592027f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40687">issues.joomla.org/tracker/joomla-cms/40687</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40687">issues.joomla.org/tracker/joomla-cms/40687</a>.</sub>

**Comment by sdwjoomla** [comment]
Thanks @Hackwar

**Pull request merged**
