### PR TITLE
[4.0] use Joomla\CMS\Filter\InputFilter;

### PR DESCRIPTION
**Pull request by brianteeman**
Update to namespce

code review

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on e2b428c18c3039611b21c4990474ab8799a35727<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31684">issues.joomla.org/tracker/joomla-cms/31684</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on e2b428c18c3039611b21c4990474ab8799a35727<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31684">issues.joomla.org/tracker/joomla-cms/31684</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31684">issues.joomla.org/tracker/joomla-cms/31684</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Another one bites the dust

**Pull request merged**
