### PR TITLE
featured filter added in com_content articles api

### PR DESCRIPTION
**Pull request by antonbag**
Pull Request for Issue # .

### Summary of Changes
Filter by featured and filter by tag included

### Testing Instructions
In postman, GET {{base_url}}/{{base_path}}/content/articles?filter[featured]=1
In postman, GET {{base_url}}/{{base_path}}/content/articles?filter[tag]=1

### Actual result BEFORE applying this Pull Request
No filtered by featured nor tag

### Expected result AFTER applying this Pull Request
Filter articles by featured and/or tag

### CODE REVIEW

**Comment by alikon** [comment]
your change didn't have only `filter[featured]`  but `filter[tag]` too please update test instructions

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 78429ae3822dee12ff6789bf6884a92fd80b9a02<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38798">issues.joomla.org/tracker/joomla-cms/38798</a>.</sub>

**Review by wilsonge — APPROVED** [review]

**Comment by ReLater** [comment]
> `filter[tag]=1`

What does that mean? "Has a tag" or is that a tag `id`?

**Comment by antonbag** [comment]
> > `filter[tag]=1`
> 
> What does that mean? "Has a tag" or is that a tag `id`?

Is a tag id

**Comment by ReLater** [comment]
I have tested this item :white_check_mark: successfully on 1c5a5fa744b66e7cbb4fa1d857bd1d204316bde6<br /><br />Tested with Linux console and several combinations like

$ token=c2hhMjU2OjM0MDo0MjExNzY2MmIzZDIwMzU2YzIw...
$ url="https://example.org/api/index.php/v1/content/articles?"

$ curl -H "Authorization: Bearer $token" $url"filter\[tag\]=3"

$ curl -H "Authorization: Bearer $token" $url"filter\[featured\]=1"

$ curl -H "Authorization: Bearer $token" $url"filter\[featured\]=1&filter\[tag\]=1"<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38798">issues.joomla.org/tracker/joomla-cms/38798</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38798">issues.joomla.org/tracker/joomla-cms/38798</a>.</sub>

**Comment by laoneo** [comment]
Thanks @antonbag for this nice improvement. Are you able to add these filters to the automated tests here https://github.com/joomla/joomla-cms/blob/4.3-dev/tests/Codeception/api/com_content/ContentCest.php? You can make new test functions for each filter.

**Comment by obuisard** [comment]
Thank you @antonbag for this great PR!

**Pull request merged**
