### PR TITLE
Move component message to system-message-container

### PR DESCRIPTION
**Pull request by n9iels**
With the move of all the filter from the left sidebar to `joomla.serachtools` some component messages has a small layout issue. The messages are stick to the serachtools, without padding.

This PR moves all messages like "Enable this plugin", "This option is enabled" to a `JFactory::getApplication()->enqueueMessage()`. So they will be displayed above the serachtools. All messages like "There are no item available` stay below the searchtools.
## Test instructions

Compare the following screenshots
1) Go to Components -> Smart Search
Before the patch:
com_finder before

After the patch:
com_finder after

2) Go to Extensions -> Manage -> Database
Before the patch:
com_installer database before

After the patch:
com_install database after

3) Go to Extensions -> Install
Before patch:
com_install before

After patch:
com_install after

4) Go to Extensions -> update
Before patch:
com_install update before

After patch:
com_install update after

5) Go to Components -> Redirect
Before the patch:
com_redirect before

After the patch:
com_redirect after

6) Go to components -> Search
Before the patch:
com_search before

After the patch:
com_search after

7) Disable the plugin, and enable/disable the Gathering statistics options. Confirm the messages are the same before and after the patch
# Note

This is a redo of #8282, someting went wrong with solving merge conflict over there

### CODE REVIEW

**Comment by infograf768** [comment]
>Does anybody know if the remove of administrator/manifests/packages/pkg_weblinks.xml in this PR is something I should care about? 

I guess that, as long as it is not deleted in script.php, it is no use indeed for new installs.

**Comment by 810** [comment]
+1 can be merged, same results as other pr.

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on dc4c0b23a64c60a37459e55ce66ecc4a420db0ad<br /><br />Followed test instructions and tested ok<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8399">issues.joomla.org/joomla-cms/8399</a>.</sub>

**Comment by n9iels** [comment]
Is it possible to set this PR on RTC? Because it is a copy of a PR which was allready tested succesful...

**Comment by anibalsanchez** [comment]
I have tested this item :white_check_mark: successfully on dc4c0b23a64c60a37459e55ce66ecc4a420db0ad<br /><br />It works OK<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8399">issues.joomla.org/joomla-cms/8399</a>.</sub>

**Comment by brianteeman** [comment]
Marking RTC (not sure why it has a 3.6 milestone)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8399">issues.joomla.org/joomla-cms/8399</a>.</sub>

**Comment by n9iels** [comment]
@brianteeman thanks :)

I solved the merge conflict, so it is completely RTC

**Comment by wilsonge** [comment]
Hi @n9iels there were conflicts again. I *think* I have fixed them when merging this Pull Request with https://github.com/joomla/joomla-cms/commit/43ac19192de37d83b9b883b991d58c3de52bb819  however if you could please review it would be very much appreciated :)

**Pull request closed without merging**
