### PR TITLE
[4.0] Remove horizontal scrollbar in media modal

### PR DESCRIPTION
**Pull request by Quy**
Pull Request for Issue #26703 .

### Summary of Changes

PR fixes margins causing the horizontal scrollbar in medial modal.
`.row` and `.media-container` are essentially the same except for margins.
Ideally, use `.row` in Media page and use `.media-container` in media modal.

### Testing Instructions
Go to Content > Articles
Edit an article
Click Images and Links tab
Click Select button
See horizontal scrollbar
Apply PR
Run `npm i`
Clear browser's cache
No horizontal scrollbar

### CODE REVIEW

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 24b92fcedf1f793dd51faa8ad7a0e08f8aaf2a29<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26988">issues.joomla.org/tracker/joomla-cms/26988</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 24b92fcedf1f793dd51faa8ad7a0e08f8aaf2a29<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26988">issues.joomla.org/tracker/joomla-cms/26988</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26988">issues.joomla.org/tracker/joomla-cms/26988</a>.</sub>

**Comment by infograf768** [comment]
tks

**Pull request merged**
