### PR TITLE
[4.0] ] fix color selector box too big issue

### PR DESCRIPTION
**Pull request by brianteeman**
I am not 100% convinced this is the correct solution but based on the accepted code in #30585 it is a working solution

npm run build:css

Pull Request for Issue #33596 

After applying PR etc
image

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on faf42876d7415eb2c5d7e3396c92151e1d2762ac<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33611">issues.joomla.org/tracker/joomla-cms/33611</a>.</sub>

**Comment by Shubham-com** [comment]
I have tested this item :white_check_mark: successfully on faf42876d7415eb2c5d7e3396c92151e1d2762ac<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33611">issues.joomla.org/tracker/joomla-cms/33611</a>.</sub>

**Comment by Kostelano** [comment]
I have tested this item :white_check_mark: successfully on faf42876d7415eb2c5d7e3396c92151e1d2762ac<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33611">issues.joomla.org/tracker/joomla-cms/33611</a>.</sub>

**Comment by alikon** [comment]
RTC

3 is a perfect number for me :smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33611">issues.joomla.org/tracker/joomla-cms/33611</a>.</sub>

**Comment by richard67** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks - still not 100% this is the best way

**Comment by richard67** [comment]
But a bit better than before.

**Pull request merged**
