### PR TITLE
Ensure public JHtml helpers can be overridden

### PR DESCRIPTION
**Pull request by mbabker**
This patch does a review on the uses of JHtml helpers in the libraries folder and ensures that most public facing methods are called through the `JHtml::_()` method to allow them to be overridden using the JHtml API.
### Summary of Change
- Calls to `static::method()` in JHtml helper classes changed to use the `JHtml::_()` method call
- Calls to certain JHtml methods (script, stylesheet, tooltipText being among the most common offenders) changed to use the `JHtml::_()` method call
### Testing Instructions

Make sure the CMS still works.  This patch touches a lot of files in most every component or JHtml helper.

### CODE REVIEW

**Comment by designbengel** [comment]
is there a better instruction to test it? "If the CMS still works" is too global IMO ;-)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7950">issues.joomla.org/joomla-cms/7950</a>.</sub>

**Comment by mbabker** [comment]
Without breaking this down into an obscene number of patches, not really.  A lot of the changes change the calls for the tooltipText method from `JHtml::tooltipText()` to `JHtml::_('tooltipText')`, so one indicator of breakage is that tooltips would not render correctly anymore.

**Comment by dgt41** [comment]
I have tested this item :white_check_mark: successfully on 6ead8f12d35f5d9b21882038cccf43846c1fdb64<br /><br />All good front end - backend, also Reviewed for typos all good<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7950">issues.joomla.org/joomla-cms/7950</a>.</sub>

**Comment by zero-24** [comment]
@mbabker can you fix merge conflicts?

**Pull request closed without merging**
