### PR TITLE
Change `range` pagination to ?`strip` pagination.

### PR DESCRIPTION
**Pull request by bato3**
### Summary of Changes

Before solution gave me stupid results:
### Documentation Changes Required

Before solution gave me stupid results:
page 1: 1 2 3 4 ... 6 7 8 9 10 
page 10:  5 6 7 8 ... 10 11 12 13 14 
page 14:  ... 10 11 12 13 14 ... 16 17 18 
page 16:  11 12 13 ... 15 16 17 18 19 ... 
last page (20):  11 12 13 14 15 16 17 18 ... 20 

AFTER:
page 1:  1 2 3 4 5 6 7 8 9 ... 
page 6:  1 2 3 4 5 6 7 8 9 ... 
page 7:  ... 3 4 5 6 7 8 9 10 ... 
page 189:  ... 185 186 187 188 189 190 191 192 ... 
page 190:  ... 186 187 188 189 190 191 192 193 194 
last page:  ... 186 187 188 189 190 191 192 193 194 
### config:

Menu link: index.php?option=com_content&view=category&layout=blog&id=49
num_intro_articles: 20

### CODE REVIEW

**Comment by brianteeman** [comment]
1. Do you realise that this file is an "override" for the specific protostar template so any changes made here will not apply to other templates - it also means that you can apply it to your own template without needing to be implemented in the core of joomla


2. I dont understand what is "stupid" about the results

**Comment by SharkyKZ** [comment]
I think he means that useless ... in the center. This was fixed in #10240 but only for Isis. Maybe should be implemented globally.

**Comment by franz-wohlkoenig** [comment]
I have tested this item :red_circle: unsuccessfully on afbc4cb5b00c5c42fd8e38f6eaeb6f13f2e249c4<br /><br />Notice: Undefined offset: 1 in /Joomla/templates/protostar/html/pagination.php on line 104<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12350">issues.joomla.org/tracker/joomla-cms/12350</a>.</sub>

**Comment by brianteeman** [comment]
I am closing this PR - it doesnt work and has not been touched for over a year. It  an always be reopened if the merge conflicts and bugs are fixed

**Pull request closed without merging**
