### PR TITLE
[plugin][actionlog][joomla] use namespaced User/Factory

### PR DESCRIPTION
**Pull request by alikon**
### Summary of Changes

- use the namespaced `User` instead of `JUser`
- use the namespaced `Factory` instead of `JFactory`

### Testing Instructions
code review 
or 
test logout, login failure user save works as before

### CODE REVIEW

**Comment by sandewt** [comment]
Ho @alikon,


The parent class is **ActionLogPlugin**, see the code of the file *plugins/actionlog/joomla/joomla.php* (1)

```
class PlgActionlogJoomla extends ActionLogPlugin
{
```

The file */administrator/components/com_actionlogs/libraries/actionlogplugin.php* (2) contains the following code in line 60
```
abstract class ActionLogPlugin extends JPlugin
{
...
$user = JFactory::getUser(); // line 60
...
```
So I think, you can move the namspace code `use Joomla\CMS\Factory` to that file (2) and change the code in line 60.

Possible, there is more code to combine.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23334">issues.joomla.org/tracker/joomla-cms/23334</a>.</sub>

**Comment by alikon** [comment]
see #23341

**Comment by sandewt** [comment]
Note:

The file *plugins/actionlog/joomla/joomla.xml* contains the following code:

```
</files>
	<config /> // this code is wrong (line 15)
</extension>

```

Delete the tag in line 15. This is unnecessary.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23334">issues.joomla.org/tracker/joomla-cms/23334</a>.</sub>

**Comment by alikon** [comment]
please do it in a separate PR

**Comment by alikon** [comment]
@sandewt 
for commemt https://github.com/joomla/joomla-cms/pull/23334#issuecomment-449973199
done

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 78a568f43fe45467b97904abec81bea22bd894c5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23334">issues.joomla.org/tracker/joomla-cms/23334</a>.</sub>

**Comment by twister65** [comment]
I have tested this item :white_check_mark: successfully on 78a568f43fe45467b97904abec81bea22bd894c5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23334">issues.joomla.org/tracker/joomla-cms/23334</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23334">issues.joomla.org/tracker/joomla-cms/23334</a>.</sub>

**Pull request merged**
