### PR TITLE
[5.2] wip Update accessibility toolbar

### PR DESCRIPTION
**Pull request by brianteeman**
Updated to v6
adds some new functions
- [x] update to latest library
- [x] increase/decrease line height (disable until/if fixed upstream)
- [x] disable animations (NEW)
- [x] default emoji icon no longer skewed
- [x] link to optional accessibility statement (NEW)
- [x] dark mode
- [x] Angie icon set (https://github.com/angieradtke/Accessibility-plugin-icons)
- [ ] Auto(partial)hide icon and expand on focus
- [x] extract css to external file to allow greater customisation
- [x] add position option
- [ ] ~add custom function to use open dyslexie font~ leave for another day
- [x] translate "hotkey"

### Still to do
- [ ] Fix hot keys not working https://github.com/ranbuch/accessibility/issues/68
- [ ] Save/close Refresh icons https://github.com/ranbuch/accessibility/issues/67
- [ ] web assets ?
- [ ] Default icon https://github.com/ranbuch/accessibility/issues/67
- [ ] Missing some icons 

Working with upstream to resolve multiple bugs

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Quy** [comment]
Can you please add #39102 to the to-do list?

**Comment by HLeithner** [comment]
This pull request has been automatically rebased to 5.2-dev.

**Comment by brianteeman** [comment]
@fedik One of the issues with this script that I would like to resolve is that there are a lot of [advanced customisations](https://ranbuch.github.io/accessibility/) that can be made via js or css. Creating a UI for this would be overkill as they are typically advanced use cases. 

My thought process is that the plugin can have two additional fields for the user to enter advanced jss and css. 

An example might be entering the following to the js field
```

instance.menuInterface.increaseText = function() {

// My own way to increase text size . . .

}
```

My question therefore is what would be the correct way to output/use the contents of these two advanced fields.

**Comment by Fedik** [comment]
That could work, but that a very bad idea :wink: 

What you could try, is to add "important options" (from your point of view) to the plugin parameters.
And then move this code https://github.com/joomla/joomla-cms/blob/a306ee6e21801c874c279b264b0241d66c9b0b53/plugins/system/accessibility/src/Extension/Accessibility.php#L105-L111
to own file (asset) `media/plg_system_accessibility/js/accessibility-config.js`
Then Advanced User can override it with template override.

And for css it can be part of `user.css` (or something kind of `accessibility-user.css`).

**Comment by brianteeman** [comment]
Before I comment on why I dont want to do it the way that you suggest can you explain why it is a bad idea. I wont learn anything otherwise.

**Comment by Fedik** [comment]
Allowing User to insert JS in backed, is kind of the same as allowing User insert PHP in backend.
We cannot control that code, and what they put in there. 
Integrate this code with existing plugin parameters will be close to impossible.

Addittionaly it can create a potential security problem.

**Comment by brianteeman** [comment]
> Allowing User to insert JS in backed, is kind of the same as allowing User insert PHP in backend.

Doh - silly me

**Comment by brianteeman** [comment]
Since I started this PR upstream has completely changed (again) 

It is now possible to create our own ui for the toolbar instead of the hacky solutions that were previously available

See the Custom Styling section https://ranbuch.github.io/accessibility/site/

**Comment by brianteeman** [comment]
Note: The icons from Angie will need to be adjusted if we want to use them as an icon font (doesnt support multiple colors/shades) although I guess if the latest upstream changes are used to create our own UI for the toolbar then svg could be used

**Comment by drmenzelit** [comment]
Doing some tests today. The hotkeys work for me, but ctrl+alt+q (animations) in Chrome but not in Firefox
ctrl+alt+r activate the reading guide an opens something from my graphic card too, but that is something specific from my PC

**Comment by brianteeman** [comment]
yeah the hotkeys are weird. No idea what to do there

**Comment by drmenzelit** [comment]
grafik
grafik

IBM Equal Access Accessibility Checker and in the Firefox Accessibility tab I get some errors / things to review... can we do something here?

**Comment by brianteeman** [comment]
As you said you didnt want to create our own ui these are both upstream issues to resolve.

**Comment by brianteeman** [comment]
i think it is probably better to use the fontawesome web asset than the icons generated by angie

**Comment by chmst** [comment]
My vision is fontawesome icons as default but an option for custom icons.

**Comment by brianteeman** [comment]
dont be confused with the icons for the toolbar actions and the icon for the button

**Comment by LadySolveig** [comment]
Just for reference, I have submitted a PR upstream for the tabindex issue https://github.com/ranbuch/accessibility/issues/87 PR https://github.com/ranbuch/accessibility/pull/86

**Comment by brianteeman** [comment]
I gave up looking at this due to the complete lack of any communication from the accessibility team

**Comment by LadySolveig** [comment]
@brianteeman would you mind reopening this PR? So that hopefully we can bring the new version into 5.4

**Comment by brianteeman** [comment]
It cant be re-opened as the 5.2-dev branch has been deleted here so github wont let me.

While I was working on it I discovered loads of bugs which he fixed but it really requires a rewrite of the plugin to be able to use the icons the way we want to. The implementation that ranbuch did for non-material icons is a pia

**Comment by LadySolveig** [comment]
Do you want to open a new one or should I do it?

**Comment by brianteeman** [comment]
> I gave up looking at this due to the complete lack of any communication from the accessibility team

Do as you wish. I won't waste any more if my time on it as the accessibility team clearly are not interested

**Comment by LadySolveig** [comment]
Thank you, then I am pleased to build on the work you have already done.

**Pull request closed without merging**
