### PR TITLE
[4] Module 'Feed Display': deprecated Notice

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #42793 .

### Summary of Changes
skip if publishDate is null

### Testing Instructions

see #42793 

### Actual result BEFORE applying this Pull Request
 deprecated Notice

### Expected result AFTER applying this Pull Request

No deprecated Notice

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on bbe656da66865df39014bf4617f87266bc0cc927<br /><br />J 4.4.3-dev<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42803">issues.joomla.org/tracker/joomla-cms/42803</a>.</sub>

**Comment by ceford** [comment]
I came across a problem testing this PR: with an Atom feed there is still a deprecated notice with the patch applied. See this Forum discussion: https://forum.joomla.org/viewtopic.php?f=834&t=1007409&p=3715335#p3715335 and perhaps try this feed url: https://www.youtube.com/feeds/videos.xml?channel_id=UCbayot0NQ0HWeCs9J8Mx7fA

I realise fixing an Atom feed may be considered a different issue to fixing an RSS feed. But that would be lost on the end user.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42803">issues.joomla.org/tracker/joomla-cms/42803</a>.</sub>

**Comment by fgsw** [comment]
I have tested this item :white_check_mark: successfully on bbe656da66865df39014bf4617f87266bc0cc927<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42803">issues.joomla.org/tracker/joomla-cms/42803</a>.</sub>

**Comment by alikon** [comment]
@ceford is right
just got the same result with `https://www.youtube.com/feeds/videos.xml?channel_id=UCbayot0NQ0HWeCs9J8Mx7fA`
image

**Comment by MacJoom** [comment]
Thank you!

**Pull request merged**
