### PR TITLE
Changed Autosuggester

### PR DESCRIPTION
**Pull request by tkempf**
Change Autosuggester so that it respects static-filters,accesslevels,publish up/down dates and article states
This code is not yet production ready but runs fine for me on a site with Joomla 2.5.17 since 2 years

### CODE REVIEW

**Comment by pjmatos** [comment]
I'm testing this in J3.4.1 and it is working okay.
Thanks, tkempf.

**Comment by kathastaden** [comment]
I tested with version: Joomla 3.4.4-dev development

1) Enable the Smart Search Plugin
2) Go to the Smart Search Component and click "Index" to get some results
3) Have a look at the Frontend and the Smart Search module and test the autosuggestion there
4) Search for an article that is unpublished - with the patch this one should not be suggested anymore
5) Search for an article that will be published in future - with the patch this one should not be suggested anymore
6) Search for an article that is only for Super Users and you are not logged in at the Frontend - with the patch this one should not be suggested anymore
7) Create a Search Filter and use the Smart Search of the Frontend to find it

Result: After I apllied the patch, the whole suggestions in the Smart Search didn't work anymore. As an example I searched for "similar" because there is an article called "Similar Tags" and this one should be suggested.
I attached a screenshot of the suggestion before the patch was applied, and after it was applied. 
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4401">issues.joomla.org/joomla-cms/4401</a>.</sub>

**Comment by hitchblade** [comment]
Using Joomla Version : 3.4.4-dev.
Enable Smart Search Plugin. Tested a while. After I applied the Plugin and go to my smartsearch in the Frontend, I get a blank Page...<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4401">issues.joomla.org/joomla-cms/4401</a>.</sub>

**Comment by zero-24** [comment]
@tkempf can you try to get the code working on the current staging? Based on the last tests it don't work. Please add a comment if you have find the issue. Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4401">issues.joomla.org/joomla-cms/4401</a>.</sub>

**Comment by tkempf** [comment]
code is now working again on current staging. There was an issue when no filter was selected. While testing i found that the content - finder plugin does not reflect state changes in the search index items. IMO disabling an article should disable the corresponding search index item. Pls. correct me if i am wrong...

**Comment by adriano-paula-ribeiro** [comment]
I confirm patch this one should not be suggested anymore.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4401">issues.joomla.org/joomla-cms/4401</a>.</sub>

**Comment by brianteeman** [comment]
Thank you for creating this but it would appear that this has been resolved elsewhere in the code base. If this is not correct then this can be re-opened<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/4401">issues.joomla.org/joomla-cms/4401</a>.</sub>

**Comment by Giuse69** [comment]
I just tested on J3.5.1 and autosuggester does not respect for example access level: as a guest I get a suggestion for a Administrator level article, so it is not resolved in codebase?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/4401">issues.joomla.org/joomla-cms/4401</a>.</sub>

**Comment by Quy** [comment]
@brianteeman Should this be closed too as unfixable per #16011?

**Pull request closed without merging**
