### PR TITLE
com_categories: batch copy not copy permission

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #8600.

### Summary of Changes
let's copy permission too

### Testing Instructions

- Create a category.
- Go to its permission tab and make a change. (e.g registered->allow creating)
- Go to Batch and Copy it somewhere else.

### Expected result

the permission are copyed

### Actual result

permission are not copied

### CODE REVIEW

**Comment by ghost** [comment]
@peteruoi @AlexRed can you please test?

**Comment by brianteeman** [comment]
Does this not have to be done everywhere there is `function batchCopy`

**Comment by alikon** [comment]
yes, true, just let see if this is considered a bug fix or a new feature before
and then we can do other's pr for article etc....

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 3947e0e320f88d41425e706c18c3c070e87b9aec<br /><br />++<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24730">issues.joomla.org/tracker/joomla-cms/24730</a>.</sub>

**Comment by infograf768** [comment]
Imho, looks rather as a bug fix, not a new feature. 
Why copy a category instead of creating a new one if the permissions are not also copied?

**Comment by richard67** [comment]
@infograf768 Well, you still can use copy because being too lazy to type again other stuff like title or desciption, which may be the same for some sub-categories below different parent categories.

So I am not sure if this PR has to be considered as bug fix or as a new feature.

I would vote for bug fix, too, but I think release leaders should decide.

=> Ping @HLeithner for 3.9 and @wilsonge for 4.0.

(Meanwhile I am preparing myself for testing.)

**Comment by infograf768** [comment]
@alikon 
we do have a Notice though:

[27-Apr-2019 11:40:38 Europe/Berlin] PHP Notice:  Trying to get property of non-object in ~/libraries/src/UCM/UCMType.php on line 169

### EDIT
The Notice is also present here before this PR

**Comment by alikon** [comment]
@infograf768 unable to  reproduce the notice
btw i've made #24736 for copying items to another category

**Comment by infograf768** [comment]
hmm... Maybe the Notice is specific to a multilingual site?
That test site is regularly updated here, so it may be another aspect

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 3947e0e320f88d41425e706c18c3c070e87b9aec<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24730">issues.joomla.org/tracker/joomla-cms/24730</a>.</sub>

**Comment by richard67** [comment]
@infograf768 I was also not able to reproduce the notice. Tested on monolingual fresh install with testing sample data.

**Comment by infograf768** [comment]
Ok, found the issue. I had in the content_types table a remaining of a 3rd party extension (Breezing forms) which had been deleted for long from the site but left a row in the table...

**Comment by infograf768** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24730">issues.joomla.org/tracker/joomla-cms/24730</a>.</sub>

**Comment by richard67** [comment]
@franz-wohlkoenig Any reason why this is not merged? Has 2 good tests, has RTC. Only thing is it needs a "rebase" (i.e. merge from staging).

**Comment by infograf768** [comment]
Rebased.
@HLeithner to decide merging or not.

**Comment by HLeithner** [comment]
thx

**Pull request merged**
