### PR TITLE
[4.0] remove unused class

### PR DESCRIPTION
**Pull request by brianteeman**
The class `order` is not present in the css (its not in j3 either) - this PR removes it

code review

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 936daaf77b493b7d6dbdc22da97ebc9b2b364fe6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26593">issues.joomla.org/tracker/joomla-cms/26593</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 936daaf77b493b7d6dbdc22da97ebc9b2b364fe6<br /><br />review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26593">issues.joomla.org/tracker/joomla-cms/26593</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26593">issues.joomla.org/tracker/joomla-cms/26593</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
