### PR TITLE
Templates modal converted to bootstrap

### PR DESCRIPTION
**Pull request by dgrammatiko**
This is a redo of #4645
#### Scope

Use bootstrap instead of the mootools modal!
#### Testing

Apply patch 
go to `/administrator/index.php?option=com_templates&view=templates`
click on the thumbs
#### Preview

screen shot 2015-03-12 at 9 25 35

### CODE REVIEW

**Comment by Fedik** [comment]
@dgt41 know funny thing?
you do not need to call `JHtml::_('bootstrap.modal');` while you have button with `data-toggle="modal"` :smile: 

[Bootstrap Modal](http://getbootstrap.com/2.3.2/javascript.html#modals) see **Usage: Via data attributes**

**Comment by dgt41** [comment]
I guess I was carried away by the line above `JHtml::_('bootstrap.tooltip');` 😄

**Comment by n9iels** [comment]
The css width of 100% ensures that the image gets bigger than the original file size. Maybe you can use `max-with:100%;` instead?

**Comment by dgt41** [comment]
Thanks @n9iels, I was wondering for this. It would be even better if we had just a class there

**Comment by n9iels** [comment]
A class for this doesn't exist so far I know.
But thanks for removing another mootools object :-)

@test works fine for me<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6408">issues.joomla.org/joomla-cms/6408</a>.</sub>

**Comment by Erftralle** [comment]
@test  looks good to me, thanks.

**Comment by MyDadisDead** [comment]
Very nice - test works fine

**Comment by web-mex** [comment]
Hi, on resize the Browserwindow the Modalwindow will hide when the window get smaller as 500px.
I the old version the Window will reachable with scrollbar.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6408">issues.joomla.org/joomla-cms/6408</a>.</sub>

**Comment by web-mex** [comment]
Hi, on resize the Browserwindow the Modalwindow will hide when the window get smaller as 500px.
I the old version the Window will reachable with scrollbar.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6408">issues.joomla.org/joomla-cms/6408</a>.</sub>

**Comment by dgt41** [comment]
@web-mex Thanks, should be fixed now!

**Comment by dgt41** [comment]
@n9iels @Erftralle @MyDadisDead @web-mex Can I ask for a re-test here?
Try to open the modal and then resize the browser to mobile width. The modal should be still visible and adapt to the new size.

**Comment by MyDadisDead** [comment]
Hi
Reverted the patch,logged out to  kill session, logged in and applied the new patch. Modal worked fine and is responsive. Great stuff!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6408">issues.joomla.org/joomla-cms/6408</a>.</sub>

**Comment by n9iels** [comment]
@test works fine for me, thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6408">issues.joomla.org/joomla-cms/6408</a>.</sub>

**Comment by dgt41** [comment]
@MyDadisDead @n9iels Can I be a pain in the a$$ and ask you to also test #4563 ?
Shouldn’t take much time, tho

**Comment by n9iels** [comment]
No problem :+1:

**Comment by Erftralle** [comment]
@test: Patch is still working, thanks. 
Noticed a little change to my previous test. Headline and image in the modal window are now left aligned instead of centered (like in your preview in the test instructions above). Liked it more when it was centered ;-) .

**Comment by dgt41** [comment]
@roland-d can you RTC this?

**Pull request closed without merging**
