### PR TITLE
[4.0] Fix dropdown hide when workflow is active

### PR DESCRIPTION
**Pull request by bembelimen**
Pull Request for Issue # .

### Summary of Changes
Fix the wrong css class selector in action dropdown in the articles list view.

### Testing Instructions
Enable the workflow, mark an article and check the action dropdown in the article list view.

### Actual result BEFORE applying this Pull Request
grafik

### Expected result AFTER applying this Pull Request
grafik

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on b3c0408c18c4c83306e217c32bc5aadb49055068<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33313">issues.joomla.org/tracker/joomla-cms/33313</a>.</sub>

**Comment by dgrammatiko** [comment]
I have tested this item :white_check_mark: successfully on b3c0408c18c4c83306e217c32bc5aadb49055068<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33313">issues.joomla.org/tracker/joomla-cms/33313</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33313">issues.joomla.org/tracker/joomla-cms/33313</a>.</sub>

**Comment by Quy** [comment]
Thanks

**Pull request merged**
