### PR TITLE
[3.7] Add a Postinstall Message to warn users on nearly unsupported envoirments

### PR DESCRIPTION
**Pull request by zero-24**
Pull Request for 3.7.x
### Summary of Changes

Based on the Joomla 4 Manifesto by @wilsonge https://developer.joomla.org/news/658-joomla4-manifesto.html i have created a postinstall warning to all not supported versions.
### Testing Instructions
- apply this patch
  Fire this SQL statment (replace #__ by your prefix)

``` sql
INSERT INTO `#__postinstall_messages` (`extension_id`, `title_key`, `description_key`, `action_key`, `language_extension`, `language_client_id`, `type`, `action_file`, `action`, `condition_file`, `condition_method`, `version_introduced`, `enabled`)
VALUES
(700, 'COM_CPANEL_MSG_JOOMLA40_PRE_CHECKS_TITLE', 'COM_CPANEL_MSG_JOOMLA40_PRE_CHECKS_BODY', '', 'com_cpanel', 1, 'message', '', '', 'admin://components/com_admin/postinstall/joomla40checks.php', 'admin_postinstall_joomla40checks_condition', '3.7.0', 1);
```

If you have a unspported version or use mssql you get a postinstall like this:

image

If you want you can test this but you have no unsupported version you can change e.g. the PHP Version check to  `version_compare(PHP_VERSION, '8.5.9', 'lt');`
### Documentation Changes Required

None

### CODE REVIEW

**Comment by wilsonge** [comment]
Hmm I'm unsure what to do about this. I think it's good. But these were provisional and not final requirements..... as per the manifesto. These versions are definitely going to be unsupported. But don't want people on higher req's to feel like they are 100% safe :/

**Comment by zero-24** [comment]
They are save based on the last data / decisions we currently have. Btw. There is no message "you are save" there is just a message to unsupported versions that they are not save.

**Comment by zero-24** [comment]
Maybe we can fix the wording to make this clear?

**Comment by brianteeman** [comment]
Without a definitive decision there really isnt anything that can be done

**Comment by dgt41** [comment]
can you also mixin:
```php
function is_32bit(){
  return PHP_INT_SIZE === 4;
}
```

and if true (32bit version of PHP) warn about `strtotime` max value is year 2038

Known unix bug: https://en.wikipedia.org/wiki/Year_2038_problem

**Comment by mbabker** [comment]
1) Not appropriate for this PR
2) Do we really need a message for the 2038 problem?

**Comment by dgt41** [comment]
@mbabker could be done in the requirements page as an asterisk or side note. Joomla most likely will be served for a linux machine, so informing people about bugs that might occur due to this fact is not a bad idea, I think. 
So the answer is short answer is: probably not, a simple note in requirements should be sufficient.

**Comment by zero-24** [comment]
The point is lets tell the `i still run PHP 5.3` etc that Joomla 4 will be not supported on this platform.

> Without a definitive decision there really isnt anything that can be done

I agree with your points but who can / would take such a final decision and when? At the release date of Joomla 4 or a week before? I personaly think we should tell the users our planings.
I just do that what i personaly would expect as user ;) -> Let me know if you know something about the planned feature.

But maybe i'm wrong and just try to  overcomunitcate that, i'm not a marketing person ;).

**Comment by brianteeman** [comment]
@zero-24 you are absolutely correct about the need for this message.

**Comment by mbabker** [comment]
It should be made clear in the message that these minimums are not finalized and may change before reaching the 4.0 beta (they shouldn't change after that and if they do there's probably been a major screwup in our choices).  With that I'd say the message is just fine as is.

**Comment by wilsonge** [comment]
The 2038 bug is irrelevant for this PR.

Ok if it's made clear that these requirements may change before 4.0 beta then let's go with it :)

**Comment by zero-24** [comment]
Maybe we can extend the Text with something like this: This are the currently planed minimum requirements that can be raised until the first Beta of 4.0 to be sure we would suggest you to use (PHP(7.0),mysql,postgresql version suggestions here).

or without the suggestions: "This are the currently planed minimum requirements that can maybe raised until the first Beta of 4.0 if we have more information this check will be updated."

**Comment by brianteeman** [comment]
That will pretty much guarantee that the message is ignored.

**Comment by zero-24** [comment]
Ok so we stay with the current message and we can get tests here :smile:

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on cfe0452394b15e43fe435948e68ea88d3aeb843c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12237">issues.joomla.org/tracker/joomla-cms/12237</a>.</sub>

**Comment by coolcat-creations** [comment]
Can´t we just add something to the PHP nag Message? 
https://issues.joomla.org/tracker/joomla-cms/11498<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12237">issues.joomla.org/tracker/joomla-cms/12237</a>.</sub>

**Comment by mbabker** [comment]
Different purposes.

The PHP nag warns explicitly against running unsupported PHP versions from the PHP project or advises to upgrade when it is getting close to its end of support.  That should continue to live on in the Joomla code base as long as Joomla's based on PHP.

This is a message specifically addressing the 4.0 minimum support requirements.

**Comment by zero-24** [comment]
The php nag message is for unsupported by php the postinstall is for unsupported php and mysql etc configs by joomla.

**Comment by conconnl** [comment]
I have tested this item :white_check_mark: successfully on cfe0452394b15e43fe435948e68ea88d3aeb843c<br /><br />Tested successfully at PBF NL<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12237">issues.joomla.org/tracker/joomla-cms/12237</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12237">issues.joomla.org/tracker/joomla-cms/12237</a>.</sub>

**Comment by zero-24** [comment]
:+1: Thanks!

**Pull request merged**
