### PR TITLE
Admin Status module

### PR DESCRIPTION
**Pull request by brianteeman**
#### Summary of Changes

Remove the extra spaces before the links
#### Testing Instructions

Apply the patch and check that there are no leading spaces on any of the links in the admin status module at the bottom

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 0dffcbc7806ea2e55968c41ba824541ca3a1466b<br /><br />Tested by code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9825">issues.joomla.org/joomla-cms/9825</a>.</sub>

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on b37801c181964c9fe3a51e7ff40a9cdda7ef7330<br /><br />Was about to comment about of the space in the multilingual link.

I see you solve it.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9825">issues.joomla.org/joomla-cms/9825</a>.</sub>

**Comment by andrepereiradasilva** [comment]
While you're at it, just to inform when you add a new module there's extra spaces in the links to. For another PR of course.
image

**Comment by brianteeman** [comment]
Yes another PR which I will look at now

**Comment by MATsxm** [comment]
I have tested this item :white_check_mark: successfully on b37801c181964c9fe3a51e7ff40a9cdda7ef7330<br /><br />the most obvious is what we don't see - Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9825">issues.joomla.org/joomla-cms/9825</a>.</sub>

**Comment by brianteeman** [comment]
RTC - thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9825">issues.joomla.org/joomla-cms/9825</a>.</sub>

**Pull request merged**
