### PR TITLE
[4.0] Styling improvements for com_config (site)

### PR DESCRIPTION
**Pull request by C-Lodder**
Pull Request for Issue # .

### Summary of Changes

This PR fixes a few styling issues for Global Configurations in the frontend.

### Testing Instructions

1. Save/cancel buttons are styled correctly.
2. Ensure the grid is aligned correctly.

### CODE REVIEW

**Comment by brianteeman** [comment]
The two column layout is still unusable 
screenshotr13-54-44

**Comment by C-Lodder** [comment]
Try now

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 43aaaa015325c89595072a5cb84a01af3b3afe86<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19230">issues.joomla.org/tracker/joomla-cms/19230</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 43aaaa015325c89595072a5cb84a01af3b3afe86<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19230">issues.joomla.org/tracker/joomla-cms/19230</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Comment by wilsonge** [comment]
Thanks guys :)

**Pull request merged**
