### PR TITLE
[4.0] FIX Menu Assignment - toggle checkboxes

### PR DESCRIPTION
**Pull request by amitranjan2**
Pull Request for Issue #23801 .

### Summary of Changes
`$type->menutype` replace this code to  `str_replace(' ', '-', $type->menutype)` 

### Testing Instructions

* Go to `administrator/index.php?option=com_templates&view=styles`
* Open the Cassiopeia template
* Go to the "Menu Assignment" tab
* Use the buttons to toggle the selection of all checkboxes

### Expected result
Toggle selection checks/unchecks the checkboxes

### Actual result

Not working as expected

### Documentation Changes Required
NO
@C-Lodder

### CODE REVIEW

**Comment by amitranjan2** [comment]
@C-Lodder  could you please review this PR?

**Comment by amitranjan2** [comment]
@C-Lodder is this PR solved your issue?
please kindly review  this

**Comment by brianteeman** [comment]
I have tested this item :red_circle: unsuccessfully on 6cc0a69fddc23f33d8ee4469a2c01a925d136d1d<br /><br />When testing make sure that the menu has more than one menu item<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23844">issues.joomla.org/tracker/joomla-cms/23844</a>.</sub>

**Comment by bahl24** [comment]
I have tested this item :red_circle: unsuccessfully on 6cc0a69fddc23f33d8ee4469a2c01a925d136d1d<br /><br />Mentioned previously at https://github.com/joomla/joomla-cms/pull/24100#issuecomment-469795488<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23844">issues.joomla.org/tracker/joomla-cms/23844</a>.</sub>

**Comment by Quy** [comment]
Closing in favor of #24335.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23844">issues.joomla.org/tracker/joomla-cms/23844</a>.</sub>

**Pull request closed without merging**
