### PR TITLE
Tab state logic fix

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # .
The problem: Many people stated that they experience odd behaviour with the tabs when a page loads (admin area).
### Summary of Changes

The javascript that controlled this behaviour was way to liberal.
So the old behaviour:
- One key-value pair
- As a user is browsing and clicking on tabs these tabs (as their ID) is stored in an array in the key-value of local storage.
- The problem is that the script will loop all this values and set for each one the relative tab as active.

The new logic:
- many key-value pairs
- regular expression removes the `&id=0000` part (could be improved, help is welcome)
- there is a unique key-value pair per view (not per item, e.g. article->edit but not article[123]->edit) 
- should be faster and glitch free
### Testing Instructions

Apply the patch and try any view with tabs

Before:
screen shot 2016-10-22 at 03 18 13

After:
screen shot 2016-10-22 at 03 17 03
### Documentation Changes Required

None

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
Testes dwith success (cannot mark it on the tracker)

Animated gif of the problem and the success test
tabs

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 81d95f0b8334284fc86c9745ab0a94622a3321ed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12503">issues.joomla.org/tracker/joomla-cms/12503</a>.</sub>

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on 81d95f0b8334284fc86c9745ab0a94622a3321ed<br /><br />much better :+1: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12503">issues.joomla.org/tracker/joomla-cms/12503</a>.</sub>

**Comment by zero-24** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12503">issues.joomla.org/tracker/joomla-cms/12503</a>.</sub>

**Comment by dgt41** [comment]
@zero-24 I set this again to pending, because the regular expression I use is matching only `&id=0000` should be more generic like`&anyword=anynumber`, but as I said before regular expressions is not my strong point

**Comment by dgt41** [comment]
screen shot 2016-10-23 at 18 38 46
that should be more generic now

**Comment by zero-24** [comment]
What is the status here? Just re testing?

**Comment by eshiol** [comment]
I tested it and solve the issue #12316.
What do you think to remove the parameter return too.

**Comment by dgt41** [comment]
@zero-24 yes

**Comment by dgt41** [comment]
>  remove the parameter return too

What do you mean? give me an example

**Comment by eshiol** [comment]
You used regular expression to remove &myStrangeId=0000
In the localStorage I found /j364/administrator/index.php?option=com_config&view=component&component=com_patchtester&path=&return=aHR0cDovL2xvY2FsaG9zdC9qMzY0L2FkbWluaXN0cmF0b3IvaW5kZXgucGhwP29wdGlvbj1jb21fcGF0Y2h0ZXN0ZXI%3D
I'd add .replace(/&return=[a-zA-Z0-9%]+$/, '') to remove the parameter return

**Comment by dgt41** [comment]
@eshiol ok, i see what you mean, what about `&[a-zA-Z]+=[a-zA-Z0-9%]+$`, will work both ways?
screen shot 2016-10-30 at 02 51 30
`

**Comment by eshiol** [comment]
I don't think so. The regular expression ends with $, so you process only the last parameter. If you put &view=component at the end of the url it doesn't work anymore. Your regex remove the parameter view.
Please try with .replace(/&[a-zA-Z]+=\d+/, '').replace(/&return=[a-zA-Z0-9%]+/, '')

**Comment by dgt41** [comment]
@eshiol I added your suggestion and also I expanded the other reg ex to include items like `item_id` and `item-id`. So this should be complete now

**Comment by eshiol** [comment]
That ok, but if you use the $ at the end of the regular expression you process only the last parameter. /&[a-zA-Z-_]+=[0-9]+$/ doesn't work with
index.php?option=com_mycomponent&myparam=123&view=myview

**Comment by dgt41** [comment]
@eshiol following the core paradigm all components for their singular view have the id as the last param. Now 3rd PD may not follow that (?) but if I remove that then a url like
`index.php?option=com_dfdsadfad&view=component&catid=33&mynice_id=2342` will eliminate both id and catId, which might not be what we want?
Anyways I am gonna remove it and if it misbehave then we can rework the regex

**Comment by eshiol** [comment]
of course, you are right.
But, what the difference between 
index.php?option=com_dfdsadfad&view=component&catid=33&mynice_id=2342

**Comment by dgt41** [comment]
> But, what the difference between 

Probably the same view and the same tabs, unless some ACL removes access to some tabs and then no tab will be selected )or something like that)

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 41ba14fb6c531002ee5b8b7f56ff62ea3cc62198<br /><br />again<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12503">issues.joomla.org/tracker/joomla-cms/12503</a>.</sub>

**Comment by ggppdk** [comment]
I have tested this item :white_check_mark: successfully on 41ba14fb6c531002ee5b8b7f56ff62ea3cc62198<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12503">issues.joomla.org/tracker/joomla-cms/12503</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12503">issues.joomla.org/tracker/joomla-cms/12503</a>.</sub>

**Pull request merged**
