### PR TITLE
[4.1] spelling goup/group

### PR DESCRIPTION
**Pull request by brianteeman**
code review

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 7cd9fa32e8e0b477194c4b0efb63c1989f1ab27e<br /><br />review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38052">issues.joomla.org/tracker/joomla-cms/38052</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 7cd9fa32e8e0b477194c4b0efb63c1989f1ab27e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38052">issues.joomla.org/tracker/joomla-cms/38052</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38052">issues.joomla.org/tracker/joomla-cms/38052</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
