### PR TITLE
[4.3] Language CLI string

### PR DESCRIPTION
**Pull request by brianteeman**
Fixes obvious error where two strings had the same label

### Before
image

### After
image

@hackwar what is the reason for having identical strings?

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 54ed84f41cc6ba8e2c219018500c80d4b7ab0f90<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39549">issues.joomla.org/tracker/joomla-cms/39549</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 54ed84f41cc6ba8e2c219018500c80d4b7ab0f90<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39549">issues.joomla.org/tracker/joomla-cms/39549</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39549">issues.joomla.org/tracker/joomla-cms/39549</a>.</sub>

**Comment by obuisard** [comment]
Thank you Brian @brianteeman!

**Pull request merged**
