### PR TITLE
Undefined $model variable for postDeleteHook() in delete() method in admin.php - $model in wrong scope

### PR DESCRIPTION
**Pull request by mgilkes**
$model is undefined at line 140 for $this->postDeleteHook($model, $cid);, because $model was instantiated within the scope of the else block. If you try to delete an item from an admin list, you will get a PHP Notice and a PHP Catchable Fatal Error. So, it is better to declare/instantiate the model outside of the else block, within the same scope of the call to postDeleteHook().

### CODE REVIEW

**Comment by wilsonge** [comment]
Is there a reason we should call the post delete hook if there aren't any items deleted? i.e. should we move the hook inside the else?

**Comment by mgilkes** [comment]
That's a good question. Logically, I concur that it would make more sense to move the hook, if we assume that the hook should only be called if the delete was successful. If that is the intended purpose of the hook call, then it should be placed in the if($model->delete($cid)) block, and the $model instantiation placed back in the else block.

**Comment by izharaazmi** [comment]
This was resolved with https://github.com/joomla/joomla-cms/pull/7097. But the approach is little different.  Please see if what suits best – close this or accept this approach.

In case it is needed, my test result for this is:

**Tested successfully.**

**Comment by brianteeman** [comment]
As it was resolved in another PR I am going to close this for now. It can always be re-opened if this approach is to be used instead

**Pull request closed without merging**
