### PR TITLE
[4.x] Allow folders with image extensions in media manager

### PR DESCRIPTION
**Pull request by SniperSister**
### Summary of Changes
Currently the mediamanager will return an error if a folder with an image extension is present in the media directory, as it (unsuccessfully) tries to fetch the image properties of such a directory. This PR fixes the issue.

### Testing Instructions
* Create the directory "text.jpg" in the /images folder
* Open the media manager in the backend

### Actual result BEFORE applying this Pull Request
Error message "The image file does not exist." is shown.

### Expected result AFTER applying this Pull Request
Message is gone, media manager works

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by TLWebdesign** [comment]
I have tested this item :white_check_mark: successfully on dac28cf8b7e319ac9678b625e1894c933d4fa0a3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42874">issues.joomla.org/tracker/joomla-cms/42874</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on dac28cf8b7e319ac9678b625e1894c933d4fa0a3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42874">issues.joomla.org/tracker/joomla-cms/42874</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42874">issues.joomla.org/tracker/joomla-cms/42874</a>.</sub>

**Comment by tomsrocket** [comment]
When Error Reporting is set to maximum in Global Configuration, even with this patch, the media manager is not working at all, because the json produces the Notice: 

Notice: exif_imagetype(): Read of 8192 bytes failed with errno=21 Is a directory in /var/www/html/libraries/src/Helper/MediaHelper.php on line 93 Notice: exif_imagetype(): Error reading from /var/www/html/images/text.jpg! in /var/www/html/libraries/src/Helper/MediaHelper.php on line 93

**Comment by SniperSister** [comment]
@tomsrocket excellent catch! PR has been updated, please retry! @TLWebdesign, can you have a look again too please?

**Comment by SniperSister** [comment]
> my memory says that there was an open issue for this but my search skills fail to find it

Same here. I stumbled upon various issues with non-utf8 filenames, but these are completely different scenarios.

**Comment by richard67** [comment]
@SniperSister @brianteeman Maybe this one #39263 ?

**Comment by TLWebdesign** [comment]
I now get this error when looking at the media manager when error reporting is set to full. 

Property 'mime_type' of argument 'item' of event onFetchMediaItems has a wrong item. Valid: string

**Comment by SniperSister** [comment]
> I now get this error when looking at the media manager when error reporting is set to full.

Yeah, and you know why? Because I'm stupid!

Fixed now too, sorry, my bad!

**Comment by TLWebdesign** [comment]
Oh hahahaha i thought it was because i did something wrong. just reapplied it before reading your comment and it was working. Haha already deleted my comment because i thought i did something wrong haha. 

Its working now.

**Comment by richard67** [comment]
Back to pending. Please test again. Thanks in advance.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42874">issues.joomla.org/tracker/joomla-cms/42874</a>.</sub>

**Comment by TLWebdesign** [comment]
I have tested this item :white_check_mark: successfully on 5ead19239f99da6de3a3aa3506c81e73b6e3ba19<br /><br />Tested the changes and now it works even with error reporting set to maximum.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42874">issues.joomla.org/tracker/joomla-cms/42874</a>.</sub>

**Comment by tomsrocket** [comment]
I have tested this item :white_check_mark: successfully on 5ead19239f99da6de3a3aa3506c81e73b6e3ba19<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42874">issues.joomla.org/tracker/joomla-cms/42874</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42874">issues.joomla.org/tracker/joomla-cms/42874</a>.</sub>

**Comment by Quy** [comment]
> my memory says that there was an open issue for this but my search skills fail to find it

#37692

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
