### PR TITLE
[4.0] Make the checked-out icon visible, fix ordering column

### PR DESCRIPTION
**Pull request by chmst**
### Summary of Changes
This PR makes a lock icon visible if an item is checked-out. Set set of parameters in jgrid is fixed .
It fixes also the ordering column.

### Testing Instructions
Go to the backend - articles overview or another list view.
Open an item for editing, close the browser window.
Open the list view in a new session

### Expected result
The locked item has a symbol "lock", orderring is possible

fixed-lock

### Actual result
The icon is not visible, the ordering column does nothing

missing-lock

### Documentation Changes Required
no

### CODE REVIEW

**Comment by brianteeman** [comment]
wasnt this fixed in your other pr?

**Comment by chmst** [comment]
This is in aonther method. The former PR fixed status icons.

**Comment by brianteeman** [comment]
ah - ok

**Comment by SharkyKZ** [comment]
Assuming HTML in tooltips is still allowed, `html_entity_decode()` should be restored.

**Comment by chmst** [comment]
@SharkyKZ thank you. The change here and the PR https://github.com/joomla/joomla-cms/pull/22424#issuecomment-425397316 at least make the icons visible.
The popovers and toolTips are not in scope of this PR.

**Comment by dgrammatiko** [comment]
> Assuming HTML in tooltips is still allowed, html_entity_decode() should be restored.

Only focusable elements can have tooltips.-

**Comment by brianteeman** [comment]
And this is focusable

**Comment by laoneo** [comment]
Where do we stay here?

**Comment by chmst** [comment]
Closing this. See https://github.com/joomla/joomla-cms/commit/087a498d966dc3f735bc836a6d7c0cd755198630#diff-b6e58f62ccdeb3628e95895228bd2e91

**Pull request closed without merging**
