### PR TITLE
B/C Admin menus: Re-using the existing language string to display the Official Languages Forum submenu

### PR DESCRIPTION
**Pull request by infograf768**
Pull Request for Issue https://github.com/joomla/joomla-cms/pull/17836#issuecomment-326808873

### Summary of Changes
Deleting a wrongly added string.
Modifying code to use the existing one in Language packs pre-3.8.0 betas

### Testing Instructions
Install French Language.
Switch backend to French.
You will have
screen shot 2017-09-02 at 11 59 31

Clicking on "Forum officiel français" will load directly the French Official Forum
screen shot 2017-09-04 at 08 55 23

switch back to English
You will have

screen shot 2017-09-02 at 11 58 10

Clicking on "Official Language Forum" will load the Languages forum section (International Zone)
screen shot 2017-09-04 at 08 53 45

@wojsmol 
@izharaazmi 

Thank you for confirming test

### CODE REVIEW

**Comment by roland-d** [comment]
I have tested this item :white_check_mark: successfully on f3496a34f03b861f2d854b7fc1dce929fb2b68d0<br /><br />The link to the official forum would send me to the forum index page. After applying the patch I was taken to the language specific forum. I have tested this with both French and German.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17857">issues.joomla.org/tracker/joomla-cms/17857</a>.</sub>

**Comment by gwsdesk** [comment]
Confirm Rolands results. I have tested this item ✅ successfully on [f3496a3](https://github.com/joomla/joomla-cms/commit/f3496a34f03b861f2d854b7fc1dce929fb2b68d0 "f3498a") Tested with French and Dutch ;-)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17857">issues.joomla.org/tracker/joomla-cms/17857</a>.</sub>

**Comment by gwsdesk** [comment]
I have tested this item :white_check_mark: successfully on f3496a34f03b861f2d854b7fc1dce929fb2b68d0<br /><br />works as expected<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17857">issues.joomla.org/tracker/joomla-cms/17857</a>.</sub>

**Comment by ghost** [comment]
RTC after two successful tests.

**Comment by infograf768** [comment]
@mbabker 
Please merge before RC as we are going to freeze langs

**Comment by wojsmol** [comment]
I have tested this item :white_check_mark: successfully on f3496a34f03b861f2d854b7fc1dce929fb2b68d0<br /><br />staging at https://github.com/joomla/joomla-cms/commit/6afc3a44c2cb50a60fa345838e63f1bf7135e2ae<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17857">issues.joomla.org/tracker/joomla-cms/17857</a>.</sub>

**Comment by wilsonge** [comment]
Thanks JM!

**Pull request merged**
