### PR TITLE
[4.0] Fix: Associations tab should display only one Notice when item edited is set to ALL languages

### PR DESCRIPTION
**Pull request by infograf768**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/20575
**Replaces https://github.com/joomla/joomla-cms/pull/21281**

### Summary of Changes
Modified js to get a unique Notice.

### Testing Instructions
Create a multingual site with 3 languages.
Create a contact (or any item) with language set to ALL.
save (NOT save and close)
Display the associations tab

### Before patch
screen shot 2018-08-02 at 15 57 35

### After patch
screen shot 2018-08-02 at 15 52 46

@franz-wohlkoenig
@jreys 
@dgrammatiko 

Note : I choose contact instead of article or category as their display is broken for now in 4.0.
As second level sub menus are also broken, one way to display the contact manager is to first display administrator/index.php?option=com_cpanel&view=system
then choose Global Configuration
Then Choose Contacts on the left sidebar. You get to Contact: Options.
Cancel
There you are. Create a new contact with language set to ALL (it will be per default)
test before and after patch.

### CODE REVIEW

**Comment by infograf768** [comment]
NOTE for people testing such PR.
If you do not use a local git repo and do not run composer install and npm install, ~~fetch nightly build and Install patchtester.~~

EDIT: can't use patchtester for that kind of PR...

**Review by dgrammatiko — APPROVED** [review]

**Comment by dgrammatiko** [comment]
Patchtester cannot be used here to test this pr :(

**Comment by infograf768** [comment]
Oh.
Then let's merge it.
@laoneo 
@wilsonge

**Comment by wojsmol** [comment]
@dgrammatiko is right - at leasts node.js is required.

**Comment by ghost** [comment]
~~I have tested this item :red_circle: unsuccessfully on dc9f0f8c4a95cc4b178325f5881ab224728718b0~~<br /><br />~~Using Patch get same count of Notices as without Patch.~~<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21362">issues.joomla.org/tracker/joomla-cms/21362</a>.</sub>

**Comment by ghost** [comment]
I have not tested this item.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21362">issues.joomla.org/tracker/joomla-cms/21362</a>.</sub>

**Comment by infograf768** [comment]
@franz-wohlkoenig 

Indeed you can't test as the min.js and .js have to get in via using node.
Basically the new files which are used are in the media folder after this PR is merged and node is used to create the new files.
This is going to be a real issue...

**Comment by ghost** [comment]
@infograf768 this is not a Problem as i can revert the Test. But it would save Time if PR-Dev. write "not testable in Patchtester".

**Comment by wojsmol** [comment]
@franz-wohlkoenig are you using glip? If yes I will try to help you with node.js and composer installation.

**Comment by dgrammatiko** [comment]
> This is going to be a real issue...

Then let's find someone with some spare time to publish this: https://github.com/joomla-projects/gsoc17_pr_testing_platform

**Comment by mbabker** [comment]
To be clear, patch tester has always been a convenience tool.  It was never designed to be the official patch testing mechanism, and can never be because to properly apply and rollback patches requires data not available within a regular CMS install (and if you do have that data available the odds are you don't need patch tester to begin with).

Truth be told, I'm pretty close to just breaking 4.0 compatibility within it.  Because 4.0 is a moving target and with the changes made this week essentially the component is useless on that version.

I will make time this weekend to work out an issue tracker level integration where you can download a packaged Joomla build for testing a pull request since it seems getting the PR testing platform to a usable state has stagnated.

**Comment by ghost** [comment]
@wojsmol i'm using Glip and thanks for your Offer. But its no Problem if i can't test an PR, most of them (so far) i can test using Patchtester.

**Comment by brianteeman** [comment]
@mbabker is this the "testing platform" you are referring to https://github.com/joomla-projects/gsoc17_pr_testing_platform ? If so it's not been touched for a year

**Comment by mbabker** [comment]
Yep.  A couple months ago the team was given the keys to a server to get that set up on our hosting architecture for use, that's the last update I have on things.

**Comment by wojsmol** [comment]
@franz-wohlkoenig  Just wrote and I  will give you  my invitation link. :)

**Comment by infograf768** [comment]
> @infograf768 this is not a Problem as i can revert the Test. But it would save Time if PR-Dev. write "not testable in Patchtester".

I will definitely do that for any future PR.

**Comment by rdeutz** [comment]
I kow most people don't like the command line but here is an option to test such a PR, we have a docker container we are using in our testing environment to install dependencies. You can use this one (when you have docker installed on your computer) to setup a testing environment. You still need a local webserver and a Database.

**Start the container**

docker run -it --rm -v $(pwd):/opt -w /opt joomlaprojects/docker-tools bash

**Any command you execute from now on is runnig in the container**

git clone --single-branch -b 4.0-dev https://github.com/joomla/joomla-cms.git
cd joomla-cms
composer install
npm i

**Now you have a actual joomla-4.0 dev version of joomla with all files you need**

**Next step is to get the PR Data**
git fetch origin pull/21362/head:local_pr_21362

**and update all files**
npm run update

**Done you can now start testing (after you installed Joomla!)**

ctrl + c to exit the container but you can also let it run, you might will update or test a different PR

**Comment by wojsmol** [comment]
@franz-wohlkoenig If :+1:  mean you wont the link then here it is https://glip.com/invite/c7ad743 - this is from my private glip outside joomla.org teams

**Comment by brianteeman** [comment]
@rdeutz as an option for people who don't like the cli that's probably a more scarey solution than we currently have :)

**Comment by ghost** [comment]
@wojsmol Link open "Bug Squad Public Discussion". 👍 means Thank for your Offer, but Patchtester (or similar) is my Level.

**Comment by rdeutz** [comment]
its just an option, I think it is far easier as install git, php and node locally

**Comment by wojsmol** [comment]
@rdeutz for example @franz-wohlkoenig AFAIK have local server then only node and composer bare missing on his Mac. The have is true for me on Windows but I have already installed missing thing.

**Comment by rdeutz** [comment]
as I said it is an option, I am not pushing people to one or another

**Comment by infograf768** [comment]
@wojsmol 
As you know your npm, can you test this PR?
I know it works, but it really would be good to merge it now.

**Comment by wojsmol** [comment]
@infograf768  If you don't have issue fact that I must apply the additionally PR https://github.com/joomla/joomla-cms/pull/21371.

**Comment by infograf768** [comment]
I do not have here the issue you describe in https://github.com/joomla/joomla-cms/pull/21371

**Comment by wojsmol** [comment]
This iS reproachable at lest on Windows and Firefox 61.0.1 (64 bits).

**Comment by ghost** [comment]
~~I have tested this item :red_circle: unsuccessfully on dc9f0f8c4a95cc4b178325f5881ab224728718b0~~<br /><br />~~Using Patch get same count of Notices as without Patch.~~

Please ignore Test as for now Front- and Backend-PRs are able to test by Patchtester.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21362">issues.joomla.org/tracker/joomla-cms/21362</a>.</sub>

**Comment by ghost** [comment]
I have not tested this item.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21362">issues.joomla.org/tracker/joomla-cms/21362</a>.</sub>

**Comment by infograf768** [comment]
For the people who do not use npm, here are the 2 files created by npm  for this PR so you can test.

they should replace their equivalent in media/com_associations/js/

[associations-edit.js.zip](https://github.com/joomla/joomla-cms/files/2257622/associations-edit.js.zip)

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on dc9f0f8c4a95cc4b178325f5881ab224728718b0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21362">issues.joomla.org/tracker/joomla-cms/21362</a>.</sub>

**Comment by wilsonge** [comment]
Thanks JM!

**Pull request merged**
