### PR TITLE
[5.1] Replace deprecated KeyboardEvent code

### PR DESCRIPTION
**Pull request by C-Lodder**
## Summary of Changes

Both the `keypress` event and `keyCode` property are deprecated in Javascript. This PR replaces them accordingly.

### Calendar:
Open a calendar and ensure:
1. <kbd>Shift</kbd> + <kbd>Space</kbd> appends the date to the input.
2. <kbd>ESC</kbd> closes the calendar.
3. <kbd>Tab</kbd> closes the calendar.
4. The arrow keys (<kbd>↑</kbd>, <kbd>↓</kbd>, <kbd>→</kbd>, <kbd>←</kbd>) navigate through the calendar accordingly.
5. Repeat step 4 in RTL mode.

### Web Install:
1. Go to `administrator/index.php?option=com_installer&view=install`, then navigate to the "Install from Web" tab.
2. Enter a phrase in the "Search" field.
3. Press <kbd>Enter</kbd>.
4. The search should be initiated.

@dgrammatiko I removed the following conditional statement:
```
if (ev.target === this.inputField && !(K>48 || K<57 || K===186 || K===189 || K===190 || K===32)) {
  return stopCalEvent(ev);
}
```
because I could not meet the condition, and using `K > 48 || K < 57` makes no sense. It's possible that this was a mistake but the code doesn't contain any comments, sol....

### CODE REVIEW

**Comment by Fedik** [comment]
Please use [event.code](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/code) instead of [event.key,](https://developer.mozilla.org/en-US/docs/Web/API/KeyboardEvent/key) because the `key` is altered by keyboard locale and layout. And `code` always represents a physical key on the keyboard.

**Comment by dgrammatiko** [comment]
> It's possible that this was a mistake but the code doesn't contain any comments

the conditional is basically a way to ignore keys other than the ones actually used by the calendar but not sure if there’s a need for it. This is code from the early 2000’s so who knows anymore…

**Comment by C-Lodder** [comment]
@Fedik Oops, done

**Comment by Quy** [comment]
In RTL, the left key moves to the right and right key moves to the left.  Not sure if this is the correct behavior as this is not the case without this PR.

**Comment by C-Lodder** [comment]
@Quy Fixed RTL. Thanks for testing

**Comment by Fedik** [comment]
@Quy are you sure? 
To me, it sounds very strange, but I cannot really check, or find any info about it.
The codes represents a physical keys on keyboard, With physical direction Up/Down/Lft/Rgt which should not changes, no matter what.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 06255066d42dfee912e6c217f0f144d79dff5ee4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42715">issues.joomla.org/tracker/joomla-cms/42715</a>.</sub>

**Comment by Quy** [comment]
@Fedik I was pointing out that this PR did the opposite for left/right keys which has been fixed since.

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 06255066d42dfee912e6c217f0f144d79dff5ee4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42715">issues.joomla.org/tracker/joomla-cms/42715</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42715">issues.joomla.org/tracker/joomla-cms/42715</a>.</sub>

**Comment by LadySolveig** [comment]
Thank you @C-Lodder and also for testing, support and review @dgrammatiko @Fedik @Quy @viocassel

**Pull request merged**
