### PR TITLE
[4.0] Site Contacts Category List Search Filters

### PR DESCRIPTION
**Pull request by infograf768**
### Summary of Changes
Adding Search Filter and Clear buttons to the `List Contacts in a Category` menu item.
Modify the placeholder string to specify the search is limited to the Contact Title.

### Testing Instructions
Create multiple contacts in the same category.
Create a `List Contacts in a Category` menu item for this category.
Make sure Filter Field is set to `Show` in the menu parameters.
Display the menu item in frontend.

### Actual result BEFORE applying this Pull Request

Screen Shot 2020-09-30 at 12 53 06

### Expected result AFTER applying this Pull Request
contact-search

### Note
1. With a similar PR, we can add a Clear filter button in the `List Articles in a Category` menu item
2. It would be nice to add css for the Clear button in order to display a different color when the filter field is empty and not. I guess this would be for the Cassiopea Team to deal with.

### CODE REVIEW

**Comment by brianteeman** [comment]
Thanks for that last change to use sr-only - I was about to comment and got distracted

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 9da66d3fd14192093437fd1832aaac30bf6fd08f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30813">issues.joomla.org/tracker/joomla-cms/30813</a>.</sub>

**Comment by infograf768** [comment]
Note:
1.
> Thanks for that last change to use sr-only - I was about to comment and got distracted

We will need to do the same for articles list. Will modify that in the new PR if this PR is accepted and merged.

2. We have to be able to modify the number of items displayed in the list by using the limit box.
It is impossible right now because the code forces $limit value to the parameters set in contact Options and the menu item, contrary to articles.
I have a patch for that. Will propose later.

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 9da66d3fd14192093437fd1832aaac30bf6fd08f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30813">issues.joomla.org/tracker/joomla-cms/30813</a>.</sub>

**Comment by jwaisner** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30813">issues.joomla.org/tracker/joomla-cms/30813</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by infograf768** [comment]
Concerning the list limit issue, please test https://github.com/joomla/joomla-cms/pull/30904

**Pull request merged**
