### PR TITLE
[4.0] Changed siteDescription field to siteTagline

### PR DESCRIPTION
**Pull request by BrainforgeUK**
Pull Request for Issue #34953  .

### Summary of Changes

Changed field name **siteDescription** to **siteTagline**
Changed CSS c;lass **site-description** to **site-tagline**

### Testing Instructions

Changing tagline of template style in back-end style editor will change the tagline in front-end.

### Actual result BEFORE applying this Pull Request

The tagname changes on the front-end.

### Expected result AFTER applying this Pull Request

The tagname changes on the front-end, as before.
CSS class **site-tagline** can be used to change the appearance of the tagline

### CODE REVIEW

**Comment by brianteeman** [comment]
I still do not understand the reason behind this change, its not for consistency so why? Please enlighten me. What am I missing.

**Comment by brianteeman** [comment]
Note that this PR is incomplete as there are sql changes that need to be made as well both for new installs and upgrades.

**Comment by BrainforgeUK** [comment]
Consistency - change applies only within the Cassiopeia template.

SQL changes
(1) Cannot see any need for such on new installs.
(2) For production site upgrades would need and to change the field name in the params column of the template styles table. - as J4 is still at RC stage ...

**Comment by brianteeman** [comment]
Consistency with what?

as a clean install sets a param with the existing fieldname then of course it needs to be changed

**Comment by BrainforgeUK** [comment]
Reopened.

**Comment by chmst** [comment]
@BrainforgeUK could you please resolve the conflicts?

**Comment by HLeithner** [comment]
This pull request has automatically rebased to 4.2-dev.

**Comment by drmenzelit** [comment]
Sorry that it took so long to make a decision, but we can't accept this PR, it implicates too many conflicts for existent websites using Cassiopeia and /or child templates.

**Pull request closed without merging**
