### PR TITLE
Repair slider view and add tab view for Beez template

### PR DESCRIPTION
**Pull request by n9iels**
This PR is the solution for issue #7662 
## What this PR does

This PR repair the slider display for com_contact in the beez template, and adds the tab display. I used `JHtml` instead of hard coded sliders.
I also changed a wrong placed language string in default_links.php
## How to test this PR

1) Create a menu item of the type "Single contact" and make sure all information of this contact will be shown
2) Set "Beez3" as default template
3) In the options of com_contact set the parameter "Display Format" to the option: Sliders
4) Confirm all sliders are displayed correctly, like this:
knipsel

4) In the options of com_contact set the parameter "Display Format" to the option: Tabs
5) Confirm all tabs are displayed correctly, like this:
knipsel

5) In the options of com_contact set the parameter "Display Format" to the option: Plain
6) Confirm all information is displayed under each other, with the good headings

### CODE REVIEW

**Comment by webberry** [comment]
I have tested this item :white_check_mark: successfully on 701df930c63a5af2c4519c27f317c6c367eb3e1e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8068">issues.joomla.org/joomla-cms/8068</a>.</sub>

**Comment by waader** [comment]
@test successful, thanks!

**Comment by SniperSister** [comment]
2 successful tests, setting RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8068">issues.joomla.org/joomla-cms/8068</a>.</sub>

**Comment by Kubik-Rubik** [comment]
Thank you @n9iels! Merged.

**Pull request merged**
