### PR TITLE
Messages inside the new Joomla 3.6 updater / max post size 8mb

### PR DESCRIPTION
**Pull request by zero-24**
Pull Request for Issue #10604 
#### Summary of Changes

change extensions to packages
#### Testing Instructions
- set maximum post size to less than 8MB
- see the message in the updater
- see the message in the extension manger

similiar to https://github.com/joomla/joomla-cms/pull/10707 Thanks @brianteeman

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on c9966c405d5dafe8ca6312023964cbf00740453b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10708">issues.joomla.org/joomla-cms/10708</a>.</sub>

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on c9966c405d5dafe8ca6312023964cbf00740453b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10708">issues.joomla.org/joomla-cms/10708</a>.</sub>

**Comment by zero-24** [comment]
RTC Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10708">issues.joomla.org/joomla-cms/10708</a>.</sub>

**Comment by zero-24** [comment]
Thanks :smile:

**Comment by wilsonge** [comment]
Thankyou!

**Pull request merged**
