### PR TITLE
Joomla cubrid

### PR DESCRIPTION
**Pull request by beyondykk9**
Pull Request for Issue # .

### Summary of Changes
A new database driver is added for CUBRID (is a open source DBMS)
The most of added driver is for qualified name of keyword columns using on SQL.

### Testing Instructions
Successful Installation

### Expected result
Successful sample data operation.

### Actual result
Successful sample data operation.

### Documentation Changes Required
Documents for database has to be updated for a new CUBRID driver.

### CODE REVIEW

**Comment by brianteeman** [comment]
We use quote and quotename and not the shortcuts q and qn

**Comment by brianteeman** [comment]
Having looked closely into what cubrid is I am not convinced that it is something we support. We are already dropping support of mssql due to the lack of users and available testing etc. Do we really think we can support another even more obscure db .

@byungwook-kim convince us

**Comment by beyondykk9** [comment]
I don't know the reason for the following error in processing CI-Appveyor/PR
It occurs on only PHP 7.1.9 not any PHP 5 or PHP 7 version.

1) JCacheStorageCacheliteTest::testCacheTimeout
[00:03:03] Some data should be available in lifetime.
[00:03:03] Failed asserting that false matches expected 'testData'.
[00:03:03] 
[00:03:03] C:\projects\joomla-cms\tests\unit\core\case\cache.php:121
[00:03:03] C:\projects\joomla-cms\tests\unit\suites\libraries\joomla\cache\storage\JCacheStorageCacheliteTest.php:67
[00:03:03] 
[00:03:03] FAILURES!

**Comment by brianteeman** [comment]
Thank you for this PR. As I stated before I really dont think this is something we can accept as it will not be maintainable by anyone else as no one is using this database

**Comment by HLeithner** [comment]
@byungwook-kim This is any really interesting PR, but as brain already mentioned its not so easy to get a new database driver in to Joomla. Especially not in a minor version while we are trying to get the next major version out of the door. 

Also the correct place for the database driver is at https://github.com/joomla-framework/database 

Anyway I would like to ask @mbabker and @wilsonge about there opinion on a way getting 3rd party database driver working with Joomla.

**Pull request closed without merging**
