### PR TITLE
[4.0] Add missing asset_id column in sample testing

### PR DESCRIPTION
**Pull request by csthomas**
### Summary of Changes
Every module row should have `asset_id` value if  the appropriate value exists in `#__assets` table.

Adds the missing `asset_id` column in the insertion query and fills IDs from the `#__ assets` table.

### Testing Instructions
Install joomla 4 with sample testing data. Installation works.

### CODE REVIEW

**Comment by laoneo** [comment]
@Bakual and @infograf768 are you guys ok with this change?

**Comment by infograf768** [comment]
I am a bit confused here.
I thought that there would be no more sample data to install at installation time in J4 (testing or else) and that only the sample data module would be used from the CPanel (for blog and multilang).

**Comment by csthomas** [comment]
> I thought that there would be no more sample data to install at installation time in J4

I thought so too, but sql files (sample_testing.sql) are still here and are constantly being updated, so I'm doing the same.
Until they are removed they should be updated.

**Comment by infograf768** [comment]
Then I guess this PR is necessary. Not really understanding why I am asked my advice. 😄

**Comment by Bakual** [comment]
They still should be removed for 4.0. So this PR is lost work in the end.
But I don't mind what you guys do with your time 😄

**Comment by csthomas** [comment]
Then I will close it.

It would be good to know that testers should not use this sample on testing PRs.

**Comment by infograf768** [comment]
Well, I guess that 4.0 Production leaders had a reason to leave these files in.
Therefore I would wait for @wilsonge to decide.

**Comment by wilsonge** [comment]
Basically from core perspective they are going to get removed. However there's been issues flagged by several template companies about going down the plugin approach. So I'm leaving these files here as a placeholder whilst I try and figure out how to best accomodate everybody (for example potentially if there is an installation sql file automatically installing it (where core won't have one by default) or something related)

**Comment by csthomas** [comment]
OK, this PR is simple, I added only one column to the insert query. 

I would like to close this task, the result is not important. Please merge it or close it.

**Comment by mbabker** [comment]
> However there's been issues flagged by several template companies about going down the plugin approach.

There is already support for a [supplemental SQL file](https://github.com/joomla/joomla-cms/blob/629a20a83f3a845cc1b486bfe40e547d82231035/installation/src/Model/DatabaseModel.php#L668-L677) in the install app without hooking into either existing convention for sample data installation.  What more is needed?

**Comment by wilsonge** [comment]
> There is already support for a supplemental SQL file in the install app without hooking into either existing convention for sample data installation. What more is needed?

Nothing. That's the first I knew of this feature.

**Comment by csthomas** [comment]
I understand that this PR is not needed.

**Pull request closed without merging**
