### PR TITLE
[4.1] remove underline on buttons etc

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #34936

This is a css change so you will need to test with either a pre-built package or by `npm run build:css`

We already remove the underline on links for badges in tables. This extends that to dropdown items and buttons.

To test go to com_users and create a note for a user.

## Before
image

## After
image

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on f9ce588efcfe213066d5685d91a399b59905e098<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36947">issues.joomla.org/tracker/joomla-cms/36947</a>.</sub>

**Comment by Kostelano** [comment]
I have tested this item :white_check_mark: successfully on f9ce588efcfe213066d5685d91a399b59905e098<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36947">issues.joomla.org/tracker/joomla-cms/36947</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36947">issues.joomla.org/tracker/joomla-cms/36947</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
