### PR TITLE
[3.10] Fix open_basedir warning when creating a menu item

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue #36788 and #35895 .

### Summary of Changes

Correctly check path

### Testing Instructions

Follow  #36788 and #35895 

### Actual result BEFORE applying this Pull Request
A warning about open_basedir stuff

### Expected result AFTER applying this Pull Request
No warning

### Documentation Changes Required
None

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 729f382fa73955efa4aa84d99a0c451ea409a93f<br /><br />J 3.10.5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36789">issues.joomla.org/tracker/joomla-cms/36789</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 729f382fa73955efa4aa84d99a0c451ea409a93f<br /><br />Tested on a copy of my homepage on my domain, where I have and always had open_basedir restrictions.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36789">issues.joomla.org/tracker/joomla-cms/36789</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36789">issues.joomla.org/tracker/joomla-cms/36789</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36789">issues.joomla.org/tracker/joomla-cms/36789</a>.</sub>

**Comment by zero-24** [comment]
Hmm that method is setup far from ideal as it depends on cases and not in all cases the variables are setup correctly. For example this issue here comes only up when the "option" == component can not be found. When that has been found it will fallback to the component root. But this patch here is right as we can not try to fallback to the component root when we do not have any information about it :)

Thanks

**Comment by silverislander** [comment]
I have tested this item :white_check_mark: successfully on 729f382fa73955efa4aa84d99a0c451ea409a93f<br /><br />Tested successfully on a client website (managed hosting).

J 3.10.5 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36789">issues.joomla.org/tracker/joomla-cms/36789</a>.</sub>

**Comment by TLWebdesign** [comment]
I have tested this item :white_check_mark: successfully on 729f382fa73955efa4aa84d99a0c451ea409a93f<br /><br />Tested this PR on 3.10 and can confirm this fixed the warning. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36789">issues.joomla.org/tracker/joomla-cms/36789</a>.</sub>

**Pull request merged**
