### PR TITLE
Fix SVG upload

### PR DESCRIPTION
**Pull request by bembelimen**
Pull Request for Issue #37439 .

### Summary of Changes
- Invalid SVG files with broken structure
- Allows comments in SVG files

### Testing Instructions
Allow svg in the media manager options (mime: image/svg+xml, extension: svg).
Take the file package from @brianteeman  https://github.com/joomla/joomla-cms/issues/37439#issuecomment-1110814263 and try uploading the files.

### Actual result BEFORE applying this Pull Request
bad1.svg + bad3.svg is uploaded (both should be blocked), bad2.svg (false positive) + bad4.svg is rejected

### Expected result AFTER applying this Pull Request
only "bad2.svg" is uploaded all other files are rejected

@woluweb could you test please?

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 7d05411dff57dd42c1a1b5becce5a125ee41147c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37703">issues.joomla.org/tracker/joomla-cms/37703</a>.</sub>

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on 7d05411dff57dd42c1a1b5becce5a125ee41147c<br /><br />Tested successfully in Joomla 4.1.3-dev of 30 April in Wampserver 3.2.8 using PHP 8.0.15<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37703">issues.joomla.org/tracker/joomla-cms/37703</a>.</sub>

**Comment by chmst** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37703">issues.joomla.org/tracker/joomla-cms/37703</a>.</sub>

**Comment by akshitrattan** [comment]
I have tested this item :white_check_mark: successfully on 0816b10a72eee0720afa7e0846821a66ba87737b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37703">issues.joomla.org/tracker/joomla-cms/37703</a>.</sub>

**Comment by bembelimen** [comment]
Thx for testing

**Pull request merged**
