### PR TITLE
[TinyMCE] Remove redundant words (label) in description

### PR DESCRIPTION
**Pull request by Quy**
### Testing Instructions
Go under Extensions > Plugins
Search `Editor - TinyMCE`
Edit
Hover mouse over `Save Warning` label

### Expected Results
tinymce-after

### Actual Results
tinymce-before

### Summary of Changes
No need to repeat the words from the label in the description.

### CODE REVIEW

**Review by brianteeman — APPROVED** [review]

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 2bb8bcda3f1c13342808be45e7baa2d3c88528f4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15413">issues.joomla.org/tracker/joomla-cms/15413</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 2bb8bcda3f1c13342808be45e7baa2d3c88528f4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15413">issues.joomla.org/tracker/joomla-cms/15413</a>.</sub>

**Comment by infograf768** [comment]
RC. Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15413">issues.joomla.org/tracker/joomla-cms/15413</a>.</sub>

**Comment by infograf768** [comment]
no idea why language change label dispeared

**Pull request merged**
