### PR TITLE
Problem with JDatabaseQuery __toString

### PR DESCRIPTION
**Pull request by fruppel**
There is an issues with the __toString method of the class JDatabaseQuery.

unionAll did not work as expected, ie the string you entered into the unionAll method was never appended to the SQL query
## Steps to reproduce the issue

```
$db = JFactory::getDbo();
$query = $db->getQuery(true);

echo $query
    ->select('*')
    ->from('#__table_1')
    ->unionAll(
        $db->getQuery(true)
        ->select('*')
        ->from('#__table_2')
    );
```
## Expected result

The code above should output "SELECT \* FROM #__table_1 UNION ALL ( SELECT \* FROM #__table_2)". 
## Actual result

At the moment the output is "SELECT \* FROM #__table_1".
## Additional comments

~~This PR also fixes a problem with the ordering of UNION and ORDER BY. You can see how to reproduce and test it here: #6789.~~

### CODE REVIEW

**Comment by fruppel** [comment]
It does not seem to be a problem with the tests, but rather with my file. Travis keeps telling me

    FILE: ...home/travis/build/joomla/joomla-cms/libraries/joomla/database/query.php
    --------------------------------------------------------------------------------
    FOUND 2 ERROR(S) AFFECTING 2 LINE(S)
    --------------------------------------------------------------------------------
    382 | ERROR | Whitespace found at end of line
    387 | ERROR | Whitespace found at end of line

I can't find any whitespaces at these lines. 
I edited the file completely on Github, may this be the problem? Sorry - it's my first PR. Any help would be appreciated.

**Comment by zero-24** [comment]
@fruppel i have just send you a PR to fix the whitespaces :smile:

**Comment by fruppel** [comment]
Thank you @zero-24 :+1: 
I think I found the problem with the whitespaces. The Github editor adds tabs on each new (empty) line which I have to remove next time.

**Comment by zero-24** [comment]
>I think I found the problem with the whitespaces. The Github editor adds tabs on each new (empty) line which I have to remove next time.

Exact :smile:

**Comment by fruppel** [comment]
Changed the order of "ORDER" and "UNION/UNION ALL" to fix #6789

**Comment by locii** [comment]
Confirmed that this pull requests fixes the related issue in #6789.

**Comment by sovainfo** [comment]
Object to applying order to the set. See https://github.com/joomla/joomla-cms/pull/3565

**Comment by fruppel** [comment]
@sovainfo ok I understand the problem. I reverted my last commit

**Comment by RonakParmar** [comment]
I have tested this item :red_circle: unsuccessfully on 8d6bb9fe3dd0b41cb8204787d53454af89577fab<br /><br />Still not fix for #6789.

Already fixed in #4127 PR.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6693">issues.joomla.org/joomla-cms/6693</a>.</sub>

**Comment by csthomas** [comment]
Can we close it as it is fixed at https://github.com/joomla/joomla-cms/pull/10817

**Comment by roland-d** [comment]
Closed in favor of #10817<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/6693">issues.joomla.org/tracker/joomla-cms/6693</a>.</sub>

**Pull request closed without merging**
