### PR TITLE
[installation] Auto-add language associations on multilanguage install

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Summary of Changes

This PR makes installation process auto create the language associations between the items (menu items, categories and articles) when installing a multilanguage site.
#### Testing Instructions
1. Download https://github.com/andrepereiradasilva/joomla-cms/archive/associations-on-install.zip (staging + this PR)
2. Make a new install with this package
   - In the sample data install step, select `None (Required for basic native multilingual site creation)` 
   - Install two or more languages
   - Select to install sample multilingual content
3. After install, login to backend and check menu items, categories and articles now have the language associations.

image

### CODE REVIEW

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 535bf190d5baf36ae580ffa5cd5047dbb7a84c82<br /><br />Works fine, although associating home pages menu items is not really necessary as these are associated by default without being recorded in the _associations table.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11254">issues.joomla.org/joomla-cms/11254</a>.</sub>

**Comment by dgt41** [comment]
@andrepereiradasilva another great improvement! 👍
> In the sample data install step, select None (Required for basic native multilingual site creation)

The process is rather counter intuitive from UX perspective. I would suggest to move the sample install data after the multilingual step (maybe a simple yes/no button will reveal the option in the case of mono and hide it till the languages are selected.

**Comment by infograf768** [comment]
@dgt41
This would require an important refactoring.
This PR is just for adding associations in the data installed in multingual for the user to understand the process.

**Comment by bertmert** [comment]
I have tested this item :white_check_mark: successfully on 535bf190d5baf36ae580ffa5cd5047dbb7a84c82<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11254">issues.joomla.org/joomla-cms/11254</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11254">issues.joomla.org/joomla-cms/11254</a>.</sub>

**Comment by andrepereiradasilva** [comment]
grrr conflicts because of 4 line spaces... will fix ...

**Comment by andrepereiradasilva** [comment]
ok conflicts fixed.
IMO no need to retest or remove the RTC

**Comment by infograf768** [comment]
@wilsonge please revert this and change milestone to 3.6.2

**Comment by brianteeman** [comment]
Why?

**Comment by infograf768** [comment]
because of new necessary lang string
#11263

**Comment by wilsonge** [comment]
Rather than revert I've done a very tacky fix of making it a generic error string (see https://github.com/joomla/joomla-cms/commit/e83f4685239cd46f9a62be7dd8bd477a4b97e446) and we will ensure #11263 is merged for 3.6.2

**Comment by infograf768** [comment]
OK. 👍

**Pull request merged**
