### PR TITLE
[4.2] Replace some static Factory calls with current app access

### PR DESCRIPTION
**Pull request by laoneo**
### Summary of Changes
Replace some static Factory application access with the current app.

### Testing Instructions
- Open the article form in the back end
- Set a title
- Save the article

### Actual result BEFORE applying this Pull Request
All works.

### Expected result AFTER applying this Pull Request
All works.

### CODE REVIEW

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on b04a922413811784a893022bc0c2a9fe9b2da51b<br /><br />Tested successfully in Joomla 4.2.0-beta1-dev of 9 June using Wampserver 3.2.9 and PHP 8.0.15<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38012">issues.joomla.org/tracker/joomla-cms/38012</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on a1ff4a84512715b04077e661a35e6701372e4eff<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38012">issues.joomla.org/tracker/joomla-cms/38012</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38012">issues.joomla.org/tracker/joomla-cms/38012</a>.</sub>

**Comment by roland-d** [comment]
@laoneo Can you check this PR, drone keeps failing.

**Comment by richard67** [comment]
Restarted drone to see if it helps because the screenshots from the failed tests have now shown anything related.

**Comment by richard67** [comment]
Seems it helped 😄

**Comment by laoneo** [comment]
I have that once in a while that drone fails on install with an empty form

**Comment by roland-d** [comment]
Thanks everybody

**Pull request merged**
