### PR TITLE
[5.1] Convert mod_sampledata to service provider

### PR DESCRIPTION
**Pull request by joomlaweby**
### Summary of Changes

Converts the sample data administrator module to service provider.

### Testing Instructions

1. Make sure you have administrator module mod_sampledata published
2. You should see module output

mod_sampledata

### Actual result BEFORE applying this Pull Request

Module works as expected

### Expected result AFTER applying this Pull Request

Module works same way as before applying pull request

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by fgsw** [comment]
How to get 'Testing Sampe Data'?

Default installation (cloudaccess) only 2 plugins:

image

**Comment by joomlaweby** [comment]
> How to get 'Testing Sampe Data'?
> 
> Default installation (cloudaccess) only 2 plugins:
> 
> image

@fgsw I suppose Testing sample data plugin is available only when Joomla installation is done from cloned github repository, but not from released package. Probably this line is removing it during build : https://github.com/joomla/joomla-cms/blob/7c6e2ca43d8d176c0a727dcd69a90b60a496e3c2/build/build.php#L151

**Comment by brianteeman** [comment]
No you are confused.

mod_sampledata is shipped with every release of Joomla. 

There are three plugins that are displayed in the module
1. Blog
2. Multilingual
3. Testing

Of these three it is the third one (testing) that is not shipped with released versions of Joomla. The other two are always shipped with Joomla and enabled by default with the module which displays them on the home page of the admin

**Comment by fgsw** [comment]
I have tested this item :white_check_mark: successfully on 1ead3d673fa928148c8537dfa692dab30582006f<br /><br />Thanks for explanations.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42866">issues.joomla.org/tracker/joomla-cms/42866</a>.</sub>

**Comment by crommie** [comment]
I have tested this item :white_check_mark: successfully on 1ead3d673fa928148c8537dfa692dab30582006f<br /><br />Module output shown before as well as after.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42866">issues.joomla.org/tracker/joomla-cms/42866</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42866">issues.joomla.org/tracker/joomla-cms/42866</a>.</sub>

**Comment by adj9** [comment]
I have tested this item :white_check_mark: successfully on 06868d679349ef5528a3ae21b0bffac03dbbe06c<br /><br />It's OK<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42866">issues.joomla.org/tracker/joomla-cms/42866</a>.</sub>

**Comment by reDimDev** [comment]
I have tested this item :white_check_mark: successfully on 06868d679349ef5528a3ae21b0bffac03dbbe06c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42866">issues.joomla.org/tracker/joomla-cms/42866</a>.</sub>

**Pull request merged**
