### PR TITLE
Bump validate email regex to html5 standards

### PR DESCRIPTION
**Pull request by dgrammatiko**
#### Html 5 got an official validation rule for emails, let's use it!

The code comes from w3c:
screen shot 2016-06-09 at 01 23 14

URL: http://www.w3.org/TR/html5/forms.html#valid-e-mail-address
#### Testing

Apply patch
Create a new user in the back end and mess around with the email address field
#### B/C

No break

### CODE REVIEW

**Comment by brianteeman** [comment]
Can you post the link to the standard please not just a screenshot<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10760">issues.joomla.org/joomla-cms/10760</a>.</sub>

**Comment by dgt41** [comment]
@brianteeman sure, I put in the description

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 25adc009cc01ed2905ecc74ff4f9856c6c56d1c7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10760">issues.joomla.org/joomla-cms/10760</a>.</sub>

**Comment by nikitadhiman** [comment]
I have tested this item :white_check_mark: successfully on 25adc009cc01ed2905ecc74ff4f9856c6c56d1c7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10760">issues.joomla.org/joomla-cms/10760</a>.</sub>

**Comment by zero-24** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10760">issues.joomla.org/joomla-cms/10760</a>.</sub>

**Pull request merged**
