### PR TITLE
[5.1] Unification patch for PR #42610

### PR DESCRIPTION
**Pull request by tecpromotion**
### Summary of Changes

This small patch standardises the spelling for occurrences of "_MANAGE_LANGUAGES_CONTENT"

See https://github.com/joomla/joomla-cms/blob/97ff305a23315d6150029a938e945d6bb7301ded/administrator/language/en-GB/mod_menu.ini#L109
and https://github.com/joomla/joomla-cms/blob/97ff305a23315d6150029a938e945d6bb7301ded/administrator/language/en-GB/com_installer.ini#L232

### Testing Instructions

code review

### Actual result BEFORE applying this Pull Request

Two notations for two equivalent constants.

### Expected result AFTER applying this Pull Request

Standardised spelling

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by heelc29** [comment]
I have tested this item :white_check_mark: successfully on 75eb4eecce8bfef9c661c00910ee19ffd8fecd6c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42663">issues.joomla.org/tracker/joomla-cms/42663</a>.</sub>

**Comment by brianteeman** [comment]
Unfortunately you can nont do this https://developer.joomla.org/development-strategy.html

> Changing or deleting a language key is considered a backwards compatibility break. Adding new ones is not. Substantially changing the meaning associated with a language key is a compatibility break. Rephrasing something for a more accurate description or proper en-GB grammar is not.

**Comment by heelc29** [comment]
@brianteeman The language string (`COM_INSTALLER_TOOLBAR_MANAGE_CONTENT_LANGUAGES`) you mean was added yesterday with https://github.com/joomla/joomla-cms/pull/42610 and is not yet included in any public release -> so it should be ok.

**Comment by brianteeman** [comment]
ok then

**Comment by LadySolveig** [comment]
Thank you @tecpromotion

**Pull request merged**
