### PR TITLE
[fix] Custom field "list of images" doesn't show directories properly #16708

### LINKED ISSUE #16708: Custom field "list of images" doesn't show directories properly
### Steps to reproduce the issue
Update from joomla 3.6.4  to joomla 3.7.2
Create a custom field with type "list of images"
Change the directory path of images

### Expected result
I can view all my folders on images folder

### Actual result
I don't see my folder structure,i only get 1 folder

### System information (as much as possible)
PHP Built On	Linux Charis-Hosting 3.13.0-79-generic #123-Ubuntu SMP Fri Feb 19 14:27:58 UTC 2016 x86_64
Database Version	5.5.55-0ubuntu0.14.04.1-log
Database Collation	utf8_general_ci
Database Connection Collation	utf8mb4_general_ci
PHP Version	7.0.20
Web Server	Apache/2.4.25 (Unix) OpenSSL/1.0.1f
WebServer to PHP Interface	fpm-fcgi
Joomla! Version	Joomla! 3.7.2 Stable [ Amani ] 22-May-2017 09:46 GMT
Joomla! Platform Version	Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT

### Additional comments
This is very weird issue because i can see only 1 folder with subfolder and no other folder inside my images folder.

### PR DESCRIPTION
**Pull request by eshiol**
Pull Request for Issue #16708

### Summary of Changes

This patch fixes JFormFieldFolderList. See: #16708

Testing Instructions

#16708 This patch should fix this behavior

Expected result

Field "list of images" works correctly.

### CODE REVIEW

**Comment by zero-24** [comment]
This would always set the path to the root and not respect the configruation.

**Comment by eshiol** [comment]
This sets the path to the directory passed via configuration starting from the root directory.
```
$path = $this->directory;
$path = JPATH_ROOT . '/' . $path;
```

**Comment by zero-24** [comment]
Ah looks like i have not looked close enough.

**Comment by zero-24** [comment]
Can you please include a issue description + test instructions?

**Comment by eshiol** [comment]
I wrote a test component called com_pr17152
[com_pr17125-3.7.3.3.zip](https://github.com/joomla/joomla-cms/files/1147644/com_pr17125-3.7.3.3.zip)
It creates a folder called "this is the right folder" in the folder components/com_pr17125 and a folder called "this is the wrong folder" in the folder administrator/components/com_pr17125.
In the configuration page you can choose the folder using a folder list field
`<field name="file_path" type="folderlist" directory="components/com_pr17125" hide_none="true" hide_default="true" recursive="false" label="folder" description=""/>`
### Steps to reproduce the issue
Install the component com_pr17125
Go to Components > PR# 17125 > TEST
### Expected result
The field should show the contents of the folder components/com_pr17125
image
### Actual result
The field shows the contents of the folder administrator/components/com_pr17125
image
### Testing Instructions
Install the patch PR# 17125
Go to Components > PR# 17125 > TEST

**Comment by ghost** [comment]
@eshiol can you please update Test Instructions in first Comment?

**Comment by Quy** [comment]
@laoneo Would this be a valid fix to always look in the root directory for `images`? Currently, it is relative so if there is an `images` in `administrator`, then it will look there and not in the root.

**Comment by laoneo** [comment]
Not in the folderlist field, otherwise we would have here a BC break. If you need that case, then I would do your own form field for the imegelist custom field.

**Comment by Quy** [comment]
@laoneo Please confirm to close this PR for a different solution.

**Comment by laoneo** [comment]
@Quy if the author is willing to implement a form field for the image list custom field in this pr then we can work it out here. Otherwise it should be closed.

**Comment by laoneo** [comment]
Why we have a BC break can be reproduced with the following steps:
- Add the following code to the file administrator/components/com_content/config.xml after line 7
`<field name="file_path" type="folderlist" directory="help" hide_none="true" hide_default="true" recursive="false" label="Help" description=""/>`
- Open the Article Manager options

### Actual result
The en-GB folder is shown:
image

### Result with patch
Warning and the select box is empty
image

**Comment by eshiol** [comment]
I'm not be able to change the code. I lost the branch.
This code should solve the BC break
```
		if (!is_dir($path) || is_dir(JPATH_ROOT . '/' . $path))
		{
			$path = JPATH_ROOT . '/' . $path;
		}
```
By removing is_dir($path) the behavior will change slightly but the function still works
```
		if (is_dir(JPATH_ROOT . '/' . $path))
		{
			$path = JPATH_ROOT . '/' . $path;
		}
```
If the path doesn't exist, in the first case the error is related to JPATH_ROOT . '/' . $path, as it is now; 
image
in the second one, the error is related to $path
image

**Comment by Quy** [comment]
@eshiol I am sorry if this is not the right way. I would close this PR and submit a new PR with the latest changes.

**Comment by eshiol** [comment]
replaced by #20294

**Pull request closed without merging**
