### PR TITLE
[4.2] Warning about creating a backup before updating

### PR DESCRIPTION
**Pull request by Kostelano**
Pull Request for Issue # .

### Summary of Changes
We have two similar notifications in the page header - before extension update and before Joomla update. In the first case, we have a notification type - warning, in the second - just information.

Screenshot_1

PR changes notification type for Joomla update to "warning":

`COM_JOOMLAUPDATE_VIEW_DEFAULT_UPDATE_NOTICE="Before you update Joomla, ensure that the installed extensions are available for the new Joomla version. <br>You are strongly advised to make a <strong>backup</strong> of your site's files and database before you start updating."`

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on ca274e2e3d2079ced5491ed3f05c715f70e47988<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38278">issues.joomla.org/tracker/joomla-cms/38278</a>.</sub>

**Comment by ReLater** [comment]
I have tested this item :white_check_mark: successfully on ca274e2e3d2079ced5491ed3f05c715f70e47988<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38278">issues.joomla.org/tracker/joomla-cms/38278</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38278">issues.joomla.org/tracker/joomla-cms/38278</a>.</sub>

**Comment by roland-d** [comment]
Thank you

**Pull request merged**
