### PR TITLE
Change namespace from cms to CMS

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #15072 .

### CODE REVIEW

**Comment by brianteeman** [comment]
Looks like travis didnt like the folder being renamed

**Comment by wilsonge** [comment]
I think you did the wrong folder. I think you wanted to make libraries/src/Joomla/CMS uppercase not the old libraries/cms that contains the non-namespaced code in :)

**Comment by brianteeman** [comment]
grrh - blame Dmitri for that

**Comment by zero-24** [comment]
Did you realy want to merge it in this state?

**Comment by brianteeman** [comment]
no - it was a mistake - can you revert it please

**Comment by zero-24** [comment]
I'm on my phone and cant see a revert button. If you can see it just hit them ;)

**Comment by brianteeman** [comment]
Guessing I dont have access to revert/undo as I dont see any options - dont want to mess around any more will have to leave it to @wilsonge or @mbabker to undo my mess up - sorry guys

**Comment by brianteeman** [comment]
PS the branch with the correct PR is https://github.com/brianteeman/joomla-cms/tree/namespace-3.8

**Comment by brianteeman** [comment]
actually looked like the code I merged by accident is correct so I will leave it to you to decide to undo it or not

**Comment by laoneo** [comment]
I'v reverted it in #15085. Because all the namespaces in the files should be changed as well when all should be uppercase.

**Pull request merged**
