### PR TITLE
(imp) Message for robots.txt, implements #5208

### PR DESCRIPTION
**Pull request by sovainfo**
Cit from @brianteeman  see: https://github.com/joomla/joomla-cms/issues/5208 (edit by @zero-24 )

About 6 months ago we updated the robots.txt file to stop blocking the templates and media folders as google now needs access to them.

For various sensible reasons we do NOT change the robots.txt file on a live site when it is being updated. However I am seeing lots of people (twitter, forum and joomladays) not realising that and then complaining about the current robots file on their site.

Is it possible to create a post install message to inform them of the new robots file and how to apply it to their site

(Sorry I don't know how to create post-install messages myself)

### CODE REVIEW

**Comment by richard67** [comment]
@test Tested successfully with both a new install of staging patched by this PR and an update of a 3.3.6 with a patched update package (also staging plus this PR).
**Note:** I had to merge the language file of the cpanel with the latest changes in staging.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5223">issues.joomla.org/joomla-cms/5223</a>.</sub>

**Comment by brianteeman** [comment]
Setting RTC - thanks for testing<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5223">issues.joomla.org/joomla-cms/5223</a>.</sub>

**Comment by zero-24** [comment]
@sovainfo can you resolve the `merge conflicts`?

**Comment by roland-d** [comment]
The conflict:
Merge conflict in administrator/language/en-GB/en-GB.com_cpanel.ini

**Comment by sovainfo** [comment]
Sorry, don't know what&how!

**Comment by roland-d** [comment]
@sovainfo In your local patch-20 branch you need to bring the en-GB.com_cpanel.ini file up-to-date with the one in the main joomla-cms repository. After that you can commit the change and this PR should be up-to-date as well. Do you think you can do that?

**Comment by sovainfo** [comment]
Sorry, doesn't seem to work!

**Comment by brianteeman** [comment]
Do you want me to do a clean PR for you from your code

On 20 January 2015 at 17:03, sovainfo <notifications@github.com> wrote:

> Sorry, doesn't seem to work!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/5223#issuecomment-70690762>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by sovainfo** [comment]
If that is what it takes, that is fine with me,

**Comment by brianteeman** [comment]
OK I will give it a go

On 20 January 2015 at 23:42, sovainfo <notifications@github.com> wrote:

> If that is what it takes, that is fine with me,
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/5223#issuecomment-70757931>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
see #5838 hope this works

Only fair I should do some of the work as you were only creating the PR because I didnt know how to

**Pull request closed without merging**
