### PR TITLE
[5.1] Update ConstraintChecker.php typo/spelling

### PR DESCRIPTION
**Pull request by brianteeman**
### Summary of Changes
fixes a typo/spelling error in the code comments

code review only

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on b3991f253a7c3a60c7bccfbf0546e072435359de<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43284">issues.joomla.org/tracker/joomla-cms/43284</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on b3991f253a7c3a60c7bccfbf0546e072435359de<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43284">issues.joomla.org/tracker/joomla-cms/43284</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43284">issues.joomla.org/tracker/joomla-cms/43284</a>.</sub>

**Comment by brianteeman** [comment]
Thanks @wilsonge

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
