### PR TITLE
[4.1] com_scheduler checked out tasks

### PR DESCRIPTION
**Pull request by heelc29**
Pull Request for Issue #36676

### Summary of Changes

- Show information about "checked out" state in tasks list
- Add button to checkin tasks

### Testing Instructions

1. Open an existing task
2. Go back to the list view (without "Close")
3. Check informations about "checked-out" state
4. "Check in" the task by using the button in the toolbar or the lock icon
5. Check the _Maintenance: Global Check-in_

#### Open task edit
image
image
image
#### Close task edit
image
image

#### Open task edit
image
image
image
#### Close task edit
image
image

### Documentation Changes Required

No documentation yet

### CODE REVIEW

**Comment by pritam825** [comment]
I have tested this item :white_check_mark: successfully on 171b038a9188f71d3ac9234c9e44b69910853a63<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36875">issues.joomla.org/tracker/joomla-cms/36875</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 171b038a9188f71d3ac9234c9e44b69910853a63<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36875">issues.joomla.org/tracker/joomla-cms/36875</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36875">issues.joomla.org/tracker/joomla-cms/36875</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
