### PR TITLE
Tab selector fixed

### PR DESCRIPTION
**Pull request by joomlaboat**
"Show full description ... " link wasn't clickable.

Pull Request for Issue # .

### CODE REVIEW

**Comment by dgrammatiko** [comment]
I have tested this item :white_check_mark: successfully on 4659a2f170399bf7045dd25779076aa4176a3763<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35469">issues.joomla.org/tracker/joomla-cms/35469</a>.</sub>

**Comment by richard67** [comment]
Some testing instructions would be nice.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 4659a2f170399bf7045dd25779076aa4176a3763<br /><br />Go to System > Plugins > Content - Page Break
Click `Show Full Description...` link
See browser's console: `Uncaught TypeError: document.querySelector(...) is null`<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35469">issues.joomla.org/tracker/joomla-cms/35469</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35469">issues.joomla.org/tracker/joomla-cms/35469</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
