### PR TITLE
Replaces gh-3123 pull request "redone", hope it is correct now.

### PR DESCRIPTION
**Pull request by fanno**
This is a redone pull request per request.

### CODE REVIEW

**Comment by nikosdion** [comment]
This PR is fine by me :) :+1:

**Comment by fanno** [comment]
not sure if it matter or not but i tried to run a unit test:

```php
Time: 45.27 seconds, Memory: 184.25Mb


FAILURES!
Tests: 5704, Assertions: 10160, Failures: 13, Errors: 216, Incomplete: 1, Skipped: 69.

Process finished with exit code 2
```
looks like it is ome database thing incorrect i and trying to figure it out

**Comment by nikosdion** [comment]
Do you get Unit Test failures for the code you touched, or any code which uses the code you touched?

**Comment by fanno** [comment]
only thing i toutch other than than this pt, is to run composer, copy "phpunit.xml" and uncomment settings for DB inside. and run it. (i have db created, and user), still looking in to what i do wrong.

I don't see and code for auth plugin?

**Comment by nikosdion** [comment]
You should start with looking at the PHPUnit output. See which tests are failing. Track them down and see if these are failures that have to do with your code or not.

**Comment by fanno** [comment]
I fixed the incorrect UT config setup

```php
Time: 54.6 seconds, Memory: 180.00Mb


FAILURES!
Tests: 5704, Assertions: 10212, Failures: 1, Incomplete: 1, Skipped: 264.

Process finished with exit code 1
```

```php
Failed asserting that false matches expected '�bc �de EUR100'.
Expected :�bc �de EUR100
Actual   :false
 <Click to see difference>

 /home/fanno/workspace/phpstorm/fanno/joomla-cms/tests/unit/suites/libraries/joomla/string/JStringTest.php:815
 phar:///home/fanno/workspace/phpunit/phpunit-lts.phar/phpunit/TextUI/Command.php:176
```

should now be gtg.

**Comment by nikosdion** [comment]
Yes, indeed. It looks that the only failing test is one which depends on unicode string manipulation that has nothing to do with your PR.

**Comment by fanno** [comment]
I had enabled all databases but only have system configured for mysql, and the utuser premissions was incorrect =) been a long time since i ran this ut last

**Comment by wilsonge** [comment]
Merged on review

**Pull request merged**
