### PR TITLE
[4.0] Align content info block icons

### PR DESCRIPTION
**Pull request by N6REJ**
Pull Request for Issue # .

### Summary of Changes
makes all info-block icons fixed with so things line up.

### Testing Instructions
install "blog" sample data.
go to administrator/index.php?option=com_menus&view=item&client_id=0&layout=edit&id=103

change red options to match as shown.
image

go to "about" page in front end..
image

verify icons show.
image

verify icons & text line up.
image

inspect icons to be sure the icon class ends in "fa-fw"
image

### Actual result BEFORE applying this Pull Request
Content & Icons didn't line up
image

### Expected result AFTER applying this Pull Request
everything is visually lined up.

### Documentation Changes Required

none

### CODE REVIEW

**Comment by hans2103** [comment]
I have tested this item :white_check_mark: successfully on 8decde9d188334ee112e42a8de9f0abfa9e2dc5e<br /><br />Every icon has same width now. Alignment will be improved by this PR. Nice!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30543">issues.joomla.org/tracker/joomla-cms/30543</a>.</sub>

**Comment by paternax** [comment]
I have tested this item :white_check_mark: successfully on 8decde9d188334ee112e42a8de9f0abfa9e2dc5e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30543">issues.joomla.org/tracker/joomla-cms/30543</a>.</sub>

**Comment by brianteeman** [comment]
thinking out aloud - any reason not to just make all icons fixes width

**Comment by sandewt** [comment]
>thinking out aloud - any reason not to just make all icons fixes width

Recommended in any case for vertical menus with different icons.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30543">issues.joomla.org/tracker/joomla-cms/30543</a>.</sub>

**Comment by infograf768** [comment]
Let’s wait for @wilsonge reply about the use of fontawesome in front end before merging this.

**Comment by N6REJ** [comment]
@infograf768 it can be merged as if it needs to change the entire core of how icons function will need to change.

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30543">issues.joomla.org/tracker/joomla-cms/30543</a>.</sub>

**Comment by Quy** [comment]
Thanks.

**Pull request merged**
