### PR TITLE
[4.0][a11y]Extra column for icon featured

### PR DESCRIPTION
**Pull request by chmst**
Continues  #23718 .

### Summary of Changes
Column featured as separate column in com_content view featured

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 6bd100bc7efb08a1db9355bdbdc6c90be50f04fa<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23757">issues.joomla.org/tracker/joomla-cms/23757</a>.</sub>

**Comment by ChristineWk** [comment]
`<a href="" onclick="return false;" class="js-stools-column-order selected js-stools-button-sort" id="sorted" data-order="a.featured" data-direction="DESC" data-caption="Featured - descending" data-sort="descending">
<span>
Featured</span>
<span class="icon-arrow-up-3" aria-hidden="true"></span>
<span class="sr-only">
Sort Table By:	Featured</span>
</a>`
Was not possible to add Code (if correct) - so I tried now in this way :-)

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on b81135295c50f48f9ebdb8cbd4ab54f4521a2b81<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23757">issues.joomla.org/tracker/joomla-cms/23757</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on b81135295c50f48f9ebdb8cbd4ab54f4521a2b81<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23757">issues.joomla.org/tracker/joomla-cms/23757</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23757">issues.joomla.org/tracker/joomla-cms/23757</a>.</sub>

**Comment by brianteeman** [comment]
@chmst what is the point in having ordering on the featured column. Evrything is featured so the order will never change

**Comment by wilsonge** [comment]
@chmst As brian says can you remove the ordering. Just echo `JFEATURED` through jtext rather than using `searchtools.sort`

**Comment by chmst** [comment]
Sorry for delay ;)

**Comment by wilsonge** [comment]
Awesome stuff :) Thanks!

**Pull request merged**
