### PR TITLE
[4.0] BS beta 3

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # .

### Summary of Changes

Beta 3

### Testing Instructions

Open the cassiopeia/index.php and add 
- After line https://github.com/joomla/joomla-cms/blob/621e20c26d9191bc5d49440bfb4dce9bace86e51/templates/cassiopeia/index.php#L97
```php

HTMLHelper::_('bootstrap.offcanvas');
````

- after line https://github.com/joomla/joomla-cms/blob/621e20c26d9191bc5d49440bfb4dce9bace86e51/templates/cassiopeia/index.php#L174

```html

<button class="btn btn-primary" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasExample" aria-controls="offcanvasExample">
  <b>OFF-CANVAS-TEST</b>
</button>

<div class="offcanvas offcanvas-start" tabindex="-1" id="offcanvasExample" aria-labelledby="offcanvasExampleLabel">
  <div class="offcanvas-header">
    <h5 class="offcanvas-title" id="offcanvasExampleLabel">Offcanvas</h5>
    <button type="button" class="btn-close text-reset" data-bs-dismiss="offcanvas" aria-label="Close"></button>
  </div>
  <div class="offcanvas-body">
    <div>
      Some text as placeholder. In real life you can have the elements you have chosen. Like, text, images, lists, etc.
    </div>
  </div>
</div>
```

You should have an off canvas like:
Screenshot 2021-03-23 at 23 09 32

### Documentation Changes Required

I wrote some documentation on using Bootstrap (the interactive parts) here: https://gist.github.com/dgrammatiko/efb3de4aa7cab4813a244f93f73cc0fd

If someone could move this to the Joomla docs I would appreciate it

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 51fb55e34248de37d80c30468f6e13c34c50bafa<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32827">issues.joomla.org/tracker/joomla-cms/32827</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 51fb55e34248de37d80c30468f6e13c34c50bafa<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32827">issues.joomla.org/tracker/joomla-cms/32827</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32827">issues.joomla.org/tracker/joomla-cms/32827</a>.</sub>

**Comment by dgrammatiko** [comment]
@Quy please remove RTC. There is a new component in Bootstrap.
Will send the code in a bit

**Comment by dgrammatiko** [comment]
Ok support for off-canvas added

**Comment by laoneo** [comment]
Guess we need here some more tests.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on b179bd6c96432765cdc8cfd457a492e066848bf2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32827">issues.joomla.org/tracker/joomla-cms/32827</a>.</sub>

**Comment by laurentgarin** [comment]
I have tested this item :white_check_mark: successfully on b179bd6c96432765cdc8cfd457a492e066848bf2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32827">issues.joomla.org/tracker/joomla-cms/32827</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32827">issues.joomla.org/tracker/joomla-cms/32827</a>.</sub>

**Pull request merged**
