### PR TITLE
Revise Blog Data to Reflect the No. of Links to 2

### PR DESCRIPTION
**Pull request by imanickam**
In the Blog Sample Data, the menu item 'Home' has the # Links set to 2; whereas, in the article 'About your home page' the number of links mentioned is 4 (Four).

Pull Request for Issue # .
None.  

Refer similar PR - https://github.com/joomla/joomla-cms/pull/17926

**### Summary of Changes**
In the Sample Data's article titled "About your home page", the number of links set is mentioned as 4 where as in the menu item 'Home' it is set as 2.

**### Testing Instructions**

(a) Create a new installation of Joomla! with **BLOG** Sample Data 

(b) Log into the Back-end

(c) Open the menu item "Home" (that is in the Menu titled "Main Menu") for Edit and go to the tab "Blog Layout". Notice that the value shown for the option "# Links" is set to 2 (Two).

blog_sample_data_menu_item_links_showing_2

(d) See the new site created in a separate browser tab

(e) Notice that in the article titled "About your home page", the number of links is mentioned as 4.

blog_sample_data_original_links_shown_as_4

**### Expected result**

In the article titled "About your home page" the number of link must specify the value 2 - NOT 4.

blog_sample_data_revised_links_shown_as_2

**### Actual result**

See the step (e) in the section ### Testing Instructions

### CODE REVIEW

**Comment by imanickam** [comment]
The following files also have the same inconsistency.
- File sample_blog.sql in the directory \installation\sql\postgresql
- File sample_blog.sql in the directory \installation\sql\sqlazure

If PostgreSQL and Azure SQL would be supported in the future, I could change the above mentioned files as well and create PRs for them.

**Comment by ghost** [comment]
> If PostgreSQL and Azure SQL would be supported in the future (…) 

@mbabker @wilsonge are they supported in Future?

**Comment by ghost** [comment]
I have tested this item :red_circle: unsuccessfully on e1e15ed948ec22d2ee8b9eb33846ff375052807d<br /><br />Installing fresh Staging using Blog-Sample Data and apply PR Article-Text stay same: "(…) 4 next oldest articles. (…)".

Revert Patch don't work:
bildschirmfoto 2017-10-29 um 07 34 28

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17929">issues.joomla.org/tracker/joomla-cms/17929</a>.</sub>

**Comment by mbabker** [comment]
A patch tester failure does not mean that a patch cannot be tested successfully.

**Comment by mbabker** [comment]
Likewise, this patch cannot be properly tested with patch tester because it is a change in the install application.

**Comment by ghost** [comment]
so this is to test by installing the Fork?

**Comment by franz-wohlkoenig** [comment]
I have not tested this item.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17929">issues.joomla.org/tracker/joomla-cms/17929</a>.</sub>

**Comment by wilsonge** [comment]
Yes just download the zip

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on e1e15ed948ec22d2ee8b9eb33846ff375052807d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17929">issues.joomla.org/tracker/joomla-cms/17929</a>.</sub>

**Comment by ghost** [comment]
Installation of Fork give in the Article titled "About your home page", the Number of Links as two.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17929">issues.joomla.org/tracker/joomla-cms/17929</a>.</sub>

**Comment by wilsonge** [comment]
> If PostgreSQL and Azure SQL would be supported in the future, I could change the above mentioned files as well and create PRs for them.

These are supported throughout Joomla 3 - so we need patches for those two files as well please

**Comment by Quy** [comment]
Updated in PR #19357<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17929">issues.joomla.org/tracker/joomla-cms/17929</a>.</sub>

**Pull request closed without merging**
