### PR TITLE
Fix smart search highliter: match word exactly

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue #38903 .

### Summary of Changes

Changed highliter config to match word "exactly".

### Testing Instructions
Apply patch, run `npm install`
Please follow #38903

### Actual result BEFORE applying this Pull Request
Some words highligted partialy, and looks broken.

### Expected result AFTER applying this Pull Request
Only whole word is highlighted.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: 
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: 
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by sandewt** [comment]
I have tested this item :red_circle: unsuccessfully on 381832028718a72a6fd60fae6f90d444c35dc3f6<br /><br />**BEFORE PATCH:**
screen shot 2022-10-05 at 14 00 01
**AFTER PATCH: URL IS NOT HIGHLIGHTED**
screen shot 2022-10-05 at 14 00 01
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38908">issues.joomla.org/tracker/joomla-cms/38908</a>.</sub>

**Comment by Fedik** [comment]
For URL need "partial" word hghlight, however "partial" word highlight will break text fobafobar word in URL also.

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 381832028718a72a6fd60fae6f90d444c35dc3f6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38908">issues.joomla.org/tracker/joomla-cms/38908</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 381832028718a72a6fd60fae6f90d444c35dc3f6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38908">issues.joomla.org/tracker/joomla-cms/38908</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38908">issues.joomla.org/tracker/joomla-cms/38908</a>.</sub>

**Comment by fancyFranci** [comment]
Good that you fixed that. Thank you!

**Pull request merged**
