### PR TITLE
[4.0] Small codestyle fix

### PR DESCRIPTION
**Pull request by joomdonation**
Pull Request for Issue # .

### Summary of Changes
Small change to correct return type of the method (it returns array, not string)

### Testing Instructions
Code review.

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 8923802817ae5a8d9e8c9c63cd475544b96889d8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32220">issues.joomla.org/tracker/joomla-cms/32220</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 8923802817ae5a8d9e8c9c63cd475544b96889d8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32220">issues.joomla.org/tracker/joomla-cms/32220</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32220">issues.joomla.org/tracker/joomla-cms/32220</a>.</sub>

**Comment by Quy** [comment]
Thanks

**Pull request merged**
