### PR TITLE
[5.1] Cog icon focus [a11y]

### PR DESCRIPTION
**Pull request by brianteeman**
adds an outline to the cog when it receives keyboard focus

Pull Request for Issue https://github.com/joomla/joomla-cms/issues/43066 .

### Expected result AFTER applying this Pull Request
image

image

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 9bcda960430028d78e9db932404dd973f2fcd549<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43135">issues.joomla.org/tracker/joomla-cms/43135</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 9bcda960430028d78e9db932404dd973f2fcd549<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43135">issues.joomla.org/tracker/joomla-cms/43135</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43135">issues.joomla.org/tracker/joomla-cms/43135</a>.</sub>

**Comment by brianteeman** [comment]
thanks @wilsonge

**Comment by wilsonge** [comment]
Thanks!

**Comment by bembelimen** [comment]
This PR is not optimal, because the selector is too generic. Now all buttons in the cpanel which are the first child get this effect. It should be either reverted or fixed.

**Comment by brianteeman** [comment]
can you provide an example please so I can check

**Comment by brianteeman** [comment]
From what I can see the only button that can ever match the selector is the cog - what am I missing?

**Comment by bembelimen** [comment]
It selected every item with the class "btn" which is the first child. So if a module has a btn, it gets the styling, too.

**Comment by chmst** [comment]
My concern is that a second button (for a custom module) does not get the focus-ring

**Comment by brianteeman** [comment]
> It selected every item with the class "btn" which is the first child. So if a module has a btn, it gets the styling, too.

demonstrably not true, otherwise the buttons in the sample data module would have the outline

> My concern is that a second button (for a custom module) does not get the focus-ring

Show an example

**Pull request merged**
