### PR TITLE
Remove Searchbox from all fields except Category

### PR DESCRIPTION
**Pull request by Bakual**
Pull Request for Issue #12843 .

### Summary of Changes
The PRs to create a category "on the fly" (#8623, #8635, #8634, #8632, #8433) changed the call to load Chosen so the search field shows always. By default it would only show if there are more than 10 options.
This PR reverts that change and adds a specific Chosen call for the category field only.

### Testing Instructions
Test the following backend edit forms
* Article
* Banner
* Newsfeed
* Contact
* Custom Field
* Module (Position field)

Before PR each list field shows a search field:
state

After PR the searchfield is gone except for the category (fields group) field.
category

### Documentation Changes Required
None

### CODE REVIEW

**Comment by smehrbrodt** [comment]
Hm the search might be useful if you have many languages, or many access levels.

**Comment by Bakual** [comment]
> Hm the search might be useful if you have many languages, or many access levels.

Indeed.
Maybe "removing" was the wrong word used in the PR. I've set it back to default.
By default it will show when you have 10 and more items in the list. So if you have many languages or access levels, you will get the search box automatically.

**Comment by dgt41** [comment]
I have tested this item :white_check_mark: successfully on 1907a6af169c3acf1a43797cb07160cab164ac3f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12855">issues.joomla.org/tracker/joomla-cms/12855</a>.</sub>

**Comment by brianteeman** [comment]
I can see why to remove it on status but I would keep it on category<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12855">issues.joomla.org/tracker/joomla-cms/12855</a>.</sub>

**Comment by Bakual** [comment]
> I can see why to remove it on status but I would keep it on category

Is it gone on category? See testing instructions:

> After PR the searchfield is gone except for the category (fields group) field.

It should stay for the category. It should only be gone for all other fields with less than 10 items.

**Comment by brianteeman** [comment]
Shoot - misread the instructions

**Comment by andrepereiradasilva** [comment]
tested all forms with permissions tabs in the core.
we still have the search box in **new/edit module permissions** tab.

**Comment by Bakual** [comment]
> we still have the search box in new/edit module permissions tab.

Looks like I missed one then. I'll add that one later today. 👍

**Comment by Bakual** [comment]
Fixed in the module edit view as well and updated test instructions.

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 6090afe5d964b0d5ea109ec7ac2488edc87be98c<br /><br />works as described<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12855">issues.joomla.org/tracker/joomla-cms/12855</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 6090afe5d964b0d5ea109ec7ac2488edc87be98c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12855">issues.joomla.org/tracker/joomla-cms/12855</a>.</sub>

**Comment by infograf768** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12855">issues.joomla.org/tracker/joomla-cms/12855</a>.</sub>

**Pull request merged**
