### PR TITLE
[5.1] Remove testing channel

### PR DESCRIPTION
**Pull request by bembelimen**
Pull Request for Issue #43732 .

### Summary of Changes
Remove the testing channel from CLI.

### Testing Instructions
- Try to set the testing channel via the CLI (see commands here: https://github.com/joomla/joomla-cms/issues/43732 )

### Actual result BEFORE applying this Pull Request
You can switch to the testing channel

### Expected result AFTER applying this Pull Request
You can't change to the testing channel

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 22885a0c85bb6b3ee86c9ed974b440fb96314644<br /><br />Thanks - I thought it might have been more complex than that to fix<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43764">issues.joomla.org/tracker/joomla-cms/43764</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 22885a0c85bb6b3ee86c9ed974b440fb96314644<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43764">issues.joomla.org/tracker/joomla-cms/43764</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43764">issues.joomla.org/tracker/joomla-cms/43764</a>.</sub>

**Comment by LadySolveig** [comment]
Thank you @bembelimen and also for testing @Quy and @brianteeman !

**Pull request merged**
