### PR TITLE
[5.0] build tools creates wrong folder

### PR DESCRIPTION
**Pull request by heelc29**
### Summary of Changes

- update build tools for multiple file output introduced with #40509 @dgrammatiko
- update file `includes/incompatible.html` by run `npm ci`

### Testing Instructions

check items of `templates\system`

### Actual result BEFORE applying this Pull Request

a new folder (including a sub folder) is created by the build tools for error pages
image

### Expected result AFTER applying this Pull Request

no extra folder like 4.3, 4.4

### Link to documentations
Please select:
- [x] No documentation changes for docs.joomla.org needed
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by dgrammatiko** [comment]
LGTM

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 263c4da5056acb2fb0a68bed6d9b3cb170ab9eb1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41321">issues.joomla.org/tracker/joomla-cms/41321</a>.</sub>

**Comment by richard67** [comment]
@dgrammatiko Could you do a real test, too? Thanks in advance.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 263c4da5056acb2fb0a68bed6d9b3cb170ab9eb1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41321">issues.joomla.org/tracker/joomla-cms/41321</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41321">issues.joomla.org/tracker/joomla-cms/41321</a>.</sub>

**Comment by HLeithner** [comment]
thanks

**Pull request merged**
