### PR TITLE
[4.0] Specify title and icon of dashboards in the component manifest

### PR DESCRIPTION
**Pull request by Bakual**
This is an alternative solution to https://github.com/joomla/joomla-cms/pull/31392 which also takes care of the dashboard icons.
Inspired by comment https://github.com/joomla/joomla-cms/pull/31392#issuecomment-726646464

### Summary of Changes
Instead of guessing a language string for the title and the icon (!) of any dashboard, this PR changes it to lookup up the components manifest file and check the `<dashboard>` entries in there. If a corresponding entry for the current requested dashboard is found, then the title and icon attributes are taken as title and icon.

If not entry is found, the current behavior with guessed language strings for titles and icons are used. I'm not sure if we want to keep the icon stuff as it looks very fishy to me. The title guessing may be fine to keep.

### Testing Instructions
Open the various dashboards (users, content, privacy, system, help, home, components, menus) and make sure the icons and title are the same as bevore

### Actual result BEFORE applying this Pull Request
Title and icon are taken from guessed language strings or hardcoded in the view.

### Expected result AFTER applying this Pull Request
Title and icon are taken from the manifest files where they exist (home, system, help, components have no corresponding component)

### Documentation Changes Required
dashboard developer documentation needs to reflect this.

### CODE REVIEW

**Comment by ceford** [comment]
The dashboard title strings are not translated:
COM_CONTENT_DASHBOARD_TITLE
COM_MENUS_DASHBOARD_TITLE
COM_USERS_DASHBOARD_TITLE<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31397">issues.joomla.org/tracker/joomla-cms/31397</a>.</sub>

**Comment by Bakual** [comment]
Aw crap, I forgot to commit the language changes. Done now.

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 9167cc5a325c646b460d1b8582458a6262b44aad<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31397">issues.joomla.org/tracker/joomla-cms/31397</a>.</sub>

**Comment by Harmageddon** [comment]
I have tested this item :white_check_mark: successfully on 39d2a013bc1b509b7f075f7b29f1bfaef571a3ac<br /><br />Looks good to me! This incorporates #31382 as a fallback solution, so either way works now. Perfect! :-)

The only point I'm not sure about: Can we assume that com_something components always have their manifest file as something.xml? I just found an extension (JEvents) using manifest.xml, but this breaks e.g. refreshing the manifest file in "Extensions - Manage", so I'd say it probably is an error on their side.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31397">issues.joomla.org/tracker/joomla-cms/31397</a>.</sub>

**Comment by Bakual** [comment]
> The only point I'm not sure about: Can we assume that com_something components always have their manifest file as something.xml? I just found an extension (JEvents) using manifest.xml, but this breaks e.g. refreshing the manifest file in "Extensions - Manage", so I'd say it probably is an error on their side.

I checked the refresh manifest code before I wrote this PR and just assumed that's the way this file is supposed to be named.
It would be simple enough to add another possible name but I only would do it if it's also be done in the refresh manifest code.

**Comment by Harmageddon** [comment]
> > The only point I'm not sure about: Can we assume that com_something components always have their manifest file as something.xml? I just found an extension (JEvents) using manifest.xml, but this breaks e.g. refreshing the manifest file in "Extensions - Manage", so I'd say it probably is an error on their side.
> 
> I checked the refresh manifest code before I wrote this PR and just assumed that's the way this file is supposed to be named.
> It would be simple enough to add another possible name but I only would do it if it's also be done in the refresh manifest code.

I agree. :+1:

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 39d2a013bc1b509b7f075f7b29f1bfaef571a3ac<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31397">issues.joomla.org/tracker/joomla-cms/31397</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31397">issues.joomla.org/tracker/joomla-cms/31397</a>.</sub>

**Comment by wilsonge** [comment]
Looks better to me. Needs documentation on https://docs.joomla.org/Manifest_files

**Comment by particthistle** [comment]
In writing an upcoming JCM article on this specific feature, I've updated JDOCs https://docs.joomla.org/Manifest_files#Dashboards 

Can someone please review that I've explained it correctly and sufficiently. If it's sufficient, remove the Documentation Required label as that task is now completed for this PR.

**Comment by ceford** [comment]
I tried setting up a dashboard a while back and gave up as it did not work and was not really necessary for my component. I looked into this again today and think I now understand what is needed for a third party component. The **Dashboards** part of the **Manifest files** document is not sufficient on its own. The core dashboards write the module specs directly into the database on installation. Any other component added later is going to need an installation script to call libraries/src/installer/installerScript.php->addDashboardMenu passing it a dashboard and preset. Is this written up somewhere else? It should be, and you could put in a link or placeholder link to that place.

**Pull request merged**
