### PR TITLE
[4.2] Replace Factory::getUser() with $this->getCurrentUser() in components view class

### PR DESCRIPTION
**Pull request by joomdonation**
Pull Request for Issue # .

### Summary of Changes
With https://github.com/joomla/joomla-cms/pull/37498/ being merged into 4.2, we can now replace deprecated method `Factory::getUser()` in components view classes with new method `$this->getCurrentUser()`

### Testing Instructions
1. Use Joomla 4.2 nightly build
2. Apply patch
3. Access to random pages (frontend, backend), make sure nothing is broken.

### CODE REVIEW

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on e6b89a701707a2a6c23ae11f66128c9c6ccccecd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38006">issues.joomla.org/tracker/joomla-cms/38006</a>.</sub>

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on e6b89a701707a2a6c23ae11f66128c9c6ccccecd<br /><br />Tested successfully in Joomla 4.2.0-beta1-dev of 9 June<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38006">issues.joomla.org/tracker/joomla-cms/38006</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38006">issues.joomla.org/tracker/joomla-cms/38006</a>.</sub>

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
