### PR TITLE
[4.0] Make the preview url respect SEF settings

### PR DESCRIPTION
**Pull request by wilsonge**
Now that https://github.com/joomla/joomla-cms/pull/16879 has been merged into J4 we can immediately take advantage of it with the backend preview button. This should now use the full SEF URl rather than the non-SEF one

### CODE REVIEW

**Comment by SharkyKZ** [comment]
Why not just use `ContentHelperRoute::getArticleRoute()`?

**Comment by wilsonge** [comment]
@SharkyKZ ~Because we're in the backend not the frontend - so we need to be able to use the `SiteRouter` object~

We probably can - but that's just assembling the non-SEF URL - we'd still need to pass it through the `SiteRouter` object here

**Comment by infograf768** [comment]
Works fine here.
Would work even better (in multilingual) if https://github.com/joomla/joomla-cms/pull/24332 was merged...

**Comment by wilsonge** [comment]
@infograf768 it's merged and merged 4.0 into this one if you want to test again :)

**Comment by SharkyKZ** [comment]
@wilsonge Correct. With `ContentHelperRoute` link building can be moved to the view as we no longer need querying the database. And then `PreviewHelper` can be removed entirely.

**Comment by wilsonge** [comment]
It doesn't actually make DB queries https://github.com/joomla/joomla-cms/blob/4.0-dev/components/com_content/helpers/route.php#L34-L55 - we'd have to make the DB Queries anyhow (I thought the same thing as you at first - but I think we'd need this helper anyhow)

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 16fc7afb3986f2820bf7140c9f8f3399c5425b6a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24195">issues.joomla.org/tracker/joomla-cms/24195</a>.</sub>

**Comment by SharkyKZ** [comment]
@wilsonge we don't need to add Itemid or look for language SEF code. Router should handle this. `Route::link('site', \ContentHelperRoute::getArticleRoute($article->id, $article->catid, $article->language), true)` is fine.

**Comment by wilsonge** [comment]
@SharkyKZ your the boss! Done

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on 66b63f385f2d928d3d01353a154eae842cc64feb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24195">issues.joomla.org/tracker/joomla-cms/24195</a>.</sub>

**Pull request merged**
