### PR TITLE
Mail function disabled message

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #9446.
#### Summary of Changes

Change message that is displayed if you try to use the test mail function and mail has been disabled in global configuration
#### Before

The mail function has been temporarily disabled on this site, please try again later.
#### After

The mail function has been disabled by the administrator.

### CODE REVIEW

**Comment by 1apweb** [comment]
I have tested this item :white_check_mark: successfully on 66b5e67c55cc1f34e25cb3c53b8ff8e764f787cc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11416">issues.joomla.org/joomla-cms/11416</a>.</sub>

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 66b5e67c55cc1f34e25cb3c53b8ff8e764f787cc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11416">issues.joomla.org/joomla-cms/11416</a>.</sub>

**Comment by joo7** [comment]
The mail function has been disabled by an administrator.

Since there might be more than one administrator?

**Comment by brianteeman** [comment]
Thanks for testing 
I have changed the administrator to an administrator
No need to retest for that - setting RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11416">issues.joomla.org/joomla-cms/11416</a>.</sub>

**Pull request merged**
