### PR TITLE
Replace deprecated JArrayHelper by Joomla\Utilities\ArrayHelper

### PR DESCRIPTION
**Pull request by joomdonation**
### Summary of Changes
Just a small change to replace deprecated JArrayHelper call by Joomla\Utilities\ArrayHelper.

### Testing Instructions
Code review

### Documentation Changes Required
None

### CODE REVIEW

**Review by zero-24 — APPROVED** [review]
👍

**Comment by tameeshB** [comment]
I would like to work on this as my first contribution!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14248">issues.joomla.org/tracker/joomla-cms/14248</a>.</sub>

**Review by dgrammatiko — APPROVED** [review]

**Comment by joomdonation** [comment]
@dgt41 This PR is kind of code review PR, since it is approved by you and @zero-24, maybe you can mark it as RTC?

**Comment by dgt41** [comment]
I 'll leave the decision to the release master @rdeutz: do we need tests here?

**Review by yvesh — APPROVED** [review]

**Pull request merged**
