### PR TITLE
Fix loading module by ID on PostgreSQL

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Fixes module loading on PostgreSQL.

### Testing Instructions

This needs to be tested on PostgreSQL.

Insert a module into an article.
View the article in frontend.

### Expected result

Module appears.

### Actual result

Module doesn't appear.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by richard67** [comment]
@SharkyKZ How is that related to PR #28269 ? I see that one and this one here do concurrent changes in the same file, and I think for the same purpose, one in staging and one in 4.0-dev. Or do I understand something wrong?

**Comment by mbabker** [comment]
The two PRs are unrelated.

**Comment by SharkyKZ** [comment]
It's ultimately the same issue. The issue exists in staging and should be fixed there. Also #28269 doesn't work correctly on PDO as noted in the comments. Meanwhile, this works correctly on all database drivers and will work when it reaches 4.0.

**Comment by SharkyKZ** [comment]
Though for 4.0 we could change argument type to integer as discussed in https://github.com/joomla/joomla-cms/pull/26531.

**Comment by mbabker** [comment]
FWIW this is needed regardless of whatever external facing API changes someone wants to propose.  The issue here is the database results come back in an inconsistent type so typecasting is needed to not break the function’s internal flow.

How is this different than the other PR?  That is aiming to change the public API of the method, this one typecasts the database results to align with the currently documented public API (so you still have to pass a string identifier in here, a non-string will fail the strict comparison).

**Comment by richard67** [comment]
@SharkyKZ I've applied your patch and done as instructed but still can't see that bloody module. Am using PotsgreSQL 11 on PHP 7.3 with the native postgresql driver. Should I use the PDO driver instead? I'll try in a while.

**Comment by richard67** [comment]
@SharkyKZ False alarm, used the wrong module, popular tags. Seems there are none. With Breadcrumbs it works ;-)

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on f02c086031dacb018c674d343c43f95e99b32b84<br /><br />Hint for other testers: You have to use PostgreSQL (PDO) to reproduce the issue. With the native PostgreSQL driver the issue doesn't happen here with PostgreSQL 11.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28278">issues.joomla.org/tracker/joomla-cms/28278</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on f02c086031dacb018c674d343c43f95e99b32b84<br /><br />Tested successful on PostgreSQL (PDO) 11.3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28278">issues.joomla.org/tracker/joomla-cms/28278</a>.</sub>

**Comment by jwaisner** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28278">issues.joomla.org/tracker/joomla-cms/28278</a>.</sub>

**Comment by richard67** [comment]
I've just tested that nothing is broken for MySQLi and MySQL (PDO). All ok.

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
