### PR TITLE
[4.0] Fixes wrapping of btn-toolbar

### PR DESCRIPTION
**Pull request by bahl24**
Signed-off-by: Nitish Bahl <nitishbahl24@gmail.com>

Pull Request for Issue # . Notice inconsistency in format of btn-toolbar, sometimes it wraps and sometimes not as shown below
screenshot from 2019-02-02 17-07-53
screenshot from 2019-02-02 17-07-28

### Summary of Changes
I feel that the toolbar should not wrap as it looks odd, thus I have added `nowrap` which fixes the issue

### Expected result
Options and help button on same line.

### Actual result
Buttons are on different lines, may be more problematic if more buttons are added in the future.
screenshot from 2019-02-03 03-15-07

### Documentation Changes Required
None

### CODE REVIEW

**Comment by bahl24** [comment]
I noticed that there is no margin between bulk import and options button due to `margin-left: auto!important;` which overides `margin-left: .75rem;`
Is there a way we can choose max of the two values?
I am new to Joomla Dev and tried putting a if statement in the sass file, but I am facing problems.

**Comment by bahl24** [comment]
@puneet0191 @yvesh @astridx It is my first PR in Joomla Dev, can you help me out in https://github.com/joomla/joomla-cms/pull/23749#issuecomment-460002380 and why Drone CI has failed?

**Comment by wojsmol** [comment]
@bahl24 Regarding dron please merge latest changes from joomla-cms/4.0-dev to this PR branch.

**Comment by bahl24** [comment]
@wojsmol Done

**Comment by infograf768** [comment]
> I noticed that there is no margin between bulk import and options button due to `margin-left: auto!important;` which overides `margin-left: .75rem;`
Is there a way we can choose max of the two values?

You have pointed here the issue with this PR.
the class `.ml-auto` overrides `.subhead .btn-toolbar` an therefore the Options toolbar button gets stuck to whatever toolbar we have before it when reducing the browser window.

There is no min or max-margin in CSS and I am not sure we can use percentages here.

**Comment by bahl24** [comment]
@infograf768 Is there any other work around for this problem. I think that if we insert margin-right for the button before option button, we can solve this. Correct me if I am wrong.

**Comment by infograf768** [comment]
Indeed, if we do
```
.btn-toolbar {
    margin-bottom: 0;
    flex-wrap: nowrap;
    > * {
      margin-right: .75rem;
      box-shadow: $atum-box-shadow;

      &:last-child {
        margin-right: 0;
      }
    }
}
```

It would work.
And then we also have to modify stuff for RTL.

**Comment by infograf768** [comment]
But the problem is anyway present when one reduces the window size to accomodate tablets and smartphones... The toolbar buttons display far away from the view...
After patch
screen shot 2019-02-07 at 11 34 07
Before patch
screen shot 2019-02-07 at 11 37 04

I think that the solution is much more complex and includes a complete refactoring of the toolbar.
@coolcat-creations

**Comment by bahl24** [comment]
@infograf768 I think you are right

**Comment by coolcat-creations** [comment]
Putting this on our list...

**Comment by Quy** [comment]
Closing as not reproducible with the new backend template.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23749">issues.joomla.org/tracker/joomla-cms/23749</a>.</sub>

**Pull request closed without merging**
