### PR TITLE
Fix introtext treatment in single article view

### PR DESCRIPTION
**Pull request by smz**
#### Summary of Changes

An issue emerged in #9830 and was partially fixed in  #9865 (_onContentPrepare plugins not acting on introtext_)

The underlying issue is that (_contrary to what is done in the "Category blog" view_) introtext is not "_treated_", even when it is the **only** text to be displayed due to the `show_noauth` option being in force and the user being guest.

This PR fixes the above issue.
#### Testing Instructions / Additional comments

Testing instructions for #9865 can be used.

Compared to current staging **nothing should change** when using the standard "Protostar" template and the single article view template is not overridden. This is because in #9865 a fix was incorporated in the single article **template** for the above behaviour.

This is not anyway correct: it shouldn't be a template's concern to "prepare" the item to be displayed: this is "view" territory. The same is done in the "Category Blog" view.

This PR fixes the issue at its roots so other (_old and/or overriden_) templates can benefit of it.

Also, there shouldn't be (_and with this fix there is none_) difference between "introtext" and "text", when used at the template level (_actually we should only use "text"_). Again, it is "view" territory to decide what should be displayed and what shouldn't.

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 1621e7fed5141f9cdf73f7f2555248e9fd167ea6<br /><br />Agree with the change. Tested and works.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9964">issues.joomla.org/joomla-cms/9964</a>.</sub>

**Comment by smz** [comment]
Thanks @andrepereiradasilva, but... you've been too quick! I'm about pushing another commit fixing another minor aspect!! :smile:

**Comment by smz** [comment]
OK, ready! I got rid of the extra spurious blank that was appended to introtext when there was no fulltext...

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 976b4cf232b69e22bef617f83e6ab9bcaafdbb97<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9964">issues.joomla.org/joomla-cms/9964</a>.</sub>

**Comment by smz** [comment]
@andrepereiradasilva, thanks again and sorry for the "double testing"!

**Comment by andrepereiradasilva** [comment]
no problem

**Comment by rgmears** [comment]
I have tested this item :white_check_mark: successfully.

**Comment by smz** [comment]
Thanks for testing, @rgmears, but I think you haven't used the correct procedure to register your result (_see that it doesn't reference latest commit of this PR and "Human Test Results" count is still at 1?_): you have to register your test at https://issues.joomla.org/tracker/joomla-cms/9964, login with your github credentials and then click on the "Test this" blue button (_above my funny face!_)

**Comment by rgmears** [comment]
I have tested this item :white_check_mark: successfully on 976b4cf232b69e22bef617f83e6ab9bcaafdbb97<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9964">issues.joomla.org/joomla-cms/9964</a>.</sub>

**Comment by rgmears** [comment]
@smz 
Is that better?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9964">issues.joomla.org/joomla-cms/9964</a>.</sub>

**Comment by smz** [comment]
@rgmears perfect! :+1: thanks!

**Comment by lunalars** [comment]
Hmmm, I'm not sure if it is a good idea to set $item->introtext = $item->text. 
There may be reasons to use introtext in the template and it has been like this for years(?), so it would break b/c?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9964">issues.joomla.org/joomla-cms/9964</a>.</sub>

**Comment by brianteeman** [comment]
@lunalars is correct - this PR is not correct at all

**Comment by smz** [comment]
I think instead this is correct and I'll try to explain why.
If you have cases for which you think this is incorrect, can you please bring examples?
It can be that I missed something, but I honestly don't see where...
_______________
I think this is the only correct way to fix the the "onContentPrepare" treatment for introtext and it is exactly what is today done in `/components/com_content/views/category/tmpl/blog_item.php` which, by a large extent, is a clone of the article view (_due to Joomla not being so DRY at this regard_).

As you surely know content is stored in two columns at the DB level:
 1. introtext
 2. fulltext

there is no "text" column, and, following the MVC architecture, it is the duty of this "view" to build the `text` that will be later _consumed_ by templates. And its duty is to do so accordingly to the options that are in force at the time it is called. This unhaplly is not what happening now.

When we fixed the treatment of introtext in #9865 (_I'm saying "we" because that's code I pushed to your PR, Brian_) we fixed only for the "Protostar" template. Millions of other sites not using Protostar are not benefiting of that "_half backed fix_" and I don't think this a good service to the name of Joomla who advertise itself as a "CMS": we should **M**anage **C**ontent in a correct way for every user, independently to which template he/she is using.

The same (_unhappily, IMHO_) happened today with #9959, where a bug was fixed, but only for Protostar, not for the entire set of Joomla sites. I think this is unfortunate: I don't want Joomla to become a "PCMS" (_Protostar Content Management System_).

We have two core site templates, Breeze and Protostar: many bugs are fixed for Protostar only. Breeze is neglected. I think a correct way to check bug fixes would be to verify that they work **at the same time** for Breeze **and** Protostar. **If they don't, then we are doing something wrong with an hackish fix at the wrong place.** We are patching things at the wrong place (_unless the bug is a template specific one, that is_).
____________
Technically, what that "accused" line of code (_again, already present elsewhere_) is changing (_hint: analyse the preceding_ `if`)?
 1. it fixes the treatement of introtext (_as per this PR title_)
 2. it changes the contentent of `$item->introtext` **only when one of two conditions are met**: The article is split by a `readmore break` **and** (_due to the options in force_) we are either
   **a)** displaying the **whole** text (`introtext` + `fulltext`) or, **b)** only the second part of text, the one below the readmore break (`fulltext`, which again is an unfortunate name but we can't do anything about that...)

Which sites could be affected by this? Only sites with templates ignoring the options in force, that is displaying introtext only (_and NOT processed by the onContentPrepare plugins_) when something else was meant to be displayed (_probably an handful if any at all, over millions_) and this would be under all skies a **mistake** from their part and they simply deserve to be broken.

**Comment by brianteeman** [comment]
If you change the behaviour so that a site that was only displaying
introtext is now displaying the full text then it doesnt matter if you
guess it is a handfull or a million it is not b/c so will not be merged

On 19 April 2016 at 13:02, Sergio Manzi <notifications@github.com> wrote:

> I think instead this is correct and I'll try to explain why.
> If you have cases for which you think this is incorrect, can you please
> bring examples?
> It can be that I missed something, but I honestly don't see where...
> ------------------------------
>
> I think this is the only correct way to fix the the "onContentPrepare"
> treatment for introtext and it is exactly what is today done in
> /components/com_content/views/category/tmpl/blog_item.php which, by a
> large extent, is a clone of the article view (*due to Joomla not being so
> DRY at this regard*).
>
> As you surely know content is stored in two columns at the DB level:
>
>    1. introtext
>    2. fulltext
>
> there is no "text" column, and, following the MVC architecture, it is the
> duty of this "view" to build the text that will be later *consumed* by
> templates. And its duty is to do so accordingly to the options that are in
> force at the time it is called. This unhaplly is not what happening now.
>
> When we fixed the treatment of introtext in #9865
> <https://github.com/joomla/joomla-cms/pull/9865> (*I'm saying "we"
> because that's code I pushed to your PR, Brian*) we fixed only for the
> "Protostar" template. Millions of other sites not using Protostar are not
> benefiting of that "*half backed fix*" and I don't think this a good
> service to the name of Joomla who advertise itself as a "CMS": we should
> *M*anage *C*ontent in a correct way for every user, independently to
> which template he/she is using.
>
> The same (*unhappily, IMHO*) happened today with #9959
> <https://github.com/joomla/joomla-cms/pull/9959>, where a bug was fixed,
> but only for Protostar, not for the entire set of Joomla sites. I think
> this is unfortunate: I don't want Joomla to become a "PCMS" (*Protostar
> Content Management System*).
>
> We have two core site templates, Breeze and Protostar: many bugs are fixed
> for Protostar only. Breeze is neglected. I think a correct way to check bug
> fixes would be to verify that they work *at the same time* for Breeze
> *and* Protostar. *If they don't, then we are doing something wrong with
> an hackish fix at the wrong place.* We are patching things at the wrong
> place (*unless the bug is a template specific one, that is*).
> ------------------------------
>
> Technically, what that "accused" line of code (*again, already present
> elsewhere*) is changing (*hint: analyse the preceding* if)?
>
>    1. it fixes the treatement of introtext (*as per this PR title*)
>    2. it changes the contentent of $item->introtext *only when one of two
>    conditions are met*: The article is split by a readmore break *and* (*due
>    to the options in force*) we are either *a)* displaying the *whole*
>    text (introtext + fulltext) or, *b)* only the second part of text, the
>    one below the readmore break (fulltext, which again is an unfortunate
>    name but we can't do anything about that...)
>
> Which sites could be affected by this? Only sites with templates ignoring
> the options in force, that is displaying introtext only (*and NOT
> processed by the onContentPrepare plugins*) when something else was meant
> to be displayed (*probably an handful if any at all, over millions*) and
> this would be under all skies a *mistake* from their part and they simply
> deserve to be broken.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/9964#issuecomment-211884005>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by smz** [comment]
Brian, that's minutiae compared to what happened with 3.5.0 and 3.5.1 (_heck, we even wiped out UCM tables for non core extensions..._) and again **those site would be in error**...

If we change an erroneous behaviour that's "**fixing a bug** ", not "**breaking B/C**"

**Comment by lunalars** [comment]
$item->introtext should just be introtext and not introtext + fulltext or anything else.

And: I am the on in a million using $item->introtext in some of the templates I created :-)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9964">issues.joomla.org/joomla-cms/9964</a>.</sub>

**Comment by smz** [comment]
@lunalars You are using the non processed introtext when introtext wasn't meant to be displayed?
Can you bring a specific example, please?

**Comment by brianteeman** [comment]
You can argue as much as you want but this breaks existing sites and will
not be merged as is

On 19 April 2016 at 13:19, Sergio Manzi <notifications@github.com> wrote:

> @lunalars <https://github.com/lunalars> You are using the non processed
> introtext when introtext wasn't meant to be displayed?
> Can you bring a specific example, please?
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/9964#issuecomment-211894940>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by smz** [comment]
Happy?

**Comment by smz** [comment]
I'll leave to the PLT to decide which solution is deemed to be better: before or after https://github.com/joomla/joomla-cms/pull/9964/commits/a491c82e60e3c47e6929713a467b07b39ff7687e

**Comment by lunalars** [comment]
Just keep it logical:
- introtext is just introtext and nothing else
- text can be introtext, intro- + fulltext or just fulltext

I would call it a bug if introtext suddenly becomes fulltext (or whatever).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9964">issues.joomla.org/joomla-cms/9964</a>.</sub>

**Comment by smz** [comment]
@lunalars can you please test with your site in a million after latest commit? Is that OK with you?

**Comment by smz** [comment]
@andrepereiradasilva and @rgmears Sorry guys, can you please retest after latest commit (_with which I don't agree, but wouldn't do any harm_)? Thanks!

**Comment by smz** [comment]
Ooops... that's new Travis doesn't like // comments spanning multiple lines (_but only for PHP 5.6_)...

Should this be fixed? Adapting my commit, anyway...

**Comment by smz** [comment]
@lunalars 
nitpiking, but:
>Just keep it logical:
>
>    introtext is just introtext and nothing else
>    text can be introtext, intro- + fulltext or just fulltext

Actually there is not much logic in the naming of those DB columns/object attributes:

- most of the time introtext **is** the whole text (_when articles do not have a readmore break_)
- never fulltext will be the whole text

**Comment by smz** [comment]
PLT, please beware: with latest commit I pushed following the wishes of @brianteeman and @lunalars, the behavior is fixed only in Protostar (_where I have corrected the affected template to use_ `text` _instead of_ `introtext`) but will not correct the behaviour for other templates (_Breeze included, I guess..._) that are using `introtext` instead of `text` for displaying the introtext when needed (_sorry for the tongue-twister..._)

**Comment by rdeutz** [comment]
@smz code style checks are running only on 5.6

**Comment by smz** [comment]
Thanks @rdeutz ! Still think a three liner // comment is much better than a /* ... */ which will probably become a 5 liner...

**Comment by TasolJamal** [comment]
I have tested this item :white_check_mark: successfully on b0eaf3cb8237b66771fd89d792e05627129f177b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9964">issues.joomla.org/joomla-cms/9964</a>.</sub>

**Comment by truptikagathara** [comment]
I have tested this item :white_check_mark: successfully on b0eaf3cb8237b66771fd89d792e05627129f177b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9964">issues.joomla.org/joomla-cms/9964</a>.</sub>

**Comment by rgmears** [comment]
I have tested this item :white_check_mark: successfully on b0eaf3c

But there is a typo. "Don't do that when **introtex** ..." should be "Don't do that when **introtext** ..."

**Comment by smz** [comment]
Thanks to all testers and my apologies to @JamalTailored for not having noticed his test of more than a month ago!

You're right about the typo, @rgmears... and I also think it would be sensible  to change the name of that variable I introduced in a491c82e60e3c47e6929713a467b07b39ff7687e from `$full_fix` to something nicer (_a contest is open for the best name!_), but I'm reluctant as I'm afraid that just applying those cosmetic changes will invalidate the 3 positive tests that we now have...

**Comment by smz** [comment]
P.S.: I'm still convinced that this PR was better before applying a491c82e60e3c47e6929713a467b07b39ff7687e, but again I leave this to a PLT decision...

**Comment by brianteeman** [comment]
> Which sites could be affected by this? Only sites with templates ignoring the options in force, that is displaying introtext only (and NOT processed by the onContentPrepare plugins) when something else was meant to be displayed (probably an handful if any at all, over millions) and this would be under all skies a mistake from their part and they simply deserve to be broken.

By your own admission this breaks existing web sites - we have no idea if it is one or one million but we should not be breaking exiting sites with an upgrade<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9964">issues.joomla.org/joomla-cms/9964</a>.</sub>

**Comment by brianteeman** [comment]
> Which sites could be affected by this? Only sites with templates ignoring the options in force, that is displaying introtext only (and NOT processed by the onContentPrepare plugins) when something else was meant to be displayed (probably an handful if any at all, over millions) and this would be under all skies a mistake from their part and they simply deserve to be broken.

By your own admission this breaks existing web sites - we have no idea if it is one or one million but we should not be breaking exiting sites with an upgrade<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9964">issues.joomla.org/joomla-cms/9964</a>.</sub>

**Comment by smz** [comment]
@brianteeman  Got, it! Got it! No need to underline that again (_twice_).

What you're probably missing is that since a491c82e60e3c47e6929713a467b07b39ff7687e that's not the case anymore...

**Comment by roland-d** [comment]
@smz What is the status of this PR, is it still needed?

**Comment by smz** [comment]
To be honest I don't know how to answer: the code has changed significantly since, and I don't fell confident advising if/how this should be merged.

If I remember correctly, there where issues here:

1. when introtext was the only available text and it  was displayed due to current authorization restrictions, then it wouldn't be _treated_ (_i.e.: plug-ins applied_) as it should..

2. Some authorization restriction was applied at the template level while it should had been applied at the view level (_so that templates cannot override an authorization restriction_)

**Comment by smz** [comment]
I amended my answer above: the first issue was already resolved in another PR and only the second (architectural) issue was addressed here.

**Comment by smz** [comment]
I just noticed that in  #11290 the following _code_ has been added:
~~~
// NOTE: The following code (usually) sets the text to contain the fulltext, but it is the
// responsibility of the layout to check 'access-view' and only use "introtext" for guests
~~~

So, apparently it has been decided that the concern of content authorization must be moved **down** to the layout level instead of **up** to the view (_or model_) level.

P.S.: I love the "_usually_"...

**Comment by brianteeman** [comment]
Based on the comments above I am closing this

**Pull request closed without merging**
