### PR TITLE
[4.0] Enable com_finder

### PR DESCRIPTION
**Pull request by brianteeman**
Prior to Joomla 4 we had two search options - we now just have finder aka smart search. So it makes no sense for this to be disabled on NEW installs. This PR enables the plugin on NEW installs so that you know longer get the warning etc.

This does not change EXISTING sites

Pull Request for Issue #25826  .

image

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on f1969ac7cd0bf30d35a0ccc844f2dfc3bdbf36be<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25839">issues.joomla.org/tracker/joomla-cms/25839</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on d6e662efec9c89d5582d57573ac7ad9a22fcf5cf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25839">issues.joomla.org/tracker/joomla-cms/25839</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25839">issues.joomla.org/tracker/joomla-cms/25839</a>.</sub>

**Comment by brianteeman** [comment]
Update branch to see if that fixes the drone error

**Comment by brianteeman** [comment]
@wilsonge the drone error is unrelated to this PR as it is a test for your jsonapi stuff thats failing 

ContentCest: Test crud on article

**Comment by jeckodevelopment** [comment]
Updated branch to check if Drone is solved

**Pull request merged**
