### PR TITLE
[4.0] Multilingual: Fix propagate functionality

### PR DESCRIPTION
**Pull request by infograf768**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/25364

### Summary of Changes
Correcting modal-fields.es5.js to prevent trying to close a modal when we are not in a modal
Thanks @Fedik  !

Note: we have not yet an es6.js. TBD by an expert.

### Testing Instructions
See https://github.com/joomla/joomla-cms/issues/25364
Run npm

### After patch
All is fine. Messages are displayed

@Fedik

### CODE REVIEW

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on 7304cfb443b6bfc8c26daa148af12556470c0e7a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25371">issues.joomla.org/tracker/joomla-cms/25371</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on f12c6054504e17d64c6d08e41cd6e5965d5b22b2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25371">issues.joomla.org/tracker/joomla-cms/25371</a>.</sub>

**Comment by infograf768** [comment]
RTC.

Thanks folks for testing.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25371">issues.joomla.org/tracker/joomla-cms/25371</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
