### PR TITLE
[4.4] Remove obsolete exclude pattern from ruleset.xml for phpcs

### PR DESCRIPTION
**Pull request by richard67**
Pull Request for Issue # .

### Summary of Changes

This pull request (PR) removes obsolete exclude patterns from the "ruleset.xml" file which is used by phpcs e.g. in the ci tests with Drone.

Obsolete means the corresponding file or folder has been removed (or moved to another place) with some PR but the exclude pattern has been forgotten about.

The following obsolete entries are removed:
- Line no. 237: File "plugins/content/joomla/joomla.php" has been moved to another place and been changed with PR #40561 .
- Line no. 238: File "plugins/content/loadmodule/loadmodule.php" has been moved to another place and been changed with PR #40561 .
- Line no. 239: File "plugins/content/pagebreak/pagebreak.php" has been moved to another place and been changed with PR #40561 .
- Line no. 244: File "plugins/user/joomla/joomla.php" has been moved to another place and been changed with PR #40180 .

The list of obsolete exclude patterns has been created with help of a small tool (PHP CLI script) which I provide with PR #40278 .

### Testing Instructions

Code review: Check that the removed exclude patterns belong to the files mentioned in the description and the files don't exist on a clean, current 4.4-dev branch.

Verify that the PHPCS step succeeded in the Drone ci checks for this PR here.

### Actual result BEFORE applying this Pull Request

File "ruleset.xml" in the Joomla root contains exclude patterns for files which doesn't exist anymore in the 4.4-dev branch.

### Expected result AFTER applying this Pull Request

File "ruleset.xml" in the Joomla root doesn't contain these exclude patterns.

PHPCS still succeeds in Drone for this PR.

### Link to documentations
Please select:
- [X] No documentation changes for docs.joomla.org needed

- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by laoneo** [comment]
As there are more plugin groups which got converted to service providers. Should we leave this one open?

**Comment by richard67** [comment]
> As there are more plugin groups which got converted to service providers. Should we leave this one open and mark it as draft?

@laoneo Up to you. You can also merge by review and I make a new PR when that is necessary.

**Comment by richard67** [comment]
@laoneo It seems the latest merges of plugin and module conversions hasn't changed anything for the ruleset.xml, so this PR here is still up to date.

**Comment by richard67** [comment]
I've just checked again, PR is still up to date, no changes needed.

**Comment by richard67** [comment]
@laoneo Why have you added the Updates Requested label? I see no change request in any review so that label does not make any sense for this PR.

**Comment by laoneo** [comment]
Because they need some updates when we merge further prs which remove files. I want to make sure that people are not wasting their time testing these pr's.

**Comment by richard67** [comment]
> Because they need some updates when we merge further prs which remove files. I want to make sure that people are not wasting their time testing these pr's.

@laoneo We never did that before. The worst thing which can happen after the upmerge is a merge conflict which can be easily solved, and in past we even did not request again 2 human tests. You are breaking all past practice and block my PR without a reason.

**Comment by laoneo** [comment]
I have it removed.

**Comment by richard67** [comment]
@laoneo This PR here is ready and up to date with the latest merge of the content plugins.

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
