### PR TITLE
[4.2] Fix Calendar pointer

### PR DESCRIPTION
**Pull request by brianteeman**
### Summary of Changes
The calendar widget used for setting the publishing date etc is sometimes using the wrong cursor when it should be using a pointer. Otherwise its not clear that the item is indeed clickable

### Testing Instructions
image

### Actual result BEFORE applying this Pull Request
Moving the cursor over any of the top 4 highlighted areas above and the cursor will be  an i-beam text cursor
Moving the cursor over any of the bottom 2 highlighted areas above and the cursor will be  an arrow cursor

### Expected result AFTER applying this Pull Request
moving the cursor over any of the 6 highlighted areas above and the cursor will be the pointing finger cursor as expected

Any other comments about any other css in the calendar is off-topic and will be ignored.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on baf67cb6df1b96385d4e4acb01b1f41ff193032c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39227">issues.joomla.org/tracker/joomla-cms/39227</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on baf67cb6df1b96385d4e4acb01b1f41ff193032c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39227">issues.joomla.org/tracker/joomla-cms/39227</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39227">issues.joomla.org/tracker/joomla-cms/39227</a>.</sub>

**Comment by laoneo** [comment]
Thanks!

**Comment by brianteeman** [comment]
thank you

**Pull request merged**
