### PR TITLE
[4.0] Configure content edit tabs

### PR DESCRIPTION
**Pull request by brianteeman**
There are a lot of tabs and a lot of options when editing content. We already have the ability to hide come of those tabs. This PR simply extends that to all the additional tabs. This PR does not change the default display it just extends the existing ability to hide some tabs to all the tabs.

### New Options
image

### Edit screen with all tabs hidden
image

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on d8f8c7a5b0403c62a73da649a51195171bd5f6d1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26629">issues.joomla.org/tracker/joomla-cms/26629</a>.</sub>

**Comment by tecpromotion** [comment]
I have tested this item :red_circle: unsuccessfully on d8f8c7a5b0403c62a73da649a51195171bd5f6d1<br /><br />After installing the patch and changing the tabs (all hide), an error occurs when creating a new post.

Save failed with the following error: Field 'metakey' doesn't have a default value

Screenshot 2019-10-19 10 03 13

**Comment by brianteeman** [comment]
@tecpromotion that is unrelated to this PR - if you hide the publishing tab then you get this and the publishing tab can be hidden without this PR - please can you create a new issue for that

**Comment by tecpromotion** [comment]
I have tested this item :white_check_mark: successfully on d8f8c7a5b0403c62a73da649a51195171bd5f6d1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26629">issues.joomla.org/tracker/joomla-cms/26629</a>.</sub>

**Comment by karo3** [comment]
I have tested this item :white_check_mark: successfully on d8f8c7a5b0403c62a73da649a51195171bd5f6d1<br /><br />Hiding the tabs works but creating a post with Publishing Options on hide does not work.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26629">issues.joomla.org/tracker/joomla-cms/26629</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26629">issues.joomla.org/tracker/joomla-cms/26629</a>.</sub>

**Comment by tecpromotion** [comment]
> Hiding the tabs works but creating a post with Publishing Options on hide does not work.

see https://github.com/joomla/joomla-cms/issues/26650

**Comment by wilsonge** [comment]
I have to say although with publish options there's some precedent I'm really reluctant to open the doors of parameters to control parameters

**Comment by brianteeman** [comment]
The door is already open. 

How do you explain to a user that you can simplify some parts of the process  but not all parts especially as there is no logic to explain why

**Comment by HLeithner** [comment]
I'm in favor for this PR. 

my 2 cents

**Comment by infograf768** [comment]
Did'nt we have some issues with Publishing Options and multilingual site in j3?
https://github.com/joomla/joomla-cms/pull/22166

**Comment by infograf768** [comment]
No apparent issue for multilingual, except evidently that hiding associations would be counter-productive.

**Comment by brianteeman** [comment]
Can this be merged then?

Would be great if it could be and then we can add similar options to other components

**Comment by wilsonge** [comment]
For the record. I disagree with options for every tab in all components.

**Comment by brianteeman** [comment]
Thanks for merging - and I still dont understand your objection ;)

**Pull request merged**
