### PR TITLE
[4.0] alerts accessibility

### PR DESCRIPTION
**Pull request by brianteeman**
When changing the permission of something if there is a child group then a popup notice is displayed. For a sighted user they can still carry on and change the permissions of other properties. However for a user using a screen reader that is not the case. After changing a permission the focus then moves to the popup notice. This has to be closed before the user can continue but the focus is returned to the url bar and they then have to navigate through the entire page again.

the same is true for all alerts although it is particularly bad with this one.

## The fix is in two parts.
Part one is to stop moving the focus to the popup notice and this change is in the custom element and can be found here https://github.com/joomla-projects/custom-elements/pull/120

### This is part two
This adds the attribute aria-live to the message container. This will ensure that the message will be announced by the screenreader even though we don't give it focus. Note it must be on the message container because the aria-live must be present in the document on page load - even if there are no messages - for aria-live to work.

aria-live=polite means that the message will be announced next ie after what is being announced now
there is another option which is not appropriate here
aria-live=assertive which means that the message will interrupt anything currently being announced.

### Testing
Testing without a screen reader is hard. The best test without one is to check that after this pr the div with the id system-message-container looks like this when there is no message displayed
```
`<div id="system-message-container" aria-live="polite">
	<div id="system-message">
			</div>
</div>`
```

### Bonus
The alert custom-element has the ability to be autodismissed after a period of time (often called a growl notification). This ability can now be enabled without breaking the accessibility

### CODE REVIEW

**Comment by manojLondhe** [comment]
Can't see code from ```Testing``` instruction from above @brianteeman

**Comment by manojLondhe** [comment]
This is what I see:

When no alert message

```
<div id="system-message-container" aria-live="polite">
	<div id="system-message">
			</div>
</div>
```

When there is an alert message:
```
<div id="system-message-container" aria-live="polite">
	<div id="system-message">
			</div>
<joomla-alert type="info" dismiss="true" role="alert" class="joomla-alert--show"><button class="joomla-alert--close" aria-label="Close">
<span aria-hidden="true">×</span></button><h4 class="alert-heading">Notice</h4><div>Permissions changed in a group with child groups. Save or reload to recalculate the child groups permissions.</div></joomla-alert>
</div>
```
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25421">issues.joomla.org/tracker/joomla-cms/25421</a>.</sub>

**Comment by brianteeman** [comment]
I fixed the instructions . Thanks for testing. Thats a successful test.

**Comment by manojLondhe** [comment]
I have tested this item :white_check_mark: successfully on 52f1de98e2ac75ca5a3620f12cbcfebdf9899c29<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25421">issues.joomla.org/tracker/joomla-cms/25421</a>.</sub>

**Comment by wilsonge** [comment]
Merged in the 4.0 branch here so we get the new custom elements. Can someone just quickly retest so we have these in combination please

**Comment by brianteeman** [comment]
Can someone please test this so that @wilsonge can merge it. There are other PR waiting on this

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on b3ac75ad20d02b4486cf6bb885fe49f9c41c18e9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25421">issues.joomla.org/tracker/joomla-cms/25421</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25421">issues.joomla.org/tracker/joomla-cms/25421</a>.</sub>

**Comment by HLeithner** [comment]
thx

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
