### PR TITLE
[4.0] quickicon user add link

### PR DESCRIPTION
**Pull request by brianteeman**
Fix a typo in the link so that it correctly goes to the new user form

First reported here https://github.com/joomla-projects/j4adminui/pull/169

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 68ca3594507ac9d8216e0a0e5f1213011ab6a9c5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27286">issues.joomla.org/tracker/joomla-cms/27286</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 68ca3594507ac9d8216e0a0e5f1213011ab6a9c5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27286">issues.joomla.org/tracker/joomla-cms/27286</a>.</sub>

**Comment by infograf768** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27286">issues.joomla.org/tracker/joomla-cms/27286</a>.</sub>

**Comment by brianteeman** [comment]
Thank you

**Pull request merged**
