### PR TITLE
Fix load language on seving component config

### PR DESCRIPTION
**Pull request by saharin88**
If you field in config not valid on save, attribute message or label field lang constant not load.
This fix that.

### CODE REVIEW

**Comment by saharin88** [comment]
else can 
`JFactory::getLanguage()->load($option, JPATH_ADMINISTRATOR)`

**Comment by infograf768** [comment]
Can you give an example of field that would not be valid?
Basically, how to test this?

**Comment by saharin88** [comment]
I was faced with this problem in a my component, but you look at the example com_tags [http://screencast.com/t/hphhfTXaNn](http://screencast.com/t/hphhfTXaNn)

**Comment by wojsmol** [comment]
@saharin88 Plase see CS PR https://github.com/saharin88/joomla-cms/pull/2

**Comment by infograf768** [comment]
hmm...
If I understand well, your demonstration is to make an obvious mistake in a config.xml (here, /administrator/components/com_tags/config.xml)
i.e. instead of
```
<field
			name="tag_list_item_maximum_characters"
			type="text"
			filter="integer"
			label="COM_TAGS_LIST_MAX_CHARACTERS_LABEL"
			description="COM_TAGS_LIST_MAX_CHARACTERS_DESC"
			showon="tag_list_show_item_description:1"
		>
		</field>
```
modify to
```
<field
			name="tag_list_item_maximum_characters"
			type="text"
			validate="url"
			scheme="http"
			label="COM_TAGS_LIST_MAX_CHARACTERS_LABEL"
			description="COM_TAGS_LIST_MAX_CHARACTERS_DESC"
			showon="tag_list_show_item_description:1"
		>
		</field>
```
to demonstrate a failure to load a language file.

**Comment by infograf768** [comment]
I suggest you to test on staging where I do get the correct translated message.
Please install staging https://github.com/joomla/joomla-cms/archive/staging.zip and test again.

**Comment by saharin88** [comment]
Yes, I see the loaded language
and what is the secret? since 3.5.1 not lang load...

**Comment by infograf768** [comment]
I guess a bug was solved :)

**Comment by infograf768** [comment]
Please close issue

**Comment by saharin88** [comment]
aha, see change method getForm in class ConfigModelComponent
add `		$lang = JFactory::getLanguage();
		$lang->load($option, JPATH_BASE, null, false, true)
		|| $lang->load($option, JPATH_BASE . "/components/$option", null, false, true);
`

**Comment by infograf768** [comment]
yep
see https://github.com/joomla/joomla-cms/pull/8529

**Pull request closed without merging**
