### PR TITLE
[4.3] Media manager better breadcrumb

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # .

### Summary of Changes

- Switch breadcrumbs to select element to fix the width on many nested paths

### Testing Instructions

- Apply the patch and run `npm ci`
- Check that the breadcrumbs work (try many nested folders)

### Actual result BEFORE applying this Pull Request

Broken layout

### Expected result AFTER applying this Pull Request

Screenshot 2023-02-10 at 11 00 53
Screenshot 2023-02-10 at 11 01 24

Screenshot 2023-02-10 at 11 01 12

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

Also just for clarification, this should solve some a11y problems with breadcrumbs and the design and idea for the select menu comes directly from the Apple Finder (the File Explorer of MacOS):
Screenshot 2023-02-11 at 13 14 04

### CODE REVIEW

**Comment by Quy** [comment]
Pleas make spacing consistent.

**Comment by Quy** [comment]
Please fix for RTL.

39831-rtl

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on fbae43d2c392fbfaf715ada192b06528558bd6ed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39831">issues.joomla.org/tracker/joomla-cms/39831</a>.</sub>

**Comment by richard67** [comment]
@dgrammatiko I've just tested this PR but it seems not to work with keyboard navigation. When I tab to the breadcrumbs, I would expect it to open the dropdown when using the enter key, but it doesn't. So there is no way to use it for navigation with keyboard only.

**Comment by dgrammatiko** [comment]
> When I tab to the breadcrumbs, I would expect it to open the dropdown when using the enter key,

I think you need to press space to open the dropdown and then use the arrow keys to select the one you want and then press enter. So there's an enter but at the end of the chain not in the start...

**Comment by richard67** [comment]
@dgrammatiko Ah, the space key was the trick. It seems only the skipto plugin uses the enter key, all our backend list views use space to open e.g. the list filters. So it's fine and consistent and just me did not know that.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on fbae43d2c392fbfaf715ada192b06528558bd6ed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39831">issues.joomla.org/tracker/joomla-cms/39831</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39831">issues.joomla.org/tracker/joomla-cms/39831</a>.</sub>

**Comment by dgrammatiko** [comment]
> all our backend list views use space to open

@richard67 actually this comes from the browser, it's the default accessibility mapping. Thus whenever we use the default select element we guarantee that the element is accessible (assuming that label, etc are in place)

**Comment by laoneo** [comment]
I don't think so that this is a good change as breadcrumbs are displayed differently in joomla, where the full path is visible. With this change only the current path is listed which might work on desktop apps (honestly I don't like this behavior but that is another story) but never saw it on the web.
image

**Comment by brianteeman** [comment]
Do we even need breadcrumbs? Its just a duplication of the information in the tree

**Comment by laoneo** [comment]
My personal opinion is that I like it, when I have an indicator where I'm actually navigated to with links without searching in the tree. Especially on smaller screens.

**Comment by chmst** [comment]
I am not in favour of this solution as it iis quite different from or usual braedcrumbs. Users expect that the behaviour of elements is consistent in a system.

**Comment by dgrammatiko** [comment]
> I am not in favour of this solution as it iis quite different from or usual braedcrumbs. 

Then fix the current one so it doesn't break even on huge screens:
Screenshot 2023-02-13 at 11 54 40

**Pull request closed without merging**
