### PR TITLE
[4.0] [com_languages] Remove deprecated method

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Removes deprecated method.

### Testing Instructions

Go to Language Overrides.
Click `Clear Cache`.
Open new override form.
Test that searching for constants/values to override still works.

### Expected result

Works like before.

### Documentation Changes Required

IDK.

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 424fc8c15fd4aad739dcf2e657f28ee4cf095e10<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28947">issues.joomla.org/tracker/joomla-cms/28947</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 424fc8c15fd4aad739dcf2e657f28ee4cf095e10<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28947">issues.joomla.org/tracker/joomla-cms/28947</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28947">issues.joomla.org/tracker/joomla-cms/28947</a>.</sub>

**Comment by infograf768** [comment]
Tks

**Pull request merged**
