### PR TITLE
[4.0] Only use the global language folder for core language files

### PR DESCRIPTION
**Pull request by Bakual**
Pull Request for Issue #23489 .

### Summary of Changes
Removes duplicated language files in the respective extension folder.
Moves language files for the backend template "Atum" to the global folder.

### Testing Instructions
Make sure the following extensions still are translated:
* Backend Template "Atum"
* Multilingual Status Module (Backend)
* Statistics Module (Backend)
* Languagecode Plugin
* Frontend Template "Cassiopeia"

### Expected result
Everything Translated

### Actual result
Everything Translated, but files are in wrong (for core) location.

### Documentation Changes Required
None

### CODE REVIEW

**Comment by infograf768** [comment]
I do not agree with this change.
A template can be duplicated and therefore also its language files.
When duplicated, the new copy of the template should contain a language folder with the modified language files.

The core templates language files should be present in both the template folder and core, which is not the case for Atum.

Therefore a correct patch should add Atum language files into a specific language folder in the template folder itself.

**Comment by Bakual** [comment]
Imho, language files should only be present in one place, not in two. I'm quite sure that if there is a change in the language strings, it will be missing in either one of the two files.

Your example of copying the template is fine, but it still only works for the en-GB files. The translations would be lost anyway. A better way would be to improve the copy function to look (also) in the global folder for possible language files and copy those.

**Comment by infograf768** [comment]
> Your example of copying the template is fine, but it still only works for the en-GB files. The translations would be lost anyway.

Someone copying a template should be aware of this imho.

> A better way would be to improve the copy function to look (also) in the global folder for possible language files and copy those.

Agree, but until someone does propose a patch, we should keep 3.x behaviour.

**Comment by SharkyKZ** [comment]
Remove language folder from file list in manifest files too:
```
administrator\modules\mod_multilangstatus\mod_multilangstatus.xml
administrator\modules\mod_stats_admin\mod_stats_admin.xml
administrator\modules\mod_version\mod_version.xml
plugins\system\languagecode\languagecode.xml
```

**Comment by brianteeman** [comment]
Can you look at resolving the conflicts so that this can be tested please.

**Comment by Bakual** [comment]
Conflicts solved

**Comment by Bakual** [comment]
Also updated manifests (somehow missed that comment by @SharkyKZ )

**Comment by infograf768** [comment]
https://github.com/joomla/joomla-cms/pull/23493#issuecomment-453001068

has still not been taken care of in TemplateModel.php

**Comment by Bakual** [comment]
Imho this is another issue which has to be handled in a separate PR.
Because the current implementation is buggy as well as it only copies the english files and ignores the available translations. We would need code which takes care of all files (or none).

**Comment by roland-d** [comment]
@Bakual If this is ready for testing can you please fix the merge conflicts so I can get this tested?

**Comment by Bakual** [comment]
@roland-d Merged 4.0 branch

**Comment by bees4ever** [comment]
I have tested this item :white_check_mark: successfully on 7adef41c88dfcbf1d7fbe81e00b5d020400860fe<br /><br />Successfully tested.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23493">issues.joomla.org/tracker/joomla-cms/23493</a>.</sub>

**Comment by Lyro274** [comment]
I have tested this item :white_check_mark: successfully on 7adef41c88dfcbf1d7fbe81e00b5d020400860fe<br /><br />All extensions were translated.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23493">issues.joomla.org/tracker/joomla-cms/23493</a>.</sub>

**Comment by ghost** [comment]
Status "Ready To Commit".

**Comment by infograf768** [comment]
Let's not forget we have to correct the Copy Template functionnality...

**Comment by brianteeman** [comment]
Create an issue and it won't be forgotten

**Comment by itsMeAnimated** [comment]
I have tested this item ✅ successfully on 7adef41
works as described <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23493">issues.joomla.org/tracker/joomla-cms/23493</a>.</sub>

**Comment by wilsonge** [comment]
Thanks

**Pull request merged**
