### PR TITLE
[4.4] User profile edit: No notice when no active menu item

### PR DESCRIPTION
**Pull request by Hackwar**
Pull Request for Issue #40499 .

### Summary of Changes
When there is not active menu item and you edit your user profile, you get a notice at the top.

### Testing Instructions
1. Enable error reporting
2. Make sure you have no menu item pointing to the user profile view or the profile edit view.
3. Login to the frontend
4. Go to `index.php?option=com_users&view=profile&layout=edit&Itemid=444444` (The 444444 is supposed to be a non-existing menu item)

### Actual result BEFORE applying this Pull Request
You get a notice about accessing query on null.

### Expected result AFTER applying this Pull Request
No notice.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 392c07ae12b420aca3489c4794809f404a24f116<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43140">issues.joomla.org/tracker/joomla-cms/43140</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 392c07ae12b420aca3489c4794809f404a24f116<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43140">issues.joomla.org/tracker/joomla-cms/43140</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43140">issues.joomla.org/tracker/joomla-cms/43140</a>.</sub>

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
