### PR TITLE
[4.0] Update table list view css/js

### PR DESCRIPTION
**Pull request by brianteeman**
This pr addresses the following issues

 - After #21127 the checkall box in the table header was misaligned
 - After #21127 when selectin a row (or select all) the cell with the article title (which has changed to a th) was not highlighted
 - Any thead that is not a link was in bold when the rest are not. Example is the Usergroups column header index.php?option=com_users&view=users

### CODE REVIEW

**Comment by brianteeman** [comment]
I dont understand the hound comments on the js 
it is saying change the tabs to spaces but all the other lines are tabs

**Comment by wilsonge** [comment]
If you merge in 4.0-dev and fix conflicts hound should be solved.

**Comment by brianteeman** [comment]
updated dev and fixed conflicts

**Comment by Quy** [comment]
> when selectin a row (or select all) the cell with the article title (which has changed to a th) was not highlighted

This is still an issue.

**Comment by brianteeman** [comment]
WOW - thats weird it is ok on all the other lists

**Comment by brianteeman** [comment]
@quy can you retest now. If its ok I will resolve the conflicts

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 00b0b492184f31976e3787182ad3ad673af0194b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21163">issues.joomla.org/tracker/joomla-cms/21163</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 00b0b492184f31976e3787182ad3ad673af0194b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/21163">issues.joomla.org/tracker/joomla-cms/21163</a>.</sub>

**Comment by wilsonge** [comment]
@brianteeman if you can fix the conflicts here I'll get this merged

**Comment by brianteeman** [comment]
@wilsonge if the conflict fix worked then its good to go

**Comment by wilsonge** [comment]
Looks good to me! Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
