### PR TITLE
[4.0]  Update Choices.js, fix placeholder for a select with multiple attribute

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue #27083 

### Summary of Changes
Update Choices.js to latest version, also it fix a placeholder for a select with multiple attribute

### Testing Instructions
apply patch, run `npm install`

### Expected result
all works, with new version

### Actual result
all works, with old version

### Documentation Changes Required
none

### CODE REVIEW

**Comment by wilsonge** [comment]
@SniperSister @zero-24 can you look at RIPS please

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 19ea64965c3cf75d5f429fa3d4cfaccfbc8512a0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27093">issues.joomla.org/tracker/joomla-cms/27093</a>.</sub>

**Comment by ghazal** [comment]
I have tested this item :white_check_mark: successfully on 19ea64965c3cf75d5f429fa3d4cfaccfbc8512a0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27093">issues.joomla.org/tracker/joomla-cms/27093</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 19ea64965c3cf75d5f429fa3d4cfaccfbc8512a0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27093">issues.joomla.org/tracker/joomla-cms/27093</a>.</sub>

**Comment by brianteeman** [comment]
Thanks @Fedik <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27093">issues.joomla.org/tracker/joomla-cms/27093</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27093">issues.joomla.org/tracker/joomla-cms/27093</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
