### PR TITLE
[html5] Beez3 frontend template

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Summary of Changes

This is a redo of https://github.com/joomla/joomla-cms/pull/9842 for **beez3** only.

This PR does a basic conversion of **beez3** template to HTML5.
Also made some minor corrections:
- Use the API in inline css/js (except error page)
- Use ie9 or lower hml5.js in all files.
#### Testing Instructions
1. Install patch
2. Set the site template as "beez3" (if not yet)
3. Go to frontend and check if the the following pages are working properly:
   - normal page (test any existent URL)
   - component popup (add `?tmpl=component&print=1` to an existent page)
   - error pages (test one non existent URL)

Check also the code changes.
#### Observations

All pages should now start with this code:

``` html
<!DOCTYPE html>
<html lang="en-gb" dir="ltr">
<head>
[...]
    <meta charset="utf-8" />
[...]
```

### CODE REVIEW

**Comment by bertmert** [comment]
I have tested this item :white_check_mark: successfully on c038a376fc8679340a19e40f55db6795356b1d93<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10640">issues.joomla.org/joomla-cms/10640</a>.</sub>

**Comment by andrepereiradasilva** [comment]
changed madded:
- Updated branch
- removed `$doc` in favour of `$this`

**Comment by anjahage** [comment]
I have tested this item :white_check_mark: successfully on c38bda651885cd2eab4ce8e691144c95a40d1ed7<br /><br />Another successful test according the test instructions.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10640">issues.joomla.org/joomla-cms/10640</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@bertmert can you retest?

**Comment by joomlara** [comment]
I have tested this item :white_check_mark: successfully on c38bda651885cd2eab4ce8e691144c95a40d1ed7<br /><br />Tested successfully<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10640">issues.joomla.org/joomla-cms/10640</a>.</sub>

**Comment by zero-24** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10640">issues.joomla.org/joomla-cms/10640</a>.</sub>

**Comment by roland-d** [comment]
Thanks everybody

**Pull request merged**
