### PR TITLE
Just update the timestamps for core sample data

### PR DESCRIPTION
**Pull request by zero-24**
Pull Request for Issue #15961 

### Summary of Changes

This now limit the timestamp updates just to the core sample data.

### Testing Instructions

- download: https://github.com/zero-24/joomla-cms/archive/just_change_core_sampledata.zip
- install as normal joomla with core sample data
- the dates should be updated
- add a sql update file (to be provided by @hendrikbehncke) to the following folder: https://github.com/zero-24/joomla-cms/tree/just_change_core_sampledata/installation/sql/mysql
- confirm the dates are not touched and the same as the values as provided.

### Expected result

The core files are uptodate and the 3rd Party files are not.

### Actual result

The core and 3rd party files are uptodate.

### Documentation Changes Required

It should be noted somewhere that this is only happening now for the core.

### CODE REVIEW

**Comment by brianteeman** [comment]
> It should be noted somewhere that this is only happening now for the core.

To be more accurate it should be noted that it only happens for sample data with those filenames.

**Comment by mbabker** [comment]
:-1: on principle

We should not be handling data sets differently based on whether it was something we were given or something that someone added to the installer through a supported path.  So either it should always be updated or never be updated.  The argument in that issue is basically "I want what is in the SQL dump to be inserted to the database with minimal (if any) changes", which is fine, but it should also be consistent across the board.

**Comment by zero-24** [comment]
> which is fine, but it should also be consistent across the board.

any suggestions on how to handle that than?

**Comment by mbabker** [comment]
Either we close the other issue as expected behavior or we change the installer to not change the timestamps.  Either way it should be consistent, this introduces inconsistency.

**Comment by zero-24** [comment]
> Either we close the other issue as expected behavior or we change the installer to not change the timestamps. 

What do you think about some kind of flag system?

**Comment by Bakual** [comment]
**If** we change the sampledata to something I proposed in https://github.com/joomla/joomla-cms/pull/7680, then that issue would be gone as the created date would be the date the user installs the sample data set.
Maybe that helps :)

**Comment by brianteeman** [comment]
@bakual it wont address the problem as the tempalte club apparently wants to keep the dates that are in the sql unoutched

**Comment by Bakual** [comment]
I guess it would be possible as well since the respective plugin would be responsible for inserting the data. If it's done by a direct query or using models wouldn't matter.

**Comment by hendrikbehncke** [comment]
This PR is what was in my mind. I see the point with inconsistency, but from my point of view there is already (some kind of) inconsistency in excluding 'sample_testing.sql'. Maybe not updating the timestamps during installation at all but updating the sql files is the correct way then? As brianteeman said, we need to keep the dates provided in the sql file.

**Comment by franz-wohlkoenig** [comment]
@zero-24 installed just_change_core_sampledata.zip, dates are updated. Where to find "… sql update file (to be provided by @hendrikbehncke) …".

**Comment by brianteeman** [comment]
Why not simply update the dates in our sql to 2017 and then remove the code that did the magic to change the sql on install to today

**Comment by alikon** [comment]
i'd prefer to go with #7680  even if it have a 3.8 milestone

**Comment by brianteeman** [comment]
as #7680 has now been merged is this PR still valid?

**Pull request closed without merging**
