### PR TITLE
Custom fields in contact mails are rendered with HTML

### PR DESCRIPTION
**Pull request by laoneo**
Pull Request for Issue #40338.

### Summary of Changes
This pr restores the behavior that custom fields in mails are rendered without HTML code. It was like that forever but the pr #37716 broke it.

### Testing Instructions
- Create a normal contact custom field
- Create a contact mail custom field
- Create a contact with an email address and fill in a value into the custom field
- Create a contact menu item the new contact selected
- Open the contact details page
- Send a mail to the contact via the web form

You can also do the testing instructions from #37716 to ensure that the contact data is rendered like an article.

### Actual result BEFORE applying this Pull Request
The custom field is rendered like on articles. The mail which got sent to the contact contains some HTML output.

### Expected result AFTER applying this Pull Request
The custom field is rendered like on articles. The mail which got sent to the contact contains no HTML output.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by richard67** [comment]
@laoneo As far as I understand this PR solves issue #40338 . If that is right. please refer to that issue in the description. Thanks in advance.

**Comment by laoneo** [comment]
Yes it fixes, thanks for the hint, updated.

**Comment by Kostelano** [comment]
We should probably remove the lines, where do we delete these files in the script..?

https://github.com/joomla/joomla-cms/blob/42328f2676b4de85311ba3e26b0f3624c787903e/administrator/components/com_admin/script.php#L6470
https://github.com/joomla/joomla-cms/blob/42328f2676b4de85311ba3e26b0f3624c787903e/administrator/components/com_admin/script.php#L6471

**Comment by richard67** [comment]
> We should probably remove the lines, where do we delete these files in the script..?

@laoneo I leave it to you if you do that with this PR or if I do it with my PR for script.php, but if I do it and the merge of my PR takes longer, the functionality might be broken when people update with nightly builds, so maybe you should fix that here.

**Comment by laoneo** [comment]
Thanks for the hint @Kostelano !

**Comment by richard67** [comment]
@laoneo It needs to remove also the deleted folders in script.php here: https://github.com/joomla/joomla-cms/blob/3f468ada220135ec43a3b7d3937b2330c466de87/administrator/components/com_admin/script.php#L7923-L7926

**Comment by laoneo** [comment]
@richard67 thanks

**Comment by richard67** [comment]
@laoneo I've just tested, also with the testing instructions from PR #37716 . What I've noticed is that when using a subform field in the mail context, i.e. the contact form, the email still contains some HTML markup, just less as before. I don't know how that's been in 4.2.8 or older before that PR had been merged, I haven't tested that yet with 4.2.8.

Besides this, everything works as expected, i.e. the contact fields and the article fields look the same, and when using single fields and not subforms for the contact form, there is no HTML markup in the email.

**Comment by laoneo** [comment]
It is probably the same on 4.2.8. All this pr does is to remove the markup around the field. But the subform probably adds some more markup to align the fields. So this should be fixed in another pr.

**Comment by richard67** [comment]
@laoneo I've just tested with 4.2.8 and there I get an error when using a subform in the contact form, so your PR doesn't break anything.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on a056f909ccdde24a9aac4073e5bd7c391adb49a7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40557">issues.joomla.org/tracker/joomla-cms/40557</a>.</sub>

**Comment by Uwe-MrT** [comment]
Testet, the Fix works... (y)

**Comment by richard67** [comment]
> Testet, the Fix works...

@Uwe-MrT Could you mark your test result in the issue tracker? Just go to https://issues.joomla.org/tracker/joomla-cms/40557  and use the blue "Test this" button at the top left corner, then select your test result (success) and submit. Thanks in advance.

**Comment by Uwe-MrT** [comment]
I have tested this item :white_check_mark: successfully on a056f909ccdde24a9aac4073e5bd7c391adb49a7<br /><br />Works for me<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40557">issues.joomla.org/tracker/joomla-cms/40557</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40557">issues.joomla.org/tracker/joomla-cms/40557</a>.</sub>

**Comment by obuisard** [comment]
Thanks Allon @laoneo for the PR and Richard @richard67 for looking into it!

**Pull request merged**
