### PR TITLE
[4.0] Fix login alert in footer

### PR DESCRIPTION
**Pull request by Quy**
Pull Request for Issue #28909.

### Summary of Changes
Move login alert to the top.

### Testing Instructions
Apply PR.
Log in to the backend with wrong credentials.
See that the login alert is at the top and not in the footer.

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 25162c28c93951ffb6417c828348ffd8684e8b6d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28911">issues.joomla.org/tracker/joomla-cms/28911</a>.</sub>

**Comment by SharkyKZ** [comment]
Can you do the same for `error_full.php`? And remove SCSS for `notify-alerts` class.

**Comment by richard67** [comment]
@Quy @SharkyKZ Any idea how I can test the error_full.php?

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 613944ca3dae98abb049b86b390615f554e766f2<br /><br />Change in login.php tested as described.
Changes in error_full.php and the scss files: Code review. Verified that the "notify-alerts" class is not used anymore in any php or js or (s)css with this PR.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28911">issues.joomla.org/tracker/joomla-cms/28911</a>.</sub>

**Comment by infograf768** [comment]
rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28911">issues.joomla.org/tracker/joomla-cms/28911</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 613944ca3dae98abb049b86b390615f554e766f2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28911">issues.joomla.org/tracker/joomla-cms/28911</a>.</sub>

**Comment by infograf768** [comment]
tks

**Pull request merged**
