### PR TITLE
[4.0] Underline links by default

### PR DESCRIPTION
**Pull request by ciar4n**
Pull Request for Issue #33629 .

### Summary of Changes
Underline links by default

### Actual result BEFORE applying this Pull Request
By default links are not underlined

### Expected result AFTER applying this Pull Request
By default links are underlined

### CODE REVIEW

**Comment by PhilETaylor** [comment]
I have not tested this item.<br /><br />It does as its intended to, although personally I think it looks visually worse.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33808">issues.joomla.org/tracker/joomla-cms/33808</a>.</sub>

**Comment by ciar4n** [comment]
I'm not a fan myself but I'm assuming this is a AA a11y requirement?

**Comment by PhilETaylor** [comment]
Im sure our resident expert will be along to confirm or deny this is an accessibility thing :)

**Comment by ciar4n** [comment]
@PhilETaylor Agreed. Underline removed from icons with https://github.com/joomla/joomla-cms/pull/33808/commits/2a68f4c74fcd0be7fadf29c38c3dda9b6f56389b

> Im sure our resident expert will be along to confirm or deny this is an accessibility thing :)

@brianteeman Willing or not, I'm assigning that grand title to you 😉

**Comment by PhilETaylor** [comment]
@ciar4n if you have time, could you take a look at Brian's PR at #33811 and see if there is an easy fix to fix the system dashboard icons, while retaining the good changes to the other dashboard and the + signs?

**Comment by brianteeman** [comment]
it was the removal of the flex-grow that caused the problem i think

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 2a68f4c74fcd0be7fadf29c38c3dda9b6f56389b

If there is time for finetuning:

> image


<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33808">issues.joomla.org/tracker/joomla-cms/33808</a>.</sub>

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on 2a68f4c74fcd0be7fadf29c38c3dda9b6f56389b<br /><br />Many years ago I read somewhere that links are supposed to be visually distinguishable from adjacent text. So this fits the bill although the underline is barely visible and I agree with others it is a bit yucky. Whatever happened to the default ancient blue/purple underlined scheme?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33808">issues.joomla.org/tracker/joomla-cms/33808</a>.</sub>

**Comment by richard67** [comment]
> If there is time for finetuning:
> 
> > image

@ciar4n Do you think you could fix that, too, the underlined space between the link and any appended language badge?

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33808">issues.joomla.org/tracker/joomla-cms/33808</a>.</sub>

**Comment by brianteeman** [comment]
Please remove RTC the issue reported by @sandramay0905 needs to be fixed

**Comment by richard67** [comment]
Back to pending. See previous comments.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33808">issues.joomla.org/tracker/joomla-cms/33808</a>.</sub>

**Comment by brianteeman** [comment]
> Is it possible to only show the underline on the text and not the whitespace between the icon and the text?

Probably something like adding `display: contents;` to the link as the problem comes from the whitespace (newlines and tabs)

**Comment by richard67** [comment]
Is this PR here still needed or useful now as #33811 has been merged?

**Comment by PhilETaylor** [comment]
I think commit 2a68f4c is still needed ?

**Comment by chmst** [comment]
Underline together with icon is really too much and not required. A user must see what is a link but the icon is sufficient for that.

**Comment by PhilETaylor** [comment]
And that is why  2a68f4c is still needed as it removed the underline from the icon for offsite links

**Comment by ciar4n** [comment]
> Is this PR here still needed or useful now as #33811 has been merged?

If #33811 is the accepted solution then maybe this PR is overkill as it makes links underlined by default where #33811 only underlines links in the cpanel modules?

**Comment by ciar4n** [comment]
@sandramay0905 Could you detail for me how to replicate? ....

image

**Comment by ghost** [comment]
@ciar4n You need a multilanguage site, you can see it on `Menu Dashboard` for the menus having `Home` set.

**Pull request closed without merging**
