### PR TITLE
[4.0] Fix typo in admin mod_menu

### PR DESCRIPTION
**Pull request by joomdonation**
Pull Request for Issue #34928.

### Summary of Changes
Fix small PR in mod_menu which causes fatal error.  Thanks @jameswadsworth for reporting and providing the solution.

### Testing Instructions
Code review.

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on a97db84bd5af4ef9776f5890b16cb75d67c945d8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34929">issues.joomla.org/tracker/joomla-cms/34929</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on a97db84bd5af4ef9776f5890b16cb75d67c945d8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34929">issues.joomla.org/tracker/joomla-cms/34929</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34929">issues.joomla.org/tracker/joomla-cms/34929</a>.</sub>

**Comment by jameswadsworth** [comment]
I have tested this item :white_check_mark: successfully on a97db84bd5af4ef9776f5890b16cb75d67c945d8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34929">issues.joomla.org/tracker/joomla-cms/34929</a>.</sub>

**Comment by Quy** [comment]
Thanks!

**Pull request merged**
