### PR TITLE
Updated 6 installation languages and 1 tinyMCE

### PR DESCRIPTION
**Pull request by Bakual**
* 6 updated languages in installation
* 1 updated language for TinyMCE

Can be merged on review after Travis has passed.

### CODE REVIEW

**Comment by brianteeman** [comment]
The Arabic file is not correct. As you will see from the comments in the code there are places that 'installation'  should not be translated and they have been. (didn't check any other languages)

**Comment by Bakual** [comment]
When I try it with Google Translator, it looks like he did a "loose" translation where it just says "installationfolder" and not "folder installation". Then the translation would actually be fine.

**Comment by brianteeman** [comment]
@Bakual no it is not fine
>  ; The word 'installation' should not be translated as it is a physical folder.

**Comment by Bakual** [comment]
I know what is written there. But I don't know arabic myself and there may be reasons this works better for them.
I can tell him, but for obvious reasons I can't change it myself.

**Comment by brianteeman** [comment]
i give up - joomla obviously dont care at all about our arabic users if we allow this sort of mistake and happily merge it,

**Comment by infograf768** [comment]
it's simple: there was a parsing error in the ini. better merge it now and try to get it corrected by tt next. that is better for arabic users.

**Comment by Bakual** [comment]
@brianteeman I can't do it myself, all I can do is tell the translator, which I did. Anyway it's off topic because this PR didn't change it. So I don't know why you cam to that conclusion.

**Comment by syntaxerror** [comment]
@brianteeman, you should not try to dictate other languages you know nothing about. There might be several good reason it fits better to use some translation.

Also, if you don't know - we do not translate strings word by word. We use what's best for our languages.

Oh, and "should not" is not the same as "it's forbidden". ;)

**Comment by brianteeman** [comment]
@syntaxerror how do you know I know nothing about arabic - you are making assumptions that are plainlly wrong? 

This word is NEVER to be translated as it refers to the name of a physical folder in the filesystem which is ALWAYS called **installation** - that is why we have that specific note after years of experience wondering why we had regular reports on the forum of users deleting the installation of joomla and then wondering why they had no joomla. It was then that we realised the name of the physical folder was being translated and this was confusing the users and that is why we added the note not to translate the word. We didnt add it just for fun!! 

So to simply repeat what is said in the comment this is NOT a word to be translated on these specific lines (unless of course joomla miraculously translated file and folder names)

**Comment by syntaxerror** [comment]
Truth is you don't care for other opinions, and now you're just being childish again.

**Comment by brianteeman** [comment]
lol

**Comment by syntaxerror** [comment]
LOL

**Comment by mbabker** [comment]
Enough with the childish crap.

**Pull request merged**
