### PR TITLE
[com_content] Unused variable

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Removes unused variable.

### Testing Instructions

Code review.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 1bedd925e9ca30095e03a470e7b69d1105eb3be9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29063">issues.joomla.org/tracker/joomla-cms/29063</a>.</sub>

**Comment by RolandSM** [comment]
I have tested this item :white_check_mark: successfully on 1bedd925e9ca30095e03a470e7b69d1105eb3be9<br /><br />Also tested with success.
Code review result is really no use of this variable.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29063">issues.joomla.org/tracker/joomla-cms/29063</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29063">issues.joomla.org/tracker/joomla-cms/29063</a>.</sub>

**Comment by zero-24** [comment]
Merging thnaks!

**Comment by senolsengul** [comment]
Hello there,
Joomla does not open articles after 3.9.19 update gives error

Errro message: Unclosed string at position: 2784

**Pull request merged**
