### PR TITLE
[plg_system_cache] Disable gzip before caching the page

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue #17501.

### Summary of Changes

Makes sure we store uncompressed page in cache.

### Testing Instructions

Enable `Gzip Compression` in Global Configuration.
Enable `System - Page Cache` plugin.
Open some cacheable frontend page with a form, e.g. username reminder page. Remember its URL.
Start a new session (e.g. clear browser session or use a different browser).
Open the same page and try to submit form.

### Expected result

Form submitted.

### Actual result

Submitting form fails with warning:

>The security token did not match. The request was aborted to prevent any security breach. Please try again.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by richard67** [comment]
~~Will the page from the cache be served zipped or unzipped?~~
Update: Looks as if the browser still gets the cached page compressed => good.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 6c8c523127856a7f4ff71d85986cc524a217ba6d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25823">issues.joomla.org/tracker/joomla-cms/25823</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 6c8c523127856a7f4ff71d85986cc524a217ba6d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25823">issues.joomla.org/tracker/joomla-cms/25823</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25823">issues.joomla.org/tracker/joomla-cms/25823</a>.</sub>

**Comment by HLeithner** [comment]
Thank you for fixing the cache.

**Pull request merged**
