### PR TITLE
Add PHP 7.2 and 7.3 to AppVeyor

### PR DESCRIPTION
**Pull request by J0WI**
### Summary of Changes
This enables tests for PHP 7.2 and 7.3 to AppVeyor.
I also changed the downloads to use a secure connection.

There are no changes expected and no further testing is required to apply this patch.

Edit: I actually had to refactor some environment variables to ensure compatibility with each version. Fell free to squash my commits.

### CODE REVIEW

**Comment by HLeithner** [comment]
@rdeutz @yvesh can you comment this?

**Comment by ghost** [comment]
Reminder for @rdeutz @yvesh

**Comment by HLeithner** [comment]
Thx

**Pull request merged**
