### PR TITLE
[5.0] Find proper script for file uninstall

### PR DESCRIPTION
**Pull request by Hackwar**
Pull Request for Issue #19085.

### Summary of Changes
When uninstalling an extension of type `file` with a script file, the preflight, postflight and actual uninstall methods are not called. The (un)installer is loading the right manifest and even the right script file, but doesn't look for the right classname.

### Testing Instructions
Get a random extension of type `file` and add an install script by adding `<scriptfile>example.script.php</scriptfile>` to the manifest and for example the attached script file [example.script.php.txt](https://github.com/joomla/joomla-cms/files/9965468/example.script.php.txt) (You have to rename it and remove the .txt at the end. Also make sure that you adapt the scripts class name to your file extensions manifest name.)

### Actual result BEFORE applying this Pull Request
Installing shows `preflighttestpostflight` as install message. Uninstall doesn't show anything.

### Expected result AFTER applying this Pull Request
Both installing and uninstalling shows `preflighttestpostflight` as (un)install message.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by richard67** [comment]
Why for the 4.3-dev branch and not 4.2-dev? As far as I understand it's a bug fix.

**Comment by richard67** [comment]
Well I only asked in order to understand.

**Comment by richard67** [comment]
Why closed? Should we reopen the original  issue?

**Comment by HLeithner** [comment]
@MacJoom @laoneo would you like to move this to 4.4?

**Comment by laoneo** [comment]
Leave it as the branch is already updated.

**Comment by bembelimen** [comment]
I have tested this item :white_check_mark: successfully on 1e59233931b072428dfecd448eabbcda8429b517<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39180">issues.joomla.org/tracker/joomla-cms/39180</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 1e59233931b072428dfecd448eabbcda8429b517<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39180">issues.joomla.org/tracker/joomla-cms/39180</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
