### PR TITLE
[4.0] Capitalize "Hide all messages"

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
For consistency, capitalize "Hide all messages" button in toolbar.

### Testing Instructions
Click Post Installation Messages button.
See capitalization in button of toolbar.

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 1d7aba050e2e782bd22b4f2854f9b2561c471734<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34765">issues.joomla.org/tracker/joomla-cms/34765</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 1d7aba050e2e782bd22b4f2854f9b2561c471734<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34765">issues.joomla.org/tracker/joomla-cms/34765</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34765">issues.joomla.org/tracker/joomla-cms/34765</a>.</sub>

**Comment by brianteeman** [comment]
Please read the style guide and correct https://developer.joomla.org/en-gb-user-interface-text-guidelines/capitalisation.html

**Comment by richard67** [comment]
So the “all” should be lowercase because of “Do not capitalise joining words and words of three characters or less such as and, to, for.”. Sure we fulfill that everywhere?

**Comment by richard67** [comment]
Back to pending.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34765">issues.joomla.org/tracker/joomla-cms/34765</a>.</sub>

**Comment by Quy** [comment]
I would say `All` has significance here vs. `to`, `for`, etc. So you are ok with this?

`Hide all Messages`

**Comment by Quy** [comment]
or change to `Hide Messages`?

**Comment by richard67** [comment]
I'm not a native speaker and did not know our style guide in detail, so I hope @brianteeman can advise further.

**Comment by Quy** [comment]
Here are some strings with `All`.

COM_ASSOCIATIONS_PURGE="Delete All Associations"
COM_ACTIONLOGS_EXPORT_ALL_CSV="Export All as CSV"
COM_CATEGORIES_CATEGORIES_VIEW_DEFAULT_TITLE="List All Categories"

**Comment by richard67** [comment]
I had the same in mind and so to me this PR seemed to be ok as it is, also according to capitalization rules of famous newspapers who capitalize “All” in their titles.

**Comment by richard67** [comment]
But I don’t wanna argue with native speakers as I am not one.

**Comment by richard67** [comment]
Back to RTC due to @Quy 's findings above. See also e.g. https://capitalizemytitle.com/ , which suggest "Hide All Messages" in all available modes. They (and also other sources) say that pronouns are capitalized, and "All" is a kind of pronoun. I assume the Joomla style guide describes the rule in a (too much and so wrong?) simplified way and possibly needs to be corrected.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34765">issues.joomla.org/tracker/joomla-cms/34765</a>.</sub>

**Comment by brianteeman** [comment]
all those sources are for US english!! But do what you want. Styleguides seem optional in joomla and only relevant when the sun is in the vernal equinox

**Comment by richard67** [comment]
> all those sources are for US english!! But do what you want. Styleguides seem optional in joomla and only relevant when the sun is in the vernal equinox

@brianteeman So if the word "all" shall not be capitalized in titles or labels, why did you then make this PR? https://github.com/joomla/joomla-cms/pull/34416 ... it seems you only care for style guides when it concerns PR's of other people but not yours.

**Comment by brianteeman** [comment]
because it is different when there are only two words eg Check for Updates

**Comment by richard67** [comment]
> because it is different when there are only two words eg Check for Updates

@brianteeman Is that described somewhere in our style guide? I can't find anything about that here: https://developer.joomla.org/en-gb-user-interface-text-guidelines/capitalisation.html

**Comment by wilsonge** [comment]
@brianteeman so what are you saying it should be? `Hide all Messages` I assume from the styleguide page? It looks a bit weird to me but if that's at least consistent it is what it is

**Comment by Quy** [comment]
delete-all-associations

export-all

**Comment by richard67** [comment]
@brianteeman Please respond to @wilsonge 's question above https://github.com/joomla/joomla-cms/pull/34765#issuecomment-878999415 with respect to consistency with @Quy 's findings here https://github.com/joomla/joomla-cms/pull/34765#issuecomment-879384055 .

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
