### PR TITLE
[4.0] Privacy dashboard module

### PR DESCRIPTION
**Pull request by infograf768**
### Summary of Changes

Adapt mod_privacy_dashboard to j4 as was done here: https://github.com/joomla/joomla-cms/pull/24563

### Before patch
Screen Shot 2019-04-13 at 10 28 36

### After patch
Screen Shot 2019-04-13 at 10 15 55

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on c42b074ee26765b870aee9360474812e3ef7adaa<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24573">issues.joomla.org/tracker/joomla-cms/24573</a>.</sub>

**Comment by ghazal** [comment]
I have tested this item :white_check_mark: successfully on c42b074ee26765b870aee9360474812e3ef7adaa<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24573">issues.joomla.org/tracker/joomla-cms/24573</a>.</sub>

**Comment by ghost** [comment]
Status "Ready To Commit".

**Comment by wilsonge** [comment]
Conflicts please

**Comment by infograf768** [comment]
@wilsonge
I think it is better to wait as I have some problems displaying the module here
`Class 'Joomla\Component\Privacy\Administrator\Extension\PrivacyComponent' not found`

**Comment by infograf768** [comment]
I have to retest with a clean install

**Comment by infograf768** [comment]
Closing as replaced by https://github.com/joomla/joomla-cms/pull/24592

**Pull request closed without merging**
