### PR TITLE
[postgresql] fix sequence start value

### PR DESCRIPTION
**Pull request by alikon**
### Summary of Changes
fix sequence start value for `#__action_log_config` table

### Testing Instructions
code review

### CODE REVIEW

**Comment by richard67** [comment]
@alikon Should it not be 20? For all other tables the sequence number is equal to (last record + 1), and here last record is 19.

**Comment by alikon** [comment]
yes you are right, fixed

**Comment by richard67** [comment]
I am German, we are always right (except when starting world wars) ;-) (joking)

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on a88a135cec46570cb64399564ced04ca9ad65345<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22206">issues.joomla.org/tracker/joomla-cms/22206</a>.</sub>

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on a88a135cec46570cb64399564ced04ca9ad65345<br /><br />Code review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22206">issues.joomla.org/tracker/joomla-cms/22206</a>.</sub>

**Comment by richard67** [comment]
RTC please

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22206">issues.joomla.org/tracker/joomla-cms/22206</a>.</sub>

**Pull request merged**
