### PR TITLE
Add a hidden menuItem Search to blog sample data

### PR DESCRIPTION
**Pull request by chmst**
Pull Request for Issue #31678 .

### Summary of Changes
Add a menuItem Search to the bottom Menu, make this a horizontal menu.

@brianteeman r- adding / removing modules is kind of difficult, especially for module set in the installation process or by multilingual sample data. This could be another PR. 

### Testing Instructions
On a clean j4 installation install the blog sample data. 
Enter a searchstring into the search module and press search. 

### Actual result BEFORE applying this Pull Request
as described in #31678, a long url is generated

### Expected result AFTER applying this Pull Request
The url is like /index.php/search?q=adsf

### CODE REVIEW

**Comment by brianteeman** [comment]
I think you misunderstood me about modules - I wasnt suggesting adding or removing any

As for the menu item my suggestion was for it to be a HIDDEN menu item within the main menu. This way it showcased the hidden menu item feature as well as fixing the SEF url

**Comment by infograf768** [comment]
This patch correctly adds a hidden search menu in the Bottom menu. It is not a new module afaik.

Screen Shot 2020-12-17 at 17 10 13

Screen Shot 2020-12-17 at 17 11 41


we correctly get a link of the type
`http://localhost:8888/sample/joomla40/en/search?q=something`

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on cc9e520d1502e90c2b768fb10a7f0fa16275eb13<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31688">issues.joomla.org/tracker/joomla-cms/31688</a>.</sub>

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on cc9e520d1502e90c2b768fb10a7f0fa16275eb13<br /><br />Tested successfully in Beta6-dev of 17 December.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31688">issues.joomla.org/tracker/joomla-cms/31688</a>.</sub>

**Comment by infograf768** [comment]
rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31688">issues.joomla.org/tracker/joomla-cms/31688</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
