### PR TITLE
Add more single value headers to the singleValueResponseHeaders array in WebApplication

### PR DESCRIPTION
**Pull request by zero-24**
Pull Request for Issue https://github.com/zero-24/plg_system_httpheader/issues/9

### Summary of Changes

Add more single value headers to the singleValueResponseHeaders array in WebApplication

New headers added to the singleValueResponseHeaders array:
- pragma
- strict-transport-security
- content-security-policy
- content-security-policy-report-only
- x-frame-options
- x-xss-protection
- x-content-type-options
- referrer-policy
- expect-ct
- feature-policy

### Testing Instructions

- Install: https://github.com/zero-24/plg_system_httpheader/releases/tag/1.0.5
- enable progressive caching (System -> Global Configuration -> System -> System Cache)
- enable the system cache plugin
- visit the frontend
- refresh the page a few times

### Expected result

image

### Actual result

image

### Documentation Changes Required

none

### Side note

This is not limited to my plugin. Any other plugins setting that headers and even the core is affected by that bug (Pragma) in that specific caching case.

### Mention

thanks @f-hamel for finding and reporting this issue. 🎉

### CODE REVIEW

**Review by wilsonge — APPROVED** [review]

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 88cfd5c8b80d7563966c8ec2c9da4e671a5e8768<br /><br />Works fine.
No double headers anymore<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24429">issues.joomla.org/tracker/joomla-cms/24429</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on cbf4bf9bea4d7486dc0306141bd2db26e70b2ce1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24429">issues.joomla.org/tracker/joomla-cms/24429</a>.</sub>

**Comment by ghost** [comment]
@f-hamel can you please retest?

**Comment by HLeithner** [comment]
I tested it successful, thx

**Comment by zero-24** [comment]
Thanks

**Pull request merged**
