### PR TITLE
[4.0] Smart Search submenu

### PR DESCRIPTION
**Pull request by brianteeman**
Smart Search has a submenu called statistics and a toolbar button called statistics which are different things

This was originally changed with PR #26278 but was mistakenly reverted in error with #27032

### CODE REVIEW

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on e38f2d10cbe40d1458b7f61922630d3f603be8b0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31492">issues.joomla.org/tracker/joomla-cms/31492</a>.</sub>

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on e38f2d10cbe40d1458b7f61922630d3f603be8b0<br /><br />Tested successfully in Beta6-dev of 26 November<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31492">issues.joomla.org/tracker/joomla-cms/31492</a>.</sub>

**Comment by infograf768** [comment]
Do we need the same string in the .ini ?

**Comment by brianteeman** [comment]
It didnt appear so

**Comment by infograf768** [comment]
> It didnt appear so

then it looks like the .ini one can be deleted in this PR

**Comment by brianteeman** [comment]
After recent comments I am unwilling to remove any strings until that is clarified

**Comment by infograf768** [comment]
The string was wrongly added in https://github.com/joomla/joomla-cms/pull/27032/files#diff-12f24be81fa3503f61f2e45ec78f985d0b71500c1bfede514206bd72674d08bbR195 (line 195) to replace the submenu one which is now correctly in the sys.ini and righfully corrected by this PR. Nothing to do anyway with b/c.

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on d824125663bc1eaba80cffbadc98a41f3fe3c017<br /><br />Other tests are still OK as last change only concerns deleting a useless string<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31492">issues.joomla.org/tracker/joomla-cms/31492</a>.</sub>

**Comment by infograf768** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31492">issues.joomla.org/tracker/joomla-cms/31492</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
