### PR TITLE
[4.0] options sidebar

### PR DESCRIPTION
**Pull request by brianteeman**
Adds a more visible highlight for the active option

this is an scss change so dont forget to rebuild 

pr for #34305 
before

### CODE REVIEW

**Comment by Krshivam25** [comment]
I have tested this item :white_check_mark: successfully on b62ed891b6dd41f8b914d674f6be5e5607840dbc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34310">issues.joomla.org/tracker/joomla-cms/34310</a>.</sub>

**Comment by Quy** [comment]
Heading is not readable.

**Comment by Krshivam25** [comment]
@Quy Please test it again 
Screenshot (254)

**Comment by brianteeman** [comment]
@quy good spot - please retest

**Comment by Krshivam25** [comment]
@brianteeman Sorry I forget to type npm run build:css in terminal to rebuild the files.

**Comment by Quy** [comment]
Can you make the entire row clickable and not just text?

**Comment by brianteeman** [comment]
any suggestions

**Comment by Quy** [comment]
Add `display: block;` here should do the trick.

```
    a {
      font-weight: $font-weight-normal;
      color: var(--atum-text-dark);
      text-decoration: none;
```

Edit: This is an issue before the PR: Also there is flickering between cursor and hand when moving up and down through the items.

**Comment by brianteeman** [comment]
added the block - i can see the cursor thing but cant see the fix

**Comment by Quy** [comment]
Sorry I don't know either. Maybe @ciar4n can help fix it in a separate PR?

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on a9a5efa5cb7fca80d02674defc1235727db17494<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34310">issues.joomla.org/tracker/joomla-cms/34310</a>.</sub>

**Comment by PhilETaylor** [comment]
I have tested this item :white_check_mark: successfully on a9a5efa5cb7fca80d02674defc1235727db17494<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34310">issues.joomla.org/tracker/joomla-cms/34310</a>.</sub>

**Comment by PhilETaylor** [comment]
If you want to fix all the comments, and also make it look better, then use this:

```scss
// Sidebar

.sidebar-nav {
  padding: 1rem 0 1rem 2rem;

  li {
    width: 100%;
    font-size: .9rem;
    font-weight: $font-weight-bold;

    &.divider {
      margin: .3rem 0;
    }

    a {
      padding: .25rem;
      display: block;
      font-weight: $font-weight-normal;
      color: var(--atum-text-dark);
      text-decoration: none;

      &::before {
        margin-inline-end: .5rem;
        font-family: "Font Awesome 5 Free";
        font-weight: 900;
        content: "\f054";

        [dir="rtl"] & {
          content: "\f053";
        }
      }
    }

    &.item:hover, &.active {
      background-color: var(--atum-bg-dark-60);

      a {
        color: var(--atum-text-light);
      }
    }
  }
}

```

**Comment by PhilETaylor** [comment]
PR https://github.com/brianteeman/joomla-cms/pull/127/files

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 672fbc7ce513fedfa887807c1a4eaeb4f01daa4d<br /><br />Perfect!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34310">issues.joomla.org/tracker/joomla-cms/34310</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 672fbc7ce513fedfa887807c1a4eaeb4f01daa4d<br /><br />Thanks all for creating, comment and test the pull request.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34310">issues.joomla.org/tracker/joomla-cms/34310</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34310">issues.joomla.org/tracker/joomla-cms/34310</a>.</sub>

**Comment by chmst** [comment]
Thanks!

**Comment by brianteeman** [comment]
great thanks

**Pull request merged**
