### PR TITLE
adds missing dropdown icon

### PR DESCRIPTION
**Pull request by N6REJ**
Pull Request for Issue #41961 

### Summary of Changes

adds missing [5.0] Installation - select dropdown icon

### Testing Instructions

Clone 5.0-dev
Open installation page

### Actual result BEFORE applying this Pull Request
image

### Expected result AFTER applying this Pull Request
image

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
You need to add the rtl version as well

**Comment by N6REJ** [comment]
> You need to add the rtl version as well

thanks, didn't think it would have a different icon.

**Comment by richard67** [comment]
As the issue tracker is still down, I can't mark any test result.

We have a difference in the chevron colour between LTR and RTL.

LTR:
j5-test-pr-42018-ltr

RTL:
j5-test-pr-42018-rtl

But that's an issue with the atum template's svg file, too. The file added with this PR here have been copied from "build/media_source/templates/administrator/atum/images", and I can confirm that they are identical.

So I think that colour difference is a separate issue not related to or caused by this PR.

Besides this my test was successful.

**Comment by HLeithner** [comment]
Thx

**Comment by brianteeman** [comment]
_color_ fixed with #42024

**Pull request merged**
