### PR TITLE
[4.0] Installation DB Order

### PR DESCRIPTION
**Pull request by brianteeman**
Changes the order of the DB connections offered so that they appear as
MySQLi
MySQL (PDO)
PostgreSQL
PostgreSQL (PDO)

AND sets MySQLi as the default

Pull Request for Issue #19779

### After
chrome_2018-02-25_11-29-20

### CODE REVIEW

**Comment by infograf768** [comment]
i am absolutey not sure this is the solution. We should first be explained why the proposal for pdo exists and what it is supposed to solve. Also, these new possibilties should get a tip to explain that choice to users.

**Comment by laoneo** [comment]
Did somebody investigate why PDO fails and mysqli works? Is it because of a bug in the driver?

**Comment by brianteeman** [comment]
PDO is not new
chrome_2018-02-25_12-30-19

**Comment by brianteeman** [comment]
@laoneo just tried mysqli pdo and I just get the spinning logo although pdo installs fine on the same server for joomla 3
But thats a different issue to the one that this PR addresses which was just the ordering of the available options and the default

**Comment by infograf768** [comment]
https://github.com/joomla/joomla-cms/issues/19779
should be reopened as it describes 2 issues, one of them being the order, the other being that pdo is broken (and no explanation concerning pdo)

**Comment by brianteeman** [comment]
> and no explanation concerning pdo

Again I repeat - PDO is not new and is present in J3 - without explanation

**Comment by mbabker** [comment]
The PDO driver has been in core since 3.4.  You're just now noticing this?

The order is primarily drawn up by alphabetical order of the driver names.  In 3.x it's this:

mysql, mysqli, pdomysql

In 4.0 it's this:

mysql, mysqli

(Note that the Framework never supported a class for the deprecated `ext/mysql` and the "MysqlDriver" class is the PDO class)

**Comment by brianteeman** [comment]
@mbabker and this PR changes the order so that they are displayed as expected

**Comment by mbabker** [comment]
"Expected" is subjective 😉 (not saying this PR isn't fine, but what you expect to be first is probably different from what I expect)

**Comment by infograf768** [comment]
I must admit i never even looked at the possibilty of pdo as i was never informed of its usefulness.
If it is “better” to use it as default (and users are informed), it’s fine to leave it as first choice (when whatever is broken is solved evidently).

**Comment by infograf768** [comment]
Found what looked like "broken"
See https://github.com/joomla/joomla-cms/issues/19779#issuecomment-368418577

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 171b794eaefb0e5d5641ebb01a7178f36389f571<br /><br />Tested OK. I guess PDO is for specific needs and those who know that will choose it.

It is better to default to mysqli<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19780">issues.joomla.org/tracker/joomla-cms/19780</a>.</sub>

**Comment by mbabker** [comment]
> I guess PDO is for specific needs and those who know that will choose it.

No, not really.  It's almost the same as MySQL versus MySQLi on PHP 5 (before the former got deprecated).  It's just a different underlying API being used to process database transactions.  With our abstraction layer the only thing that should matter is whether you have the dependencies for each driver installed.  PDO's not some "super advanced special case" system (quite the opposite, most of the PHP ecosystem only uses or supports PDO based database connections, CMS' like Joomla and WordPress are the exception to this pattern where the non-PDO based PHP extensions are used more dominantly).

**Comment by infograf768** [comment]
You are most certainly right, but it is not explained to users installing new sites as we have no tip.

**Comment by dgrammatiko** [comment]
> but it is not explained to users installing new sites as we have no tip.

That needs to be in the requirements page of Joomla **NOT** in the db page of the installation

**Comment by brianteeman** [comment]
> The PDO driver has been in core since 3.4. You're just now noticing this?

Again I repeat - PDO is not new and is present in J3 - without explanation

**Comment by mbabker** [comment]
Times like this make me wish we would've accepted the "kill multi-db support" proposals, then we could just unplug everything but MySQLi and be done with it...

**Comment by brianteeman** [comment]
as the default is set at mysqli the order doesnt matter

**Pull request closed without merging**
