### PR TITLE
[4.2] Update 3rd party dependencies

### PR DESCRIPTION
**Pull request by SniperSister**
### Summary of Changes
Updating various 3rd party dependencies in composer and npm to make dependabot happy. 

### Testing Instructions
*  Check out the 4.2-dev branch
*  Run npm ci
*  Run composer install
* Try to install and use Jooma

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :red_circle: unsuccessfully on 56f6754fd04633a7be6bf74dd90554581f3e93fd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39433">issues.joomla.org/tracker/joomla-cms/39433</a>.</sub>

**Comment by brianteeman** [comment]
This pr is not complete. You need to run the build scripts locally and you will see that they generate additional changed files that you need to add to this PR as well. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39433">issues.joomla.org/tracker/joomla-cms/39433</a>.</sub>

**Comment by brianteeman** [comment]
In addition I can see at least one major library (codemirror) that has not been updated and is now at least 5 versions out of date despite our package.json allowing for it to be updated.

**Comment by SniperSister** [comment]
> This pr is not complete. You need to run the build scripts locally and you will see that they generate additional changed files that you need to add to this PR as well. 

Good catch, fixed!

**Comment by SniperSister** [comment]
> In addition I can see at least one major library (codemirror) that has not been updated and is now at least 5 versions out of date despite our package.json allowing for it to be updated.

The PR is not a generic "update all the things" PR, but specifically limited to dependencies that have received upstream security changes.

**Comment by brianteeman** [comment]
> The PR is not a generic "update all the things" PR, but specifically limited to dependencies that have received upstream security changes.

You are assuming that they all publish if an update is security related

**Comment by laoneo** [comment]
In maintainers we discussed this topic and came to the conclusion that general updates of dependencies should only be made in minor versions to ensure stability for the current release stream. Except when there are security issues, then this needs to be made in patch releases. This is not something Mr Jardin does now for fun, he follows the process.

**Comment by brianteeman** [comment]
It is still makling an assumption that is risky - but clearly I am in a minority. Would be good to see this policy documented as there is none for patch releases

**Comment by laoneo** [comment]
Agree that this needs to be better documented. For now this is mentioned in the meeting report here https://volunteers.joomla.org/teams/cms-maintenance-team/reports/1744-meeting-notes-june-08-2022.

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 7c3fd875b349a8d276f73830503bb7b1caf36eda<br /><br />does what it says<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39433">issues.joomla.org/tracker/joomla-cms/39433</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 7c3fd875b349a8d276f73830503bb7b1caf36eda<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39433">issues.joomla.org/tracker/joomla-cms/39433</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39433">issues.joomla.org/tracker/joomla-cms/39433</a>.</sub>

**Pull request merged**
