### PR TITLE
[4.0] Change duplicate label to span for extension name in extensions manager list view

### PR DESCRIPTION
**Pull request by richard67**
Pull Request for Issue [https://github.com/joomla/joomla-cms/pull/25642#issuecomment-513395666](https://github.com/joomla/joomla-cms/pull/25642#issuecomment-513395666) and [https://github.com/joomla/joomla-cms/pull/25642#issuecomment-513403795](https://github.com/joomla/joomla-cms/pull/25642#issuecomment-513403795).

### Summary of Changes

Change HTML element of the extension name from `<label>` to `<span>` in the extensions manager's list view because the check box to select the item is already a label for the same thing, and duplicate labels for same thing is invalid HTML.

See also the comment mentioned above as issue.

### Testing Instructions

Inspect with your browser's developer tools the HTML of the extensions manager's list view.

Check the label element just before the check box and then the extension name for a particular extension.

Or validate the page and check for duplicate label errors.

### Expected result

Only 1 label for the check box, which is the element before the check box, and the extension name is not another label for that.

### Actual result

1 label for the check box, which is the element before the check box, and the extension name is another label for that.

### Documentation Changes Required

None.

### CODE REVIEW

**Comment by richard67** [comment]
@Quy Done.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 2c8090ce1b2f4a7fa82c61239b92846dccb179c1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25696">issues.joomla.org/tracker/joomla-cms/25696</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 2c8090ce1b2f4a7fa82c61239b92846dccb179c1<br /><br />Should be correct with: <span **tabindex**="0">Banners</span>
OT: I had to enter the verification code.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25696">issues.joomla.org/tracker/joomla-cms/25696</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25696">issues.joomla.org/tracker/joomla-cms/25696</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by richard67** [comment]
Thanks.

**Pull request merged**
