### PR TITLE
Post-Install Messages ignores extensions records

### PR DESCRIPTION
**Pull request by demis-palma**
As long as at least one post-install message associated to Joomla exists, the control panel displays a warning and leads to com_postinstall.
There, all messages as shown, regardless of they are associated to Joomla or 3rd party extensions.
However, as soon as all the Joomla related messages are marked as read, the control panel no longer indicates that other post-installation messages are present.
Messages associated to 3rd party extension will not be notified in the control panel until at least one message associated to Joomla will added again.

### CODE REVIEW

**Comment by demis-palma** [comment]
Help. It seems that in this pull request I have included some outdated commits. How to remove them?

**Comment by Bakual** [comment]
Easiest is to just create a new clean branch and a new PR from there.

Personally I would argue that the cPanel should only show a notification for Joomla messages. And the extensions should show a notification for their own messages (which is simple to include). But I can understand your point of view as well.

**Comment by demis-palma** [comment]
Thanks, Bakual. I'll create a clear branch.
Can you please explain further "extensions should show a notification for their own messages"?
Do you mean by using post-install messages in a different way or using a different system for messages?

**Comment by Bakual** [comment]
If I were to use postinstall messages for my extension, I would include a notification similar to the cPanel one into the views of my extension.
It's only a few lines of code to do that notification text:
https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_cpanel/views/cpanel/view.html.php#L50-L59 in the view to check if there are messages and https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_cpanel/views/cpanel/tmpl/default.php#L32-L53 in the layout to show the message.
You need a line or two more to get the ID of your extension so you can adjust the eid in the calls. But other than that you can reuse that code.

**Comment by nikosdion** [comment]
You can also take a look in Akeeba Backup Core or Admin Tools Core. We use Post-installation Messages and we do show a notification inside our components based on whether there are published *and* active notifications.

**Pull request closed without merging**
