### PR TITLE
[4.0] Back to Dashboard string

### PR DESCRIPTION
**Pull request by brianteeman**
the string TPL_BACK_TO_CONTROL_PANEL was removed in error in the template repo. This PR puts it back and at the same ttime takes the opportunity to name it correctly as TPL_ATUM_BACK_TO_CONTROL_PANEL

The string is used for the link on the logo in the top corner

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 5e4bbb4d6169f0bfd04130bd96879da9948394b1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25935">issues.joomla.org/tracker/joomla-cms/25935</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 5e4bbb4d6169f0bfd04130bd96879da9948394b1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25935">issues.joomla.org/tracker/joomla-cms/25935</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25935">issues.joomla.org/tracker/joomla-cms/25935</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
