### PR TITLE
[4.1] codestyle Update web.config

### PR DESCRIPTION
**Pull request by brianteeman**
super pedantic but I spotted these extra spaces so might as well fix it

### CODE REVIEW

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 12dcce5148ed52b47507b9bb329865f4cd434b7b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37680">issues.joomla.org/tracker/joomla-cms/37680</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 12dcce5148ed52b47507b9bb329865f4cd434b7b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37680">issues.joomla.org/tracker/joomla-cms/37680</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37680">issues.joomla.org/tracker/joomla-cms/37680</a>.</sub>

**Comment by Quy** [comment]
Thanks

**Pull request merged**
