### PR TITLE
[4.1] Correcting Icon tooltip position for select menu item modal

### PR DESCRIPTION
**Pull request by hirakei1203**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/37467.

### Summary of Changes
In the Frontend, "Select a Menu Item" Modal, Menu Editing Page, 
the position of tooltip was moved to left to just below the tooltip target element.

### Testing Instructions
Log in frontend and check the tooltip position.

### Actual result BEFORE applying this Pull Request
image

### Expected result AFTER applying this Pull Request
image_fix_37467_after_khirano

This is my first PR to this Project!:) Thanks.

### CODE REVIEW

**Comment by Kostelano** [comment]
I have tested this item :white_check_mark: successfully on d9d2b21b31dcb8f44d7ba5f364a2035cc5384919<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37695">issues.joomla.org/tracker/joomla-cms/37695</a>.</sub>

**Comment by SumCompanyInc** [comment]
I have tested this item :white_check_mark: successfully on d9d2b21b31dcb8f44d7ba5f364a2035cc5384919<br /><br />i wasnt able to use the patch tester, but i was able to update using the download with patch, and it got the tooltip icon much more closer. but it wasnt centered, but that just nitpicking, it certainly much better than across the screen. great job! thanks! image<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37695">issues.joomla.org/tracker/joomla-cms/37695</a>.</sub>

**Comment by chmst** [comment]
RTC. Thank you @hirakei1203!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37695">issues.joomla.org/tracker/joomla-cms/37695</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
