### PR TITLE
[4.1] Fix Create/edit Procedure For Cron-based Scheduled Tasks

### PR DESCRIPTION
**Pull request by ditsuke**
Pull Request for Issue #36452.

### Summary of Changes
Fixes procedure to save/edit cron-based scheduled tasks.

### Testing Instructions
Create or edit an existing task with the "Cron Expression" execution rule.

### Actual result BEFORE applying this Pull Request
Creating or editing a cron-based task fails.

### Expected result AFTER applying this Pull Request
Creating or editing a cron-based task is successful

### Documentation Changes Required
`nil`

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 494704b003f070def16172d93c74b7af3ee7e445<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36927">issues.joomla.org/tracker/joomla-cms/36927</a>.</sub>

**Comment by khu5h1** [comment]
I have tested this item :white_check_mark: successfully on 494704b003f070def16172d93c74b7af3ee7e445<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36927">issues.joomla.org/tracker/joomla-cms/36927</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36927">issues.joomla.org/tracker/joomla-cms/36927</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
