### PR TITLE
[4.0][com_banners] - syntax error

### PR DESCRIPTION
**Pull request by alikon**
### Summary of Changes
fix syntax error 

code review

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 268c58e779d1323e5d93b789b8c58e702c061fd2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26525">issues.joomla.org/tracker/joomla-cms/26525</a>.</sub>

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on 268c58e779d1323e5d93b789b8c58e702c061fd2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26525">issues.joomla.org/tracker/joomla-cms/26525</a>.</sub>

**Comment by SharkyKZ** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26525">issues.joomla.org/tracker/joomla-cms/26525</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26525">issues.joomla.org/tracker/joomla-cms/26525</a>.</sub>

**Comment by richard67** [comment]
Thanks for fixing my bug. Shame on me that I haven't seen it.

**Comment by alikon** [comment]
np 
shit usually happens  the **Murphy's law** is always working fine :smile:

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
