### PR TITLE
[4.3] CSP Supplementary to #39726

### PR DESCRIPTION
**Pull request by dgrammatiko**
- Also intorduce the class `js-select-reset-on-change` that resets all the other filters except the target and submits the form

Pull Request for Issue #39726 .

### Summary of Changes
- Intorduces the class `js-select-reset-on-change` that resets all the other filters except the target and submits the form
- Fix the functionality for selects that are outside of the container `.js-stools-container-bar` and have either a class `js-select-reset-on-change` or `js-select-submit-on-change`

### Testing Instructions

Check the left most selects on the pages:
- administrator/index.php?option=com_menus&view=menus
- administrator/index.php?option=com_associations&view=associations
- administrator/index.php?option=com_languages&view=installed and all the other com_menus views
- administrator/index.php?option=com_modules&view=modules&client_id=0
- administrator/index.php?option=com_modules&view=modules&client_id=1
- administrator/index.php?option=com_templates&view=templates&client_id=0
- administrator/index.php?option=com_templates&view=templates&client_id=1
- administrator/index.php?option=com_templates&view=styles&client_id=0
- administrator/index.php?option=com_templates&view=styles&client_id=1

### Expected result AFTER applying this Pull Request

Works

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

@Quy

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 2c94343029dd5375861c0be9ebecdb72057a9c50<br /><br />THANK YOU!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39772">issues.joomla.org/tracker/joomla-cms/39772</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 2c94343029dd5375861c0be9ebecdb72057a9c50<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39772">issues.joomla.org/tracker/joomla-cms/39772</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39772">issues.joomla.org/tracker/joomla-cms/39772</a>.</sub>

**Comment by obuisard** [comment]
Thank you Dimitris @dgrammatiko, great work!

**Pull request merged**
