### PR TITLE
[4] Add dry-run and verbose/debug modes to update:joomla:remove-old-files cmd

### LINKED ISSUE #31901: [4][CLI] update:joomla:remove-old-files incorrectly states "files removed"
### Steps to reproduce the issue

Repeatedly run the CLI command 

`php cli/joomla.php update:joomla:remove-old-files`

### Expected result

After the first run (or even on the first run depending on the actual result) it should say NO files removed, because the command has NOT removed files. 

### Actual result

Command's success message always states that "Files removed" which is factually incorrect. Nothing was removed. 

Screenshot 2021-01-08 at 17 36 58

### System information (as much as possible)

```
PHP 7.4.13 (cli) (built: Dec 23 2020 11:21:05) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.13, Copyright (c), by Zend Technologies
```

### PR DESCRIPTION
**Pull request by PhilETaylor**
Closes #31901 replaces #31914

### Summary of Changes

Improvements to the `update:joomla:remove-old-files` CLI Command

 - Adds an option for `--dry-run`
 - Adds an output change for very verbose mode `-vv`
 - Adds an output change for debug mode `-vvv`

`--dry-run` option is a standard for all Symfony based commands that do destructive things. 

`-v` `-vv` `-vvv` options are a standard Symfony command option for increasing the verbosity to assist with debugging and gathering additional information from a command.

Also See https://github.com/joomla/joomla-cms/pull/31941 for a proposal to rename this command to `Joomla:update:cleanup` but this PR can be applied without that one. 

### Testing Instructions

run these commands to create yourself some folders and files to then go on to delete with the CLI from this PR:

```
touch administrator/components/com_actionlogs/actionlogs.php
touch administrator/components/com_actionlogs/controller.php
mkdir -p templates/system/images
mkdir -p templates/system/html
mkdir -p templates/protostar/less
mkdir -p templates/protostar/language/en-GB
mkdir -p templates/protostar/language
mkdir -p templates/protostar/js
mkdir -p templates/protostar/img
mkdir -p templates/protostar/images/system
```

Apply PR. 

Run these commands as a test of each new feature:

This command should show s summary, but not delete anything:
`php cli/joomla.php update:joomla:remove-old-files --dry-run`

Screenshot 2021-01-09 at 15 54 48

-- 

This command should show what files and folders will be deleted
` php cli/joomla.php update:joomla:remove-old-files --dry-run -vv`

Screenshot 2021-01-09 at 15 56 24

-- 

This command should show what files and folders are checked and what will be deleted (output is huge, so screenshots below are snipped to show important bits)
` php cli/joomla.php update:joomla:remove-old-files --dry-run -vvv`

Screenshot 2021-01-09 at 15 57 42

Screenshot 2021-01-09 at 15 57 53

-- 

You can then set up your folders/files with the test script above, and run any of these commands to ACTUALLY DELETE the files and folders. 

`php cli/joomla.php update:joomla:remove-old-files`

Screenshot 2021-01-09 at 15 58 42

`php cli/joomla.php update:joomla:remove-old-files -vv`

Screenshot 2021-01-09 at 16 00 27

and lastly `php cli/joomla.php update:joomla:remove-old-files -vvv` but Im not going to show that output as its huge and meant for debugging. 

### Actual result BEFORE applying this Pull Request

Screenshot 2021-01-09 at 16 02 23

### Expected result AFTER applying this Pull Request

As explained above

### CODE REVIEW

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on 0a2266dd3843a93e00e1c363d51435512d544444<br /><br />Tested successfully in Beta7-dev of 9 January.

PHP notices were reported each time the remove-old-files command was run
Notice: Undefined variable: supressOutput in C:\www\joomla4\administrator\components\com_admin\script.php on line 6275
Notice: Undefined variable: supressOutput in C:\www\joomla4\administrator\components\com_admin\script.php on line 6280
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31943">issues.joomla.org/tracker/joomla-cms/31943</a>.</sub>

**Comment by PhilETaylor** [comment]
supressOutput was renamed suppressOutput - sorry

**Review by wilsonge — APPROVED** [review]
Love it. Needs tests. But good job!

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on 3f9d3ce002d90c533b1fa2d5ceba80de6a6a6d41<br /><br />Works as described. But at the delete stage - best to delete with the -vv option first!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31943">issues.joomla.org/tracker/joomla-cms/31943</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31943">issues.joomla.org/tracker/joomla-cms/31943</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 3f9d3ce002d90c533b1fa2d5ceba80de6a6a6d41<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31943">issues.joomla.org/tracker/joomla-cms/31943</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31943">issues.joomla.org/tracker/joomla-cms/31943</a>.</sub>

**Comment by PhilETaylor** [comment]
> @ceford Works as described. But at the delete stage - best to delete with the -vv option first!

Well not that level of control is in the hands of the person running the commands to delete things. Before there was no feedback at all. :-) 

If you mean for testing this PR, then yes, you will need to run the creation commands to give you some test files/folders to delete after every delete (non --dry-run) command to give something for the next delete command to actually delete.

**Comment by ceford** [comment]
Sorry if my comment seemed unkind. It was meant for other testers. The testing instructions were excellent - amongst the best I have encountered.

**Comment by PhilETaylor** [comment]
Not unkind at all - I never took it that way at all :) Thanks for testing.

**Comment by drmenzelit** [comment]
Thanks

**Pull request merged**
