### PR TITLE
[4.0] Change com_config to services

### PR DESCRIPTION
**Pull request by laoneo**
Pull Request for Issue #20481, #20356 and #20484.

#20619 needs to be merged first!!

Moves com_config to the service based extension setup.

See #20217 for details.

### CODE REVIEW

**Comment by brianteeman** [comment]
because #20619 needs to be merged first according to the test instructions this cannot be tested with com_patchtester

**Comment by laoneo** [comment]
Why do you can't test it with patch tester? Is there an error?

**Comment by infograf768** [comment]
> Why do you can't test it with patch tester? Is there an error?

afaik patchtester can't move files around.

**Comment by laoneo** [comment]
Ok, here is a link to the branch where you can download joomla directly https://github.com/Digital-Peak/joomla-cms/archive/j4/services/config.zip

**Comment by brianteeman** [comment]
it cant be tested with patchtester as you say it needs #20619 installed first and as this also touches one of the same files patchtester prevents this one being applied

**Comment by laoneo** [comment]
#20619 is included in this pr as well, otherwise I couldn't develop it either

**Comment by brianteeman** [comment]
ah - then your message was confusing

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 13bf706017bf44a60f52314d95985e4de0dc385b<br /><br />Tested the admin and works
Tested the site config and template config from front end and previous issues are resolved by this pr<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20620">issues.joomla.org/tracker/joomla-cms/20620</a>.</sub>

**Pull request merged**
