### PR TITLE
[4.0] Fix creating new file/folder in template manager

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/26172.

### Summary of Changes

Use correct elements in JS.

### Testing Instructions

`node build.js --compile-js` required after applying patch.

Edit a template.
Click `Manage Folders`.
In the modal click on an icon next to a folder.
Enter a folder name and click `Create`.
Click `New File`.
In the modal click on an icon next to a folder.
Enter a file name and click `Create`.

### Expected result

File/folder created in selected folders.

### Actual result

File/folder created in template's root folder.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 26d54e976a428e312bb9d2aaf2586a063f4dc6db<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27742">issues.joomla.org/tracker/joomla-cms/27742</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 26d54e976a428e312bb9d2aaf2586a063f4dc6db<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27742">issues.joomla.org/tracker/joomla-cms/27742</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27742">issues.joomla.org/tracker/joomla-cms/27742</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
