### PR TITLE
selectively hide extension updates

### PR DESCRIPTION
**Pull request by BRoehling**
Pull Request for Issue # .

### Summary of Changes

i don't know if this was discussed before, but it might be useful for some joomla users to have the option
to selectively hide extension updates. in my case for updates for which I don't need an update.
if you like this idea, it could be implemented in joomla 3.9.x and 4.x
### Testing Instructions

-

### Actual result BEFORE applying this Pull Request

no option available

### Expected result AFTER applying this Pull Request

option available

### Documentation Changes Required

yes (if it's implemented)

### CODE REVIEW

**Comment by zero-24** [comment]
hi @BRoehling it seems you are merging staging into 3.10 please double check the branch that you mad your changes and send a PR with that changes ;)

**Comment by BRoehling** [comment]
am I in the proper sector? I want to tell the joomla core developers to think about the idea of implementing an extension update selective hide option.

**Comment by zero-24** [comment]
Sure but you sended a PR did you just wanted to open a feature request? Or do you have code already?

**Comment by BRoehling** [comment]
I'm not a joomla core developer. I want to point to a new feature in Joomla

**Comment by zero-24** [comment]
Ok so please go here https://github.com/joomla/joomla-cms/issues/new and create an feature request and close this PR here.

So we can keep track of that feature request.

**Pull request closed without merging**
