### PR TITLE
set() returns the old value of the variable

### PR DESCRIPTION
**Pull request by GABBAR1947**
Pull Request for Issue #8859 

Testing instructions remain the same as referenced in the issue:
 $session = JFactory::getSession();
 $session->set('test', 1);
 echo $session->set('test', 2);

### CODE REVIEW

**Comment by wilsonge** [comment]
Adding 3.5 blocking tag on this as it's a b/c break introduced in 3.4.8

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 114ccb1727de2562a932c3629c9b3d0624184a80<br /><br />Tested with success with code snippet provided here and in #8859 and with more detailed test instructions from #8859 .

Works as described.

The code change makes sense when reading, too.

But since I am not expert in Joomla! session handling I cannot judge if the documentation and this PR are correct (very likely), or if maybe the change in how the function works was by purpose (very unlikely, just wanted to mention that).<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9276">issues.joomla.org/joomla-cms/9276</a>.</sub>

**Comment by wilsonge** [comment]
It wasn't on purpose - I can confirm that!

**Comment by richard67** [comment]
Then this PR here seems to solve it in the right way, yes?

**Comment by wilsonge** [comment]
This is definitely the right thing to do - just needs 1 more test :P

**Comment by richard67** [comment]
@wilsonge What is strange is that on GitHub in this PR, there are 2 bad commits always shown at the end as done just now here in the conversation tab and also in the commits tab, but when looking at the changed files in this PR they seem to be outdated, and the final result of this PR looks good regarding code style, what these 2 commits don't. So there seems to be something wrong with display here (maybe a NULL date in the point of time of these 2 commits in GitHub?). On the issue tracker the history looks OK.

Looks like a GitHub problem, not related to this PR. Just wanted to mention.

**Comment by Kubik-Rubik** [comment]
@GABBAR1947 It seems like you've messed up the commits. Could you please create a new, clean PR with only the session change? Once done, please reference on this PR and close it. Thanks!

**Comment by richard67** [comment]
@Kubik-Rubik Hmm, I hope he not missunderstood and closed without redo.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9276">issues.joomla.org/joomla-cms/9276</a>.</sub>

**Comment by GABBAR1947** [comment]
@richard67 No, I'm coming up with a new one. Actually the moment I commit the code, there appears to be an indentation issue.

**Comment by wilsonge** [comment]
Yah I noticed that in some other github PR's as well - as you say likely a github issue - I guess we just have to wait for them to clear it up :/

**Comment by GABBAR1947** [comment]
https://github.com/joomla/joomla-cms/pull/9284/commits

**Comment by GABBAR1947** [comment]
https://github.com/joomla/joomla-cms/pull/9285

**Pull request closed without merging**
