### PR TITLE
[Regression] Readded stuff from #10190

### PR DESCRIPTION
**Pull request by bembelimen**
Pull Request for Issue #9814
#### Summary of Changes

Add batch check again
#### Testing Instructions

Apply patch => Choose "All menu items" => check batch

### CODE REVIEW

**Comment by infograf768** [comment]
Please take care of formatting in the batchcopy regression.
Spaces instead of tabs
I also have indented after the conditional in my original PR

**Comment by infograf768** [comment]
@bembelimen 
Can you merge
https://github.com/bembelimen/joomla-cms/pull/5 as we also need the correct code for the footer

**Comment by infograf768** [comment]
BTW, Travis error has nothing to do with this PR.

**Comment by bembelimen** [comment]
Thanks @infograf768

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 6dc251560467d8e976d8eeecdda4c08272d91088<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10281">issues.joomla.org/joomla-cms/10281</a>.</sub>

**Comment by infograf768** [comment]
rtc, as this a regression.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10281">issues.joomla.org/joomla-cms/10281</a>.</sub>

**Comment by infograf768** [comment]
please add milstone to 3.6.0 and merge. thanks

**Pull request merged**
