### PR TITLE
Minor improvement to JViewLegacy

### PR DESCRIPTION
**Pull request by joomdonation**
#### Summary of Changes

This PR makes a small change to _addPath method of JViewLegacy. There is no reason for running jimport command inside the loop, I just move that comand out side of for each loop
#### Testing Instructions

This can be merged by code review.

### CODE REVIEW

**Comment by wojsmol** [comment]
@joomdonation See https://github.com/joomdonation/joomla-cms/pull/2

**Comment by joomdonation** [comment]
Thanks @wojsmol. I didn't see your PR, so I fixed the CS issue myself. Hope it is OK now

**Comment by bembelimen** [comment]
I have tested this item :white_check_mark: successfully on b8e1a03aa9771e27aa5615dad608d127a90c55a6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9969">issues.joomla.org/joomla-cms/9969</a>.</sub>

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on b8e1a03aa9771e27aa5615dad608d127a90c55a6<br /><br />on code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9969">issues.joomla.org/joomla-cms/9969</a>.</sub>

**Pull request merged**
