### PR TITLE
module assignment

### PR DESCRIPTION
**Pull request by brianteeman**
I find the labels used in the column to show where the module is assigned is unclear. This PR changes the strings a little. 

Before
before

After
after

### CODE REVIEW

**Comment by zero-24** [comment]
@test success<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5813">issues.joomla.org/joomla-cms/5813</a>.</sub>

**Comment by wilsonge** [comment]
I personally think all except selected is clear. I agree with moving selected only to just selected though

**Comment by brianteeman** [comment]
I'm not bothered about that one. Anyone else have a comment?

**Comment by anibalsanchez** [comment]
@test success

@brianteeman Just wondering .. (I am not native english speaker) ... "Only on the pages selected"... should be "Only on the selected pages"?
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5813">issues.joomla.org/joomla-cms/5813</a>.</sub>

**Comment by brianteeman** [comment]
Yes that is better/correct english

**Comment by pe7er** [comment]
@test
This PR changes the labels in the Module Manager overview page " Module Manager: Modules".
IMHO these new shorter styles are better...

**Comment by infograf768** [comment]
"All except selected" should stay imho.

**Comment by nternetinspired** [comment]
Less text is better text IMO, this is a good change.

**Comment by brianteeman** [comment]
Because I really wanted to get the confusing "Selected only" changed I am updating the PR to remove the change to "all except selected" instead of the entire PR getting delayed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5813">issues.joomla.org/joomla-cms/5813</a>.</sub>

**Comment by brianteeman** [comment]
Update done and setting to RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5813">issues.joomla.org/joomla-cms/5813</a>.</sub>

**Pull request merged**
