### PR TITLE
[4.2] unification YubiKey vs Yubikey

### PR DESCRIPTION
**Pull request by tecpromotion**
### Summary of Changes

Unified spelling of the word YubiKey.

### Testing Instructions

.

### Actual result BEFORE applying this Pull Request

Mix of YubiKey and Yubikey

### Expected result AFTER applying this Pull Request

YubiKey

### Documentation Changes Required

.

### CODE REVIEW

**Comment by richard67** [comment]
@roland-d Should @tecpromotion revert the changes in the 2 "plg_twofactorauth_yubikey*.ini" files because those will be merged up later from 4.1-dev when his PR #38037 has bee merged into the 4.1-dev branch, and having the same changes here will cause a merge conflict? Or are you ok with that?

**Comment by roland-d** [comment]
@richard67 That should be OK, because the same lines are changed Git will know what to do with it. If not, I can fix the merge conflict, should be easy.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 9438f512d6f953143ab6e5ac96e607187ec5ae3c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38036">issues.joomla.org/tracker/joomla-cms/38036</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 9438f512d6f953143ab6e5ac96e607187ec5ae3c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38036">issues.joomla.org/tracker/joomla-cms/38036</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38036">issues.joomla.org/tracker/joomla-cms/38036</a>.</sub>

**Comment by roland-d** [comment]
Thanks everybody

**Pull request merged**
