### PR TITLE
[com_media] Alignment and spacing fixes

### PR DESCRIPTION
**Pull request by ciar4n**
Pull Request for Issue # .

### Summary of Changes
General alignment and spacing fixes to the media manager

### Testing Instructions
Apply patch and navigate to media manager. Ensure that elements are in line with each other. Navigate to a sub folder and ensure the back button is vertically centered within its container.

### Before Patch
media1

### After Patch
media2

### Documentation Changes Required
None

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on b51d2292f0513b5327df61178c0c053dff1dc840<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14506">issues.joomla.org/tracker/joomla-cms/14506</a>.</sub>

**Comment by brianteeman** [comment]
@ciar4n can you resolve the conflicts please AND it would be helpful if you could highlight what has changed on the images  so that testers can confirm all the changes - thanks

**Comment by ciar4n** [comment]
Conflicts fixed and testing instructions updated.

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on c515e75889e46c4efd868e808b3680e769f6cd9a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14506">issues.joomla.org/tracker/joomla-cms/14506</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on c515e75889e46c4efd868e808b3680e769f6cd9a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14506">issues.joomla.org/tracker/joomla-cms/14506</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Pull request merged**
