### PR TITLE
3.5.0 Beta. Regression: Fixes #8637. Contacts. Ordering by headline defect.

### LINKED ISSUE #8637: Beta 3.5.0 Contacts ordering by headline click not working
Test:
Install Beta 3.5.0.
Go to Components > Contacts.
Try to order colums by clicking on headlines.
No reaction.

Firefox console:
> TypeError: r.filter_order is undefined core.js:1:2443

This is line 272 in core.uncompressed.js
https://github.com/joomla/joomla-cms/blob/staging/media/system/js/core-uncompressed.js#L272-L274

### PR DESCRIPTION
**Pull request by ghost**
Issue: https://github.com/joomla/joomla-cms/issues/8637

Test:
Install Beta 3.5.0.
Go to Components > Contacts.
Try to order colums by clicking on headlines.
No reaction.

Apply patch.
Try again

### CODE REVIEW

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 4fd8ea9d3715dd992dc6cf3dd08ea6bc79f5d31e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8638">issues.joomla.org/joomla-cms/8638</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 4fd8ea9d3715dd992dc6cf3dd08ea6bc79f5d31e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8638">issues.joomla.org/joomla-cms/8638</a>.</sub>

**Comment by infograf768** [comment]
Added Regression to title<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8638">issues.joomla.org/joomla-cms/8638</a>.</sub>

**Comment by waader** [comment]
I have tested this item :white_check_mark: successfully on 4fd8ea9d3715dd992dc6cf3dd08ea6bc79f5d31e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8638">issues.joomla.org/joomla-cms/8638</a>.</sub>

**Comment by brianteeman** [comment]
Thanks for testing - setting RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8638">issues.joomla.org/joomla-cms/8638</a>.</sub>

**Pull request merged**
