### PR TITLE
[4.3] Guided Tours module sort

### PR DESCRIPTION
**Pull request by brianteeman**
### Summary of Changes
Removes the automatic sorting on the All Tours display.

The problem with the sort is that it is based on the component value eg [com_contact] and not a language value. This results in an ordering that makes no sense in any languatge and also ignores any ordering that is set in the actual component

### Testing Instructions
apply pr

### Actual result BEFORE applying this Pull Request
image

### Expected result AFTER applying this Pull Request
image

You can then if you want to change the ordering of the tours and it will be reflected in the module

image

image

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 60864560bb89f2a5d1d3e4bd9bf3ef55a5223963<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40087">issues.joomla.org/tracker/joomla-cms/40087</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 60864560bb89f2a5d1d3e4bd9bf3ef55a5223963<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40087">issues.joomla.org/tracker/joomla-cms/40087</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40087">issues.joomla.org/tracker/joomla-cms/40087</a>.</sub>

**Comment by formfranska** [comment]
I have tested this item :white_check_mark: successfully on 60864560bb89f2a5d1d3e4bd9bf3ef55a5223963<br /><br />I have tested this sucessfully.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40087">issues.joomla.org/tracker/joomla-cms/40087</a>.</sub>

**Comment by obuisard** [comment]
Thank you Brian @brianteeman

**Comment by brianteeman** [comment]
thx

**Pull request merged**
