### PR TITLE
[4.0] Fix custom select missing icon on focus

### PR DESCRIPTION
**Pull request by Quy**
Pull Request for Issue #27543.

### Summary of Changes
Fix custom select missing icon on focus.

### Testing Instructions
Click Post Installation in the upper right corner
Look at the `Showing messages for` dropdown
Click it
You'll notice the arrow icon disappears

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 9ba546f9c3c35da7d1645c4846d356d1227cb5a2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27544">issues.joomla.org/tracker/joomla-cms/27544</a>.</sub>

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on 9ba546f9c3c35da7d1645c4846d356d1227cb5a2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27544">issues.joomla.org/tracker/joomla-cms/27544</a>.</sub>

**Comment by SharkyKZ** [comment]
RTC.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27544">issues.joomla.org/tracker/joomla-cms/27544</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
