### PR TITLE
[bump.php] Replace also __DEPLOY_VERSION__ by the build release

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Summary of Changes

This PR updates bump.php to replace the string `__DEPLOY_VERSION__` by the current release (if needed).
#### Testing Instructions
1. Change a since tag in any php file to `__DEPLOY_VERSION__`.
2. Run `php build/bump.php -v 3.6.0-beta2` (or current version, if other)
3. Check the since tag in the file you changed before is now `3.6.0`.
#### Observations

This allow to not worry anymore about the since tag. Just but `__DEPLOY_VERSION__` on the PR code and when a version bump is done it will be replaced by the release version.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :red_circle: unsuccessfully on c2407f96da4ccb2c0841055a6ed322a1a8f30b58<br /><br />## With Patch 
brians-MacBook-Air:github-joomla-cms brian1$ php build/bump.php -v 3.6.0-beta2

Version data:
- Main:			3.6
- Release:		3.6.0
- Full:			3.6.0-beta2
- Build:		
- Dev Level:		0-beta2
- Dev Status:		Beta
- Release date:		21-June-2016
- Release time:		10:53
- Release timezone:	GMT
- Creation date:	June 2016


Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 151553344 bytes) in /Applications/MAMP/htdocs/github-joomla-cms/build/bump.php on line 305

## Without patch
brians-MacBook-Air:github-joomla-cms brian1$ php build/bump.php -v 3.6.0-beta2

Version data:
- Main:			3.6
- Release:		3.6.0
- Full:			3.6.0-beta2
- Build:		
- Dev Level:		0-beta2
- Dev Status:		Beta
- Release date:		21-June-2016
- Release time:		10:53
- Release timezone:	GMT
- Creation date:	June 2016

Version bump complete!
brians-MacBook-Air:github-joomla-cms brian1$ 
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10883">issues.joomla.org/joomla-cms/10883</a>.</sub>

**Comment by andrepereiradasilva** [comment]
i don't think it's a pre-requisite for bump.php to work on php memory limit of 128MB :)

**Comment by brianteeman** [comment]
Increased memory to 512M to remove that error
Changed 
 * @since  1.6
to
 * @since  __DEPLOY_VERSION__

ran script - no error - no change in the edited file

**Comment by andrepereiradasilva** [comment]
no change ? are you sure? what is the output of the script?

**Comment by brianteeman** [comment]
brians-MacBook-Air:github-joomla-cms brian1$ /Applications/MAMP/bin/php/php5.5.26/bin/php build/bump.php -v 3.6.0-beta2

Version data:
- Main:			3.6
- Release:		3.6.0
- Full:			3.6.0-beta2
- Build:		
- Dev Level:		0-beta2
- Dev Status:		Beta
- Release date:		21-June-2016
- Release time:		11:53
- Release timezone:	GMT
- Creation date:	June 2016

**Comment by andrepereiradasilva** [comment]
what is the file you changed?

**Comment by brianteeman** [comment]
Changed two
administrator/components/com_admin/controllers/profile.php 
plugins/system/highlight/highlight.php

**Comment by andrepereiradasilva** [comment]
ok will test those

**Comment by andrepereiradasilva** [comment]
```console
[user@host build]# php bump.php -v 3.6.0-beta2

Version data:
- Main:                 3.6
- Release:              3.6.0
- Full:                 3.6.0-beta2
- Build:
- Dev Level:            0-beta2
- Dev Status:           Beta
- Release date:         21-June-2016
- Release time:         12:03
- Release timezone:     GMT
- Creation date:        June 2016

- Since Version changed in 2 files.

Version bump complete!
```

Are you sure you added `__DEPLOY_VERSION__`?

**Comment by brianteeman** [comment]
yes and I just tried again with a copy paste

**Comment by andrepereiradasilva** [comment]
brian i can't reproduce your issue.

**Comment by brianteeman** [comment]
Just checked php error log and that still shows a memory error even though its not logged to the screen - weird - must be me

**Comment by roland-d** [comment]
I have tested this item :white_check_mark: successfully on c2407f96da4ccb2c0841055a6ed322a1a8f30b58<br /><br />After applying the patch the __DEPLOY_VERSION__ has been changed to 3.6.0 as expected. I did have to increase memory to 512MB to get the bump script to work though ;)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10883">issues.joomla.org/joomla-cms/10883</a>.</sub>

**Pull request merged**
