### PR TITLE
Fix logout redirect error

### PR DESCRIPTION
**Pull request by joomdonation**
Pull Request for Issue #14826 .

### Summary of Changes
See https://github.com/joomla/joomla-cms/issues/14826 for explaination of the issue. This PR is an attempt to fix it

### Testing Instructions
1. See https://github.com/joomla/joomla-cms/issues/14826 , confirm the issue

2. Apply patch, check it again, confirm the issue fixed

@Hackwar Not sure if this is a proper fix? Could you please review?

### Documentation Changes Required
None

### CODE REVIEW

**Comment by AlexRed** [comment]
I have tested this item :white_check_mark: successfully on f5213c28c18f4fe47e31da6a212ed0c2d17df48b<br /><br />Patch ok for me<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14836">issues.joomla.org/tracker/joomla-cms/14836</a>.</sub>

**Comment by stellainformatica** [comment]
I have tested this item :white_check_mark: successfully on f5213c28c18f4fe47e31da6a212ed0c2d17df48b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14836">issues.joomla.org/tracker/joomla-cms/14836</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC as there are 2 successfully Tests?

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14836">issues.joomla.org/tracker/joomla-cms/14836</a>.</sub>

**Pull request merged**
