### PR TITLE
fixed missing own asset rule for parent recursive get access rule

### PR DESCRIPTION
**Pull request by julienV**
Pull Request for Issue # .

### Summary of Changes
Fixed a failing strict comparison operator, which prevents parent recursive asset rule to work properly
`self::$assetPermissionsParentIdMapping[$extensionName][$id]` is the result of a database query, so the type of `self::$assetPermissionsParentIdMapping[$extensionName][$id]->id` is string.
`$assetId` if an integer, so the test result is false, but it should be true...

selection_168

### Testing Instructions
Not easy to test, as this parameters don't seem to be use directly in joomla core...

### Documentation Changes Required
none

### CODE REVIEW

**Comment by csthomas** [comment]
IMO It would be better to set this more explicitly, I mean using `(int) $a !== $b`. I know that does not change anything in php but for people it is more explicit.

**Comment by julienV** [comment]
sure, i can change it to 
`(int) self::$assetPermissionsParentIdMapping[$extensionName][$id]->id`, but does it really makes it more readable ? the variable name is so long, you don't really see the type casting.

**Comment by ggppdk** [comment]
> sure, i can change it to
(int) self::$assetPermissionsParentIdMapping[$extensionName][$id]->id, but does it really makes it more readable ? the variable name is so long, you don't really see the type casting.

it a not only about readability, which i argue it is quite readable , it is not too long,
it will also make clear to people looking at the code in the future what the comparison does, thus avoid the bug being re-introduced by future modifications

**Comment by julienV** [comment]
@ggppdk i added the casting to int

**Review by mbabker — APPROVED** [review]

**Comment by mbabker** [comment]
All this critique about type casting and no follow on...

(Needs merge conflicts resolved)

**Comment by julienV** [comment]
there was no conflict, merging of staging branch went fine...

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on fc4d25578f5be94105b1a9be721b2e6990517030<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17009">issues.joomla.org/tracker/joomla-cms/17009</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17009">issues.joomla.org/tracker/joomla-cms/17009</a>.</sub>

**Comment by HLeithner** [comment]
Finally a happy end. Thanks

**Pull request merged**
