### PR TITLE
[4.1] Fix nested items re-ordering

### PR DESCRIPTION
**Pull request by joomdonation**
Pull Request for Issue #37778.

### Summary of Changes
Make small change to draggable script to solve the re-ordering  nested items (menu items, categories...) as reported https://github.com/joomla/joomla-cms/issues/37778 .

### Testing Instructions
- Use Joomla 4.1.3 (or 4.1 nightly build)
- Look at https://github.com/joomla/joomla-cms/issues/37778 , confirm the issue
- Upgrade your site to the download package generated for this PR.
- Confirm the issue fixed. 
- Please try to re-order other items like articles, modules, categories and make sure the ordering are saved properly, too

### CODE REVIEW

**Comment by joomdonation** [comment]
For some reasons, the upgrade packages generated for this PR does not contains change for the JS files. So to test this PR, please get the attached zip file, unzip it, and upload the received files to **media/system/js** folder on your Joomla installation to have the change applied.
[draggable.zip](https://github.com/joomla/joomla-cms/files/8675148/draggable.zip)

**Comment by fredhob** [comment]
Hi,

I replace files with yours and clean browser cache but the issue stay. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37781">issues.joomla.org/tracker/joomla-cms/37781</a>.</sub>

**Comment by joomdonation** [comment]
@fredhob Thanks for trying. I don't know why it is not working for you because on my local installation, it worked OK for me.

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 4879f662f6412e8d3a1ff3569f8d53ad30aaf987<br /><br />patched my local branch and rebuilt the js

The menu sort and re-order now works as expected<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37781">issues.joomla.org/tracker/joomla-cms/37781</a>.</sub>

**Comment by fredhob** [comment]
Yes it's work for me now too, it's weird but thanks a lot!

**Comment by joomdonation** [comment]
@fredhob The only reason is that the js files were cached and it took sometime for your browser to load the updated files. I'm glad it works for you now.

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37781">issues.joomla.org/tracker/joomla-cms/37781</a>.</sub>

**Comment by laoneo** [comment]
Thanks!

**Comment by Sandvelder** [comment]
Hi, I copied the contents of the ZIP file to media/system/js but to no avail. Should I do anything other than copying the files in that directory?
Regards,<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37781">issues.joomla.org/tracker/joomla-cms/37781</a>.</sub>

**Comment by joomdonation** [comment]
@Sandvelder After copying the files, please clear browser cache and the issue should be sorted.

**Comment by Sandvelder** [comment]
Thank you, it worked!

**Pull request merged**
