### PR TITLE
[Regression] Delete button on the media manager doesn't work anymore

### LINKED ISSUE #7336: [Regression] Delete button on the media manager don't work after update to 3.4.2/3
#### Steps to reproduce the issue

Go to com_media
select (using the checkboxes at the images) some images
try to hit the delete button.

#### Expected result

In 3.4.1 all images gets deletet.

#### Actual result

In 3.4.2/3 nothing happens

#### Additional comments

The delete button can  be found here:
https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_media/views/media/view.html.php#L142-149

That calls a layout: https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_media/layouts/toolbar/deletemedia.php

So that button call this: https://github.com/joomla/joomla-cms/blob/staging/media/media/js/mediamanager.js#L39

But I'm not sure what is the next step or what fails as it looks correct for me.

#### References (german)
http://www.joomla-bugs.de/forum/index.php/topic,677.0.html
and
http://forum.joomla.de/index.php/Thread/535-kleines-Problem-mit-Medien-Manager-bei-Joomla-3-4-3/

### PR DESCRIPTION
**Pull request by dgrammatiko**
#### The problem:

Go to com_media
select (using the checkboxes at the images) some images
try to hit the delete button.

Expected result
deleting images.

Actual result
Console error
#### Testing

Apply patch
follow the steps above
Verify that you get the expected result: images are trashed.

### CODE REVIEW

**Comment by jwaisner** [comment]
@test 

PR resolves issue with the delete button not working.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7338">issues.joomla.org/joomla-cms/7338</a>.</sub>

**Comment by smz** [comment]
#Test OK

**Unrelated:** I just noticed that folders containing blanks in their names are inaccessible by com_media, but I think I've seen this issue cited somewhere else...

**Comment by zero-24** [comment]
Thanks :smile: RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7338">issues.joomla.org/joomla-cms/7338</a>.</sub>

**Comment by zero-24** [comment]
@smz 

>Unrelated: I just noticed that folders containing blanks in their names are inaccessible by com_media, but I think I've seen this issue cited somewhere else...

This is expected behavior. You also can't create a folder with blanks ;)

**Comment by smz** [comment]
@zero-24 
TBH I agree that this can view as at least "*enforcing best practices*"

**Comment by wilsonge** [comment]
Merged - thanks everyone :)

**Comment by N6REJ** [comment]
is the pr gone once merged?  Cause I can't find it in patch tester

**Comment by zero-24** [comment]
>is the pr gone once merged?

Yes :smile:

**Pull request merged**
