### PR TITLE
[3.10] Update unit testing

### PR DESCRIPTION
**Pull request by HLeithner**
The Pull Request started as simple "add php 8.1 and 8.2" to the test pipeline...

Now I try to full fill all requirements for phpunit 9.5...

1. PHP 8+ Tests will have own unit tests in directory tests/unit8 and it's own phpunit-php8.xml config file
2. The dependencies are changed to fit the requirement for phpunit 9.5
3. added yoast/phpunit-polyfills for some testing functions that get removed in phpunit 9.x

TODOS:
* reactivate phar-wrapper
* re-add all other php version tests
* Find a alternative solution for assertTag()

Done:
* Skip JArrayHelper::softObjects till #36503 is merged
* * add crypto tests back when #36491 is merged

### CODE REVIEW

**Comment by zero-24** [comment]
hmm looks like phpunit is broken on 8.0+?

**Comment by brianteeman** [comment]
phpunit is out of date - each is not available in php8

**Comment by PhilETaylor** [comment]
Cough https://github.com/joomla/joomla-cms/issues/36393

**Comment by HLeithner** [comment]
@zero-24
> hmm looks like phpunit is broken on 8.0+?

No it seems the patch is not applied to the new image (but I thought phpunit 8 got updated to support 8.0) I will take a look

@brianteeman
> phpunit is out of date - each is not available in php8

No idea what you mean https://phpunit.de/supported-versions.html phpunit 8 shouldn't be the problem, for 3.10 we will likely stick to phpunit 4 and 8. Maybe someone want to look at https://github.com/Yoast/PHPUnit-Polyfills if it could solve some problems for us (didn't looked at it)

@PhilETaylor 
> Cough #36393

It's not ignored, I just added the tests first so it's easier to check and complete everything at once, but Christmas time is family time and I have only limited timeslots beside work.

**Comment by PhilETaylor** [comment]
Thanks for reading the first line of my issue and nothing more. I’ll do the work myself as you seem to have no interest in understanding that pollyfilling is not the way forward for PHP 8 and PHPUnit 9

**Comment by HLeithner** [comment]
@PhilETaylor
> Thanks for reading the first line of my issue and nothing more. I’ll do the work myself as you seem to have no interest in understanding that pollyfilling is not the way forward for PHP 8 and PHPUnit 9

Did I said that? Problem is to have the same phpunit version for php 5.3 and 8.1, that's the reason why I see this as an option for J3 not for j4. But as already mentioned I didn't looked at it at all. Please stop telling me what I have done and what I didn't.

I only said I will look at this when the ci provides proper testing images, not more not less. 

Thanks

**Comment by PhilETaylor** [comment]
Im not sure what you have done to drone but every PR since yesterday is failing...

**Comment by HLeithner** [comment]
I will take a look, it's possible that it noe uses the development php.ini (before it's doesn't used any and had a memory limit of 128mb)

**Comment by HLeithner** [comment]
ok it wasn't the ini stuff, the git repository wasn't clean and mixed the php versions, new build is running and should fix the problem soon.

**Comment by HLeithner** [comment]
https://github.com/joomla/joomla-cms/pull/36491 is needed for system tests to work on php 8+

**Comment by zero-24** [comment]
@HLeithner do you think that PR here is now good to go or do we need some updates here? Looks like the signature of the drone file is not correct as that build is blocked?

**Comment by HLeithner** [comment]
@zero-24 I think the PR is ok, didn't had the time to finish it and doesn't know if anything is missing now. I will pick it up after PSR-12 is merged

**Comment by zero-24** [comment]
Thanks

**Comment by HLeithner** [comment]
but it would be really appreciated if you help, seems 8.1 and 8.2 tests are not so happy @zero-24

**Comment by zero-24** [comment]
Looks like the tests do not run in the first place? I do get `Build is blocked, please, contact repo admin in order to proceed` https://ci.joomla.org/joomla/joomla-cms/53773

**Comment by HLeithner** [comment]
Because the drone file is not signed correctly

**Comment by zero-24** [comment]
@HLeithner Are there any plans to complete this task here?

**Comment by zero-24** [comment]
Will close here for now can be reopend when there are any plans to procced here and make it ready to be merged.

**Pull request closed without merging**
