### PR TITLE
[3.10] Fix typo within two language strings uninstall -> uninstalled

### PR DESCRIPTION
**Pull request by zero-24**
Replaces Pull Request for Issue #36964 #36963 original work done by @MartijnMaandag

### Summary of Changes

Fix typo within two language strings uninstall -> uninstalled

### Testing Instructions

review the changes

### Actual result BEFORE applying this Pull Request

uninstall 

### Expected result AFTER applying this Pull Request

uninstalled

### Documentation Changes Required

none.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 76faaaa082834e2b38b2d16f36239348fe1b234e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36969">issues.joomla.org/tracker/joomla-cms/36969</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 76faaaa082834e2b38b2d16f36239348fe1b234e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36969">issues.joomla.org/tracker/joomla-cms/36969</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36969">issues.joomla.org/tracker/joomla-cms/36969</a>.</sub>

**Review by its0x08 — APPROVED** [review]

**Comment by zero-24** [comment]
Merging :-)

**Pull request merged**
