### PR TITLE
[#33222] # Config not outputing error messages when a required field is not fille...

### PR DESCRIPTION
**Pull request by compojoom**
http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=33222&start=0

### CODE REVIEW

**Comment by n9iels** [comment]
@test I can't reproduce the bug. When I edit my config.xml, I can't save the file without fill it out. When I go to another tab, I also get a message<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/3026">issues.joomla.org/joomla-cms/3026</a>.</sub>

**Comment by pe7er** [comment]
Could you please add a step-by-step testing procedure, including screen shots with arrows & annotations?
That way the issue + your patch will be easier to test.
Could you please respond within 30 days, otherwise this issue will be closed.
Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/3026">issues.joomla.org/joomla-cms/3026</a>.</sub>

**Comment by compojoom** [comment]
The reproduce steps that I've posted on joomlacode are still correct for Cmandrill & cmc.
However if you want to reproduce this with com_content, since we now have js validation you should modify the view files & remove the validation there. 

To make things easier, let's test with CMandrill.
First download CMandrill from:
https://compojoom.com/downloads/official-releases-stable/mandrill

then install it. Now go to components -> CMandrill options. Go to the permissions tab and try to change any permission. Save. The page will refresh without any error message and the permissions that you've applied shouldn't be saved.

Now apply the patch and try to save the config again. This time you'll see the error message.

**Comment by compojoom** [comment]
Okay, the above description is wrong. We have now javascript validation and running into the issue is a little difficult. 
First we need to disable the javascript validation. Go to: 
administrator\components\com_config\view\component\tmpl\default.php
comment out line 23,24 & 27. At the end your code should look like this:
``` 
Joomla.submitbutton = function(task)
	{
//		if (task === "config.cancel.component" || document.formvalidator.isValid(document.getElementById("component-form")))
//		{
			Joomla.submitform(task, document.getElementById("component-form"));
//		}
	};
```
After that test it with CMandrill:
First download CMandrill from:
https://compojoom.com/downloads/official-releases-stable/mandrill

then install it. Now go to components -> CMandrill options. Go to the permissions tab and try to change any permission. Save. The page will refresh without any error message and the permissions that you've applied shouldn't be saved.

Now apply the patch and try to save the config again. This time you'll see the error message.

**Comment by compojoom** [comment]
I've somehow managed to screw the pull request with another pull request.
Closing this and will open a new one.

**Pull request closed without merging**
