### PR TITLE
[4.0] Add accessibility to stats table

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
Add accessibility to stats table.

### Testing Instructions
In the "Joomla! would like your permission to collect some basic statistics." box, click `Select here to see the information that will be sent.`
Use browser's inspector and select Unique ID.

### Expected result
`<th scope="row">Unique ID</th>`

### Actual result
`<td><strong>Unique ID</strong></td>`

### CODE REVIEW

**Comment by brianteeman** [comment]
This change is correct but its only a partial fix as there is still no table column headings or a legend. In Joomla 3 this was a definition list and thinking about this data it should probably still be a definition list

**Comment by ceford** [comment]
Is there a way to invoke this box in an installation where it has already been dismissed?

I noticed that the Post Installation Messages screen Help document is missing - I will fix that.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29570">issues.joomla.org/tracker/joomla-cms/29570</a>.</sub>

**Comment by chmst** [comment]
The changes in the table are correct. 
But there is a link for opening the table. This has two problems: It is not visible as link for colourblind and it is not a link but a button.

If you say that this is not in scope, I will give it a positive test.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29570">issues.joomla.org/tracker/joomla-cms/29570</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 7fcf7fb64d96c1b473ec7a15d8207fc9c84dff82<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29570">issues.joomla.org/tracker/joomla-cms/29570</a>.</sub>

**Comment by brianteeman** [comment]
@ceford yes in the plugin itself

@quy thanks for those extra changes

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 7fcf7fb64d96c1b473ec7a15d8207fc9c84dff82<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29570">issues.joomla.org/tracker/joomla-cms/29570</a>.</sub>

**Comment by alikon** [comment]
rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29570">issues.joomla.org/tracker/joomla-cms/29570</a>.</sub>

**Comment by ceford** [comment]
OK - All good.

**Comment by richard67** [comment]
Thanks!

**Pull request merged**
