### PR TITLE
Joomla is not installing on remote databases

### PR DESCRIPTION
**Pull request by zero-24**
Pull Request for Issue #17246

### Summary of Changes

I have just added a extra code that sets a session state when all checks passed. When this is set no thing is displayed.

For some reason that i did not come behind until now the installer did not run when there is any kind of message displayed.

### Testing Instructions

try to install with a remote database
Zip package: https://github.com/zero-24/joomla-cms/archive/fixinstaller.zip

### Expected result

works

### Actual result

hangs at the installstep

### Documentation Changes Required

This page should be updated with texts how to fix the 3.7.4 issue until this fix is delivered. https://docs.joomla.org/Special:MyLanguage/J3.x:Secured_procedure_for_installing_Joomla_with_a_remote_database

### CODE REVIEW

**Comment by AlexRed** [comment]
Test ok for me on remote database with the **fixinstaller.zip** Joomla 3.8 version.

But after delete the txt file and press "next" in the installation procedure I can see again the message:

> Warning
> You are trying to use a database host which is not on your local server. For security reasons, you need to verify the ownership of your web hosting account. Please read the documentation for more information.

warning-fix

Better a "confirmation message" or nothing like if I try again with the same browser, no more checks.

**Comment by zero-24** [comment]
Yes because this is the message we displayed on the other sceen.
If you hit `install` the message is gone.

But i have something in mind that may can help here when i'm back to my PC later i can take a look if that works too.

Thanks.

**Comment by Song2017** [comment]
It seems that host like **127.0.0.1:49858** is not regarded as local database.
After delete verify file, it hangs on creating configuration File during Installing, then Got this 
```
The most recent request was denied because it contained an invalid security token. 
Please refresh the page and try again.
```

**Comment by zero-24** [comment]
There is a dedicated PR for the ports thing: https://github.com/joomla/joomla-cms/pull/17251

**Comment by zero-24** [comment]
@AlexRed please test again. Sorry that it took longer than expected..

**Comment by wilsonge** [comment]
@zero-24 can you look at conflicts please?

**Comment by zero-24** [comment]
fixed @wilsonge

**Comment by AlexRed** [comment]
I have tested this item :white_check_mark: successfully on 3fe3e3f49767fa97614d78029319ae041b777942<br /><br />Patch ok for me<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17248">issues.joomla.org/tracker/joomla-cms/17248</a>.</sub>

**Comment by e-struct** [comment]
Patch worked for me too.

**Comment by ghost** [comment]
RTC after two successful tests.

**Comment by ghost** [comment]
@e-struct i altered your Test as successfully at Issue Tracker. thanks for Test.

**Comment by zero-24** [comment]
Thanks!

**Comment by BenMitnicK** [comment]
not ok for me with 1&1 database impossible to move in next step I blocked on database I must replace this 

if (!in_array($options->db_host, $localhost))  to  if(false) for installing joomla 3.7.4

**Comment by wojsmol** [comment]
@BenMitnicK This is nerged for 3.8.0. This is known issue in 3.7.4 - see https://docs.joomla.org/J3.x:Secured_procedure_for_installing_Joomla_with_a_remote_database

**Comment by clx81** [comment]
OK, now installation with a localhost is accepted but after the database are filled with tables, the installation come back to the overview, the configuration file is not created !

**Comment by zero-24** [comment]
@clx81 please open a new issue containing all details what you did and what happend after that so we can try to reproduce and fix the bug. Commenting on closed / merged issues get lost very fast. Thanks for understanding.

**Comment by bettelli** [comment]
hi, can anybody upload the fix, its down https://github.com/zero-24/joomla-cms/archive/fixinstaller.zip 404 not found Thanks

**Comment by wojsmol** [comment]
@bettelli This fix is included in Joomla 3.7.5.

**Comment by bettelli** [comment]
thanks for the info but  i delete the line  in database.php and works, i installed from a yootheme template.

**Comment by zero-24** [comment]
I'm going to lock this issue now. On any questions please [open a new issue](https://github.com/joomla/joomla-cms/issues/new) . Which describes the problem so we can investigate that.

Thanks for understanding.

**Pull request merged**
