### PR TITLE
Update references to label in description to match label name

### PR DESCRIPTION
**Pull request by Quy**
Pull Request for Issue #17963.

### Summary of Changes
Update references to label in description to match label name.

### Testing Instructions
Create a new menu item of `Create Article`.
Under Options tab, put cursor over ` Custom Redirect on Cancel` to display popover.

### Expected result
`Submission/Cancel Redirect`

### Actual result
`Submission Redirect`

### Documentation Changes Required
None

### CODE REVIEW

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on e7395546246987f029105accca83a87eb248e47f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18555">issues.joomla.org/tracker/joomla-cms/18555</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on e7395546246987f029105accca83a87eb248e47f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18555">issues.joomla.org/tracker/joomla-cms/18555</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Comment by ghost** [comment]
RTC after two successful tests.

**Pull request merged**
