### PR TITLE
[4.3] ComponentDispatcher comments

### PR DESCRIPTION
**Pull request by brianteeman**
Fixes copy paste errors - code review only

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 94ca5bf5a6b1039d16f11c72ecffdc1bed769a5b<br /><br />code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41005">issues.joomla.org/tracker/joomla-cms/41005</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 94ca5bf5a6b1039d16f11c72ecffdc1bed769a5b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41005">issues.joomla.org/tracker/joomla-cms/41005</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41005">issues.joomla.org/tracker/joomla-cms/41005</a>.</sub>

**Comment by obuisard** [comment]
Thank you Brian @brianteeman.

**Pull request merged**
