### PR TITLE
Remove 2.5 remnant from hathor

### PR DESCRIPTION
**Pull request by brianteeman**
For testing instructions see #5840
It would appear that this extra string is a remnant from a 2.5 override as the missing string is not used in core

### CODE REVIEW

**Comment by zero-24** [comment]
@brianteeman can i ask you to fix this also for the debug group view? https://github.com/joomla/joomla-cms/blob/staging/administrator/templates/hathor/html/com_users/debuggroup/default.php#L70

For the debug user view this patch is ok here. Thanks.

**Comment by brianteeman** [comment]
@zero-24 done

**Comment by zero-24** [comment]
Thanks @brianteeman @test success

**Comment by infograf768** [comment]
No p here. Merging, Thanks.

NOTE: I have had memory limit issues here when trying to display user permissions. I had to raise memory limit very high.

**Pull request merged**
