### PR TITLE
[4.1]Change task type asc and desc

### PR DESCRIPTION
**Pull request by niharikamahajan02**
### Summary of Changes
Change task type asc and desc . Also interval typo.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on e5bd14da7c2fb50ce55de1202b5ff813638d0a88<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36657">issues.joomla.org/tracker/joomla-cms/36657</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on e5bd14da7c2fb50ce55de1202b5ff813638d0a88<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36657">issues.joomla.org/tracker/joomla-cms/36657</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36657">issues.joomla.org/tracker/joomla-cms/36657</a>.</sub>

**Comment by tecpromotion** [comment]
I have tested this item :white_check_mark: successfully on e5bd14da7c2fb50ce55de1202b5ff813638d0a88<br /><br />thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36657">issues.joomla.org/tracker/joomla-cms/36657</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
