### PR TITLE
CodeMirror 5.19

### PR DESCRIPTION
**Pull request by okonomiyaki3000**
Pull Request for Issue # .
### Summary of Changes

Updated CodeMirror to 5.19. Also, starting with this version, All uglified js files are being processed with [optimize-js](https://github.com/nolanlawson/optimize-js) which promises faster code execution in most javscript engines. 
### Testing Instructions

Just use CodeMirror as usual. Expect it to work normally. 
### Documentation Changes Required

Nope

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 5e6919b057eaba315bc6d381803ea119a21527e4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12300">issues.joomla.org/tracker/joomla-cms/12300</a>.</sub>

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on 5e6919b057eaba315bc6d381803ea119a21527e4<br /><br />Thanks :+1: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12300">issues.joomla.org/tracker/joomla-cms/12300</a>.</sub>

**Comment by zero-24** [comment]
RTC. Thanks! This is ready for 3.7.x :+1: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12300">issues.joomla.org/tracker/joomla-cms/12300</a>.</sub>

**Comment by rdeutz** [comment]
when it is for 3.7 should we change the base branch?

**Comment by zero-24** [comment]
First we need to merge staging into 3.7.x else we break this pr if we change the base

**Comment by zero-24** [comment]
Thanks. It looks like staging gets merged into 3.7.x at some time :smile:

**Pull request merged**
