### PR TITLE
Redo 13567

### PR DESCRIPTION
**Pull request by wilsonge**
Pull Request for Issue #13567 .

This is a straight redo of #13567 with the changes proposed by @mbabker 

### Summary of Changes
Extension updates that pull the install file from Github fail because no user_agent is supplied. This proposed change provides a userAgent to the http transport adapter. Put userAgent value in options passed to http transport adapter.

### Documentation Changes Required
None

### CODE REVIEW

**Comment by csthomas** [comment]
I have tested this item :white_check_mark: successfully on 1d020d69730dced70d54adb8e48337537150c8ed<br /><br />Code review.

I did not found any example of not working link before patch.
I tested before and after patch on update plugin from the web - no difference. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13605">issues.joomla.org/tracker/joomla-cms/13605</a>.</sub>

**Comment by marrouchi** [comment]
@wilsonge Can you please add some test instructions ? I have no idea how to reproduce the issue.

**Comment by franz-wohlkoenig** [comment]
same like @marrouchi at @wilsonge.

**Comment by brianteeman** [comment]
@wilsonge it has been over a year since you created this PR. It now has conflicts that require resolving. If this is something we need then it should be fixed. If not then please close it

**Comment by wilsonge** [comment]
This was just a redo of someone else's work. Given no one knows how to reproduce I'm closing it

**Pull request closed without merging**
