### PR TITLE
alpha order com_users.ini

### PR DESCRIPTION
**Pull request by zero-24**
### Summary of Changes

alpha order com_users.ini

### Testing Instructions

None / Review

### Documentation Changes Required

None

### CODE REVIEW

**Comment by yvesh** [comment]
I have tested this item :white_check_mark: successfully on 228c5491c66a1b9c5ba77eb92cf719b395fc36c6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14126">issues.joomla.org/tracker/joomla-cms/14126</a>.</sub>

**Comment by ladyjer** [comment]
I have tested this item :white_check_mark: successfully on 228c5491c66a1b9c5ba77eb92cf719b395fc36c6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14126">issues.joomla.org/tracker/joomla-cms/14126</a>.</sub>

**Comment by infograf768** [comment]
Please take off the empty lines before the comments. This way they do show OK in translations software.

I.e.:

```ini
JLIB_RULES_SETTING_NOTES="Changes apply to this component only.<br /><em><strong>Inherited</strong></em> - a Global Configuration setting or higher level setting is applied.<br /><em><strong>Denied</strong></em> always wins - whatever is set at the Global or higher level and applies to all child elements.<br /><em><strong>Allowed</strong></em> will enable the action for this component unless it is overruled by a Global Configuration setting."
; Categories overrides
COM_CATEGORIES_CATEGORY_ADD_TITLE="User Notes: New Category"
COM_CATEGORIES_CATEGORY_EDIT_TITLE="User Notes: Edit Category"
; Fields overrides
COM_USERS_USER_CATEGORIES_TITLE="Users: Field Groups"
COM_USERS_USER_CATEGORY_ADD_TITLE="Users: New Field Group"
COM_USERS_USER_CATEGORY_EDIT_TITLE="Users: Edit Field Group"

```
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14126">issues.joomla.org/tracker/joomla-cms/14126</a>.</sub>

**Comment by infograf768** [comment]
RTC on review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14126">issues.joomla.org/tracker/joomla-cms/14126</a>.</sub>

**Pull request merged**
