### PR TITLE
[4] Codestyle Remove space

### PR DESCRIPTION
**Pull request by PhilETaylor**
Code review.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on f1c99b4eed2002aac1ccbd78319d8cd998a87388<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35857">issues.joomla.org/tracker/joomla-cms/35857</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on f1c99b4eed2002aac1ccbd78319d8cd998a87388<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35857">issues.joomla.org/tracker/joomla-cms/35857</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35857">issues.joomla.org/tracker/joomla-cms/35857</a>.</sub>

**Comment by richard67** [comment]
Thanks

**Pull request merged**
