### PR TITLE
Fix Notice on Joomla update with PHP 7.4

### PR DESCRIPTION
**Pull request by degobbis**
Pull Request for Issue # .

### Summary of Changes
A PHP Notice will be shown on Joomla Update with PHP 7.4.
This Patch solves this notice.

### Testing Instructions
Needs Joomla 3.9.13 and PHP 7.4 installed
Go to Joomla administration -> Components -> Joomla! Update and -> Check for Updates

### Expected result
An Update or the actual version for reinstallation will bi shown, without any PHP notices

### Actual result
PHP Notice will shown

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on a4dd3cd57a5102cef8107321b2fb235fd2fad99b<br /><br />Replicated the issue and confirm the test does what it says<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27219">issues.joomla.org/tracker/joomla-cms/27219</a>.</sub>

**Comment by degobbis** [comment]
@brianteeman thx for testing

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on a4dd3cd57a5102cef8107321b2fb235fd2fad99b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27219">issues.joomla.org/tracker/joomla-cms/27219</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27219">issues.joomla.org/tracker/joomla-cms/27219</a>.</sub>

**Comment by degobbis** [comment]
@viocassel thx for testing

**Comment by zero-24** [comment]
Merging thanks for fixing this issue 👍

**Pull request merged**
