### PR TITLE
[4.0] Style list modules consistently

### PR DESCRIPTION
**Pull request by ciar4n**
Pull Request for Issue # .

### Summary of Changes
Consistent styling across list modules

### Before
image

### After
image

### CODE REVIEW

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on c4c62e6ff9efe7efb2403027c4e6633fd08a2ae5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32181">issues.joomla.org/tracker/joomla-cms/32181</a>.</sub>

**Comment by brianteeman** [comment]
could you look at the test errors please https://ci.joomla.org/joomla/joomla-cms/39668/1/20

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on c4c62e6ff9efe7efb2403027c4e6633fd08a2ae5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32181">issues.joomla.org/tracker/joomla-cms/32181</a>.</sub>

**Comment by richard67** [comment]
Previous tests are still valid since the change after the tests was only code style. I've restored the test results in the issue tracker.

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32181">issues.joomla.org/tracker/joomla-cms/32181</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
