### PR TITLE
[com_tags] Fix field name typo

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
Related to PR #23593.

There is a typo in `all_tags_show_tag_descripion`, thus , this setting is always enabled on the frontend.

### Testing Instructions
Code review
or
Install demo
Go `Global Configuration > Tags > List All Tags`
Toggle `Tag Descriptions` and check frontend under `All Tags`.

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 22dbd0198542dd225e8257b18cc0fd395b75d957<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23595">issues.joomla.org/tracker/joomla-cms/23595</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 22dbd0198542dd225e8257b18cc0fd395b75d957<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23595">issues.joomla.org/tracker/joomla-cms/23595</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23595">issues.joomla.org/tracker/joomla-cms/23595</a>.</sub>

**Comment by HLeithner** [comment]
thx

**Pull request merged**
