### PR TITLE
fixes

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue #14890 .

### Summary of Changes
- Call the menu function with the right amount of variables
- Fix all the logic for the modals (since modals they need to be checked against `window.parent.Joomla` NOT `Joomla` ). THIS CODE WILL NEVER BE EXECUTED IN 3.x DUE TO THE EXISTENCE of `jInsertEditorText(tag, editor);`, BUT SINCE IT'S ALREADY FIXED IN J4 THIS ALIGNS THE 2 CODEBASES

### Testing Instructions
Inside an article use the menu button to insert a link to a menu item in an article

### CODE REVIEW

**Comment by AlexRed** [comment]
I have tested this item :white_check_mark: successfully on e70da540be346b857897e7035de6f0d75513c024<br /><br />Patch ok for me<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14902">issues.joomla.org/tracker/joomla-cms/14902</a>.</sub>

**Comment by infograf768** [comment]
will test tomorrow.
First grr solved the language. ;)

**Comment by dgt41** [comment]
@infograf768 I should go back to school and re learn counting from 1 to 6 :)

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 581c0b1d7f9c90d5089879ff58cc3f5071ef9a16<br /><br />Ok now. (Did not test multiple editors)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14902">issues.joomla.org/tracker/joomla-cms/14902</a>.</sub>

**Comment by infograf768** [comment]
@wilsonge @rdeutz 
Please tag to 3.7.0 and release blocker.

**Comment by brianteeman** [comment]
Added release blocker and milestone as requested

**Pull request merged**
