### PR TITLE
Fixed the label functionality in the search module

### PR DESCRIPTION
**Pull request by RickR2H**
The search label was not visible due to the class that was added. Also the Label default value was set to "Search ..." when the label text field was empty. This PR changes this so the label is not visible when the label text field is completely empty.

How to test:
Apply the patch and go to the Search module in position-0
Fill in a text in the Box Label field and save the module.
adminpanel-searchmod

The search label must now be visible on the front end of the website.
searchfield-withlabel

Remove the label and clear the text field completely. Also remove spaces! After that the label must be gone without errors on the front end of the website.
searchfield-withoutlabel

### CODE REVIEW

**Comment by infograf768** [comment]
We indeed have a contradiction here (proposing a label field that will be invisible since 2012 https://github.com/joomla/joomla-cms/commit/cd663c07837e050ed2c183956ead8089487412a9 ) and, if it is decided to merge this, the tooltip has also to be changed:
screen shot 2015-08-15 at 09 03 04

**Comment by Bakual** [comment]
I think the label is there but invisible on purpose to assist with screen readers. I wouldn't change that.
If you want to show it on your site, you can use layout overrides to achieve it.

**Comment by RickR2H** [comment]
@Bakual I get it. But it didn't make sense since there was a field you can put text in, but isn't visible in the front end. Is it then  better plan to remove the label field? In my opinion it then has no use.

**Comment by rdeutz** [comment]
As @Bakual already said the label must be there for other assisting tools like screen readers. What might  be discussable is if we should show the label when someone put text into the Box Label field. So that would mean we change the class for the label, when someone put text into the Box Label field in the backend.

**Comment by RickR2H** [comment]
@rdeutz @Bakual I think it is an acceptable solution to change the class when the label box field is filled... Shall I implement this solution?

**Comment by Bakual** [comment]
I'm not so sure. For those people who entered a value suddenly the label will appear in the module and depending on the template it could appear quite broken. Imho, the label never serves any purpose except for screen readers, and thus always can stay invisible.

I wonder what the issue is you're trying to solve. You can already show the label using a simple CSS rule. Or you can do a layout override in your template.

If the gain from this PR outweigths the potential B/C issue, then yes, we can do it. But currently I don't see any real gain.

**Comment by RickR2H** [comment]
I guess you are right @Bakual. The only thing that didn't make sense to me was the label box text field that didn't show when the field was filled. That's what triggered me to make the label visible. I'll close the PR.

**Pull request closed without merging**
