### PR TITLE
[4.0] Application library prepared statements

### PR DESCRIPTION
**Pull request by SharkyKZ**
# Summary of Changes

Adds prepared statements and cleans up queries in `Joomla\CMS\Application` namespace.

### Testing Instructions

Login to backend.
Duplicate admin template style.
Edit your profile, select the new style, save profile.
Check that selected style is respected.
Check that frontend works like before.

### Expected result

Works like before.

### Documentation Changes Required
No.

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 6b88a85a4d6d46a2018dd49c617ea221fb2c8803<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25926">issues.joomla.org/tracker/joomla-cms/25926</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 6b88a85a4d6d46a2018dd49c617ea221fb2c8803<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25926">issues.joomla.org/tracker/joomla-cms/25926</a>.</sub>

**Comment by ghost** [comment]
Status "Ready To Commit".

**Comment by HLeithner** [comment]
Thank you trying to make Joomla safer.

**Pull request merged**
