### PR TITLE
[5.2] CalendarField: changing strftime to date

### PR DESCRIPTION
**Pull request by Hackwar**
Pull Request for Issue #42790 and a lot more.

### Summary of Changes
When using the calendar field without a format and without setting `translateformat="true"`, the field tries to convert the value with `strftime()`, which is deprecated and throws a warning. This PR replaces `strftime()` with `date()` instead and converts the time format from strftime to date-format. To make this as compatible as possible, the conversion method has been extended to include as many conversions as possible. Since this only converts datetimes, the chance that someone is using a format with additional text besides the strftime-format is neglectable.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by ceford** [comment]
Can you give us exact test instructions? I have forgotten what happened previously and I cannot reproduce the error in 5.2.0-beta3-dev.

**Comment by richard67** [comment]
> Can you give us exact test instructions? I have forgotten what happened previously and I cannot reproduce the error in 5.2.0-beta3-dev.

@ceford Maybe it can be tested as described in PR #43947 ? I haven't tried that yet.

**Comment by chmst** [comment]
I get the message only with PHP < 8.2. 

Field definition in my component.
```
	<field
		name="date_from"
		type="calendar"
		format="%Y-%m-%d"
		showtime="false"
		label="COM_EVENT_DATE_FROM"
		description="COM_EVENT_DATE_FROM_DESC"
	/>
```
@ceford for a test, change the field definiton in a compoment, for example in com_article, article.xml  like this or with all possicble different settings: 

```
		<field
			name="created"
			type="calendar"
			label="COM_CONTENT_FIELD_CREATED_LABEL"
		format="%Y-%m-%d"
		showtime="false"
			filter="user_utc"
		/>
```
and different php versions

**Comment by aberenguer78** [comment]
Solution of Chat GPT:
If your current code looks like this using strftime():

php
Copiar código
echo strftime('%Y-%m-%d %H:%M:%S', time());

You can replace it with the DateTime object or the date() function as follows:

php
Copiar código
// Using DateTime object
$date = new DateTime();
echo $date->format('Y-m-d H:i:s');

// Or using the date() function
echo date('Y-m-d H:i:s', time());

**Comment by aberenguer78** [comment]
The solution provided I do not consider a proper solution. I don't want to change the configuration of xml manifest field.
You must solve in the code as described before.

**Comment by fgsw** [comment]
@aberenguer78 Can you open https://issues.joomla.org/tracker/joomla-cms/44114 and 
- click button "Test this"
- mark "Tested successfully"

The test will count as successfull.

**Comment by aberenguer78** [comment]
I have tested this item :white_check_mark: successfully on bc5ba1157f9bd8759cdf033405e0738716310ce4<br /><br />I have replaced the files modified in Joomla core, and the deprecation errors disappear without changing any XML manifest configuration of the component.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44114">issues.joomla.org/tracker/joomla-cms/44114</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on bc5ba1157f9bd8759cdf033405e0738716310ce4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44114">issues.joomla.org/tracker/joomla-cms/44114</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44114">issues.joomla.org/tracker/joomla-cms/44114</a>.</sub>

**Comment by pe7er** [comment]
Thanks @Hackwar !

**Pull request merged**
