### PR TITLE
[4.0] Action logs separator

### PR DESCRIPTION
**Pull request by brianteeman**
Typically we use a switcher and not a list when we only have two options

### Before
image

### After
image

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 3635d1059f7bd182a20c4103ae0fd0f1436436cd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26024">issues.joomla.org/tracker/joomla-cms/26024</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 3635d1059f7bd182a20c4103ae0fd0f1436436cd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26024">issues.joomla.org/tracker/joomla-cms/26024</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26024">issues.joomla.org/tracker/joomla-cms/26024</a>.</sub>

**Comment by HLeithner** [comment]
Makes this sense on a not "Yes/No" field? what is the other color?

**Comment by Quy** [comment]
Options are `Comma` and `Semicolon`. There are other settings with 2 options ie `Global Configuration > Articles > Positioning of the Links` with options `Below` and `Above`.

**Comment by brianteeman** [comment]
The color is on the default

**Comment by brianteeman** [comment]
Even if you dont like the switcher for this having a list with two items is just crazy

**Comment by simbus82** [comment]
In a correct UX, the UI element must depend by Type of content, not by "number of elements".
A switch must be used only for boolean... "off, on", "true, false"...
If you have to do a choice between two (or more) "types", a list is preferable.

**Comment by brianteeman** [comment]
a boolean is anything that represents one of two possible values

**Comment by simbus82** [comment]
> a boolean is anything that represents one of two possible values

Umh, boolean is something that represents two truth values... not only two "generic" values... :-P

This is only my opinion, :
With a list I can see the choices available before selecting one, and a list is ready for any additions without changing UI (maybe I want a custom separator? Or the | "more" ?)

But in this case, the "default/true" is "Comma" in a CommaSV. OK!

**Comment by wilsonge** [comment]
I agree with @simbus82 here. Switcher doesn't make sense unless it's a truthy question. However i accept that the list seems slightly excessive here. Maybe a standard radio button is more appropriate here?

**Comment by Quy** [comment]
There are several settings like this. Changing this to radio button then the others will have to be changed too.

**Comment by wilsonge** [comment]
I think that's correct. Any on/off or true/false or show/hide etc where there's a true boolean coming out should be switcher. I think others for short selection options should be radio :/ we went through a lot of these settings and tweaked the language strings to be more question like in many places to enable this. Possible some got missed along the way or there are others like this which are just selection based than boolean based

**Comment by brianteeman** [comment]
ok - i will close this here and check all switchers to see if they should be radio

**Comment by brianteeman** [comment]
Sorry too many to check and only 4 instances of a radio group in the cms - of which two three should not be

**Pull request closed without merging**
