### PR TITLE
[4.0] Apply .form-control

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
Apply form field formatting.

### Testing Instructions
Go to System > Redirects
Click `Bulk Import` button

### Actual result BEFORE applying this Pull Request
Dark border and no padding.

bulk

### Expected result AFTER applying this Pull Request
Light border with padding.

bulk-form-control

### CODE REVIEW

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on e86e78d07614aab81e2f5cf92079045434c72cbb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32079">issues.joomla.org/tracker/joomla-cms/32079</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on e86e78d07614aab81e2f5cf92079045434c72cbb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32079">issues.joomla.org/tracker/joomla-cms/32079</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on e86e78d07614aab81e2f5cf92079045434c72cbb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32079">issues.joomla.org/tracker/joomla-cms/32079</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
