### PR TITLE
[4] cleanup more of libraries/vendor before release

### PR DESCRIPTION
**Pull request by PhilETaylor**
Code review.

Although this doesnt drastically reduce the size of the final zip files, it does significantly cleanup the libraries/vendor folders removing all kinds of build files that just are not needed on a live Joomla 4.x site. 

The complete list of files this deletes are:

```
libraries/vendor/algo26-matthias/idna-convert/CODE_OF_CONDUCT.md
libraries/vendor/dealerdirect/phpcodesniffer-composer-installer/CODE_OF_CONDUCT.md
libraries/vendor/softcreatr/jsonpath/CODE_OF_CONDUCT.md
libraries/vendor/spomky-labs/cbor-php/CODE_OF_CONDUCT.md
libraries/vendor/algo26-matthias/idna-convert/docker-compose.yml
libraries/vendor/algo26-matthias/idna-convert/phpunit.xml
libraries/vendor/phpunit/php-timer/phpunit.xml
libraries/vendor/phpunit/php-token-stream/phpunit.xml
libraries/vendor/phpunit/php-code-coverage/phpunit.xml
libraries/vendor/phpunit/php-file-iterator/phpunit.xml
libraries/vendor/sebastian/comparator/phpunit.xml
libraries/vendor/sebastian/global-state/phpunit.xml
libraries/vendor/sebastian/object-enumerator/phpunit.xml
libraries/vendor/sebastian/object-reflector/phpunit.xml
libraries/vendor/sebastian/code-unit-reverse-lookup/phpunit.xml
libraries/vendor/sebastian/diff/phpunit.xml
libraries/vendor/sebastian/recursion-context/phpunit.xml
libraries/vendor/sebastian/type/phpunit.xml
libraries/vendor/sebastian/environment/phpunit.xml
libraries/vendor/sebastian/exporter/phpunit.xml
libraries/vendor/wamania/php-stemmer/README.md
libraries/vendor/myclabs/deep-copy/README.md
libraries/vendor/php-cs-fixer/diff/README.md
libraries/vendor/ralouphie/getallheaders/README.md
libraries/vendor/joomla-projects/joomla-browser/README.md
libraries/vendor/codeception/codeception/ext/README.md
libraries/vendor/codeception/codeception/src/Codeception/Util/README.md
libraries/vendor/codeception/codeception/src/Codeception/Step/README.md
libraries/vendor/codeception/codeception/src/Codeception/README.md
libraries/vendor/codeception/codeception/src/Codeception/Lib/README.md
libraries/vendor/codeception/codeception/src/Codeception/Subscriber/README.md
libraries/vendor/codeception/phpunit-wrapper/README.md
libraries/vendor/phpmailer/phpmailer/README.md
libraries/vendor/friendsofphp/php-cs-fixer/README.md
libraries/vendor/guzzlehttp/promises/README.md
libraries/vendor/guzzlehttp/psr7/README.md
libraries/vendor/guzzlehttp/guzzle/README.md
libraries/vendor/theseer/tokenizer/README.md
libraries/vendor/algo26-matthias/idna-convert/README.md
libraries/vendor/google/recaptcha/README.md
libraries/vendor/web-auth/webauthn-lib/README.md
libraries/vendor/web-auth/metadata-service/README.md
libraries/vendor/web-auth/cose-lib/README.md
libraries/vendor/composer/xdebug-handler/README.md
libraries/vendor/composer/ca-bundle/README.md
libraries/vendor/composer/semver/README.md
libraries/vendor/phpdocumentor/reflection-common/README.md
libraries/vendor/phpdocumentor/type-resolver/README.md
libraries/vendor/phpdocumentor/reflection-docblock/README.md
libraries/vendor/dealerdirect/phpcodesniffer-composer-installer/README.md
libraries/vendor/behat/gherkin/README.md
libraries/vendor/php-webdriver/webdriver/README.md
libraries/vendor/laminas/laminas-zendframework-bridge/README.md
libraries/vendor/laminas/laminas-diactoros/README.md
libraries/vendor/paragonie/sodium_compat/README.md
libraries/vendor/paragonie/sodium_compat/src/Core32/Curve25519/README.md
libraries/vendor/paragonie/sodium_compat/src/Core/Curve25519/README.md
libraries/vendor/softcreatr/jsonpath/README.md
libraries/vendor/doctrine/lexer/README.md
libraries/vendor/doctrine/inflector/README.md
libraries/vendor/doctrine/annotations/README.md
libraries/vendor/doctrine/instantiator/README.md
libraries/vendor/phpunit/php-timer/README.md
libraries/vendor/phpunit/php-token-stream/README.md
libraries/vendor/phpunit/phpunit/README.md
libraries/vendor/phpunit/php-text-template/README.md
libraries/vendor/phpunit/php-code-coverage/README.md
libraries/vendor/phpunit/php-file-iterator/README.md
libraries/vendor/phar-io/manifest/README.md
libraries/vendor/phar-io/version/README.md
libraries/vendor/nyholm/psr7/README.md
libraries/vendor/willdurand/negotiation/README.md
libraries/vendor/php-http/message-factory/README.md
libraries/vendor/defuse/php-encryption/README.md
libraries/vendor/justinrainbow/json-schema/demo/README.md
libraries/vendor/justinrainbow/json-schema/README.md
libraries/vendor/typo3/phar-stream-wrapper/README.md
libraries/vendor/fgrosse/phpasn1/README.md
libraries/vendor/psr/event-dispatcher/README.md
libraries/vendor/psr/http-message/README.md
libraries/vendor/psr/container/README.md
libraries/vendor/psr/link/README.md
libraries/vendor/psr/http-client/README.md
libraries/vendor/psr/log/README.md
libraries/vendor/psr/http-factory/README.md
libraries/vendor/voku/portable-ascii/README.md
libraries/vendor/voku/portable-utf8/README.md
libraries/vendor/symfony/polyfill-iconv/README.md
libraries/vendor/symfony/polyfill-php73/README.md
libraries/vendor/symfony/polyfill-php80/README.md
libraries/vendor/symfony/polyfill-ctype/README.md
libraries/vendor/symfony/polyfill-php72/README.md
libraries/vendor/symfony/browser-kit/README.md
libraries/vendor/symfony/ldap/README.md
libraries/vendor/symfony/event-dispatcher/README.md
libraries/vendor/symfony/var-dumper/README.md
libraries/vendor/symfony/filesystem/README.md
libraries/vendor/symfony/options-resolver/README.md
libraries/vendor/symfony/polyfill-intl-normalizer/README.md
libraries/vendor/symfony/css-selector/README.md
libraries/vendor/symfony/event-dispatcher-contracts/README.md
libraries/vendor/symfony/web-link/README.md
libraries/vendor/symfony/dom-crawler/README.md
libraries/vendor/symfony/finder/README.md
libraries/vendor/symfony/stopwatch/README.md
libraries/vendor/symfony/yaml/README.md
libraries/vendor/symfony/string/README.md
libraries/vendor/symfony/deprecation-contracts/README.md
libraries/vendor/symfony/service-contracts/README.md
libraries/vendor/symfony/error-handler/README.md
libraries/vendor/symfony/process/README.md
libraries/vendor/symfony/console/README.md
libraries/vendor/symfony/polyfill-mbstring/README.md
libraries/vendor/symfony/polyfill-intl-grapheme/README.md
libraries/vendor/ramsey/uuid/README.md
libraries/vendor/squizlabs/php_codesniffer/README.md
libraries/vendor/webmozart/assert/README.md
libraries/vendor/phpspec/prophecy/README.md
libraries/vendor/sebastian/comparator/README.md
libraries/vendor/sebastian/global-state/README.md
libraries/vendor/sebastian/object-enumerator/README.md
libraries/vendor/sebastian/object-reflector/README.md
libraries/vendor/sebastian/code-unit-reverse-lookup/README.md
libraries/vendor/sebastian/diff/README.md
libraries/vendor/sebastian/recursion-context/README.md
libraries/vendor/sebastian/type/README.md
libraries/vendor/sebastian/version/README.md
libraries/vendor/sebastian/environment/README.md
libraries/vendor/sebastian/exporter/README.md
libraries/vendor/sebastian/resource-operations/README.md
libraries/vendor/joomla/cms-coding-standards/README.md
libraries/vendor/joomla/database/README.md
libraries/vendor/joomla/di/README.md
libraries/vendor/joomla/archive/README.md
libraries/vendor/joomla/test/README.md
libraries/vendor/joomla/coding-standards/README.md
libraries/vendor/joomla/coding-standards/manual/README.md
libraries/vendor/joomla/coding-standards/Joomla/ExampleRulesets/README.md
libraries/vendor/joomla/input/README.md
libraries/vendor/joomla/crypt/README.md
libraries/vendor/joomla/ldap/README.md
libraries/vendor/joomla/oauth2/README.md
libraries/vendor/joomla/filesystem/README.md
libraries/vendor/joomla/utilities/README.md
libraries/vendor/joomla/http/README.md
libraries/vendor/joomla/registry/README.md
libraries/vendor/joomla/string/README.md
libraries/vendor/joomla/filter/README.md
libraries/vendor/joomla/data/README.md
libraries/vendor/joomla/uri/README.md
libraries/vendor/joomla/authentication/README.md
libraries/vendor/joomla/event/README.md
libraries/vendor/joomla/mediawiki/README.md
libraries/vendor/joomla/console/README.md
libraries/vendor/joomla/session/README.md
libraries/vendor/joomla/router/README.md
libraries/vendor/jakeasmith/http_build_url/readme.md
libraries/vendor/guzzlehttp/guzzle/UPGRADING.md
libraries/vendor/algo26-matthias/idna-convert/UPGRADING.md
libraries/vendor/voku/portable-utf8/SUMMARY.md
libraries/vendor/codeception/stub/.travis.yml
libraries/vendor/algo26-matthias/idna-convert/.travis.yml
libraries/vendor/google/recaptcha/.travis.yml
libraries/vendor/phpunit/php-timer/.travis.yml
libraries/vendor/phpunit/php-token-stream/.travis.yml
libraries/vendor/phpunit/php-code-coverage/.travis.yml
libraries/vendor/phpunit/php-file-iterator/.travis.yml
libraries/vendor/willdurand/negotiation/.travis.yml
libraries/vendor/jakeasmith/http_build_url/.travis.yml
libraries/vendor/sebastian/comparator/.travis.yml
libraries/vendor/sebastian/global-state/.travis.yml
libraries/vendor/sebastian/object-enumerator/.travis.yml
libraries/vendor/sebastian/object-reflector/.travis.yml
libraries/vendor/sebastian/code-unit-reverse-lookup/.travis.yml
libraries/vendor/sebastian/diff/.travis.yml
libraries/vendor/sebastian/recursion-context/.travis.yml
libraries/vendor/sebastian/type/.travis.yml
libraries/vendor/sebastian/environment/.travis.yml
libraries/vendor/sebastian/exporter/.travis.yml
libraries/vendor/joomla/event/.travis.yml
libraries/vendor/wamania/php-stemmer/.gitignore
libraries/vendor/joomla-projects/joomla-browser/.gitignore
libraries/vendor/codeception/phpunit-wrapper/.gitignore
libraries/vendor/codeception/stub/.gitignore
libraries/vendor/algo26-matthias/idna-convert/.gitignore
libraries/vendor/google/recaptcha/.gitignore
libraries/vendor/paragonie/sodium_compat/.gitignore
libraries/vendor/softcreatr/jsonpath/.gitignore
libraries/vendor/phpunit/php-timer/.gitignore
libraries/vendor/phpunit/php-token-stream/.gitignore
libraries/vendor/phpunit/php-text-template/.gitignore
libraries/vendor/phpunit/php-code-coverage/.gitignore
libraries/vendor/phpunit/php-file-iterator/.gitignore
libraries/vendor/willdurand/negotiation/.gitignore
libraries/vendor/psr/event-dispatcher/.gitignore
libraries/vendor/psr/container/.gitignore
libraries/vendor/psr/http-factory/.gitignore
libraries/vendor/symfony/event-dispatcher-contracts/.gitignore
libraries/vendor/symfony/deprecation-contracts/.gitignore
libraries/vendor/symfony/service-contracts/.gitignore
libraries/vendor/jakeasmith/http_build_url/.gitignore
libraries/vendor/sebastian/comparator/.gitignore
libraries/vendor/sebastian/global-state/.gitignore
libraries/vendor/sebastian/object-enumerator/.gitignore
libraries/vendor/sebastian/object-reflector/.gitignore
libraries/vendor/sebastian/code-unit-reverse-lookup/.gitignore
libraries/vendor/sebastian/diff/tests/fixtures/out/.gitignore
libraries/vendor/sebastian/diff/.gitignore
libraries/vendor/sebastian/recursion-context/.gitignore
libraries/vendor/sebastian/type/.gitignore
libraries/vendor/sebastian/version/.gitignore
libraries/vendor/sebastian/environment/.gitignore
libraries/vendor/sebastian/exporter/.gitignore
libraries/vendor/sebastian/resource-operations/.gitignore
libraries/vendor/joomla/cms-coding-standards/.gitignore
libraries/vendor/joomla/event/.gitignore
libraries/vendor/algo26-matthias/idna-convert/.github/ISSUE_TEMPLATE
libraries/vendor/google/recaptcha/.github/ISSUE_TEMPLATE
libraries/vendor/softcreatr/jsonpath/.github/ISSUE_TEMPLATE
libraries/vendor/friendsofphp/php-cs-fixer/CONTRIBUTING.md
libraries/vendor/google/recaptcha/CONTRIBUTING.md
libraries/vendor/behat/gherkin/CONTRIBUTING.md
libraries/vendor/doctrine/instantiator/CONTRIBUTING.md
libraries/vendor/phpunit/php-code-coverage/.github/CONTRIBUTING.md
libraries/vendor/willdurand/negotiation/CONTRIBUTING.md
libraries/vendor/squizlabs/php_codesniffer/CONTRIBUTING.md
libraries/vendor/joomla/database/.github/CONTRIBUTING.md
libraries/vendor/joomla/di/.github/CONTRIBUTING.md
libraries/vendor/joomla/test/.github/CONTRIBUTING.md
libraries/vendor/joomla/input/.github/CONTRIBUTING.md
libraries/vendor/joomla/crypt/CONTRIBUTING.md
libraries/vendor/joomla/crypt/.github/CONTRIBUTING.md
libraries/vendor/joomla/ldap/.github/CONTRIBUTING.md
libraries/vendor/joomla/oauth2/.github/CONTRIBUTING.md
libraries/vendor/joomla/filesystem/.github/CONTRIBUTING.md
libraries/vendor/joomla/utilities/.github/CONTRIBUTING.md
libraries/vendor/joomla/http/.github/CONTRIBUTING.md
libraries/vendor/joomla/registry/.github/CONTRIBUTING.md
libraries/vendor/joomla/string/.github/CONTRIBUTING.md
libraries/vendor/joomla/data/.github/CONTRIBUTING.md
libraries/vendor/joomla/uri/.github/CONTRIBUTING.md
libraries/vendor/joomla/authentication/.github/CONTRIBUTING.md
libraries/vendor/joomla/event/.github/CONTRIBUTING.md
libraries/vendor/joomla/session/.github/CONTRIBUTING.md
libraries/vendor/joomla/router/.github/CONTRIBUTING.md
libraries/vendor/behat/gherkin/CHANGES.md
libraries/vendor/phpspec/prophecy/CHANGES.md
libraries/vendor/friendsofphp/php-cs-fixer/CHANGELOG.md
libraries/vendor/guzzlehttp/promises/CHANGELOG.md
libraries/vendor/guzzlehttp/psr7/CHANGELOG.md
libraries/vendor/guzzlehttp/guzzle/CHANGELOG.md
libraries/vendor/theseer/tokenizer/CHANGELOG.md
libraries/vendor/composer/xdebug-handler/CHANGELOG.md
libraries/vendor/composer/semver/CHANGELOG.md
libraries/vendor/php-webdriver/webdriver/CHANGELOG.md
libraries/vendor/laminas/laminas-zendframework-bridge/CHANGELOG.md
libraries/vendor/laminas/laminas-diactoros/CHANGELOG.md
libraries/vendor/softcreatr/jsonpath/CHANGELOG.md
libraries/vendor/doctrine/annotations/CHANGELOG.md
libraries/vendor/phar-io/manifest/CHANGELOG.md
libraries/vendor/phar-io/version/CHANGELOG.md
libraries/vendor/nyholm/psr7/CHANGELOG.md
libraries/vendor/php-http/message-factory/CHANGELOG.md
libraries/vendor/fgrosse/phpasn1/CHANGELOG.md
libraries/vendor/psr/http-message/CHANGELOG.md
libraries/vendor/psr/http-client/CHANGELOG.md
libraries/vendor/voku/portable-ascii/CHANGELOG.md
libraries/vendor/voku/portable-utf8/CHANGELOG.md
libraries/vendor/symfony/browser-kit/CHANGELOG.md
libraries/vendor/symfony/ldap/CHANGELOG.md
libraries/vendor/symfony/event-dispatcher/CHANGELOG.md
libraries/vendor/symfony/var-dumper/CHANGELOG.md
libraries/vendor/symfony/filesystem/CHANGELOG.md
libraries/vendor/symfony/options-resolver/CHANGELOG.md
libraries/vendor/symfony/css-selector/CHANGELOG.md
libraries/vendor/symfony/event-dispatcher-contracts/CHANGELOG.md
libraries/vendor/symfony/web-link/CHANGELOG.md
libraries/vendor/symfony/dom-crawler/CHANGELOG.md
libraries/vendor/symfony/finder/CHANGELOG.md
libraries/vendor/symfony/stopwatch/CHANGELOG.md
libraries/vendor/symfony/yaml/CHANGELOG.md
libraries/vendor/symfony/string/CHANGELOG.md
libraries/vendor/symfony/deprecation-contracts/CHANGELOG.md
libraries/vendor/symfony/service-contracts/CHANGELOG.md
libraries/vendor/symfony/error-handler/CHANGELOG.md
libraries/vendor/symfony/process/CHANGELOG.md
libraries/vendor/symfony/console/CHANGELOG.md
libraries/vendor/ramsey/uuid/CHANGELOG.md
libraries/vendor/webmozart/assert/CHANGELOG.md
libraries/vendor/phpmailer/phpmailer/SECURITY.md
libraries/vendor/brick/math/SECURITY.md
libraries/vendor/voku/portable-utf8/SECURITY.md
libraries/vendor/brick/math/psalm-baseline.xml
libraries/vendor/dealerdirect/phpcodesniffer-composer-installer/.yamllint
libraries/vendor/dealerdirect/phpcodesniffer-composer-installer/.remarkrc
libraries/vendor/psr/event-dispatcher/.editorconfig
libraries/vendor/psr/link/.editorconfig
libraries/vendor/webmozart/assert/.editorconfig
libraries/vendor/sebastian/diff/tests/fixtures/out/.editorconfig
libraries/vendor/sebastian/diff/tests/fixtures/.editorconfig
libraries/vendor/joomla/mediawiki/.editorconfig
libraries/vendor/joomla/session/.editorconfig
libraries/vendor/paragonie/sodium_compat/appveyor.yml
libraries/vendor/willdurand/negotiation/appveyor.yml
libraries/vendor/wamania/php-stemmer/phpunit.xml.dist
libraries/vendor/phpmailer/phpmailer/phpunit.xml.dist
libraries/vendor/google/recaptcha/phpunit.xml.dist
libraries/vendor/paragonie/sodium_compat/phpunit.xml.dist
libraries/vendor/softcreatr/jsonpath/phpunit.xml.dist
libraries/vendor/willdurand/negotiation/phpunit.xml.dist
libraries/vendor/justinrainbow/json-schema/phpunit.xml.dist
libraries/vendor/jakeasmith/http_build_url/phpunit.xml.dist
libraries/vendor/joomla/database/phpunit.xml.dist
libraries/vendor/joomla/di/phpunit.xml.dist
libraries/vendor/joomla/input/phpunit.xml.dist
libraries/vendor/joomla/crypt/phpunit.xml.dist
libraries/vendor/joomla/ldap/phpunit.xml.dist
libraries/vendor/joomla/oauth2/phpunit.xml.dist
libraries/vendor/joomla/filesystem/phpunit.xml.dist
libraries/vendor/joomla/utilities/phpunit.xml.dist
libraries/vendor/joomla/http/phpunit.xml.dist
libraries/vendor/joomla/registry/phpunit.xml.dist
libraries/vendor/joomla/string/phpunit.xml.dist
libraries/vendor/joomla/data/phpunit.xml.dist
libraries/vendor/joomla/uri/phpunit.xml.dist
libraries/vendor/joomla/authentication/phpunit.xml.dist
libraries/vendor/joomla/event/phpunit.xml.dist
libraries/vendor/joomla/session/phpunit.xml.dist
libraries/vendor/joomla/router/phpunit.xml.dist
libraries/vendor/guzzlehttp/psr7/.php_cs.dist
libraries/vendor/theseer/tokenizer/.php_cs.dist
libraries/vendor/spomky-labs/cbor-php/.php_cs.dist
libraries/vendor/phpunit/php-timer/.php_cs.dist
libraries/vendor/phpunit/php-code-coverage/.php_cs.dist
libraries/vendor/phpunit/php-file-iterator/.php_cs.dist
libraries/vendor/justinrainbow/json-schema/.php_cs.dist
libraries/vendor/sebastian/comparator/.php_cs.dist
libraries/vendor/sebastian/global-state/.php_cs.dist
libraries/vendor/sebastian/diff/.php_cs.dist
libraries/vendor/sebastian/type/.php_cs.dist
libraries/vendor/sebastian/environment/.php_cs.dist
libraries/vendor/sebastian/exporter/.php_cs.dist
libraries/vendor/sebastian/resource-operations/.php_cs.dist
libraries/vendor/squizlabs/php_codesniffer/phpcs.xsd
libraries/vendor/softcreatr/jsonpath/phpcs.xml
libraries/vendor/phpunit/php-timer/build.xml
libraries/vendor/phpunit/php-token-stream/build.xml
libraries/vendor/phpunit/php-code-coverage/build.xml
libraries/vendor/sebastian/comparator/build.xml
libraries/vendor/sebastian/global-state/build.xml
libraries/vendor/sebastian/object-enumerator/build.xml
libraries/vendor/sebastian/object-reflector/build.xml
libraries/vendor/sebastian/code-unit-reverse-lookup/build.xml
libraries/vendor/sebastian/diff/build.xml
libraries/vendor/sebastian/recursion-context/build.xml
libraries/vendor/sebastian/type/build.xml
libraries/vendor/sebastian/environment/build.xml
libraries/vendor/sebastian/exporter/build.xml
libraries/vendor/sebastian/resource-operations/build.xml
libraries/vendor/spomky-labs/cbor-php/infection.json.dist
libraries/vendor/phpdocumentor/type-resolver/phpbench.json
libraries/vendor/doctrine/instantiator/phpbench.json
libraries/vendor/composer/ca-bundle/phpstan.neon.dist
libraries/vendor/doctrine/inflector/phpstan.neon.dist
libraries/vendor/doctrine/instantiator/phpstan.neon.dist
libraries/vendor/doctrine/instantiator/.doctrine-project.json
libraries/vendor/psr/http-factory/.pullapprove.yml
libraries/vendor/spomky-labs/cbor-php/phpstan.neon
libraries/vendor/typo3/phar-stream-wrapper/_config.yml
```

### CODE REVIEW

**Comment by wilsonge** [comment]
Thanks!

**Comment by wilsonge** [comment]
FWIW I think a lot of those files are developer depedencies though (e.g. phpunit). Don't forget prod builds are run with `composer install --no-dev`

**Comment by PhilETaylor** [comment]
When run for real it's about 46 files it deletes :-(

**Comment by wilsonge** [comment]
Every file counts :)

**Comment by wilsonge** [comment]
@richard67 this one will require changes to the script.php file - but let's hold and do a final change next weekend or so.

**Pull request merged**
