### PR TITLE
[Regression] fix keepalive URL

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/10697.
#### Summary of Changes

Correct keepalive URL.
#### Testing Instructions
- Set session to 1 minute
- Open browser console "XHR" tab
- Edit a article and go do something
- When  you return notice the 404 errors on the console
- Apply patch
- Repeat steps, no errors now.

### CODE REVIEW

**Comment by brianteeman** [comment]
@andrepereiradasilva can you locate the PR where this was changed and leave a note there that it has been reverted by this PR - thanks

**Comment by andrepereiradasilva** [comment]
https://github.com/joomla/joomla-cms/pull/9665

**Comment by brianteeman** [comment]
Thanks @andrepereiradasilva

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 146e2442e66012e5d510134b760d2935a28236db<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10698">issues.joomla.org/joomla-cms/10698</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@brianteeman we need one more tester here. can you help?

Without this PR users, depending on their session time and inactive time, will get errors when editing content and loss their form data because the session will expire.

**Comment by grhcj** [comment]
I have tested this item :white_check_mark: successfully on 146e2442e66012e5d510134b760d2935a28236db<br /><br />Verified the issue and saw that applying the patch solved the problem.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10698">issues.joomla.org/joomla-cms/10698</a>.</sub>

**Comment by andrepereiradasilva** [comment]
thanks @infograf768 @grhcj for testing!

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10698">issues.joomla.org/joomla-cms/10698</a>.</sub>

**Pull request merged**
