### PR TITLE
Implementing "No Matching Results" in Users modal

### PR DESCRIPTION
**Pull request by brianteeman**
In the article manage when selecting a User in the publishing tab  the list of users is displayed in a modal window.
When filtering and if no results, the display is just empty instead of the usual message "No Matching Results"
This patch is just implementing the message in the modal when necessary.

Thanks to @infograf768 for the code idea

### CODE REVIEW

**Comment by infograf768** [comment]
OK here.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7236">issues.joomla.org/joomla-cms/7236</a>.</sub>

**Comment by Kubik-Rubik** [comment]
@brianteeman You have to move all lines in the code section one indent to the right, so that the opening and ending tags are in the same row (e.g. thead is not in the same row). Thanks!

**Comment by brianteeman** [comment]
Sorry not got a clue what you mean
Please create a PR against my branch so that I can see what you mean
(BTW I think you are confusing row and column)

On 23 June 2015 at 12:36, Viktor Vogel <notifications@github.com> wrote:

> @brianteeman <https://github.com/brianteeman> You have to move all lines
> in the code section one indent to the right, so that the opening and ending
> tags are in the same row (e.g. thead is not in the same row). Thanks!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/7236#issuecomment-114456971>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Kubik-Rubik** [comment]
@brianteeman Sorry, I meant column of course. Okay, I will send you a PR soon. :-)

**Comment by Kubik-Rubik** [comment]
Thank you, @brianteeman and @infograf768!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7236">issues.joomla.org/joomla-cms/7236</a>.</sub>

**Comment by Kubik-Rubik** [comment]
Thank you @brianteeman! Merged.

**Pull request closed without merging**
