### PR TITLE
[4.0] Fix padding for menu item edit link in Cassiopeia frontend editing

### PR DESCRIPTION
**Pull request by richard67**
Pull Request for [https://github.com/joomla/joomla-cms/pull/32070#issuecomment-763919602](https://github.com/joomla/joomla-cms/pull/32070#issuecomment-763919602) issue 1.

### Summary of Changes

Remove unwanted padding from menu item edit icons.

### Testing Instructions

1. On a current 4.0-dev branch or latest nightly built with the merged PR #32070 included, install blog sample data if you haven't done that yet, or make sure in some other way to have enough menus at diverse positions to verify the issue and the fix.
2. Enable frontend editing for menus:

3. Login to frontend and go to some other page than the start page to get rid of the big image being shown at the top.
4. Check horizontal alignment of menu items (in case of a horizontal menu the first one) in menu modules to other modules' content.
Result: There is some padding before the menu item's edit icon.
5. Log out so there is no frontend editing and check again alignment, check again horizontal alignment of menu items and note the change in vertical module positions.
Result: Without frontend editing, menu items are aligned well horizontally with other content. Thing below the header section moved a bit up compared to frontend editing on.
6. Check the same (steps 4 and 5) for LTR. You can easily change to LTR by editing file `language/en-GB/langmetadata.xml` and changing `<rtl>0</rtl>` to `<rtl>1</rtl>` in the `<metadata>` section.
Result: Not that easy to see due to the other issue with the position of the module edit buttons.
7. Apply the patch of this PR.
8. Repeat steps 3 to 6.
Result: See section "Expected result AFTER applying this Pull Request" below.

### Actual result BEFORE applying this Pull Request

LTR with frontend editing enabled:

The menu items are not aligned as they would be when frontend editing was switched off, see red lines in the screenshot above and green lines in the one below.

LTR without frontend editing:

The 2 screenshots have been made with the same window size. As you can see by the articles' texts at the bottom, the vertical space needed by the horizontal menu in the header changes when frontend editing is on, so everything below the header moves a bit down.

### Expected result AFTER applying this Pull Request

LTR with frontend editing enabled:

Compared to screenshot 2 in the previous section, the vertical positions of things below the header area haven't changed.

The horizontal alignment of menu item edit icons to menu titles or other content is the same as the horizontal alignment of menu item titles without frontend editing e.g. when logged off.

For RTL, the results are harder to verify due to the other issue with position of the module edit buttons.

### Additional information

The underline of the menu item edit link in the header section has to be fixed with another PR.

I've tried a bit when doing this PR here but did not really find a nice way. It should be removed completely for the edit icon in _header.scss (and possibly also _footer.scss).

### Documentation Changes Required

None.

### CODE REVIEW

**Comment by brianteeman** [comment]
This can be done without any special LTR or RTL css

Use padding-inline-start and padding-inline-end

**Comment by richard67** [comment]
> This can be done without any special LTR or RTL css
> 
> Use padding-inline-start and padding-inline-end

@brianteeman I know. But I was not sure regarding browser support. As I just can see we already use `padding-inline` at a few places. Will change it here, if that's wrong it has to be changed here and at these other places.

**Comment by brianteeman** [comment]
https://caniuse.com/?search=padding-inline-start

**Comment by richard67** [comment]
@brianteeman Thanks, changed.

**Comment by richard67** [comment]
@brianteeman Unfortunately it seems that some other logical CSS properties which could be useful to fix the other issue with positioning of module edit buttons for RTL have less browser support: https://caniuse.com/?search=inset-inline-end . Can we use `inset-inline` now or should we better not to that (yet)?

**Comment by brianteeman** [comment]
Only when they have full browser support for the browsers that we support

**Comment by richard67** [comment]
If I only knew which browsers we have to support ;-)

**Comment by brianteeman** [comment]
Not ie and all current browser versions and version minus 1

**Comment by richard67** [comment]
As I can see we don't use `inset-inline` anywhere yet, in opposite to `padding-inline` and `margin-inline`, which both have better browser support than `inset-inline`.

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on f30f5d5fc5742320b40204ef174e9a1aadf7894f<br /><br />Works as described.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32124">issues.joomla.org/tracker/joomla-cms/32124</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on f30f5d5fc5742320b40204ef174e9a1aadf7894f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32124">issues.joomla.org/tracker/joomla-cms/32124</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32124">issues.joomla.org/tracker/joomla-cms/32124</a>.</sub>

**Comment by drmenzelit** [comment]
Thanks

**Comment by richard67** [comment]
Thanks!

**Pull request merged**
