### PR TITLE
[4.0] add additional php settings to system info helpful for debugging

### PR DESCRIPTION
**Pull request by PhilETaylor**
### Summary of Changes

[4.0] add additional php settings to system info helpful for debugging

Those added are 

`memory_limit`
`upload_max_filesize`
`post_max_size`

These are all very useful in debugging. Adding them here also adds them to the export of configuration by `txt` and `json` formats. 

### Testing Instructions

Login to Joomla 4 admin and navigate to system -> System Information -> PHP Settings tab

### Actual result BEFORE applying this Pull Request

These are not shown

### Expected result AFTER applying this Pull Request

Screenshot 2020-07-07 at 10 14 05

### Documentation Changes Required

None/new screenshot?

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 62bb432ab5c981b17d9459a0d6fefeda8d5fd77d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30040">issues.joomla.org/tracker/joomla-cms/30040</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 62bb432ab5c981b17d9459a0d6fefeda8d5fd77d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30040">issues.joomla.org/tracker/joomla-cms/30040</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30040">issues.joomla.org/tracker/joomla-cms/30040</a>.</sub>

**Comment by richard67** [comment]
Thanks!

**Pull request merged**
