### PR TITLE
[4.0] Missing check icon in media manager

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Fixes https://github.com/joomla/joomla-cms/issues/29150.

### Testing Instructions

`npm i` required.

> * Open any article in the Article Manager
> 
> * Navigate to the `Images and Links` tab
> 
> * Click the `select` button under `Full Article Image` (which will open the Media Manager)
> 
> * Select an image

### Expected result

Checkmark icon not missing.

### Actual result

Checkmark icon missing.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by C-Lodder** [comment]
I have tested this item :white_check_mark: successfully on bcbc66be8dbcf48089878d0d1ac610990fa7c9ec<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29153">issues.joomla.org/tracker/joomla-cms/29153</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on bcbc66be8dbcf48089878d0d1ac610990fa7c9ec<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29153">issues.joomla.org/tracker/joomla-cms/29153</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29153">issues.joomla.org/tracker/joomla-cms/29153</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
