### PR TITLE
[4.0] Remove obsolete JHtml includes

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Removes obsolete `JHtml` path includes.

### Testing Instructions

Code review.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on c53424c28cc9f4ffee013d88f6d78b99f1133bf5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27124">issues.joomla.org/tracker/joomla-cms/27124</a>.</sub>

**Comment by richard67** [comment]
@SharkyKZ I'd really like to help with a good test, but I don't know how to see by code review if the removed code was obsolete or not. How do I have to check that?

**Comment by SharkyKZ** [comment]
@richard67 Need to check for two things. First that removed calls reference non-existing directories. And that HTML services are registered anyways. In components this is done automatically and elsewhere this can be done with application's `bootComponent()` method with the component specificed, e.g. like here https://github.com/joomla/joomla-cms/blob/c53424c28cc9f4ffee013d88f6d78b99f1133bf5/administrator/modules/mod_privacy_status/mod_privacy_status.php#L24-L25.

**Comment by richard67** [comment]
@SharkyKZ Thanks for the help. I'll test later.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on c53424c28cc9f4ffee013d88f6d78b99f1133bf5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27124">issues.joomla.org/tracker/joomla-cms/27124</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27124">issues.joomla.org/tracker/joomla-cms/27124</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
