### PR TITLE
s/translateable/translatable

### PR DESCRIPTION
**Pull request by PhilETaylor**
s/translateable/translatable

### CODE REVIEW

**Comment by Razzo1987** [comment]
Also in /administrator/components/com_content/src/Helper/ContentHelper.php line 95

**Comment by PhilETaylor** [comment]
@Razzo1987 please update your local copy of Joomla 4.0-dev

The file you reference was updated 11 hours ago with that typo fix - see https://github.com/joomla/joomla-cms/pull/31932

Proof that I am not mass find&replace but manually reviewing code to find these :)

**Comment by Razzo1987** [comment]
I have tested this item :white_check_mark: successfully on b7795a1b87f9f6fd03cd9484a76e24c15d524a9d<br /><br />Yes @PhilETaylor I'm using the nightly, sorry :smile: 

It's correct<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31956">issues.joomla.org/tracker/joomla-cms/31956</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on b7795a1b87f9f6fd03cd9484a76e24c15d524a9d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31956">issues.joomla.org/tracker/joomla-cms/31956</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31956">issues.joomla.org/tracker/joomla-cms/31956</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
