### PR TITLE
[5.1] Generic doc icon

### PR DESCRIPTION
**Pull request by brianteeman**
Replaces the pdf icon used in media manager with a more generic doc icon as this is applied to a variety of doc types.

### To test
Use one of the prebuilt packages for this PR and check to see that the icon used in media manager for any doc type is no longer a pdf icon.

Changing the icon to a specific one for each type of doc is beyond the scope of this PR

Pull Request for Issue #42518

## Before
image

## After
image
 .

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by ChristineWk** [comment]
The NPM Package (under Download) is not available.

**Comment by brianteeman** [comment]
updating branch to see if it will trigger the downloads to be created

**Comment by dgrammatiko** [comment]
@brianteeman https://github.com/joomla/joomla-cms/pull/36723 has more icons

**Comment by brianteeman** [comment]
but that is closed and as stated
> Changing the icon to a specific one for each type of doc is beyond the scope of this PR

**Comment by richard67** [comment]
> The NPM Package (under Download) is not available.

@ChristineWk You can find the downloads here: https://artifacts.joomla.org/drone/joomla/joomla-cms/5.1-dev/42527/downloads/72301/ . Currently there is something broken with updating the links to these downloads on GitHub.

**Comment by ChristineWk** [comment]
@richard67 
Thank you. Hv installed your download with relevant custom update server.



Can this be called successful? see 2nd picture (.doc)

**Comment by richard67** [comment]
> Can this be called successful? see 2nd picture (.doc)

@ChristineWk Not sure now and no time to check. @brianteeman Do you know why she gets the "No preview" icon for the 2nd case `.doc`?

**Comment by brianteeman** [comment]
1. did it show the pdf icon before?
2. is .doc an allowed file type?

**Comment by ChristineWk** [comment]
> 1. did it show the pdf icon before?
sorry, I'm not sure
> 
>     2. is .doc an allowed file type?
Yes

**Comment by brianteeman** [comment]
An essential part of testing is to replicate the before scenario. As you can see in both my before and after screenshots both show the doc file with first a pdf and then a generic icon your test is not successful for some reason

**Comment by dautrich** [comment]
I have tested this item :white_check_mark: successfully on 7873ca85d7b34f4ba8933290bb9cba5b9cd5bfb3<br /><br />Tested with document types PDF, TXT, DOCX, XLSX<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42527">issues.joomla.org/tracker/joomla-cms/42527</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 7873ca85d7b34f4ba8933290bb9cba5b9cd5bfb3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42527">issues.joomla.org/tracker/joomla-cms/42527</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42527">issues.joomla.org/tracker/joomla-cms/42527</a>.</sub>

**Comment by Razzo1987** [comment]
Thanks!

**Pull request merged**
