### PR TITLE
Convert any special characters from 'Site Name' settled in Global Con…

### PR DESCRIPTION
**Pull request by nppsbh**
…figuration

Example
Site name: my "website name"

HTML output
without this change:
my

with this change:
my &quot;website name&quot;

Pull Request for Issue # .

### CODE REVIEW

**Comment by brianteeman** [comment]
Not checked this but surely if it correct them the change has to be made everywhere that we get the sitemap!e and not just in the login

**Comment by infograf768** [comment]
The change is correct when the site name is used in html. 
Beware when `$sitename` is used for mails. In that case htmlspecialchars should not be used.

**Comment by Heggi93** [comment]
Please add some detailed test instructions <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17209">issues.joomla.org/tracker/joomla-cms/17209</a>.</sub>

**Comment by brianteeman** [comment]
@Heggi93 pretty much as it says in the original post.

In global configuration create a site name with a special character eg `My "site" Rocks`

On the administrator login page view the source code for the joomla logo. Before this PR the alt text will be invalid markup. After this PR the alt text should be valid markup.

Note that if correct then this change needs to be used in other places that we use the $sitename variable in a similar way

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on d6c89e68e3cd5b3e636e66922de07ad8460df2e6
#### Source Code without PR:
bildschirmfoto 2017-08-26 um 08 03 34
#### Source Code with PR:
bildschirmfoto 2017-08-26 um 08 04 18
@brianteeman Thanks for Test Instructions.
@Heggi93 can you please test?
<hr />
<sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17209">issues.joomla.org/tracker/joomla-cms/17209</a>.</sub>

**Comment by sanderpotjer** [comment]
I have tested this item :white_check_mark: successfully on d6c89e68e3cd5b3e636e66922de07ad8460df2e6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17209">issues.joomla.org/tracker/joomla-cms/17209</a>.</sub>

**Comment by ghost** [comment]
RTC after two successful tests.

**Pull request merged**
