### PR TITLE
[4.0] com_users unblocked

### PR DESCRIPTION
**Pull request by brianteeman**
The action was changed to unblock so it makes sense that the message is unblocked not enabled

image

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 0f0fb89a795bd548d9690e7a61995276a62bcd97<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34348">issues.joomla.org/tracker/joomla-cms/34348</a>.</sub>

**Comment by YatharthVyas** [comment]
I have tested this item :white_check_mark: successfully on 0f0fb89a795bd548d9690e7a61995276a62bcd97<br /><br />After PR

image
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34348">issues.joomla.org/tracker/joomla-cms/34348</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34348">issues.joomla.org/tracker/joomla-cms/34348</a>.</sub>

**Comment by Quy** [comment]
Thanks!

**Comment by brianteeman** [comment]
thx

**Pull request merged**
