### PR TITLE
[4.0] Fix modals tabbing in media manager

### PR DESCRIPTION
**Pull request by wilsonge**
Fix the tabbing of modals in media manager. Before the PR tabs are totally locked on the input element in both the create folder and the rename modal. After this PR the focus in all modals is locked to the modal. However all elements in that (buttons etc) can be tabbed into.

### CODE REVIEW

**Comment by brianteeman** [comment]
Great will put it on todays test list

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 9949e5ec01d99823c77f971453d7bb379db24a21<br /><br />1. Checked modals for file rename and file creation in media manager.
2. Applied patch with patchtester.
3. Did composer install and nmp install.
4. Checked modals for file rename and file creation in media manager.

Result:
Before patch no tabbing inside modals.
After patch tabbing inside modals is possible.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24654">issues.joomla.org/tracker/joomla-cms/24654</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 9949e5ec01d99823c77f971453d7bb379db24a21<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24654">issues.joomla.org/tracker/joomla-cms/24654</a>.</sub>

**Comment by ghost** [comment]
Status "Ready To Commit".

**Comment by wilsonge** [comment]
Thanks guys!

**Comment by richard67** [comment]
Thanks too.

**Pull request merged**
