### PR TITLE
removed code as advised in #13631

### PR DESCRIPTION
**Pull request by rdeutz**
Pull Request for Issue #13631 .

### Summary of Changes
Removed code as advised in #13631

### Testing Instructions
* Install latest staging
* Install an extension that used the with Joomla! core shipped fof version
* Create a 2nd admin menu with a menu item pointing to the above installed extension
* Install an update of the extension

-> menu items are deleted 

**Apply patch**

* Install latest staging
* Install an extension that used the with Joomla! core shipped fof version
* Create a 2nd admin menu with a menu item pointing to the above installed extension
* Install an update of the extension

-> menu items are NOT deleted 

### Documentation Changes Required
Mention in release notes

### CODE REVIEW

**Comment by rdeutz** [comment]
seems https://github.com/joomla/joomla-cms/issues/13642 is the bigger problem

**Comment by franz-wohlkoenig** [comment]
#13642 is closed.

**Comment by rdeutz** [comment]
I know someone has to review this

**Comment by franz-wohlkoenig** [comment]
thanks @rdeutz

**Comment by richard67** [comment]
Someone should change the milestone, now as 3.7.0 is released ;-)

**Comment by photodude** [comment]
I hate to say it, but following what has been policy; this should be closed like every other PR that makes changes to 3rd party libraries. (who cares that FOF2 is EOL and that the author has specifically said that we can make the necessary updates. Hasn't stopped the closing all of the other PR's to fix the FOF2 issues)

**Comment by rdeutz** [comment]
I closing this, I can't make the problem occur so I don't see how to prove the fix is a fix and not only a change :-)

**Pull request closed without merging**
