### PR TITLE
[4] Filtering for non-core extensions closes the searchbar

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #41382 .

### Summary of Changes

added core to filter

### Testing Instructions
open /administrator/index.php?option=com_installer&view=manage
Select the last filter "non-core extensions"

### Actual result BEFORE applying this Pull Request
page releoad
search bar is closed

### Expected result AFTER applying this Pull Request

page releoad
search bar is open

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on dc60c9c060b483344469d5f2bbfe547efd4478a4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41383">issues.joomla.org/tracker/joomla-cms/41383</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on dc60c9c060b483344469d5f2bbfe547efd4478a4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41383">issues.joomla.org/tracker/joomla-cms/41383</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41383">issues.joomla.org/tracker/joomla-cms/41383</a>.</sub>

**Comment by rachelwalraven** [comment]
On Joomla 4.3.5 Dev with PHP 8.1.22 and using Chrome I do not have the issue. When selecting the non-core-extensions the filteroption bar stays open.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41383">issues.joomla.org/tracker/joomla-cms/41383</a>.</sub>

**Comment by HLeithner** [comment]
thanks

**Pull request merged**
