### PR TITLE
Using JLayout for combo field

### PR DESCRIPTION
**Pull request by degobbis**
### Summary of Changes

Please make sure that combo field still work

### Usage

See [Combo form field type](https://docs.joomla.org/Combo_form_field_type) on Joomla!

### Expected result

the combo filed can be overwritten using a layout

### Actual result

No usage of a layout

### Documentation Changes Required

None

### CODE REVIEW

**Comment by zero-24** [comment]
@degobbis i have just fixed some things spaces to tabs and the usage of deploy version ;)

**Comment by degobbis** [comment]
@zero-24 thx

**Comment by degobbis** [comment]
ping @laoneo @zero-24

**Comment by zero-24** [comment]
I can confirm that it sill works as bevore. But it looks like that combo field is broken before and after the patch. Maybe @ciar4n can take a look here if it is realted to the isis restyle.

image

I have just used the sample code prodvided here: https://docs.joomla.org/Combo_form_field_type
```
<field name="myeditbox" type="combo" label="MyEditBox" description="myeditbox_Desc" size="7">
  <option value="1">Option 1</option>
  <option value="2">Option 2</option>
</field>
````

And added it here: https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_content/config.xml#L18

**Comment by ciar4n** [comment]
I can only really help with CSS. This appears to be more of a JS issue. The dropdown here is been positioned by JS added inline. Only on some views it appears to be positioning relevant to the toggle button rather than the input field. Testing this in a module XML and it appears to work fine 😕

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on 16c3dd18c3b306aba3823dc2345897a282755c91<br /><br />It works like before and the issue i mention above is a different one. Thanks @degobbis <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16293">issues.joomla.org/tracker/joomla-cms/16293</a>.</sub>

**Comment by laoneo** [comment]
I have tested this item :white_check_mark: successfully on 16c3dd18c3b306aba3823dc2345897a282755c91<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16293">issues.joomla.org/tracker/joomla-cms/16293</a>.</sub>

**Comment by ghost** [comment]
RTC after two successful tests.

**Pull request merged**
