### PR TITLE
Update CodeMirror to 5.56.0

### LINKED ISSUE #30338: [3.x] Codemirror update
Codemirror needs to be updated as its several point releases out of date.

There is a script that has been used in the past to generate the update https://github.com/okonomiyaki3000/joomla-codemirror-builder

However I just tried and got errors - and I dont have time/skill/interest in working out the error.

### PR DESCRIPTION
**Pull request by SharkyKZ**
Closes https://github.com/joomla/joomla-cms/issues/30338.

### Summary of Changes

Update CodeMirror using https://github.com/okonomiyaki3000/joomla-codemirror-builder.

List of changes https://github.com/codemirror/CodeMirror/compare/5.52.2...5.56.0.

### Testing Instructions

Test that CodeMirror still works.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by brianteeman** [comment]
thanks

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 54c914d4b6156638cf8fc4e81bd1875fa6806e36<br /><br />Tested 
- on win10 with firefox and edge.
- in backend and frontend for writing articles. 
- Compared Plugins Settings from the older versiom. 

Everythin is ok in my environment.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30370">issues.joomla.org/tracker/joomla-cms/30370</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 54c914d4b6156638cf8fc4e81bd1875fa6806e36<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30370">issues.joomla.org/tracker/joomla-cms/30370</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30370">issues.joomla.org/tracker/joomla-cms/30370</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 54c914d4b6156638cf8fc4e81bd1875fa6806e36<br /><br />One more test is never bad ... just as I've finished it had become RTC ;-)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30370">issues.joomla.org/tracker/joomla-cms/30370</a>.</sub>

**Comment by infograf768** [comment]
Works fine here, also when used by a 3rd party extension (com_localise)

**Comment by infograf768** [comment]
Tks

**Pull request merged**
