### PR TITLE
[4.0] privacy consent descriptions

### PR DESCRIPTION
**Pull request by brianteeman**
descriptions should end with a .

code review

### CODE REVIEW

**Review by saumyasarkar11 — APPROVED** [review]

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 7170b1fe34021479f09a06f77c0938ca58a09861<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32882">issues.joomla.org/tracker/joomla-cms/32882</a>.</sub>

**Comment by PhilETaylor** [comment]
I have tested this item :white_check_mark: successfully on 7170b1fe34021479f09a06f77c0938ca58a09861<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32882">issues.joomla.org/tracker/joomla-cms/32882</a>.</sub>

**Comment by saumyasarkar11** [comment]
RTC

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/32882">issues.joomla.org/tracker/joomla-cms/32882</a>.</sub>

**Comment by Quy** [comment]
Thanks.

**Comment by brianteeman** [comment]
thx

**Pull request merged**
