### PR TITLE
[4.0] Fix disable and enable buttons

### PR DESCRIPTION
**Pull request by maliouris**
Pull Request for Issue # .

### Summary of Changes
Remove connectedCallback() call from the constructor as it might cause some issues later and moved a part of code from the costructor to the connectedCallback() function in order to disable buttons properly

### CODE REVIEW

**Comment by infograf768** [comment]
Please solve conflicting file

**Comment by infograf768** [comment]
@Fedik 
is that one OK?

**Comment by Fedik** [comment]
yes that looks good :wink:

**Comment by wilsonge** [comment]
Awesome stuff! Thankyou very much!

**Pull request merged**
