### PR TITLE
PHP8 fix Debug plugin setMediaVersion use String

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue #38847 .

### Summary of Changes

Use empty String instead of `null`.

### Testing Instructions

Please follow #38847

### CODE REVIEW

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on ec5b6f2f60d9c922ec7ab881a780f477c1648b18<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38848">issues.joomla.org/tracker/joomla-cms/38848</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on ec5b6f2f60d9c922ec7ab881a780f477c1648b18<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38848">issues.joomla.org/tracker/joomla-cms/38848</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38848">issues.joomla.org/tracker/joomla-cms/38848</a>.</sub>

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
