### PR TITLE
[4.0] left sidebar align

### PR DESCRIPTION
**Pull request by astridx**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/26201.

### Summary of Changes
No margin for sidebar left.

### Testing Instructions

1. Apply this patch and run `node build.js --compile-css` for updating the changed `scss` file. Alternatively you can run `npm i`.
2. Add a module to the left sidebar.
3. Open the side in the front end and see, that the Cassiopeia sidebars and component area horizontally aligned.

### Expected result
Cassiopeia sidebars and component area horizontally aligned.

### Actual result
Cassiopeia sidebars and component area not horizontally aligned.

### Documentation Changes Required
No

### CODE REVIEW

**Comment by Scrabble96** [comment]
This PR needs to include no top margin for the container-component as well. As I said in my issue #26201, if there is no left sidebar but there is a right sidebar, then the margin is applied to the component area and the right sidebar appears higher than the component (at least it does on larger screens; on the smallest screens both left and right sidebars drop down below the component area.)

**Comment by astridx** [comment]
@Scrabble96 You are right. I added the missing class now.

**Comment by ChristineWk** [comment]
@astridx As I don't know about npm /node, I tried as follows:
Changed in template.css (line 12349) from the file: https://github.com/joomla/joomla-cms/pull/26210/commits/a236fc6808d44c66c0702e779b5615005d2ee58a accordingly. 

But I think there is missing after: margin-bottom:20px; **}** Because the: + **div** becomes:red instead green. So, I added the missing }
Unfortunately still Actual Result. Also I don't know how to compile it to scss file. Sorry. 
 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26210">issues.joomla.org/tracker/joomla-cms/26210</a>.</sub>

**Comment by astridx** [comment]
@ChristineWK  Thank you for trying to test. If you like to make you familiar with the environment this is a good entry for windows users: https://www.wicked-software.de/joomla-v4-0-win10-composer-and-npm

**Comment by ChristineWk** [comment]
@astridx Thank you for your info - I hv to study :-)

just OT: On my test-site (using user.css) entered: 

.site-grid .container-header + div:not(.container-banner) {
    margin-top: 0px;
}
it looks OK.
regards, christine

**Comment by ChristineWk** [comment]
Hi Astrid,

Thanks for adding commits. After activating under Options CI Server Settings > Switch CI Integration > ON unfortenately (still):
The patch could not be applied either due to missing connection to the server or missing patch on the server.

rgds Christine<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26210">issues.joomla.org/tracker/joomla-cms/26210</a>.</sub>

**Comment by ChristineWk** [comment]
The reason for might be:
"This branch is out-of-date with the base branch ..."

**Comment by brianteeman** [comment]
No that would not be the issue

**Comment by ChristineWk** [comment]
@brianteeman 

Thank you for info. What is the issue for? Maybe: "Some checks were not successful. Build is failing ...." 
If you think there is no way, then I would have to stop the activities in this regard.
 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26210">issues.joomla.org/tracker/joomla-cms/26210</a>.</sub>

**Comment by Kaustubharas** [comment]
I have tested this item :red_circle: unsuccessfully on 068cc4abd6b790c1d2671a47250d1e5bfed13da5<br /><br />Cassiopeia sidebars and component area not horizontally aligned.

When a module is present at sidebar-left position, the margin-top: 15px applies to it.

And, when there is no sidebar-left position, the margin-top: 15px applies to the component area,<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26210">issues.joomla.org/tracker/joomla-cms/26210</a>.</sub>

**Comment by patjun** [comment]
without patch
without-patch

patch applied
patch-applied

**Comment by patjun** [comment]
I have tested this item :white_check_mark: successfully on 068cc4abd6b790c1d2671a47250d1e5bfed13da5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26210">issues.joomla.org/tracker/joomla-cms/26210</a>.</sub>

**Comment by sanderpotjer** [comment]
I have tested this item :white_check_mark: successfully on 068cc4abd6b790c1d2671a47250d1e5bfed13da5<br /><br />After test sidebar is nicely aligned. Thanks @astridx<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26210">issues.joomla.org/tracker/joomla-cms/26210</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by Scrabble96** [comment]
Thank you :-)

**Pull request merged**
