### PR TITLE
[5.1] Tour primary button changes size on hover, adding annoying flicker

### PR DESCRIPTION
**Pull request by obuisard**
### Summary of Changes

shepherd-button-primary button needs to have a border always. 
Replaced 'border-color' properties with 'border'.
It also ensures buttons for the tour are consistent to the buttons of the rest of the interface (in dark mode especially, where borders are more prominent).

### Testing Instructions

Get the latest 5.1 version.
Start a tour.
Hover the 'Start' button.

### Actual result BEFORE applying this Pull Request

The Start button gets a border on hover, while the initial button does not have a border, resulting on a certain flicker.

### Expected result AFTER applying this Pull Request

No flicker, the primary button looks like the rest of the primary buttons on the page.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 17f45b7c8e722b4bd5191f85443b6184e772003a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43038">issues.joomla.org/tracker/joomla-cms/43038</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 17f45b7c8e722b4bd5191f85443b6184e772003a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43038">issues.joomla.org/tracker/joomla-cms/43038</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43038">issues.joomla.org/tracker/joomla-cms/43038</a>.</sub>

**Comment by garstud** [comment]
I have tested this item :white_check_mark: successfully on 17f45b7c8e722b4bd5191f85443b6184e772003a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43038">issues.joomla.org/tracker/joomla-cms/43038</a>.</sub>

**Pull request merged**
