### PR TITLE
Added module event triggers

### PR DESCRIPTION
**Pull request by ghost**
This PR adds 4 event triggers in the module rendering process.
This gives the ability to extensions to manipulate the module list and modules themselves.

Currently extensions that do this (like MetaMod, Advanced Module Manager, T3 framework) are forced to override the module helper class. Which causes compatibility issues.

By adding these extra events in core, it opens up flexibility and possibilities for everyone.
### onPrepareModuleList

```
$app->triggerEvent('onPrepareModuleList', array(&$modules));
```

This is triggered just before the module list is fetched from the database.
If a handler creates a module list itself (by setting the $modules variable to an array), then the core will not attempt to fetch modules itself (after this event).
### onAfterModuleList

```
$app->triggerEvent('onAfterModuleList', array(&$modules));
```

This is triggered just after the module list is fetched from the database.
This can be used to manipulate the module list by adding/removing modules, or even changing the modules data.
### onAfterCleanModuleList

```
$app->triggerEvent('onAfterCleanModuleList', array(&$modules));
```

After the previous `onAfterModuleList` trigger, the module list is cleaned by removing any duplicates.
The `onAfterCleanModuleList` event is triggered just after this cleaning. Again, so that the list can be manipulated before it is returned.
### onRenderModule

```
$app->triggerEvent('onRenderModule', array(&$module, &$attribs));
```

This is triggered near the end of the `renderModule` method.
It passes the `$module``(and``$attribs``) to the event handler. This makes it possible to manipulate the modules data. If the event handler nulls the``$module```, it will return an empty string, instead of passing the module's content to the templates chrome.
## Code syntax cleanup

This PR also moves some of the code in the module list method `load` to some separate methods to make the code clearer and cleaner.
Added methods are:
`getModuleList` which does the main database querying to get the module list
`cleanModuleList` which cleans the final module list (removing duplicates)
## Testing

As an example for the `onRenderModule` you could do this in a plugin:

```
class plgSystemMyPlugin
{
    public function onRenderModule(&$module)
    {
        // Module is nulled
        if (is_null($module))
        {
            return;
        }

        // Just add some text before the module text
        $module->content = '<p>TESTING</p>' . $module->content;
    }
}
```

### CODE REVIEW

**Comment by nonumber** [comment]
Looks like Travis is having issues...

**Comment by mbabker** [comment]
It's an issue with one of the dependencies of pear/Cache_Lite (the dependency apparently released a new version today).  See https://pear.php.net/bugs/bug.php?id=20511

**Comment by mbabker** [comment]
You can also merge staging in and Travis will work right again.  Made some tweaks to not use PEAR for any of the testing dependencies.

**Comment by nonumber** [comment]
All is well. Please test and/or give feedback...

**Comment by compojoom** [comment]
Tested and it works. 
When you create your module make sure to not return an array in the onPrepareModuleList method, but to actually set the $modules variable to array.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6320">issues.joomla.org/joomla-cms/6320</a>.</sub>

**Comment by yvesh** [comment]
Tested and it works :heart: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6320">issues.joomla.org/joomla-cms/6320</a>.</sub>

**Comment by nonumber** [comment]
Cool, thanks!

**Comment by zero-24** [comment]
RTC based on testing. Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6320">issues.joomla.org/joomla-cms/6320</a>.</sub>

**Comment by phproberto** [comment]
Merged. Thanks!

**Comment by nonumber** [comment]
Thank you :)

**Comment by Mathewlenning** [comment]
I think this is one of those merges that @Hackwar was talking about regarding SemVer compliance. We really should try to keep these "Improvements" to minor releases. Especially considering that it breaks @nonumber own extension on T3 and Helix and probably a few too.

**Comment by Kubik-Rubik** [comment]
@Mathewlenning You are right, I would not merge it into the 3.4.x branch, it should have been merged in 3.5.0 because it introduces a new feature (behavior)!

**Comment by nonumber** [comment]
Issues are created when 3rd party extensions overrule core functionality.
Other extensions rely on (new) core features. If the extensions that override the functionality do not support these features, stuff breaks. Which is the case now with this.

On the other hand, this PR is there to prevent this in the future, as the reason these 3rd party extensions are overriding the core module helper, is because of the missing triggers added through this PR.

**Comment by Mathewlenning** [comment]
@nonumber The problem isn't caused by 3rd party extensions. Because those extensions worked until this PR. The problem is that the core changed behavior in a patch release. 

This PR might make it easier for 3PD to accomplish the same thing in the future, but that doesn't justify breaking their extensions without so much as a warning. 

If we are SemVer then we must be SemVer, if we are not then we need to stop pretending we are.

**Comment by Bakual** [comment]
@Mathewlenning and @Kubik-Rubik are right, this shouldn't have been merged into a patch release. It should have gone into the next minor (3.5.0). We're basically create new APIs here, which can only happen in minor releases, not patch releases.

**Comment by davdebcom** [comment]
@nonumber_nl Is there a way to make this backwards compatible now, so it
can stay in? Like adding it as a new method/function/whatever instead of
overwriting existing.

Just thinking out load...

**Comment by nonumber** [comment]
This doesn't break BC.
These are new triggers that you can use or not.

The issue here is that 3rd party extensions have decided to override the module helper. These are not updated to use these new triggers yet.
So if there are other extensions that do use these new triggers, they will fail, as these triggers are not present in the 3rd party overrides.

Solution: 3rd party devs need to update their code to stay in sync with core!

**Comment by Bakual** [comment]
The issue isn't with B/C. That would be fine.
The real issue is that according to SemVer it wasn't allowed to go into a patch release. Since it introduces new features.

**Comment by mbabker** [comment]
The two options at this point are break B/C by reverting the patch just to re-apply it for 3.5 or to carry on and add it to lessons learned.

**Comment by Bakual** [comment]
Exactly :smile:

**Comment by Mathewlenning** [comment]
If those are the options, I vote for lessons learned. 

Sincerely,
Mathew Lenning

Babel-university.com

P.S. This message was sent via iPhone, so please forgive any errors

**Pull request closed without merging**
