### PR TITLE
[4.0] Move the switcher code to the right place

### PR DESCRIPTION
**Pull request by dgrammatiko**
Fields are parts of Joomla so their code cannot be in the `media\vendor` folder

Pull Request for Issue # .

### Summary of Changes
- Just move code around
- Fixes the Grunt (although the proper fix is to kill it) so we can compile/transpile CE

### Testing Instructions
Go to admin-> global configuration
Switches should render and function normally

### Documentation Changes Required
Not for this one

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 6bffe8fa0a63008022e67a531b1b7745021fac6e<br /><br />Can't uninstall Pull Request cause:

bildschirmfoto 2018-01-03 um 14 46 02

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19274">issues.joomla.org/tracker/joomla-cms/19274</a>.</sub>

**Comment by dgrammatiko** [comment]
@franz-wohlkoenig that’s normal as patch tester can’t find the original file in that location (it doesn’t exit)

**Review by C-Lodder — APPROVED** [review]

**Comment by C-Lodder** [comment]
Ignore Hound comments

**Comment by anuragteapot** [comment]
I have tested this item :white_check_mark: successfully on 6bffe8fa0a63008022e67a531b1b7745021fac6e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19274">issues.joomla.org/tracker/joomla-cms/19274</a>.</sub>

**Comment by Quy** [comment]
RTC

**Comment by C-Lodder** [comment]
Conflict needs fixing first

**Comment by dgrammatiko** [comment]
This was merged with #19407 so closing here

**Pull request closed without merging**
