### PR TITLE
make status order icon responsively correct in mobile view

### PR DESCRIPTION
**Pull request by pinak3748**
Pull Request for Issue # .

### Summary of Changes

On every page which has status column in which the status icon was not properly aligned in mobile view.
The order icon was going below the status.

it is same issue as #34709 

### Testing Instructions

- Firstly, run `npm ci`  in order to compile new SCSS changes

and

- You need to have some entry on every page that has a status column.

### Actual result BEFORE applying this Pull Request

before

### Expected result AFTER applying this Pull Request

after

### CODE REVIEW

**Comment by Quy** [comment]
Thank you for the PR, however, this is already fixed in #34714.

**Comment by brianteeman** [comment]
Sorry @pinak3748 as you closed it without a replacement I did it.

**Comment by pinak3748** [comment]
i thought you said to create a new pr so that's why i closed it

**Comment by pinak3748** [comment]
no worry it was fun working on real production.

**Pull request closed without merging**
