### PR TITLE
Number validation as global handler

### PR DESCRIPTION
**Pull request by jackkum**
Pull Request for Issue #5619 .
#### Summary of Changes
- Added handler for the number field validation
- Minified uncompressed file
#### Testing Instructions
1. Go to the Joomla administration
2. Then: System => Global Configuration => System (Tab) => Session Settings 
3. Try input in the field 'Session Lifetime' zero or negative value

You should see error (red border around and title on mouseover)

This PR add handler as global, only for session lifetime (com_config) here: #9997

### CODE REVIEW

**Comment by piotr-cz** [comment]
Could you use 4 spaces as described [here](http://joomla.github.io/coding-standards/?coding-standards/chapters/javascript.md)?

This file is really botched in terms of indentation 
tabsspacesboth

**Comment by jackkum** [comment]
@piotr-cz :laughing: 
Look at this line https://github.com/joomla/joomla-cms/blob/staging/media/system/js/validate-uncompressed.js#L189 
Fix all?

**Comment by piotr-cz** [comment]
I'd love to, but probably not in this PR, because it would break git diffs (all lines would show as changed).

Looks like 2x tabs would fit current CS here (ATM there is space + tab + space + tab :smile: ).

**Comment by Fedik** [comment]
Hm, why it names "number" validation? I see only some "range" validation.
It will return `true` for the string that not a number.

**Comment by jackkum** [comment]
Need a PR for add `class="validate-range"` in a file `administrator/components/com_config/model/form/application.xml` for the field `lifetime`.

**Comment by brianteeman** [comment]
@jackkum Sorry I dont understand your last comment<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9998">issues.joomla.org/joomla-cms/9998</a>.</sub>

**Comment by jackkum** [comment]
@brianteeman 
By @Fedik advice i renamed `number` to `range` and validation on client side for the field `lifetime` will not be applied, so need a PR for this.

Sorry for my English.

**Comment by rahultomar** [comment]
Can you please mention the Both scenario before patch and after patch, as i tested and it seems working same in both cases <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9998">issues.joomla.org/joomla-cms/9998</a>.</sub>

**Comment by RonakParmar** [comment]
I have tested this PR in Joomla! 3.6.4, before patch and after patch the session field is working same in bath scenarios.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9998">issues.joomla.org/tracker/joomla-cms/9998</a>.</sub>

**Comment by jeckodevelopment** [comment]
@jackkum can you please fix the conflicts?
` media/system/js/validate.js `

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on d2a18fbcacf89d0a6692e0a39e6d0c8cc70219a5<br /><br />Before and after Patch works in same Way.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9998">issues.joomla.org/tracker/joomla-cms/9998</a>.</sub>

**Comment by RonakParmar** [comment]
@jackkum  Can you please fix conflict in media/system/js/validate.js file?

**Comment by brianteeman** [comment]
@jackkum it has been six months since the first request to resolve the merge conflicts. Also as several people have reported that they cannot see any difference after applying the PR I am going to close this at this time. It can always be reopened if you resolve the conflicts and address the comments about no change after this PR

**Pull request closed without merging**
