### PR TITLE
[3] - same DDL for table #__contact_details

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #31271

### Summary of Changes
Table `#__contact_details`  the same from install #__contact_details

### Testing Instructions

code review

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 066f6a6d44c6eeef0cfc142813ee570f5d905134<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31274">issues.joomla.org/tracker/joomla-cms/31274</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 066f6a6d44c6eeef0cfc142813ee570f5d905134<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31274">issues.joomla.org/tracker/joomla-cms/31274</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31274">issues.joomla.org/tracker/joomla-cms/31274</a>.</sub>

**Comment by HLeithner** [comment]
Whats the reason for changing char to varchar for the language column? My understanding is that char always reserves 7 char (I expect bytes) and varchar in could be 5 to 28 bytes which have a performance penalty for utf8 and variable length.

Maybe my information are wrong or outdated ymmv.

**Comment by alikon** [comment]
it come from https://github.com/joomla/joomla-cms/commit/2428786dd06c5a4deff34e0dc1a4501b286c77ae#diff-be47cba58b55d509f8fe51ce691d0aa15c0272086fdbb6ea6a319ced93c6cc41R284

https://github.com/joomla/joomla-cms/pull/14113 some kind of 4 y ago

**Comment by alikon** [comment]
it come from https://github.com/joomla/joomla-cms/commit/2428786dd06c5a4deff34e0dc1a4501b286c77ae#diff-be47cba58b55d509f8fe51ce691d0aa15c0272086fdbb6ea6a319ced93c6cc41R284

https://github.com/joomla/joomla-cms/pull/14113 some kind of 4 y ago

**Comment by HLeithner** [comment]
thanks

**Pull request merged**
