### PR TITLE
[4.0] Fix Hide Article Options #36168 [revert revert]

### PR DESCRIPTION
**Pull request by HLeithner**
Redone the pull request https://github.com/joomla/joomla-cms/pull/36168 I accidentally merged.
@wilsonge can be merged after release

sorry @joomdonation

### CODE REVIEW

**Comment by joomdonation** [comment]
I thought I made something broken with the PR :D.

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on 98c9f006ca44107f29c598d1e051547ea95d8682<br /><br />Still works!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36182">issues.joomla.org/tracker/joomla-cms/36182</a>.</sub>

**Comment by khu5h1** [comment]
I have tested this item :white_check_mark: successfully on 98c9f006ca44107f29c598d1e051547ea95d8682<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36182">issues.joomla.org/tracker/joomla-cms/36182</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36182">issues.joomla.org/tracker/joomla-cms/36182</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36182">issues.joomla.org/tracker/joomla-cms/36182</a>.</sub>

**Comment by pritam825** [comment]
I have tested this item :white_check_mark: successfully on 98c9f006ca44107f29c598d1e051547ea95d8682<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36182">issues.joomla.org/tracker/joomla-cms/36182</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
