### PR TITLE
[4.3] Update notification email

### PR DESCRIPTION
**Pull request by brianteeman**
Minor change to remove the words "for download". As the majority of people will never download the update it is enough to just say "Your site has discovered that there is an updated version of Joomla! available"

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 025d573ec018d379dee971853b395154b67e3b10<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40266">issues.joomla.org/tracker/joomla-cms/40266</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 025d573ec018d379dee971853b395154b67e3b10<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40266">issues.joomla.org/tracker/joomla-cms/40266</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40266">issues.joomla.org/tracker/joomla-cms/40266</a>.</sub>

**Comment by sdwjoomla** [comment]
Thanks brianteeman

**Comment by brianteeman** [comment]
thx

**Pull request merged**
