### PR TITLE
[4] com_installer warnings empty state

### PR DESCRIPTION
**Pull request by PhilETaylor**
### Testing Instructions

Fix all your warnings ;-) 

### Actual result BEFORE applying this Pull Request

Screenshot 2021-04-29 at 19 03 21

### Expected result AFTER applying this Pull Request

Screenshot 2021-04-29 at 19 03 11

and if you have a warning the link on the documentation is updated

Screenshot 2021-04-29 at 19 18 18

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on f4ce3634d0a13792bdf32c92da45f3db675a9e51<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33411">issues.joomla.org/tracker/joomla-cms/33411</a>.</sub>

**Comment by PhilETaylor** [comment]
@Quy ... What? not even ONE comment? not one thing to change... I'm going to need to lie down and gather my thoughts hahahahahahahhaah

Thanks for all your testing and mopping up my spills :)

**Comment by Quy** [comment]
I am speechless. 🤣 You're very welcome! Keep up the awesome work!!!

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on f4ce3634d0a13792bdf32c92da45f3db675a9e51<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33411">issues.joomla.org/tracker/joomla-cms/33411</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33411">issues.joomla.org/tracker/joomla-cms/33411</a>.</sub>

**Comment by drmenzelit** [comment]
Thanks

**Pull request merged**
