### PR TITLE
com_redirect adding urls larger than 255

### PR DESCRIPTION
**Pull request by Kixo**
.after some reading up I found up that maximum allowed URL in IE is 2083, other browsers allow much higher numbers, even over 100.000, but we must stand with the lowest one, so I set it up for 2083.
Example description here: http://www.boutell.com/newfaq/misc/urllength.html

In this PR I have removed unique constraint. When we insert new row we are actually doing this check inside of the Joomla code, so this is not needed. And it was making a trouble because maximum varchar key for unique key is 767. So while removing it for mysql, I removed it for all DBs because as stated above, it is not needed.

Please check this code against Postgre and sqlazure if possible.

### CODE REVIEW

**Comment by waader** [comment]
@test failed for mssql

Please add the closing ) in installation/sql/sqlazure/joomla.sql line 2364.

Unrelated to that but found in the course of testing: Saving a link in the redirect component gives an error when using postgresql or mssql as database because NULL cannot be inserted into column "referer".

**Comment by Kixo** [comment]
thanks for testing @waader I uninstalled mssql so I did not test changes for the second time.
I have updated the PR with corrected SQL.

**Comment by waader** [comment]
There is another small problem. In 3.4.0-2014-09-16.sql 

ALTER TABLE `#__redirect_links` MODIFY new_url varchar(255);

results in this problem - when you update the database schema via "Extension manager" > Database > Fix:

Table 'uy937_redirect_links' does not have column 'new_url' with type 'varchar(255)'. (From file 3.4.0-2014-09-16.sql.)

So this line could be deleted.

**Comment by mbabker** [comment]
That column is supposed to be in the table (see https://github.com/joomla/joomla-cms/blob/staging/installation/sql/mysql/joomla.sql#L1517).

**Comment by waader** [comment]
Of course, but there is a conflict with this statement in 3.4.0-2014-10-17.sql

ALTER TABLE `#__redirect_links` CHANGE `new_url` `new_url` varchar(2083) NOT NULL;

**Comment by Kixo** [comment]
@waader I am not exactly sure what the problem is. Can you please explain in more detail or propose the solution.

**Comment by waader** [comment]
The proposed solution was to delete

ALTER TABLE #__redirect_links MODIFY new_url varchar(255);

in 3.4.0-2014-09-16.sql.

**Comment by Kixo** [comment]
ok updated

**Comment by waader** [comment]
@test works with mysql and will probably work with postgresql and mssql. But there is another unrelated problem there. Thanks Kixo!

**Comment by brianteeman** [comment]
Please see #9269

**Pull request closed without merging**
