### PR TITLE
[4.0] Fix validation adding icons to TinyMCE buttons

### PR DESCRIPTION
**Pull request by C-Lodder**
Pull Request for Issue #16567

### Summary of Changes

This PR fixes the form validation JS by which tick icons are added to all the TinyMCE buttons.

### CODE REVIEW

**Comment by zero-24** [comment]
Do you want to have the `min` version of the JS in the the not minified file (validate.js) and the not minified version of the code in the minified file (validate.min.js)?

**Comment by C-Lodder** [comment]
Oh sorry. Comitted too quickly. Will fix after din dins

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on fd3032a05bef63e75be948a56d8713c08b2ba687<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17078">issues.joomla.org/tracker/joomla-cms/17078</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on fd3032a05bef63e75be948a56d8713c08b2ba687<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17078">issues.joomla.org/tracker/joomla-cms/17078</a>.</sub>

**Comment by ghost** [comment]
RTC after two successful tests.

**Pull request merged**
