### PR TITLE
GDPR § 13 implementation into users registration

### PR DESCRIPTION
**Pull request by schultz-it-solutions**
Pull Request for Issue [no issue created beforehand] .

GDPR will be in effect from may 25th, 2018.
One of the implications of this is, that a controller (see GDPR §4.7) is required to inform the 'data subject' about his/her rights regarding the collected personal data "at the time, when this data is collected" (see GDPR §13 https://gdpr-info.eu/art-13-gdpr/ ).

To help website administrators with this requirement, we could include a link to the respective "information article" in the registration form.
I implemented such a solution with this pull request (and am looking forward to discuss this).

### Summary of Changes
1) include three more fields in the [backend] com_users "config.xml"
2) prepare the link to the respective article in [frontend] com_users/views/registration/view.html.php
3) add the link to the registration form, directly before the submit button in [frontend] 
      com_users/views/registration/tmpl/default.php
4 and 5) provide nessessary language strings in backend and frontend

### Testing Instructions
Go to "user administration" [Backend] and open the [Advanced] tab in the user configuration dialog
provide respective info in the last three (new) configuration fields
Goto frontend and register a new user:

### Expected result
the link to the "information regarding GDPR §13" shows up before the submit button
clicking the link opens a new window with this information article

### Actual result
currently there is no support in Joomla to deal with this new legal requirement (although a website admin could of course always circumvent this himself).

### CODE REVIEW

**Comment by mbabker** [comment]
Just looking at how the code is done here, IMO it should NOT be named explicitly regarding GDPR.

- It is not a worldwide law (even if it becomes so in practice)
- There are numerous privacy related laws and regulations worldwide, we should not be coding against or naming tools in the UI for one of those sets of laws and regulations, especially if said laws and regulations are superseded or duplicated in another region under a different name

**Comment by brianteeman** [comment]
How is this different to #20051

**Comment by brianteeman** [comment]
Lots of issues with this PR but I wait for a reply to how it is different to #20051 before commenting further

**Comment by schultz-it-solutions** [comment]
I must have overlooked  #20051 indeed.
I will check it out, but am pretty sure that this is the better course of action. So I close this PR right away.

**Pull request closed without merging**
