### PR TITLE
Removed Automatic Title from SQL installation + unit tests

### PR DESCRIPTION
**Pull request by pe7er**
Some Administrator Modules have an option called "Automatic title" which is not used anymore.
This PR removes all references to 
,"automatic_title":"1"
,"automatic_title":"0"
in SQL files & Unit test.

Please see related items:
Removed Automatic title option from 4 Administrator Modules https://github.com/joomla/joomla-cms/pull/5789
Removed unused Automatic Title from Admin Templates: Hathor & System https://github.com/joomla/joomla-cms/pull/5792

### CODE REVIEW

**Comment by waader** [comment]
There is a general problem with a patch affecting sample data.  When not tested and merged immediatley the are rapidly out of sync. Besides that when all sample data for all databases are touched the are untestable for com_patchtest user.

The only solution I see is to consume them in smaller portions. Is there another way to get such patches in?

**Comment by hvdmeer** [comment]
@pe7er Is there any way I can test this removing of references?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5793">issues.joomla.org/joomla-cms/5793</a>.</sub>

**Comment by pe7er** [comment]
I am not sure. Maybe you could try:

use phpMyAdmin check the #__modules table.
Admin modules might have 
automatic_title":"1" 
or
automatic_title":"0" 
in the params field.

Apply the Patch.
Remove /configuration.php and reinstall the local Joomla website
After installation use phpMyAdmin check the #__modules table.

The automatic_title references should not be there anymore.

BTW: You'll need to install the Patch Tester Component again after this test...<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5793">issues.joomla.org/joomla-cms/5793</a>.</sub>

**Comment by brianteeman** [comment]
As the related PR have already been merged this really should be applied to the installation sql as well<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5793">issues.joomla.org/joomla-cms/5793</a>.</sub>

**Comment by Bakual** [comment]
Agreed and merged based on review.

**Pull request closed without merging**
