### PR TITLE
Add Publish down to content sorting options

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #12483 .

### Summary of Changes
In the front end we can sort by date and chose to use either the created, modified or published dates. This PR add the unpublished date to that list.

This is for the category blog, category list and featured views and there is a new global option as well

#### Part 1
Create a category with 3 featured articles - each with a different Stop Publishing date
Create a category blog, category list and featured menu item to display those articles
In the options for the menu item select
Article Order - Oldest First or Most recent first
Date for Ordering - Unpublished

You will see that the articles are now displayed in the order that they will be unpublished

#### Part 2
Go to the component options for the articles and in the Shared tab set the Date for Ordering to Unpublished
Go back to your three menu items and change the Date for Ordering to Use Global

You will see that the articles are still displayed in the order that they will be unpublished

### CODE REVIEW

**Comment by Martijn-Boomsma** [comment]
- I have applied the patch
- I have created a category with 3 featured articles - each with a different
"Finish Publishing" date.
- I have created a category blog menu item to display those articles
- In the options for the menu item I selected 
->  Article Order - Most recent first
-> Date for Ordering - Unpublished

Nothing I change in the "Finish Publishing" date of the article changes anything in the sorting. See http://prntscr.com/d3045t.  Am I doing something wrong or is the sorting not working as intended?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12615">issues.joomla.org/tracker/joomla-cms/12615</a>.</sub>

**Comment by brianteeman** [comment]
Does this help?

feature

**Comment by Martijn-Boomsma** [comment]
It seems to confirm I have the right settings but patch doesn't work for me:
http://prntscr.com/d30sfn

If you look at screenshot, how can the date Test [#12615] - 1 - 2017-01-16 be last while it should be in the middle. The right order should be Number 2 - 1 - 3 according to the date.

  <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12615">issues.joomla.org/tracker/joomla-cms/12615</a>.</sub>

**Comment by brianteeman** [comment]
i'm as confused as you - thanks for trying though

**Comment by Luchen6** [comment]
I have tested this item :red_circle: unsuccessfully on f3051771c4c8880e265c06741054f05d8dc3b51f<br /><br />Applying the patch does not give the correct result.

Initial order was 'published'; after applying test result was already 'unpublished'.

Cannot change to 'publish' anymore.
Selection box gives strange list.


<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12615">issues.joomla.org/tracker/joomla-cms/12615</a>.</sub>

**Comment by brianteeman** [comment]
So long and farewell

**Pull request closed without merging**
