### PR TITLE
[4.0] breadcrumbs Changing unordered list to ordered list

### PR DESCRIPTION
**Pull request by yaume**
Un unordered list seems to be semantically wrong. An ordered list could be better

Issue #16312

### Documentation Changes Required

[Google guides](https://developers.google.com/search/docs/data-types/breadcrumbs)
[BreadcrumbList](http://schema.org/BreadcrumbList)

### CODE REVIEW

**Comment by brianteeman** [comment]
I suspect that this will have to wait until j4 as it potentially will break the layout on an existing site

**Comment by yaume** [comment]
It'll wait quite easely as it's not very important and it can be overrided

**Comment by brianteeman** [comment]
updated title

**Comment by C-Lodder** [comment]
Seem fine for J4.

@yaume - would you mind submitting a PR against the `4.0-dev` branch instead?

**Comment by zero-24** [comment]
@C-Lodder i have just changed the base branch. So @yaume don't need to do anything ;) Just someone review / test & merge against 4.0

**Comment by C-Lodder** [comment]
I have tested this item :white_check_mark: successfully on 2c361e7d5b39f925da6a7558f836e6c5b7be9698<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16313">issues.joomla.org/tracker/joomla-cms/16313</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :red_circle: unsuccessfully on 2c361e7d5b39f925da6a7558f836e6c5b7be9698<br /><br />please see Screenshot below for Reason of unsuccessfully Test:

bildschirmfoto 2017-07-20 um 16 08 28
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16313">issues.joomla.org/tracker/joomla-cms/16313</a>.</sub>

**Comment by C-Lodder** [comment]
Hmm, worked for me in FF. What browser are you using @franz-wohlkoenig ?

**Comment by ghost** [comment]
### System information
4.0.0-dev
macOS Sierra, 10.12.5
Firefox 54 (64-bit)
#### MAMP 4.1.1
- PHP 7.0.15
- MySQLi 5.6.35

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 2c361e7d5b39f925da6a7558f836e6c5b7be9698<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16313">issues.joomla.org/tracker/joomla-cms/16313</a>.</sub>

**Comment by ghost** [comment]
RTC after two successful tests.

**Comment by C-Lodder** [comment]
Are you still having issues with this one franz?

**Comment by zero-24** [comment]
any feedback on this @franz-wohlkoenig ?

**Comment by brianteeman** [comment]
Once this is merged we can look at making it accessible

**Comment by ghost** [comment]
Sorry @zero-24 , missed Question. Will have a Look when #17594 is solved.

**Comment by ghost** [comment]
@C-Lodder Answer on your [Comment](https://github.com/joomla/joomla-cms/pull/16313#issuecomment-318813809): Issue is solved.

**Comment by zero-24** [comment]
merging than. Thanks for the feedback. Thanks @yaume for your contribution!

**Pull request merged**
