### PR TITLE
Install Languages duplicated in potsgres #9188

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #9188 .
#### Steps to reproduce the issue

>  Install Joomla staging on a postrgresl database
>  Go to extensions install languages
> Observe number of languages displayed
> Click on find languages
> #### Expected result
> 
> The list of available languages should not change
> #### Actual result
> 
> Every language is repeated in the list
#### Comment

in sql `"pkg_de-DE"` is not like `strtolower("pkg_de-DE")`

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 9435131603f16e62bc52442c0d9d2b7992779c8f<br /><br />Tested only with mariadb (mysql) and works as before, so if it works in postrgresl too ok.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9241">issues.joomla.org/joomla-cms/9241</a>.</sub>

**Comment by waader** [comment]
I have tested this item :white_check_mark: successfully on 9435131603f16e62bc52442c0d9d2b7992779c8f<br /><br />Tested with mysql and postgresql. Thanks alikon!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9241">issues.joomla.org/joomla-cms/9241</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 9435131603f16e62bc52442c0d9d2b7992779c8f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9241">issues.joomla.org/joomla-cms/9241</a>.</sub>

**Comment by brianteeman** [comment]
Great to see we finally have some more people testing with pgsql 

Setting RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9241">issues.joomla.org/joomla-cms/9241</a>.</sub>

**Pull request merged**
