### PR TITLE
[4.0] a11y plugin description

### PR DESCRIPTION
**Pull request by brianteeman**
Simple PR to update the description of the plugin as its more than just for the admin interface

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 934782a7ac619e468b7a894b0ce225d06504e028<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28837">issues.joomla.org/tracker/joomla-cms/28837</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 934782a7ac619e468b7a894b0ce225d06504e028<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28837">issues.joomla.org/tracker/joomla-cms/28837</a>.</sub>

**Comment by jwaisner** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28837">issues.joomla.org/tracker/joomla-cms/28837</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
