### PR TITLE
[4.0] Group toolbar buttons in com_plugins

### PR DESCRIPTION
**Pull request by chmst**
### Summary of Changes
This PR continues the grouping of action buttons in the backend (see #22832, #22393, #23337 and #23336, #23374, #23368, #23380). This time the plugins overview.

### Testing Instructions
Go to the plugins overview in the backend and check the toolbar. There should be a "Change status" dropdown now which activates when you select one or more plugins.

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 9c9ab6100eaf97237debedb82d097bdb3b7a884b<br /><br />just a question - for instance: User-Joomla Plugin should not be possible to disable (?) <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23391">issues.joomla.org/tracker/joomla-cms/23391</a>.</sub>

**Comment by Hackwar** [comment]
I have tested this item :white_check_mark: successfully on 9c9ab6100eaf97237debedb82d097bdb3b7a884b<br /><br />I tested this successfully. And @ChristineWk every plugin should be disablebel. There are plugins out there that replace that plugin for example.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23391">issues.joomla.org/tracker/joomla-cms/23391</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23391">issues.joomla.org/tracker/joomla-cms/23391</a>.</sub>

**Comment by wilsonge** [comment]
Thanks :)

**Pull request merged**
