### PR TITLE
Tinymce doesn't need to remove the images basepath

### PR DESCRIPTION
**Pull request by HLeithner**
Pull Request for Issue #25015 .

### Summary of Changes
Removed the deletion of the image base path from the upload path.

### Testing Instructions
c/p from https://github.com/joomla/joomla-cms/issues/25015#issuecomment-496568853

Create a sub-directory of "images" under the main images directory.
Create a sub-directory of "testing123" under that directory.

Update the plugin: Editor - TinyMCE
Make sure you are editing tab "Set 0" so Administrator is showing in the groups that use this profile.
Under the "Images Directory" setting, select "images/testing123" (save & close)

> please try all variants

the actual path on the server is "images/images/testing123"
Go under content, and articles and either create a new or edit an existing.

Drag and Drop an image into the content window.

Also change the image and file path in com_media options and try it with different pathes

### Expected result
You should not receive an error and see the image.

### Actual result
You should receive an error the file can not be uploaded, showing the filename as undefined.

### CODE REVIEW

**Comment by GCLW** [comment]
Tested with above listed parameters and this update worked.
Additional tests:

Set TinyMCE image dir to images (images/images) - Drag and Drop worked.
Set TinyMCE to just a sub-directory under the main images directory - Drag and Drop worked.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25037">issues.joomla.org/tracker/joomla-cms/25037</a>.</sub>

**Comment by GCLW** [comment]
I have tested this item :white_check_mark: successfully on e2becdf24555d3f09347237918faf7ee9d1c6b93<br /><br />Tested with above listed parameters and this update worked.
Additional tests:

Set TinyMCE image dir to images (images/images) - Drag and Drop worked.
Set TinyMCE to just a sub-directory under the main images directory - Drag and Drop worked.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25037">issues.joomla.org/tracker/joomla-cms/25037</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on e2becdf24555d3f09347237918faf7ee9d1c6b93<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25037">issues.joomla.org/tracker/joomla-cms/25037</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25037">issues.joomla.org/tracker/joomla-cms/25037</a>.</sub>

**Comment by dgrammatiko** [comment]
The test instructions don’t reflect what that part of the code was supposed to cover. You need to test this after setting a different directory for the images in com_media...

**Comment by ghost** [comment]
@dgrammatiko should RTC be removed?

**Comment by HLeithner** [comment]
@dgrammatiko thx for the info but the parameter in the plugin doesn't add the base path to the return value, so it's not needed anyway or do I missing something in the history?

Updated test instructions.

**Comment by dgrammatiko** [comment]
As far as I understand the issue is that if you populate the field in tinymce for the final storage path people expect it to be relative to images but in reality it always wasn’t. Actually a better description for that field would do here (eg if you want a folder something relative to images then type images/something). By the way removing this logic in staging is a B/C break for those not using the root/images path for the media manager (I’m one of those few ppl)

**Comment by HLeithner** [comment]
You can't enter a path in the plugin I think you created a new fieldtype "imagespath" and you have to select it from the dropdown.

**Comment by brianteeman** [comment]
@dgrammatiko is referring to this option in the media manager
image

**Comment by HLeithner** [comment]
thats the path used in the plugin and is added automatically on upload, not if you set the path in the plugin. ymmv

**Comment by dgrammatiko** [comment]
@HLeithner quite honestly I thought that I had introduced that piece of code but looking at the initial commit of the drag and drop it seems that isn't the case, eg: https://github.com/joomla/joomla-cms/blob/3bb31c895604ce001bc16289dbff5b90f48ef31b/plugins/editors/tinymce/tinymce.php#L625-L665 the code doesn't have all these preg/replaces there... (https://github.com/joomla/joomla-cms/pull/7435 )
Then looking at the github blame https://github.com/joomla/joomla-cms/pull/15057 comes up as the bug source. 
Anyways by reviewing the code I think this should work fine, all the extra code there is kinda bloat but please check the case when a user has a diferent media path than the standard `images` folder

**Comment by HLeithner** [comment]
@dgrammatiko ok thx, I added the imagepath property to the test instructions and tested it by my self without any problems for the drag and drop upload.

**Comment by Quy** [comment]
Tested successfully with a different image root folder.

**Comment by rdeutz** [comment]
All JSessionTest are failing because of  "Warning: A non-numeric value encountered in C:\projects\joomla-cms\libraries\vendor\joomla\string\src\phputf8\utf8.php on line 38"

I can't tell what is wrong and I am sorry but I don't have the time now to dig into this deeper. Just reporting, this fails only on 7.2

**Pull request merged**
