### PR TITLE
Import JFolder (Fix #7265)

### LINKED ISSUE #7265: [REGRESSION] - Class 'JFolder' not found in languagefilter.php
#### Steps to reproduce the issue
- Have a multilingual site
- In Language Filter set Automatic Language Change to "Yes"
- Create an user and assign to him/her a language different from the default one
- Navigate to the default language home page
- Login with the above created user

#### Expected result
User logged in and redirected to assigned language

#### Actual result
You'll get an error:
`Fatal error: Class 'JFolder' not found in base-path/plugins/system/languagefilter/languagefilter.php on line 527`

#### Additional comments

I don't have the slightest clue why this is happening!

### PR DESCRIPTION
**Pull request by mbabker**
JFolder is one of the few non-autoloadable classes.  So, import it.

### CODE REVIEW

**Comment by smz** [comment]
Wow! That's quite a feat, @mbabker! :clap:

#test OK!

**Comment by smz** [comment]
Isn't there a way to make JFolder autoloadoable, **or**, couldn't we create an autoloadable proxy class to for general usage?

**Comment by smz** [comment]
I hope this one will go in 3.4.2...

**Comment by infograf768** [comment]
OK here. Urgent for 3.4.2!

RTC please

**Comment by Bakual** [comment]
> Isn't there a way to make JFolder autoloadoable, or, couldn't we create an autoloadable proxy class for general usage?

We could add the following code to https://github.com/joomla/joomla-cms/blob/staging/libraries/cms.php:
JLoader::register('JFile', JPATH_LIBRARIES . '/joomla/filesystem/file.php');
JLoader::register('JFolder', JPATH_LIBRARIES . '/joomla/filesystem/folder.php');

That would make them autoloading.

In the case of the language filter plugin, you probably could also just use `is_dir()` instead of `JFolder::exists()`. The only difference is that JFolder does some sanitising on the path. I'm not sure that is needed here.

**Comment by smz** [comment]
@Bakual
Is there any particular reason for not having made those two classes autoloadable?
Couldn't had been that the fix for this issue?

I agree `is_dir()` could had been enough in that case: in the next few days I plan to propose a code review of languagefilter.php and I'll adopt your suggestion in it.

**Comment by mbabker** [comment]
> Is there any particular reason for not having made those two classes autoloadable?

It requires renaming the classes in `libraries/joomla/filesystem`.  `JFile` -> `JFilesystemFile` for example.

Truthfully, I wouldn't bother with it at this point.  The next rename should be introducing the Framework's namespaced classes (i.e. `Joomla\Filesystem\File`) which would all be autoloaded anyway.

**Comment by smz** [comment]
Got it, thanks!

**Pull request merged**
