### PR TITLE
[4.0] Mail templates - Fix Paragraph and Remove Whitespace

### PR DESCRIPTION
**Pull request by YatharthVyas**
Pull Request for Issue #33658

### Summary of Changes
Removed blank spaces after \n and made the paragraph break consistently with two \n

### Testing Instructions
<ol>
<li>Visit Backend</li>
<li>System -> Mail Templates</li>
<li>Check the following:
<ul>
<li> Action Logs </li>
<li> Messages: New message </li>
<li> Users: New account with admin activation </li>
<li> Users: New account with admin activation (With PW) </li>
<li> Users: Password Reset </li>
<li> Users: Request to admin to verify new account </li>
</ul>
</li>
</ol>

### Actual result BEFORE applying this Pull Request
Perfectly explained here: #33658

### Expected result AFTER applying this Pull Request
Whitespaces are removed and paragraph breaking is consistent.

### Documentation Changes Required
None

### CODE REVIEW

**Comment by Abernyte-Git** [comment]
I have tested this item :white_check_mark: successfully on decd87581d242e8c351da4f2259a77615c7ea4c5<br /><br />
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33686">issues.joomla.org/tracker/joomla-cms/33686</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on decd87581d242e8c351da4f2259a77615c7ea4c5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33686">issues.joomla.org/tracker/joomla-cms/33686</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33686">issues.joomla.org/tracker/joomla-cms/33686</a>.</sub>

**Comment by richard67** [comment]
Thanks!

**Comment by YatharthVyas** [comment]
Thanks everyone

**Pull request merged**
