### PR TITLE
[4.0] [mod_tags_similar] Always render module layout

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/20810. Redo of https://github.com/joomla/joomla-cms/pull/20811 for 4.0.

### Summary of Changes

Moves early return when no items are found to the layout. This way the layout is always rendered, allowing users to show custom content when no items are found.
Also removes previously unused message.

### Testing Instructions

On a site without tagged items publish `Tags - Similar` module.
Create module's layout override containing some custom code/message.
Check if the module is displayed.

### Expected result

Module is displayed.

### Actual result

Module not displayed.

### Documentation Changes Required
Probably not.

### CODE REVIEW

**Comment by brianteeman** [comment]
I am not in favour of this change as we have had lots of requests to ensure that a module is not rendered at all if there is no content - this does the opposite

**Comment by HLeithner** [comment]
But it's the better solution, the layout should decide what it should do if the list is empty.

**Comment by SharkyKZ** [comment]
@brianteeman see discussion in #20811. If you're talking about empty module positions appearing in templates, we get them anyways. There's a PR #19416 for fixing that.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 033604419e9ae7f1cd1bfc09dee1f25028ab2db3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24879">issues.joomla.org/tracker/joomla-cms/24879</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 033604419e9ae7f1cd1bfc09dee1f25028ab2db3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24879">issues.joomla.org/tracker/joomla-cms/24879</a>.</sub>

**Comment by ghost** [comment]
Status "Ready To Commit".

**Comment by Quy** [comment]
@wilsonge @roland-d Please merge.  Similar to #25071.

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
