### PR TITLE
[5.1] com_installer getListQuery

### PR DESCRIPTION
**Pull request by brianteeman**
### Summary of Changes
Remove unnecessary duplicated condition

In the method to get the database query in `administrator\components\com_installer\src\Model\UpdateModel.php` a query is constructed that has a duplicated condition `where($db->quoteName('u.extension_id') . ' != 0'`

It is first added 
https://github.com/joomla/joomla-cms/blob/806d2663501a4a431444c92835ab77591888ebf1/administrator/components/com_installer/src/Model/UpdateModel.php#L113

and then added again 
https://github.com/joomla/joomla-cms/blob/806d2663501a4a431444c92835ab77591888ebf1/administrator/components/com_installer/src/Model/UpdateModel.php#L144

### Testing Instructions
Install an old extension and check for updates with debug on to see the queries

### Actual result BEFORE applying this Pull Request
**Query 1**
```
SELECT u.*,`e`.`manifest_cache`
FROM `euj03_updates` AS `u`
LEFT JOIN `euj03_extensions` AS `e` ON `e`.`extension_id` = `u`.`extension_id`
WHERE `u`.`extension_id` != 0 AND `u`.`extension_id` != 0 AND `u`.`extension_id` != :eid
ORDER BY `u`.`name` ASC LIMIT 25

```

**Query 2**
```
SELECT COUNT(*)
FROM `euj03_updates` AS `u`
LEFT JOIN `euj03_extensions` AS `e` ON `e`.`extension_id` = `u`.`extension_id`
WHERE `u`.`extension_id` != 0 AND `u`.`extension_id` != 0 AND `u`.`extension_id` != :eid

```

### Expected result AFTER applying this Pull Request
**Query 1**
```
SELECT u.*,`e`.`manifest_cache`
FROM `euj03_updates` AS `u`
LEFT JOIN `euj03_extensions` AS `e` ON `e`.`extension_id` = `u`.`extension_id`
WHERE `u`.`extension_id` != 0 AND `u`.`extension_id` != :eid
ORDER BY `u`.`name` ASC LIMIT 25

```

**Query 2**
```
SELECT COUNT(*)
FROM `euj03_updates` AS `u`
LEFT JOIN `euj03_extensions` AS `e` ON `e`.`extension_id` = `u`.`extension_id`
WHERE `u`.`extension_id` != 0 AND `u`.`extension_id` != :eid

```

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by HLeithner** [comment]
I rebased it to 5.1 since it's not a bugfix.

**Comment by brianteeman** [comment]
What is it then if its not a bug?

**Comment by rdeutz** [comment]
your change doesn't change the query result, so it is a optimisation and not a bug fix

**Comment by brianteeman** [comment]
your logic escapes me

**Comment by brianteeman** [comment]
The first condition is always applied. The second condition is conditionally applied. So you either get the condition once or twice. You can never have a situation where the condition is not applied. This PR is removing the second condition not the first

**Comment by richard67** [comment]
> The first condition is always applied. The second condition is conditionally applied. So you either get the condition once or twice. You can never have a situation where the condition is not applied. This PR is removing the second condition not the first

I see now. You are right. By review this PR seems right to me.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on c5f096ad80b76d738e1d6167ad2aa26f1de2eaf9<br /><br />Nice catch!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42140">issues.joomla.org/tracker/joomla-cms/42140</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on c5f096ad80b76d738e1d6167ad2aa26f1de2eaf9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42140">issues.joomla.org/tracker/joomla-cms/42140</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42140">issues.joomla.org/tracker/joomla-cms/42140</a>.</sub>

**Comment by brianteeman** [comment]
On what planet is this a feature?

**Pull request merged**
