### PR TITLE
[4.0] Add dashboard module colour

### PR DESCRIPTION
**Pull request by infograf768**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/25878

### Summary of Changes
Modifying border and text link colour to default link colour as what we have is hardly visible and the whole box is clickable.

### Testing Instructions
Load Administration
After patch use npm.

### Before patch

Screen Shot 2019-10-31 at 08 01 55

### After patch
Screen Shot 2019-10-31 at 07 56 24

@C-Lodder @Mari234 @TobsBobs

### CODE REVIEW

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on 10db694193f01f9dd01726d3af9c8f99263dd8e0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26872">issues.joomla.org/tracker/joomla-cms/26872</a>.</sub>

**Comment by TobsBobs** [comment]
I have tested this item :white_check_mark: successfully on a7e0c44b4742b423b636d3a94371423d1593d6aa<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26872">issues.joomla.org/tracker/joomla-cms/26872</a>.</sub>

**Comment by infograf768** [comment]
rtc tks for testing.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26872">issues.joomla.org/tracker/joomla-cms/26872</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
