### PR TITLE
[com_contact] Solving list contacts in category - filter with pagination

### PR DESCRIPTION
**Pull request by muhakh**
Pull Request for Issue #9273 .
#### Summary of Changes

I changed the method of the searching form from "post" to "get" to solve the issue.
#### Testing Instructions

You can go through the instructions in the issue https://github.com/joomla/joomla-cms/issues/9273#issuecomment-191939584

### CODE REVIEW

**Comment by brianteeman** [comment]
This just doesnt seem correct to me - every form in joomla uses post not get

**Comment by muhakh** [comment]
I think I found the problem, it's in the form action. When the "filter-search" is added to it, the issue is solved.
What about adding "filter-search" to the JUri using setVar?

**Comment by rahultomar** [comment]
I have tested this item :white_check_mark: successfully on 965f19d68a12fb0a453aaa1af1c0a9585a3090b9<br /><br />Yeah, its working search box shows value and url also with search input<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9327">issues.joomla.org/joomla-cms/9327</a>.</sub>

**Comment by roland-d** [comment]
I agree that changing from get to post is not the correct solution. The search filter shouldn't be added to the URL either. The question actually is, why are the search settings not stored in the session? If you look at the back-end lists, none of the settings are in the URL, they are all stored in the session, the same thing should be done for the front-end.

**Comment by brianteeman** [comment]
I am closing this as it is not a correct solution<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9327">issues.joomla.org/joomla-cms/9327</a>.</sub>

**Pull request closed without merging**
