### PR TITLE
[4.0] Remove IDs from URLs

### PR DESCRIPTION
**Pull request by brianteeman**
This PR changes the default  value for this setting that is found in com_content, com_contact and com_newsfeeds from the old showing of IDs in the url to the much improved new way of not displaying them.

This is only for new installs. It will not change an updated site.

### CODE REVIEW

**Comment by ceford** [comment]
I have not tested with a new install but I did look at what happens when the "Remove IDs from URLs" is changed manually - looks OK. And I changed the wording of the associated Help screens. It was:

>**"URL Routing".** (Legacy/Modern) Modern routing enables advanced features but may change your URLs. Legacy routing ensures full comptability for existing sites. This is configured per component.

and is now:

> **Remove IDs from URLs.** (Yes or No) Whether or not to show the database id of a newsfeed in a link.

For newsfeed read article or contact or newsfeed. Is that correct?

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31370">issues.joomla.org/tracker/joomla-cms/31370</a>.</sub>

**Comment by brianteeman** [comment]
@ceford Nothing to do with this PR but the help screen was obviusly out of date as the text you quote  refers to an option in Joomla 3 that was removed from joomla4

**Comment by adj9** [comment]
I did a test with and without PR. The ID of the article and the contact, with the active PR, remains at the end of the URL and is what I see in the content area in the BackEnd.
<b>Example</b>
- URL: ~index.php/contact-uncategory/1-c
- BackEnd Screan:
Schermata 2020-11-14 alle 17 52 16

Which ID are you talking about?

**Comment by brianteeman** [comment]
Its the id in the URL

**Comment by Bakual** [comment]
@brianteeman If you change the default value in the XML, you also have to change the default values in the PHP files where the param is used. Those values always need to match. With your current code, the behavior would switch the moment the settings are saved, if  there was no stored value for `sef_ids` before.

If you want to change it only for new installations, then it is sufficient to change only the installation SQL files. You have to leave the XML and PHP the way they are.

**Comment by brianteeman** [comment]
> the behavior would switch the moment the settings are saved, if there was no stored value for sef_ids before.

Good spot - thanks

So just t confirm. By only changing the sql will mean - new installs default to  "no id"
existing installs are not changed on update AND existing installs will not be changed when an unrelated setting is changed.

**Comment by Bakual** [comment]
Looks fine now.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 93fd8551fe237291da4d68f7c8ab253318f6ca51<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31370">issues.joomla.org/tracker/joomla-cms/31370</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 93fd8551fe237291da4d68f7c8ab253318f6ca51<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31370">issues.joomla.org/tracker/joomla-cms/31370</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31370">issues.joomla.org/tracker/joomla-cms/31370</a>.</sub>

**Comment by brianteeman** [comment]
Any reason why this RTC pr has not been merged?

**Comment by wilsonge** [comment]
Just had missed it in the list of things. LGTM!

**Comment by brianteeman** [comment]
thx

**Pull request merged**
