### PR TITLE
[4.0] mso/idna-convert is abandoned

### PR DESCRIPTION
**Pull request by Hackwar**
According to composer, `mso/idna-convert` is abandoned and should be replaced with `algo26-matthias/idna-convert`.

### CODE REVIEW

**Comment by wilsonge** [comment]
Is this actually b/c with the existing library?

**Comment by infograf768** [comment]
I think it is the same library.
We can ask author. Will do.

**Comment by infograf768** [comment]
https://github.com/algo26-matthias/idna-convert/issues/14

**Comment by infograf768** [comment]
I ran composer update. The former one is deleted while the new one is installed.

The version of the library is the same (1.1.0)

**Comment by infograf768** [comment]
`use Mso\IdnaConvert\IdnaConvert;` is used in `/libraries/src/String/PunycodeHelper.php`
but we also have
`"name": "mso/idna-convert",`
in
`/libraries/vendor/algo26-matthias/idna-convert/composer.json`

Also the namespace in the new library is kept
`namespace Mso\IdnaConvert;`

autoload does a redirect.
READme.md may have to be modified.

Just a test... remaining is for specialists 😄

**Comment by infograf768** [comment]
I confirm though that it works fine. Tested with mail and domain names.

**Comment by wilsonge** [comment]
Thanks!

**Comment by glensc** [comment]
https://github.com/joomla/joomla-cms/pull/24009#issuecomment-466964151

it's because:
1. github redirects old repo to new repo
2. the new repo is just renamed, so it points to exact same git tag
2. the immutable git tag still contains the same code

**Comment by infograf768** [comment]
tks, @glensc

**Comment by infograf768** [comment]
Please read
https://github.com/algo26-matthias/idna-convert/issues/14#issuecomment-467508928

Tag has changed

**Comment by infograf768** [comment]
I.e.
        "algo26-matthias/idna-convert" : "2.*"

**Comment by infograf768** [comment]
Using this last one I also get changes in composer.lock

**Comment by infograf768** [comment]
Tested new version. I get 
`Class 'Mso\IdnaConvert\IdnaConvert' not found`

**Comment by infograf768** [comment]
version 2.0.2 modified the namespace which is now
`namespace Algo26\IdnaConvert;`
This implies some changes in our code.

**Comment by wilsonge** [comment]
https://github.com/joomla/joomla-cms/pull/24037 This updates things to latest versions - but yes we should also update to the version 2.0 so there are definitely no conflicts

**Pull request merged**
