### PR TITLE
Changing hardcoded text to language string in template preview

### PR DESCRIPTION
**Pull request by infograf768**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/22304

### Summary of Changes

As title says

### Testing Instructions
Allow Preview template in Templates General Options.
Preview template to display the modules positions.

After patching, change the site en-GB.ini new strings values to reflect the fact that `Position:` and `Style:` are no more harcoded

New strings are
JGLOBAL_PREVIEW_POSITION="Position: "
JGLOBAL_PREVIEW_STYLE="Style: "

Verify that you still get:

screen shot 2018-09-25 at 07 12 32

Note: No need to test in RTL. I did it. To test it in RTL, it is not enough to set en-GB to rtl. One has to use a RTL string value containing a `:`

### CODE REVIEW

**Comment by SharkyKZ** [comment]
Use language variables?

**Comment by infograf768** [comment]
> Use language variables?

I do not understand your question

**Comment by SharkyKZ** [comment]
Add variable (`%s`) to string for style/position and use `JText::sprintf()`? Just a suggestion.

**Comment by brianteeman** [comment]
Is it possible to remove the space from the string and have a space in the markup?

**Comment by infograf768** [comment]
good suggestion. On it.

**Comment by infograf768** [comment]
> Is it possible to remove the space from the string and have a space in the markup?

I am now modifying to use a sprintf, as suggested by @SharkyKZ, therefore the space has to be in the string

**Comment by infograf768** [comment]
That should be it now.

**Comment by SharkyKZ** [comment]
But now to keep the intended styling `<span>` has to be inside the string 😕 

```
JGLOBAL_PREVIEW_POSITION="<span>Position:</span> %s"
JGLOBAL_PREVIEW_STYLE="<span>Style:</span> %s"
```

**Comment by infograf768** [comment]
grrr

**Comment by infograf768** [comment]
have to cook now, will see later

**Comment by infograf768** [comment]
Done. Can be tested.

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on 45ac0c7f2ea5b258a1f53ee5418c897737cf710c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22365">issues.joomla.org/tracker/joomla-cms/22365</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 45ac0c7f2ea5b258a1f53ee5418c897737cf710c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22365">issues.joomla.org/tracker/joomla-cms/22365</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22365">issues.joomla.org/tracker/joomla-cms/22365</a>.</sub>

**Pull request merged**
