### PR TITLE
J4.x Fix Pagination Float and Wrap on mobile Cassiopeia

### PR DESCRIPTION
**Pull request by coolcat-creations**
I actually wanted to create a PR for issue https://github.com/joomla/joomla-cms/issues/32674 but it's wrongly assigned to frontend while the Screenshot in the Issue is the Backend. However the Pagination in Frontend was broken on mobile too, so I fixed it with flex-wrap class in the pagination and I adjusted the Pages Information to only float-end from mid-screen size.

### Testing Instructions
Create some articles to have a large Pagination list or fake it with the browser inspector.
On Mobile the pagination should not break the layout.
- Check Blog and Category List Layout
- Check Com Contact Layout
- Archive Layout

### Actual result BEFORE applying this Pull Request
grafik
grafik

Don't mind the wrong pagination numbers as I faked the page Items instead of creating more articles)

### Expected result AFTER applying this Pull Request
grafik

### Documentation Changes Required
No

### CODE REVIEW

**Comment by brianteeman** [comment]
Shouldn't a mobile pagination be truncated in the middle instead of wrapped?

image

**Comment by coolcat-creations** [comment]
Looks good but seems it involves Javascript I don't know for sure how to implement. Maybe something similar to this: https://codepen.io/allicarn/pen/jPowab

**Comment by HLeithner** [comment]
This pull requests has automatically rebased to 4.2-dev.

**Comment by Magnumv44** [comment]
The problem is still present in version 4.2.1

**Comment by coolcat-creations** [comment]
@HLeithner sorry I had massive issues with my repo and deleted it. should I bring back this PR? I mean it's obviously not solved the right way maybe someone with JS Skills can help?

**Comment by HLeithner** [comment]
Yes please fix it, maybe as brian suggested, this can be done with css only, you only need a new element for ... the rest should work with css classes (sadly only for bootstrap...).

So please fix it as you suggested.

**Comment by coolcat-creations** [comment]
How do you mean with css like Brian suggested? I think JS is needed tbh - can you show me an example how to fix with css?

**Comment by brianteeman** [comment]
css only

https://codepen.io/brianteeman/pen/dyePjrN

https://codepen.io/brianteeman/pen/ExLapJV

**Comment by coolcat-creations** [comment]
thank you. Second one seems to work I will try to create a new PR

**Comment by veyline** [comment]
Hi all! I'm bad at php. Could you tell me how to apply this css code for my template Cassiopeia. I inserted the CSS code and replace the old code, but did not achieve the desired result.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37711">issues.joomla.org/tracker/joomla-cms/37711</a>.</sub>

**Comment by veyline** [comment]
https://frenchpalm.com/ - here is my site. After pasting the css suggested brianteeman my list is limited to 10 pages, but there are more than 25 pages and I need it to look as beautiful as the screenshot above.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37711">issues.joomla.org/tracker/joomla-cms/37711</a>.</sub>

**Comment by LuxLOL** [comment]
Why was this fix not being implemented? It's now almost 2 years.

**Comment by coolcat-creations** [comment]
> Why was this fix not being implemented? It's now almost 2 years.

Can you create a PR? I will be happy to test it

**Comment by LuxLOL** [comment]
> > Why was this fix not being implemented? It's now almost 2 years.
> 
> Can you create a PR? I will be happy to test it

I asked to get access to the Pull Request. Lets see if some wakes up. 😅
In my option this is a big design bug in Joomla. Not sure why this has been ignored for so long. 😐

**Comment by coolcat-creations** [comment]
@LuxLOL what kind of access? Just create an own PR and mark me to test it. This one is closed anyway.

**Comment by dron-baton** [comment]
Good day! As I see on Joomla 4.3 this problem is not solved. I can give you access to my site to fix it and maybe this fix will become global at a later date.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37711">issues.joomla.org/tracker/joomla-cms/37711</a>.</sub>

**Comment by veyline** [comment]
Hello! I am also waiting for this problem to finally be solved, if there is a temporary solution, please share.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37711">issues.joomla.org/tracker/joomla-cms/37711</a>.</sub>

**Comment by hans2103** [comment]
reopen this issue please. #40620 has been closed, not merged.

**Comment by richard67** [comment]
> reopen this issue please. #40620 has been closed, not merged.

@hans2103 This is not an issue, this is a PR, and it's closed since long time, I haven't closed it today due to Brian's PR, in opposite to the other issue which I've just reopened.

**Comment by hans2103** [comment]
my bad... sorry

**Pull request closed without merging**
