### PR TITLE
Update PHPMailer to 5.2.14

### PR DESCRIPTION
**Pull request by wilsonge**
This updates PHPMailer to the latest version. Please see the changelog on their repo (https://github.com/PHPMailer/PHPMailer/releases) if you are interested. To test this ensure that sending emails in Joomla works as expected

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 0ac03aa19fb815c9a55d055241ea7ef5225b7b20<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8736">issues.joomla.org/joomla-cms/8736</a>.</sub>

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 0ac03aa19fb815c9a55d055241ea7ef5225b7b20<br /><br />Used Mass e-mail for tests.

Tested successfully in 3 different configurations:
- Mailer: PHP Mail
- Mailer: SMTP | SMTP Auth: Yes | SMTP Security: SSL | Port: 465 | SMTP Host: mail.remotehost.tld
- Mailer: SMTP | SMTP Auth: Yes | SMTP Security: TLS | Port: 587 | SMTP Host: mail.remotehost.tld<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8736">issues.joomla.org/joomla-cms/8736</a>.</sub>

**Comment by mbabker** [comment]
`libraries/vendor/phpmailer/phpmailer/extras/README.md` and `libraries/vendor/phpmailer/phpmailer/get_oauth_token.php` should be added to gitignore and removed from this PR

`libraries/vendor/phpmailer/phpmailer/extras/class.html2text.php` needs to be added to the list of deleted files in the update script

**Comment by wilsonge** [comment]
Thanks for the review @mbabker - all done

**Comment by brianteeman** [comment]
RTC -  thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8736">issues.joomla.org/joomla-cms/8736</a>.</sub>

**Pull request merged**
