### PR TITLE
fixed missing alpha.png

### PR DESCRIPTION
**Pull request by N6REJ**
Pull Request for Issue # .
#9761
#### Summary of Changes

fixed path to alpha.png
#### Testing Instructions

open media manager and with element inspector check for error.
This does NOT fix- #9761

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on c50ef767839e7a6edbd62e5c2ac38f4d9f982b65<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9795">issues.joomla.org/joomla-cms/9795</a>.</sub>

**Comment by MATsxm** [comment]
I have tested this item :white_check_mark: successfully on c50ef767839e7a6edbd62e5c2ac38f4d9f982b65<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9795">issues.joomla.org/joomla-cms/9795</a>.</sub>

**Comment by brianteeman** [comment]
RTC - thanks @N6REJ <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9795">issues.joomla.org/joomla-cms/9795</a>.</sub>

**Comment by N6REJ** [comment]
yw

**Comment by wilsonge** [comment]
Merged - thanks Troy :)

**Comment by N6REJ** [comment]
yw.. glad I could contribute
Bear

**Pull request merged**
