### PR TITLE
fix error of improper padding for close button in rtl in add modules …

### PR DESCRIPTION
**Pull request by Subhang23**
…modal

Pull Request for Issue #27823 .

### Summary of Changes
Styled the close button in the modal of add modules

### Testing Instructions
Shift to any RTL language and view the modal of add modules

### Actual result

Screenshot from 2020-02-10 23-29-08

### CODE REVIEW

**Comment by Subhang23** [comment]
Could someone explain why the build is failing?

**Comment by infograf768** [comment]
Nothing related to your patch. But there are some cs issues and I am not sure you chose the best solution.
Will look tomorrow.

**Comment by infograf768** [comment]
I don't think we should do it as you propose. See https://github.com/joomla/joomla-cms/issues/27823#issuecomment-582807738

Your patch gives
Screen Shot 2020-02-11 at 08 37 01

Mine gives
Screen Shot 2020-02-11 at 09 00 42

As you can see, the text is placed OK, similar to LTR and not near to the icon
Screen Shot 2020-02-11 at 08 29 32


This is a .diff I made here:
```
diff --git a/administrator/templates/atum/scss/blocks/_modals.scss b/administrator/templates/atum/scss/blocks/_modals.scss
index 4975528..8246c79 100644
--- a/administrator/templates/atum/scss/blocks/_modals.scss
+++ b/administrator/templates/atum/scss/blocks/_modals.scss
@@ -66,5 +66,4 @@
     background-color: var(--danger);
     color: hsla(0, 0%, 100%, .9);
-
     display: inline-block;
     width: 2.375rem;
@@ -72,4 +71,8 @@
     margin: 0 16px 0 -22px;
     line-height: 2.375rem;
+
+    [dir=rtl] & {
+       margin: 0 -22px 0 16px;
+    }
   }
 
@@ -81,5 +84,4 @@
     background-color: var(--success);
     color: hsla(0, 0%, 100%, .9);
-
     display: inline-block;
     width: 2.375rem;
@@ -87,6 +89,9 @@
     margin: 0 16px 0 -22px;
     line-height: 2.375rem;
-  }
 
+    [dir=rtl] & {
+       margin: 0 -22px 0 16px;
+    }
+  }
 }

```
The whole file would be 
[_modals.scss.zip](https://github.com/joomla/joomla-cms/files/4184572/_modals.scss.zip)

Could you correct this PR, or shall we close it and I will make a new one?

**Comment by Subhang23** [comment]
@infograf768 I will correct this PR

**Comment by infograf768** [comment]
I have not tested this item.<br /><br />thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27883">issues.joomla.org/tracker/joomla-cms/27883</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 288ec4e66d12ed61c3e846ba9d4710241401982b<br /><br />thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27883">issues.joomla.org/tracker/joomla-cms/27883</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 288ec4e66d12ed61c3e846ba9d4710241401982b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27883">issues.joomla.org/tracker/joomla-cms/27883</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27883">issues.joomla.org/tracker/joomla-cms/27883</a>.</sub>

**Comment by infograf768** [comment]
thanks

**Pull request merged**
