### PR TITLE
Revert #19977: Plugins field behavior

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue # .

### Summary of Changes

PR #19977 wasn't tested properly. As a result, it introduced unwanted behavior when saving form. The change prevents default value from being saved when it is set as a custom option in XML form.

Additionally, it adds check for a hardcoded language constant. This is not correct because the constant is added through custom option in XML form and could be anything.

### Testing Instructions

Enable a Captcha plugin (e.g. reCaptcha).
Select the plugin as default Captcha plugin in Global Configuration and save.
Disable the plugin.
Go to Global Configuration and save again.
a) Open username reminder or password reset page
b) Check Captcha setting value (either in configuration.php or through JFactory::getApplication()->get('captcha')).

### Expected result

a) No traces of captcha.
b) `0`

### Actual result

a) Captcha label shown in form, indicating that Captcha plugin is set in configuration.
b) `recaptcha`

### Documentation Changes Required
No.

### CODE REVIEW

**Comment by zero-24** [comment]
Cc @tonypartridge so the original author is aware ;-)

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 929f46f8c8415294f36f1085145eaef8c55fe791<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20293">issues.joomla.org/tracker/joomla-cms/20293</a>.</sub>

**Comment by alikon** [comment]
don' t hate me but yet another one for you @HLeithner

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on bb57a759f7c8030b531bfd075f9358b202d2fc25<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20293">issues.joomla.org/tracker/joomla-cms/20293</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20293">issues.joomla.org/tracker/joomla-cms/20293</a>.</sub>

**Comment by HLeithner** [comment]
thx

**Pull request merged**
