### PR TITLE
[com_banners] Fix #15147

### LINKED ISSUE #15147: [com_banners] Undefined variable: canDo & Call to a member function get() on null in Hathor
### Steps to reproduce the issue
Install demo.
Go to Components > Banners > Clients.
Edit a client.

banner-clients

```
PHP Notice:  Undefined variable: canDo in C:\xampp\htdocs\joomla-cms-staging\administrator\templates\hathor\html\com_banners\client\edit.php on line 42

PHP Fatal error:  Call to a member function get() on null in C:\xampp\htdocs\joomla-cms-staging\administrator\templates\hathor\html\com_banners\client\edit.php on line 42
```

### PR DESCRIPTION
**Pull request by Quy**
Thanks @joomdonation for the fix.

Pull Request for Issue #15147 .

### Testing Instructions
Switch to Hathor style.
Go to Components > Banners > Clients.
Edit a client.

### Actual result
No more warnings.

### CODE REVIEW

**Comment by joomdonation** [comment]
I have tested this item :white_check_mark: successfully on b84c5c2dc2c7f705e65b8c7af38f33c654f2eec6<br /><br />code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15168">issues.joomla.org/tracker/joomla-cms/15168</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on b84c5c2dc2c7f705e65b8c7af38f33c654f2eec6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15168">issues.joomla.org/tracker/joomla-cms/15168</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Comment by infograf768** [comment]
Bot getting crazy:
@mbabker 
This should be RTC and milestone to 3.7.0

**Pull request merged**
