### PR TITLE
[4] s/nameif/name of

### PR DESCRIPTION
**Pull request by PhilETaylor**
s/nameif/name of

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 0c6eed3c70c8536c8812fd07a187efa401ed3bd5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35858">issues.joomla.org/tracker/joomla-cms/35858</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 0c6eed3c70c8536c8812fd07a187efa401ed3bd5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35858">issues.joomla.org/tracker/joomla-cms/35858</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35858">issues.joomla.org/tracker/joomla-cms/35858</a>.</sub>

**Comment by Quy** [comment]
Thanks!

**Pull request merged**
