### PR TITLE
[3.x] explain symbols

### PR DESCRIPTION
**Pull request by brianteeman**
To avoid confusion on what a "symbol" is this PR includes an example in the error message.

cc @MartijnMaandag 

_Please note that anyone using the rule to enforce symbols is not make their site more secure and is stopping their users from being able to reliably use a password manager_

### CODE REVIEW

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 03a8c70daf01c234a8f8d2cf307e4a32eebfb689<br /><br />Updating strings look good.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29445">issues.joomla.org/tracker/joomla-cms/29445</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 03a8c70daf01c234a8f8d2cf307e4a32eebfb689<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29445">issues.joomla.org/tracker/joomla-cms/29445</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/29445">issues.joomla.org/tracker/joomla-cms/29445</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thx

**Pull request merged**
