### PR TITLE
fix less / css

### PR DESCRIPTION
**Pull request by brianteeman**
recompile less using our generatecss.php script

Most changes seem to be codestyle - i guess someone used a different less compiler

BUT check the changes to input-prepend

### CODE REVIEW

**Comment by Bakual** [comment]
The input-prepend stuff is related to this PR that was merged lately: https://github.com/joomla/joomla-cms/pull/12442

**Comment by Bakual** [comment]
Btw: https://github.com/joomla/joomla-cms/blob/3.7.x/media/jui/less/bootstrap-extended.less#L376-L383 doesn't look right (and is also related to the mentioned PR).

**Comment by zero-24** [comment]
@ciar4n can you take a look here?

**Comment by ciar4n** [comment]
I have tested this item :white_check_mark: successfully on 3e6bd2ca7f4c3f1486e6f4fa58605f0cd73aa81e<br /><br />@brianteeman Apologies as this was most likely my doing. Noted for future PRs! :)

@Bakual I emptied these selectors for #12442 . As empty selectors are ignored by LESS, I didn't bother removing them.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12548">issues.joomla.org/tracker/joomla-cms/12548</a>.</sub>

**Comment by Bakual** [comment]
> As empty selectors are ignored by LESS, I didn't bother removing them.

You should have, as empty selectors are useless :smile:

**Comment by ciar4n** [comment]
@Bakual True :) They are not outputted to the CSS so no ill effect for the time been. I'll remove them at the next given chance.

**Comment by brianteeman** [comment]
@zero-24 @bakual can you guys test this so we can get it merged and then other PRs wont be effected by this error<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12548">issues.joomla.org/tracker/joomla-cms/12548</a>.</sub>

**Comment by Bakual** [comment]
I have tested this item :white_check_mark: successfully on 3e6bd2ca7f4c3f1486e6f4fa58605f0cd73aa81e<br /><br />Tested with Protostar, Isis and my own template and couldn't see any notable difference.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12548">issues.joomla.org/tracker/joomla-cms/12548</a>.</sub>

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
