### PR TITLE
[4.0] Test sample data help links

### PR DESCRIPTION
**Pull request by brianteeman**
Updates the sample data to use help links for j4 and not j3

code review

### CODE REVIEW

**Comment by Razzo1987** [comment]
Hi @brianteeman We are searching the text:
`<p>This module shows a list of the calendar months containing archived articles. After you have changed the status of an article to archived, this list will be automatically generated. <a href='https://help.joomla.org/proxy/index.php?option=com_help&amp;keyref=Help31:Extensions_Module_Manager_Articles_Archive' title='Archive Module'>Help</a></p><div class='sample-module'>{loadmodule articles_archive,Archived Articles}</div>`
But we think is not in the articles. We fond a part of it in the module description, but not the link to the docs.
Can you help us to find how to test it?

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on a6aa59b9107e7513919727d4051f7d2ee7417c06<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28714">issues.joomla.org/tracker/joomla-cms/28714</a>.</sub>

**Comment by toivo** [comment]
Tried to apply the patch to Nightly Build of 29 April but the Patch Tester says "The file marked for modification does not exist: plugins/sampledata/testing/language/en-GB/en-GB.plg_sampledata_testing.ini"<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28714">issues.joomla.org/tracker/joomla-cms/28714</a>.</sub>

**Comment by Quy** [comment]
Testing Sample Data is not included in the nightly builds, thus, the warning. You will have to compile/setup the development branch to test.

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on a6aa59b9107e7513919727d4051f7d2ee7417c06<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28714">issues.joomla.org/tracker/joomla-cms/28714</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28714">issues.joomla.org/tracker/joomla-cms/28714</a>.</sub>

**Comment by wilsonge** [comment]
Thankyou!

**Comment by brianteeman** [comment]
Thx

**Pull request merged**
