### PR TITLE
[4.0] Blocked Users

### PR DESCRIPTION
**Pull request by brianteeman**
Users are blocked not disabled

code review

PR for #31740

### CODE REVIEW

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 8224484640140f2285ba00e81a50c172b6a483f4<br /><br />Code Review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31742">issues.joomla.org/tracker/joomla-cms/31742</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 8224484640140f2285ba00e81a50c172b6a483f4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31742">issues.joomla.org/tracker/joomla-cms/31742</a>.</sub>

**Comment by chmst** [comment]
RTC

**Comment by laoneo** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
