### PR TITLE
[4.1] Simplify notification labels

### PR DESCRIPTION
**Pull request by Quy**
### Summary of Changes
The legend states it is Notifications. Remove the redundant `Notifications on` to simplify labels.

### Testing Instructions
Go to System > Scheduled Tasks
Create a new task.
Go to Advanced tab.
See Notifications section.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 0de9678afedb5c5f1da82a271f845b1461ecfb37<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36271">issues.joomla.org/tracker/joomla-cms/36271</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 0de9678afedb5c5f1da82a271f845b1461ecfb37<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36271">issues.joomla.org/tracker/joomla-cms/36271</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36271">issues.joomla.org/tracker/joomla-cms/36271</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
