### PR TITLE
[4.0] Joomla\Database\DatabaseQuery::rand() codestyle

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Corrects casing.

### Testing Instructions

Code review.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on f8e59538cf256b7b8b46f1e766cf282dcd18c02f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25686">issues.joomla.org/tracker/joomla-cms/25686</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on f8e59538cf256b7b8b46f1e766cf282dcd18c02f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25686">issues.joomla.org/tracker/joomla-cms/25686</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25686">issues.joomla.org/tracker/joomla-cms/25686</a>.</sub>

**Comment by HLeithner** [comment]
thx

**Pull request merged**
