### PR TITLE
Ui Input Adjustment

### PR DESCRIPTION
**Pull request by ghost**
Pull Request for Issue #13862

### Summary of Changes
Minor CSS Adjustments which define input widths in the right sidebar of editing screens to provide a more consistent appearance. 
Specifically: 
Tag Select Input, Version Text Input and Version Note Text Input
Found in editor interface for various components.

Publish & Unpublish Date Select Inputs
Found in Module editor interface.

### Testing Instructions
Enter item editing screen in the following components:
Articles, Categories, Menu Items, Banners, Contacts, News Feeds, Tags, Modules

This PR adjusts Note, Version Note, Tags, and Publish / Unpublish inputs. If there are other inputs with issues please let me know and I will make further adjustments.

### Expected result
All parameter options found on the right side should be the same width in all components.

editor-inputs

### Documentation Changes Required
None

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
I have not tested this item.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13940">issues.joomla.org/tracker/joomla-cms/13940</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
I have tested this item :white_check_mark: successfully on 50f0276fbc707a16a2d0515d2c118b27a5229013<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13940">issues.joomla.org/tracker/joomla-cms/13940</a>.</sub>

**Comment by C-Lodder** [comment]
If the note input is going to be made that small, it should be changed to a textarea. A note could potentially be a small paragraph, so using a small input seems pointless.

**Comment by cpfeifer** [comment]
I don't disagree, but the issue in question was that the text inputs were hanging off to the right side. This is a minor detail in my opinion and I could go either way on it.

**Comment by C-Lodder** [comment]
So rather than changing the width just to make it blend in, why don't we do the right thing and use the correct element? Will need a simple tweak in the XML file.

**Comment by cpfeifer** [comment]
I can do that. I didn't mess with the input types at all but that makes a lot sense.

**Comment by tuts-22** [comment]
I have tested the request and it works fine

**Comment by cpfeifer** [comment]
I'll update this PR this week with the field types, it's a busy week for me.

**Comment by franz-wohlkoenig** [comment]
@cpfeifer any News about this PR?

**Comment by brianteeman** [comment]
@cpfeifer it has been several months since you said you would be updating this PR. It now has multiple conflicts which also need resolving. If this isnt updated it will be closed in a few weeks time as there is no point in keeping an abandoned and non mergeable PR open. Thanks

**Pull request closed without merging**
