### PR TITLE
[4.0] admin latest articles

### PR DESCRIPTION
**Pull request by brianteeman**
I made a copy paste error in #20962 and changed the date column from created date to published date. This PR reverts that

### testing
create a new article and leave it in the default unpublished
~check it in the module on the home dashboard and the date will be messed up as it doesnt have a date~
check in the module on the home dashboard and the date will be today. 
now go back to the article and change the **created** date to yesterday
check in the module on the home dashboard and the date will still be today. 
this is because when the published date is not set the helper uses today as the value (which is a recent change and why people couldnt replicate the issue)

apply pr -
check in the module on the home dashboard and the date will correctly be yesterday.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on b5d857b10cea4e665929ff2f4944219afde35f80<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26074">issues.joomla.org/tracker/joomla-cms/26074</a>.</sub>

**Comment by Quy** [comment]
Your PR is similar to #24968. OK to close the other PR? This should be applied to mod_popular too.

**Comment by Quy** [comment]
This is no longer reproducible.

**Comment by idefax** [comment]
I can't reproduce it.

Tested with:

PHP Version 	7.3.8
Web Server 	Apache
WebServer to PHP Interface 	cgi-fcgi
Joomla! Version 	Joomla! 4.0.0-beta1-dev Development [ Amani ] 17-October-2019 20:21 GMT
User Agent 	Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:69.0) Gecko/20100101 Firefox/69.0 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26074">issues.joomla.org/tracker/joomla-cms/26074</a>.</sub>

**Comment by neotrendch** [comment]
not reproducible<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26074">issues.joomla.org/tracker/joomla-cms/26074</a>.</sub>

**Comment by oschuldt** [comment]
I have tested this item :white_check_mark: successfully on b5d857b10cea4e665929ff2f4944219afde35f80<br /><br />ok<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26074">issues.joomla.org/tracker/joomla-cms/26074</a>.</sub>

**Comment by pravinTek** [comment]
Unable to reproduce and it's showing publish date

**Comment by Nilesh5995** [comment]
I have tested this item :white_check_mark: successfully on b5d857b10cea4e665929ff2f4944219afde35f80<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26074">issues.joomla.org/tracker/joomla-cms/26074</a>.</sub>

**Comment by MarLinDT** [comment]
not reproducible<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26074">issues.joomla.org/tracker/joomla-cms/26074</a>.</sub>

**Comment by brianteeman** [comment]
The error with the date format has indeed gone now but it is still displaying the wrong date

**Comment by idefax** [comment]
Date looks good to me. "Beitrag 1" without patch, "Beitrag 2" with patch.

[Screenshot](http://prntscr.com/plir4v "Screenshot")<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26074">issues.joomla.org/tracker/joomla-cms/26074</a>.</sub>

**Comment by Quy** [comment]
Make same change to mod_popular.

**Comment by vijaykhollam** [comment]
The date looks good to me without applying the patch.
#pbf19 #test1
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26074">issues.joomla.org/tracker/joomla-cms/26074</a>.</sub>

**Comment by Quiviro** [comment]
All seems correct before patch. After applying it, nothing changes?
#PBF19es<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26074">issues.joomla.org/tracker/joomla-cms/26074</a>.</sub>

**Comment by Quiviro** [comment]
I have tested this item :red_circle: unsuccessfully on b5d857b10cea4e665929ff2f4944219afde35f80<br /><br />Nothing seems to change after applying the patch<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26074">issues.joomla.org/tracker/joomla-cms/26074</a>.</sub>

**Comment by jwaisner** [comment]
I also cannot reproduce this issue. When checking the dashboard the date is correct for the new article.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26074">issues.joomla.org/tracker/joomla-cms/26074</a>.</sub>

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on cff4675acc17a11d51e98c35e944fc409d1de7d8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26074">issues.joomla.org/tracker/joomla-cms/26074</a>.</sub>

**Comment by Fedik** [comment]
It obviously should be `$item->created` instead of `$item->publish_up`,

For testers: just apply the patch and make sure the date are displayed without any errors

**Comment by SharkyKZ** [comment]
This looks misleading when ordering by modified date. When using automatic title, the title is `Last 5 Modified Articles` but created date is shown. Maybe change this to be based on ordering?

**Comment by brianteeman** [comment]
@SharkyKZ automatic title is a separate issue

**Comment by brianteeman** [comment]
updated original post and instructions

**Comment by SharkyKZ** [comment]
It's not just with automatic title. You can title the module "Recently Modified Articles" yourself and order by modified date. But created date is shown instead. I think that's wrong. At the very least date label should indicate which date is shown.

**Comment by wilsonge** [comment]
Merging this on review based on what the original PR did. Don't dispute something looks wrong with the existing 3.x behaviour though - so if someone wants to work on that I'd definitely be interested in such a PR

**Comment by brianteeman** [comment]
thx

**Pull request merged**
