### PR TITLE
Visual update for isis

### PR DESCRIPTION
**Pull request by dgrammatiko**
#### Let’s drop a few more gradients

Some FACTS:
- Joomla is locked with Bootstrap 2.3.2
- The less files are already touched multiple times
- There’s not gonna be an update for BS 2.3.2
- Joomla 3 is already 3 years old with the same template

With all those facts in mind I tried to drop a few more gradients so the rendered pages resemble a Bootstrap 3 template.
~~The changes are global since the less files touched here are the bootstrap 2.3.2 files~~
Changes affect only Isis template, the true impact is that 5 files are duplicated so changes in e.g. bootstrap buttons have to be done in two places, but since bootstrap is NOT gonna have any release for 2.3.x this is only theoretical, in practice we just have some duplicate less files to achieve our goal. Same goes for chosen, also notice that this version of chosen is dropping the png files and using icomoon which is always loaded for Isis...
#### B/C:

Other than the change in the appearance I don’t see any drawbacks here.
#### Preview:

screen shot 2015-08-01 at 15 01 41

### CODE REVIEW

**Comment by brianteeman** [comment]
Spotted quite a few bugs

Drop Down menu items are invisible on hover
Text on Buttons like the Review Messages are unreadable
Toolbar buttons have no border/background (except on hover)

Finally the select boxes look the same as a disabled option

**Comment by dgt41** [comment]
@brianteeman thanks, should be ok now<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7610">issues.joomla.org/joomla-cms/7610</a>.</sub>

**Comment by Bakual** [comment]
Changing the Bootstrap LESS files will likely not be accepted due to B/C. You would be changing all templates that work from those. And they rightfully expect a Bootstrap 2.3.2 stack there.
The only changes we made to those files were needed to make it compatible with some MooTools stuff.
If you want to update Isis/Protostar, do it in the template folder itself. Don't touch the jui folders.
However I would argue that changing Protostar is not really a good idea as it affects productive sites all over the planet, changing their appearance quite a bit. Not everyone will think it's an improvement.
Isis is fine to change as it affects only administrators, not the public.

**Comment by brianteeman** [comment]
@dgt41 The issues I spotted with Isis are resolved. 

Completely missed that you had updated protostar as well. I tend to agree with @Bakual on that one.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7610">issues.joomla.org/joomla-cms/7610</a>.</sub>

**Comment by dgt41** [comment]
Redid this with overrides only for Isis

**Comment by infograf768** [comment]
Please test https://github.com/joomla/joomla-cms/pull/7609 to solve another issue

**Comment by brianteeman** [comment]
Updated title to remove reference to protostar<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7610">issues.joomla.org/joomla-cms/7610</a>.</sub>

**Comment by ghazal** [comment]
I have been using this Isis visual update on a few sites' backend and I quite like it.
One pb though, the dropdown of Modules position doesn't take into account the templates names.
>OLD
old_isis
>NEW
new_isis

**Comment by dgt41** [comment]
@ghazal thanks for finding that, I will push some code this weekend

**Comment by dgt41** [comment]
This is a UX/UI territory so I am gonna close and let them decide.

**Comment by Gerlof** [comment]
Color of 'delete icon' (grey, and black on hover) does not match with blue background of button. Grey on blue: low contrast.
pull-7610

**Comment by infograf768** [comment]
I guess this will need some changes in generatecss.php

**Comment by dgt41** [comment]
@infograf768 actually it works great with generatecss.php (all the changes are in the template.less)

**Comment by cpfeifer** [comment]
Thanks for sharing your work, the JUX team will review and consider this idea.

**Pull request closed without merging**
