### PR TITLE
Add support for different plugin groups to com_ajax

### PR DESCRIPTION
**Pull request by Bakual**
Currently, `com_ajax` is hardcoded to load the "Ajax" plugin group.
This PR proposes to add support for a `group` URL parameter which tells com_ajax to import a custom plugin group. If omitted it will fall back to the ajax group.

The reason is that we may have for example a content plugin which uses Ajax functionality. With the current implementation it would neeed two plugins, one in the content group for the markup/whatever and a second one in the ajax group to process the AJAX requests. That doesn't make much sense.
#### Testing
- You can use the example plugin https://github.com/Joomla-Ajax-Interface/Ajax-Latest-Articles to see that nothing breaks when using `index.php?option=com_ajax&plugin=latestarticles&format=debug` (should give you a list of articles).
- To test the new group parameter you can add `&group=content` to the URL and see that the example plugin isn't triggered anymore (you get an empty array).
- Now you can copy the function `onAjaxLatestarticles` from the example plugin to a content plugin of your choice and it should work again.

### CODE REVIEW

**Comment by nielsnuebel** [comment]
@Bakual i tried this with the group editors-xtd. Does not worked. Maybe i misunderstood these workflow

**Comment by Bakual** [comment]
It should work with that group as well. You just need to pass the plugin group in the AJAX request (&group=editors-xtd).

**Comment by mbabker** [comment]
As long as the default CMD filter isn't stripping the -.  If it's not
working that's probably the issue.

**Comment by nielsnuebel** [comment]
No it dosen't. 

This is my link index.php?option=com_ajax&plugin=GetForm&format=raw&group=editors-xtd

The Dispatcher has only System Plugins
https://www.dropbox.com/s/vo2ffqmgyhivglx/Screenshot%202016-09-21%2016.34.08.jpg?dl=0

**Comment by Bakual** [comment]
To me it looks then like `JPluginHelper::importPlugin()` doesn't work with that plugin group or at least doesn't register them in that observer array for some reason. I would have to track down how the editor buttons plugins are called in detail.

**Comment by zero-24** [comment]
Maybe it would be better to open a new issue than ;)

**Pull request closed without merging**
