### PR TITLE
[4.3][Guided Tours] Editors should be accessible with tabs

### PR DESCRIPTION
**Pull request by obuisard**
### Summary of Changes

Editors such as TinyMCE and JCE use iframes for editing content.
The script has been modified to be able to support step targets that are actually iframes.
Iframe elements cannot get 'blur' events so that event is passed on to the iframe's contentWindow.
It allows the tours to tab through the editor and the guided tour step without loosing focus.

### Testing Instructions

Select TinyMCE or install and select the JCE Editor in the global configuration of your test site.
Start a tour, for instance, start the tour 'How to create categories'.
Step through the tour, up to the last step before the editor (the alias field).
Select 'Next'.
The step for the content editor will open.

image

Tab once gets you to the 'cancel' button.
Tab once or twice will get you to the editor (depending if content is already present in the editor).
Tab once will get you back into the modal, on the 'Next' button.
Shift tab will get you on the back button.
You can cycle through all of those elements with tab and shift tab.

### Actual result BEFORE applying this Pull Request

The steps were tabbing through the content of TinyMCE only with a hack allowing the content to be added to the code source of the editor. JCE was not supported.

### Expected result AFTER applying this Pull Request

TinyMCE and JCE are usable with guided tours without any hack. 
Any iframe target used for any element will get proper events in the future.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
@richard67 does this change need an update sql from beta3

**Comment by richard67** [comment]
> @richard67 does this change need an update sql from beta3

I think yes.

**Comment by brianteeman** [comment]
> > @richard67 does this change need an update sql from beta3
> 
> I think yes.

;) it was my _polite_ way of saying @obuisard please will you update this PR to provide an update sql from current to this

**Comment by obuisard** [comment]
My apologies, I have added the necessary SQL for updates from beta 4.

**Comment by brianteeman** [comment]
As can be seen in the video (with captured keystrokes) the problem occurs when you tab out of the editor.


https://user-images.githubusercontent.com/1296369/223853640-7bc4d56f-e982-4d15-b167-37e964375e4b.mp4

**Comment by obuisard** [comment]
The script works under Firefox, fails with Chromium-enabled browsers.

**Comment by obuisard** [comment]
Brian @brianteeman do you mind checking again? I would really appreciate. Thank you!
I have set a time out to catch the focus when leaving the editor.

**Comment by brianteeman** [comment]
Will test tomorrow as I don't use the computer on Saturday

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on d39e6ceeb1d37c036961c921c758814feccaa1fd<br /><br />seems to work now. hope all these changes to the js dont conflict with each other<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40044">issues.joomla.org/tracker/joomla-cms/40044</a>.</sub>

**Comment by obuisard** [comment]
> hope all these changes to the js dont conflict with each other

They won't, I tested the whole thing together.

**Comment by khu5h1** [comment]
I have tested this item :white_check_mark: successfully on d39e6ceeb1d37c036961c921c758814feccaa1fd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40044">issues.joomla.org/tracker/joomla-cms/40044</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40044">issues.joomla.org/tracker/joomla-cms/40044</a>.</sub>

**Comment by sdwjoomla** [comment]
RTC

**Pull request merged**
