### PR TITLE
Config Search - blue bar with Fieldset Description

### PR DESCRIPTION
**Pull request by pe7er**
Most **Component Configuration Options** have under the option tab **a blue bar with a description**

### Summary of Changes

This PR **changes the tab option name** from [Component] to [Search Settings] and **adds a blue bar** with description.

#### Before the PR:
backend: System > Global Configuration > (in Left menu) Search > [**Component**]

info-label-options-search-component-before

#### After the PR:
backend: System > Global Configuration > (in Left menu) Search > [**Search Settings**]

info-label-options-search-component-after

### CODE REVIEW

**Comment by brianteeman** [comment]
There are several components like this. It would be great if you could fix
them all.

**Comment by brianteeman** [comment]
Too early in the morning. I see that you have done that already. Thank you.

**Comment by pe7er** [comment]
Yes, I created a PR per component because that way it will be easier to test, to change (because some language string descriptions could probably be improved) and if ok, to merge with core (without merge conflicts).

**Comment by brianteeman** [comment]
It's fine and a good method. I just replied before my first coffee :)

**Comment by rdeutz** [comment]
I like the change for the tab but I think the "blue bar" is not needed at least in this case

**Comment by ciar4n** [comment]
I have tested this item :white_check_mark: successfully on 1f55a70786bb83d84adfa7a7ab5cf397b8b2cdb6<br /><br />Works :) although will need translating!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12092">issues.joomla.org/joomla-cms/12092</a>.</sub>

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on 1f55a70786bb83d84adfa7a7ab5cf397b8b2cdb6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12092">issues.joomla.org/joomla-cms/12092</a>.</sub>

**Comment by jeckodevelopment** [comment]
@brianteeman please look at this so we can go RTC

**Comment by RonakParmar** [comment]
I have tested this item :white_check_mark: successfully on 1f55a70786bb83d84adfa7a7ab5cf397b8b2cdb6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12092">issues.joomla.org/joomla-cms/12092</a>.</sub>

**Comment by brianteeman** [comment]
The blue bar is not needed - you just added some meaningless text in order to justify adding th blue bar - my 2c

**Comment by Quy** [comment]
The blue bar/text is stating the obvious and adds no additional information so I agree with Brian/Robert that it is not necessary in this case.

**Comment by brianteeman** [comment]
Closed for the reasons stated above

**Pull request closed without merging**
