### PR TITLE
Use proper field name to show modified user

### PR DESCRIPTION
**Pull request by Bakual**
### Summary of Changes
Adjusting the field form xml to properly show the user which modified the field

### Testing Instructions
Change an existing field and check the "modified by" field.
Before PR this will be empty, even after multiple saves.
After PR this will be populated after first change of the field.

### Documentation Changes Required
None

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on b3e3bd20d7f09fe62e3f7e43ad8514001b99159c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12736">issues.joomla.org/tracker/joomla-cms/12736</a>.</sub>

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on b3e3bd20d7f09fe62e3f7e43ad8514001b99159c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12736">issues.joomla.org/tracker/joomla-cms/12736</a>.</sub>

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on b3e3bd20d7f09fe62e3f7e43ad8514001b99159c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12736">issues.joomla.org/tracker/joomla-cms/12736</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12736">issues.joomla.org/tracker/joomla-cms/12736</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12736">issues.joomla.org/tracker/joomla-cms/12736</a>.</sub>

**Pull request merged**
