### PR TITLE
SimpleXMLElement::addChild() [simplexmlelement.addchild]: unterminated entity reference

### PR DESCRIPTION
**Pull request by JamesShaver**
#### Steps to reproduce the issue

Create a user custom profile with a country list and a properly escaped ampersand (Issue tracker may replace my escaped ampersand as non-escaped):
<field
        name="country"
        type="list"
        default=""
        label="PLG_USER_PROFILE_FIELD_COUNTRY_LABEL"
        description="PLG_USER_PROFILE_FIELD_COUNTRY_DESC">
        <option value="US">United States</option>
        <option value="AG">Antigua &amp; Barbuda</option>
        ...
        <option value="BA">Bosnia &amp; Herzegovina</option>
        ...
        <option value="TT">Trinidad &amp; Tobago</option>
</field>
#### Expected result

Simple list of countries in the profile
#### Actual result

Warning: SimpleXMLElement::addChild() [simplexmlelement.addchild]: unterminated entity reference Barbuda in /home/website/public_html/joomla/libraries/joomla/form/form.php on line 2119
Warning: SimpleXMLElement::addChild() [simplexmlelement.addchild]: unterminated entity reference Herzegovina in /home/website/public_html/joomla/libraries/joomla/form/form.php on line 2119
Warning: SimpleXMLElement::addChild() [simplexmlelement.addchild]: unterminated entity reference Tobago in /home/website/public_html/joomla/libraries/joomla/form/form.php on line 2119
#### System information (as much as possible)

PHP Version: 5.4.24
Web Server: Apache Phusion_Passenger/4.0.10 mod_bwlimited/1.4 mod_fcgid/2.3.9
WebServer to PHP Interface: cgi-fcgi
Joomla! Version: Joomla! 3.3.4 Stable [ Ember ] 23-September-2014 14:00 GMT
Joomla! Platform Version: Joomla Platform 13.1.0 Stable [ Curiosity ] 24-Apr-2013 00:00 GMT
User Agent: Mozilla/5.0 (Windows NT 6.1; rv:32.0) Gecko/20100101 Firefox/32.0 
#### Additional comments

Solving the problem is simply updating form.php at line 2119:

//$node = $source->addChild($new->getName(), trim($new));
$node = $source->addChild($new->getName(), htmlspecialchars(trim($new)));

Using language files for all of the countries with ampersands also works to solve the issue, however I do not believe this should be the preferred method to fix it.

### CODE REVIEW

**Comment by Fedik** [comment]
last week I got similar error with german language, with umlauts,
and I noticed that better use `html_entity_decode` instead of `htmlspecialchars`, as it more "XML safe" ... can someone confirm it? 

```xml
<field name="test" type="list" label="test">
  <option value="1">Geschäftlich</option>
</field>
```

**Comment by hitchblade** [comment]
Some text with ```some fenced code``` inside.

```
<field name="test" type="list" label="test">
	<option value="1">United States</option>
	<option value="2">Antigua &amp; Barbuda</option>
	<option value="3">Trinidad &amp; Tobago</option>
	<option value="4">Bosnia &amp; Herzegovina</option>
	<option value="5">Geschäftlich</option>
</field>
```

I actualy can't open the User Profile Page and there appear some warnings...
After applying the Patch it's working like descriped! Good work!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4353">issues.joomla.org/joomla-cms/4353</a>.</sub>

**Comment by MPompejus** [comment]
Tested with & and ü the german umlaut vor ue both worked good after patch.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4353">issues.joomla.org/joomla-cms/4353</a>.</sub>

**Comment by MPompejus** [comment]
Tested with & and ü the german umlaut vor ue both worked good after patch.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4353">issues.joomla.org/joomla-cms/4353</a>.</sub>

**Pull request merged**
