### PR TITLE
[5.2] parent keyword misused

### PR DESCRIPTION
**Pull request by Denitz**
### Summary of Changes

Use `$this->` instead of `parent::` in the non-parent methods.

### Testing Instructions

Apply patch

### Actual result BEFORE applying this Pull Request

See IDE warnings, plus inability to extend from certain classes with calling own methods.

### Expected result AFTER applying this Pull Request

No IDE warnings, composition is better.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by HLeithner** [comment]
As https://github.com/joomla/joomla-cms/pull/41661 this must be evaluated per case what we want.

**Comment by HLeithner** [comment]
This pull request has been automatically rebased to 5.1-dev.

**Comment by HLeithner** [comment]
This pull request has been automatically rebased to 5.2-dev.

**Comment by Hackwar** [comment]
Looking at the code, all looks correct and other than #41661 there is nothing wrong here. Could @rdeutz and @HLeithner review/test this? Then I could merge it.

**Review by HLeithner — APPROVED** [review]

**Pull request merged**
