### PR TITLE
[5.0Beta1] Task titles

### PR DESCRIPTION
**Pull request by brianteeman**
Simple PR to change the title of the three newly created tasks to real words (if possible).

As these are not translated strings it makes it easier for machine translators when real words are used

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by HLeithner** [comment]
That will not migration beta1 installations right?

**Comment by richard67** [comment]
@brianteeman Shouldn't these be changed, too, if we go that way?
- https://github.com/joomla/joomla-cms/blob/5.0-dev/administrator/components/com_admin/script.php#L2458
- https://github.com/joomla/joomla-cms/blob/5.0-dev/administrator/components/com_admin/script.php#L2527

The 3 tasks which you have found are created with the deletion of the old, obsolete system plugin.

The 2 mentioned by me are created when the old system plugin continues to exist and only some of their parameters are moved to the new task, that's why those 2 are in the postflight.

@HLeithner Should we migrate the Beta 1 task titles with Beta 2? I'm not sure if it's worth the effort, as the titles are used only for title display and nothing else, i.e. not in any code for identifying a task. At least I don't remember having seen anything like that.

On the long run I think task titles should be translatable. No idea why that's not the case.

**Review by alikon — APPROVED** [review]

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 9f44be709910ee3c8e7250505d5fed47e3cd9340<br /><br />I don't think it needs an update SQL script to update the titles from beta 1 to beta 2.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41603">issues.joomla.org/tracker/joomla-cms/41603</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 9f44be709910ee3c8e7250505d5fed47e3cd9340<br /><br />cr<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41603">issues.joomla.org/tracker/joomla-cms/41603</a>.</sub>

**Comment by alikon** [comment]
rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41603">issues.joomla.org/tracker/joomla-cms/41603</a>.</sub>

**Comment by HLeithner** [comment]
yes we should update from beta1 to beta2 the titles.

**Comment by richard67** [comment]
> yes we should update from beta1 to beta2 the titles.

@brianteeman Could you do that with an update SQL? Here my suggestion for MySQL. For PostgreSQL it just needs to change the names quotes.

```
UPDATE `#__scheduler_tasks` SET `title` = 'Delete Action Logs' WHERE `type` = 'delete.actionlogs' AND `title` = 'DeleteActionLogs';
UPDATE `#__scheduler_tasks` SET `title` = 'Privacy Consent' WHERE `type` = 'privacy.consent' AND `title` = 'PrivacyConsent';
UPDATE `#__scheduler_tasks` SET `title` = 'Rotate Logs' WHERE `type` = 'rotation.logs' AND `title` = 'RotateLogs';
UPDATE `#__scheduler_tasks` SET `title` = 'Session GC' WHERE `type` = 'session.gc' AND `title` = 'SessionGC';
UPDATE `#__scheduler_tasks` SET `title` = 'Update Notification' WHERE `type` = 'update.notification' AND `title` = 'UpdateNotification';```

The type should be in the where condition to not accidentally update an unrelated task with that title, and the title is in the where condition in order not to update the title for that type when the user has already changed it to something else.

**Comment by brianteeman** [comment]
will do that in the morning

**Comment by brianteeman** [comment]
sql updates added

**Comment by richard67** [comment]
Back to pending doe to changes (new update SQL).

@alikon Could you test again? Maybe this time also with updating a 5.0-dev to the update package or custom update URL from Drone. I will do that myself too in a minute or two.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41603">issues.joomla.org/tracker/joomla-cms/41603</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 7ca4991c5e83b92106052c54411cf47f73129fc8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41603">issues.joomla.org/tracker/joomla-cms/41603</a>.</sub>

**Comment by HLeithner** [comment]
can you please fix the merge conflict then it can be merged.

**Comment by richard67** [comment]
> can you please fix the merge conflict then it can be merged.

@HLeithner @brianteeman I've allowed myself to do that.

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
