### PR TITLE
[4.0] Simplify code in Indexer

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Some code simplification.

### Testing Instructions

Install sample data.
Enable `Content - Smart Search` plugin.
Go to Smart Search. Build index.
Use Smart Search in frontend. Check that it works like before.
Edit and save an article or some other content item.
Check again in frontend that indexed content is correctly updated.

### Expected result

Works like before.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 90e9d4479fc20967784a2a81fb240086eb15ea98<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26010">issues.joomla.org/tracker/joomla-cms/26010</a>.</sub>

**Comment by uGE70** [comment]
I have tested this item :white_check_mark: successfully on 90e9d4479fc20967784a2a81fb240086eb15ea98<br /><br />Tested: Clear Index, Index, Publish/Unpublish, Filter Options, Statistics, Search with accents.

Note (CSS): action button is unreadable when items are selected in any rows of the Smart search backend component tables.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26010">issues.joomla.org/tracker/joomla-cms/26010</a>.</sub>

**Comment by ghost** [comment]
Status "Ready To Commit".

**Review by Hackwar — APPROVED** [review]

**Comment by HLeithner** [comment]
Thank you for the optimization.

**Pull request merged**
