### PR TITLE
Route the redirect in the menu logout

### PR DESCRIPTION
**Pull request by laoneo**
### Summary of Changes
The logout via a menu item should route the redirect to logout task. This error happens on one of my production site but not on a fresh Joomla. So it is probably a configuration issue. Neverthless, all controller actions in this class are routing the requests, so should the menu logout as well.

### Testing Instructions
- Create a logout menu item
- Log in on the front end
- Click on the logout menu item
- Additionally this can also be tested with the htaccess redirect

### Actual result BEFORE applying this Pull Request
Logout doesn't work on some sites.

### Expected result AFTER applying this Pull Request
Logout through a menu item works direct.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by laoneo** [comment]
Thanks @brianteeman for the reference. Can you give it a test? So we can ship with the next release.

**Comment by brianteeman** [comment]
I have tested this item :red_circle: unsuccessfully on 501ae72813a82e3159bde6ace4c548b3698e6cc5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42473">issues.joomla.org/tracker/joomla-cms/42473</a>.</sub>

**Comment by brianteeman** [comment]
That was done at the time. Here is a recording

menu

**Comment by laoneo** [comment]
@brianteeman found the issue, can you test again?

**Comment by brianteeman** [comment]
> Sorry for the delay in responding - I had to set up a j4 dev again
> 
> Using the detailed test instructions that I wrote in #37763
> 
> Before this PR I can no longer replicate the issue in that pr so it must have been solved elsewhere and I have closed it.
> 
> With this PR both tests for logging out with the menu item FAIL
> 
> > Warning
> > The security token did not match. The request was cancelled to prevent any security breach. Please try again.

Repeated the tests.
Still can't replicate the original error
Still can confirm the new error with the earlier version of this pr
Applied the  current version of this pr and got no errors

**Comment by laoneo** [comment]
Thanks for the test, I could also only reproduce the issue on one of my sites I'm maintaining.

**Comment by sandewt** [comment]
> Thanks for the test, I could also only reproduce the issue on one of my sites I'm maintaining.

Does the error also occur when you add a new logout menu item to that site?

**Comment by laoneo** [comment]
It happens only then.

**Comment by sandewt** [comment]
> It happens only then.

What kind of message do you see when this error occurs?

**Pull request merged**
