### PR TITLE
'Verify Peer' option not respected in Authentication - Gmail plugin

### LINKED ISSUE #30621: [3][http] Joomla HTTP cannot connect to insecure https sites
### Steps to reproduce the issue

CURL Options passed to the GMAIL Authentication Plugin are not used by the http transport. This is the bug. But digging deeper in abstract: 

dump this code into test.php in the root of your Joomla site

This example is based on the Gmail Authentication Plugin code, stripped back.
```php
<?php

use Joomla\Registry\Registry;

define('_JEXEC', 1);
define('JPATH_BASE', __DIR__);

require_once JPATH_BASE.'/includes/defines.php';
require_once JPATH_BASE.'/includes/framework.php';

$app = JFactory::getApplication('site');


$curlParams = array(
    'transport.curl' => array(
        // DO NOT DO THIS ON A LIVE SITE - NEVER EVER FOLLOW ADVICE TO DO THIS !!!! 
        CURLOPT_SSL_VERIFYPEER => false,
        CURLOPT_SSL_VERIFYHOST => false,
        CURLOPT_PROXY_SSL_VERIFYPEER => false, // PHP7.3+
        CURLOPT_PROXY_SSL_VERIFYHOST => false,// PHP7.3+
    ),
);

$transportParams = new Registry($curlParams);

$http = JHttpFactory::getHttp($transportParams, 'curl');

try {
    $result = $http->get('https://self-signed.badssl.com');
} catch (\Exception $exception){
    echo '<pre>';
    var_dump($exception);
}
```

Navigate to `http://yourdevdomain.dev/test.php` 

### Expected result

No errors, the HTTP should use the curl transport and connect to the badssl.com site without exception or error. 

### Actual result

Exception thrown `SSL certificate problem: self signed certificate`

### System information (as much as possible)

PHP 7.4 tested

### PR DESCRIPTION
**Pull request by SharkyKZ**
Closes https://github.com/joomla/joomla-cms/issues/30621.

### Summary of Changes

Corrects data passed to `JRegistry`.

### Testing Instructions
Review.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by PhilETaylor** [comment]
If it were me I would remove the verify option completely!!

Why would anyone want to ever NOT verify the cert of gmail.com before sending credentials to it?

It just promotes lack of security by design. 

Disabling verification of SSL certs is just a lazy way of developing. There are always better options.

In this exact case no one in their right might should disable verification - and joomla should not even give them the option.

Of course, just my opinion. It's not like this code has ever worked anyway. Hence the PR to correct it.

**Comment by PhilETaylor** [comment]
@Joomla/security

**Comment by richard67** [comment]
Ping @SniperSister @zero-24 .

**Comment by HLeithner** [comment]
Beside that fact that it is a bad idea to use no verification in production we also know that there are enough crape hosts out there with old certificate root.

Anyway the function exists so it should work. If we have 2 tests it can be merged. Removing this feature can be scheduled for j5

**Comment by richard67** [comment]
@HLeithner Any idea how it can be tested, beside code review?

**Comment by jiweigert** [comment]
I go with PhilETaylor,
having a now fixed function, which disables the verification of SSLCerts and haven't even worked when introduced,
is kinda silly.

It is fairly easy to setup a dev/localhost CA/ self-signed SSL cert, so verification could be done that way.

On production, there should be no way to disable the verification of SSL certs.

Hosts which are unmaintained and have old/ outdated SSL Certs have certainly more problems than just invalid SSL certs.
Those hosts should go offline anyway, just to secure the visitors of that site, or otherd because that host ist already hijacked.

But that's just my own 2c.

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30624">issues.joomla.org/tracker/joomla-cms/30624</a>.</sub>

**Comment by richard67** [comment]
Either way it has to be fixed: Fix the buggy function like this PR here does, or remove the buggy function. But leave it as it is should not be an option.

**Comment by HLeithner** [comment]
@richard67 replace the root certificate for curl with an empty one should work

**Comment by zero-24** [comment]
Dear @SharkyKZ 

in preperation of the upcomming release of Joomla 3.10 we have used GitHubs rename feature to rename the staging branch into 3.10-dev. Usually GitHub moves all existing PRs towards the new branch just fine, but here it didnt work. The reason seems to be that the fork of the CMS that was used as base for this PR has been deleted so GitHub does no longer have a base to rebase the PR against the new branch and we are also not able to reopen the PR. For that reason GitHub closed this PR in my name, when this issue is still valid It would require a new PR against the new 3.10-dev or 4.0-dev branch.

**Pull request closed without merging**
