### PR TITLE
[4.0] Site Login Module does not load 'modal_menu' type

### PR DESCRIPTION
**Pull request by infograf768**
### Summary of Changes
As title says

### Testing Instructions
Edit the site login module.
Login Redirection Page and Logout Redirection Page fields use a textarea instead of the Select menu

### After patch
Screen Shot 2019-06-02 at 09 14 23

Can be merged on review

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 34a23f97048d5b9dab0e6608ef2501aa11788435<br /><br />Can be merged by review ... but can also be successfully tested with the Patchtester :tongue: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25084">issues.joomla.org/tracker/joomla-cms/25084</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on dbd498739ef86cb02d760dedd49e21be39652ca9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25084">issues.joomla.org/tracker/joomla-cms/25084</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on dbd498739ef86cb02d760dedd49e21be39652ca9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25084">issues.joomla.org/tracker/joomla-cms/25084</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25084">issues.joomla.org/tracker/joomla-cms/25084</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
