### PR TITLE
[5.1] add missing Header in guidedtours.joomla_welcome

### PR DESCRIPTION
**Pull request by tecpromotion**
Pull Request for PR #41659.

### Summary of Changes

add missing headers in guidedtours.joomla_welcome.ini and guidedtours.joomla_welcome_steps.ini

### Testing Instructions

.

### Actual result BEFORE applying this Pull Request

no header

### Expected result AFTER applying this Pull Request

header

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by tecpromotion** [comment]
@obuisard please check.

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 79ce12bfb86b05342f241f6ccca57ba17b0c1d05<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43115">issues.joomla.org/tracker/joomla-cms/43115</a>.</sub>

**Comment by wojsmol** [comment]
I have tested this item :white_check_mark: successfully on 79ce12bfb86b05342f241f6ccca57ba17b0c1d05<br /><br />code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43115">issues.joomla.org/tracker/joomla-cms/43115</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43115">issues.joomla.org/tracker/joomla-cms/43115</a>.</sub>

**Comment by bembelimen** [comment]
Thanks

**Pull request merged**
