### PR TITLE
[4.0] mod_login accessibility regression

### PR DESCRIPTION
**Pull request by brianteeman**
At some point the site module login has lost the label for the password field. This puts it back

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on aaaa792efc21a432cfac67414efa3aa9a89ad80f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27604">issues.joomla.org/tracker/joomla-cms/27604</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on aaaa792efc21a432cfac67414efa3aa9a89ad80f<br /><br />as I didn't lose yet this label, checked via code review :-)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27604">issues.joomla.org/tracker/joomla-cms/27604</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27604">issues.joomla.org/tracker/joomla-cms/27604</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
ta

**Pull request merged**
