### PR TITLE
[4.0] Restore Joomla\CMS\Helper\ContentHistoryHelper

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Class was removed without deprecation but it still has an alias valid until 5.0. This is causing stub generator to fail.
This restores the class, proxies its code to new Versioning API, and deprecates it for 5.0.

### Testing Instructions

Would be good to test that its methods are still working as expected. Besides that try running stub generator script.

### Actual result BEFORE applying this Pull Request

Stub generator fails with error:

```
ReflectionException {#160
  #message: "Class Joomla\CMS\Helper\ContentHistoryHelper does not exist"
  #code: -1
  #file: "build\stubGenerator.php"
  #line: 75
  trace: {
    build\stubGenerator.php:75 {
      StubGenerator->doExecute()^
      › // Figure out if the alias is for a class or interface
      › $reflection = new ReflectionClass($newName);
      › $type       = $reflection->isInterface() ? 'interface' : 'class';
      arguments: {
        $argument: "Joomla\CMS\Helper\ContentHistoryHelper"
      }
    }
    libraries\src\Application\CliApplication.php:241 { …}
    build\stubGenerator.php:147 { …}
  }
}
```

### Expected result AFTER applying this Pull Request

Stub generator works and it's possible to get/delete/store versions using the class.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by ceford** [comment]
I could not figure out how to test this. I searched the code for both ContentHistoryHelper and JHelperContenthistory and could not find anything testable. I guess it may be something in Versions - but where?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30932">issues.joomla.org/tracker/joomla-cms/30932</a>.</sub>

**Comment by SharkyKZ** [comment]
This isn't used by core and can only be properly tested by using custom code.

**Comment by piotr-cz** [comment]
I'm not sure if it's right thing to restore the class, but the fact is that subs generator is broken and restoring this class makes it work again as it's present in classmap file:

https://github.com/joomla/joomla-cms/blob/12a74a3e96bc47cafed209ba9f489b26aed31cd6/libraries/classmap.php#L109

If this class is restored, part of this PR should be removing it from list of files marked to delete during migration from 3.10 to 4.0:
https://github.com/joomla/joomla-cms/blob/12a74a3e96bc47cafed209ba9f489b26aed31cd6/administrator/components/com_admin/script.php#L3801

**Comment by wilsonge** [comment]
Closing in favour of https://github.com/joomla/joomla-cms/pull/34904 adding the deprecations back into 3.10

**Comment by piotr-cz** [comment]
@wilsonge does the #34904 fix the issue (broken stubs generation)?

**Comment by wilsonge** [comment]
That one I directly fixed with https://github.com/joomla/joomla-cms/commit/f5442b32447dae45dc6f3b63c5f786a7b060256c

**Comment by piotr-cz** [comment]
@wilsonge Thank you, this looks like a proper solution for this problem

**Pull request closed without merging**
