### PR TITLE
[4.0] Adding Mail Templates menu link to alternate preset

### PR DESCRIPTION
**Pull request by infograf768**
### Summary of Changes 
As title says.

### Testing Instructions
Modify Administrator Menu Module to use `Alternative Main Menu Preset`

### After patch
The Mails Template link is available.
Screen Shot 2019-10-18 at 10 34 39

### CODE REVIEW

**Comment by waader** [comment]
I have tested this item :white_check_mark: successfully on 3fc71cc3489785db1d2c50732e716f784bfd328d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26622">issues.joomla.org/tracker/joomla-cms/26622</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 3fc71cc3489785db1d2c50732e716f784bfd328d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26622">issues.joomla.org/tracker/joomla-cms/26622</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26622">issues.joomla.org/tracker/joomla-cms/26622</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
