### PR TITLE
[com_cache] Success and error messages

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Description

When deleting cached items, the user performs and action,so  like in many other views, should receive a success or error message.

So, this PR:
- adds success messages when deleting cache
- adds error messages when an error occured when deleting cache

Also:
- removes deprecated JError usage from com_cache
- other code/coments improvements (check code changes)
#### How to test
1. Use latest staging
2. Go to System -> Global configuration and enable some type of caching
3. Navigate in the backend and in the frontend to generate some cache
4. Go to System -> Clear Cache, you will see some cached items in "site" and in "administrator"
5. Delete some items, you will see you get no message after the page reloads.
6. Apply this patch
7. Repeat step 5. You will get a success message.

For testing error messages you need to simulate an error (like changing a cache group folder permissions in /cache/).

### CODE REVIEW

**Comment by richard67** [comment]
@andrepereiradasilva I could test the success message, but I was not able to provoke an error for testing the error message. Rename page to page1 folder in cache, or changing permissions did not help. It seems the cache cleaner helps itself if permissions do not fit. Shall I mark my test result as success anyway?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9180">issues.joomla.org/joomla-cms/9180</a>.</sub>

**Comment by andrepereiradasilva** [comment]
If in linux, did you try to change the owner/group of folder to one that your php as no permissions do write?

**Comment by richard67** [comment]
Is Linux shared hosting, not really useful to do a chown because am not root.

**Comment by andrepereiradasilva** [comment]
this function (https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/cache/storage/file.php#L417) has to generate some kind of error (in other words, return false).

You can add a

**Comment by richard67** [comment]
@andrepereiradasilva I did modify the file as you said, but still see only a sucess message. But the size of the cache group is same, so nothing was deleted. Any idea what I do wrong?

**Comment by richard67** [comment]
@andrepereiradasilva No, sorry, seems files are deleted, and success message, with the file hacked as you mentioned => ???

**Comment by andrepereiradasilva** [comment]
Do you have Cahe enabled with "File" cahce handler in global config?

Do you have https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/cache/storage/file.php#L417 starting like this?

```php
	protected function _deleteFolder($path)
	{
		return false;
		// Rest of the code
	}
```

It should work.

**Comment by richard67** [comment]
No, I used Cache_Lite. But this one also uses the files, or not?

**Comment by richard67** [comment]
And the file.php I had modified like you wrote.

**Comment by richard67** [comment]
Anyway, I go sleep now. I will check again tomorrow if still necessary.

**Comment by andrepereiradasilva** [comment]
i don't have cache lite, but i think you must do a similiar change in this method https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/cache/storage/cachelite.php#L205

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on e44e0e5ed4e1519509a0cab97caaf4f9a87261d8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9180">issues.joomla.org/joomla-cms/9180</a>.</sub>

**Comment by richard67** [comment]
I just switched to cache handler = File for the test.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9180">issues.joomla.org/joomla-cms/9180</a>.</sub>

**Comment by andrepereiradasilva** [comment]
ok thanks

**Comment by infograf768** [comment]
This works fine.
Example of error:
screen shot 2016-02-21 at 10 37 02

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on e44e0e5ed4e1519509a0cab97caaf4f9a87261d8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9180">issues.joomla.org/joomla-cms/9180</a>.</sub>

**Comment by infograf768** [comment]
RTC. Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9180">issues.joomla.org/joomla-cms/9180</a>.</sub>

**Pull request merged**
