### PR TITLE
Radio field: fix readonly and disabled option

### PR DESCRIPTION
**Pull request by Minei3oat**
Pull Request for Issue #8996 .
### Summary of Changes

After this PR radio fields can be `readonly` and single options of it can be `disabled`. Furthermore I adjusted the solution from @dgt41 in #10969 to fit with the solution of `disabled` options and `readonly`.
### Testing Instructions
- Take some radio fields and add the `disabled` or `readonly` attribute or add the `disabled` attribute to a single option.
- add the class `btn-group` and test again (In Beez3 you won't see a difference as the css code for `btn-group` is missing. See #12029.)

(I've applyed disabled, readonly and disabled option for illustrating. For testing please use only one at time since they have similar effects.)

``` xml
<field
    type="radio"
    default="1"
    disabled="true"
    readonly="true"
    class="btn-group"
>
    <option value="1">JYES</option>
    <option value="0" disabled="true">JNO</option>
</field>
```
### Documentation Changes Required

none

Btw.: Why isn't the JavaScript code related to `btn-group` in a central file so that all templates can use it without copying it? A central file would result in one file to update instead applying the same change on multiple files by multiple developers because every template developer must apply the fix himself.

### CODE REVIEW

**Comment by ggppdk** [comment]
I would like to see this fixed, as now i am doing this, with my own code, adding it in views that have bootstrap styled radio fields that are "readonly"

>Btw.: Why isn't the JavaScript code related to btn-group in a central file so that all templates can use it without copying it? A central file would result in one file to update instead applying the same change on multiple files by multiple developers because every template developer must apply the fix himself.

So that you can have non-bootstrap templates ... or / and also make easier to use other bootstrap version, and also to allow customizing it,

that is why this code is in every single template

Comments:
- i see that this PR removes the JS code and move the adding of the INLINE styling and of the 'disabled' class into the LAYOUT file of radio field, this means that radio-set fields that do not use this layout will no longer work, maybe this is acceptable ?
- also this PR adds the same class to fieldset TAG "disabled" for both the cases that the radio-set is disabled / readonly. For B/C display i see the benefit of adding 'disabled' class to the FIELDSET, but at least 1 more class should be there to allow different styling that would be "readonly" CSS class ?

**Comment by Minei3oat** [comment]
Now there is a `readonly` class on readonly radio fields.

**Comment by Devportobello** [comment]
I have tested this item :white_check_mark: successfully on 15d63938d65396734f7f4e8c485cf61a0cc95558<br /><br />Patch tested successfully<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12039">issues.joomla.org/tracker/joomla-cms/12039</a>.</sub>

**Comment by ghost** [comment]
@ggppdk can you please test so we get the needed 2nd one?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12039">issues.joomla.org/tracker/joomla-cms/12039</a>.</sub>

**Comment by fancyFranci** [comment]
I have tested this item :white_check_mark: successfully on 15d63938d65396734f7f4e8c485cf61a0cc95558<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12039">issues.joomla.org/tracker/joomla-cms/12039</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Pull request merged**
