### PR TITLE
Small Grammar change

### PR DESCRIPTION
**Pull request by brianteeman**
### Before

> ...  has to also be a published Content language.
### After

> ...  also has to be a published Content language.

### CODE REVIEW

**Comment by MATsxm** [comment]
I have tested this item :white_check_mark: successfully on a546b4141c85e31ff7eaf4765fb9fa27271cb0b2<br /><br />on code review - thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11788">issues.joomla.org/joomla-cms/11788</a>.</sub>

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on a546b4141c85e31ff7eaf4765fb9fa27271cb0b2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11788">issues.joomla.org/joomla-cms/11788</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11788">issues.joomla.org/joomla-cms/11788</a>.</sub>

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
