### PR TITLE
Fixing Contact urls for linked authors (New)

### PR DESCRIPTION
**Pull request by Hackwar**
Pull Request for Issue #12603, redo of #12616
### Summary of Changes

Used the right method to generate that URL.
### Testing Instructions

Create a contact for the super user
Create some articles
Create a menu item to display one or multiple articles, do NOT make it the home page.
Create a menu item displaying the Contact category to which belongs the super user contact: alias is english-contacts in this case.
Do NOT create a menu item displaying the single contact.
Display the article in frontend.
Click on the Super User link in the article intro
See that the link is not correct.
Apply patch and see that the link is correct.
### Documentation Changes Required

none

### CODE REVIEW

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 21a278790f73c3ec7a44af177b9d1f2910956eb2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12629">issues.joomla.org/tracker/joomla-cms/12629</a>.</sub>

**Comment by Hackwar** [comment]
Sorry, still had to add the JLoader call.

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on d78a276102fb202b5eabadaf65bc9f0a319f2c9b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12629">issues.joomla.org/tracker/joomla-cms/12629</a>.</sub>

**Comment by conconnl** [comment]
I have tested this item :white_check_mark: successfully on d78a276102fb202b5eabadaf65bc9f0a319f2c9b<br /><br />Tested successfully at PBF NL<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12629">issues.joomla.org/tracker/joomla-cms/12629</a>.</sub>

**Comment by zero-24** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12629">issues.joomla.org/tracker/joomla-cms/12629</a>.</sub>

**Comment by johstrom** [comment]
I am having exact this issue on latest Joomla v3.9.18. How do I fix it? Didn't find any way to download the fixed file to replace the faulty one.

**Comment by Hackwar** [comment]
As has been already written above: This issue has been closed and a long time ago actually. This has been part of Joomla for several years now. If you have this issue, then your installation has not been properly updated. If you really have an issue here, please open a new one.

**Pull request merged**
