### PR TITLE
[4.0] Ensure language code is validated in the mail template

### PR DESCRIPTION
**Pull request by wilsonge**
Pull Request for Issue #30957 .

### Summary of Changes
Ensure there is a valid language code for an application when saving.

### Testing Instructions
You can't follow the instructions in the issue anymore as another PR has disabled the ability to navigate directly to the edit form. However you can reproduce by editing the form directly (as below) - this screenshot also shows the expected error when you save an item with an invalid language code:

image

### Actual result BEFORE applying this Pull Request
Result saves or gives database error

### Expected result AFTER applying this Pull Request
Error message as in the above screenshot

### Documentation Changes Required
None

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 0aed6366c2844653050e8f7882757f4302336821<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31835">issues.joomla.org/tracker/joomla-cms/31835</a>.</sub>

**Comment by ceford** [comment]
I have tested this item :white_check_mark: successfully on 0aed6366c2844653050e8f7882757f4302336821<br /><br />Save without the patch gave: Save failed with the following error: Data too long for column 'language' at row 1

With the patch it gave: Invalid Language Code

That link with a drop down arrow to the right I found confusing. Better to make it a more obvious button?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31835">issues.joomla.org/tracker/joomla-cms/31835</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31835">issues.joomla.org/tracker/joomla-cms/31835</a>.</sub>

**Comment by drmenzelit** [comment]
Thanks

**Pull request merged**
