### PR TITLE
[4.0] Remove "version" parameter from recaptcha plugin

### PR DESCRIPTION
**Pull request by C-Lodder**
### Summary of Changes

The recaptcha plugin only uses version 2, therefore I don't see the need to have a parameter for this at all.

This PR simply removes that parameter

@mbabker thoughts?

### CODE REVIEW

**Review by brianteeman — APPROVED** [review]

**Comment by roland-d** [comment]
My thought is to add the noCaptcha to this plugin. See this open PR #16599

**Comment by brianteeman** [comment]
@roland-d I still think that nocaptcha should be a seperate plugin - its more future proof that way. combining v1 and v2 in the same plugin was a bad idea

**Comment by mbabker** [comment]
I left it since IIRC the PR with the NoCaptcha support was adding it to the same plugin so it's less merge conflicts to deal with.  If it goes into a separate plugin then go ahead and remove it.

Not saying either approach is preferred right now, just why I left the param in place.

**Comment by C-Lodder** [comment]
Cool, I'll leave this open whilst that decision gets made

**Pull request closed without merging**
