### PR TITLE
[4.0] Fix filename not displaying properly in media manager.

### PR DESCRIPTION
**Pull request by anuragteapot**
###Issue

File and folder name not displaying properly.
The file path is showing in the place of the filename.

### Summary of Changes
Changes in:
<code>plugins/filesystem/local/Adapter/LocalAdapter.php</code> 

### Testing Instructions
Open media manager and check out.

### CODE REVIEW

**Comment by ghost** [comment]
Without Pull Request have no Issue:

bildschirmfoto 2018-01-03 um 13 49 27
### System information
4.0-dev
Sample Data
macOS Sierra, 10.12.6
Firefox 57 (64-bit)
#### MAMP 4.2
- Apache-Server
- PHP 7.0.22
- MySQLi 5.6.35

**Comment by anuragteapot** [comment]
@franz-wohlkoenig but I am getting this issue<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19273">issues.joomla.org/tracker/joomla-cms/19273</a>.</sub>

**Comment by joomdonation** [comment]
It is an issue on Windows,  I can confirm it.  Haven't looked at the code yet but maybe you should make PR on this repo https://github.com/joomla-projects/media-manager-improvement

**Comment by anuragteapot** [comment]
@joomdonation yes, I am using windows.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19273">issues.joomla.org/tracker/joomla-cms/19273</a>.</sub>

**Comment by anuragteapot** [comment]
ok, I am going to make PR to media-manager-improvement<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19273">issues.joomla.org/tracker/joomla-cms/19273</a>.</sub>

**Comment by joomdonation** [comment]
Without testing much, I think proper fix would be change code to:

```php
private function getFileName($path)
{
	$path = \JPath::clean($path);

	// Basename does not work here as it strips out certain characters like upper case umlaut u
	$path = explode(DIRECTORY_SEPARATOR, $path);

	// Return the last element
	return array_pop($path);
}
```

It should work on both Windows and Linux

**Comment by anuragteapot** [comment]
@joomdonation Yes this one is a proper fix for this issue thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19273">issues.joomla.org/tracker/joomla-cms/19273</a>.</sub>

**Comment by anuragteapot** [comment]
Should I make a PR to media-manager-improvement with these changes?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19273">issues.joomla.org/tracker/joomla-cms/19273</a>.</sub>

**Comment by joomdonation** [comment]
I think so. Look like media manager is still being developed on it own repo, so better make PR on https://github.com/joomla-projects/media-manager-improvement

**Comment by anuragteapot** [comment]
@joomdonation Thanks

**Pull request closed without merging**
