### PR TITLE
language plugin

### PR DESCRIPTION
**Pull request by fuchshofer**
hi,

i work on a big site, the site has on http 15000 likes, we changed to https.

the problem from joomla comes now. like facebook requested i must put og url to http, what i did.

we use falang, falang use /plugins/system/languagefilter/languagefilter.php

and this makes

example.com/de   canonical to    /de/

for all subpages it set hiself as page canonical.

the problem is facebook consider canonical AND og url, if they both different, Facebook is completly confused, so i can remove over a code the canonical over the theme.php BUT!!  if i want to set a 

301  from /de  to /de/ then i get an error, over the htacess.

any clean suggestions how to resolve that?

ty.

### CODE REVIEW

**Comment by infograf768** [comment]
I do not understand this PR.
For your info, canonical is not added by the language filter in core, but by the SEF plugin.
An issue was solved recently: https://github.com/joomla/joomla-cms/pull/8568 which will be available in 3.5.0

**Comment by fuchshofer** [comment]
hmm, ok.
the problem is, that joomla set a canonical 

from /de  to  /de/ for example..

  <link href="/de/" rel="canonical" />


in /de.

so do you think this canonical come for sure from falang? stephane(falang) said it uses languagefilter plugin and come from there....

ty.

**Comment by infograf768** [comment]
Joomla will ONLY set a canonical <b>after the patch https://github.com/joomla/joomla-cms/pull/8568</b> when a domain is entered in the SF plugin parameter.

Otherwise, if the languagefilter is set so, it will provide `alternate` links, not canonical.

**Comment by fuchshofer** [comment]
but i need to set from /de to /de/ a redirect.

we use falang as language plugin, must i contact then falang???? because if i make over htacess it give me error then for complete page!

understand?

**Comment by infograf768** [comment]
You created a Pull Request. This PR does not contain any change to staging, therefore I can't understand your issue.

**Comment by brianteeman** [comment]
I am closing this at this time. Its been over a month since the last comment - the PR has no changes etc etc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8750">issues.joomla.org/joomla-cms/8750</a>.</sub>

**Pull request closed without merging**
