### PR TITLE
[4.3] Finder: Enforce Taxonomies to contain a title

### PR DESCRIPTION
**Pull request by Hackwar**
Pull Request for Issue #35977.

### Summary of Changes
If a finder plugin tries to add an empty taxonomy, this can fail with the error message from #35977. This PR should fix that. This most likely is an article with a non-existing author or something similar. 

### Testing Instructions
Unfortunately I can't replicate the issue from #35977 and the below testing instructions seem to not be able to replicate the problem. Maybe @Stuartemk can investigate this further and try to test this?
1. Create a user.
2. Create an article and set the author of the article to the previously created user.
3. Delete the user.
4. Clear your search index and rebuild it.

### Actual result BEFORE applying this Pull Request
It fails with the above error message (An Error Has Occurred Category must have a title.)

### Expected result AFTER applying this Pull Request
Everything is properly indexed.

### CODE REVIEW

**Comment by brianteeman** [comment]
Followed test instructions and was unable to replicate the reported problem

**Comment by danpdanp** [comment]
I have tested this item :white_check_mark: successfully on 28dc8cc006f9cc792fe17428d980c8080ab486b5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36759">issues.joomla.org/tracker/joomla-cms/36759</a>.</sub>

**Comment by RickR2H** [comment]
I was not able to reproduce the issue. We need better guidance to reproduce the issue...<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36759">issues.joomla.org/tracker/joomla-cms/36759</a>.</sub>

**Comment by Fedik** [comment]
From code review it looks like a valid fix. 
The error comes from table class https://github.com/joomla/joomla-cms/blob/f520c98c64efb538e70e918acffb60d07e4d6b1e/administrator/components/com_finder/src/Table/MapTable.php#L63-L65

The taxonomy title requirement was introduced in #21327
I suspect User may have some custom finder plugin, that not adapted it.

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on 7050d69b169f83c5921d30a003f2d630515515f4<br /><br />On review looks valid, everything still works, I count it as success :)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36759">issues.joomla.org/tracker/joomla-cms/36759</a>.</sub>

**Comment by RickR2H** [comment]
I have tested this item :white_check_mark: successfully on 7050d69b169f83c5921d30a003f2d630515515f4<br /><br />Even when I could not reproduce the issue, it also doesn't break things. I tested all the search options and everything seems to be okay. That's a good test IMHO.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36759">issues.joomla.org/tracker/joomla-cms/36759</a>.</sub>

**Comment by RickR2H** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36759">issues.joomla.org/tracker/joomla-cms/36759</a>.</sub>

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
