### PR TITLE
[4.0] Resizing template editor causes multiple editor instances #22778 #30240

### PR DESCRIPTION
**Pull request by shim-sao**
Pull Request for Issue #22778 .

### Summary of Changes
Avoid codemirror editor duplication when we are trying to resize the page.

### Testing Instructions
Use codemirror as editor
Try to resize the page
Try to click on add readmore or something else

### Actual result BEFORE applying this Pull Request
The editor is duplicated each time we are doing a resize of the page

### Expected result AFTER applying this Pull Request
A single instance of the editor
Add readmore and other button should work

### Documentation Changes Required

To test the patch, use `npm run build:js` to build the final file `admin-article-readmore.min.js.gz`

### CODE REVIEW

**Comment by richard67** [comment]
@shim-sao Could you add a hint in the testing instructions that it needs to run npm after having applied the change of this PR in order to get the js built? Not every tester knows that. Thanks in advance.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 9ea3c3937e45e698b8588fbca6134dcaf0fbdcaf<br /><br />I could reproduce the issue with having multiple instances of the codemirror editor e.g. in the template details file edit view after having resized the broswer windows from large to small and back to large, and I could verify that this PR fixes it.

Browser is Firefox 78.0.2 (64-Bit) on Windows 10.

Hint for other testers: It needs to run npm to build the changed js.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30241">issues.joomla.org/tracker/joomla-cms/30241</a>.</sub>

**Comment by shim-sao** [comment]
Sorry, I don't use npm, I have just tested directly by creating the gzip file with 7z

**Comment by richard67** [comment]
That's also a way if only such small changes. Anyway, it needs a 2nd good test, then it will get RTC status, which means ready to commit, and then it will be ready for final review and merge by a maintainer.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 9ea3c3937e45e698b8588fbca6134dcaf0fbdcaf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30241">issues.joomla.org/tracker/joomla-cms/30241</a>.</sub>

**Comment by richard67** [comment]
@shim-sao For developing (s)css or js stuff in Joomla 4 it needs npm if your are not sure where to copy the files to and to which js standard to transpile them to, too, and for some PHP stuff sometimes composer. You can find the details about how to set up a development environment here: [https://docs.joomla.org/J4.x:Setting_Up_Your_Local_Environment](https://docs.joomla.org/J4.x:Setting_Up_Your_Local_Environment). At a first look that might seem oversized to you, but I was told by people that that's the future in web development.

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30241">issues.joomla.org/tracker/joomla-cms/30241</a>.</sub>

**Comment by shim-sao** [comment]
No problem for the technologies, I know how all is working.
I discover a little how Joomla 4 is done and the work in/of the team.
I've always wanted to help without daring, so I'm going for it. I will do things cleaner in the future

**Comment by brianteeman** [comment]
@shim-sao thank you very much for your first of what I hope will be many pull requests

**Comment by wilsonge** [comment]
@shim-sao thankyou very much for this PR! Nice work! Hope to see you around more in the future.

**Comment by Scrabble96** [comment]
This is still an issue in 4.0.0-rc1.

**Pull request merged**
