### PR TITLE
[4.0] JLoader::registerNamespace() to use psr4 autoloading as default

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Per doc block, autoloading type should default to `psr4` in 4.0

### Testing Instructions

Code review?

### Documentation Changes Required

Yeah.

### CODE REVIEW

**Comment by richard67** [comment]
@SharkyKZ Looks good to me on code review. I only wonder why the same change hasn't been made for the `getNamespaces` function here [https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/loader.php#L171](https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/loader.php#L171), i.e. same doc block notice added in past so that it now could be changed, too. But maybe that's right, I don't know. Do you have any idea?

Update: Maybe the `prs` typo in the comment here should be corrected, too? [https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/loader.php#L165](https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/loader.php#L165)

**Comment by SharkyKZ** [comment]
No idea. Typos already corrected.

**Comment by 810** [comment]
We should also edit the getNamespaces on the libraries/namespacemap.php file.

It should also support the libraries dir when you have added the namespace on the xml file. So you don't need to add a extra plugin to execute it.

Now you need a extra plugin if you just want to add a Library.

**Comment by SharkyKZ** [comment]
@810 I'm already working on that, but that will be a different PR.

**Comment by 810** [comment]
Ok thnx,
i had edited yesterday already, but i removed the code.

**Comment by 810** [comment]
ps on the registerNamespace on loader.php
there is also a windows dir issue. You can add a path::clean($path) to fix it.
now for me its: loading this location: C:\wamp\www\freshj4\libraries\kunena/

**Comment by 810** [comment]
its working, but the path is: C:\wamp\www\freshj4\libraries/kunena/

`
\JLoader::registerNamespace('Kunena\\Forum\\Libraries', JPATH_LIBRARIES . '/kunena/');
`

**Comment by SharkyKZ** [comment]
Mixed slashes generally don't cause issues. If you need to perform string manipulation of the paths for whatever reason, you can use `Joomla\CMS\Filesystem\Path::clean()` yourself.

**Comment by richard67** [comment]
> Mixed slashes generally don't cause issues. If you need to perform string manipulation of the paths for whatever reason, you can use `Joomla\CMS\Filesystem\Path::clean()` yourself.

Correct.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 6dd0919bed713f33c196954034d6a163ad4e9be2<br /><br />Code review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27460">issues.joomla.org/tracker/joomla-cms/27460</a>.</sub>

**Comment by richard67** [comment]
@wilsonge Do you think it needs to make the same change here https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/loader.php#L171 for function `getNamespaces`, i.e. let `$type` parameter default to `'psr4'`?

**Comment by 810** [comment]
I have tested this item :white_check_mark: successfully on 6dd0919bed713f33c196954034d6a163ad4e9be2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27460">issues.joomla.org/tracker/joomla-cms/27460</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27460">issues.joomla.org/tracker/joomla-cms/27460</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
