### PR TITLE
com_wrapper auto-height error in IE

### PR DESCRIPTION
**Pull request by wojsmol**
fix for https://github.com/joomla/joomla-cms/issues/8989
Original issue description

> javascript code in /media/com_wrapper should have
> 
> ```
> document.frames['blockrandom'].document.body.scrollHeight
> ```
> 
> but not
> 
> ```
> document.frames('blockrandom').document.body.scrollHeight
> ```
> 
> Note that auto-height actually works for IE only.

### CODE REVIEW

**Comment by Denitz** [comment]
Looks great!

**Comment by Denitz** [comment]
Hm.. after tests I found the better code which works for IE, Chrome and Firefox:

```
function iFrameHeight()
{
	if (window.frames && window.frames['blockrandom'])
	{
		var doc = window.frames['blockrandom'].contentDocument || window.frames['blockrandom'].document || window.frames['blockrandom'].contentWindow.document;
		if (doc !== undefined) {
			document.getElementById('blockrandom').style.height = parseInt(doc.body.scrollHeight) + 20 + 'px';
		}
	}
}
```

**Comment by brianteeman** [comment]
@Denitz Can you please submit a PR with that code<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8991">issues.joomla.org/joomla-cms/8991</a>.</sub>

**Comment by wojsmol** [comment]
@brianteeman Code proposed by the @Denitz in https://github.com/joomla/joomla-cms/pull/8991#issuecomment-175526890 I added in https://github.com/joomla/joomla-cms/pull/8991/commits/f9cb8fdd8efef07f4efeb029b2bffeca84ca70ee

**Comment by brianteeman** [comment]
Thanks - I can see that now on github.com but the issue tracker didnt show that ;(<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8991">issues.joomla.org/joomla-cms/8991</a>.</sub>

**Comment by conconnl** [comment]
Is this ready for testing?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8991">issues.joomla.org/joomla-cms/8991</a>.</sub>

**Comment by wojsmol** [comment]
yes

**Comment by schmidtpaddy** [comment]
I have tested this item :white_check_mark: successfully on f9cb8fdd8efef07f4efeb029b2bffeca84ca70ee<br /><br />tested in edge. changes were made. @icampus<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8991">issues.joomla.org/joomla-cms/8991</a>.</sub>

**Comment by mcanuste** [comment]
I have tested this item :red_circle: unsuccessfully on f9cb8fdd8efef07f4efeb029b2bffeca84ca70ee<br /><br />Tested @icampus
After PR:
Console shows this error on IE version 11.
- SCRIPT5: Access is denied.
- iframe-height.min.js (1,73)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8991">issues.joomla.org/joomla-cms/8991</a>.</sub>

**Comment by Denitz** [comment]
@mcanuste What is iframe URL? Ensure that same-origin policy is respected.

**Comment by slibbe** [comment]
I have tested this item :red_circle: unsuccessfully on f9cb8fdd8efef07f4efeb029b2bffeca84ca70ee<br /><br />I'm with kevinscheithauer. I could not reproduce this issue; maybe someone can write more precise test instructions?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8991">issues.joomla.org/tracker/joomla-cms/8991</a>.</sub>

**Comment by slibbe** [comment]
I'm with kevinscheithauer. I could not reproduce this issue; maybe someone can write more precise test instructions?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8991">issues.joomla.org/tracker/joomla-cms/8991</a>.</sub>

**Comment by microtribe** [comment]
I have tested this item :red_circle: unsuccessfully on f9cb8fdd8efef07f4efeb029b2bffeca84ca70ee<br /><br />Like others I think we need better instructions to recreate the issue. I created a new menu item wrapper with auto-height set, and it displayed exactly the same in Chrome and IE 11.09600.18499<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8991">issues.joomla.org/tracker/joomla-cms/8991</a>.</sub>

**Comment by jeckodevelopment** [comment]
@wojsmol can you please look at the conflicts?

**Comment by wojsmol** [comment]
@jeckodevelopment fixed with https://github.com/joomla/joomla-cms/pull/11554

**Pull request closed without merging**
