### PR TITLE
flysystem

### PR DESCRIPTION
**Pull request by dgrammatiko**

### CODE REVIEW

**Comment by dgt41** [comment]
This is only for testing purposes, do not merge it!

**Comment by Bakual** [comment]
Closing as not meant to be merged.
If you want to testrun Travis, you can set it up to run on your fork as well. It's just a few clicks :smile:

**Comment by Kubik-Rubik** [comment]
@Bakual Please do not close PR's that are against this branch! We need them in the code sprint.

**Comment by Bakual** [comment]
Ah, didn't see it's not against staging.

**Comment by Kubik-Rubik** [comment]
No problem! ;-)

**Pull request closed without merging**
