### PR TITLE
Hide the filter_tag parameter in URL

### PR DESCRIPTION
**Pull request by QuonXF**
Pull Request for Issue #36546 and #34527.

Fix for SEF-URL (search engines friendly url), hides the filter_tag parameter from the URL when the menu item is created with category type and filtering by tag or tags.

### Actual result BEFORE applying this Pull Request
https://site.local/menu?filter_tag[0]=X?filter_tag[1]=Y
https://site.local/menu/itemA?filter_tag[0]=X
https://site.local/menu/itemA/subitemA?filter_tag[0]=X

### Expected result AFTER applying this Pull Request
https://site.local/menu
https://site.local/menu/itemA
https://site.local/menu/itemA/subitemA

### CODE REVIEW

**Comment by brianteeman** [comment]
Surely that is not correct. If you already have a menu item `/menu/category`

**Comment by QuonXF** [comment]
There is a menu item with the blog category type and with a selection by tag, as well as a sub menu item with the same parameters.

Before the patch:
https://site.local/menu?filter_tag[0]=XXX
https://site.local/menu/itemA?filter_tag[0]=XXX
https://site.local/menu/itemA/subitemA?filter_tag[0]=XXX

After the patch:
https://site.local/menu
https://site.local/menu/itemA
https://site.local/menu/itemA/subitemA

**Comment by QuonXF** [comment]
Then nothing will happen to him.

If the menu was created without filtering by tag, then when getting the menu item 
**$item = $this->router->menu->getItem($query['Itemid'])**

the filter_tag parameter will be missing and check 
**if ($item->query['filter_tag'] === $query['filter_tag'])**

will return false and will not execute 
**unset($query['filter_tag'])**

When SEF-URL (search engines friendly url) is disabled, everything will be in place.

With tag filtering:
index.php?option=com_content&view=category&layout=blog&id=145&**filter_tag[0]=2**&Itemid=401

Without tag filtering:
index.php?option=com_content&view=category&layout=blog&id=145&Itemid=403

**Comment by brianteeman** [comment]
This is clearly wrong and should be closed

**Comment by QuonXF** [comment]
Added a check for the existence of the filter_tag variable by the selected item, and added a check for query for the presence of a filter_tag.

**Comment by MacJoom** [comment]
I have tested this item :white_check_mark: successfully on 676db1920cc9469829cef568217684257869085a<br /><br />Before Patch: https://bugsfun.jdayusa.com/site6/index.php/de/tagged?filter_tag[0]=2
After Patch: https://bugsfun.jdayusa.com/site6/index.php/de/tagged
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40225">issues.joomla.org/tracker/joomla-cms/40225</a>.</sub>

**Comment by formfranska** [comment]
I have tested this item :white_check_mark: successfully on 676db1920cc9469829cef568217684257869085a<br /><br />Thank you for this patch 👍🏽😊🙏🏽<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40225">issues.joomla.org/tracker/joomla-cms/40225</a>.</sub>

**Comment by obuisard** [comment]
Thank you @QuonXF for the PR!

**Pull request merged**
