### PR TITLE
[4.2]Corrected different multi-select behavior in media manage

### PR DESCRIPTION
**Pull request by rajputanuj31**
Pull Request #33637

Summary of Changes
Multi select without using shift key

### Testing Instructions
Open Media
Try to Select media manager files.

### Actual result BEFORE applying this Pull Request
You can not select multiple items without holding the shift key.

### Expected result AFTER applying this Pull Request
You can select multiple items by holding `ctrl key` & clicking on items.
You can also select all files between two selected files by holding `shift key`.

https://user-images.githubusercontent.com/115709571/216755468-f55e3c02-a972-448f-87d1-0a3c9ec364fe.mp4

### CODE REVIEW

**Comment by dgrammatiko** [comment]
@rajputanuj31 I think the expected behaviour involves both `ctrl` and `shift` keys, I had started fixing it here: https://github.com/joomla/joomla-cms/pull/39679#issuecomment-1399528891 (it needs the `shift` key logic as explained in that comment)

**Comment by richard67** [comment]
Besides this, the javascript linter at the drone CI tests reports errors here https://ci.joomla.org/joomla/joomla-cms/61584/1/26 :
```
+ npm run lint:js

> joomla@4.0.0 lint:js
> eslint --config build/.eslintrc --ignore-pattern '/media/' --ext .es6.js,.es6,.vue .

/********/src/administrator/components/com_media/resources/scripts/components/browser/items/item.es6.js
  117:17  error  'event' is defined but never used  no-unused-vars

/********/src/administrator/components/com_media/resources/scripts/components/browser/items/row.vue
  96:13  error  'event' is defined but never used  no-unused-vars

✖ 2 problems (2 errors, 0 warnings)
```

**Comment by rajputanuj31** [comment]
> @rajputanuj31 I think the expected behaviour involves both `ctrl` and `shift` keys, I had started fixing it here: [#39679 (comment)](https://github.com/joomla/joomla-cms/pull/39679#issuecomment-1399528891) (it needs the `shift` key logic as explained in that comment)

@dgrammatiko Is this looks fine??

https://user-images.githubusercontent.com/115709571/216788557-34c9634c-1e0a-412a-809d-9076ab5e95bb.mp4

**Comment by dgrammatiko** [comment]
@rajputanuj31 please rebase this pr to 4.3-dev

**Comment by rajputanuj31** [comment]
Please Review this PR #39824.
Previously I have forked only 4.2 branch so for rebasing had to fork again 🙃

**Pull request closed without merging**
