### PR TITLE
blank space typo

### PR DESCRIPTION
**Pull request by marco2142**
### Summary of Changes

fixed blank space typo in line 40

### CODE REVIEW

**Comment by ghost** [comment]
@marcogold1 thanks for your Contribution.

**Comment by ChathuraT** [comment]
I have tested this item :white_check_mark: successfully on abc5f8fa6d33093e6630ad60eb6cf40575230375<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17137">issues.joomla.org/tracker/joomla-cms/17137</a>.</sub>

**Comment by Quy** [comment]
PR #17993

**Comment by ghost** [comment]
closed as having Pull Request #17993<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17137">issues.joomla.org/tracker/joomla-cms/17137</a>.</sub>

**Pull request closed without merging**
