### PR TITLE
[4.0] Non-existent string

### PR DESCRIPTION
**Pull request by brianteeman**
Removes reference to non existing description string.

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 75ad95a1b6ca4159f19dca51d592ac480fb7fee0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25340">issues.joomla.org/tracker/joomla-cms/25340</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 75ad95a1b6ca4159f19dca51d592ac480fb7fee0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25340">issues.joomla.org/tracker/joomla-cms/25340</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25340">issues.joomla.org/tracker/joomla-cms/25340</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
