### PR TITLE
[4.0] Move joomlaupdate to vanilla JS

### PR DESCRIPTION
**Pull request by laoneo**
As the title say, moves the joomla update script to vanilla JS.

Tabs got changed to spaces too.

### CODE REVIEW

**Comment by wilsonge** [comment]
Need a test on this one before we merge it. Just because I don't know the order of updates and stuff well enough (unsure if we need to load the jquery anyhow because we'll have the 3.x file still after an update has run). I think this should be fine. But until it's tested not sure enough

**Comment by laoneo** [comment]
You mean testing an update from 3 to 4?

**Comment by laoneo** [comment]
Because to test the full code a temp modification of the view file is needed.

**Comment by laoneo** [comment]
What should we do here as it is unlikely that an upgrade will be tested in the close future?

**Comment by HLeithner** [comment]
@laoneo I will test it do you have short test instructions or is it just simulate the update process with pr installed first?

And could you resolve the conflict?

**Comment by laoneo** [comment]
@wilsonge what exactly needs to be tested here? DIdin't get you full from your comment https://github.com/joomla/joomla-cms/pull/22421#issuecomment-425398287

**Comment by wilsonge** [comment]
On this specific page we might still have some old files loaded/non-updated files loaded on the upgrade. We might still have the old file and require jQuery or other things. Basically onupgrade is when we have the most bugs and generally I'd like to test that kinda thing as opposed to 'code review' merges which is what i do normally. because it's hard to predict exactly what happens on upgrade.

Actually to test *all* i need to do is to figure out how to generate the deleted files list in j4 from j3. if i can do that then we should be able to upgrade straight from 3.9.2 (which is what i think 4.0-dev is synced with right now) to 4.x via package upload in 3.9. Obviously however trying to figure out an automated way of doing that is proving hard - i tried thinking about this about two weeks ago but it's really tricky

**Comment by HLeithner** [comment]
But this site doesn't load any 3rd party code and the upgrade screen will be shown after a successful upgrade to j4. At this stage shouldn't be any legacy file for the next upgrade or?

**Comment by roland-d** [comment]
@laoneo Can you fix the merge conflict so I can get this tested? How should this be tested?

**Comment by zero-24** [comment]
> But this site doesn't load any 3rd party code and the upgrade screen will be shown after a successful upgrade to j4. At this stage shouldn't be any legacy file for the next upgrade or?

On a short review this seams to be true the page we need to be very carefull with is: https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_joomlaupdate/tmpl/update/default.php#L18

But I'm happy to assist on any upgrade tests to make sure this does not break things.

**Comment by laoneo** [comment]
Conflicts fixed, @zero-24 and @roland-d would be nice to get this tested. Thanks for your help.

**Comment by roland-d** [comment]
@laoneo I can test this but let me know how did you test it? Some test instructions are welcome :)

**Comment by laoneo** [comment]
We need some sort of upgrade path and then the upgrade should be tested. If I got @zero-24 right, then he can help with it.

**Comment by infograf768** [comment]
Tested:

Modify the version.php to a 3.9.x, fix database, choose custom URL for J Update with `https://update.joomla.org/core/nightlies/next_major_list.xml` and get the correct current version of J in the update checks.

_With a Notice though:_

`Notice: Trying to get property 'version' of non-object in .../administrator/components/com_joomlaupdate/Model/UpdateModel.php on line 1357`

Screen Shot 2019-09-12 at 10 32 29

Nevertheless, I clicked on Update and got

Screen Shot 2019-09-12 at 10 35 47

version was modified, database was updated OK. Looks like all went fine.

**Comment by laoneo** [comment]
Thanks @infograf768!

**Comment by infograf768** [comment]
Maybe solve the Notice too?Or shall I just set the Test as OK?

**Comment by laoneo** [comment]
Better to do it in it's own pr as it is not related to this one.

**Comment by roland-d** [comment]
Looks good to me:
image

**Comment by roland-d** [comment]
I have tested this item :white_check_mark: successfully on 7702f1ee1c0dccb38b9e26be5d1f271a698ee3ee<br /><br />The Joomla Updater works as expected because it updated my site to the latest available Joomla version.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22421">issues.joomla.org/tracker/joomla-cms/22421</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 7702f1ee1c0dccb38b9e26be5d1f271a698ee3ee<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22421">issues.joomla.org/tracker/joomla-cms/22421</a>.</sub>

**Comment by ghost** [comment]
Status "Ready To Commit".

**Comment by zero-24** [comment]
Hmm i'm not sure whether this is a valid way of testing as pointing to the major_nighty Update server and this still ships the original files. I'm at the joomla day this weekend so i'm not sure whether i can build the package. It should also be tested with an package that include the change. As noted above i don't think this is relevant to this specific change but as George requested it we should double check this.

@JM can you please open an issue and tag me so i can take a look after my holidays?

**Comment by ghost** [comment]
@zero-24 RTC off?

**Comment by wilsonge** [comment]
Already asked @roland-d to test this case - yes remove RTC temporarily please. If both work then it's good to go

**Comment by wilsonge** [comment]
Roland has tested this successfully next to me. So merged. Thankyou @roland-d and of course @laoneo

**Comment by roland-d** [comment]
I tested an update from 3.9.12 to 4.0.0-alpha12. Upgrade went fine. Just some small things I noticed

image

image

The template notice @wilsonge mentioned.

**Comment by wilsonge** [comment]
@roland-d can you open a PR for the duplicate ID? That ones new to me?

**Comment by zero-24** [comment]
👍 Great!

**Comment by infograf768** [comment]
still need an issue for the Notice?

**Comment by wilsonge** [comment]
Yes please! Just the duplicate ID one. Button sizing isn’t that important yet

**Comment by infograf768** [comment]
I am speaking of
`Notice: Trying to get property 'version' of non-object in .../administrator/components/com_joomlaupdate/Model/UpdateModel.php on line 1357`
not the duplicate ID

**Comment by wilsonge** [comment]
Oh I totally missed that 🤦‍♂ yes please

**Comment by zero-24** [comment]
https://github.com/joomla/joomla-cms/pull/26293 cc @infograf768 i have done a PR to fix that notice in the installer :)

**Pull request merged**
