### PR TITLE
[4] [Workflow] Removed unused constants

### PR DESCRIPTION
**Pull request by Kostelano**
### Summary of Changes
I have not been able to find any places where these constants are used. The search also did not help. The constants are probably not up to date.

### CODE REVIEW

**Comment by richard67** [comment]
@bembelimen Conditions have been removed as far as I remember, right? I can confirm the texts removed by this PR are not used in any PHP or JS.

**Comment by bembelimen** [comment]
> Conditions have been removed as far as I remember, right?

Yes

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on ab1ef7ca5827f5868c4fdc4942ff905908c2e60d<br /><br />Code search: I can confirm the removed language strings are not used in any PHP or JS or XML file. They belong to removed features, descriptions or messages.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33377">issues.joomla.org/tracker/joomla-cms/33377</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on ab1ef7ca5827f5868c4fdc4942ff905908c2e60d<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33377">issues.joomla.org/tracker/joomla-cms/33377</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33377">issues.joomla.org/tracker/joomla-cms/33377</a>.</sub>

**Pull request merged**
