### PR TITLE
Node 12 reached EOL

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # .

### Summary of Changes
Use the current Node/Npm

[
schedule
](https://nodejs.org/en/about/releases/)

### Documentation Changes Required

Yes, all docs that have hardcoded the min version for Node/NPM need an update

### CODE REVIEW

**Comment by zero-24** [comment]
FYI i have added a signature which should let drone accept the changes to the drone file ;)

**Comment by dgrammatiko** [comment]
Thanks Tobias 👍

**Review by wilsonge — APPROVED** [review]

**Comment by bembelimen** [comment]
Thx

**Comment by HLeithner** [comment]
Seems some of our ci doesn't work with the new version... for example nightlies and PR packager/download

**Comment by dgrammatiko** [comment]
@HLeithner where is the code for those?

**Comment by HLeithner** [comment]
Hannes and me fixing it now, its at github.com/joomla-projects/docker-images packager branch

**Comment by dgrammatiko** [comment]
@HLeithner let me know if I can somehow help

**Comment by HLeithner** [comment]
What's the best way to install/update node on debian?

**Comment by dgrammatiko** [comment]
If you have snap: `sudo snap install node --classic --channel=18`
if not `apt-get update && apt-get install snapd` then the above command

**Comment by HLeithner** [comment]
I decided todo the offical way using https://github.com/nodesource/distributions/blob/master/README.md

**Comment by dgrammatiko** [comment]
@HLeithner just make sure you go with 18. The 16 on the main repo is ok as the code is expected to be used from devs so switching directly to 18 (skipping 16 that has a 6 or so more months till EOL) would forced more people to update their node. But internal tooling is ok to use 18 (one less update for October)

**Comment by HLeithner** [comment]
ok, I also wanted to ask this^^

**Comment by dgrammatiko** [comment]
@HLeithner fyi: https://github.com/joomla/joomla-cms/pull/37830

**Comment by Hackwar** [comment]
This is still not really the way I like it, but anyway. My big problem right now is, that the node:16-alpine docker image has npm 8.5.5 installed, while our package.json requires npm 8.6.0. That means we get an error at the beginning of each npm build. Is there a reason for using npm 8.6.0 as requirement instead of 8.5.5? I don't care which way we go, but I want that error to be gone...

**Comment by dgrammatiko** [comment]
@Hackwar https://github.com/joomla/joomla-cms/pull/37830 sets npm min to 8.5.5

**Comment by Hackwar** [comment]
thx

**Pull request merged**
