### PR TITLE
CodeMirror updated to v5.27.4

### PR DESCRIPTION
**Pull request by okonomiyaki3000**
Pull Request for Issue # .

### Summary of Changes
CodeMirror updated to latest version.
http://codemirror.net/doc/releases.html

### Testing Instructions
Use CodeMirror.

### Expected result
It should work just as the previous version.

### Actual result
Yes it does.

### Documentation Changes Required
Nope.

### CODE REVIEW

**Comment by okonomiyaki3000** [comment]
I don't believe there is much of particular interest to most Joomla users in this update.

**Comment by okonomiyaki3000** [comment]
This Hound seems like a good boy but he need not check 3rd party libraries.

**Comment by C-Lodder** [comment]
Really not sure why Hound is linting the JS, as I've disabled it on the staging branch: https://github.com/joomla/joomla-cms/blob/staging/.hound.yml#L7

**Comment by okonomiyaki3000** [comment]
I don't know what this error is but it's surely wrong.

**Comment by C-Lodder** [comment]
@okonomiyaki3000 - errors are valid points, but we're not using going to be linting JS on Joomla 3, only Joomla 4

**Comment by okonomiyaki3000** [comment]
@C-Lodder Hmm. Before I rebased it there was some other error I'd never seen before. I'm not sure it had anything to with linting but it went away after a rebase.

**Comment by C-Lodder** [comment]
Ah, well just ignore the comments by Hound, they hopefully won't happen on future PR's for staging ;)

**Comment by okonomiyaki3000** [comment]
Ah, now I remember, there was a Jenkins pr-merge error for some reason. Anyway, gone now so no problem.

**Comment by mbabker** [comment]
That one was from the [new Jenkins pipeline](https://developer.joomla.org/news/699-information-about-our-development-setup.html).  It's still a little quirky but not a merge blocker so it's safe to ignore until we say otherwise 😉

**Comment by okonomiyaki3000** [comment]
It's back.

**Comment by brianteeman** [comment]
I am going to close this as there now is a newer release

**Pull request closed without merging**
