### PR TITLE
[com_finder] maps view: Indexed content counting and other improvements

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
Pull Request for Improvement.
#### Summary of Changes

This PR adds some improvements to Smart Search Content Maps:
1. Add a label to each content map title (it was missing)
2. Adds link to view only the first level sublevels in the blue badges.
3. Adds counting and corresponding links to "Indexed Content" view.
###### Before PR

image
###### After PR

image
#### Testing Instructions

3 simple test needed.
1. Apply patch
2. Go to Smart Search -> Indexed Content and run the index
3. Go to Smart Search -> Content Maps
4. Click on a content map "Title" and check that in that row the select box is checked.
   
   ok = test 1 passed
5. Click on the blue level 1 badge. and confirm it showns only the sublevels after click. Clear the filter after.
   
   ok = test 2 passed
6. Confirm the published/unpublished counting is working properly and they link to the index content view with the corresponding filter.
   Please note that the content_map will only be activated if PR https://github.com/joomla/joomla-cms/pull/10256 is also installed, but you can check the resulting URL (check the filter is there) for this test propose.
   
   ok = test 3 passed

### CODE REVIEW

**Comment by grhcj** [comment]
I have tested this item :red_circle: unsuccessfully on e19edeb3af1e3f033baa36c43f1dd172a1f864d3<br /><br />With this PR applied, I get   
<code>Notice: Undefined property: stdClass::$num_nodes in [...]\administrator\components\com_finder\views\maps\tmpl\default.php on line 134</code>   
for every element at content maps view.
I cleared my browser cache and tested with latest staging.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10257">issues.joomla.org/joomla-cms/10257</a>.</sub>

**Comment by andrepereiradasilva** [comment]
ok will check that.

**Comment by andrepereiradasilva** [comment]
ok should be fixed now.

**Comment by andrepereiradasilva** [comment]
@grhcj please retest

**Comment by grhcj** [comment]
I have tested this item :white_check_mark: successfully on ed45c327099e8a933fedf4117c3c9f713cfcd8e1<br /><br />In test 3, the filter param was present in the URL, but I can't verify that the filter value is right.
Because this shouldn't be part of this PR, I didn't do further tests on this.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10257">issues.joomla.org/joomla-cms/10257</a>.</sub>

**Comment by andrepereiradasilva** [comment]
thsnk for testing, yes that will only work with https://github.com/joomla/joomla-cms/pull/10256 also applied

**Comment by chrisdavenport** [comment]
I have tested this item :white_check_mark: successfully on ed45c327099e8a933fedf4117c3c9f713cfcd8e1<br /><br />Works as described now that #10256 has been merged.  Nice improvement.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10257">issues.joomla.org/joomla-cms/10257</a>.</sub>

**Comment by brianteeman** [comment]
RTC -before merging please double check the unrelated Travis issue<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10257">issues.joomla.org/joomla-cms/10257</a>.</sub>

**Comment by wilsonge** [comment]
Travis is unrelated and now fixed in staging. Merging this

**Comment by andrepereiradasilva** [comment]
thanks for testing, comments and merging!

**Pull request merged**
