### PR TITLE
com_privacy consents

### PR DESCRIPTION
**Pull request by brianteeman**
The code was setup correctly to handle multiples but there was no separate string for a singular in english. As a result if you invalidate 1 consent you got the same message as when you invalidate 9 consents

### CODE REVIEW

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on 8a5a36375e5239f46c9943cc2689022c60d20c89<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26792">issues.joomla.org/tracker/joomla-cms/26792</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 8a5a36375e5239f46c9943cc2689022c60d20c89<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26792">issues.joomla.org/tracker/joomla-cms/26792</a>.</sub>

**Comment by infograf768** [comment]
rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26792">issues.joomla.org/tracker/joomla-cms/26792</a>.</sub>

**Comment by infograf768** [comment]
tks

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
