### PR TITLE
Add correct path for language css [fix for 16506]

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/16506.

### Summary of Changes

Sin 3.7.0 admin template does not load language specific css.
This PR intends to solve that.

### Testing Instructions

1. Use latest staging
2. Add a en-GB.css file in `/administrator/language/en-GB/en-GB.css`
3. Load the admin in isis and hathor and confirm the css file is loaded.

### Expected result

Language specific CSS file is loaded.

### Actual result

Language specific CSS file is not loaded.

### Documentation Changes Required

None.

### CODE REVIEW

**Comment by C-Lodder** [comment]
I have tested this item :white_check_mark: successfully on 4780f219c18248249c5e5eef868b163a26d40f9b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16513">issues.joomla.org/tracker/joomla-cms/16513</a>.</sub>

**Comment by infograf768** [comment]
I had solved it here with
`JHtml::_('stylesheet', 'administrator/language/' . $lang->getTag() . '/' . $lang->getTag() . '.css', array('version' => 'auto'));`

because the case is not taken care of in the `includeRelativeFiles` method
`.../libraries/cms/html/html.php`

where it defaults to `$path = JPATH_ROOT . "/$file";`

Will now test this PR

**Comment by infograf768** [comment]
Sorry, this patch does not work for me.

**Comment by andrepereiradasilva** [comment]
@infograf768 `ltrim($this->baseurl, '/')` in administrator tempaltes is `administrator` so is the same as you have done but without hardcoding `administrator`.

It worked in my case can you explain better where it doesn't work?

**Comment by infograf768** [comment]
I have no idea why it does not work here on Firefox. It works OK on Safari.

I know that with my solution I do get the correct href in source in both browsers

`<link href="/testnew/trunkgitnew/administrator/language/fa-IR/fa-IR.css?1558dc3b794518a5caee794b66aaf3f0" rel="stylesheet" />`

for info `$this->baseurl` here gives
`/testnew/trunkgitnew/administrator`

**Comment by infograf768** [comment]
Hmm, maybe a session issue. After quit and reload Firefox, it is OK

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 4780f219c18248249c5e5eef868b163a26d40f9b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16513">issues.joomla.org/tracker/joomla-cms/16513</a>.</sub>

**Comment by infograf768** [comment]
RTC. Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16513">issues.joomla.org/tracker/joomla-cms/16513</a>.</sub>

**Comment by Quy** [comment]
On my local install, where Joomla is in `joomla-cms` directory:

Not working with PR: `joomla-cms/administrator/language/en-GB/en-GB.css`
I think it is looking for `joomla-cms` inside `joomla-cms`.

Working with manual change and no relative: `administrator/language/en-GB/en-GB.css`

**Comment by andrepereiradasilva** [comment]
ok @Quy thanks.
yeah forgot subdir joomla installs ...

**Comment by infograf768** [comment]
i take of the rtc for now<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16513">issues.joomla.org/tracker/joomla-cms/16513</a>.</sub>

**Comment by andrepereiradasilva** [comment]
should work now

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 96e00bdef816bcee576bbb1156690686259ff99f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16513">issues.joomla.org/tracker/joomla-cms/16513</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 96e00bdef816bcee576bbb1156690686259ff99f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16513">issues.joomla.org/tracker/joomla-cms/16513</a>.</sub>

**Comment by infograf768** [comment]
RTC for good now. :)

@C-Lodder 
Please use this code in 4.0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16513">issues.joomla.org/tracker/joomla-cms/16513</a>.</sub>

**Comment by C-Lodder** [comment]
Cheers. Will update tomorrow

**Pull request merged**
