### PR TITLE
[4.0] Smart Search categories plugin needs to use right extension element

### PR DESCRIPTION
**Pull request by Hackwar**
This is a redo of PR #16278.

When using the advanced features of the category system, specifically several types of categories per component, the Smart Search categories plugin fails and uses the wrong parts of the extension. This should fix that.

### Testing Instructions
1. Make sure that the `Content - Smart Search` plugin is enabled.
2. Go to `administrator/index.php?option=com_categories&view=categories&extension=com_content.test` of your 4.0 test installation. This simulates that you have a category type `test` for a component.
3. Click on "New" and create a category with a unique name, so that you can find it again in the Smart Search backend. Alternatively you can clear the index of Smart Search first.
4. Save the new category and then go to the Smart Search index. See that the category has NOT been indexed.
5. Apply the patch, go to the above URL again, edit the category that we just created and save it again.
6. Go to the Smart Search again and see that the category has now been indexed.

### CODE REVIEW

**Comment by carlitorweb** [comment]
> Install a component that uses categories with sections

Any suggestion for this?

**Comment by carlitorweb** [comment]
> Install a component that uses categories with sections

@Quy you have an idea what extension can use for this? no come nothing to my mind now

**Comment by Quy** [comment]
Sorry I don't know any to recommend.

**Comment by Hackwar** [comment]
I used this feature of com_categories in a component for a customer, but that component is not public. Sorry.

**Comment by carlitorweb** [comment]
@Hackwar if you find or other find an extension we can use for test this, or another way, like modified some core component, let us know

**Comment by brianteeman** [comment]
Weblinks ?

**Comment by TobsBobs** [comment]
What extension should i use for testing?

**Comment by carlitorweb** [comment]
That is the big question ;)

**Comment by Hackwar** [comment]
Wow, just took me half a year, but now I have a way for you to test this.

### How to test
1. Make sure that the `Content - Smart Search` plugin is enabled.
2. Go to `administrator/index.php?option=com_categories&view=categories&extension=com_content.test` of your 4.0 test installation. This simulates that you have a category type `test` for a component.
3. Click on "New" and create a category with a unique name, so that you can find it again in the Smart Search backend. Alternatively you can clear the index of Smart Search first.
4. Save the new category and then go to the Smart Search index. See that the category has NOT been indexed.
5. Apply the patch, go to the above URL again, edit the category that we just created and save it again.
6. Go to the Smart Search again and see that the category has now been indexed.

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 14c085ccb2e0bf543388ed7a8c34016964e2770c<br /><br />I've tested this, following exactly the test instructions.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20658">issues.joomla.org/tracker/joomla-cms/20658</a>.</sub>

**Comment by bembelimen** [comment]
I have tested this item :white_check_mark: successfully on 14c085ccb2e0bf543388ed7a8c34016964e2770c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20658">issues.joomla.org/tracker/joomla-cms/20658</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20658">issues.joomla.org/tracker/joomla-cms/20658</a>.</sub>

**Pull request merged**
