### PR TITLE
Update TinyMCE to 4.5.9

### PR DESCRIPTION
**Pull request by brianteeman**
Version 4.5.9 (2018-08-02)
  Fixed a bug where Edge 17 wouldn't be able to select images or tables.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 53321b9169cf4c214c9749691300d3ce0566ec63<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22879">issues.joomla.org/tracker/joomla-cms/22879</a>.</sub>

**Comment by vc-development** [comment]
I have tested this item :white_check_mark: successfully on 53321b9169cf4c214c9749691300d3ce0566ec63<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22879">issues.joomla.org/tracker/joomla-cms/22879</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22879">issues.joomla.org/tracker/joomla-cms/22879</a>.</sub>

**Comment by jsubri** [comment]
I have tested this item :white_check_mark: successfully on 53321b9169cf4c214c9749691300d3ce0566ec63<br /><br />This is solving a long outstanding issue reported by end-users on Edge.
Screen shot below

Edited: broken English being so happy this is fixed.
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22879">issues.joomla.org/tracker/joomla-cms/22879</a>.</sub>

**Comment by jsubri** [comment]
Now working with this patch
screen shot 2018-11-01 at 19 36 07<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22879">issues.joomla.org/tracker/joomla-cms/22879</a>.</sub>

**Comment by zero-24** [comment]
Merged. Thanks!

**Comment by brianteeman** [comment]
Thanks - another one bites the dust

**Comment by ssnobben** [comment]
Ok thats fine. 

I also see that WordPress 4.9.8 updated to TinyMCE 4.8.0 and that is 20 update versions https://www.tiny.cloud/docs/changelog/ after this version of Joomla. What stops Joomla to get to the 4.8 versions too?

**Comment by brianteeman** [comment]
Its not backwards compatible

**Comment by ssnobben** [comment]
hmm ok yeah Joomla is behind Wordpress a lot now with TinyMCE and also soon with the Gutenberg editor https://frontenberg.tomjn.com/

**Comment by mbabker** [comment]
TinyMCE 4.6 dropped support for browsers that Joomla is still supporting; a review of that same changelog document would have shown that.  Therefore, Joomla cannot upgrade the distributed TinyMCE editor without abandoning browser support.

Gutenberg is Automattic's attempt to use the open source project "founded" by their CEO to compete with other SaaS solutions by introducing an entirely new management workflow.  It has nothing to do with upgrading editors.

**Pull request merged**
