### PR TITLE
[4.0]Update sites missing string

### PR DESCRIPTION
**Pull request by brianteeman**
There was no label on the first filter for select state

To test view source on the select state selector and see that the label is not "enabled" or code review

### CODE REVIEW

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 92a8f914274db2d2612f4ff74d7c2f5323903330<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28187">issues.joomla.org/tracker/joomla-cms/28187</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 92a8f914274db2d2612f4ff74d7c2f5323903330<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28187">issues.joomla.org/tracker/joomla-cms/28187</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28187">issues.joomla.org/tracker/joomla-cms/28187</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
