### PR TITLE
Code review on com_admin component

### PR DESCRIPTION
**Pull request by mbabker**
This PR is a general overview and cleanup of some code structure and doc blocks in the com_admin component.  Changes of note:
- Doc blocks cleaned up some to follow standard
- Default object types set to match the documented type
- Not using variables for items only referenced once
- Construct of the arrays in the sysinfo model
- Renamed private `_addDirectory()` method to `addDirectory()` to comply with code style
- Return the results of the view's `display()` methods to be consistent with the documented return
### Testing Instructions

Pages from com_admin (the System Information, Joomla! Help, and the Edit Account menu items) function correctly pre- and post- patch.

### CODE REVIEW

**Comment by kolvar** [comment]
tested with the given com_admin-Pages. Works.

**Comment by kolvar** [comment]
I have tested this item :white_check_mark: successfully on 9ef16320720766fe9317c25e259ba348671d7742<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8078">issues.joomla.org/joomla-cms/8078</a>.</sub>

**Comment by matrikular** [comment]
I have tested this item :white_check_mark: successfully on 9ef16320720766fe9317c25e259ba348671d7742<br /><br />Tested by code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8078">issues.joomla.org/joomla-cms/8078</a>.</sub>

**Comment by Bakual** [comment]
Merged, thanks!

**Comment by jduerscheid** [comment]
Tested sucessful<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/8078">issues.joomla.org/joomla-cms/8078</a>.</sub>

**Comment by widmann-it** [comment]
Works

**Pull request merged**
