### PR TITLE
[imp] Add the ability to use a custom.css with Protostar.

### PR DESCRIPTION
**Pull request by roland-d**
Currently it is impossible to use a custom.css file when using the Protostar template. A search on the net always ends up with a core hack of the index.php file, which could result in a problem when the index.php is being updated in a Joomla update.

This change checks if the file custom.css exists and if so, load it.

### CODE REVIEW

**Comment by roland-d** [comment]
This topic came up again at the local user group. So I am thinking is, if custom.css can't be used, what if we change the name to something else for example user.css?

**Comment by brianteeman** [comment]
Is the only problem the name custom.css?
If so then I would go with local.css or user.css 
Seems easy enough

**Comment by roland-d** [comment]
From what I understand what @infograf768 wrote it is indeed the name custom.css that is the problem here. Can you confirm @infograf768 ?

**Comment by brianteeman** [comment]
If thats the case then its an easy and useful addition

**Comment by dgt41** [comment]
@roland-d May I propose another way to solve this problem?
Here is my thought:
Introduce an empty less file e.g. isis/less/user.less
Edit template.less to include this new file at the end (same for the rtl)
Provide a button on the backend so admin can recreate the template.css, template-rtl.css

This way we will not introduce one more http request and users can always get some custom css served!

**Comment by brianteeman** [comment]
Thats not a good idea. Running the less compiler on a live " low resourced
shared" server is a guaranteed way to kill your account.

On 20 January 2015 at 22:12, Dimitris Grammatiko <notifications@github.com>
wrote:

> @roland-d <https://github.com/roland-d> May I propose another way to
> solve this problem?
> Here is my thought:
> Introduce an empty less file e.g. isis/less/user.less
> Edit template.less to include this new file at the end (same for the rtl)
> Provide a button on the backend so admin can recreate the template.css,
> template-rtl.css
>
> This way we will not introduce one more http request and users can always
> get some custom css served!
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/4211#issuecomment-70744961>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by dgt41** [comment]
@brianteeman The less compiler will be required to run only once, I didn’t mean "run less compiler for every request". But anyhow I haven’t benchmark this, so you might be right.

**Comment by brianteeman** [comment]
I understand you but users will make a change- compile make a change -
compile make a change - compile etct - trust me - seen it happen too often
on too many sites - it kills poor hosts

On 20 January 2015 at 22:25, Dimitris Grammatiko <notifications@github.com>
wrote:

> @brianteeman <https://github.com/brianteeman> The less compiler will be
> required to run only once, I didn’t mean "run less compiler for every
> request". But anyhow I haven’t benchmark this, so you might be right.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/4211#issuecomment-70747050>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by Bakual** [comment]
I still don't see what the problem is we're trying to solve. There are various extensions on JED which allow to do just that. And they are all better than what we would do here.

**Comment by infograf768** [comment]
>From what I understand what @infograf768 wrote it is indeed the name custom.css that is the problem here. Can you confirm @infograf768 ?

yep.

>There are various extensions on JED which allow to do just that. And they are all better than what we would do here.

There are indeed quite a few in 
http://extensions.joomla.org/category/style-a-design/templating

**Comment by roland-d** [comment]
> I still don't see what the problem is we're trying to solve. 

The problem is that users can't add their own CSS styling to Protostar without having to use a 3PD extension or hack the Protostar template. The majority of templates have such an option and it is almost standard to have a custom css file users can edit.

> And they are all better than what we would do here.

I think we can offer the simplicity of custom css file, if users want more they can use an extension. Having to use an extension for a 4 line change seems overkill to me.

**Comment by brianteeman** [comment]
Agree. Were spending more time discussing it than it will take to
write,tear,document and comit

**Comment by infograf768** [comment]
Anyhow, we would also need a rtl one I guess.
And the name anyway should be changed.

**Comment by roland-d** [comment]
I will update the PR with the needed changes.

**Comment by infograf768** [comment]
Without adding a Parameter, this would be a hidden feature....

**Comment by mbabker** [comment]
No, we don't.  We just need to document it, IMO there is no need for a parameter to tell the template to scan for an optional custom CSS file.

**Comment by brianteeman** [comment]
A common thing done by many template clubs is to have a check for a custom
css file > 0k
If it is >0k then the file is included otherwise it isnt

So no need for any parameter. If it has content then it is used. If it has
no content then it is ignored

**Comment by roland-d** [comment]
Ok, I have updated the name of the file and check if the size is larger than 0. Once this is merged I can write the documentation for it.

As for needing an RTL one, I think this is not needed as RTL specific changes can be put in this file as well because it is the last file loaded, so it will always be applied.

**Comment by brianteeman** [comment]
Are the travis errors on this PR related to the PR or the Unit Tests<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4211">issues.joomla.org/joomla-cms/4211</a>.</sub>

**Comment by roland-d** [comment]
@brianteeman I don't see any errors on this PR?

**Comment by brianteeman** [comment]
Travis says it fails

**Comment by wilsonge** [comment]
Not the last commit from what i can see. I think you missed the most recent two

**Comment by brianteeman** [comment]
Ah I was going by the one at the top of this page on issues.joomla.org

On 4 February 2015 at 15:15, George Wilson <notifications@github.com> wrote:

> Not the last commit from what i can see. I think you missed the most
> recent two
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/4211#issuecomment-72872200>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by roland-d** [comment]
@brianteeman I wonder if that is a bug of JIssues not updating the status.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4211">issues.joomla.org/joomla-cms/4211</a>.</sub>

**Comment by brianteeman** [comment]
Yeah I've raised that as a bug

**Comment by brianteeman** [comment]
@test 
Created a user.css using the template manager
Tested it is loaded after template.css 
Tested it is not loaded if empty

All good<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4211">issues.joomla.org/joomla-cms/4211</a>.</sub>

**Comment by thebeuving** [comment]
@test
Created a user.css in the templates/protostar/css directory
loads after template.css
does not load if empty

**Comment by zero-24** [comment]
Moving RTC thanks for testing. Can someone add the `New Feature` and `RTC` label?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4211">issues.joomla.org/joomla-cms/4211</a>.</sub>

**Comment by brianteeman** [comment]
Setting RTc - thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/4211">issues.joomla.org/joomla-cms/4211</a>.</sub>

**Comment by ghazal** [comment]
Why restrain this new feature to 3.5 ?
Tested in last 3.4.2RC, and it works allright. no big deal either.
As it is said earlier, now, it's common practice among frameworked templates to allow the ability to add a custom.css file to the template.
And, as Brian Teeman says, "So no need for any parameter. If it has content then it is used. If it has no content then it is ignored".
Furthermore, why add a third party extension to perform such a trivial action, very useful though.
To make it short, I think It would be a very nice addition to J!3.4.2

**Comment by Bakual** [comment]
> Why restrain this new feature to 3.5 ?

Because according to SemVer, new features require a new minor version. So it will be 3.5. No big deal either :smile:

**Comment by mbabker** [comment]
Merged to `3.5-dev` via 1f16717

**Comment by haya1300** [comment]
I prefer custom.css instead of user.css because in all documentation on the internet or in pdf docs there it is called custom.css. If you want to have properly documentation you must add this exception for the Protostar template in the documentation.
Also plenty Joomla users who are using the custom.css of the Protostar template on their website(s) it will not functioning any more and it must be adjusted after an upgrade to Joomla 3.5
Off course it can be fixed easily but that is not user-friendly.
This is the reason why I should prefer to call it custom.css

**Comment by zero-24** [comment]
@haya1300 

>Also plenty Joomla users who are using the custom.css of the Protostar template on their website(s) it will not functioning any more and it must be adjusted after an upgrade to Joomla 3.5

No. If it works bevor the update it will work also after the update. (e.g. via Plugin) If you use a core hack to make this work without a template copy this gets reverted every update anyway ;)

**Comment by roland-d** [comment]
@haya1300 It is not possible to use the name custom.css because Tinymce will otherwise use the file and apply the CSS style to your editor window.

>  If you want to have properly documentation you must add this exception for the Protostar template in the documentation.

It doesn't have to be us. Joomla is a community, so you can do it as well.

**Comment by jjsjjs** [comment]
Am i correct that i only have to use/change the index.php to be able to use custom.css ?
Can i use it already in 3.4.8?
If so this is a great feature as i believe Protostar is one of the finest templates around.

**Comment by wilsonge** [comment]
No it's going to be in Joomla 3.5 (you can look at the milestone on the right to see what version it will be in) - and it will not require any changes to index.php when it's introduced - you will just need to create your custom CSS file.

**Comment by jjsjjs** [comment]
ok great!
Thanks

**Comment by N6REJ** [comment]
You can use a custom.css with any template easily if you install my plugin
http://extensions.joomla.org/extension/jowwow-css-loader

**Comment by jjsjjs** [comment]
Thanks a lot :)
I going to check it out right now.

If works ok i will write a review on the extensions page. THis would be also a good candidate as a standard item for Joomla ;)

**Comment by N6REJ** [comment]
@jjsjjs let me go do that really fast.. idky its not correct.

**Comment by thebeuving** [comment]
I am out of the office February 18th and 19th. If this is an emergency please call me at (209) 217-6400 and leave a voicemail if I don't answer, I will do my best to respond promptly.

I will reply to all non-emergency requests on Monday February 22st.

Thank you,
David Beuving

**Comment by N6REJ** [comment]
@jjsjjs  updated

**Comment by jjsjjs** [comment]
Thanks Bear! Great plug-in. Worked instantly, no hasle. I will write a review this week on the extensions page under the pseudoname idnib (haha it's the reverse of my daughter's name)

**Comment by N6REJ** [comment]
Thanks... its been a long time since I updated it but it does everything 
I can reasonably want it to do and now with the ability to add css file 
right from within the template manager I dont' see the urgent need to 
change it.
Bear

**Comment by wilsonge** [comment]
Guys this isn't the place to be talking about 3rd party plugins ;) Please take it off this thread :)

**Comment by N6REJ** [comment]
just close the ticket george

**Comment by wilsonge** [comment]
It's been closed since August ;)

**Pull request closed without merging**
