### PR TITLE
[4.0] Toolbar - Options class

### PR DESCRIPTION
**Pull request by brianteeman**
The code that adds the class "ml-auto" to the Options button on all the toolbars has an extra space. It doesn't break anything but technically its invalid markup.

To test view the source of any Options button in any component before and after this PR.

It will change from
`<joomla-toolbar-button class=" ml-auto">
`to
`<joomla-toolbar-button class="ml-auto">
`

### CODE REVIEW

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on aa800751929e603d6a8ce50b8a6e3a3883ef8271<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27660">issues.joomla.org/tracker/joomla-cms/27660</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on aa800751929e603d6a8ce50b8a6e3a3883ef8271<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27660">issues.joomla.org/tracker/joomla-cms/27660</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27660">issues.joomla.org/tracker/joomla-cms/27660</a>.</sub>

**Comment by brianteeman** [comment]
Thx

**Pull request merged**
