### PR TITLE
remove link to dead domain

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue ##10868
#### Summary of Changes

Looks like Andi Tarr is no longer in control of the domain tarrconsulting.com which is referenced in the Hathor template
#### Testing Instructions

Back-end > Extensions > Templates.
In the left column, the items "Styles" and "Templates" are present. Click on "Templates" and display the admin templates. 

Before the PR the author email and author url both refer to tarrconsultingcom

After the PR the author email is changed to admin@joomla.org (the same as with Isis) and the author url is removed.

### CODE REVIEW

**Comment by brianteeman** [comment]
As the domain referred to is now a spam/scam/unsafe site I have marked this as a release blocker for 3.6<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10869">issues.joomla.org/joomla-cms/10869</a>.</sub>

**Comment by bertmert** [comment]
I have tested this item :white_check_mark: successfully on 919829e123b46bc2334e91de0597765f7e38208f<br /><br />Link is still present under
Extensions > Manage > Manage > Tooltip in column Author but not clickable.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10869">issues.joomla.org/joomla-cms/10869</a>.</sub>

**Comment by brianteeman** [comment]
@bertmert the only way I know to resolve that is to press the rebuild cache button on that page. The data will then be rebuilt from the changed file in this PR. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10869">issues.joomla.org/joomla-cms/10869</a>.</sub>

**Comment by mbabker** [comment]
On an update all the core extension manifest caches are refreshed also so it should clear itself up.

**Comment by brianteeman** [comment]
OK - cool

On 19 June 2016 at 22:56, Michael Babker <notifications@github.com> wrote:

> On an update all the core extension manifest caches are refreshed also so
> it should clear itself up.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/10869#issuecomment-227022771>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABPH8fvuJB62_A_emESyzVZIFKKcXzxFks5qNbsagaJpZM4I5QcC>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by ggppdk** [comment]
I have tested this item :white_check_mark: successfully on 919829e123b46bc2334e91de0597765f7e38208f<br /><br />Also updating web-site via:
Components / Joomla! Update / Upload & Update TAB
- cleared the manifest cache too, thus tool-tip that @bertmert mentioned appeared correctly

(NOTE: i had to extract the zip file that i downloaded from GitHub and remove the sub-folder, so that web-site update via upload will work)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10869">issues.joomla.org/joomla-cms/10869</a>.</sub>

**Comment by infograf768** [comment]
RTC. Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10869">issues.joomla.org/joomla-cms/10869</a>.</sub>

**Comment by wilsonge** [comment]
Thanks Brian! :)

**Pull request merged**
