### PR TITLE
[4.0] Disable category state and access filter when indexing

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue #26114 and #26226.

### Summary of Changes

Disables category state and access filter in finder plugins.

### Testing Instructions

Enable `Content - Smart Search` plugin.
Create an article.
Unpublish its category.

### Expected result

Category unpublished.

### Actual result

>An error has occurred.

>    0 Argument 2 passed to Joomla\Component\Finder\Administrator\Indexer\Result::addNestedTaxonomy() must implement interface Joomla\CMS\Tree\ImmutableNodeInterface, null given, called in plugins\finder\content\content.php on line 322 

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on c114b7c244ce5521663ba31cd2d7406821240b0e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26235">issues.joomla.org/tracker/joomla-cms/26235</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on c114b7c244ce5521663ba31cd2d7406821240b0e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26235">issues.joomla.org/tracker/joomla-cms/26235</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26235">issues.joomla.org/tracker/joomla-cms/26235</a>.</sub>

**Comment by wilsonge** [comment]
Why's this required now :/ this isn't an issue in 3.x right?

**Comment by wilsonge** [comment]
@Hackwar this feels like a "bug" introduced by the interfaces (even if it's due to badly designed code to start with)

**Comment by Hackwar** [comment]
This isn't an issue in 3.x, since there we don't have the nested taxonomies and the taxonomy is just 2 strings. I wouldn't call this a bug.

**Comment by wilsonge** [comment]
There's definitely a bug. You can't install testing sample data without this patch

**Comment by brianteeman** [comment]
It is only a bug when I say it is a bug. The rear of the titimet is your fault :)

**Comment by N6REJ** [comment]
I have tested this item :white_check_mark: successfully on 6142a59e72c2e4d4f7aabd12906c5380fc6952a3<br /><br />
RTC
solved #26226<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26235">issues.joomla.org/tracker/joomla-cms/26235</a>.</sub>

**Comment by wilsonge** [comment]
Still holding on this for now. I believe in the end we're going to find this is related in some way to the sample data. It's good to know we have a fallback option though

**Comment by SharkyKZ** [comment]
Nothing to do with sample data. Finder plugins require a category. We have to disable filters here. Otherwise indexed content would differ based on who triggered the indexing.

**Comment by infograf768** [comment]
After patching with this I do get the error stated in https://github.com/joomla/joomla-cms/issues/26404#issuecomment-540990571

Sample data or not. Only solved if I disable the smartsearch plugins.

**Comment by SharkyKZ** [comment]
I see we need to run category state through `$this->translateState()`. Not sure if we also need to check parent category state.

**Comment by infograf768** [comment]
@Hackwar 
We need to solve these. As it is your baby, please help.

**Comment by SharkyKZ** [comment]
Should be good now, I think. @brianteeman @Quy can you test again?

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 7898300101a6260928a7eae5f528f03686066b9a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26235">issues.joomla.org/tracker/joomla-cms/26235</a>.</sub>

**Comment by infograf768** [comment]
Taking off RTC until we get another test.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26235">issues.joomla.org/tracker/joomla-cms/26235</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 7898300101a6260928a7eae5f528f03686066b9a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26235">issues.joomla.org/tracker/joomla-cms/26235</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26235">issues.joomla.org/tracker/joomla-cms/26235</a>.</sub>

**Comment by Renuka-S** [comment]
I have tested this item :white_check_mark: successfully on e2338e170c08395058d1d55a8554cb3fa10ee089<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26235">issues.joomla.org/tracker/joomla-cms/26235</a>.</sub>

**Comment by jduerscheid** [comment]
I have tested this item :white_check_mark: successfully on e2338e170c08395058d1d55a8554cb3fa10ee089<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26235">issues.joomla.org/tracker/joomla-cms/26235</a>.</sub>

**Comment by infograf768** [comment]
@wilsonge 
This PR is still working fine here. Can you merge?

**Comment by HLeithner** [comment]
thx

**Pull request merged**
