### PR TITLE
Install again -> Update again

### PR DESCRIPTION
**Pull request by sovainfo**
Changed the text from Reinstall Joomla core files to Update. Originally suggested "Update again", but it might be the first time you update.
The reinstall is actually processing the update again or for the first time. It is not limited to replenishing the files.

### CODE REVIEW

**Comment by C-Lodder** [comment]
Personally, I think the current label (`Reinstall Joomla core files`) is better suited

**Comment by izharaazmi** [comment]
If it is limited to reinstall core **files** only, the current label is better. If it performs database update/fix as well then the better choice would be just "Reinstall Joomla".

**Comment by sovainfo** [comment]
As mentioned on Joomla! CMS Development it just executes the update again. Which means it does the same thing as what the original update does. Obviously, it doesn't process the schema changes again, that would produce a lot of errors. It does process new schema changes (unprocessed schema changes)

Surprised to see that people still don't know what an update does. There is more to it than replacing files and processing database updates.

**Comment by izharaazmi** [comment]
Well, certainly a schema change process would cause errors as most (if not all) of the sql servers do not allow `IF EXISTS` type of check for columns and several other limitations also apply.

And there is nothing to be surprised. Not all of us use/work with every segment of anything, even Joomla. 😄

**Comment by brianteeman** [comment]
Reinstall means more to me that just replacing files. It is not correct to say "Update again" as that implies it is only useful for people who have already done an update. It might be a fresh 3.6.2 site that they made a mistake and hacked core files and they want to reinstall

**Comment by izharaazmi** [comment]
Should we have something that checks the integrity of everything in Joomla core files + database and fixes them as well? About files a simple overwrite/delete should be sufficient. But when it comes to database check it usually gets complicated.
May be we can have a some schema definition file format other than plain SQL scripts – may be XML or something better, that can be used to build/fix the db using the appropriate drivers.

This may be an off-topic query. Should I take this to Google Groups instead?

**Comment by zero-24** [comment]
In the core? There are some external components and services that provide that kind of check iirc

**Comment by izharaazmi** [comment]
I think having that in the core will help better.

**Comment by brianteeman** [comment]
I am even less in favour of just changing it to the word "update" - that is definitely an incorrect description in english as you are definitely no updating when you reinstall the same version

**Comment by roland-d** [comment]
In my opinion the current text is good enough for people to understand that they can reinstall Joomla. Users do not need to know or understand all the things that go on behind the scenes.

Therefore I will close this PR as it will not be merged. Thank you all for your participation.

**Comment by Webdongle** [comment]
Reinstall Joomla files suggests they are reinstalled but they are not reinstalled ... they are rewritten and the the update run.

'Update' suggests the site is updated but it is not updated

imho both 'Reinstall Joomla' files and 'Update' are incorrect.  Perhaps '**Rerun Update**' would be more descriptive because most users know that running the update replaces the files and makes necessary changes to the database ?

**Comment by brianteeman** [comment]
You can not rerun an update if the site has never been updated - that makes no sense

**Comment by Webdongle** [comment]
But you can't 'Reinstall Joomla files' because they the files are written not installed

**Comment by zero-24** [comment]
Maybe Refresh Joomla files?

**Comment by izharaazmi** [comment]
If we are really into changing it, then imho, the better substitute could be "Reset Joomla core files"

**Comment by sovainfo** [comment]
Why don't you call it `Refresh manifests`, that is also one of the thing the update does.
Or `Remove obsolete files`, `Update Assets`,`Flush sessions`, `convert to utf8mb4`

Maybe instead just mentioning one of those actions, use `Apply update`.

**Pull request closed without merging**
