### PR TITLE
Tag save-events missing in JHelperTags::createTagsFromField

### PR DESCRIPTION
**Pull request by csthomas**
Pull Request for Issue #5631.
#### Summary of Changes

When you create a new tag from com_tags component then save-events are triggered, but from com_content article edit layout after add a new tag events are missing.

I created a proposal for missing content event for 
onContentBeforeSave and onContentAfterSave.

I put a raw context "com_tags.tag" but it may be changed to ex: typeAlias.

Method  JHelperTags::createTagsFromField currently is not a static method so should be run as
instance method in addTagMapping at line 65:

$tags = self::createTagsFromField($tags);
#### Testing Instructions

It requires some content plugin with methods onContentBeforeSave and onContentAfterSave for context "com_tags.tag".

I want to use that for filter tag alias and title.

### CODE REVIEW

**Comment by brianteeman** [comment]
Testers please review comments on #5631<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9307">issues.joomla.org/joomla-cms/9307</a>.</sub>

**Comment by csthomas** [comment]
Thanks you for merge the patch

**Comment by csthomas** [comment]
Sorry I created  a mistake.

**Comment by csthomas** [comment]
I created a mistake closing that request. I still think that this patch can help.

May be that commit is not beautiful, but complete tags events.

Events should be run when:
- a tag is creating or modifying at com_tags edit form (currently it is working)
- and when a tag is creating at com_content edit form (currently missing)
- probably on other components because tags is everywhere, but I concentrate only on article tags. 

When some developer want to create some tag validation for articles then there is a problem. 

What should I do when I want to filter tags and do not allow to creating tags with match regular pattern?
- my answer is to use this patch

Please give me some advice.
What should I change for patch to be considered useful enough to be accepted?

**Comment by marrouchi** [comment]
@csthomas I think this PR is the simplest solution to use right now. I would suggest in a future intervention the following  :  
1. Move the createTagsFromField into a core system plugin that gets executed on onContentAfterSave. The plugin in question would simply search if there's any tag attribute in the saved object and then create the new tags found.
2. Use the TagsModelTag::save instead of TagsTableTag::store to automatically trigger the onContentAfterSave with a "com_tags.com_tags.tag" context. 

Do you want me to test this PR ?

**Comment by csthomas** [comment]
This PR wait a long time for any interest.  
If you can please test. 
You need some plugin which will catch that events. If there will be a success test then PR will be more interesting for others.

If more people would like more changes then I can try to find better solution.

**Comment by marrouchi** [comment]
I have tested this item :white_check_mark: successfully on 9bda7fe3cff4448a84aeab868b65d3e19d942ae8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9307">issues.joomla.org/tracker/joomla-cms/9307</a>.</sub>

**Comment by brianteeman** [comment]
@csthomas this is very hard to test without a plugin that catches these events - if you can provide one it will be easier to get people to test it

**Pull request closed without merging**
