### PR TITLE
[4.4] Postinstallation-Message htaccess.txt brotli change (#43173) - strings sorted alphabetically

### PR DESCRIPTION
**Pull request by tecpromotion**
Pull Request for PR #43173 .

### Summary of Changes

Strings sorted alphabetically

### Testing Instructions

.

### Actual result BEFORE applying this Pull Request

not sorted alphabetically

### Expected result AFTER applying this Pull Request

sorted alphabetically

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 7a7c341d633708ccae2eb2bed884de7959c33409<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43180">issues.joomla.org/tracker/joomla-cms/43180</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 7a7c341d633708ccae2eb2bed884de7959c33409<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43180">issues.joomla.org/tracker/joomla-cms/43180</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43180">issues.joomla.org/tracker/joomla-cms/43180</a>.</sub>

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
