### PR TITLE
[3.9][com_installer] Show error alert on error, not message alert

### PR DESCRIPTION
**Pull request by ReLater**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/24209

### Testing Instructions
- See https://github.com/joomla/joomla-cms/issues/24209

### Expected result
- Red error alert if extension update fails

### Actual result
- Message alert if update fails

### CODE REVIEW

**Review by HLeithner — APPROVED** [review]

**Comment by kofaysi** [comment]
I have tested this item :white_check_mark: successfully on a40977996924bb0527fc1436e260ce013801e2fe<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24210">issues.joomla.org/tracker/joomla-cms/24210</a>.</sub>

**Comment by kofaysi** [comment]
> I have tested this item ✅ successfully on [a409779](https://github.com/joomla/joomla-cms/commit/a40977996924bb0527fc1436e260ce013801e2fe)
> This comment was created with the [J!Tracker Application](https://github.com/joomla/jissues) at [issues.joomla.org/tracker/joomla-cms/24210](https://issues.joomla.org/tracker/joomla-cms/24210).

image

**Comment by Quy** [comment]
Do you want to match the code using `$msg` and `$msgType` as in `\administrator\components\com_installer\models\install.php`?

```
		// Install the package.
		if (!$installer->install($package['dir']))
		{
			// There was an error installing the package.
			$msg = JText::sprintf('COM_INSTALLER_INSTALL_ERROR', JText::_('COM_INSTALLER_TYPE_TYPE_' . strtoupper($package['type'])));
			$result = false;
			$msgType = 'error';
		}
		else
		{
			// Package installed successfully.
			$msg = JText::sprintf('COM_INSTALLER_INSTALL_SUCCESS', JText::_('COM_INSTALLER_TYPE_TYPE_' . strtoupper($package['type'])));
			$result = true;
			$msgType = 'message';
		}
```

**Comment by ReLater** [comment]
From my point of view my code is clearer and it's approved already.
We have already a successful test and I don't want to waste time of valuable testers.
But like always: Take over if you want to and I close here. I don't want to waste too much time with a small change like this.

**Comment by HLeithner** [comment]
I only wait for a second test to merge.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on a40977996924bb0527fc1436e260ce013801e2fe<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24210">issues.joomla.org/tracker/joomla-cms/24210</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24210">issues.joomla.org/tracker/joomla-cms/24210</a>.</sub>

**Comment by HLeithner** [comment]
thx

**Pull request merged**
