### PR TITLE
Add stylesheet version to all css files and replace deprecated stylesheet signatures usage

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/9638 (css part).

### Summary of Changes

This does for css the same that was done in https://github.com/joomla/joomla-cms/pull/12373 for js.

So, this PR replaces all deprecated stylesheets methods signature usage across the CMS.

Also:

- adds stylesheet version to all js files to solve https://github.com/joomla/joomla-cms/pull/9638
- use the api in conditional ie statements

### Testing Instructions

1. Code review.
2. Use latest staging
3. Apply https://github.com/joomla/joomla-cms/pull/12375 and them this patch
4. Navigate in the frontend/backend/installation (several template). Confirm all is working fine and check all external css files are loaded and with media version

### Documentation Changes Required

None.

### Notes

Unit tests will fail until https://github.com/joomla/joomla-cms/pull/12375 is merged.

### CODE REVIEW

**Comment by roland-d** [comment]
@andrepereiradasilva Travis still doesn't like you ;)

**Comment by andrepereiradasilva** [comment]
> ### Notes
> 
> Unit tests will fail until #12375 is merged.

:wink:

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 519d0cec3aae2ac19d11833358b77b1012189341<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12720">issues.joomla.org/tracker/joomla-cms/12720</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@brianteeman just update brandy since the other pr is now merged to fix the unit tests. Please Mark again as tested with success. No changes.

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on ae520ae143583b8eaa506af2c8df56d8079d16c7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12720">issues.joomla.org/tracker/joomla-cms/12720</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on ae520ae143583b8eaa506af2c8df56d8079d16c7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12720">issues.joomla.org/tracker/joomla-cms/12720</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12720">issues.joomla.org/tracker/joomla-cms/12720</a>.</sub>

**Pull request merged**
