### PR TITLE
[4] Remove PHP from a plain text file

### PR DESCRIPTION
**Pull request by PhilETaylor**
Code review.

There is no point having a PHP comment in a file without a PHP extension, it will never be parsed and doesn't ever run.

### CODE REVIEW

**Comment by brianteeman** [comment]
> There is no point having a PHP comment in a file without a PHP extension, it will never be parsed and doesn't ever run.

No point indeed for it being inside php. But deleting the copyright itself is not a solution. That has to remain.

**Comment by brianteeman** [comment]
I have tested this item :red_circle: unsuccessfully on 7d5f994c83e1d75232d36fd3be161c25a5658166<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35138">issues.joomla.org/tracker/joomla-cms/35138</a>.</sub>

**Comment by PhilETaylor** [comment]
I disagree. There is no copyright statement in  README.md README.txt 

There is no need for a copyright statement in this file. Just like there is no need for yet another LICENSE.txt file in the installation that you put there.

**Comment by brianteeman** [comment]
agree to disagree - really not worth spending any time on it

**Comment by PhilETaylor** [comment]
so yet another PR destined to be left open for another decade. Pathetic.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 8f8bbc55017d866929890105d323cad10b34a2fb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35138">issues.joomla.org/tracker/joomla-cms/35138</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 8f8bbc55017d866929890105d323cad10b34a2fb<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35138">issues.joomla.org/tracker/joomla-cms/35138</a>.</sub>

**Comment by jwaisner** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35138">issues.joomla.org/tracker/joomla-cms/35138</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
