### PR TITLE
Remove show_tag_num_items

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #11478

Redo to resolve merge conflicts.

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 88b0629fc7582c813f9b5e2fc3e8c8ea83422062<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13013">issues.joomla.org/tracker/joomla-cms/13013</a>.</sub>

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on 88b0629fc7582c813f9b5e2fc3e8c8ea83422062<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13013">issues.joomla.org/tracker/joomla-cms/13013</a>.</sub>

**Comment by brianteeman** [comment]
Thanks for retesting - back to RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13013">issues.joomla.org/tracker/joomla-cms/13013</a>.</sub>

**Comment by wilsonge** [comment]
Can you fix the conflicts please :)

**Comment by brianteeman** [comment]
Grrh not again!!!

**Comment by brianteeman** [comment]
@wilsonge I have tried to resolve the conflict - pretty sure I did everything right but it still thinks there is a conflict :( 
Can you take a look please as I really dont want to redo this PR for a THIRD time

**Comment by wilsonge** [comment]
Done - looks  like someone already removed it from the com_tags extension

**Comment by brianteeman** [comment]
Ah maybe that was Andre in his options cleanup - thanks

**Pull request merged**
