### PR TITLE
[4.0] Site title Cassiopeia

### PR DESCRIPTION
**Pull request by brianteeman**
It is not clear that you can have either a logo or text. Hopefully this makes it a little clearer

image

### CODE REVIEW

**Comment by toivo** [comment]
I have tested this item :white_check_mark: successfully on a6f65a9d94013960be05cbc2abbb2c44bad0097a<br /><br />Tested successfully in Beta6-dev of 29 November.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31531">issues.joomla.org/tracker/joomla-cms/31531</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on a6f65a9d94013960be05cbc2abbb2c44bad0097a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31531">issues.joomla.org/tracker/joomla-cms/31531</a>.</sub>

**Comment by infograf768** [comment]
rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31531">issues.joomla.org/tracker/joomla-cms/31531</a>.</sub>

**Comment by infograf768** [comment]
tks

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
