### PR TITLE
SQL - improve  CAST  with CAST('field' AS CHAR(n))

### PR DESCRIPTION
**Pull request by alikon**
as per comment on  #12348 see https://github.com/joomla/joomla-cms/pull/12348#pullrequestreview-3409261
### Summary of Changes
- implemented missing feature for  SQL CAST `CAST('field' AS CHAR(n))`
- moved the `castAsChar()` from query.php to each driver
### Testing Instructions

this kind of CAST works now
`$query->select($query->castAsChar('field', 40))`
`$query->select($query->castAsChar('field'))`
### Documentation Changes Required

we can use this type of SQL too
`$query->select($query->castAsChar('field', 40))`

### CODE REVIEW

**Comment by mbabker** [comment]
You need to keep the base function in `JDatabaseQuery` otherwise if it's used with a subclass not implementing the method you'll end up with a fatal error.  Otherwise aside from the CI failures seems fine to me.

**Comment by alikon** [comment]
restored `castAsChar()` in `JDatabaseQuery` as suggested

**Comment by waader** [comment]
I have tested this item :white_check_mark: successfully on c5711ba755bc674e4aff0220b8b2fdb6e2e9d766<br /><br />Tested with mysql and postgresql. Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12417">issues.joomla.org/tracker/joomla-cms/12417</a>.</sub>

**Comment by jeckodevelopment** [comment]
@alikon Nicola, can you please check the conflicting file?
` libraries/joomla/database/query/mysqli.php `

**Comment by alikon** [comment]
conflict fixed

**Comment by waader** [comment]
The mssql implementation is missing here.

**Comment by alikon** [comment]
@waader added the mssql part

**Comment by waader** [comment]
@alikon: is this ready for testing?

**Comment by alikon** [comment]
yes now fixed last comment from @csthomas about mssql

**Comment by waader** [comment]
I have tested this item :white_check_mark: successfully on a3bad12ba7d25bc58ac537fb8ce5c890b1e9a99a<br /><br />Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12417">issues.joomla.org/tracker/joomla-cms/12417</a>.</sub>

**Comment by csthomas** [comment]
I have tested this item :white_check_mark: successfully on a3bad12ba7d25bc58ac537fb8ce5c890b1e9a99a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12417">issues.joomla.org/tracker/joomla-cms/12417</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12417">issues.joomla.org/tracker/joomla-cms/12417</a>.</sub>

**Comment by wilsonge** [comment]
@alikon Would you mind porting this to the framework package so that it can go into the 4.x branch please - I just realised it's gone missing (issue to track this on framework at https://github.com/joomla-framework/database/issues/157)

**Comment by alikon** [comment]
went out of my radar i'll try to add #18961 then too

**Pull request merged**
