### PR TITLE
[4.0] Fix typo in com_associations

### PR DESCRIPTION
**Pull request by joomdonation**
Pull Request for Issue # .

### Summary of Changes
This small pr fixes some small code error in Associations controller. Look like it happens when staging was merged to 4.0-dev

### Testing Instructions
Code review

### CODE REVIEW

**Comment by tonypartridge** [comment]
Please fix drone error.

**Comment by joomdonation** [comment]
The error is not related to this PR. And I don't see a sample of multiple lines comment, so someone has experience with CS please help fixing it.

**Comment by brianteeman** [comment]
@joomdonation see https://developer.joomla.org/coding-standards/inline-code-comments.html Formatting of Comments

**Comment by joomdonation** [comment]
Thanks Brian. Look like I was able to fix it in PR #16329

**Pull request merged**
