### PR TITLE
[40] br not br slash in html5

### PR DESCRIPTION
**Pull request by brianteeman**
The tag is just br in html5 there is no need for the closing slash and it is actually invalid

### CODE REVIEW

**Comment by Twincarb** [comment]
I have tested this item :white_check_mark: successfully on 6e2087de97f7e3b537a832575f8610d1ba45d1b7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15435">issues.joomla.org/tracker/joomla-cms/15435</a>.</sub>

**Review by C-Lodder — APPROVED** [review]

**Comment by RonakParmar** [comment]
I have tested this item :white_check_mark: successfully on 6e2087de97f7e3b537a832575f8610d1ba45d1b7<br /><br />Done code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15435">issues.joomla.org/tracker/joomla-cms/15435</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Comment by laoneo** [comment]
Don't understand why it is invalid?

**Comment by C-Lodder** [comment]
@laoneo it's not invalid. It's optional. I decided yo remove the backslash on all void element in  prevois PR so it's best tk stay consistant

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
