### PR TITLE
Define identifier field

### PR DESCRIPTION
**Pull request by miguelbgouveia**
Pull Request for Issue # .
#### Testing Instructions

Creation of an identifier field property in order to define the table field that store the identifier.
I need to create a plugin to a specific module that have identifier field in table other than id.

### CODE REVIEW

**Comment by miguelbgouveia** [comment]
I was creating an smart search plugin for a specific component.
The problem is that component use a table where the identifier field don't have the 'id' name.
To resolve the problem it will be good if I could specified the field identifier name in cases that the name is other than 'id'.

I just create an pull request with the solution but it don't pass in the CI tool in some php versions.
The pull request is #9202

**Comment by brianteeman** [comment]
Someone else can confirm but looks to me like an issue with the CI tool and not your code @wilsonge @mbabker

**Comment by mbabker** [comment]
Resubmit to staging, 3.5-dev is effectively closed since it was merged into
staging (should be deleted once any PRs still targeting it are handled)

**Comment by miguelbgouveia** [comment]
Ok, thanks for the information. Any other actions needed for this pull be accepted?

**Comment by miguelbgouveia** [comment]
Can I submit it to any other branch?

**Comment by dgt41** [comment]
staging will do

**Comment by brianteeman** [comment]
Sorry I missed that you had submitted to the wrong branch

As @mbabker stated please resubmit to the staging branch - it will then need to be tested/reviewed by others before it is considered to be merged.

Closing as you will be creating a new PR on  the correct branch

**Comment by mbabker** [comment]
Submit it against the staging branch, make sure CI passes (if you changed
something affecting unit tested code the tests shouldn't break, and on
staging the PHP 5.6 run also tests code style compliance), then it just
needs testing & review.

**Pull request closed without merging**
