### PR TITLE
[4.x] Component Permissions description

### PR DESCRIPTION
**Pull request by brianteeman**
Every component that has options has a permissions tab.

All of these tabs begin with the text

>  Permissions for this component unless they are changed for a specific item.

However only a very few components have item level permissions. For those components that do not have item level permissions the information is incorrect and confusing.

This PR removes the description from those components

To test. Go to the item view of a component and see if it has a permissions tab and then check the component options.

These four components should still display the information as they are the only ones with per item permissions.

com_content
com_menus
com_modules
com_scheduler

All other components should not display the information any more.

### Documentation Changes Required
none

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on e128eb3526a321e310dca5d70bfefab34b7fe804<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37875">issues.joomla.org/tracker/joomla-cms/37875</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on e128eb3526a321e310dca5d70bfefab34b7fe804<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37875">issues.joomla.org/tracker/joomla-cms/37875</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37875">issues.joomla.org/tracker/joomla-cms/37875</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
