### PR TITLE
[4][com_finder] undefined variable $f_id

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue # .

### Summary of Changes
use the defined varialble

### Testing Instructions
code review

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 5afce01026d0892c445251d9d1fd09f966ece4e1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38896">issues.joomla.org/tracker/joomla-cms/38896</a>.</sub>

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on 5afce01026d0892c445251d9d1fd09f966ece4e1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38896">issues.joomla.org/tracker/joomla-cms/38896</a>.</sub>

**Comment by Fedik** [comment]
R2C<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38896">issues.joomla.org/tracker/joomla-cms/38896</a>.</sub>

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
