### PR TITLE
Coding style. PHP constants true, false, and null MUST be in lower case.

### PR DESCRIPTION
**Pull request by marcochirienti**
### Summary of Changes

The PHP keywords MUST be in lower case. The PHP constants true, false, and null MUST be in lower case.

See Joomla Coding Standards: [https://github.com/joomla/coding-standards/blob/master/manual/php.md](https://github.com/joomla/coding-standards/blob/master/manual/php.md)

### Testing Instructions

Code review

### Documentation Changes Required

None

### CODE REVIEW

**Review by andrepereiradasilva — APPROVED** [review]

**Comment by andrepereiradasilva** [comment]
this is fine by code review

there is no travis error here, anyone can restart travis in this PR?

**Comment by brianteeman** [comment]
Restarted travis as requested

**Comment by andrepereiradasilva** [comment]
thanks

**Comment by zero-24** [comment]
@marcochirienti we need to take out the changes in `administrator/components/com_joomlaupdate/restore.php` file as this is 3rd Party code other changes looks good from here.

**Comment by marcochirienti** [comment]
Ok, i'm sorry, but i'm new to this world. Should i remove changes to this file and send a new pull request?

**Comment by zero-24** [comment]
see here: https://github.com/marcochirienti/joomla-cms/pull/1

**Comment by yvesh** [comment]
I have tested this item :white_check_mark: successfully on 920e697064e4980bc47b544bec88113d9057e3da<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13010">issues.joomla.org/tracker/joomla-cms/13010</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 920e697064e4980bc47b544bec88113d9057e3da<br /><br />on code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13010">issues.joomla.org/tracker/joomla-cms/13010</a>.</sub>

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on 920e697064e4980bc47b544bec88113d9057e3da<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13010">issues.joomla.org/tracker/joomla-cms/13010</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13010">issues.joomla.org/tracker/joomla-cms/13010</a>.</sub>

**Comment by zero-24** [comment]
Thanks merged

**Pull request merged**
