### PR TITLE
[4.0] Select Client/Administrator filter [a11y]

### PR DESCRIPTION
**Pull request by brianteeman**
The labels for some of these fields was missing or not being used due to the layout. In addition the labels have been standardised to "Select Client" which is more in keeping with other similar labels.

To test you will need to apply the patch and then view the source code to see that all these filters have an sr-only label of Select Client

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 57562c908674eb2eefe09a4feeb9b56a860e8cc5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27099">issues.joomla.org/tracker/joomla-cms/27099</a>.</sub>

**Comment by wilsonge** [comment]
If we're standardising everything to `Select Client` doesn't it make more sense to normalise them to a global language string rather than setting them per component here

**Comment by brianteeman** [comment]
It can be if you want

**Comment by wilsonge** [comment]
Should keep translators lives a bit easier than 3 dupes. It's not totally outlandish to think it might have uses in fields etc too for frontend/backend form editing etc. so yeah lets go with it

**Comment by brianteeman** [comment]
@wilsonge done

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 5c5db7e7a3fba9e93b7663c1469ef1d6944c5d5e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27099">issues.joomla.org/tracker/joomla-cms/27099</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 5c5db7e7a3fba9e93b7663c1469ef1d6944c5d5e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27099">issues.joomla.org/tracker/joomla-cms/27099</a>.</sub>

**Comment by infograf768** [comment]
rtc
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27099">issues.joomla.org/tracker/joomla-cms/27099</a>.</sub>

**Comment by infograf768** [comment]
Apparently this branch is out-of-date but I can't update it.

**Comment by wilsonge** [comment]
@brianteeman can you fix conflicts please

**Comment by brianteeman** [comment]
conflicts resolved

**Comment by infograf768** [comment]
This works but I still can't update the branch and therefore can't merge this PR.

**Comment by brianteeman** [comment]
1. Unless there are conflicts there is no need to update a branch before you can merge it
2. I deliberately set my branch so that it could not be updated by others

**Comment by infograf768** [comment]
Then "ordinary" maintainers are not able to merge your stuff as "Squash and Merge" is not available.
Screen Shot 2019-11-25 at 11 41 38

**Comment by brianteeman** [comment]
so be it

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
