### PR TITLE
Links to buttons

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue # .

### Summary of Changes
This replaces link tags that look and act like buttons with actual buttons. See #20682 for details.

### Testing Instructions
Code review.

### CODE REVIEW

**Comment by brianteeman** [comment]
LGTM

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on b67cf1d309717878b70ae140085152412c6dd0b9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22546">issues.joomla.org/tracker/joomla-cms/22546</a>.</sub>

**Comment by zwiastunsw** [comment]
I have tested this item :white_check_mark: successfully on b67cf1d309717878b70ae140085152412c6dd0b9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22546">issues.joomla.org/tracker/joomla-cms/22546</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22546">issues.joomla.org/tracker/joomla-cms/22546</a>.</sub>

**Pull request merged**
