### PR TITLE
Tags menu items

### PR DESCRIPTION
**Pull request by brianteeman**
Updates the name of the various tags component menu types to match the codestyle

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on f055044788002d531fe27fa665d2c4af35274633<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26739">issues.joomla.org/tracker/joomla-cms/26739</a>.</sub>

**Comment by TobsBobs** [comment]
I have tested this item :white_check_mark: successfully on f055044788002d531fe27fa665d2c4af35274633<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26739">issues.joomla.org/tracker/joomla-cms/26739</a>.</sub>

**Comment by SharkyKZ** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26739">issues.joomla.org/tracker/joomla-cms/26739</a>.</sub>

**Comment by HLeithner** [comment]
thx

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
