### PR TITLE
TinyMCE builder: make sure the value exist, and cache the layout data

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue #13886 .

### Summary of Changes
Make sure the value exist, and cache the layout data

### Testing Instructions
please see #13886

### Documentation Changes Required
nope

### CODE REVIEW

**Review by sevenstudio — APPROVED** [review]

**Comment by sevenstudio** [comment]
I have tested this item :white_check_mark: successfully on df4fb734772f693b3061208c655b48b61ef3aaaa<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13901">issues.joomla.org/tracker/joomla-cms/13901</a>.</sub>

**Comment by JoshuaLewis** [comment]
I couldn't replicate this issue. Does it only occur for sites upgraded from J3.5 to 3.6? Tested with a fresh install of J3.6 alpha 2 with the latest version of com_patchtester, and PHP 7.1 and PHP 7.0.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13901">issues.joomla.org/tracker/joomla-cms/13901</a>.</sub>

**Comment by sevenstudio** [comment]
@JoshuaLewis the issue appears after upgrading to **3.7.0 (beta 1)**, it is related to changes (new features) in the TinyMCE plugin in upcoming 3.7.0 version. Please test after upgrade to 3.7.0 beta 1.

**Comment by JoshuaLewis** [comment]
I have tested this item :white_check_mark: successfully on df4fb734772f693b3061208c655b48b61ef3aaaa<br /><br />Hopefully RTC? It's an important issue.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13901">issues.joomla.org/tracker/joomla-cms/13901</a>.</sub>

**Comment by sevenstudio** [comment]
@Fedik Thank you for providing fix here, and btw. thanks for the work done with subform field!

**Pull request merged**
