### PR TITLE
[3] backport of #35362

### PR DESCRIPTION
**Pull request by alikon**
### Summary of Changes
 clear the order 

### Testing Instructions

see #35362

### CODE REVIEW

**Comment by richard67** [comment]
@alikon Same as it was with the other PR at the beginning: Please change the comment in this line here

https://github.com/joomla/joomla-cms/blob/5b7b2b0ae8175222950d8862bba621df31330b75/libraries/src/MVC/Model/BaseDatabaseModel.php#L359

to `// Remove the limit, offset and order parts if it's a \JDatabaseQuery object`

I would have made a suggestion on GitHub but that doesn't work if the place of the suggestion in code is too far away from the code changed in a PR.

**Review by bembelimen — APPROVED** [review]

**Review by richard67 — APPROVED** [review]

**Comment by bembelimen** [comment]
I have tested this item :white_check_mark: successfully on 41bbe97440197eb0670268d18c77ad6ea9d4a75e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35383">issues.joomla.org/tracker/joomla-cms/35383</a>.</sub>

**Comment by carcam** [comment]
I have tested this item :red_circle: unsuccessfully on 41bbe97440197eb0670268d18c77ad6ea9d4a75e<br /><br />I have applied instructions provided and the "order by" keeps showing:

SELECT l.link_id, l.object,SUM(m.weight) AS ordering
FROM vuu2c_finder_links AS l
INNER JOIN `vuu2c_finder_links_terms` AS m ON m.link_id = l.link_id
WHERE `l`.`access` IN (:preparedArray1,:preparedArray2,:preparedArray3) AND l.state = 1 AND l.published = 1 AND (l.publish_start_date IS NULL OR l.publish_start_date <= '2021-09-17 15:45:00') AND (l.publish_end_date IS NULL OR l.publish_end_date >= '2021-09-17 15:45:00') AND l.language IN ('en-GB', '*') AND m.term_id IN (1836)
GROUP BY l.link_id,l.object
HAVING SUM(CASE WHEN m.term_id IN (1836) THEN 1 ELSE 0 END) > 0
ORDER BY ordering DESC LIMIT 20<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/35383">issues.joomla.org/tracker/joomla-cms/35383</a>.</sub>

**Comment by richard67** [comment]
> 
> 
> I have tested this item 🔴 unsuccessfully on [41bbe97](https://github.com/joomla/joomla-cms/commit/41bbe97440197eb0670268d18c77ad6ea9d4a75e)
> 
> I have applied instructions provided and the "order by" keeps showing:
> 
> SELECT l.link_id, l.object,SUM(m.weight) AS ordering
> FROM vuu2c_finder_links AS l
> INNER JOIN `vuu2c_finder_links_terms` AS m ON m.link_id = l.link_id
> WHERE `l`.`access` IN (:preparedArray1,:preparedArray2,:preparedArray3) AND l.state = 1 AND l.published = 1 AND (l.publish_start_date IS NULL OR l.publish_start_date <= '2021-09-17 15:45:00') AND (l.publish_end_date IS NULL OR l.publish_end_date >= '2021-09-17 15:45:00') AND l.language IN ('en-GB', '*') AND m.term_id IN (1836)
> GROUP BY l.link_id,l.object
> HAVING SUM(CASE WHEN m.term_id IN (1836) THEN 1 ELSE 0 END) > 0
> ORDER BY ordering DESC LIMIT 20
> This comment was created with the [J!Tracker Application](https://github.com/joomla/jissues) at [issues.joomla.org/tracker/joomla-cms/35383](https://issues.joomla.org/tracker/joomla-cms/35383).

@carcam I think you have mixed up the queries. There are 2 identical ones, one for getting the list items and another second one for getting the count. This PR here modifies that for the count. I.e. before ther PR there are 2 queries with ordering, and with this PR there is only one. You have to check that one which does not have the LIMIT clause. Please revert your wrong test result. Thanks in advance.

**Comment by richard67** [comment]
@carcam It might be that you are right but the query which you have pasted in your test result is a query from Joomla 4. It cannot be used here in Joomla 3 in this way with prepared statement.

**Comment by zero-24** [comment]
I can confirm that this code does not seem to get triggered by smart search while i agree that we should clear the order thing in generally too. Will merge this based on the test by @bembelimen and @richard67 's and mine review.

**Pull request merged**
