### PR TITLE
[com_privacy] - version 3.9.0

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue #22144  .

### Summary of Changes
component version from 3.0.0 to 3.9.0

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 6ed98671adb3ae57ca9acc4f52fe09b344814b33<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22145">issues.joomla.org/tracker/joomla-cms/22145</a>.</sub>

**Comment by ggppdk** [comment]
I have tested this item :white_check_mark: successfully on 6ed98671adb3ae57ca9acc4f52fe09b344814b33<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22145">issues.joomla.org/tracker/joomla-cms/22145</a>.</sub>

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on 6ed98671adb3ae57ca9acc4f52fe09b344814b33<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22145">issues.joomla.org/tracker/joomla-cms/22145</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/22145">issues.joomla.org/tracker/joomla-cms/22145</a>.</sub>

**Pull request merged**
