### PR TITLE
New installer plugins: remove the dot in the plugin name and other language review

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
#### Summary of Changes

Small changes in the new "Install from URL or Path Folder" plugin language file.
- Removes the dot in the plugin name (for consistency with all others)
- Add the plugin name in the main language file 
- Alpha order the language strings
#### Testing Instructions

Code review.

### CODE REVIEW

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on 9746c0c15622b0c4c0f496b95fb855e62c65c0ee<br /><br />Looks good to me @brianteeman can you have a final look?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10299">issues.joomla.org/joomla-cms/10299</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 9746c0c15622b0c4c0f496b95fb855e62c65c0ee<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10299">issues.joomla.org/joomla-cms/10299</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10299">issues.joomla.org/joomla-cms/10299</a>.</sub>

**Comment by andrepereiradasilva** [comment]
thanks for testing, comments and merging!

**Pull request merged**
