### PR TITLE
Added Cypress test for categories of banners , contacts and content

### PR DESCRIPTION
**Pull request by rajputanuj31**
Added Cypress test for categories of banners , contacts and content.

### CODE REVIEW

**Comment by laoneo** [comment]
Can you change the describe texts that they look the same as https://github.com/joomla/joomla-cms/blob/4.4-dev/tests/System/integration/api/com_newsfeed/Categories.cy.js#L1?

**Comment by rajputanuj31** [comment]
> Thanks for the pr. Can you change the describe texts that they look the same as https://github.com/joomla/joomla-cms/blob/4.4-dev/tests/System/integration/api/com_newsfeed/Categories.cy.js#L1?

Done.

**Comment by rajputanuj31** [comment]
Hey @laoneo can you please check why one test is failing. it is running perfectly in my local system.

**Comment by laoneo** [comment]
Run the install test first and then this one. You will figure out what the problem is then.

**Comment by laoneo** [comment]
The problem was that there are default categories created during installation (with the title 'Uncategorized') where data[0] is returning that one instead the newly created one.

**Comment by laoneo** [comment]
Finally, thanks!

**Comment by rajputanuj31** [comment]
> The problem was that there are default categories created during installation (with the title 'Uncategorized') where data[0] is returning that one instead the newly created one.

Ok understood. I spent a lot of time to understand why test is failing but fail to get the reason.
Thanks a lot for this.

**Comment by laoneo** [comment]
In cypress when you click on the actual request, then it prints the response to the browser console. Like that you can see quickly what comes back from the API:
image

**Pull request merged**
