### PR TITLE
Preventing slashes added by bootstrap tab if lang string contains single quote

### PR DESCRIPTION
**Pull request by infograf768**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/11400

The issue comes from the fact that json_encode was added in https://github.com/joomla/joomla-cms/pull/3922 in \layouts\libraries\cms\html\bootstrap\addtabscript.php

@vinespie 
Please add the test instructions.

### CODE REVIEW

**Comment by vinespie** [comment]
#### Testing Instructions

1- Go to Administrator -> Extensions -> Langages -> Overrides
2016-08-03 09_53_49-control panel - joomla36 - administration

2- In filter, select "Administrator" language
3- Click "new" and add language override with single quote for :
	
	COM_MENUS_PAGE_OPTIONS_LABEL
2016-08-03 10_41_09-languages_ edit override - joomla36 - administration

	PLG_DEBUG_LANGUAGE_FIELDSET_LABEL
2016-08-03 10_01_25-languages_ edit override - joomla36 - administration

	COM_ADMIN_USER_SETTINGS_FIELDSET_LABEL
2016-08-03 10_03_10-languages_ edit override - joomla36 - administration
	
5- Go to Administrator -> Menus -> Main Menu -> Add New Menu Item
2016-08-03 10_08_57-menus_ items main menu - joomla36 - administration

6- Tab contains slash before single quote
2016-08-03 10_09_47-menus_ new item - joomla36 - administration

7- Go to Administrator -> Extensions -> Plugins -> Edit "System - Debug"
8- Tab contains slash before single quote
2016-08-03 10_13_43-plugins_ system - debug - joomla36 - administration

9- Got to Administrator -> Edit your user acount
2016-08-03 10_11_33-menus_ items main menu - joomla36 - administration

10- Tab contains slash before single quote
2016-08-03 10_23_11-my profile - joomla36 - administration

11- Apply patch
12- Return to points 5 7 9 and tabs not have slash before single quote
13- Test finished

**Comment by infograf768** [comment]
@brianteeman @ggppdk 
We need this in 3.6.1. Thank you for testing.

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on bedb57aed3f15b5fd663061f56e3576d935f25e7<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/11409">issues.joomla.org/joomla-cms/11409</a>.</sub>

**Comment by wilsonge** [comment]
@vinespie can i confirm you tested this successfully?

**Comment by infograf768** [comment]
@wilsonge
In fact I just used here the code proposed by @vinespie in https://github.com/vinespie/joomla-cms/commit/34f9ff9c938252131bb0f79c0a30b6dc59cfd98b and tested myself. So either he has or I have. ☺ so we do have a second test

**Pull request merged**
