### PR TITLE
[4.0] Fix sendmail token error

### PR DESCRIPTION
**Pull request by C-Lodder**
Pull Request for Issue #18596

### Summary of Changes

Fix the error due to the token check always returning false

### Testing Instructions

Attempt to submit a test mail via com_config

### CODE REVIEW

**Comment by C-Lodder** [comment]
@mbabker @zero-24  is this right?

**Comment by dgrammatiko** [comment]
@C-Lodder that shouldn't be required in J4 as we have the csrf token generated automatically

**Comment by C-Lodder** [comment]
@dgt41 - yup, I know the token gets generated automatically, but `\JSession::checkToken('get')` doesn't **get** that token for some reason.

**Comment by mbabker** [comment]
If it's not part of the query string that would cause the check (which is being told to check GET variables) to fail.  So where's the automatic CSRF token being added to?  And is the request it's making even a GET request?

**Comment by C-Lodder** [comment]
@mbabker - well not automatically, but it's added here: https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_config/tmpl/application/default.php#L115

**Comment by andrepereiradasilva** [comment]
hi, i have not followed this new token "thing", but since this uses a Joomla.Request ajax js, don't you need to add in https://github.com/joomla/joomla-cms/blob/4.0-dev/administrator/components/com_config/tmpl/application/default_mail.php the

```php
Joomla\CMS\Factory::getDocument()->addScriptOptions('csrf.token', Joomla\CMS\Session\Session::getFormToken());
```
or something like that?
see https://github.com/dneukirchen/joomla-cms/blob/4.0-dev/media/system/js/core.js#L822

**Review by tonypartridge — COMMENTED** [review]
Quick question.. What happens when caching is enabled... does this form get cached and thus the Token too??

**Comment by asika32764** [comment]
You need a `JHtml::_('jquery.token')` to make sure CSRF auto injected when using jQuery ajax

See 3.x branch: https://github.com/joomla/joomla-cms/blob/staging/administrator/components/com_config/view/application/tmpl/default_mail.php#L12

And https://github.com/dneukirchen/joomla-cms/blob/4.0-dev/libraries/cms/html/jquery.php#L133-L158

Reference to CSRF relative PR: https://github.com/joomla/joomla-cms/pull/14952

**Comment by asika32764** [comment]
`sendtestmail.js` uses jQuery Ajax now not `Joomla.Request`

**Comment by andrepereiradasilva** [comment]
No. afaik in 4.0 the usage of jquery on the Core is being removed to improve js render time and bytes transfered
https://github.com/joomla/joomla-cms/blob/4.0-dev/media/system/js/fields/sendtestmail.js#L30

The cache thing is a good point there are cache workaround for the form session input but i don't think they exist for this new method. See https://github.com/joomla/joomla-cms/blob/4.0-dev/libraries/src/Cache/Cache.php#L529

**Comment by asika32764** [comment]
Seems not only one reasons. I fixed it in https://github.com/joomla/joomla-cms/pull/18821

**Pull request closed without merging**
