### PR TITLE
Added Toggle Unpublished Modules in Menu item edit view

### PR DESCRIPTION
**Pull request by cheiff**
Pull Request for a new feature.
#### Summary of Changes

Added a button to toggle unpublished modules in menu item edit view, similar to toggle unassigned modules.
#### Testing Instructions

From Administrator panel, select a menu (e.g. Main Menu), select a menu item (e.g. Home). In the Module Assignment tab, there is a new column "Published" and a new button that allows to toggle the modules based on their status (published/unpublished).
If there are some modules and some are unpublished, clicking the button will hide them.
#### Comments

I let the label colour for "Trashed" as default (gray) after editing a module in order to be easily recognizable. On reloading, trashed modules will disappear from the view, so it is a temporary colour.

I put the buttons next to each other in order to not take up more space. That is the reason for a new layout file for the fieldset. If there is a better way or I should let the buttons one on top of the other, just let me know.

One idiomatic question: I left the language strings same as for toggle unassigned menus, but, shouldn't it be "Shows or hides modules" instead of "Shows or hide modules"?

Thanks, regards

### CODE REVIEW

**Comment by cheiff** [comment]
Two screenshots showing what the PR does

togglebutton1
togglebutton2

**Comment by infograf768** [comment]
We have in core en-GB
93 occurences of "Show or hide etc."
One occurence of "Shows or hide etc." 
`COM_MENUS_ITEM_FIELD_HIDE_UNASSIGNED_DESC="Shows or hide modules unassigned to this menu item."`
One occurence of "Shows or hides etc."
`COM_TAGS_SHOW_ITEM_DESCRIPTION_DESC="Shows or hides the description for each tag listed."`
@brianteeman ??

**Comment by brianteeman** [comment]
@infograf768 it should be Show or hide

On 26 February 2016 at 07:32, infograf768 <notifications@github.com> wrote:

> We have in core en-GB
> 93 occurences of "Show or hide etc."
> One occurence of "Shows or hide etc."
> COM_MENUS_ITEM_FIELD_HIDE_UNASSIGNED_DESC="Shows or hide modules
> unassigned to this menu item."
> One occurence of "Shows or hides etc."
> COM_TAGS_SHOW_ITEM_DESCRIPTION_DESC="Shows or hides the description for
> each tag listed."
> @brianteeman <https://github.com/brianteeman> ??
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/9216#issuecomment-189147093>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by infograf768** [comment]
@brianteeman
Can you make a PR for the 2 wrong strings?

**Comment by brianteeman** [comment]
yes I will do that

On 26 February 2016 at 08:17, infograf768 <notifications@github.com> wrote:

> @brianteeman <https://github.com/brianteeman>
> Can you make a PR for the 2 wrong strings?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/9216#issuecomment-189157628>.
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by cheiff** [comment]
I'll correct mine, then. 
Thanks, regards

**Comment by cheiff** [comment]
There it is. Thank you.
Regards

**Comment by bullet64** [comment]
I have tested this item successfully.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 525cb786fee72b0dbb62f560b0a680c339d1366e<br /><br />Works as described in test instructions.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9216">issues.joomla.org/joomla-cms/9216</a>.</sub>

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on 525cb786fee72b0dbb62f560b0a680c339d1366e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9216">issues.joomla.org/joomla-cms/9216</a>.</sub>

**Comment by brianteeman** [comment]
RTC - thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9216">issues.joomla.org/joomla-cms/9216</a>.</sub>

**Comment by cheiff** [comment]
Thank you! :smile:

**Comment by rdeutz** [comment]
new feature has to go into 3.6 and not into 3.5.x

**Comment by brianteeman** [comment]
oops - i didnt consider it a new feature but thats fine

**Comment by zero-24** [comment]
if there is the decision that this is a new feature can we have a `New feature` label here than? @rdeutz

**Comment by rdeutz** [comment]
@zero-24 your wish is my command :-)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9216">issues.joomla.org/joomla-cms/9216</a>.</sub>

**Comment by zero-24** [comment]
:+1: Thanks ;)

**Pull request merged**
