### PR TITLE
SEF for feeds

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/7437.
#### Summary of Changes

This PR adds the SEF plugin conversion to rss/atom feeds.
###### Before

image
###### After

image
#### Testing Instructions
1. Use latest staging
2. Create a Category List or blog menu item to list a category
3. Edit one of the articles of that category and add some internal links (+Article in editor) and images.
4. Ativate SEF system plugin and SEF in global config
5. Go to frontend to the category page (created at 1). Check all internal URL are converted to SEF URL
6. Add `?type=rss&format=feed` to the category URL to view the feed.
7. Notice the URL are not SEF in the feed.
8. Apply patch
9. Repeat step 5 and 6, notice the feed internal URL are now converted to SEF URL.
10. Do a general test to check if the SEF URL are working properly in the site and nothing is broken.
11. Test also with different combinations of SEF in global config and with/without multilanguage (language filter plugin).

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on acc297d24a65ff522c77c943d53a3db361dec67e<br /><br />tested sef and non sef and it works as described<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10442">issues.joomla.org/joomla-cms/10442</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on acc297d24a65ff522c77c943d53a3db361dec67e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10442">issues.joomla.org/joomla-cms/10442</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@brianteeman RTC here?

**Comment by wojsmol** [comment]
@andrepereiradasilva github see conflicts here.

**Comment by andrepereiradasilva** [comment]
right, you're code style review. Will fix them.

**Comment by andrepereiradasilva** [comment]
conflicts fixed (jut added two lines of spaces before and after the foreach cycle)

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 10aa5e357940c526b195d2f583613ea1d36d6677<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10442">issues.joomla.org/joomla-cms/10442</a>.</sub>

**Comment by brianteeman** [comment]
Setting RTC based on tests before last update which was cometic only<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10442">issues.joomla.org/joomla-cms/10442</a>.</sub>

**Comment by roland-d** [comment]
Thanks everybody

**Pull request merged**
