### PR TITLE
[4.0] Privavcy dashboard module display

### PR DESCRIPTION
**Pull request by infograf768**
Replaces https://github.com/joomla/joomla-cms/pull/24573 as com_privacy structure is now namespaced

### Summary of Changes
Adapt mod_privacy_dashboard to j4 as was done here: #24563

### Before patch
Screen Shot 2019-04-13 at 10 28 36
### After patch
Screen Shot 2019-04-13 at 10 15 55

@alikon @ghazal

### CODE REVIEW

**Comment by brianteeman** [comment]
The Total Request and Active Requests should not be part of the table. They are not related to anything in the table headers. If you read down the columns you can see that the data here is nothing to do with the rest of the data in the columns.

As this is not related to the table it should be outside of the table and as it is not tabular data it can simply be a new div

**Comment by brianteeman** [comment]
There is no need for the data-original-title attribute either as you have removed the class=hasTooltip

**Comment by infograf768** [comment]
`<div>` would not work. BTW, this is what we have in 3.x:
Screen Shot 2019-04-16 at 05 54 29

To avoid alignment with the headers I have added colspans to keep things together and centering the total and active requests to get this:

Screen Shot 2019-04-16 at 05 54 47

**Comment by brianteeman** [comment]
It is 2019. Please do not misuse tables for display purposes

**Comment by infograf768** [comment]
You know better, as usual. Then make the patch yourself.

**Comment by brianteeman** [comment]
Thank you for your kind words

**Pull request closed without merging**
