### PR TITLE
Add missing period

### PR DESCRIPTION
**Pull request by brianteeman**
Simple PR to add a period (full stop) to the end of the string

COM_INSTALLER_MSG_LANGUAGES_TRY_LATER="Try again later or <a href="_QQ_"https://community.joomla.org/translations/joomla-3-translations.html"_QQ_">contact the language team coordinator</a>."

### CODE REVIEW

**Comment by zero-24** [comment]
RTC for 3.6.4 Thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12356">issues.joomla.org/tracker/joomla-cms/12356</a>.</sub>

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on bde18496c925925706d7079d5bcc0951947bdd0c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12356">issues.joomla.org/tracker/joomla-cms/12356</a>.</sub>

**Comment by brianteeman** [comment]
Milestone changed to 3.7 as it is now not planned to have a 3.6.4 release

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
