### PR TITLE
[4.0] Missing string

### PR DESCRIPTION
**Pull request by brianteeman**
Pr for #27025

### Testing Instructions
Install multilingual
Go to Content > Categories
Edit Uncategorised
Click Associations button

### CODE REVIEW

**Comment by Quy** [comment]
Before: `Articles: Edit Category` 
After the alert: `Edit Category`

**Comment by brianteeman** [comment]
ah - I was just working from the screenshot will update soon

**Comment by brianteeman** [comment]
I have made the change - but - I think you will find that Add Category is also 

> Before: Articles: AddCategory
After the alert: Add Category

**Comment by Quy** [comment]
It is now `$s: Edit Category`. Changed `$s` to `%s`, but still an issue.

**Comment by brianteeman** [comment]
sorry - should work now but please check the Add

**Comment by Quy** [comment]
> Warning: sprintf(): Too few arguments in \libraries\src\Language\Text.php on line 315

**Comment by brianteeman** [comment]
Sorry I am going to revert the last changes back to the original one. I am sure if you check the Add category you will see the same "issue" with before/after

**Comment by infograf768** [comment]
Although we do need that string indeed when a 3rd party component does not have the "normal" string AND I agree with that patch, we should do better than that for core components as the issue is due to an incomplete redirect.

I looked at the urls produced
When first editing the category, we have
`administrator/index.php?option=com_categories&view=category&layout=edit&id=2&extension=com_content` and we get a nice title

but after reload because Associations could not be performed, we have
`administrator/index.php?option=com_categories&view=category&layout=edit&id=2com_content` and we get the "COM_CATEGORIES_CATEGORY_BASE_etc"

This is due to an error in the AdminModel.php redirects in the `editAssociations($data)` method.
Line 1659 on should be
```
			$extension       = $app->input->get('extension', 'com_content');
			$this->typeAlias = $extension . '.category';
			$extension       = '&extension=' . $extension;
```
and not only
```
			$extension       = $app->input->get('extension', 'com_content');
			$this->typeAlias = $extension . '.category';
```

Will make patch now.

**Comment by infograf768** [comment]
See https://github.com/joomla/joomla-cms/pull/27031

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 9e1ca61cada02a75ec74b3cf3c620c39a03dbb4a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27029">issues.joomla.org/tracker/joomla-cms/27029</a>.</sub>

**Comment by infograf768** [comment]
(Note: looks like we have the same issue in 3.x)

**Comment by infograf768** [comment]
Obvious missing string. Tks.

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
