### PR TITLE
[4.0] fix alpha ordering

### PR DESCRIPTION
**Pull request by hardik-codes**
This PR fixes alpha ordering in ``` administrator/language/en-GB/en-GB.com_templates.ini```

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 61b0d477371b4d4527edc1c4169f993da1190bee<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24818">issues.joomla.org/tracker/joomla-cms/24818</a>.</sub>

**Comment by grhcj** [comment]
I have tested this item :white_check_mark: successfully on 61b0d477371b4d4527edc1c4169f993da1190bee<br /><br />On code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24818">issues.joomla.org/tracker/joomla-cms/24818</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/24818">issues.joomla.org/tracker/joomla-cms/24818</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
