### PR TITLE
[4.0] Remove hide default

### PR DESCRIPTION
**Pull request by astridx**
Pull Request for Issue # https://github.com/joomla/joomla-cms/issues/27735 .

### CODE REVIEW

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on 6c10ff60fe84b04a95ddc5c9ce95a165757d6f91<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27746">issues.joomla.org/tracker/joomla-cms/27746</a>.</sub>

**Comment by richard67** [comment]
@astridx @SharkyKZ How shall this be tested? Code review? If real test: Please provide instructions.

**Comment by SharkyKZ** [comment]
@richard67 Code review. Check that the attribute is not used by [Joomla\CMS\Form\Field\MediaField](https://github.com/joomla/joomla-cms/blob/dc35e30c7d80fe52444781bd7675b3751d63d671/libraries/src/Form/Field/MediaField.php).

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 6c10ff60fe84b04a95ddc5c9ce95a165757d6f91<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27746">issues.joomla.org/tracker/joomla-cms/27746</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27746">issues.joomla.org/tracker/joomla-cms/27746</a>.</sub>

**Comment by richard67** [comment]
Ah, I had tested it, too, and just had forgotten to set test result. Was successful.

**Comment by rdeutz** [comment]
After the change the code doesn't makes sense, can be removed entirely

**Comment by richard67** [comment]
@rdeutz Good catch ... haven't noticed that before, but yes, except of the different name the child class does nothing different to the parent now.

**Comment by richard67** [comment]
@rdeutz Adding back RTC was not me, I just commented on GH.

**Comment by richard67** [comment]
Wait, I'll remove it again.

**Comment by rdeutz** [comment]
@astridx can you remove the entire function, please

**Comment by astridx** [comment]
> @rdeutz After the change the code doesn't makes sense, can be removed entirely

You are right. Done

**Comment by richard67** [comment]
@rdeutz Should the now empty child class be marked as deprecated so it can be removed in J5 in favour of using the base class instead?

**Comment by rdeutz** [comment]
No the pluging class needs to be there to be an active pluging

**Comment by richard67** [comment]
I see. Thanks for clarification.

**Comment by richard67** [comment]
@rdeutz I think it needs to change status in the tracker for setting RTC. Shall I do that?

**Comment by rdeutz** [comment]
@richard67 I did already, falling into this always

**Pull request merged**
