### PR TITLE
[com_banners] clients view: Banners counting

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
Pull Request for Improvement.
#### Summary of Changes

This PR adds the counting columns like the ones that exist in categories and menus to the com_banners clients view.

Also does some minor changes in code.
###### Before PR

image
###### After PR

image
#### Testing Instructions
1. Use latest staging and apply this patch
2. Go to Extensions -> Banners -> Clients and create some banner clients
3. Go to Extensions -> Banners -> Banners, create some banners and associate then to the clients created in 2.
4. Go again to Extensions -> Banners -> Clients and test the counting and their links.

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 31ad9c3bef65fd33a78dd5d4582deb3582a31529<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9976">issues.joomla.org/joomla-cms/9976</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :red_circle: unsuccessfully on 31ad9c3bef65fd33a78dd5d4582deb3582a31529<br /><br />I tested with testing data and found following bug:

Because each client only had 1 banner, I copied one banner and saved it with a new name.

Result: One unpublished and one published counted for this client => OK.

Then I published the copied banner.

Result: Still one published only, and zero unpublished => Wrong for published.

Reason: You count the distinct number of client ids, but you have to count the banners with the particular client IDs.

Means you have to change in your query in line 225 the "->select('cid, COUNT(cid) AS count_published')" to ->select('cid, COUNT(DISTINCT cid) AS count_published'), i.e. just remove the "DISTINCT".

Since I am an Oracle SQL expert on guru level you can trust me.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9976">issues.joomla.org/joomla-cms/9976</a>.</sub>

**Comment by richard67** [comment]
@andrepereiradasilva See [https://github.com/andrepereiradasilva/joomla-cms/pull/32](https://github.com/andrepereiradasilva/joomla-cms/pull/32 "https://github.com/andrepereiradasilva/joomla-cms/pull/32")<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9976">issues.joomla.org/joomla-cms/9976</a>.</sub>

**Comment by richard67** [comment]
@brianteeman How did you test this? With 1 banner of each status, so the count always would correctly show 1?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9976">issues.joomla.org/joomla-cms/9976</a>.</sub>

**Comment by andrepereiradasilva** [comment]
ok @richard67 thansk for the hint. solved the question. please retest

**Comment by brianteeman** [comment]
yes - retesting it now

On 19 April 2016 at 10:39, Richard Fath <notifications@github.com> wrote:

> @brianteeman <https://github.com/brianteeman> How did you test this? With
> 1 banner of each status, so the count always would correctly show 1?
> ------------------------------
> This comment was created with the J!Tracker Application
> <https://github.com/joomla/jissues> at issues.joomla.org/joomla-cms/9976
> <https://issues.joomla.org/tracker/joomla-cms/9976>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/9976#issuecomment-211826697>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by andrepereiradasilva** [comment]
ups sorry there seems also be a problem with archived. wait a sec

**Comment by andrepereiradasilva** [comment]
ok archived solved too.

**Comment by richard67** [comment]
@andrepereiradasilva If you find time, please correct the code comments, too: They contain "menu" where it should be "banners", e.g.

> // Get the unpublished menu counts.

I assume this could be also the case for your other recent PRs?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9976">issues.joomla.org/joomla-cms/9976</a>.</sub>

**Comment by richard67** [comment]
Or

> // Get the menu types of menus in the list.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9976">issues.joomla.org/joomla-cms/9976</a>.</sub>

**Comment by andrepereiradasilva** [comment]
That was a copy paste problem. will correct. thanks

no, this is the only PR that use counts.
The other ones are just for adding the max level filters.

**Comment by richard67** [comment]
Ah yes sorry, was confused it seems. Sure, only this one. I will test anyway because is only a comments problem.

**Comment by andrepereiradasilva** [comment]
ok, comments also corrected. sorry for that guys.
please retest.

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on a4501d61b9c407cc478265c2bfac6a6610f06c66<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9976">issues.joomla.org/joomla-cms/9976</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on a4501d61b9c407cc478265c2bfac6a6610f06c66<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9976">issues.joomla.org/joomla-cms/9976</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@richard67 @brianteeman thanks for testing!

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/9976">issues.joomla.org/joomla-cms/9976</a>.</sub>

**Comment by rdeutz** [comment]
technically this is a new feature and it doesn't fix a bug so it has to go into 3.6.0

**Comment by brianteeman** [comment]
It fixes a bug in that the counting is present elsewhere but not in this
component ;)

**Comment by andrepereiradasilva** [comment]
IMHO sometimes a "new feature" is created to solve a logical inconsistency (bug).
But, of course, i leave to you maintainers to decide that.

**Pull request merged**
