### PR TITLE
[4.1] invalid button type

### PR DESCRIPTION
**Pull request by brianteeman**
obvious typo - button only has two t

### CODE REVIEW

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 85c17b17c603036f5214fc9919e022a5e34c8f8b<br /><br />code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38049">issues.joomla.org/tracker/joomla-cms/38049</a>.</sub>

**Comment by laoneo** [comment]
I have tested this item :white_check_mark: successfully on 85c17b17c603036f5214fc9919e022a5e34c8f8b<br /><br />code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38049">issues.joomla.org/tracker/joomla-cms/38049</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38049">issues.joomla.org/tracker/joomla-cms/38049</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
