### PR TITLE
[4.0] Fix 'fixed' toolbar on edit views

### PR DESCRIPTION
**Pull request by C-Lodder**
This is a proper fix for: https://github.com/joomla/joomla-cms/pull/19169

The PR simply moves the logic that sets the `left` position for the toolbar when the sidebar doesn't exists or is collapsed.

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on e49ce5f435865b08c4cda24eb1527d1ace3a1c8e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19212">issues.joomla.org/tracker/joomla-cms/19212</a>.</sub>

**Comment by anuragteapot** [comment]
I have tested this item :white_check_mark: successfully on e49ce5f435865b08c4cda24eb1527d1ace3a1c8e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19212">issues.joomla.org/tracker/joomla-cms/19212</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Comment by anuragteapot** [comment]
@C-Lodder Ok, Thanks for PR.I also think same logic to fix this issue after my first attempt. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19212">issues.joomla.org/tracker/joomla-cms/19212</a>.</sub>

**Pull request merged**
