### PR TITLE
[4.1] Child Templates buttons

### PR DESCRIPTION
**Pull request by brianteeman**
Corrects the code so that the buttons are not double translated.

To test enable language debug

### Before
image

### After
image

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on e1b63a3d562ac931056cf64df3ecf4ee3f20ee19<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36241">issues.joomla.org/tracker/joomla-cms/36241</a>.</sub>

**Comment by dgrammatiko** [comment]
I have tested this item :white_check_mark: successfully on e1b63a3d562ac931056cf64df3ecf4ee3f20ee19<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36241">issues.joomla.org/tracker/joomla-cms/36241</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36241">issues.joomla.org/tracker/joomla-cms/36241</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
