### PR TITLE
Add "No direct access" code

### PR DESCRIPTION
**Pull request by buyanov**
This PR adds the "No direct access" code to the read more layout.

### CODE REVIEW

**Comment by infograf768** [comment]
This readmore.php layout is indeed missing a `defined('_JEXEC') or die;` or `defined('JPATH_BASE') or die;`

But this patch also adds `JHtml::_('bootstrap.framework');`
Please explain why.

**Comment by buyanov** [comment]
My mistake =)
I saw this line
JHtml :: _ ('string.truncate', ($ item-> title), $ params-> get ('readmore_limit'));
and added,
JHtml :: _ ('bootstrap.framework’);

**Comment by zero-24** [comment]
@buyanov I have just send you a Fix. That makes Travis happy and remove the jhtml call.

**Comment by buyanov** [comment]
👍

**Comment by infograf768** [comment]
@buyanov 
You have to merge @zero-24  PR ( https://github.com/buyanov/joomla-cms/pull/1 ) in your PR.

**Comment by xsability** [comment]
I've tested successfully. But I don't unterstand why you have add the following lines.
// No direct access (this I unterstand. That's the Issue)
defined('JPATH_BASE') or die;

// this I don't understand. (why is the following lines required for this issue?)
JHtml::_('bootstrap.framework');

$params = $displayData['params'];
$item = $displayData['item'];<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/7731">issues.joomla.org/joomla-cms/7731</a>.</sub>

**Comment by zero-24** [comment]
@xsability yes. There for i opend the pull here: https://github.com/buyanov/joomla-cms/pull/1 to fix that :smile: if @buyanov merge that PR into this we can go future here.

**Comment by buyanov** [comment]
yeah! :)

**Comment by bertmert** [comment]
I think this PR can be closed.
```
defined('JPATH_BASE') or die;
``` 
is present in 3.5.0beta in /layouts/joomla/content/readmore.php

**Comment by brianteeman** [comment]
Closed as this was resolved in a later PR #8398 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/7731">issues.joomla.org/joomla-cms/7731</a>.</sub>

**Pull request closed without merging**
