### PR TITLE
[4.0] Content History [a11y]

### PR DESCRIPTION
**Pull request by brianteeman**
Accessibility review of the content history component

Fixes multiple things including
 - invalid html markup
 - missing table caption
 - missing table headers
 - missing page title
 - missing landmarks
 - featured information should say current AND it was hidden from the accessibility tree

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on dde91b88d4dbd5208c1862adcd8d3253bbae81cc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27515">issues.joomla.org/tracker/joomla-cms/27515</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on dde91b88d4dbd5208c1862adcd8d3253bbae81cc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27515">issues.joomla.org/tracker/joomla-cms/27515</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27515">issues.joomla.org/tracker/joomla-cms/27515</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
