### PR TITLE
[4.0] Toggle Password Visibility

### PR DESCRIPTION
**Pull request by brianteeman**
Now that the code has been fixed with #27412 I can update the strings to be more meaningful.

The strings for Screen Readers are now "Show Password" and "Hide Password"

### Testing Instructions
Make sure you are the current codebase (ie you have #27412)

Apply this PR

Update the javascript with
npm i 

Inspect the password field in the admin user manager, admin login, site login

The strings for Screen Readers are now "Show Password" and "Hide Password"

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 6220a788a4f59a3aa72894d913f7b4c4e817dfbd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27425">issues.joomla.org/tracker/joomla-cms/27425</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 6220a788a4f59a3aa72894d913f7b4c4e817dfbd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27425">issues.joomla.org/tracker/joomla-cms/27425</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27425">issues.joomla.org/tracker/joomla-cms/27425</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
w00t

**Pull request merged**
