### PR TITLE
Correcting Hathor postinstall message

### PR DESCRIPTION
**Pull request by infograf768**
This corrects 2 issues:
1. The code loading language would never load another language than en-GB (if the string is present) after a successful change of template via the postinstall message 
2. Typo in the language constant `TLP` instead of `TPL` (this will be forwarded to TTs).

### Test instructions
Install staging.
Install French Language https://github.com/infograf768/fr-FR-3.x/releases/download/v3.7.0.1.RC3/fr-FR_joomla_lang_full_3.7.0v1.zip

Switch template to Hathor and admin language to French

Go to administrator/index.php?option=com_postinstall

Click on the button to switch to Isis.
The success message will be in English.

Now patch,  AND replace the string 
`TLP_HATHOR_CHANGED_DEFAULT_TEMPLATE_TO_ISIS="Le style de template administrateur vient d'être changé en '%s'"`
to
`TPL_HATHOR_CHANGED_DEFAULT_TEMPLATE_TO_ISIS="Le style de template administrateur vient d'être changé en '%s'"`
in the /administrator/language/fr-FR/fr-FR.tpl_hathor.ini

switch to Hathor in the template manager and back to postinstall messages.
Click in the button to switch to Isis

You will now get a correct success message
screen shot 2017-04-19 at 16 58 54
correctly:

### CODE REVIEW

**Comment by brianteeman** [comment]
Either we are or we are not in language freeze. That part of this PR should really wait until after the language freeze. It is not necessary to change the string to fix the genuine bug

**Comment by infograf768** [comment]
The problem is that if we do not change it now, we never will and someone will make a PR to change that, and we will be forced to make a new string...

**Comment by infograf768** [comment]
Now, if it is decided so, I have no issue to NEVER correct that constant until Hathor's death and limit the patch to the lang load

**Comment by infograf768** [comment]
and, btw, we were already in lang freeze when this postinstall message was merged...

**Comment by AlexRed** [comment]
I have tested this item :white_check_mark: successfully on f0dc34e31955f225c06dee97a02d6d5733e3e135<br /><br />Patch ok for me.
Please add it on 3.7.0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15414">issues.joomla.org/tracker/joomla-cms/15414</a>.</sub>

**Comment by imanickam** [comment]
I have tested this item :white_check_mark: successfully on f0dc34e31955f225c06dee97a02d6d5733e3e135<br /><br />Tested the patch with multiple languages and it works fine now.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15414">issues.joomla.org/tracker/joomla-cms/15414</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Pull request merged**
