### PR TITLE
[4.0] IIS 7

### PR DESCRIPTION
**Pull request by brianteeman**
The mention of the specific IIS version is confusing as it implies the instructions are only for IIS 7

As we mean all versions of IIS since the release of 7 in 2008 I think it is safe to assume that we can just remove the version number

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 43d9a847dd8a7844c6a52c1b374169a0c55d7a3c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26596">issues.joomla.org/tracker/joomla-cms/26596</a>.</sub>

**Comment by SharkyKZ** [comment]
I have tested this item :white_check_mark: successfully on 43d9a847dd8a7844c6a52c1b374169a0c55d7a3c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26596">issues.joomla.org/tracker/joomla-cms/26596</a>.</sub>

**Comment by SharkyKZ** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26596">issues.joomla.org/tracker/joomla-cms/26596</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
thanks for the quick test and merge

**Pull request merged**
