### PR TITLE
[4.0] Mail Templates SMTP password

### PR DESCRIPTION
**Pull request by brianteeman**
Updates the field to use the new lock option

Pull Request for #31917

To test
1. System -> Mail Templates
2. Options
3. Per Template Mail Settings -> Yes
4. Open any mail template and go to options tab
5. Mailer -> SMTP
6. SMTP Authentication -> Yes
7. Observe SMTP Password field

### Before
image

### After

image

### CODE REVIEW

**Comment by Abernyte-Git** [comment]
I have tested this item :white_check_mark: successfully on b270559c813d7973c2374f2eacf93310a13a2ef9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33727">issues.joomla.org/tracker/joomla-cms/33727</a>.</sub>

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on b270559c813d7973c2374f2eacf93310a13a2ef9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33727">issues.joomla.org/tracker/joomla-cms/33727</a>.</sub>

**Comment by richard67** [comment]
@brianteeman This PR seems to contain an unrelated change on an image `images/banners/banner.jpg`, see https://github.com/joomla/joomla-cms/pull/33727/files .

**Comment by brianteeman** [comment]
oops

**Comment by richard67** [comment]
I've restored the previous test results in the issue tracker because the commit which has invalidated them was just the revert of an unrelated change not having any impact on the tested functionality.

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/33727">issues.joomla.org/tracker/joomla-cms/33727</a>.</sub>

**Comment by Quy** [comment]
Thanks

**Pull request merged**
