### PR TITLE
Add anchor css for menu item type of separator

### PR DESCRIPTION
**Pull request by AteDev**
This PR add a field in menu item type of separator to give possibility to add anchor css (like component, url ...)

### CODE REVIEW

**Comment by zero-24** [comment]
@test successful

### How to test

- apply the patch
- add a new menu item with type `Text Separator` (can be found under `System`)
- add a new class to the new field (e.g. `red`)
- reload the frontend
- use your dev tools (from your browser) to inspect the menu item
- make sure the new class is added


@AteDev Thanks. PS: Please provide in the feature some kind of non tecnical testinstructions how to test. With it it will be easyier to test and understand your change :smile:

**Comment by bertmert** [comment]
@test Success

**Comment by zero-24** [comment]
RTC'ing Thanks :smile: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6897">issues.joomla.org/joomla-cms/6897</a>.</sub>

**Comment by Kubik-Rubik** [comment]
Thanks @AteDev for your contribution. Since this PR introduces a new feature, I've set the milestone to 3.5.

**Comment by mbabker** [comment]
Merged to `3.5-dev` via 8d6246a

**Pull request closed without merging**
