### PR TITLE
[4.0] [a11y] Remove redundant title from modules

### PR DESCRIPTION
**Pull request by brianteeman**
The title attribute is generally not very accessible. Keyboard users and touch screen users will never see it.

It is particularly useless to add a title which is the same as other text already present as that can result in a screen reader announcing the same text twice.

This PR removes the redundant title attribute where the same text is already present from the admin stats module.
This PR removes the title attribute "Go" from the search button, if enabled, of the site smart search module as it is redundant. The language string is also removed.

### CODE REVIEW

**Comment by wilsonge** [comment]
Looks good to me - can you revert the package lock changes though please

**Comment by brianteeman** [comment]
oops

**Comment by wilsonge** [comment]
Overriding system test fails as drone appears to have broken. Merging on review

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
