### PR TITLE
[5.3] Loadmodule plugin remove unused options

### PR DESCRIPTION
**Pull request by brianteeman**
This simple PR removes two options from the loadmodule plugin which have not done anything since 4.0 as they are for module chromes that have not existed since 3.x

I marked the language strings as deprecated as _i think_ that is the requirement although they can probably just be deleted now. That's a maintainer decision

### Testing Instructions
code review

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 382cab63c1a922ee122e49c9a0787cac563b420f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44273">issues.joomla.org/tracker/joomla-cms/44273</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 382cab63c1a922ee122e49c9a0787cac563b420f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44273">issues.joomla.org/tracker/joomla-cms/44273</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44273">issues.joomla.org/tracker/joomla-cms/44273</a>.</sub>

**Comment by brianteeman** [comment]
thx

**Pull request merged**
