### PR TITLE
[4.0] Email Validation if there are more than 63 characters

### PR DESCRIPTION
**Pull request by astridx**
### Summary of Changes
The url http://www.w3.org/TR/html-markup/input.email.html did not exist any more. The correct url is now https://www.w3.org/TR/html/sec-forms.html#email-state-typeemail

The label  of an email 
`1*( atext / "." ) "@" label *( "." label )`
is limited to a length of 63 characters by RFC 1034 section 3.5 (https://tools.ietf.org/html/rfc1034#section-3.5)

### Testing Instructions
Create an user and use an email address with more than 63 characters. For example
 
test@**1234abcdefghijklmnopqrstuvwyz0123456789abcdefghijklmnopqrstuvwyz**.org
test@test.**1234abcdefghijklmnopqrstuvwyz0123456789abcdefghijklmnopqrstuvwyz**
test@**1234abcdefghijklmnopqrstuvwyz0123456789abcdefghijklmnopqrstuvwyz**.example.org

### Expected result
I expect to see a warning and the email address should not be saved.

### Actual result
No warning and the email address is saved. 

If you apply this patch, you see the warning and the email address is not saved if you use an email address with more than 63 characters for label. 
If you use an email address with less than 63 characters, for example

test@**123abcdefghijklmnopqrstuvwyz0123456789abcdefghijklmnopqrstuvwyz**.org
test@test.**123abcdefghijklmnopqrstuvwyz0123456789abcdefghijklmnopqrstuvwyz**
test@**123abcdefghijklmnopqrstuvwyz0123456789abcdefghijklmnopqrstuvwyz**.example.org

the email address is saved. 

### Documentation Changes Required
No

### Todo

If you install Joomla, the email field is marked an invalid field, when you click in step 3 on "Install Joomla", but you see no warning that explains why the field is marked as invalid.

The same goes for Joomla version 3.

Addition: If we merge this we should do this for media/system/js/validate-uncompressed.js, too.

### CODE REVIEW

**Comment by brianteeman** [comment]
Personally I would remove the email regex completely.and simply use the native PHP filter_var

**Comment by ReLater** [comment]
> Personally I would remove the email regex completely.and simply use the native PHP filter_var

Me, too, but
filter_var (FILTER_VALIDATE_EMAIL) doesn't support dotless domains.
https://secure.php.net/manual/en/filter.filters.validate.php

E.g. in a local environment dotless domains are common.

**Comment by brianteeman** [comment]
so take the other option - remove all validation. Leave it to the user to make sure they type their own email address correctly. The internet wastes far too much time writing regex for emails and then updating them etc etc

**Comment by brianteeman** [comment]
I was looking to see what has changed since j3 

In J3 all validation was done by validation.js (which did have the character count)

It looks to me that the removal of that script is exposing a lot of different errors and instead of them all being reported one at a time - everything that was tested with validation.js in J3 should be checked in J4. Otherwise we are just adding bandaids

**Comment by sanderpotjer** [comment]
@astridx thanks for your PR! Can you update the PR to solve the merge conflict? Thanks in advance :)

**Comment by astridx** [comment]
@sanderpotjer Done

**Comment by sanderpotjer** [comment]
@astridx thanks! With the merge this change is lost: 
> The url http://www.w3.org/TR/html-markup/input.email.html did not exist any more. The correct url is now https://www.w3.org/TR/html/sec-forms.html#email-state-typeemail

**Comment by astridx** [comment]
I'm not good at resolving conflicts. Is there any interest for this function? Then I would close this PR and open a new one.

**Comment by sanderpotjer** [comment]
@astridx l do think it is good to fix this :-) I've made a Pull Request against your PR on https://github.com/astridx/joomla-cms/pull/1 If you merge that, this PR should be fine :)

**Comment by astridx** [comment]
@sanderpotjer Thank you

**Comment by eXsiLe95** [comment]
I have tested this item :red_circle: unsuccessfully on 2b05a3f5940f2074bdecb0c87b6e7eab42fe4dae<br /><br />When creating an user with an invalid email address (e.g. test@123abcdefghijklmnopqrstuvwyz0123456789abcdefghijklmnopqrstuvwyzzzz.org, label has length of 66), the warning is shown but the user is still saved.

Result Screenshot

phpmyadmin<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19300">issues.joomla.org/tracker/joomla-cms/19300</a>.</sub>

**Comment by Schmidie64** [comment]
I would extend the problem of PR a bit more. The problem also occurs when updating a user.

**After Click on the Save User Button (update)**
error with existing user

**System**
PHP Build On: Windows NT 10.0 build 18362 (Windows 10) i586
10.1.37-MariaDB
PHP-Version: 7.3.0
Webserver: Apache/2.4.37 (Win32) OpenSSL/1.1.1a PHP/7.3.0
Joomla! Version: 	Joomla! 4.0.0-alpha12-dev Development [ Amani ] 19-August-2019 13:40 GMT
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36

**Comment by astridx** [comment]
@eXsiLe95 Thank you for testing. 
I just tested it myself again and you're right. The warning appears. The user is saved despite the warning.
Now I do not know how to continue. For my understanding, the user should not be saved if the RegX does not fit. And the RegX does not fit, because of the warning. The user was not saved when I created this PR. Is it possible that something else is wrong with the server-side validation?

@Schmidie64 You are right. I will do this, if this Pr is accepted :).

**Comment by uthorat** [comment]
I have tested this item :red_circle: unsuccessfully on 2b05a3f5940f2074bdecb0c87b6e7eab42fe4dae<br /><br />after applying patch, user still getting the warning and user also get saved.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19300">issues.joomla.org/tracker/joomla-cms/19300</a>.</sub>

**Comment by vaibhavsTekdi** [comment]
I have tested this item :red_circle: unsuccessfully on 2b05a3f5940f2074bdecb0c87b6e7eab42fe4dae<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19300">issues.joomla.org/tracker/joomla-cms/19300</a>.</sub>

**Comment by rajnish-dargan** [comment]
I have tested this item :white_check_mark: successfully on 2b05a3f5940f2074bdecb0c87b6e7eab42fe4dae<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19300">issues.joomla.org/tracker/joomla-cms/19300</a>.</sub>

**Comment by jwaisner** [comment]
@Quy Can you advise what updates need to be made to this PR?

**Comment by astridx** [comment]
@Quy Why did you set the Label "Updates Requested"?

**Comment by Quy** [comment]
@astridx Per your comment https://github.com/joomla/joomla-cms/pull/19300#issuecomment-530099770

**Comment by astridx** [comment]
I just looked at this PR again. The behavior is now again as described in the test description. The user is not saved.

Users  New   tes   Administration(1)

The PR can be tested again.

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on af401a51db2576935f776910989704c596afeed0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19300">issues.joomla.org/tracker/joomla-cms/19300</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on af401a51db2576935f776910989704c596afeed0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19300">issues.joomla.org/tracker/joomla-cms/19300</a>.</sub>

**Comment by jwaisner** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19300">issues.joomla.org/tracker/joomla-cms/19300</a>.</sub>

**Comment by richard67** [comment]
Thanks.

**Comment by brianteeman** [comment]
Unfortunately this PR is not correct as the regex being used requires the email address to have a TLD and it is perfectly valid to have an email address without a tld see #28570

**Pull request merged**
