### PR TITLE
[5.0] New onAfterInitialiseDocument event

### PR DESCRIPTION
**Pull request by Fedik**
### Summary of Changes

The event that everyone waiting for :) 
This should finally solve an issue everyone hit when need to access to Document at early stage, but `onAfterRoute` document not available and `onAfterDispatch` is to late.

~PR also add a general Document event class, it introduce classes for 2 events: `AfterInitialiseDocumentEvent`, `BeforeCompileHeadEvent`~

~**Note**~
~Before we can merge this PR it would be good to add CMS\ApplicationEvent, and the document event should be a child of it (because technically it is Application event).
Thoughts?~

### Testing Instructions

Apply #40522 then apply current patch. Solve conflicts.
Add in any System plugin:
```php
public function onAfterInitialiseDocument(Joomla\CMS\Event\Application\AfterInitialiseDocumentEvent $event)
{
    var_dump($event->getDocument()->getTitle());
}
```

### Actual result BEFORE applying this Pull Request
Nothing

### Expected result AFTER applying this Pull Request
You should see Dump output.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: https://docs.joomla.org/Plugin/Events#System
- [ ] No documentation changes for docs.joomla.org needed
- [ ] Pull Request link for manual.joomla.org: IDK
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by dgrammatiko** [comment]
Merge it!

**Comment by Fedik** [comment]
Note: I have removed Event classes from this PR, it is better to do separately, with all Application events.

**Comment by HLeithner** [comment]
> Note: I have removed Event classes from this PR, it is better to do separately, with all Application events.

Nope, all new events must have a corresponding class, also you don't provide the $document in the event now.

please revert your cleanup again.

**Comment by Fedik** [comment]
> all new events must have a corresponding class

I fully agree, but unfortunately here we have to wait when Application event classes will be implemented.
Doing it here will be like runing on front of a train.

I mean that PR should go first. Then classes can be added in this one.
I maybe try to preapre something later.

**Comment by Fedik** [comment]
I have readed the event class, now it will work with #40522,
However, merge conflicts is expected :)

**Comment by HLeithner** [comment]
thanks

**Comment by HLeithner** [comment]
maybe we get a manual.joomla.org entry please?

**Comment by Fedik** [comment]
I will make it.
Also will be need update  https://docs.joomla.org/Plugin/Events#System

**Pull request merged**
