### PR TITLE
[4.3] Use in subform filter

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #39531 .

### Summary of Changes
Consistent filter name and meaningful options when selected

### Testing Instructions
Create some fiels including some marked for subform only
Test filters

### Actual result BEFORE applying this Pull Request
image

### Expected result AFTER applying this Pull Request
image

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by ReLater** [comment]
I have tested this item :white_check_mark: successfully on 45daaba7d1b905b48c0cc0870ce9a395e7554c5a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39534">issues.joomla.org/tracker/joomla-cms/39534</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 45daaba7d1b905b48c0cc0870ce9a395e7554c5a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39534">issues.joomla.org/tracker/joomla-cms/39534</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39534">issues.joomla.org/tracker/joomla-cms/39534</a>.</sub>

**Comment by obuisard** [comment]
Thank you, Brian @brianteeman !

**Comment by brianteeman** [comment]
thanks

**Comment by Kostelano** [comment]
@brianteeman Brian, the value `COM_FIELDS_ONLY_USE_IN_SUBFORM_ANY="Any Form"` is NOT all fields (as is now clear from the description), but only those that are NOT a subform. I think there is a problem.

**Pull request merged**
