### PR TITLE
[4.1] Expression can be replaced with '??' version

### PR DESCRIPTION
**Pull request by PhilETaylor**
Expression can be replaced with '??' version

Code review

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on f8f2a4ce3767f4011dbe1b40630f97d0d88ef495<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36383">issues.joomla.org/tracker/joomla-cms/36383</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on cfef43b71e7df57531c0b8ef4da22206341bc2c2<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36383">issues.joomla.org/tracker/joomla-cms/36383</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36383">issues.joomla.org/tracker/joomla-cms/36383</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Pull request merged**
