### PR TITLE
[com_tags] Image caption in Tags view

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue #14636.

### Summary of Changes

This loads caption.js in Tags view so teaser image caption displays properly.

### Testing Instructions

Create a tag, add teaser image and caption.
Create `List of all tags` menu item, set `Item Images` to `Show`.
Open the menu item in frontend.

### Expected result

Caption appears under image.

### Actual result

Caption does not appear.

### Documentation Changes Required
No.

### CODE REVIEW

**Comment by ghost** [comment]
thanks @SharkyKZ, will test Tomorrow.

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 04b5fb2d58b180283d87a429a87af80a0e7d91ee<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20648">issues.joomla.org/tracker/joomla-cms/20648</a>.</sub>

**Comment by Quy** [comment]
@franz-wohlkoenig Caption is not showing up. Can you please provide screenshot? Thanks.

**Comment by ghost** [comment]
@Quy have deleted all after Test, so i can test at End of Month.

**Comment by ghost** [comment]
Test was on SharkyKZ:com_tags_caption_3x  if this make a Difference for showing up Caption.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 04b5fb2d58b180283d87a429a87af80a0e7d91ee<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20648">issues.joomla.org/tracker/joomla-cms/20648</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/20648">issues.joomla.org/tracker/joomla-cms/20648</a>.</sub>

**Comment by wilsonge** [comment]
Nice stuff! Thanks!

**Pull request merged**
