### PR TITLE
[4.0] [com_content] Deprecate QueryHelper::buildVotingQuery()

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue # .

### Summary of Changes

Deprecates unused `Joomla\Component\Content\Site\Helper\QueryHelper::buildVotingQuery()` method.

### Testing Instructions

Code review.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 527c91c52d4f23b187bfb0dd39ce31ddc2a22dfd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27722">issues.joomla.org/tracker/joomla-cms/27722</a>.</sub>

**Comment by richard67** [comment]
Not used in core anymore.

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 527c91c52d4f23b187bfb0dd39ce31ddc2a22dfd<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27722">issues.joomla.org/tracker/joomla-cms/27722</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27722">issues.joomla.org/tracker/joomla-cms/27722</a>.</sub>

**Pull request merged**
