### PR TITLE
Add missing com_finder to com_admin script php

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
Pull Request for New Issue.
#### Summary of Changes

com_finder is missing in com_admin script.php.
This PR adds it.
#### Testing Instructions

Code review.

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
BTW, `com_joomlaupdate` is missing to. 
@wilsonge

**Comment by zero-24** [comment]
Good find. Can you add com_joomlaupdate as well to the PR?

**Comment by andrepereiradasilva** [comment]
ok @zero-24 added it.
Did not added before because not sure it should be added here, that's why i pinged @wilsonge

**Comment by zero-24** [comment]
Easy fix. Thanks -> RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10300">issues.joomla.org/joomla-cms/10300</a>.</sub>

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on 68b3124c13b5379d2424166559795deef498a562<br /><br />:+1: <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10300">issues.joomla.org/joomla-cms/10300</a>.</sub>

**Comment by andrepereiradasilva** [comment]
thanks for testing, comments and merging!

**Pull request merged**
