### PR TITLE
[5.2][Events] Use event classes for Authentication plugins

### PR DESCRIPTION
**Pull request by Fedik**
### Summary of Changes

Update `authentication` and `api-authentication` plugins to use `SubscriberInterface` and an event classes.

### Testing Instructions

Login/Logout,
do API request.

All should work as before.

### Actual result BEFORE applying this Pull Request

Works

### Expected result AFTER applying this Pull Request

Works

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed
- [x] Pull Request link for manual.joomla.org: https://github.com/joomla/Manual/pull/177
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by LadySolveig** [comment]
I have tested this item :white_check_mark: successfully on 9825e5a4d184c17c4f4b87411e2659c85c7bb8d5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43601">issues.joomla.org/tracker/joomla-cms/43601</a>.</sub>

**Comment by exlemor** [comment]
I have tested this item :white_check_mark: successfully on 9825e5a4d184c17c4f4b87411e2659c85c7bb8d5<br /><br />Hi, thanks to @LadySolveig, and @bembelimen, I was able to successfully test this.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43601">issues.joomla.org/tracker/joomla-cms/43601</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43601">issues.joomla.org/tracker/joomla-cms/43601</a>.</sub>

**Comment by Hackwar** [comment]
Thank you for your contribution @Fedik!

**Pull request merged**
