### PR TITLE
Frontend: com_wrapper view review

### PR DESCRIPTION
**Pull request by zero-24**
### Summary of Changes

Frontend: com_wrapper view review

### Testing Instructions

install testing data and test a iframe view

### Expected result

works

### Actual result

works with very smal cs things

### Documentation Changes Required

none.

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on dc04fc75b1b57873f865d1ce0267a9a30f8913bb<br /><br />Code review.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17237">issues.joomla.org/tracker/joomla-cms/17237</a>.</sub>

**Comment by n9iels** [comment]
I have tested this item :white_check_mark: successfully on 0be508f025cb9d29ded63e303cae2e6c6c2be5ad<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17237">issues.joomla.org/tracker/joomla-cms/17237</a>.</sub>

**Comment by ghost** [comment]
@Quy can you please retest?

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 0be508f025cb9d29ded63e303cae2e6c6c2be5ad<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/17237">issues.joomla.org/tracker/joomla-cms/17237</a>.</sub>

**Comment by ghost** [comment]
RTC after two successful tests.

**Pull request merged**
