### PR TITLE
Update copyright for #7829

### PR DESCRIPTION
**Pull request by Fedik**
It seems year already has changed, and I missed this :smile: 
sorry!

here is update for the copyright year in the subform field #7829

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 801e029c8513fa2412f452289327d9d8900ef3a3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10375">issues.joomla.org/joomla-cms/10375</a>.</sub>

**Comment by brianteeman** [comment]
Simple fix direct to RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10375">issues.joomla.org/joomla-cms/10375</a>.</sub>

**Comment by dgt41** [comment]
@Fedik one request from me, as I guess the field calendar is still not working correctly with the new repeatable can we add:
```javascript
		// Handle the calendar field
		if($.fn.fieldCalendar){
			$row.find('.field-calendar-wrapper').fieldCalendar();
		}
```
And I will provide the required changes in the calendar-setup.js and the calendar field with the use of JLayouts

**Comment by Fedik** [comment]
@dgt41 I think should not be a problem to add it in same time when will be changes for the calendar-setup.js :wink:

**Pull request merged**
