### PR TITLE
Improve message

### PR DESCRIPTION
**Pull request by Bakual**
Improving the en-GB warning text about the new TinyMCE configuration change.

### Summary of Changes
Improves the warning text.

### Testing Instructions
Review (pinging @Hils)

#### Disclaimer
Work is done by @brianteeman

### CODE REVIEW

**Comment by infograf768** [comment]
ok for me.

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 15b538eeb2c0a3abddef877a1ccd5b82348bf8b5<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14386">issues.joomla.org/tracker/joomla-cms/14386</a>.</sub>

**Comment by infograf768** [comment]
Simple change which makes sense. RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14386">issues.joomla.org/tracker/joomla-cms/14386</a>.</sub>

**Comment by Hils** [comment]
Successful test from me.

**Comment by Hils** [comment]
@Bakual  Unfortunately I am not receiving the 'pings'. I am just seeing them as I do my daily Git'Crawl' - could you tell me how and where I should be receiving them please? (Very willing to assist)

**Comment by jeckodevelopment** [comment]
@Hils you should look at this page: https://github.com/joomla/joomla-cms/labels/Language%20Change 
But i don't know if it's possible to have a sort of feed when there's something new

**Comment by Bakual** [comment]
@Hils You should at least get it in the notification view on GitHub (https://github.com/notifications).
That's where I look first usually :)

**Comment by zero-24** [comment]
@Hils you can have a look here: https://github.com/settings/notifications there you can change the setting about sending mails and or showing it in the web ;)  If you enable this:
image

You should also get the mails to your github account. Feel free to ping me on Glip if you have any other questions about github :smile:

**Comment by Hils** [comment]
@Bakual @jeckodevelopment and @zero-24 
Thanks for your kind help guys! I get all the github mails in my gmail inbox and I can now see the mention. I checked by preferences and added the only unchecked one which seemed irrelevant! and something automagical has happened!
**Brian Mitchell to joomla/joomla-websites, me, Mention**
Phew!

**Pull request merged**
