### PR TITLE
improve/fix support for multiple database connections.

### PR DESCRIPTION
**Pull request by freywald**
Pull Request for Issue #9742 .

I propose the following changes to Joomla to improve/fix support for multiple database connections.

### CODE REVIEW

**Comment by chrisdavenport** [comment]
I have tested this item :white_check_mark: successfully on 7bc5f43d5ade21290fac90fa8c6734bb5860e608<br /><br />Simple and obvious fix.  Can be merged on review, but just in case, I installed it and clicked around various places that would have been affected.  No problems found.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10369">issues.joomla.org/joomla-cms/10369</a>.</sub>

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on 7bc5f43d5ade21290fac90fa8c6734bb5860e608<br /><br />Works. Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10369">issues.joomla.org/joomla-cms/10369</a>.</sub>

**Comment by zero-24** [comment]
RTC. Thanks.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10369">issues.joomla.org/joomla-cms/10369</a>.</sub>

**Comment by Kubik-Rubik** [comment]
Thank you @nsrsr and testers!

**Pull request merged**
