### PR TITLE
Added an api test for content group fields

### PR DESCRIPTION
**Pull request by rajputanuj31**
Added an api test for content group fields.

### CODE REVIEW

**Comment by brianteeman** [comment]
something has gone wrong here. 

The pr and the code say "content group fields."
But the file name is tests/System/integration/api/**com_contact**/Field_Group.cy.js

**Comment by rajputanuj31** [comment]
> something has gone wrong here.
> 
> The pr and the code say "content group fields." But the file name is tests/System/integration/api/**com_contact**/Field_Group.cy.js

Fixed.

**Comment by rajputanuj31** [comment]
> something has gone wrong here.
> 
> The pr and the code say "content group fields." But the file name is tests/System/integration/api/**com_contact**/Field_Group.cy.js


POST API test is failing, I am unable to find the reason
I will be grateful if you help me with this.

**Comment by MacJoom** [comment]
May be related to #40610 ?

**Comment by rajputanuj31** [comment]
> May be related to #40610 ?

It's working. After successful merge of #40610 this PR can we merged.
thanks a lot.

**Comment by rajputanuj31** [comment]
@MacJoom Is PR #40610 is merged in 4.4-dev??

**Comment by MacJoom** [comment]
Yes it should be in the upmerge. But I see that drone is still failing so I need to check

**Comment by MacJoom** [comment]
No - it wasn't ... i will do another upmerge

**Comment by rajputanuj31** [comment]
> No - it wasn't ... i will do another upmerge

Ok

**Pull request merged**
