### PR TITLE
[4.0] House cleaning => remove obsolete div element in system message container

### PR DESCRIPTION
**Pull request by hans2103**
Pull Request for Issue # .

### Summary of Changes

This PR will remove the obsolete `<div id="system-message"></div>` from layout/joomla/system/message.php 
This id was used in J3 plugin installer_webinstaller. It is not used in the J4 version anymore. 
Therefor this element is obsolete and can be removed. 
This PR will also remove the obsolete styling for this removed element.

### Testing Instructions

- Joomla 4 
- Find the login module in the sidebar, don't fill any fields and press the button login. 
- The page refreshes on `/index.php/author-login` with an alert

> Empty password not allowed.

The HTML of this alert is:
```
<div id="system-message-container" aria-live="polite"><joomla-alert type="warning" dismiss="true" class="joomla-alert--show" role="alert"><button class="joomla-alert--close" aria-label="Close"><span aria-hidden="true">×</span></button><div class="alert-heading"><span class="warning"></span><span class="sr-only">Warning</span></div><div class="alert-wrapper"><div class="alert-message">Empty password not allowed.</div></div></joomla-alert></div>
```

Press the X to close the alert

### Actual result BEFORE applying this Pull Request

You are able to close the alert.
The HTML of the closed alert is:
```
<div id="system-message-container" aria-live="polite"><div id="system-message"></div></div>
```

### Expected result AFTER applying this Pull Request

You are able to close the alert.
The HTML of the closed alert is:
```
<div id="system-message-container" aria-live="polite"></div>
```

Without the obsolete `div` element you can properly use the css `:empty` trigger to remove a margin between succeeding elements. No JS needed.

### CODE REVIEW

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 891ac39a1e45e9bcbb6dd3a1f01f1114c31d9976<br /><br />OK for this.

 @chmst `#system-message-container` needs to be added to Cassiopea css with `margin-top: 0;`<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31195">issues.joomla.org/tracker/joomla-cms/31195</a>.</sub>

**Comment by hans2103** [comment]
> @chmst #system-message-container needs to be added to Cassiopea css with margin-top: 0;

No... only `#system-message-container:empty` and the :first-child of the parent of #system-message-container needs a `margin-top:0`. 
This should be done after merge of this PR

**Comment by hans2103** [comment]
PR https://github.com/joomla/cassiopeia/pull/194 is created to fix obsolete margin in Cassiopeia

**Comment by adj9** [comment]
I have tested this item :white_check_mark: successfully on 891ac39a1e45e9bcbb6dd3a1f01f1114c31d9976<br /><br />OK
Schermata 2020-10-22 alle 14 38 57

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31195">issues.joomla.org/tracker/joomla-cms/31195</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/31195">issues.joomla.org/tracker/joomla-cms/31195</a>.</sub>

**Comment by chmst** [comment]
Thanks!

**Pull request merged**
