### PR TITLE
[4.0] getExtensionGroups typo

### PR DESCRIPTION
**Pull request by brianteeman**
Fixes obvious typo - code review

### CODE REVIEW

**Comment by HLeithner** [comment]
Is this only called from this file? because basically it would be a b/c break on the other side it doesn't exists after installation so isn't really part of joomla.

**Comment by brianteeman** [comment]
There are no other instances in the core

**Comment by HLeithner** [comment]
Good to know thx, cc @wilsonge

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 2d7e941f8befc3a210c389bb2310712fab6866f8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26309">issues.joomla.org/tracker/joomla-cms/26309</a>.</sub>

**Comment by wilsonge** [comment]
We officially don't guarantee b/c on extensions anyhow. so it's all fine even if someone does something stupid

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
