### PR TITLE
Buttons on modal footer freaks out the forms - continued

### PR DESCRIPTION
**Pull request by brianteeman**
Continuing the work of #14483 but completing the final two places identified by @infograf768 here https://github.com/joomla/joomla-cms/pull/14483#issuecomment-285855181

### CODE REVIEW

**Comment by tonypartridge** [comment]
I have tested this item :white_check_mark: successfully on b52efacfd855256491f665d41371518ac816a7f0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16156">issues.joomla.org/tracker/joomla-cms/16156</a>.</sub>

**Comment by dgt41** [comment]
I have tested this item :white_check_mark: successfully on b52efacfd855256491f665d41371518ac816a7f0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16156">issues.joomla.org/tracker/joomla-cms/16156</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
RTC after two successful tests.

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
