### PR TITLE
[4] PHP 8.2 Dynamic property - SmartSearch

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue php 8.2 - dynamic property Deprecated

### Summary of Changes
declared property

### Testing Instructions
open frontend Smart Search with php 8.2 with Error Reporting = maximum 

### Actual result BEFORE applying this Pull Request

Deprecated: Creation of dynamic property Joomla\Component\Finder\Administrator\Indexer\Query::$dates is deprecated

### Expected result AFTER applying this Pull Request
no more deprecated

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by carlitorweb** [comment]
I have tested this item :white_check_mark: successfully on 716fde06244c8a9df13221c746864a0614776e00<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39633">issues.joomla.org/tracker/joomla-cms/39633</a>.</sub>

**Comment by laoneo** [comment]
I have tested this item :white_check_mark: successfully on 716fde06244c8a9df13221c746864a0614776e00<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39633">issues.joomla.org/tracker/joomla-cms/39633</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39633">issues.joomla.org/tracker/joomla-cms/39633</a>.</sub>

**Comment by roland-d** [comment]
Thank you

**Pull request merged**
