### PR TITLE
TinyMCE tolbar builder: use TinyMCE translation for the TinyMCE buttons

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue #13343

### Summary of Changes
This pull make the builder to use TinyMCE translation for the TinyMCE buttons

### Testing Instructions
Set the admin language to different from English, and check that 99% of button are translated already, in the Plugin -TinyMCE.

### Documentation Changes Required
nope

### CODE REVIEW

**Comment by AlexRed** [comment]
I have tested this item :white_check_mark: successfully on f1e84dc9ffff1b5a9e08ac3aba758dfae605d12d<br /><br />patch ok<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13368">issues.joomla.org/tracker/joomla-cms/13368</a>.</sub>

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on f1e84dc9ffff1b5a9e08ac3aba758dfae605d12d<br /><br />Bravo!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13368">issues.joomla.org/tracker/joomla-cms/13368</a>.</sub>

**Comment by infograf768** [comment]
RTC. Thank!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13368">issues.joomla.org/tracker/joomla-cms/13368</a>.</sub>

**Comment by wilsonge** [comment]
Thankyou :)

**Pull request merged**
