### PR TITLE
[5.1] Convert mod_title to service provider

### PR DESCRIPTION
**Pull request by joomlaweby**
### Summary of Changes

Converts the administrator title module to service provider.

### Testing Instructions

1. Make sure you have site module mod_title published
2. You should see module output in administrator area

mod_title

### Actual result BEFORE applying this Pull Request

Module works as expected

### Expected result AFTER applying this Pull Request

Module works same way as before applying pull request

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by fgsw** [comment]
I have tested this item :white_check_mark: successfully on a11583812a3cceffa8eb2c6f73664e2b451de8ca<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42801">issues.joomla.org/tracker/joomla-cms/42801</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on a11583812a3cceffa8eb2c6f73664e2b451de8ca<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42801">issues.joomla.org/tracker/joomla-cms/42801</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/42801">issues.joomla.org/tracker/joomla-cms/42801</a>.</sub>

**Comment by LadySolveig** [comment]
Thank you @joomlaweby and also for testing @fgsw @viocassel

**Pull request merged**
