### PR TITLE
Repeat #27963: load showon.js only once

### PR DESCRIPTION
**Pull request by chmst**
Pull Request for Issue # .

### Summary of Changes
#27963 was accidentally deleted, this restores all changes.

### CODE REVIEW

**Comment by Fedik** [comment]
layout changes covered in #28431 :wink: 
but not components/com_contact

**Comment by chmst** [comment]
@Fedik  you add com_contact to your pr? Then I can close this one.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28456">issues.joomla.org/tracker/joomla-cms/28456</a>.</sub>

**Comment by Fedik** [comment]
@chmst I have added ;)

**Comment by chmst** [comment]
Thank you @Fedik

**Pull request closed without merging**
