### PR TITLE
[#31516] Create JLayout's for common social buttons

### PR DESCRIPTION
**Pull request by wilsonge**
This starts the process of making some features not already in the CMS available as JLayouts. This starts with:
- Facebook Like
- Twitter Share
- Twitter Follow
- Twitter Hashtag
- Twitter Mention
- Google +1

Note this is the same as my old PR as https://github.com/joomla/joomla-cms/pull/1550 except targeted at staging instead of master
## Screenshot

image

Note including them in articles is **_NOT**_ included in this PR - this is just demonstrating their use
### Google+1
- **data-size** _small, medium, standard, tall_ Size of the icon - default standard.
- **data-annotation** _inline, bubble, none_ The style of annotation to appear - default inline.
- **data-width** _integer_ The width of the icon - default 300
- **data-href** _URL_ The URL for the like to link to. By default the current URL (JUri::current())
- **show-count** _true/false_ Show/Hide the number of people who have +1'd the page
- **language** _Language string recognized by google_ Defaults to the locale according to the language (https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/language/language.php#L1244).
### Facebook Like
- **appid** _integer_ The appid if one exists for the like to link with
- **data-href** _URL_ The URL for the like to link to. By default the current URL (JUri::current())
- **data-width** _integer_ The width of the icon - default 450
- **show-faces** _true/false_ Shows the faces of others who have liked the page. Default true.
- **data-layout** _standard, button_count, box_count_ Layout of button. Default standard.
- **data-action** _'empty attribute'/like, recommend_ Verb for the button. Default empty (which is "like").
- **data-colorscheme** _light, dark_ Color scheme. Default like
- **language** _Language string recognized by fb_ Defaults to the locale according to the language (https://github.com/joomla/joomla-cms/blob/staging/libraries/joomla/language/language.php#L1244).
#### Follow
- **show-count** _true/false_ Show the number of users followed. Default false
- **user** _Valid Twitter user_ The user for twitter. If not entered will give a JLog priority warning.
#### Share

To be written up (see code for now)
#### Hashtag

To be written up (see code for now)
#### Mention

To be written up (see code for now)
## Issues
- Is my new language file in a good location and with a good name?
- Twitter hashtag langs don't seem to work at the moment (the other twitter views do)
- Is the location of the social layouts package in a good place?
## Testers
- Check multiple instances of each icon work
- Check each icon work
- Check parameters work as expected
- Check multilingual aspect

Suggested code:

```
$layout = new JLayoutFile('social.google');
echo $layout->render(array());
$layout2 = new JLayoutFile('social.twitter.share');
echo $layout2->render(array());
$layout3 = new JLayoutFile('social.facebook');
echo $layout3->render(array());
$layout4 = new JLayoutFile('social.twitter.follow;);
echo $layout4->render(array('user'=>'GW1992'));  // or similar for a twitter username (please don't spam mine :P)
```

### CODE REVIEW

**Comment by brianteeman** [comment]
Setting to Needs Review so that the CMS Maintainers can make a decision on this - otherwise its going to sit here forever<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/5252">issues.joomla.org/joomla-cms/5252</a>.</sub>

**Comment by mbabker** [comment]
IMO unless we intend on baking social features into core, let this one go.

**Comment by smz** [comment]
@wilsonge Although I agree this should have not gone in the core, I feel it is unfortunate that this potentially useful code on which you've probably spent some time has gone to /dev/nul. Wasn't there any other option possible?

**Comment by mbabker** [comment]
Throw it in a repo somewhere, build an extension out of it.  Definitely not /dev/null worthy effort.

**Pull request closed without merging**
