### PR TITLE
[4.0] [NO CACHE] Enable code style for Vue App Media Manager 

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue # .

### Summary of Changes
- Enable Eslint to lint also vue files
- Rename the .js media files to .es6.js so that these could be listed as well
- Fix indentation
- Replace deprecated code
- Fix slots
- Suppress all other errors/warnings

From
```
✖ 1254 problems (1221 errors, 33 warnings)
  1082 errors and 18 warnings potentially fixable with the `--fix` option.
```
to `No errors`

### Testing Instructions
Check that all the modals and the rest of the media manager functionality is intact

### CODE REVIEW

**Comment by SharkyKZ** [comment]
Please use `git mv` to rename files.

**Comment by dgrammatiko** [comment]
> Please use `git mv` to rename files.

I did: https://github.com/joomla/joomla-cms/pull/30839/commits/39693c2d9a769ea268375381bcc650232b82f808

**Comment by SharkyKZ** [comment]
Weird because Github shows somes files as deleted/added.

**Comment by dgrammatiko** [comment]
> Weird because Github shows somes files as deleted/added.

Are we looking at the same thing? The first commit in this PR clearly shows that I just renamed the files (with git mv as you've asked eg `$ git mv translate.js translate.es6.js`) 


According to SO this is expected: https://stackoverflow.com/questions/2314652/is-it-possible-to-move-rename-files-in-git-and-maintain-their-history

**Comment by dgrammatiko** [comment]
@richard67 could you please restart drone here? Thanks

**Comment by SharkyKZ** [comment]
I'm looking at the Files tab here on Github. Some look to have been moved correctly (e.g `getters.js`) and others don't. The diff also shows some files being deleted:

    diff --git a/administrator/components/com_media/resources/scripts/store/mutations.js b/administrator/components/com_media/resources/scripts/store/mutations.js
    deleted file mode 100644

But git blame appears to be intact.

**Comment by dgrammatiko** [comment]
> and others don't

Maybe wrong permissions? I honestly redid this PR using `git mv`. I'm not a git guru...

**Comment by bonzani** [comment]
It depends on your [similarity threshold](https://git-scm.com/docs/git-diff#Documentation/git-diff.txt---find-renamesltngt) setting in the Git client. In any case `git mv oldname newname` is just shorthand for:
```
mv oldname newname
git add newname
git rm oldname
```

**Comment by particthistle** [comment]
I have tested this item :red_circle: unsuccessfully on f39f6e11883d0ff7318d9536d30273d520aadf03<br /><br />### Before Patching ###
Modal for previewing an image has an X to close (fa-times icon), allowing you to close the image preview.

### After Patching ###
Modal X no longer visible, had to press escape to close the image preview.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30839">issues.joomla.org/tracker/joomla-cms/30839</a>.</sub>

**Comment by dgrammatiko** [comment]
@richard67 could you restart drone here?

**Comment by particthistle** [comment]
I have tested this item :white_check_mark: successfully on 1e94346c26e3294ab03479f6d4f9f4d4dc8c6012<br /><br />Tested again after close icon was fixed.

- Image preview modal works
- Create new folder modal works
- Rename file modal works (though renaming a file doesn't trigger a warning that it will affect existing links to the file throughout the site - perhaps needs another issue raised?)
- Delete file modal works
- Delete folder modal works

Everything looks to be working correctly, without any console errors appearing.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/30839">issues.joomla.org/tracker/joomla-cms/30839</a>.</sub>

**Comment by wilsonge** [comment]
LGTM on review too. Thanks!

**Pull request merged**
