### PR TITLE
Menu Items Manager: status tips don't show for System Links

### PR DESCRIPTION
**Pull request by infograf768**
Before patch, mouse over the status icons for the url, alias, separator and heading menu items: the tip does not display because $tip was set to false

After patch:
screen shot 2015-04-03 at 11 45 50
screen shot 2015-04-03 at 11 45 28
screen shot 2015-04-03 at 11 45 18
screen shot 2015-04-03 at 11 45 09

### CODE REVIEW

**Comment by dneukirchen** [comment]
confirm issue.
@test successful

**Comment by fontanil** [comment]
@test
Patch works for me

**Comment by infograf768** [comment]
Folks, let's wait for that one. We have an issue when the item is trashed. In that case the trashed state being -2, when added to the default # for the array, it gives a wrong tip.

I can see also that, even before the patch, when filtering by trashed state, these System links do not display when filtering by Trashed.

The code responsible is:
```
$query->select(
			'CASE a.type' .
				' WHEN ' . $db->quote('component') . ' THEN a.published+2*(e.enabled-1) ' .
				' WHEN ' . $db->quote('url') . ' THEN a.published+2 ' .
				' WHEN ' . $db->quote('alias') . ' THEN a.published+4 ' .
				' WHEN ' . $db->quote('separator') . ' THEN a.published+6 ' .
				' WHEN ' . $db->quote('heading') . ' THEN a.published+8 ' .
				' END AS published'
		);
		$query->from($db->quoteName('#__menu') . ' AS a');
```
I guess we have to find a complete solution for both issues.
@zero-24
please take of RTC

**Comment by infograf768** [comment]
Please test again.
Now the system links menu items get a new tip when trashed  ("Publish menu item") as well as the right trash icon.

This PR includes https://github.com/joomla/joomla-cms/pull/6629

**Comment by fontanil** [comment]
@test: icons and tooltips are now OK

**Comment by Fedik** [comment]
**test** works good form me

**Comment by infograf768** [comment]
seting back to RTC. Thanks for testing.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6641">issues.joomla.org/joomla-cms/6641</a>.</sub>

**Pull request merged**
