### PR TITLE
[4.4][Performance] Fix duplicated DB queries for non-existing asset

### PR DESCRIPTION
**Pull request by Fedik**
### Summary of Changes

Fix duplicated DB queries for non-existing asset.

### Testing Instructions
Enable debug and debug Query in the debug plugin.
Login in administrator section as **manager**.
Open Articles list table.
Check amount of DB queries in debug panel.

Or run folowing code, in templates/atum/index.php.
```php
for ($i = 0; $i < 100; $i++) {
    $app->getIdentity()->authorise('core.edit', 'com_content.category.1');
}
```

### Actual result BEFORE applying this Pull Request
Around 55.

With testing code it is around 155 or more;

### Expected result AFTER applying this Pull Request
Around 45

With testing code it is around 45;

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed
- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by tkuschel** [comment]
You can also fix the strange comment "// Else we have to do an extra db query to fetch it from the table **fetch it from table.**" with this PR.

**Comment by Fedik** [comment]
done

**Comment by fgsw** [comment]
I have tested this item :white_check_mark: successfully on 892c8923fe86bca114981cecdc0f24949f69593c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44033">issues.joomla.org/tracker/joomla-cms/44033</a>.</sub>

**Comment by Hackwar** [comment]
I have tested this item :white_check_mark: successfully on 892c8923fe86bca114981cecdc0f24949f69593c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44033">issues.joomla.org/tracker/joomla-cms/44033</a>.</sub>

**Comment by Hackwar** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44033">issues.joomla.org/tracker/joomla-cms/44033</a>.</sub>

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
