### PR TITLE
Extend editors API

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue #17665 .

### Summary of Changes
This PR introduces one more method to our Joomla.Editors API:
```js
getSelection() { /* return the current selection */ }
```
Why?
Well it's a missing piece of the puzzle but mainly because it allows DEVs to do more advanced stuff instead of always replacing some selected text.

As this is a PR for the issue linked above, the menu button is the only place where this API is used at the moment. Also this part (in media/com_menus/js/admin-items-modal.js might be removed depending on the decision about B/C break, check the notes bellow)

### Testing Instructions
Apply patch select some text in the editor and then through the menu button (xtd_button) try to insert a link! The link will have as text the selected text in the editor instead of the default menu name.

Repeat the process for all three core editors: none, tinyMCE and codemirror

### Expected result
When you link to menu items etc, if you highlight text and link it the selected text gets replaced.

### Actual result
When you link to menu items etc, if you highlight text and link it the selected text becomes the link text.

### Preview
screenshot 2018-12-03 at 20 19 12
screenshot 2018-12-03 at 20 19 26

### Documentation Changes Required
This PR is **not** breaking any API but it changes the behaviour. Eg
- old behaviour: either some text is selected or nothing then the link will have the default menu text and the selected text gets replaced
- new behaviour: if some text is selected then that will become the text of the menu item. If nothing is selected the link will have the default menu text.

@mbabker @wilsonge please make up your mind on the B/C here

@tonypartridge this one is for you 😉

### CODE REVIEW

**Comment by tonypartridge** [comment]
Dimitris my hero! Personally I don’t think it’s a BC Break as nothing is breaking but changing for the better in the way it’s always been assumed it should work....

**Comment by wilsonge** [comment]
I'm happy with this new proposed behaviour. Is there a reason we don't have an implementation for codemirror?

**Comment by dgrammatiko** [comment]
> Is there a reason we don't have an implementation for codemirror

Yes! Basically the Joomla's API for the editors is a one to one match for ~~the~~ some public functions of code mirror (naming methods is hard 😉). BTW the images above showcase that this is working with codemirror

**Review by wilsonge — APPROVED** [review]

**Comment by wilsonge** [comment]
Cool. One test here and I'm happy

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 939cfa6cc05b4098096888620287be52d128f661<br /><br />Tested fine here also in multilingual<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23224">issues.joomla.org/tracker/joomla-cms/23224</a>.</sub>

**Pull request merged**
