### PR TITLE
Track plugins being loaded to unique dispatchers

### PR DESCRIPTION
**Pull request by mbabker**
Pull Request for Issue #12690

### Summary of Changes

`JPluginHelper::importPlugin()` has a static tracking array that only allows a plugin to be loaded once, preventing the ability for plugins to be registered to anything but the first dispatcher that gets used.  Change the method to track loaded plugins based on the dispatcher to allow custom imports.

### Testing Instructions

See the issue for more information.

### Expected result

Plugins imported to each unique dispatcher.

### Actual result

Plugins are only loaded to the first dispatcher (generally the singleton from `JEventDispatcher::getInstance()`).

### Documentation Changes Required

N/A

### CODE REVIEW

**Comment by zero-24** [comment]
hmm. did i something wrong?

To me it looks like:
image

**Comment by mbabker** [comment]
We just had even more static tracking in the helper than I accounted for.  Should be fine now.

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on 6823e492ac7b704560a3816393a90aebbb358016<br /><br />looks good to me. Thanks @mbabker

@iv660 and @franz-wohlkoenig can you take a look here? Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15607">issues.joomla.org/tracker/joomla-cms/15607</a>.</sub>

**Comment by franz-wohlkoenig** [comment]
@zero-24 didn't understand anything.

**Comment by zero-24** [comment]
@franz-wohlkoenig may you found some time to test this as you commented on the other issue too ;)

**Comment by franz-wohlkoenig** [comment]
@zero-24 i asked if Issue is on latest staging too;-)

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 414a26be0d4faeb93afb6b2f971f8a399026844a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/15607">issues.joomla.org/tracker/joomla-cms/15607</a>.</sub>

**Pull request merged**
