### PR TITLE
#6688 Toggle ssl off for unverified peer/host.

### PR DESCRIPTION
**Pull request by haydenyoung**
Fix for unverified peer/host certificate.

I have added a unit test but have been unable to test as running JHttpTransportTest tests skips all tests. I've also run phpunit --testsuite libraries-cms but I think it is skipping my test also.

Also this needs an https url with a private cert or a cert with an invalid name attribute.

Alternatively, I have run a test in my dev environment using:

``` php
$array = array(
    'curl'=>array(
        'ssl'=>array(
            "verifypeer"=false,
            "verifyhost"=>false)));

$options = new \Joomla\Registry\Registry($array);
$http = JFactory::getHttp($options);
...
```

### CODE REVIEW

**Comment by wilsonge** [comment]
Sorry to be a pain but can you swap the spaces for tabs back please otherwise travis will definitely fail on the codestyle :)

**Comment by mbabker** [comment]
So 2 things:

1) Can you change your settings to keep the tab indentions?  As is it looks like you've changed the entire file.
2) In the Framework, we went for a route that allows custom options to be injected for all transports whereas this really only works for the curl SSL options.  Take a look at https://github.com/joomla-framework/http/pull/12

**Comment by haydenyoung** [comment]
2) seems like a much better option than what I'm proposing as it would, as you say, give much more control over all transport settings. My solution was really just an immediate fix to a specific problem.

Will this be merged into the joomla-cms any time soon?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6689">issues.joomla.org/joomla-cms/6689</a>.</sub>

**Comment by haydenyoung** [comment]
1) are we using PSR-2 requirement of 4 spaces rather than a tab?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6689">issues.joomla.org/joomla-cms/6689</a>.</sub>

**Comment by mbabker** [comment]
> 1) are we using PSR-2 requirement of 4 spaces rather than a tab?

No, we do not follow PSR-2.

**Comment by haydenyoung** [comment]
Got it. So size 4 tabs.

Anyway I think it would be preferable to use the joomla-framework/http#12 implementation instead.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/6689">issues.joomla.org/joomla-cms/6689</a>.</sub>

**Comment by mbabker** [comment]
Feel free to PR it in.

**Comment by wilsonge** [comment]
I've PR'd that framework thing in as part of https://github.com/joomla/joomla-cms/pull/6692 if it helps :)

**Comment by zero-24** [comment]
@haydenyoung is the PR by @wilsonge a replecement of this PR so this here can be closed?

**Comment by haydenyoung** [comment]
@zero-24 yes can be closed.

**Pull request closed without merging**
