### PR TITLE
[com_tags] - Add count and link to tagged items

### PR DESCRIPTION
**Pull request by alikon**
redo of  #8975 .
#### Summary of Changes

see comment https://github.com/joomla/joomla-cms/pull/8975#issuecomment-217636135
#### Testing Instructions

see #8975
You can select the tag "content type"  alias article, contact, newsfeed, weblink ect
staging administration tags manager
and have a better idea where tags  are located
test administration tags manager2

### CODE REVIEW

**Comment by brianteeman** [comment]
1. I like the UI now - thanks

2. You added code to com_banners but I dont see where you add a tag to a banner

3. The select box is sorted by the KEY - it should be sorted by the VALUE
eg in english because you are sorting be KEY it displays
Contact
Article
Newsfeed

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10895">issues.joomla.org/joomla-cms/10895</a>.</sub>

**Comment by brianteeman** [comment]
There are missing strings - see this animation
newsfeed

**Comment by brianteeman** [comment]
I see where the banners stuff is now - its banners category

See image for the sort issue of the strings
screen shot 2016-06-21 at 16 53 46
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10895">issues.joomla.org/joomla-cms/10895</a>.</sub>

**Comment by alikon** [comment]
sort issue + lang string should be ok now
@brianteeman thanks for reporting
tagconterlangsort

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on e60383a24d3540b371bb367943c3a47ed0aec5c8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10895">issues.joomla.org/joomla-cms/10895</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 9c44cbeeef2a76d76899b83f3f69e55663929f9e<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10895">issues.joomla.org/joomla-cms/10895</a>.</sub>

**Comment by infograf768** [comment]
```
+COM_NEWSFEEDS_TAGS_NEWSFEED="Newsfeed"
+COM_NEWSFEEDS_TAGS_CATEGORY="Newsfeed Category"
```
I guess should be
```
+COM_NEWSFEEDS_TAGS_NEWSFEED="News Feed"
+COM_NEWSFEEDS_TAGS_CATEGORY="News Feed Category"
```

also concerning
`$lang->load($extension . '.sys', JPATH_ADMINISTRATOR, null, false, true);`

should not you add
`|| $lang->load($extension . 'sys', JPath::clean(JPATH_ADMINISTRATOR . '/components/' . $extension), null, false, true);`
to take into account the 3rd party extensions with language files in their language folder?

**Comment by brianteeman** [comment]
Good spot on the language strings - I missed that

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 365a784db01271170499b3c47ab24e961f13f707<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10895">issues.joomla.org/joomla-cms/10895</a>.</sub>

**Comment by alikon** [comment]
@infograf768  i've tested with com_weblinks before later discovered
that com_weblinks lang ini files are still in the current staging (even without the component installed)
https://github.com/joomla/joomla-cms/blob/staging/administrator/language/en-GB/en-GB.com_weblinks.sys.ini
.....

:confused:

**Comment by andrepereiradasilva** [comment]
you can also discover com_weblinks hathor override in staging ...
https://github.com/joomla/joomla-cms/tree/staging/administrator/templates/hathor/html/com_weblinks

**Comment by infograf768** [comment]
@alikon 
com_weblinks ini files are in the global language folder (as well as smart search weblinks and search weblinks plugin files )in order to be translated by the TTs and included in their core packs.

**Comment by alikon** [comment]
But com_weblinks is not more  a core component, so these INI should be
removed from core distribution and included in the com_weblinks repo I
think, what I'm thinking wrong?

**Comment by infograf768** [comment]
Ideally you are right, except that no way has been devised to get all 60+  languages ini files for the weblinks extensions to be added to the weblinks repo by the TTs in an easy way (most of them don't even know how to use git). Therefore, —until a way is defined—, any change in the various weblinks extensions en-GB ini files in their repo have to be ALSO done in core. The decision has been taken when weblinks, which is maintained by Core, was separated. And it should be the same for any other component taken away from J releases.
Not speaking about B/C, as ini files in core languages folder have priority over extensions language folder, thus would not propose the right translations or have missing new strings for people who are keeping weblinks in their 1.7=>2.5=>3.x legacy sites.

**Comment by infograf768** [comment]
Therefore, please add the new strings in core weblinks sys ini as well as in the weblinks repo. ;)

**Comment by alikon** [comment]
Ok, When and if this pr will be merged, I'll submit a new pr for lang
string here and on com_weblinks + helper code ...

**Comment by hardiktasol** [comment]
I have tested this item :red_circle: unsuccessfully on 365a784db01271170499b3c47ab24e961f13f707<br /><br />I applied the patch. After applying tags listing now appears with the new options, no counter showing and clicking on counter circle gives me error.
Joomla version: 3.6.0
Tags listing
Error page<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10895">issues.joomla.org/joomla-cms/10895</a>.</sub>

**Comment by hardiktasol** [comment]
Here are the images:
screen shot 2016-06-24 at 07 26 40
screen shot 2016-06-24 at 07 26 56<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10895">issues.joomla.org/joomla-cms/10895</a>.</sub>

**Comment by brianteeman** [comment]
Works for me

On 24 June 2016 at 13:27, hardiktasol <notifications@github.com> wrote:

> Here are the images:
> [image: screen shot 2016-06-24 at 07 26 40]
> <https://camo.githubusercontent.com/e00f2fd90a1a30c2a7f62a3b97f976110777245f/68747470733a2f2f6973737565732e6a6f6f6d6c612e6f72672f75706c6f6164732f312f39623739393762343933653838636334623733326134373062393437396337382e706e67>
> [image: screen shot 2016-06-24 at 07 26 56]
> <https://camo.githubusercontent.com/e72de71d4e34a382fd1e31e0c584bb776ac28047/68747470733a2f2f6973737565732e6a6f6f6d6c612e6f72672f75706c6f6164732f312f37313731353662313831663063643465366364656532393463626630366636382e706e67>
> ------------------------------
> This comment was created with the J!Tracker Application
> <https://github.com/joomla/jissues> at issues.joomla.org/joomla-cms/10895
> <https://issues.joomla.org/tracker/joomla-cms/10895>.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/10895#issuecomment-228333101>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABPH8X63Z3RzyrORlq8IAkuKyHtIlPEZks5qO80ygaJpZM4I7EFD>
> .
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
Correction I have a found a bug

On 24 June 2016 at 13:31, Brian Teeman <brian@teeman.net> wrote:

> Works for me
>
> On 24 June 2016 at 13:27, hardiktasol <notifications@github.com> wrote:
>
>> Here are the images:
>> [image: screen shot 2016-06-24 at 07 26 40]
>> <https://camo.githubusercontent.com/e00f2fd90a1a30c2a7f62a3b97f976110777245f/68747470733a2f2f6973737565732e6a6f6f6d6c612e6f72672f75706c6f6164732f312f39623739393762343933653838636334623733326134373062393437396337382e706e67>
>> [image: screen shot 2016-06-24 at 07 26 56]
>> <https://camo.githubusercontent.com/e72de71d4e34a382fd1e31e0c584bb776ac28047/68747470733a2f2f6973737565732e6a6f6f6d6c612e6f72672f75706c6f6164732f312f37313731353662313831663063643465366364656532393463626630366636382e706e67>
>> ------------------------------
>> This comment was created with the J!Tracker Application
>> <https://github.com/joomla/jissues> at issues.joomla.org/joomla-cms/10895
>> <https://issues.joomla.org/tracker/joomla-cms/10895>.
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/joomla/joomla-cms/pull/10895#issuecomment-228333101>,
>> or mute the thread
>> <https://github.com/notifications/unsubscribe/ABPH8X63Z3RzyrORlq8IAkuKyHtIlPEZks5qO80ygaJpZM4I7EFD>
>> .
>>
>
>
>
> --
> Brian Teeman
> Co-founder Joomla! and OpenSourceMatters Inc.
> http://brian.teeman.net/
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
There is a problem when you first load the component as it shows the count even though there is no filter selected nd this is why you get a view not found. Hard to describe so I made a video

https://www.dropbox.com/s/ngcgfymxxisci1i/10895.mp4?dl=0
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10895">issues.joomla.org/joomla-cms/10895</a>.</sub>

**Comment by hardiktasol** [comment]
Exactly the problem is only with no tags selection in filter.

In my case article counter is also not visible, though there are articles with the tag added.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10895">issues.joomla.org/joomla-cms/10895</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 365a784db01271170499b3c47ab24e961f13f707<br /><br />That fixed it<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10895">issues.joomla.org/joomla-cms/10895</a>.</sub>

**Comment by hardiktasol** [comment]
I have tested this item :white_check_mark: successfully on 365a784db01271170499b3c47ab24e961f13f707<br /><br />Now works.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10895">issues.joomla.org/joomla-cms/10895</a>.</sub>

**Comment by brianteeman** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10895">issues.joomla.org/joomla-cms/10895</a>.</sub>

**Comment by wilsonge** [comment]
Merged with https://github.com/joomla/joomla-cms/commit/e2e4b987ec2ea0251df83da3fd09f597a3908ae4

**Pull request closed without merging**
