### PR TITLE
Removing duplicated AS in sql query

### PR DESCRIPTION
**Pull request by sweco-semhul**
Pull Request for Issue #13005.

### Summary of Changes
Removing duplicated AS in sql query resolving query problem

### Testing Instructions
Setup Joomla against SQL Server
Go to "smart search"
Reindex
Select any link in the list and click Delete

### Documentation Changes Required
none

### CODE REVIEW

**Comment by brianteeman** [comment]
(you don't need to create an issue if you are going to create a pull request - the system is clever and all pull requests appear in the issue tracker automatically)

**Comment by sweco-semhul** [comment]
ok. since the PR template included issue information I thought it was mandatory

**Comment by brianteeman** [comment]
No you can write that in the pull request

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 343a929d5d0a87e84b74fd2806f11f94ddc19a9a<br /><br />on code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13006">issues.joomla.org/tracker/joomla-cms/13006</a>.</sub>

**Comment by bembelimen** [comment]
I have tested this item :white_check_mark: successfully on 343a929d5d0a87e84b74fd2806f11f94ddc19a9a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13006">issues.joomla.org/tracker/joomla-cms/13006</a>.</sub>

**Pull request merged**
