### PR TITLE
[com_redirect] Add dropdown actions

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
Pull Request for Improvement.
#### Summary of Changes

This PR adds state tasks dropdown actions to redirect component.
##### Before PR

image
##### After PR

image
#### Testing Instructions
1. Use latest staging and apply patch 
2. Test the new dropdown menu in all possible tags states (published, unpublished, archived and trash)

### CODE REVIEW

**Comment by RonakParmar** [comment]
@andrepereiradasilva I have applied this patch and works fine, but this patch applied "The Redirect Plugin is disabled. Enable it in the Plugin Manager." this message is not visible.

I have reverted this patch message is visible. Is it an issue or you have done it purposely.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10182">issues.joomla.org/joomla-cms/10182</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@RonakParmar it's working fine. Just tested again.
As you can see from the code diff there is no change in the message.

Please test with latest staging.

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 97a719fe47f19d76dd95b51bf737aab6cc16f19a<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10182">issues.joomla.org/joomla-cms/10182</a>.</sub>

**Comment by BurtNL** [comment]
I have tested this item :white_check_mark: successfully on 97a719fe47f19d76dd95b51bf737aab6cc16f19a<br /><br />Nice!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10182">issues.joomla.org/joomla-cms/10182</a>.</sub>

**Comment by brianteeman** [comment]
Rtc<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10182">issues.joomla.org/joomla-cms/10182</a>.</sub>

**Comment by andrepereiradasilva** [comment]
@brianteeman 3.6.0 label?

**Pull request merged**
