### PR TITLE
allow PHP7 to fail

### PR DESCRIPTION
**Pull request by rdeutz**
Temporary till travis sorted out the problem

### CODE REVIEW

**Comment by mbabker** [comment]
:-1: 

This implies to me there is an issue in Joomla's code that requires stopping PHP 7 support.  Since this is an issue with the third party provider's service, the build failure there should be tracked as a known failure unless they indicate that a fix for the issue is going to take some unacceptable timeframe to achieve.

**Comment by rdeutz** [comment]
It is now 5 days, I will look at it and as soon as the problem is solved I will switch it back

**Comment by rdeutz** [comment]
Further more, we have the master branch protected so that nothing can be push when travis fails. That gives us more fun because Jenkins is also failing and we are surrounded from red lights.

**Comment by Bakual** [comment]
For reference: https://github.com/travis-ci/travis-ci/issues/5111

**Comment by wojsmol** [comment]
@rdeutz  see https://github.com/travis-ci/travis-ci/issues/5111#issuecomment-158091632 - travis ci problem is fixed now

**Comment by zero-24** [comment]
I have just send a PR to revert here: https://github.com/joomla/joomla-cms/pull/8499

**Comment by rdeutz** [comment]
I removed the four lines directly :-), so we are back on track!

**Pull request merged**
