### PR TITLE
DateTime object formatted according to the specified format

### PR DESCRIPTION
**Pull request by GABBAR1947**
Pull Request for Issue #9169  .

### CODE REVIEW

**Comment by brianteeman** [comment]
Please provide testing instructions

**Comment by softwareschreiber** [comment]
Cool, later I will be a famous Joomla tester and may be one of the developer....

**Comment by photodude** [comment]
@GABBAR1947 Can you address the Code style issues that failed in your PR?
```
FILE: /libraries/cms/html/html.php
--------------------------------------------------------------------------------
FOUND 5 ERROR(S) AFFECTING 2 LINE(S)
--------------------------------------------------------------------------------
 982 | ERROR | Tabs must be used to indent lines; spaces are not allowed
 982 | ERROR | No space found after comma in function call
 983 | ERROR | Tabs must be used to indent lines; spaces are not allowed
 983 | ERROR | No space found after comma in function call
 983 | ERROR | No space found after comma in function call
```

And Testing instructions would definitely be helpful.

**Comment by softwareschreiber** [comment]
Create a form with a calendar field in a database table. Input a date lower than 1.1.1970, save it and reopen it in the same form. If you see the date, all is ok.

**Comment by Bakual** [comment]
The main issue comes from the fact that we use `strftime` which uses a different formatstrings for the date format than `date` does. Simply removing the `%` unfortunately doesn't the trick. It only works for a subset of the possible options.
See http://php.net/manual/en/function.strftime.php and http://php.net/manual/en/function.date.php

Also the input value currently can in theory be any date which is recognised by PHP. Eg also the format used in Germany (31.01.2016), not only the english one (2016-01-31).

**Comment by wilsonge** [comment]
So at the moment you can specify a calendar with a text representation of the date i.e. `%B %Y` which will render like January 2016. That would completely fail apart with this change :(

There's no way this can be merged in it's present form :/

**Comment by wilsonge** [comment]
P.S. Tabs instead of spaces is your issue I think with the code style :)

**Comment by GABBAR1947** [comment]
Everything's fine in my system, but the moment the code comes on git, the indentation changes.

**Comment by Bakual** [comment]
> There's no way this can be merged in it's present form 

I'm going to close this as in the current form it's not going to be merged (not backward compatible).
If you find another way to solve the issue, feel free to do a new PR or request to reopen this one.

**Comment by GABBAR1947** [comment]
@wilsonge Can you guide , as to how to fix up the issue

**Pull request closed without merging**
