### PR TITLE
com_newsfeed update tooltip

### PR DESCRIPTION
**Pull request by brianteeman**
in the options for newsfeed is a field for the character count with a default value of 0 which means no limit. this small PR updates the tooltip to explain that.
image

### CODE REVIEW

**Comment by andrepereiradasilva** [comment]
I have tested this item :white_check_mark: successfully on c5bd765a85e28a1c2fc7b9a8c7809f2e7cb97d98<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12892">issues.joomla.org/tracker/joomla-cms/12892</a>.</sub>

**Comment by jeckodevelopment** [comment]
I have tested this item :white_check_mark: successfully on c5bd765a85e28a1c2fc7b9a8c7809f2e7cb97d98<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12892">issues.joomla.org/tracker/joomla-cms/12892</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/12892">issues.joomla.org/tracker/joomla-cms/12892</a>.</sub>

**Comment by brianteeman** [comment]
Thanks

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
