### PR TITLE
[4.0] Install From Web improvements

### PR DESCRIPTION
**Pull request by C-Lodder**
Pull Request for Issue # .

### Summary of Changes

1. Remove remaining jQuery dependency
2. Fix Joomla loading icon now showing
3. Some JS improvements

### Testing Instructions

First run `node build.js --compile-js` from your terminal, then:

1. Go to `administrator/index.php?option=com_installer`
2. Click on the "Install from Web" tab
3. Ensure the Joomla loading icons shows as per the screenshot below
4. Ensure you can navigate through the installer

### Screenshot

screeny

### CODE REVIEW

**Comment by adj9** [comment]
I have tested this item :white_check_mark: successfully on 0bfe005566b9a3350be6f1458d3635e471142ea9<br /><br />With and without patch I can JED without any problem after the load. the URLs to the components open<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28981">issues.joomla.org/tracker/joomla-cms/28981</a>.</sub>

**Comment by richard67** [comment]
@C-Lodder Even if it's clear to you and me, but could you next time add a hint in testing instruction if npm has to be used? We still need npm if js or scss is changed as long as Patchtester 4 with CI server doesn't work reliably. And we have many new testers since the "Bugs and Fun at Home" events. For those such a hint could be a help.

**Comment by richard67** [comment]
@adj9 Have you also tested if the Joomla loading logo is shown as described in the testing instructions when the patch for this Pull Request (PR) is applied? And have you run npm after having applied the patch, so the changed javascript was applied?

**Comment by brianteeman** [comment]
No need for a hint. Github does that for you. 

image

**Comment by richard67** [comment]
@brianteeman I know. But I am not really sure if new testers know that, too.

**Comment by brianteeman** [comment]
@richard67 well they should be reading the github post etc in order to test ;)

**Comment by C-Lodder** [comment]
@richard67 ah yes sorry, I keep forgetting.

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 0bfe005566b9a3350be6f1458d3635e471142ea9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28981">issues.joomla.org/tracker/joomla-cms/28981</a>.</sub>

**Comment by 810** [comment]
Can you also fix the modal. 

When selecting plugin - install - the modal is on the bottom of the page.

When i click on install again, the installer isn't loaded. Only on "install from url" i see the package url

**Comment by C-Lodder** [comment]
@810 Is that issue introduced by this PR?

**Comment by 810** [comment]
No, same issue as on core.

**Comment by richard67** [comment]
> When selecting plugin - install - the modal is on the bottom of the page.
 
Confirmed. The Install From Web seems to have some issues which are not fixed by this PR. Seems it needs more love.

@810 Do you get an error in browser console when trying to install with the button at the bottom?

**Comment by 810** [comment]
````
Uncaught TypeError: Joomla.submitbutton5 is not a function
    at HTMLInputElement.onclick (index.php?option=com_installer&view=install:349)
````

**Comment by C-Lodder** [comment]
@810 in which case can you please raise a separate issue?

**Comment by richard67** [comment]
@C-Lodder In the Install From Web is a green "Install" button at the top area. If you use that button, 2 new buttons are shown at the very bottom, a blue "Install" and a grey "Cancel". If you click the blue "Install" you get that error.

**Comment by richard67** [comment]
@C-Lodder Furthermore, as @810 pointed out, and I can confirm that, it seems that these 2 buttons should belong to a modal, but it is not a modal, it is integrated in the page.

Has all nothing to do with this PR. This PR doesn't change anything to worse. But maybe you can fix that with another PR?

**Comment by richard67** [comment]
I've just found an old meta-issue: https://github.com/joomla/joomla-cms/issues/19429 . @C-Lodder you were also involved in it, but it is a bit old.

**Comment by C-Lodder** [comment]
I'll start lookng into it now

**Comment by adj9** [comment]
@richard67 The logo loads it correctly. I realized now that the green taste of installazine does not work properly, on click it does nothing (Akeeba page e.g.) with & without PR.
Schermata 2020-05-07 alle 21 29 20

Sorry, I gave a hasty confirmation.

**Comment by richard67** [comment]
@adj9 Problem with install button and others are known, we have an issue for that: #19429 . So this PR here is ok. Thanks for testing.

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/28981">issues.joomla.org/tracker/joomla-cms/28981</a>.</sub>

**Comment by infograf768** [comment]
Tks.

**Pull request merged**
