### PR TITLE
Fixing the comment

### PR DESCRIPTION
**Pull request by artur-stepien**
Fixing the comment in captcha object as it's clearly wrong.

### Summary of Changes
Just fixing 2 comments to match what they describe.

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [X] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [X] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 84a42224a876510e40875da8f13b8220f80f7ac4<br /><br />Code Review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43773">issues.joomla.org/tracker/joomla-cms/43773</a>.</sub>

**Comment by richard67** [comment]
@artur-stepien The typos exist already in 4.4 so they should be fixed in the 4.4-dev branch. Release managers will later merge it up to the other branches when it has been merged into 4.4-dev.

Could you rebase to or redo on the 4.4-dev branch? Thanks in advance.

**Comment by richard67** [comment]
P.S.: See https://github.com/joomla/joomla-cms/blob/4.4-dev/libraries/src/Captcha/Captcha.php#L236

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 84a42224a876510e40875da8f13b8220f80f7ac4<br /><br />Code Review (J 4.4.6)<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/43773">issues.joomla.org/tracker/joomla-cms/43773</a>.</sub>

**Comment by richard67** [comment]
@chmst @ChristineWk New PR for 4.4-dev is #43888 . Could you "test" that one, too? Thanks in advance.

**Pull request closed without merging**
