### PR TITLE
[#33312] Also calls jQuery events on form submission

### PR DESCRIPTION
**Pull request by fredden**
This means that the event listeners in the HTML5-fallback library (which use jQuery) are also triggered. See JoomlaCode issue: http://joomlacode.org/gf/project/joomla/tracker/?action=TrackerItemEdit&tracker_item_id=33312

### CODE REVIEW

**Comment by dgt41** [comment]
@test success
Needs also the same mods in the compressed file!

Test instructions:
Apply patch
Enable debug
Open /administrator/components/com_content/views/article/tmpl/edit.php
and insert 
```php
JFactory::getDocument()->addScriptDeclaration('
jQuery(document).ready(function() {
	jQuery("#item-form").bind("submit", function() {
		console.log("works");
	});
});
');
```
just before ? > at around line 75

Try to create (save) an article, you should get in browsers log `works`

screen shot 2015-03-09 at 12 35 57

**Comment by dgt41** [comment]
@fredden Can you update the code as it says that there are conflicts?
Also can you apply the mod to the compressed file?

**Comment by fredden** [comment]
Okay, I've updated this pull request. Hopefully that's the correct procedure.
I've not tested this on a real site, but the Travis CI build passed.

**Comment by dgt41** [comment]
This `form.classOfForm` doesn’t work. Sorry I should have comment on that before, as I tried that recommendation but I forgot to write about it!

**Comment by fredden** [comment]
Thanks. Ideally I'd have tested before committing. Updated per your example @dgt41, still untested by me.

**Comment by dgt41** [comment]
@Fedik @Anibalsanchez can you take a look at this one?
@beat did you mean something like this:
```
        var formClass = jQuery(form).attr("class");
        jQuery(form, "."+formClass).submit();
```
?

**Comment by Fedik** [comment]
in theory should be enough just `jQuery(form).submit()` or `jQuery(form).trigger('submit');`.
I do not know what the reason to use some tricky `formClass`, the form could be without any `class`

**Comment by dgt41** [comment]
@Fedik This works with no problems for me as well, but @beat mentioned that an extra class selector should be in place. I think this is not necessary as we are triggering the event for a specific object, so I don’t see how this can conflict somehow with, lets say another form in the page...

**Comment by Fedik** [comment]
well, I do not see info that can confirm it on http://api.jquery.com/submit/
quick test show that it will not work, and form will be submitted when you trigger `submit` event on `form` element ... unless I missed something :smile:

**Comment by dgt41** [comment]
> This allows to prevent the default form submit if wanted
That was the exact reason @beat mentioned in the comment above, but I am not sure what he means or how this can be tested!

**Comment by Fedik** [comment]
>This allows to prevent the default form submit if wanted

this do not prevent, just try :wink: 

Maybe something like this can only trigger, and then submit by `form.submit()`:
```javascript
if(jquery){
  jQuery(form).submit(function (event) {
    event.preventDefault();
  });
  jQuery(form).submit();
}
form.submit()
```

but I do not see much sense it this :smile:

**Comment by anibalsanchez** [comment]
I concur, no need of tricky formClass. Besides, I could have to add more classes.

**Comment by dgt41** [comment]
So @Fedik @anibalsanchez @beat we all agree that this formClass is not needed?
@fredden Can I ask you to revert this without my and @beat ’s suggestion?

**Comment by dgt41** [comment]
@Fedik @anibalsanchez can you test it? @fredden reverted to the original `jQuery(form).submit();`

**Comment by Fedik** [comment]
**test** works good for me

**Comment by zero-24** [comment]
RTC based on testing Thanks!<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/3484">issues.joomla.org/joomla-cms/3484</a>.</sub>

**Comment by dgt41** [comment]
@mbabker It seems that the solution provided here doesn’t work for all cases e.g. #6207 (last comments)
Do we need a new PR to change it to `jQuery(form).trigger("submit");` or this can be done here?

**Comment by mbabker** [comment]
Do it as a PR please.  I manually merged this one due to conflicts and had to triple check myself when merging the compressed file changes; at least a PR (hopefully) has the right changes :smiley:

**Comment by dgt41** [comment]
ok will do that

**Pull request closed without merging**
