### PR TITLE
[4.0] Disallow using dashes in template name

### PR DESCRIPTION
**Pull request by joomdonation**
Pull Request for Issue #32621.

### Summary of Changes
Using dash "-" character in template causes potential issue as described at https://github.com/joomla/joomla-cms/issues/32621 . This PR adds validation to prevent using that character in template name. In general, we only accept Letters, numbers and underscore for template name as displayed in UI.

### Testing Instructions
1. Go to System -> Site Templates -> Cassiopeia Details and Files
2. Click on Copy Template button in the toolbar to create a copy of the template
3. Enter a template name contains - character, for example test-template-name
4. Before patch: Template is created
5. After patch: Template could not be created, there is error message displayed **Invalid template name. Please use only letters, numbers and underscores**

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 407c5a38baafb2cfc220a45d377ebc110a0b236b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34196">issues.joomla.org/tracker/joomla-cms/34196</a>.</sub>

**Comment by Abernyte-Git** [comment]
I have tested this item :white_check_mark: successfully on 407c5a38baafb2cfc220a45d377ebc110a0b236b<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34196">issues.joomla.org/tracker/joomla-cms/34196</a>.</sub>

**Comment by joomdonation** [comment]
RTC. Thanks !<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34196">issues.joomla.org/tracker/joomla-cms/34196</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
