### PR TITLE
[4.4] Web Asset Manager loads CSS from Joomla ROOT

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue #40395 .

### Summary of Changes

- better check

### Testing Instructions

Follow the issue (basically create a `template.min.css` in the root folder)

### Link to documentations
Please select:
No, it's a bug

@Fedik

### CODE REVIEW

**Comment by Fedik** [comment]
"It not a bug, it feature" :smile:

**Review by Fedik — APPROVED** [review]

**Comment by dgrammatiko** [comment]
> "It not a bug, it feature" 😄

Yes, I shouldn't mark this as a bug as the WAM and Joomla expects normally the assets inside the media folder. Then again it's hard to explain to people what is considered expected behaviour...

**Comment by Fedik** [comment]
I have tested this item :white_check_mark: successfully on a78e2cdd51bcaed48216530916ff8885974e4e78<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40409">issues.joomla.org/tracker/joomla-cms/40409</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on a78e2cdd51bcaed48216530916ff8885974e4e78<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40409">issues.joomla.org/tracker/joomla-cms/40409</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40409">issues.joomla.org/tracker/joomla-cms/40409</a>.</sub>

**Comment by dgrammatiko** [comment]
So is this for 4.3 or 4.4? I'm confused

**Comment by laoneo** [comment]
Yes we rebased it to 4.4 as it is no urgent bug which get fixed.

**Comment by laoneo** [comment]
Thanks!

**Pull request merged**
