### PR TITLE
Sync columns in contact_details table, add missing defaults, clean up

### PR DESCRIPTION
**Pull request by csthomas**
Pull Request for issue https://github.com/joomla/joomla-cms/issues/13289
To help #7680 on mssql

### Summary of Changes

1. Add missing defaults for columns [all db]:
* xreference
* sortname1, sortname2, sortname3
* ~~metakey, metadesc~~ - column type TEXT can not have default value for mysql

2. Add missing default for sqlsrv only:
* checked_out
* created_by_alias
* published

3. Remove defaults because that columns can not have default '' for :
* name
* alias
* language # for postgresql only

4. Remove `DEFAULT NULL` or alone `NULL` from sql files because this is redundant.

5. Clean up for postgresql:
Replace `DEFAULT 0 NOT NULL` to `NOT NULL DEFAULT 0`

Info:
https://github.com/joomla/joomla-cms/blob/staging/installation/sql/postgresql/joomla.sql#L264
https://github.com/joomla/joomla-cms/blob/staging/installation/sql/mysql/joomla.sql#L287

### Testing Instructions
Install joomla with applied changes. 
Installation should pass on all databases. 
Test create contact.

### CODE REVIEW

**Comment by joomdonation** [comment]
I have tested this item :white_check_mark: successfully on 308e1d3fa7e06216da08e236a842ebf482e9a3aa<br /><br />Installation works well. Contacts can be created both on com_contact component and  User - Contact Creator plugin

Please note that I only tested it on MySQL.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14113">issues.joomla.org/tracker/joomla-cms/14113</a>.</sub>

**Comment by waader** [comment]
I have tested this item :white_check_mark: successfully on 308e1d3fa7e06216da08e236a842ebf482e9a3aa<br /><br />I tested postgresql and mssql.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/14113">issues.joomla.org/tracker/joomla-cms/14113</a>.</sub>

**Comment by rdeutz** [comment]
@csthomas could you have a look if I fixed the conflicts right

**Comment by csthomas** [comment]
It is OK

**Pull request merged**
