### PR TITLE
Admin Menu: Components menu container menu items may go missing, tell users

### PR DESCRIPTION
**Pull request by izharaazmi**
Tell the users in advance that the default menu items under components menu container may go missing if unpublished.

On a clean install this may only be the case when the sample data pre-shipped or 3PD ones have it unpublished by default. However, there may be some be other cases where this may be helpful. Letting the user know doesn’t hurt anyway.

Pull Request for Issue #13630.

### Summary of Changes
Added note for the users when they set a menu item as a components menu container.

### Testing Instructions
Change the "components menu container" flag to yes – note should be shown.

### Documentation Changes Required
None

### CODE REVIEW

**Comment by izharaazmi** [comment]
@nikosdion If this should be sufficient for your issue #13630, you may close that. Otherwise my commitment stays.

**Comment by nikosdion** [comment]
Yes, Joomla! making it clear it's the expected behavior is an acceptable alternative.

**Comment by franz-wohlkoenig** [comment]
@izharaazmi i added a ` COM_MENUS_TYPE_CONTAINER ` to a custom Menu, got no Warning. There are missing lang-Strings:
bildschirmfoto 2017-02-22 um 18 46 27

**Comment by jeckodevelopment** [comment]
@izharaazmi can you please look at the conflicts?

**Comment by izharaazmi** [comment]
This PR is now invalid as we do not use published/unpublished state for container items. Sorry for missing on this.

**Pull request closed without merging**
