### PR TITLE
[4] cannot pass null to trim function in php 8.1

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue # .

### Summary of Changes
set a default value

### Testing Instructions

open admin

### Actual result BEFORE applying this Pull Request
image

### Expected result AFTER applying this Pull Request

no Exception

### CODE REVIEW

**Comment by HLeithner** [comment]
please stop adding `?? ''` blindly everywhere you seeing this error.

For example in this case we take the variable 2 lines above, so being sure that a string is returned should bin in this line.

Beside that `trim($xxx ?? '');` looks ugly and doesn't explain why we expect an empty variable at this point in the code. Please a proper if statement above and explain with a comment why it could be `NULL` (if it's not logical)

**Comment by alikon** [comment]
sound better now ?

**Comment by HLeithner** [comment]
thanks

**Review by wilsonge — APPROVED** [review]

**Comment by Krshivam25** [comment]
I have tested this item :white_check_mark: successfully on fb7a29de635e461154b7d04aa18fc552e78dedf3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36281">issues.joomla.org/tracker/joomla-cms/36281</a>.</sub>

**Comment by xillibit** [comment]
I have tested this item :white_check_mark: successfully on fb7a29de635e461154b7d04aa18fc552e78dedf3<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36281">issues.joomla.org/tracker/joomla-cms/36281</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36281">issues.joomla.org/tracker/joomla-cms/36281</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
