### PR TITLE
Fix multi-line assignments in array

### PR DESCRIPTION
**Pull request by frankmayer**
### Summary of Changes
Fix multi-line assignments in array

### Testing Instructions
None, code review only.

### Documentation Changes Required
None.

### CODE REVIEW

**Review by andrepereiradasilva — APPROVED** [review]

**Comment by laoneo** [comment]
I have tested this item :white_check_mark: successfully on ace797e1426859904e3c64b5f8bf9df425cd6acf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13441">issues.joomla.org/tracker/joomla-cms/13441</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on ace797e1426859904e3c64b5f8bf9df425cd6acf<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13441">issues.joomla.org/tracker/joomla-cms/13441</a>.</sub>

**Comment by jeckodevelopment** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13441">issues.joomla.org/tracker/joomla-cms/13441</a>.</sub>

**Comment by zero-24** [comment]
Thanks 👍

**Pull request merged**
