### PR TITLE
xml codestyle

### PR DESCRIPTION
**Pull request by brianteeman**
Fixes one that was missed and another that was merged without checking

### CODE REVIEW

**Comment by Quy** [comment]
Swap lines 709-710:
https://github.com/brianteeman/joomla-cms/blob/281ceee81b4e7d92f023581f74b80555e8d8fae2/components/com_content/views/categories/tmpl/default.xml#L710

**Comment by zero-24** [comment]
Looks good to me :+1:

**Review by zero-24 — APPROVED** [review]

**Comment by Quy** [comment]
Sorry one more:
https://github.com/brianteeman/joomla-cms/blob/9cda48eb07a254e2c4ea22b2bdabaff24ab0b0ff/components/com_content/views/categories/tmpl/default.xml#L465

Capitalize `JYes` and `JNo`. There are many instances of this in this file. Beyond the scope of this PR?
https://github.com/brianteeman/joomla-cms/blob/9cda48eb07a254e2c4ea22b2bdabaff24ab0b0ff/components/com_content/views/categories/tmpl/default.xml#L546

**Comment by brianteeman** [comment]
fixed the first - for the Jno etc i will do that in another pr when these are merged or we will get conflict fun

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 5a4f3e2527f52e11fa5f5e3c2b88371b166572f8<br /><br />Code review<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18251">issues.joomla.org/tracker/joomla-cms/18251</a>.</sub>

**Comment by ghost** [comment]
@zero-24 can i alter your Test as successfully?

**Comment by zero-24** [comment]
I have tested this item :white_check_mark: successfully on 5a4f3e2527f52e11fa5f5e3c2b88371b166572f8<br /><br />i have just done that myself<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/18251">issues.joomla.org/tracker/joomla-cms/18251</a>.</sub>

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
