### PR TITLE
[4.0] post install messages newsfeed [a11y]

### PR DESCRIPTION
**Pull request by brianteeman**
The title is "Release news from the Joomla! Project" but because of the positioning of the link a screen reader announces the unhelpful "the Joomla! Project".

This pr moves the link to the correct place so that the screen reader will announce ""Release news"

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 09837c80c9c1ee029047da177e5cba222099cbe1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27434">issues.joomla.org/tracker/joomla-cms/27434</a>.</sub>

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 09837c80c9c1ee029047da177e5cba222099cbe1<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27434">issues.joomla.org/tracker/joomla-cms/27434</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27434">issues.joomla.org/tracker/joomla-cms/27434</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Comment by brianteeman** [comment]
Thx

**Pull request merged**
