### PR TITLE
move2scheduler

### PR DESCRIPTION
**Pull request by alikon**
Pull Request for Issue # .

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
I can see what you are trying to do here. For b/c you cannot move2shceduler but you can add2scheduler

**Comment by alikon** [comment]
the day when I'll understand, this "fast moving target"...

is plugin covered with these strict b/ c policies ?

**Comment by brianteeman** [comment]
just think about it. 
moving would mean that something that currently happens by default with no user intervention will stop working and a user will need to setup and configure something that they never had to do before

**Comment by brianteeman** [comment]
if i was writing this then I would be copying to the the scheduler AND adding an instruction in the scheduler to disable the automatic process in the plugin.

**Comment by alikon** [comment]
i'll redo with the add instead of move

**Pull request closed without merging**
