### PR TITLE
[com_categories] Cleaner tree view

### PR DESCRIPTION
**Pull request by andrepereiradasilva**
Pull Request for Improvement.
#### Summary of Changes

This PR is a proposal to make a better visual to the trees in the list views of isis.

If accepted i can do in the other tree views (tags, menu items, etc).

As you can see from the code difference is just one line of code that changes.
###### Before PR (current scenario)

image
###### After PR (proposed scenario)

image
#### Testing Instructions
1. Use latest staging (the difference is more visible)
2. Apply patch
3. Go to content categories and check the visual difference
4. Do also some searches (with and without patch to check the difference)

### CODE REVIEW

**Comment by brianteeman** [comment]
Not convinced myself that this is any better than the current option. I
find that as the symbol looks like a letter L my eyes try to read it.

On 3 May 2016 at 14:45, andrepereiradasilva <notifications@github.com>
wrote:

> Pull Request for Improvement.
> Summary of Changes
>
> This PR is a proposal to make a better visual to the trees in the list
> views of isis.
>
> If accepted i can do in the other tree views (tags, menu items, etc).
>
> As you can see from the code difference is just one line of code that
> changes.
> Before PR (current scenario)
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/9630530/14984924/1e3146f2-113d-11e6-8782-1528e84ea7a8.png>
> After PR (proposed scenario)
>
> [image: image]
> <https://cloud.githubusercontent.com/assets/9630530/14984919/1a8e8190-113d-11e6-8372-425be9e6e13f.png>
> Testing Instructions
>
>    1. Use latest staging (the difference is more visible)
>    2. Apply patch
>    3. Go to content categories and check the visual difference
>    4. Do also some searches (with and without patch to check the
>    difference)
>
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/joomla/joomla-cms/pull/10213
> Commit Summary
>
>    - cleaner tree
>
> File Changes
>
>    - *M*
>    administrator/components/com_categories/views/categories/tmpl/default.php
>    <https://github.com/joomla/joomla-cms/pull/10213/files#diff-0> (2)
>
> Patch Links:
>
>    - https://github.com/joomla/joomla-cms/pull/10213.patch
>    - https://github.com/joomla/joomla-cms/pull/10213.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/10213>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by andrepereiradasilva** [comment]
we can add another symbol.
The main propose of this is to better understand the tree view and it's levels.

**Comment by brianteeman** [comment]
I understand the aim - I was just pointing out an issue (for me) with the
chosen symbol

On 3 May 2016 at 15:25, andrepereiradasilva <notifications@github.com>
wrote:

> we can add another symbol.
> The main propose of this is to better understand the tree view and it's
> levels.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/10213#issuecomment-216545420>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by brianteeman** [comment]
What do you think about changing your three vertical dots with a dash or even an elipsis (love the muted class you are using) and then using &#8627; `&#8627;`<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10213">issues.joomla.org/joomla-cms/10213</a>.</sub>

**Comment by andrepereiradasilva** [comment]
ok! will give it another try when i have time.

**Comment by BurtNL** [comment]
I have tested this item :white_check_mark: successfully on 28ffdc38fc1bc739909e39ed451bd25d73991f28<br /><br />Tested, works as described. The view has become clearer to me.
Looking forward to the setup as proposed by @brianteeman <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10213">issues.joomla.org/joomla-cms/10213</a>.</sub>

**Comment by andrepereiradasilva** [comment]
well i think it's a matter of taste.

some examples:

image

image

image

image

image

**Comment by andrepereiradasilva** [comment]
BTW, htmlentities used http://www.w3schools.com/charsets/ref_utf_box.asp

**Comment by andrepereiradasilva** [comment]
i prefer the last one because it's cleaner.

**Comment by BurtNL** [comment]
I agree with @andrepereiradasilva, I prefer the last example too.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10213">issues.joomla.org/joomla-cms/10213</a>.</sub>

**Comment by pe7er** [comment]
Great! Thanks @andrepereiradasilva, this is a huge UX improvement!

IMHO this version is the most clear one:
Category-overview
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10213">issues.joomla.org/joomla-cms/10213</a>.</sub>

**Comment by andrepereiradasilva** [comment]
lol, each one likes a different one.
I think this is going to have to be a PLT decision.

The goal is to apply this to all the items with tree structures (menus, access level, tags, categories, etc) so we can have a consistent trre structure across all views.

pinging @wilsonge for a decision.

**Comment by brianteeman** [comment]
Set to Needs Review - not sure if its PLT or UI team on this one<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10213">issues.joomla.org/joomla-cms/10213</a>.</sub>

**Comment by wilsonge** [comment]
I prefer the last one (i.e. https://cloud.githubusercontent.com/assets/9630530/15011868/1e7a8592-11ec-11e6-9e4e-69e91f4a7292.png) - I think the arrows Brian proposed are not rendering consistently between platforms (I can see large differences between windows and mac). So I think this is the next best solution

**Comment by andrepereiradasilva** [comment]
is that a opinion or a decision?

**Comment by brianteeman** [comment]
I think I agree with @wilsonge

Can you update the PR to use that styling so it can be tested in real life<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10213">issues.joomla.org/joomla-cms/10213</a>.</sub>

**Comment by andrepereiradasilva** [comment]
yes, once i remember the character i used for the dash :wink:

**Comment by andrepereiradasilva** [comment]
ok done

**Comment by brianteeman** [comment]
Are you sure thats the correct symbol the dash looks very narrow 
screen shot 2016-05-16 at 16 46 32<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10213">issues.joomla.org/joomla-cms/10213</a>.</sub>

**Comment by andrepereiradasilva** [comment]
hum Mac right?
in Windows
image

**Comment by brianteeman** [comment]
yes - a mac ;)

On 16 May 2016 at 22:50, andrepereiradasilva <notifications@github.com>
wrote:

> hum Mac right?
> in Windows
> [image: image]
> <https://cloud.githubusercontent.com/assets/9630530/15305025/9f136ebe-1bb8-11e6-85e8-da0ccb4da20c.png>
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/10213#issuecomment-219559414>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by andrepereiradasilva** [comment]
is ok now?

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on e0d34507a0746e4aad8b571304c8ccb642bd74ed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10213">issues.joomla.org/joomla-cms/10213</a>.</sub>

**Comment by brianteeman** [comment]
Yes thats it - screenshot for reference 

screen shot 2016-05-16 at 17 02 35<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10213">issues.joomla.org/joomla-cms/10213</a>.</sub>

**Comment by andrepereiradasilva** [comment]
ok @wilsonge, so do we have an ok on this tree view?

**Comment by wilsonge** [comment]
Yes :)

**Comment by andrepereiradasilva** [comment]
ok then, so when this gets tested and eventually merged i will do PR for the others tree like structures (tags, menus and user groups).

**Comment by MATsxm** [comment]
I have tested this item :white_check_mark: successfully on e0d34507a0746e4aad8b571304c8ccb642bd74ed<br /><br />Like this way :+1: - thanks<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/10213">issues.joomla.org/joomla-cms/10213</a>.</sub>

**Comment by wilsonge** [comment]
You'd better get moving then :) Merged with two good tests!

**Comment by andrepereiradasilva** [comment]
no pressure right? ;)

**Pull request merged**
