### PR TITLE
[4.3] Template Media folder should never disappear

### PR DESCRIPTION
**Pull request by dgrammatiko**
Pull Request for Issue https://github.com/joomla/joomla-cms/pull/40712#issuecomment-1575687382

### Summary of Changes

Template Media folder should never disappear 

### Testing Instructions

- Create a Child template
- Delete all the folders of the media folder

### Actual result BEFORE applying this Pull Request

Media folder disappears

### Expected result AFTER applying this Pull Request

Media folder doesn't disappear

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [x] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on dcb7b79dd4c6d373c124423e48ae764dfaab9a21<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40719">issues.joomla.org/tracker/joomla-cms/40719</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on dcb7b79dd4c6d373c124423e48ae764dfaab9a21<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40719">issues.joomla.org/tracker/joomla-cms/40719</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/40719">issues.joomla.org/tracker/joomla-cms/40719</a>.</sub>

**Comment by obuisard** [comment]
Thank you Dimitris @dgrammatiko for the PR :-)

**Pull request merged**
