### PR TITLE
[Associations] Correcting Copy Reference to Target issue

### PR DESCRIPTION
**Pull request by infograf768**
Pull Request for Issue https://github.com/joomla/joomla-cms/issues/16168

### Summary of Changes
`src` is used elsewhere in the js. 
Therefore the error was to use `data-url`

### Testing Instructions
Patch. Clear all caches.

### After Patch
All should be fine.

multiassoc_copy

@appnweb @brianteeman @PhilETaylor @AlexRed @alikon

### CODE REVIEW

**Comment by AlexRed** [comment]
I have tested this item :white_check_mark: successfully on 788f99cb6cd574a161335395d9d7d3663a085a88<br /><br />Patch ok for me<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16178">issues.joomla.org/tracker/joomla-cms/16178</a>.</sub>

**Comment by brianteeman** [comment]
I have tested this item :white_check_mark: successfully on 788f99cb6cd574a161335395d9d7d3663a085a88<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/16178">issues.joomla.org/tracker/joomla-cms/16178</a>.</sub>

**Comment by PhilETaylor** [comment]
Did everyone also test to see if this still fixes the race condition?

Im not convinced that this is the correct fix, all this does is revert my race condition fix, and put a iframe reload in place, the race condition would still be present, but masked.

**Comment by brianteeman** [comment]
No i didnt as I couldnt replicate that before

**Comment by infograf768** [comment]
I did not get any race condition anymore ( You are not permitted, etc.)

**Comment by dgt41** [comment]
@PhilETaylor you can still have your code back here with a little more code, e.g. have a container div with all the attributes the iframe needs and then **create** the iframe element in runtime. That will cover the race conditions, I guess

**Comment by infograf768** [comment]
If a variable is changed —in this case the variable `src` was changed to `data-url` in the edit form, then it should have been changed all over the js when the target is loaded. That was not the case and it indeed broke the target reload.

**Comment by PhilETaylor** [comment]
If it works it works.

**Comment by PhilETaylor** [comment]
The copy to reference is a huge crap load of functions, it first saves the article in the left pane, then loads an article in the left pane, then decides its the wrong language and so loads the initial language in the left pane, and then finally loads the right pane.... 

The whole component is badly written - because it tried to reuse existing core features (like tmpl=component)...

So if this fixes the race and fixes the copy then excellent...

**Comment by infograf768** [comment]
I hope someone will improve all this in 4.0 😺

**Pull request merged**
