### PR TITLE
[4.0] Moved error messages from the labels to the field controls.

### PR DESCRIPTION
**Pull request by todordev**
### Summary of Changes
The error message does not look good if I reduce the gap between the labels and the fields.

### Testing Instructions
Merge this PR and generate the scripts.
`npm run build:js`

### Before
error_message_before

### After
error_message_after

### CODE REVIEW

**Comment by dgrammatiko** [comment]
No! You are doing it wrong!
- element.closest() needs a polyfill for ie so that will not work
- making a totally neutral js file to be bootstrap markup dependent is not really clever

**Comment by brianteeman** [comment]
> element.closest() needs a polyfill for ie so that will not work

This is no longer wrong as the production department have decided to adopt a browser support policy of PROD2019/005 - Change minimum version requirements for all browsers to n-2 and drop support for Internet Explorer. https://volunteers.joomla.org/departments/production/reports/1031-production-dept-meeting-may-28-2019

**Comment by Schmidie64** [comment]
I have tested this item :red_circle: unsuccessfully on 631de8deceeab8843e5a7fb2958b0507cbf2a7a0<br /><br />The described behavior, I can not reproduce in the newest Joomla 4 version. The error message looks the same before and after applying the patch.
2019-09-02 11_28_49-Window

**System**: 
PHP Build On: Windows NT 10.0 build 18362 (Windows 10) i586
10.1.37-MariaDB
PHP-Version: 7.3.0
Webserver: Apache/2.4.37 (Win32) OpenSSL/1.1.1a PHP/7.3.0
Joomla! Version: 	Joomla! 4.0.0-alpha12-dev Development [ Amani ] 19-August-2019 13:40 GMT
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.132 Safari/537.36

<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23975">issues.joomla.org/tracker/joomla-cms/23975</a>.</sub>

**Comment by itsMeAnimated** [comment]
I have tested this item 🔴 unsuccessfully on 631de8d
The error message looks the same before and after applying the patch on the newest Joomla 4 version. 

**System :**

PHP Built On 	 : Linux  4.15.0-58-generic #64-Ubuntu 
Database Version :	10.4.6-MariaDB
PHP Version 	 : 7.3.8
Web Server 	 : Apache/2.4.39 (Unix) OpenSSL/1.0.2s PHP/7.3.8 mod_perl/2.0.8-dev Perl/v5.16.3
Joomla! Version  : Joomla! 4.0.0-alpha12-dev Development [ Amani ] 19-August-2019 13:40 GMT
User Agent 	 : Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:68.0) Gecko/20100101 Firefox/68.0 <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23975">issues.joomla.org/tracker/joomla-cms/23975</a>.</sub>

**Comment by HRIT-Florian** [comment]
I have tested this item :red_circle: unsuccessfully on 631de8deceeab8843e5a7fb2958b0507cbf2a7a0<br /><br />The PR is from february. Meanwhile the msg is different styled and the issue could not been reproduzed.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23975">issues.joomla.org/tracker/joomla-cms/23975</a>.</sub>

**Comment by jduerscheid** [comment]
Loks this way at the moment without the patch, so I think this PR can be removed:
screen shot 2019-10-19 at 12 54 57<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/23975">issues.joomla.org/tracker/joomla-cms/23975</a>.</sub>

**Comment by zero-24** [comment]
Closing as reported above this is no longer required.

**Pull request closed without merging**
