### PR TITLE
[4.0] itemid is overruled when system - sef is enabled #35570

### PR DESCRIPTION
**Pull request by 810**
Pull Request for Issue #35570 .

### Summary of Changes
Allow itemid from other menu then from the main menu. Now its getting overruled by the default menu item.

### Testing Instructions

Apply patch.

Add hardcode html:

`<a href="index.php?option=com_kunena&view=topic&layout=reply&catid=2&id=37&Itemid=151">
	test
</a>`

### Actual result BEFORE applying this Pull Request

`<a href="/j4/index.php?option=com_kunena&amp;view=topic&amp;layout=reply&amp;catid=2&amp;id=37&amp;Itemid=101">
	test
</a>`

### Expected result AFTER applying this Pull Request

`<a href="/j4/index.php?option=com_kunena&amp;view=topic&amp;layout=reply&amp;catid=2&amp;id=37&amp;Itemid=151">
	test
</a>`

### CODE REVIEW

**Comment by PhilETaylor** [comment]
The comments being removed were added in https://github.com/joomla/joomla-cms/pull/12020 by @wilsonge and the code is from https://github.com/joomla/joomla-cms/pull/18260 from @csthomas 

It might be useful to get their comments on this change, as it seems the code being removed/changed has history and has a lot of thought put into it previously. 

It would also be worth checking those two PR's above, and ensuring that this PR doesnt reintroduce the bugs those fix.

**Comment by 810** [comment]
Any comments? I don't know why you always needs the active menu. Thats only needed, when have a simple website. 

If you have complicated website with multiple menus, then this "feature" (active menu item matches the requested query)  doesn't make any sense for me.

**Comment by xillibit** [comment]
The line before the change in this PR is identical on J! 3.10.x, the issue was in Kunena, i have found a weird change in KunenaRoute which have reverted it which solve the issue. But we still lose the Kunena menu when we are on views which use pagination and when going to anther page

**Comment by HLeithner** [comment]
This pull request has automatically rebased to 4.2-dev.

**Comment by bembelimen** [comment]
So we can't just use any give Itemid.

I agree that we should not throw away valid Itemids but we have to check if they're valid. Could you please improve your PR in that regards?

**Comment by HLeithner** [comment]
This pull request has been automatically rebased to 4.3-dev.

**Comment by HLeithner** [comment]
This pull request has been automatically rebased to 4.4-dev.

**Pull request closed without merging**
