### PR TITLE
[4.0] Changing phpcs to run from composer and a generic image in drone

### PR DESCRIPTION
**Pull request by Hackwar**
What the title says.

### CODE REVIEW

**Comment by rdeutz** [comment]
The idea to let phpcs run as early as possible is the this is cheap and fast. It gives the developer a soon notice that the coding style is not correct. This is not a good idea, it will bind our resources for a longer timeframe, because as we know most of the PR needs corrections for code styles.

**Comment by HLeithner** [comment]
It looks like it's still the same order but uses not a custom image or Hannes?

**Comment by rdeutz** [comment]
@HLeithner if you look at the failed build you will see it runs after the prepare step, so a failed build will need 6 minutes more than before. I made a docker image based on 7.2-cli and installed phpcs v2 within it

**Comment by wilsonge** [comment]
@rdeutz the issue is we want to run phpcs from the standards located here https://github.com/joomla/coding-standards which means we need to have run composer install first (although not the npm install). So unless we separate them (which would be fine - i think npm is the majority of the 6 minutes). we have to run after prepare

**Comment by HLeithner** [comment]
@rdeutz oops didn't notice this...

**Comment by rdeutz** [comment]
@wilsonge we can do this as part of the docker image build, we are cache composer anyway. We really need to make this as quick as possible and is not something that change every hour

**Comment by wilsonge** [comment]
That's absolutely fine. The cached version of composer should be just fine for this!

**Comment by Hackwar** [comment]
I've updated the order of steps and that should make it rather fast enough. Unfortunately we seem to have a discrepancy between the sniffs in our phpcs image and our repo or something like that. Anyway, it fails at that one file.

**Comment by Hackwar** [comment]
I excluded the node_modules folder and now this passes. (I also ordered the excluded folders alphanumerically.)

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
