### PR TITLE
[4.2] Fix permission overridecheck quickicon

### PR DESCRIPTION
**Pull request by heelc29**
### Summary of Changes

The permission for show the quickicon and the link/ajax do not match (`com_installer` vs. `com_templates`)
https://github.com/joomla/joomla-cms/blob/e9b9263a34ad919c7a8e6b817074f53eb1997565/plugins/quickicon/overridecheck/overridecheck.php#L68-L77

### Testing Instructions

Check the admin dashboard with a user with these permissions:
image

### Actual result BEFORE applying this Pull Request

Ajax request get 403 status (forbidden)
image
image

When you click on the quickicon
image

### Expected result AFTER applying this Pull Request

The quickicon is no longer displayed

Now if you swap permissions for com_installer/com_templates, the quickicon works correctly:
image
image

### Link to documentations
Please select:
- [x] No documentation changes for docs.joomla.org needed
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by carlitorweb** [comment]
I have tested this item :white_check_mark: successfully on 9427139c8d8e4fef16e4d3216d9e3e3dd34c9238<br /><br />**Note:** For get the right permission the test require, is enough with create a user under Registered group and add the "Access Administration Access" from the global configuration permissions. From there you can follow the test indication.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39485">issues.joomla.org/tracker/joomla-cms/39485</a>.</sub>

**Comment by viocassel** [comment]
I have tested this item :white_check_mark: successfully on 9427139c8d8e4fef16e4d3216d9e3e3dd34c9238<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39485">issues.joomla.org/tracker/joomla-cms/39485</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/39485">issues.joomla.org/tracker/joomla-cms/39485</a>.</sub>

**Comment by roland-d** [comment]
Thank you

**Pull request merged**
