### PR TITLE
change show_page_heading default

### PR DESCRIPTION
**Pull request by radiant-tech**
The param show_page_heading still defaults to 1 in some views of com_content and in com_search which is not the desired default behavior.

This was supposedly changed in 2.5 (see Tracker #28682) , but it's back again.  Providing this for the sake of code consistency across components.

### CODE REVIEW

**Comment by designbengel** [comment]
Where should it be tested, please? Is it regarding the page title of an article?<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/3186">issues.joomla.org/joomla-cms/3186</a>.</sub>

**Comment by bembelimen** [comment]
@test Works, but I think it's not B/C

**Comment by brianteeman** [comment]
Why not?

**Comment by bembelimen** [comment]
If the parameter is not set, the title will be displayed (before patch), with the patch the title will not be displayed anymore.

**Comment by sovainfo** [comment]
View an article, category blog, archive and search. When they don't give a problem, it works.

Considering the changes in the past it can't be avoided to result in changed behaviour. Expecting this to be the desired behaviour.

**Comment by continga** [comment]
Obviously this is already patched in the actual staging version.

**Comment by nonumber** [comment]
@roland-d Please close. Already fixed in staging.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="http://issues.joomla.org/tracker/joomla-cms/3186">issues.joomla.org/joomla-cms/3186</a>.</sub>

**Comment by zero-24** [comment]
Closing as requested thanks @nonumber

**Pull request closed without merging**
