### PR TITLE
[4.0] Alias menu item types not working in admin menus

### PR DESCRIPTION
**Pull request by SharkyKZ**
Pull Request for Issue # .

### Summary of Changes

Fixes query error preventing alias menu item types from showing in admin menus.

### Testing Instructions

Create admin menu.
Create a menu item.
Create an alias for that menu item.
Publish a menu module.

### Expected result

Menu item and its alias are showing.

### Actual result

Only first menu item is shown.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by infograf768** [comment]
I am a bit confused here.
Could you add screenshots for before and after patch?

**Comment by infograf768** [comment]
OK, I understood. You meant create a "Menu Item Alias" type.
Tested and indeed your PR solves the issue.

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 7314ca26cbaba8d1c62b9d27c4fea41b697b8d02<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26625">issues.joomla.org/tracker/joomla-cms/26625</a>.</sub>

**Comment by waader** [comment]
I have tested this item :white_check_mark: successfully on 7314ca26cbaba8d1c62b9d27c4fea41b697b8d02<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26625">issues.joomla.org/tracker/joomla-cms/26625</a>.</sub>

**Comment by SharkyKZ** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26625">issues.joomla.org/tracker/joomla-cms/26625</a>.</sub>

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
