### PR TITLE
[4.0] Webinstaller

### PR DESCRIPTION
**Pull request by N6REJ**
Pull Request for Issue # .
#26716
### Summary of Changes
The installer isn't a "web" installer like whmcs et al so lets not call it that.

### Testing Instructions
Do a clean install of 4.0-dev.
Check Installer title 
Apply patch
Test again.

### Expected result
image

### Actual result
image

### CODE REVIEW

**Comment by wilsonge** [comment]
Remove the package lock file changes please :)

**Comment by softforge** [comment]
I have tested this item :white_check_mark: successfully on 0837fe18dc63908675a027548f448e3904b8abb7<br /><br />Web removed (yep they whole web with one PR) <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26717">issues.joomla.org/tracker/joomla-cms/26717</a>.</sub>

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 0837fe18dc63908675a027548f448e3904b8abb7<br /><br />Code review is sufficient, I see no need for a real test.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/26717">issues.joomla.org/tracker/joomla-cms/26717</a>.</sub>

**Comment by richard67** [comment]
@N6REJ Yes, George is right, undo the package.lock changes.

**Comment by N6REJ** [comment]
UGH!

**Pull request closed without merging**
