### PR TITLE
[4.0] Typo in language string

### PR DESCRIPTION
**Pull request by Bakual**
A translator notified me of this typo. Can be merged by review.

### CODE REVIEW

**Comment by brianteeman** [comment]
good spot

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 9cf1c5a267056344201999295e50be1743373575<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27600">issues.joomla.org/tracker/joomla-cms/27600</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 9cf1c5a267056344201999295e50be1743373575<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27600">issues.joomla.org/tracker/joomla-cms/27600</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27600">issues.joomla.org/tracker/joomla-cms/27600</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Comment by horus68** [comment]
@Bakual same error in file File: joomla.ini 
INSTL_DATABASE_ENCRYPTION_MSG_CONN_NOT_ENCRYPT

**Comment by Bakual** [comment]
Thanks, created PR: https://github.com/joomla/joomla-cms/pull/27616

**Pull request merged**
