### PR TITLE
Remove unneeded queries in featured feed

### PR DESCRIPTION
**Pull request by SharkyKZ**
### Summary of Changes

Removes unneeded queries.

### Testing Instructions

In Articles component options, in `Integration` tab set `Include in Feed` option to `Full Text`.
Create an article with read more.
Make it featured.
View featured feed (`index.php?option=com_content&view=featured&format=feed`).

### Expected result

Full article text appears like before patch.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by uGE70** [comment]
I have tested this item :white_check_mark: successfully on ba7b09969db5269d98f6511d957a716ddda180f8<br /><br />Created a featured article with a read more short code
Set to Full Text in RSS feed
After patch applied, full text is displayed in RSS feed<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25965">issues.joomla.org/tracker/joomla-cms/25965</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on ba7b09969db5269d98f6511d957a716ddda180f8<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25965">issues.joomla.org/tracker/joomla-cms/25965</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/25965">issues.joomla.org/tracker/joomla-cms/25965</a>.</sub>

**Comment by HLeithner** [comment]
Thanks for care about rss feeds.

**Pull request merged**
