### PR TITLE
Disable password reset requirement when user resets password

### LINKED ISSUE #27147: 'Forgotten Password' process doesn't clear 'Password Reset Required' flag if set
### Steps to reproduce the issue
1) Set the 'Require Password Reset' flag on a user using the Administrator interface
2) Assume the role of that user, but who's forgotten their password
3) Use the 'Forgotten Password' process flow
4) Upon completing the password reset, when the user logs in, they are immediately asked to reset their password again.

### Expected result
A 'Forgotten Password' reset should satisfy a pending 'Require Password Reset' and clear that flag if set.

### Actual result
The user must reset their password twice.

### System information (as much as possible)
Joomla! Version 3.9.13
Joomla! Platform Version 13.1.0 Stable
PHP 7.3.11
Apache 2.4.41
Server OS Ubuntu

### Additional comments
Requiring the user to reset the password immediately after they've just completed that process is superfluous and a less than ideal UX which could lead to confusion and additional calls for support to system Administrators.

### PR DESCRIPTION
**Pull request by SharkyKZ**
Closes #27147.

### Summary of Changes

Disable `Password Reset Required` flag when after users complete password reset.

### Testing Instructions

Create a user. Set "Require Password Reset" to `Yes`.
In frontend, use password reset form for that user.
Reset the password.
Login.

### Expected result

Not required to reset password again.

### Actual result

Required to reset password again.

### Documentation Changes Required

No.

### CODE REVIEW

**Comment by mbabker** [comment]
This should not be needed in component level MVC.  There is logic in the User class to take care of clearing the flag if the class is actually used correctly.

**Comment by SharkyKZ** [comment]
@mbabker Thanks for the tip. I hope this is what you meant.

**Comment by mbabker** [comment]
Looks right just going from memory.

**Comment by vbv2312** [comment]
can i as a beginner work on this issue to contrive a patch ??please can anyone guide me i am new to open source <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27413">issues.joomla.org/tracker/joomla-cms/27413</a>.</sub>

**Comment by SharkyKZ** [comment]
@vbv2312 this is already a patch for issue #27147. No need for another patch for the same issue, unless you have a better/nicer solution. Other than that, yes, you can work on any issue you want and don't need to ask for permission. See this documentation page for information about contributing https://docs.joomla.org/Portal:Joomla!_Code_Contributors.

**Comment by vbv2312** [comment]
Can you please suggest some good first bugs for me I am a beginner and want to contribute . Thanks

**Comment by alikon** [comment]
@vbv2312  you could simply test this one for start https://docs.joomla.org/Testing_Joomla!_patches

**Comment by vbv2312** [comment]
> @vbv2312 you could simply test this one for start https://docs.joomla.org/Testing_Joomla!_patches

okk can you please lay out some more tasks so that i can brush up my contribution to open source

**Comment by alikon** [comment]
Have you tested this PR ?
if yes, you  should "Record your test results" as reported here https://docs.joomla.org/Testing_Joomla!_patches

**Comment by jwaisner** [comment]
I have tested this item :white_check_mark: successfully on 1c2d32e2482eae8d40be7db9c11cfb8f463c713c<br /><br />Works great. Flag is disabled after user resets password.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27413">issues.joomla.org/tracker/joomla-cms/27413</a>.</sub>

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 1c2d32e2482eae8d40be7db9c11cfb8f463c713c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27413">issues.joomla.org/tracker/joomla-cms/27413</a>.</sub>

**Comment by Quy** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/27413">issues.joomla.org/tracker/joomla-cms/27413</a>.</sub>

**Comment by HLeithner** [comment]
Thanks

**Pull request merged**
