### PR TITLE
[4.2] tag selection in article category menus

### PR DESCRIPTION
**Pull request by brianteeman**
Related Pull Request for Issue #38087 .

### Summary of Changes
When creating a menu item of type article-category or article-list you can filter by tags.
This PR Prevents the ability to create new tags when selecting tags. They're not actually created anyway and it doesnt make sense that you would be able to create a new tag here anyway.

This PR uses a field attribute `custom="deny"` to prevent the fake ability to create a new tag.

### Testing Instructions
Create a few articles with tags
Create an arrticle categoru blog and categpory list menu and select existing tags AND try to type in a non-existing tag and hit enter

### Before
image

### After
image

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on 72b8d089ae9599b09b5115534a6cc48fcd634a5c<br /><br />Test on menu item type Category Blog and Category List.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38088">issues.joomla.org/tracker/joomla-cms/38088</a>.</sub>

**Comment by ChristineWk** [comment]
I have tested this item :white_check_mark: successfully on 72b8d089ae9599b09b5115534a6cc48fcd634a5c<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38088">issues.joomla.org/tracker/joomla-cms/38088</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/38088">issues.joomla.org/tracker/joomla-cms/38088</a>.</sub>

**Comment by roland-d** [comment]
Thanks everybody

**Pull request merged**
