### PR TITLE
[4.1] Jooa11y string

### PR DESCRIPTION
**Pull request by brianteeman**
Pull Request for Issue #37280 .

### Summary of Changes
Simple change of the constant for one string

### CODE REVIEW

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 6a283a18e2d7baefe03942712ed602c5729e2b37<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37283">issues.joomla.org/tracker/joomla-cms/37283</a>.</sub>

**Comment by brianteeman** [comment]
@chmst as you never responded before and this underline test was your request can you please confirm that it is what you were looking for

**Comment by Kostelano** [comment]
I have tested this item :white_check_mark: successfully on 6a283a18e2d7baefe03942712ed602c5729e2b37<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37283">issues.joomla.org/tracker/joomla-cms/37283</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/37283">issues.joomla.org/tracker/joomla-cms/37283</a>.</sub>

**Comment by Quy** [comment]
Thanks

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
