### PR TITLE
regression: Make tinyMCE's buttons behave

### PR DESCRIPTION
**Pull request by dgrammatiko**
#### Moving code from onInit() to OnDisplay()

The reason for this is that only the function onDisplay contains all the needed variables to correctly setup the initialisation script. Solves https://github.com/joomla/joomla-cms/issues/8712
#### Testing

Edit a category with editor set to tinymce. The buttons ReadMore and Pagebreak SHOULD NOT display, but they do.
Apply patch retry editing a category. The buttons ReadMore and Pagebreak DO NOT display.

### CODE REVIEW

**Comment by infograf768** [comment]
I have tested this item :white_check_mark: successfully on 60495d91cc9c16859ec747f93d019857b868a1f4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8716">issues.joomla.org/joomla-cms/8716</a>.</sub>

**Comment by JerryChr** [comment]
I have tested this item :red_circle: unsuccessfully on 60495d91cc9c16859ec747f93d019857b868a1f4<br /><br />Video of my test and the issues that occured http://screencast.com/t/iTofr0wruP5H
Tested on Win10 XAMPP PHP 5.5 and Ubuntu 4.14 PHP 5.5.9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8716">issues.joomla.org/joomla-cms/8716</a>.</sub>

**Comment by infograf768** [comment]
@JerryChr 

have you cleaned all caches after patching?

**Comment by JerryChr** [comment]
@infograf768 yes and also tested in FireFox, Chrome and IE.
Just checked again and opened the console to see if there was anything in there - it gives me this:
Failed to load resource: the server responded with a status of 404 (Not Found)
Failed to load: media/editors/tinymce/plugins/jdragdrop/plugin.min.js in tinymce.min.js:4

**Comment by infograf768** [comment]
>Failed to load: media/editors/tinymce/plugins/jdragdrop/plugin.min.js in tinymce.min.js:4

is the culprit as this is in 3.5.0-dev/staging

I suggest you install a new staging ( https://github.com/joomla/joomla-cms/archive/staging.zip ), then patchtester, then this PR

**Comment by JerryChr** [comment]
@infograf768 Of course.. Think I need to debug my sleepy brain today instead.
Works on staging - will mark it succesfull now.

**Comment by JerryChr** [comment]
I have tested this item :white_check_mark: successfully on 60495d91cc9c16859ec747f93d019857b868a1f4<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8716">issues.joomla.org/joomla-cms/8716</a>.</sub>

**Comment by infograf768** [comment]
RTC as 2 good tests<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/8716">issues.joomla.org/joomla-cms/8716</a>.</sub>

**Comment by dgt41** [comment]
Just added the two lines from #8711, to test follow the test instructions on #8711

**Comment by infograf768** [comment]
I have an issue here in multilingual sites with custom.css, which I never remarked before.

In multilanguage, this will give a confusing result as we have one Home per Content Language and one could choose a different template (not only style) per language. 
This code returns Beez instead of protostar 
```
			$db    = JFactory::getDbo();
			$query = $db->getQuery(true)
				->select('template')
				->from('#__template_styles')
				->where('client_id=0 AND home=' . $db->quote('1'));

			$db->setQuery($query);
			try
			{
				$template = $db->loadResult();
			}
```
When we choose Beez as default template for Language All 


screen shot 2015-12-19 at 11 51 35

My suggestions :
1. Modify the tip
2. Introduce the case of multilanguage by displaying an error if the field is not filled with a full url.

What do you think?

--------------------------------------------------------

Note: concerning IPv6, it does not load the file here locally with MAMP, i.e. with an url of the type
`http://[::1]:8888/trunkgitnew/`
or
`http://[0:0:0:0:0:0:0:1]:8888/trunkgitnew/`

where joomla is installed in the trunkgitnew folder.
Source shows:
```
content_css : "http://[0:0:0:0:0:0:0:1]:8888/trunkgitnew/templates/system/css/editor.css",
			document_base_url : "http://[0:0:0:0:0:0:0:1]:8888/trunkgitnew/",
```
As that may be expected I can't test it good or wrong.

**Comment by dgt41** [comment]
@infograf768 For the multilingual part I would say that a modified tooltip that will point to the default for all languages is good enough. Trying to sort it out otherwise will be tricky I guess, not in front of my pc to actually test it.
About the second IPv6 and custom css, I think I forgot to change to `Juri::root(true)` which worked in the other PR

**Comment by infograf768** [comment]
Even after changing to `JUri::root(true)` here, it does not work although we have now a relative link (corrected slash). Example:
```
content_css : "/trunkgitnew/templates/system/css/editor.css",
			document_base_url : "http://[0:0:0:0:0:0:0:1]:8888/trunkgitnew/",
```
But this could be due to MAMP here.


By the way this needs another slash before `templates` as @Fedik rightfully suggested in the other PR. Should be:
`$content_css = 'content_css : "' . JUri::root(true) . '/templates/' . $template . '/css/' . $content_css_custom . '",';`
`$content_css = 'content_css : "' . JUri::root(true) . '/templates/system/css/editor.css",';`
`$content_css = 'content_css : "' . JUri::root(true) . '/templates/' . $template . '/css/editor.css",';`

**Comment by dgt41** [comment]
@infograf768 what version of mamp are you using? (I'm on 3.5)

**Comment by infograf768** [comment]
2.1.1 

(anyway needs the slash ☺ )

**Comment by dgt41** [comment]
@infograf768 ok done!

**Comment by infograf768** [comment]
Milestone here has to be 3.5.0

**Pull request merged**
