### PR TITLE
[4.1] s/algorightms/algorithms

### PR DESCRIPTION
**Pull request by brianteeman**
typo

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 9666b7c2ee9756b112d5b0990efae72f4b0a6e2f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36819">issues.joomla.org/tracker/joomla-cms/36819</a>.</sub>

**Comment by chmst** [comment]
I have tested this item :white_check_mark: successfully on 9666b7c2ee9756b112d5b0990efae72f4b0a6e2f<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36819">issues.joomla.org/tracker/joomla-cms/36819</a>.</sub>

**Comment by chmst** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/36819">issues.joomla.org/tracker/joomla-cms/36819</a>.</sub>

**Comment by bembelimen** [comment]
Thx

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
