### PR TITLE
[4.0] Fix Article Versions JS error

### PR DESCRIPTION
**Pull request by Arpit-24**
Pull Request for Issue #23811 .

### Summary of Changes

Added special function that will be used when browser is IE11 and returns the closest element

### Testing Instructions

npm ci is required
In IE11, open any article in your Article Manager
Click the "Versions" button
Check any of the checkboxes

### Actual result

No error in console now

### Documentation Changes Required

None

### CODE REVIEW

**Comment by ghost** [comment]
@C-Lodder please test.

**Comment by C-Lodder** [comment]
At work so can't properly test.
Looks fine from a code review. Just need to fix the Hound violations

**Comment by Arpit-24** [comment]
> At work so can't properly test.
> Looks fine from a code review. Just need to fix the Hound violations

Fixed hound violations

**Comment by wilsonge** [comment]
Thanks!

**Pull request merged**
