### PR TITLE
Categories and Category model cleanup

### PR DESCRIPTION
**Pull request by joomdonation**
Pull Request for Issue # .

### Summary of Changes
Some clean up to Categories and Category model of com_contnet:

- Code simplify for getting active menu item
- Remove un-used class properties for Category Model
- Added missing class properties for Category Model
- Correct return data type and docblock for some methods

If this is accepted, we can do similar changes for other components.
### Testing Instructions
Code review

### CODE REVIEW

**Comment by PhilETaylor** [comment]
I have tested this item :white_check_mark: successfully on 76af2669097898412440fef4cf6b55e3bc93cb31<br /><br />my type of PR - love it. <hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/34570">issues.joomla.org/tracker/joomla-cms/34570</a>.</sub>

**Comment by PhilETaylor** [comment]
can we kick drone again to see what its complaining about?

**Comment by chmst** [comment]
@joomdonation could you please resolve the conflict?

**Comment by HLeithner** [comment]
This pull request has automatically rebased to 4.2-dev.

**Comment by drmenzelit** [comment]
@joomdonation can you please check your PRs, rebase to 4.3 and resolve conflicts? Thanks

**Comment by joomdonation** [comment]
Closing because the PR looks much more complicated than how it was due to conflict.

**Pull request closed without merging**
