### PR TITLE
[4.0] Html5 does not have a closing tag on br

### PR DESCRIPTION
**Pull request by brianteeman**
Sure I did this before but this PR removes the use of a closing slash on a br tag as this is not correct for html5

### CODE REVIEW

**Comment by ghost** [comment]
I have tested this item :white_check_mark: successfully on b0f30f9f7999f3e31bb05fefadc6be6cc60100e9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19228">issues.joomla.org/tracker/joomla-cms/19228</a>.</sub>

**Comment by anuragteapot** [comment]
If We are using <code>xhtml</code> systems that generate HTML based on XML generators. <code>XHTML</code> Elements Must Always Be Closed.
So, use of  closing tag on br is more fine to use because it support both <code>html5</code> and <code>xhtml</code> 
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19228">issues.joomla.org/tracker/joomla-cms/19228</a>.</sub>

**Comment by brianteeman** [comment]
Joomla 4 is html5 not XHTML

**Comment by anuragteapot** [comment]
Ok done!
<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19228">issues.joomla.org/tracker/joomla-cms/19228</a>.</sub>

**Comment by anuragteapot** [comment]
I have tested this item :white_check_mark: successfully on b0f30f9f7999f3e31bb05fefadc6be6cc60100e9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/19228">issues.joomla.org/tracker/joomla-cms/19228</a>.</sub>

**Comment by ghost** [comment]
Ready to Commit after two successful tests.

**Comment by brianteeman** [comment]
Thanks

**Pull request merged**
