### PR TITLE
Updated installation language files

### PR DESCRIPTION
**Pull request by Bakual**
Merge by review once Travis passed.

### CODE REVIEW

**Comment by ghost** [comment]
Travis is passed.

**Comment by brianteeman** [comment]
I see that we are still accepting translations that are translating the name of the installation folder  :(

Can we please not merge these obviously incorrect translations

**Comment by Bakual** [comment]
I'm not going to play "translation police".

**Comment by brianteeman** [comment]
This is crazy - we have an obvious mistake in the translation - we should not be merging anything that is incorrect

**Comment by Bakual** [comment]
The question is who is going to enforce that? I refuse to do that. I do check the technical correctness of the files to a degree, but not the content of the translation. That one is the responsibility of the translator.

Imho, the users of those languages should open a complain/issue with their respective translation teams. If they don't care, I will not care as well.

**Comment by brianteeman** [comment]
I guess it is time to take this seriously then and if you wont then we need someone who will ;(

**Comment by brianteeman** [comment]
I apologise for caring

**Comment by syntaxerror** [comment]
It's the same "mistake" in the English files, using uppercase letters etc ...

If that "logic" of you @brianteeman should make any sense, it would need to be changed also in English. Because it's actually telling **the exact same thing** in English as it would in any other language when it's translated, for all those strings.

Like here it's also uppercase:
`INSTL_COMPLETE_FOLDER_REMOVED="Installation folder removed."`

To make your reasoning make any sense, it would need to be changed into something like:
`INSTL_COMPLETE_FOLDER_REMOVED="The "installation" folder was removed."`

_Else there isn't anything more to waste time on, and pollute every language PR with, like a child trying to get his/her will this way ... Agree or disagree ..._

**Comment by mbabker** [comment]
@syntaxerror It's very obvious you have a dislike for Brian, there is no need to comment on every pull request arguing with him if you aren't going to add anything productive to the conversation.

**Comment by syntaxerror** [comment]
Oh, it seems like it's Brian having to post and post on every PR ... And I added something productive here, for those who care about others opinions.

**Comment by mbabker** [comment]
You were fine until you started with the personal shots at the end.  Leave those out of your posts if you really feel compelled to reply.

And you may look at it like someone crying, but fact of the matter is Brian is one of the few contributors who is a native English (British type) speaker, so I would hope he is doing a level of QA checks and "being childish" for the sake of ensuring things are consistent and grammatically correct, the same way others do levels of QA checks for things like code style or efficient (or even correct) PHP/JavaScript code.

**Comment by syntaxerror** [comment]
So then he's allowed to do as he like. Treat people, translators and others like s h i t - so they don't care to contribute. Well ... that says it all ...

**Comment by mbabker** [comment]
No, he is not free to do as he likes.  And I fail to see the issue with him pointing out that the translation teams are not following instructions and providing potentially incorrect translations.  If that's really seen as whining, then realistically any level of QA is whining.

**Comment by syntaxerror** [comment]
Still he does in PR after PR, forums, Twitter etc. Using a level of language others are not allowed to.

And yes, he's a native British English speaker, not a native in other languages. So it's at it best only potential mistakes, assumed mistakes. But still it's being nagged about in PR after PR, without being a good example fixing the real issues in English instead.

Pointing out is one thing, nagging is another.

**Comment by rdeutz** [comment]
If there is a problem make a PR or open an issue, enough said here

**Pull request merged**
