### PR TITLE
[5.0] Cropper fix

### PR DESCRIPTION
**Pull request by Fedik**
Pull Request for Issue # .

### Summary of Changes

The PR #41034 mixed a bit with the module names, and now the crop does not work.
@dgrammatiko Dimitris your original naming was good.

### Testing Instructions
Apply patch, run `npm install`
Check image crop feature

### Actual result BEFORE applying this Pull Request
Broken

### Expected result AFTER applying this Pull Request
Works

### Link to documentations
Please select:
- [x] No documentation changes for docs.joomla.org needed
- [x] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by richard67** [comment]
I have tested this item :white_check_mark: successfully on 6523300cb17869f516a5f323277b2a38631b61f0<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41071">issues.joomla.org/tracker/joomla-cms/41071</a>.</sub>

**Comment by dgrammatiko** [comment]
I have tested this item :white_check_mark: successfully on afa403536d5b8932840b884f4ff9e681045d4a15<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41071">issues.joomla.org/tracker/joomla-cms/41071</a>.</sub>

**Comment by richard67** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/41071">issues.joomla.org/tracker/joomla-cms/41071</a>.</sub>

**Comment by HLeithner** [comment]
thanks

**Pull request merged**
