### PR TITLE
All e-mail can be in UTF-8

### PR DESCRIPTION
**Pull request by rigin**
not only the domain name, the same address of the user can be in UTF-8 
Continuing Pull # 13742

Pull Request for Issue # .

### CODE REVIEW

**Comment by franz-wohlkoenig** [comment]
same test instructions like #13742?

**Comment by richard67** [comment]
As far as I understand, #13742 and this one here have to be tested together, I guess instructions will be as in #13742 . I wish I had more time to advice rigin better. Maybe @infograf768 can have a look on this here and  #13742 and advice and check? As far as I remember he has worked on email cloaking stuff in past.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13770">issues.joomla.org/tracker/joomla-cms/13770</a>.</sub>

**Comment by rigin** [comment]
Yes, it is necessary to integrate and test of 13742

**Comment by franz-wohlkoenig** [comment]
I have tested this item :red_circle: unsuccessfully on 5875c00350258c86b2163f58b4ed3e051b2b3d5f<br /><br />Email-Field `Вадим@Ригин.рф` stay after PR red an user isn't saved as without PR.<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/13770">issues.joomla.org/tracker/joomla-cms/13770</a>.</sub>

**Comment by rigin** [comment]
I will carefully consider, in what there can be a problem.
I close these Pulls?

**Comment by infograf768** [comment]
This is a 3rd party library. Do not touch at it!
https://github.com/bestiejs/punycode.js

Please close indeed.

**Comment by franz-wohlkoenig** [comment]
should this PR closed?

**Comment by richard67** [comment]
According to Jean Marie (infograf768), this PR here and the other one #13742 should be closed.

**Comment by franz-wohlkoenig** [comment]
thanks @richard67

**Comment by zero-24** [comment]
@rigin please move this request against the upstream repo: https://github.com/bestiejs/punycode.js

**Pull request closed without merging**
