### PR TITLE
[5.3] Deprecate unused language strings mod_stats_admin

### PR DESCRIPTION
**Pull request by brianteeman**
This PR deprecates various language strings that are not used in the module

code review.

Thanks to @leeroy1821

Pull Request for Issue #44252 

### Testing Instructions
code review

### Link to documentations
Please select:
- [ ] Documentation link for docs.joomla.org: <link>
- [ ] No documentation changes for docs.joomla.org needed

- [ ] Pull Request link for manual.joomla.org: <link>
- [ ] No documentation changes for manual.joomla.org needed

### CODE REVIEW

**Comment by Quy** [comment]
I have tested this item :white_check_mark: successfully on 86a450e171f12cccfbe2b43f9ca6020c14081ff9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44271">issues.joomla.org/tracker/joomla-cms/44271</a>.</sub>

**Comment by alikon** [comment]
I have tested this item :white_check_mark: successfully on 86a450e171f12cccfbe2b43f9ca6020c14081ff9<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44271">issues.joomla.org/tracker/joomla-cms/44271</a>.</sub>

**Comment by alikon** [comment]
RTC<hr /><sub>This comment was created with the <a href="https://github.com/joomla/jissues">J!Tracker Application</a> at <a href="https://issues.joomla.org/tracker/joomla-cms/44271">issues.joomla.org/tracker/joomla-cms/44271</a>.</sub>

**Comment by brianteeman** [comment]
thanks

**Pull request merged**
