### PR TITLE
improved modal layout

### PR DESCRIPTION
**Pull request by GABBAR1947**
Pull Request for Issue  #9822

### CODE REVIEW

**Comment by brianteeman** [comment]
Please do NOT edit the css file directly.

You must edit the less file and then run the generatess.php to update the css

**Comment by andrepereiradasilva** [comment]
Just checking the code i think this will add a `padding-top: 12px;` to ALL the form with that uses the `.form-horizontal .control-group` css class...

**Comment by brianteeman** [comment]
Yes this is not the correct solution at all

On 15 April 2016 at 12:49, andrepereiradasilva <notifications@github.com>
wrote:

> Just checking the code i think this will add a padding-top: 12px; to ALL
> the form with that uses the .form-horizontal .control-group css class...
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/joomla/joomla-cms/pull/9930#issuecomment-210435407>
>



-- 
Brian Teeman
Co-founder Joomla! and OpenSourceMatters Inc.
http://brian.teeman.net/

**Comment by GABBAR1947** [comment]
@brianteeman working on it !

**Comment by GABBAR1947** [comment]
So ,should I create a new class for this particular form so that the other forms don't get affected ?

**Comment by andrepereiradasilva** [comment]
i think the problem you're referring only applies to tinymce modals.
And IMHO this is not the way to solve that problem because it would have side effects.

IMHO you should close this and take more time to think of a way of solving the problem without side effects.

**Comment by andrepereiradasilva** [comment]
@rdeutz why did you merge this? I has no text and it will have side effects.

**Comment by andrepereiradasilva** [comment]
ok i see this was not merged although github thinks so because this one https://github.com/joomla/joomla-cms/pull/9946 has merged .

**Comment by rdeutz** [comment]
Strange, isn't it? Bug in Github?

**Comment by zero-24** [comment]
It is because both PRs include this commit: https://github.com/GABBAR1947/joomla-cms/commit/890f0481f4a877fa05e37bb90d9f2ef5b1f9fcd0

And @rdeutz merged the other PR.

**Pull request merged**
